SCRIPTS = [
("cf_fix_party_size_recursive", #I am not exactly happy about the recursive
                      [
                        (store_script_param, ":cur_party", 1),
                        (store_script_param, ":mode", 2),
                        (assign, ":reg0_backup", reg0),
                        (party_get_num_companions, ":num", ":cur_party"),
                        (try_begin),
                          (gt, ":num", reg0),
                          (neq, 0, reg0),
                          (store_sub, ":delta", ":num", reg0),
                          (party_get_num_companion_stacks, ":num_stacks", ":cur_party"),
                          (assign, ":to_del_stack", 0),
                          (assign, ":checker", 100),
                          (try_for_range, ":index", 0, ":num_stacks"),
                            (party_stack_get_troop_id, ":cur_troop", ":cur_party", ":index"),
                            (store_character_level, ":cur_level", ":cur_troop"),
                            (le, ":cur_level", ":checker"),
                            (assign, ":checker", ":cur_level"),
                            (assign, ":to_del_stack", ":index"),
                          (try_end),
                          (party_stack_get_size, ":num_troop", ":cur_party", ":to_del_stack"),
                          (party_stack_get_troop_id, ":cur_troop", ":cur_party", ":to_del_stack"),
                          (try_begin),
                            (le, ":num_troop", ":delta"),
                            (assign, ":delta", ":num_troop"),
                          (try_end),
                          (party_remove_members, ":cur_party", ":cur_troop", ":delta"),
                          (try_begin),
                            (eq, ":mode", 1),
                            (party_add_members, "p_main_party", ":cur_troop", ":delta"),
                          (try_end),
                          (assign, reg0, ":reg0_backup"),
                          (call_script, "script_cf_fix_party_size_recursive", ":cur_party", ":mode"),
                        (try_end),
                      ]
                    ),
]
