SCRIPTS = [
("create_village_farmer_party",
      [(store_script_param, ":village_no", 1),
        (party_get_slot, ":town_no", ":village_no", slot_village_market_town),

        (store_faction_of_party, ":party_faction", ":town_no"),
        (set_spawn_radius, 0),
        (spawn_around_party, ":village_no", "pt_village_farmers"),
        (assign, ":new_party", reg0),

        (party_get_slot, ":population", ":village_no", slot_center_sod_local_population),
        (party_get_slot, ":health", ":village_no", slot_center_sod_local_health),
        (party_get_slot, ":prosperity", ":village_no", slot_town_prosperity),
        (call_script, "script_sod_get_village_output_profile", ":village_no"),
        (assign, ":village_workforce", reg0),
        (assign, ":village_labor_capacity", reg5),
        (assign, ":village_fragility", reg6),
        (assign, ":village_reliability", reg8),
        (store_sub, ":population_surplus", ":population", village_pop_min),
        (val_max, ":population_surplus", 0),
        (assign, ":farmer_capacity", ":population_surplus"),
        (val_min, ":farmer_capacity", ":village_workforce"),
        (store_mul, ":reliable_capacity", ":farmer_capacity", ":village_reliability"),
        (val_div, ":reliable_capacity", 100),
        (assign, ":farmer_capacity", ":reliable_capacity"),
        (try_begin),
          (gt, ":village_labor_capacity", 0),
          (store_mul, ":labor_cap", ":village_labor_capacity", 2),
          (val_min, ":farmer_capacity", ":labor_cap"),
        (try_end),
        (try_begin),
          (lt, ":health", 30),
          (val_div, ":farmer_capacity", 2),
        (else_try),
          (lt, ":prosperity", 30),
          (val_mul, ":farmer_capacity", 2),
          (val_div, ":farmer_capacity", 3),
        (try_end),
        (try_begin),
          (gt, ":village_fragility", 70),
          (val_mul, ":farmer_capacity", 60),
          (val_div, ":farmer_capacity", 100),
        (try_end),
        (try_begin),
          (le, ":farmer_capacity", 0),
          (assign, ":farmer_count", 0),
        (else_try),
          (store_party_size, ":farmer_count", ":new_party"),
          (gt, ":farmer_count", ":farmer_capacity"),
          (store_sub, ":farmers_to_remove", ":farmer_count", ":farmer_capacity"),
          (party_get_num_companion_stacks, ":num_stacks", ":new_party"),
          (try_for_range_backwards, ":stack_no", 0, ":num_stacks"),
            (gt, ":farmers_to_remove", 0),
            (party_stack_get_troop_id, ":stack_troop", ":new_party", ":stack_no"),
            (party_stack_get_size, ":stack_size", ":new_party", ":stack_no"),
            (assign, ":remove_count", ":stack_size"),
            (val_min, ":remove_count", ":farmers_to_remove"),
            (party_remove_members, ":new_party", ":stack_troop", ":remove_count"),
            (val_sub, ":farmers_to_remove", ":remove_count"),
          (try_end),
          (store_party_size, ":farmer_count", ":new_party"),
        (try_end),
        (val_min, ":farmer_count", ":population_surplus"),
        (val_sub, ":population", ":farmer_count"),
        (val_max, ":population", village_pop_min),
        (party_set_slot, ":village_no", slot_center_sod_local_population, ":population"),

        (try_begin),
          (gt, ":farmer_count", 0),
          (party_set_faction, ":new_party", ":party_faction"),
          (party_set_slot, ":new_party", slot_party_home_center, ":village_no"),
          (party_set_slot, ":new_party", slot_party_type, spt_village_farmer),
          (party_set_slot, ":new_party", slot_party_ai_state, spai_trading_with_town),
          (party_set_slot, ":new_party", slot_party_ai_object, ":town_no"),
          (party_set_ai_behavior, ":new_party", ai_bhvr_travel_to_party),
          (party_set_ai_object, ":new_party", ":town_no"),
          (party_set_flags, ":new_party", pf_default_behavior, 0),
          (store_sub, ":item_to_price_slot", slot_town_trade_good_prices_begin, trade_goods_begin),
          (try_for_range, ":cur_goods", trade_goods_begin, trade_goods_end),
            (store_add, ":cur_good_price_slot", ":cur_goods", ":item_to_price_slot"),
            (party_get_slot, ":cur_village_price", ":village_no", ":cur_good_price_slot"),
            (party_set_slot, ":new_party", ":cur_good_price_slot", ":cur_village_price"),
          (try_end),
        (else_try),
          (remove_party, ":new_party"),
          (assign, ":new_party", -1),
        (try_end),
        (assign, reg0, ":new_party"),
    ]),
]
