SCRIPTS = [
("event_player_defeated_enemy_party",
        [
          (store_script_param_1, ":defeated_party"),
          (try_begin),
            (gt, ":defeated_party", 0),
            (party_is_active, ":defeated_party"),
            (assign, "$g_enemy_party", ":defeated_party"),
          (assign, "$g_sod_last_defeated_party", ":defeated_party"),
          (call_script, "script_sod_runtime_trace_event", 1, ":defeated_party", -1),
          (try_begin),
            (party_slot_eq, "$g_enemy_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
            (call_script, "script_sod_tax_courier_award_payload_to_player", "$g_enemy_party", 2),
          (try_end),
          (try_begin),
            (party_slot_eq, "$g_enemy_party", slot_party_type, spt_prisoner_train),
            (call_script, "script_sod_prisoner_train_destroyed", "$g_enemy_party", "fac_player_supporters_faction"),
            (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_free_captives, 2),
          (try_end),
          (try_begin),
            (party_slot_eq, "$g_enemy_party", slot_party_sod_support_type, sod_support_type_castle_patrol),
            (store_faction_of_party, ":enemy_faction", "$g_enemy_party"),
            (call_script, "script_sod_castle_patrol_destroyed", "$g_enemy_party"),
            (call_script, "script_sod_diplomacy_record_event", ":enemy_faction", sod_diplomacy_memory_border_raid, 1),
          (try_end),
          (try_begin),
            (party_slot_eq, "$g_enemy_party", slot_party_type, spt_kingdom_caravan),
            (store_faction_of_party, ":enemy_faction", "$g_enemy_party"),
            (call_script, "script_sod_diplomacy_record_event", ":enemy_faction", sod_diplomacy_memory_caravan_attack, 1),
          (try_end),
          (try_begin),
            (party_get_slot, ":enemy_party_type", "$g_enemy_party", slot_party_type),
            (this_or_next|eq, ":enemy_party_type", spt_ai_mercenaries),
            (this_or_next|eq, ":enemy_party_type", spt_player_mercenaries),
            (eq, ":enemy_party_type", spt_mercenary_lord_party),
            (call_script, "script_sod_merc_lord_note_battle_outcome", "$g_enemy_party", -1),
          (try_end),
          (try_begin),
            (party_get_template_id, ":enemy_template", "$g_enemy_party"),
            (try_begin),
              (eq, ":enemy_template", "pt_bandits"),
              (party_slot_ge, "$g_enemy_party", slot_party_sod_looter_raid_state, sod_looter_raid_state_moving_to_target),
              (party_get_slot, ":looter_raid_target", "$g_enemy_party", slot_party_sod_looter_raid_target),
              (party_get_slot, ":raid_state", "$g_enemy_party", slot_party_sod_looter_raid_state),
              (party_get_slot, ":assault_resolved", "$g_enemy_party", slot_party_sod_looter_raid_assault_resolved),
              (assign, ":reward_allowed", 0),
              (try_begin),
                (is_between, ":looter_raid_target", villages_begin, villages_end),
                (store_current_day, ":current_day"),
                (party_get_slot, ":reward_cooldown_until", ":looter_raid_target", slot_center_sod_looter_player_reward_cooldown_until),
                (le, ":reward_cooldown_until", ":current_day"),
                (assign, ":reward_allowed", 1),
              (try_end),
              (call_script, "script_sod_looter_resolve_village_raid", "$g_enemy_party", 2),
              (try_begin),
                (eq, ":reward_allowed", 1),
                (is_between, ":looter_raid_target", villages_begin, villages_end),
                (str_store_party_name_link, s1, ":looter_raid_target"),
                (try_begin),
                  (lt, ":raid_state", sod_looter_raid_state_assaulting),
                  (display_message, "@You broke the looters before they reached {s1}. The village will remember the road was saved before blood reached the lanes.", 0x99CCFF),
                (else_try),
                  (eq, ":assault_resolved", 1),
                  (lt, ":raid_state", sod_looter_raid_state_plundering),
                  (display_message, "@You drove off the looters after the militia of {s1} had already paid for the first assault.", 0x99CCFF),
                (else_try),
                  (ge, ":raid_state", sod_looter_raid_state_plundering),
                  (display_message, "@You rescued {s1} from looters already loose among the outer farms.", 0x99CCFF),
                (else_try),
                  (display_message, "@You have broken the looter raid threatening {s1}. The villagers will remember it.", 0x99CCFF),
                (try_end),
                (call_script, "script_change_player_relation_with_center", ":looter_raid_target", 1),
                (call_script, "script_change_troop_renown", "trp_player", 1),
                (call_script, "script_change_player_honor", 1),
                (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_help_village, 2),
                (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 2),
                (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_food_security, 1),
                (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_build_security, 1),
                (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_orderly_profit, 1),
                (try_begin),
                  (ge, ":raid_state", sod_looter_raid_state_plundering),
                  (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_help_village, 1),
                  (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_food_security, 1),
                (else_try),
                  (lt, ":raid_state", sod_looter_raid_state_assaulting),
                  (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 1),
                (try_end),
                (try_begin),
                  (call_script, "script_cf_sod_companion_in_main_party", "trp_npc3"),
                  (display_message, "@Ymira watches the village road until the last runner is safe. 'That is the sort of victory people can live inside.'", 0x99CCFF),
                (else_try),
                  (call_script, "script_cf_sod_companion_in_main_party", "trp_npc10"),
                  (display_message, "@Bunduk counts the scattered looters by their tracks. 'Good. Roads stay safe when trouble learns the price early.'", 0x99CCFF),
                (else_try),
                  (call_script, "script_cf_sod_companion_in_main_party", "trp_npc2"),
                  (display_message, "@Marnid looks toward the grain carts. 'A road saved today is a market saved tomorrow.'", 0x99CCFF),
                (else_try),
                  (call_script, "script_cf_sod_companion_in_main_party", "trp_npc7"),
                  (display_message, "@Deshavi looks toward the tree line. 'Raiders come back to soft places. This one is harder now.'", 0x99CCFF),
                (else_try),
                  (call_script, "script_cf_sod_companion_in_main_party", "trp_npc1"),
                  (display_message, "@Borcha spits into the dust. 'Good. Bandits should learn villages have teeth.'", 0x99CCFF),
                (try_end),
                (store_current_day, ":current_day"),
                (store_add, ":reward_cooldown_until", ":current_day", sod_looter_raid_player_reward_cooldown_days),
                (party_set_slot, ":looter_raid_target", slot_center_sod_looter_player_reward_cooldown_until, ":reward_cooldown_until"),
              (try_end),
            (else_try),
              (eq, ":enemy_template", "pt_black_khergit_raiders"),
              (call_script, "script_sod_black_khergits_apply_player_action", sod_black_khergit_action_defeat_raiders, 8),
              (try_begin),
                (call_script, "script_cf_sod_companion_in_main_party", "trp_npc1"),
                (display_message, "@Borcha marks the raider trail with a boot. 'One less bad road pretending to be empty.'", 0x99CCFF),
              (try_end),
            (else_try),
              (eq, ":enemy_template", "pt_black_khergit_night_guard"),
              (call_script, "script_sod_black_khergits_apply_player_action", sod_black_khergit_action_defeat_guards, 10),
            (else_try),
              (eq, ":enemy_template", "pt_black_khergit_horde_camp"),
              (call_script, "script_sod_black_khergits_apply_player_action", sod_black_khergit_action_attack_camp, 40),
              (try_begin),
                (call_script, "script_cf_sod_companion_in_main_party", "trp_npc1"),
                (display_message, "@Borcha watches the horde camp break apart. 'There. Roads breathe better when the wolves lose their den.'", 0x99CCFF),
              (try_end),
            (else_try),
              (this_or_next|eq, ":enemy_template", "pt_black_army_patrol"),
              (eq, ":enemy_template", "pt_black_army_contract_column"),
              (call_script, "script_sod_black_army_apply_player_action", sod_black_army_action_attack_patrol, 25),
            (else_try),
              (this_or_next|eq, ":enemy_template", "pt_conquistador_procurement_column"),
              (eq, ":enemy_template", "pt_conquistador_expeditionary_camp"),
              (call_script, "script_sod_conquistador_apply_player_action", sod_conquistador_action_take_stores, 50),
            (else_try),
              (this_or_next|eq, ":enemy_template", "pt_serpent_host_route_screen"),
              (eq, ":enemy_template", "pt_serpent_host_courier_lance"),
              (call_script, "script_sod_serpent_host_apply_player_action", sod_serpent_action_attack_screen, 20),
            (else_try),
              (eq, ":enemy_template", "pt_slavers_caravan"),
              (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_hostile, 12),
              (call_script, "script_sod_companion_apply_player_action", sod_companion_action_free_captives, 3),
            (else_try),
              (this_or_next|eq, ":enemy_template", "pt_elephant_guard_sanctuary_patrol"),
              (eq, ":enemy_template", "pt_elephant_guard_relic_procession"),
              (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", -3),
              (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_abuse_village, 1),
              (display_message, "@Word travels that you broke an Elephant Guard road-vow party. Their regard for you falls.", 0xCC3333),
            (else_try),
              (this_or_next|eq, ":enemy_template", "pt_jotnar_hearth_guard"),
              (eq, ":enemy_template", "pt_jotnar_wintering_camp"),
              (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", -3),
              (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_abuse_village, 1),
              (display_message, "@Word travels that you struck a Jotnar hearth-road party. Their fires will be colder to you.", 0xCC3333),
            (else_try),
              (this_or_next|eq, ":enemy_template", "pt_boar_clan_fighters"),
              (eq, ":enemy_template", "pt_boar_clan_fighters_desert"),
              (call_script, "script_sod_boar_clan_apply_player_action", sod_boar_action_defeat_band, 8),
            (try_end),
          (try_end),
          (try_begin),
            (check_quest_active, "qst_raid_caravan_to_start_war"),
            (neg|check_quest_concluded, "qst_raid_caravan_to_start_war"),
            (party_slot_eq, "$g_enemy_party", slot_party_type, spt_kingdom_caravan),
            (store_faction_of_party, ":enemy_faction", "$g_enemy_party"),
            (quest_slot_eq, "qst_raid_caravan_to_start_war", slot_quest_target_faction, ":enemy_faction"),
            (quest_get_slot, ":cur_state", "qst_raid_caravan_to_start_war", slot_quest_current_state),
            (quest_get_slot, ":quest_target_amount", "qst_raid_caravan_to_start_war", slot_quest_target_amount),
            (val_add, ":cur_state", 1),
            (quest_set_slot, "qst_raid_caravan_to_start_war", slot_quest_current_state, ":cur_state"),
            (try_begin),
              (ge, ":cur_state", ":quest_target_amount"),
              (quest_get_slot, ":quest_target_faction", "qst_raid_caravan_to_start_war", slot_quest_target_faction),
              (quest_get_slot, ":quest_giver_troop", "qst_raid_caravan_to_start_war", slot_quest_giver_troop),
              (store_troop_faction, ":quest_giver_faction", ":quest_giver_troop"),
              (call_script, "script_diplomacy_start_war_between_kingdoms", ":quest_target_faction", ":quest_giver_faction", 1),
              (call_script, "script_succeed_quest", "qst_raid_caravan_to_start_war"),
            (try_end),
		  (else_try),
			(check_quest_active, "qst_serpent_host_raid_caravan"),
            (neg|check_quest_concluded, "qst_serpent_host_raid_caravan"),
            (party_slot_eq, "$g_enemy_party", slot_party_type, spt_kingdom_caravan),
            (store_faction_of_party, ":enemy_faction", "$g_enemy_party"),
            (quest_slot_eq, "qst_serpent_host_raid_caravan", slot_quest_target_faction, ":enemy_faction"),
            (call_script, "script_succeed_quest", "qst_serpent_host_raid_caravan"),
		  (else_try),
			(check_quest_active, "qst_jotnar_clan_free_clansmen"),
            (neg|check_quest_concluded, "qst_jotnar_clan_free_clansmen"),
            (quest_slot_eq, "qst_jotnar_clan_free_clansmen", slot_quest_target_party, "$g_enemy_party"),
			(set_spawn_radius, 1),
			(spawn_around_party, "p_main_party", "pt_jotnar_clansmen"),
            (assign, ":freed_clansmen_party", reg0),
            (try_begin),
              (gt, ":freed_clansmen_party", 0),
              (party_is_active, ":freed_clansmen_party"),
              (quest_set_slot, "qst_jotnar_clan_free_clansmen", slot_quest_target_party, ":freed_clansmen_party"),
              (party_set_ai_behavior, ":freed_clansmen_party", ai_bhvr_hold),
              (party_set_ai_object, ":freed_clansmen_party", "p_main_party"),
              (party_set_flags, ":freed_clansmen_party", pf_default_behavior, 0),
              (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_free_captives, 2),
              (display_message, "@The freed Jotnar clansmen gather near your camp. Speak with them before taking the road home.", 0x99CCFF),
            (else_try),
              (call_script, "script_succeed_quest", "qst_jotnar_clan_free_clansmen"),
              (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_free_captives, 1),
              (display_message, "@The freed Jotnar clansmen scatter from the broken slaver camp and make for home. The guildmaster will hear of it.", 0x99CCFF),
            (try_end),
          (try_end),
          (else_try),
            (assign, "$g_enemy_party", -1),
          (try_end),

      ]),
]
