SCRIPTS = [
("event_hero_taken_prisoner_by_player",
        [
          (store_script_param_1, ":troop_no"),
          (try_begin),
            (is_between, ":troop_no", heroes_begin, heroes_end),
            (assign, "$g_sod_last_captured_hero", ":troop_no"),
            (call_script, "script_sod_runtime_trace_event", 2, "p_main_party", ":troop_no"),
            (call_script, "script_sod_house_note_lord_captured_by_player", ":troop_no"),
            (call_script, "script_sod_quest_battle_note_target_captured", ":troop_no"),
            (try_begin),
            (check_quest_active, "qst_persuade_lords_to_make_peace"),
            (try_begin),
              (quest_slot_eq, "qst_persuade_lords_to_make_peace", slot_quest_target_troop, ":troop_no"),
              (val_mul, ":troop_no", -1),
              (quest_set_slot, "qst_persuade_lords_to_make_peace", slot_quest_target_troop, ":troop_no"),
              (val_mul, ":troop_no", -1),
            (else_try),
              (quest_slot_eq, "qst_persuade_lords_to_make_peace", slot_quest_object_troop, ":troop_no"),
              (val_mul, ":troop_no", -1),
              (quest_set_slot, "qst_persuade_lords_to_make_peace", slot_quest_object_troop, ":troop_no"),
              (val_mul, ":troop_no", -1),
            (try_end),
            (neg|check_quest_concluded, "qst_persuade_lords_to_make_peace"),
            (neg|quest_slot_ge, "qst_persuade_lords_to_make_peace", slot_quest_target_troop, 0),
            (neg|quest_slot_ge, "qst_persuade_lords_to_make_peace", slot_quest_object_troop, 0),
            (call_script, "script_succeed_quest", "qst_persuade_lords_to_make_peace"),
            (try_end),
            (call_script, "script_update_troop_location_notes", ":troop_no", 0),
          (try_end),
      ]),
]
