SCRIPTS = [
("get_player_party_morale_values",
    [
      (assign, reg0, 50),
      (assign, "$g_player_party_morale_modifier_party_size", 0),
      (assign, "$g_player_party_morale_modifier_leadership", 0),
      (assign, "$g_player_party_morale_modifier_food", 0),
      (assign, "$g_player_party_morale_modifier_no_food", 0),
      (assign, "$g_player_party_morale_modifier_rations", 0),
      (assign, "$g_player_party_morale_modifier_debt", 0),
      (assign, "$g_player_party_morale_modifier_company_accounts", 0),
      (assign, "$g_player_party_morale_modifier_retinue_cohesion", 0),
      (try_begin),
      (main_party_has_troop, "trp_player"),
      (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
      (assign, ":num_men", 0),
      (try_for_range, ":i_stack", 1, ":num_stacks"),
        (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":i_stack"),
        (is_between, ":stack_troop", 0, "trp_last_troop"),
        (try_begin),
          (troop_is_hero, ":stack_troop"),
          #MORDACHAI - reduce the negative morale of a hero
          (val_add, ":num_men", 1),
        (else_try),
          (party_stack_get_size, ":stack_size", "p_main_party", ":i_stack"),
          (val_add, ":num_men", ":stack_size"),
        (try_end),
      (try_end),

      #MORDACHAI - reduce the effect of party size on morale to 2/3
      (val_mul, ":num_men", 2),
      (val_div, ":num_men", 3),

      (assign, "$g_player_party_morale_modifier_party_size", ":num_men"),

      (store_skill_level, ":player_leadership", "skl_leadership", "trp_player"),
      #MORDACHAI - increase morale boost to leadership x 10 (was x 7)
      (store_mul, "$g_player_party_morale_modifier_leadership", ":player_leadership", 10),
      (assign, ":new_morale", "$g_player_party_morale_modifier_leadership"),
      (val_sub, ":new_morale", "$g_player_party_morale_modifier_party_size"),
      (val_add, ":new_morale", 50),

      (assign, "$g_player_party_morale_modifier_food", 0),
      (try_for_range, ":cur_edible", food_begin, food_end),
        (call_script, "script_cf_player_has_item_without_modifier", ":cur_edible", imod_rotten),
        (item_get_slot, ":food_bonus", ":cur_edible", slot_item_food_bonus),
        (val_add, "$g_player_party_morale_modifier_food", ":food_bonus"),
      (try_end),
      (val_add, ":new_morale", "$g_player_party_morale_modifier_food"),

      (try_begin),
        (eq, "$g_player_party_morale_modifier_food", 0),
        (assign, "$g_player_party_morale_modifier_no_food", 30),
        (val_sub, ":new_morale", "$g_player_party_morale_modifier_no_food"),
      (else_try),
        (assign, "$g_player_party_morale_modifier_no_food", 0),
      (try_end),

      (assign, "$g_player_party_morale_modifier_rations", 0),
      (try_begin),
        (eq, "$g_sod_company_ration_policy", sod_company_ration_policy_thin),
        (assign, "$g_player_party_morale_modifier_rations", -3),
      (else_try),
        (eq, "$g_sod_company_ration_policy", sod_company_ration_policy_generous),
        (gt, "$g_player_party_morale_modifier_food", 0),
        (assign, "$g_player_party_morale_modifier_rations", 4),
      (else_try),
        (eq, "$g_sod_company_ration_policy", sod_company_ration_policy_officer_austerity),
        (assign, "$g_player_party_morale_modifier_rations", 1),
      (try_end),
      (val_add, ":new_morale", "$g_player_party_morale_modifier_rations"),

      (assign, "$g_player_party_morale_modifier_debt", 0),
      (try_begin),
        (val_max, "$g_player_debt_to_party_members", 0),
        (gt, "$g_player_debt_to_party_members", 0),
        (call_script, "script_calculate_player_faction_wage"),
        (assign, ":total_wages", reg0),
        (gt, ":total_wages", 0),
        (store_mul, "$g_player_party_morale_modifier_debt", "$g_player_debt_to_party_members", 10),
        (val_div, "$g_player_party_morale_modifier_debt", ":total_wages"),
        (val_clamp, "$g_player_party_morale_modifier_debt", 1, 31),
        (val_sub, ":new_morale", "$g_player_party_morale_modifier_debt"),
      (try_end),

      (assign, "$g_player_party_morale_modifier_company_accounts", 0),
      (try_begin),
        (ge, "$g_sod_company_camp_strain", 40),
        (assign, "$g_player_party_morale_modifier_company_accounts", "$g_sod_company_camp_strain"),
        (val_div, "$g_player_party_morale_modifier_company_accounts", 20),
        (val_clamp, "$g_player_party_morale_modifier_company_accounts", 1, 6),
        (val_sub, ":new_morale", "$g_player_party_morale_modifier_company_accounts"),
      (try_end),

      (assign, "$g_player_party_morale_modifier_retinue_cohesion", 0),
      (call_script, "script_sod_companion_retinue_get_account_totals_to_regs"),
      (try_begin),
        (gt, reg(76), 0),
        (lt, reg(75), 45),
        (store_sub, "$g_player_party_morale_modifier_retinue_cohesion", 45, reg(75)),
        (val_div, "$g_player_party_morale_modifier_retinue_cohesion", 8),
        (val_clamp, "$g_player_party_morale_modifier_retinue_cohesion", 1, 6),
        (val_sub, ":new_morale", "$g_player_party_morale_modifier_retinue_cohesion"),
      (try_end),

      (val_clamp, ":new_morale", 0, 101),
      (assign, reg0, ":new_morale"),
      (try_end),
  ]),
]
