SCRIPTS = [
("get_max_skill_of_player_party",
      [(store_script_param, ":skill_no", 1),
        (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
        (store_skill_level, ":max_skill", ":skill_no", "trp_player"),
        (assign, ":skill_owner", "trp_player"),
        (try_for_range, ":i_stack", 0, ":num_stacks"),
          (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":i_stack"),
          (troop_is_hero, ":stack_troop"),
          (neg|troop_is_wounded, ":stack_troop"),
          (store_skill_level, ":cur_skill", ":skill_no", ":stack_troop"),
          (gt, ":cur_skill", ":max_skill"),
          (assign, ":max_skill", ":cur_skill"),
          (assign, ":skill_owner", ":stack_troop"),
        (try_end),
        (assign, reg0, ":max_skill"),
        (assign, reg1, ":skill_owner"),
    ]),
]
