SCRIPTS = [
("offer_ransom_amount_to_player_for_prisoners_in_party",
        [(store_script_param, ":party_no", 1),
          (assign, ":result", 0),
          (party_get_num_prisoner_stacks, ":num_stacks", ":party_no"),
          (try_for_range, ":i_stack", 0, ":num_stacks"),
            (eq, ":result", 0),
            (party_prisoner_stack_get_troop_id, ":stack_troop", ":party_no", ":i_stack"),
            (troop_is_hero, ":stack_troop"),
            (this_or_next|troop_slot_eq, ":stack_troop", slot_troop_occupation, slto_kingdom_hero),
            (troop_slot_eq, ":stack_troop", slot_troop_occupation, slto_mercenary_lord),
            (store_troop_faction, ":stack_troop_faction", ":stack_troop"),
            (store_random_in_range, ":random_no", 0, 100),
            (try_begin),
              (faction_slot_eq, ":stack_troop_faction", slot_faction_state, sfs_active),
              (le, ":random_no", 5),
              (neq, "$g_ransom_offer_rejected", 1),
              (assign, ":num_stacks", 0), #break
              (assign, ":result", 1),
              (assign, "$g_ransom_offer_troop", ":stack_troop"),
              (assign, "$g_ransom_offer_party", ":party_no"),
              (jump_to_menu, "mnu_enemy_offer_ransom_for_prisoner"),
            (try_end),
          (try_end),
          (assign, reg0, ":result"),
      ]),
]
