SCRIPTS = [
("party_calculate_loot",
    [
      (store_script_param_1, ":enemy_party"), #Enemy Party_id


      (call_script, "script_calculate_main_party_shares"),
      (assign, ":num_player_party_shares", reg0),
      (val_max, ":num_player_party_shares", 1),
      (assign, ":loot_source_party", "$g_enemy_party"),
      (assign, ":loot_source_valid", 0),
      (try_begin),
        (gt, ":loot_source_party", 0),
        (party_is_active, ":loot_source_party"),
        (assign, ":loot_source_valid", 1),
      (try_end),
      (try_begin),
        (eq, ":loot_source_valid", 0),
        (gt, "$g_encountered_party", 0),
        (party_is_active, "$g_encountered_party"),
        (assign, ":loot_source_party", "$g_encountered_party"),
        (assign, ":loot_source_valid", 1),
      (else_try),
        (eq, ":loot_source_valid", 0),
        (is_between, "$current_town", walled_centers_begin, walled_centers_end),
        (assign, ":loot_source_party", "$current_town"),
        (assign, ":loot_source_valid", 1),
      (else_try),
        (eq, ":loot_source_valid", 0),
        (is_between, "$g_player_besiege_town", walled_centers_begin, walled_centers_end),
        (assign, ":loot_source_party", "$g_player_besiege_town"),
        (assign, ":loot_source_valid", 1),
      (else_try),
        (eq, ":loot_source_valid", 0),
        (gt, ":enemy_party", 0),
        (party_is_active, ":enemy_party"),
        (assign, ":loot_source_party", ":enemy_party"),
        (assign, ":loot_source_valid", 1),
      (try_end),
      (assign, ":is_siege_center", 0),
      (try_begin),
        (eq, ":loot_source_valid", 1),
        (this_or_next|party_slot_eq, ":loot_source_party", slot_party_type, spt_town),
        (party_slot_eq, ":loot_source_party", slot_party_type, spt_castle),
        (assign, ":is_siege_center", 1),
      (else_try),
        (this_or_next|eq, "$g_next_menu", "mnu_castle_taken"),
        (eq, "$g_next_menu", "mnu_castle_taken_by_friends"),
        (this_or_next|is_between, "$g_enemy_party", walled_centers_begin, walled_centers_end),
        (this_or_next|is_between, "$g_encountered_party", walled_centers_begin, walled_centers_end),
        (this_or_next|is_between, "$current_town", walled_centers_begin, walled_centers_end),
        (is_between, "$g_player_besiege_town", walled_centers_begin, walled_centers_end),
        (assign, ":is_siege_center", 1),
      (try_end),
      #      (assign, ":num_ally_shares", reg1),
      #      (store_add, ":num_shares",  ":num_player_party_shares", ":num_ally_shares"),

      #Calculate player loot probability
      #      (assign, ":loot_probability", 100),
      #      (val_mul, ":loot_probability", 10),
      #      (val_div, ":loot_probability", ":num_shares"),

      (try_begin),
        (eq, ":loot_source_valid", 1),
        (try_for_range, ":i_loot", 0, num_party_loot_slots),
          (store_add, ":cur_loot_slot", ":i_loot", slot_party_looted_item_1),
          (party_get_slot, ":item_no", ":loot_source_party", ":cur_loot_slot"),
          (gt, ":item_no", 0),
          (party_set_slot, ":loot_source_party", ":cur_loot_slot", 0),
          (val_sub, ":cur_loot_slot", slot_party_looted_item_1),
          (val_add, ":cur_loot_slot", slot_party_looted_item_1_modifier),
          (party_get_slot, ":item_modifier", ":loot_source_party", ":cur_loot_slot"),
          (troop_add_item, "trp_temp_troop", ":item_no", ":item_modifier"),
        (try_end),
        (party_set_slot, ":loot_source_party", slot_party_next_looted_item_slot, 0),
      (try_end),

      (assign, ":num_looted_items", 0),
      (try_begin),
        (eq, ":loot_source_valid", 1),
        (this_or_next|party_slot_eq, ":loot_source_party", slot_party_type, spt_kingdom_caravan),
        (party_slot_eq, ":loot_source_party", slot_party_type, spt_village_farmer),
        (store_mul, ":plunder_amount", player_loot_share, 30),
        (val_mul, ":plunder_amount", "$g_strength_contribution_of_player"),
        (val_div, ":plunder_amount", 100),
        (val_div, ":plunder_amount", ":num_player_party_shares"),
        (try_begin),
          (party_slot_eq, ":loot_source_party", slot_party_type, spt_kingdom_caravan),
          #          (val_clamp, ":plunder_amount", 1, 50),
          (reset_item_probabilities, 100),
          (assign, ":range_min", trade_goods_begin),
          (assign, ":range_max", trade_goods_end),
        (else_try),
          (val_div, ":plunder_amount", 5),
          #          (val_clamp, ":plunder_amount", 1, 10),
          (reset_item_probabilities, 1),
          (assign, ":range_min", food_begin),
          (assign, ":range_max", food_end),
        (try_end),
        (store_sub, ":item_to_price_slot", slot_town_trade_good_prices_begin, trade_goods_begin),
        (try_for_range, ":cur_goods", ":range_min", ":range_max"),
          (store_add, ":cur_price_slot", ":cur_goods", ":item_to_price_slot"),
          (party_get_slot, ":cur_price", ":loot_source_party", ":cur_price_slot"),
          (val_max, ":cur_price", 1),
          (assign, ":cur_probability", 100),
          (val_mul, ":cur_probability", average_price_factor),
          (val_div, ":cur_probability", ":cur_price"),
          (val_mul, ":cur_probability", average_price_factor),
          (val_div, ":cur_probability", ":cur_price"),
          (val_mul, ":cur_probability", average_price_factor),
          (val_div, ":cur_probability", ":cur_price"),
          (assign, reg0, ":cur_probability"),
          (set_item_probability_in_merchandise, ":cur_goods", ":cur_probability"),
        (try_end),
        (troop_add_merchandise, "trp_temp_troop", itp_type_goods, ":plunder_amount"),
        (assign, reg5, ":plunder_amount"),
        (val_add, ":num_looted_items", ":plunder_amount"),
      (try_end),

      #Now loot the defeated party
      (store_mul, ":loot_probability", player_loot_share, 3),
      (val_mul, ":loot_probability", "$g_strength_contribution_of_player"),
      (party_get_skill_level, ":player_party_looting", "p_main_party", "skl_looting"),
      (val_add, ":player_party_looting", 10),
      (val_mul, ":loot_probability", ":player_party_looting"),
      (val_div, ":loot_probability", 10),
      (val_div, ":loot_probability", ":num_player_party_shares"),

      (assign, ":troop_loot_party", ":enemy_party"),
      (assign, ":troop_loot_party_valid", 0),
      (try_begin),
        (gt, ":troop_loot_party", 0),
        (party_is_active, ":troop_loot_party"),
        (assign, ":troop_loot_party_valid", 1),
      (else_try),
        (eq, ":loot_source_valid", 1),
        (assign, ":troop_loot_party", ":loot_source_party"),
        (assign, ":troop_loot_party_valid", 1),
      (try_end),
      (try_begin),
        (eq, ":troop_loot_party_valid", 1),
        (party_get_num_companion_stacks, ":num_stacks", ":troop_loot_party"),
        (try_for_range, ":i_stack", 0, ":num_stacks"),
          (party_stack_get_troop_id,     ":stack_troop", ":troop_loot_party", ":i_stack"),
          (neg|troop_is_hero, ":stack_troop"),
          (party_stack_get_size, ":stack_size", ":troop_loot_party", ":i_stack"),
          (try_for_range, ":unused", 0, ":stack_size"),
            (troop_loot_troop, "trp_temp_troop", ":stack_troop", ":loot_probability"),
          (try_end),
        (try_end),
      (try_end),
      (troop_get_inventory_capacity, ":inv_cap", "trp_temp_troop"),
      (try_for_range, ":i_slot", 0, ":inv_cap"),
        (troop_get_inventory_slot, ":item_id", "trp_temp_troop", ":i_slot"),
        (ge, ":item_id", 0),
        (val_add, ":num_looted_items", 1),
      (try_end),
      (try_begin),
        (eq, ":num_looted_items", 0),
        (eq, ":is_siege_center", 1),
        (store_mul, ":plunder_amount", player_loot_share, 3),
        (val_mul, ":plunder_amount", "$g_strength_contribution_of_player"),
        (val_div, ":plunder_amount", 100),
        (val_div, ":plunder_amount", ":num_player_party_shares"),
        (val_clamp, ":plunder_amount", 1, 5),
        (reset_item_probabilities, 1),
        (try_for_range, ":cur_food", food_begin, food_end),
          (set_item_probability_in_merchandise, ":cur_food", 100),
        (try_end),
        (troop_add_merchandise, "trp_temp_troop", itp_type_goods, ":plunder_amount"),
        (assign, ":num_looted_items", 0),
        (troop_get_inventory_capacity, ":inv_cap", "trp_temp_troop"),
        (try_for_range, ":i_slot", 0, ":inv_cap"),
          (troop_get_inventory_slot, ":item_id", "trp_temp_troop", ":i_slot"),
          (ge, ":item_id", 0),
          (val_add, ":num_looted_items", 1),
        (try_end),
      (try_end),

      (assign, reg0, ":num_looted_items"),
  ]),
]
