SCRIPTS = [
("sod_merc_party_return_to_guild_or_disband",
 [
   (store_script_param_1, ":cur_party"),

   (assign, ":assigned", 0),
   (assign, ":base", 0),
   (assign, ":guild_faction", 0),
   (try_begin),
     (party_is_active, ":cur_party"),
     (party_get_slot, ":old_boss_troop", ":cur_party", slot_party_boss),
     (party_get_slot, ":base", ":cur_party", slot_party_starting_base),
     (party_get_slot, ":guild_faction", ":cur_party", slot_party_sod_merc_contract_guild),
     (try_begin),
       (neg|is_between, ":guild_faction", guilds_begin, guilds_end),
       (party_get_slot, ":guild_faction", ":cur_party", slot_party_orginal_faction),
     (try_end),
     (try_begin),
       (is_between, ":old_boss_troop", kingdom_heroes_begin, kingdom_heroes_end),
       (troop_slot_eq, ":old_boss_troop", slot_troop_mercenaries, ":cur_party"),
       (troop_set_slot, ":old_boss_troop", slot_troop_mercenaries, -1),
     (try_end),
     (party_set_slot, ":cur_party", slot_party_boss, -1),
     (party_set_slot, ":cur_party", slot_party_sod_merc_contract_employer, 0),
     (try_begin),
       (gt, ":guild_faction", 0),
       (party_set_slot, ":cur_party", slot_party_orginal_faction, ":guild_faction"),
       (party_set_slot, ":cur_party", slot_party_sod_merc_contract_guild, ":guild_faction"),
       (call_script, "script_sod_merc_lord_note_battle_outcome", ":cur_party", 0),
     (try_end),
   (try_end),

   (try_begin),
     (party_is_active, ":cur_party"),
     (gt, ":base", 0),
     (assign, ":active_base_parties", 0),
     (try_for_parties, ":other_party"),
       (party_slot_eq, ":other_party", slot_party_type, spt_ai_mercenaries),
       (party_slot_eq, ":other_party", slot_party_starting_base, ":base"),
       (neq, ":other_party", ":cur_party"),
       (party_get_slot, ":other_commander", ":other_party", slot_party_commander_party),
       (eq, ":other_commander", ":base"),
       (val_add, ":active_base_parties", 1),
     (try_end),
     (lt, ":active_base_parties", 3),
     (party_set_slot, ":cur_party", slot_party_commander_party, ":base"),
     (party_set_ai_behavior, ":cur_party", ai_bhvr_patrol_party),
     (party_set_ai_object, ":cur_party", ":base"),
     (party_set_ai_patrol_radius, ":cur_party", 5),
     (store_current_day, ":cur_day"),
     (store_add, ":contract_end", ":cur_day", 15),
     (party_set_slot, ":cur_party", slot_party_merc_contract, ":contract_end"),
     (party_set_slot, ":cur_party", slot_party_sod_merc_contract_term_end, ":contract_end"),
     (party_set_slot, ":cur_party", slot_party_sod_merc_contract_value, 0),
     (party_set_faction, ":cur_party", "fac_commoners"),
     (party_set_banner_icon, ":cur_party", 0),
     (try_begin),
       (eq, ":base", "p_sod_merc_guild_1"),
       (party_set_banner_icon, ":cur_party", "icon_banner_162"),
     (else_try),
       (eq, ":base", "p_sod_merc_guild_2"),
       (party_set_banner_icon, ":cur_party", "icon_banner_163"),
     (else_try),
       (eq, ":base", "p_sod_merc_guild_3"),
       (party_set_banner_icon, ":cur_party", "icon_banner_164"),
     (else_try),
       (eq, ":base", "p_sod_merc_guild_4"),
       (party_set_banner_icon, ":cur_party", "icon_banner_165"),
     (else_try),
       (eq, ":base", "p_sod_merc_guild_5"),
       (party_set_banner_icon, ":cur_party", "icon_banner_166"),
     (try_end),
     (assign, ":assigned", 1),
   (try_end),

   (try_begin),
     (party_is_active, ":cur_party"),
     (eq, ":assigned", 0),
     (party_set_slot, ":cur_party", slot_party_commander_party, -1),
     (party_set_faction, ":cur_party", "fac_commoners"),
     (party_set_banner_icon, ":cur_party", 0),
     (party_set_ai_behavior, ":cur_party", ai_bhvr_patrol_location),
   (try_end),

   (assign, reg0, ":assigned"),
 ]),
]
