SCRIPTS = [
("sod_external_party_set_order",
 [
   (store_script_param, ":party_no", 1),
   (store_script_param, ":order", 2),
   (store_script_param, ":target", 3),

   (assign, reg0, ":party_no"),
   (assign, ":valid_external_party", 0),
   (try_begin),
     (party_is_active, ":party_no"),
     (party_get_slot, ":party_type", ":party_no", slot_party_type),
     (this_or_next|eq, ":party_type", spt_player_mercenaries),
     (eq, ":party_type", spt_player_patrol),
     (assign, ":valid_external_party", 1),
   (try_end),

   (try_begin),
     (eq, ":valid_external_party", 1),
     (party_get_attached_to, ":attached_to", ":party_no"),

     (try_begin),
       (eq, ":order", sod_external_order_follow_player),
       (try_begin),
         (gt, ":attached_to", 0),
         (party_detach, ":party_no"),
       (try_end),
       (call_script, "script_party_set_ai_state", ":party_no", spai_accompanying_army, "p_main_party"),
       (party_set_slot, ":party_no", slot_party_follow_me, 1),
       (party_get_template_id, ":template", ":party_no"),
       (try_begin),
         (neq, ":template", "pt_player_patrol"),
         (call_script, "script_change_party_template", ":party_no", "pt_player_patrol"),
         (assign, ":party_no", "$g_encountered_party"),
       (try_end),
       (assign, reg0, ":party_no"),

     (else_try),
       (eq, ":order", sod_external_order_hold_here),
       (try_begin),
         (gt, ":attached_to", 0),
         (party_detach, ":party_no"),
       (try_end),
       (party_get_position, pos1, ":party_no"),
       (party_set_ai_behavior, ":party_no", ai_bhvr_hold),
       (party_set_ai_target_position, ":party_no", pos1),
       (party_set_slot, ":party_no", slot_party_ai_state, sod_external_order_hold_here),
       (party_set_slot, ":party_no", slot_party_ai_object, -1),
       (party_set_slot, ":party_no", slot_party_follow_me, 0),
       (party_set_slot, ":party_no", slot_party_ai_substate, 0),
       (party_get_template_id, ":template", ":party_no"),
       (try_begin),
         (neq, ":template", "pt_player_patrol_2"),
         (call_script, "script_change_party_template", ":party_no", "pt_player_patrol_2"),
         (assign, ":party_no", "$g_encountered_party"),
       (try_end),
       (assign, reg0, ":party_no"),

     (else_try),
       (eq, ":order", sod_external_order_patrol_here),
       (try_begin),
         (gt, ":attached_to", 0),
         (party_detach, ":party_no"),
       (try_end),
       (party_get_position, pos1, ":party_no"),
       (party_set_ai_behavior, ":party_no", ai_bhvr_patrol_location),
       (party_set_ai_target_position, ":party_no", pos1),
       (party_set_ai_patrol_radius, ":party_no", 5),
       (party_set_slot, ":party_no", slot_party_ai_state, sod_external_order_patrol_here),
       (party_set_slot, ":party_no", slot_party_ai_object, -1),
       (party_set_slot, ":party_no", slot_party_follow_me, 1),
       (party_set_slot, ":party_no", slot_party_ai_substate, 0),
       (party_get_template_id, ":template", ":party_no"),
       (try_begin),
         (neq, ":template", "pt_player_patrol_2"),
         (call_script, "script_change_party_template", ":party_no", "pt_player_patrol_2"),
         (assign, ":party_no", "$g_encountered_party"),
       (try_end),
       (assign, reg0, ":party_no"),

     (else_try),
       (eq, ":order", spai_holding_center),
       (is_between, ":target", centers_begin, centers_end),
       (call_script, "script_party_set_ai_state", ":party_no", spai_holding_center, ":target"),
       (party_set_slot, ":party_no", slot_party_follow_me, 0),
       (party_get_template_id, ":template", ":party_no"),
       (try_begin),
         (neq, ":template", "pt_player_patrol"),
         (call_script, "script_change_party_template", ":party_no", "pt_player_patrol"),
         (assign, ":party_no", "$g_encountered_party"),
       (try_end),
       (assign, reg0, ":party_no"),

     (else_try),
       (eq, ":order", spai_patrolling_around_center),
       (is_between, ":target", centers_begin, centers_end),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":target"),
       (party_set_slot, ":party_no", slot_party_follow_me, 1),
       (party_get_template_id, ":template", ":party_no"),
       (try_begin),
         (neq, ":template", "pt_player_patrol_2"),
         (call_script, "script_change_party_template", ":party_no", "pt_player_patrol_2"),
         (assign, ":party_no", "$g_encountered_party"),
       (try_end),
       (assign, reg0, ":party_no"),

     (else_try),
       (eq, ":order", sod_external_order_noop),
       (assign, reg0, ":party_no"),
     (try_end),
   (try_end),
 ]),
]
