SCRIPTS = [
("sod_initialize_party",
    [
      #SoD Character Creation begin
      (troop_clear_inventory, "trp_player"),
      (troop_add_item, "trp_player", "itm_smoked_fish", 0),
      (troop_add_item, "trp_player", "itm_dried_meat", 0),
      (troop_add_item, "trp_player", "itm_bread", 0),
      (troop_add_item, "trp_player", "itm_sausages", 0),

      # give them some low-requirements basic equipment so that they're not naked
      (troop_add_item, "trp_player", "itm_sword_medieval_a", 0),
      (troop_add_item, "trp_player", "itm_leather_boots", 0),
      (troop_add_item, "trp_player", "itm_courser", 0),
      (troop_add_item, "trp_player", "itm_nobleman_outfit", 0),

      (try_begin),
        (eq, "$g_sod_country", cb_antares),
        (troop_add_item, "trp_player", "itm_darkboots", 0),
        (troop_add_item, "trp_player", "itm_antgaunt2", 0),
        (troop_add_item, "trp_player", "itm_antplate1", 0),
        (troop_add_item, "trp_player", "itm_anthelm1", 0),
        (troop_add_item, "trp_player", "itm_antshield", 0),
        (troop_add_item, "trp_player", "itm_anthorse1", 0),
      (else_try),
        (eq, "$g_sod_country", cb_marina),
        (troop_add_item, "trp_player", "itm_marboots1", 0),
        (troop_add_item, "trp_player", "itm_marchain1", 0),
        (troop_add_item, "trp_player", "itm_marhelm1", 0),
        (troop_add_item, "trp_player", "itm_darkgauntlets", 0),
        (troop_add_item, "trp_player", "itm_warhorse", 0),
        (troop_add_item, "trp_player", "itm_realglaive", 0),
        (troop_add_item, "trp_player", "itm_bolts", 0),
        (troop_add_item, "trp_player", "itm_light_crossbow", 0),
      (else_try),
        (eq, "$g_sod_country", cb_aden),
        (troop_add_item, "trp_player", "itm_mail_boots", 0),
        (troop_add_item, "trp_player", "itm_mail_mittens", 0),
        (troop_add_item, "trp_player", "itm_coat_of_plates", 0),
        (troop_add_item, "trp_player", "itm_pigface", 0),
        (troop_add_item, "trp_player", "itm_shield_heater_generic_a", 0),
        (troop_add_item, "trp_player", "itm_warhorse", 0),
      (else_try),
        (eq, "$g_sod_country", cb_villian),
        (troop_add_item, "trp_player", "itm_villboots1", 0),
        (troop_add_item, "trp_player", "itm_villgloves1", 0),
        (troop_add_item, "trp_player", "itm_vilarmor_9", 0),
        (troop_add_item, "trp_player", "itm_villhelm1", 0),
        (troop_add_item, "trp_player", "itm_villshield", 0),
        (troop_add_item, "trp_player", "itm_vilhorse1", 0),
        (troop_add_item, "trp_player", "itm_barbed_arrows", 0),
        (troop_add_item, "trp_player", "itm_long_bow", 0),
      (else_try),
        (eq, "$g_sod_country", cb_zerrikan),
        (troop_add_item, "trp_player", "itm_noble_start_boots", 0),
        (troop_add_item, "trp_player", "itm_mail_mittens", 0),
        (troop_add_item, "trp_player", "itm_noble_padded_leather", 0),
        (troop_add_item, "trp_player", "itm_noble_spiked_helm", 0),
        (troop_add_item, "trp_player", "itm_decor_colors3_shield", 0),
        (troop_add_item, "trp_player", "itm_noble_charger", 0), #this is actually a warhorse
        (troop_add_item, "trp_player", "itm_nomad_bow", 0), 
        (troop_add_item, "trp_player", "itm_arrows", 0), 
      (try_end),

      (try_begin),
        (eq, "$g_sod_faith", cb_the_one),
        (troop_add_item, "trp_player", "itm_morningstar", 0),
      (else_try),
        (eq, "$g_sod_faith", cb_old_gods),
        (troop_add_item, "trp_player", "itm_onehandedwarhammer", 0),
      (else_try),
        (eq, "$g_sod_faith", cb_the_void),
        (troop_add_item, "trp_player", "itm_darkespadon", 0),
      (else_try),
        (eq, "$g_sod_faith", cb_enlightenment),
        (troop_add_item, "trp_player", "itm_seax", 0),
      (else_try),
        (eq, "$g_sod_faith", cb_atheism),
        (troop_add_item, "trp_player", "itm_polehammer", 0),
      (try_end),
	  (call_script, "script_sod_initialize_strategy_advisor"),
      (call_script, "script_sod_initialize_vassals"),
      (call_script, "script_sod_apply_initial_party_members"),
      (assign, "$g_sod_main_party_setup_pending", 0),
      (assign, "$g_sod_initial_party_members_pending", 0),
      (assign, "$g_sod_pending_player_banner_map_icon", -1),
      (assign, "$g_sod_player_map_icon_dirty", 1),
    ]
  ),
("sod_apply_initial_party_members",
    [
      (party_add_members, "p_main_party", "trp_sod_strategy_advisor", 1),

      (try_begin),
        (eq, "$g_sod_country", cb_antares),
        (party_add_members, "p_main_party", "trp_sod_ant_noble", 3),
        (party_add_members, "p_main_party", "trp_sod_ant_elite", 1),
        (party_add_members, "p_main_party", "trp_sod_ant_veteran", 5),
        (party_add_members, "p_main_party", "trp_sod_ant_regular", 15),
        (party_add_members, "p_main_party", "trp_sod_ant_javelinman", 15),
        (party_add_members, "p_main_party", "trp_sod_ant_trained_javelinman", 5),
        (party_add_members, "p_main_party", "trp_sod_ant_scout", 5),
      (else_try),
        (eq, "$g_sod_country", cb_marina),
        (party_add_members, "p_main_party", "trp_sod_mar_mercenary", 3),
        (party_add_members, "p_main_party", "trp_sod_mar_elite", 1),
        (party_add_members, "p_main_party", "trp_sod_mar_veteran", 3),
        (party_add_members, "p_main_party", "trp_sod_mar_regular", 5),
        (party_add_members, "p_main_party", "trp_sod_mar_conscript", 10),
        (party_add_members, "p_main_party", "trp_sod_mar_crossbowman", 10),
        (party_add_members, "p_main_party", "trp_sod_mar_trained_crossbowman", 5),
        (party_add_members, "p_main_party", "trp_sod_mar_elite_crossbowman", 3),
        (party_add_members, "p_main_party", "trp_sod_mar_sharpshooter", 1),
      (else_try),
        (eq, "$g_sod_country", cb_aden),
        (party_add_members, "p_main_party", "trp_sod_ade_knight", 1),
        (party_add_members, "p_main_party", "trp_sod_ade_sqire", 3),
        (party_add_members, "p_main_party", "trp_sod_ade_heavy", 1),
        (party_add_members, "p_main_party", "trp_sod_ade_medium", 3),
        (party_add_members, "p_main_party", "trp_sod_ade_light", 5),
        (party_add_members, "p_main_party", "trp_sod_ade_regular", 5),
        (party_add_members, "p_main_party", "trp_sod_ade_archer", 10),
        (party_add_members, "p_main_party", "trp_sod_ade_regular", 10),
        (party_add_members, "p_main_party", "trp_sod_ade_veteran", 5),
      (else_try),
        (eq, "$g_sod_country", cb_villian),
        (party_add_members, "p_main_party", "trp_sod_vil_chief", 1),
        (party_add_members, "p_main_party", "trp_sod_vil_noble", 3),
        (party_add_members, "p_main_party", "trp_sod_vil_sharpshooter", 1),
        (party_add_members, "p_main_party", "trp_sod_vil_elite_longbowman", 3),
        (party_add_members, "p_main_party", "trp_sod_vil_veteran", 5),
        (party_add_members, "p_main_party", "trp_sod_vil_veteran_longbowman", 5),
        (party_add_members, "p_main_party", "trp_sod_vil_regular", 10),
        (party_add_members, "p_main_party", "trp_sod_vil_longbowman", 10),
        (party_add_members, "p_main_party", "trp_sod_vil_scout", 5),
      (else_try),
        (eq, "$g_sod_country", cb_zerrikan),
        (party_add_members, "p_main_party", "trp_sod_zer_2_noble", 1),
        (party_add_members, "p_main_party", "trp_sod_zer_1_noble", 3),
        (party_add_members, "p_main_party", "trp_sod_zer_3_cavalry", 1),
        (party_add_members, "p_main_party", "trp_sod_zer_1_cavalry_archer", 3),
        (party_add_members, "p_main_party", "trp_sod_zer_2_cavalry", 5),
        (party_add_members, "p_main_party", "trp_sod_zer_1_cavalry", 5),
        (party_add_members, "p_main_party", "trp_sod_zer_1_infantry", 10),
        (party_add_members, "p_main_party", "trp_sod_zer_1_archer", 10),
        (party_add_members, "p_main_party", "trp_sod_zer_2_archer", 5),
      (try_end),
      (assign, "$g_sod_initial_party_members_pending", 0),
    ]
  ),
("sod_apply_player_banner_map_icon",
    [
      (store_script_param_1, ":flag_icon"),
      (assign, "$g_sod_pending_player_banner_map_icon", ":flag_icon"),
      (party_set_banner_icon, "p_main_party", ":flag_icon"),
      (assign, "$g_sod_pending_player_banner_map_icon", -1),
      (assign, "$g_sod_player_map_icon_dirty", 1),
    ]
  ),
("sod_refresh_player_map_icon",
    [
      (try_begin),
        (eq, "$g_sod_player_world_ready", 1),
        (main_party_has_troop, "trp_player"),
        (troop_get_inventory_slot, ":cur_horse", "trp_player", 8),
        (assign, ":new_icon", -1),
        (try_begin),
          (eq, "$g_player_icon_state", pis_normal),
          (try_begin),
            (ge, ":cur_horse", 0),
            (assign, ":new_icon", "icon_player_horseman"),
          (else_try),
            (assign, ":new_icon", "icon_player"),
          (try_end),
        (else_try),
          (eq, "$g_player_icon_state", pis_camping),
          (assign, ":new_icon", "icon_camp"),
        (else_try),
          (eq, "$g_player_icon_state", pis_ship),
          (assign, ":new_icon", "icon_ship"),
        (try_end),
        (try_begin),
          (neq, ":new_icon", "$g_player_party_icon"),
          (assign, "$g_player_party_icon", ":new_icon"),
          (party_set_icon, "p_main_party", ":new_icon"),
        (try_end),
        (assign, "$g_sod_player_map_icon_initialized", 1),
        (assign, "$g_sod_player_map_icon_dirty", 0),
        (store_current_hours, ":cur_hours"),
        (store_add, ":next_check_hour", ":cur_hours", 1),
        (assign, "$g_sod_player_map_icon_next_check_hour", ":next_check_hour"),
      (try_end),
    ]
  ),
("sod_finish_initial_party_world_setup",
    [
      (try_begin),
        (eq, "$g_sod_player_world_ready", 0),
        (try_begin),
          (eq, "$g_sod_initial_party_members_pending", 1),
          (call_script, "script_sod_apply_initial_party_members"),
        (try_end),
        (store_random_in_range, ":starting_training_ground", training_grounds_begin, training_grounds_end),
        (party_relocate_near_party, "p_main_party", ":starting_training_ground", 3),
        (call_script, "script_store_troop_name_fief", s5, "trp_player"),
        (party_set_name, "p_main_party", s5),
        (try_begin),
          (gt, "$g_sod_pending_player_banner_map_icon", 0),
          (party_set_banner_icon, "p_main_party", "$g_sod_pending_player_banner_map_icon"),
          (assign, "$g_sod_pending_player_banner_map_icon", -1),
        (try_end),
        (call_script, "script_get_player_party_morale_values"),
        (party_set_morale, "p_main_party", reg0),
        (assign, "$g_sod_main_party_setup_pending", 0),
        (assign, "$g_sod_initial_party_members_pending", 0),
        (assign, "$g_sod_initial_world_setup_pending", 0),
        (assign, "$g_sod_player_world_ready", 1),
        (assign, "$g_player_party_icon", -1),
        (assign, "$g_sod_player_map_icon_dirty", 1),
        (call_script, "script_sod_refresh_player_map_icon"),
      (try_end),
    ]
  ),
("sod_try_finish_initial_party_after_creation",
    [
      (assign, reg0, 0),
      (try_begin),
        (map_free),
        (main_party_has_troop, "trp_player"),
        (try_begin),
          (eq, "$g_sod_main_party_setup_pending", 1),
          (store_random_in_range, ":starting_training_ground", training_grounds_begin, training_grounds_end),
          (party_relocate_near_party, "p_main_party", ":starting_training_ground", 3),
          (call_script, "script_store_troop_name_fief", s5, "trp_player"),
          (party_set_name, "p_main_party", s5),
          (assign, "$g_sod_main_party_setup_pending", 0),
          (assign, "$g_player_party_icon", -1),
          (assign, "$g_sod_player_map_icon_dirty", 1),
        (try_end),
        (try_begin),
          (eq, "$g_sod_initial_party_members_pending", 1),
          (call_script, "script_sod_apply_initial_party_members"),
        (try_end),
        (try_begin),
          (gt, "$g_sod_pending_player_banner_map_icon", 0),
          (party_set_banner_icon, "p_main_party", "$g_sod_pending_player_banner_map_icon"),
          (assign, "$g_sod_pending_player_banner_map_icon", -1),
        (try_end),
        (call_script, "script_get_player_party_morale_values"),
        (party_set_morale, "p_main_party", reg0),
        (assign, reg0, 1),
      (try_end),
    ]
  ),
("sod_apply_rtc_starting_salvage_bonus",
    [
      (try_begin),
        (eq, "$g_sod_rtc_enabled", 1),
        (main_party_has_troop, "trp_player"),
        (eq, "$g_sod_rtc_starting_survivors_applied", 0),
        (eq, "$g_sod_rtc_starting_salvage_choice", sod_rtc_salvage_wounded),
        (try_begin),
          (eq, "$g_sod_country", cb_antares),
          (party_add_members, "p_main_party", "trp_sod_ant_regular", 4),
          (party_add_members, "p_main_party", "trp_sod_ant_javelinman", 4),
          (party_wound_members, "p_main_party", "trp_sod_ant_regular", 3),
          (party_wound_members, "p_main_party", "trp_sod_ant_javelinman", 3),
        (else_try),
          (eq, "$g_sod_country", cb_marina),
          (party_add_members, "p_main_party", "trp_sod_mar_regular", 4),
          (party_add_members, "p_main_party", "trp_sod_mar_crossbowman", 4),
          (party_wound_members, "p_main_party", "trp_sod_mar_regular", 3),
          (party_wound_members, "p_main_party", "trp_sod_mar_crossbowman", 3),
        (else_try),
          (eq, "$g_sod_country", cb_aden),
          (party_add_members, "p_main_party", "trp_sod_ade_light", 4),
          (party_add_members, "p_main_party", "trp_sod_ade_archer", 4),
          (party_wound_members, "p_main_party", "trp_sod_ade_light", 3),
          (party_wound_members, "p_main_party", "trp_sod_ade_archer", 3),
        (else_try),
          (eq, "$g_sod_country", cb_villian),
          (party_add_members, "p_main_party", "trp_sod_vil_regular", 4),
          (party_add_members, "p_main_party", "trp_sod_vil_longbowman", 4),
          (party_wound_members, "p_main_party", "trp_sod_vil_regular", 3),
          (party_wound_members, "p_main_party", "trp_sod_vil_longbowman", 3),
        (else_try),
          (eq, "$g_sod_country", cb_zerrikan),
          (party_add_members, "p_main_party", "trp_sod_zer_1_infantry", 4),
          (party_add_members, "p_main_party", "trp_sod_zer_1_archer", 4),
          (party_wound_members, "p_main_party", "trp_sod_zer_1_infantry", 3),
          (party_wound_members, "p_main_party", "trp_sod_zer_1_archer", 3),
        (try_end),
        (assign, "$g_sod_rtc_starting_survivors_applied", 1),
      (try_end),
    ]
  ),
]
