SCRIPTS = [
("total_victory_try_enemy_hero_resolution",
    [
      (assign, reg0, 0),
      (assign, ":stack_troop_dna", 0),
      (party_get_num_companion_stacks, ":num_stacks", "p_encountered_party_backup"),

      (try_for_range, ":stack_no", "$last_defeated_hero", ":num_stacks"),
        (eq, reg0, 0),
        (party_stack_get_troop_id, ":stack_troop", "p_encountered_party_backup", ":stack_no"),
        (party_stack_get_troop_dna, ":stack_troop_dna", "p_encountered_party_backup", ":stack_no"),

        (troop_is_hero, ":stack_troop"),
        (store_add, "$last_defeated_hero", ":stack_no", 1),

        (call_script, "script_remove_troop_from_prison", ":stack_troop"),
        (troop_set_slot, ":stack_troop", slot_troop_leaded_party, -1),
        (store_troop_faction, ":defeated_faction", ":stack_troop"),

        (try_begin),
          (eq, ":stack_troop", "trp_khergit_chieftain"),
          (assign, "$talk_context", tc_hero_defeated),
          (call_script, "script_setup_troop_meeting", ":stack_troop", ":stack_troop_dna"),
          (assign, reg0, 1),
        (else_try),
          (call_script, "script_cf_check_hero_can_die_in_battle", ":stack_troop"),
          (call_script, "script_store_troop_name", s1, ":stack_troop"),
          (str_store_faction_name, s3, ":defeated_faction"),
          (str_store_string, s17, "@{s1} of {s3} has died in battle."),
          (display_log_message, "@{s17}", warning_color),
          (call_script, "script_sod_runtime_trace_event", 5, "$g_enemy_party", ":stack_troop"),
          (call_script, "script_kill_kingdom_hero", ":stack_troop"),
          (call_script, "script_store_troop_name", s1, ":stack_troop"),
          (str_store_faction_name, s3, ":defeated_faction"),
          (str_store_string, s17, "@{s1} of {s3} has died in battle."),
          (jump_to_menu, "mnu_enemy_slipped_away"),
          (assign, reg0, 1),
        (else_try),
          (call_script, "script_cf_check_hero_can_escape_from_player", ":stack_troop"),
          (call_script, "script_store_troop_name", s1, ":stack_troop"),
          (str_store_faction_name, s3, ":defeated_faction"),
          (str_store_string, s17, "@{s1} of {s3} managed to escape."),
          (display_log_message, "@{s17}", warning_color),
          (jump_to_menu, "mnu_enemy_slipped_away"),
          (assign, reg0, 1),
        (else_try),
          (assign, "$talk_context", tc_hero_defeated),
          (call_script, "script_sod_artifact_capture_spoils", "trp_player", ":stack_troop"),
          (faction_get_slot, ":weariness", ":defeated_faction", slot_faction_diplomacy_war_weariness),
          (val_add, ":weariness", 2),
          (val_clamp, ":weariness", 0, 101),
          (faction_set_slot, ":defeated_faction", slot_faction_diplomacy_war_weariness, ":weariness"),
          (call_script, "script_setup_troop_meeting", ":stack_troop", ":stack_troop_dna"),
          (assign, reg0, 1),
        (try_end),
      (try_end),
  ]),
]
