SCRIPTS = [
("total_victory_distribute_leftovers",
    [
      # After the capture/loot screens, redistribute anything still sitting in
      # p_temp_party back into the allied or reinforcement group.
      (try_begin),
        (gt, "$g_ally_party", 0),
        (party_is_active, "$g_ally_party"),
        (distribute_party_among_party_group, "p_temp_party", "$g_ally_party"),
        (call_script, "script_cf_fix_party_size", "$g_ally_party", 0),
        (store_faction_of_party, ":ally_faction", "$g_ally_party"),
        (call_script, "script_get_nonempty_party_in_group", "$g_ally_party"),
        (assign, ":ally_prisoner_carrier", reg0),
        (try_begin),
          (gt, ":ally_prisoner_carrier", 0),
          (neq, ":ally_prisoner_carrier", "p_main_party"),
          (call_script, "script_sod_maybe_create_prisoner_train_from_party", ":ally_prisoner_carrier", ":ally_faction", 2, sod_prisoner_train_purpose_imprisonment),
        (try_end),
      (else_try),
        (party_get_num_attached_parties, ":num_quick_attachments", "p_main_party"),
        (gt, ":num_quick_attachments", 0),
        (party_get_attached_party_with_rank, ":helper_party", "p_main_party", 0),
        (gt, ":helper_party", 0),
        (party_is_active, ":helper_party"),
        (distribute_party_among_party_group, "p_temp_party", ":helper_party"),
        (call_script, "script_cf_fix_party_size", ":helper_party", 0),
        (store_faction_of_party, ":helper_faction", ":helper_party"),
        (call_script, "script_sod_maybe_create_prisoner_train_from_party", ":helper_party", ":helper_faction", 3, sod_prisoner_train_purpose_imprisonment),
      (try_end),
  ]),
]
