SCRIPTS = [
("cf_sod_companion_in_main_party",
 [
   (store_script_param_1, ":companion"),
   (this_or_next|is_between, ":companion", companions_begin, companions_end),
   (is_between, ":companion", special_companions_begin, special_companions_end),
   # A hero may transiently appear in p_main_party without being one of the
   # player's active companions.  World effects and dialogue must not treat
   # that stack membership as companion participation.
   (troop_slot_eq, ":companion", slot_troop_occupation, slto_player_companion),
   (main_party_has_troop, ":companion"),
   (party_count_companions_of_type, ":companion_count", "p_main_party", ":companion"),
   (gt, ":companion_count", 0),
 ]),
("cf_sod_any_companion_in_main_party",
 [
   (store_script_param_1, ":companion_a"),
   (store_script_param_2, ":companion_b"),
   (store_script_param, ":companion_c", 3),
   (assign, ":found", 0),
   (try_begin),
     (gt, ":companion_a", 0),
     (call_script, "script_cf_sod_companion_in_main_party", ":companion_a"),
     (assign, ":found", 1),
   (try_end),
   (try_begin),
     (eq, ":found", 0),
     (gt, ":companion_b", 0),
     (call_script, "script_cf_sod_companion_in_main_party", ":companion_b"),
     (assign, ":found", 1),
   (try_end),
   (try_begin),
     (eq, ":found", 0),
     (gt, ":companion_c", 0),
     (call_script, "script_cf_sod_companion_in_main_party", ":companion_c"),
     (assign, ":found", 1),
   (try_end),
   (eq, ":found", 1),
 ]),
]
