SCRIPTS = [
("fill_tournament_participants_troop",
        [(store_script_param, ":center_no", 1),
          (store_script_param, ":player_at_center", 2),
          (assign, ":cur_slot", 0),

          (try_begin),
            (eq, ":player_at_center", 1),
            (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
            (try_for_range, ":stack_no", 0, ":num_stacks"),
              (party_stack_get_troop_id, ":cur_troop", "p_main_party", ":stack_no"),
              (troop_is_hero, ":cur_troop"),
              (neq, ":cur_troop", "trp_kidnapped_girl"),
              (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":cur_troop"),
              (val_add, ":cur_slot", 1),
            (try_end),
          (try_end),

          (party_collect_attachments_to_party, ":center_no", "p_temp_party"),
          (party_get_num_companion_stacks, ":num_stacks", "p_temp_party"),
          (try_for_range, ":stack_no", 0, ":num_stacks"),
            (party_stack_get_troop_id, ":cur_troop", "p_temp_party", ":stack_no"),
            (troop_is_hero, ":cur_troop"),
            (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":cur_troop"),
            (val_add, ":cur_slot", 1),
          (try_end),

          (try_begin),
            (store_random_in_range, ":random_no", 0, 100),
            (lt, ":random_no", 50),
            (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_xerina"),
            (val_add, ":cur_slot", 1),
          (try_end),
          (try_begin),
            (store_random_in_range, ":random_no", 0, 100),
            (lt, ":random_no", 50),
            (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_dranton"),
            (val_add, ":cur_slot", 1),
          (try_end),
          (try_begin),
            (store_random_in_range, ":random_no", 0, 100),
            (lt, ":random_no", 50),
            (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_kradus"),
            (val_add, ":cur_slot", 1),
          (try_end),

          (assign, ":begin_slot", ":cur_slot"),
          (try_for_range, ":cur_slot", ":begin_slot", 64),
            (store_random_in_range, ":random_no", 0, 10),
            (try_begin),
              (eq, ":random_no", 0),
              (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_regular_fighter"),
            (else_try),
              (le, ":random_no", 3),
              (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_veteran_fighter"),
            (else_try),
              (le, ":random_no", 6),
              (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_champion_fighter"),
            (else_try),
              (eq, ":random_no", 7),
              (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_sword_sister"),
            (else_try),
              (eq, ":random_no", 8),
              (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_hired_blade"),
            (else_try),
              (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_mercenary_swordsman"),
            (try_end),
          (try_end),
      ]),
]
