from header_operations import *
from module_constants import *
from module_troops import *

try:
    slot_troop_companion_grievance
except NameError:
    slot_troop_companion_grievance = slot_troop_companion_cohesion + 1

SCRIPTS = [
    ("npc_morale",
        [
          (store_script_param_1, ":npc"),

          (troop_get_slot, ":morality_grievances", ":npc", slot_troop_morality_penalties),
          (troop_get_slot, ":personality_grievances", ":npc", slot_troop_personalityclash_penalties),
          (troop_get_slot, ":companion_cohesion", ":npc", slot_troop_companion_cohesion),
          (party_get_morale, ":party_morale", "p_main_party"),

          (store_sub, ":troop_morale", ":party_morale", ":morality_grievances"),
          (val_sub, ":troop_morale", ":personality_grievances"),
          (store_sub, ":cohesion_bonus", ":companion_cohesion", 50),
          (val_div, ":cohesion_bonus", 3),
          (store_div, ":bond_bonus", ":companion_cohesion", 8),
          (store_div, ":grievance_drag", ":personality_grievances", 7),
          (assign, ":cohesion_gap", 0),
          (val_add, ":cohesion_bonus", ":bond_bonus"),
          (val_sub, ":cohesion_bonus", ":grievance_drag"),

          (assign, ":camp_stability_bonus", 0),
          (try_begin),
            (ge, "$g_companion_recent_resentment", 60),
            (assign, ":camp_stability_bonus", -4),
          (else_try),
            (ge, "$g_companion_recent_resentment", 40),
            (assign, ":camp_stability_bonus", -2),
          (else_try),
            (lt, "$g_companion_recent_resentment", 15),
            (assign, ":camp_stability_bonus", 2),
          (try_end),
          (try_begin),
            (ge, "$g_companion_clash_chain", 3),
            (val_sub, ":camp_stability_bonus", 2),
          (else_try),
            (eq, "$g_companion_clash_chain", 0),
            (val_add, ":camp_stability_bonus", 1),
          (try_end),
          (val_add, ":cohesion_bonus", ":camp_stability_bonus"),

          (try_begin),
            (ge, ":companion_cohesion", ":personality_grievances"),
            (val_add, ":cohesion_bonus", 3),
          (else_try),
            (val_sub, ":cohesion_bonus", 3),
          (try_end),

          (try_begin),
            (ge, ":companion_cohesion", COMPANION_COHESION_STRONG),
            (le, ":personality_grievances", COMPANION_GRIEVANCE_LOW),
            (val_add, ":cohesion_bonus", 4),
          (else_try),
            (le, ":companion_cohesion", COMPANION_COHESION_WEAK),
            (ge, ":personality_grievances", COMPANION_GRIEVANCE_HIGH),
            (val_sub, ":cohesion_bonus", 4),
          (try_end),

          (store_sub, ":cohesion_gap", ":companion_cohesion", ":personality_grievances"),
          (try_begin),
            (gt, ":cohesion_gap", 20),
            (val_add, ":cohesion_bonus", 4),
          (else_try),
            (gt, ":cohesion_gap", 10),
            (val_add, ":cohesion_bonus", 2),
          (else_try),
            (gt, ":cohesion_gap", 0),
            (val_add, ":cohesion_bonus", 1),
          (else_try),
            (lt, ":cohesion_gap", -20),
            (val_sub, ":cohesion_bonus", 4),
          (else_try),
            (lt, ":cohesion_gap", -10),
            (val_sub, ":cohesion_bonus", 2),
          (else_try),
            (lt, ":cohesion_gap", 0),
            (val_sub, ":cohesion_bonus", 1),
          (try_end),

          (val_add, ":troop_morale", ":cohesion_bonus"),
          (val_add, ":troop_morale", 50),

          (assign, reg8, ":troop_morale"),

          (val_mul, ":troop_morale", 3),
          (val_div, ":troop_morale", 4),
          (val_clamp, ":troop_morale", 0, 101),

          (assign, reg5, ":party_morale"),
          (assign, reg6, ":morality_grievances"),
          (assign, reg7, ":personality_grievances"),
          (assign, reg9, ":troop_morale"),
          (assign, reg10, ":companion_cohesion"),
          (assign, reg11, ":cohesion_bonus"),

          #        (call_script, "script_store_troop_name_link", s11, ":npc"),
          #        (display_message, "@{s11}'s morale = PM{reg5} + 50 - MG{reg6} - PG{reg7} = {reg8} x 0.75 = {reg9}", debug_color),

          (try_begin),
            (lt, ":morality_grievances", 3),
            (str_store_string, 7, "str_happy"),
          (else_try),
            (lt, ":morality_grievances", 15),
            (str_store_string, 7, "str_content"),
          (else_try),
            (lt, ":morality_grievances", 30),
            (str_store_string, 7, "str_concerned"),
          (else_try),
            (lt, ":morality_grievances", 45),
            (str_store_string, 7, "str_not_happy"),
          (else_try),
            (str_store_string, 7, "str_miserable"),
          (try_end),


          (try_begin),
            (lt, ":personality_grievances", 3),
            (str_store_string, 6, "str_happy"),
          (else_try),
            (lt, ":personality_grievances", 15),
            (str_store_string, 6, "str_content"),
          (else_try),
            (lt, ":personality_grievances", 30),
            (str_store_string, 6, "str_concerned"),
          (else_try),
            (lt, ":personality_grievances", 45),
            (str_store_string, 6, "str_not_happy"),
          (else_try),
            (str_store_string, 6, "str_miserable"),
          (try_end),


          (try_begin),
            (gt, ":troop_morale", 80),
            (str_store_string, 8, "str_happy"),
            (str_store_string, 63, "str_bar_enthusiastic"),
          (else_try),
            (gt, ":troop_morale", 60),
            (str_store_string, 8, "str_content"),
            (str_store_string, 63, "str_bar_content"),
          (else_try),
            (gt, ":troop_morale", 40),
            (str_store_string, 8, "str_concerned"),
            (str_store_string, 63, "str_bar_weary"),
          (else_try),
            (gt, ":troop_morale", 20),
            (str_store_string, 8, "str_not_happy"),
            (str_store_string, 63, "str_bar_disgruntled"),
          (else_try),
            (str_store_string, 8, "str_miserable"),
            (str_store_string, 63, "str_bar_miserable"),
          (try_end),


          (str_store_string, 21, "str_npc_morale_report"),
          (assign, reg0, ":troop_morale"),

      ]),
]
