SCRIPTS = [
("reduce_companion_morale_for_clash",
        [
          (store_script_param, ":companion_1", 1),
          (store_script_param, ":companion_2", 2),
          (store_script_param, ":slot_for_clash_state", 3),

          (troop_get_slot, ":clash_state", ":companion_1", ":slot_for_clash_state"),
          (troop_get_slot, ":grievance_1", ":companion_1", slot_troop_personalityclash_penalties),
          (troop_get_slot, ":grievance_2", ":companion_2", slot_troop_personalityclash_penalties),
          (troop_get_slot, ":cohesion_1", ":companion_1", slot_troop_companion_cohesion),
          (troop_get_slot, ":cohesion_2", ":companion_2", slot_troop_companion_cohesion),

          (troop_get_slot, ":match_1", ":companion_1", slot_troop_personalitymatch_object),
          (troop_get_slot, ":match_2", ":companion_2", slot_troop_personalitymatch_object),
          (troop_get_slot, ":clash_1", ":companion_1", slot_troop_personalityclash_object),
          (troop_get_slot, ":clash_2", ":companion_2", slot_troop_personalityclash_object),
          (troop_get_slot, ":clash2_1", ":companion_1", slot_troop_personalityclash2_object),
          (troop_get_slot, ":clash2_2", ":companion_2", slot_troop_personalityclash2_object),

          (assign, ":pair_bias", 0),
          (try_begin),
            (eq, ":match_1", ":companion_2"),
            (val_sub, ":pair_bias", 2),
          (try_end),
          (try_begin),
            (eq, ":match_2", ":companion_1"),
            (val_sub, ":pair_bias", 2),
          (try_end),
          (try_begin),
            (eq, ":clash_1", ":companion_2"),
            (val_add, ":pair_bias", 2),
          (try_end),
          (try_begin),
            (eq, ":clash_2", ":companion_1"),
            (val_add, ":pair_bias", 2),
          (try_end),
          (try_begin),
            (eq, ":clash2_1", ":companion_2"),
            (val_add, ":pair_bias", 1),
          (try_end),
          (try_begin),
            (eq, ":clash2_2", ":companion_1"),
            (val_add, ":pair_bias", 1),
          (try_end),

          (try_begin),
            (eq, ":clash_state", pclash_penalty_to_self),
            (val_add, ":grievance_1", 5),
            (val_sub, ":cohesion_1", 5),
            (val_sub, ":cohesion_2", 2),
          (else_try),
            (eq, ":clash_state", pclash_penalty_to_other),
            (val_add, ":grievance_2", 5),
            (val_sub, ":cohesion_1", 2),
            (val_sub, ":cohesion_2", 5),
          (else_try),
            (eq, ":clash_state", pclash_penalty_to_both),
            (val_add, ":grievance_1", 3),
            (val_add, ":grievance_2", 3),
            (val_sub, ":cohesion_1", 3),
            (val_sub, ":cohesion_2", 3),
          (try_end),

          (try_begin),
            (gt, ":pair_bias", 0),
            (val_add, ":grievance_1", ":pair_bias"),
            (val_add, ":grievance_2", ":pair_bias"),
            (val_sub, ":cohesion_1", 1),
            (val_sub, ":cohesion_2", 1),
            (val_add, "$g_companion_recent_resentment", ":pair_bias"),
            (try_begin),
              (ge, ":pair_bias", 3),
              (val_add, "$g_companion_clash_chain", 1),
            (try_end),
          (else_try),
            (lt, ":pair_bias", 0),
            (val_sub, ":grievance_1", 1),
            (val_sub, ":grievance_2", 1),
            (val_add, ":cohesion_1", 1),
            (val_add, ":cohesion_2", 1),
            (val_sub, "$g_companion_recent_resentment", 1),
          (try_end),

          (try_begin),
            (gt, ":clash_state", 0),
            (assign, "$g_companion_banter_last_pair_a", ":companion_1"),
            (assign, "$g_companion_banter_last_pair_b", ":companion_2"),
            (assign, "$g_companion_banter_last_context", 3),
          (try_end),

          (try_begin),
            (lt, ":pair_bias", 0),
            (ge, ":cohesion_1", 70),
            (ge, ":cohesion_2", 70),
            (val_add, ":cohesion_1", 1),
            (val_add, ":cohesion_2", 1),
          (try_end),

          (val_clamp, ":cohesion_1", 0, 100),
          (val_clamp, ":cohesion_2", 0, 100),
          (val_clamp, ":grievance_1", 0, 100),
          (val_clamp, ":grievance_2", 0, 100),
          (val_clamp, "$g_companion_recent_resentment", 0, 100),
          (val_clamp, "$g_companion_clash_chain", 0, 5),

          (troop_set_slot, ":companion_1", slot_troop_personalityclash_penalties, ":grievance_1"),
          (troop_set_slot, ":companion_2", slot_troop_personalityclash_penalties, ":grievance_2"),
          (troop_set_slot, ":companion_1", slot_troop_companion_cohesion, ":cohesion_1"),
          (troop_set_slot, ":companion_2", slot_troop_companion_cohesion, ":cohesion_2"),
      ]),
]
