SCRIPTS = [
("troop_get_banner_mesh",[
        (store_script_param_1, ":troop_no"),
        (assign, ":banner_mesh" , "mesh_banners_default_a"),
        (try_begin),
#            (eq, ":troop_no", 0),
#            (assign, ":banner_mesh", "mesh_banners_default_a"),
#        (else_try),
            (ge, ":troop_no", 0),
            (try_begin),
                (troop_slot_ge, ":troop_no", slot_troop_banner_scene_prop, 1),
                (troop_get_slot, ":banner_spr", ":troop_no", slot_troop_banner_scene_prop),
                (store_add, ":banner_scene_props_end", banner_scene_props_end_minus_one, 1),
                (is_between, ":banner_spr", banner_scene_props_begin, ":banner_scene_props_end"),
                (val_sub, ":banner_spr", banner_scene_props_begin),
                (store_add, ":banner_mesh", ":banner_spr", arms_meshes_begin),
            (try_end),
        (else_try),
            (eq, ":troop_no", -1),
            (assign, ":banner_mesh", "mesh_banners_default_a"),
        (else_try),
            (eq, ":troop_no", -2),
            (assign, ":banner_mesh", "mesh_banners_default_b"),
        (else_try),
            (eq, ":troop_no", -3),
            (assign, ":banner_mesh", "mesh_banners_default_c"),
        (try_end),
        (assign, reg1, ":banner_mesh"),
    ]),
]
