SCRIPTS = [
("update_companion_candidates_in_taverns",
      [  (try_for_range, ":troop_no", companions_begin, companions_end),
          (troop_set_slot, ":troop_no", slot_troop_cur_center, -1),
          (troop_slot_eq, ":troop_no", slot_troop_occupation, 0),
          (store_random_in_range, ":town_no", towns_begin, towns_end),
          (try_begin),
            (neg|troop_slot_eq, ":troop_no", slot_troop_home, ":town_no"),
            (neg|troop_slot_eq, ":troop_no", slot_troop_first_encountered, ":town_no"),
            (troop_set_slot, ":troop_no", slot_troop_cur_center, ":town_no"),
            (try_begin),
              (eq, "$cheat_mode", 1),
              (call_script, "script_store_troop_name_link", 4, ":troop_no"),
              (str_store_party_name_link, 5, ":town_no"),
              (display_message, "@{s4} is in {s5}", debug_color),
            (try_end),
          (try_end),
        (try_end),
    ]),
]
