SCRIPTS = [
("update_troop_location_notes",
      [(store_script_param, ":troop_no", 1),
        (store_script_param, ":see_or_hear", 2),
        (call_script, "script_get_information_about_troops_position", ":troop_no", 1),
        (try_begin),
          (neq, reg0, 0),
          (troop_get_type, reg1, ":troop_no"),
          (try_begin),
			(troop_slot_eq, ":troop_no", slot_troop_occupation, slto_dead),
			(add_troop_note_from_sreg, ":troop_no", 2, "@{reg1?She:He} is dead.", 1),
		  (else_try),
            (eq, ":see_or_hear", 0),
            (add_troop_note_from_sreg, ":troop_no", 2, "@The last time you saw {reg1?her:him}, {s1}", 1),
          (else_try),
            (add_troop_note_from_sreg, ":troop_no", 2, "@The last time you heard about {reg1?her:him}, {s1}", 1),
          (try_end),
        (try_end),
    ]),
]
