MENUS = [
("black_army_security_report", mnf_enable_hot_keys,
    "{s1}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),
      (call_script, "script_sod_black_army_describe_status_to_s24"),
      (store_current_day, ":cur_day"),
      (store_sub, ":days_since_payment", ":cur_day", "$g_sod_black_army_last_report_contract_day"),
      (store_sub, reg10, 7, ":days_since_payment"),
      (val_max, reg10, 0),
      (try_begin),
        (lt, "$g_sod_black_army_last_report_contract_day", 1),
        (assign, reg10, 0),
      (try_end),
      (call_script, "script_sod_mini_faction_describe_recent_incident_to_s28", sod_mini_faction_incident_black_army_contract),
      (call_script, "script_sod_mini_faction_describe_recent_countermeasure_to_s30", 7),
      (faction_get_slot, ":contract_heat", "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
      (call_script, "script_sod_mini_faction_describe_recommendation_to_s32", 7, ":contract_heat"),
      (str_store_string, s1, "@Black Army Contract Security^^{s24}{s28}{s30}{s32}^^Report actions share one 7-day contract cooldown.^Security contract costs 500 denars. Cooldown remaining: {reg10} days.^Road interdiction costs 800 denars and pushes Black Army patrols against Slaver, Boar, and Black Khergit road pressure.^^Field notes:^Black Army patrols and contract columns sell order. Security contracts improve their fund and relation with you; attacking them raises contract heat. Their patrols can move against Slaver and Boar Clan road predators when nearby."),
    ],
    [
      ("black_army_security_report_pay", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 500),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_payment", ":cur_day", "$g_sod_black_army_last_report_contract_day"),
          (this_or_next|ge, ":days_since_payment", 7),
          (lt, "$g_sod_black_army_last_report_contract_day", 1),
        ], "Fund a 500 denar security contract.",
        [
          (call_script, "script_sod_player_charge_gold", 500),
          (store_current_day, ":cur_day"),
          (assign, "$g_sod_black_army_last_report_contract_day", ":cur_day"),
          (call_script, "script_sod_black_army_apply_player_action", sod_black_army_action_security_contract, 500),
          (call_script, "script_sod_mini_faction_apply_report_counterplay", 7, 4),
          (display_message, "@The Black Army expands road-security work under your contract.", 0x444444),
          (jump_to_menu, "mnu_black_army_security_report"),
        ]),
      ("black_army_security_report_pay_cooldown", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 500),
          (ge, "$g_sod_black_army_last_report_contract_day", 1),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_payment", ":cur_day", "$g_sod_black_army_last_report_contract_day"),
          (lt, ":days_since_payment", 7),
        ], "Security contract unavailable: the shared report contract is still active.",
        [
          (display_message, "@The Black Army is still fulfilling your current report contract."),
          (jump_to_menu, "mnu_black_army_security_report"),
        ]),
      ("black_army_security_report_pay_no_gold", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (lt, ":player_gold", 500),
        ], "Security contract unavailable: you need 500 denars.",
        [
          (display_message, "@You need 500 denars to fund a Black Army security contract."),
          (jump_to_menu, "mnu_black_army_security_report"),
        ]),
      ("black_army_security_report_interdict", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 800),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_payment", ":cur_day", "$g_sod_black_army_last_report_contract_day"),
          (this_or_next|ge, ":days_since_payment", 7),
          (lt, "$g_sod_black_army_last_report_contract_day", 1),
        ], "Fund 800 denars of road-threat interdiction.",
        [
          (call_script, "script_sod_player_charge_gold", 800),
          (store_current_day, ":cur_day"),
          (assign, "$g_sod_black_army_last_report_contract_day", ":cur_day"),
          (call_script, "script_sod_black_army_apply_player_action", sod_black_army_action_interdict_road_threats, 800),
          (call_script, "script_sod_mini_faction_apply_report_counterplay", 7, 8),
          (display_message, "@Black Army captains take your writ and move against road predators.", 0x444444),
          (jump_to_menu, "mnu_black_army_security_report"),
        ]),
      ("black_army_security_report_interdict_no_gold", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_payment", ":cur_day", "$g_sod_black_army_last_report_contract_day"),
          (this_or_next|ge, ":days_since_payment", 7),
          (lt, "$g_sod_black_army_last_report_contract_day", 1),
          (lt, ":player_gold", 800),
        ], "Road-threat interdiction unavailable: you need 800 denars.",
        [
          (display_message, "@You need 800 denars to fund Black Army road-threat interdiction."),
          (jump_to_menu, "mnu_black_army_security_report"),
        ]),
      ("black_army_security_report_overview", [], "Back to mini-faction overview.", [(jump_to_menu, "mnu_mercenary_world_activity_report")]),
      ("black_army_security_report_back", [], "Back to reports.", [(jump_to_menu, "mnu_reports")]),
    ]
  ),
]
