MENUS = [
("elephant_guard_warden_report", mnf_enable_hot_keys,
    "{s1}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),
      (call_script, "script_sod_elephant_guard_describe_status_to_s21"),
      (faction_get_slot, ":devotion", "fac_sod_merc_guild3", slot_faction_elephant_guard_devotion),
      (faction_get_slot, ":supplies", "fac_sod_merc_guild3", slot_faction_elephant_guard_supplies),
      (faction_get_slot, ":omens", "fac_sod_merc_guild3", slot_faction_elephant_guard_omens),
      (faction_get_slot, ":active_parties", "fac_sod_merc_guild3", slot_faction_elephant_guard_active_parties),
      (faction_get_slot, ":slaver_alarm", "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),
      (faction_get_slot, ":target_center", "fac_sod_merc_guild3", slot_faction_elephant_guard_target_center),
      (str_store_string, s2, "@no current focus"),
      (try_begin),
        (gt, ":target_center", 0),
        (str_store_party_name, s2, ":target_center"),
      (try_end),
      (store_num_parties_of_template, ":sanctuary_patrols", "pt_elephant_guard_sanctuary_patrol"),
      (store_num_parties_of_template, ":relic_processions", "pt_elephant_guard_relic_procession"),
      (store_num_parties_of_template, ":slaver_transports", "pt_slavers_caravan"),
      (store_relation, ":standing", "fac_player_supporters_faction", "fac_sod_merc_guild3"),
      (str_store_string, s3, "@no formal standing"),
      (try_begin),
        (ge, ":standing", 20),
        (str_store_string, s3, "@trusted"),
      (else_try),
        (ge, ":standing", 5),
        (str_store_string, s3, "@friendly"),
      (else_try),
        (le, ":standing", -20),
        (str_store_string, s3, "@hostile"),
      (else_try),
        (le, ":standing", -5),
        (str_store_string, s3, "@wary"),
      (try_end),
      (try_begin),
        (lt, ":devotion", 35),
        (str_store_string, s4, "@devotion is quiet"),
      (else_try),
        (lt, ":devotion", 70),
        (str_store_string, s4, "@devotion is steady"),
      (else_try),
        (str_store_string, s4, "@devotion is fervent"),
      (try_end),
      (try_begin),
        (lt, ":supplies", 35),
        (str_store_string, s5, "@relief stores are thin"),
      (else_try),
        (lt, ":supplies", 70),
        (str_store_string, s5, "@relief stores can answer ordinary need"),
      (else_try),
        (str_store_string, s5, "@relief stores are strong enough for wider sanctuary work"),
      (try_end),
      (try_begin),
        (lt, ":omens", 35),
        (str_store_string, s6, "@omens are quiet"),
      (else_try),
        (lt, ":omens", 70),
        (str_store_string, s6, "@omens are being watched"),
      (else_try),
        (str_store_string, s6, "@omens are driving the wardens onto the roads"),
      (try_end),
      (try_begin),
        (lt, ":slaver_alarm", 35),
        (str_store_string, s7, "@Slaver alarm is low"),
      (else_try),
        (lt, ":slaver_alarm", 70),
        (str_store_string, s7, "@Slaver alarm is active"),
      (else_try),
        (str_store_string, s7, "@Slaver alarm is urgent"),
      (try_end),
      (try_begin),
        (le, ":active_parties", 0),
        (str_store_string, s8, "@no active rites are visible"),
      (else_try),
        (le, ":active_parties", 2),
        (str_store_string, s8, "@a few active rites are visible"),
      (else_try),
        (str_store_string, s8, "@active rites are common enough to shape the roads"),
      (try_end),
      (try_begin),
        (le, ":sanctuary_patrols", 0),
        (str_store_string, s9, "@sanctuary patrols are scarce"),
      (else_try),
        (le, ":relic_processions", 0),
        (str_store_string, s9, "@sanctuary patrols move without many processions"),
      (else_try),
        (str_store_string, s9, "@sanctuary patrols and relic processions are both moving"),
      (try_end),
      (try_begin),
        (le, ":slaver_transports", 0),
        (str_store_string, s11, "@No Slaver transports are confirmed by warden scouts."),
      (else_try),
        (le, ":slaver_transports", 2),
        (str_store_string, s11, "@Warden scouts report a few Slaver transports."),
      (else_try),
        (str_store_string, s11, "@Warden scouts report persistent Slaver transport movement."),
      (try_end),
      (store_current_day, ":cur_day"),
      (store_sub, ":days_since_donation", ":cur_day", "$g_sod_elephant_guard_last_report_donation_day"),
      (store_sub, reg10, 7, ":days_since_donation"),
      (val_max, reg10, 0),
      (try_begin),
        (lt, "$g_sod_elephant_guard_last_report_donation_day", 1),
        (assign, reg10, 0),
      (try_end),
      (call_script, "script_sod_mini_faction_describe_recent_incident_to_s28", sod_mini_faction_incident_elephant_alarm),
      (call_script, "script_sod_mini_faction_describe_recent_countermeasure_to_s30", 3),
      (call_script, "script_sod_mini_faction_describe_recommendation_to_s32", 3, ":slaver_alarm"),
      (str_store_string, s1, "@Elephant Guard Sacred Wardens^^Rites: {s4}; {s5}; {s6}.^Road alarm: {s7}.^Active rites: {s8}; {s9}.^Current focus: {s2}.^Your standing: {s3}.^^{s11}^^{s21}{s28}{s30}{s32}^^Report action:^Relief support costs 500 denars. Cooldown remaining: {reg10} days. Strong relief support lowers Slaver alarm and chips away at black-market supply.^^Field notes:^High omens or Slaver alarm push the Guard toward sanctuary patrols. Strong supplies allow relic processions and settlement aid. Honorable captains can receive blessings or shrine-road volunteers from active road parties, but carrying slaves blocks those favors."),
      (str_clear, s3),
    ],
    [
      ("elephant_guard_warden_report_donate", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 500),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_donation", ":cur_day", "$g_sod_elephant_guard_last_report_donation_day"),
          (this_or_next|ge, ":days_since_donation", 7),
          (lt, "$g_sod_elephant_guard_last_report_donation_day", 1),
        ], "Send 500 denars to Elephant Guard relief stores.",
        [
          (call_script, "script_sod_player_charge_gold", 500),
          (store_current_day, ":cur_day"),
          (assign, "$g_sod_elephant_guard_last_report_donation_day", ":cur_day"),
          (call_script, "script_sod_elephant_guard_apply_player_support", 3),
          (call_script, "script_sod_mini_faction_apply_report_counterplay", 3, 6),
          (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_elephant_guard_support, 3),
          (display_message, "@Your donation reaches Elephant Guard relief stores. Their supplies and devotion improve.", 0x8B4513),
          (jump_to_menu, "mnu_elephant_guard_warden_report"),
        ]),
      ("elephant_guard_warden_report_donate_cooldown", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 500),
          (ge, "$g_sod_elephant_guard_last_report_donation_day", 1),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_donation", ":cur_day", "$g_sod_elephant_guard_last_report_donation_day"),
          (lt, ":days_since_donation", 7),
        ], "Relief support unavailable: wardens are still moving supplies.",
        [
          (display_message, "@Elephant Guard wardens are still moving the last relief stores."),
          (jump_to_menu, "mnu_elephant_guard_warden_report"),
        ]),
      ("elephant_guard_warden_report_donate_no_gold", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (lt, ":player_gold", 500),
        ], "Relief support unavailable: you need 500 denars.",
        [
          (display_message, "@You need 500 denars to fund Elephant Guard relief stores."),
          (jump_to_menu, "mnu_elephant_guard_warden_report"),
        ]),

      ("elephant_guard_warden_report_overview", [], "Back to mini-faction overview.",
        [
          (jump_to_menu, "mnu_mercenary_world_activity_report"),
        ]),

      ("elephant_guard_warden_report_back", [], "Back to reports.",
        [
          (jump_to_menu, "mnu_reports"),
        ]),
    ]
  ),
]
