MENUS = [
("invasion_status_report", mnf_enable_hot_keys,
    "{s1}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),
      (store_current_day, ":cur_day"),
      (try_begin),
        (faction_slot_eq, "fac_kingdom_6", slot_faction_state, sfs_active),
        (call_script, "script_sod_imperial_expedition_describe_status_to_s28"),
        (faction_get_slot, ":front_center", "fac_kingdom_6", slot_faction_central_center),
        (str_store_party_name, s32, ":front_center"),
        (faction_get_slot, ":imperial_armies", "fac_kingdom_6", slot_faction_num_armies),
        (faction_get_slot, ":imperial_towns", "fac_kingdom_6", slot_faction_num_towns),
        (faction_get_slot, ":imperial_castles", "fac_kingdom_6", slot_faction_num_castles),
        (faction_get_slot, ":imperial_power", "fac_kingdom_6", slot_faction_current_power),
        (assign, reg5, 0),
        (try_for_range, ":kingdom_no", kingdoms_begin, kingdoms_end),
          (neq, ":kingdom_no", "fac_kingdom_6"),
          (faction_slot_eq, ":kingdom_no", slot_faction_state, sfs_active),
          (store_relation, ":relation", ":kingdom_no", "fac_kingdom_6"),
          (lt, ":relation", 0),
          (val_add, reg5, 1),
        (try_end),
        (try_begin),
          (faction_slot_eq, "fac_player_supporters_faction", slot_faction_state, sfs_active),
          (store_relation, ":player_legion_relation", "fac_player_supporters_faction", "fac_kingdom_6"),
        (else_try),
          (assign, ":player_legion_relation", 0),
        (try_end),
        (try_begin),
          (le, ":imperial_armies", 2),
          (str_store_string, s34, "@a hard vanguard"),
        (else_try),
          (le, ":imperial_armies", 5),
          (str_store_string, s34, "@several disciplined columns"),
        (else_try),
          (str_store_string, s34, "@many marching columns"),
        (try_end),
        (try_begin),
          (le, ":imperial_towns", 0),
          (str_store_string, s35, "@no secure towns"),
        (else_try),
          (le, ":imperial_towns", 2),
          (str_store_string, s35, "@a narrow town foothold"),
        (else_try),
          (str_store_string, s35, "@a dangerous town network"),
        (try_end),
        (try_begin),
          (le, ":imperial_castles", 0),
          (str_store_string, s36, "@few fixed strongpoints"),
        (else_try),
          (le, ":imperial_castles", 3),
          (str_store_string, s36, "@several strongpoints"),
        (else_try),
          (str_store_string, s36, "@deep fortified support"),
        (try_end),
        (try_begin),
          (lt, ":imperial_power", 4000),
          (str_store_string, s37, "@dangerous but still containable"),
        (else_try),
          (lt, ":imperial_power", 9000),
          (str_store_string, s37, "@a severe strategic threat"),
        (else_try),
          (str_store_string, s37, "@an existential threat if left unchecked"),
        (try_end),
        (try_begin),
          (lt, ":player_legion_relation", 0),
          (str_store_string, s38, "@your realm is already counted among their enemies"),
        (else_try),
          (str_store_string, s38, "@your realm is not yet openly committed against them"),
        (try_end),
        (try_begin),
          (gt, reg5, 0),
          (str_store_string, s39, "@several realms have answered"),
        (else_try),
          (str_store_string, s39, "@too few realms have answered"),
        (try_end),
        (str_store_string, s1, "@Imperial Invasion Status^^Front: {s32}^Imperial field strength: {s34}.^Foothold: {s35}; {s36}.^Strategic danger: {s37}.^Calradian war response: {s39}. {s38}.{s28}^^Strategic read:^Hold border garrisons near the front, keep mobile reserves ready to intercept centurions, sabotage supply cohesion, and exploit any alliance pressure against the Legion."),
      (else_try),
        (store_sub, reg1, "$g_sod_invasion_begin", ":cur_day"),
        (val_max, reg1, 0),
        (assign, reg2, "$g_sod_imperial_delay_total"),
        (store_sub, reg3, 90, "$g_sod_imperial_delay_total"),
        (val_max, reg3, 0),
        (store_sub, ":days_since_delay", ":cur_day", "$g_sod_imperial_last_delay_day"),
        (store_sub, reg4, 20, ":days_since_delay"),
        (val_max, reg4, 0),
        (try_begin),
          (lt, "$g_sod_imperial_last_delay_day", 1),
          (assign, reg4, 0),
        (try_end),
        (call_script, "script_sod_imperial_expedition_calculate_anti_legion_coalition"),
        (assign, reg7, reg0),
        (assign, reg8, reg1),
        (assign, reg9, reg2),
        (str_store_string, s33, "@not ready"),
        (try_begin),
          (ge, reg7, 30),
          (str_store_string, s33, "@ready"),
        (try_end),
        (try_begin),
          (le, reg1, 20),
          (str_store_string, s34, "@very soon"),
        (else_try),
          (le, reg1, 60),
          (str_store_string, s34, "@within a season"),
        (else_try),
          (str_store_string, s34, "@not immediate, but no longer distant"),
        (try_end),
        (try_begin),
          (ge, reg7, 30),
          (str_store_string, s35, "@ready"),
        (else_try),
          (ge, reg7, 18),
          (str_store_string, s35, "@nearly ready"),
        (else_try),
          (str_store_string, s35, "@not ready"),
        (try_end),
        (try_begin),
          (le, reg2, 0),
          (str_store_string, s36, "@Counter-intelligence has not bought meaningful time yet"),
        (else_try),
          (le, reg2, 30),
          (str_store_string, s36, "@Counter-intelligence has bought some useful time"),
        (else_try),
          (str_store_string, s36, "@Counter-intelligence has bought a meaningful delay"),
        (try_end),
        (try_begin),
          (le, reg3, 0),
          (str_store_string, s37, "@no further delay window remains"),
        (else_try),
          (le, reg3, 30),
          (str_store_string, s37, "@only a narrow delay window remains"),
        (else_try),
          (str_store_string, s37, "@there is still room to mislead the Legion"),
        (try_end),
        (str_store_string, s1, "@Imperial Invasion Status^^The Legion has not yet entered Calradia.^Estimated arrival: {s34}.^{s36}; {s37}.^Next delay operation available in: {reg4} days.^^Anti-Legion coalition: {s35}. Friendly realms and Trusted mini-factions are the backbone of the network.^^Strategic read:^Build reserves, improve border fiefs, secure mercenary relations, and prepare a fast field army before the first Imperial armies arrive. Repeated counter-intelligence can push the invasion back, but it now requires allies: friendly kingdoms, Trusted mini-factions, and a player realm capable of hosting the network."),
      (try_end),
    ],
    [
      ("delay_imperial_invasion", [
          (neg|faction_slot_eq, "fac_kingdom_6", slot_faction_state, sfs_active),
          (store_current_day, ":cur_day"),
          (lt, ":cur_day", "$g_sod_invasion_begin"),
          (lt, "$g_sod_imperial_delay_total", 90),
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 2500),
          (call_script, "script_sod_imperial_expedition_calculate_anti_legion_coalition"),
          (ge, reg0, 30),
          (store_sub, ":days_since_delay", ":cur_day", "$g_sod_imperial_last_delay_day"),
          (this_or_next|ge, ":days_since_delay", 20),
          (lt, "$g_sod_imperial_last_delay_day", 1),
        ], "Spend 2500 denars and coalition favors to delay the invasion.",
        [
          (call_script, "script_sod_player_charge_gold", 2500),
          (store_current_day, ":cur_day"),
          (assign, "$g_sod_imperial_last_delay_day", ":cur_day"),
          (call_script, "script_sod_imperial_expedition_apply_player_action", sod_imperial_expedition_action_delay_invasion, 2500),
          (try_begin),
            (gt, reg0, 0),
            (try_begin),
              (le, reg0, 3),
              (str_store_string, s1, "@a small delay"),
            (else_try),
              (le, reg0, 10),
              (str_store_string, s1, "@a useful delay"),
            (else_try),
              (str_store_string, s1, "@a serious delay"),
            (try_end),
            (display_message, "@Allied agents burn courier routes, mislead frontier guides, and buy silence in Imperial ports. The operation buys {s1}.", 0x99CCFF),
            (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_scout_warning, 1),
          (else_try),
            (display_message, "@The Imperial timetable can no longer be delayed by quiet work.", 0xAA7777),
          (try_end),
          (jump_to_menu, "mnu_invasion_status_report"),
        ]),
      ("delay_imperial_invasion_needs_allies", [
          (neg|faction_slot_eq, "fac_kingdom_6", slot_faction_state, sfs_active),
          (store_current_day, ":cur_day"),
          (lt, ":cur_day", "$g_sod_invasion_begin"),
          (lt, "$g_sod_imperial_delay_total", 90),
          (call_script, "script_sod_imperial_expedition_calculate_anti_legion_coalition"),
          (lt, reg0, 30),
        ], "Delay operation unavailable: build an anti-Legion coalition first.",
        [
          (display_message, "@Counter-intelligence this large needs allies: friendly realms, Trusted mini-factions, and a player realm to host the network.", 0xAA7777),
          (jump_to_menu, "mnu_invasion_status_report"),
        ]),
      ("delay_imperial_invasion_no_gold", [
          (neg|faction_slot_eq, "fac_kingdom_6", slot_faction_state, sfs_active),
          (store_current_day, ":cur_day"),
          (lt, ":cur_day", "$g_sod_invasion_begin"),
          (lt, "$g_sod_imperial_delay_total", 90),
          (call_script, "script_sod_imperial_expedition_calculate_anti_legion_coalition"),
          (ge, reg0, 30),
          (store_troop_gold, ":player_gold", "trp_player"),
          (lt, ":player_gold", 2500),
        ], "Delay operation unavailable: you need 2500 denars.",
        [
          (display_message, "@You need 2500 denars to fund a coalition counter-intelligence operation.", 0xAA7777),
          (jump_to_menu, "mnu_invasion_status_report"),
        ]),
      ("sabotage_imperial_supply", [
          (faction_slot_eq, "fac_kingdom_6", slot_faction_state, sfs_active),
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 1000),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_sabotage", ":cur_day", "$g_sod_imperial_last_sabotage_day"),
          (this_or_next|ge, ":days_since_sabotage", 10),
          (lt, "$g_sod_imperial_last_sabotage_day", 1),
        ], "Spend 1000 denars to sabotage Imperial supply lines.",
        [
          (call_script, "script_sod_player_charge_gold", 1000),
          (store_current_day, ":cur_day"),
          (assign, "$g_sod_imperial_last_sabotage_day", ":cur_day"),
          (call_script, "script_sod_imperial_expedition_apply_player_action", sod_imperial_expedition_action_sabotage_supply, 1000),
          (display_message, "@Your agents disrupt Imperial depots and courier routes.", 0x222222),
          (jump_to_menu, "mnu_invasion_status_report"),
        ]),
      ("continue", [], "Continue.", [(jump_to_menu, "mnu_reports")]),
    ]
  ),
]
