MENUS = [
("jotnar_hearth_report", mnf_enable_hot_keys,
    "{s1}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),
      (call_script, "script_sod_jotnar_describe_status_to_s22"),
      (faction_get_slot, ":hearth_pressure", "fac_sod_merc_guild4", slot_faction_jotnar_hearth_pressure),
      (faction_get_slot, ":slaver_pressure", "fac_sod_merc_guild4", slot_faction_jotnar_slaver_pressure),
      (faction_get_slot, ":active_parties", "fac_sod_merc_guild4", slot_faction_jotnar_active_parties),
      (faction_get_slot, ":target_center", "fac_sod_merc_guild4", slot_faction_jotnar_target_center),
      (str_store_string, s2, "@no current hearth focus"),
      (try_begin),
        (gt, ":target_center", 0),
        (str_store_party_name, s2, ":target_center"),
      (try_end),
      (store_num_parties_of_template, ":hearth_guards", "pt_jotnar_hearth_guard"),
      (store_num_parties_of_template, ":wintering_camps", "pt_jotnar_wintering_camp"),
      (store_num_parties_of_template, ":slaver_transports", "pt_slavers_caravan"),
      (store_relation, ":standing", "fac_player_supporters_faction", "fac_sod_merc_guild4"),
      (str_store_string, s3, "@no formal standing"),
      (try_begin),
        (ge, ":standing", 20),
        (str_store_string, s3, "@trusted"),
      (else_try),
        (ge, ":standing", 5),
        (str_store_string, s3, "@friendly"),
      (else_try),
        (le, ":standing", -20),
        (str_store_string, s3, "@hostile"),
      (else_try),
        (le, ":standing", -5),
        (str_store_string, s3, "@wary"),
      (try_end),
      (try_begin),
        (lt, ":hearth_pressure", 35),
        (str_store_string, s4, "@quiet"),
      (else_try),
        (lt, ":hearth_pressure", 65),
        (str_store_string, s4, "@strained"),
      (else_try),
        (str_store_string, s4, "@dangerously stretched"),
      (try_end),
      (try_begin),
        (lt, ":slaver_pressure", 35),
        (str_store_string, s5, "@distant"),
      (else_try),
        (lt, ":slaver_pressure", 65),
        (str_store_string, s5, "@near enough to worry the kin-shelters"),
      (else_try),
        (str_store_string, s5, "@hunting close to the hearth roads"),
      (try_end),
      (try_begin),
        (le, ":active_parties", 0),
        (str_store_string, s6, "@no visible hearth parties"),
      (else_try),
        (le, ":active_parties", 2),
        (str_store_string, s6, "@a few hearth parties"),
      (else_try),
        (str_store_string, s6, "@many hearth parties"),
      (try_end),
      (try_begin),
        (le, ":hearth_guards", 0),
        (str_store_string, s7, "@few guards are seen"),
      (else_try),
        (le, ":wintering_camps", 0),
        (str_store_string, s7, "@guards are moving without settled camps"),
      (else_try),
        (str_store_string, s7, "@guards and wintering camps are both visible"),
      (try_end),
      (try_begin),
        (le, ":slaver_transports", 0),
        (str_store_string, s8, "@No Slaver transports are confirmed nearby."),
      (else_try),
        (le, ":slaver_transports", 2),
        (str_store_string, s8, "@A few Slaver transports are being watched."),
      (else_try),
        (str_store_string, s8, "@Slaver transports are moving often enough to trouble the hearth."),
      (try_end),
      (store_current_day, ":cur_day"),
      (store_sub, ":days_since_donation", ":cur_day", "$g_sod_jotnar_last_report_donation_day"),
      (store_sub, reg10, 7, ":days_since_donation"),
      (val_max, reg10, 0),
      (try_begin),
        (lt, "$g_sod_jotnar_last_report_donation_day", 1),
        (assign, reg10, 0),
      (try_end),
      (call_script, "script_sod_mini_faction_describe_recent_incident_to_s28", sod_mini_faction_incident_jotnar_hearth),
      (call_script, "script_sod_mini_faction_describe_recent_countermeasure_to_s30", 2),
      (call_script, "script_sod_mini_faction_describe_recommendation_to_s32", 2, ":hearth_pressure"),
      (str_store_string, s1, "@Jotnar Hearthbound Kin^^Hearth pressure: {s4}.^Slaver kin-threat: {s5}.^Hearth parties: {s6}; {s7}.^Current village focus: {s2}.^Your standing: {s3}.^^{s8}^^{s22}{s28}{s30}{s32}^^Report action:^Hearth support costs 400 denars. Cooldown remaining: {reg10} days. This support also weakens Slaver supply and demand when clan kin-rescue pressure is active.^^Field notes:^Jotnar hearth guards and wintering camps support weak villages, preserve scattered families, and watch slave roads for lost kin. Supporting the hearth lowers pressure and improves clan standing. Carrying or buying slaves damages your reputation with the clan."),
      (str_clear, s3),
    ],
    [
      ("jotnar_hearth_report_donate", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 400),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_donation", ":cur_day", "$g_sod_jotnar_last_report_donation_day"),
          (this_or_next|ge, ":days_since_donation", 7),
          (lt, "$g_sod_jotnar_last_report_donation_day", 1),
        ], "Send 400 denars to Jotnar hearth stores.",
        [
          (call_script, "script_sod_player_charge_gold", 400),
          (store_current_day, ":cur_day"),
          (assign, "$g_sod_jotnar_last_report_donation_day", ":cur_day"),
          (call_script, "script_sod_jotnar_apply_player_support", 3),
          (call_script, "script_sod_mini_faction_apply_report_counterplay", 2, 6),
          (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_jotnar_support, 3),
          (display_message, "@Your gift reaches Jotnar hearth stores. Clan pressure eases.", 0x99CCFF),
          (jump_to_menu, "mnu_jotnar_hearth_report"),
        ]),
      ("jotnar_hearth_report_donate_cooldown", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (ge, ":player_gold", 400),
          (ge, "$g_sod_jotnar_last_report_donation_day", 1),
          (store_current_day, ":cur_day"),
          (store_sub, ":days_since_donation", ":cur_day", "$g_sod_jotnar_last_report_donation_day"),
          (lt, ":days_since_donation", 7),
        ], "Hearth support unavailable: stores are already being distributed.",
        [
          (display_message, "@Jotnar hearth runners are still distributing your last support."),
          (jump_to_menu, "mnu_jotnar_hearth_report"),
        ]),
      ("jotnar_hearth_report_donate_no_gold", [
          (store_troop_gold, ":player_gold", "trp_player"),
          (lt, ":player_gold", 400),
        ], "Hearth support unavailable: you need 400 denars.",
        [
          (display_message, "@You need 400 denars to support Jotnar hearth stores."),
          (jump_to_menu, "mnu_jotnar_hearth_report"),
        ]),

      ("jotnar_hearth_report_overview", [], "Back to mini-faction overview.",
        [
          (jump_to_menu, "mnu_mercenary_world_activity_report"),
        ]),

      ("jotnar_hearth_report_back", [], "Back to reports.",
        [
          (jump_to_menu, "mnu_reports"),
        ]),
    ]
  ),
]
