MENUS = [
("trade_network_report", mnf_enable_hot_keys,
    "{s1}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),
      (call_script, "script_sod_trade_network_describe_report_to_s20"),
      (str_store_string, s1, "@{s20}"),
    ],
    [
      ("trade_network_fund_patrols",
       [(store_troop_gold, ":gold", "trp_player"), (ge, ":gold", 1200)],
       "Fund road patrols. (1200 denars)",
       [(call_script, "script_sod_trade_network_apply_strategy_action", 1), (jump_to_menu, "mnu_trade_network_report")]),
      ("trade_network_suppress_tolls",
       [(store_troop_gold, ":gold", "trp_player"), (ge, ":gold", 900)],
       "Challenge Boar toll pressure. (900 denars)",
       [(call_script, "script_sod_trade_network_apply_strategy_action", 2), (jump_to_menu, "mnu_trade_network_report")]),
      ("trade_network_subsidize_relief",
       [(store_troop_gold, ":gold", "trp_player"), (ge, ":gold", 1000), (is_between, "$g_sod_trade_network_last_result_center", centers_begin, centers_end)],
       "Subsidize relief to the last known needy market. (1000 denars)",
       [(call_script, "script_sod_trade_network_apply_strategy_action", 3), (jump_to_menu, "mnu_trade_network_report")]),
      ("trade_network_repeat_route",
       [(store_troop_gold, ":gold", "trp_player"), (ge, ":gold", 800), (gt, "$g_sod_trade_network_last_result_party", 0)],
       "Invest in the familiar caravan route. (800 denars)",
       [(call_script, "script_sod_trade_network_apply_strategy_action", 4), (jump_to_menu, "mnu_trade_network_report")]),
      ("trade_network_report_back", [], "Back to reports.", [(jump_to_menu, "mnu_reports")]),
    ]
  ),
]
