DIALOGS = [
[anyone, "gm_mission_fight_troops_accepted", [
  (quest_get_slot, ":message_text", "$random_quest_no", slot_quest_r1),
  (str_store_string, s15, ":message_text"),
  (assign, "$fight_guild_troops_quest", "$random_quest_no"),
  ], "{s15}", "close_window",
   [
   (try_begin),
		(eq, "$fight_guild_troops_quest", "qst_black_army_fight_guild_troops"),
		(assign, ":fgtq_mt", "mt_fgtq_inf"),
		(assign, ":fgtq_scene", "scn_fgtq_ba_s1"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(set_visitor, 1, "trp_black_army_fresh_blade"),
		(set_visitor, 2, "trp_black_army_fresh_blade"),
		(set_visitor, 3, "trp_black_army_fresh_blade"),
		(set_visitor, 4, "trp_black_army_fresh_blade"),
		(set_visitor, 5, "trp_black_army_line_supporter"),
		(set_visitor, 6, "trp_black_army_line_supporter"),
		(set_visitor, 10, "trp_black_army_fresh_blade"),
		(set_visitor, 11, "trp_black_army_fresh_blade"),
		(set_visitor, 12, "trp_black_army_fresh_blade"),
		(set_visitor, 13, "trp_black_army_line_keeper"),
		(set_visitor, 14, "trp_black_army_line_keeper"),
		(set_visitor, 15, "trp_black_army_line_supporter"),
		(set_visitor, 16, "trp_black_army_line_supporter"),
	(else_try),
		(eq, "$fight_guild_troops_quest", "qst_conquistadors_fight_guild_troops"),
		(assign, ":fgtq_mt", "mt_fgtq_c_rodelero"),
		(assign, ":fgtq_scene", "scn_fgtq_c_s1"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(store_random_in_range, ":fgtq_team_size", 5, 10),
		(try_for_range, ":entry_p", 1, ":fgtq_team_size"),
			(set_visitor, ":entry_p", "trp_conquistador_rodelero"),
		(try_end),
		(val_add, ":fgtq_team_size", 10),
		(try_for_range, ":entry_p", 10, ":fgtq_team_size"),
			(set_visitor, ":entry_p", "trp_conquistador_seasoned_crossbowman"),
		(try_end),
	(else_try),
		(eq, "$fight_guild_troops_quest", "qst_elephant_guard_fight_guild_troops"),
		(assign, ":fgtq_mt", "mt_fgtq_inf"),
		(assign, ":fgtq_scene", "scn_fgtq_eg_s1"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(call_script, "script_fgtq_add_player_troops_to_scene", 7),
		(try_for_range, ":entry_p", 10, 14),
			(set_visitor, ":entry_p", "trp_elephant_guard_spearman"),
		(try_end),
		(try_for_range, ":entry_p", 14, 18),
			(set_visitor, ":entry_p", "trp_elephant_guard_penetrator"),
		(try_end),
	(else_try),
		(eq, "$fight_guild_troops_quest", "qst_jotnar_clan_fight_guild_troops"),
		(assign, ":fgtq_mt", "mt_fgtq_inf"),
		(assign, ":fgtq_scene", "scn_fgtq_jc_s1"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(call_script, "script_fgtq_add_player_troops_to_scene", 6),
		(try_for_range, ":entry_p", 10, 15),
			(set_visitor, ":entry_p", "trp_jotnar_clan_armsman"),
		(try_end),
		(set_visitor, 15, "trp_jotnar_clan_axe_thrower"),
		(set_visitor, 16, "trp_jotnar_clan_axe_thrower"),
	(else_try),
		(eq, "$fight_guild_troops_quest", "qst_serpent_host_fight_guild_troops"),
		(assign, ":fgtq_mt", "mt_fgtq_inf"),
		(assign, ":fgtq_scene", "scn_fgtq_sh_s1"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(call_script, "script_fgtq_add_player_troops_to_scene", 9),
		(try_for_range, ":entry_p", 10, 20),
			(set_visitor, ":entry_p", "trp_serpent_host_athanatoi"),
		(try_end),
	(else_try),
		(eq, "$fight_guild_troops_quest", "qst_serpent_host_fight_guild_troops_2"),
		(assign, ":fgtq_mt", "mt_fgtq_inf"),
		(assign, ":fgtq_scene", "scn_fgtq_sh_s3"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(set_visitor, 10, "trp_serpent_host_guild_master"),
	(else_try),
		(eq, "$fight_guild_troops_quest", "qst_slavers_fight_guild_troops"),
		(party_get_slot, ":fgtq_scene", "$g_encountered_party", slot_town_fgtq),
		(assign, ":fgtq_mt", "mt_fgtq_s_hunter"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(set_visitor, 1, "trp_slave_driver"),
		(set_visitor, 2, "trp_slave_driver"),
		(set_visitor, 3, "trp_henchman"),
		(set_visitor, 4, "trp_henchman"),
		(try_for_range, ":entry_p", 10, 18),
			(set_visitor, ":entry_p", "trp_slave"),
		(try_end),
		(set_visitor, 18, "trp_slave_female"),
		(set_visitor, 19, "trp_slave_female"),
	(else_try),
		(eq, "$fight_guild_troops_quest", "qst_bc_fight_guild_troops"),
		(assign, ":fgtq_mt", "mt_fgtq_bc_warrior"),
		(assign, ":fgtq_scene", "scn_fgtq_bc_s1"),
		(modify_visitors_at_site, ":fgtq_scene"),
		(reset_visitors),
		(try_for_range, ":entry_p", 1, 6),
			(set_visitor, ":entry_p", "trp_boar_clan_clansman"),
		(try_end),
		(try_for_range, ":entry_p", 6, 10),
			(set_visitor, ":entry_p", "trp_boar_clan_warrior"),
		(try_end),
		(try_for_range, ":entry_p", 10, 14),
			(set_visitor, ":entry_p", "trp_boar_clan_clansman"),
		(try_end),
		(try_for_range, ":entry_p", 14, 18),
			(set_visitor, ":entry_p", "trp_boar_clan_warrior"),
		(try_end),
		(set_visitor, 18, "trp_boar_clan_vet_warrior"),
		(set_visitor, 19, "trp_boar_clan_vet_warrior"),
    (try_end),
	(set_visitor, 0, "trp_player"),
    (set_jump_mission, ":fgtq_mt"),
    (jump_to_scene, ":fgtq_scene"),
	(change_screen_mission),
   ]],
]
