DIALOGS = [
[anyone|plyr, "gm_talk", [(store_partner_quest, "$g_gm_quest"),
												(eq, "$g_gm_quest", "qst_conquistadors_deliver_horses"),
                                                (quest_get_slot, ":quest_target_amount", "$g_gm_quest", slot_quest_target_amount),
												(quest_get_slot, ":quest_target_item", "$g_gm_quest", slot_quest_target_item),
                                                (call_script, "script_get_troop_item_amount", "trp_player", ":quest_target_item"),
                                                (assign, ":cur_amount", reg0),
												(try_begin),
													(eq, ":quest_target_item", "itm_saddle_horse"),
													(call_script, "script_get_troop_item_amount", "trp_player", "itm_rok_saddle_horse2"),
													(val_add, ":cur_amount", reg0),
												(else_try),
													(eq, ":quest_target_item", "itm_steppe_horse"),
													(call_script, "script_get_troop_item_amount", "trp_player", "itm_steppe_horse_b"),
													(val_add, ":cur_amount", reg0),
													(call_script, "script_get_troop_item_amount", "trp_player", "itm_steppe_horse_lv"),
													(val_add, ":cur_amount", reg0),
												(try_end),
												(ge, ":cur_amount", ":quest_target_amount"),
                                                (assign, reg5, ":quest_target_amount"),
												(store_sub, reg6, reg5, 1),
												(try_begin),
													(gt, reg5, 1),
													(str_store_item_name_plural, s13, ":quest_target_item"),
													(str_store_string, s14, "@I brought you {reg5} {s13} mounts."),
												(else_try),
													(str_store_item_name, s13, ":quest_target_item"),
													(str_store_string, s14, "@I brought you a {s13} mount."),
												(try_end),
                                                 ],
   "{s14}", "gm_deliver_horses_thank",
   []],
]
