DIALOGS = [
[anyone, "gm_deliver_grain_mission_accept", [], "Thank you, {playername}. We'll be praying for you night and day.", "close_window",
   [(assign, "$g_leave_encounter", 1),
    (call_script, "script_change_player_relation_with_faction", "$g_talk_troop_faction", 1),
	 (call_script, "script_store_troop_name_link", s9, "$g_talk_troop"),
	 (quest_get_slot, ":quest_target_item", "$random_quest_no", slot_quest_target_item),
     (quest_get_slot, reg5, "$random_quest_no", slot_quest_target_amount),
	 (store_sub, reg6, reg5, 1),
	 (call_script, "script_store_troop_name_link", s9, "$g_talk_troop"),
	 (setup_quest_text, "$random_quest_no"),
	 (str_store_item_name_plural, s13, ":quest_target_item"),
	 (try_begin),
		(eq, "$random_quest_no", "qst_conquistadors_deliver_horses"),
		(str_store_string, s2, "@{s9} asked you to bring him {reg5?{reg5}:a} {s13} mount{reg5?s:}."),
	 (else_try),
		(str_store_string, s2, "@{s9} asked you to bring them {reg5} bags of {s13}."),
	 (try_end),
    (call_script, "script_start_quest", "$random_quest_no", "$g_talk_troop"),
  (finish_mission),
    ]],
]
