DIALOGS = [
[anyone|plyr|repeat_for_parties, "mate_give_order_details",
    [
      (store_repeat_object, ":party_no"),
	  (store_faction_of_party, ":party_faction", ":party_no"),
      (assign, ":continue", 0),
      (try_begin),
        (eq, "$temp_1", spai_holding_center),
        (try_begin),
          (this_or_next|party_slot_eq, ":party_no", slot_party_type, spt_castle),
          (party_slot_eq, ":party_no", slot_party_type, spt_town),
		  (eq, ":party_faction", "$players_kingdom"),
          (assign, ":continue", 1),
        (try_end),
      (else_try),
        (eq, "$temp_1", spai_patrolling_around_center),
        (try_begin),
          (is_between, ":party_no", centers_begin, centers_end),
          (assign, ":continue", 1),
        (try_end),
      (try_end),
      (eq, ":continue", 1),
      (neq, ":party_no", "$g_encountered_party"),
      (str_store_party_name, s1, ":party_no")
    ],
    "{s1}", "mate_chat_pre_talk",
    [
      (store_repeat_object, "$temp_2"),
      (call_script, "script_sod_external_party_set_order", "$g_encountered_party", "$temp_1", "$temp_2"),
      (assign, "$g_encountered_party", reg0),
    ]],
]
