DIALOGS = [
[anyone, "mate_check_leadership",
    [
      (call_script, "script_check_for_patrols"),
      (store_skill_level, ":max_amount", skl_leadership, "trp_player"),
      (troop_get_slot, ":renown", "trp_player", slot_troop_renown),
      (val_div, ":renown", 250),
      (val_add, ":max_amount", ":renown"),
      (try_for_range, ":num", walled_centers_begin, walled_centers_end),
        (party_slot_eq, ":num", slot_town_lord, "trp_player"),
        (val_add, ":max_amount", 1),
      (try_end),
      (gt, ":max_amount", reg0),
    ],
    "Very well.", "close_window",
    [
      (store_conversation_troop, ":soldier"),
      (remove_member_from_party, ":soldier"),
      (spawn_around_party, "p_main_party", "pt_player_patrol"),
      (party_add_leader, reg(0), ":soldier"),
	  (party_set_slot, reg0, slot_party_type, spt_player_patrol),
      (try_begin),
				(eq, "$g_custom_banner", 1),
				(troop_get_slot, ":flag_icon", "trp_player", slot_troop_custom_banner_map_flag_type),
				(val_max, ":flag_icon", 0),
				(val_add, ":flag_icon", custom_banner_map_icons_begin),
				(party_set_banner_icon, reg(0), ":flag_icon"),
			(else_try),
				(troop_get_slot, ":cur_banner", "trp_player", slot_troop_banner_scene_prop),
				(gt, ":cur_banner", 0),
				(val_sub, ":cur_banner", banner_scene_props_begin),
				(val_add, ":cur_banner", banner_map_icons_begin),
				(party_set_banner_icon, reg(0), ":cur_banner"),
			  (try_end),
      (party_set_ai_behavior, reg(0), ai_bhvr_escort_party),
	  (party_set_ai_object, reg(0), "p_main_party"),
    ]
  ],
]
