DIALOGS = [
[anyone, "capture_enemy_hero_thank", [
     (check_quest_active, "qst_capture_enemy_hero"),
     (quest_get_slot, ":quest_target_troop", "qst_capture_enemy_hero", slot_quest_target_troop),
     (party_count_prisoners_of_type, ":count_prisoners", "p_main_party", ":quest_target_troop"),
     (ge, ":count_prisoners", 1),
     (quest_get_slot, reg5, "qst_capture_enemy_hero", slot_quest_gold_reward),
   ],
   "You brought me more than a prisoner; you brought leverage with a pulse. The bargain can finally move. Take these {reg5} denars, and know that this cell will speak louder than any envoy.", "capture_enemy_hero_thank_2",
   [(quest_get_slot, ":quest_target_troop", "qst_capture_enemy_hero", slot_quest_target_troop),
     (quest_get_slot, ":quest_target_faction", "qst_capture_enemy_hero", slot_quest_target_faction),
     (try_begin),
       (check_quest_active, "qst_capture_enemy_hero"),
       (party_count_prisoners_of_type, ":count_prisoners", "p_main_party", ":quest_target_troop"),
       (ge, ":count_prisoners", 1),
       (party_remove_prisoners, "p_main_party", ":quest_target_troop", 1),
       (store_relation, ":reln", "$g_encountered_party_faction", ":quest_target_faction"),
       (try_begin),
         (lt, ":reln", 0),
         (party_add_prisoners, "$g_encountered_party", ":quest_target_troop", 1), #Adding him to the dungeon
       (else_try),
         #Do not add a non-enemy lord to the dungeon (due to recent diplomatic changes or due to a neutral town/castle)
         (troop_set_slot, ":quest_target_troop", slot_troop_prisoner_of_party, -1),
       (try_end),
       (quest_get_slot, ":reward", "qst_capture_enemy_hero", slot_quest_gold_reward),
       (call_script, "script_troop_add_gold", "trp_player", ":reward"),
       (add_xp_as_reward, 2500),
       (call_script, "script_change_player_relation_with_troop", "$g_talk_troop", 4),
       (call_script, "script_end_quest", "qst_capture_enemy_hero"),
     (else_try),
       (display_message, "@The captured lord handoff could not be completed because the prisoner was no longer in your party.", 0xFF6666),
     (try_end),
   ]],
]
