MENUS = [
(
    "jotnar_clan_competition", 0,
    "You are participating in a duel tournament.^The clan expects a strong run before the judges name a champion.^^Standing: {s1}^Wear on the fighter: {s2}",
    "none",
    [
	(quest_get_slot, reg1, "qst_jotnar_clan_competition", slot_quest_target_amount),
	(quest_get_slot, reg2, "qst_jotnar_clan_competition", slot_quest_gold_reward),
  (try_begin),
    (lt, reg1, 4),
    (str_store_string, s1, "@unproven"),
  (else_try),
    (lt, reg1, 8),
    (str_store_string, s1, "@promising"),
  (else_try),
    (str_store_string, s1, "@near championship standing"),
  (try_end),
  (try_begin),
    (lt, reg2, 3),
    (str_store_string, s2, "@fresh"),
  (else_try),
    (lt, reg2, 6),
    (str_store_string, s2, "@tested"),
  (else_try),
    (str_store_string, s2, "@nearly spent"),
  (try_end),
	(try_begin),
		(ge, reg1, 10),
		(le, reg2, 7),
		(jump_to_menu, "mnu_jotnar_clan_competition_won"),
	(else_try),
		(eq, reg2, 7),
		(lt, reg1, 10),
		(jump_to_menu, "mnu_jotnar_clan_competition_lost"),
	(try_end),
	],
    [
      ("choose_opponent", [], "Choose your next opponent.",
       [(jump_to_menu, "mnu_jc_choose_opponent"),
        ]),
	  ("get_choosen", [], "Wait until someone chooses you as an opponent.",
       [(jump_to_menu, "mnu_jc_get_choosen"),
        ]),
	  ("resign", [], "Withdraw from the tournament.",
       [(call_script, "script_end_quest", "qst_jotnar_clan_competition"),
	   (call_script, "script_change_troop_renown", "trp_player", -5),
	   (call_script, "script_change_player_relation_with_troop", jotnar_clan_guild_master, -2),
	   (jump_to_menu, "mnu_sod_merc_guild"),
        ]),
     ]
  ),
]
