MENUS = [
  ("castle_mercenary_guild_hall", mnf_enable_hot_keys,
   "{s20}",
   "none",
   [
     (call_script, "script_sod_center_refresh_mercenary_guild_hall_stock", "$current_town"),
     (call_script, "script_sod_center_describe_mercenary_guild_hall_to_s20", "$current_town"),
   ],
   [
     ("castle_mercenary_guild_hall_hire_select",
      [
        (call_script, "script_cf_sod_center_can_hire_mercenary_hall_troops", "$current_town"),
        (party_get_slot, ":troop", "$current_town", slot_center_sod_merc_hall_troop_type),
        (party_get_slot, ":amount", "$current_town", slot_center_sod_merc_hall_troop_amount),
        (gt, ":troop", 0),
        (gt, ":amount", 0),
        (str_store_troop_name_by_count, s21, ":troop", ":amount"),
        (assign, reg21, ":amount"),
      ],
      "Review the available {reg21} {s21}.",
      [
        (party_get_slot, ":troop", "$current_town", slot_center_sod_merc_hall_troop_type),
        (party_get_slot, ":starting_amount", "$current_town", slot_center_sod_merc_hall_troop_amount),
        (party_clear, "p_temp_party"),
        (try_begin),
          (gt, ":troop", 0),
          (gt, ":starting_amount", 0),
          (party_add_members, "p_temp_party", ":troop", ":starting_amount"),
        (try_end),
        (store_troop_gold, ":gold_before", "trp_player"),
        (assign, "$g_sod_merc_hall_buy_screen_active", 1),
        (set_mercenary_source_party, "p_temp_party"),
        (change_screen_buy_mercenaries),
        (assign, "$g_sod_merc_hall_buy_screen_active", 0),
        (party_get_num_companions, ":remaining", "p_temp_party"),
        (val_max, ":remaining", 0),
        (val_min, ":remaining", ":starting_amount"),
        (store_sub, ":taken", ":starting_amount", ":remaining"),
        (val_max, ":taken", 0),
        (party_set_slot, "$current_town", slot_center_sod_merc_hall_troop_amount, ":remaining"),
        (try_begin),
          (gt, ":taken", 0),
          (store_troop_gold, ":gold_after", "trp_player"),
          (store_sub, ":spent", ":gold_before", ":gold_after"),
          (val_max, ":spent", 0),
          (val_add, "$g_sod_weekly_troops_hired", ":spent"),
          (val_clamp, "$g_sod_weekly_troops_hired", 0, 2000001),
          (party_get_slot, ":guild", "$current_town", slot_center_sod_merc_hall_guild),
          (try_begin),
            (gt, ":guild", 0),
            (faction_get_slot, ":manpower", ":guild", slot_faction_sod_merc_manpower),
            (val_sub, ":manpower", ":taken"),
            (val_max, ":manpower", 0),
            (faction_set_slot, ":guild", slot_faction_sod_merc_manpower, ":manpower"),
          (try_end),
        (try_end),
        (party_clear, "p_temp_party"),
        (jump_to_menu, "mnu_castle_mercenary_guild_hall"),
      ]),

     ("castle_mercenary_guild_hall_hire_one",
      [
        (call_script, "script_cf_sod_center_can_hire_mercenary_hall_troops", "$current_town"),
        (party_get_slot, ":troop", "$current_town", slot_center_sod_merc_hall_troop_type),
        (call_script, "script_game_get_join_cost", ":troop"),
        (assign, ":cost", reg0),
        (val_mul, ":cost", 115),
        (val_div, ":cost", 100),
        (store_troop_gold, ":gold", "trp_player"),
        (ge, ":gold", ":cost"),
        (assign, reg21, ":cost"),
        (str_store_troop_name, s21, ":troop"),
      ],
      "Hire one {s21} ({reg21} denars).",
      [
        (party_get_slot, ":troop", "$current_town", slot_center_sod_merc_hall_troop_type),
        (call_script, "script_game_get_join_cost", ":troop"),
        (assign, ":cost", reg0),
        (val_mul, ":cost", 115),
        (val_div, ":cost", 100),
        (call_script, "script_sod_player_charge_gold", ":cost"),
        (call_script, "script_sod_center_mercenary_guild_hall_consume_stock", "$current_town", "p_main_party", 1),
        (jump_to_menu, "mnu_castle_mercenary_guild_hall"),
      ]),

     ("castle_mercenary_guild_hall_hire_five",
      [
        (call_script, "script_cf_sod_center_can_hire_mercenary_hall_troops", "$current_town"),
        (party_slot_ge, "$current_town", slot_center_sod_merc_hall_troop_amount, 5),
        (party_get_slot, ":troop", "$current_town", slot_center_sod_merc_hall_troop_type),
        (call_script, "script_game_get_join_cost", ":troop"),
        (assign, ":cost", reg0),
        (val_mul, ":cost", 5),
        (val_mul, ":cost", 115),
        (val_div, ":cost", 100),
        (store_troop_gold, ":gold", "trp_player"),
        (ge, ":gold", ":cost"),
        (assign, reg21, ":cost"),
        (str_store_troop_name_by_count, s21, ":troop", 5),
      ],
      "Hire five {s21} ({reg21} denars).",
      [
        (party_get_slot, ":troop", "$current_town", slot_center_sod_merc_hall_troop_type),
        (call_script, "script_game_get_join_cost", ":troop"),
        (assign, ":cost", reg0),
        (val_mul, ":cost", 5),
        (val_mul, ":cost", 115),
        (val_div, ":cost", 100),
        (call_script, "script_sod_player_charge_gold", ":cost"),
        (call_script, "script_sod_center_mercenary_guild_hall_consume_stock", "$current_town", "p_main_party", 5),
        (jump_to_menu, "mnu_castle_mercenary_guild_hall"),
      ]),

     ("castle_mercenary_guild_hall_back", [], "Return to the castle.", [(jump_to_menu, "mnu_town")]),
   ]),
]
