SIMPLE_TRIGGERS = [
(24 * 7,
  [
		(call_script, "script_get_player_propaganda"),
		
		(try_begin),
			(eq, "$g_sod_king", 1),
			(try_begin),
				(gt, reg52, 0),
				(display_message, "@Your proclamations have been well received, strengthening your standing among your subjects by {reg52}.", dark_green),
			(else_try),
				(lt, reg52, 0),
				(display_message, "@Your proclamations have stirred resentment, weakening your standing among your subjects by {reg52}.", dark_red),
			(try_end),
		(try_end),
		
		(try_for_range, ":center_no", centers_begin, centers_end),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(party_get_slot, ":cur_relation", ":center_no", slot_center_player_relation),
			(val_add, ":cur_relation", reg52),
			(val_clamp, ":cur_relation", -100, 101),
			(party_set_slot, ":center_no", slot_center_player_relation, ":cur_relation"),

			(party_get_slot, ":center_health", ":center_no", slot_center_sod_local_health),
			(party_get_slot, ":center_prosperity", ":center_no", slot_town_prosperity),
			(try_begin),
				(gt, reg52, 1),
				(lt, ":center_health", 70),
				(call_script, "script_change_center_health", ":center_no", 1),
			(else_try),
				(lt, reg52, -1),
				(gt, ":center_health", 25),
				(call_script, "script_change_center_health", ":center_no", -1),
			(try_end),
			(try_begin),
				(gt, reg52, 2),
				(lt, ":center_prosperity", 75),
				(store_random_in_range, ":propaganda_prosperity_roll", 0, 100),
				(lt, ":propaganda_prosperity_roll", 35),
				(call_script, "script_change_center_prosperity", ":center_no", 1),
			(else_try),
				(lt, reg52, -2),
				(gt, ":center_prosperity", 25),
				(store_random_in_range, ":propaganda_unrest_roll", 0, 100),
				(lt, ":propaganda_unrest_roll", 35),
				(call_script, "script_change_center_prosperity", ":center_no", -1),
			(try_end),
		(try_end),
  ]),
]
