SIMPLE_TRIGGERS = [
(24*7,
   [
       (try_for_range, ":troop_no", kingdom_heroes_begin, kingdom_heroes_end),
         (troop_get_slot, ":cur_debt", ":troop_no", slot_troop_player_debt), #Increasing debt
         (val_mul, ":cur_debt", 101),
         (val_div, ":cur_debt", 100),
         (troop_set_slot, ":troop_no", slot_troop_player_debt, ":cur_debt"),
         (call_script, "script_calculate_hero_weekly_net_income_and_add_to_wealth", ":troop_no"), #Adding net income
       (try_end),
       (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
         #If non-player center, adding income to wealth (from population and prosperity, not thin air)
         (neg|party_slot_eq, ":center_no", slot_town_lord, "trp_player"), #center does not belong to player.
         (party_slot_ge, ":center_no", slot_town_lord, 1), #center belongs to someone.
         (try_begin),
           (party_slot_eq, ":center_no", slot_party_type, spt_town),
           (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
           (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
           (val_max, ":center_population", 0),
           (val_max, ":prosperity", 0),
           (call_script, "script_sod_get_town_market_profile", ":center_no"),
           (assign, ":town_market_score", reg0),
           (assign, ":town_rural_surplus", reg1),
           (assign, ":town_services", reg4),
           (assign, ":town_liquidity", reg6),
           (assign, ":town_tax_reliability", reg9),
           (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
           (assign, ":tax_recovery_pct", reg5),
           (assign, ":tax_wealth_drift", reg6),
           (store_mul, ":added_wealth", ":center_population", 2),
           (store_mul, ":prosperity_part", ":prosperity", 10),
           (val_add, ":added_wealth", ":prosperity_part"),
           (store_mul, ":service_wealth", ":town_services", 20),
           (val_add, ":added_wealth", ":service_wealth"),
           (store_mul, ":surplus_wealth", ":town_rural_surplus", 12),
           (val_add, ":added_wealth", ":surplus_wealth"),
           (store_mul, ":market_wealth", ":town_market_score", 15),
           (val_add, ":added_wealth", ":market_wealth"),
           (store_mul, ":liquidity_wealth", ":town_liquidity", 6),
           (val_add, ":added_wealth", ":liquidity_wealth"),
           (val_mul, ":added_wealth", 3),
           (val_div, ":added_wealth", 2),
           (val_mul, ":added_wealth", ":town_tax_reliability"),
           (val_div, ":added_wealth", 100),
           (val_mul, ":added_wealth", ":tax_recovery_pct"),
           (val_div, ":added_wealth", 100),
           (val_add, ":added_wealth", ":tax_wealth_drift"),
           (val_max, ":added_wealth", 50),
         (else_try),
           # Castles are military estates: reserves come from support, bound villages,
           # roads, stores, administration, and noble access rather than town markets.
           (call_script, "script_sod_get_castle_support_profile", ":center_no"),
           (assign, ":castle_support", reg0),
           (assign, ":bound_population", reg2),
           (assign, ":bound_villages", reg3),
           (assign, ":food_security", reg4),
           (assign, ":administration", reg5),
           (assign, ":road_control", reg6),
           (assign, ":noble_access", reg7),
           (assign, ":military_power", reg8),
           (assign, ":tax_reliability", reg15),
           (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
           (assign, ":tax_recovery_pct", reg5),
           (assign, ":tax_wealth_drift", reg6),

           (store_div, ":added_wealth", ":bound_population", 8),
           (store_mul, ":support_dues", ":castle_support", 6),
           (val_add, ":added_wealth", ":support_dues"),
           (store_mul, ":village_dues", ":bound_villages", 75),
           (val_add, ":added_wealth", ":village_dues"),
           (store_mul, ":road_dues", ":road_control", 8),
           (val_add, ":added_wealth", ":road_dues"),
           (store_mul, ":admin_dues", ":administration", 12),
           (val_add, ":added_wealth", ":admin_dues"),
           (store_div, ":military_dues", ":military_power", 8),
           (val_add, ":added_wealth", ":military_dues"),
           (try_begin),
             (eq, ":noble_access", 1),
             (val_add, ":added_wealth", 150),
           (try_end),
           (val_mul, ":added_wealth", ":tax_reliability"),
           (val_div, ":added_wealth", 100),
           (val_mul, ":added_wealth", ":tax_recovery_pct"),
           (val_div, ":added_wealth", 100),
           (val_add, ":added_wealth", ":tax_wealth_drift"),

           (try_begin),
             (lt, ":food_security", 300),
             (val_mul, ":added_wealth", 60),
             (val_div, ":added_wealth", 100),
           (else_try),
             (lt, ":food_security", 700),
             (val_mul, ":added_wealth", 85),
             (val_div, ":added_wealth", 100),
           (try_end),
           (val_clamp, ":added_wealth", 50, 3501),
         (try_end),
         (call_script, "script_calculate_weekly_party_wage", ":center_no"),
         (store_sub, ":net_wealth_change", ":added_wealth", reg0),
         (call_script, "script_sod_change_center_wealth", ":center_no", ":net_wealth_change"),
       (try_end),
    ]),
]
