SIMPLE_TRIGGERS = [
(24 * 7,
  [
    (try_for_range, ":center_no", centers_begin, centers_end),
      (this_or_next|is_between, ":center_no", towns_begin, towns_end),
      (this_or_next|is_between, ":center_no", villages_begin, villages_end),
      (is_between, ":center_no", castles_begin, castles_end),
      (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
      (assign, ":food_balance", reg0),
      (assign, ":strategic_balance", reg2),
      (assign, ":scarcity_pressure", reg4),
      (assign, ":trade_willingness", reg5),
      (assign, ":liquidity_pressure", reg6),
      (assign, ":wealth_delta", reg7),
      (assign, ":prosperity_pressure", reg8),

      (try_begin),
        (neq, ":wealth_delta", 0),
        (call_script, "script_sod_change_center_wealth", ":center_no", ":wealth_delta"),
      (try_end),

      (try_begin),
        (gt, ":prosperity_pressure", 0),
        (ge, ":trade_willingness", 75),
        (ge, ":liquidity_pressure", 80),
        (call_script, "script_change_center_prosperity", ":center_no", 1),
      (else_try),
        (lt, ":prosperity_pressure", 0),
        (this_or_next|gt, ":scarcity_pressure", 160),
        (lt, ":trade_willingness", 45),
        (call_script, "script_change_center_prosperity", ":center_no", -1),
      (try_end),

      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (lt, ":food_balance", -50),
        (call_script, "script_sod_change_center_local_prosperity", ":center_no", -1),
      (else_try),
        (is_between, ":center_no", castles_begin, castles_end),
        (lt, ":strategic_balance", -40),
        (call_script, "script_sod_change_center_local_prosperity", ":center_no", -1),
      (try_end),
    (try_end),
  ]),
]
