from header_common import *
from header_operations import *
from module_constants import *

SIMPLE_TRIGGERS = [
    (
        24 * 7,
        [
            (try_for_range, ":center_no", centers_begin, centers_end),
                (call_script, "script_get_center_ideal_health", ":center_no"),
                (assign, ":ideal_health", reg0),
                (party_get_slot, ":current_health", ":center_no", slot_center_health),
                (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
                (party_get_slot, ":food_store", ":center_no", slot_town_food_store),
                (party_get_slot, ":player_relation", ":center_no", slot_town_player_relation),

                (store_sub, ":health_gap", ":ideal_health", ":current_health"),
                (assign, ":local_pressure", 0),

                (try_begin),
                    (lt, ":prosperity", 80),
                    (store_sub, ":temp_pressure", 80, ":prosperity"),
                    (val_add, ":local_pressure", ":temp_pressure"),
                (try_end),

                (try_begin),
                    (lt, ":food_store", 120),
                    (store_sub, ":temp_pressure", 120, ":food_store"),
                    (val_add, ":local_pressure", ":temp_pressure"),
                (try_end),

                (try_begin),
                    (lt, ":player_relation", 0),
                    (store_sub, ":temp_pressure", 0, ":player_relation"),
                    (val_add, ":local_pressure", ":temp_pressure"),
                (try_end),

                (assign, ":special_event_chance", 1),
                (val_add, ":special_event_chance", ":local_pressure"),
                (try_begin),
                    (gt, ":health_gap", 0),
                    (val_add, ":special_event_chance", ":health_gap"),
                (else_try),
                    (store_sub, ":health_surplus", 0, ":health_gap"),
                    (val_div, ":health_surplus", 2),
                    (val_sub, ":special_event_chance", ":health_surplus"),
                (try_end),
                (val_div, ":special_event_chance", 10),
                (val_max, ":special_event_chance", 1),
                (val_min, ":special_event_chance", 20),

                (store_random_in_range, ":special_event_roll", 0, 200),
                (lt, ":special_event_roll", ":special_event_chance"),
                (try_begin),
                    (str_store_party_name, s0, ":center_no"),
                    (display_message, "@{s0} suffers an unusual health setback.", 0xFFAA0000),
                    (assign, ":special_health_change", 1),
                    (val_add, ":special_health_change", ":special_event_chance"),
                    (val_div, ":special_health_change", 4),
                    (val_max, ":special_health_change", 1),
                    (val_mul, ":special_health_change", -1),
                    (call_script, "script_change_center_health", ":center_no", ":special_health_change"),
                (try_end),

                (assign, ":health_change", ":health_gap"),
                (val_div, ":health_change", 3),

                (try_begin),
                    (gt, ":health_gap", 0),
                    (val_add, ":health_change", ":local_pressure"),
                    (try_begin),
                        (lt, ":food_store", 100),
                        (store_sub, ":food_pressure", 100, ":food_store"),
                        (val_div, ":food_pressure", 10),
                        (val_add, ":health_change", ":food_pressure"),
                    (try_end),
                    (try_begin),
                        (lt, ":prosperity", 70),
                        (store_sub, ":prosperity_pressure", 70, ":prosperity"),
                        (val_div, ":prosperity_pressure", 8),
                        (val_add, ":health_change", ":prosperity_pressure"),
                    (try_end),
                    (try_begin),
                        (lt, ":player_relation", 0),
                        (store_sub, ":relation_pressure", 0, ":player_relation"),
                        (val_div, ":relation_pressure", 25),
                        (val_add, ":health_change", ":relation_pressure"),
                    (try_end),
                (else_try),
                    (store_sub, ":health_surplus", 0, ":health_gap"),
                    (val_div, ":health_surplus", 3),
                    (val_sub, ":health_change", ":health_surplus"),
                    (try_begin),
                        (lt, ":food_store", 100),
                        (store_sub, ":food_pressure", 100, ":food_store"),
                        (val_div, ":food_pressure", 12),
                        (val_sub, ":health_change", ":food_pressure"),
                    (try_end),
                    (try_begin),
                        (lt, ":prosperity", 70),
                        (store_sub, ":prosperity_pressure", 70, ":prosperity"),
                        (val_div, ":prosperity_pressure", 10),
                        (val_sub, ":health_change", ":prosperity_pressure"),
                    (try_end),
                    (try_begin),
                        (lt, ":player_relation", 0),
                        (store_sub, ":relation_pressure", 0, ":player_relation"),
                        (val_div, ":relation_pressure", 30),
                        (val_sub, ":health_change", ":relation_pressure"),
                    (try_end),
                (try_end),

                (call_script, "script_change_center_health", ":center_no", ":health_change"),
            (try_end),
        ],
    ),
]