SIMPLE_TRIGGERS = [
(24 * 7,
  [
    (try_begin),
      (eq, "$g_sod_hide_messages", -2),
      (set_show_messages, 0),
    (try_end),

    (assign, ":count", 0),
    (try_for_range, ":center_no", centers_begin, centers_end),

      # ensure that it has a university
      (party_slot_eq, ":center_no", slot_center_has_university, 1),

      # ensure that this center is currently owned by the player's faction
      (store_faction_of_party, ":center_faction", ":center_no"),
      (this_or_next|eq, ":center_faction", "fac_player_supporters_faction"),
      (eq, ":center_faction", "fac_player_faction"),

      # grant renown to the owner
      (try_begin),
        (party_get_slot, ":center_lord", ":center_no", slot_town_lord),
        (ge, ":center_lord", 0), #if negative, then unowned
        (set_show_messages, 0),
        (call_script, "script_change_troop_renown", ":center_lord", "$g_sod_building_university_renown"),
        (set_show_messages, 1),
      (try_end),

      # Universities should also improve the underlying quality of life over time.
      (party_get_slot, ":center_health", ":center_no", slot_center_sod_local_health),
      (party_get_slot, ":center_prosperity", ":center_no", slot_town_prosperity),
      (party_get_slot, ":food_store", ":center_no", slot_party_food_store),
      (call_script, "script_center_get_food_store_limit", ":center_no"),
      (assign, ":food_store_limit", reg0),
      (try_begin),
        (lt, ":center_health", 70),
        (call_script, "script_change_center_health", ":center_no", 1),
      (try_end),
      (try_begin),
        (lt, ":center_prosperity", 55),
        (call_script, "script_change_center_prosperity", ":center_no", 1),
      (else_try),
        (ge, ":center_health", 65),
        (lt, ":center_prosperity", 70),
        (store_random_in_range, ":university_growth_roll", 0, 100),
        (lt, ":university_growth_roll", 35),
        (call_script, "script_change_center_prosperity", ":center_no", 1),
      (try_end),
      (try_begin),
        (gt, ":food_store_limit", 0),
        (store_mul, ":university_comfortable_stock_threshold", ":food_store_limit", 3),
        (val_div, ":university_comfortable_stock_threshold", 5),
        (ge, ":food_store", ":university_comfortable_stock_threshold"),
        (ge, ":center_health", 60),
        (lt, ":center_prosperity", 78),
        (store_random_in_range, ":university_supply_roll", 0, 100),
        (lt, ":university_supply_roll", 25),
        (call_script, "script_change_center_prosperity", ":center_no", 1),
      (try_end),

      # increase this center's relation with the player
      # Only when the player is the center lord OR the player is the faction leader (king).
      (try_begin),
        (this_or_next|party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
        (faction_slot_eq, ":center_faction", slot_faction_leader, "trp_player"),
        (party_get_slot, ":cur_relation", ":center_no", slot_center_player_relation),
        (val_add, ":cur_relation", "$g_sod_building_university_reputation"),
		(val_min, ":cur_relation", 100), # FIX: cap relation at 100 so it doesn't break dialogue trees
        (party_set_slot, ":center_no", slot_center_player_relation, ":cur_relation"),

        # inform the player that their universities are paying off
        (try_begin),
          (eq, "$g_sod_hide_messages", 0),
          (str_store_party_name_link, s1, ":center_no"),
          (display_message, "@Scholars in {s1} speak well of your patronage, adding to your renown and strengthening the people's regard for your rule.", renown_color),
        (try_end),
      (try_end),

      # remaining effects apply to player only
      (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),

      # keep track of count
      (val_add, ":count", 1),
    (try_end),

      # inform the player that their universities are paying off
      (try_begin),
        (eq, "$g_sod_hide_messages", -1),
        (ge, ":count", 1),
        (display_message, "@Your universities spread learning and carry your name farther across the kingdom.", renown_color),
      (try_end),

	(try_for_range, ":center_no", centers_begin, centers_end),
		(party_slot_eq, ":center_no", slot_center_has_inn, 1),
		(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
		(party_get_slot, ":cur_relation", ":center_no", slot_center_player_relation),
		(val_add, ":cur_relation", "$g_sod_building_inn_reputation"),
		(val_min, ":cur_relation", 100), # FIX: cap relation at 100
		(val_clamp, ":cur_relation", -100, 101),
		(party_set_slot, ":center_no", slot_center_player_relation, ":cur_relation"),
		(party_get_slot, ":center_health", ":center_no", slot_center_sod_local_health),
		(party_get_slot, ":center_prosperity", ":center_no", slot_town_prosperity),
		(party_get_slot, ":food_store", ":center_no", slot_party_food_store),
		(call_script, "script_center_get_food_store_limit", ":center_no"),
		(assign, ":food_store_limit", reg0),
		(try_begin),
			(lt, ":center_health", 60),
			(call_script, "script_change_center_health", ":center_no", 1),
		(try_end),
		(try_begin),
			(gt, ":food_store_limit", 0),
			(store_mul, ":inn_low_stock_threshold", ":food_store_limit", 2),
			(val_div, ":inn_low_stock_threshold", 5),
			(store_mul, ":inn_comfortable_stock_threshold", ":food_store_limit", 3),
			(val_div, ":inn_comfortable_stock_threshold", 5),
			(store_div, ":inn_food_boost", ":food_store_limit", 32),
			(val_clamp, ":inn_food_boost", 6, 20),
			(lt, ":food_store", ":inn_low_stock_threshold"),
			(val_add, ":food_store", ":inn_food_boost"),
			(val_min, ":food_store", ":food_store_limit"),
			(party_set_slot, ":center_no", slot_party_food_store, ":food_store"),
		(try_end),
		(try_begin),
			(ge, ":center_health", 55),
			(lt, ":center_prosperity", 68),
			(store_random_in_range, ":inn_circulation_roll", 0, 100),
			(lt, ":inn_circulation_roll", 25),
			(call_script, "script_change_center_prosperity", ":center_no", 1),
		(try_end),
		(try_begin),
			(gt, ":food_store_limit", 0),
			(ge, ":food_store", ":inn_comfortable_stock_threshold"),
			(ge, ":center_health", 58),
			(lt, ":center_prosperity", 76),
			(store_random_in_range, ":inn_trade_surge_roll", 0, 100),
			(lt, ":inn_trade_surge_roll", 20),
			(call_script, "script_change_center_prosperity", ":center_no", 1),
		(try_end),
    (try_end),
	  
    (try_begin),
      (eq, "$g_sod_hide_messages", -2),
      (set_show_messages, 1),
    (try_end),
  ]),
]
