SCRIPTS = [
("game_get_prisoner_price",
    [
      (store_script_param_1, ":troop_id"),
      (assign, reg0, 50),
      (store_character_level, ":troop_level", ":troop_id"),
      (assign, ":ransom_amount", ":troop_level"),
      (val_add, ":ransom_amount", 10),
      (val_mul, ":ransom_amount", ":ransom_amount"),
      (try_begin),
        (is_between, "$g_talk_troop", ransom_brokers_begin, ransom_brokers_end),
        (val_div, ":ransom_amount", 10),
        (try_begin),
          (troop_slot_eq, ":troop_id", slot_troop_occupation, slto_kingdom_hero),
          (val_add, ":ransom_amount", 120),
        (else_try),
          (ge, ":troop_level", 25),
          (val_add, ":ransom_amount", 40),
        (else_try),
          (ge, ":troop_level", 15),
          (val_add, ":ransom_amount", 15),
        (try_end),
        (assign, reg0, ":ransom_amount"),
      (else_try),
        (this_or_next|eq, "$g_talk_troop", "trp_slaver_guild_master"),
        (eq, "$g_talk_troop", "trp_slaver_rep_1"),
        (val_div, ":ransom_amount", 12),
        (try_begin),
          (troop_slot_eq, ":troop_id", slot_troop_occupation, slto_kingdom_hero),
          (val_add, ":ransom_amount", 90),
        (else_try),
          (ge, ":troop_level", 25),
          (val_add, ":ransom_amount", 35),
        (else_try),
          (ge, ":troop_level", 15),
          (val_add, ":ransom_amount", 15),
        (try_end),
        (val_max, ":ransom_amount", 60),
        (assign, reg0, ":ransom_amount"),
      (try_end),
      (set_trigger_result, reg0),
  ]),
]
