SCRIPTS = [
("game_get_skill_modifier_for_troop",
    [(store_script_param, ":troop_no", 1),
      (store_script_param, ":skill_no", 2),
      (assign, ":modifier_value", 0),
      (try_begin),
        (eq, ":skill_no", "skl_wound_treatment"),
        (call_script, "script_get_troop_item_amount", ":troop_no", "itm_book_wound_treatment_reference"),
        (gt, reg0, 0),
        (val_add, ":modifier_value", 1),
      (try_end),
      (try_begin),
        (eq, ":skill_no", "skl_trainer"),
        (call_script, "script_get_troop_item_amount", ":troop_no", "itm_book_training_reference"),
        (gt, reg0, 0),
        (val_add, ":modifier_value", 1),
      (try_end),
      (try_begin),
        (eq, ":skill_no", "skl_surgery"),
        (call_script, "script_get_troop_item_amount", ":troop_no", "itm_book_surgery_reference"),
        (gt, reg0, 0),
        (val_add, ":modifier_value", 1),
      (try_end),
      (try_begin),
        (eq, ":skill_no", "skl_pathfinding"),
        (call_script, "script_get_troop_item_amount", ":troop_no", "itm_book_pathfinding_reference"),
        (gt, reg0, 0),
        (val_add, ":modifier_value", 1),
      (try_end),
      (try_begin),
        (eq, ":troop_no", "trp_player"),
        (eq, ":skill_no", "skl_spotting"),
        (eq, "$g_camp_mode", 1),
        (eq, "$g_player_icon_state", pis_camping),
        (main_party_has_troop, "trp_npc1"),
        (store_current_hours, ":cur_hours"),
        (gt, "$g_sod_camp_borcha_sight_until_hour", ":cur_hours"),
        (val_add, ":modifier_value", "$g_sod_camp_borcha_sight_bonus"),
      (try_end),
      (try_begin),
        (eq, ":troop_no", "trp_player"),
        (eq, ":skill_no", "skl_wound_treatment"),
        (eq, "$g_camp_mode", 1),
        (eq, "$g_player_icon_state", pis_camping),
        (main_party_has_troop, "trp_npc12"),
        (store_current_hours, ":cur_hours"),
        (gt, "$g_sod_camp_jeremus_healing_until_hour", ":cur_hours"),
        (val_add, ":modifier_value", "$g_sod_camp_jeremus_healing_bonus"),
      (try_end),
      (try_begin),
        (eq, ":troop_no", "trp_player"),
        (eq, ":skill_no", "skl_tactics"),
        (eq, "$g_camp_mode", 1),
        (eq, "$g_player_icon_state", pis_camping),
        (main_party_has_troop, "trp_npc6"),
        (store_current_hours, ":cur_hours"),
        (gt, "$g_sod_camp_firentis_readiness_until_hour", ":cur_hours"),
        (val_add, ":modifier_value", "$g_sod_camp_firentis_readiness"),
      (try_end),
      (set_trigger_result, ":modifier_value"),
  ]),
]
