PRESENTATIONS = [
("sod_troop_trees", prsntf_read_only, 0,[
		(ti_on_presentation_load, [
		(set_fixed_point_multiplier, 1000),
		(presentation_set_duration, 99999),
		(try_begin),
			(eq, "$g_sod_sa_talk_subject", 11),
			(create_mesh_overlay, reg1, "mesh_swadian_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 12),
			(create_mesh_overlay, reg1, "mesh_vaeghir_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 13),
			(create_mesh_overlay, reg1, "mesh_khergit_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 14),
			(create_mesh_overlay, reg1, "mesh_nord_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 15),
			(create_mesh_overlay, reg1, "mesh_rhodok_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 21),
			(create_mesh_overlay, reg1, "mesh_antarian_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 22),
			(create_mesh_overlay, reg1, "mesh_marinian_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 23),
			(create_mesh_overlay, reg1, "mesh_adenian_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 24),
			(create_mesh_overlay, reg1, "mesh_villianese_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 25),
			(create_mesh_overlay, reg1, "mesh_zerrikane_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 31),
			(create_mesh_overlay, reg1, "mesh_black_army_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 37),
			(create_mesh_overlay, reg1, "mesh_boar_clan_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 32),
			(create_mesh_overlay, reg1, "mesh_conquistadors_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 33),
			(create_mesh_overlay, reg1, "mesh_elephant_guard_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 34),
			(create_mesh_overlay, reg1, "mesh_jotnar_clan_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 35),
			(create_mesh_overlay, reg1, "mesh_serpent_host_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 36),
			(create_mesh_overlay, reg1, "mesh_slavers_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 4),
			(create_mesh_overlay, reg1, "mesh_imperial_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 5),
			(create_mesh_overlay, reg1, "mesh_peasants_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 6),
			(create_mesh_overlay, reg1, "mesh_bandit_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 7),
			(create_mesh_overlay, reg1, "mesh_random_merc_troop_tree"),
		(else_try),
			(eq, "$g_sod_sa_talk_subject", 8),
			(create_mesh_overlay, reg1, "mesh_faith_troop_tree"),
		(else_try),
			(create_mesh_overlay, reg1, "mesh_random_merc_troop_tree"),
		(try_end),
		(position_set_x, pos1, 0),
        (position_set_y, pos1, 0),
        (overlay_set_position, reg1, pos1),
	  ]),
	  
	  (ti_on_presentation_run,
       [
        (try_begin),
            (this_or_next|key_clicked, key_escape),
			(this_or_next|game_key_clicked, gk_jump),
			(this_or_next|game_key_clicked, gk_attack),
			(game_key_clicked, gk_defend),
            (presentation_set_duration, 0),
        (try_end),
        ]),
		]),
]
