SCRIPTS = [
("coherence",
                      [
                        (get_scene_boundaries, pos3, pos4),
                        (assign, ":num_allies", 0),
                        (assign, ":coh_allies", 0),
                        (assign, ":num_enemies", 0),
                        (assign, ":coh_enemies", 0),
                        (try_for_agents, ":agent"),
                          (agent_is_ally, ":agent"),
                          (agent_is_human, ":agent"),
                          (store_agent_hit_points, ":hitpoints", ":agent", 0),
                          (agent_get_troop_id, ":troop_type", ":agent"),
                          (store_character_level, ":troop_level", ":troop_type"),
                          #(val_div, ":troop_level", 10),
                          (val_mul, ":hitpoints", ":troop_level"),
						  #SoD begin
                          (val_add, ":num_allies", 1),
						  #SoD end
                          (val_add, ":coh_allies", ":hitpoints"),
                        (else_try),
                          (agent_is_human, ":agent"),
                          (store_agent_hit_points, ":hitpoints", ":agent", 0),
                          (agent_get_troop_id, ":troop_type", ":agent"),
                          (store_character_level, ":troop_level", ":troop_type"),
                          #(val_div, ":troop_level", 10),
                          (val_mul, ":hitpoints", ":troop_level"),
						  #SoD begin
                          (val_add, ":num_enemies", 1),
						  #SoD end
                          (val_add, ":coh_enemies", ":hitpoints"),
                        (end_try),
                        (val_div, ":coh_allies", ":num_allies"),
                        (assign, "$allies_coh_base", ":coh_allies"),
						#SoD begin battle advantage also takes troop level into account now, it will have influence on morale, each point of BA is 5% more or less morale
						(assign, ":advantage", "$sod_battle_advantage"),
						(try_begin),
							(gt, "$sod_battle_advantage", 0),
							(val_mul, ":advantage", 5),
							(val_add, ":advantage", 100),
							(val_mul, "$allies_coh_base", ":advantage"),
							(val_div, "$allies_coh_base", 100),
						(try_end),
						#SoD  player's party morale will influence his battle morale, no such thing is done for computer,
						#AI is retarded already and let's asume that enemy is always happy,
						#finally some reason to keep really high morale! Better grab more food!
						  (party_get_morale, ":map_morale", "p_main_party"),
						  (val_div, ":map_morale", 2),
						  (val_add, ":map_morale", 100),
						  (val_mul, "$allies_coh_base", ":map_morale"),
						  (val_div, "$allies_coh_base", 150),	
                        (assign, "$allies_coh", "$allies_coh_base"),
						(assign, ":kills", "$new_kills"),
						(val_mul, ":kills", 10),
                        (val_add, "$allies_coh", ":kills"),
                        (val_div, ":coh_enemies", ":num_enemies"),
						(try_begin),
							(lt, "$sod_battle_advantage", 0),
							(val_mul, ":advantage", -5),
							(val_add, ":advantage", 100),
							(val_mul, ":coh_enemies", ":advantage"),
							(val_div, ":coh_enemies", 100),
						(try_end),
                        (assign, "$enemies_coh", ":coh_enemies"),
						#SoD end
                      ]
                    ),
]
