SCRIPTS = [
("enter_town_center_from_passage",
    [
      (assign, "$talk_context", 0),
      (assign, "$town_entered", 1),
      (call_script, "script_sod_companion_retinue_repair_all"),
      (try_begin),
        (party_slot_eq, "$current_town", slot_party_type, spt_castle),
        (party_get_slot, ":castle_exterior", "$current_town", slot_castle_exterior),
        (modify_visitors_at_site, ":castle_exterior"),
        (reset_visitors),

        (try_begin),
          (store_faction_of_party, ":castle_faction", "$current_town"),
          (faction_get_slot, ":troop_prison_guard", ":castle_faction", slot_faction_prison_guard_troop),
          (gt, ":troop_prison_guard", 0),
          (set_visitor, 24, ":troop_prison_guard"),
        (try_end),

        (assign, ":guard_no", 40),
        (try_begin),
          (store_faction_of_party, ":castle_faction", "$current_town"),
          (faction_get_slot, ":troop_castle_guard", ":castle_faction", slot_faction_castle_guard_troop),
          (gt, ":troop_castle_guard", 0),
          (set_visitor, ":guard_no", ":troop_castle_guard"),
          (val_add, ":guard_no", 1),
          (set_visitor, ":guard_no", ":troop_castle_guard"),
          (val_add, ":guard_no", 1),
        (try_end),

        (party_get_num_companion_stacks, ":num_stacks", "$g_encountered_party"),
        (try_for_range, ":troop_iterator", 0, ":num_stacks"),
          (lt, ":guard_no", 47),
          (party_stack_get_troop_id, ":cur_troop_id", "$g_encountered_party", ":troop_iterator"),
          (neg|troop_is_hero, ":cur_troop_id"),
          (party_stack_get_size, ":stack_size", "$g_encountered_party", ":troop_iterator"),
          (party_stack_get_num_wounded, ":num_wounded", "$g_encountered_party", ":troop_iterator"),
          (val_sub, ":stack_size", ":num_wounded"),
          (gt, ":stack_size", 0),
          (party_stack_get_troop_dna, ":troop_dna", "$g_encountered_party", ":troop_iterator"),
          (set_visitor, ":guard_no", ":cur_troop_id", ":troop_dna"),
          (val_add, ":guard_no", 1),
        (try_end),

        (set_jump_entry, 1),
        (set_jump_mission, "mt_castle_visit"),
        (jump_to_scene, ":castle_exterior"),
        (change_screen_mission),
      (else_try),
      (party_get_slot, ":town_scene", "$current_town", slot_town_center),
      (modify_visitors_at_site, ":town_scene"),
      (reset_visitors),
      (assign, "$g_mt_mode", tcm_default),
      (store_faction_of_party, ":town_faction", "$current_town"),
      (try_begin),
        (faction_get_slot, ":troop_prison_guard", ":town_faction", slot_faction_prison_guard_troop),
        (faction_get_slot, ":troop_castle_guard", ":town_faction", slot_faction_castle_guard_troop),
        (gt, ":troop_prison_guard", 0),
        (gt, ":troop_castle_guard", 0),
        (set_visitor, 23, ":troop_castle_guard"),
        (set_visitor, 24, ":troop_prison_guard"),
      (try_end),
      (faction_get_slot, ":tier_2_troop", ":town_faction", slot_faction_tier_2_troop),
      (faction_get_slot, ":tier_3_troop", ":town_faction", slot_faction_tier_3_troop),
      (faction_get_slot, ":guard_troop", ":town_faction", slot_faction_guard_troop),
      (faction_get_slot, ":castle_guard_troop", ":town_faction", slot_faction_castle_guard_troop),

      (try_begin),
        (gt, ":tier_2_troop", 0),
        (assign, reg(0), ":tier_3_troop"),
        (assign, reg(1), ":tier_3_troop"),
        (assign, reg(2), ":tier_2_troop"),
        (assign, reg(3), ":tier_2_troop"),
      (else_try),
        (gt, ":guard_troop", 0),
        (gt, ":castle_guard_troop", 0),
        (assign, reg(0), ":castle_guard_troop"),
        (assign, reg(1), ":castle_guard_troop"),
        (assign, reg(2), ":guard_troop"),
        (assign, reg(3), ":guard_troop"),
      (else_try),
        (assign, reg(0), "trp_vaegir_infantry"),
        (assign, reg(1), "trp_vaegir_infantry"),
        (assign, reg(2), "trp_vaegir_archer"),
        (assign, reg(3), "trp_vaegir_footman"),
      (try_end),
      (shuffle_range, 0, 4),
      (set_visitor, 25, reg(0)),
      (set_visitor, 26, reg(1)),
      (set_visitor, 27, reg(2)),
      (set_visitor, 28, reg(3)),

      (party_get_slot, ":spawned_troop", "$current_town", slot_town_armorer),
      (set_visitor, 9, ":spawned_troop"),
      (party_get_slot, ":spawned_troop", "$current_town", slot_town_weaponsmith),
      (set_visitor, 10, ":spawned_troop"),
      (party_get_slot, ":spawned_troop", "$current_town", slot_town_elder),
      (set_visitor, 11, ":spawned_troop"),
      (party_get_slot, ":spawned_troop", "$current_town", slot_town_horse_merchant),
      (set_visitor, 12, ":spawned_troop"),

      (call_script, "script_init_town_walkers"),
      (set_jump_mission, "mt_town_center"),
      (mission_tpl_entry_set_override_flags, "mt_town_center", 0, af_override_horse),
      (mission_tpl_entry_set_override_flags, "mt_town_center", 2, af_override_horse),
      (mission_tpl_entry_set_override_flags, "mt_town_center", 3, af_override_horse),
      (mission_tpl_entry_set_override_flags, "mt_town_center", 4, af_override_horse),
      (mission_tpl_entry_set_override_flags, "mt_town_center", 5, af_override_horse),
      (mission_tpl_entry_set_override_flags, "mt_town_center", 6, af_override_horse),
      (mission_tpl_entry_set_override_flags, "mt_town_center", 7, af_override_horse),
      (jump_to_scene, ":town_scene"),
      (change_screen_mission),
      (try_end),
  ]),
]
