SCRIPTS = [
("fgtq_end",
	[
		(store_script_param_1, ":won"),
			
		(quest_get_slot, ":completed", "$fight_guild_troops_quest", slot_quest_rounds_completed),
		(quest_get_slot, ":num_rounds", "$fight_guild_troops_quest", slot_quest_num_rounds),
		(val_add, ":completed", 1),
		(quest_set_slot, "$fight_guild_troops_quest", slot_quest_rounds_completed, ":completed"),
		 
		(quest_get_slot, ":num_won", "$fight_guild_troops_quest", slot_quest_rounds_won),
		(try_begin),
			(eq, ":won", 1),
			(val_add, ":num_won", 1),
			(quest_set_slot, "$fight_guild_troops_quest", slot_quest_rounds_won, ":num_won"),
		(try_end),
			 
		(try_begin),
			(eq, "$fgtq_state", fgtq_eg_special),
			(str_store_string, s0, "@Thanks for your assistance; and now my heart is at ease, knowing I'd have all the time I would ever need during a raid to preserve the treasures of our tribes.  This battle was a fitting challenge for our Battle Shamans as well.  Once again, I thank you, and may the Spirits watch over your warband - you are worth of their protection indeed."),
			(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 4),
			(add_xp_as_reward, 400),
			(try_begin),
				(eq, ":won", 1),
				(call_script, "script_change_troop_renown", "trp_player", 10),
			(try_end),
			(assign, "$fgtq_state", fgtq_end),
		(else_try),
			(eq, ":completed", ":num_rounds"),
			(try_begin),
				(gt, ":num_won", 0),
				(call_script, "script_succeed_quest", "$fight_guild_troops_quest"),
			(else_try),
				(call_script, "script_fail_quest", "$fight_guild_troops_quest"),
			(try_end),
			(call_script, "script_end_quest", "$fight_guild_troops_quest"),
			(assign, "$fgtq_state", fgtq_end),
			(try_begin),
				(eq, "$fight_guild_troops_quest", "qst_black_army_fight_guild_troops"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(str_store_string, s0, "str_sod_1_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 400),
					(call_script, "script_troop_add_gold", "trp_player", 400),
					(call_script, "script_change_troop_renown", "trp_player", 5),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild1", 4),
				(else_try),
					(eq, ":num_won", 0),
					(str_store_string, s0, "str_sod_1_quest_fight_guild_troops_o1"),
					(call_script, "script_change_troop_renown", "trp_player", -5),
				(else_try),
					(eq, ":num_won", 1),
					(str_store_string, s0, "str_sod_1_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 100),
					(call_script, "script_troop_add_gold", "trp_player", 100),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild1", 1),
				(else_try),
					(str_store_string, s0, "str_sod_1_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 200),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild1", 2),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_conquistadors_fight_guild_troops"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 400),
					(call_script, "script_troop_add_gold", "trp_player", 400),
					(call_script, "script_change_troop_renown", "trp_player", 5),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild2", 4),
				(else_try),
					(eq, ":num_won", 0),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_o1"),
					(call_script, "script_change_troop_renown", "trp_player", -5),
				(else_try),
					(eq, ":num_won", 1),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 100),
					(call_script, "script_troop_add_gold", "trp_player", 100),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild2", 1),
				(else_try),
					(eq, ":num_won", 3),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 300),
					(call_script, "script_troop_add_gold", "trp_player", 300),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild2", 3),
				(else_try),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 200),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild2", 2),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_elephant_guard_fight_guild_troops"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(assign, "$fgtq_state", fgtq_eg_special),
					(str_store_string, s0, "str_sod_3_quest_fight_guild_troops_o4"),
					(add_xp_as_reward, 400),
					(call_script, "script_troop_add_gold", "trp_player", 400),
					(call_script, "script_change_troop_renown", "trp_player", 5),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 4),
				(else_try),
					(eq, ":num_won", 0),
					(str_store_string, s0, "str_sod_3_quest_fight_guild_troops_o3"),
					(call_script, "script_change_troop_renown", "trp_player", -5),
				(else_try),
					(eq, ":num_won", 1),
					(str_store_string, s0, "str_sod_3_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 100),
					(call_script, "script_troop_add_gold", "trp_player", 100),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 1),
				(else_try),
					(str_store_string, s0, "str_sod_3_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 200),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 2),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_jotnar_clan_fight_guild_troops"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(str_store_string, s0, "str_sod_4_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 400),
					(call_script, "script_troop_add_gold", "trp_player", 400),
					(call_script, "script_change_troop_renown", "trp_player", 5),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", 4),
				(else_try),
					(eq, ":num_won", 0),
					(str_store_string, s0, "str_sod_4_quest_fight_guild_troops_o1"),
					(call_script, "script_change_troop_renown", "trp_player", -5),
				(else_try),
					(eq, ":num_won", 1),
					(str_store_string, s0, "str_sod_4_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 100),
					(call_script, "script_troop_add_gold", "trp_player", 100),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", 1),
				(else_try),
					(str_store_string, s0, "str_sod_4_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 200),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", 2),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_serpent_host_fight_guild_troops"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops_o4"),
					(add_xp_as_reward, 500),
					(call_script, "script_troop_add_gold", "trp_player", 2000),
					(call_script, "script_change_troop_renown", "trp_player", 25),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild5", 5),
				(else_try),
					(ge, ":num_won", 2),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 250),
					(call_script, "script_troop_add_gold", "trp_player", 1000),
					(call_script, "script_change_troop_renown", "trp_player", 5),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild5", 3),
				(else_try),
					(eq, ":num_won", 1),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 100),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild5", 1),
				(else_try),
					(eq, ":num_won", 0),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops_o1"),
					(call_script, "script_change_troop_renown", "trp_player", -10),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_serpent_host_fight_guild_troops_2"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops2_o4"),
					(add_xp_as_reward, 400),
					(call_script, "script_troop_add_gold", "trp_player", 400),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild5", 4),
				(else_try),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops2_o3"),
					(add_xp_as_reward, 200),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild5", 2),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_slavers_fight_guild_troops"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(str_store_string, s0, "str_sod_6_quest_fight_guild_troops_o4"),
					(add_xp_as_reward, 500),
					(call_script, "script_troop_add_gold", "trp_player", 1000),
					(call_script, "script_change_player_honor", -5),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild6", 4),
				(else_try),
					(eq, ":num_won", 0),
					(str_store_string, s0, "str_sod_6_quest_fight_guild_troops_o3"),
					(call_script, "script_troop_add_gold", "trp_player", 50),
				(else_try),
					(eq, ":num_won", 1),
					(str_store_string, s0, "str_sod_6_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 100),
					(call_script, "script_troop_add_gold", "trp_player", 100),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild6", 1),
				(else_try),
					(str_store_string, s0, "str_sod_6_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 200),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild6", 2),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_bc_fight_guild_troops"),
				(try_begin),
					(eq, ":num_won", ":completed"),
					(str_store_string, s0, "str_sod_7_quest_fight_guild_troops_o3"),
					(add_xp_as_reward, 400),
					(call_script, "script_troop_add_gold", "trp_player", 400),
					(call_script, "script_change_troop_renown", "trp_player", 5),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild7", 4),
				(else_try),
					(eq, ":num_won", 1),
					(str_store_string, s0, "str_sod_7_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 200),
					(call_script, "script_troop_add_gold", "trp_player", 200),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild7", 2),
				(else_try),
					(str_store_string, s0, "str_sod_7_quest_fight_guild_troops_o2"),
					(add_xp_as_reward, 100),
					(call_script, "script_troop_add_gold", "trp_player", 100),
					(call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild7", 1),
				(try_end),
			(try_end),
		(else_try),
			(assign, "$fgtq_state", fgtq_next),
			(try_begin),
				(eq, "$fight_guild_troops_quest", "qst_black_army_fight_guild_troops"),
				(try_begin),
					(eq, ":completed", 1),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_1_quest_fight_guild_troops_r1w"),
					(else_try),
						(str_store_string, s1, "str_sod_1_quest_fight_guild_troops_r1l"),
					(try_end),
					(str_store_string, s0, "str_sod_1_quest_fight_guild_troops_r2"),
				(else_try),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_1_quest_fight_guild_troops_r2w"),
					(else_try),
						(str_store_string, s1, "str_sod_1_quest_fight_guild_troops_r2l"),
					(try_end),
					(str_store_string, s0, "str_sod_1_quest_fight_guild_troops_r3"),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_conquistadors_fight_guild_troops"),
				(try_begin),
					(eq, ":completed", 1),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_2_quest_fight_guild_troops_r1w"),
					(else_try),
						(str_store_string, s1, "str_sod_2_quest_fight_guild_troops_r1l"),
					(try_end),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_r2"),
				(else_try),
					(eq, ":completed", 2),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_2_quest_fight_guild_troops_r2w"),
					(else_try),
						(str_store_string, s1, "str_sod_2_quest_fight_guild_troops_r2l"),
					(try_end),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_r3"),
				(else_try),
					(eq, ":completed", 3),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_2_quest_fight_guild_troops_r3w"),
					(else_try),
						(str_store_string, s1, "str_sod_2_quest_fight_guild_troops_r3l"),
					(try_end),
					(str_store_string, s0, "str_sod_2_quest_fight_guild_troops_r4"),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_elephant_guard_fight_guild_troops"),
				(try_begin),
					(eq, ":completed", 1),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_3_quest_fight_guild_troops_r1w"),
					(else_try),
						(str_store_string, s1, "str_sod_3_quest_fight_guild_troops_r1l"),
					(try_end),
					(str_store_string, s0, "str_sod_3_quest_fight_guild_troops_r2"),
				(else_try),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_3_quest_fight_guild_troops_r2w"),
					(else_try),
						(str_store_string, s1, "str_sod_3_quest_fight_guild_troops_r2l"),
					(try_end),
					(str_store_string, s0, "str_sod_3_quest_fight_guild_troops_r3"),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_jotnar_clan_fight_guild_troops"),
				(try_begin),
					(eq, ":completed", 1),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_4_quest_fight_guild_troops_r1w"),
					(else_try),
						(str_store_string, s1, "str_sod_4_quest_fight_guild_troops_r1l"),
					(try_end),
					(str_store_string, s0, "str_sod_4_quest_fight_guild_troops_r2"),
				(else_try),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_4_quest_fight_guild_troops_r2w"),
					(else_try),
						(str_store_string, s1, "str_sod_4_quest_fight_guild_troops_r2l"),
					(try_end),
					(str_store_string, s0, "str_sod_4_quest_fight_guild_troops_r3"),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_serpent_host_fight_guild_troops_2"),
				(try_begin),
					(eq, ":won", 1),
					(str_store_string, s1, "str_sod_5_quest_fight_guild_troops2_r1"),
					(assign, "$fgtq_state", fgtq_sh_2_next),
				(else_try),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops2_o1"),
					(assign, "$fgtq_state", fgtq_end),
					(call_script, "script_end_quest", "$fight_guild_troops_quest"),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_serpent_host_fight_guild_troops"),
				(try_begin),
					(eq, ":completed", 1),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_5_quest_fight_guild_troops_r1w"),
					(else_try),
						(str_store_string, s1, "str_sod_5_quest_fight_guild_troops_r1l"),
					(try_end),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops_r2"),
				(else_try),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_5_quest_fight_guild_troops_r2w"),
					(else_try),
						(str_store_string, s1, "str_sod_5_quest_fight_guild_troops_r2l"),
					(try_end),
					(str_store_string, s0, "str_sod_5_quest_fight_guild_troops_r3"),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_slavers_fight_guild_troops"),
				(try_begin),
					(eq, ":completed", 1),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_6_quest_fight_guild_troops_r1w"),
					(else_try),
						(str_store_string, s1, "str_sod_6_quest_fight_guild_troops_r1l"),
					(try_end),
					(str_store_string, s0, "str_sod_6_quest_fight_guild_troops_r2"),
				(else_try),
					(try_begin),
						(eq, ":won", 1),
						(str_store_string, s1, "str_sod_6_quest_fight_guild_troops_r2w"),
					(else_try),
						(str_store_string, s1, "str_sod_6_quest_fight_guild_troops_r2l"),
					(try_end),
					(str_store_string, s0, "str_sod_6_quest_fight_guild_troops_r3"),
				(try_end),
			(else_try),
				(eq, "$fight_guild_troops_quest", "qst_bc_fight_guild_troops"),
				(eq, ":completed", 1),
				(try_begin),
					(eq, ":won", 1),
					(str_store_string, s1, "str_sod_7_quest_fight_guild_troops_r1w"),
				(else_try),
					(str_store_string, s1, "str_sod_7_quest_fight_guild_troops_r1l"),
				(try_end),
				(str_store_string, s0, "str_sod_7_quest_fight_guild_troops_r2"),
			(try_end),
		(try_end),
		
		(try_begin),
			(eq, "$fight_guild_troops_quest", "qst_slavers_fight_guild_troops"),	
			(party_get_slot, ":base_scene", "$g_encountered_party", slot_town_slavers),
		(else_try),
			(party_get_slot, ":base_scene", "$g_encountered_party", slot_castle_exterior),
		(try_end),
		(assign, "$g_mt_mode", abm_visit),
		(set_jump_mission, "mt_mercenary_base_talk_to_guild_master"),
		(jump_to_scene,":base_scene"),
		(change_screen_mission),
	]),
]
