SCRIPTS = [
("generate_titles",
    [
      (try_for_range, ":troop_no", "trp_player", kingdom_heroes_end),
        (this_or_next|troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero),
        (eq, ":troop_no", "trp_player"),
        (troop_set_slot, ":troop_no", slot_troop_title, 0),
        (store_troop_faction, ":troop_faction_no", ":troop_no"),
        (assign, ":fiefs", 0),
        (try_for_range,":num",centers_begin,centers_end),
          (party_is_active, ":num"),
          (this_or_next|party_slot_eq, ":num", slot_party_type, spt_town),
          (this_or_next|party_slot_eq, ":num", slot_party_type, spt_castle),
          (party_slot_eq, ":num", slot_party_type, spt_village),
          (party_slot_eq, ":num", slot_town_lord, ":troop_no"),
          (try_begin),
            (is_between,":num",towns_begin,towns_end),
            (val_add,":fiefs",3),
          (else_try),
            (val_add,":fiefs",1),
          (try_end),
        (try_end),
        (try_begin),
          (neq, ":troop_no", "trp_player"),
          (faction_slot_eq,":troop_faction_no",slot_faction_leader,":troop_no"),
		  (faction_get_slot, ":title", ":troop_faction_no", slot_faction_ruler_title),
          (troop_set_slot, ":troop_no", slot_troop_title, ":title"),
        (else_try),
          (eq, ":troop_no", "trp_player"),
          (eq, "$g_sod_king", 1),
		  (faction_get_slot, ":title", "fac_player_supporters_faction", slot_faction_ruler_title),
          (troop_set_slot, ":troop_no", slot_troop_title, ":title"),
        (else_try),
          (neq, ":troop_no", "trp_player"),
          (faction_slot_eq,":troop_faction_no",slot_faction_marshall,":troop_no"),
		  (faction_get_slot, ":title", ":troop_faction_no", slot_faction_marshal_title),
          (troop_set_slot, ":troop_no", slot_troop_title, ":title"),
        (else_try),
          (this_or_next|eq, ":fiefs",0),
		  (eq, ":fiefs",1),
		  (faction_get_slot, ":title", ":troop_faction_no", slot_faction_t1_title),
          (troop_set_slot, ":troop_no", slot_troop_title, ":title"),
        (else_try),
          (eq, ":fiefs",2),
		  (faction_get_slot, ":title", ":troop_faction_no", slot_faction_t2_title),
          (troop_set_slot, ":troop_no", slot_troop_title, ":title"),
        (else_try),
          (ge, ":fiefs",3),
		  (faction_get_slot, ":title", ":troop_faction_no", slot_faction_t3_title),
          (troop_set_slot, ":troop_no", slot_troop_title, ":title"),
        (try_end),
      (try_end),
  ]),
]
