SCRIPTS = [
("morale_check",
                      [
					  				  
                        (try_begin),
                          (assign, ":ally_pressure", 0),
                          (try_begin),
                            (lt, "$allies_coh", 650),
                            (store_sub, ":ally_pressure", 650, "$allies_coh"),
                            (val_div, ":ally_pressure", 7),
                          (try_end),
                          (try_begin),
                            (gt, "$enemies_coh", "$allies_coh"),
                            (assign, ":ally_base", "$allies_coh"),
                            (val_max, ":ally_base", 1),
                            (store_mul, ":enemy_advantage_pct", "$enemies_coh", 100),
                            (val_div, ":enemy_advantage_pct", ":ally_base"),
                            (store_sub, ":advantage_pressure", ":enemy_advantage_pct", 125),
                            (val_div, ":advantage_pressure", 3),
                            (val_max, ":advantage_pressure", 0),
                            (val_add, ":ally_pressure", ":advantage_pressure"),
                          (try_end),
                          (val_clamp, ":ally_pressure", 0, 95),
                          (gt, ":ally_pressure", 0),
                          (call_script, "script_sod_battle_apply_courage_pressure", 0, ":ally_pressure"),
                          (call_script, "script_sod_battle_apply_courage_routs", 0),
                          (store_random_in_range, ":routed", 1, 101),
                          (assign, ":chance_ply", ":ally_pressure"),
                          (try_begin),
                            (le, ":routed", ":chance_ply"),
                            (display_message, "@Morale of your troops wavers!", red),
                            (assign, "$g_sod_battle_player_morale_wavered", 1),
                            (call_script, "script_flee_allies"),
                          (try_end),
                        (try_end),

                        (try_begin),
                          (assign, ":enemy_pressure", 0),
                          (try_begin),
                            (lt, "$enemies_coh", 650),
                            (store_sub, ":enemy_pressure", 650, "$enemies_coh"),
                            (val_div, ":enemy_pressure", 7),
                          (try_end),
                          (try_begin),
                            (gt, "$allies_coh", "$enemies_coh"),
                            (assign, ":enemy_base", "$enemies_coh"),
                            (val_max, ":enemy_base", 1),
                            (store_mul, ":ally_advantage_pct", "$allies_coh", 100),
                            (val_div, ":ally_advantage_pct", ":enemy_base"),
                            (store_sub, ":advantage_pressure", ":ally_advantage_pct", 125),
                            (val_div, ":advantage_pressure", 3),
                            (val_max, ":advantage_pressure", 0),
                            (val_add, ":enemy_pressure", ":advantage_pressure"),
                          (try_end),
                          (val_clamp, ":enemy_pressure", 0, 95),
                          (gt, ":enemy_pressure", 0),
                          (call_script, "script_sod_battle_apply_courage_pressure", 1, ":enemy_pressure"),
                          (call_script, "script_sod_battle_apply_courage_routs", 1),
                          (store_random_in_range, ":routed", 1, 101),
                          (assign, ":chance_ply", ":enemy_pressure"),
                          (try_begin),
                            (le, ":routed", ":chance_ply"),
                            (display_message, "@Morale of your enemies wavers!", green),
                            (call_script, "script_flee_enemies"),
                          (try_end),
                        (try_end),
                      ]
                    ),
]
