SCRIPTS = [
("sod_law_store_law_name",
  [
    (store_script_param_1, ":law"),
    (try_begin),
      (is_between, ":law", sod_laws_begin, sod_laws_end),
      (call_script, "script_sod_law_get_display_name_string", ":law"),
      (str_store_string, s10, reg0),
    (else_try),
      (str_store_string, s10, "@None"),
    (try_end),
  ]),

("sod_law_append_faction_law_names",
  [
    (store_script_param_1, ":faction_no"),
    (str_store_string, s70, "@"),
    (assign, ":count", 0),
    (try_for_range, ":slot", faction_laws_begin, faction_laws_end),
      (faction_get_slot, ":law", ":faction_no", ":slot"),
      (is_between, ":law", sod_laws_begin, sod_laws_end),
      (neq, ":law", sod_law_spacer_villagers),
      (neq, ":law", sod_law_spacer_townspeople),
      (neq, ":law", sod_law_spacer_clergy),
      (call_script, "script_sod_law_store_law_name", ":law"),
      (try_begin),
        (eq, ":count", 0),
        (str_store_string_reg, s70, s10),
      (else_try),
        (str_store_string, s71, "@{s70}, {s10}"),
        (str_store_string_reg, s70, s71),
      (try_end),
      (val_add, ":count", 1),
    (try_end),
    (try_begin),
      (eq, ":count", 0),
      (str_store_string, s70, "@No active laws recorded"),
    (try_end),
    (str_store_string_reg, s11, s70),
    (assign, reg0, ":count"),
  ]),

("sod_law_store_block_reason_text",
  [
    (store_script_param_1, ":reason"),
    (store_script_param_2, ":related_law"),
    (try_begin),
      (eq, ":reason", sod_law_block_capacity),
      (str_store_string, s13, "@Your realm already has the maximum number of active laws."),
    (else_try),
      (eq, ":reason", sod_law_block_already_active),
      (str_store_string, s13, "@This law is already active."),
    (else_try),
      (eq, ":reason", sod_law_block_placeholder),
      (str_store_string, s13, "@This category spacer is not an enactable law."),
    (else_try),
      (eq, ":reason", sod_law_block_invalid_law),
      (str_store_string, s13, "@This law record is invalid."),
    (else_try),
      (eq, ":reason", sod_law_block_conflict),
      (call_script, "script_sod_law_store_law_name", ":related_law"),
      (str_store_string, s13, "@Blocked by conflict with {s10}."),
    (else_try),
      (eq, ":reason", sod_law_block_missing_requirement),
      (call_script, "script_sod_law_store_law_name", ":related_law"),
      (str_store_string, s13, "@Requires {s10} first."),
    (else_try),
      (eq, ":reason", sod_law_block_cooldown),
      (str_store_string, s13, "@The realm is not ready for another legal change yet."),
    (else_try),
      (eq, ":reason", sod_law_block_unrest),
      (str_store_string, s13, "@Current unrest makes this law too dangerous to enact."),
    (else_try),
      (str_store_string, s13, "@This law cannot currently be enacted."),
    (try_end),
  ]),

("sod_law_maybe_notify_foreign_change",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (store_script_param, ":is_enactment", 3),
    (try_begin),
      (neq, ":faction_no", "fac_player_supporters_faction"),
      (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
      (store_relation, ":relation", ":faction_no", "fac_player_supporters_faction"),
      (faction_get_slot, ":intel", ":faction_no", slot_faction_intelligence_score),
      (assign, ":show", 0),
      (try_begin),
        (le, ":relation", -10),
        (assign, ":show", 1),
      (else_try),
        (ge, ":intel", 30),
        (assign, ":show", 1),
      (try_end),
      (eq, ":show", 1),
      (str_store_faction_name, s12, ":faction_no"),
      (call_script, "script_sod_law_store_law_name", ":law"),
      (try_begin),
        (eq, ":is_enactment", 1),
        (display_log_message, "@Reports from {s12}: the realm has enacted {s10}.", dark_green),
      (else_try),
        (display_log_message, "@Reports from {s12}: the realm has dismissed {s10}.", dark_blue),
      (try_end),
    (try_end),
  ]),

("sod_law_append_foreign_realm_law_report",
  [
    (assign, ":visible_faction_count", 0),
    (assign, ":hidden_faction_count", 0),
    (try_for_range, ":faction_no", kingdoms_begin, kingdoms_end),
      (neq, ":faction_no", "fac_player_supporters_faction"),
      (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
      (str_store_faction_name, s12, ":faction_no"),
      (call_script, "script_update_faction_intelligence_report", ":faction_no", 0),
      (faction_get_slot, ":intel", ":faction_no", slot_faction_intelligence_score),
      (try_begin),
        (ge, ":intel", 20),
        (val_add, ":visible_faction_count", 1),
        (call_script, "script_sod_law_recalculate_faction_law_modifiers", ":faction_no"),
        (call_script, "script_sod_law_append_faction_law_names", ":faction_no"),
        (assign, reg10, reg0),
        (faction_get_slot, reg11, ":faction_no", slot_faction_law_militarization),
        (faction_get_slot, reg12, ":faction_no", slot_faction_law_centralization),
        (faction_get_slot, reg13, ":faction_no", slot_faction_law_unrest),
        (str_store_string, s99, "@{s98}^{s12}: {reg10} known law(s), militarization {reg11}, centralization {reg12}, unrest {reg13}. {s11}"),
        (str_store_string_reg, s98, s99),
      (else_try),
        (val_add, ":hidden_faction_count", 1),
      (try_end),
    (try_end),
    (try_begin),
      (gt, ":hidden_faction_count", 0),
      (assign, reg21, ":hidden_faction_count"),
      (str_store_string, s99, "@{s98}^Unknown realms omitted due to insufficient intelligence: {reg21}."),
      (str_store_string_reg, s98, s99),
    (else_try),
      (eq, ":visible_faction_count", 0),
      (str_store_string, s99, "@{s98}^No foreign realm laws are currently known."),
      (str_store_string_reg, s98, s99),
    (try_end),
  ]),

("sod_law_append_player_compliance_report",
  [
    (assign, ":center_count", 0),
    (assign, ":loyal_count", 0),
    (assign, ":wavering_count", 0),
    (assign, ":resistant_count", 0),
    (assign, ":support_total", 0),
    (assign, ":lowest_support", 142),
    (assign, ":lowest_center", -1),
    (try_for_range, ":center_no", centers_begin, centers_end),
      (neg|party_slot_eq, ":center_no", slot_party_type, spt_castle),
      (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
      (call_script, "script_sod_law_calculate_center_tax_compliance", ":center_no"),
      (assign, ":tax_compliance", reg0),
      (assign, ":law_support", reg1),
      (val_add, ":center_count", 1),
      (val_add, ":support_total", ":law_support"),
      (try_begin),
        (lt, ":law_support", ":lowest_support"),
        (assign, ":lowest_support", ":law_support"),
        (assign, ":lowest_center", ":center_no"),
      (try_end),
      (try_begin),
        (lt, ":tax_compliance", 90),
        (val_add, ":resistant_count", 1),
      (else_try),
        (lt, ":tax_compliance", 105),
        (val_add, ":wavering_count", 1),
      (else_try),
        (val_add, ":loyal_count", 1),
      (try_end),
    (try_end),
    (try_begin),
      (gt, ":center_count", 0),
      (store_div, ":average_support", ":support_total", ":center_count"),
      (assign, reg21, ":center_count"),
      (assign, reg22, ":average_support"),
      (assign, reg23, ":loyal_count"),
      (assign, reg24, ":wavering_count"),
      (assign, reg25, ":resistant_count"),
      (str_store_party_name, s14, ":lowest_center"),
      (assign, reg26, ":lowest_support"),
      (str_store_string, s99, "@{s98}^^Local compliance:^Governed towns and villages: {reg21}^Average law support: {reg22}^Loyal/compliant: {reg23}^Wavering: {reg24}^Resisting collectors: {reg25}^Lowest support: {s14} ({reg26})"),
      (str_store_string_reg, s98, s99),
    (else_try),
      (str_store_string, s99, "@{s98}^^Local compliance:^No towns or villages are currently governed directly by your court."),
      (str_store_string_reg, s98, s99),
    (try_end),
  ]),

("sod_law_describe_center_compliance_to_s21",
  [
    (store_script_param_1, ":center_no"),
    (str_clear, s21),
    (try_begin),
      (neg|party_slot_eq, ":center_no", slot_village_state, svs_looted),
      (call_script, "script_sod_law_calculate_center_tax_compliance", ":center_no"),
      (assign, ":tax_compliance", reg0),
      (assign, reg21, reg1),
      (assign, reg22, ":tax_compliance"),
      (try_begin),
        (lt, ":tax_compliance", 90),
        (str_store_string, s21, "@ Legal mood: resistant. Law support {reg21}; collector compliance {reg22}%."),
      (else_try),
        (lt, ":tax_compliance", 105),
        (str_store_string, s21, "@ Legal mood: wary. Law support {reg21}; collector compliance {reg22}%."),
      (else_try),
        (str_store_string, s21, "@ Legal mood: compliant. Law support {reg21}; collector compliance {reg22}%."),
      (try_end),
    (try_end),
  ]),

("sod_law_describe_realm_law_report",
  [
    (call_script, "script_sod_law_migrate_player_legacy_slots"),
    (call_script, "script_sod_law_recalculate_faction_law_modifiers", "fac_player_supporters_faction"),
    (call_script, "script_sod_law_sync_player_globals_from_faction"),
    (call_script, "script_sod_law_append_faction_law_names", "fac_player_supporters_faction"),
    (assign, ":active_law_count", reg0),
    (faction_get_slot, ":peasant_tax", "fac_player_supporters_faction", slot_faction_law_tax_peasants),
    (faction_get_slot, ":town_tax", "fac_player_supporters_faction", slot_faction_law_tax_townspeople),
    (assign, reg2, ":peasant_tax"),
    (assign, reg3, ":town_tax"),
    (faction_get_slot, reg4, "fac_player_supporters_faction", slot_faction_law_village_population_modifier),
    (faction_get_slot, reg5, "fac_player_supporters_faction", slot_faction_law_town_population_modifier),
    (faction_get_slot, reg6, "fac_player_supporters_faction", slot_faction_law_holy_modifier),
    (faction_get_slot, reg7, "fac_player_supporters_faction", slot_faction_law_lord_party_size_modifier),
    (faction_get_slot, reg8, "fac_player_supporters_faction", slot_faction_law_legitimacy),
    (faction_get_slot, reg9, "fac_player_supporters_faction", slot_faction_law_unrest),
    (call_script, "script_sod_get_realm_military_centralization_profile", "fac_player_supporters_faction"),
    (assign, ":military_centralization", reg0),
    (assign, ":militarization", reg1),
    (assign, ":ruler_host_modifier", reg2),
    (assign, ":vassal_host_modifier", reg3),
    (assign, ":noble_happiness", reg4),
    (assign, ":law_unrest", reg5),
    (assign, reg14, "$g_sod_village_rep_modifier"),
    (assign, reg15, "$g_sod_town_rep_modifier"),
    (assign, reg16, "$g_sod_village_prosp_modifier"),
    (assign, reg17, "$g_sod_town_prosp_modifier"),
    (assign, reg18, "$g_sod_local_village_faith_modifier"),
    (assign, reg19, "$g_sod_local_town_faith_modifier"),
    (assign, reg20, "$g_sod_debt_to_merchants_guild"),
    (call_script, "script_sod_law_calculate_trade_tax_policy", "fac_player_supporters_faction"),
    (assign, reg21, reg0),
    (assign, reg22, reg1),
    (assign, reg23, reg2),
    (assign, reg24, reg3),
    (call_script, "script_sod_get_realm_tax_pressure_profile", "fac_player_supporters_faction"),
    (assign, ":tax_peasant_extraction", reg0),
    (assign, ":tax_merchant_tariffs", reg1),
    (assign, ":tax_noble_obligations", reg2),
    (assign, ":tax_clergy_support", reg3),
    (assign, ":tax_war_taxes", reg4),
    (assign, ":tax_social_pressure", reg5),
    (assign, ":tax_revenue_modifier", reg6),
    (assign, ":tax_recovery_modifier", reg7),
    (assign, ":tax_migration_modifier", reg8),
    (assign, ":tax_trade_volume_modifier", reg9),
    (assign, ":tax_unrest_pressure", reg10),
    (assign, ":tax_commoner_happiness", reg11),
    (assign, ":tax_merchant_happiness", reg12),
    (assign, ":tax_noble_happiness", reg13),
    (assign, ":tax_clergy_happiness", reg14),
    (assign, ":tax_tariff_capture", reg15),
    (assign, reg2, ":peasant_tax"),
    (assign, reg3, ":town_tax"),
    (assign, reg1, ":active_law_count"),
    (assign, reg30, ":military_centralization"),
    (assign, reg31, ":militarization"),
    (assign, reg32, ":ruler_host_modifier"),
    (assign, reg33, ":vassal_host_modifier"),
    (assign, reg34, ":noble_happiness"),
    (assign, reg35, ":law_unrest"),
    (assign, reg36, ":tax_peasant_extraction"),
    (assign, reg37, ":tax_merchant_tariffs"),
    (assign, reg38, ":tax_noble_obligations"),
    (assign, reg39, ":tax_clergy_support"),
    (assign, reg40, ":tax_war_taxes"),
    (assign, reg41, ":tax_social_pressure"),
    (assign, reg42, ":tax_revenue_modifier"),
    (assign, reg43, ":tax_recovery_modifier"),
    (assign, reg44, ":tax_migration_modifier"),
    (assign, reg45, ":tax_trade_volume_modifier"),
    (assign, reg46, ":tax_unrest_pressure"),
    (assign, reg47, ":tax_commoner_happiness"),
    (assign, reg48, ":tax_merchant_happiness"),
    (assign, reg49, ":tax_noble_happiness"),
    (assign, reg50, ":tax_clergy_happiness"),
    (assign, reg51, ":tax_tariff_capture"),
    (str_store_string, s98, "@Realm Law Report^^Your realm has {reg1} active law(s):^{s11}^^Realm modifiers:^Peasant tax: {reg2}%^Townspeople tax: {reg3}%^Village population growth: {reg4}%^Town population growth: {reg5}%^Holy law modifier: {reg6}%^Lord party size: {reg7}^Legitimacy: {reg8}^Unrest: {reg9}^Village relation: {reg14}^Town relation: {reg15}^Village prosperity: {reg16}^Town prosperity: {reg17}^Village faith: {reg18}^Town faith: {reg19}^Merchant guild debt: {reg20}^^Military centralization:^Centralization {reg30}^Militarization {reg31}^Ruler host modifier {reg32}^Vassal host modifier {reg33}^Noble happiness {reg34}^Unrest pressure {reg35}. Centralization concentrates hosts around the crown; decentralization strengthens vassal military estates.^^Trade tax policy:^Tax pressure: {reg21}%^Trade volume: {reg22}%^Merchant mood: {reg23}^Tariff capture: {reg24}%^^Tax social pressure:^Peasant extraction {reg36}^Merchant tariffs {reg37}^Noble obligations {reg38}^Clergy/faith support {reg39}^War taxes {reg40}^Total pressure {reg41}; revenue {reg42}%, recovery {reg43}%, migration {reg44}%, trade volume {reg45}%, tariff capture {reg51}%, unrest {reg46}.^Happiness deltas: commoners {reg47}, merchants {reg48}, nobles {reg49}, clergy {reg50}. High extraction raises immediate rents but slows wealth, merchants, migration, and recovery."),
    (call_script, "script_sod_law_append_player_compliance_report"),
    (str_store_string, s99, "@{s98}^^Foreign realm laws (shown only for realms with sufficient intelligence):"),
    (str_store_string_reg, s98, s99),
    (call_script, "script_sod_law_append_foreign_realm_law_report"),
  ]),
]
