SCRIPTS = [
("sod_law_is_active_for_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (assign, ":is_active", 0),
    (try_for_range, ":cur_law_slot", faction_laws_begin, faction_laws_end),
      (faction_slot_eq, ":faction_no", ":cur_law_slot", ":law"),
      (assign, ":is_active", 1),
    (try_end),
    (assign, reg0, ":is_active"),
  ]),

("sod_law_count_active_for_faction",
  [
    (store_script_param_1, ":faction_no"),
    (assign, ":count", 0),
    (try_for_range, ":cur_law_slot", faction_laws_begin, faction_laws_end),
      (faction_get_slot, ":law", ":faction_no", ":cur_law_slot"),
      (is_between, ":law", sod_laws_begin, sod_laws_end),
      (neq, ":law", sod_law_spacer_villagers),
      (neq, ":law", sod_law_spacer_townspeople),
      (neq, ":law", sod_law_spacer_clergy),
      (val_add, ":count", 1),
    (try_end),
    (assign, reg0, ":count"),
  ]),

("sod_law_find_empty_slot_for_faction",
  [
    (store_script_param_1, ":faction_no"),
    (assign, ":empty_slot", -1),
    (try_for_range, ":cur_law_slot", faction_laws_begin, faction_laws_end),
      (eq, ":empty_slot", -1),
      (faction_slot_eq, ":faction_no", ":cur_law_slot", 0),
      (assign, ":empty_slot", ":cur_law_slot"),
    (try_end),
    (assign, reg0, ":empty_slot"),
  ]),

("sod_law_compact_faction_laws",
  [
    (store_script_param_1, ":faction_no"),
    (assign, ":write_slot", faction_laws_begin),
    (try_for_range, ":read_slot", faction_laws_begin, faction_laws_end),
      (faction_get_slot, ":law", ":faction_no", ":read_slot"),
      (try_begin),
        (neq, ":law", 0),
        (faction_set_slot, ":faction_no", ":write_slot", ":law"),
        (val_add, ":write_slot", 1),
      (try_end),
    (try_end),
    (try_for_range, ":clear_slot", ":write_slot", faction_laws_end),
      (faction_set_slot, ":faction_no", ":clear_slot", 0),
    (try_end),
  ]),

("sod_law_sync_player_legacy_slots",
  [
    (try_for_range, ":slot", enacted_laws_begin, enacted_laws_end),
      (troop_set_slot, "trp_law", ":slot", 0),
    (try_end),
    (assign, ":legacy_slot", enacted_laws_begin),
    (try_for_range, ":faction_slot", faction_laws_begin, faction_laws_end),
      (faction_get_slot, ":law", "fac_player_supporters_faction", ":faction_slot"),
      (try_begin),
        (neq, ":law", 0),
        (lt, ":legacy_slot", enacted_laws_end),
        (troop_set_slot, "trp_law", ":legacy_slot", ":law"),
        (val_add, ":legacy_slot", 1),
      (try_end),
    (try_end),
  ]),

("sod_law_migrate_player_legacy_slots",
  [
    (try_begin),
      (neg|faction_slot_eq, "fac_player_supporters_faction", slot_faction_sod_laws_migrated, 1),
      (try_for_range, ":slot", faction_laws_begin, faction_laws_end),
        (faction_set_slot, "fac_player_supporters_faction", ":slot", 0),
      (try_end),
      (assign, ":faction_slot", faction_laws_begin),
      (try_for_range, ":legacy_slot", enacted_laws_begin, enacted_laws_end),
        (troop_get_slot, ":law", "trp_law", ":legacy_slot"),
        (try_begin),
          (is_between, ":law", sod_laws_begin, sod_laws_end),
          (neq, ":law", sod_law_spacer_villagers),
          (neq, ":law", sod_law_spacer_townspeople),
          (neq, ":law", sod_law_spacer_clergy),
          (lt, ":faction_slot", faction_laws_end),
          (faction_set_slot, "fac_player_supporters_faction", ":faction_slot", ":law"),
          (val_add, ":faction_slot", 1),
        (try_end),
      (try_end),
      (faction_set_slot, "fac_player_supporters_faction", slot_faction_sod_laws_migrated, 1),
    (try_end),
    (call_script, "script_sod_law_compact_faction_laws", "fac_player_supporters_faction"),
    (call_script, "script_sod_law_sync_player_legacy_slots"),
    (call_script, "script_sod_law_recalculate_faction_law_modifiers", "fac_player_supporters_faction"),
    (call_script, "script_sod_law_sync_player_globals_from_faction"),
  ]),

("sod_law_get_category",
  [
    (store_script_param_1, ":law"),
    (assign, ":category", sod_law_category_placeholder),
    (try_begin),
      (is_between, ":law", 1, 10),
      (assign, ":category", sod_law_category_villagers),
    (else_try),
      (is_between, ":law", 11, 20),
      (assign, ":category", sod_law_category_townspeople),
    (else_try),
      (is_between, ":law", 21, 30),
      (assign, ":category", sod_law_category_clergy),
    (else_try),
      (is_between, ":law", 31, 40),
      (assign, ":category", sod_law_category_nobility),
    (try_end),
    (try_begin),
      (this_or_next|eq, ":law", sod_law_spacer_villagers),
      (this_or_next|eq, ":law", sod_law_spacer_townspeople),
      (eq, ":law", sod_law_spacer_clergy),
      (assign, ":category", sod_law_category_placeholder),
    (try_end),
    (assign, reg0, ":category"),
  ]),

("sod_law_get_display_name_string",
  [
    (store_script_param_1, ":law"),
    (assign, reg0, law_names_begin),
    (try_begin),
      (is_between, ":law", 0, sod_laws_end),
      (store_add, reg0, law_names_begin, ":law"),
    (try_end),
  ]),

("sod_law_get_description_string",
  [
    (store_script_param_1, ":law"),
    (assign, reg0, law_descriptions_begin),
    (try_begin),
      (is_between, ":law", 0, sod_laws_end),
      (store_add, reg0, law_descriptions_begin, ":law"),
    (try_end),
  ]),

("sod_law_get_mesh",
  [
    (store_script_param_1, ":law"),
    (assign, reg0, law_meshes_begin),
    (try_begin),
      (is_between, ":law", 0, sod_laws_end),
      (store_add, reg0, law_meshes_begin, ":law"),
    (try_end),
  ]),

("sod_law_get_ai_tags",
  [
    (store_script_param_1, ":law"),
    (assign, ":tags", 0),
    (try_begin),
      (this_or_next|eq, ":law", sod_law_village_fairs),
      (this_or_next|eq, ":law", sod_law_access_to_woods),
      (this_or_next|eq, ":law", sod_law_towns_mint),
      (this_or_next|eq, ":law", sod_law_free_cities),
      (this_or_next|eq, ":law", sod_law_salt_mining),
      (eq, ":law", sod_law_mercantilism),
      (assign, ":tags", sod_law_ai_tag_economic),
      (val_add, ":tags", sod_law_ai_tag_mercantile),
    (else_try),
      (this_or_next|eq, ":law", sod_law_draft),
      (this_or_next|eq, ":law", sod_law_military_reimbursement),
      (eq, ":law", sod_law_holy_war),
      (assign, ":tags", sod_law_ai_tag_military),
      (val_add, ":tags", sod_law_ai_tag_expansionist),
    (else_try),
      (this_or_next|eq, ":law", sod_law_tithe_from_villages),
      (this_or_next|eq, ":law", sod_law_tithe_from_towns),
      (this_or_next|eq, ":law", sod_law_temple_supremacy),
      (this_or_next|eq, ":law", sod_law_royal_supremacy),
      (this_or_next|eq, ":law", sod_law_inquisition),
      (this_or_next|eq, ":law", sod_law_theocracy),
      (eq, ":law", sod_law_clergy_immunity),
      (assign, ":tags", sod_law_ai_tag_religious),
    (else_try),
      (this_or_next|eq, ":law", sod_law_enfranchisement),
      (this_or_next|eq, ":law", sod_law_low_capitation),
      (this_or_next|eq, ":law", sod_law_representation),
      (this_or_next|eq, ":law", sod_law_senate),
      (eq, ":law", sod_law_elective_monarchy),
      (assign, ":tags", sod_law_ai_tag_populist),
      (val_add, ":tags", sod_law_ai_tag_legitimizing),
    (else_try),
      (this_or_next|eq, ":law", sod_law_serfdom),
      (this_or_next|eq, ":law", sod_law_absolute_monarchy),
      (this_or_next|eq, ":law", sod_law_arbitrary_edicts),
      (eq, ":law", sod_law_high_capitation),
      (assign, ":tags", sod_law_ai_tag_centralizing),
      (val_add, ":tags", sod_law_ai_tag_oppressive),
    (else_try),
      (is_between, ":law", sod_laws_begin, sod_laws_end),
      (assign, ":tags", sod_law_ai_tag_aristocratic),
      (val_add, ":tags", sod_law_ai_tag_defensive),
    (try_end),
    (assign, reg0, ":tags"),
  ]),

("sod_law_get_conflict_mask_or_pair_checks",
  [
    (store_script_param_1, ":law"),
    (store_script_param_2, ":other_law"),
    (assign, ":conflicts", 0),
    (try_begin),
      (eq, ":law", sod_law_enfranchisement),
      (eq, ":other_law", sod_law_serfdom),
      (assign, ":conflicts", 1),
    (else_try),
      (eq, ":law", sod_law_serfdom),
      (eq, ":other_law", sod_law_enfranchisement),
      (assign, ":conflicts", 1),
    (else_try),
      (eq, ":law", sod_law_high_capitation),
      (eq, ":other_law", sod_law_low_capitation),
      (assign, ":conflicts", 1),
    (else_try),
      (eq, ":law", sod_law_low_capitation),
      (eq, ":other_law", sod_law_high_capitation),
      (assign, ":conflicts", 1),
    (else_try),
      (eq, ":law", sod_law_low_town_taxes),
      (eq, ":other_law", sod_law_high_town_taxes),
      (assign, ":conflicts", 1),
    (else_try),
      (eq, ":law", sod_law_high_town_taxes),
      (eq, ":other_law", sod_law_low_town_taxes),
      (assign, ":conflicts", 1),
    (else_try),
      (eq, ":law", sod_law_temple_supremacy),
      (eq, ":other_law", sod_law_royal_supremacy),
      (assign, ":conflicts", 1),
    (else_try),
      (eq, ":law", sod_law_royal_supremacy),
      (eq, ":other_law", sod_law_temple_supremacy),
      (assign, ":conflicts", 1),
    (else_try),
      (this_or_next|eq, ":law", sod_law_senate),
      (this_or_next|eq, ":law", sod_law_absolute_monarchy),
      (this_or_next|eq, ":law", sod_law_elective_monarchy),
      (eq, ":law", sod_law_theocracy),
      (this_or_next|eq, ":other_law", sod_law_senate),
      (this_or_next|eq, ":other_law", sod_law_absolute_monarchy),
      (this_or_next|eq, ":other_law", sod_law_elective_monarchy),
      (eq, ":other_law", sod_law_theocracy),
      (neq, ":law", ":other_law"),
      (assign, ":conflicts", 1),
    (try_end),
    (assign, reg0, ":conflicts"),
  ]),

("sod_law_get_required_law_checks",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (assign, ":passes", 1),
    (assign, ":required_law", 0),
    (try_begin),
      (eq, ":law", sod_law_holy_war),
      (call_script, "script_sod_law_is_active_for_faction", ":faction_no", sod_law_theocracy),
      (eq, reg0, 0),
      (assign, ":passes", 0),
      (assign, ":required_law", sod_law_theocracy),
    (else_try),
      (eq, ":law", sod_law_theocracy),
      (call_script, "script_sod_law_is_active_for_faction", ":faction_no", sod_law_temple_supremacy),
      (assign, ":temple", reg0),
      (call_script, "script_sod_law_is_active_for_faction", ":faction_no", sod_law_royal_supremacy),
      (assign, ":royal", reg0),
      (eq, ":temple", 0),
      (eq, ":royal", 0),
      (assign, ":passes", 0),
      (assign, ":required_law", sod_law_temple_supremacy),
    (try_end),
    (assign, reg0, ":passes"),
    (assign, reg1, ":required_law"),
  ]),

("sod_law_can_enact_for_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (assign, ":allowed", 1),
    (assign, ":reason", sod_law_block_none),
    (assign, ":related_law", 0),
    (try_begin),
      (this_or_next|lt, ":law", sod_laws_begin),
      (ge, ":law", sod_laws_end),
      (assign, ":allowed", 0),
      (assign, ":reason", sod_law_block_invalid_law),
    (else_try),
      (this_or_next|eq, ":law", sod_law_spacer_villagers),
      (this_or_next|eq, ":law", sod_law_spacer_townspeople),
      (eq, ":law", sod_law_spacer_clergy),
      (assign, ":allowed", 0),
      (assign, ":reason", sod_law_block_placeholder),
    (else_try),
      (call_script, "script_sod_law_is_active_for_faction", ":faction_no", ":law"),
      (eq, reg0, 1),
      (assign, ":allowed", 0),
      (assign, ":reason", sod_law_block_already_active),
    (else_try),
      (call_script, "script_sod_law_find_empty_slot_for_faction", ":faction_no"),
      (eq, reg0, -1),
      (assign, ":allowed", 0),
      (assign, ":reason", sod_law_block_capacity),
    (else_try),
      (assign, ":conflict", 0),
      (try_for_range, ":slot", faction_laws_begin, faction_laws_end),
        (eq, ":conflict", 0),
        (faction_get_slot, ":other_law", ":faction_no", ":slot"),
        (call_script, "script_sod_law_get_conflict_mask_or_pair_checks", ":law", ":other_law"),
        (eq, reg0, 1),
        (assign, ":conflict", ":other_law"),
      (try_end),
      (gt, ":conflict", 0),
      (assign, ":allowed", 0),
      (assign, ":reason", sod_law_block_conflict),
      (assign, ":related_law", ":conflict"),
    (else_try),
      (call_script, "script_sod_law_get_required_law_checks", ":faction_no", ":law"),
      (eq, reg0, 0),
      (assign, ":allowed", 0),
      (assign, ":reason", sod_law_block_missing_requirement),
      (assign, ":related_law", reg1),
    (else_try),
      (faction_get_slot, ":unrest", ":faction_no", slot_faction_law_unrest),
      (ge, ":unrest", 18),
      (call_script, "script_sod_law_get_ai_tags", ":law"),
      (assign, ":tags", reg0),
      (store_and, ":is_oppressive", ":tags", sod_law_ai_tag_oppressive),
      (try_begin),
        (this_or_next|gt, ":is_oppressive", 0),
        (this_or_next|eq, ":law", sod_law_high_town_taxes),
        (this_or_next|eq, ":law", sod_law_inquisition),
        (this_or_next|eq, ":law", sod_law_holy_war),
        (this_or_next|eq, ":law", sod_law_draft),
        (eq, ":law", sod_law_arbitrary_edicts),
        (assign, ":allowed", 0),
        (assign, ":reason", sod_law_block_unrest),
      (try_end),
    (try_end),
    (assign, reg0, ":allowed"),
    (assign, reg1, ":reason"),
    (assign, reg2, ":related_law"),
  ]),

("sod_law_can_dismiss_for_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (assign, ":allowed", 0),
    (assign, ":reason", sod_law_block_invalid_law),
    (try_begin),
      (call_script, "script_sod_law_is_active_for_faction", ":faction_no", ":law"),
      (eq, reg0, 1),
      (assign, ":allowed", 1),
      (assign, ":reason", sod_law_block_none),
    (try_end),
    (assign, reg0, ":allowed"),
    (assign, reg1, ":reason"),
    (assign, reg2, 0),
  ]),

("sod_law_get_block_reason",
  [
    (store_script_param_1, ":reason"),
    (assign, reg0, "str_sod_law_description_blank"),
    (try_begin),
      (eq, ":reason", sod_law_block_none),
      (assign, reg0, "str_sod_law_description_blank"),
    (else_try),
      (eq, ":reason", sod_law_block_invalid_law),
      (assign, reg0, "str_sod_law_description_blank"),
    (else_try),
      (eq, ":reason", sod_law_block_placeholder),
      (assign, reg0, "str_sod_law_description_blank"),
    (else_try),
      (eq, ":reason", sod_law_block_already_active),
      (assign, reg0, "str_sod_law_description_blank"),
    (else_try),
      (eq, ":reason", sod_law_block_capacity),
      (assign, reg0, "str_sod_law_description_blank"),
    (else_try),
      (eq, ":reason", sod_law_block_conflict),
      (assign, reg0, "str_sod_law_description_blank"),
    (else_try),
      (eq, ":reason", sod_law_block_missing_requirement),
      (assign, reg0, "str_sod_law_description_blank"),
    (try_end),
  ]),

("sod_law_add_to_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (call_script, "script_sod_law_can_enact_for_faction", ":faction_no", ":law"),
    (assign, ":allowed", reg0),
    (assign, ":reason", reg1),
    (try_begin),
      (eq, ":allowed", 1),
      (call_script, "script_sod_law_find_empty_slot_for_faction", ":faction_no"),
      (assign, ":empty_slot", reg0),
      (ge, ":empty_slot", faction_laws_begin),
      (faction_set_slot, ":faction_no", ":empty_slot", ":law"),
      (call_script, "script_sod_law_apply_enactment_costs", ":faction_no", ":law"),
      (call_script, "script_sod_law_compact_faction_laws", ":faction_no"),
      (call_script, "script_sod_law_recalculate_faction_law_modifiers", ":faction_no"),
      (try_begin),
        (eq, ":faction_no", "fac_player_supporters_faction"),
        (call_script, "script_sod_law_sync_player_legacy_slots"),
        (call_script, "script_sod_law_sync_player_globals_from_faction"),
      (else_try),
        (call_script, "script_sod_law_maybe_notify_foreign_change", ":faction_no", ":law", 1),
      (try_end),
    (try_end),
    (assign, reg0, ":allowed"),
    (assign, reg1, ":reason"),
  ]),

("sod_law_remove_from_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (call_script, "script_sod_law_can_dismiss_for_faction", ":faction_no", ":law"),
    (assign, ":allowed", reg0),
    (assign, ":reason", reg1),
    (try_begin),
      (eq, ":allowed", 1),
      (assign, ":done", 0),
      (try_for_range, ":slot", faction_laws_begin, faction_laws_end),
        (eq, ":done", 0),
        (faction_slot_eq, ":faction_no", ":slot", ":law"),
        (faction_set_slot, ":faction_no", ":slot", 0),
        (assign, ":done", 1),
      (try_end),
      (call_script, "script_sod_law_apply_dismissal_costs", ":faction_no", ":law"),
      (call_script, "script_sod_law_compact_faction_laws", ":faction_no"),
      (call_script, "script_sod_law_recalculate_faction_law_modifiers", ":faction_no"),
      (try_begin),
        (eq, ":faction_no", "fac_player_supporters_faction"),
        (call_script, "script_sod_law_sync_player_legacy_slots"),
        (call_script, "script_sod_law_sync_player_globals_from_faction"),
      (else_try),
        (call_script, "script_sod_law_maybe_notify_foreign_change", ":faction_no", ":law", 0),
      (try_end),
    (try_end),
    (assign, reg0, ":allowed"),
    (assign, reg1, ":reason"),
  ]),
]
