SCRIPTS = [
("sod_law_get_weight_for_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (assign, ":weight", 10),
    (call_script, "script_sod_law_get_ai_tags", ":law"),
    (assign, ":tags", reg0),
    (faction_get_slot, ":ambition", ":faction_no", slot_faction_ambition),
    (faction_get_slot, ":power", ":faction_no", slot_faction_current_power),
    (faction_get_slot, ":economy", ":faction_no", slot_faction_economic_strength),
    (faction_get_slot, ":badboy", ":faction_no", slot_faction_badboy_rating),
    (faction_get_slot, ":unrest", ":faction_no", slot_faction_law_unrest),
    (try_begin),
      (ge, ":ambition", 70),
      (this_or_next|eq, ":law", sod_law_draft),
      (this_or_next|eq, ":law", sod_law_military_reimbursement),
      (this_or_next|eq, ":law", sod_law_holy_war),
      (eq, ":law", sod_law_absolute_monarchy),
      (val_add, ":weight", 30),
    (try_end),
    (try_begin),
      (ge, ":economy", 70),
      (this_or_next|eq, ":law", sod_law_towns_mint),
      (this_or_next|eq, ":law", sod_law_free_cities),
      (this_or_next|eq, ":law", sod_law_mercantilism),
      (eq, ":law", sod_law_low_town_taxes),
      (val_add, ":weight", 25),
    (try_end),
    (try_begin),
      (lt, ":power", 50),
      (this_or_next|eq, ":law", sod_law_draft),
      (this_or_next|eq, ":law", sod_law_serfdom),
      (eq, ":law", sod_law_high_capitation),
      (val_add, ":weight", 18),
    (try_end),
    (try_begin),
      (ge, ":badboy", 20),
      (this_or_next|eq, ":law", sod_law_holy_war),
      (eq, ":law", sod_law_inquisition),
      (val_add, ":weight", 15),
    (try_end),
    (try_begin),
      (ge, ":unrest", 12),
      (this_or_next|eq, ":law", sod_law_high_capitation),
      (this_or_next|eq, ":law", sod_law_high_town_taxes),
      (this_or_next|eq, ":law", sod_law_arbitrary_edicts),
      (eq, ":law", sod_law_inquisition),
      (val_sub, ":weight", 40),
    (try_end),
    (try_begin),
      (eq, ":tags", 0),
      (assign, ":weight", -1000),
    (try_end),
    (assign, reg0, ":weight"),
  ]),

("sod_law_ai_apply_stability_adjustment",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (store_script_param, ":base_weight", 3),
    (assign, ":weight", ":base_weight"),
    (call_script, "script_sod_law_get_ai_tags", ":law"),
    (assign, ":tags", reg0),
    (faction_get_slot, ":unrest", ":faction_no", slot_faction_law_unrest),
    (faction_get_slot, ":legitimacy", ":faction_no", slot_faction_law_legitimacy),
    (store_and, ":is_oppressive", ":tags", sod_law_ai_tag_oppressive),
    (store_and, ":is_legitimizing", ":tags", sod_law_ai_tag_legitimizing),
    (store_and, ":is_populist", ":tags", sod_law_ai_tag_populist),
    (store_and, ":is_centralizing", ":tags", sod_law_ai_tag_centralizing),
    (try_begin),
      (ge, ":unrest", 8),
      (gt, ":is_oppressive", 0),
      (store_mul, ":risk_penalty", ":unrest", 2),
      (val_sub, ":weight", ":risk_penalty"),
    (try_end),
    (try_begin),
      (ge, ":unrest", 8),
      (this_or_next|gt, ":is_legitimizing", 0),
      (gt, ":is_populist", 0),
      (store_mul, ":recovery_bonus", ":unrest", 2),
      (val_add, ":weight", ":recovery_bonus"),
    (try_end),
    (try_begin),
      (lt, ":legitimacy", 0),
      (gt, ":is_legitimizing", 0),
      (store_mul, ":legitimacy_need", ":legitimacy", -1),
      (val_add, ":weight", ":legitimacy_need"),
      (val_add, ":weight", 10),
    (try_end),
    (try_begin),
      (lt, ":legitimacy", 0),
      (gt, ":is_oppressive", 0),
      (val_sub, ":weight", 15),
    (try_end),
    (try_begin),
      (ge, ":legitimacy", 12),
      (le, ":unrest", 6),
      (gt, ":is_centralizing", 0),
      (val_add, ":weight", 10),
    (try_end),
    (assign, reg0, ":weight"),
  ]),

("sod_law_ai_score_law_for_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_script_param_2, ":law"),
    (call_script, "script_sod_law_can_enact_for_faction", ":faction_no", ":law"),
    (try_begin),
      (eq, reg0, 1),
      (call_script, "script_sod_law_get_weight_for_faction", ":faction_no", ":law"),
      (call_script, "script_sod_law_ai_apply_stability_adjustment", ":faction_no", ":law", reg0),
    (else_try),
      (assign, reg0, -1000),
    (try_end),
  ]),

("sod_law_ai_pick_law_to_enact",
  [
    (store_script_param_1, ":faction_no"),
    (assign, ":best_law", 0),
    (assign, ":best_score", -1000),
    (try_for_range, ":law", sod_laws_begin, sod_laws_end),
      (call_script, "script_sod_law_ai_score_law_for_faction", ":faction_no", ":law"),
      (assign, ":score", reg0),
      (gt, ":score", ":best_score"),
      (assign, ":best_score", ":score"),
      (assign, ":best_law", ":law"),
    (try_end),
    (assign, reg0, ":best_law"),
    (assign, reg1, ":best_score"),
  ]),

("sod_law_ai_pick_law_to_dismiss",
  [
    (store_script_param_1, ":faction_no"),
    (assign, ":worst_law", 0),
    (assign, ":worst_score", 1000),
    (try_for_range, ":slot", faction_laws_begin, faction_laws_end),
      (faction_get_slot, ":law", ":faction_no", ":slot"),
      (is_between, ":law", sod_laws_begin, sod_laws_end),
      (call_script, "script_sod_law_get_weight_for_faction", ":faction_no", ":law"),
      (call_script, "script_sod_law_ai_apply_stability_adjustment", ":faction_no", ":law", reg0),
      (assign, ":score", reg0),
      (lt, ":score", ":worst_score"),
      (assign, ":worst_score", ":score"),
      (assign, ":worst_law", ":law"),
    (try_end),
    (assign, reg0, ":worst_law"),
    (assign, reg1, ":worst_score"),
  ]),

("sod_law_ai_process_faction",
  [
    (store_script_param_1, ":faction_no"),
    (store_current_day, ":cur_day"),
    (faction_get_slot, ":cooldown_day", ":faction_no", slot_faction_sod_law_cooldown_day),
    (try_begin),
      (le, ":cooldown_day", ":cur_day"),
      (call_script, "script_sod_law_recalculate_faction_law_modifiers", ":faction_no"),
      (faction_get_slot, ":unrest", ":faction_no", slot_faction_law_unrest),
      (try_begin),
        (ge, ":unrest", 18),
        (call_script, "script_sod_law_ai_pick_law_to_dismiss", ":faction_no"),
        (assign, ":law", reg0),
        (gt, ":law", 0),
        (call_script, "script_sod_law_remove_from_faction", ":faction_no", ":law"),
      (else_try),
        (call_script, "script_sod_law_ai_pick_law_to_enact", ":faction_no"),
        (assign, ":law", reg0),
        (assign, ":score", reg1),
        (gt, ":score", 15),
        (call_script, "script_sod_law_add_to_faction", ":faction_no", ":law"),
      (try_end),
      (store_add, ":next_day", ":cur_day", 21),
      (faction_set_slot, ":faction_no", slot_faction_sod_law_cooldown_day, ":next_day"),
    (try_end),
  ]),

("sod_law_ai_process_all_factions",
  [
    (try_for_range, ":faction_no", kingdoms_begin, kingdoms_end),
      (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
      (neq, ":faction_no", "fac_player_supporters_faction"),
      (call_script, "script_sod_law_ai_process_faction", ":faction_no"),
    (try_end),
  ]),
]
