SCRIPTS = [
("sod_initialize_strategy_advisor",
[
(troop_clear_inventory, "trp_sod_strategy_advisor"),

#Universal items,
(troop_add_item, "trp_sod_strategy_advisor", "itm_legion_sword_centurion", 0),


#Faction specific equipment
(try_begin),
(eq, "$g_sod_country", cb_antares),
(troop_add_item, "trp_sod_strategy_advisor", "itm_bascinet", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_antplate6", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_mail_mittens", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_mail_boots", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_antshield2", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_shortened_military_scythe", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_war_spear", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_anthorse1", 0),
(else_try),
(eq, "$g_sod_country", cb_marina),
(troop_add_item, "trp_sod_strategy_advisor", "itm_marhelm2", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_marchain2", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_darkgauntlets", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_marboots1", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_tab_shield_round_c", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_light_crossbow", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_steel_bolts", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_warhorse", 0),
(else_try),
(eq, "$g_sod_country", cb_aden),
(troop_add_item, "trp_sod_strategy_advisor", "itm_bascinetnasal", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_heraldic_mail_with_tabard", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_mail_mittens", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_mail_boots", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_lance", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_fighting_axe", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_shield_heater_generic_c", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_warhorse", 0),
(else_try),
(eq, "$g_sod_country", cb_villian),
(troop_add_item, "trp_sod_strategy_advisor", "itm_villhelm2", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_vilarmor_10", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_villgloves2", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_villboots2", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_villshield", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_long_bow", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_barbed_arrows", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_vilhorse1", 0),
(else_try),
(eq, "$g_sod_country", cb_zerrikan),
(troop_add_item, "trp_sod_strategy_advisor", "itm_oprichnik_helm", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_oprichnik_armor", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_mail_mittens", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_oprichnik_boots", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_arena_lance", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_decor_red2_shield", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_throwing_decor_hammer", 0),
(troop_add_item, "trp_sod_strategy_advisor", "itm_rok_oprichnik_charger", 0),
(try_end),
(troop_equip_items, "trp_sod_strategy_advisor"),
    ]
  ),
]
