SCRIPTS = [
("spawn_bandits",
      [(set_spawn_radius, 1),
        (try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_mountain_bandits"),
          (lt, ":num_parties", 12),
          (store_random, ":spawn_point", num_mountain_bandit_spawn_points),
          (val_add, ":spawn_point", "p_mountain_bandit_spawn_point"),
          (spawn_around_party, ":spawn_point", "pt_mountain_bandits"),
        (try_end),
        (try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_forest_bandits"),
          (lt, ":num_parties", 12),
          (store_random, ":spawn_point", num_mountain_bandit_spawn_points),
          (val_add, ":spawn_point", "p_forest_bandit_spawn_point"),
          (spawn_around_party, ":spawn_point", "pt_forest_bandits"),
        (try_end),
        (try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_sea_raiders"),
          (lt, ":num_parties", 12),
          (store_random, ":spawn_point", num_sea_raider_spawn_points),
          (val_add, ":spawn_point", "p_sea_raider_spawn_point_1"),
          (spawn_around_party, ":spawn_point", "pt_sea_raiders"),
        (try_end),
		(try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_boar_clan_fighters"),
          (lt, ":num_parties", 6),
		  (store_random_in_range, ":rand_town", 0, 3),
		  (try_begin),
			(eq, ":rand_town", 0),
			(assign, ":rand_town", "p_town_18"),
		  (else_try),
			(eq, ":rand_town", 1),
			(assign, ":rand_town", "p_town_3"),
		  (else_try),
			(assign, ":rand_town", "p_town_15"),
		  (try_end),
          (spawn_around_party, ":rand_town", "pt_boar_clan_fighters"),
		  (assign, ":new_party", reg0),
		  (party_set_banner_icon, ":new_party", "icon_banner_297"),
		  (try_begin),
			  (store_character_level, ":level", "trp_player"),
			  (val_div, ":level", 5),
			  (gt, ":level", 0),
			  (try_for_range, ":unused2", 0, ":level"),
				(party_add_template, ":new_party", "pt_boar_clan_reinforcements"),
			  (try_end),
		  (try_end),
		(try_end),
		(try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_boar_clan_fighters_desert"),
          (lt, ":num_parties", 10),
		  (store_random_in_range, ":rand", 0, 6),
		  (try_for_range, ":unused", 0, ":rand"),
			(spawn_around_party, "p_sod_merc_guild_7", "pt_boar_clan_fighters_desert"),
			(assign, ":new_party", reg0),
			(party_set_banner_icon, ":new_party", "icon_banner_297"),
			(store_character_level, ":level", "trp_player"),
			(val_div, ":level", 5),
			(gt, ":level", 0),
			(try_for_range, ":unused2", 0, ":level"),
				(party_add_template, ":new_party", "pt_boar_clan_reinforcements"),
			(try_end),
		  (try_end),
        (try_end),
        (try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_steppe_bandits"),
          (lt, ":num_parties", 8),
          (store_random, ":spawn_point", num_steppe_bandit_spawn_points),
          (val_add, ":spawn_point", "p_steppe_bandit_spawn_point"),
          (spawn_around_party, ":spawn_point", "pt_steppe_bandits"),
        (try_end),
        (try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_bandits"),
          (lt, ":num_parties", 90),
		  (store_sub, ":missing_parties", 90, ":num_parties"),
		  (store_div, ":max_spawn_batches", ":missing_parties", 12),
		  (val_add, ":max_spawn_batches", 1),
		  (val_min, ":max_spawn_batches", 8),
		  (val_max, ":max_spawn_batches", 2),
		  (store_random_in_range, ":rand", 1, ":max_spawn_batches"),
		  (try_for_range, ":unused", 0, ":rand"),
			  (store_random_in_range, ":spawn_point", villages_begin, villages_end),
			  (spawn_around_party, ":spawn_point", "pt_bandits"),
			  (assign, ":spawned_party_id", reg0),
			  (store_character_level, ":level", "trp_player"),
			  (val_div, ":level", 5),
			  (gt, ":level", 0),
			  (try_for_range, ":unused2", 0, ":level"),
				(party_add_template, ":spawned_party_id", "pt_bandit_reinfocements"),
			  (try_end),
			  (try_begin),
                (check_quest_active, "qst_deal_with_looters"),
                (party_set_flags, ":spawned_party_id", pf_quest_party, 1),
              (else_try),
                (party_set_flags, ":spawned_party_id", pf_quest_party, 0),
              (try_end),
			  (assign, ":bandit_target", -1),
			  (assign, ":bandit_target_threat", 0),
			  (assign, ":bandit_target_score", -1000),
			  (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
			    (store_distance_to_party_from_party, ":center_dist", ":spawn_point", ":center_no"),
			    (lt, ":center_dist", 45),
			    (call_script, "script_get_center_threat_level", ":center_no"),
			    (assign, ":center_threat", reg0),
			    (gt, ":center_threat", 0),
			    (assign, ":center_score", ":center_threat"),
			    (store_mul, ":center_bonus", ":center_threat", 5),
			    (val_add, ":center_score", ":center_bonus"),
			    (val_sub, ":center_score", ":center_dist"),
			    (store_random_in_range, ":center_jitter", 0, 5),
			    (val_add, ":center_score", ":center_jitter"),
			    (try_begin),
			      (gt, ":center_score", ":bandit_target_score"),
			      (assign, ":bandit_target_score", ":center_score"),
			      (assign, ":bandit_target", ":center_no"),
			      (assign, ":bandit_target_threat", ":center_threat"),
			    (try_end),
			  (try_end),
			  (try_begin),
			    (gt, ":bandit_target", 0),
			    (store_random_in_range, ":bandit_ai_roll", 0, 100),
			    (assign, ":bandit_raid_chance", 15),
			    (store_mul, ":bandit_threat_bonus", ":bandit_target_threat", 8),
			    (val_add, ":bandit_raid_chance", ":bandit_threat_bonus"),
			    (store_div, ":bandit_missing_bonus", ":missing_parties", 4),
			    (val_add, ":bandit_raid_chance", ":bandit_missing_bonus"),
			    (val_clamp, ":bandit_raid_chance", 15, 85),
			    (try_begin),
			      (lt, ":bandit_ai_roll", ":bandit_raid_chance"),
			      (call_script, "script_party_set_ai_state", ":spawned_party_id", spai_raiding_around_center, ":bandit_target"),
			    (else_try),
			      (call_script, "script_party_set_ai_state", ":spawned_party_id", spai_patrolling_around_center, ":bandit_target"),
			    (try_end),
			  (else_try),
			    (call_script, "script_party_set_ai_state", ":spawned_party_id", spai_holding_center, ":spawn_point"),
			  (try_end),
		  (try_end),
        (try_end),
        (try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_deserters"),
          (lt, ":num_parties", 15),
          (set_spawn_radius, 4),
          (try_for_range, ":troop_no", kingdom_heroes_begin, kingdom_heroes_end),
			(store_troop_faction, ":troop_fac", ":troop_no"),
			(is_between, ":troop_fac", "fac_kingdom_1", "fac_kingdoms_end"),
            (troop_get_slot, ":party_no", ":troop_no", slot_troop_leaded_party),
            (gt, ":party_no", 0),
            (neg|party_is_in_any_town, ":party_no"),
            (store_party_size, ":party_size", ":party_no"),
            (ge, ":party_size", 20),
            (store_random_in_range, ":random_no", 0, 100),
            (lt, ":random_no", 5),
            (spawn_around_party, ":party_no", "pt_deserters"),
            (assign, ":new_party", reg0),
            (store_troop_faction, ":faction_no", ":troop_no"),
            (faction_get_slot, ":tier_1_troop", ":faction_no", slot_faction_tier_1_troop),
            (store_div, ":number_to_add", ":party_size", 8),
            (val_add, ":number_to_add", 3),
            (val_clamp, ":number_to_add", 5, 20),
            (party_add_members, ":new_party", ":tier_1_troop", ":number_to_add"),
            (store_random_in_range, ":random_no", 1, 4),
            (try_for_range, ":unused", 0, ":random_no"),
              (call_script, "script_cf_party_upgrade_with_xp", ":new_party", 100000),
            (try_end),
            (call_script, "script_get_closest_walled_center", ":party_no"),
            (assign, ":deserter_target", reg0),
            (try_begin),
              (gt, ":deserter_target", 0),
              (call_script, "script_party_set_ai_state", ":new_party", spai_patrolling_around_center, ":deserter_target"),
            (else_try),
              (call_script, "script_party_set_ai_state", ":new_party", spai_holding_center, ":party_no"),
            (try_end),
          (try_end),
        (try_end),
		(try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_sod_deserters"),
          (lt, ":num_parties", 15),
          (set_spawn_radius, 10),
          (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
            (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
            (party_get_slot, ":center_health", ":center_no", slot_center_sod_local_health),
            (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
            (store_sub, ":surplus", ":center_population", town_pop_min),
            (val_max, ":surplus", 0),
            (gt, ":surplus", 25),
            (lt, ":center_health", 60),
            (lt, ":prosperity", 60),
            (store_random_in_range, ":random_no", 0, 100),
            (lt, ":random_no", 10),
            (store_div, ":number_to_add", ":surplus", 12),
            (val_add, ":number_to_add", 5),
            (val_clamp, ":number_to_add", 5, 18),
            (val_sub, ":center_population", ":number_to_add"),
            (val_max, ":center_population", town_pop_min),
            (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
            (spawn_around_party, ":center_no", "pt_sod_deserters"),
            (assign, ":new_party", reg0),
            (store_character_level, ":level", "trp_player"),
			(val_div, ":level", 7),
			(val_max, ":level", 1),
			(store_random_in_range, ":rand", 0, 10),
			(try_begin),
				(eq, ":rand", 0),
				(assign, ":reinforcement_template", "pt_sod_1_reinforcements_a"),
			(else_try),
				(eq, ":rand", 1),
				(assign, ":reinforcement_template", "pt_sod_1_reinforcements_b"),
			(else_try),
				(eq, ":rand", 2),
				(assign, ":reinforcement_template", "pt_sod_2_reinforcements_a"),
			(else_try),
				(eq, ":rand", 3),
				(assign, ":reinforcement_template", "pt_sod_2_reinforcements_b"),
			(else_try),
				(eq, ":rand", 4),
				(assign, ":reinforcement_template", "pt_sod_3_reinforcements_a"),
			(else_try),
				(eq, ":rand", 5),
				(assign, ":reinforcement_template", "pt_sod_3_reinforcements_b"),
			(else_try),
				(eq, ":rand", 6),
				(assign, ":reinforcement_template", "pt_sod_4_reinforcements_a"),
			(else_try),
				(eq, ":rand", 7),
				(assign, ":reinforcement_template", "pt_sod_4_reinforcements_b"),
			(else_try),
				(eq, ":rand", 8),
				(assign, ":reinforcement_template", "pt_sod_5_reinforcements_a"),
			(else_try),
				(eq, ":rand", 9),
				(assign, ":reinforcement_template", "pt_sod_5_reinforcements_b"),
			(try_end),
			(try_for_range, ":unused", 0, ":level"),
				(party_add_template, ":new_party", ":reinforcement_template"),
			(try_end),
            (call_script, "script_party_set_ai_state", ":new_party", spai_patrolling_around_center, ":center_no"),
          (try_end),
        (try_end),
		(try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_sod_merc_deserters"),
          (lt, ":num_parties", 6),
          (set_spawn_radius, 15),
          (try_for_range, ":center_no", "p_sod_merc_guild_1", "p_spawn_points_end"),
            (spawn_around_party, ":center_no", "pt_sod_merc_deserters"),
            (assign, ":new_party", reg0),
            (store_faction_of_party, ":faction_no", ":center_no"),
			(store_random_in_range, ":rand", 0, 2),
			(try_begin),
				(eq, ":rand", 0),
				(assign, ":troop_slot", slot_guild_tier_1_unit_1),
			(else_try),
				(eq, ":rand", 1),
				(assign, ":troop_slot", slot_guild_tier_1_unit_2),
			(try_end),
            (faction_get_slot, ":tier_1_troop", ":faction_no", ":troop_slot"),
            (store_character_level, ":level", "trp_player"),
            (store_mul, ":max_number_to_add", ":level", 2),
            (val_add, ":max_number_to_add", 19),
            (store_random_in_range, ":number_to_add", 15, ":max_number_to_add"),
            (party_add_members, ":new_party", ":tier_1_troop", ":number_to_add"),
            (call_script, "script_cf_party_upgrade_with_xp", ":new_party", 10000),
            (call_script, "script_party_set_ai_state", ":new_party", spai_holding_center, ":center_no"),
          (try_end),
        (try_end),
        (try_begin),
          (store_num_parties_of_template, ":num_parties", "pt_mercenaries"),
          (lt, ":num_parties", 30),
          (store_random_in_range, ":spawn_point", towns_begin, towns_end),
          (spawn_around_party, ":spawn_point", "pt_mercenaries"),
		  (store_random_in_range, ":random_no", 1, 4),
          (try_for_range, ":unused", 0, ":random_no"),
              (call_script, "script_cf_party_upgrade_with_xp", reg0, 150000),
          (try_end),
        (try_end),
    ]),
]
