SCRIPTS = [
("tick_mercenary_walkers",
      [(try_for_agents, ":cur_agent"),
		  (agent_get_entry_no, ":starting_entry", ":cur_agent"),
		  (is_between, ":starting_entry", 11, 20),
          (agent_get_slot, ":target_entry_point", ":cur_agent", 0),
		  
		(assign, reg0, 11),
        (assign, reg1, 12),
        (assign, reg2, 13),
        (assign, reg3, 14),
        (assign, reg4, 15),
        (assign, reg5, 16),
        (assign, reg6, 17),
        (assign, reg7, 18),
        (assign, reg8, 19),
        (assign, reg9, 20),
          (try_begin),
            (eq, ":target_entry_point", 11),
            (assign, reg0, 0),
          (else_try),
            (eq, ":target_entry_point", 12),
            (assign, reg1, 0),
          (else_try),
            (eq, ":target_entry_point", 13),
            (assign, reg2, 0),
          (else_try),
            (eq, ":target_entry_point", 14),
            (assign, reg3, 0),
          (else_try),
            (eq, ":target_entry_point", 15),
            (assign, reg4, 0),
          (else_try),
            (eq, ":target_entry_point", 16),
            (assign, reg5, 0),
          (else_try),
            (eq, ":target_entry_point", 17),
            (assign, reg6, 0),
          (else_try),
            (eq, ":target_entry_point", 18),
            (assign, reg7, 0),
          (else_try),
            (eq, ":target_entry_point", 19),
            (assign, reg8, 0),
          (else_try),
            (eq, ":target_entry_point", 20),
            (assign, reg9, 0),
          (try_end),
        (assign, ":try_limit", 100),
        (assign, ":target_entry_point", 0),
        (try_for_range, ":unused", 0, ":try_limit"),
          (shuffle_range, 0, 10),
          (gt, reg0, 0),
          (assign, ":target_entry_point", reg0),
          (assign, ":try_limit", 0),
        (try_end),
        (try_begin),
          (gt, ":target_entry_point", 0),
          (agent_set_slot, ":cur_agent", 0, ":target_entry_point"),
          (entry_point_get_position, pos1, ":target_entry_point"),
          (agent_set_scripted_destination, ":cur_agent", pos1, 0),
          (agent_set_speed_limit, ":cur_agent", 5),
        (try_end),
	 (try_end),
	 (try_for_agents, ":cur_agent"),
		  (agent_get_entry_no, ":starting_entry", ":cur_agent"),
		  (gt, ":starting_entry", 20),
          (agent_get_slot, ":target_entry_point", ":cur_agent", 0),
		  
		(assign, reg0, 21),
        (assign, reg1, 22),
        (assign, reg2, 23),
        (assign, reg3, 24),
        (assign, reg4, 25),
        (assign, reg5, 26),
        (assign, reg6, 27),
        (assign, reg7, 28),
        (assign, reg8, 29),
        (assign, reg9, 30),
          (try_begin),
            (eq, ":target_entry_point", 21),
            (assign, reg0, 0),
          (else_try),
            (eq, ":target_entry_point", 22),
            (assign, reg1, 0),
          (else_try),
            (eq, ":target_entry_point", 23),
            (assign, reg2, 0),
          (else_try),
            (eq, ":target_entry_point", 24),
            (assign, reg3, 0),
          (else_try),
            (eq, ":target_entry_point", 25),
            (assign, reg4, 0),
          (else_try),
            (eq, ":target_entry_point", 26),
            (assign, reg5, 0),
          (else_try),
            (eq, ":target_entry_point", 27),
            (assign, reg6, 0),
          (else_try),
            (eq, ":target_entry_point", 28),
            (assign, reg7, 0),
          (else_try),
            (eq, ":target_entry_point", 29),
            (assign, reg8, 0),
          (else_try),
            (eq, ":target_entry_point", 30),
            (assign, reg9, 0),
          (try_end),
        (assign, ":try_limit", 100),
        (assign, ":target_entry_point", 0),
        (try_for_range, ":unused", 0, ":try_limit"),
          (shuffle_range, 0, 10),
          (gt, reg0, 0),
          (assign, ":target_entry_point", reg0),
          (assign, ":try_limit", 0),
        (try_end),
        (try_begin),
          (gt, ":target_entry_point", 0),
          (agent_set_slot, ":cur_agent", 0, ":target_entry_point"),
          (entry_point_get_position, pos1, ":target_entry_point"),
          (agent_set_scripted_destination, ":cur_agent", pos1, 0),
          (agent_set_speed_limit, ":cur_agent", 5),
        (try_end),
	 (try_end),
    ]),
]
