try:
    from src.compiler import *
except:
    from src.module_system import *

from src.constants.module_constants import *


SCRIPTS = [
    (
        "update_center_population_supply",
        [
            (store_script_param, ":center_no", 1),
            (try_begin),
                (gt, ":center_no", 0),
                (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
                (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
                (party_get_slot, ":prosperity", ":center_no", slot_center_sod_local_prosperity),
                (party_get_slot, ":town_prosperity", ":center_no", slot_town_prosperity),
                (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
                (call_script, "script_sod_get_center_modifier_totals", ":center_no"),
                (assign, ":building_population_capacity_bonus", reg0),
                (assign, ":building_population_growth_bonus", reg1),
                (assign, ":building_population_growth_pct", reg2),
                (assign, ":building_population_recovery_bonus", reg3),
                (assign, ":building_raid_recovery_bonus", reg16),
                (call_script, "script_sod_get_center_population_capacity_profile", ":center_no"),
                (assign, ":population_recovery_capacity_pct", reg5),
                (call_script, "script_sod_get_center_food_profile", ":center_no"),
                (assign, ":food_security", reg4),
                (assign, ":food_pressure", reg6),
                (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
                (assign, ":tax_extraction_pressure", reg1),
                (assign, ":tax_migration_retention_pct", reg3),
                (assign, ":tax_recovery_pct", reg5),
                (call_script, "script_sod_get_center_security_economy_profile", ":center_no"),
                (assign, ":security_recovery_pct", reg1),
                (assign, ":bandit_pressure_pct", reg2),
                (assign, ":raid_damage_pct", reg3),
                (assign, ":merchant_confidence", reg4),
                (try_begin),
                    (le, ":population", 0),
                    (call_script, "script_sod_normalize_center_population", ":center_no"),
                    (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
                    (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
                    (party_get_slot, ":prosperity", ":center_no", slot_center_sod_local_prosperity),
                    (party_get_slot, ":town_prosperity", ":center_no", slot_town_prosperity),
                    (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
                    (call_script, "script_sod_get_center_modifier_totals", ":center_no"),
                    (assign, ":building_population_capacity_bonus", reg0),
                    (assign, ":building_population_growth_bonus", reg1),
                    (assign, ":building_population_growth_pct", reg2),
                    (assign, ":building_population_recovery_bonus", reg3),
                    (assign, ":building_raid_recovery_bonus", reg16),
                    (call_script, "script_sod_get_center_population_capacity_profile", ":center_no"),
                    (assign, ":population_recovery_capacity_pct", reg5),
                    (call_script, "script_sod_get_center_food_profile", ":center_no"),
                    (assign, ":food_security", reg4),
                    (assign, ":food_pressure", reg6),
                    (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
                    (assign, ":tax_extraction_pressure", reg1),
                    (assign, ":tax_migration_retention_pct", reg3),
                    (assign, ":tax_recovery_pct", reg5),
                    (call_script, "script_sod_get_center_security_economy_profile", ":center_no"),
                    (assign, ":security_recovery_pct", reg1),
                    (assign, ":bandit_pressure_pct", reg2),
                    (assign, ":raid_damage_pct", reg3),
                    (assign, ":merchant_confidence", reg4),
                (try_end),
                (assign, ":population_change", 0),
                (try_begin),
                    (gt, ":health", 0),
                    (store_div, ":health_bonus", ":health", 50),
                    (val_add, ":population_change", ":health_bonus"),
                (try_end),
                (try_begin),
                    (gt, ":prosperity", 0),
                    (store_div, ":prosperity_bonus", ":prosperity", 200),
                    (val_add, ":population_change", ":prosperity_bonus"),
                (try_end),
                (try_begin),
                    (gt, ":town_prosperity", 0),
                    (store_div, ":town_prosperity_bonus", ":town_prosperity", 35),
                    (val_add, ":population_change", ":town_prosperity_bonus"),
                (try_end),
                (try_begin),
                    (gt, ":wealth", 0),
                    (store_div, ":wealth_bonus", ":wealth", 5000),
                    (val_add, ":population_change", ":wealth_bonus"),
                (else_try),
                    (lt, ":wealth", 0),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (gt, ":building_population_growth_bonus", 0),
                    (ge, ":health", 35),
                    (ge, ":town_prosperity", 25),
                    (val_add, ":population_change", ":building_population_growth_bonus"),
                (try_end),
                (try_begin),
                    (gt, ":population_change", 0),
                    (val_mul, ":population_change", ":building_population_growth_pct"),
                    (val_div, ":population_change", 100),
                    (store_faction_of_party, ":center_faction", ":center_no"),
                    (assign, ":population_modifier", 100),
                    (try_begin),
                        (party_slot_eq, ":center_no", slot_party_type, spt_village),
                        (faction_get_slot, ":population_modifier", ":center_faction", slot_faction_law_village_population_modifier),
                    (else_try),
                        (faction_get_slot, ":population_modifier", ":center_faction", slot_faction_law_town_population_modifier),
                    (try_end),
                    (try_begin),
                        (le, ":population_modifier", 0),
                        (assign, ":population_modifier", 100),
                    (try_end),
                    (val_mul, ":population_change", ":population_modifier"),
                    (val_div, ":population_change", 100),
                    (val_mul, ":population_change", ":tax_migration_retention_pct"),
                    (val_div, ":population_change", 100),
                (try_end),
                (try_begin),
                    (lt, ":health", 20),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (lt, ":town_prosperity", 20),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (lt, ":food_security", 300),
                    (val_sub, ":population_change", 2),
                (else_try),
                    (lt, ":food_security", 700),
                    (val_sub, ":population_change", 1),
                (else_try),
                    (ge, ":food_security", 1400),
                    (gt, ":health", 35),
                    (gt, ":town_prosperity", 25),
                    (val_add, ":population_change", 1),
                (try_end),
                (try_begin),
                    (gt, ":food_pressure", 50),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (gt, ":tax_extraction_pressure", 35),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (gt, ":bandit_pressure_pct", 125),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (gt, ":raid_damage_pct", 85),
                    (lt, ":health", 50),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (lt, ":merchant_confidence", -20),
                    (lt, ":town_prosperity", 45),
                    (val_sub, ":population_change", 1),
                (try_end),
                (try_begin),
                    (gt, ":building_raid_recovery_bonus", 0),
                    (lt, ":health", 50),
                    (val_add, ":population_change", ":building_raid_recovery_bonus"),
                (try_end),
                (try_begin),
                    (gt, ":building_population_recovery_bonus", 0),
                    (lt, ":health", 60),
                    (val_add, ":population_change", ":building_population_recovery_bonus"),
                (try_end),
                (try_begin),
                    (gt, ":population_change", 0),
                    (val_mul, ":population_change", ":population_recovery_capacity_pct"),
                    (val_div, ":population_change", 100),
                    (val_mul, ":population_change", ":tax_recovery_pct"),
                    (val_div, ":population_change", 100),
                    (val_mul, ":population_change", ":security_recovery_pct"),
                    (val_div, ":population_change", 100),
                (try_end),
                (assign, ":old_population", ":population"),
                (val_add, ":population", ":population_change"),
                (val_max, ":population", 0),
                (try_begin),
                    (party_slot_eq, ":center_no", slot_party_type, spt_village),
                    (store_add, ":population_cap", village_pop_max, ":building_population_capacity_bonus"),
                    (val_min, ":population", ":population_cap"),
                (else_try),
                    (store_add, ":population_cap", town_pop_max, ":building_population_capacity_bonus"),
                    (val_min, ":population", ":population_cap"),
                (try_end),
                (store_sub, ":population_delta", ":population", ":old_population"),
                (call_script, "script_sod_center_apply_population_delta", ":center_no", ":population_delta"),
            (try_end),
        ],
    ),
    (
        "get_center_recruitable_population",
        [
            (store_script_param, ":center_no", 1),
            (store_script_param, ":requested_amount", 2),
            (assign, reg0, 0),
            (try_begin),
                (gt, ":center_no", 0),
                (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
                (store_sub, ":available", ":population", village_pop_min),
                (val_max, ":available", 0),
                (try_begin),
                    (gt, ":requested_amount", 0),
                    (val_min, ":available", ":requested_amount"),
                (try_end),
                (assign, reg0, ":available"),
            (try_end),
        ],
    ),
    (
        "spend_center_population_for_recruitment",
        [
            (store_script_param, ":center_no", 1),
            (store_script_param, ":recruit_count", 2),
            (try_begin),
                (gt, ":center_no", 0),
                (gt, ":recruit_count", 0),
                (store_mul, ":population_delta", ":recruit_count", -1),
                (call_script, "script_sod_center_apply_population_delta", ":center_no", ":population_delta"),
            (try_end),
        ],
    ),
]
