MENUS = [
("banner_selection", mnf_disable_all_keys,
  "You have been awarded the right to carry a banner.",
  "none",
  [],[
  ("normal_banner",[],
  "Choose one of the existing banners.", [
  (jump_to_menu, "mnu_auto_return"),
  (start_presentation, "prsnt_banner_selection"),
  ]),
  # ("temp_banner",[],
  # "Custom banners will be included in one of the future SoD version.", [
  # (jump_to_menu, "mnu_banner_selection"),
  # ]),
  ("custom_banner",[],
  "Design your own, custom banner.", [
  (troop_set_slot, "trp_player", slot_troop_custom_banner_bg_type, 0),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_type_1, 0),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_type_2, 0),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_type_3, 0),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_type_4, 0),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_flag_type, -1),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_num_charges, 1),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_positioning, 0),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_map_flag_type, -1),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_bg_color_1, 0xFF1E4F9A),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_bg_color_2, 0xFFE4C46A),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_1, 0xFF111111),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_2, 0xFFFFFFFF),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_3, 0xFFFFFFFF),
  (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_4, 0xFFFFFFFF),
  (troop_set_slot, "trp_player", slot_troop_banner_scene_prop, -1),

  (try_for_range, ":trp_slot_index", 0, 128),
    (troop_set_slot, "trp_temp_array_a", ":trp_slot_index", -1),
  (try_end),
  (jump_to_menu, "mnu_auto_return"),
  (start_presentation, "prsnt_custom_banner"),
  ]),
  ]),
]
