MENUS = [
(
    "event_15", mnf_disable_all_keys,
    "My Liege. Our kingdom is suffering from real pandemy! What should we do?",
    "none",
    [
    ],
    [
      ("choice_15_1", [], "Pay as much as it's neccesary to fight it! =1500=",
       [
        (store_troop_gold, ":gold", "trp_player"),
        (try_begin),
          (ge, ":gold", 1500),
          (troop_remove_gold, "trp_player", 1500),
          (display_message, "@It was small price to pay. Disease killed many people, and hurt economy but was stopped.", quest_success_color),
        (else_try),
          (display_message, "@You don't have enough gold. How embarassing! Disease kiled many people, hurt economy and may spread even further!", quest_fail_color),
          (call_script, "script_change_troop_renown", "trp_player", -2),
          (val_add, "$g_sod_global_health", 2),
        (try_end),

        (try_for_range, ":center_no", centers_begin, centers_end),
          (neg|party_slot_eq, ":center_no", slot_party_type, spt_castle),
          (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
          (try_begin),
            (party_slot_eq, ":center_no", slot_party_type, spt_village),
            (store_random_in_range, ":rand", 20, 50),
            (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
            (val_sub, ":center_population", ":rand"),
            (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
            (call_script, "script_change_center_prosperity", "$temp", -5),
            (party_get_slot, ":center_health", "$temp", slot_center_sod_local_health),
            (val_sub, ":center_health", 10),
            (party_set_slot, "$temp", slot_center_sod_local_health, ":center_health"),
          (else_try),
            (store_random_in_range, ":rand", 50, 150),
            (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
            (val_sub, ":center_population", ":rand"),
            (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
            (call_script, "script_change_center_prosperity", "$temp", -5),
            (party_get_slot, ":center_health", "$temp", slot_center_sod_local_health),
            (val_sub, ":center_health", 10),
            (party_set_slot, "$temp", slot_center_sod_local_health, ":center_health"),
          (try_end),
        (try_end),
        (change_screen_return),
        ]
       ),
      ("choice_15_2", [], "Just keep the sick away from me.",
       [
        (try_for_range, ":center_no", centers_begin, centers_end),
        (neg|party_slot_eq, ":center_no", slot_party_type, spt_castle),
        (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
        (val_sub, "$g_sod_global_health", 2),
            (try_begin),
                (party_slot_eq, ":center_no", slot_party_type, spt_village),
                (store_random_in_range, ":rand", 20, 50),
                (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
                (val_sub, ":center_population", ":rand"),
                (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
                (call_script, "script_change_center_prosperity", "$temp", -5),
                (party_get_slot, ":center_health", "$temp", slot_center_sod_local_health),
        (val_sub, ":center_health", 10),
        (party_set_slot, "$temp", slot_center_sod_local_health, ":center_health"),
            (else_try),
                (store_random_in_range, ":rand", 50, 150),
                (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
                (val_sub, ":center_population", ":rand"),
                (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
                (call_script, "script_change_center_prosperity", "$temp", -5),
                (party_get_slot, ":center_health", "$temp", slot_center_sod_local_health),
                (val_sub, ":center_health", 10),
                (party_set_slot, "$temp", slot_center_sod_local_health, ":center_health"),
            (try_end),
        (try_end),
        (display_message, "@Disease killed many people throughout whole kingdom. Hurt our economy badly and may spread even further!", quest_fail_color),
        (change_screen_return),
        ]
       ),
      ]
  ),
]
