MENUS = [
(
    "good_guys_result", mnf_scale_picture,
    "{s9}",
    "none",
    [(try_begin),
       (eq, "$g_battle_result", 1),
       (str_store_string, s9, "@Your soldiers, excited by the slaughter raped all peasant women and razed the village to the ground."),
       (set_background_mesh, "mesh_pic_looted_village"),
	   (party_get_slot, ":population", "$current_town", slot_center_sod_local_population),
		(store_div, ":population_loss", ":population", 10),
		(val_mul, ":population_loss", 3),
		(call_script, "script_sod_apply_center_raid_resistance", "$current_town", ":population_loss"),
		(val_sub, ":population", reg0),
		(val_max, ":population", village_pop_min),
		(party_set_slot, "$current_town", slot_center_sod_local_population, ":population"),
     (else_try),
       (jump_to_menu, "mnu_defeated_by_peasants"),
     (try_end),
    ],
    [
      ("continue", [(neq, "$g_battle_result", 1)], "Continue...",
       [(party_set_slot, "$current_town", slot_village_infested_by_bandits, 0),
        (call_script, "script_village_set_state", "$current_town", svs_looted),
        (party_set_slot, "$current_town", slot_village_raid_progress, 0),
        (party_set_slot, "$current_town", slot_village_recover_progress, 0),
        (try_begin),
          (check_quest_active, "qst_slavers_deal_with_good_guys"),
          (quest_slot_eq, "qst_slavers_deal_with_good_guys", slot_quest_target_center, "$g_encountered_party"),
          (call_script, "script_succeed_quest", "qst_slavers_deal_with_good_guys"),
		(try_end),
		(party_get_slot, ":population", "$current_town", slot_center_sod_local_population),
		(call_script, "script_sod_apply_center_raid_resistance", "$current_town", 15),
		(val_sub, ":population", reg0),
		(val_max, ":population", village_pop_min),
		(party_set_slot, "$current_town", slot_center_sod_local_population, ":population"),
        (jump_to_menu, "mnu_village"), ]),
    ],
  ),
]
