MENUS = [
(
    "requested_castle_granted_to_player", mnf_scale_picture,
    "You receive a message from your liege, {s3}.^^ {reg4?She:He} has decided to grant {s2}{reg3? and the nearby village of {s4}:} to you, with all due incomes and titles, to hold in {reg4?her:his} name for as long as you maintain your oath of homage.",
    "none",
    [(set_background_mesh, "mesh_pic_messenger"),
     (faction_get_slot, ":faction_leader", "$players_kingdom", slot_faction_leader),
     (call_script, "script_store_troop_name", s3, ":faction_leader"),
     (str_store_party_name, s2, "$g_center_to_give_to_player"),
     (try_begin),
       (party_slot_eq, "$g_center_to_give_to_player", slot_party_type, spt_castle),
       (assign, reg3, 1),
       (try_for_range, ":cur_village", villages_begin, villages_end),
         (party_slot_eq, ":cur_village", slot_village_bound_center, "$g_center_to_give_to_player"),
         (str_store_party_name, s4, ":cur_village"),
       (try_end),
     (else_try),
       (assign, reg3, 0),
     (try_end),
     (troop_get_type, reg4, ":faction_leader"),
    ],
    [
      ("continue", [], "Continue.",
       [(call_script, "script_give_center_to_lord", "$g_center_to_give_to_player", "trp_player", 0),
        (jump_to_menu, "mnu_give_center_to_player_2"),
        ]),
     ],
  ),
]
