MENUS = [
(
    "give_center_to_player_2", 0,
    "{s68}",
    "none",
    [
      (str_store_string, s2, "@the awarded fief"),
      (str_store_string, s68, "@The confirmation cannot be completed because the awarded fief can no longer be resolved."),
      (assign, reg3, 0),
      (assign, reg5, 0),
      (try_begin),
        (is_between, "$g_center_to_give_to_player", centers_begin, centers_end),
        (str_store_party_name, s2, "$g_center_to_give_to_player"),
        (try_begin),
          (party_slot_eq, "$g_center_to_give_to_player", slot_party_type, spt_castle),
          (assign, reg5, 1),
          (try_for_range, ":cur_village", villages_begin, villages_end),
            (party_slot_eq, ":cur_village", slot_village_bound_center, "$g_center_to_give_to_player"),
            (str_store_party_name, s4, ":cur_village"),
            (assign, reg3, 1),
          (try_end),
        (try_end),
        (try_begin),
          (eq, reg3, 1),
          (str_store_string, s69, "@ and its bound village {s4}"),
        (else_try),
          (str_clear, s69),
        (try_end),
        (try_begin),
          (eq, reg5, 1),
          (str_store_string, s70, "@This is a high military honor: the castle gives you command of a garrison, stores, road control, and noble mustering rights."),
        (else_try),
          (eq, reg3, 1),
          (str_store_string, s70, "@They will make a fine part of your fiefdom."),
        (else_try),
          (str_store_string, s70, "@It will make a fine part of your fiefdom."),
        (try_end),
        (str_store_string, s68, "@With a brief ceremony, you are officially confirmed as the new lord of {s2}{s69}. {s70} You can now claim the rents and revenues from your personal estates there, draft soldiers from the populace, and manage the lands as you see fit. However, you are also expected to defend your fief and your people from harm, as well as maintaining the rule of law and order."),
      (try_end),
    ],
    [
      ("continue", [], "Continue...",
       [(change_screen_return),
        ]),
    ],
  ),
]
