MENUS = [
(
    "town_trade_assessment", mnf_disable_all_keys,
    "As the party member with the highest trade skill ({reg2}), {reg3?you try to figure out:{s1} tries to figure out} the best goods to trade in. {s2}",
    "none",
      [
        (set_background_mesh, "$g_sod_town_background"),

        (call_script, "script_get_max_skill_of_player_party", "skl_trade"),
        (assign, ":max_skill", reg0),
        (assign, ":max_skill_owner", reg1),

        (assign, ":num_best_results", 0),
        (assign, ":best_result_1_item", -1),
        (assign, ":best_result_1_town", -1),
        (assign, ":best_result_1_profit", 0),
        (assign, ":best_result_2_item", -1),
        (assign, ":best_result_2_town", -1),
        (assign, ":best_result_2_profit", 0),
        (assign, ":best_result_3_item", -1),
        (assign, ":best_result_3_town", -1),
        (assign, ":best_result_3_profit", 0),

        (store_sub, ":num_towns", towns_end, towns_begin),
        (store_sub, ":num_goods", trade_goods_end, trade_goods_begin),
        (store_mul, ":max_iteration", ":num_towns", ":num_goods"),
        (val_mul, ":max_iteration", ":max_skill"),
        (val_div, ":max_iteration", 20),

        (assign, ":org_encountered_party", "$g_encountered_party"),

        (try_for_range, ":unused", 0, ":max_iteration"),
        (store_random_in_range, ":random_trade_good", trade_goods_begin, trade_goods_end),
        (store_random_in_range, ":random_town", towns_begin, towns_end),
        (assign, ":already_best", 0),
        (try_begin),
          (eq, ":random_trade_good", ":best_result_1_item"),
          (eq, ":random_town", ":best_result_1_town"),
          (val_add, ":already_best", 1),
        (else_try),
          (eq, ":random_trade_good", ":best_result_2_item"),
          (eq, ":random_town", ":best_result_2_town"),
          (val_add, ":already_best", 1),
        (else_try),
          (eq, ":random_trade_good", ":best_result_3_item"),
          (eq, ":random_town", ":best_result_3_town"),
          (val_add, ":already_best", 1),
        (try_end),
        (eq, ":already_best", 0),
        (store_item_value, ":random_trade_good_price", ":random_trade_good"),
        (assign, "$g_encountered_party", ":org_encountered_party"),
        (call_script, "script_game_get_item_buy_price_factor", ":random_trade_good"),
        (store_mul, ":random_trade_good_buy_price", ":random_trade_good_price", reg0),
        (val_div, ":random_trade_good_buy_price", 100),
        (val_max, ":random_trade_good_buy_price", 1),
        (assign, "$g_encountered_party", ":random_town"),
        (call_script, "script_game_get_item_sell_price_factor", ":random_trade_good"),
        (store_mul, ":random_trade_good_sell_price", ":random_trade_good_price", reg0),
        (val_div, ":random_trade_good_sell_price", 100),
        (val_max, ":random_trade_good_sell_price", 1),
        (store_sub, ":difference", ":random_trade_good_sell_price", ":random_trade_good_buy_price"),
        (try_begin),
          (gt, ":difference", ":best_result_1_profit"),
          (val_add, ":num_best_results", 1),
          (val_min, ":num_best_results", 3),
          (assign, ":best_result_3_item", ":best_result_2_item"),
          (assign, ":best_result_3_town", ":best_result_2_town"),
          (assign, ":best_result_3_profit", ":best_result_2_profit"),
          (assign, ":best_result_2_item", ":best_result_1_item"),
          (assign, ":best_result_2_town", ":best_result_1_town"),
          (assign, ":best_result_2_profit", ":best_result_1_profit"),
          (assign, ":best_result_1_item", ":random_trade_good"),
          (assign, ":best_result_1_town", ":random_town"),
          (assign, ":best_result_1_profit", ":difference"),
        (else_try),
          (gt, ":difference", ":best_result_2_profit"),
          (val_add, ":num_best_results", 1),
          (val_min, ":num_best_results", 3),
          (assign, ":best_result_3_item", ":best_result_2_item"),
          (assign, ":best_result_3_town", ":best_result_2_town"),
          (assign, ":best_result_3_profit", ":best_result_2_profit"),
          (assign, ":best_result_2_item", ":random_trade_good"),
          (assign, ":best_result_2_town", ":random_town"),
          (assign, ":best_result_2_profit", ":difference"),
        (else_try),
          (gt, ":difference", ":best_result_3_profit"),
          (val_add, ":num_best_results", 1),
          (val_min, ":num_best_results", 3),
          (assign, ":best_result_3_item", ":random_trade_good"),
          (assign, ":best_result_3_town", ":random_town"),
          (assign, ":best_result_3_profit", ":difference"),
        (try_end),
      (try_end),

      (assign, "$g_encountered_party", ":org_encountered_party"),

      (str_clear, s3),

      (assign, reg2, ":max_skill"),
      (try_begin),
        (eq, ":max_skill_owner", "trp_player"),
        (assign, reg3, 1),
      (else_try),
        (assign, reg3, 0),
        (call_script, "script_store_troop_name", s1, ":max_skill_owner"),
      (try_end),

      (try_begin),
        (le, ":num_best_results", 0),
        (str_store_string, s2, "@However, {reg3?You are:{s1} is} unable to find any trade goods that would bring a profit."),
      (else_try),
        (try_begin),
          (ge, ":best_result_3_item", 0),
          (assign, reg6, ":best_result_3_profit"),
          (str_store_item_name, s4, ":best_result_3_item"),
          (str_store_party_name, s5, ":best_result_3_town"),
          (str_store_string, s3, "@^Buying {s4} here and selling it at {s5} would bring a profit of {reg6} denars per item.{s3}"),
        (try_end),
        (try_begin),
          (ge, ":best_result_2_item", 0),
          (assign, reg6, ":best_result_2_profit"),
          (str_store_item_name, s4, ":best_result_2_item"),
          (str_store_party_name, s5, ":best_result_2_town"),
          (str_store_string, s3, "@^Buying {s4} here and selling it at {s5} would bring a profit of {reg6} denars per item.{s3}"),
        (try_end),
        (try_begin),
          (ge, ":best_result_1_item", 0),
          (assign, reg6, ":best_result_1_profit"),
          (str_store_item_name, s4, ":best_result_1_item"),
          (str_store_party_name, s5, ":best_result_1_town"),
          (str_store_string, s3, "@^Buying {s4} here and selling it at {s5} would bring a profit of {reg6} denars per item.{s3}"),
        (try_end),
        (str_store_string, s2, "@{reg3?You find:{s1} finds} out the following:^{s3}"),
      (try_end),
    ],
    [
      ("continue", [], "Continue...", [(jump_to_menu, "mnu_town_trade")]),
    ]
  ),
]
