MENUS = [
(
    "disembark", 0,
    "Do you wish to disembark?",
    "none",
    [],
    [
      ("disembark_yes", [], "Yes.",
       [(assign, "$g_player_icon_state", pis_normal),
        (party_set_flags, "p_main_party", pf_is_ship, 0),
        (party_get_position, pos1, "p_main_party"),
        (party_set_position, "p_main_party", pos0),
        (try_begin),
          (this_or_next|le, "$g_main_ship_party", 0),
          (neg|party_is_active, "$g_main_ship_party"),
          (set_spawn_radius, 0),
          (spawn_around_party, "p_main_party", "pt_none"),
          (assign, "$g_main_ship_party", reg0),
          (try_begin),
            (gt, "$g_main_ship_party", 0),
            (party_is_active, "$g_main_ship_party"),
            (party_set_flags, "$g_main_ship_party", pf_is_static|pf_always_visible|pf_hide_defenders|pf_is_ship, 1),
            (call_script, "script_store_troop_name", s1, "trp_player"),
            (party_set_name, "$g_main_ship_party", "@{s1}'s Ship"),
            (party_set_icon, "$g_main_ship_party", "icon_ship"),
            (party_set_slot, "$g_main_ship_party", slot_party_type, spt_ship),
          (try_end),
        (try_end),
        (try_begin),
          (gt, "$g_main_ship_party", 0),
          (party_is_active, "$g_main_ship_party"),
          (enable_party, "$g_main_ship_party"),
          (party_set_position, "$g_main_ship_party", pos0),
          (party_set_icon, "$g_main_ship_party", "icon_ship_on_land"),
        (try_end),
        (assign, "$g_main_ship_party", -1),
        (change_screen_return),
        ]),
      ("disembark_no", [], "No.",
       [(change_screen_return),
        ]),
    ]
  ),
]
