MENUS = [
("sod_upgrade", 0,
	"{reg7?This center can train troops of {s5}{reg2? and its old {s2} traditions:}. :This center has no regular military training facilities. }{reg1?{reg1}:No} troops in your party can be promoted here.{s19}",
	"none", [
		(try_begin),
			(party_slot_eq, "$g_encountered_party", slot_center_has_barracks, 0),
			(party_slot_eq, "$g_encountered_party", slot_center_has_range, 0),
			(party_slot_eq, "$g_encountered_party", slot_center_has_stables, 0),
			(assign, reg7, 0),
			(str_clear, s19),
		(else_try),
			(assign, reg7, 1),
			(store_faction_of_party, ":town_faction", "$g_encountered_party"),
			(str_store_faction_name, s5, ":town_faction"),
			(party_get_slot, ":org_fac", "$g_encountered_party", slot_center_original_faction),
			(try_begin),
				(eq, ":org_fac", 0),
				(assign, reg2, 0),
			(else_try),
				(eq, ":town_faction", ":org_fac"),
				(assign, reg2, 0),
			(else_try),
				(str_store_faction_name, s2, ":org_fac"),
				(assign, reg2, 1),
			(try_end),
			
			(assign, ":num_improvements", 0),
			(try_for_range, ":improvement_no", slot_center_has_barracks, slot_center_has_chapter),
				(party_slot_eq, "$g_encountered_party", ":improvement_no", 1),
				(val_add, ":num_improvements", 1),
				(call_script, "script_get_improvement_details", ":improvement_no"),
				(try_begin),
					(eq, ":num_improvements", 1),
					(str_store_string, s18, "@{s0}"),
				(else_try),
					(str_store_string, s18, "@{s18}, {s0}"),
				(try_end),
			(try_end),

			(try_begin),
				(neq, ":num_improvements", 0),
				(str_store_string, s19, "@^^^Military facilities:^{s18}.^^Elite note: nobles require a chapter house; faith elites require chapel or temple support."),
			(else_try),
				(str_clear, s19),
			(try_end),
		(try_end),
			
		(assign, ":total", 0),
		(assign, reg1, 0),
		(try_for_range, ":troop_no", 0, "trp_last_troop"),
			(assign, ":can_up1", 0),
			(assign, ":can_up2", 0),
			(party_count_companions_of_type, ":troop_count", "p_main_party", ":troop_no"),
			(troop_get_slot, ":upgrade1", ":troop_no", slot_troop_sod_upgrade1),
			(try_begin),
				(is_between, ":upgrade1", 0, "trp_last_troop"),
				(call_script, "script_sod_can_upgrade_troops_here", ":upgrade1", "$g_encountered_party"),
				(assign, ":can_up1", reg0),
			(try_end),
			(troop_get_slot, ":upgrade2", ":troop_no", slot_troop_sod_upgrade2),
			(try_begin),
				(is_between, ":upgrade2", 0, "trp_last_troop"),
				(call_script, "script_sod_can_upgrade_troops_here", ":upgrade2", "$g_encountered_party"),
				(assign, ":can_up2", reg0),
			(try_end),
			(this_or_next|eq, ":can_up1", 1),
			(eq, ":can_up2", 1),
			(val_add, ":total", ":troop_count"),
		(try_end),
		(assign, reg1, ":total"),
	],
		generate_upgrade_options()
	),
]
