DIALOGS = [
[anyone|plyr, "escort_merchant_caravan_quest_brief", [(party_get_num_companions, ":party_size", "p_main_party"),
                                                       (quest_get_slot, ":quest_target_amount", "qst_escort_merchant_caravan", slot_quest_target_amount),
                                                       (ge, ":party_size", ":quest_target_amount"),
                                                       (quest_get_slot, ":quest_target_center", "qst_escort_merchant_caravan", slot_quest_target_center),
                                                       (party_is_active, ":quest_target_center"),
                                                       (party_is_active, "$g_encountered_party"),
                                                       ],
   "I will see the caravan through, and I will be paid for the risk.", "merchant_quest_taken",
   [(quest_get_slot, ":quest_target_center", "qst_escort_merchant_caravan", slot_quest_target_center),
    (set_spawn_radius, 1),
    (spawn_around_party, "$g_encountered_party", "pt_merchant_caravan"),
    (assign, ":quest_target_party", reg0),
    (try_begin),
      (gt, ":quest_target_party", 0),
      (party_is_active, ":quest_target_party"),
      (party_set_ai_behavior, ":quest_target_party", ai_bhvr_track_party),
      (party_set_ai_object, ":quest_target_party", "p_main_party"),
      (party_set_flags, ":quest_target_party", pf_default_behavior, 0),
      (quest_set_slot, "qst_escort_merchant_caravan", slot_quest_target_party, ":quest_target_party"),
      (quest_set_slot, "qst_escort_merchant_caravan", slot_quest_current_state, 0),
      (str_store_party_name_link, s8, ":quest_target_center"),
      (setup_quest_text, "qst_escort_merchant_caravan"),
      (str_store_string, s2, "@Escort the merchant caravan to the town of {s8}."),
      (call_script, "script_start_quest", "qst_escort_merchant_caravan", "$g_talk_troop"),
    (else_try),
      (display_message, "@The merchant caravan could not be placed on the map. Return later and ask again.", 0xFFCC66),
    (try_end),
    ]],
]
