DIALOGS = [
[anyone|plyr, "slavers_escort_merchant_caravan_quest_brief", [],
   "Alright. I will escort the caravan.", "gm_merchant_quest_taken_bandits",
   [(quest_get_slot, ":quest_target_center", "qst_slavers_escort_merchant_caravan", slot_quest_target_center),
    (set_spawn_radius, 1),
    (spawn_around_party, "$g_encountered_party", "pt_slavers_caravan"),
    (assign, ":quest_target_party", reg0),
    (party_set_ai_behavior, ":quest_target_party", ai_bhvr_track_party),
    (party_set_ai_object, ":quest_target_party", "p_main_party"),
    (party_set_flags, ":quest_target_party", pf_default_behavior, 0),
    (quest_set_slot, "qst_slavers_escort_merchant_caravan", slot_quest_target_party, ":quest_target_party"),
    (quest_set_slot, "qst_slavers_escort_merchant_caravan", slot_quest_current_state, 0),
    (str_store_party_name_link, s8, ":quest_target_center"),
	(str_store_party_name, s10, "$g_encountered_party"),
    (setup_quest_text, "qst_slavers_escort_merchant_caravan"),
    (str_store_string, s2, "@Slaver Chief of {s10} asked you to move slaves to {s8}."),
    (call_script, "script_start_quest", "qst_slavers_escort_merchant_caravan", "$g_talk_troop"),
    ]],
]
