DIALOGS = [
[anyone, "village_elder_companion_ymira_refugees",
  [
    (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
    (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
    (store_add, reg1, ":male_slaves", ":female_slaves"),
    (val_max, reg1, "$g_sod_ymira_refugee_captive_count"),
    (party_is_active, "$current_town"),
    (str_store_party_name_link, s3, "$current_town"),
  ],
  "{s3} has empty corners, frightened children, and old debts to mercy. But {reg1} frightened souls draw eyes. Slaver riders ask questions with ropes in their hands. If your healer-woman wants shelter here, what protection follows them?",
  "village_elder_companion_ymira_refugees_choice",
  []],

[anyone|plyr, "village_elder_companion_ymira_refugees_choice", [],
  "They come under my banner. Feed them, hide them, and send word if Slaver riders come. I will answer.",
  "village_elder_companion_ymira_refugees_guard",
  []],

[anyone, "village_elder_companion_ymira_refugees_guard", [],
  "A banner that returns is worth more than a promise that rides away. We will take names tonight. If the riders come, they will find you here or find us alone.",
  "village_elder_talk",
  [
    (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
    (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
    (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
    (val_max, ":slave_count", "$g_sod_ymira_refugee_captive_count"),
    (assign, "$g_sod_ymira_refugee_captive_count", ":slave_count"),
    (assign, "$g_sod_ymira_refugee_witnessed", 1),
    (quest_set_slot, "qst_companion_ymira_mercy_under_arms", slot_quest_sod_runtime_progress, 50),
    (quest_set_slot, "qst_companion_ymira_mercy_under_arms", slot_quest_sod_runtime_last_center, "$current_town"),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_ymira_refugee_mercy, 2),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_help_village, 2),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc3"),
    (display_message, "@The elder agrees to hear the refugees by name. Ymira asks you to stay for the riders the village fears.", 0x99CCFF),
    (jump_to_menu, "mnu_ymira_refugee_standoff"),
    (finish_mission),
  ]],

[anyone|plyr, "village_elder_companion_ymira_refugees_choice",
  [
    (store_troop_gold, ":gold", "trp_player"),
    (ge, ":gold", 300),
  ],
  "I will leave coin for grain, blankets, and silence. Hide the weakest first.",
  "village_elder_companion_ymira_refugees_coin",
  []],

[anyone, "village_elder_companion_ymira_refugees_coin", [],
  "Coin buys grain. Silence costs trust. We will take the weakest and the sick, but if riders follow the tracks, coin will not stand in the road.",
  "village_elder_talk",
  [
    (call_script, "script_sod_player_charge_gold", 300),
    (eq, reg1, 1),
    (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
    (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
    (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
    (val_max, ":slave_count", "$g_sod_ymira_refugee_captive_count"),
    (assign, "$g_sod_ymira_refugee_captive_count", ":slave_count"),
    (assign, "$g_sod_ymira_refugee_witnessed", 1),
    (assign, "$g_sod_ymira_refugee_result_grade", 2),
    (quest_set_slot, "qst_companion_ymira_mercy_under_arms", slot_quest_sod_runtime_progress, 50),
    (quest_set_slot, "qst_companion_ymira_mercy_under_arms", slot_quest_sod_runtime_last_center, "$current_town"),
    (quest_set_slot, "qst_companion_ymira_mercy_under_arms", slot_quest_sod_runtime_metadata, 2),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_free_captives, 2),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc3"),
    (display_message, "@The village takes your coin and names the risk aloud. Ymira waits to see whether coin is followed by protection.", 0xCC9966),
    (jump_to_menu, "mnu_ymira_refugee_standoff"),
    (finish_mission),
  ]],

[anyone|plyr, "village_elder_companion_ymira_refugees_choice", [],
  "If Slaver riders come, tell them nothing. I cannot spare guards.",
  "village_elder_companion_ymira_refugees_refuse_risk",
  []],

[anyone, "village_elder_companion_ymira_refugees_refuse_risk", [],
  "Then you are asking poor houses to become a shield without wood or iron. We will not buy your clean conscience with our children's fear.",
  "village_elder_talk",
  [
    (call_script, "script_sod_companion_shift_approval", "trp_npc3", -4),
    (assign, "$g_sod_ymira_refugee_result_grade", 1),
    (call_script, "script_sod_companion_try_ymira_refugee_expedience", 3),
    (display_message, "@The elder refuses shelter without protection. Ymira's mercy has found a road, but not yet a safe door.", 0xCC6666),
  ]],
]
