DIALOGS = [
[anyone|plyr, "black_army_escort_merchant_caravan_quest_brief", [],
   "Alright. I will escort the caravan.", "gm_merchant_quest_taken_bandits",
   [(quest_get_slot, ":quest_target_center", "qst_black_army_escort_merchant_caravan", slot_quest_target_center),
    (set_spawn_radius, 1),
    (spawn_around_party, "$g_encountered_party", "pt_black_army_caravan"),
    (assign, ":quest_target_party", reg0),
	(try_for_range, ":unused", 0, 5),
          (call_script, "script_cf_party_upgrade_with_xp", ":quest_target_party", 500),
    (try_end),
    (party_set_ai_behavior, ":quest_target_party", ai_bhvr_track_party),
    (party_set_ai_object, ":quest_target_party", "p_main_party"),
    (party_set_flags, ":quest_target_party", pf_default_behavior, 0),
    (quest_set_slot, "qst_black_army_escort_merchant_caravan", slot_quest_target_party, ":quest_target_party"),
    (quest_set_slot, "qst_black_army_escort_merchant_caravan", slot_quest_current_state, 1),
	(call_script, "script_store_troop_name_link", s9, "$g_talk_troop"),
    (str_store_party_name_link, s8, ":quest_target_center"),
    (setup_quest_text, "qst_black_army_escort_merchant_caravan"),
    (str_store_string, s2, "@{s9} asked you to escort caravan to {s8}."),
    (call_script, "script_start_quest", "qst_black_army_escort_merchant_caravan", "$g_talk_troop"),
    ]],
]
