from header_operations import *
from module_constants import *
from module_troops import *

try:
    slot_troop_companion_grievance
except NameError:
    slot_troop_companion_grievance = slot_troop_companion_cohesion + 1

COMPANION_COHESION_NEUTRAL = 50
COMPANION_COHESION_STRONG = 80
COMPANION_COHESION_WEAK = 20
COMPANION_GRIEVANCE_HIGH = 80
COMPANION_GRIEVANCE_LOW = 30

SCRIPTS = [
    ("companions_resent",
     [
         (store_script_param, ":companion_a", 1),
         (store_script_param, ":companion_b", 2),
         (store_script_param, ":clash_severity", 3),

         (try_begin),
             (le, ":clash_severity", 0),
             (assign, ":clash_severity", "$g_companion_last_clash_severity"),
         (try_end),

         (assign, ":valid_a", 0),
         (assign, ":valid_b", 0),
         (assign, ":cohesion_total", 0),
         (assign, ":grievance_total", 0),
         (assign, ":cohesion_count", 0),
         (assign, ":relationship_shift", 0),
         (assign, ":average_cohesion", 0),
         (assign, ":average_grievance", 0),
         (assign, ":reaction_tier", 0),
         (assign, ":is_reconciliation", 0),
         (assign, ":severity", 0),
         (assign, ":loss", 0),
         (assign, ":cohesion_shift", 0),
         (assign, ":grievance_shift", 0),

         (try_begin),
             (is_between, ":companion_a", companions_begin, companions_end),
             (call_script, "script_cf_sod_companion_in_main_party", ":companion_a"),
             (assign, ":valid_a", 1),
         (try_end),
         (try_begin),
             (is_between, ":companion_b", companions_begin, companions_end),
             (neq, ":companion_b", ":companion_a"),
             (call_script, "script_cf_sod_companion_in_main_party", ":companion_b"),
             (assign, ":valid_b", 1),
         (try_end),

         (try_begin),
             (eq, ":valid_a", 1),
             (troop_get_slot, ":cohesion_a", ":companion_a", slot_troop_companion_cohesion),
             (troop_get_slot, ":grievance_a", ":companion_a", slot_troop_companion_grievance),
             (val_add, ":cohesion_total", ":cohesion_a"),
             (val_add, ":grievance_total", ":grievance_a"),
             (val_add, ":cohesion_count", 1),
         (try_end),
         (try_begin),
             (eq, ":valid_b", 1),
             (troop_get_slot, ":cohesion_b", ":companion_b", slot_troop_companion_cohesion),
             (troop_get_slot, ":grievance_b", ":companion_b", slot_troop_companion_grievance),
             (val_add, ":cohesion_total", ":cohesion_b"),
             (val_add, ":grievance_total", ":grievance_b"),
             (val_add, ":cohesion_count", 1),
         (try_end),

         (try_begin),
             (eq, ":valid_a", 1),
             (eq, ":valid_b", 1),
             (troop_get_slot, ":match_a", ":companion_a", slot_troop_personalitymatch_object),
             (troop_get_slot, ":clash_a", ":companion_a", slot_troop_personalityclash_object),
             (troop_get_slot, ":clash2_a", ":companion_a", slot_troop_personalityclash2_object),
             (troop_get_slot, ":match_b", ":companion_b", slot_troop_personalitymatch_object),
             (troop_get_slot, ":clash_b", ":companion_b", slot_troop_personalityclash_object),
             (troop_get_slot, ":clash2_b", ":companion_b", slot_troop_personalityclash2_object),

             (try_begin),
                 (eq, ":match_a", ":companion_b"),
                 (val_sub, ":relationship_shift", 2),
             (try_end),
             (try_begin),
                 (eq, ":match_b", ":companion_a"),
                 (val_sub, ":relationship_shift", 2),
             (try_end),
             (try_begin),
                 (eq, ":clash_a", ":companion_b"),
                 (val_add, ":relationship_shift", 3),
             (try_end),
             (try_begin),
                 (eq, ":clash_b", ":companion_a"),
                 (val_add, ":relationship_shift", 3),
             (try_end),
             (try_begin),
                 (eq, ":clash2_a", ":companion_b"),
                 (val_add, ":relationship_shift", 1),
             (try_end),
             (try_begin),
                 (eq, ":clash2_b", ":companion_a"),
                 (val_add, ":relationship_shift", 1),
             (try_end),

             (assign, ":average_cohesion", ":cohesion_total"),
             (val_div, ":average_cohesion", ":cohesion_count"),
             (assign, ":average_grievance", ":grievance_total"),
             (val_div, ":average_grievance", ":cohesion_count"),

             (assign, ":severity", ":clash_severity"),
             (store_div, ":loss", ":average_grievance", 4),
             (val_add, ":severity", ":loss"),
             (store_div, ":loss", ":average_cohesion", 5),
             (val_sub, ":severity", ":loss"),
             (store_div, ":loss", "$g_companion_recent_resentment", 5),
             (val_add, ":severity", ":loss"),
             (val_add, ":severity", "$g_companion_clash_chain"),
             (val_add, ":severity", ":relationship_shift"),

             (try_begin),
                 (lt, ":relationship_shift", 0),
                 (val_sub, ":severity", 4),
             (try_end),
             (try_begin),
                 (gt, ":relationship_shift", 0),
                 (val_add, ":severity", 3),
             (try_end),
             (try_begin),
                 (ge, ":average_cohesion", 75),
                 (le, ":average_grievance", 35),
                 (val_sub, ":severity", 8),
                 (assign, ":is_reconciliation", 1),
             (try_end),
             (try_begin),
                 (ge, ":average_cohesion", 85),
                 (le, ":average_grievance", 20),
                 (val_sub, ":severity", 4),
                 (assign, ":is_reconciliation", 1),
             (try_end),

             (val_max, ":severity", 0),
             (val_min, ":severity", 100),

             (try_begin),
                 (lt, ":severity", 12),
                 (assign, ":reaction_tier", 0),
             (else_try),
                 (lt, ":severity", 28),
                 (assign, ":reaction_tier", 1),
             (else_try),
                 (lt, ":severity", 50),
                 (assign, ":reaction_tier", 2),
             (else_try),
                 (lt, ":severity", 75),
                 (assign, ":reaction_tier", 3),
             (else_try),
                 (assign, ":reaction_tier", 4),
             (try_end),

             (try_begin),
                 (lt, ":average_cohesion", 45),
                 (val_add, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (lt, ":average_cohesion", 25),
                 (val_add, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (ge, ":average_grievance", 60),
                 (val_add, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (ge, "$g_companion_recent_resentment", 50),
                 (val_add, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (ge, "$g_companion_clash_chain", 2),
                 (val_add, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (le, ":relationship_shift", -3),
                 (val_sub, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (ge, ":relationship_shift", 4),
                 (val_add, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (ge, ":average_cohesion", 80),
                 (le, ":average_grievance", 25),
                 (lt, ":severity", 20),
                 (val_sub, ":reaction_tier", 1),
             (try_end),
             (try_begin),
                 (lt, ":average_grievance", 15),
                 (lt, ":severity", 18),
                 (val_sub, ":reaction_tier", 1),
             (try_end),
             (val_max, ":reaction_tier", 0),
             (val_min, ":reaction_tier", 4),

             (try_begin),
                 (eq, ":reaction_tier", 0),
                 (try_begin),
                     (le, ":severity", 15),
                     (ge, ":average_cohesion", 75),
                     (le, ":average_grievance", 35),
                     (assign, ":is_reconciliation", 1),
                 (try_end),
             (try_end),

             (try_begin),
                 (eq, ":reaction_tier", 0),
                 (assign, ":cohesion_shift", 1),
                 (store_div, ":loss", ":average_cohesion", 20),
                 (val_add, ":cohesion_shift", ":loss"),
                 (assign, ":grievance_shift", 1),
                 (store_div, ":loss", ":average_grievance", 30),
                 (val_sub, ":grievance_shift", ":loss"),
                 (store_div, ":loss", ":severity", 20),
                 (val_sub, ":grievance_shift", ":loss"),
                 (try_begin),
                     (lt, ":relationship_shift", 0),
                     (val_add, ":cohesion_shift", 1),
                 (try_end),
                 (try_begin),
                     (ge, ":average_cohesion", 80),
                     (le, ":average_grievance", 25),
                     (val_add, ":cohesion_shift", 1),
                     (val_sub, ":grievance_shift", 1),
                 (try_end),
                 (val_add, ":cohesion_a", ":cohesion_shift"),
                 (val_add, ":cohesion_b", ":cohesion_shift"),
                 (val_sub, ":grievance_a", ":grievance_shift"),
                 (val_sub, ":grievance_b", ":grievance_shift"),
             (else_try),
                 (assign, ":cohesion_shift", ":reaction_tier"),
                 (assign, ":grievance_shift", ":reaction_tier"),
                 (store_div, ":loss", ":severity", 20),
                 (val_add, ":cohesion_shift", ":loss"),
                 (store_div, ":loss", ":severity", 18),
                 (val_add, ":grievance_shift", ":loss"),
                 (try_begin),
                     (lt, ":average_cohesion", 35),
                     (val_add, ":cohesion_shift", 1),
                 (try_end),
                 (try_begin),
                     (ge, ":average_grievance", 65),
                     (val_add, ":grievance_shift", 1),
                 (try_end),
                 (try_begin),
                     (gt, ":relationship_shift", 0),
                     (val_add, ":cohesion_shift", 1),
                     (val_add, ":grievance_shift", 1),
                 (try_end),
                 (try_begin),
                     (lt, ":relationship_shift", 0),
                     (val_sub, ":cohesion_shift", 1),
                 (try_end),
                 (val_sub, ":cohesion_a", ":cohesion_shift"),
                 (val_sub, ":cohesion_b", ":cohesion_shift"),
                 (val_add, ":grievance_a", ":grievance_shift"),
                 (val_add, ":grievance_b", ":grievance_shift"),
             (try_end),

             (val_max, ":cohesion_a", 0),
             (val_min, ":cohesion_a", 100),
             (val_max, ":cohesion_b", 0),
             (val_min, ":cohesion_b", 100),
             (val_max, ":grievance_a", 0),
             (val_min, ":grievance_a", 100),
             (val_max, ":grievance_b", 0),
             (val_min, ":grievance_b", 100),

             (troop_set_slot, ":companion_a", slot_troop_companion_cohesion, ":cohesion_a"),
             (troop_set_slot, ":companion_b", slot_troop_companion_cohesion, ":cohesion_b"),
             (troop_set_slot, ":companion_a", slot_troop_companion_grievance, ":grievance_a"),
             (troop_set_slot, ":companion_b", slot_troop_companion_grievance, ":grievance_b"),

             (assign, "$g_companion_last_clash_severity", ":severity"),
             (assign, "$g_companion_last_clash_average_cohesion", ":average_cohesion"),
             (assign, "$g_companion_last_clash_tier", ":reaction_tier"),
             (assign, "$g_companion_last_clash_was_reconciliation", ":is_reconciliation"),

             (assign, "$g_companion_recent_resentment", ":severity"),
             (store_div, ":loss", ":average_grievance", 4),
             (val_add, "$g_companion_recent_resentment", ":loss"),
             (store_div, ":loss", ":average_cohesion", 10),
             (val_sub, "$g_companion_recent_resentment", ":loss"),
             (try_begin),
                 (eq, ":is_reconciliation", 1),
                 (val_sub, "$g_companion_recent_resentment", 10),
             (try_end),
             (val_max, "$g_companion_recent_resentment", 0),
             (val_min, "$g_companion_recent_resentment", 100),

             (try_begin),
                 (gt, ":reaction_tier", 0),
                 (val_add, "$g_companion_clash_chain", 1),
             (else_try),
                 (val_sub, "$g_companion_clash_chain", 1),
             (try_end),
             (try_begin),
                 (eq, ":is_reconciliation", 1),
                 (val_sub, "$g_companion_clash_chain", 1),
             (try_end),
             (val_max, "$g_companion_clash_chain", 0),
             (val_min, "$g_companion_clash_chain", 5),

             (assign, reg0, ":reaction_tier"),
             (assign, reg1, ":average_cohesion"),
         (else_try),
             (eq, ":valid_a", 1),
             (assign, ":average_cohesion", ":cohesion_a"),
             (assign, reg0, 0),
             (assign, reg1, ":average_cohesion"),
         (else_try),
             (eq, ":valid_b", 1),
             (assign, ":average_cohesion", ":cohesion_b"),
             (assign, reg0, 0),
             (assign, reg1, ":average_cohesion"),
         (else_try),
             (assign, reg0, 0),
             (assign, reg1, 0),
         (try_end),
     ]),
]
