from header_operations import *
from module_constants import *
from module_troops import *

try:
    slot_troop_companion_grievance
except NameError:
    slot_troop_companion_grievance = slot_troop_companion_cohesion + 1

COMPANION_COHESION_NEUTRAL = 50
COMPANION_COHESION_STRONG = 80
COMPANION_COHESION_WEAK = 20
COMPANION_GRIEVANCE_HIGH = 80
COMPANION_GRIEVANCE_LOW = 30

SCRIPTS = [
    ("player_relations",
     [
         (store_script_param, ":maybe_target", 1),
         (store_script_param, ":base_relation", 2),
         (assign, ":relation_score", ":base_relation"),
         (assign, ":total_bonus", 0),
         (assign, ":companion_count", 0),
         (try_begin),
             (is_between, ":maybe_target", companions_begin, companions_end),
             (assign, ":troop_no", ":maybe_target"),
             (troop_get_slot, ":cohesion", ":troop_no", slot_troop_companion_cohesion),
             (troop_get_slot, ":grievance", ":troop_no", slot_troop_companion_grievance),
             (val_max, ":cohesion", 0),
             (val_min, ":cohesion", 100),
             (val_max, ":grievance", 0),
             (val_min, ":grievance", 100),
             (assign, ":bonus", 0),
             (try_begin),
                 (ge, ":cohesion", COMPANION_COHESION_STRONG),
                 (assign, ":bonus", 15),
             (else_try),
                 (ge, ":cohesion", 65),
                 (assign, ":bonus", 8),
             (else_try),
                 (ge, ":cohesion", COMPANION_COHESION_NEUTRAL),
                 (assign, ":bonus", 3),
             (else_try),
                 (ge, ":cohesion", COMPANION_COHESION_WEAK),
                 (assign, ":bonus", -4),
             (else_try),
                 (assign, ":bonus", -10),
             (try_end),
             (try_begin),
                 (ge, ":grievance", COMPANION_GRIEVANCE_HIGH),
                 (val_sub, ":bonus", 15),
             (else_try),
                 (ge, ":grievance", 50),
                 (val_sub, ":bonus", 8),
             (else_try),
                 (lt, ":grievance", COMPANION_GRIEVANCE_LOW),
                 (val_add, ":bonus", 3),
             (try_end),
             (try_begin),
                 (ge, ":grievance", 90),
                 (val_sub, ":bonus", 5),
             (try_end),
             (val_add, ":relation_score", ":bonus"),
         (else_try),
             (gt, ":maybe_target", 0),
             (assign, ":relation_score", ":base_relation"),
             (try_for_range, ":troop_no", companions_begin, companions_end),
                 (troop_get_slot, ":cohesion", ":troop_no", slot_troop_companion_cohesion),
                 (troop_get_slot, ":grievance", ":troop_no", slot_troop_companion_grievance),
                 (val_max, ":cohesion", 0),
                 (val_min, ":cohesion", 100),
                 (val_max, ":grievance", 0),
                 (val_min, ":grievance", 100),
                 (assign, ":bonus", 0),
                 (try_begin),
                     (ge, ":cohesion", COMPANION_COHESION_STRONG),
                     (assign, ":bonus", 15),
                 (else_try),
                     (ge, ":cohesion", 65),
                     (assign, ":bonus", 8),
                 (else_try),
                     (ge, ":cohesion", COMPANION_COHESION_NEUTRAL),
                     (assign, ":bonus", 3),
                 (else_try),
                     (ge, ":cohesion", COMPANION_COHESION_WEAK),
                     (assign, ":bonus", -4),
                 (else_try),
                     (assign, ":bonus", -10),
                 (try_end),
                 (try_begin),
                     (ge, ":grievance", COMPANION_GRIEVANCE_HIGH),
                     (val_sub, ":bonus", 15),
                 (else_try),
                     (ge, ":grievance", 50),
                     (val_sub, ":bonus", 8),
                 (else_try),
                     (lt, ":grievance", COMPANION_GRIEVANCE_LOW),
                     (val_add, ":bonus", 3),
                 (try_end),
                 (try_begin),
                     (ge, ":grievance", 90),
                     (val_sub, ":bonus", 5),
                 (try_end),
                 (val_add, ":total_bonus", ":bonus"),
                 (val_add, ":companion_count", 1),
             (try_end),
             (try_begin),
                 (gt, ":companion_count", 0),
                 (store_div, ":total_bonus", ":total_bonus", ":companion_count"),
             (try_end),
             (val_add, ":relation_score", ":total_bonus"),
         (try_end),
         (try_begin),
             (gt, "$g_companion_recent_resentment", 40),
             (val_sub, ":relation_score", 2),
         (try_end),
         (try_begin),
             (gt, "$g_companion_clash_chain", 2),
             (val_sub, ":relation_score", 1),
         (try_end),
         (assign, reg0, ":relation_score"),
     ]),
]