# -*- coding: utf-8 -*-
# Companion personal quest framework identities.
#
# The companion-depth troop slots remain the live compatibility layer for
# campfire, direct dialogue, reports, and role payoffs. These quest records are
# deliberately dormant at game start: they must not use qf_random_quest or any
# startup-visible flag, because they should enter the journal only after a
# companion earns trust and script_sod_companion_sync_personal_quest_framework
# accepts the matching arc.
# Live stage ownership stays on slot_troop_companion_personal_quest_stage.

QUESTS = [
 *quest_chain_from_specs(
  "companion_personal_arcs",
 "Companion Personal Arcs",
 quests=(
   quest_template_spec(
    "companion_borcha_road_keeps_own",
    "Borcha: The Road Keeps Its Own",
    0,
    "Borcha is testing whether old horde roads can become safe roads under better command.",
    stages=(
     quest_stage_spec("borcha_road_opening", "Old Hoofbeats", "Speak with Borcha after earning enough trust to hear what the road took from him.", metadata={"companion": "trp_npc1", "phase": "opening"}),
     quest_stage_spec("borcha_road_field_test", "A Bad Road Chosen", "Resolve a roadcraft or Black Khergit pressure incident.", rewards=("Scout payoff if the road is made safer",), failures=("hard roadcraft compromise",), metadata={"companion": "trp_npc1", "phase": "test"}),
     quest_stage_spec("borcha_road_aftermath", "Roads Remembered", "Borcha remembers whether the road became warning, profit, or refuge.", metadata={"companion": "trp_npc1", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Borcha", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_marnid_honest_price",
    "Marnid: The Honest Price",
    0,
    "Marnid is testing whether trade can remain honest when war makes every price hungry.",
    stages=(
     quest_stage_spec("marnid_price_opening", "The Ledger Opens", "Speak with Marnid after earning enough trust to hear what dishonest profit cost him.", metadata={"companion": "trp_npc2", "phase": "opening"}),
     quest_stage_spec("marnid_price_field_test", "A Bargain Under Strain", "Resolve a trade or caravan incident through honest profit or hard advantage.", rewards=("Quartermaster or Envoy payoff if trade is stabilized",), failures=("dirty-profit compromise",), metadata={"companion": "trp_npc2", "phase": "test"}),
     quest_stage_spec("marnid_price_aftermath", "The Price Remembered", "Marnid remembers whether the books became trust or leverage.", metadata={"companion": "trp_npc2", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Marnid", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_rolf_name_worth_wearing",
    "Rolf: A Name Worth Wearing",
    0,
    "Rolf is testing whether a grand name can become earned dignity instead of only noise.",
    stages=(
     quest_stage_spec("rolf_name_opening", "The Claim", "Speak with Rolf after earning enough trust to press him about the name he wears.", metadata={"companion": "trp_npc4", "phase": "opening"}),
     quest_stage_spec("rolf_name_field_test", "Witnesses to a Name", "Resolve a public honor incident by earning the name or preserving the claim.", rewards=("Envoy or Captain payoff if dignity is earned",), failures=("prestige compromise",), metadata={"companion": "trp_npc4", "phase": "test"}),
     quest_stage_spec("rolf_name_aftermath", "The Name Remembered", "Rolf remembers whether the company made room for truth or theater.", metadata={"companion": "trp_npc4", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Rolf", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_baheshtur_unbroken_saddle",
    "Baheshtur: The Unbroken Saddle",
    0,
    "Baheshtur is testing whether loyalty can be chosen without becoming a rein.",
    stages=(
     quest_stage_spec("baheshtur_saddle_opening", "The Rein Refused", "Speak with Baheshtur after earning enough trust to hear why submission tastes like dust.", metadata={"companion": "trp_npc5", "phase": "opening"}),
     quest_stage_spec("baheshtur_saddle_field_test", "Riders at the Edge", "Resolve a rider or horde incident through chosen loyalty or forced submission.", rewards=("Scout or Captain payoff if loyalty remains chosen",), failures=("submission compromise",), metadata={"companion": "trp_npc5", "phase": "test"}),
     quest_stage_spec("baheshtur_saddle_aftermath", "The Saddle Remembered", "Baheshtur remembers whether command held reins or kept faith.", metadata={"companion": "trp_npc5", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Baheshtur", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_deshavi_tracks_through_ash",
    "Deshavi: Tracks Through Ash",
    0,
    "Deshavi is testing whether the forgotten are worth finding before victory moves on.",
    stages=(
     quest_stage_spec("deshavi_tracks_opening", "Smoke in the Tracks", "Speak with Deshavi after earning enough trust to hear why missing people matter to her.", metadata={"companion": "trp_npc7", "phase": "opening"}),
     quest_stage_spec("deshavi_tracks_field_test", "Survivors or Pursuit", "Resolve a trail incident by sheltering survivors or hunting only the threat.", rewards=("Scout or Spymaster payoff if survivors are protected",), failures=("hunt-only compromise",), metadata={"companion": "trp_npc7", "phase": "test"}),
     quest_stage_spec("deshavi_tracks_aftermath", "Ash Remembered", "Deshavi remembers whether the company read tracks as people or targets.", metadata={"companion": "trp_npc7", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Deshavi", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_matheld_no_backward_step",
    "Matheld: No Backward Step",
    0,
    "Matheld is testing whether courage can hold without wasting itself for reputation.",
    stages=(
     quest_stage_spec("matheld_step_opening", "Forward Only", "Speak with Matheld after earning enough trust to hear what retreat means in her tongue.", metadata={"companion": "trp_npc8", "phase": "opening"}),
     quest_stage_spec("matheld_step_field_test", "The Shield Still Faces Forward", "Resolve a battle incident through disciplined courage or blood spent for reputation.", rewards=("Captain payoff if courage is held in discipline",), failures=("blood-price compromise",), metadata={"companion": "trp_npc8", "phase": "test"}),
     quest_stage_spec("matheld_step_aftermath", "Courage Remembered", "Matheld remembers whether courage became strength or appetite.", metadata={"companion": "trp_npc8", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Matheld", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_alayen_standard_self",
    "Alayen: The Standard and the Self",
    0,
    "Alayen is testing whether honor means duty when prestige asks for the banner first.",
    stages=(
     quest_stage_spec("alayen_standard_opening", "The Banner's Weight", "Speak with Alayen after earning enough trust to hear what honor demands of him.", metadata={"companion": "trp_npc9", "phase": "opening"}),
     quest_stage_spec("alayen_standard_field_test", "Duty Before Display", "Resolve a duty incident through responsibility or prestige.", rewards=("Envoy payoff if duty outranks vanity",), failures=("prestige compromise",), metadata={"companion": "trp_npc9", "phase": "test"}),
     quest_stage_spec("alayen_standard_aftermath", "The Standard Remembered", "Alayen remembers whether the banner served people or pride.", metadata={"companion": "trp_npc9", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Alayen", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_katrin_last_coin",
    "Katrin: The Last Coin in Camp",
    0,
    "Katrin is testing whether practical care can survive heroic waste and empty stores.",
    stages=(
     quest_stage_spec("katrin_coin_opening", "The Empty Purse", "Speak with Katrin after earning enough trust to hear why waste is never abstract to her.", metadata={"companion": "trp_npc11", "phase": "opening"}),
     quest_stage_spec("katrin_coin_field_test", "A Camp That Must Eat", "Resolve a supply incident through practical care or wasteful display.", rewards=("Quartermaster payoff if the camp is protected",), failures=("heroic-waste compromise",), metadata={"companion": "trp_npc11", "phase": "test"}),
     quest_stage_spec("katrin_coin_aftermath", "The Coin Remembered", "Katrin remembers whether care counted before speeches.", metadata={"companion": "trp_npc11", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Katrin", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_nizar_impossible_charge",
    "Nizar: The Impossible Charge",
    0,
    "Nizar is testing whether glory is still beautiful when survivors must carry the song.",
    stages=(
     quest_stage_spec("nizar_charge_opening", "The Song Before Steel", "Speak with Nizar after earning enough trust to hear why he runs toward impossible moments.", metadata={"companion": "trp_npc13", "phase": "opening"}),
     quest_stage_spec("nizar_charge_field_test", "Glory With an Exit", "Resolve a daring battle incident through survivable glory or legend paid in blood.", rewards=("Captain payoff if glory keeps survivors",), failures=("legendary-blood compromise",), metadata={"companion": "trp_npc13", "phase": "test"}),
     quest_stage_spec("nizar_charge_aftermath", "The Charge Remembered", "Nizar remembers whether the story deserved its listeners.", metadata={"companion": "trp_npc13", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Nizar", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_artimenner_siege_that_should",
    "Artimenner: The Siege That Should Have Worked",
    0,
    "Artimenner is testing whether plans are respected before blame becomes convenient.",
    stages=(
     quest_stage_spec("artimenner_siege_opening", "The Failed Plan", "Speak with Artimenner after earning enough trust to hear which collapse still follows him.", metadata={"companion": "trp_npc15", "phase": "opening"}),
     quest_stage_spec("artimenner_siege_field_test", "Design or Blame", "Resolve an engineering incident through respected design or shifted blame.", rewards=("Engineer payoff if the design is respected",), failures=("blame compromise",), metadata={"companion": "trp_npc15", "phase": "test"}),
     quest_stage_spec("artimenner_siege_aftermath", "The Works Remembered", "Artimenner remembers whether structure mattered before reputation.", metadata={"companion": "trp_npc15", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Artimenner", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_klethi_knife_with_name",
    "Klethi: A Knife With a Name",
    0,
    "Klethi is testing whether belonging can be chosen without becoming another trap.",
    stages=(
     quest_stage_spec("klethi_knife_opening", "A Name on the Blade", "Speak with Klethi after earning enough trust to hear what old leverage still follows her.", metadata={"companion": "trp_npc16", "phase": "opening"}),
     quest_stage_spec("klethi_knife_field_test", "Choice or Leverage", "Resolve a secret or old-job incident by letting Klethi choose or using the secret.", rewards=("Spymaster payoff if belonging remains chosen",), failures=("leverage compromise",), metadata={"companion": "trp_npc16", "phase": "test"}),
     quest_stage_spec("klethi_knife_aftermath", "The Knife Remembered", "Klethi remembers whether the company gave her a place or another price tag.", metadata={"companion": "trp_npc16", "phase": "aftermath"}),
    ),
    metadata={"category": "companion", "companion": "Klethi", "depth_layer": "dragon_age_style"},
   ),
   quest_template_spec(
    "companion_bunduk_men_hold_line",
    "Bunduk: The Men Who Hold the Line",
    0,
    "Bunduk is testing whether command remembers the soldiers who make victory possible. Wages, casualties, and officer cruelty will decide his trust.",
    stages=(
     quest_stage_spec(
      "bunduk_line_opening",
      "The Line Has Names",
      "Speak with Bunduk after earning enough trust for him to name the men behind his anger.",
      description="Bunduk's personal arc opens when approval rises into trust.",
      actions=("trust conversation", "record companion memory"),
      metadata={"companion": "trp_npc10", "phase": "opening"},
     ),
     quest_stage_spec(
      "bunduk_line_field_test",
      "A Grievance in the Ranks",
      "Resolve a soldier grievance through advocacy, compromise, or crackdown.",
      description="The player chooses whether discipline protects ordinary soldiers or spends them.",
      conditions=("Bunduk in party", "wages, casualties, or officer abuse creates pressure"),
      actions=("advance from companion-depth world/menu hook",),
      rewards=("Captain role payoff if the line is protected",),
      failures=("Bunduk warning and hard compromise payoff if the line is silenced",),
      metadata={"companion": "trp_npc10", "phase": "test"},
     ),
     quest_stage_spec(
      "bunduk_line_aftermath",
      "The Men Remember",
      "Bunduk remembers whether command gave soldiers a voice or merely kept them useful.",
      description="The company report and direct talk remember the outcome.",
      metadata={"companion": "trp_npc10", "phase": "aftermath"},
     ),
    ),
    metadata={
     "category": "companion",
     "companion": "Bunduk",
     "depth_layer": "dragon_age_style",
    },
   ),
   quest_template_spec(
    "companion_jeremus_hands_triage",
    "Jeremus: Hands That Will Not Harden",
    0,
    "Jeremus is testing whether a healer can remain gentle while marching with an army. Battlefield triage and civilian mercy will decide the shape of his service.",
    stages=(
     quest_stage_spec(
      "jeremus_triage_opening",
      "The Healer's Burden",
      "Speak with Jeremus after earning enough trust for him to admit what war is doing to his hands.",
      description="Jeremus's personal arc opens when approval rises into trust.",
      actions=("trust conversation", "record companion memory"),
      metadata={"companion": "trp_npc12", "phase": "opening"},
     ),
     quest_stage_spec(
      "jeremus_triage_field_test",
      "Triage After Battle",
      "Resolve a casualty or civilian triage incident through care, prioritization, or hard necessity.",
      description="The player chooses whether healing is protected, rationed, or hardened.",
      conditions=("Jeremus in party", "casualties or civilians require triage"),
      actions=("advance from companion-depth world/menu hook",),
      rewards=("Surgeon role payoff if compassion survives triage",),
      failures=("Jeremus warning and hard compromise payoff if care is spent too cheaply",),
      metadata={"companion": "trp_npc12", "phase": "test"},
     ),
     quest_stage_spec(
      "jeremus_triage_aftermath",
      "What Remains Whole",
      "Jeremus remembers whether healing remained a duty or became another instrument of command.",
      description="The company report and direct talk remember the outcome.",
      metadata={"companion": "trp_npc12", "phase": "aftermath"},
     ),
    ),
    metadata={
     "category": "companion",
     "companion": "Jeremus",
     "depth_layer": "dragon_age_style",
    },
   ),
   quest_template_spec(
    "companion_firentis_debt_restitution",
    "Firentis: Debt of the Sword",
    0,
    "Firentis is testing whether service can become restitution rather than punishment. Mercy, restraint, and battlefield aftermath will decide what his sword means.",
    stages=(
     quest_stage_spec(
      "firentis_debt_opening",
      "A Debt Named Aloud",
      "Speak with Firentis after earning enough trust for him to explain the debt he carries.",
      description="Firentis's personal arc opens when approval rises into trust.",
      actions=("trust conversation", "record companion memory"),
      metadata={"companion": "trp_npc6", "phase": "opening"},
     ),
     quest_stage_spec(
      "firentis_debt_field_test",
      "Restraint Under Steel",
      "Resolve a battle aftermath or restitution incident through repair, penance, or hard justice.",
      description="The player chooses whether violence answers for itself or only wins.",
      conditions=("Firentis in party", "battlefield aftermath creates a restitution choice"),
      actions=("advance from companion-depth world/menu hook",),
      rewards=("Captain or Envoy role payoff if restitution is protected",),
      failures=("Firentis warning and hard compromise payoff if the debt deepens",),
      metadata={"companion": "trp_npc6", "phase": "test"},
     ),
     quest_stage_spec(
      "firentis_debt_aftermath",
      "The Sword Accounted",
      "Firentis remembers whether service became repair or merely another debt.",
      description="The company report and direct talk remember the outcome.",
      metadata={"companion": "trp_npc6", "phase": "aftermath"},
     ),
    ),
    metadata={
     "category": "companion",
     "companion": "Firentis",
     "depth_layer": "dragon_age_style",
    },
   ),
   quest_template_spec(
    "companion_ymira_mercy_under_arms",
    "Ymira: Mercy Under Arms",
    0,
    "Ymira has asked whether mercy can survive inside an army. Captives, refugees, and Slaver cruelty will test the answer.",
    stages=(
     quest_stage_spec(
      "ymira_mercy_opening",
      "A Question of Mercy",
      "Speak with Ymira after earning enough trust for her to name the wound behind her mercy.",
      description="Ymira's personal arc opens when approval rises into trust.",
      actions=("trust conversation", "record companion memory"),
      metadata={"companion": "trp_npc3", "phase": "opening"},
     ),
     quest_stage_spec(
      "ymira_mercy_field_test",
      "Captives on the Road",
      "Resolve a captive or refugee incident through protection, ransom, or hard expedience.",
      description="The player chooses whether mercy is protected, compromised, or spent.",
      conditions=("Ymira in party", "captives or refugees encountered"),
      actions=("advance from companion-depth world/menu hook",),
      rewards=("Surgeon role payoff if resolved mercifully",),
      failures=("Ymira warning and hard compromise payoff if resolved harshly",),
      metadata={"companion": "trp_npc3", "phase": "test"},
     ),
     quest_stage_spec(
      "ymira_mercy_aftermath",
      "The Names Remembered",
      "Ymira remembers whether command made room for mercy or merely survived without it.",
      description="The company report and direct talk remember the outcome.",
      metadata={"companion": "trp_npc3", "phase": "aftermath"},
     ),
    ),
    metadata={
     "category": "companion",
     "companion": "Ymira",
     "depth_layer": "dragon_age_style",
    },
   ),
   quest_template_spec(
    "companion_lezalit_discipline_without_chains",
    "Lezalit: Discipline Without Chains",
    0,
    "Lezalit is testing whether discipline must be cruel to remain strong. Imperial doctrine and battlefield command will decide how far he bends.",
    stages=(
     quest_stage_spec(
      "lezalit_discipline_opening",
      "A Soldier's Doctrine",
      "Speak with Lezalit after earning enough trust for him to discuss order, fear, and Imperial discipline.",
      description="Lezalit's personal arc opens when approval rises into trust.",
      actions=("trust conversation", "record companion memory"),
      metadata={"companion": "trp_npc14", "phase": "opening"},
     ),
     quest_stage_spec(
      "lezalit_discipline_field_test",
      "The Captured Drill",
      "Resolve an Imperial discipline test through reform, fear, or open defiance.",
      description="The player chooses what kind of army Lezalit should respect.",
      conditions=("Lezalit in party", "Imperial discipline incident available"),
      actions=("advance from companion-depth world/menu hook",),
      rewards=("Captain role payoff if resolved through disciplined reform",),
      failures=("Lezalit warning and hard compromise payoff if resolved through fear",),
      metadata={"companion": "trp_npc14", "phase": "test"},
     ),
     quest_stage_spec(
      "lezalit_discipline_aftermath",
      "Order Remembered",
      "Lezalit remembers whether strength learned restraint or merely sharpened fear.",
      description="The company report and direct talk remember the outcome.",
      metadata={"companion": "trp_npc14", "phase": "aftermath"},
     ),
    ),
    metadata={
     "category": "companion",
     "companion": "Lezalit",
     "depth_layer": "dragon_age_style",
    },
   ),
   quest_template_spec(
    "companion_cassian_last_order",
    "Cassian Varro: The Last Order",
    0,
    "Cassian Varro has opened the last sealed order your father left him. The order points toward an old Imperial spy network that may still be alive.",
    stages=(
     quest_stage_spec(
      "cassian_last_order_opening",
      "The Sealed Order",
      "Speak with Cassian Varro after you hold land or the invasion draws near.",
      description="Cassian reveals that he still carries one sealed order from your father.",
      actions=("direct mentor conversation", "record mentor memory"),
      metadata={"mentor": "trp_sod_strategy_advisor", "phase": "opening"},
     ),
     quest_stage_spec(
      "cassian_last_order_network",
      "The Old Network",
      "Choose how to use, expose, rescue, or burn Cassian's surviving Imperial network.",
      description="The old network can become sabotage, rescue, public reckoning, or mercy through destruction.",
      conditions=("Cassian's mentor arc is active", "focus center or cause stored"),
      actions=("direct dialogue resolution", "quest memory update", "mentor trust outcome"),
      rewards=("Improved mentor trust", "Legion memory", "strategic consequence"),
      failures=("reduced trust if the network is used without conscience",),
      metadata={"mentor": "trp_sod_strategy_advisor", "phase": "choice"},
     ),
     quest_stage_spec(
      "cassian_last_order_aftermath",
      "The Order Remembered",
      "Cassian remembers whether the last order became conscience, weapon, reckoning, or ash.",
      description="The mentor trust report and direct talk remember the outcome.",
      metadata={"mentor": "trp_sod_strategy_advisor", "phase": "aftermath"},
     ),
    ),
    metadata={
     "category": "mentor",
     "mentor": "Cassian Varro",
     "depth_layer": "strategy_advisor_mentor",
    },
   ),
  ),
 ).as_legacy_tuples(),
]
