DIALOGS = [
[anyone, "jotnar_world_hearth_about", [
   (call_script, "script_sod_jotnar_describe_status_to_s22"),
   (faction_get_slot, ":target_center", "fac_sod_merc_guild4", slot_faction_jotnar_target_center),
   (faction_get_slot, ":hearth_pressure", "fac_sod_merc_guild4", slot_faction_jotnar_hearth_pressure),
   (faction_get_slot, ":slaver_pressure", "fac_sod_merc_guild4", slot_faction_jotnar_slaver_pressure),
   (str_store_string, s21, "@no village in particular"),
   (try_begin),
     (gt, ":target_center", 0),
     (str_store_party_name_link, s21, ":target_center"),
   (try_end),
   (try_begin),
     (lt, ":hearth_pressure", 25),
     (str_store_string, s23, "@The hearth is quiet, but quiet is when watchfires matter"),
   (else_try),
     (lt, ":hearth_pressure", 55),
     (str_store_string, s23, "@The hearth is uneasy"),
   (else_try),
     (lt, ":hearth_pressure", 85),
     (str_store_string, s23, "@The hearth is under strain"),
   (else_try),
     (str_store_string, s23, "@The hearth is close to breaking"),
   (try_end),
   (try_begin),
     (lt, ":slaver_pressure", 25),
     (str_store_string, s24, "@slave-road danger is distant"),
   (else_try),
     (lt, ":slaver_pressure", 55),
     (str_store_string, s24, "@slave-road danger is moving nearby"),
   (else_try),
     (lt, ":slaver_pressure", 85),
     (str_store_string, s24, "@slave-road danger is hunting close"),
   (else_try),
     (str_store_string, s24, "@slave-road danger is at the door"),
   (try_end),
  ], "A clan survives by knowing where people are thin, sick, or hungry. The hearth is watching {s21}. {s23}; {s24}. If the village holds, we all have another road, another granary, another fire.", "jotnar_world_hearth_talk", []],
]
