DIALOGS = [
[anyone, "gm_qst_bc_capture_prisoners", [],
   "Good. Chains are poor company, but these prisoners give us leverage. Your pay is ready.", "gm_pretalk",
   [
     (try_begin),
       (eq, "$g_lords_quest", "qst_bc_capture_prisoners"),
       (check_quest_active, "qst_bc_capture_prisoners"),
       (quest_get_slot, ":quest_target_amount", "qst_bc_capture_prisoners", slot_quest_target_amount),
       (quest_get_slot, ":quest_target_troop", "qst_bc_capture_prisoners", slot_quest_target_troop),
       (party_count_prisoners_of_type, ":count_prisoners", "p_main_party", ":quest_target_troop"),
       (ge, ":count_prisoners", ":quest_target_amount"),
       (party_remove_prisoners, "p_main_party", ":quest_target_troop", ":quest_target_amount"),
       (quest_get_slot, ":gold", "qst_bc_capture_prisoners", slot_quest_gold_reward),
       (quest_get_slot, ":xp", "qst_bc_capture_prisoners", slot_quest_xp_reward),
       (add_xp_as_reward, ":xp"),
       (call_script, "script_troop_add_gold", "trp_player", ":gold"),
       (call_script, "script_change_player_relation_with_faction", "$g_talk_troop_faction", 5),
       (call_script, "script_succeed_quest", "qst_bc_capture_prisoners"),
       (call_script, "script_end_quest", "qst_bc_capture_prisoners"),
     (else_try),
       (display_message, "@The prisoner delivery could not be completed because the required captives were no longer in your party.", 0xFF6666),
     (try_end),
    ]],
]
