DIALOGS = [
[anyone, "party_encounter_mercs_ask", [
	(store_encountered_party, ":cur_party"),
	(assign, ":troop", -1),
	(str_store_string, s1, "@an unknown captain"),
	(str_store_string, s2, "@an unmarked company"),
	(str_store_string, s3, "@uncertain service"),
	(try_begin),
		(gt, ":cur_party", 0),
		(party_is_active, ":cur_party"),
		(party_get_slot, ":troop", ":cur_party", slot_party_boss),
	(try_end),
	(try_begin),
		(is_between, ":troop", 0, "trp_last_troop"),
		(call_script, "script_store_troop_name", s1, ":troop"),
		(store_troop_faction, ":troop_fac", ":troop"),
		(try_begin),
			(is_between, ":troop_fac", 0, "fac_factions_end"),
			(str_store_faction_name, s3, ":troop_fac"),
		(try_end),
	(try_end),
	(try_begin),
		(is_between, "$g_encountered_party_faction", 0, "fac_factions_end"),
		(str_store_faction_name, s2, "$g_encountered_party_faction"),
	(try_end),
	],"We are mercenaries from {s2}, hired by {s1} of {s3}.", "party_encounter_mercs", []],
]
