DIALOGS = [
[anyone|plyr, "gm_troublesome_bandits_quest_brief", [],
   "Alright. I will hunt down those bandits.", "gm_merchant_quest_taken_bandits",
   [(set_spawn_radius, 2),
	(faction_get_slot, ":merc_base", "$g_talk_troop_faction", slot_guild_base),
	(quest_get_slot, ":troops", "$random_quest_no", slot_quest_target_troop),
	(quest_get_slot, ":p_template", "$random_quest_no", slot_quest_target_party_template),
    (spawn_around_party, ":merc_base", ":p_template"),
    (quest_set_slot, "$random_quest_no", slot_quest_target_party, reg0),
	(str_store_party_name, s3, reg0),
	(store_character_level, ":plyr_lvl", "trp_player"),
	(val_mul, ":plyr_lvl", 2),
	(store_party_size, ":p_size", "p_main_party"),
	(store_random_in_range, ":rand", ":plyr_lvl", ":p_size"),
	(party_add_members, reg0, ":troops", ":rand"),
    (store_num_parties_destroyed_by_player, ":parties_eliminated", ":p_template"),
	(quest_set_slot, "$random_quest_no", slot_quest_bandits_eliminated_by_player, ":parties_eliminated"),
    (call_script, "script_store_troop_name_link", s9, "$g_talk_troop"),
    (setup_quest_text, "$random_quest_no"),
    (str_store_string, s2, "@{s9} asked you to hunt down the {s3} near the guild base."),
    (call_script, "script_start_quest", "$random_quest_no", "$g_talk_troop"),
    ]],
]
