SCRIPTS = [
("start_badboy_war",
     [ (assign, ":new_wars", 0),  # twan new
	   (assign, ":new_peaces", 0),
	 
	   (try_for_range, ":kingdom_no", "fac_kingdom_1", kingdoms_end), #twan453
       (faction_slot_eq, ":kingdom_no", slot_faction_state, sfs_active),
       (store_relation, ":rln", ":kingdom_no", "fac_player_supporters_faction"),
       (try_begin),
       (gt, ":rln", -1),
	   (val_add, ":new_wars", 1),
	   (str_store_faction_name, s4, ":kingdom_no"),
	   (try_begin),
	       (eq, ":new_wars", 1),
		   (assign, ":first_war", ":kingdom_no"),
		   (str_store_string, s31, "@Badboy War !^^{s4} declared war to you !"),
       (else_try),
            (eq, ":new_wars", 2),  	   
			(call_script, "script_diplomacy_start_war_between_kingdoms", ":kingdom_no", "fac_player_supporters_faction", 3),
			(str_store_string, s31, "@{s31}^^All realms of Calradia decided it's time to ally against you.^{s4} declared war to you too"),
	    (else_try),
		    (eq, ":new_wars", 3),  	   
			(call_script, "script_diplomacy_start_war_between_kingdoms", ":kingdom_no", "fac_player_supporters_faction", 3),
			(str_store_string, s31, "@{s31} and {s4} as well"),
		(else_try),
		    (eq, ":new_wars", 4),  	   
			(call_script, "script_diplomacy_start_war_between_kingdoms", ":kingdom_no", "fac_player_supporters_faction", 3),
			(str_store_string, s31, "@{s31} exactly as {s4}"),
		(else_try),
		    (eq, ":new_wars", 4),  	   
			(call_script, "script_diplomacy_start_war_between_kingdoms", ":kingdom_no", "fac_player_supporters_faction", 3),
			(str_store_string, s31, "@{s31} and {s4}"),
		(else_try),
		    (eq, ":new_wars", 6),  	   
			(call_script, "script_diplomacy_start_war_between_kingdoms", ":kingdom_no", "fac_player_supporters_faction", 3),
			(str_store_string, s31, "@{s31} and even the Legion"),
	   (try_end),
	   
       (try_for_range, ":other_kingdom_no", "fac_kingdom_1", kingdoms_end), #twan453
       (faction_slot_eq, ":other_kingdom_no", slot_faction_state, sfs_active),
       (store_relation, ":rln", ":kingdom_no", ":other_kingdom_no"),
	   (store_random_in_range, ":rnd", 0, 6),
	   (try_begin),
	   (this_or_next|eq, ":kingdom_no", "fac_kingdom_6"),
	   (eq, ":other_kingdom_no", "fac_kingdom_6"),
	   (assign, ":peace_chance", 1),
	   (else_try),
	   (assign, ":peace_chance", 3),
	   (try_end),
	   
       (try_begin), 
	   (le, ":rnd", ":peace_chance"),
	   (lt, ":rln", 0),
	   (call_script, "script_diplomacy_start_peace_between_kingdoms", ":kingdom_no", ":other_kingdom_no", 3),
       (val_add, ":new_peaces", 1),  	   
	   (str_store_faction_name, s4, ":kingdom_no"),
	   (str_store_faction_name, s5, ":other_kingdom_no"),
	   (str_store_string, s8, "@{s4} proposed peace to {s5} and it was accepted."),
       (try_end),
	   (try_begin),
	       (eq, ":new_peaces", 1),
		   (str_store_string, s6, "@The war between {s4} and {s5} has ended."),
		   (call_script, "script_diplomacy_start_peace_between_kingdoms", ":kingdom_no", ":other_kingdom_no", 3),
		   (str_store_string, s7, "@{s6}^{s8}"),
		   (assign, ":first_peace_1", ":kingdom_no"),
		   (assign, ":first_peace_2", ":other_kingdom_no"),
       (else_try),
	       (eq, ":new_peaces", 2),
		   (str_store_string, s7, "@They decided to end their wars :^{s6}^{s8}"),
	   (else_try),
           (str_store_string, s7, "@{s7}^{s8}"),  	   
	   (try_end),
	   
	   (try_end),  # end tries for range
	   (try_end),
	   
	   (try_begin),
	   (ge, ":new_wars", 1),
	   (call_script, "script_diplomacy_start_war_between_kingdoms", ":first_war", "fac_player_supporters_faction", 2), # display the only menu
	   (str_store_string, s31, "@{s31}.^^{s7}"),
	   (else_try),
	   (ge, ":new_peaces", 1),
	   (str_store_string, s31, "@Badboy War !^^All realms of Calradia decided it's time to ally against you.^{s7}"),
	   (call_script, "script_diplomacy_start_peace_between_kingdoms", ":first_peace_1", ":first_peace_2", 2), # display the only menu
	   (else_try),
	   (faction_set_slot, "fac_player_supporters_faction", slot_faction_badboy_rating, 39), # avoid to reset badboy to 32 if badboy war had no effect
	   (try_end),	   #twan new
  ]),
]
