PRESENTATIONS = [
("sliders",0,0,[
      (ti_on_presentation_load,
       [(set_fixed_point_multiplier, 1000),
        (create_slider_overlay, "$g_presentation_obj_1", 0, 100),
        (create_slider_overlay, "$g_presentation_obj_2", 0, 100),
        (create_slider_overlay, "$g_presentation_obj_3", 0, 100),
        (create_slider_overlay, "$g_presentation_obj_4", 0, 100),
        (assign, reg1, 25),
        (str_store_string, s1, "str_reg1"),
        (create_text_overlay, "$g_presentation_obj_5", s1),
        (create_text_overlay, "$g_presentation_obj_6", s1),
        (create_text_overlay, "$g_presentation_obj_7", s1),
        (create_text_overlay, "$g_presentation_obj_8", s1),
        (assign, "$g_presentation_obj_1_val", 25),
        (overlay_set_val, "$g_presentation_obj_1", 25),
        (assign, "$g_presentation_obj_2_val", 25),
        (overlay_set_val, "$g_presentation_obj_2", 25),
        (assign, "$g_presentation_obj_3_val", 25),
        (overlay_set_val, "$g_presentation_obj_3", 25),
        (assign, "$g_presentation_obj_4_val", 25),
        (overlay_set_val, "$g_presentation_obj_4", 25),
        (position_set_x, pos1, 600),
        (position_set_y, pos1, 200),
        (overlay_set_position, "$g_presentation_obj_1", pos1),
        (position_set_y, pos1, 300),
        (overlay_set_position, "$g_presentation_obj_2", pos1),
        (position_set_y, pos1, 400),
        (overlay_set_position, "$g_presentation_obj_3", pos1),
        (position_set_y, pos1, 500),
        (overlay_set_position, "$g_presentation_obj_4", pos1),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 200),
        (overlay_set_position, "$g_presentation_obj_5", pos1),
        (position_set_y, pos1, 300),
        (overlay_set_position, "$g_presentation_obj_6", pos1),
        (position_set_y, pos1, 400),
        (overlay_set_position, "$g_presentation_obj_7", pos1),
        (position_set_y, pos1, 500),
        (overlay_set_position, "$g_presentation_obj_8", pos1),
        (position_set_x, pos1, 500),
        (overlay_set_size, "$g_presentation_obj_3", pos1),
        ]),
      (ti_on_presentation_run,
       [
        ]),
      (ti_on_presentation_event_state_change,
       [(store_trigger_param_1, ":object"),
        (store_trigger_param_2, ":value"),
        (val_clamp, ":value", 0, 101),
        (assign, ":val_changed", 0),
        (assign, ":old_value", 0),
        (try_begin),
          (eq, ":object", "$g_presentation_obj_1"),
          (try_begin),
            (neq, "$g_presentation_obj_1_val", ":value"),
            (assign, ":old_value", "$g_presentation_obj_1_val"),
            (assign, "$g_presentation_obj_1_val", ":value"),
            (assign, ":val_changed", 1),
          (try_end),
        (else_try),
          (eq, ":object", "$g_presentation_obj_2"),
          (try_begin),
            (neq, "$g_presentation_obj_2_val", ":value"),
            (assign, ":old_value", "$g_presentation_obj_2_val"),
            (assign, "$g_presentation_obj_2_val", ":value"),
            (assign, ":val_changed", 1),
          (try_end),
        (else_try),
          (eq, ":object", "$g_presentation_obj_3"),
          (try_begin),
            (neq, "$g_presentation_obj_3_val", ":value"),
            (assign, ":old_value", "$g_presentation_obj_3_val"),
            (assign, "$g_presentation_obj_3_val", ":value"),
            (assign, ":val_changed", 1),
          (try_end),
        (else_try),
          (eq, ":object", "$g_presentation_obj_4"),
          (try_begin),
            (neq, "$g_presentation_obj_4_val", ":value"),
            (assign, ":old_value", "$g_presentation_obj_4_val"),
            (assign, "$g_presentation_obj_4_val", ":value"),
            (assign, ":val_changed", 1),
          (try_end),
        (try_end),
        (try_begin),
          (eq, ":val_changed", 1),
          (val_clamp, "$g_presentation_obj_1_val", 0, 101),
          (val_clamp, "$g_presentation_obj_2_val", 0, 101),
          (val_clamp, "$g_presentation_obj_3_val", 0, 101),
          (val_clamp, "$g_presentation_obj_4_val", 0, 101),
          (store_sub, ":delta", ":value", ":old_value"),
          (try_begin),
            (gt, ":delta", 0),
            (assign, ":remaining_delta", ":delta"),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_1"),
              (gt, ":remaining_delta", 0),
              (assign, ":transfer", "$g_presentation_obj_1_val"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_sub, "$g_presentation_obj_1_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_2"),
              (gt, ":remaining_delta", 0),
              (assign, ":transfer", "$g_presentation_obj_2_val"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_sub, "$g_presentation_obj_2_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_3"),
              (gt, ":remaining_delta", 0),
              (assign, ":transfer", "$g_presentation_obj_3_val"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_sub, "$g_presentation_obj_3_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_4"),
              (gt, ":remaining_delta", 0),
              (assign, ":transfer", "$g_presentation_obj_4_val"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_sub, "$g_presentation_obj_4_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
            (try_begin),
              (gt, ":remaining_delta", 0),
              (val_sub, ":value", ":remaining_delta"),
              (try_begin),
                (eq, ":object", "$g_presentation_obj_1"),
                (assign, "$g_presentation_obj_1_val", ":value"),
              (else_try),
                (eq, ":object", "$g_presentation_obj_2"),
                (assign, "$g_presentation_obj_2_val", ":value"),
              (else_try),
                (eq, ":object", "$g_presentation_obj_3"),
                (assign, "$g_presentation_obj_3_val", ":value"),
              (else_try),
                (eq, ":object", "$g_presentation_obj_4"),
                (assign, "$g_presentation_obj_4_val", ":value"),
              (try_end),
            (try_end),
          (else_try),
            (lt, ":delta", 0),
            (store_mul, ":remaining_delta", ":delta", -1),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_1"),
              (gt, ":remaining_delta", 0),
              (store_sub, ":room", 100, "$g_presentation_obj_1_val"),
              (assign, ":transfer", ":room"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_add, "$g_presentation_obj_1_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_2"),
              (gt, ":remaining_delta", 0),
              (store_sub, ":room", 100, "$g_presentation_obj_2_val"),
              (assign, ":transfer", ":room"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_add, "$g_presentation_obj_2_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_3"),
              (gt, ":remaining_delta", 0),
              (store_sub, ":room", 100, "$g_presentation_obj_3_val"),
              (assign, ":transfer", ":room"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_add, "$g_presentation_obj_3_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
            (try_begin),
              (neq, ":object", "$g_presentation_obj_4"),
              (gt, ":remaining_delta", 0),
              (store_sub, ":room", 100, "$g_presentation_obj_4_val"),
              (assign, ":transfer", ":room"),
              (val_min, ":transfer", ":remaining_delta"),
              (val_add, "$g_presentation_obj_4_val", ":transfer"),
              (val_sub, ":remaining_delta", ":transfer"),
            (try_end),
          (try_end),
          (val_clamp, "$g_presentation_obj_1_val", 0, 101),
          (val_clamp, "$g_presentation_obj_2_val", 0, 101),
          (val_clamp, "$g_presentation_obj_3_val", 0, 101),
          (val_clamp, "$g_presentation_obj_4_val", 0, 101),
        (try_end),
        (overlay_set_val, "$g_presentation_obj_1", "$g_presentation_obj_1_val"),
        (overlay_set_val, "$g_presentation_obj_2", "$g_presentation_obj_2_val"),
        (overlay_set_val, "$g_presentation_obj_3", "$g_presentation_obj_3_val"),
        (overlay_set_val, "$g_presentation_obj_4", "$g_presentation_obj_4_val"),
        (assign, reg1, "$g_presentation_obj_1_val"),
        (str_store_string, s1, "str_reg1"),
        (overlay_set_text, "$g_presentation_obj_5", s1),
        (assign, reg1, "$g_presentation_obj_2_val"),
        (str_store_string, s1, "str_reg1"),
        (overlay_set_text, "$g_presentation_obj_6", s1),
        (assign, reg1, "$g_presentation_obj_3_val"),
        (str_store_string, s1, "str_reg1"),
        (overlay_set_text, "$g_presentation_obj_7", s1),
        (assign, reg1, "$g_presentation_obj_4_val"),
        (str_store_string, s1, "str_reg1"),
        (overlay_set_text, "$g_presentation_obj_8", s1),
        ]),
      ]),
]
