MISSION_TEMPLATES = [
(
    "custom_battle_siege", mtf_battle_mode, -1,
    "You lead your men to battle.",
    [
      (0, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (1, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (2, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (3, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (4, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (5, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (6, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (7, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),

      (8, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (9, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (10, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (11, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (12, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (13, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (14, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),
      (15, mtef_visitor_source|mtef_team_0, af_override_horse, aif_start_alarmed, 1, []),

      (16, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (17, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (18, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (19, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (20, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (21, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (22, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (23, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),

      (24, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (25, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (26, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (27, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (28, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (29, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (30, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
      (31, mtef_visitor_source|mtef_team_1, af_override_horse, aif_start_alarmed, 1, []),
     ],
    [
      common_battle_mission_start,
      common_battle_xp_log_suppression_tick,

      (0, 0, ti_once,
       [
         (assign, "$defender_team", 0),
         (assign, "$attacker_team", 1),
         (assign, "$defender_team_2", 2),
         (assign, "$attacker_team_2", 3),
         ], []),

      common_custom_battle_tab_press,
      common_custom_battle_question_answered,
      common_inventory_not_available,
      common_custom_siege_init,
      common_music_situation_update,
      custom_battle_check_victory_condition,
      custom_battle_check_defeat_condition,
      common_siege_attacker_do_not_stall,
      common_siege_refill_ammo,
      common_siege_init_ai_and_belfry,
      common_siege_move_belfry,
      common_siege_rotate_belfry,
      common_siege_assign_men_to_belfry,
      common_siege_ai_trigger_init_2,
	  common_battle_order_panel,
      common_battle_order_panel_tick,
      ],
    ),
]
