SIMPLE_TRIGGERS = [
(10,
    [
      (try_for_range, ":troop_no", kingdom_heroes_begin, kingdom_heroes_end),
        (assign, ":modifier", 1),
		
        (try_begin),  #twan453 begin
        (eq, "$g_sod_deactivate_lords_ai", 1), 		
			(try_for_range,":num",centers_begin,centers_end),
			   (party_slot_eq, ":num", slot_town_lord, ":troop_no"),
			   (try_begin),
				 (is_between,":num",towns_begin,towns_end),
				 (val_add,":modifier",3),
			   (else_try),
				 (is_between,":num",castles_begin,castles_end),
				 (val_add,":modifier",2),
			   (else_try),
				 (val_add,":modifier",1),
			   (try_end),
			 (try_end),
		(try_end), 
        (troop_get_slot, ":party_no", ":troop_no", slot_troop_leaded_party),
		(store_troop_faction, ":faction_no", ":troop_no"),
		
		(try_begin),
			(gt, ":party_no", 0),
			(party_is_active, ":party_no"),
			# (store_party_size, ":size"),
			# (val_div, ":size", 10),
			(eq, ":faction_no", "fac_player_supporters_faction"),
			(store_party_size, ":size", ":party_no"),
			(val_div, ":size", 20),
			(val_add, ":modifier", ":size"),
		(try_end),   
		
        (try_begin),
          (gt, ":party_no", 0),
          (party_get_slot, ":commander_party", ":party_no", slot_party_commander_party),
          (ge, ":commander_party", 0),
          (store_faction_of_party, ":faction_no", ":party_no"),
          (faction_get_slot, ":faction_marshall", ":faction_no", slot_faction_marshall),
          (ge, ":faction_marshall", 0),
          (troop_get_slot, ":marshall_party", ":faction_marshall", slot_troop_leaded_party),
          (eq, ":commander_party", ":marshall_party"),
			  (try_begin),
			  (eq, "$g_sod_deactivate_ai", 1),
			  (assign, ":modifier", -2),
			  (else_try),
			  (assign, ":modifier", -1),
			  (try_end),#twan453 end
        (try_end),
        (troop_get_slot, ":readiness", ":troop_no", slot_troop_readiness_to_join_army),
        (val_add, ":readiness", ":modifier"),
        (val_clamp, ":readiness", 0, 101),
        (troop_set_slot, ":troop_no", slot_troop_readiness_to_join_army, ":readiness"),
		(troop_set_slot, ":troop_no", slot_troop_readiness_to_follow_orders, ":readiness"),
        # (assign, ":modifier", 1),
        # (try_begin),
          # (gt, ":party_no", 0),
          # (store_troop_faction, ":troop_faction", ":troop_no"),
          # (eq, ":troop_faction", "fac_player_supporters_faction"),
          # (neg|troop_slot_eq, ":troop_no", slot_troop_player_order_state, spai_undefined),
          # (party_get_slot, ":party_ai_state", ":party_no", slot_party_ai_state),
          # (party_get_slot, ":party_ai_object", ":party_no", slot_party_ai_object),
          #Check if party is following player orders
          # (try_begin),
            # (troop_slot_eq, ":troop_no", slot_troop_player_order_state, ":party_ai_state"),
            # (troop_slot_eq, ":troop_no", slot_troop_player_order_object, ":party_ai_object"),
            # (assign, ":modifier", -1),
          # (else_try),
            #Leaving following player orders if the current party order is not the same.
            # (troop_set_slot, ":troop_no", slot_troop_player_order_state, spai_undefined),
            # (troop_set_slot, ":troop_no", slot_troop_player_order_object, -1),
          # (try_end),
        # (try_end),
        # (troop_get_slot, ":readiness", ":troop_no", slot_troop_readiness_to_follow_orders),
        # (val_add, ":readiness", ":modifier"),
        # (val_clamp, ":readiness", 0, 101),
        # ,
        (try_begin),
          (lt, ":readiness", 10),
          (troop_set_slot, ":troop_no", slot_troop_player_order_state, spai_undefined),
          (troop_set_slot, ":troop_no", slot_troop_player_order_object, -1),
        (try_end),
      (try_end),
      ]),
]
