# -*- coding: cp1252 -*-
# AUTO-GENERATED by build/build_quests.py (do not edit by hand)
# -*- coding: utf-8 -*-
# Shared quest authoring helpers injected into compile/module_quests.py by build/build_quests.py.
from header_quests import qf_random_quest
from src.quests.quest_schema import (
    QuestAction,
    QuestBlueprint,
    QuestChain,
    QuestChainSpec,
    QuestComponentRegistry,
    QuestCondition,
    QuestDiagnostic,
    QuestDiagnosticsReport,
    QuestFailure,
    QuestLaneContract,
    QuestNPCState,
    QuestOffer,
    QuestBranch,
    QuestReward,
    QuestStage,
    QuestStageSpec,
    QuestTemplate,
    QuestTemplateSpec,
    QuestTrigger,
    QuestWorldContext,
    DEFAULT_DYNAMIC_QUEST_TEMPLATES,
    DynamicQuestTemplate,
    GeneratedQuestOffer,
    QUEST_GENERATION_INPUTS,
    QUEST_GENERATION_TYPES,
    QuestGenerationContext,
    QuestGenerationRule,
    ambush_quest,
    delivery_quest,
    diplomacy_quest,
    dynamic_quest_template,
    escort_quest,
    generate_dynamic_quest_offers,
    ensure_unique_quest_ids,
    hunt_quest,
    investigation_quest,
    quest_generation_context_from_mapping,
    quest_generation_rule,
    quest_action,
    quest_branch,
    quest_blueprint,
    quest_chain,
    quest_chain_from_specs,
    quest_chain_spec,
    quest_chain_spec_from_mapping,
    quest_components_from_mapping,
    quest_component_registry,
    quest_condition,
    quest_dialogue_lanes,
    quest_delivery_quest,
    quest_escort_quest,
    quest_failure_bundle,
    quest_failure,
    quest_graph_dot,
    quest_graph_mermaid,
    quest_graph_report_json,
    quest_graph_snapshot,
    quest_graph_snapshots,
    quest_hunt_quest,
    quest_motif_from_mapping,
    quest_motif_delivery_complication_reward,
    quest_motif_escort_ambush_debrief,
    quest_motif_linear_chain,
    quest_motif_rescue_pursuit_return,
    quest_npc_state,
    quest_optional_stage,
    quest_offer,
    quest_lane_contract,
    quest_outcome_triggers,
    quest_repeatable_stage,
    quest_rescue_quest,
    quest_reward,
    quest_reward_bundle,
    quest_battle_objective,
    quest_single_stage_quest,
    quest_stage,
    quest_stage_spec,
    quest_stage_spec_from_mapping,
    quest_template,
    quest_template_spec,
    quest_template_spec_from_mapping,
    quest_timed_stage,
    rescue_quest,
    siege_quest,
    quest_trigger,
    quest_world_context,
    validate_quest_id,
    validate_dynamic_generation_templates,
    validate_quest_chain_graph,
    validate_quest_template_graph,
)
# -*- coding: utf-8 -*-
# Shared quest runtime and event helpers injected into compile/module_quests.py by build/build_quests.py.
from src.quests.quest_events import (
    QuestEventDispatchRecord,
    QuestEventDispatcher,
    QuestEventSubscription,
    QuestWorldEvent,
    quest_agent_killed_event,
    quest_battle_ended_event,
    quest_battle_started_event,
    quest_caravan_created_event,
    quest_caravan_destroyed_event,
    quest_center_besieged_event,
    quest_conversation_ended_event,
    quest_conversation_started_event,
    quest_event_category,
    quest_event_dispatcher,
    quest_event_matches,
    quest_event_spec,
    quest_event_subscription,
    quest_event_subscriptions_from_specs,
    quest_faction_state_changed_event,
    quest_inventory_updated_event,
    quest_item_acquired_event,
    quest_item_lost_event,
    quest_mission_failed_event,
    quest_mission_succeeded_event,
    quest_party_entered_center_event,
    quest_prisoner_captured_event,
    quest_prisoner_freed_event,
    quest_relation_changed_event,
    quest_time_passed_event,
    quest_village_raided_event,
    quest_world_event,
    quest_world_event_subscription,
)
from src.quests.quest_runtime import (
    QUEST_STAGE_ACTIVE,
    QUEST_STAGE_ABORTED,
    QUEST_STAGE_COMPLETED,
    QUEST_STAGE_FAILED,
    QUEST_STAGE_PENDING,
    QUEST_STATE_ACTIVE,
    QUEST_STATE_ABORTED,
    QUEST_STATE_ABORTED as QUEST_STATE_CANCELLED,
    QUEST_STATE_ABORTED as QUEST_STATE_CANCELED,
    QUEST_STATE_ABORTED as QUEST_STATE_STOPPED,
    QUEST_STATE_COMPLETED,
    QUEST_STATE_FAILED,
    QUEST_STATE_INACTIVE,
    QuestJournal,
    QuestProgressEvent,
    QuestRuntime,
    QuestStageRuntime,
    quest_journal_from_blueprints,
    quest_journal_from_chain,
    quest_runtime_from_blueprint,
)

# [ src/quests/0001_prison_break_chain.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.
#
# Schema-backed authoring example:
# - quest_chain_from_specs groups related quests
# - quest_template_spec captures the legacy quest tuple shape plus richer metadata
# - quest_stage_spec keeps stage authoring compact for future runtime integration

# [ src/quests/0002_mercenary_guild_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.

# [ src/quests/0003_lord_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.

# [ src/quests/0004_enemy_lord_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.

# [ src/quests/0005_army_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.

# [ src/quests/0006_lady_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.

# [ src/quests/0007_mayor_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.

# [ src/quests/0008_village_elder_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.

# [ src/quests/0009_story_and_meta_quests.py ]
# -*- coding: utf-8 -*-
# Auto-generated from src/quests/0001_all_quests.py.
# Keep quest definitions in the numbered fragments and rebuild with build/build_quests.py.
#
# Schema-backed authoring example:
# - quest_chain_from_specs groups related quests
# - quest_template_spec captures the legacy quest tuple shape plus richer metadata
# - quest_stage_spec keeps stage authoring compact for future runtime integration

# [ src/quests/0010_sample_campaign_quests.py ]
# -*- coding: utf-8 -*-
# Sample campaign fragment showing a quest chain authored with the schema helpers.
# Keep quest definitions in numbered fragments and rebuild with build/build_quests.py.
#
# SAMPLE CAMPAIGN AUTHORING NOTES
# -------------------------------
# This file is intentionally more verbose than normal production content. It is
# both a compile-safe quest fragment and a living feature tour for the Advanced
# Quest framework. When adding a new framework helper, add at least one compact
# usage here and leave a short note explaining why the helper exists.
#
# The sample has two jobs:
# 1. Keep a realistic, multi-quest campaign arc in QUESTS so legacy tuple output
#    remains stable.
# 2. Keep small preview objects near the top so authors can copy a minimal
#    pattern without reading the entire stress-test chain.
#
# FEATURE COVERAGE CHECKLIST
# --------------------------
# - quest_chain_from_specs for a grouped campaign arc
# - quest_template_spec for single-stage and multi-stage quest templates
# - quest_stage_spec and mapping-based stage authoring
# - stage metadata, quest metadata, transitions, and dialogue/choice-oriented text
# - quest_condition, quest_action, quest_reward, quest_failure, and quest_trigger helpers
# - quest_offer, quest_template, quest_blueprint, and the delivery/hunt/escort/rescue
#   convenience helpers
# - quest_npc_state, quest_world_context, and quest_battle_objective helpers
# - QuestComponentRegistry plus both manual and mapping-based registry population
# - quest_motif_from_mapping and named motif helpers through a compact motif demo
# - quest_reward_bundle, quest_failure_bundle, quest_branch, optional/timed/repeatable
#   DSL stages, and graph snapshot/report/diagram helpers
# - quest_lane_contract, quest_dialogue_lanes, and quest_outcome_triggers for
#   connecting graph lanes to dialogue, journal, and outcome trigger names
#
# Everything lives inside QUESTS so build/build_quests.py copies a self-contained
# payload into compile/module_quests.py.
#
# The terminal quests_end sentinel stays in the final fragment so quest ids remain stable.

# NOTE: Registry setup.
# The registry gives authors named, reusable building blocks. This sample keeps
# one manually constructed registry and one mapping-constructed registry so both
# authoring styles are covered. Production quest files should prefer the mapping
# form when a family has many reusable components.
SAMPLE_AUTHORING_REGISTRY = quest_component_registry(
 "sample_authoring_registry",
 metadata={"category": "sample", "framework": "component_registry"},
)
SAMPLE_AUTHORING_REGISTRY.update_from_mapping(
 {
  "conditions": {
   "contract_ready": "contract ready",
  },
  "actions": {
   "brief_patrol": "brief patrol",
  },
  "rewards": {
   "route_secured": "route secured",
  },
  "failures": {
   "route_lost": "route lost",
  },
 }
)

SAMPLE_BULK_AUTHORING_REGISTRY = quest_components_from_mapping(
 "sample_bulk_authoring_registry",
 {
  "conditions": {
   "captain_available": "captain available",
  },
  "actions": {
   "mark_route": "mark route",
  },
  "rewards": {
   "captain_trust": "captain trust improved",
  },
  "failures": {
   "captain_doubt": "captain confidence lost",
  },
 },
 metadata={"category": "sample", "framework": "component_registry_bulk"},
)

# NOTE: DSL preview objects.
# These are stored as metadata previews rather than emitted as standalone legacy
# quests. They keep the sample's main campaign readable while still proving the
# DSL helpers can create structured rewards, failures, branches, and stage
# variants. Copy these patterns into real quest stages when authoring content.
SAMPLE_DSL_REWARDS = quest_reward_bundle(
 "sample_campaign_dsl_rewards",
 "captain praise",
 gold=150,
 xp=75,
 renown=1,
 metadata={"category": "sample", "framework": "dsl_reward_bundle"},
)
SAMPLE_DSL_FAILURES = quest_failure_bundle(
 "sample_campaign_dsl_failures",
 "captain disappointed",
 relation=-1,
 cooldown_days=2,
 metadata={"category": "sample", "framework": "dsl_failure_bundle"},
)
SAMPLE_DSL_BRANCH = quest_branch(
 "sample_campaign_dsl_success",
 "sample_campaign_dsl_optional",
 from_stage="sample_campaign_dsl_start",
 condition="success",
 description="A preview branch used by the optional/timed/repeatable stage examples.",
 metadata={"category": "sample", "framework": "dsl_branch"},
)
SAMPLE_DSL_OPTIONAL_STAGE = quest_optional_stage(
 "sample_campaign_dsl_optional",
 "Optional Road Clue",
 "Find the optional road clue before committing the patrol.",
 rewards=SAMPLE_DSL_REWARDS,
 metadata={"category": "sample", "framework": "dsl_optional_stage"},
)
SAMPLE_DSL_TIMED_STAGE = quest_timed_stage(
 "sample_campaign_dsl_timed",
 "Timed Patrol Muster",
 "Muster the patrol before the gate closes.",
 duration_hours=8,
 transitions=(SAMPLE_DSL_BRANCH,),
 failures=SAMPLE_DSL_FAILURES,
 metadata={"category": "sample", "framework": "dsl_timed_stage"},
)
SAMPLE_DSL_REPEATABLE_STAGE = quest_repeatable_stage(
 "sample_campaign_dsl_repeatable",
 "Repeat Watch Sweep",
 "Repeat the watch sweep until the route is quiet.",
 max_repeats=3,
 repeat_cooldown_days=1,
 rewards=SAMPLE_DSL_REWARDS,
 metadata={"category": "sample", "framework": "dsl_repeatable_stage"},
)

# NOTE: Quest lane contract preview.
# Lanes are the bridge between a graph edge and actual gameplay surfaces. A
# transition such as "accepted" is only useful when dialogue, journal text, and
# script/outcome triggers agree on what that lane means.
SAMPLE_LANE_CONTRACT = quest_lane_contract(
 "sample_campaign_lane_contract",
 dialogue_lanes=quest_dialogue_lanes(
  offer="sample_campaign_offer_lane",
  accepted="sample_campaign_accepted_lane",
  declined="sample_campaign_declined_lane",
  success="sample_campaign_success_lane",
  failure="sample_campaign_failure_lane",
  complete="sample_campaign_complete_lane",
 ),
 outcome_triggers=quest_outcome_triggers(
  success="sample_campaign_success_trigger",
  failure="sample_campaign_failure_trigger",
  complete="sample_campaign_complete_trigger",
 ),
 journal_lanes={
  "offer": "sample_campaign_offer_journal",
  "accepted": "sample_campaign_accepted_journal",
  "declined": "sample_campaign_declined_journal",
  "success": "sample_campaign_success_journal",
  "failure": "sample_campaign_failure_journal",
  "complete": "sample_campaign_complete_journal",
 },
 required_lanes=("offer", "accepted", "declined"),
 required_outcomes=("success", "failure"),
 metadata={"category": "sample", "framework": "lane_contract"},
)

# NOTE: Motif and graph preview.
# Motifs are intentionally compact. The detailed campaign below remains the
# stress test; this motif is the copy-friendly version that shows how a new
# author can get a chain, registry defaults, graph snapshots, and diagram text
# with very little boilerplate.
SAMPLE_MOTIF_CHAIN = quest_motif_from_mapping(
 {
  "chain_id": "sample_campaign_motif",
  "title": "Sample Campaign Motif",
  "motif": "escort_ambush_debrief",
  "flags": qf_random_quest,
  "registry": SAMPLE_AUTHORING_REGISTRY,
  "metadata": {
   "category": "sample",
   "framework": "motif_demo",
   "registry": SAMPLE_AUTHORING_REGISTRY.snapshot(),
   "lane_contract": SAMPLE_LANE_CONTRACT.to_snapshot(),
  },
 }
)
SAMPLE_MOTIF_SNAPSHOTS = quest_graph_snapshots((SAMPLE_MOTIF_CHAIN,))
SAMPLE_MOTIF_GRAPH_REPORT = quest_graph_report_json((SAMPLE_MOTIF_CHAIN,), diagnostics=())
SAMPLE_MOTIF_MERMAID = quest_graph_mermaid(SAMPLE_MOTIF_CHAIN)
SAMPLE_MOTIF_DOT = quest_graph_dot(SAMPLE_MOTIF_CHAIN)

# NOTE: Legacy payload.
# Only objects expanded inside QUESTS become legacy quest tuples. Preview
# objects above are intentionally included through metadata snapshots so the
# compiler receives the same tuple shape while the framework still exercises
# richer authoring/reporting features.

quests = [

# [ src/quests/0001_prison_break_chain.py ]

 *quest_chain_from_specs(
  "prison_break_chain",
  "Prison Break Chain",
  quests=(
   quest_template_spec(
    "slave_q1",
    "Deliver message to {s13}",
    0,
    "Diego, a village elder imprisoned by the Slavers, asked you to take a message to his old friend {s13}.",
    stage_title="Deliver Diego's Message",
    stage_objective="Take Diego's message to {s13}.",
    stage_description="Travel to the target and deliver the message from Diego.",
    metadata={
     "category": "story",
     "authoring": "schema",
     "chain": "prison_break_chain",
     "sequence": 1,
    },
    stage_metadata={
     "phase": "intro",
     "tracking": "delivery",
    },
   ),
   quest_template_spec(
    "slave_q2",
    "Return to Diego with the bad news",
    0,
    "The lord you spoke with refused to help Diego directly. Return to Diego and tell him the bad news.",
    stage_title="Report Back to Diego",
    stage_objective="Return to Diego with the bad news.",
    stage_description="Tell Diego that his request was denied and close out the failed diplomacy step.",
    metadata={
     "category": "story",
     "authoring": "schema",
     "chain": "prison_break_chain",
     "sequence": 2,
    },
    stage_metadata={
     "phase": "followup",
     "tracking": "reporting",
    },
   ),
   quest_template_spec(
    "slave_q3",
    "Prison Break",
    0,
    "Free Diego and fight your way out of the dungeon.",
    stage_title="Break Out of the Dungeon",
    stage_objective="Free Diego and escape the dungeon.",
    stage_description="Force a breakout, secure Diego, and fight through the escape route.",
    metadata={
     "category": "story",
     "authoring": "schema",
     "chain": "prison_break_chain",
     "sequence": 3,
    },
    stage_metadata={
     "phase": "escape",
     "tracking": "rescue",
    },
   ),
  ),
  metadata={
   "category": "story",
   "authoring": "schema",
   "legacy_fragment": "0001_prison_break_chain",
   "converted_from": "legacy_tuple_fragment",
  },
 ).as_legacy_tuples(),

# --- 0002_mercenary_guild_quests.py ---
# [ src/quests/0002_mercenary_guild_quests.py:L6-L8 ] bc_deliver_message
 ("bc_deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L10-L12 ] bc_troublesome_bandits
 ("bc_troublesome_bandits", "Hunt down bandits", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L14-L16 ] bc_raise_troops
 ("bc_raise_troops", "Recruit {reg1} man", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L18-L20 ] bc_hunt_down_fugitive
 ("bc_hunt_down_fugitive", "Punish fugitive", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L22-L27 ] bc_capture_prisoners
 ("bc_capture_prisoners", "Bring {reg1} {s3} Prisoners", qf_random_quest,
  "{s9} wanted you to bring him {reg1} {s3} as prisoners."
  ),
 # ("bc_fight_guild_troops_lh", "Redemption", qf_random_quest,
  # "none"
  # ),
# [ src/quests/0002_mercenary_guild_quests.py:L29-L32 ] bc_fight_guild_troops
 ("bc_fight_guild_troops", "Try-out", qf_random_quest,
  "none"
  ),
# Slavers,
# [ src/quests/0002_mercenary_guild_quests.py:L34-L36 ] slavers_deliver_message
 ("slavers_deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L38-L40 ] slavers_deliver_wine
 ("slavers_deliver_wine", "Smuggle wine to {s4}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L42-L44 ] slavers_collect_debt
 ("slavers_collect_debt", "Collect the debt {s3} owes to the Slavers", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L46-L48 ] slavers_escort_merchant_caravan
 ("slavers_escort_merchant_caravan", "Move slaves to {s8}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L50-L52 ] slavers_bring_back_runaway_slaves
 ("slavers_bring_back_runaway_slaves", "Bring back runaway slaves", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L54-L56 ] slavers_deal_with_good_guys
 ("slavers_deal_with_good_guys", "Deal with the Good Guys", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L58-L61 ] slavers_fight_guild_troops
 ("slavers_fight_guild_troops", "Underground arena matches", qf_random_quest,
  "none"
  ),
#serpent_host,
# [ src/quests/0002_mercenary_guild_quests.py:L63-L65 ] serpent_host_deliver_message
 ("serpent_host_deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L67-L69 ] serpent_host_raise_troops
 ("serpent_host_raise_troops", "Raise {reg1} man", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L71-L73 ] serpent_host_troublesome_bandits
 ("serpent_host_troublesome_bandits", "Kill Deserters", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L75-L77 ] serpent_host_competition
 ("serpent_host_competition", "Take part in competition", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L79-L81 ] serpent_host_raid_caravan
 ("serpent_host_raid_caravan", "Raid a Caravan of {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L83-L85 ] serpent_host_free_spy
 ("serpent_host_free_spy", "Free Spy", qf_random_quest,
  "none"
 ),
# [ src/quests/0002_mercenary_guild_quests.py:L87-L89 ] serpent_host_fight_guild_troops
 ("serpent_host_fight_guild_troops", "Arena championship", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L91-L94 ] serpent_host_fight_guild_troops_2
 ("serpent_host_fight_guild_troops_2", "Gaze of the Basilisk", qf_random_quest,
  "none"
  ),
# elephant_guard_,
# [ src/quests/0002_mercenary_guild_quests.py:L96-L98 ] elephant_guard_deliver_message
 ("elephant_guard_deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L100-L102 ] elephant_guard_troublesome_bandits
 ("elephant_guard_troublesome_bandits", "Hunt down the ravaging bandits", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L104-L106 ] elephant_guard_hunt_down_fugitive
 ("elephant_guard_hunt_down_fugitive", "Hunt down the thief", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L108-L110 ] elephant_guard_train_peasants_against_bandits
 ("elephant_guard_train_peasants_against_bandits", "Train the Elephant Guard fighters", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L112-L114 ] elephant_guard_deliver_grain
 ("elephant_guard_deliver_grain", "Bring {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L116-L118 ] elephant_guard_capture_the_bastard
 ("elephant_guard_capture_the_bastard", "Capture Khergit chieftain", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L120-L123 ] elephant_guard_fight_guild_troops
 ("elephant_guard_fight_guild_troops", "Learn and adapt", qf_random_quest,
  "none"
  ),
# conquistadors_,
# [ src/quests/0002_mercenary_guild_quests.py:L125-L127 ] conquistadors_deliver_message
 ("conquistadors_deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L129-L131 ] conquistadors_collect_debt
 ("conquistadors_collect_debt", "Collect the debt {s3} owes to the Conquistadors", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L133-L135 ] conquistadors_deliver_grain
 ("conquistadors_deliver_grain", "Bring {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L137-L139 ] conquistadors_raise_troops
 ("conquistadors_raise_troops", "Raise {reg1} man", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L141-L143 ] conquistadors_deliver_horses
 ("conquistadors_deliver_horses", "Bring horses", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L145-L147 ] conquistadors_hunt_down_fugitive
 ("conquistadors_hunt_down_fugitive", "Hunt down the thief", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L149-L151 ] conquistadors_troublesome_bandits
 ("conquistadors_troublesome_bandits", "Hunt down a group of rogue mercenaries", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L153-L156 ] conquistadors_fight_guild_troops
 ("conquistadors_fight_guild_troops", "Specialized drills", qf_random_quest,
  "none"
  ),
  #jotnar clan,
# [ src/quests/0002_mercenary_guild_quests.py:L158-L160 ] jotnar_clan_deliver_message
 ("jotnar_clan_deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L162-L164 ] jotnar_clan_competition
 ("jotnar_clan_competition", "Take a part in a daily competition", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L166-L168 ] jotnar_clan_free_clansmen
 ("jotnar_clan_free_clansmen", "Free clansmen captured by the Slavers", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L170-L172 ] jotnar_clan_revenge
  ("jotnar_clan_revenge", "Revenge", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L174-L176 ] jotnar_clan_escort
  ("jotnar_clan_escort", "Escort a Norn Mistress to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L178-L180 ] jotnar_clan_aid_warband
  ("jotnar_clan_aid_warband", "Support the Jotnar Clan warriors in battle near {s8}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L182-L185 ] jotnar_clan_fight_guild_troops
 ("jotnar_clan_fight_guild_troops", "Clashing with clansmen", qf_random_quest,
  "none"
  ),
  #the Balck_Army,
# [ src/quests/0002_mercenary_guild_quests.py:L187-L189 ] black_army_deliver_message
  ("black_army_deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L191-L193 ] black_army_collect_debt
  ("black_army_collect_debt", "Collect the debt {s3} owes to the Black Army", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L195-L197 ] black_army_raise_troops
 ("black_army_raise_troops", "Raise {reg1} man", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L199-L201 ] black_army_escort_merchant_caravan
 ("black_army_escort_merchant_caravan", "Escort caravan to {s8}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L203-L205 ] black_army_aid_warband
 ("black_army_aid_warband", "Help needed at {s8}", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L207-L209 ] black_army_kill_rivals
 ("black_army_kill_rivals", "Get rid of the rivals", qf_random_quest,
  "none"
  ),
# [ src/quests/0002_mercenary_guild_quests.py:L211-L216 ] black_army_fight_guild_troops
 ("black_army_fight_guild_troops", "Siege soldier's course", qf_random_quest,
  "none"
  ),
  
  
# Note : This is defined as the first governer quest in module_constants.py:,

# --- 0003_lord_quests.py ---
# [ src/quests/0003_lord_quests.py:L6-L8 ] deliver_message
 ("deliver_message", "Deliver Message to {s13}", qf_random_quest,
  "{s9} asked you to take a message to {s13}. {s13} was at {s4} when you were given this quest."
  ),
# [ src/quests/0003_lord_quests.py:L10-L12 ] deliver_message_to_enemy_lord
 ("deliver_message_to_enemy_lord", "Deliver Message to {s13}", qf_random_quest,
  "{s9} asked you to take a message to {s13} of {s15}. {s13} was at {s4} when you were given this quest."
  ),
# [ src/quests/0003_lord_quests.py:L14-L16 ] raise_troops
 ("raise_troops", "Raise {reg1} {s14}", qf_random_quest,
  "{s9} asked you to raise {reg1} {s14} and bring them to him."
  ),
# [ src/quests/0003_lord_quests.py:L18-L35 ] escort_lady
 ("escort_lady", "Escort {s13} to {s14}", qf_random_quest,
  "None"
  ),
## ("rescue_lady_under_siege", "Rescue {s3} from {s4}", qf_random_quest,
##  "{s1} asked you to rescue his {s7} {s3} from {s4} and return her back to him."
##  ),
## ("deliver_message_to_lover", "Deliver Message to {s3}", qf_random_quest,
##  "{s1} asked you to take a message to his lover {s3} at {s4}."
##  ),
## ("bring_prisoners_to_enemy", "Bring Prisoners to {s4}", qf_random_quest,
##  "{s1} asked you to bring {reg1} {s3} as prisoners to the guards at {s4}."
##  ),
## ("bring_reinforcements_to_siege", "Bring Reinforcements to the Siege of {s5}", qf_random_quest,
##  "{s1} asked you to bring {reg1} {s3} to {s4} at the siege of {s5}."
##  ),
## ("deliver_supply_to_center_under_siege", "Deliver Supplies to {s5}", qf_random_quest,
##  "TODO: Take {reg1} cartloads of supplies from constable {s3} and deliver them to constable {s4} at {s5}."
##  ),
# [ src/quests/0003_lord_quests.py:L37-L39 ] deal_with_bandits_at_lords_village
 ("deal_with_bandits_at_lords_village", "Save the Village of {s15} from Marauding Bandits", qf_random_quest,
  "{s13} asked you to deal with the bandits who took refuge in his village of {s15} and then report back to him."
  ),
# [ src/quests/0003_lord_quests.py:L41-L43 ] collect_taxes
 ("collect_taxes", "Collect taxes from {s3}", qf_random_quest,
  "{s9} asked you to collect taxes from {s3}. He offered to leave you one-fifth of all the money you collect there."
  ),
# [ src/quests/0003_lord_quests.py:L45-L53 ] hunt_down_fugitive
 ("hunt_down_fugitive", "Hunt down {s4}", qf_random_quest,
  "{s9} asked you to hunt down the fugitive named {s4}. He is currently believed to be at {s3}."
  ),
## ("capture_messenger", "Capture {s3}", qf_random_quest,
##  "{s1} asked you to capture a {s3} and bring him back."
##  ),
## ("bring_back_deserters", "Bring {reg1} {s3}", qf_random_quest,
##  "{s1} asked you to bring {reg1} {s3}."
##  ),
# [ src/quests/0003_lord_quests.py:L55-L57 ] kill_local_merchant
 ("kill_local_merchant", "Assassinate Local Merchant at {s3}", qf_random_quest,
  "{s9} asked you to assassinate a local merchant at {s3}."
  ),
# [ src/quests/0003_lord_quests.py:L59-L61 ] bring_back_runaway_serfs
 ("bring_back_runaway_serfs", "Bring Back Runaway Serfs", qf_random_quest,
  "{s9} asked you to bring back the three groups of runaway serfs back to {s2}. He said all three groups must be running away in the direction of {s3}."
  ),
# [ src/quests/0003_lord_quests.py:L63-L65 ] follow_spy
 ("follow_spy", "Follow the Spy to Meeting", qf_random_quest,
  "{s11} asked you to follow the spy that will leave {s12}. You must be careful not to be seen by the spy during his travel, or else he may get suspicious and turn back. Once the spy meets with his accomplice, you are to ambush and capture them and bring them both back to {s11}."
 ),
# [ src/quests/0003_lord_quests.py:L67-L69 ] capture_enemy_hero
 ("capture_enemy_hero", "Capture a Lord from {s13}", qf_random_quest,
  "{s11} asked you to capture a lord from {s13} and deliver proof that the enemy noble is safely in custody."
  ),
# [ src/quests/0003_lord_quests.py:L71-L73 ] lend_companion
 ("lend_companion", "Lend Your Companion {s3} to {s9}", qf_random_quest,
  "{s9} asked you to lend your companion {s3} to him for a week."
  ),
# [ src/quests/0003_lord_quests.py:L75-L83 ] collect_debt
 ("collect_debt", "Collect the debt {s3} owes to {s9}", qf_random_quest,
  "{s9} asked you to collect the debt of {reg4} denars {s3} owes to him."
  ),
## ("capture_conspirators", "Capture Conspirators", qf_random_quest,
##  "TODO: {s1} asked you to capture all troops in {reg1} conspirator parties that plan to rebel against him and join {s3}."
##  ),
## ("defend_nobles_against_peasants", "Defend Nobles Against Peasants", qf_random_quest,
##  "TODO: {s1} asked you to defend {reg1} noble parties against peasants."
##  ),
# [ src/quests/0003_lord_quests.py:L85-L87 ] incriminate_loyal_commander
 ("incriminate_loyal_commander", "Incriminate the Loyal Commander of {s13}, {s16}", qf_random_quest,
  "None"
  ),
# [ src/quests/0003_lord_quests.py:L89-L91 ] raid_caravan_to_start_war
 ("raid_caravan_to_start_war", "Raid {reg13} Caravans of {s13}", qf_random_quest,
  "None"
  ),
# [ src/quests/0003_lord_quests.py:L93-L95 ] meet_spy_in_enemy_town
 ("meet_spy_in_enemy_town", "Meet Spy in {s13}", qf_random_quest,
  "None"
  ),
# [ src/quests/0003_lord_quests.py:L97-L108 ] capture_prisoners
 ("capture_prisoners", "Bring {reg1} {s3} Prisoners", qf_random_quest,
  "{s9} wanted you to bring him {reg1} {s3} as prisoners."
  ),

## ("hunt_down_raiders", "Hunt Down Raiders",qf_random_quest,
##  "{s1} asked you to hunt down and punish the raiders that attacked a village near {s3} before they reach the safety of their base at {s4}."
##  ),

##################
# Enemy Kingdom Lord quests
##################
# Note : This is defined as the first enemy lord quest in module_constants.py:,

# --- 0004_enemy_lord_quests.py ---
# [ src/quests/0004_enemy_lord_quests.py:L6-L13 ] lend_surgeon
 ("lend_surgeon", "Lend Your Surgeon {s3} to {s1}", qf_random_quest,
  "Lend your experienced surgeon {s3} to {s1}."
  ),

##################
# Kingdom Army quests
##################
# Note : This is defined as lord quests end in module_constants.py:,

# --- 0005_army_quests.py ---
# [ src/quests/0005_army_quests.py:L6-L8 ] follow_army
 ("follow_army", "Follow {s9}'s Army", qf_random_quest,
  "None"
  ),
# [ src/quests/0005_army_quests.py:L10-L13 ] report_to_army
 ("report_to_army", "Report to {s13}, the Marshall", qf_random_quest,
  "None"
  ),
# Note : This is defined as the first army quest in module_constants.py:,
# [ src/quests/0005_army_quests.py:L15-L17 ] deliver_cattle_to_army
 ("deliver_cattle_to_army", "Deliver {reg3} Heads of Cattle to {s13}", qf_random_quest,
  "None"
  ),
# [ src/quests/0005_army_quests.py:L19-L21 ] join_siege_with_army
 ("join_siege_with_army", "Join the Siege of {s14}", qf_random_quest,
  "None"
  ),
# [ src/quests/0005_army_quests.py:L23-L31 ] scout_waypoints
 ("scout_waypoints", "Scout {s13}, {s14} and {s15}", qf_random_quest,
  "None"
  ),


##################
# Kingdom Lady quests
##################
# Note : This is defined as the first kingdom lady quest in module_constants.py:,

# --- 0006_lady_quests.py ---
# [ src/quests/0006_lady_quests.py:L6-L8 ] rescue_lord_by_replace
 ("rescue_lord_by_replace", "Rescue {s13} from {s14}", qf_random_quest,
  "None"
  ),
# [ src/quests/0006_lady_quests.py:L10-L12 ] deliver_message_to_prisoner_lord
 ("deliver_message_to_prisoner_lord", "Deliver Message to {s13} at {s14}", qf_random_quest,
  "None"
  ),
# [ src/quests/0006_lady_quests.py:L14-L21 ] duel_for_lady
  ("duel_for_lady", "Challenge {s13} to a Trial of Arms", qf_random_quest,
  "None"
  ),

##################
# Mayor quests
##################
# Note : This is defined as the first mayor quest in module_constants.py:,

# --- 0007_mayor_quests.py ---
# [ src/quests/0007_mayor_quests.py:L6-L8 ] move_cattle_herd
 ("move_cattle_herd", "Move Cattle Herd to {s13}", qf_random_quest,
  "Guildmaster of {s10} asked you to move a cattle herd to {s13}."
  ),
# [ src/quests/0007_mayor_quests.py:L10-L12 ] escort_merchant_caravan
 ("escort_merchant_caravan", "Escort Merchant Caravan to {s8}", qf_random_quest,
  "Escort the merchant caravan to the town of {s8}."
  ),
# [ src/quests/0007_mayor_quests.py:L14-L16 ] deliver_wine
 ("deliver_wine", "Deliver {reg5} Units of {s6} to {s4}", qf_random_quest,
  "{s9} of {s3} asked you to deliver {reg5} units of {s6} to the tavern in {s4} in 7 days."
  ),
# [ src/quests/0007_mayor_quests.py:L18-L20 ] troublesome_bandits
 ("troublesome_bandits", "Hunt Down Troublesome Bandits", qf_random_quest,
  "{s9} of {s4} asked you to hunt down the troublesome bandits in the vicinity of the town."
  ),
# [ src/quests/0007_mayor_quests.py:L22-L26 ] kidnapped_girl
 ("kidnapped_girl", "Ransom Girl from Bandits", qf_random_quest,
  "Guildmaster of {s4} gave you {reg12} denars to pay the ransom of a girl kidnapped by bandits.\
 You are to meet the bandits near {s3} and pay them the ransom fee.\
 After that you are to bring the girl back to {s4}."
  ),
# [ src/quests/0007_mayor_quests.py:L28-L32 ] persuade_lords_to_make_peace
 ("persuade_lords_to_make_peace", "Make Sure Two Lords Do Not Object to Peace", qf_random_quest,
  "Guildmaster of {s4} promised you {reg12} denars if you can make sure that\
 {s12} and {s13} no longer pose a threat to a peace settlement between {s15} and {s14}.\
 In order to do that, you must either convince them or make sure they fall captive and remain so until a peace agreement is made."
  ),
# [ src/quests/0007_mayor_quests.py:L34-L36 ] deal_with_looters
 ("deal_with_looters", "Deal with Looters", qf_random_quest,
  "The Guildmaster of {s4} has asked you to deal with several bands of looters around {s4}, and bring back any goods you recover."
 ),
# [ src/quests/0007_mayor_quests.py:L38-L45 ] deal_with_night_bandits
 ("deal_with_night_bandits", "Deal with Night Bandits", qf_random_quest,
  "The Guildmaster of {s14} has asked you to patrol the streets after dusk and break the night bandits preying on the town."
  ),

############
# Village Elder quests
############
# Note : This is defined as the first village elder quest in module_constants.py:,

# --- 0008_village_elder_quests.py ---
# [ src/quests/0008_village_elder_quests.py:L6-L8 ] deliver_grain
 ("deliver_grain", "Bring wheat to {s3}", qf_random_quest,
  "The elder of the village of {s3} asked you to bring them {reg5} packs of wheat.."
  ),
# [ src/quests/0008_village_elder_quests.py:L10-L12 ] deliver_cattle
 ("deliver_cattle", "Deliver {reg5} Heads of Cattle to {s3}", qf_random_quest,
  "The elder of the village of {s3} asked you to bring {reg5} heads of cattle."
  ),
# [ src/quests/0008_village_elder_quests.py:L14-L24 ] train_peasants_against_bandits
 ("train_peasants_against_bandits", "Train the Peasants of {s13} Against Bandits.", qf_random_quest,
  "None"
  ), 
# Deliver horses, Deliver food, Escort_Caravan, Hunt bandits, Ransom Merchant.
## ("capture_nobleman", "Capture Nobleman",qf_random_quest,
##  "{s1} wanted you to capture an enemy nobleman on his way from {s3} to {s4}. He said the nobleman would leave {s3} in {reg1} days."
##  ),

# Bandit quests: Capture rich merchant, capture banker, kill manhunters?..

# Note : This is defined as the last village elder quest in module_constants.py:,
# [ src/quests/0008_village_elder_quests.py:L26-L28 ] eliminate_bandits_infesting_village
 ("eliminate_bandits_infesting_village", "Save the Village of {s7} from Marauding Bandits", qf_random_quest,
  "A villager from {s7} begged you to save their village from the bandits that took refuge there."
  ),

# [ src/quests/0009_story_and_meta_quests.py ]

 *quest_chain_from_specs(
  "story_and_meta_quests",
  "Story and Meta Quests",
  quests=(
   quest_template_spec(
    "regional_threat_contract",
    "Regional Threat Contract",
    qf_random_quest,
    "You accepted a regional threat-board contract. Track down the marked warband, defeat it, and return to any threat board to claim the posted reward.",
    stages=(
     quest_stage_spec(
      "stage_1",
      "Hunt the Threat",
      "Find and defeat the marked warband.",
      description="Pursue the target and clear the contract objective.",
      conditions=(
       "contract accepted",
       "warband tracked",
      ),
      actions=(
       "travel to marked target",
       "defeat warband",
       "return to threat board",
      ),
      rewards=(
       "posted reward",
      ),
      metadata={
       "phase": "hunt",
       "tracking": "contract",
      },
     ),
    ),
    metadata={
     "category": "story",
     "authoring": "schema",
    },
   ),
   quest_template_spec(
    "join_faction",
    "Give Oath of Homage to {s1}",
    qf_random_quest,
    "Find {s1} and give him your oath of homage.",
    metadata={
     "category": "story",
     "authoring": "schema",
    },
   ),
   quest_template_spec(
    "rebel_against_kingdom",
    "Help {s13} Claim the Throne of {s14}",
    qf_random_quest,
    "None",
    metadata={
     "category": "story",
     "authoring": "schema",
    },
   ),
   quest_template_spec(
    "quests_end",
    "Quests End",
    0,
    ".",
    metadata={
     "category": "meta",
     "authoring": "schema",
     "sentinel": True,
    },
   ),
  ),
 ).as_legacy_tuples(),

# [ src/quests/0010_sample_campaign_quests.py ]

 *quest_chain_from_specs(
  "sample_campaign_quests",
  "Sample Campaign Quests",
  quests=(
   quest_template_spec(
    "sample_campaign_briefing",
    "Brief the Gate Captain",
    qf_random_quest,
    "The gate captain needs a reliable runner. Hear the problem, accept or decline the job, and prepare the patrol if you take it.",
    stage_title="Choose Your Contract",
    stage_objective="Meet the captain and decide whether to accept the campaign.",
    stage_id="sample_campaign_briefing_stage",
    stage_description="This opening stage exercises the dialogue-driven quest path and the accept / decline choice flow.",
    conditions=(
     quest_condition(
      "sample_campaign_contract_condition",
      "contract accepted",
      description="The player has accepted the sample contract.",
      metadata={
       "category": "sample",
       "kind": "condition",
      },
     ),
     "player near gate",
    ),
    actions=(
     quest_action(
      "sample_campaign_assembly_action",
      "assemble patrol",
      description="Bring the patrol together and prepare the route.",
      metadata={
       "category": "sample",
       "kind": "action",
      },
     ),
     "record the player choice",
     "open the patrol quest",
    ),
    triggers=(
     quest_trigger(
      "sample_campaign_contract_trigger",
      "conversation started",
      conditions=(
       quest_condition(
        "sample_campaign_contract_condition",
        "contract accepted",
        description="The player has accepted the sample contract.",
        metadata={
         "category": "sample",
         "kind": "condition",
        },
       ),
      ),
      actions=(
       quest_action(
        "sample_campaign_assembly_action",
        "assemble patrol",
        description="Bring the patrol together and prepare the route.",
        metadata={
         "category": "sample",
         "kind": "action",
        },
       ),
      ),
      description="Marks the quest-giver conversation path for the sample contract.",
      metadata={
       "category": "sample",
       "kind": "trigger",
      },
     ),
     quest_trigger(
      "sample_campaign_contract_end_trigger",
      "conversation ended",
      conditions=(
       quest_condition(
        "sample_campaign_contract_condition",
        "contract accepted",
        description="The player has accepted the sample contract.",
        metadata={
         "category": "sample",
         "kind": "condition",
        },
       ),
      ),
      actions=(
       quest_action(
        "sample_campaign_return_action",
        "deliver report",
        description="Return the report to the captain and close out the campaign.",
        metadata={
         "category": "sample",
         "kind": "action",
        },
       ),
      ),
      description="Marks the end of the sample contract conversation path.",
      metadata={
       "category": "sample",
       "kind": "trigger",
      },
     ),
    ),
    rewards=(
     quest_reward(
      "sample_campaign_route_reward",
      "patrol formed",
      description="The patrol has been assembled and is ready to move.",
      metadata={
       "category": "sample",
       "kind": "reward",
      },
     ),
    ),
    failures=(
     quest_failure(
      "sample_campaign_route_failure",
      "patrol delayed",
      description="The patrol could not be assembled in time.",
      metadata={
       "category": "sample",
       "kind": "failure",
      },
     ),
     "job declined",
    ),
    transitions={
     "accepted": "sample_campaign_patrol",
     "declined": "sample_campaign_debrief",
    },
    metadata={
     "category": "sample",
     "framework": "dialogue",
     "choice_flow": "accept_decline",
     "offer_preview": quest_offer(
      "sample_campaign_briefing_offer",
      quest_id="sample_campaign_briefing",
      giver_id="trp_gate_captain",
      title="Brief the Gate Captain",
      summary="A sample offer that opens the contract and demonstrates the offer helper.",
      conditions=(
       quest_condition(
        "sample_campaign_contract_condition",
        "contract accepted",
        description="The player has accepted the sample contract.",
        metadata={
         "category": "sample",
         "kind": "condition",
        },
       ),
      ),
      actions=(
       quest_action(
        "sample_campaign_assembly_action",
        "assemble patrol",
        description="Bring the patrol together and prepare the route.",
        metadata={
         "category": "sample",
         "kind": "action",
        },
       ),
      ),
      triggers=(
       quest_trigger(
        "sample_campaign_contract_trigger",
        "conversation started",
        conditions=(),
        actions=(),
        description="Marks the quest-giver conversation path for the sample contract.",
        metadata={
         "category": "sample",
         "kind": "trigger",
        },
       ),
      ),
      rewards=(),
      failures=(),
      npc_state=quest_npc_state(
       "trp_gate_captain",
       state="available",
       dialogue_state="briefing",
       available_quests=("sample_campaign_briefing",),
       completed_quests=(),
       failed_quests=(),
       locked_chains=("sample_campaign_quests",),
       cooldown_days=0,
       faction_alignment="neutral",
       personality="pragmatic",
       special_flags={
        "sample": True,
        "framework": "npc_state",
       },
       metadata={
        "category": "sample",
        "kind": "npc_state",
       },
      ),
      world_context=quest_world_context(
       "sample_campaign_gate_context",
       location_id="town_gate",
       center_id="sample_town",
       party_id="sample_patrol_party",
       faction_id="sample_faction",
       region="roadside",
       day=12,
       turn=3,
       metadata={
        "category": "sample",
        "kind": "world_context",
       },
      ),
      expires_in_days=3,
      transitions={
       "accepted": "sample_campaign_briefing",
       "declined": "sample_campaign_debrief",
      },
      metadata={
       "category": "sample",
       "kind": "offer",
      },
     ).to_snapshot(),
     "helper_library": {
      "direct_template": quest_template(
       "sample_campaign_direct_template",
       "Ledger the Watch",
       qf_random_quest,
       "A direct template that exercises the raw quest_template helper.",
       stages=(
        quest_stage(
         "sample_campaign_direct_stage",
         "Keep the Watch",
         "Hold the line until the road is secure.",
         description="This stage uses the raw quest_template and quest_stage helpers.",
         conditions=(
          quest_condition(
           "sample_campaign_contract_condition",
           "contract accepted",
           description="The player has accepted the sample contract.",
           metadata={
            "category": "sample",
            "kind": "condition",
           },
          ),
          quest_condition(
           "sample_campaign_route_condition",
           "route known",
           description="The patrol route has been identified.",
           metadata={
            "category": "sample",
            "kind": "condition",
           },
          ),
         ),
         actions=(
          quest_action(
           "sample_campaign_assembly_action",
           "assemble patrol",
           description="Bring the patrol together and prepare the route.",
           metadata={
            "category": "sample",
            "kind": "action",
           },
          ),
         ),
         battle_hooks=("sample_direct_battle_hook",),
         triggers=(
          quest_trigger(
           "sample_campaign_contract_trigger",
           "conversation started",
           conditions=(),
           actions=(),
           description="Marks the quest-giver conversation path for the sample contract.",
           metadata={
            "category": "sample",
            "kind": "trigger",
           },
          ),
          quest_trigger(
           "sample_campaign_contract_end_trigger",
           "conversation ended",
           conditions=(),
           actions=(),
           description="Marks the end of the sample contract conversation path.",
           metadata={
            "category": "sample",
            "kind": "trigger",
           },
          ),
         ),
         rewards=(
          quest_reward(
           "sample_campaign_route_reward",
           "patrol formed",
           description="The patrol has been assembled and is ready to move.",
           metadata={
            "category": "sample",
            "kind": "reward",
           },
          ),
         ),
         failures=(
          quest_failure(
           "sample_campaign_route_failure",
           "patrol delayed",
           description="The patrol could not be assembled in time.",
           metadata={
            "category": "sample",
            "kind": "failure",
           },
          ),
         ),
         battle_objective=quest_battle_objective(
          "sample_campaign_tower_objective",
          "hold_position",
          target_party_id="sample_raider_party",
          required_count=1,
          progress=0,
          wave_index=1,
          failure_state="tower_lost",
          required_payload_keys=("road", "route"),
          success_message="The watchtower is secure.",
          failure_message="The tower fell before the patrol could regroup.",
          metadata={
           "category": "sample",
           "kind": "battle_objective",
          },
         ),
         metadata={
          "category": "sample",
          "kind": "direct_template",
         },
        ),
       ),
       conditions=(
        quest_condition(
         "sample_campaign_contract_condition",
         "contract accepted",
         description="The player has accepted the sample contract.",
         metadata={
          "category": "sample",
          "kind": "condition",
         },
        ),
       ),
       actions=(
        quest_action(
         "sample_campaign_assembly_action",
         "assemble patrol",
         description="Bring the patrol together and prepare the route.",
         metadata={
          "category": "sample",
          "kind": "action",
         },
        ),
       ),
       triggers=(
        quest_trigger(
         "sample_campaign_contract_trigger",
         "conversation started",
         conditions=(),
         actions=(),
         description="Marks the quest-giver conversation path for the sample contract.",
         metadata={
          "category": "sample",
          "kind": "trigger",
         },
        ),
       ),
       rewards=(
        quest_reward(
         "sample_campaign_route_reward",
         "patrol formed",
         description="The patrol has been assembled and is ready to move.",
         metadata={
          "category": "sample",
          "kind": "reward",
         },
        ),
       ),
       failures=(
        quest_failure(
         "sample_campaign_route_failure",
         "patrol delayed",
         description="The patrol could not be assembled in time.",
         metadata={
          "category": "sample",
          "kind": "failure",
         },
        ),
       ),
       npc_state=quest_npc_state(
        "trp_gate_captain",
        state="available",
        dialogue_state="briefing",
        available_quests=("sample_campaign_briefing",),
        completed_quests=(),
        failed_quests=(),
        locked_chains=("sample_campaign_quests",),
        cooldown_days=0,
        faction_alignment="neutral",
        personality="pragmatic",
        special_flags={
         "sample": True,
         "framework": "npc_state",
        },
        metadata={
         "category": "sample",
         "kind": "npc_state",
        },
       ),
       world_context=quest_world_context(
        "sample_campaign_gate_context",
        location_id="town_gate",
        center_id="sample_town",
        party_id="sample_patrol_party",
        faction_id="sample_faction",
        region="roadside",
        day=12,
        turn=3,
        metadata={
         "category": "sample",
         "kind": "world_context",
        },
       ),
       metadata={
        "category": "sample",
        "framework": "direct_template",
       },
      ).to_snapshot(),
      "blueprint": quest_blueprint(
       "sample_campaign_blueprint",
       "Blueprint the Tower",
       qf_random_quest,
       "A direct blueprint that exercises the quest_blueprint alias.",
       stages=(
        quest_stage(
         "sample_campaign_blueprint_stage",
         "Secure the Tower",
         "Use the tower vantage point to hold off attackers until the road is clear.",
         description="This stage exercises quest_blueprint, quest_stage, and the battle objective helper.",
         conditions=(
          quest_condition(
           "sample_campaign_combat_condition",
           "ambush spotted",
           description="The patrol has spotted the ambush site.",
           metadata={
            "category": "sample",
            "kind": "condition",
           },
          ),
         ),
         actions=(
          quest_action(
           "sample_campaign_combat_action",
           "engage raiders",
           description="Fight through the ambush and secure the road.",
           metadata={
            "category": "sample",
            "kind": "action",
           },
          ),
         ),
         battle_hooks=("sample_blueprint_battle_hook",),
         triggers=(
          quest_trigger(
           "sample_campaign_combat_trigger",
           "battle started",
           conditions=(),
           actions=(),
           description="Tracks the combat-facing patrol ambush phase.",
           metadata={
            "category": "sample",
            "kind": "trigger",
           },
          ),
          quest_trigger(
           "sample_campaign_end_trigger",
           "battle ended",
           conditions=(),
           actions=(),
           description="Tracks the campaign wrap-up path.",
           metadata={
            "category": "sample",
            "kind": "trigger",
           },
          ),
         ),
         rewards=(
          quest_reward(
           "sample_campaign_combat_reward",
           "road secured",
           description="The road is safe again after the ambush is cleared.",
           metadata={
            "category": "sample",
            "kind": "reward",
           },
          ),
         ),
         failures=(
          quest_failure(
           "sample_campaign_combat_failure",
           "patrol scattered",
           description="The ambush broke the patrol and forced a fallback.",
           metadata={
            "category": "sample",
            "kind": "failure",
           },
          ),
         ),
         battle_objective=quest_battle_objective(
          "sample_campaign_tower_objective",
          "hold_position",
          target_party_id="sample_raider_party",
          required_count=1,
          progress=0,
          wave_index=1,
          failure_state="tower_lost",
          required_payload_keys=("road", "route"),
          success_message="The watchtower is secure.",
          failure_message="The tower fell before the patrol could regroup.",
          metadata={
           "category": "sample",
           "kind": "battle_objective",
          },
         ),
         metadata={
          "category": "sample",
          "kind": "blueprint",
         },
        ),
       ),
       conditions=(
        quest_condition(
         "sample_campaign_combat_condition",
         "ambush spotted",
         description="The patrol has spotted the ambush site.",
         metadata={
          "category": "sample",
          "kind": "condition",
         },
        ),
       ),
       actions=(
        quest_action(
         "sample_campaign_combat_action",
         "engage raiders",
         description="Fight through the ambush and secure the road.",
         metadata={
          "category": "sample",
          "kind": "action",
         },
        ),
       ),
       triggers=(
        quest_trigger(
         "sample_campaign_combat_trigger",
         "battle started",
         conditions=(),
         actions=(),
         description="Tracks the combat-facing patrol ambush phase.",
         metadata={
          "category": "sample",
          "kind": "trigger",
         },
        ),
       ),
       rewards=(
        quest_reward(
         "sample_campaign_combat_reward",
         "road secured",
         description="The road is safe again after the ambush is cleared.",
         metadata={
          "category": "sample",
          "kind": "reward",
         },
        ),
       ),
       failures=(
        quest_failure(
         "sample_campaign_combat_failure",
         "patrol scattered",
         description="The ambush broke the patrol and forced a fallback.",
         metadata={
          "category": "sample",
          "kind": "failure",
         },
        ),
       ),
       npc_state=quest_npc_state(
        "trp_gate_captain",
        state="available",
        dialogue_state="briefing",
        available_quests=("sample_campaign_briefing",),
        completed_quests=(),
        failed_quests=(),
        locked_chains=("sample_campaign_quests",),
        cooldown_days=0,
        faction_alignment="neutral",
        personality="pragmatic",
        special_flags={
         "sample": True,
         "framework": "npc_state",
        },
        metadata={
         "category": "sample",
         "kind": "npc_state",
        },
       ),
       world_context=quest_world_context(
        "sample_campaign_gate_context",
        location_id="town_gate",
        center_id="sample_town",
        party_id="sample_patrol_party",
        faction_id="sample_faction",
        region="roadside",
        day=12,
        turn=3,
        metadata={
         "category": "sample",
         "kind": "world_context",
        },
       ),
       metadata={
        "category": "sample",
        "kind": "blueprint",
       },
      ).to_snapshot(),
      "delivery": quest_delivery_quest(
       "sample_campaign_delivery",
       "Carry the Supply Crates",
       qf_random_quest,
       "Carry crates to the patrol camp and demonstrate the delivery helper.",
       item_name="supply crates",
       destination="the patrol camp",
       stage_title="Deliver the Crates",
       stage_id="sample_campaign_delivery_stage",
       conditions=(
        quest_condition(
         "sample_campaign_contract_condition",
         "contract accepted",
         description="The player has accepted the sample contract.",
         metadata={
          "category": "sample",
          "kind": "condition",
         },
        ),
       ),
       actions=(
        quest_action(
         "sample_campaign_assembly_action",
         "assemble patrol",
         description="Bring the patrol together and prepare the route.",
         metadata={
          "category": "sample",
          "kind": "action",
         },
        ),
       ),
       triggers=(
        quest_trigger(
         "sample_campaign_contract_trigger",
         "conversation started",
         conditions=(),
         actions=(),
         description="Marks the quest-giver conversation path for the sample contract.",
         metadata={
          "category": "sample",
          "kind": "trigger",
         },
        ),
       ),
       rewards=(
        quest_reward(
         "sample_campaign_route_reward",
         "patrol formed",
         description="The patrol has been assembled and is ready to move.",
         metadata={
          "category": "sample",
          "kind": "reward",
         },
        ),
       ),
       failures=(
        quest_failure(
         "sample_campaign_route_failure",
         "patrol delayed",
         description="The patrol could not be assembled in time.",
         metadata={
          "category": "sample",
          "kind": "failure",
         },
        ),
       ),
       quest_metadata={
        "category": "sample",
        "kind": "delivery",
       },
       stage_metadata={
        "category": "sample",
        "kind": "delivery_stage",
       },
       npc_state=quest_npc_state(
        "trp_gate_captain",
        state="available",
        dialogue_state="briefing",
        available_quests=("sample_campaign_briefing",),
        completed_quests=(),
        failed_quests=(),
        locked_chains=("sample_campaign_quests",),
        cooldown_days=0,
        faction_alignment="neutral",
        personality="pragmatic",
        special_flags={
         "sample": True,
         "framework": "npc_state",
        },
        metadata={
         "category": "sample",
         "kind": "npc_state",
        },
       ),
       world_context=quest_world_context(
        "sample_campaign_gate_context",
        location_id="town_gate",
        center_id="sample_town",
        party_id="sample_patrol_party",
        faction_id="sample_faction",
        region="roadside",
        day=12,
        turn=3,
        metadata={
         "category": "sample",
         "kind": "world_context",
        },
       ),
      ).to_snapshot(),
      "hunt": quest_hunt_quest(
       "sample_campaign_hunt",
       "Hunt the Raiders",
       qf_random_quest,
       "Track the raiders down and defeat them to demonstrate the hunt helper.",
       target_name="the raiders",
       stage_title="Hunt the Raiders",
       stage_id="sample_campaign_hunt_stage",
       conditions=(
        quest_condition(
         "sample_campaign_contract_condition",
         "contract accepted",
         description="The player has accepted the sample contract.",
         metadata={
          "category": "sample",
          "kind": "condition",
         },
        ),
       ),
       actions=(
        quest_action(
         "sample_campaign_combat_action",
         "engage raiders",
         description="Fight through the ambush and secure the road.",
         metadata={
          "category": "sample",
          "kind": "action",
         },
        ),
       ),
       triggers=(
        quest_trigger(
         "sample_campaign_combat_trigger",
         "battle started",
         conditions=(),
         actions=(),
         description="Tracks the combat-facing patrol ambush phase.",
         metadata={
          "category": "sample",
          "kind": "trigger",
         },
        ),
       ),
       rewards=(
        quest_reward(
         "sample_campaign_combat_reward",
         "road secured",
         description="The road is safe again after the ambush is cleared.",
         metadata={
          "category": "sample",
          "kind": "reward",
         },
        ),
       ),
       failures=(
        quest_failure(
         "sample_campaign_combat_failure",
         "patrol scattered",
         description="The ambush broke the patrol and forced a fallback.",
         metadata={
          "category": "sample",
          "kind": "failure",
         },
        ),
       ),
       quest_metadata={
        "category": "sample",
        "kind": "hunt",
       },
       stage_metadata={
        "category": "sample",
        "kind": "hunt_stage",
       },
       npc_state=quest_npc_state(
        "trp_gate_captain",
        state="available",
        dialogue_state="briefing",
        available_quests=("sample_campaign_briefing",),
        completed_quests=(),
        failed_quests=(),
        locked_chains=("sample_campaign_quests",),
        cooldown_days=0,
        faction_alignment="neutral",
        personality="pragmatic",
        special_flags={
         "sample": True,
         "framework": "npc_state",
        },
        metadata={
         "category": "sample",
         "kind": "npc_state",
        },
       ),
       world_context=quest_world_context(
        "sample_campaign_gate_context",
        location_id="town_gate",
        center_id="sample_town",
        party_id="sample_patrol_party",
        faction_id="sample_faction",
        region="roadside",
        day=12,
        turn=3,
        metadata={
         "category": "sample",
         "kind": "world_context",
        },
       ),
      ).to_snapshot(),
      "escort": quest_escort_quest(
       "sample_campaign_escort",
       "Escort the Captain",
       qf_random_quest,
       "Escort the captain to the next watch post to demonstrate the escort helper.",
       person_name="the captain",
       stage_title="Escort the Captain",
       stage_id="sample_campaign_escort_stage",
       conditions=(
        quest_condition(
         "sample_campaign_contract_condition",
         "contract accepted",
         description="The player has accepted the sample contract.",
         metadata={
          "category": "sample",
          "kind": "condition",
         },
        ),
       ),
       actions=(
        quest_action(
         "sample_campaign_assembly_action",
         "assemble patrol",
         description="Bring the patrol together and prepare the route.",
         metadata={
          "category": "sample",
          "kind": "action",
         },
        ),
       ),
       triggers=(
        quest_trigger(
         "sample_campaign_contract_end_trigger",
         "conversation ended",
         conditions=(),
         actions=(),
         description="Marks the end of the sample contract conversation path.",
         metadata={
          "category": "sample",
          "kind": "trigger",
         },
        ),
       ),
       rewards=(
        quest_reward(
         "sample_campaign_route_reward",
         "patrol formed",
         description="The patrol has been assembled and is ready to move.",
         metadata={
          "category": "sample",
          "kind": "reward",
         },
        ),
       ),
       failures=(
        quest_failure(
         "sample_campaign_route_failure",
         "patrol delayed",
         description="The patrol could not be assembled in time.",
         metadata={
          "category": "sample",
          "kind": "failure",
         },
        ),
       ),
       quest_metadata={
        "category": "sample",
        "kind": "escort",
       },
       stage_metadata={
        "category": "sample",
        "kind": "escort_stage",
       },
       npc_state=quest_npc_state(
        "trp_gate_captain",
        state="available",
        dialogue_state="briefing",
        available_quests=("sample_campaign_briefing",),
        completed_quests=(),
        failed_quests=(),
        locked_chains=("sample_campaign_quests",),
        cooldown_days=0,
        faction_alignment="neutral",
        personality="pragmatic",
        special_flags={
         "sample": True,
         "framework": "npc_state",
        },
        metadata={
         "category": "sample",
         "kind": "npc_state",
        },
       ),
       world_context=quest_world_context(
        "sample_campaign_gate_context",
        location_id="town_gate",
        center_id="sample_town",
        party_id="sample_patrol_party",
        faction_id="sample_faction",
        region="roadside",
        day=12,
        turn=3,
        metadata={
         "category": "sample",
         "kind": "world_context",
        },
       ),
      ).to_snapshot(),
      "rescue": quest_rescue_quest(
       "sample_campaign_rescue",
       "Rescue the Scout",
       qf_random_quest,
       "Free the captured scout and demonstrate the rescue helper.",
       person_name="the scout",
       stage_title="Rescue the Scout",
       stage_id="sample_campaign_rescue_stage",
       conditions=(
        quest_condition(
         "sample_campaign_combat_condition",
         "ambush spotted",
         description="The patrol has spotted the ambush site.",
         metadata={
          "category": "sample",
          "kind": "condition",
         },
        ),
       ),
       actions=(
        quest_action(
         "sample_campaign_combat_action",
         "engage raiders",
         description="Fight through the ambush and secure the road.",
         metadata={
          "category": "sample",
          "kind": "action",
         },
        ),
       ),
       triggers=(
        quest_trigger(
         "sample_campaign_end_trigger",
         "battle ended",
         conditions=(),
         actions=(),
         description="Tracks the campaign wrap-up path.",
         metadata={
          "category": "sample",
          "kind": "trigger",
         },
        ),
       ),
       rewards=(
        quest_reward(
         "sample_campaign_combat_reward",
         "road secured",
         description="The road is safe again after the ambush is cleared.",
         metadata={
          "category": "sample",
          "kind": "reward",
         },
        ),
       ),
       failures=(
        quest_failure(
         "sample_campaign_combat_failure",
         "patrol scattered",
         description="The ambush broke the patrol and forced a fallback.",
         metadata={
          "category": "sample",
          "kind": "failure",
         },
        ),
       ),
       quest_metadata={
        "category": "sample",
        "kind": "rescue",
       },
       stage_metadata={
        "category": "sample",
        "kind": "rescue_stage",
       },
       npc_state=quest_npc_state(
        "trp_gate_captain",
        state="available",
        dialogue_state="briefing",
        available_quests=("sample_campaign_briefing",),
        completed_quests=(),
        failed_quests=(),
        locked_chains=("sample_campaign_quests",),
        cooldown_days=0,
        faction_alignment="neutral",
        personality="pragmatic",
        special_flags={
         "sample": True,
         "framework": "npc_state",
        },
        metadata={
         "category": "sample",
         "kind": "npc_state",
        },
       ),
       world_context=quest_world_context(
        "sample_campaign_gate_context",
        location_id="town_gate",
        center_id="sample_town",
        party_id="sample_patrol_party",
        faction_id="sample_faction",
        region="roadside",
        day=12,
        turn=3,
        metadata={
         "category": "sample",
         "kind": "world_context",
        },
       ),
      ).to_snapshot(),
      "single_stage": quest_template(
       "sample_campaign_single_stage",
       "Single Stage Showcase",
       qf_random_quest,
       "A direct template variant that shows the single-stage quest path.",
       stages=(
        quest_stage(
         "sample_campaign_single_stage_entry",
         "Showcase the Contract",
         "Demonstrate the framework in a compact single-stage setup.",
         description="This keeps the single-stage path visible for the generated module.",
         conditions=(
          quest_condition(
           "sample_campaign_contract_condition",
           "contract accepted",
           description="The player has accepted the sample contract.",
           metadata={
            "category": "sample",
            "kind": "condition",
           },
          ),
        ),
         actions=(
          quest_action(
           "sample_campaign_return_action",
           "deliver report",
           description="Return the report to the captain and close out the campaign.",
           metadata={
            "category": "sample",
            "kind": "action",
           },
          ),
        ),
         battle_hooks=("sample_single_stage_hook",),
         triggers=(
          quest_trigger(
           "sample_campaign_contract_end_trigger",
           "conversation ended",
           conditions=(),
           actions=(),
           description="Marks the end of the sample contract conversation path.",
           metadata={
            "category": "sample",
            "kind": "trigger",
           },
          ),
         ),
         rewards=(
          quest_reward(
           "sample_campaign_wrap_reward",
           "campaign complete",
           description="The sample campaign has reached a successful conclusion.",
           metadata={
            "category": "sample",
            "kind": "reward",
           },
          ),
         ),
         failures=(
          quest_failure(
           "sample_campaign_wrap_failure",
           "report lost",
           description="The final report was lost before the captain could review it.",
           metadata={
            "category": "sample",
            "kind": "failure",
           },
          ),
         ),
         battle_objective=quest_battle_objective(
          "sample_campaign_tower_objective",
          "hold_position",
          target_party_id="sample_raider_party",
          required_count=1,
          progress=0,
          wave_index=1,
          failure_state="tower_lost",
          required_payload_keys=("road", "route"),
          success_message="The watchtower is secure.",
          failure_message="The tower fell before the patrol could regroup.",
          metadata={
           "category": "sample",
           "kind": "battle_objective",
          },
         ),
         metadata={
          "category": "sample",
          "kind": "single_stage",
         },
        ),
       ),
       conditions=(
        quest_condition(
         "sample_campaign_contract_condition",
         "contract accepted",
         description="The player has accepted the sample contract.",
         metadata={
          "category": "sample",
          "kind": "condition",
         },
        ),
       ),
       actions=(
        quest_action(
         "sample_campaign_return_action",
         "deliver report",
         description="Return the report to the captain and close out the campaign.",
         metadata={
          "category": "sample",
          "kind": "action",
         },
        ),
       ),
       triggers=(
        quest_trigger(
         "sample_campaign_contract_end_trigger",
         "conversation ended",
         conditions=(),
         actions=(),
         description="Marks the end of the sample contract conversation path.",
         metadata={
          "category": "sample",
          "kind": "trigger",
         },
        ),
       ),
       rewards=(
        quest_reward(
         "sample_campaign_wrap_reward",
         "campaign complete",
         description="The sample campaign has reached a successful conclusion.",
         metadata={
          "category": "sample",
          "kind": "reward",
         },
        ),
       ),
       failures=(
        quest_failure(
         "sample_campaign_wrap_failure",
         "report lost",
         description="The final report was lost before the captain could review it.",
         metadata={
          "category": "sample",
          "kind": "failure",
         },
        ),
       ),
       npc_state=quest_npc_state(
        "trp_gate_captain",
        state="available",
        dialogue_state="briefing",
        available_quests=("sample_campaign_briefing",),
        completed_quests=(),
        failed_quests=(),
        locked_chains=("sample_campaign_quests",),
        cooldown_days=0,
        faction_alignment="neutral",
        personality="pragmatic",
        special_flags={
         "sample": True,
         "framework": "npc_state",
        },
        metadata={
         "category": "sample",
         "kind": "npc_state",
        },
       ),
       world_context=quest_world_context(
        "sample_campaign_gate_context",
        location_id="town_gate",
        center_id="sample_town",
        party_id="sample_patrol_party",
        faction_id="sample_faction",
        region="roadside",
        day=12,
        turn=3,
        metadata={
         "category": "sample",
         "kind": "world_context",
        },
       ),
       metadata={
        "category": "sample",
        "framework": "single_stage",
       },
      ).to_snapshot(),
     },
     "battle_objective_preview": quest_battle_objective(
      "sample_campaign_tower_objective",
      "hold_position",
      target_party_id="sample_raider_party",
      required_count=1,
      progress=0,
      wave_index=1,
      failure_state="tower_lost",
      required_payload_keys=("road", "route"),
      success_message="The watchtower is secure.",
      failure_message="The tower fell before the patrol could regroup.",
      metadata={
       "category": "sample",
       "kind": "battle_objective",
      },
     ).to_snapshot(),
     "npc_state_preview": quest_npc_state(
      "trp_gate_captain",
      state="available",
      dialogue_state="briefing",
      available_quests=("sample_campaign_briefing",),
      completed_quests=(),
      failed_quests=(),
      locked_chains=("sample_campaign_quests",),
      cooldown_days=0,
      faction_alignment="neutral",
      personality="pragmatic",
      special_flags={
       "sample": True,
       "framework": "npc_state",
      },
      metadata={
       "category": "sample",
       "kind": "npc_state",
      },
     ).to_snapshot(),
     "world_context_preview": quest_world_context(
      "sample_campaign_gate_context",
      location_id="town_gate",
      center_id="sample_town",
      party_id="sample_patrol_party",
      faction_id="sample_faction",
      region="roadside",
      day=12,
      turn=3,
      metadata={
       "category": "sample",
       "kind": "world_context",
      },
     ).to_snapshot(),
    },
    stage_metadata={
     "tone": "introductory",
     "sample": True,
    },
   ),
   quest_template_spec(
    "sample_campaign_patrol",
    "Road Patrol",
    qf_random_quest,
    "Escort the patrol, secure the road, and handle the ambush that tests the combat layer.",
    stages=(
     {
      "key": "patrol_assembly",
      "title": "Assemble the Patrol",
      "objective": "Ready the patrol at the gate and brief the squad.",
      "description": "The first patrol stage uses mapping-based authoring to exercise the stage mapping helpers.",
      "conditions": (
       quest_condition(
        "sample_campaign_route_condition",
        "route known",
        description="The patrol route has been identified.",
        metadata={
         "category": "sample",
         "kind": "condition",
        },
       ),
       "squad ready",
      ),
      "actions": (
       quest_action(
        "sample_campaign_assembly_action",
        "assemble patrol",
        description="Bring the patrol together and prepare the route.",
        metadata={
         "category": "sample",
         "kind": "action",
        },
       ),
       "inspect the route",
      ),
      "triggers": (
       quest_trigger(
        "sample_campaign_patrol_trigger",
        "party assembled",
        conditions=(),
        actions=(),
        description="Tracks the patrol assembly phase.",
        metadata={
         "category": "sample",
         "kind": "trigger",
        },
       ),
      ),
      "rewards": (
       quest_reward(
        "sample_campaign_route_reward",
        "patrol formed",
        description="The patrol has been assembled and is ready to move.",
        metadata={
         "category": "sample",
         "kind": "reward",
        },
       ),
      ),
      "failures": (
       quest_failure(
        "sample_campaign_route_failure",
        "patrol delayed",
        description="The patrol could not be assembled in time.",
        metadata={
         "category": "sample",
         "kind": "failure",
        },
       ),
       "patrol delayed",
      ),
      "transitions": {
       "advance": "patrol_ambush",
      },
      "metadata": {
       "phase": "assembly",
       "source": "mapping",
      },
     },
     quest_stage_spec(
      "patrol_ambush",
      "Break the Ambush",
      "Defeat the raiders on the road and keep the patrol intact.",
      description="The second stage exercises the direct stage helper and the combat-facing narrative layer.",
      conditions=(
       quest_condition(
        "sample_campaign_combat_condition",
        "ambush spotted",
        description="The patrol has spotted the ambush site.",
        metadata={
         "category": "sample",
         "kind": "condition",
        },
       ),
      ),
      actions=(
       quest_action(
        "sample_campaign_combat_action",
        "engage raiders",
        description="Fight through the ambush and secure the road.",
        metadata={
         "category": "sample",
         "kind": "action",
        },
       ),
       "secure the road",
       "return to the captain",
      ),
      battle_hooks=("sample_patrol_battle_hook",),
      triggers=(
       quest_trigger(
        "sample_campaign_combat_trigger",
        "battle started",
        conditions=(),
        actions=(),
        description="Tracks the combat-facing patrol ambush phase.",
        metadata={
         "category": "sample",
         "kind": "trigger",
        },
       ),
       quest_trigger(
        "sample_campaign_end_trigger",
        "battle ended",
        conditions=(),
        actions=(),
        description="Tracks the campaign wrap-up path.",
        metadata={
         "category": "sample",
         "kind": "trigger",
        },
       ),
      ),
      rewards=(
       quest_reward(
        "sample_campaign_combat_reward",
        "road secured",
        description="The road is safe again after the ambush is cleared.",
        metadata={
         "category": "sample",
         "kind": "reward",
        },
       ),
       quest_reward(
        "sample_campaign_wrap_reward",
        "campaign complete",
        description="The sample campaign has reached a successful conclusion.",
        metadata={
         "category": "sample",
         "kind": "reward",
        },
       ),
      ),
      failures=(
       quest_failure(
        "sample_campaign_combat_failure",
        "patrol scattered",
        description="The ambush broke the patrol and forced a fallback.",
        metadata={
         "category": "sample",
         "kind": "failure",
        },
       ),
      ),
      transitions={
       "success": "sample_campaign_debrief",
      },
      metadata={
       "phase": "combat",
       "source": "direct",
      },
     ),
    ),
    metadata={
     "category": "sample",
     "framework": "combat",
     "choice_flow": "battle_resolution",
    },
   ),
   quest_template_spec(
    "sample_campaign_debrief",
    "Return the Report",
    qf_random_quest,
    "Bring the report back, resolve the outcome, and collect the final reward or consequence.",
    stage_title="Campaign Debrief",
    stage_objective="Return to the captain and close out the sample campaign.",
    stage_id="sample_campaign_debrief_stage",
    stage_description="This closing stage wraps the sample campaign and demonstrates the single-stage helper fields again.",
    conditions=(
     quest_condition(
      "sample_campaign_contract_condition",
      "contract accepted",
      description="The player has accepted the sample contract.",
      metadata={
       "category": "sample",
       "kind": "condition",
      },
     ),
     "captain present",
    ),
    actions=(
     quest_action(
      "sample_campaign_return_action",
      "deliver report",
      description="Return the report to the captain and close out the campaign.",
      metadata={
       "category": "sample",
       "kind": "action",
      },
     ),
     "claim the reward",
     "record the outcome",
    ),
    triggers=(
     quest_trigger(
      "sample_campaign_contract_end_trigger",
      "conversation ended",
      conditions=(),
      actions=(),
      description="Marks the end of the sample contract conversation path.",
      metadata={
       "category": "sample",
       "kind": "trigger",
      },
     ),
     quest_trigger(
      "sample_campaign_end_trigger",
      "battle ended",
      conditions=(),
      actions=(),
      description="Tracks the campaign wrap-up path.",
      metadata={
       "category": "sample",
       "kind": "trigger",
      },
     ),
    ),
    rewards=(
     quest_reward(
      "sample_campaign_wrap_reward",
      "campaign complete",
      description="The sample campaign has reached a successful conclusion.",
      metadata={
       "category": "sample",
       "kind": "reward",
      },
     ),
    ),
    failures=(
     quest_failure(
      "sample_campaign_wrap_failure",
      "report lost",
      description="The final report was lost before the captain could review it.",
      metadata={
       "category": "sample",
       "kind": "failure",
      },
     ),
     "report lost",
    ),
    transitions={
     "done": "quests_end",
    },
    metadata={
     "category": "sample",
     "framework": "wrap_up",
     "choice_flow": "consequence_resolution",
    },
    stage_metadata={
     "tone": "closing",
     "sample": True,
    },
   ),
  ),
  entry_quest_id="sample_campaign_briefing",
  metadata={
   "category": "sample",
   "framework": "framework_demo",
   "campaign": "sample_campaign",
  },
  quest_metadata={
   "campaign": "sample_campaign",
   "demo": True,
 },
 stage_metadata={
   "campaign": "sample_campaign",
   "demo": True,
  },
 ).as_legacy_tuples(),
 *quest_chain(
  "sample_campaign_authoring_demo",
  "Sample Campaign Authoring Demo",
  quests=SAMPLE_MOTIF_CHAIN.normalized_quests(),
  entry_quest_id=SAMPLE_MOTIF_CHAIN.entry_quest_id,
  branches=SAMPLE_MOTIF_CHAIN.branches,
  metadata={
   "category": "sample",
   "framework": "authoring_demo",
   "registry": SAMPLE_AUTHORING_REGISTRY.snapshot(),
   "bulk_registry": SAMPLE_BULK_AUTHORING_REGISTRY.snapshot(),
   "lane_contract": SAMPLE_LANE_CONTRACT.to_snapshot(),
   "graph": quest_graph_snapshot(SAMPLE_MOTIF_CHAIN),
   "graph_snapshots": SAMPLE_MOTIF_SNAPSHOTS,
   "graph_report": SAMPLE_MOTIF_GRAPH_REPORT,
   "graph_mermaid": SAMPLE_MOTIF_MERMAID,
   "graph_dot": SAMPLE_MOTIF_DOT,
   "dsl_previews": {
    "reward_bundle": [reward.to_snapshot() for reward in SAMPLE_DSL_REWARDS],
    "failure_bundle": [failure.to_snapshot() for failure in SAMPLE_DSL_FAILURES],
    "branch": {
     "branch_id": SAMPLE_DSL_BRANCH.branch_id,
     "from_stage": SAMPLE_DSL_BRANCH.from_stage,
     "to_stage": SAMPLE_DSL_BRANCH.to_stage,
     "condition": SAMPLE_DSL_BRANCH.condition,
     "description": SAMPLE_DSL_BRANCH.description,
     "metadata": dict(SAMPLE_DSL_BRANCH.metadata),
    },
    "optional_stage": SAMPLE_DSL_OPTIONAL_STAGE.to_snapshot(),
    "timed_stage": SAMPLE_DSL_TIMED_STAGE.to_snapshot(),
    "repeatable_stage": SAMPLE_DSL_REPEATABLE_STAGE.to_snapshot(),
   },
  },
 ).as_legacy_tuples(),

]
