SCRIPTS = [
("add_notification_menu",
    [
      (store_script_param, ":menu_no", 1),
      (store_script_param, ":menu_var_1", 2),
      (store_script_param, ":menu_var_2", 3),
      # Decision menus remain immediate, but duplicate background notices must not grow forever.
      (assign, ":queue_limit", 8),
      (assign, ":duplicate", 0),
      (assign, ":insert_slot", -1),
      (try_for_range, ":cur_slot", 0, ":queue_limit"),
        (try_begin),
          (troop_slot_ge, "trp_notification_menu_types", ":cur_slot", 1),
          (try_begin),
            (troop_slot_eq, "trp_notification_menu_types", ":cur_slot", ":menu_no"),
            (troop_slot_eq, "trp_notification_menu_var1", ":cur_slot", ":menu_var_1"),
            (troop_slot_eq, "trp_notification_menu_var2", ":cur_slot", ":menu_var_2"),
            (assign, ":duplicate", 1),
          (try_end),
        (else_try),
          (lt, ":insert_slot", 0),
          (assign, ":insert_slot", ":cur_slot"),
        (try_end),
      (try_end),
      (assign, reg0, 0),
      (try_begin),
        (eq, ":duplicate", 0),
        (ge, ":insert_slot", 0),
        (troop_set_slot, "trp_notification_menu_types", ":insert_slot", ":menu_no"),
        (troop_set_slot, "trp_notification_menu_var1", ":insert_slot", ":menu_var_1"),
        (troop_set_slot, "trp_notification_menu_var2", ":insert_slot", ":menu_var_2"),
        (assign, reg0, 1),
      (try_end),
  ]),
]
