# COST: low
SCRIPTS = [
("cf_merc_guild_give_new_employer",
	[
	(store_script_param_1, ":guild_no"),

	(call_script, "script_cf_sod_merc_guild_uses_classic_employer_rotation", ":guild_no"),
	(call_script, "script_merc_update_guild_marshal_faction", ":guild_no", "fac_commoners"),

	(assign, ":best_candidate", 0),
	(assign, ":best_score", -100000),
	(try_for_range, ":candidate", native_kingdoms_begin, native_kingdoms_end),
		(faction_slot_eq, ":candidate", slot_faction_state, sfs_active),
		(faction_slot_eq, ":candidate", slot_faction_merc_pact, 0),

		(call_script, "script_sod_merc_market_calculate_kingdom_demand", ":candidate", 0, 0, 0, 0),
		(assign, ":demand_score", reg0),
		(assign, ":budget", reg1),
		(assign, ":max_bid", reg2),
		(assign, ":need_type", reg3),
		(assign, ":urgency", reg4),
		(faction_get_slot, ":preferred_guild", ":candidate", slot_faction_sod_merc_preferred_guild),
		(gt, ":demand_score", 0),
		(gt, ":budget", 0),
		(neq, ":need_type", sod_merc_contract_role_none),

		(call_script, "script_sod_merc_market_calculate_kingdom_guild_weight", ":candidate", ":guild_no", 0, ":need_type"),
		(assign, ":guild_weight", reg0),
		(gt, ":guild_weight", -40),

		(assign, ":candidate_score", ":demand_score"),
		(store_mul, ":urgency_score", ":urgency", 15),
		(val_add, ":candidate_score", ":urgency_score"),
		(store_div, ":bid_score", ":max_bid", 200),
		(val_add, ":candidate_score", ":bid_score"),
		(val_add, ":candidate_score", ":guild_weight"),
		(try_begin),
			(eq, ":preferred_guild", ":guild_no"),
			(val_add, ":candidate_score", 25),
		(try_end),
		(try_begin),
			(faction_get_slot, ":last_hired_guild", ":candidate", slot_faction_sod_merc_last_hired_guild),
			(eq, ":last_hired_guild", ":guild_no"),
			(val_add, ":candidate_score", 10),
		(try_end),
		(try_begin),
			(lt, ":budget", 500),
			(val_sub, ":candidate_score", 15),
		(try_end),
		(gt, ":candidate_score", ":best_score"),
		(assign, ":best_score", ":candidate_score"),
		(assign, ":best_candidate", ":candidate"),
	(try_end),

	(gt, ":best_candidate", 0),
	(faction_set_slot, ":best_candidate", slot_faction_merc_pact, ":guild_no"),
	(faction_set_slot, ":best_candidate", slot_faction_sod_merc_last_hired_guild, ":guild_no"),
	(call_script, "script_merc_update_guild_marshal_faction", ":guild_no", ":best_candidate"),

	]),
]
