SCRIPTS = [
("get_realtion_name_s3",
                      [
                        (store_script_param, ":cur_relation", 1),
                        (try_begin),
                          (ge, ":cur_relation", 90),
                          (str_store_string, s3, "@Loyal"),
                        (else_try),
                          (ge, ":cur_relation", 80),
                          (str_store_string, s3, "@Devoted"),
                        (else_try),
                          (ge, ":cur_relation", 70),
                          (str_store_string, s3, "@Fond"),
                        (else_try),
                          (ge, ":cur_relation", 60),
                          (str_store_string, s3, "@Gracious"),
                        (else_try),
                          (ge, ":cur_relation", 50),
                          (str_store_string, s3, "@Friendly"),
                        (else_try),
                          (ge, ":cur_relation", 40),
                          (str_store_string, s3, "@Supportive"),
                        (else_try),
                          (ge, ":cur_relation", 30),
                          (str_store_string, s3, "@Favorable"),
                        (else_try),
                          (ge, ":cur_relation", 20),
                          (str_store_string, s3, "@Cooperative"),
                        (else_try),
                          (ge, ":cur_relation", 10),
                          (str_store_string, s3, "@Accepting"),
                        (else_try),
                          (ge, ":cur_relation", 0),
                          (str_store_string, s3, "@Indifferent"),
                        (else_try),
                          (ge, ":cur_relation", -10),
                          (str_store_string, s3, "@Suspicious"),
                        (else_try),
                          (ge, ":cur_relation", -20),
                          (str_store_string, s3, "@Grumbling"),
                        (else_try),
                          (ge, ":cur_relation", -30),
                          (str_store_string, s3, "@Hostile"),
                        (else_try),
                          (ge, ":cur_relation", -40),
                          (str_store_string, s3, "@Resentful"),
                        (else_try),
                          (ge, ":cur_relation", -50),
                          (str_store_string, s3, "@Angry"),
                        (else_try),
                          (ge, ":cur_relation", -60),
                          (str_store_string, s3, "@Hateful"),
                        (else_try),
                          (ge, ":cur_relation", -70),
                          (str_store_string, s3, "@Revengeful"),
                        (else_try),
                          (str_store_string, s3, "@Vengeful"),
                        (try_end),
                      ]
                    ),
]
