SCRIPTS = [
("get_player_propaganda", [
		(store_skill_level, ":skill", "skl_persuasion", "trp_player"),
		(val_mul, ":skill", 50),

		(assign, reg0, ":skill"),
		
		(assign, ":size", 0),
		(try_for_range, ":center_no", centers_begin, centers_end),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(try_begin),
				(party_slot_eq, ":center_no", slot_party_type, spt_village),
				(val_add, ":size", 10),
			(else_try),
				(party_slot_eq, ":center_no", slot_party_type, spt_castle),
				(val_add, ":size", 15),
			(else_try),
				(party_slot_eq, ":center_no", slot_party_type, spt_town),
				(val_add, ":size", 30),
			(try_end),
			#building modifiers
			# (try_begin),
				# (party_slot_eq, ":center_no", slot_center_has_inn, 1),
				# (val_sub, ":size", 5),
			# (try_end),
		(try_end),
		
		(val_sub, ":skill", ":size"),
		
		(try_begin),
			(gt, ":skill", 200),
			(assign, reg52, 3),
		(else_try),
			(gt, ":skill", 100),
			(assign, reg52, 2),
		(else_try),
			(gt, ":skill", 50),
			(assign, reg52, 1),
		(else_try),
			(lt, ":skill", -50),
			(assign, reg52, -1),
		(else_try),
			(lt, ":skill", -100),
			(assign, reg52, -2),
		(else_try),
			(lt, ":skill", -200),
			(assign, reg52, -3),
		(else_try),
			(assign, reg52, 0),
		(try_end),
		]),
]
