SCRIPTS = [
("get_rumor_to_s61",
        [
          (store_script_param, ":base_rumor_id", 1), # the script returns the same rumor for the same rumor id, so that one cannot hear all rumors by
          # speaking to a single person.

          (store_current_hours, ":cur_hours"),
          (store_div, ":cur_day", ":cur_hours", 24),
          (assign, ":rumor_found", 0),
          (assign, ":num_tries", 3),
          (try_for_range, ":try_no", 0, ":num_tries"),
            (store_mul, ":rumor_id", ":try_no", 6781),
            (val_add, ":rumor_id", ":base_rumor_id"),
            (store_mod, ":rumor_type", ":rumor_id", 7),
            (val_add, ":rumor_id", ":cur_hours"),
            (try_begin),
              (eq,  ":rumor_type", 0),
              (try_begin),
                (store_sub, ":range", towns_end, towns_begin),
                (store_mod, ":random_center", ":rumor_id", ":range"),
                (val_add, ":random_center", towns_begin),
                (party_slot_ge, ":random_center", slot_town_has_tournament, 1),
                (neq, ":random_center", "$current_town"),
                (str_store_party_name_link, s62, ":random_center"),
                (str_store_string, s61, "@I heard that there will be a tournament in {s62} soon."),
                (assign, ":rumor_found", 1),
              (try_end),
            (else_try),
              (eq,  ":rumor_type", 1),
              (try_begin),
                (store_sub, ":range", kingdom_heroes_end, kingdom_heroes_begin),
                (store_mod, ":random_hero", ":rumor_id", ":range"),
                (val_add, ":random_hero", kingdom_heroes_begin),
                (troop_get_slot, ":personality", ":random_hero", slot_lord_reputation_type),
                (gt, ":personality", 0),
                (store_add, ":rumor_string", ":personality", "str_gossip_about_character_default"),
                (call_script, "script_store_troop_name_link_fief", s6, ":random_hero"),
                (str_store_string, s61, ":rumor_string"),
                (assign, ":rumor_found", 1),
              (try_end),
            (else_try),
              (eq,  ":rumor_type", 2),
              (try_begin),
                (store_sub, ":range", trade_goods_end, trade_goods_begin),
                (store_add, ":random_trade_good", ":rumor_id", ":cur_day"),
                (store_mod, ":random_trade_good", ":random_trade_good", ":range"),
                (store_add, ":random_trade_good_slot", ":random_trade_good", slot_town_trade_good_prices_begin),
                (val_add, ":random_trade_good", trade_goods_begin),
                (store_mul, ":min_price", average_price_factor, 3),
                (val_div, ":min_price", 4),
                (assign, ":min_price_center", -1),
                (try_for_range, ":sub_try_no", 0, 10),
                  (store_sub, ":range", towns_end, towns_begin),
                  (store_add, ":center_rumor_id", ":rumor_id", ":sub_try_no"),
                  (store_mod, ":random_center", ":center_rumor_id", ":range"),
                  (val_add, ":random_center", towns_begin),
                  (neq, ":random_center", "$g_encountered_party"),
                  (party_get_slot, ":cur_price", ":random_center", ":random_trade_good_slot"),
                  (lt, ":cur_price", ":min_price"),
                  (assign, ":min_price", ":cur_price"),
                  (assign, ":min_price_center", ":random_center"),
                (try_end),
                (ge, ":min_price_center", 0),
                (str_store_item_name, s62, ":random_trade_good"),
                (str_store_party_name_link, s63, ":min_price_center"),
                (str_store_string, s61, "@I heard that one can buy {s62} very cheap at {s63}."),
                (assign, ":rumor_found", 1),
              (try_end),
            (else_try),
              (eq,  ":rumor_type", 3),
              (try_begin),
                (store_sub, ":range", trade_goods_end, trade_goods_begin),
                (store_add, ":random_trade_good", ":rumor_id", ":cur_day"),
                (store_mod, ":random_trade_good", ":random_trade_good", ":range"),
                (store_add, ":random_trade_good_slot", ":random_trade_good", slot_town_trade_good_prices_begin),
                (val_add, ":random_trade_good", trade_goods_begin),
                (store_mul, ":max_price", average_price_factor, 5),
                (val_div, ":max_price", 4),
                (assign, ":max_price_center", -1),
                (try_for_range, ":sub_try_no", 0, 10),
                  (store_sub, ":range", towns_end, towns_begin),
                  (store_add, ":center_rumor_id", ":rumor_id", ":sub_try_no"),
                  (store_mod, ":random_center", ":center_rumor_id", ":range"),
                  (val_add, ":random_center", towns_begin),
                  (neq, ":random_center", "$g_encountered_party"),
                  (party_get_slot, ":cur_price", ":random_center", ":random_trade_good_slot"),
                  (gt, ":cur_price", ":max_price"),
                  (assign, ":max_price", ":cur_price"),
                  (assign, ":max_price_center", ":random_center"),
                (try_end),
                (ge, ":max_price_center", 0),
                (str_store_item_name, s62, ":random_trade_good"),
                (str_store_party_name_link, s63, ":max_price_center"),
                (str_store_string, s61, "@I heard that they pay a very high price for {s62} at {s63}."),
                (assign, ":rumor_found", 1),
              (try_end),
            (else_try),
              (eq,  ":rumor_type", 4),
              (try_begin),
                (store_sub, ":range", kingdom_heroes_end, kingdom_heroes_begin),
                (try_for_range, ":sub_try_no", 0, 12),
                  (eq, ":rumor_found", 0),
                  (store_add, ":lord_rumor_id", ":rumor_id", ":sub_try_no"),
                  (store_mod, ":random_lord", ":lord_rumor_id", ":range"),
                  (val_add, ":random_lord", kingdom_heroes_begin),
                  (troop_slot_eq, ":random_lord", slot_troop_occupation, slto_kingdom_hero),
                  (troop_get_slot, ":lord_party", ":random_lord", slot_troop_leaded_party),
                  (gt, ":lord_party", 0),
                  (party_is_active, ":lord_party"),
                  (troop_get_slot, ":lord_morale", ":random_lord", slot_troop_sod_lord_party_morale),
                  (troop_get_slot, ":pay_strain", ":random_lord", slot_troop_sod_lord_pay_strain),
                  (troop_get_slot, ":fatigue", ":random_lord", slot_troop_sod_lord_campaign_fatigue),
                  (troop_get_slot, ":supply", ":random_lord", slot_troop_sod_lord_supply_confidence),
                  (troop_get_slot, ":land_satisfaction", ":random_lord", slot_troop_sod_lord_land_satisfaction),
                  (troop_get_slot, ":ruler_confidence", ":random_lord", slot_troop_sod_lord_ruler_confidence),
                  (troop_get_slot, ":last_petition_day", ":random_lord", slot_troop_sod_lord_last_petition_day),
                  (store_sub, ":days_since_petition", ":cur_day", ":last_petition_day"),
                  (troop_get_slot, ":last_refusal_day", ":random_lord", slot_troop_sod_lord_last_battle_refusal_day),
                  (store_sub, ":days_since_refusal", ":cur_day", ":last_refusal_day"),
                  (troop_get_slot, ":last_broken_day", ":random_lord", slot_troop_sod_lord_last_morale_broken_event_day),
                  (store_sub, ":days_since_broken", ":cur_day", ":last_broken_day"),
                  (troop_get_slot, ":last_home_day", ":random_lord", slot_troop_sod_lord_last_home_morale_event_day),
                  (store_sub, ":days_since_home", ":cur_day", ":last_home_day"),
                  (troop_get_slot, ":last_pay_day", ":random_lord", slot_troop_sod_lord_last_pay_strain_event_day),
                  (store_sub, ":days_since_pay", ":cur_day", ":last_pay_day"),
                  (troop_get_slot, ":last_exhaust_day", ":random_lord", slot_troop_sod_lord_last_exhaustion_event_day),
                  (store_sub, ":days_since_exhaust", ":cur_day", ":last_exhaust_day"),
                  (troop_get_slot, ":last_confident_day", ":random_lord", slot_troop_sod_lord_last_confident_campaign_event_day),
                  (store_sub, ":days_since_confident", ":cur_day", ":last_confident_day"),
                  (call_script, "script_store_troop_name_link_fief", s62, ":random_lord"),
                  (try_begin),
                    (is_between, ":days_since_petition", 0, 22),
                    (str_store_string, s61, "@They say {s62} has asked for land and received promises instead of walls. Landless lords listen carefully when stronger patrons speak."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (lt, ":land_satisfaction", 30),
                    (lt, ":ruler_confidence", 45),
                    (str_store_string, s61, "@I hear {s62} has no fief and little faith left in the ruler's gratitude. A lord without land is a banner looking for wind."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (is_between, ":days_since_broken", 0, 8),
                    (str_store_string, s61, "@The talk is that {s62}'s camp has broken in spirit. Men in that state watch the road home more than the banner."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (is_between, ":days_since_home", 0, 8),
                    (str_store_string, s61, "@I heard {s62} has pulled close to shelter. Some say it is prudence; others say the men would not bear another march."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (is_between, ":days_since_refusal", 0, 8),
                    (str_store_string, s61, "@They say {s62} refused a fight recently. Not cowardice, maybe, but the sort of caution that grows in tired camps."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (is_between, ":days_since_pay", 0, 8),
                    (str_store_string, s61, "@There is grumbling around {s62}'s pay chest. A hungry purse can point a lord toward desperate plunder."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (is_between, ":days_since_exhaust", 0, 8),
                    (str_store_string, s61, "@They say {s62}'s host has marched itself hollow. Even loyal men stumble when the campaign eats their feet."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (is_between, ":days_since_confident", 0, 8),
                    (str_store_string, s61, "@Word is {s62}'s host has coin, food, and confidence. If war offers a prize, that banner may move soon."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (ge, ":pay_strain", 70),
                    (str_store_string, s61, "@They say {s62}'s men are counting their pay twice and smiling never. A poor lord with hungry purses may look for a village or caravan soon."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (ge, ":fatigue", 70),
                    (str_store_string, s61, "@Word is {s62}'s host is exhausted from the campaign. Men can march on pride for a day, but not for a season."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (is_between, ":lord_morale", 1, 30),
                    (str_store_string, s61, "@I hear {s62}'s camp has gone quiet in the wrong way. If pressed too hard, some of those men may simply leave."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (this_or_next|ge, ":lord_morale", 80),
                    (ge, ":supply", 75),
                    (str_store_string, s61, "@They say {s62}'s host is fed, paid, and marching with its chin up. That sort of army does not stay idle long."),
                    (assign, ":rumor_found", 1),
                  (try_end),
              (try_end),
            (try_end),
            (else_try),
              (eq, ":rumor_type", 5),
              (try_begin),
                (try_for_parties, ":train_party"),
                  (eq, ":rumor_found", 0),
                  (party_is_active, ":train_party"),
                  (party_slot_eq, ":train_party", slot_party_type, spt_prisoner_train),
                  (party_get_slot, ":destination", ":train_party", slot_party_sod_prisoner_destination),
                  (is_between, ":destination", centers_begin, centers_end),
                  (party_get_slot, ":purpose", ":train_party", slot_party_sod_prisoner_purpose),
                  (party_get_slot, ":total", ":train_party", slot_party_sod_prisoner_total_count),
                  (gt, ":total", 0),
                  (str_store_party_name_link, s62, ":destination"),
                  (assign, reg61, ":total"),
                  (try_begin),
                    (eq, ":purpose", sod_prisoner_train_purpose_slaver_market),
                    (str_store_string, s61, "@They say a guarded prisoner train is moving captives toward the slave markets. There are about {reg61} souls in chains, if the road talk is true."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (eq, ":purpose", sod_prisoner_train_purpose_liberation),
                    (str_store_string, s61, "@I heard a prisoner train is carrying freed captives toward {s62}. Hungry mouths, grateful hands, and trouble for anyone hunting slaves."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (eq, ":purpose", sod_prisoner_train_purpose_exchange),
                    (str_store_string, s61, "@A prisoner train is bound for {s62}, they say. Military captives, likely for exchange if the lords can stomach a bargain."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (eq, ":purpose", sod_prisoner_train_purpose_ransom),
                    (str_store_string, s61, "@There is talk of a prisoner train headed for {s62}. Ransom brokers and counting houses will be busy if it arrives."),
                    (assign, ":rumor_found", 1),
                  (else_try),
                    (str_store_string, s61, "@A prisoner train is said to be moving toward {s62}, guarded but slow. Such parties draw protectors, raiders, and desperate kin alike."),
                    (assign, ":rumor_found", 1),
                  (try_end),
                (try_end),
              (try_end),
            (try_end),
            (try_begin),
              (gt, ":rumor_found", 0),
              (assign, ":num_tries", 0),
            (try_end),
          (try_end),
          (assign, reg0, ":rumor_found"),
      ]),
]
