SCRIPTS = [
("init_mercenary_base_walkers",
    [
	  (store_script_param_1, ":cur_scene"),
	  (try_begin),
		(is_between, ":cur_scene", "scn_slavers_base", "scn_jotnar_clan_arena"),
		(assign, ":base_center", "p_sod_merc_guild_6"),
		(assign, ":num_walkers", 3),
		(assign, ":num_guards", 5),
	  (else_try),
		(eq, "$g_sod_from_menu", -1),
		(assign, ":base_center", "$g_encountered_party"),
		(assign, ":num_walkers", 0),
		(assign, ":num_guards", 6),
	  (else_try),
		(assign, ":base_center", "$g_encountered_party"),
		(assign, ":num_walkers", 5),
		(assign, ":num_guards", 9),
	  (try_end),
      (modify_visitors_at_site, ":cur_scene"),
      (reset_visitors),
	  (try_begin),
		(eq, "$g_sod_from_menu", -1),
		(store_faction_of_party, ":guild", ":base_center"),
		(faction_get_slot, ":representative", ":guild", slot_guild_representative),
		(set_visitor, 10, ":representative"),
	  (try_end),
	  (try_begin),
		(eq, ":base_center", "p_sod_merc_guild_6"),
        (set_visitor, 10, "trp_slaver_guild_master"),
		(assign, ":entry_no", 21),
		(try_for_range, ":unused", 0, 10),
			(set_visitor, ":entry_no", "trp_slave"),
			(val_add, ":entry_no", 1),
		(try_end),
	  (try_end),
	  (try_begin),
		(neq, "$prison_break", 5),
		(neq, "$prison_break", 6),
		(eq, ":cur_scene", "scn_slavers_base_jelkala"),
        (set_visitor, 20, "trp_slave_hero"),
	  (try_end),
	  (assign, reg0, slot_center_walker_0_troop),
      (assign, reg1, slot_center_walker_1_troop),
      (assign, reg2, slot_center_walker_2_troop),
      (assign, reg3, slot_center_walker_3_troop),
      (assign, reg4, slot_center_walker_4_troop),
      (try_for_range, ":walker_no", 0, ":num_walkers"),
		  (shuffle_range, 0, 5),
          (store_add, ":troop_slot", slot_center_walker_0_troop, ":walker_no"),
          (party_get_slot, ":walker_troop_id", ":base_center", ":troop_slot"),
          (store_add, ":entry_no", 11, ":walker_no"),
          (set_visitor, ":entry_no", ":walker_troop_id"),
      (try_end),
	  (assign, reg0, slot_center_guard_0_troop),
      (assign, reg1, slot_center_guard_1_troop),
      (assign, reg2, slot_center_guard_2_troop),
      (assign, reg3, slot_center_guard_3_troop),
      (assign, reg4, slot_center_guard_4_troop),
      (assign, reg5, slot_center_guard_5_troop),
      (assign, reg6, slot_center_guard_6_troop),
      (assign, reg7, slot_center_guard_7_troop),
      (assign, reg8, slot_center_guard_8_troop),
	  (try_begin),
		  (eq, ":cur_scene", "scn_sod_merc_guild_3_interior"),
		  (try_for_range, ":walker_no", 0, ":num_guards"),
			  (store_add, ":entry_no", 1, ":walker_no"),
			  (set_visitor, ":entry_no", "trp_elephant_guard_battle_shaman"),
		  (try_end),
	  (else_try),
		  (try_for_range, ":walker_no", 0, ":num_guards"),
			  (shuffle_range, 0, 9),
			  (party_get_slot, ":walker_troop_id", ":base_center", reg0),
			  (store_add, ":entry_no", 1, ":walker_no"),
			  (set_visitor, ":entry_no", ":walker_troop_id"),
		  (try_end),
	  (try_end),
	  (assign, "$talk_context", tc_mercenary_base),
	  ]),
]
