# COST: trivial
SCRIPTS = [
("merc_describe_pact_status",
 [
   (store_script_param_1, ":guild_faction"),
   (str_store_string, s59, "@No pact has been recorded."),
   (try_begin),
     (gt, ":guild_faction", 0),
     (store_relation, ":rel", ":guild_faction", "fac_player_faction"),
     (assign, reg5, "$g_mercenary_guild_weekly_payment"),
     (faction_get_slot, reg6, ":guild_faction", player_debt_to_faction),
     (try_begin),
       (ge, "$g_sod_merc_weekly_paiment_not_paid_in_a_row", 4),
       (str_store_string, s59, "@Severe arrears: the pact is close to cancellation. New companies are refused until the debt is settled."),
     (else_try),
       (gt, reg6, 3000),
       (str_store_string, s59, "@Heavy debt outstanding: {reg6} denars. Prices rise sharply, replacements stop, and guild patience is thin."),
     (else_try),
       (gt, reg6, 0),
       (str_store_string, s59, "@Debt outstanding: {reg6} denars. This weakens priority, raises retainers, and stops replacements until paid."),
     (else_try),
       (ge, "$g_sod_merc_weekly_paiment_not_paid_in_a_row", 2),
       (str_store_string, s59, "@Payment record poor: the guild is keeping you on a short leash until you rebuild trust."),
     (else_try),
       (ge, ":rel", 35),
       (str_store_string, s59, "@Trusted pact: your standing softens the burden and helps contain debt."),
     (else_try),
       (ge, ":rel", 20),
       (str_store_string, s59, "@Stable pact: the guild still expects punctual payment, but relations are sound."),
     (else_try),
       (str_store_string, s59, "@Fragile pact: missed payments will quickly poison this arrangement."),
     (try_end),
   (try_end),
 ]),
]
