# COST: medium
SCRIPTS = [
("merc_apply_daily_standing_perks",
 [
   (try_for_parties, ":cur_party"),
     (party_slot_eq, ":cur_party", slot_party_type, spt_player_mercenaries),
     (party_slot_eq, ":cur_party", slot_party_boss, "trp_player"),
     (party_get_slot, ":guild_faction", ":cur_party", slot_party_orginal_faction),
     (gt, ":guild_faction", 0),
     (store_relation, ":rel", ":guild_faction", "fac_player_faction"),
     (ge, ":rel", 25),
     (store_party_size, ":size", ":cur_party"),
     (faction_get_slot, ":proportion", ":guild_faction", slot_guild_troop_proportion),
     (store_sub, ":target_size", 34, ":proportion"),
     (val_max, ":target_size", 18),
     (val_add, ":target_size", 8),
     (store_sub, ":room", ":target_size", ":size"),
     (val_max, ":room", 0),
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild1"),
       (store_mul, ":xp", ":size", 4),
       (call_script, "script_cf_party_upgrade_with_xp", ":cur_party", ":xp", 0),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild2"),
       (ge, ":rel", 30),
       (gt, ":room", 0),
       (faction_get_slot, ":troop_no", ":guild_faction", slot_guild_tier_1_unit_2),
       (party_add_members, ":cur_party", ":troop_no", 1),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild3"),
       (ge, ":rel", 40),
       (gt, ":room", 0),
       (faction_get_slot, ":troop_no", ":guild_faction", slot_guild_noble),
       (party_add_members, ":cur_party", ":troop_no", 1),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild4"),
       (gt, ":room", 0),
       (faction_get_slot, ":troop_no", ":guild_faction", slot_guild_tier_1_unit_1),
       (party_add_members, ":cur_party", ":troop_no", 1),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild5"),
       (ge, ":rel", 35),
       (gt, ":room", 0),
       (try_begin),
         (ge, ":room", 2),
         (faction_get_slot, ":troop_no", ":guild_faction", slot_guild_tier_1_unit_2),
       (else_try),
         (faction_get_slot, ":troop_no", ":guild_faction", slot_guild_tier_1_unit_1),
       (try_end),
       (party_add_members, ":cur_party", ":troop_no", 1),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       (troop_add_gold, "trp_player", 25),
       (gt, ":room", 0),
       (faction_get_slot, ":troop_no", ":guild_faction", slot_guild_tier_1_unit_1),
       (party_add_members, ":cur_party", ":troop_no", 1),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild7"),
       (gt, ":room", 0),
       (faction_get_slot, ":troop_no", ":guild_faction", slot_guild_tier_1_unit_1),
       (party_add_members, ":cur_party", ":troop_no", 1),
       (store_mul, ":xp", ":size", 2),
       (call_script, "script_cf_party_upgrade_with_xp", ":cur_party", ":xp", 0),
     (try_end),
   (try_end),

   (try_begin),
     (faction_get_slot, ":pact_guild", "fac_player_faction", slot_faction_merc_pact),
     (gt, ":pact_guild", 0),
     (store_relation, ":rel", ":pact_guild", "fac_player_faction"),
     (ge, ":rel", 35),
     (faction_get_slot, ":debt", ":pact_guild", player_debt_to_faction),
     (assign, ":discount", 20),
     (try_begin),
       (eq, ":pact_guild", "fac_sod_merc_guild3"),
       (assign, ":discount", 25),
     (else_try),
       (eq, ":pact_guild", "fac_sod_merc_guild6"),
       (assign, ":discount", 35),
       (store_num_regular_prisoners, ":num_prisoners", "p_main_party"),
       (gt, ":num_prisoners", 0),
       (assign, ":prisoner_cut", ":num_prisoners"),
       (val_min, ":prisoner_cut", 3),
       (store_mul, ":prisoner_cut", ":prisoner_cut", 25),
       (troop_add_gold, "trp_player", ":prisoner_cut"),
     (try_end),
     (gt, ":debt", 0),
     (val_sub, ":debt", ":discount"),
     (val_max, ":debt", 0),
     (faction_set_slot, ":pact_guild", player_debt_to_faction, ":debt"),
   (try_end),
 ]),
]
