# COST: medium
SCRIPTS = [
("merc_apply_master_service",
 [
   (store_script_param_1, ":guild_faction"),

   (assign, ":service_cost", 0),
   (assign, ":applied", 0),
   (call_script, "script_merc_describe_master_service", ":guild_faction"),

   (try_begin),
     (eq, ":guild_faction", "fac_sod_merc_guild1"),
     (assign, ":service_cost", 1200),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild2"),
     (assign, ":service_cost", 900),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild3"),
     (assign, ":service_cost", 1000),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild4"),
     (assign, ":service_cost", 700),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild5"),
     (assign, ":service_cost", 1100),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild6"),
     (assign, ":service_cost", 500),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild7"),
     (assign, ":service_cost", 800),
   (try_end),

   (store_troop_gold, ":gold", "trp_player"),
   (try_begin),
     (ge, ":gold", ":service_cost"),
     (call_script, "script_sod_player_charge_gold", ":service_cost"),
     (call_script, "script_change_player_relation_with_faction", ":guild_faction", -2),

     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       (assign, ":captives_sold", 0),
       (assign, ":bonus", 0),
       (party_get_num_prisoner_stacks, ":num_prisoner_stacks", "p_main_party"),
       (try_for_range_backwards, ":stack_no", 0, ":num_prisoner_stacks"),
         (lt, ":captives_sold", 3),
         (party_prisoner_stack_get_troop_id, ":stack_troop", "p_main_party", ":stack_no"),
         (neg|troop_is_hero, ":stack_troop"),
         (party_prisoner_stack_get_size, ":stack_size", "p_main_party", ":stack_no"),
         (store_sub, ":space_left", 3, ":captives_sold"),
         (assign, ":sold_now", ":stack_size"),
         (val_min, ":sold_now", ":space_left"),
         (gt, ":sold_now", 0),
         (party_remove_prisoners, "p_main_party", ":stack_troop", ":sold_now"),
         (store_mul, ":stack_bonus", ":sold_now", 80),
         (val_add, ":bonus", ":stack_bonus"),
         (val_add, ":captives_sold", ":sold_now"),
       (try_end),
       (try_begin),
         (gt, ":bonus", 0),
         (troop_add_gold, "trp_player", ":bonus"),
         (assign, reg59, ":captives_sold"),
         (display_message, "@The slavers broker {reg59} captives through their hidden market and cut you in on the take.", 0x66CC66),
       (else_try),
         (troop_add_gold, "trp_player", 250),
         (display_message, "@The slavers sell you dirty information and a small kickback, but they expect further business.", 0x66CC66),
       (try_end),
       (assign, ":applied", 1),
     (else_try),
       (try_for_parties, ":cur_party"),
         (eq, ":applied", 0),
         (party_slot_eq, ":cur_party", slot_party_type, spt_player_mercenaries),
         (party_slot_eq, ":cur_party", slot_party_boss, "trp_player"),
         (party_slot_eq, ":cur_party", slot_party_orginal_faction, ":guild_faction"),
         (try_begin),
           (eq, ":guild_faction", "fac_sod_merc_guild1"),
           (store_party_size, ":size", ":cur_party"),
           (store_mul, ":xp", ":size", 25),
           (call_script, "script_cf_party_upgrade_with_xp", ":cur_party", ":xp", 0),
         (else_try),
           (eq, ":guild_faction", "fac_sod_merc_guild2"),
           (faction_get_slot, ":t1_1", ":guild_faction", slot_guild_tier_1_unit_1),
           (faction_get_slot, ":t1_2", ":guild_faction", slot_guild_tier_1_unit_2),
           (party_add_members, ":cur_party", ":t1_1", 4),
           (party_add_members, ":cur_party", ":t1_2", 2),
         (else_try),
           (eq, ":guild_faction", "fac_sod_merc_guild3"),
           (faction_get_slot, ":noble", ":guild_faction", slot_guild_noble),
           (party_add_members, ":cur_party", ":noble", 2),
           (store_party_size, ":size", ":cur_party"),
           (store_mul, ":xp", ":size", 12),
           (call_script, "script_cf_party_upgrade_with_xp", ":cur_party", ":xp", 0),
         (else_try),
           (eq, ":guild_faction", "fac_sod_merc_guild4"),
           (faction_get_slot, ":t1_1", ":guild_faction", slot_guild_tier_1_unit_1),
           (faction_get_slot, ":t1_2", ":guild_faction", slot_guild_tier_1_unit_2),
           (party_add_members, ":cur_party", ":t1_1", 5),
           (party_add_members, ":cur_party", ":t1_2", 2),
         (else_try),
           (eq, ":guild_faction", "fac_sod_merc_guild5"),
           (faction_get_slot, ":noble", ":guild_faction", slot_guild_noble),
           (faction_get_slot, ":t1_1", ":guild_faction", slot_guild_tier_1_unit_1),
           (party_add_members, ":cur_party", ":noble", 2),
           (party_add_members, ":cur_party", ":t1_1", 2),
         (else_try),
           (eq, ":guild_faction", "fac_sod_merc_guild6"),
           (faction_get_slot, ":t1_1", ":guild_faction", slot_guild_tier_1_unit_1),
           (faction_get_slot, ":t1_2", ":guild_faction", slot_guild_tier_1_unit_2),
           (party_add_members, ":cur_party", ":t1_1", 6),
           (party_add_members, ":cur_party", ":t1_2", 3),
         (else_try),
           (eq, ":guild_faction", "fac_sod_merc_guild7"),
           (faction_get_slot, ":t1_1", ":guild_faction", slot_guild_tier_1_unit_1),
           (faction_get_slot, ":noble", ":guild_faction", slot_guild_noble),
           (party_add_members, ":cur_party", ":t1_1", 4),
           (party_add_members, ":cur_party", ":noble", 1),
         (try_end),
         (assign, ":applied", 1),
       (try_end),
     (try_end),

     (try_begin),
       (eq, ":applied", 0),
       (eq, ":guild_faction", "fac_sod_merc_guild7"),
       (party_add_members, "p_main_party", "trp_boar_clan_clansman", 2),
       (party_add_members, "p_main_party", "trp_boar_clan_tusk_rider", 1),
       (display_message, "@A few Boar Clan outriders volunteer to ride with you for a while.", 0x66CC66),
       (assign, ":applied", 1),
     (try_end),

     (try_begin),
       (eq, ":applied", 1),
       (neq, ":guild_faction", "fac_sod_merc_guild6"),
       (neq, ":guild_faction", "fac_sod_merc_guild7"),
       (display_message, "@The guild master arranges the service at once. Your standing drops slightly from the favor and price haggling.", 0x66CC66),
     (try_end),
   (try_end),
 ]),
]
