# COST: trivial
SCRIPTS = [
("merc_describe_guild_offer",
 [
   (store_script_param_1, ":guild_faction"),

   (str_store_string, s50, "@balanced companies"),
   (str_store_string, s51, "@steady field replacement"),
   (str_store_string, s52, "@standard rates"),
   (assign, reg20, 100),

   (try_begin),
     (eq, ":guild_faction", "fac_sod_merc_guild1"),
     (str_store_string, s50, "@elite shock troops"),
     (str_store_string, s51, "@slow but brutal replacement quality"),
     (str_store_string, s52, "@premium rates"),
     (assign, reg20, 118),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild2"),
     (str_store_string, s50, "@disciplined mixed-arms companies"),
     (str_store_string, s51, "@reliable recovery"),
     (str_store_string, s52, "@above-average rates"),
     (assign, reg20, 108),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild3"),
     (str_store_string, s50, "@heavy specialist warbands"),
     (str_store_string, s51, "@measured recovery"),
     (str_store_string, s52, "@specialist rates"),
     (assign, reg20, 110),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild4"),
     (str_store_string, s50, "@hardy raiding bands"),
     (str_store_string, s51, "@quick replenishment"),
     (str_store_string, s52, "@discount rates"),
     (assign, reg20, 94),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild5"),
     (str_store_string, s50, "@fast striking cavalry"),
     (str_store_string, s51, "@selective reinforcement"),
     (str_store_string, s52, "@premium mounted rates"),
     (assign, reg20, 116),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild6"),
     (str_store_string, s50, "@cheap disposable muscle"),
     (str_store_string, s51, "@very quick replenishment"),
     (str_store_string, s52, "@cheap rates"),
     (assign, reg20, 88),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild7"),
     (str_store_string, s50, "@rugged frontier fighters"),
     (str_store_string, s51, "@fast replacement"),
     (str_store_string, s52, "@hard bargain rates"),
     (assign, reg20, 92),
   (try_end),

   (store_relation, ":rel", ":guild_faction", "fac_player_faction"),
   (str_store_string, s53, "@no trust discount"),
   (try_begin),
     (ge, ":rel", 75),
     (str_store_string, s53, "@deep-trust discount"),
   (else_try),
     (ge, ":rel", 50),
     (str_store_string, s53, "@strong-trust discount"),
   (else_try),
     (ge, ":rel", 25),
     (str_store_string, s53, "@favored-client discount"),
   (else_try),
     (lt, ":rel", 0),
     (str_store_string, s53, "@suspicion surcharge"),
   (try_end),
 ]),
]
