# COST: trivial
SCRIPTS = [
("merc_describe_guild_progression",
 [
   (store_script_param_1, ":guild_faction"),

   (store_relation, ":rel", ":guild_faction", "fac_player_faction"),
   (call_script, "script_merc_get_elite_relation_requirement", ":guild_faction"),
   (assign, ":elite_req", reg0),

   (str_store_string, s64, "@No promotion backing yet."),
   (str_store_string, s65, "@No pact is on the books."),

   (try_begin),
     (ge, ":rel", 40),
     (str_store_string, s64, "@Trusted favor is open."),
   (else_try),
     (ge, ":rel", 30),
     (str_store_string, s64, "@Special service is open."),
   (else_try),
     (ge, ":rel", ":elite_req"),
     (str_store_string, s64, "@Elite access is open."),
   (else_try),
     (ge, ":rel", 10),
     (str_store_string, s64, "@Promotion backing is open."),
   (try_end),

   (try_begin),
     (faction_slot_eq, "fac_player_faction", slot_faction_merc_pact, ":guild_faction"),
     (str_store_string, s65, "@Pact in force."),
   (else_try),
     (call_script, "script_cf_sod_player_has_active_merc_company_from_guild", ":guild_faction"),
     (str_store_string, s65, "@Company in the field."),
   (try_end),

   (call_script, "script_merc_get_guild_quest_tier", ":guild_faction"),
   (try_begin),
     (eq, reg0, 4),
     (str_store_string, s66, "@Elite contracts are available."),
   (else_try),
     (eq, reg0, 3),
     (str_store_string, s66, "@Advanced work is available."),
   (else_try),
     (eq, reg0, 2),
     (str_store_string, s66, "@Contract work is available."),
   (else_try),
     (eq, reg0, 1),
     (str_store_string, s66, "@Basic guild work is available."),
   (else_try),
     (str_store_string, s66, "@Only courier work is being offered."),
   (try_end),

   (assign, reg0, ":elite_req"),
 ]),
]
