# COST: trivial
SCRIPTS = [
("merc_describe_standing_report",
 [
   (store_script_param_1, ":guild_faction"),

   (store_relation, ":rel", ":guild_faction", "fac_player_faction"),
   (call_script, "script_merc_get_elite_relation_requirement", ":guild_faction"),
   (assign, ":elite_req", reg0),
   (assign, reg0, ":elite_req"),

   (str_store_string, s56, "@No standing benefits yet."),
   (str_store_string, s57, "@Next unlock: promotion permission at 10 relation."),
   (str_store_string, s58, "@Standing track: 10 promote access, guild passive support, elite access, 30 special service, 40 trusted favor."),

   (try_begin),
     (ge, ":rel", 40),
     (str_store_string, s57, "@All major trust unlocks are already open to you here."),
   (else_try),
     (ge, ":rel", 30),
     (str_store_string, s57, "@Next unlock: trusted favor at 40 relation."),
   (else_try),
     (ge, ":rel", ":elite_req"),
     (str_store_string, s57, "@Next unlock: special service at 30 relation."),
   (else_try),
     (ge, ":rel", 10),
     (str_store_string, s57, "@Next unlock: elite access at {reg0} relation."),
   (try_end),

   (try_begin),
     (lt, ":rel", 10),
     (str_store_string, s56, "@You are still an outsider here. The guild deals with you, but trust remains limited."),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild1"),
     (store_num_parties_of_template, reg10, "pt_black_army_patrol"),
     (store_num_parties_of_template, reg11, "pt_black_army_contract_column"),
     (store_add, reg12, reg10, reg11),
     (try_begin),
       (assign, ":employer_faction", 0),
       (try_for_range, ":cur_faction", native_kingdoms_begin, native_kingdoms_end),
         (eq, ":employer_faction", 0),
         (faction_slot_eq, ":cur_faction", slot_faction_merc_pact, "fac_sod_merc_guild1"),
         (faction_slot_eq, ":cur_faction", slot_faction_state, sfs_active),
         (assign, ":employer_faction", ":cur_faction"),
       (try_end),
       (gt, ":employer_faction", 0),
       (str_store_faction_name, s59, ":employer_faction"),
     (else_try),
       (str_store_string, s59, "@no realm"),
     (try_end),
     (call_script, "script_sod_black_army_describe_status_to_s24"),
     (str_store_string, s56, "@Black Army standing: road-security network active. Security fund {reg24}, contract heat {reg25}, active detachments {reg23}, current employer {s21}. Protection contracts and anti-bandit work feed this pressure."),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild2"),
     (call_script, "script_sod_conquistador_describe_status_to_s25"),
     (str_store_string, s56, "@Conquistador standing: expeditionary supply machine active. Supply stock {reg24}, requisition heat {reg25}, active logistics parties {reg23}. Their contracts favor disciplined supply, iron, horses, and military readiness."),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild3"),
     (call_script, "script_sod_elephant_guard_describe_status_to_s21"),
     (store_num_parties_of_template, reg10, "pt_elephant_guard_sanctuary_patrol"),
     (store_num_parties_of_template, reg11, "pt_elephant_guard_relic_procession"),
     (store_add, reg12, reg10, reg11),
     (str_store_string, s56, "@Elephant Guard standing: sanctuary patrols active: {reg10}; relic processions active: {reg11} ({reg12} total). Devotion {reg21}, supplies {reg22}, omens {reg23}. Current rite focus: {s21}."),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild4"),
     (store_num_parties_of_template, reg10, "pt_jotnar_hearth_guard"),
     (store_num_parties_of_template, reg11, "pt_jotnar_wintering_camp"),
     (store_add, reg12, reg10, reg11),
     (faction_get_slot, reg13, "fac_sod_merc_guild4", slot_faction_jotnar_hearth_pressure),
     (faction_get_slot, ":target_center", "fac_sod_merc_guild4", slot_faction_jotnar_target_center),
     (call_script, "script_sod_store_center_name_or_fallback_to_s21", ":target_center", "@no confirmed frontier village"),
     (str_store_string, s56, "@Jotnar standing: hearth guards active: {reg10}; wintering camps active: {reg11} ({reg12} total). Clan hearth pressure {reg13}; current village focus: {s21}."),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild5"),
     (call_script, "script_sod_serpent_host_describe_status_to_s26"),
     (str_store_string, s56, "@Serpent Host standing: route intelligence network active. Pressure {reg24}, intelligence {reg25}, safe passage {reg26}, active riders {reg23}, focus {s21}. They sell maps, warnings, and quiet roads."),
   (else_try),
     (eq, ":guild_faction", "fac_sod_merc_guild6"),
     (call_script, "script_sod_slavers_describe_status_to_s20"),
     (str_store_string, s56, "@Slaver standing: black-market web active. Demand {reg20}, supply {reg21}, heat {reg22}, bases {reg23}, active transports {reg24}. Prisoner sales and slave purchases feed this pressure."),
  (else_try),
    (eq, ":guild_faction", "fac_sod_merc_guild7"),
    (call_script, "script_sod_boar_clan_describe_status_to_s23"),
    (str_store_string, s56, "@Boar Clan standing: toll-band network active. Pressure {reg24}, tribute {reg25}, intimidation {reg26}, active bands {reg23}, current mark {s21}. Paying tolls or hiring bands buys rough respect; defying them makes the roads meaner."),
  (try_end),
]),
]
