# COST: moderate
SCRIPTS = [
("ponavosa_duel_resolve",
 [
   (store_script_param_1, ":result"), # 1 ally wins, 2 enemy wins, 3 dishonor, 4 stalemate
   (assign, ":routing_team", -1),
   (try_begin),
     (eq, ":result", 1),
     (assign, ":routing_team", "$ponavosa_duel_enemy_team"),
     (display_message, "@The enemy commander falls! Their line wavers!", 0x7CFC00),
     (agent_get_wielded_item, ":winner_weapon", "$ponavosa_duel_ally_agent", 0),
     (agent_get_troop_id, ":winner_troop", "$ponavosa_duel_ally_agent"),
     (try_begin),
       (gt, ":winner_weapon", 0),
       (call_script, "script_sod_artifact_add_kill", ":winner_weapon", 0, ":winner_troop", 5),
     (try_end),
     (try_begin),
       (eq, "$ponavosa_duel_player_involved", 1),
       (call_script, "script_change_player_honor", 5),
       (assign, "$g_sod_doctrine_inspiration", 5),
       (display_message, "@The victory becomes a drill-yard legend. A few veterans will train with renewed fire.", 0x7CFC00),
     (try_end),
   (else_try),
     (eq, ":result", 2),
     (assign, ":routing_team", "$ponavosa_duel_ally_team"),
     (display_message, "@Our champion is beaten! The men recoil in horror!", 0xFF4500),
     (agent_get_wielded_item, ":winner_weapon", "$ponavosa_duel_enemy_agent", 0),
     (agent_get_troop_id, ":winner_troop", "$ponavosa_duel_enemy_agent"),
     (try_begin),
       (gt, ":winner_weapon", 0),
       (call_script, "script_sod_artifact_add_kill", ":winner_weapon", 0, ":winner_troop", 5),
     (try_end),
   (else_try),
     (eq, ":result", 3),
     (display_message, "@The duel is dishonored! The ring breaks and battle resumes!", 0xFF4500),
     (try_begin),
       (eq, "$ponavosa_duel_player_involved", 1),
       (call_script, "script_change_player_honor", -8),
     (try_end),
   (else_try),
     (display_message, "@The duel ends in stalemate. Neither army yields the field.", 0xFFD27A),
   (try_end),
   (try_begin),
     (ge, ":routing_team", 0),
     (display_message, "@The sight rolls through the ranks like a judgement. Lesser troops start to break.", 0xFFD27A),
     (try_for_agents, ":agent_no"),
       (agent_is_alive, ":agent_no"),
       (agent_is_human, ":agent_no"),
       (agent_get_team, ":team_no", ":agent_no"),
       (eq, ":team_no", ":routing_team"),
       (agent_get_troop_id, ":troop_no", ":agent_no"),
       (try_begin),
         (troop_is_hero, ":troop_no"),
         (agent_clear_scripted_mode, ":agent_no"),
       (else_try),
         (store_character_level, ":level", ":troop_no"),
         (lt, ":level", 16),
         (agent_get_position, pos1, ":agent_no"),
         (position_move_y, pos1, -5200),
         (agent_set_scripted_destination, ":agent_no", pos1, 1),
         (agent_set_speed_limit, ":agent_no", 12),
         (agent_ai_set_always_attack_in_melee, ":agent_no", 0),
       (else_try),
         (lt, ":level", 25),
         (agent_get_position, pos1, ":agent_no"),
         (position_move_y, pos1, -3000),
         (agent_set_scripted_destination, ":agent_no", pos1, 1),
         (agent_set_speed_limit, ":agent_no", 8),
         (agent_ai_set_always_attack_in_melee, ":agent_no", 0),
       (else_try),
         (agent_clear_scripted_mode, ":agent_no"),
         (agent_set_speed_limit, ":agent_no", 6),
       (try_end),
     (try_end),
   (try_end),
   (call_script, "script_ponavosa_duel_restore"),
 ]),
]
