# COST: trivial
SCRIPTS = [
("ponavosa_duel_apply_commander_aura",
 [
   (store_script_param_1, ":agent_no"),
   (agent_get_troop_id, ":troop_no", ":agent_no"),
   (store_attribute_level, ":str", ":troop_no", ca_strength),
   (store_attribute_level, ":agi", ":troop_no", ca_agility),
   (store_add, ":prowess", ":str", ":agi"),
   (store_div, ":faith_rank", "$g_sod_faith", 20),
   (val_clamp, ":faith_rank", 0, 6),
   (store_div, ":speed_bonus", ":prowess", 12),
   (val_add, ":speed_bonus", ":faith_rank"),
   (store_add, ":speed_limit", 7, ":speed_bonus"),
   (val_clamp, ":speed_limit", 7, 13),
   (troop_get_slot, ":nemesis_strength", ":troop_no", slot_troop_sod_nemesis_strength),
   (try_begin),
     (gt, ":nemesis_strength", 0),
     (val_add, ":speed_limit", ":nemesis_strength"),
     (val_clamp, ":speed_limit", 7, 16),
   (try_end),
   (agent_set_speed_limit, ":agent_no", ":speed_limit"),
   (agent_set_slot, ":agent_no", slot_agent_duel_faith_rank, ":faith_rank"),
   (agent_set_slot, ":agent_no", slot_agent_duel_speed_limit, ":speed_limit"),
   (agent_set_slot, ":agent_no", slot_agent_duel_pressure, 1),
   (agent_ai_set_always_attack_in_melee, ":agent_no", 1),
   (store_agent_hit_points, ":hp", ":agent_no"),
   (troop_get_slot, ":adaptation", ":troop_no", slot_troop_sod_nemesis_adaptation),
   (troop_get_slot, ":adapt_count", ":troop_no", slot_troop_sod_nemesis_adaptation_count),
   (try_begin),
     (ge, ":faith_rank", 4),
     (lt, ":hp", 85),
     (agent_set_hit_points, ":agent_no", 85),
   (else_try),
     (ge, ":faith_rank", 2),
     (lt, ":hp", 75),
     (agent_set_hit_points, ":agent_no", 75),
   (try_end),
   (try_begin),
     (gt, ":nemesis_strength", 0),
     (store_mul, ":nemesis_hp_floor", ":nemesis_strength", 4),
     (val_add, ":nemesis_hp_floor", 75),
     (val_min, ":nemesis_hp_floor", 98),
     (store_agent_hit_points, ":hp", ":agent_no"),
     (lt, ":hp", ":nemesis_hp_floor"),
     (agent_set_hit_points, ":agent_no", ":nemesis_hp_floor"),
     (str_store_troop_name, s3, ":troop_no"),
     (assign, reg3, ":nemesis_strength"),
     (display_message, "@{s3} has hardened from repeated defeats. Nemesis strength {reg3}.", 0xFFD27A),
   (try_end),
   (try_begin),
     (gt, ":adapt_count", 0),
     (str_store_troop_name, s3, ":troop_no"),
     (assign, reg4, ":adapt_count"),
     (try_begin),
       (eq, ":adaptation", sod_nemesis_adaptation_anti_cavalry),
       (display_message, "@{s3} has drilled against mounted pressure since your last victory. Adaptation {reg4}.", 0xFFB347),
     (else_try),
       (eq, ":adaptation", sod_nemesis_adaptation_anti_ranged),
       (display_message, "@{s3} has learned to cross killing ground under shields. Adaptation {reg4}.", 0xFFB347),
     (else_try),
       (eq, ":adaptation", sod_nemesis_adaptation_anti_duel),
       (display_message, "@{s3} has trained for the moment when command becomes single combat. Adaptation {reg4}.", 0xFFB347),
     (else_try),
       (display_message, "@{s3} has revised his guard and footwork for a closer fight. Adaptation {reg4}.", 0xFFB347),
     (try_end),
   (try_end),
   (try_begin),
     (ge, ":prowess", 40),
     (display_message, "@A veteran champion steps into the ring.", 0xFFD27A),
   (else_try),
     (ge, ":prowess", 32),
     (display_message, "@A proven commander accepts the challenge.", 0xFFD27A),
   (try_end),
   (try_begin),
     (ge, ":faith_rank", 4),
     (display_message, "@The faithful cry out; the champion surges with dreadful purpose.", faith_color),
   (else_try),
     (ge, ":faith_rank", 2),
     (display_message, "@A hard prayer passes through the ranks as the duel begins.", faith_color),
   (try_end),
   (try_begin),
     (troop_is_hero, ":troop_no"),
     (str_store_troop_name, s3, ":troop_no"),
     (display_message, "@{s3}'s name carries weight across the field.", 0xFFD27A),
   (try_end),
 ]),
]
