# COST: moderate
SCRIPTS = [
("ponavosa_duel_explain_challenge",
 [
   (get_player_agent_no, ":player_agent"),
   (try_begin),
     (lt, ":player_agent", 0),
     (display_message, "@You cannot issue a commander challenge from here.", 0xFFD27A),
   (else_try),
     (neg|agent_is_alive, ":player_agent"),
     (display_message, "@You are in no state to challenge an enemy commander.", 0xFFD27A),
   (else_try),
     (store_agent_hit_points, ":player_hp", ":player_agent"),
     (le, ":player_hp", 50),
     (display_message, "@You are too wounded to force a commander duel.", 0xFFD27A),
   (else_try),
     (agent_get_position, pos1, ":player_agent"),
     (assign, ":nearby_allies", 0),
     (try_for_agents, ":near_agent"),
       (agent_is_alive, ":near_agent"),
       (agent_is_human, ":near_agent"),
       (agent_is_ally, ":near_agent"),
       (neq, ":near_agent", ":player_agent"),
       (agent_get_position, pos3, ":near_agent"),
       (get_distance_between_positions, ":ally_dist", pos1, pos3),
       (lt, ":ally_dist", 1400),
       (val_add, ":nearby_allies", 1),
     (try_end),
     (gt, ":nearby_allies", 5),
     (display_message, "@Step out from your line to make the challenge heard.", 0xFFD27A),
   (else_try),
     (assign, ":nearest_enemy_commander", -1),
     (assign, ":nearest_dist", 999999),
     (try_for_agents, ":enemy_agent"),
       (agent_is_alive, ":enemy_agent"),
       (agent_is_human, ":enemy_agent"),
       (neg|agent_is_ally, ":enemy_agent"),
       (agent_get_troop_id, ":enemy_troop", ":enemy_agent"),
       (call_script, "script_ponavosa_duel_is_commander", ":enemy_troop"),
       (eq, reg0, 1),
       (agent_get_position, pos2, ":enemy_agent"),
       (get_distance_between_positions, ":dist", pos1, pos2),
       (lt, ":dist", ":nearest_dist"),
       (assign, ":nearest_dist", ":dist"),
       (assign, ":nearest_enemy_commander", ":enemy_agent"),
     (try_end),
     (try_begin),
       (lt, ":nearest_enemy_commander", 0),
       (display_message, "@No enemy commander can hear your challenge.", 0xFFD27A),
     (else_try),
       (lt, ":nearest_dist", 700),
       (display_message, "@There is no room for a formal duel. Back off and call them out.", 0xFFD27A),
     (else_try),
       (gt, ":nearest_dist", 2200),
       (display_message, "@Move closer to the enemy commander before issuing a challenge.", 0xFFD27A),
     (else_try),
       (store_agent_hit_points, ":enemy_hp", ":nearest_enemy_commander"),
       (le, ":enemy_hp", 50),
       (display_message, "@The enemy commander is too battered to answer a formal challenge.", 0xFFD27A),
     (else_try),
       (agent_get_position, pos2, ":nearest_enemy_commander"),
       (assign, ":nearby_enemy_support", 0),
       (try_for_agents, ":near_enemy"),
         (agent_is_alive, ":near_enemy"),
         (agent_is_human, ":near_enemy"),
         (neg|agent_is_ally, ":near_enemy"),
         (neq, ":near_enemy", ":nearest_enemy_commander"),
         (agent_get_position, pos3, ":near_enemy"),
         (get_distance_between_positions, ":enemy_support_dist", pos2, pos3),
         (lt, ":enemy_support_dist", 1400),
         (val_add, ":nearby_enemy_support", 1),
       (try_end),
       (gt, ":nearby_enemy_support", 7),
       (display_message, "@The enemy commander is still shielded by too many troops.", 0xFFD27A),
     (else_try),
       (display_message, "@Find open ground between the lines before issuing the challenge.", 0xFFD27A),
     (try_end),
   (try_end),
 ]),
]
