# COST: moderate
SCRIPTS = [
("ponavosa_duel_begin",
 [
   (store_script_param_1, ":ally_agent"),
   (store_script_param_2, ":enemy_agent"),
   (assign, "$ponavosa_duel_active", 1),
   (assign, "$ponavosa_duel_ally_agent", ":ally_agent"),
   (assign, "$ponavosa_duel_enemy_agent", ":enemy_agent"),
   (agent_get_team, "$ponavosa_duel_ally_team", ":ally_agent"),
   (agent_get_team, "$ponavosa_duel_enemy_team", ":enemy_agent"),
   (store_mission_timer_a, "$ponavosa_duel_start_time"),
   (assign, "$ponavosa_duel_camera_active", 0),
   (get_player_agent_no, ":player_agent"),
   (assign, "$ponavosa_duel_player_involved", 0),
   (try_begin),
     (this_or_next|eq, ":ally_agent", ":player_agent"),
     (eq, ":enemy_agent", ":player_agent"),
     (assign, "$ponavosa_duel_player_involved", 1),
   (try_end),
   (agent_set_team, ":ally_agent", 6),
   (agent_set_team, ":enemy_agent", 7),
   (try_for_range, ":team", 0, 6),
     (team_set_relation, ":team", 6, 0),
     (team_set_relation, ":team", 7, 0),
   (try_end),
   (team_set_relation, 6, 7, -1),
   (team_set_relation, 7, 6, -1),
   (agent_get_position, pos1, ":ally_agent"),
   (agent_get_position, pos2, ":enemy_agent"),
   (position_get_x, ":x1", pos1),
   (position_get_y, ":y1", pos1),
   (position_get_x, ":x2", pos2),
   (position_get_y, ":y2", pos2),
   (store_add, ":mx", ":x1", ":x2"),
   (store_add, ":my", ":y1", ":y2"),
   (val_div, ":mx", 2),
   (val_div, ":my", 2),
   (position_set_x, pos3, ":mx"),
   (position_set_y, pos3, ":my"),
   (agent_set_scripted_destination, ":ally_agent", pos3, 1),
   (agent_set_scripted_destination, ":enemy_agent", pos3, 1),
   (call_script, "script_ponavosa_duel_apply_commander_aura", ":ally_agent"),
   (call_script, "script_ponavosa_duel_apply_commander_aura", ":enemy_agent"),
   (agent_get_troop_id, ":ally_troop", ":ally_agent"),
   (agent_get_troop_id, ":enemy_troop", ":enemy_agent"),
   (str_store_troop_name, s1, ":ally_troop"),
   (str_store_troop_name, s2, ":enemy_troop"),
   (display_message, "@A commander duel begins: {s1} faces {s2}!", 0xFFD27A),
   (agent_get_wielded_item, ":ally_weapon", ":ally_agent", 0),
   (try_begin),
     (gt, ":ally_weapon", 0),
     (item_get_slot, ":flags", ":ally_weapon", slot_item_artifact_flags),
     (store_and, ":is_artifact", ":flags", artifact_flag_weapon),
     (gt, ":is_artifact", 0),
     (str_store_item_name, s3, ":ally_weapon"),
     (display_message, "@{s1} carries {s3}, a weapon with royal provenance.", 0xD6B15E),
   (try_end),
   (agent_get_wielded_item, ":enemy_weapon", ":enemy_agent", 0),
   (try_begin),
     (gt, ":enemy_weapon", 0),
     (item_get_slot, ":flags", ":enemy_weapon", slot_item_artifact_flags),
     (store_and, ":is_artifact", ":flags", artifact_flag_weapon),
     (gt, ":is_artifact", 0),
     (str_store_item_name, s3, ":enemy_weapon"),
     (display_message, "@{s2} answers with {s3}; the duel becomes a matter for chronicles.", 0xD6B15E),
   (try_end),
   (start_presentation, "prsnt_ponavosa_commander_duel"),
 ]),
]
