SCRIPTS = [
("print_wpn_upgrades_to_s0",
                      [
                        (store_script_param_1, ":troop"),

                        (str_store_string, s0, "str_empty_string"),
                        (troop_get_slot, ":upg", ":troop", slot_troop_upgrade_wpn_0),
                        (troop_get_inventory_slot, ":item", ":troop", 0),
                        (try_begin),
                          (ge, ":item", 0),
                          (str_store_item_name, s10, ":item"),
                        (else_try),
                          (str_store_string, s10, "str_none"),
                        (try_end),
                        (val_add, ":upg", "str_hero_wpn_slot_none"),
                        (str_store_string, s1, ":upg"),
                        (str_store_string_reg, s68, s0),
                        (str_store_string, s0, "@{s68}^{s1}"),
                        (troop_get_slot, ":upg", ":troop", slot_troop_upgrade_wpn_1),
                        (troop_get_inventory_slot, ":item", ":troop", 1),
                        (try_begin),
                          (ge, ":item", 0),
                          (str_store_item_name, s10, ":item"),
                        (else_try),
                          (str_store_string, s10, "str_none"),
                        (try_end),
                        (val_add, ":upg", "str_hero_wpn_slot_none"),
                        (str_store_string, s1, ":upg"),
                        (str_store_string_reg, s68, s0),
                        (str_store_string, s0, "@{s68}^{s1}"),
                        (troop_get_slot, ":upg", ":troop", slot_troop_upgrade_wpn_2),
                        (troop_get_inventory_slot, ":item", ":troop", 2),
                        (try_begin),
                          (ge, ":item", 0),
                          (str_store_item_name, s10, ":item"),
                        (else_try),
                          (str_store_string, s10, "str_none"),
                        (try_end),
                        (val_add, ":upg", "str_hero_wpn_slot_none"),
                        (str_store_string, s1, ":upg"),
                        (str_store_string_reg, s68, s0),
                        (str_store_string, s0, "@{s68}^{s1}"),
                        (troop_get_slot, ":upg", ":troop", slot_troop_upgrade_wpn_3),
                        (troop_get_inventory_slot, ":item", ":troop", 3),
                        (try_begin),
                          (ge, ":item", 0),
                          (str_store_item_name, s10, ":item"),
                        (else_try),
                          (str_store_string, s10, "str_none"),
                        (try_end),
                        (val_add, ":upg", "str_hero_wpn_slot_none"),
                        (str_store_string, s1, ":upg"),
                        (str_store_string_reg, s68, s0),
                        (str_store_string, s0, "@{s68}^{s1}"),
                      ]
                    ),
]
