# COST: low
SCRIPTS = [
("sod_merc_lord_note_battle_outcome",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":outcome"),

   (try_begin),
     (party_is_active, ":party_no"),
     (party_get_slot, ":party_type", ":party_no", slot_party_type),
     (this_or_next|eq, ":party_type", spt_ai_mercenaries),
     (this_or_next|eq, ":party_type", spt_player_mercenaries),
     (eq, ":party_type", spt_mercenary_lord_party),
     (party_get_slot, ":guild_faction", ":party_no", slot_party_sod_merc_contract_guild),
     (try_begin),
       (neg|is_between, ":guild_faction", guilds_begin, guilds_end),
       (party_get_slot, ":guild_faction", ":party_no", slot_party_orginal_faction),
     (try_end),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (faction_get_slot, ":manpower", ":guild_faction", slot_faction_sod_merc_manpower),
     (faction_get_slot, ":veterans", ":guild_faction", slot_faction_sod_merc_veterans),
     (faction_get_slot, ":market_reputation", ":guild_faction", slot_faction_sod_merc_market_reputation),
     (faction_get_slot, ":treasury", ":guild_faction", slot_faction_sod_merc_treasury),
     (party_get_slot, ":initial_size", ":party_no", slot_party_sod_merc_contract_initial_size),
     (party_get_num_companions, ":current_size", ":party_no"),
     (store_sub, ":losses", ":initial_size", ":current_size"),
     (val_max, ":losses", 0),
     (try_begin),
       (lt, ":outcome", 0),
       (store_div, ":manpower_loss", ":losses", 2),
       (val_add, ":manpower_loss", 8),
       (store_div, ":veteran_loss", ":losses", 8),
       (val_add, ":veteran_loss", 1),
       (val_sub, ":manpower", ":manpower_loss"),
       (val_sub, ":veterans", ":veteran_loss"),
       (val_sub, ":market_reputation", 3),
       (store_mul, ":treasury_loss", ":veteran_loss", 75),
       (val_sub, ":treasury", ":treasury_loss"),
       (party_set_slot, ":party_no", slot_party_sod_merc_contract_loss_score, ":losses"),
     (else_try),
       (gt, ":outcome", 0),
       (party_get_slot, ":contract_value", ":party_no", slot_party_sod_merc_contract_value),
       (store_div, ":reputation_gain", ":contract_value", 1500),
       (val_clamp, ":reputation_gain", 1, 4),
       (val_add, ":market_reputation", ":reputation_gain"),
       (store_div, ":veteran_gain", ":current_size", 30),
       (val_add, ":veterans", ":veteran_gain"),
     (try_end),
     (val_clamp, ":manpower", 0, 1000),
     (val_clamp, ":veterans", 0, 500),
     (val_clamp, ":market_reputation", 0, 100),
     (val_clamp, ":treasury", 0, 1000000),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_manpower, ":manpower"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_veterans, ":veterans"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_market_reputation, ":market_reputation"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_treasury, ":treasury"),
     (call_script, "script_sod_merc_market_apply_guardrails", ":guild_faction"),
   (try_end),
 ]),
]
