# COST: trivial
SCRIPTS = [
("sod_threat_board_describe_center_stakes",
 [
   (store_script_param_1, ":center_no"),
   (try_begin),
     (neg|is_between, ":center_no", centers_begin, centers_end),
     (assign, reg(11), 0),
     (assign, reg(12), 0),
     (assign, reg(13), 0),
     (assign, reg(14), 0),
     (assign, reg(15), 0),
     (assign, reg(16), 0),
     (assign, reg(17), 0),
     (assign, reg(18), 0),
     (assign, reg(19), 0),
     (assign, reg(20), 0),
     (assign, reg(21), 0),
     (assign, reg(22), 0),
     (str_store_string, s8, "@No valid center selected."),
   (else_try),

   (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
   (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
   (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
   (party_get_slot, ":local_prosperity", ":center_no", slot_center_sod_local_prosperity),
   (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
   (call_script, "script_sod_get_center_security_profile", ":center_no"),
   (assign, ":effective_threat", reg0),
   (assign, ":security", reg1),
   (assign, ":raid_resistance", reg3),
   (assign, ":patrol_response", reg7),
   (assign, ":unrest_pressure", reg8),
   (assign, ":vulnerability", reg10),
   (assign, ":cattle", 0),
   (try_begin),
     (party_slot_eq, ":center_no", slot_party_type, spt_village),
     (party_get_slot, ":cattle", ":center_no", slot_village_number_of_cattle),
   (try_end),

    (assign, reg(11), ":population"),
    (assign, reg(12), ":health"),
    (assign, reg(13), ":prosperity"),
    (assign, reg(14), ":local_prosperity"),
    (assign, reg(15), ":wealth"),
    (assign, reg(16), ":cattle"),
    (assign, reg(17), ":security"),
    (assign, reg(18), ":effective_threat"),
    (assign, reg(19), ":raid_resistance"),
    (assign, reg(20), ":patrol_response"),
    (assign, reg(21), ":unrest_pressure"),
    (assign, reg(22), ":vulnerability"),

   (try_begin),
     (lt, ":population", 250),
     (str_store_string, s9, "@a small settlement"),
   (else_try),
     (lt, ":population", 700),
     (str_store_string, s9, "@a modest settlement"),
   (else_try),
     (str_store_string, s9, "@a crowded settlement"),
   (try_end),

   (try_begin),
     (lt, ":wealth", 250),
     (str_store_string, s10, "@little coin"),
   (else_try),
     (lt, ":wealth", 700),
     (str_store_string, s10, "@some coin and stores"),
   (else_try),
     (str_store_string, s10, "@valuable stores"),
   (try_end),

   (try_begin),
     (gt, ":effective_threat", ":security"),
     (str_store_string, s11, "@the local watch is being outpaced"),
   (else_try),
     (gt, ":vulnerability", 60),
     (str_store_string, s11, "@the place would suffer badly if raiders came"),
   (else_try),
     (gt, ":patrol_response", 60),
     (str_store_string, s11, "@nearby patrols should answer quickly"),
   (else_try),
     (str_store_string, s11, "@the road danger is present but not overwhelming"),
   (try_end),

   (try_begin),
     (party_slot_eq, ":center_no", slot_party_type, spt_village),
     (try_begin),
       (gt, ":cattle", 30),
       (str_store_string, s12, "@with herds worth protecting"),
     (else_try),
       (str_store_string, s12, "@with few herds to spare"),
     (try_end),
     (str_store_string, s8, "@Local stakes: {s9} with {s10}, {s12}. {s11}."),
   (else_try),
     (str_store_string, s8, "@Local stakes: {s9} with {s10}. {s11}."),
   (try_end),
   (try_end),
 ]),
]
