# COST: low
SCRIPTS = [
("sod_threat_board_describe_offer",
 [
   (store_script_param_1, ":offer_index"),

   (assign, ":slot_no", slot_quest_sod_threat_offer_1),
   (try_begin),
     (eq, ":offer_index", 2),
     (assign, ":slot_no", slot_quest_sod_threat_offer_2),
   (else_try),
     (eq, ":offer_index", 3),
     (assign, ":slot_no", slot_quest_sod_threat_offer_3),
   (try_end),
   (quest_get_slot, ":archetype", "qst_regional_threat_contract", ":slot_no"),
   (call_script, "script_sod_threat_board_get_archetype", ":archetype"),
    (assign, ":tier", reg(1)),
    (assign, ":deadline", reg(3)),

   (call_script, "script_sod_threat_board_calculate_reward", ":archetype"),
    (assign, ":gold", reg(0)),
    (assign, ":xp", reg(1)),
    (assign, reg(1), ":tier"),
    (assign, reg(2), ":gold"),
    (assign, reg(3), ":deadline"),
    (assign, reg(4), ":xp"),

   (try_begin),
     (eq, ":archetype", sod_threat_archetype_river_pirates),
     (str_store_string, s1, "@River pirates - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_coastal_smugglers),
     (str_store_string, s1, "@Coastal smugglers - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_army_deserters),
     (str_store_string, s1, "@Army deserters - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_noble_deserters),
     (str_store_string, s1, "@Noble deserters - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_relic_thieves),
     (str_store_string, s1, "@Relic thieves - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_tomb_robbers),
     (str_store_string, s1, "@Tomb robbers - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_rogue_company),
     (str_store_string, s1, "@Rogue company - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_guild_traitors),
     (str_store_string, s1, "@Guild traitors - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_cattle_raiders),
     (str_store_string, s1, "@Cattle raiders - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_herd_rustlers),
     (str_store_string, s1, "@Herd rustlers - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_invader_scouts),
     (str_store_string, s1, "@Invader scouts - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (else_try),
     (str_store_string, s1, "@Raiding captain - T{reg1}, {reg2} denars, {reg4} XP, {reg3} days."),
   (try_end),
 ]),
]
