# COST: medium
SCRIPTS = [
("sod_tax_courier_center_has_remittance_building",
 [
   (store_script_param_1, ":center_no"),
   (assign, reg0, 0),
   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),
     (try_begin),
       (party_slot_eq, ":center_no", slot_center_has_messenger_post, 1),
       (assign, reg0, 1),
     (else_try),
       (party_slot_eq, ":center_no", slot_party_type, spt_village),
       (this_or_next|party_slot_eq, ":center_no", slot_center_has_manor, 1),
       (party_slot_eq, ":center_no", slot_center_has_monastery, 1),
       (assign, reg0, 1),
     (else_try),
       (party_slot_eq, ":center_no", slot_party_type, spt_town),
       (this_or_next|party_slot_eq, ":center_no", slot_center_has_guild, 1),
       (party_slot_eq, ":center_no", slot_center_has_bank, 1),
       (assign, reg0, 1),
     (else_try),
       (party_slot_eq, ":center_no", slot_party_type, spt_castle),
       (party_slot_eq, ":center_no", slot_center_has_chapter, 1),
       (assign, reg0, 1),
     (try_end),
   (try_end),
 ]),

("cf_sod_tax_courier_origin_safe_to_dispatch",
 [
   (store_script_param_1, ":origin_center"),

   (is_between, ":origin_center", centers_begin, centers_end),
   (party_slot_eq, ":origin_center", slot_center_is_besieged_by, -1),

   (try_begin),
     (party_slot_eq, ":origin_center", slot_party_type, spt_village),
     (neg|party_slot_eq, ":origin_center", slot_village_state, svs_being_raided),
     (neg|party_slot_eq, ":origin_center", slot_village_state, svs_looted),
   (try_end),

   (store_faction_of_party, ":origin_faction", ":origin_center"),
   (assign, ":danger_radius", 5),
   (try_begin),
     (this_or_next|party_slot_eq, ":origin_center", slot_center_has_messenger_post, 1),
     (party_slot_eq, ":origin_center", slot_center_has_watch_tower, 1),
     (assign, ":danger_radius", 4),
   (else_try),
     (party_slot_eq, ":origin_center", slot_center_has_stables, 1),
     (assign, ":danger_radius", 4),
   (else_try),
     (neg|party_slot_eq, ":origin_center", slot_center_has_messenger_post, 1),
     (neg|party_slot_eq, ":origin_center", slot_center_has_watch_tower, 1),
     (neg|party_slot_eq, ":origin_center", slot_center_has_stables, 1),
     (assign, ":danger_radius", 7),
   (try_end),

   (assign, ":blocked", 0),
   (try_for_parties, ":party_no"),
     (eq, ":blocked", 0),
     (party_is_active, ":party_no"),
     (neg|is_between, ":party_no", centers_begin, centers_end),
     (neq, ":party_no", "p_main_party"),
     (store_faction_of_party, ":party_faction", ":party_no"),
     (store_relation, ":relation", ":origin_faction", ":party_faction"),
     (lt, ":relation", 0),
     (store_distance_to_party_from_party, ":distance", ":origin_center", ":party_no"),
     (le, ":distance", ":danger_radius"),
     (assign, ":blocked", 1),
   (try_end),
   (eq, ":blocked", 0),
 ]),

("cf_sod_tax_courier_destination_safe",
 [
   (store_script_param_1, ":destination"),

   (gt, ":destination", 0),
   (party_is_active, ":destination"),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (party_slot_eq, ":destination", slot_center_is_besieged_by, -1),
     (try_begin),
       (party_slot_eq, ":destination", slot_party_type, spt_village),
       (neg|party_slot_eq, ":destination", slot_village_state, svs_being_raided),
       (neg|party_slot_eq, ":destination", slot_village_state, svs_looted),
     (try_end),
   (try_end),
 ]),

("sod_tax_courier_resolve_destination",
 [
   (store_script_param_1, ":origin_center"),
   (store_script_param_2, ":recipient_lord"),
   (assign, reg0, -1),

   (try_begin),
     (eq, ":recipient_lord", "trp_player"),
     (assign, reg0, "p_main_party"),
   (else_try),
     (is_between, ":recipient_lord", kingdom_heroes_begin, kingdom_heroes_end),
     (troop_get_slot, ":lord_party", ":recipient_lord", slot_troop_leaded_party),
     (gt, ":lord_party", 0),
     (party_is_active, ":lord_party"),
     (assign, reg0, ":lord_party"),
   (else_try),
     (troop_get_slot, ":cur_center", ":recipient_lord", slot_troop_cur_center),
     (is_between, ":cur_center", centers_begin, centers_end),
     (party_slot_eq, ":cur_center", slot_center_is_besieged_by, -1),
     (assign, reg0, ":cur_center"),
   (else_try),
     (is_between, ":origin_center", centers_begin, centers_end),
     (store_faction_of_party, ":lord_faction", ":origin_center"),
     (assign, ":best_center", -1),
     (assign, ":best_distance", 999999),
     (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
       (party_slot_eq, ":center_no", slot_town_lord, ":recipient_lord"),
       (party_slot_eq, ":center_no", slot_center_is_besieged_by, -1),
       (store_faction_of_party, ":center_faction", ":center_no"),
       (eq, ":center_faction", ":lord_faction"),
       (store_distance_to_party_from_party, ":distance", ":origin_center", ":center_no"),
       (lt, ":distance", ":best_distance"),
       (assign, ":best_distance", ":distance"),
       (assign, ":best_center", ":center_no"),
     (try_end),
     (assign, reg0, ":best_center"),
   (try_end),
 ]),

("cf_sod_create_tax_courier",
 [
   (store_script_param_1, ":origin_center"),
   (store_script_param_2, ":recipient_lord"),
   (store_script_param, ":destination", 3),
   (store_script_param, ":payload", 4),
   (store_script_param, ":rents_component", 5),
   (store_script_param, ":tariffs_component", 6),

   (assign, reg0, -1),
   (is_between, ":origin_center", centers_begin, centers_end),
   (this_or_next|eq, ":recipient_lord", "trp_player"),
   (is_between, ":recipient_lord", kingdom_heroes_begin, kingdom_heroes_end),
   (gt, ":destination", 0),
   (party_is_active, ":destination"),
   (call_script, "script_cf_sod_tax_courier_destination_safe", ":destination"),
   (gt, ":payload", 0),
   (party_slot_eq, ":origin_center", slot_center_sod_active_tax_courier, 0),

   (store_faction_of_party, ":origin_faction", ":origin_center"),
   (faction_get_slot, ":messenger_troop", ":origin_faction", slot_faction_messenger_troop),
   (try_begin),
     (le, ":messenger_troop", 0),
     (assign, ":messenger_troop", "trp_swadian_messenger"),
   (try_end),

   (set_spawn_radius, 1),
   (spawn_around_party, ":origin_center", "pt_messenger_party"),
   (assign, ":courier_party", reg0),
   (gt, ":courier_party", 0),
   (party_is_active, ":courier_party"),

   (party_set_faction, ":courier_party", ":origin_faction"),
   (party_set_slot, ":courier_party", slot_party_type, spt_messenger),
   (party_set_slot, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_origin_center, ":origin_center"),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_recipient_troop, ":recipient_lord"),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_destination_party, ":destination"),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_amount, ":payload"),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_rents, ":rents_component"),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_tariffs, ":tariffs_component"),
   (store_current_day, ":cur_day"),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_created_day, ":cur_day"),
   (store_add, ":expiry_day", ":cur_day", 10),
   (try_begin),
     (party_slot_eq, ":origin_center", slot_center_has_messenger_post, 1),
     (val_add, ":expiry_day", 2),
   (try_end),
   (try_begin),
     (party_slot_eq, ":origin_center", slot_center_has_stables, 1),
     (val_add, ":expiry_day", 1),
   (try_end),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_expiry_day, ":expiry_day"),
   (party_set_slot, ":courier_party", slot_party_sod_tax_courier_status, sod_tax_courier_status_traveling),

   (party_add_leader, ":courier_party", ":messenger_troop"),
   (try_begin),
     (this_or_next|party_slot_eq, ":origin_center", slot_party_type, spt_town),
     (party_slot_eq, ":origin_center", slot_party_type, spt_castle),
     (party_slot_eq, ":origin_center", slot_center_has_messenger_post, 1),
     (party_add_members, ":courier_party", ":messenger_troop", 1),
   (try_end),
   (try_begin),
     (party_slot_eq, ":origin_center", slot_center_has_stables, 1),
     (party_add_members, ":courier_party", ":messenger_troop", 1),
   (try_end),

   (try_begin),
     (eq, ":recipient_lord", "trp_player"),
     (str_store_party_name, s68, ":origin_center"),
     (str_store_string, s69, "@Your Tax Courier from {s68}"),
   (else_try),
     (str_store_party_name, s68, ":origin_center"),
     (str_store_string, s69, "@Tax Courier from {s68}"),
   (try_end),
   (party_set_name, ":courier_party", s69),
   (party_set_ai_behavior, ":courier_party", ai_bhvr_travel_to_party),
   (party_set_ai_object, ":courier_party", ":destination"),
   (party_set_flags, ":courier_party", pf_default_behavior, 0),
   (party_set_slot, ":origin_center", slot_center_sod_active_tax_courier, ":courier_party"),
   (party_set_slot, ":origin_center", slot_center_sod_last_tax_courier_day, ":cur_day"),

   (assign, reg0, ":courier_party"),
 ]),

("sod_tax_courier_cleanup_party",
 [
   (store_script_param_1, ":courier_party"),
   (try_begin),
     (gt, ":courier_party", 0),
     (neq, ":courier_party", "p_main_party"),
     (party_is_active, ":courier_party"),
     (try_begin),
       (party_slot_eq, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
       (party_get_slot, ":origin_center", ":courier_party", slot_party_sod_tax_courier_origin_center),
       (try_begin),
         (is_between, ":origin_center", centers_begin, centers_end),
         (party_slot_eq, ":origin_center", slot_center_sod_active_tax_courier, ":courier_party"),
         (party_set_slot, ":origin_center", slot_center_sod_active_tax_courier, 0),
       (try_end),
       (party_set_slot, ":courier_party", slot_party_sod_tax_courier_amount, 0),
       (party_set_slot, ":courier_party", slot_party_sod_tax_courier_destination_party, -1),
       (party_set_slot, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_none),
     (try_end),
     (remove_party, ":courier_party"),
   (try_end),
 ]),

("sod_try_dispatch_ai_tax_courier_from_center",
 [
   (store_script_param_1, ":center_no"),
   (assign, reg0, 0),
   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),
     (party_get_slot, ":town_lord", ":center_no", slot_town_lord),
     (neq, ":town_lord", "trp_player"),
     (is_between, ":town_lord", kingdom_heroes_begin, kingdom_heroes_end),
     (party_get_slot, ":accumulated_rents", ":center_no", slot_center_accumulated_rents),
     (party_get_slot, ":accumulated_tariffs", ":center_no", slot_center_accumulated_tariffs),
     (troop_get_slot, ":troop_wealth", ":town_lord", slot_troop_wealth),

     (val_max, ":accumulated_rents", 0),
     (val_max, ":accumulated_tariffs", 0),
     (val_max, ":troop_wealth", 0),

     (assign, ":total_income", ":accumulated_rents"),
     (val_add, ":total_income", ":accumulated_tariffs"),
     (gt, ":total_income", 0),

     (assign, ":center_reserve", ":total_income"),
     (val_div, ":center_reserve", 5),
     (assign, ":lord_share", ":total_income"),
     (val_sub, ":lord_share", ":center_reserve"),
     (val_max, ":lord_share", 0),

     (assign, ":direct_share", ":lord_share"),
     (val_mul, ":direct_share", 60),
     (val_div, ":direct_share", 100),
     (assign, ":courier_share", ":lord_share"),
     (val_sub, ":courier_share", ":direct_share"),
     (val_max, ":courier_share", 0),

     (assign, ":can_send_courier", 0),
     (call_script, "script_sod_tax_courier_center_has_remittance_building", ":center_no"),
     (try_begin),
       (eq, reg0, 1),
       (assign, ":minimum_payload", 300),
       (try_begin),
         (party_slot_eq, ":center_no", slot_party_type, spt_town),
         (assign, ":minimum_payload", 800),
       (else_try),
         (party_slot_eq, ":center_no", slot_party_type, spt_castle),
         (assign, ":minimum_payload", 800),
       (try_end),
       (ge, ":courier_share", ":minimum_payload"),
       (assign, ":can_send_courier", 1),
     (try_end),

     (party_get_slot, ":active_courier", ":center_no", slot_center_sod_active_tax_courier),
     (try_begin),
       (gt, ":active_courier", 0),
       (try_begin),
         (party_is_active, ":active_courier"),
         (assign, ":can_send_courier", 0),
       (else_try),
         (party_set_slot, ":center_no", slot_center_sod_active_tax_courier, 0),
       (try_end),
     (try_end),

     (try_begin),
       (eq, ":can_send_courier", 1),
       (try_begin),
         (call_script, "script_cf_sod_tax_courier_origin_safe_to_dispatch", ":center_no"),
         (call_script, "script_sod_tax_courier_resolve_destination", ":center_no", ":town_lord"),
         (assign, ":destination", reg0),
         (gt, ":destination", 0),
         (party_is_active, ":destination"),
         (call_script, "script_cf_sod_tax_courier_destination_safe", ":destination"),
         (assign, ":rents_component", ":courier_share"),
         (val_min, ":rents_component", ":accumulated_rents"),
         (assign, ":tariffs_component", ":courier_share"),
         (val_sub, ":tariffs_component", ":rents_component"),
         (val_max, ":tariffs_component", 0),
         (call_script, "script_cf_sod_create_tax_courier", ":center_no", ":town_lord", ":destination", ":courier_share", ":rents_component", ":tariffs_component"),
         (val_add, ":troop_wealth", ":direct_share"),
         (val_min, ":troop_wealth", 2000000),
         (troop_set_slot, ":town_lord", slot_troop_wealth, ":troop_wealth"),
         (call_script, "script_sod_change_center_wealth", ":center_no", ":center_reserve"),
         (call_script, "script_sod_center_clear_revenue_accounts", ":center_no"),
         (assign, reg0, 1),
         (try_begin),
           (eq, "$g_sod_debug", 1),
           (str_store_party_name, s1, ":center_no"),
           (call_script, "script_store_troop_name", s2, ":town_lord"),
           (str_store_party_name, s3, ":destination"),
           (assign, reg1, ":courier_share"),
           (display_message, "@tax_courier: leaves {s1} carrying {reg1} denars for {s2}; destination {s3}.", debug_color),
         (try_end),
       (else_try),
         (assign, ":can_send_courier", 0),
       (try_end),
     (try_end),

     (try_begin),
       (eq, ":can_send_courier", 0),
       (val_add, ":troop_wealth", ":lord_share"),
       (val_min, ":troop_wealth", 2000000),
       (troop_set_slot, ":town_lord", slot_troop_wealth, ":troop_wealth"),
       (call_script, "script_sod_change_center_wealth", ":center_no", ":center_reserve"),
       (call_script, "script_sod_center_clear_revenue_accounts", ":center_no"),
       (assign, reg0, 0),
     (try_end),
   (try_end),
 ]),

("sod_try_dispatch_player_tax_courier_from_center",
 [
   (store_script_param_1, ":center_no"),
   (assign, reg0, 0),
   (try_begin),
     (eq, "$g_sod_player_tax_couriers_enabled", 1),
     (is_between, ":center_no", centers_begin, centers_end),
     (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
     (party_get_slot, ":accumulated_rents", ":center_no", slot_center_accumulated_rents),
     (party_get_slot, ":accumulated_tariffs", ":center_no", slot_center_accumulated_tariffs),
     (val_max, ":accumulated_rents", 0),
     (val_max, ":accumulated_tariffs", 0),
     (assign, ":payload", ":accumulated_rents"),
     (val_add, ":payload", ":accumulated_tariffs"),
     (gt, ":payload", 0),

     (call_script, "script_sod_tax_courier_center_has_remittance_building", ":center_no"),
     (eq, reg0, 1),
     (assign, ":minimum_payload", 300),
     (try_begin),
       (party_slot_eq, ":center_no", slot_party_type, spt_town),
       (assign, ":minimum_payload", 800),
     (else_try),
       (party_slot_eq, ":center_no", slot_party_type, spt_castle),
       (assign, ":minimum_payload", 800),
     (try_end),
     (ge, ":payload", ":minimum_payload"),

     (party_get_slot, ":active_courier", ":center_no", slot_center_sod_active_tax_courier),
     (try_begin),
       (gt, ":active_courier", 0),
       (try_begin),
         (party_is_active, ":active_courier"),
         (assign, ":active_courier", -1),
       (else_try),
         (party_set_slot, ":center_no", slot_center_sod_active_tax_courier, 0),
         (assign, ":active_courier", 0),
       (try_end),
     (try_end),
     (eq, ":active_courier", 0),

     (call_script, "script_cf_sod_tax_courier_origin_safe_to_dispatch", ":center_no"),
     (call_script, "script_sod_tax_courier_resolve_destination", ":center_no", "trp_player"),
     (assign, ":destination", reg0),
     (gt, ":destination", 0),
     (party_is_active, ":destination"),
     (call_script, "script_cf_sod_tax_courier_destination_safe", ":destination"),
      (call_script, "script_cf_sod_create_tax_courier", ":center_no", "trp_player", ":destination", ":payload", ":accumulated_rents", ":accumulated_tariffs"),
      (gt, reg0, 0),
      (call_script, "script_sod_center_clear_revenue_accounts", ":center_no"),
      (call_script, "script_sod_report_record_event", sod_report_category_roads, sod_report_severity_notable, sod_report_subject_center, ":center_no", sod_report_subject_party, ":destination", ":payload", sod_report_reason_tax_departure),
      (assign, reg0, 1),
   (try_end),
 ]),

("sod_process_tax_courier_parties",
 [
   (store_current_day, ":cur_day"),
   (try_for_parties, ":courier_party"),
     (try_begin),
       (party_is_active, ":courier_party"),
       (party_slot_eq, ":courier_party", slot_party_type, spt_messenger),
       (party_slot_eq, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
       (party_get_slot, ":origin_center", ":courier_party", slot_party_sod_tax_courier_origin_center),
       (party_get_slot, ":recipient_lord", ":courier_party", slot_party_sod_tax_courier_recipient_troop),
       (party_get_slot, ":destination", ":courier_party", slot_party_sod_tax_courier_destination_party),
       (party_get_slot, ":payload", ":courier_party", slot_party_sod_tax_courier_amount),
       (party_get_slot, ":created_day", ":courier_party", slot_party_sod_tax_courier_created_day),
       (party_get_slot, ":expiry_day", ":courier_party", slot_party_sod_tax_courier_expiry_day),
       (gt, ":payload", 0),
       (ge, ":created_day", 0),
       (is_between, ":origin_center", centers_begin, centers_end),
       (this_or_next|eq, ":recipient_lord", "trp_player"),
       (is_between, ":recipient_lord", kingdom_heroes_begin, kingdom_heroes_end),
       (assign, ":delivered", 0),
       (assign, ":expired", 0),
       (try_begin),
         (gt, ":destination", 0),
         (party_is_active, ":destination"),
         (store_distance_to_party_from_party, ":distance", ":courier_party", ":destination"),
         (lt, ":distance", 3),
         (assign, ":delivered", 1),
       (else_try),
         (ge, ":cur_day", ":expiry_day"),
         (assign, ":expired", 1),
       (else_try),
         (assign, ":destination_invalid", 0),
         (try_begin),
           (le, ":destination", 0),
           (assign, ":destination_invalid", 1),
         (else_try),
           (neg|party_is_active, ":destination"),
           (assign, ":destination_invalid", 1),
         (try_end),
         (eq, ":destination_invalid", 1),
         (call_script, "script_sod_tax_courier_resolve_destination", ":origin_center", ":recipient_lord"),
         (assign, ":new_destination", reg0),
         (try_begin),
           (gt, ":new_destination", 0),
           (party_is_active, ":new_destination"),
           (call_script, "script_cf_sod_tax_courier_destination_safe", ":new_destination"),
           (party_set_slot, ":courier_party", slot_party_sod_tax_courier_destination_party, ":new_destination"),
           (party_set_ai_behavior, ":courier_party", ai_bhvr_travel_to_party),
           (party_set_ai_object, ":courier_party", ":new_destination"),
           (try_begin),
             (eq, "$g_sod_debug", 1),
             (call_script, "script_store_troop_name", s2, ":recipient_lord"),
             (str_store_party_name, s3, ":new_destination"),
             (assign, reg1, ":payload"),
             (display_message, "@tax_courier: for {s2} reroutes to {s3}; payload {reg1} denars.", debug_color),
           (try_end),
         (else_try),
           (party_set_slot, ":courier_party", slot_party_sod_tax_courier_destination_party, -1),
           (assign, ":expired", 1),
           (try_begin),
             (eq, "$g_sod_debug", 1),
             (str_store_party_name, s1, ":origin_center"),
             (call_script, "script_store_troop_name", s2, ":recipient_lord"),
             (assign, reg1, ":payload"),
             (display_message, "@tax_courier: from {s1} for {s2} has no valid destination; {reg1} denars are returned or written off.", debug_color),
           (try_end),
         (try_end),
       (try_end),

       (try_begin),
         (eq, ":delivered", 1),
          (try_begin),
            (eq, ":recipient_lord", "trp_player"),
            (call_script, "script_troop_add_gold", "trp_player", ":payload"),
            (call_script, "script_sod_report_record_event", sod_report_category_roads, sod_report_severity_notable, sod_report_subject_center, ":origin_center", sod_report_subject_none, -1, ":payload", sod_report_reason_tax_delivery),
         (else_try),
           (troop_get_slot, ":troop_wealth", ":recipient_lord", slot_troop_wealth),
           (val_max, ":troop_wealth", 0),
           (val_add, ":troop_wealth", ":payload"),
           (val_min, ":troop_wealth", 2000000),
           (troop_set_slot, ":recipient_lord", slot_troop_wealth, ":troop_wealth"),
         (try_end),
         (try_begin),
           (is_between, ":origin_center", centers_begin, centers_end),
           (party_set_slot, ":origin_center", slot_center_sod_active_tax_courier, 0),
         (try_end),
         (party_set_slot, ":courier_party", slot_party_sod_tax_courier_status, sod_tax_courier_status_delivered),
         (try_begin),
           (eq, "$g_sod_debug", 1),
           (str_store_party_name, s1, ":origin_center"),
           (call_script, "script_store_troop_name", s2, ":recipient_lord"),
           (assign, reg1, ":payload"),
           (display_message, "@tax_courier: from {s1} delivered {reg1} denars to {s2}.", debug_color),
         (try_end),
         (call_script, "script_sod_tax_courier_cleanup_party", ":courier_party"),
       (else_try),
         (eq, ":expired", 1),
         (try_begin),
           (eq, ":recipient_lord", "trp_player"),
           (assign, ":recipient_faction", "fac_player_supporters_faction"),
         (else_try),
           (store_troop_faction, ":recipient_faction", ":recipient_lord"),
         (try_end),
         (store_faction_of_party, ":origin_faction", ":origin_center"),
         (store_relation, ":origin_relation", ":origin_faction", ":recipient_faction"),
         (try_begin),
           (ge, ":origin_relation", 0),
           (party_get_slot, ":rents_component", ":courier_party", slot_party_sod_tax_courier_rents),
           (party_get_slot, ":tariffs_component", ":courier_party", slot_party_sod_tax_courier_tariffs),
           (call_script, "script_sod_center_apply_rents_delta", ":origin_center", ":rents_component"),
           (call_script, "script_sod_center_apply_tariffs_delta", ":origin_center", ":tariffs_component"),
           (try_begin),
             (eq, "$g_sod_debug", 1),
             (str_store_party_name, s1, ":origin_center"),
             (call_script, "script_store_troop_name", s2, ":recipient_lord"),
             (assign, reg1, ":payload"),
             (display_message, "@tax_courier: from {s1} expired; {reg1} denars return to the center accounts for {s2}.", debug_color),
           (try_end),
         (else_try),
           (party_get_slot, ":losses", ":origin_center", slot_center_sod_tax_courier_losses),
           (val_add, ":losses", ":payload"),
           (party_set_slot, ":origin_center", slot_center_sod_tax_courier_losses, ":losses"),
           (try_begin),
             (eq, "$g_sod_debug", 1),
             (str_store_party_name, s1, ":origin_center"),
             (assign, reg1, ":payload"),
             (display_message, "@tax_courier: from {s1} expired after hostile control changed; {reg1} denars are lost.", debug_color),
           (try_end),
         (try_end),
         (party_set_slot, ":origin_center", slot_center_sod_active_tax_courier, 0),
         (party_set_slot, ":courier_party", slot_party_sod_tax_courier_amount, 0),
         (party_set_slot, ":courier_party", slot_party_sod_tax_courier_status, sod_tax_courier_status_expired),
         (call_script, "script_sod_tax_courier_cleanup_party", ":courier_party"),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_tax_courier_resolve_defeated_by_party",
 [
   (store_script_param_1, ":courier_party"),
   (store_script_param_2, ":winner_party"),
   (assign, reg0, 0),
   (try_begin),
     (gt, ":courier_party", 0),
     (neq, ":courier_party", "p_main_party"),
     (party_is_active, ":courier_party"),
     (party_slot_eq, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
     (party_get_slot, ":payload", ":courier_party", slot_party_sod_tax_courier_amount),
     (gt, ":payload", 0),
     (party_get_slot, ":origin_center", ":courier_party", slot_party_sod_tax_courier_origin_center),
     (try_begin),
       (is_between, ":origin_center", centers_begin, centers_end),
       (party_slot_eq, ":origin_center", slot_center_sod_active_tax_courier, ":courier_party"),
       (party_set_slot, ":origin_center", slot_center_sod_active_tax_courier, 0),
     (try_end),
     (assign, ":awarded", 0),
     (try_begin),
       (gt, ":winner_party", 0),
       (party_is_active, ":winner_party"),
       (store_faction_of_party, ":winner_faction", ":winner_party"),
       (eq, ":winner_faction", "fac_player_supporters_faction"),
       (call_script, "script_sod_tax_courier_award_payload_to_player", ":courier_party", 3),
       (assign, ":awarded", reg0),
     (else_try),
       (gt, ":winner_party", 0),
       (party_is_active, ":winner_party"),
       (party_get_num_companion_stacks, ":num_stacks", ":winner_party"),
       (gt, ":num_stacks", 0),
       (party_stack_get_troop_id, ":winner_leader", ":winner_party", 0),
       (is_between, ":winner_leader", kingdom_heroes_begin, kingdom_heroes_end),
       (troop_get_slot, ":winner_wealth", ":winner_leader", slot_troop_wealth),
       (val_max, ":winner_wealth", 0),
       (val_add, ":winner_wealth", ":payload"),
       (val_min, ":winner_wealth", 2000000),
       (troop_set_slot, ":winner_leader", slot_troop_wealth, ":winner_wealth"),
       (party_set_slot, ":courier_party", slot_party_sod_tax_courier_amount, 0),
       (assign, ":awarded", ":payload"),
       (try_begin),
         (eq, "$g_sod_debug", 1),
         (try_begin),
           (is_between, ":origin_center", centers_begin, centers_end),
           (str_store_party_name, s1, ":origin_center"),
         (else_try),
           (str_store_string, s1, "@an unknown estate"),
         (try_end),
         (call_script, "script_store_troop_name", s2, ":winner_leader"),
         (assign, reg1, ":payload"),
         (display_message, "@tax_courier: {s2} captures {reg1} denars from a tax courier out of {s1}.", debug_color),
       (try_end),
     (try_end),
     (try_begin),
       (eq, ":awarded", 0),
       (party_set_slot, ":courier_party", slot_party_sod_tax_courier_amount, 0),
       (try_begin),
         (is_between, ":origin_center", centers_begin, centers_end),
         (party_get_slot, ":losses", ":origin_center", slot_center_sod_tax_courier_losses),
         (val_add, ":losses", ":payload"),
         (party_set_slot, ":origin_center", slot_center_sod_tax_courier_losses, ":losses"),
       (try_end),
       (try_begin),
         (eq, "$g_sod_debug", 1),
         (try_begin),
           (is_between, ":origin_center", centers_begin, centers_end),
           (str_store_party_name, s1, ":origin_center"),
         (else_try),
           (str_store_string, s1, "@an unknown estate"),
         (try_end),
         (assign, reg1, ":payload"),
         (display_message, "@tax_courier: from {s1} is destroyed; {reg1} denars are lost.", debug_color),
       (try_end),
     (try_end),
     (party_set_slot, ":courier_party", slot_party_sod_tax_courier_status, sod_tax_courier_status_lost),
     (assign, reg0, ":awarded"),
     (call_script, "script_sod_tax_courier_cleanup_party", ":courier_party"),
   (try_end),
 ]),

("sod_tax_courier_record_social_event",
 [
   (store_script_param_1, ":courier_party"),
   (store_script_param_2, ":event_type"),
   (store_script_param, ":payload", 3),
   (try_begin),
     (gt, ":courier_party", 0),
     (party_is_active, ":courier_party"),
     (party_slot_eq, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
     (store_current_day, ":cur_day"),
     (store_faction_of_party, ":courier_faction", ":courier_party"),
     (party_get_slot, ":origin_center", ":courier_party", slot_party_sod_tax_courier_origin_center),
     (try_begin),
       (le, ":payload", 0),
       (party_get_slot, ":payload", ":courier_party", slot_party_sod_tax_courier_amount),
     (try_end),
     (assign, "$g_sod_tax_courier_last_social_event", ":event_type"),
     (assign, "$g_sod_tax_courier_last_social_event_day", ":cur_day"),
     (assign, "$g_sod_tax_courier_last_social_event_faction", ":courier_faction"),
     (assign, "$g_sod_tax_courier_last_social_event_center", ":origin_center"),
     (assign, "$g_sod_tax_courier_last_social_event_amount", ":payload"),
     (try_begin),
       (eq, ":event_type", 1),
       (val_add, "$g_sod_tax_courier_nonhostile_coercions", 1),
     (else_try),
       (eq, ":event_type", 2),
       (val_add, "$g_sod_tax_courier_hostile_seizures", 1),
     (else_try),
       (eq, ":event_type", 3),
       (val_add, "$g_sod_tax_courier_safe_passages", 1),
     (try_end),
   (try_end),
 ]),

("sod_store_tax_courier_rumor_to_s12",
 [
   (store_script_param_1, ":speaker_kind"),
   (assign, reg0, 0),
   (try_begin),
     (gt, "$g_sod_tax_courier_last_social_event", 0),
     (store_current_day, ":cur_day"),
     (store_sub, ":age", ":cur_day", "$g_sod_tax_courier_last_social_event_day"),
     (is_between, ":age", 0, 15),
     (try_begin),
       (is_between, "$g_sod_tax_courier_last_social_event_center", centers_begin, centers_end),
       (str_store_party_name, s13, "$g_sod_tax_courier_last_social_event_center"),
     (else_try),
       (str_store_string, s13, "@a distant estate"),
     (try_end),
     (try_begin),
       (is_between, "$g_sod_tax_courier_last_social_event_faction", kingdoms_begin, kingdoms_end),
       (str_store_faction_name, s14, "$g_sod_tax_courier_last_social_event_faction"),
     (else_try),
       (str_store_string, s14, "@a lord's household"),
     (try_end),
     (assign, reg12, "$g_sod_tax_courier_last_social_event_amount"),
     (assign, reg13, "$g_sod_tax_courier_hostile_seizures"),
     (assign, reg14, "$g_sod_tax_courier_safe_passages"),
     (try_begin),
       (eq, ":speaker_kind", 1),
       (neq, "$g_sod_tax_courier_tavern_rumor_seen_day", ":cur_day"),
       (try_begin),
         (eq, "$g_sod_tax_courier_last_social_event", 1),
         (str_store_string, s12, "@The room lowers its voice around strongboxes now. They say a tax chest out of {s13} changed hands without a proper battle, and coin remembers the road better than men do."),
       (else_try),
         (eq, "$g_sod_tax_courier_last_social_event", 2),
         (str_store_string, s12, "@Someone bled a hostile tax road near {s13}. Men are calling it war work when soldiers listen, and robbery when they do not."),
       (else_try),
         (eq, "$g_sod_tax_courier_last_social_event", 3),
         (str_store_string, s12, "@A tax courier made it through from {s13} under your shadow. The sort who count coins are starting to count you as weather worth watching."),
       (try_end),
       (assign, reg0, 1),
     (else_try),
       (eq, ":speaker_kind", 2),
       (neq, "$g_sod_tax_courier_lord_rumor_seen_day", ":cur_day"),
       (try_begin),
         (eq, "$g_sod_tax_courier_last_social_event", 1),
         (str_store_string, s12, "@I have heard of the courier from {s13}. A realm does not run on frightened clerks and opened chests, {playername}. If you mean to make policy from road dust, own the cost of it."),
       (else_try),
         (eq, "$g_sod_tax_courier_last_social_event", 2),
         (str_store_string, s12, "@Your hand has been seen on hostile tax roads. Useful, perhaps. But useful men become dangerous men when they forget who names the enemy."),
       (else_try),
         (eq, "$g_sod_tax_courier_last_social_event", 3),
         (str_store_string, s12, "@I hear couriers have begun to breathe easier when your banner is near. That is not a small thing. Pay reaches soldiers before speeches do."),
       (try_end),
       (assign, reg0, 1),
     (else_try),
       (eq, ":speaker_kind", 3),
       (neq, "$g_sod_tax_courier_merchant_rumor_seen_day", ":cur_day"),
       (try_begin),
         (eq, "$g_sod_tax_courier_last_social_event", 1),
         (str_store_string, s12, "@Taxes move like blood, {sir/madam}. Stop enough of it on the road from {s13}, and even proud banners go pale. I prefer my ledgers with fewer knife marks."),
       (else_try),
         (eq, "$g_sod_tax_courier_last_social_event", 2),
         (str_store_string, s12, "@A hostile chest taken cleanly is still a chest taken. Markets respect strength, but they charge extra for uncertainty."),
       (else_try),
         (eq, "$g_sod_tax_courier_last_social_event", 3),
         (str_store_string, s12, "@A safe courier means wages paid, guards sober, and gates opened on time. Very dull. Very profitable."),
       (try_end),
       (assign, reg0, 1),
     (try_end),
   (try_end),
 ]),

("sod_tax_courier_apply_nonhostile_coercion_consequence",
 [
   (store_script_param_1, ":courier_party"),
   (assign, reg0, 0),
   (try_begin),
     (gt, ":courier_party", 0),
     (party_is_active, ":courier_party"),
     (party_slot_eq, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
     (store_faction_of_party, ":courier_faction", ":courier_party"),
     (is_between, ":courier_faction", kingdoms_begin, kingdoms_end),
     (neq, ":courier_faction", "fac_player_supporters_faction"),
     (store_relation, ":relation", ":courier_faction", "fac_player_supporters_faction"),
     (ge, ":relation", 0),
     (call_script, "script_change_player_relation_with_faction", ":courier_faction", -5),
     (call_script, "script_change_player_honor", -2),
     (call_script, "script_sod_diplomacy_record_event", ":courier_faction", sod_diplomacy_memory_caravan_attack, 1),
     (party_get_slot, ":payload", ":courier_party", slot_party_sod_tax_courier_amount),
     (call_script, "script_sod_tax_courier_record_social_event", ":courier_party", 1, ":payload"),
     (str_store_faction_name, s68, ":courier_faction"),
     (display_message, "@You have coerced a tax courier under lawful colors. Relations with {s68} suffer.", 0xFF6666),
     (assign, reg0, 1),
   (try_end),
 ]),

("sod_tax_courier_award_payload_to_player",
 [
   (store_script_param_1, ":courier_party"),
   (store_script_param_2, ":capture_mode"),
   (try_begin),
     (gt, ":courier_party", 0),
     (party_is_active, ":courier_party"),
     (party_slot_eq, ":courier_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
     (party_get_slot, ":payload", ":courier_party", slot_party_sod_tax_courier_amount),
     (gt, ":payload", 0),
     (party_get_slot, ":origin_center", ":courier_party", slot_party_sod_tax_courier_origin_center),
     (try_begin),
       (is_between, ":origin_center", centers_begin, centers_end),
       (party_slot_eq, ":origin_center", slot_center_sod_active_tax_courier, ":courier_party"),
       (party_set_slot, ":origin_center", slot_center_sod_active_tax_courier, 0),
     (try_end),
     (party_set_slot, ":courier_party", slot_party_sod_tax_courier_amount, 0),
     (party_set_slot, ":courier_party", slot_party_sod_tax_courier_status, sod_tax_courier_status_lost),
     (call_script, "script_troop_add_gold", "trp_player", ":payload"),
     (try_begin),
       (neq, ":capture_mode", 1),
       (call_script, "script_sod_tax_courier_record_social_event", ":courier_party", 2, ":payload"),
     (try_end),
     (assign, reg1, ":payload"),
     (try_begin),
       (is_between, ":origin_center", centers_begin, centers_end),
       (str_store_party_name, s68, ":origin_center"),
     (else_try),
       (str_store_string, s68, "@an unknown estate"),
     (try_end),
     (try_begin),
       (eq, ":capture_mode", 1),
       (display_message, "@The tax courier surrenders the chest from {s68}. You seize {reg1} denars.", 0xFFCC66),
     (else_try),
       (eq, ":capture_mode", 3),
       (display_message, "@Your patrol captures a hostile tax courier from {s68}. {reg1} denars are sent to your coffers.", 0xFFCC66),
     (else_try),
       (display_message, "@You seize {reg1} denars from the hostile tax courier out of {s68}.", 0xFFCC66),
     (try_end),
     (assign, reg0, ":payload"),
   (else_try),
     (assign, reg0, 0),
   (try_end),
 ]),

("sod_tax_courier_surrender_to_player",
 [
   (store_script_param_1, ":courier_party"),
   (call_script, "script_sod_tax_courier_award_payload_to_player", ":courier_party", 1),
   (try_begin),
     (gt, ":courier_party", 0),
     (party_is_active, ":courier_party"),
     (call_script, "script_sod_tax_courier_cleanup_party", ":courier_party"),
   (try_end),
   (assign, "$g_leave_encounter", 1),
 ]),
]
