# COST: medium
SCRIPTS = [
("sod_threat_board_accept_contract",
 [
  (store_script_param_1, ":offer_index"),

   (assign, ":can_accept", 1),
   (assign, ":slot_no", slot_quest_sod_threat_offer_1),
   (try_begin),
     (check_quest_active, "qst_regional_threat_contract"),
     (assign, ":can_accept", 0),
     (display_message, "@You already have an active job board contract.", 0xFFCC66),
   (else_try),
     (try_begin),
       (eq, ":offer_index", 1),
     (else_try),
       (eq, ":offer_index", 2),
       (assign, ":slot_no", slot_quest_sod_threat_offer_2),
     (else_try),
       (eq, ":offer_index", 3),
       (assign, ":slot_no", slot_quest_sod_threat_offer_3),
     (else_try),
       (assign, ":can_accept", 0),
       (display_message, "@That contract option is not available.", 0xCC4444),
     (try_end),
   (try_end),
   (try_begin),
     (eq, ":can_accept", 1),

     (quest_get_slot, ":archetype", "qst_regional_threat_contract", ":slot_no"),
      (call_script, "script_sod_threat_board_normalize_center", "$g_sod_threat_board_context_center"),
      (assign, "$g_sod_threat_board_context_center", reg0),
      (assign, ":sponsor_center", "$g_sod_threat_board_context_center"),

      (call_script, "script_sod_threat_board_get_archetype", ":archetype"),
     (assign, ":threat_type", reg(0)),
     (assign, ":tier", reg(1)),
    (assign, ":relation_reward", reg(4)),

     (store_current_day, ":cur_day"),
     (store_add, ":reward_seed", ":cur_day", ":archetype"),
      (call_script, "script_sod_threat_board_spawn_target", ":archetype", ":sponsor_center", ":reward_seed"),
     (assign, ":target_party", reg(0)),
     (assign, ":deadline_day", reg(1)),
     (assign, ":sponsor_faction", reg(2)),

     (try_begin),
       (gt, ":target_party", 0),
       (party_is_active, ":target_party"),
       (call_script, "script_sod_threat_board_calculate_reward", ":archetype"),
      (assign, ":reward_gold", reg(0)),
      (assign, ":reward_xp", reg(1)),

       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_type, ":threat_type"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_tier, ":tier"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_archetype, ":archetype"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_target_party, ":target_party"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_sponsor_center, ":sponsor_center"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_sponsor_faction, ":sponsor_faction"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_reward_gold, ":reward_gold"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_reward_relation, ":relation_reward"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_deadline_day, ":deadline_day"),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_ready_to_claim, 0),
       (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_reward_xp, ":reward_xp"),
       (str_store_party_name, s1, ":target_party"),
       (str_store_party_name, s2, ":sponsor_center"),
       (assign, reg(1), ":reward_gold"),
       (assign, reg(2), ":reward_xp"),
       (assign, reg(3), ":deadline_day"),
      (str_store_string, s5, "@Target: {s1}. Sponsor: {s2}."),
      (str_store_string, s6, "@Reward: {reg1} denars, {reg2} XP, local relation."),
      (str_store_string, s7, "@Deadline: day {reg3}. Defeat the target, then claim at any job board."),

       (call_script, "script_start_quest", "qst_regional_threat_contract", "trp_player"),
      (add_quest_note_from_sreg, "qst_regional_threat_contract", 2, s5, 0),
       (add_quest_note_from_sreg, "qst_regional_threat_contract", 3, s6, 0),
       (add_quest_note_from_sreg, "qst_regional_threat_contract", 4, s7, 0),

      (display_message, "@Contract accepted. The marked party is on the map.", 0xD6B15E),
     (else_try),
       (display_message, "@That contract could not be issued right now. Please try again at the job board.", 0xCC4444),
     (try_end),
    (try_end),
  ]),
]
