# COST: Weekly center migration and population-transfer stage.
SCRIPTS = [
("sod_center_weekly_get_migration_food_adjusted_score",
 [
    (store_script_param, ":base_score", 1),
    (store_script_param, ":food_store", 2),
    (store_script_param, ":food_consumption", 3),
    (store_script_param, ":food_capacity_ratio", 4),
    (store_script_param, ":include_surplus_bonus", 5),

    (assign, ":score", ":base_score"),
    (try_begin),
      (gt, ":food_consumption", 0),
      (store_mul, ":three_day_stock", ":food_consumption", 3),
      (store_mul, ":seven_day_stock", ":food_consumption", 7),
      (try_begin),
        (le, ":food_store", 0),
        (val_sub, ":score", 20),
      (else_try),
        (lt, ":food_store", ":three_day_stock"),
        (val_sub, ":score", 12),
      (else_try),
        (lt, ":food_store", ":seven_day_stock"),
        (val_sub, ":score", 6),
      (else_try),
        (eq, ":include_surplus_bonus", 1),
        (store_mul, ":fourteen_day_stock", ":food_consumption", 14),
        (gt, ":food_store", ":fourteen_day_stock"),
        (val_add, ":score", 3),
      (try_end),
    (try_end),
    (try_begin),
      (lt, ":food_capacity_ratio", 15),
      (val_sub, ":score", 10),
    (else_try),
      (lt, ":food_capacity_ratio", 30),
      (val_sub, ":score", 4),
    (else_try),
      (ge, ":food_capacity_ratio", 70),
      (val_add, ":score", 2),
    (try_end),
    (assign, reg0, ":score"),
 ]),

("sod_center_weekly_get_basic_migration_pressure",
 [
    (store_script_param, ":prosperity", 1),
    (store_script_param, ":health", 2),
    (store_script_param, ":relation", 3),

    (assign, ":migration_pressure", 0),
    (assign, ":pressure_poverty", 0),
    (assign, ":pressure_sickness", 0),
    (assign, ":pressure_unrest", 0),

    (try_begin),
      (lt, ":prosperity", 45),
      (assign, ":pressure_poverty", 1),
      (store_sub, ":tmp", 45, ":prosperity"),
      (val_div, ":tmp", 4),
      (val_add, ":migration_pressure", ":tmp"),
    (try_end),
    (try_begin),
      (lt, ":health", 45),
      (assign, ":pressure_sickness", 1),
      (store_sub, ":tmp", 45, ":health"),
      (val_div, ":tmp", 4),
      (val_add, ":migration_pressure", ":tmp"),
    (try_end),
    (try_begin),
      (lt, ":relation", -5),
      (assign, ":pressure_unrest", 1),
      (store_sub, ":tmp", 0, ":relation"),
      (val_div, ":tmp", 8),
      (val_add, ":migration_pressure", ":tmp"),
    (try_end),

    (assign, reg0, ":migration_pressure"),
    (assign, reg1, ":pressure_poverty"),
    (assign, reg2, ":pressure_sickness"),
    (assign, reg3, ":pressure_unrest"),
 ]),

("sod_center_weekly_get_food_migration_pressure",
 [
    (store_script_param, ":food_store", 1),
    (store_script_param, ":food_consumption", 2),
    (store_script_param, ":food_capacity_ratio", 3),

    (assign, ":migration_pressure", 0),
    (assign, ":pressure_hunger", 0),
    (try_begin),
      (gt, ":food_consumption", 0),
      (store_mul, ":three_day_stock", ":food_consumption", 3),
      (store_mul, ":seven_day_stock", ":food_consumption", 7),
      (try_begin),
        (le, ":food_store", 0),
        (assign, ":pressure_hunger", 1),
        (val_add, ":migration_pressure", 8),
      (else_try),
        (lt, ":food_store", ":three_day_stock"),
        (assign, ":pressure_hunger", 1),
        (val_add, ":migration_pressure", 5),
      (else_try),
        (lt, ":food_store", ":seven_day_stock"),
        (assign, ":pressure_hunger", 1),
        (val_add, ":migration_pressure", 2),
      (try_end),
    (try_end),
    (try_begin),
      (lt, ":food_capacity_ratio", 15),
      (assign, ":pressure_hunger", 1),
      (val_add, ":migration_pressure", 5),
    (else_try),
      (lt, ":food_capacity_ratio", 30),
      (assign, ":pressure_hunger", 1),
      (val_add, ":migration_pressure", 2),
    (try_end),

    (assign, reg0, ":migration_pressure"),
    (assign, reg1, ":pressure_hunger"),
 ]),

("sod_center_weekly_get_migration_transfer_to_reg",
 [
    (store_script_param, ":migrants", 1),
    (store_script_param, ":dest_pop", 2),
    (store_script_param, ":dest_pop_max", 3),
    (store_script_param, ":score_gap", 4),

    (store_sub, ":dest_room", ":dest_pop_max", ":dest_pop"),
    (assign, ":transfer", ":migrants"),
    (val_min, ":transfer", ":dest_room"),

    (assign, ":gap_cap", ":score_gap"),
    (val_div, ":gap_cap", 6),
    (val_add, ":gap_cap", 1),
    (val_min, ":transfer", ":gap_cap"),
    (assign, reg0, ":transfer"),
 ]),

("sod_center_weekly_apply_migration",
 [
    (try_begin),
      (eq, "$g_sod_hide_messages", -2),
      (set_show_messages, 0),
    (try_end),
    (call_script, "script_sod_center_weekly_refresh_profile_cache"),

    (try_for_range, ":source_no", villages_begin, villages_end),
      (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":source_no"),
      (assign, ":src_pop", reg0),
      (assign, ":src_prosp", reg1),
      (assign, ":src_health", reg2),
      (assign, ":src_food_store", reg3),
      (assign, ":src_food_consumption", reg5),
      (assign, ":src_food_capacity_ratio", reg6),
      (assign, ":src_relation", reg8),
      (assign, ":src_lord", reg9),
      (gt, ":src_lord", 0),

      (store_sub, ":surplus", ":src_pop", village_pop_min),
      (ge, ":surplus", sod_migration_pop_surplus_min),

      (call_script, "script_sod_center_weekly_get_basic_migration_pressure", ":src_prosp", ":src_health", ":src_relation"),
      (assign, ":migration_pressure", reg0),
      (assign, ":src_pressure_poverty", reg1),
      (assign, ":src_pressure_sickness", reg2),
      (assign, ":src_pressure_unrest", reg3),
      (call_script, "script_sod_center_weekly_get_food_migration_pressure", ":src_food_store", ":src_food_consumption", ":src_food_capacity_ratio"),
      (assign, ":food_migration_pressure", reg0),
      (assign, ":src_pressure_hunger", reg1),
      (val_add, ":migration_pressure", ":food_migration_pressure"),

      (store_troop_faction, ":src_faction", ":src_lord"),
      (assign, ":src_score", ":src_prosp"),
      (val_add, ":src_score", ":src_health"),
      (val_add, ":src_score", ":src_relation"),
      (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":src_score", ":src_food_store", ":src_food_consumption", ":src_food_capacity_ratio", 0),
      (assign, ":src_score", reg0),
      (try_begin),
        (ge, ":src_pop", 425),
        (lt, ":src_prosp", 55),
        (val_add, ":migration_pressure", 1),
      (try_end),
      (gt, ":migration_pressure", 0),

      (store_random_in_range, ":migrants", 1, sod_migration_max_per_week),
      (val_min, ":migrants", ":surplus"),
      (val_min, ":migrants", ":migration_pressure"),
      (gt, ":migrants", 0),

      (try_for_range, ":dest_no", villages_begin, villages_end),
        (neq, ":dest_no", ":source_no"),
        (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":dest_no"),
        (assign, ":dest_pop", reg0),
        (assign, ":dest_prosp", reg1),
        (assign, ":dest_health", reg2),
        (assign, ":dest_food_store", reg3),
        (assign, ":dest_food_consumption", reg5),
        (assign, ":dest_food_capacity_ratio", reg6),
        (assign, ":dest_relation", reg8),
        (assign, ":dest_lord", reg9),
        (gt, ":dest_lord", 0),

        (store_troop_faction, ":dest_faction", ":dest_lord"),
        (eq, ":dest_faction", ":src_faction"),
        (lt, ":dest_pop", village_pop_max),

        (store_sub, ":prosp_gap", ":dest_prosp", ":src_prosp"),
        (ge, ":prosp_gap", 5),

        (assign, ":dest_score", ":dest_prosp"),
        (val_add, ":dest_score", ":dest_health"),
        (val_add, ":dest_score", ":dest_relation"),
        (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":dest_score", ":dest_food_store", ":dest_food_consumption", ":dest_food_capacity_ratio", 1),
        (assign, ":dest_score", reg0),
        (store_sub, ":score_gap", ":dest_score", ":src_score"),
        (ge, ":score_gap", 8),

        (call_script, "script_sod_center_weekly_get_migration_transfer_to_reg", ":migrants", ":dest_pop", village_pop_max, ":score_gap"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),

        (call_script, "script_sod_center_transfer_population", ":source_no", ":dest_no", ":transfer"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),
        (store_mul, ":source_cache_delta", ":transfer", -1),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":source_no", ":source_cache_delta"),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":dest_no", ":transfer"),
        (call_script, "script_sod_report_pick_pressure_reason_to_reg", ":src_pressure_hunger", ":src_pressure_sickness", ":src_pressure_unrest", ":src_pressure_poverty"),
        (call_script, "script_sod_report_record_center_event", sod_report_category_settlements, sod_report_severity_notable, ":source_no", ":dest_no", ":transfer", reg0),
        (assign, ":migrants", 0),
        (assign, ":dest_no", villages_end), # loop break
      (try_end),

      (gt, ":migrants", 0),
      (try_for_range, ":dest_no", towns_begin, towns_end),
        (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":dest_no"),
        (assign, ":dest_pop", reg0),
        (assign, ":dest_prosp", reg1),
        (assign, ":dest_health", reg2),
        (assign, ":dest_food_store", reg3),
        (assign, ":dest_food_consumption", reg5),
        (assign, ":dest_food_capacity_ratio", reg6),
        (assign, ":dest_relation", reg8),
        (assign, ":dest_lord", reg9),
        (gt, ":dest_lord", 0),

        (store_troop_faction, ":dest_faction", ":dest_lord"),
        (eq, ":dest_faction", ":src_faction"),
        (lt, ":dest_pop", town_pop_max),

        (store_sub, ":prosp_gap", ":dest_prosp", ":src_prosp"),
        (ge, ":prosp_gap", 5),

        (assign, ":dest_score", ":dest_prosp"),
        (val_add, ":dest_score", ":dest_health"),
        (val_add, ":dest_score", ":dest_relation"),
        (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":dest_score", ":dest_food_store", ":dest_food_consumption", ":dest_food_capacity_ratio", 1),
        (assign, ":dest_score", reg0),
        (store_sub, ":score_gap", ":dest_score", ":src_score"),
        (ge, ":score_gap", 8),

        (call_script, "script_sod_center_weekly_get_migration_transfer_to_reg", ":migrants", ":dest_pop", town_pop_max, ":score_gap"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),

        (call_script, "script_sod_center_transfer_population", ":source_no", ":dest_no", ":transfer"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),
        (store_mul, ":source_cache_delta", ":transfer", -1),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":source_no", ":source_cache_delta"),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":dest_no", ":transfer"),
        (call_script, "script_sod_report_pick_pressure_reason_to_reg", ":src_pressure_hunger", ":src_pressure_sickness", ":src_pressure_unrest", ":src_pressure_poverty"),
        (call_script, "script_sod_report_record_center_event", sod_report_category_settlements, sod_report_severity_notable, ":source_no", ":dest_no", ":transfer", reg0),
        (assign, ":migrants", 0),
        (assign, ":dest_no", towns_end), # loop break
      (try_end),
    (try_end),

    (try_for_range, ":source_no", towns_begin, towns_end),
      (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":source_no"),
      (assign, ":src_pop", reg0),
      (assign, ":src_prosp", reg1),
      (assign, ":src_health", reg2),
      (assign, ":src_food_store", reg3),
      (assign, ":src_food_consumption", reg5),
      (assign, ":src_food_capacity_ratio", reg6),
      (assign, ":src_relation", reg8),
      (assign, ":src_lord", reg9),
      (gt, ":src_lord", 0),

      (assign, ":src_pressure_hunger", 0),

      (store_sub, ":surplus", ":src_pop", town_pop_min),
      (ge, ":surplus", sod_migration_pop_surplus_min),

      (call_script, "script_sod_center_weekly_get_basic_migration_pressure", ":src_prosp", ":src_health", ":src_relation"),
      (assign, ":migration_pressure", reg0),
      (assign, ":src_pressure_poverty", reg1),
      (assign, ":src_pressure_sickness", reg2),
      (assign, ":src_pressure_unrest", reg3),
      (call_script, "script_sod_center_weekly_get_food_migration_pressure", ":src_food_store", ":src_food_consumption", ":src_food_capacity_ratio"),
      (assign, ":food_migration_pressure", reg0),
      (assign, ":src_pressure_hunger", reg1),
      (val_add, ":migration_pressure", ":food_migration_pressure"),
      (try_begin),
        (ge, ":src_pop", 2200),
        (lt, ":src_prosp", 60),
        (val_add, ":migration_pressure", 3),
      (else_try),
        (ge, ":src_pop", 1700),
        (lt, ":src_prosp", 55),
        (val_add, ":migration_pressure", 2),
      (else_try),
        (ge, ":src_pop", 1200),
        (lt, ":src_prosp", 50),
        (val_add, ":migration_pressure", 1),
      (try_end),
      (gt, ":migration_pressure", 0),

      (store_troop_faction, ":src_faction", ":src_lord"),
      (assign, ":src_score", ":src_prosp"),
      (val_add, ":src_score", ":src_health"),
      (val_add, ":src_score", ":src_relation"),
      (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":src_score", ":src_food_store", ":src_food_consumption", ":src_food_capacity_ratio", 0),
      (assign, ":src_score", reg0),

      (store_random_in_range, ":migrants", 1, sod_migration_max_per_week),
      (val_min, ":migrants", ":surplus"),
      (val_min, ":migrants", ":migration_pressure"),
      (gt, ":migrants", 0),

      (try_for_range, ":dest_no", villages_begin, villages_end),
        (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":dest_no"),
        (assign, ":dest_pop", reg0),
        (assign, ":dest_prosp", reg1),
        (assign, ":dest_health", reg2),
        (assign, ":dest_food_store", reg3),
        (assign, ":dest_food_consumption", reg5),
        (assign, ":dest_food_capacity_ratio", reg6),
        (assign, ":dest_relation", reg8),
        (assign, ":dest_lord", reg9),
        (gt, ":dest_lord", 0),

        (store_troop_faction, ":dest_faction", ":dest_lord"),
        (eq, ":dest_faction", ":src_faction"),
        (lt, ":dest_pop", village_pop_max),

        (store_sub, ":prosp_gap", ":dest_prosp", ":src_prosp"),
        (ge, ":prosp_gap", 5),

        (assign, ":dest_score", ":dest_prosp"),
        (val_add, ":dest_score", ":dest_health"),
        (val_add, ":dest_score", ":dest_relation"),
        (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":dest_score", ":dest_food_store", ":dest_food_consumption", ":dest_food_capacity_ratio", 1),
        (assign, ":dest_score", reg0),
        (store_sub, ":score_gap", ":dest_score", ":src_score"),
        (ge, ":score_gap", 8),

        (call_script, "script_sod_center_weekly_get_migration_transfer_to_reg", ":migrants", ":dest_pop", village_pop_max, ":score_gap"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),

        (call_script, "script_sod_center_transfer_population", ":source_no", ":dest_no", ":transfer"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),
        (store_mul, ":source_cache_delta", ":transfer", -1),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":source_no", ":source_cache_delta"),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":dest_no", ":transfer"),
        (call_script, "script_sod_report_pick_pressure_reason_to_reg", ":src_pressure_hunger", ":src_pressure_sickness", ":src_pressure_unrest", ":src_pressure_poverty"),
        (call_script, "script_sod_report_record_center_event", sod_report_category_settlements, sod_report_severity_notable, ":source_no", ":dest_no", ":transfer", reg0),
        (assign, ":migrants", 0),
        (assign, ":dest_no", villages_end), # loop break
      (try_end),

      (gt, ":migrants", 0),
      (try_for_range, ":dest_no", towns_begin, towns_end),
        (neq, ":dest_no", ":source_no"),
        (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":dest_no"),
        (assign, ":dest_pop", reg0),
        (assign, ":dest_prosp", reg1),
        (assign, ":dest_health", reg2),
        (assign, ":dest_food_store", reg3),
        (assign, ":dest_food_consumption", reg5),
        (assign, ":dest_food_capacity_ratio", reg6),
        (assign, ":dest_relation", reg8),
        (assign, ":dest_lord", reg9),
        (gt, ":dest_lord", 0),

        (store_troop_faction, ":dest_faction", ":dest_lord"),
        (eq, ":dest_faction", ":src_faction"),
        (lt, ":dest_pop", town_pop_max),

        (store_sub, ":prosp_gap", ":dest_prosp", ":src_prosp"),
        (ge, ":prosp_gap", 5),

        (assign, ":dest_score", ":dest_prosp"),
        (val_add, ":dest_score", ":dest_health"),
        (val_add, ":dest_score", ":dest_relation"),
        (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":dest_score", ":dest_food_store", ":dest_food_consumption", ":dest_food_capacity_ratio", 1),
        (assign, ":dest_score", reg0),
        (store_sub, ":score_gap", ":dest_score", ":src_score"),
        (ge, ":score_gap", 8),

        (call_script, "script_sod_center_weekly_get_migration_transfer_to_reg", ":migrants", ":dest_pop", town_pop_max, ":score_gap"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),

        (call_script, "script_sod_center_transfer_population", ":source_no", ":dest_no", ":transfer"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),
        (store_mul, ":source_cache_delta", ":transfer", -1),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":source_no", ":source_cache_delta"),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":dest_no", ":transfer"),
        (call_script, "script_sod_report_pick_pressure_reason_to_reg", ":src_pressure_hunger", ":src_pressure_sickness", ":src_pressure_unrest", ":src_pressure_poverty"),
        (call_script, "script_sod_report_record_center_event", sod_report_category_settlements, sod_report_severity_notable, ":source_no", ":dest_no", ":transfer", reg0),
        (assign, ":migrants", 0),
        (assign, ":dest_no", towns_end), # loop break
      (try_end),
    (try_end),

    (try_begin),
      (eq, "$g_sod_hide_messages", -2),
      (set_show_messages, 1),
    (try_end),
 ]),
]
