# COST: O(bound villages)
SCRIPTS = [
("sod_get_center_regional_flow_profile",
  [
    (store_script_param, ":center_no", 1),

    (assign, ":flow_score", 0),
    (assign, ":upstream_villages", 0),
    (assign, ":rural_output", 0),
    (assign, ":market_pull", 0),
    (assign, ":security", 0),
    (assign, ":effective_threat", 0),
    (assign, ":food_security", 1000),
    (assign, ":weakness_score", 0),
    (assign, ":recommended_mode", 1),
    (assign, ":recovery_strength", 0),

    (try_begin),
      (is_between, ":center_no", villages_begin, villages_end),
      (call_script, "script_sod_get_village_output_profile", ":center_no"),
      (assign, ":village_workforce", reg0),
      (assign, ":village_food_output", reg1),
      (assign, ":village_raw_output", reg3),
      (assign, ":village_fragility", reg6),
      (assign, ":village_reliability", reg8),
      (assign, ":rural_output", ":village_food_output"),
      (val_add, ":rural_output", ":village_raw_output"),
      (assign, ":flow_score", ":rural_output"),
      (val_add, ":flow_score", ":village_workforce"),
      (val_mul, ":flow_score", ":village_reliability"),
      (val_div, ":flow_score", 100),
      (call_script, "script_sod_get_center_food_profile", ":center_no"),
      (assign, ":food_security", reg4),
      (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
      (assign, ":tax_pressure", reg1),
      (assign, ":tax_recovery_pct", reg5),
      (call_script, "script_sod_get_center_security_profile", ":center_no"),
      (assign, ":effective_threat", reg0),
      (assign, ":security", reg1),
      (assign, ":weakness_score", ":village_fragility"),
      (val_add, ":weakness_score", ":tax_pressure"),
      (store_mul, ":threat_weakness", ":effective_threat", 8),
      (val_add, ":weakness_score", ":threat_weakness"),
      (try_begin),
        (lt, ":food_security", 600),
        (store_sub, ":food_weakness", 600, ":food_security"),
        (val_div, ":food_weakness", 15),
        (val_add, ":weakness_score", ":food_weakness"),
      (try_end),
      (assign, ":recovery_strength", ":village_reliability"),
      (val_mul, ":recovery_strength", ":tax_recovery_pct"),
      (val_div, ":recovery_strength", 100),
      (try_begin),
        (gt, ":weakness_score", 70),
        (assign, ":recommended_mode", 1),
      (else_try),
        (assign, ":recommended_mode", 0),
      (try_end),

    (else_try),
      (is_between, ":center_no", towns_begin, towns_end),
      (call_script, "script_sod_get_town_market_profile", ":center_no"),
      (assign, ":flow_score", reg0),
      (assign, ":rural_output", reg1),
      (assign, ":consumption_pressure", reg2),
      (assign, ":market_pull", reg3),
      (assign, ":services", reg4),
      (assign, ":recovery_strength", reg5),
      (assign, ":liquidity", reg6),
      (assign, ":food_security", reg10),
      (assign, ":security", reg11),
      (assign, ":effective_threat", reg12),
      (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
      (assign, ":tax_pressure", reg1),
      (assign, ":tax_recovery_pct", reg5),
      (try_for_range, ":village_no", villages_begin, villages_end),
        (party_slot_eq, ":village_no", slot_village_bound_center, ":center_no"),
        (val_add, ":upstream_villages", 1),
      (try_end),
      (val_add, ":market_pull", ":consumption_pressure"),
      (val_add, ":flow_score", ":services"),
      (store_div, ":liquidity_flow", ":liquidity", 2),
      (val_add, ":flow_score", ":liquidity_flow"),
      (store_div, ":import_weakness", ":market_pull", 3),
      (assign, ":weakness_score", ":import_weakness"),
      (store_mul, ":threat_weakness", ":effective_threat", 8),
      (val_add, ":weakness_score", ":threat_weakness"),
      (val_add, ":weakness_score", ":tax_pressure"),
      (try_begin),
        (lt, ":liquidity", 80),
        (store_sub, ":liquidity_weakness", 80, ":liquidity"),
        (val_div, ":liquidity_weakness", 2),
        (val_add, ":weakness_score", ":liquidity_weakness"),
      (try_end),
      (try_begin),
        (lt, ":food_security", 700),
        (store_sub, ":food_weakness", 700, ":food_security"),
        (val_div, ":food_weakness", 20),
        (val_add, ":weakness_score", ":food_weakness"),
      (try_end),
      (try_begin),
        (lt, ":food_security", 500),
        (assign, ":recommended_mode", 1),
      (else_try),
        (lt, ":liquidity", 80),
        (assign, ":recommended_mode", 2),
      (else_try),
        (assign, ":recommended_mode", 2),
      (try_end),
      (val_mul, ":recovery_strength", ":tax_recovery_pct"),
      (val_div, ":recovery_strength", 100),

    (else_try),
      (is_between, ":center_no", castles_begin, castles_end),
      (call_script, "script_sod_get_castle_support_profile", ":center_no"),
      (assign, ":castle_support", reg0),
      (assign, ":rural_output", reg2),
      (assign, ":upstream_villages", reg3),
      (assign, ":food_security", reg4),
      (assign, ":security", reg6),
      (assign, ":military_power", reg8),
      (assign, ":siege_readiness", reg11),
      (assign, ":recovery_strength", reg12),
      (assign, ":village_protection", reg16),
      (call_script, "script_sod_get_center_security_profile", ":center_no"),
      (assign, ":effective_threat", reg0),
      (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
      (assign, ":tax_pressure", reg1),
      (assign, ":tax_recovery_pct", reg5),
      (store_div, ":flow_score", ":castle_support", 1),
      (store_div, ":military_flow", ":military_power", 20),
      (val_add, ":flow_score", ":military_flow"),
      (val_add, ":flow_score", ":village_protection"),
      (assign, ":market_pull", ":siege_readiness"),
      (try_begin),
        (lt, ":castle_support", 100),
        (store_sub, ":support_weakness", 100, ":castle_support"),
        (val_div, ":support_weakness", 2),
        (val_add, ":weakness_score", ":support_weakness"),
      (try_end),
      (try_begin),
        (lt, ":siege_readiness", 80),
        (store_sub, ":siege_weakness", 80, ":siege_readiness"),
        (val_div, ":siege_weakness", 2),
        (val_add, ":weakness_score", ":siege_weakness"),
      (try_end),
      (store_mul, ":threat_weakness", ":effective_threat", 8),
      (val_add, ":weakness_score", ":threat_weakness"),
      (val_add, ":weakness_score", ":tax_pressure"),
      (try_begin),
        (lt, ":food_security", 700),
        (store_sub, ":food_weakness", 700, ":food_security"),
        (val_div, ":food_weakness", 20),
        (val_add, ":weakness_score", ":food_weakness"),
      (try_end),
      (try_begin),
        (lt, ":food_security", 500),
        (assign, ":recommended_mode", 1),
      (else_try),
        (assign, ":recommended_mode", 3),
      (try_end),
      (val_mul, ":recovery_strength", ":tax_recovery_pct"),
      (val_div, ":recovery_strength", 100),
    (try_end),

    (val_clamp, ":flow_score", 0, 1001),
    (val_clamp, ":rural_output", 0, 1001),
    (val_clamp, ":market_pull", 0, 501),
    (val_clamp, ":security", -100, 301),
    (val_clamp, ":effective_threat", 0, 11),
    (val_clamp, ":food_security", 0, 2001),
    (val_clamp, ":weakness_score", 0, 301),
    (val_clamp, ":recovery_strength", 0, 301),

    (assign, reg0, ":flow_score"),
    (assign, reg1, ":upstream_villages"),
    (assign, reg2, ":rural_output"),
    (assign, reg3, ":market_pull"),
    (assign, reg4, ":security"),
    (assign, reg5, ":effective_threat"),
    (assign, reg6, ":food_security"),
    (assign, reg7, ":weakness_score"),
    (assign, reg8, ":recommended_mode"),
    (assign, reg9, ":recovery_strength"),
  ]),
]
