# COST: medium
SCRIPTS = [
("sod_merc_lord_try_spawn_for_troop",
 [
   (store_script_param_1, ":troop_no"),

   (assign, ":spawned_party", 0),
   (try_begin),
     (troop_slot_eq, ":troop_no", slot_troop_occupation, slto_mercenary_lord),
     (neg|troop_slot_ge, ":troop_no", slot_troop_prisoner_of_party, 0),
     (neg|troop_slot_ge, ":troop_no", slot_troop_leaded_party, 1),
     (neg|main_party_has_troop, ":troop_no"),
     (store_troop_faction, ":guild_faction", ":troop_no"),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (call_script, "script_sod_merc_market_calculate_guild_supply", ":guild_faction", 0),
     (assign, ":available_companies", reg0),
     (assign, ":max_company_size", reg1),
     (assign, ":quality", reg2),
     (assign, ":refusal_reason", reg6),
     (faction_get_slot, ":support_capacity", ":guild_faction", slot_faction_sod_merc_support_capacity),
     (faction_get_slot, ":active_contracts", ":guild_faction", slot_faction_sod_merc_active_contracts),
     (gt, ":support_capacity", ":active_contracts"),
     (gt, ":available_companies", 0),
     (neq, ":refusal_reason", sod_merc_refusal_no_capacity),
     (neq, ":refusal_reason", sod_merc_refusal_low_manpower),
     (neq, ":refusal_reason", sod_merc_refusal_low_treasury),
     (neq, ":refusal_reason", sod_merc_refusal_overextended),
     (faction_get_slot, ":treasury", ":guild_faction", slot_faction_sod_merc_treasury),
     (faction_get_slot, ":manpower", ":guild_faction", slot_faction_sod_merc_manpower),
     (faction_get_slot, ":veterans", ":guild_faction", slot_faction_sod_merc_veterans),
     (faction_get_slot, ":elite_stock", ":guild_faction", slot_faction_sod_merc_elite_stock),
     (ge, ":treasury", 1000),
     (ge, ":manpower", 60),

     (assign, ":employer_faction", 0),
     (assign, ":base", 0),
     (assign, ":patrol_radius", 35),
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       (assign, ":employer_faction", ":guild_faction"),
       (store_random_in_range, ":base", towns_begin, towns_end),
       (assign, ":patrol_radius", 500),
     (else_try),
       (try_for_range, ":cur_kingdom", native_kingdoms_begin, native_kingdoms_end),
         (eq, ":employer_faction", 0),
         (faction_slot_eq, ":cur_kingdom", slot_faction_state, sfs_active),
         (faction_slot_eq, ":cur_kingdom", slot_faction_merc_pact, ":guild_faction"),
         (call_script, "script_sod_merc_market_calculate_kingdom_demand", ":cur_kingdom", 0, 0, 0, 0),
         (assign, ":demand_score", reg0),
         (ge, ":demand_score", 35),
         (assign, ":employer_faction", ":cur_kingdom"),
       (try_end),
       (faction_get_slot, ":base", ":guild_faction", slot_guild_base),
     (try_end),
     (gt, ":employer_faction", 0),
     (gt, ":base", 0),

     (assign, ":party_size", ":max_company_size"),
     (val_min, ":party_size", 100),
     (val_max, ":party_size", 60),
     (try_begin),
       (ge, ":quality", 3),
       (val_add, ":party_size", 10),
     (else_try),
       (le, ":quality", 1),
       (val_sub, ":party_size", 10),
     (try_end),
     (val_clamp, ":party_size", 50, 110),
     (ge, ":manpower", ":party_size"),

     (spawn_around_party, ":base", "pt_mercenary_lord_party"),
     (assign, ":merc_lord_party", reg0),
     (gt, ":merc_lord_party", 0),
     (party_is_active, ":merc_lord_party"),
     (party_set_faction, ":merc_lord_party", ":employer_faction"),
     (troop_set_slot, ":troop_no", slot_troop_leaded_party, ":merc_lord_party"),
     (str_store_troop_name, s1, ":troop_no"),
     (party_set_name, ":merc_lord_party", s1),
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild1"),
       (party_set_banner_icon, ":merc_lord_party", "icon_banner_298"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild2"),
       (party_set_banner_icon, ":merc_lord_party", "icon_banner_299"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild3"),
       (party_set_banner_icon, ":merc_lord_party", "icon_banner_300"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild4"),
       (party_set_banner_icon, ":merc_lord_party", "icon_banner_301"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild5"),
       (party_set_banner_icon, ":merc_lord_party", "icon_banner_302"),
     (else_try),
       (party_set_banner_icon, ":merc_lord_party", "icon_banner_303"),
     (try_end),
     (party_set_slot, ":merc_lord_party", slot_party_starting_size, ":party_size"),
     (party_set_slot, ":merc_lord_party", slot_party_type, spt_mercenary_lord_party),
     (party_set_slot, ":merc_lord_party", slot_party_orginal_faction, ":guild_faction"),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_employer, ":employer_faction"),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_guild, ":guild_faction"),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_role, sod_merc_contract_role_mercenary_lord),
     (store_mul, ":contract_value", ":party_size", 30),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_value, ":contract_value"),
     (store_current_day, ":cur_day"),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_start_day, ":cur_day"),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_initial_size, ":party_size"),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_loss_score, 0),
     (store_add, ":contract_end", ":cur_day", 30),
     (party_set_slot, ":merc_lord_party", slot_party_merc_contract, ":contract_end"),
     (party_set_slot, ":merc_lord_party", slot_party_sod_merc_contract_term_end, ":contract_end"),

     (call_script, "script_sod_merc_guild_get_roster", ":guild_faction"),
     (assign, ":t1_1", reg0),
     (assign, ":t1_2", reg1),
     (assign, ":noble", reg2),
     (assign, ":proportion", reg3),
     (gt, ":t1_1", 0),
     (gt, ":t1_2", 0),
     (gt, ":noble", 0),
     (neq, ":t1_1", "trp_player"),
     (neq, ":t1_2", "trp_player"),
     (neq, ":noble", "trp_player"),
     (party_add_leader, ":merc_lord_party", ":troop_no"),
     (store_add, ":noble_count", 2, ":quality"),
     (party_add_members, ":merc_lord_party", ":noble", ":noble_count"),
     (store_sub, ":remaining_size", ":party_size", ":noble_count"),
     (store_mul, ":t1_1_units", ":noble_count", ":proportion"),
     (party_add_members, ":merc_lord_party", ":t1_1", ":t1_1_units"),
     (store_sub, ":t1_2_units", ":remaining_size", ":t1_1_units"),
     (try_begin),
       (gt, ":t1_2_units", 0),
       (try_begin),
         (eq, ":guild_faction", "fac_sod_merc_guild1"),
         (store_div, ":black_army_thirds", ":t1_2_units", 6),
         (val_min, ":black_army_thirds", 16),
         (val_sub, ":t1_2_units", ":black_army_thirds"),
         (party_add_members, ":merc_lord_party", black_army_tier_1_unit_3, ":black_army_thirds"),
       (try_end),
       (party_add_members, ":merc_lord_party", ":t1_2", ":t1_2_units"),
     (try_end),
     (store_add, ":upgrade_passes", 3, ":quality"),
     (try_for_range, ":unused", 0, ":upgrade_passes"),
       (call_script, "script_cf_party_upgrade_with_xp", ":merc_lord_party", 7500, 0),
     (try_end),
     (party_set_ai_behavior, ":merc_lord_party", ai_bhvr_patrol_location),
     (party_get_position, pos1, ":base"),
     (party_set_ai_target_position, ":merc_lord_party", pos1),
     (party_set_ai_patrol_radius, ":merc_lord_party", ":patrol_radius"),

     (val_sub, ":manpower", ":party_size"),
     (store_div, ":veteran_commitment", ":party_size", 6),
     (val_sub, ":veterans", ":veteran_commitment"),
     (try_begin),
       (ge, ":quality", 3),
       (val_sub, ":elite_stock", 2),
     (else_try),
       (ge, ":quality", 2),
       (val_sub, ":elite_stock", 1),
     (try_end),
     (val_max, ":manpower", 0),
     (val_max, ":veterans", 0),
     (val_max, ":elite_stock", 0),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_manpower, ":manpower"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_veterans, ":veterans"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_elite_stock, ":elite_stock"),
     (assign, ":spawned_party", ":merc_lord_party"),
   (try_end),

   (assign, reg0, ":spawned_party"),
 ]),
]
