# COST: O(1); called only when the player asks an AI mercenary company about its work.
SCRIPTS = [
("sod_merc_market_describe_ai_contract_to_s68",
 [
   (store_script_param_1, ":party_no"),

   (assign, reg0, 0),
   (str_store_string, s68, "@We have no current contract to discuss."),
   (str_store_string, s69, "@an unknown employer"),
   (str_store_string, s70, "@an unknown destination"),
   (str_store_string, s71, "@an unknown captain"),
   (str_store_string, s72, "@a free company"),
   (assign, ":role", sod_merc_contract_role_none),
   (assign, ":target_center", -1),
   (assign, ":boss_troop", -1),
   (assign, ":guild_faction", -1),

   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (party_slot_eq, ":party_no", slot_party_type, spt_ai_mercenaries),
     (assign, reg0, 1),

     # The role and AI target are the contract's live state, not its original bid.
     (party_get_slot, ":role", ":party_no", slot_party_sod_merc_contract_role),
     (party_get_slot, ":employer_faction", ":party_no", slot_party_sod_merc_contract_employer),
     (party_get_slot, ":guild_faction", ":party_no", slot_party_sod_merc_contract_guild),
     (try_begin),
       (neg|is_between, ":guild_faction", guilds_begin, guilds_end),
       (party_get_slot, ":guild_faction", ":party_no", slot_party_orginal_faction),
     (try_end),
     # The line identifies the specialist instead of making every company sound interchangeable.
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild1"),
       (str_store_string, s72, "@a Black Army security detachment"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild2"),
       (str_store_string, s72, "@a Conquistador pike-and-crossbow company"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild3"),
       (str_store_string, s72, "@an Elephant Guard warden company"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild4"),
       (str_store_string, s72, "@a Jotnar hearth company"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild5"),
       (str_store_string, s72, "@a Serpent Host route company"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       (str_store_string, s72, "@a Slaver capture company"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild7"),
       (str_store_string, s72, "@a Boar Clan frontier company"),
     (try_end),
     (try_begin),
       (is_between, ":employer_faction", 0, "fac_factions_end"),
       (str_store_faction_name, s69, ":employer_faction"),
     (else_try),
       (store_faction_of_party, ":party_faction", ":party_no"),
       (is_between, ":party_faction", 0, "fac_factions_end"),
       (str_store_faction_name, s69, ":party_faction"),
     (try_end),

     (party_get_slot, ":target_center", ":party_no", slot_party_ai_object),
     (try_begin),
       (is_between, ":target_center", centers_begin, centers_end),
       (str_store_party_name, s70, ":target_center"),
     (else_try),
       (assign, ":target_center", -1),
     (try_end),

     (party_get_slot, ":boss_troop", ":party_no", slot_party_boss),
     (try_begin),
       (is_between, ":boss_troop", 0, "trp_last_troop"),
       (str_store_troop_name, s71, ":boss_troop"),
     (try_end),

     (try_begin),
       (eq, ":role", sod_merc_contract_role_patrol),
       (is_between, ":target_center", villages_begin, villages_end),
       (str_store_string, s68, "@We are {s72}, under contract to patrol the roads around {s70} for {s69}."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_garrison_support),
       (is_between, ":target_center", walled_centers_begin, walled_centers_end),
       (str_store_string, s68, "@We are {s72}, under contract to bolster the garrison at {s70} for {s69}."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_supply_column),
       (is_between, ":target_center", centers_begin, centers_end),
       (str_store_string, s68, "@We are {s72}, carrying food and relief stores to {s70} for {s69}."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_field_company),
       (is_between, ":boss_troop", 0, "trp_last_troop"),
       (str_store_string, s68, "@We are {s72} in field service for {s69}, under {s71}'s command."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_field_company),
       (str_store_string, s68, "@We are {s72} in field service for {s69}, moving where the contract needs us."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_escort),
       (str_store_string, s68, "@We are {s72}, serving as an escort company for {s69}; the client sets the route."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_mercenary_lord),
       (is_between, ":boss_troop", 0, "trp_last_troop"),
       (str_store_string, s68, "@We are {s72} in mercenary-lord service for {s69}, under {s71}'s command."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_mercenary_lord),
       (str_store_string, s68, "@We are {s72}, serving as a mercenary-lord company for {s69}."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_special_world_activity),
       (str_store_string, s68, "@We are {s72} on a special assignment for {s69}; our captain keeps the details close."),
     (else_try),
       (eq, ":role", sod_merc_contract_role_none),
       (str_store_string, s68, "@We are a free company with no current assignment."),
     (else_try),
       (str_store_string, s68, "@We are under contract to {s69}, but our current task is being reassigned."),
     (try_end),
   (try_end),
 ]),
]
