# COST: trivial
SCRIPTS = [
("sod_threat_board_get_archetype",
 [
   (store_script_param_1, ":archetype"),

   (assign, ":threat_type", sod_threat_type_pirates),
   (assign, ":tier", 1),
   (assign, ":party_template", "pt_bandits"),
   (assign, ":deadline_days", 8),
   (assign, ":relation_reward", 1),
   (assign, ":guild_sponsor", 0),

   (try_begin),
     (eq, ":archetype", sod_threat_archetype_river_pirates),
     (assign, ":threat_type", sod_threat_type_pirates),
     (assign, ":tier", 1),
     (assign, ":party_template", "pt_bandits"),
     (assign, ":deadline_days", 8),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_coastal_smugglers),
     (assign, ":threat_type", sod_threat_type_pirates),
     (assign, ":tier", 2),
     (assign, ":party_template", "pt_sea_raiders"),
     (assign, ":deadline_days", 9),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_army_deserters),
     (assign, ":threat_type", sod_threat_type_deserters),
     (assign, ":tier", 2),
     (assign, ":party_template", "pt_deserters"),
     (assign, ":deadline_days", 10),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_noble_deserters),
     (assign, ":threat_type", sod_threat_type_deserters),
     (assign, ":tier", 3),
     (assign, ":party_template", "pt_sod_merc_deserters"),
     (assign, ":deadline_days", 11),
     (assign, ":relation_reward", 2),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_relic_thieves),
     (assign, ":threat_type", sod_threat_type_relic_thieves),
     (assign, ":tier", 2),
     (assign, ":party_template", "pt_mountain_bandits"),
     (assign, ":deadline_days", 10),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_tomb_robbers),
     (assign, ":threat_type", sod_threat_type_relic_thieves),
     (assign, ":tier", 3),
     (assign, ":party_template", "pt_ravaging_bandits"),
     (assign, ":deadline_days", 12),
     (assign, ":relation_reward", 2),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_rogue_company),
     (assign, ":threat_type", sod_threat_type_rogue_company),
     (assign, ":tier", 3),
     (assign, ":party_template", "pt_mercenaries"),
     (assign, ":deadline_days", 11),
     (assign, ":relation_reward", 2),
     (assign, ":guild_sponsor", "fac_sod_merc_guild1"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_guild_traitors),
     (assign, ":threat_type", sod_threat_type_rogue_company),
     (assign, ":tier", 4),
     (assign, ":party_template", "pt_sod_mercs"),
     (assign, ":deadline_days", 12),
     (assign, ":relation_reward", 3),
     (assign, ":guild_sponsor", "fac_sod_merc_guild3"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_cattle_raiders),
     (assign, ":threat_type", sod_threat_type_cattle_raiders),
     (assign, ":tier", 1),
     (assign, ":party_template", "pt_troublesome_bandits"),
     (assign, ":deadline_days", 7),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_herd_rustlers),
     (assign, ":threat_type", sod_threat_type_cattle_raiders),
     (assign, ":tier", 2),
     (assign, ":party_template", "pt_forest_bandits"),
     (assign, ":deadline_days", 8),
     (assign, ":relation_reward", 2),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_invader_scouts),
     (assign, ":threat_type", sod_threat_type_faction_problem),
     (assign, ":tier", 3),
     (assign, ":party_template", "pt_serpent_host_ravaging_bandits"),
     (assign, ":deadline_days", 11),
     (assign, ":relation_reward", 2),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_raiding_captain),
     (assign, ":threat_type", sod_threat_type_faction_problem),
     (assign, ":tier", 4),
     (assign, ":party_template", "pt_bc_bandits"),
     (assign, ":deadline_days", 12),
     (assign, ":relation_reward", 3),
   (try_end),

    (assign, reg(0), ":threat_type"),
    (assign, reg(1), ":tier"),
    (assign, reg(2), ":party_template"),
    (assign, reg(3), ":deadline_days"),
    (assign, reg(4), ":relation_reward"),
    (assign, reg(5), ":guild_sponsor"),
 ]),
]
