# COST: moderate
SCRIPTS = [
("sod_black_khergits_update_horde_state",
 [
   (call_script, "script_sod_black_khergits_enforce_player_standing"),
   (store_num_parties_of_template, ":active_raiders", "pt_black_khergit_raiders"),
   (store_num_parties_of_template, ":active_guards", "pt_black_khergit_night_guard"),
   (store_num_parties_of_template, ":active_camps", "pt_black_khergit_horde_camp"),
   (assign, ":camp_party", 0),
   (try_for_parties, ":party_no"),
     (eq, ":camp_party", 0),
     (party_is_active, ":party_no"),
     (party_get_template_id, ":template", ":party_no"),
     (eq, ":template", "pt_black_khergit_horde_camp"),
     (assign, ":camp_party", ":party_no"),
   (try_end),

   (assign, ":target_center", 0),
   (assign, ":target_score", 0),
   (try_for_range, ":center_no", towns_begin, towns_end),
     (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
     (assign, ":center_score", ":prosperity"),
     (store_div, ":wealth_score", ":wealth", 80),
     (val_add, ":center_score", ":wealth_score"),
     (try_for_parties, ":caravan_party"),
       (party_is_active, ":caravan_party"),
       (party_get_template_id, ":caravan_template", ":caravan_party"),
       (eq, ":caravan_template", "pt_merchant_caravan"),
       (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":center_no"),
       (le, ":road_dist", 18),
       (val_add, ":center_score", 4),
     (try_end),
     (try_begin),
       (gt, ":camp_party", 0),
       (store_distance_to_party_from_party, ":dist", ":camp_party", ":center_no"),
       (store_sub, ":dist_penalty", ":dist", 20),
       (val_max, ":dist_penalty", 0),
       (val_div, ":dist_penalty", 2),
       (val_sub, ":center_score", ":dist_penalty"),
     (try_end),
     (gt, ":center_score", ":target_score"),
     (assign, ":target_score", ":center_score"),
     (assign, ":target_center", ":center_no"),
   (try_end),

   (faction_get_slot, ":stored_target", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (faction_get_slot, ":target_lock_until", "fac_black_khergits", slot_faction_black_khergit_target_lock_until),
   (store_current_day, ":cur_day"),
   (try_begin),
     (gt, ":target_lock_until", ":cur_day"),
     (is_between, ":stored_target", centers_begin, centers_end),
     (assign, ":target_center", ":stored_target"),
   (try_end),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (assign, ":target_center", "p_town_18"),
   (try_end),

   (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
   (val_clamp, ":pressure", 0, 101),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":camp_party"),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":target_center"),
   (assign, reg0, ":active_raiders"),
   (assign, reg1, ":active_guards"),
   (assign, reg2, ":active_camps"),
   (assign, reg3, ":camp_party"),
   (assign, reg4, ":target_center"),
   (assign, reg5, ":pressure"),
 ]),

("sod_black_khergits_process_pressure_economy",
 [
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (store_current_day, ":cur_day"),
   (faction_get_slot, ":last_pressure_day", "fac_black_khergits", slot_faction_black_khergit_last_pressure_day),
   (try_begin),
     (gt, ":cur_day", ":last_pressure_day"),
     (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
     (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
     (store_num_parties_of_template, ":active_raiders", "pt_black_khergit_raiders"),
     (store_num_parties_of_template, ":active_guards", "pt_black_khergit_night_guard"),
      (try_begin),
        (gt, ":camp_party", 0),
        (val_add, ":pressure", 3),
        (store_mul, ":raider_pressure", ":active_raiders", 2),
        (val_add, ":pressure", ":raider_pressure"),
        (val_add, ":pressure", ":active_guards"),
        (try_begin),
          (is_between, ":target_center", centers_begin, centers_end),
          (party_get_slot, ":target_prosperity", ":target_center", slot_town_prosperity),
          (store_div, ":target_pressure", ":target_prosperity", 18),
          (val_add, ":pressure", ":target_pressure"),
          (try_for_parties, ":caravan_party"),
            (party_is_active, ":caravan_party"),
            (party_get_template_id, ":caravan_template", ":caravan_party"),
            (eq, ":caravan_template", "pt_merchant_caravan"),
            (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":target_center"),
            (le, ":road_dist", 18),
            (val_add, ":pressure", 1),
          (try_end),
        (try_end),
      (else_try),
        (val_sub, ":pressure", 5),
      (try_end),
     (val_clamp, ":pressure", 0, 101),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":pressure"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_pressure_day, ":cur_day"),
     (call_script, "script_sod_black_khergits_enforce_player_standing"),
   (try_end),
 ]),

("sod_black_khergits_spawn_or_recover_camp",
 [
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (faction_get_slot, ":disrupted_until", "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until),
   (store_current_day, ":cur_day"),
   (try_begin),
     (le, ":camp_party", 0),
     (le, ":disrupted_until", ":cur_day"),
      (assign, ":spawn_center", "p_town_18"),
      (try_begin),
        (is_between, ":target_center", centers_begin, centers_end),
        (assign, ":spawn_center", ":target_center"),
      (try_end),
     (set_spawn_radius, 10),
     (spawn_around_party, ":spawn_center", "pt_black_khergit_horde_camp"),
     (assign, ":camp_party", reg0),
     (party_set_faction, ":camp_party", "fac_black_khergits"),
     (party_set_slot, ":camp_party", slot_party_black_khergit_camp_activity, 1),
     (party_set_slot, ":camp_party", slot_party_black_khergit_origin, ":spawn_center"),
     (party_set_slot, ":camp_party", slot_party_black_khergit_target, ":spawn_center"),
     (party_set_slot, ":camp_party", slot_party_black_khergit_role, sod_black_khergit_role_camp),
     (party_set_banner_icon, ":camp_party", "icon_banner_302"),
     (party_set_icon, ":camp_party", "icon_khergit_horseman_b"),
     (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":camp_party"),
     (call_script, "script_party_set_ai_state", ":camp_party", spai_holding_center, ":spawn_center"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":camp_party"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, ":cur_day"),
     (display_message, "@A Black Khergit horde camp has been sighted on the steppe roads.", 0x222222),
   (try_end),
 ]),

("sod_black_khergits_process_day_cycle",
 [
   (call_script, "script_sod_black_khergits_spawn_or_recover_camp"),
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (call_script, "script_sod_black_khergits_update_scout_intelligence"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (faction_get_slot, ":last_migration_day", "fac_black_khergits", slot_faction_black_khergit_last_migration_day),
   (store_current_day, ":cur_day"),
   (store_current_hours, ":cur_hours"),
   (store_mod, ":hour_of_day", ":cur_hours", 24),
   (assign, ":is_night", 0),
   (try_begin),
     (this_or_next|ge, ":hour_of_day", 18),
     (lt, ":hour_of_day", 6),
     (assign, ":is_night", 1),
   (try_end),

   (try_begin),
     (gt, ":camp_party", 0),
     (try_begin),
       (eq, ":is_night", 1),
       (party_set_icon, ":camp_party", "icon_camp"),
     (else_try),
       (party_set_icon, ":camp_party", "icon_khergit_horseman_b"),
     (try_end),
   (try_end),

   (try_begin),
     (gt, ":camp_party", 0),
     (is_between, ":target_center", centers_begin, centers_end),
     (store_sub, ":days_since_migration", ":cur_day", ":last_migration_day"),
     (ge, ":days_since_migration", 4),
     (party_set_slot, ":camp_party", slot_party_black_khergit_target, ":target_center"),
     (party_set_ai_behavior, ":camp_party", ai_bhvr_travel_to_party),
     (party_set_ai_object, ":camp_party", ":target_center"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, ":cur_day"),
     (str_store_party_name, s21, ":target_center"),
     (display_message, "@The Black Khergit camp is moving toward the rich roads around {s21}.", 0x222222),
   (try_end),

   (try_begin),
     (eq, ":is_night", 1),
     (store_num_parties_of_template, ":active_guards", "pt_black_khergit_night_guard"),
     (lt, ":active_guards", 2),
     (gt, ":camp_party", 0),
     (set_spawn_radius, 3),
     (spawn_around_party, ":camp_party", "pt_black_khergit_night_guard"),
     (assign, ":guard_party", reg0),
     (party_set_faction, ":guard_party", "fac_black_khergits"),
     (party_set_slot, ":guard_party", slot_party_black_khergit_camp_activity, 1),
     (party_set_slot, ":guard_party", slot_party_black_khergit_origin, ":camp_party"),
     (party_set_slot, ":guard_party", slot_party_black_khergit_target, ":target_center"),
     (party_set_slot, ":guard_party", slot_party_black_khergit_role, sod_black_khergit_role_guard),
     (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":guard_party"),
     (call_script, "script_party_set_ai_state", ":guard_party", spai_patrolling_around_center, ":camp_party"),
     (party_set_ai_patrol_radius, ":guard_party", 5),
   (else_try),
     (eq, ":is_night", 0),
     (gt, ":camp_party", 0),
     (try_for_parties, ":guard_party"),
       (party_is_active, ":guard_party"),
       (party_get_template_id, ":guard_template", ":guard_party"),
       (eq, ":guard_template", "pt_black_khergit_night_guard"),
       (store_distance_to_party_from_party, ":guard_dist", ":guard_party", ":camp_party"),
       (le, ":guard_dist", 8),
       (remove_party, ":guard_party"),
     (try_end),
     (try_begin),
       (eq, ":hour_of_day", 12),
       (call_script, "script_sod_black_khergits_process_pressure_economy"),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_spawn_raids",
 [
   (call_script, "script_sod_black_khergits_spawn_or_recover_camp"),
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (call_script, "script_sod_black_khergits_process_scattered_raider_aftermath"),
   (store_relation, ":player_relation", "fac_player_supporters_faction", "fac_black_khergits"),
   (try_begin),
     (ge, ":player_relation", 100),
     (assign, ":stop_for_player_friendship", 1),
   (else_try),
     (assign, ":stop_for_player_friendship", 0),
   (try_end),
   (try_begin),
     (eq, ":stop_for_player_friendship", 0),
     (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
     (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
     (try_begin),
       (neg|is_between, ":target_center", centers_begin, centers_end),
       (assign, ":target_center", "p_town_18"),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":target_center"),
     (try_end),
     (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (store_num_parties_of_template, ":active_raiders", "pt_black_khergit_raiders"),
     (store_current_day, ":cur_day"),
     (faction_get_slot, ":last_spawn_day", "fac_black_khergits", slot_faction_black_khergit_last_spawn_day),
     (store_sub, ":days_since_spawn", ":cur_day", ":last_spawn_day"),
     (assign, ":raider_cap", 1),
     (try_begin),
       (ge, ":pressure", 30),
       (val_add, ":raider_cap", 1),
     (try_end),
     (try_begin),
       (ge, ":pressure", 65),
       (val_add, ":raider_cap", 1),
     (try_end),
     (try_begin),
       (gt, ":camp_party", 0),
       (main_party_has_troop, "trp_npc1"),
       (troop_slot_eq, "trp_npc1", slot_troop_companion_role, sod_companion_role_scout),
       (troop_slot_eq, "trp_npc1", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
       (val_sub, ":pressure", 2),
       (val_max, ":pressure", 0),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":pressure"),
       (val_sub, ":raider_cap", 1),
       (val_max, ":raider_cap", 1),
       (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
       (try_begin),
         (lt, ":last_raid_report_day", ":cur_day"),
         (display_message, "@Borcha finds a hidden road before the Black Khergit camp can flood it with riders.", 0x99CCFF),
         (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
       (try_end),
     (try_end),
     (try_begin),
       (gt, ":camp_party", 0),
       (lt, ":active_raiders", ":raider_cap"),
       (this_or_next|ge, ":days_since_spawn", 2),
       (lt, ":last_spawn_day", 1),
       (set_spawn_radius, 5),
       (spawn_around_party, ":camp_party", "pt_black_khergit_raiders"),
       (assign, ":raider_party", reg0),
       (party_set_faction, ":raider_party", "fac_black_khergits"),
       (party_set_slot, ":raider_party", slot_party_black_khergit_camp_activity, 1),
       (party_set_slot, ":raider_party", slot_party_black_khergit_origin, ":camp_party"),
       (party_set_slot, ":raider_party", slot_party_black_khergit_target, ":target_center"),
       (party_set_slot, ":raider_party", slot_party_black_khergit_role, sod_black_khergit_role_raider),
       (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":raider_party"),
       (try_begin),
         (is_between, ":target_center", centers_begin, centers_end),
         (call_script, "script_party_set_ai_state", ":raider_party", spai_patrolling_around_center, ":target_center"),
         (party_set_ai_patrol_radius, ":raider_party", 14),
       (else_try),
         (call_script, "script_party_set_ai_state", ":raider_party", spai_patrolling_around_center, ":camp_party"),
         (party_set_ai_patrol_radius, ":raider_party", 12),
       (try_end),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_spawn_day, ":cur_day"),
       (display_message, "@Black Khergit raiders have ridden out from the horde camp.", 0x222222),
     (try_end),

     (try_for_range, ":center_no", villages_begin, villages_end),
       (assign, ":raided", 0),
       (try_for_parties, ":raider_party"),
         (eq, ":raided", 0),
         (party_is_active, ":raider_party"),
         (party_get_template_id, ":raider_template", ":raider_party"),
         (eq, ":raider_template", "pt_black_khergit_raiders"),
         (store_distance_to_party_from_party, ":raid_dist", ":raider_party", ":center_no"),
         (le, ":raid_dist", 7),
         (assign, ":raided", 1),
       (try_end),
       (try_begin),
         (eq, ":raided", 1),
         (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
         (try_begin),
           (gt, ":wealth", 250),
           (val_sub, ":wealth", 12),
           (val_max, ":wealth", 250),
           (party_set_slot, ":center_no", slot_town_wealth, ":wealth"),
           (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
           (try_begin),
             (lt, ":last_raid_report_day", ":cur_day"),
             (str_store_party_name, s22, ":center_no"),
             (display_message, "@Black Khergit raiders are stripping wealth from the villages around {s22}.", 0x222222),
             (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
           (try_end),
         (try_end),
         (party_get_slot, ":prosperity", ":center_no", slot_center_sod_local_prosperity),
         (try_begin),
           (gt, ":prosperity", 25),
           (val_sub, ":prosperity", 1),
           (party_set_slot, ":center_no", slot_center_sod_local_prosperity, ":prosperity"),
         (try_end),
       (try_end),
     (try_end),

     (try_for_parties, ":raider_party"),
       (party_is_active, ":raider_party"),
       (party_get_template_id, ":raider_template", ":raider_party"),
       (eq, ":raider_template", "pt_black_khergit_raiders"),
       (try_for_parties, ":caravan_party"),
         (party_is_active, ":caravan_party"),
         (party_get_template_id, ":caravan_template", ":caravan_party"),
         (eq, ":caravan_template", "pt_merchant_caravan"),
         (store_distance_to_party_from_party, ":caravan_dist", ":raider_party", ":caravan_party"),
         (lt, ":caravan_dist", 8),
         (party_set_ai_behavior, ":raider_party", ai_bhvr_attack_party),
         (party_set_ai_object, ":raider_party", ":caravan_party"),
         (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
         (try_begin),
           (lt, ":last_raid_report_day", ":cur_day"),
           (str_store_party_name, s22, ":caravan_party"),
           (display_message, "@Black Khergit riders have found a caravan to harry near {s22}.", 0x222222),
           (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
         (try_end),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_apply_safe_passage_to_party",
 [
   (store_script_param_1, ":party_no"),
   (faction_get_slot, ":safe_until", "fac_black_khergits", slot_faction_black_khergit_safe_passage_until),
   (store_current_hours, ":cur_hours"),
   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (gt, ":safe_until", ":cur_hours"),
     (store_sub, ":safe_hours", ":safe_until", ":cur_hours"),
     (party_set_slot, ":party_no", slot_party_ignore_player_until, ":safe_until"),
     (party_ignore_player, ":party_no", ":safe_hours"),
   (try_end),
 ]),

("sod_black_khergits_scatter_or_cleanup_patrols",
 [
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (assign, ":target_center", "p_town_18"),
   (try_end),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (party_get_template_id, ":template", ":party_no"),
     (try_begin),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (remove_party, ":party_no"),
     (else_try),
       (eq, ":template", "pt_black_khergit_raiders"),
       (party_set_slot, ":party_no", slot_party_black_khergit_origin, 0),
       (party_set_slot, ":party_no", slot_party_black_khergit_target, ":target_center"),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_raider),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":target_center"),
       (party_set_ai_patrol_radius, ":party_no", 18),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_refresh_active_parties",
 [
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (assign, ":target_center", "p_town_18"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":target_center"),
   (try_end),
   (store_current_hours, ":cur_hours"),
   (store_mod, ":hour_of_day", ":cur_hours", 24),
   (assign, ":is_night", 0),
   (try_begin),
     (this_or_next|ge, ":hour_of_day", 18),
     (lt, ":hour_of_day", 6),
     (assign, ":is_night", 1),
   (try_end),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (party_get_template_id, ":template", ":party_no"),
     (eq, ":template", "pt_black_khergit_horde_camp"),
     (assign, ":camp_party", ":party_no"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":party_no"),
   (try_end),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (party_get_template_id, ":template", ":party_no"),
     (assign, ":is_horde_party", 0),
     (try_begin),
       (eq, ":template", "pt_black_khergit_horde_camp"),
       (assign, ":is_horde_party", 1),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_camp),
       (assign, ":camp_party", ":party_no"),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":party_no"),
     (else_try),
       (eq, ":template", "pt_black_khergit_raiders"),
       (assign, ":is_horde_party", 1),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_raider),
     (else_try),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (assign, ":is_horde_party", 1),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_guard),
     (try_end),
     (eq, ":is_horde_party", 1),
     (party_set_slot, ":party_no", slot_party_black_khergit_camp_activity, 1),
     (party_set_slot, ":party_no", slot_party_black_khergit_target, ":target_center"),
     (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":party_no"),
     (try_begin),
       (eq, ":template", "pt_black_khergit_horde_camp"),
       (is_between, ":target_center", centers_begin, centers_end),
       (try_begin),
         (eq, ":is_night", 1),
         (party_set_icon, ":party_no", "icon_camp"),
       (else_try),
         (party_set_icon, ":party_no", "icon_khergit_horseman_b"),
       (try_end),
       (party_set_ai_behavior, ":party_no", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":party_no", ":target_center"),
     (else_try),
       (eq, ":template", "pt_black_khergit_raiders"),
       (is_between, ":target_center", centers_begin, centers_end),
       (try_begin),
         (gt, ":camp_party", 0),
         (party_set_slot, ":party_no", slot_party_black_khergit_origin, ":camp_party"),
       (try_end),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":target_center"),
       (party_set_ai_patrol_radius, ":party_no", 14),
     (else_try),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (gt, ":camp_party", 0),
       (party_set_slot, ":party_no", slot_party_black_khergit_origin, ":camp_party"),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":camp_party"),
       (party_set_ai_patrol_radius, ":party_no", 5),
     (else_try),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (is_between, ":target_center", centers_begin, centers_end),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":target_center"),
       (party_set_ai_patrol_radius, ":party_no", 8),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_apply_player_action",
 [
   (store_script_param_1, ":action"),
   (store_script_param_2, ":magnitude"),
   (val_max, ":magnitude", 1),
   (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
   (faction_get_slot, ":tribute", "fac_black_khergits", slot_faction_black_khergit_tribute),
  (try_begin),
    (eq, ":action", sod_black_khergit_action_tribute),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_tribute, 4),
    (call_script, "script_sod_companion_try_klethi_old_job_incident", 1, 2),
    (val_add, ":tribute", ":magnitude"),
     (val_sub, ":pressure", 3),
     (store_current_hours, ":safe_until"),
     (store_div, ":safe_hours", ":magnitude", 5),
     (val_clamp, ":safe_hours", 24, 169),
     (val_add, ":safe_until", ":safe_hours"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_safe_passage_until, ":safe_until"),
     (call_script, "script_sod_black_khergits_refresh_active_parties"),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 1),
  (else_try),
    (eq, ":action", sod_black_khergit_action_bribe_target),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_bribe, 4),
    (call_script, "script_sod_companion_try_klethi_old_job_incident", 1, 3),
    (val_add, ":tribute", ":magnitude"),
      (val_add, ":pressure", 4),
      (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 2),
      (call_script, "script_sod_black_khergits_choose_bribed_target"),
      (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
      (store_current_day, ":lock_until"),
      (val_add, ":lock_until", 7),
      (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, ":lock_until"),
  (try_begin),
    (is_between, ":target_center", centers_begin, centers_end),
    (str_store_party_name, s21, ":target_center"),
    (display_message, "@The Black Khergit Khan takes the silver. His riders turn toward {s21}, and the paid mark will hold for several days.", 0x222222),
    (store_faction_of_party, ":target_faction", ":target_center"),
        (call_script, "script_sod_diplomacy_apply_memory", ":target_faction", sod_diplomacy_memory_border_raid, 1),
      (try_end),
      (call_script, "script_sod_black_khergits_refresh_active_parties"),
    (else_try),
    (eq, ":action", sod_black_khergit_action_persuade_enemy),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_bribe, 3),
    (call_script, "script_sod_companion_try_klethi_old_job_incident", 1, 2),
    (val_add, ":pressure", 6),
      (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 1),
      (call_script, "script_sod_black_khergits_choose_enemy_target"),
      (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
      (store_current_day, ":lock_until"),
      (val_add, ":lock_until", 5),
      (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, ":lock_until"),
  (try_begin),
    (is_between, ":target_center", centers_begin, centers_end),
    (str_store_party_name, s21, ":target_center"),
    (display_message, "@Black Khergit scouts carry your enemy's name into the steppe. The horde turns toward {s21} for now.", 0x222222),
    (store_faction_of_party, ":target_faction", ":target_center"),
        (call_script, "script_sod_diplomacy_apply_memory", ":target_faction", sod_diplomacy_memory_border_raid, 1),
      (try_end),
      (call_script, "script_sod_black_khergits_refresh_active_parties"),
  (else_try),
    (eq, ":action", sod_black_khergit_action_attack_camp),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 4),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_camp_defeat, 4),
    (call_script, "script_sod_companion_try_baheshtur_saddle_incident", 2, 4),
    (val_sub, ":pressure", 30),
     (val_sub, ":tribute", ":magnitude"),
     (store_current_day, ":cur_day"),
     (store_div, ":disruption_days", ":magnitude", 5),
     (val_clamp, ":disruption_days", 7, 22),
     (val_add, ":cur_day", ":disruption_days"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until, ":cur_day"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, 0),
     (call_script, "script_sod_black_khergits_scatter_or_cleanup_patrols"),
     (display_message, "@With the Black Khergit camp broken, its night guards vanish and loose raiders scatter along the roads.", 0x222222),
     (call_script, "script_change_troop_renown", "trp_player", 12),
     (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
     (try_begin),
       (is_between, ":target_center", centers_begin, centers_end),
       (call_script, "script_change_player_relation_with_center", ":target_center", 2),
       (str_store_party_name, s21, ":target_center"),
       (display_message, "@Merchants and villagers near {s21} breathe easier: the horde's heart has been broken for now.", 0x99CCFF),
     (try_end),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", -8),
  (else_try),
    (eq, ":action", sod_black_khergit_action_defeat_raiders),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 2),
    (call_script, "script_sod_companion_try_baheshtur_saddle_incident", 1, 2),
    (val_sub, ":pressure", ":magnitude"),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", -2),
  (else_try),
    (eq, ":action", sod_black_khergit_action_defeat_guards),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 2),
    (call_script, "script_sod_companion_try_baheshtur_saddle_incident", 1, 2),
    (val_sub, ":pressure", ":magnitude"),
     (val_sub, ":tribute", 5),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", -4),
  (else_try),
    (eq, ":action", sod_black_khergit_action_duel_victory),
    (val_sub, ":pressure", 22),
    (val_sub, ":tribute", 10),
    (call_script, "script_sod_black_khergits_choose_relocation_target"),
    (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
    (store_current_day, ":lock_until"),
    (val_add, ":lock_until", 8),
    (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, ":lock_until"),
    (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, 0),
    (call_script, "script_sod_black_khergits_refresh_active_parties"),
    (call_script, "script_change_troop_renown", "trp_player", 15),
    (call_script, "script_sod_black_khergits_strengthen_khan_after_duel_loss"),
    (try_begin),
      (is_between, ":target_center", centers_begin, centers_end),
      (str_store_party_name, s21, ":target_center"),
      (display_message, "@Temujin Black Sky yields the field. The Black Khergit camp pulls its stakes and rides toward {s21}.", 0x99CCFF),
    (else_try),
      (display_message, "@Temujin Black Sky yields the field. The Black Khergit camp pulls its stakes and vanishes onto a colder road.", 0x99CCFF),
    (try_end),
    (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 10),
    (call_script, "script_sod_black_khergits_enforce_player_standing"),
  (else_try),
    (eq, ":action", sod_black_khergit_action_duel_defeat),
    (val_add, ":pressure", 8),
    (display_message, "@Temujin Black Sky leaves you breathing. The horde laughs, and its riders grow bold.", 0xCC9966),
    (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 1),
   (try_end),
   (val_clamp, ":pressure", 0, 101),
   (val_clamp, ":tribute", 0, 5000),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":pressure"),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_tribute, ":tribute"),
   (call_script, "script_sod_black_khergits_enforce_player_standing"),
   (assign, reg0, ":pressure"),
    (assign, reg1, ":tribute"),
 ]),

("sod_black_khergits_strengthen_khan_after_duel_loss",
 [
   (troop_get_slot, ":duel_losses", "trp_black_khergit_khan", slot_troop_black_khergit_khan_duel_losses),
   (val_add, ":duel_losses", 1),
   (troop_set_slot, "trp_black_khergit_khan", slot_troop_black_khergit_khan_duel_losses, ":duel_losses"),
   (store_mul, ":xp_gain", ":duel_losses", 750),
   (val_add, ":xp_gain", 2500),
   (val_clamp, ":xp_gain", 2500, 9001),
   (add_xp_to_troop, ":xp_gain", "trp_black_khergit_khan"),
   (troop_raise_attribute, "trp_black_khergit_khan", ca_strength, 1),
   (troop_raise_attribute, "trp_black_khergit_khan", ca_agility, 1),
   (try_begin),
     (store_mod, ":even_loss", ":duel_losses", 2),
     (eq, ":even_loss", 0),
     (troop_raise_attribute, "trp_black_khergit_khan", ca_charisma, 1),
     (troop_raise_skill, "trp_black_khergit_khan", "skl_tactics", 1),
   (try_end),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_ironflesh", 1),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_power_strike", 1),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_riding", 1),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_horse_archery", 1),
   (store_mul, ":prof_bonus", ":duel_losses", 2),
   (val_add, ":prof_bonus", 10),
   (val_clamp, ":prof_bonus", 10, 26),
   (troop_raise_proficiency_linear, "trp_black_khergit_khan", wpt_one_handed_weapon, ":prof_bonus"),
   (troop_raise_proficiency_linear, "trp_black_khergit_khan", wpt_polearm, ":prof_bonus"),
   (troop_raise_proficiency_linear, "trp_black_khergit_khan", wpt_archery, ":prof_bonus"),
   (assign, reg44, ":duel_losses"),
   (assign, reg45, ":xp_gain"),
   (display_message, "@Temujin Black Sky remembers defeat. His next challenge will be harder: duel scars {reg44}, experience gained {reg45}.", 0xCC9966),
 ]),

("sod_black_khergits_enforce_player_standing",
 [
   (store_relation, ":player_relation", "fac_player_supporters_faction", "fac_black_khergits"),
   (try_begin),
     (ge, ":player_relation", 100),
     (set_relation, "fac_black_khergits", "fac_player_supporters_faction", 100),
     (set_relation, "fac_black_khergits", "fac_player_faction", 100),
     (set_relation, "fac_player_supporters_faction", "fac_black_khergits", 100),
     (set_relation, "fac_player_faction", "fac_black_khergits", 100),
     (store_current_hours, ":safe_until"),
     (val_add, ":safe_until", 8760),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_safe_passage_until, ":safe_until"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, 0),
   (try_end),
 ]),

("sod_black_khergits_prepare_hire_offer",
 [
   (store_relation, ":relation", "fac_player_supporters_faction", "fac_black_khergits"),
   (val_clamp, ":relation", 0, 101),
   (store_div, ":relation_band", ":relation", 20),
   (store_random_in_range, ":random_bonus", 0, 3),
   (store_add, ":total", 2, ":relation_band"),
   (val_add, ":total", ":random_bonus"),
   (val_clamp, ":total", 2, 9),
   (store_div, ":max_guards", ":total", 3),
   (val_add, ":max_guards", 2),
   (store_random_in_range, ":guards", 0, ":max_guards"),
   (val_min, ":guards", ":total"),
   (store_sub, ":horsemen", ":total", ":guards"),
   (store_sub, ":horseman_cost", 220, ":relation"),
   (val_max, ":horseman_cost", 120),
   (store_sub, ":guard_cost", 320, ":relation"),
   (val_max, ":guard_cost", 200),
   (store_mul, ":cost", ":horsemen", ":horseman_cost"),
   (store_mul, ":guard_total", ":guards", ":guard_cost"),
   (val_add, ":cost", ":guard_total"),
   (assign, "$g_sod_black_khergit_hire_horsemen", ":horsemen"),
   (assign, "$g_sod_black_khergit_hire_guards", ":guards"),
   (assign, "$g_sod_black_khergit_hire_cost", ":cost"),
   (assign, reg40, ":horsemen"),
   (assign, reg41, ":guards"),
   (assign, reg42, ":cost"),
   (assign, reg43, ":relation"),
 ]),

("sod_black_khergits_buy_hire_offer",
 [
   (store_troop_gold, ":player_gold", "trp_player"),
   (try_begin),
     (ge, ":player_gold", "$g_sod_black_khergit_hire_cost"),
     (gt, "$g_sod_black_khergit_hire_cost", 0),
     (troop_remove_gold, "trp_player", "$g_sod_black_khergit_hire_cost"),
     (try_begin),
       (gt, "$g_sod_black_khergit_hire_horsemen", 0),
       (party_add_members, "p_main_party", "trp_black_khergit_horseman", "$g_sod_black_khergit_hire_horsemen"),
     (try_end),
     (try_begin),
       (gt, "$g_sod_black_khergit_hire_guards", 0),
       (party_add_members, "p_main_party", "trp_black_khergit_guard", "$g_sod_black_khergit_hire_guards"),
     (try_end),
     (assign, reg40, "$g_sod_black_khergit_hire_horsemen"),
     (assign, reg41, "$g_sod_black_khergit_hire_guards"),
     (assign, reg42, "$g_sod_black_khergit_hire_cost"),
     (display_message, "@Temujin Black Sky sends {reg40} horsemen and {reg41} guards to ride under your banner for {reg42} denars.", 0x99CCFF),
     (call_script, "script_sod_black_khergits_choose_relocation_target"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, 0),
     (call_script, "script_sod_black_khergits_refresh_active_parties"),
   (else_try),
     (display_message, "@The Black Khergit hire bargain cannot be completed right now.", 0xCC9966),
   (try_end),
   (assign, "$g_sod_black_khergit_hire_horsemen", 0),
   (assign, "$g_sod_black_khergit_hire_guards", 0),
   (assign, "$g_sod_black_khergit_hire_cost", 0),
 ]),

("sod_black_khergits_choose_relocation_target",
 [
   (assign, ":best_center", 0),
   (assign, ":best_score", -100000),
   (try_for_range, ":center_no", centers_begin, centers_end),
     (store_faction_of_party, ":center_faction", ":center_no"),
     (neq, ":center_faction", "fac_player_supporters_faction"),
     (neq, ":center_faction", "fac_player_faction"),
     (try_begin),
       (gt, "$players_kingdom", 0),
       (neq, ":center_faction", "$players_kingdom"),
     (try_end),
     (neg|party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
     (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
     (store_distance_to_party_from_party, ":dist", "p_main_party", ":center_no"),
     (assign, ":score", ":dist"),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (store_div, ":prosperity_score", ":prosperity", 2),
     (val_add, ":score", ":prosperity_score"),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),
   (try_begin),
     (neg|is_between, ":best_center", centers_begin, centers_end),
     (assign, ":best_center", "p_town_18"),
   (try_end),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":best_center"),
   (assign, reg0, ":best_center"),
 ]),

("sod_black_khergits_resolve_khan_duel",
 [
   (store_script_param_1, ":result"),
   (try_begin),
     (eq, ":result", 1),
     (call_script, "script_sod_black_khergits_apply_player_action", sod_black_khergit_action_duel_victory, 1),
   (else_try),
     (call_script, "script_sod_black_khergits_apply_player_action", sod_black_khergit_action_duel_defeat, 1),
   (try_end),
   (assign, "$g_sod_black_khergit_duel_active", 0),
 ]),

("sod_black_khergits_update_scout_intelligence",
 [
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (store_current_day, ":cur_day"),
   (faction_get_slot, ":last_seen_day", "fac_black_khergits", slot_faction_black_khergit_last_seen_day),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (store_distance_to_party_from_party, ":dist", "p_main_party", ":camp_party"),
     (assign, ":spotting_range", 18),
     (party_get_skill_level, ":spotting", "p_main_party", skl_spotting),
     (party_get_skill_level, ":tracking", "p_main_party", skl_tracking),
     (store_add, ":fieldcraft", ":spotting", ":tracking"),
     (val_mul, ":fieldcraft", 4),
     (val_add, ":spotting_range", ":fieldcraft"),
     (try_begin),
       (main_party_has_troop, "trp_npc1"),
       (troop_slot_eq, "trp_npc1", slot_troop_companion_role, sod_companion_role_scout),
       (val_add, ":spotting_range", 12),
     (try_end),
     (try_begin),
       (main_party_has_troop, "trp_npc7"),
       (this_or_next|troop_slot_eq, "trp_npc7", slot_troop_companion_role, sod_companion_role_scout),
       (troop_slot_eq, "trp_npc7", slot_troop_companion_role, sod_companion_role_spymaster),
       (val_add, ":spotting_range", 10),
     (try_end),
     (le, ":dist", ":spotting_range"),
     (call_script, "script_get_closest_center", ":camp_party"),
     (assign, ":seen_center", reg0),
     (is_between, ":seen_center", centers_begin, centers_end),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_seen_center, ":seen_center"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_seen_day, ":cur_day"),
     (try_begin),
       (lt, ":last_seen_day", ":cur_day"),
       (str_store_party_name, s21, ":seen_center"),
       (try_begin),
         (main_party_has_troop, "trp_npc7"),
         (display_message, "@Deshavi finds steppe ash and tether marks: the Black Khergit camp was last seen near {s21}.", 0x99CCFF),
       (else_try),
         (main_party_has_troop, "trp_npc1"),
         (display_message, "@Borcha reads the road dirt: the Black Khergit camp was last seen near {s21}.", 0x99CCFF),
       (else_try),
         (display_message, "@Your scouts mark Black Khergit camp signs near {s21}.", 0x99CCFF),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_process_scattered_raider_aftermath",
 [
   (store_current_day, ":cur_day"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (faction_get_slot, ":disrupted_until", "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until),
   (try_begin),
     (this_or_next|le, ":camp_party", 0),
     (gt, ":disrupted_until", ":cur_day"),
     (try_for_parties, ":party_no"),
       (party_is_active, ":party_no"),
       (party_get_template_id, ":template", ":party_no"),
       (eq, ":template", "pt_black_khergit_raiders"),
       (party_slot_eq, ":party_no", slot_party_black_khergit_origin, 0),
       (party_get_num_companions, ":size", ":party_no"),
       (try_begin),
         (le, ":size", 10),
         (remove_party, ":party_no"),
       (else_try),
         (call_script, "script_cf_party_remove_random_regular_troop", ":party_no"),
         (try_begin),
           (gt, ":size", 20),
           (call_script, "script_cf_party_remove_random_regular_troop", ":party_no"),
         (try_end),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_choose_bribed_target",
 [
   (assign, ":best_center", 0),
   (assign, ":best_score", 0),
   (try_for_range, ":center_no", towns_begin, towns_end),
     (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
     (assign, ":score", ":prosperity"),
     (store_div, ":wealth_score", ":wealth", 60),
     (val_add, ":score", ":wealth_score"),
     (try_for_parties, ":caravan_party"),
       (party_is_active, ":caravan_party"),
       (party_get_template_id, ":caravan_template", ":caravan_party"),
       (eq, ":caravan_template", "pt_merchant_caravan"),
       (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":center_no"),
       (le, ":road_dist", 18),
       (val_add, ":score", 4),
     (try_end),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),
   (try_begin),
     (gt, ":best_center", 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":best_center"),
   (try_end),
 ]),

("sod_black_khergits_choose_enemy_target",
 [
   (assign, ":best_center", 0),
   (assign, ":best_score", 0),
   (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
     (store_faction_of_party, ":center_faction", ":center_no"),
     (assign, ":valid_enemy", 0),
     (try_begin),
       (gt, "$players_kingdom", 0),
       (store_relation, ":relation", "$players_kingdom", ":center_faction"),
       (lt, ":relation", 0),
       (assign, ":valid_enemy", 1),
     (else_try),
       (store_relation, ":relation", "fac_player_faction", ":center_faction"),
       (lt, ":relation", 0),
       (assign, ":valid_enemy", 1),
     (try_end),
     (eq, ":valid_enemy", 1),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
     (assign, ":score", ":prosperity"),
     (store_div, ":wealth_score", ":wealth", 80),
     (val_add, ":score", ":wealth_score"),
     (try_for_parties, ":caravan_party"),
       (party_is_active, ":caravan_party"),
       (party_get_template_id, ":caravan_template", ":caravan_party"),
       (eq, ":caravan_template", "pt_merchant_caravan"),
       (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":center_no"),
       (le, ":road_dist", 18),
       (val_add, ":score", 4),
     (try_end),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),
   (try_begin),
     (gt, ":best_center", 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":best_center"),
   (try_end),
 ]),

("sod_black_khergits_describe_status_to_s27",
 [
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (store_num_parties_of_template, reg21, "pt_black_khergit_raiders"),
   (store_num_parties_of_template, reg22, "pt_black_khergit_night_guard"),
   (store_num_parties_of_template, reg23, "pt_black_khergit_horde_camp"),
   (faction_get_slot, reg24, "fac_black_khergits", slot_faction_black_khergit_pressure),
   (faction_get_slot, reg25, "fac_black_khergits", slot_faction_black_khergit_tribute),
  (faction_get_slot, reg26, "fac_black_khergits", slot_faction_black_khergit_last_migration_day),
  (store_relation, reg27, "fac_player_supporters_faction", "fac_black_khergits"),
  (str_store_string, s22, "@no formal standing"),
  (try_begin),
    (ge, reg27, 100),
    (str_store_string, s22, "@blood-respected"),
  (else_try),
    (ge, reg27, 20),
    (str_store_string, s22, "@trusted"),
  (else_try),
    (ge, reg27, 5),
    (str_store_string, s22, "@friendly"),
  (else_try),
    (le, reg27, -20),
    (str_store_string, s22, "@hostile"),
  (else_try),
    (le, reg27, -5),
    (str_store_string, s22, "@wary"),
  (try_end),
  (faction_get_slot, ":safe_until", "fac_black_khergits", slot_faction_black_khergit_safe_passage_until),
   (faction_get_slot, reg29, "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until),
   (faction_get_slot, reg30, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
   (faction_get_slot, ":lock_until", "fac_black_khergits", slot_faction_black_khergit_target_lock_until),
   (store_current_day, ":cur_day"),
   (assign, reg31, 0),
   (try_begin),
     (gt, reg29, ":cur_day"),
     (store_sub, reg31, reg29, ":cur_day"),
   (try_end),
   (assign, reg32, 0),
   (str_store_string, s23, "@The horde's mark is not bound by payment or pressure."),
   (try_begin),
     (gt, ":lock_until", ":cur_day"),
     (store_sub, reg32, ":lock_until", ":cur_day"),
     (str_store_string, s23, "@The current mark is locked by recent silver or persuasion for {reg32} more days."),
   (try_end),
   (store_current_hours, ":cur_hours"),
   (assign, reg28, 0),
   (try_begin),
     (gt, ":safe_until", ":cur_hours"),
     (store_sub, reg28, ":safe_until", ":cur_hours"),
   (try_end),
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (call_script, "script_sod_store_center_name_or_fallback_to_s21", ":target_center", "@no confirmed rich road"),
  (faction_get_slot, ":last_seen_center", "fac_black_khergits", slot_faction_black_khergit_last_seen_center),
  (faction_get_slot, reg33, "fac_black_khergits", slot_faction_black_khergit_last_seen_day),
  (str_store_string, s24, "@no reliable last sighting"),
  (try_begin),
    (is_between, ":last_seen_center", centers_begin, centers_end),
    (str_store_party_name_link, s24, ":last_seen_center"),
  (try_end),
  (str_store_string, s27, "@^Black Khergit horde: {reg23} camp, {reg21} raider bands, {reg22} night guards. Horde pressure {reg24}; tribute {reg25}; current mark {s21}; last seen near {s24} on day {reg33}; last migration day {reg26}; your standing {s22} ({reg27}); safe-passage hours {reg28}; camp disrupted until day {reg29} ({reg31} days remaining); last reported raid day {reg30}. {s23} Raiders range around the mark; night guards cling to the camp. If the camp is broken, guards vanish and loose raiders scatter until the horde reforms."),
  (str_clear, s22),
  (str_clear, s23),
  (str_clear, s24),
 ]),
]
