# COST: low
SCRIPTS = [
("sod_merc_market_calculate_renewal_price",
 [
   (store_script_param_1, ":party_no"),

   (assign, ":renewal_price", 0),
   (assign, ":term_days", 30),
   (assign, ":refusal_reason", sod_merc_refusal_none),

   (try_begin),
     (party_is_active, ":party_no"),
     (party_get_slot, ":party_type", ":party_no", slot_party_type),
     (this_or_next|eq, ":party_type", spt_ai_mercenaries),
     (eq, ":party_type", spt_mercenary_lord_party),
     (party_get_slot, ":guild_faction", ":party_no", slot_party_sod_merc_contract_guild),
     (try_begin),
       (neg|is_between, ":guild_faction", guilds_begin, guilds_end),
       (party_get_slot, ":guild_faction", ":party_no", slot_party_orginal_faction),
     (try_end),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (call_script, "script_sod_merc_market_calculate_guild_supply", ":guild_faction", 0),
     (assign, ":price_pressure", reg3),
     (assign, ":long_contract_willingness", reg4),
     (assign, ":danger_willingness", reg5),
     (assign, ":refusal_reason", reg6),
     (neq, ":refusal_reason", sod_merc_refusal_overextended),
     (neq, ":refusal_reason", sod_merc_refusal_low_manpower),
     (neq, ":refusal_reason", sod_merc_refusal_loss_shock),

     (party_get_num_companions, ":party_size", ":party_no"),
     (party_get_slot, ":role", ":party_no", slot_party_sod_merc_contract_role),
     (try_begin),
       (le, ":role", sod_merc_contract_role_none),
       (assign, ":role", sod_merc_contract_role_field_company),
     (try_end),
     (store_mul, ":renewal_price", ":party_size", 10),
     (try_begin),
       (eq, ":role", sod_merc_contract_role_field_company),
       (val_mul, ":renewal_price", 120),
       (val_div, ":renewal_price", 100),
       (assign, ":term_days", 30),
     (else_try),
       (eq, ":role", sod_merc_contract_role_garrison_support),
       (val_mul, ":renewal_price", 110),
       (val_div, ":renewal_price", 100),
       (assign, ":term_days", 25),
     (else_try),
       (eq, ":role", sod_merc_contract_role_patrol),
       (assign, ":term_days", 20),
     (else_try),
       (eq, ":role", sod_merc_contract_role_special_world_activity),
       (val_mul, ":renewal_price", 115),
       (val_div, ":renewal_price", 100),
       (assign, ":term_days", 20),
     (try_end),
     (val_mul, ":renewal_price", ":price_pressure"),
     (val_div, ":renewal_price", 100),
     (try_begin),
       (lt, ":long_contract_willingness", 35),
       (val_mul, ":renewal_price", 115),
       (val_div, ":renewal_price", 100),
     (try_end),
     (try_begin),
       (lt, ":danger_willingness", 35),
       (eq, ":role", sod_merc_contract_role_field_company),
       (val_mul, ":renewal_price", 115),
       (val_div, ":renewal_price", 100),
     (try_end),
     (val_max, ":renewal_price", 250),
   (try_end),

   (assign, reg0, ":renewal_price"),
   (assign, reg1, ":term_days"),
   (assign, reg2, ":refusal_reason"),
 ]),
]
