# COST: medium
SCRIPTS = [
("sod_merc_market_calculate_kingdom_guild_weight",
 [
   (store_script_param_1, ":kingdom_faction"),
   (store_script_param_2, ":guild_faction"),
   (store_script_param, ":use_cached_contract_totals", 3),
   (store_script_param, ":demand_type", 4),

   (assign, ":weight", -100),
   (assign, ":service_days", 0),
   (assign, ":contract_value", 0),
   (assign, ":contract_losses", 0),
   (assign, ":active_contracts", 0),
   (assign, ":role_fit", 0),

   (try_begin),
     (is_between, ":kingdom_faction", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":kingdom_faction", slot_faction_state, sfs_active),
     (is_between, ":guild_faction", guilds_begin, guilds_end),

     (store_relation, ":stored_relation", ":kingdom_faction", ":guild_faction"),
     (store_div, ":weight", ":stored_relation", 2),

     (try_begin),
       (gt, ":use_cached_contract_totals", 0),
       (store_sub, ":guild_offset", ":guild_faction", guilds_begin),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_service_days_cache_begin, ":guild_offset"),
       (faction_get_slot, ":service_days", ":kingdom_faction", ":cache_slot"),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_value_cache_begin, ":guild_offset"),
       (faction_get_slot, ":contract_value", ":kingdom_faction", ":cache_slot"),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_loss_cache_begin, ":guild_offset"),
       (faction_get_slot, ":contract_losses", ":kingdom_faction", ":cache_slot"),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_count_cache_begin, ":guild_offset"),
       (faction_get_slot, ":active_contracts", ":kingdom_faction", ":cache_slot"),
       (val_max, ":service_days", 0),
       (val_max, ":contract_value", 0),
       (val_max, ":contract_losses", 0),
       (val_max, ":active_contracts", 0),
     (else_try),
       (store_current_day, ":cur_day"),
       (try_for_parties, ":party_no"),
         (party_is_active, ":party_no"),
         (party_slot_eq, ":party_no", slot_party_sod_merc_contract_employer, ":kingdom_faction"),
         (party_slot_eq, ":party_no", slot_party_sod_merc_contract_guild, ":guild_faction"),
         (party_get_slot, ":start_day", ":party_no", slot_party_sod_merc_contract_start_day),
         (party_get_slot, ":value", ":party_no", slot_party_sod_merc_contract_value),
         (party_get_slot, ":loss_score", ":party_no", slot_party_sod_merc_contract_loss_score),
         (val_max, ":start_day", 0),
         (val_max, ":value", 0),
         (val_max, ":loss_score", 0),
         (store_sub, ":days", ":cur_day", ":start_day"),
         (val_max, ":days", 0),
         (val_add, ":service_days", ":days"),
         (val_add, ":contract_value", ":value"),
         (val_add, ":contract_losses", ":loss_score"),
         (val_add, ":active_contracts", 1),
       (try_end),
     (try_end),

     (store_div, ":time_score", ":service_days", 5),
     (val_add, ":weight", ":time_score"),
     (store_div, ":money_score", ":contract_value", 350),
     (val_add, ":weight", ":money_score"),
     (store_mul, ":active_score", ":active_contracts", 4),
     (val_add, ":weight", ":active_score"),
     (store_mul, ":loss_penalty", ":contract_losses", 2),
     (val_sub, ":weight", ":loss_penalty"),

     # Relationship and prior service decide trust; role fit decides whether this
     # company is useful for the employer's present problem.
     (call_script, "script_sod_merc_market_calculate_guild_role_fit", ":guild_faction", ":demand_type"),
     (assign, ":role_fit", reg0),
     (val_add, ":weight", ":role_fit"),

     (faction_get_slot, ":economic_strength", ":kingdom_faction", slot_faction_economic_strength),
     (val_max, ":economic_strength", 0),
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild2"),
       (ge, ":economic_strength", 45),
       (val_add, ":weight", 8),
     (try_end),

     (faction_get_slot, ":slavery_policy", ":kingdom_faction", slot_faction_diplomacy_policy_slavery),
     (try_begin),
       (le, ":slavery_policy", 0),
       (assign, ":slavery_policy", sod_diplomacy_policy_slavery_tolerated),
     (try_end),
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild3"),
       (faction_get_slot, ":slaver_alarm", "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),
       (ge, ":slaver_alarm", 25),
       (this_or_next|eq, ":slavery_policy", sod_diplomacy_policy_slavery_banned),
       (eq, ":slavery_policy", sod_diplomacy_policy_slavery_tolerated),
       (val_add, ":weight", 12),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       (eq, ":slavery_policy", sod_diplomacy_policy_slavery_banned),
       (val_sub, ":weight", 18),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       (this_or_next|eq, ":slavery_policy", sod_diplomacy_policy_slavery_regulated),
       (eq, ":slavery_policy", sod_diplomacy_policy_slavery_accepted),
       (val_add, ":weight", 10),
     (try_end),

     (try_begin),
       (faction_slot_eq, ":kingdom_faction", slot_faction_merc_pact, ":guild_faction"),
       (val_add, ":weight", 10),
     (try_end),
     (val_clamp, ":weight", -100, 101),
   (try_end),

   (assign, reg0, ":weight"),
   (assign, reg1, ":service_days"),
   (assign, reg2, ":contract_value"),
   (assign, reg3, ":contract_losses"),
   (assign, reg4, ":role_fit"),
 ]),
]
