# COST: light to moderate
SCRIPTS = [
("sod_trade_network_validate_center_to_reg",
 [
   (store_script_param_1, ":center_no"),
   (store_script_param_2, ":fallback_center"),
   (assign, reg0, ":center_no"),
   (try_begin),
     (neg|is_between, reg0, centers_begin, centers_end),
     (assign, reg0, ":fallback_center"),
   (try_end),
   (try_begin),
     (neg|is_between, reg0, centers_begin, centers_end),
     (assign, reg0, "p_town_1"),
   (try_end),
 ]),

("sod_trade_network_get_route_pressure_to_regs",
 [
   (faction_get_slot, reg10, "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure),
   (faction_get_slot, reg11, "fac_black_khergits", slot_faction_black_khergit_pressure),
   (faction_get_slot, reg12, "fac_sod_merc_guild5", slot_faction_serpent_route_pressure),
   (faction_get_slot, reg13, "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
   (faction_get_slot, reg14, "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (faction_get_slot, reg15, "fac_sod_merc_guild4", slot_faction_jotnar_hearth_pressure),
   (faction_get_slot, reg16, "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),
 ]),

("sod_trade_network_initialize_caravan",
 [
   (store_script_param_1, ":party_no"),
   (try_begin),
     (gt, ":party_no", 0),
     (neg|party_slot_ge, ":party_no", slot_party_sod_trade_destination, 1),
     (call_script, "script_get_closest_center", ":party_no"),
     (assign, ":origin", reg0),
     (get_party_ai_object, ":destination", ":party_no"),
     (call_script, "script_sod_trade_network_validate_center_to_reg", ":origin", ":destination"),
     (assign, ":origin", reg0),
     (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":origin"),
     (assign, ":destination", reg0),
     (party_set_slot, ":party_no", slot_party_sod_trade_origin, ":origin"),
     (party_set_slot, ":party_no", slot_party_sod_trade_destination, ":destination"),
     (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":destination"),
     (assign, ":cargo_focus", reg0),
     (party_set_slot, ":party_no", slot_party_sod_trade_cargo_focus, ":cargo_focus"),
     (call_script, "script_sod_trade_network_evaluate_route", ":origin", ":destination"),
     (party_set_slot, ":party_no", slot_party_sod_trade_route_risk, reg0),
     (party_set_slot, ":party_no", slot_party_sod_trade_recent_trouble, reg1),
     (party_set_slot, ":party_no", slot_party_sod_trade_last_result, sod_trade_result_none),
   (try_end),
   (try_begin),
     (gt, ":party_no", 0),
     (neg|party_slot_ge, ":party_no", slot_party_sod_trade_player_trust, 1),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_trust, 50),
     (store_current_day, ":cur_day"),
     (store_mul, ":seed", ":party_no", 17),
     (val_add, ":seed", ":cur_day"),
     (party_set_slot, ":party_no", slot_party_sod_trade_captain_seed, ":seed"),
     (store_mod, ":house_style", ":seed", 4),
     (party_set_slot, ":party_no", slot_party_sod_trade_house_style, ":house_style"),
     (party_set_slot, ":party_no", slot_party_sod_trade_route_reputation, sod_trade_result_none),
   (try_end),
 ]),

("sod_trade_network_evaluate_route",
 [
   (store_script_param_1, ":origin"),
   (store_script_param_2, ":destination"),
   (assign, ":risk", 15),
   (assign, ":trouble", sod_trade_route_safe),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":origin", ":destination"),
   (assign, ":origin", reg0),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":origin"),
   (assign, ":destination", reg0),
   (try_begin),
     (is_between, ":origin", centers_begin, centers_end),
     (is_between, ":destination", centers_begin, centers_end),
     (store_distance_to_party_from_party, ":route_distance", ":origin", ":destination"),
     (store_div, ":distance_risk", ":route_distance", 10),
     (val_add, ":risk", ":distance_risk"),
   (try_end),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (call_script, "script_sod_center_public_health_compute_causes", ":destination"),
     (party_get_slot, ":destination_health", ":destination", slot_center_sod_local_health),
     (party_get_slot, ":disease_risk", ":destination", slot_center_health_disease_risk),
     (party_get_slot, ":outbreak", ":destination", slot_center_health_outbreak_type),
     (party_get_slot, ":severity", ":destination", slot_center_health_outbreak_severity),
     (party_get_slot, ":quarantine", ":destination", slot_center_health_quarantine),
     (try_begin),
       (lt, ":destination_health", 15),
       (store_sub, ":health_risk", 25, ":destination_health"),
       (val_add, ":risk", ":health_risk"),
     (else_try),
       (ge, ":destination_health", 55),
       (val_sub, ":risk", 4),
     (try_end),
     (try_begin),
       (gt, ":outbreak", sod_outbreak_none),
       (store_div, ":outbreak_risk", ":severity", 3),
       (val_add, ":outbreak_risk", 8),
       (val_add, ":risk", ":outbreak_risk"),
       (assign, ":trouble", sod_trade_route_sickness),
     (else_try),
       (ge, ":disease_risk", 60),
       (store_sub, ":disease_route_risk", ":disease_risk", 45),
       (val_div, ":disease_route_risk", 2),
       (val_add, ":risk", ":disease_route_risk"),
       (assign, ":trouble", sod_trade_route_sickness),
     (try_end),
     (try_begin),
       (gt, ":quarantine", 0),
       (val_add, ":risk", 8),
       (assign, ":trouble", sod_trade_route_sickness),
     (try_end),
     (call_script, "script_sod_get_center_trade_demand_profile", ":destination"),
     (assign, ":scarcity", reg0),
     (assign, ":import_demand", reg1),
     (assign, ":security_willingness", reg4),
     (assign, ":caravan_attractiveness", reg6),
     (store_div, ":scarcity_risk", ":scarcity", 12),
     (val_add, ":risk", ":scarcity_risk"),
     (store_sub, ":security_drag", 80, ":security_willingness"),
     (val_max, ":security_drag", 0),
     (val_div, ":security_drag", 3),
     (val_add, ":risk", ":security_drag"),
     (try_begin),
       (ge, ":scarcity", 120),
       (assign, ":trouble", sod_trade_route_starving),
     (else_try),
       (ge, ":caravan_attractiveness", 130),
       (assign, ":trouble", sod_trade_route_luxury),
     (else_try),
       (ge, ":import_demand", 90),
       (assign, ":trouble", sod_trade_route_grain),
     (try_end),
     (try_begin),
       (gt, ":outbreak", sod_outbreak_none),
       (assign, ":trouble", sod_trade_route_sickness),
     (else_try),
       (gt, ":quarantine", 0),
       (assign, ":trouble", sod_trade_route_sickness),
     (else_try),
       (ge, ":disease_risk", 60),
       (assign, ":trouble", sod_trade_route_sickness),
     (try_end),
   (try_end),
   (call_script, "script_sod_trade_network_get_route_pressure_to_regs"),
   (assign, ":boar_pressure", reg10),
   (assign, ":horde_pressure", reg11),
   (assign, ":serpent_pressure", reg12),
   (assign, ":black_army_heat", reg13),
   (assign, ":slaver_heat", reg14),
   (assign, ":jotnar_pressure", reg15),
   (assign, ":elephant_alarm", reg16),
   (store_div, ":boar_risk", ":boar_pressure", 8),
   (store_div, ":horde_risk", ":horde_pressure", 7),
   (store_div, ":serpent_warning", ":serpent_pressure", 12),
   (store_div, ":black_army_cover", ":black_army_heat", 14),
   (store_div, ":slaver_risk", ":slaver_heat", 12),
   (store_div, ":jotnar_cover", ":jotnar_pressure", 18),
   (store_div, ":elephant_cover", ":elephant_alarm", 18),
   (val_add, ":risk", ":boar_risk"),
   (val_add, ":risk", ":horde_risk"),
   (val_add, ":risk", ":serpent_warning"),
   (val_add, ":risk", ":slaver_risk"),
   (val_sub, ":risk", ":black_army_cover"),
   (val_sub, ":risk", ":jotnar_cover"),
   (val_sub, ":risk", ":elephant_cover"),
   (try_begin),
     (ge, ":boar_pressure", 55),
     (assign, ":trouble", sod_trade_route_toll),
   (else_try),
     (ge, ":horde_pressure", 55),
     (assign, ":trouble", sod_trade_route_raider),
   (else_try),
     (ge, ":serpent_pressure", 45),
     (assign, ":trouble", sod_trade_route_watched),
   (try_end),
   (val_clamp, ":risk", 0, 101),
   (assign, reg0, ":risk"),
   (assign, reg1, ":trouble"),
 ]),

("sod_trade_network_get_contract_terms_to_regs",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":contract"),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
   (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
   (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
   (party_get_slot, ":cargo_focus", ":party_no", slot_party_sod_trade_cargo_focus),
   (assign, ":cost", 400),
   (assign, ":expected_return", 0),
   (try_begin),
     (eq, ":contract", sod_trade_contract_guards),
     (assign, ":cost", 350),
     (store_div, ":risk_cost", ":risk", 4),
     (val_add, ":cost", ":risk_cost"),
   (else_try),
     (eq, ":contract", sod_trade_contract_cargo_space),
     (assign, ":cost", 500),
     (try_begin),
       (is_between, ":destination", centers_begin, centers_end),
       (call_script, "script_sod_get_center_trade_demand_profile", ":destination"),
       (assign, ":scarcity", reg0),
       (assign, ":import_demand", reg1),
       (store_div, ":demand_cost", ":scarcity", 8),
       (val_add, ":cost", ":demand_cost"),
       (store_div, ":import_cost", ":import_demand", 8),
       (val_add, ":cost", ":import_cost"),
     (try_end),
     (try_begin),
       (eq, ":cargo_focus", sod_trade_cargo_luxury),
       (val_add, ":cost", 125),
     (else_try),
       (eq, ":cargo_focus", sod_trade_cargo_strategic),
       (val_add, ":cost", 75),
     (try_end),
   (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
     (assign, ":cost", 180),
     (store_div, ":risk_cost", ":risk", 2),
     (val_add, ":cost", ":risk_cost"),
   (else_try),
     (eq, ":contract", sod_trade_contract_relief),
     (assign, ":cost", 500),
     (try_begin),
       (is_between, ":destination", centers_begin, centers_end),
       (call_script, "script_sod_center_public_health_compute_causes", ":destination"),
       (party_get_slot, ":disease_risk", ":destination", slot_center_health_disease_risk),
       (party_get_slot, ":outbreak", ":destination", slot_center_health_outbreak_type),
       (party_get_slot, ":severity", ":destination", slot_center_health_outbreak_severity),
       (party_get_slot, ":quarantine", ":destination", slot_center_health_quarantine),
       (store_div, ":disease_cost", ":disease_risk", 3),
       (val_add, ":cost", ":disease_cost"),
       (try_begin),
         (gt, ":outbreak", sod_outbreak_none),
         (store_mul, ":outbreak_cost", ":severity", 4),
         (val_add, ":cost", ":outbreak_cost"),
       (try_end),
       (try_begin),
         (gt, ":quarantine", 0),
         (val_add, ":cost", 80),
       (try_end),
     (try_end),
   (else_try),
     (eq, ":contract", sod_trade_contract_profit),
     (assign, ":cost", 650),
     (store_div, ":risk_cost", ":risk", 3),
     (val_sub, ":cost", ":risk_cost"),
   (try_end),
   (try_begin),
     (ge, ":trust", 70),
     (val_mul, ":cost", 9),
     (val_div, ":cost", 10),
   (else_try),
     (le, ":trust", 35),
     (val_mul, ":cost", 6),
     (val_div, ":cost", 5),
   (try_end),
   (val_clamp, ":cost", 150, 1500),
   (try_begin),
     (eq, ":contract", sod_trade_contract_cargo_space),
     (store_mul, ":expected_return", ":cost", 6),
     (val_div, ":expected_return", 5),
   (else_try),
     (eq, ":contract", sod_trade_contract_profit),
     (store_mul, ":expected_return", ":cost", 7),
     (val_div, ":expected_return", 5),
   (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
     (store_mul, ":expected_return", ":cost", 2),
   (try_end),
   (assign, reg0, ":cost"),
   (assign, reg1, ":expected_return"),
   (assign, reg2, ":risk"),
   (assign, reg3, ":trust"),
 ]),

("sod_trade_network_describe_center_identity_to_s23",
 [
   (store_script_param_1, ":center_no"),
   (assign, ":cargo_focus", sod_trade_cargo_unknown),
   (str_store_string, s23, "@ordinary market"),
   (try_begin),
     (eq, ":center_no", "p_town_1"),
     (assign, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s23, "@northern grain harbor"),
   (else_try),
     (eq, ":center_no", "p_town_2"),
     (assign, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s23, "@cattle and butter market"),
   (else_try),
     (eq, ":center_no", "p_town_3"),
     (assign, ":cargo_focus", sod_trade_cargo_strategic),
     (str_store_string, s23, "@iron and tool market"),
   (else_try),
     (eq, ":center_no", "p_town_4"),
     (assign, ":cargo_focus", sod_trade_cargo_luxury),
     (str_store_string, s23, "@busy caravan hub"),
   (else_try),
     (eq, ":center_no", "p_town_5"),
     (assign, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s23, "@thin-stored frontier market"),
   (else_try),
     (eq, ":center_no", "p_town_6"),
     (assign, ":cargo_focus", sod_trade_cargo_luxury),
     (str_store_string, s23, "@velvet and spice court"),
   (else_try),
     (eq, ":center_no", "p_town_10"),
     (assign, ":cargo_focus", sod_trade_cargo_raw),
     (str_store_string, s23, "@wool and hide country"),
   (else_try),
     (eq, ":center_no", "p_town_14"),
     (assign, ":cargo_focus", sod_trade_cargo_strategic),
     (str_store_string, s23, "@salt-road fortress market"),
   (else_try),
     (gt, ":center_no", 0),
     (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
     (assign, ":food_balance", reg0),
     (assign, ":raw_balance", reg1),
     (assign, ":strategic_balance", reg2),
     (assign, ":luxury_flow", reg3),
     (assign, ":scarcity", reg4),
     (assign, ":liquidity", reg6),
     (try_begin),
       (ge, ":scarcity", 150),
       (assign, ":cargo_focus", sod_trade_cargo_food),
       (str_store_string, s23, "@starving market"),
     (else_try),
       (ge, ":luxury_flow", 45),
       (assign, ":cargo_focus", sod_trade_cargo_luxury),
       (str_store_string, s23, "@luxury sink"),
     (else_try),
       (ge, ":strategic_balance", 45),
       (assign, ":cargo_focus", sod_trade_cargo_strategic),
       (str_store_string, s23, "@strategic depot"),
     (else_try),
       (ge, ":raw_balance", 55),
       (assign, ":cargo_focus", sod_trade_cargo_raw),
       (str_store_string, s23, "@raw-goods market"),
     (else_try),
       (ge, ":food_balance", 55),
       (assign, ":cargo_focus", sod_trade_cargo_food),
       (str_store_string, s23, "@grain root"),
     (else_try),
       (ge, ":liquidity", 90),
       (assign, ":cargo_focus", sod_trade_cargo_luxury),
       (str_store_string, s23, "@caravan hub"),
     (try_end),
   (try_end),
   (assign, reg0, ":cargo_focus"),
 ]),

("sod_trade_network_describe_route_to_s22",
 [
   (store_script_param_1, ":party_no"),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (party_get_slot, ":origin", ":party_no", slot_party_sod_trade_origin),
   (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
   (call_script, "script_sod_trade_network_evaluate_route", ":origin", ":destination"),
   (assign, ":risk", reg0),
   (assign, ":route_label", reg1),
   (party_set_slot, ":party_no", slot_party_sod_trade_route_risk, ":risk"),
   (party_set_slot, ":party_no", slot_party_sod_trade_recent_trouble, ":route_label"),
   (assign, reg22, ":risk"),
   (str_store_string, s22, "@The road is quiet enough for honest wagons."),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (call_script, "script_sod_center_public_health_compute_causes", ":destination"),
     (party_get_slot, ":destination_health", ":destination", slot_center_sod_local_health),
     (party_get_slot, ":outbreak", ":destination", slot_center_health_outbreak_type),
     (party_get_slot, ":severity", ":destination", slot_center_health_outbreak_severity),
     (party_get_slot, ":quarantine", ":destination", slot_center_health_quarantine),
     (try_begin),
       (gt, ":outbreak", sod_outbreak_none),
       (call_script, "script_sod_center_public_health_outbreak_name_to_s0", ":outbreak"),
       (str_store_string_reg, s29, s0),
       (assign, reg29, ":severity"),
       (str_store_string, s22, "@The market ahead has {s29}. Severity is spoken of as {reg29}; drivers want clean water, healer writs, and hazard coin."),
     (else_try),
       (gt, ":quarantine", 0),
       (str_store_string, s22, "@The destination is under quarantine. Cargo can still matter there, but gates, guards, and fear slow every wheel."),
     (else_try),
       (lt, ":destination_health", 12),
     (str_store_string, s22, "@The market ahead has sickness in the talk. Some drivers will not unload without extra coin and clean water."),
     (else_try),
       (eq, ":route_label", sod_trade_route_sickness),
       (str_store_string, s22, "@The destination is not in open crisis, but sickness is close enough that careful caravans charge for clean handling."),
     (try_end),
   (else_try),
     (eq, ":route_label", sod_trade_route_toll),
     (str_store_string, s22, "@Boar tolls have made this road ugly. Expect hazard silver and hard words at the crossings."),
   (else_try),
     (eq, ":route_label", sod_trade_route_raider),
     (str_store_string, s22, "@Rich roads draw Black Khergit eyes. A fast escort is worth more than a pretty writ."),
   (else_try),
     (eq, ":route_label", sod_trade_route_watched),
     (str_store_string, s22, "@Serpent scouts are whispering over this route. That means warnings, but also trouble worth warning about."),
   (else_try),
     (eq, ":route_label", sod_trade_route_luxury),
     (str_store_string, s22, "@This is a luxury artery. The profit is good, and so is the smell of blood around it."),
   (else_try),
     (eq, ":route_label", sod_trade_route_grain),
     (str_store_string, s22, "@This is a grain road. Hungry markets are pulling carts this way."),
   (else_try),
     (eq, ":route_label", sod_trade_route_starving),
     (str_store_string, s22, "@The destination is thin on stores. Relief cargo would matter there."),
   (else_try),
     (eq, ":route_label", sod_trade_route_sickness),
     (str_store_string, s22, "@The destination has sickness in the road gossip. Relief cargo and careful unloading matter there."),
   (try_end),
   (call_script, "script_sod_trade_network_get_route_pressure_to_regs"),
   (try_begin),
     (ge, reg14, 45),
     (str_store_string, s22, "@There is captive traffic somewhere near the road. Honest wagons avoid chains when they can."),
   (else_try),
     (ge, reg15, 55),
     (str_store_string, s22, "@Jotnar hearth guards have been seen on nearby roads. Proud folk, but they make slavers and raiders think twice."),
   (else_try),
     (ge, reg16, 45),
     (str_store_string, s22, "@Elephant Guard sanctuary patrols have made this road feel watched in a better way."),
   (try_end),
 ]),

("sod_trade_network_describe_caravan_to_s20",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":mode"),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (party_get_slot, ":origin", ":party_no", slot_party_sod_trade_origin),
   (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":origin", ":destination"),
   (assign, ":origin", reg0),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":origin"),
   (assign, ":destination", reg0),
   (party_get_slot, ":cargo_focus", ":party_no", slot_party_sod_trade_cargo_focus),
   (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
   (party_get_slot, ":contract", ":party_no", slot_party_sod_trade_contract),
   (party_get_slot, ":last_result", ":party_no", slot_party_sod_trade_last_result),
   (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
   (store_skill_level, ":trade_skill", "skl_trade", "trp_player"),
   (party_get_skill_level, ":pathfinding", "p_main_party", skl_pathfinding),
   (party_get_skill_level, ":spotting", "p_main_party", skl_spotting),
   (troop_get_slot, ":renown", "trp_player", slot_troop_renown),
   (assign, ":road_skill", ":pathfinding"),
   (val_max, ":road_skill", ":spotting"),
   (assign, ":local_relation", 0),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (party_get_slot, ":local_relation", ":destination", slot_center_player_relation),
   (try_end),
   (try_begin),
     (is_between, ":origin", centers_begin, centers_end),
     (str_store_party_name, s21, ":origin"),
   (else_try),
     (str_store_string, s21, "@the last market"),
   (try_end),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (str_store_party_name, s22, ":destination"),
     (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":destination"),
   (else_try),
     (str_store_string, s22, "@the next market"),
     (str_store_string, s23, "@ordinary market"),
   (try_end),
   (str_store_string, s24, "@mixed goods"),
   (try_begin),
     (eq, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s24, "@food, flour, ale, and whatever fills hungry shelves"),
   (else_try),
     (eq, ":cargo_focus", sod_trade_cargo_raw),
     (str_store_string, s24, "@wool, hides, pottery, and raw goods"),
   (else_try),
     (eq, ":cargo_focus", sod_trade_cargo_strategic),
     (str_store_string, s24, "@salt, iron, oil, tools, and military stores"),
   (else_try),
     (eq, ":cargo_focus", sod_trade_cargo_luxury),
     (str_store_string, s24, "@spice, velvet, wine, and soft things that make hard roads profitable"),
   (try_end),
   (assign, reg20, ":risk"),
   (assign, reg21, ":trust"),
   (str_store_string, s25, "@No player bargain is marked on this run."),
   (try_begin),
     (eq, ":contract", sod_trade_contract_guards),
     (str_store_string, s25, "@Your funded guards are riding with this caravan."),
   (else_try),
     (eq, ":contract", sod_trade_contract_cargo_space),
     (str_store_string, s25, "@Your cargo stake is loaded into these wagons."),
   (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
     (str_store_string, s25, "@Your insurance mark is written against this run."),
   (else_try),
     (eq, ":contract", sod_trade_contract_relief),
     (str_store_string, s25, "@Your relief cargo is riding under this caravan's guard."),
   (else_try),
     (eq, ":contract", sod_trade_contract_profit),
     (str_store_string, s25, "@Your profit stake is riding with this caravan."),
   (try_end),
   (str_store_string, s26, "@We have no old account with you."),
   (try_begin),
     (eq, ":last_result", sod_trade_result_protected),
     (str_store_string, s26, "@We remember your guards. That kind of help is worth more than seals."),
   (else_try),
     (eq, ":last_result", sod_trade_result_dangerous),
     (str_store_string, s26, "@Last run left men counting arrows and missing wheels."),
   (else_try),
     (eq, ":last_result", sod_trade_result_taxed),
     (str_store_string, s26, "@Last run paid too much at the crossings."),
   (else_try),
     (eq, ":last_result", sod_trade_result_raided),
     (str_store_string, s26, "@Last run had raider shadows on it."),
   (else_try),
     (eq, ":last_result", sod_trade_result_shortage_supplied),
     (str_store_string, s26, "@Last run carried relief. Folk remember bread when ledgers forget names."),
   (else_try),
     (eq, ":last_result", sod_trade_result_exploited),
     (str_store_string, s26, "@Last run earned hard coin from a hungry market. Some drivers still mutter about it."),
   (else_try),
     (ge, ":trust", 65),
     (str_store_string, s26, "@Your name is not strange to this caravan."),
   (else_try),
     (le, ":trust", 35),
     (str_store_string, s26, "@We keep our ledgers close around unfamiliar blades."),
   (try_end),
   (str_store_string, s27, "@That is a merchant's guess, broad as a cart track."),
   (try_begin),
     (ge, ":trade_skill", 5),
     (str_store_string, s27, "@You have the eye for ledgers, so I will say it plain: shortage and price are both pulling this road."),
   (else_try),
     (ge, ":local_relation", 10),
     (str_store_string, s27, "@They speak better of you near that market, so the gossip comes less wrapped in fog."),
   (else_try),
     (lt, ":renown", 100),
     (str_store_string, s27, "@No offense meant, but a caravan keeps its sharpest price talk for names the road already knows."),
   (try_end),
   (str_store_string, s28, "@Road danger is old-woman talk until arrows prove it."),
   (try_begin),
     (ge, ":road_skill", 5),
     (str_store_string, s28, "@Your scouts would read the same signs: fresh wheels, thin guards, and too few campfires off the road."),
   (else_try),
     (ge, ":trust", 70),
     (str_store_string, s28, "@You know this road well enough now. It has places where men count purses before prayers; that is familiar-road truth, not tavern smoke."),
   (else_try),
     (lt, ":renown", 100),
     (str_store_string, s28, "@You are not yet a name every driver knows, so take this as road mutter rather than sworn witness."),
   (try_end),
   (try_begin),
     (eq, ":mode", 1),
     (str_store_string, s20, "@We are carrying {s24}. Carts like ours make towns breathe. {s26}"),
   (else_try),
     (eq, ":mode", 2),
     (str_store_string, s20, "@We came out of {s21}. If you want the truth of a market, ask the drivers leaving it."),
   (else_try),
     (eq, ":mode", 3),
     (str_store_string, s20, "@We are bound for {s22}. They are known as a {s23}, so the right cargo can still earn. {s27}"),
   (else_try),
     (eq, ":mode", 4),
     (call_script, "script_sod_trade_network_describe_route_to_s22", ":party_no"),
     (str_store_string, s20, "@{s22} {s28} {s26}"),
   (else_try),
     (eq, ":mode", 5),
     (str_store_string, s20, "@Goods selling well? Watch {s22}. A {s23} often pays for {s24}, if the road lets the carts through. {s27}"),
   (else_try),
     (eq, ":mode", 6),
     (call_script, "script_sod_trade_network_describe_route_to_s22", ":party_no"),
     (str_store_string, s20, "@Avoid roads like this when you are slow: {s22} I speak from cart wheels, superstition, and rumor, not a lord's map."),
   (else_try),
     (eq, ":mode", 7),
     (call_script, "script_sod_trade_network_get_contract_terms_to_regs", ":party_no", sod_trade_contract_guards),
     (str_store_string, s20, "@Protection is always welcome. For this road, extra guards would cost about {reg0} denars. Trusted names get better terms; strangers pay for uncertainty. {s25}"),
   (else_try),
     (str_store_string, s20, "@We run from {s21} to {s22}, carrying {s24}. They call the destination a {s23}. {s25} {s26}"),
   (try_end),
 ]),

("sod_trade_network_describe_caravan_sickness_to_s20",
 [
   (store_script_param_1, ":party_no"),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (party_get_slot, ":origin", ":party_no", slot_party_sod_trade_origin),
   (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":origin", ":destination"),
   (assign, ":origin", reg0),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":origin"),
   (assign, ":destination", reg0),
   (party_get_slot, ":route_label", ":party_no", slot_party_sod_trade_recent_trouble),
   (assign, ":origin_risk", 0),
   (assign, ":destination_risk", 0),
   (assign, ":origin_outbreak", sod_outbreak_none),
   (assign, ":destination_outbreak", sod_outbreak_none),
   (assign, ":origin_severity", 0),
   (assign, ":destination_severity", 0),
   (assign, ":destination_quarantine", 0),
   (try_begin),
     (is_between, ":origin", centers_begin, centers_end),
     (str_store_party_name, s21, ":origin"),
     (call_script, "script_sod_center_public_health_compute_causes", ":origin"),
     (assign, ":origin_risk", reg4),
     (party_get_slot, ":origin_outbreak", ":origin", slot_center_health_outbreak_type),
     (party_get_slot, ":origin_severity", ":origin", slot_center_health_outbreak_severity),
   (else_try),
     (str_store_string, s21, "@the last market"),
   (try_end),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (str_store_party_name, s22, ":destination"),
     (call_script, "script_sod_center_public_health_compute_causes", ":destination"),
     (assign, ":destination_risk", reg4),
     (party_get_slot, ":destination_outbreak", ":destination", slot_center_health_outbreak_type),
     (party_get_slot, ":destination_severity", ":destination", slot_center_health_outbreak_severity),
     (party_get_slot, ":destination_quarantine", ":destination", slot_center_health_quarantine),
   (else_try),
     (str_store_string, s22, "@the next market"),
   (try_end),
   (assign, reg20, ":origin_risk"),
   (assign, reg21, ":destination_risk"),
   (str_store_string, s20, "@No open sickness is riding this road, so far as drivers dare swear. Still, we keep the water skins covered and unload away from crowded gates."),
   (try_begin),
     (gt, ":destination_outbreak", sod_outbreak_none),
     (call_script, "script_sod_center_public_health_outbreak_name_to_s0", ":destination_outbreak"),
     (str_store_string_reg, s23, s0),
     (assign, reg22, ":destination_severity"),
     (str_store_string, s20, "@The bad word is at {s22}: {s23}, spoken of as severity {reg22}. Wagons go in only for good coin, clean handling, or relief cargo."),
   (else_try),
     (gt, ":origin_outbreak", sod_outbreak_none),
     (call_script, "script_sod_center_public_health_outbreak_name_to_s0", ":origin_outbreak"),
     (str_store_string_reg, s23, s0),
     (assign, reg22, ":origin_severity"),
     (str_store_string, s20, "@We came out of {s21} with {s23} in the talk, severity {reg22}. A careful master keeps sacks sealed and men away from common wells."),
   (else_try),
     (gt, ":destination_quarantine", 0),
     (str_store_string, s20, "@{s22} is under quarantine. That does not close every gate, but it turns every unload into an argument with guards, healers, and frightened merchants."),
   (else_try),
     (eq, ":route_label", sod_trade_route_sickness),
     (str_store_string, s20, "@No bell is tolling openly, but sickness is near this road. Origin risk is {reg20}, destination risk is {reg21}; careful caravans charge for clean water and slow unloading."),
   (else_try),
     (ge, ":destination_risk", 70),
     (str_store_string, s20, "@{s22} is not yet in outbreak, but the drivers are wary. Destination disease risk is {reg21}; famine, crowding, or dirty water can make a market turn overnight."),
   (else_try),
     (ge, ":origin_risk", 70),
     (str_store_string, s20, "@{s21} has the wrong smell in the road gossip. Origin disease risk is {reg20}; we watch our men for coughs before sharing fires."),
   (try_end),
 ]),

("sod_trade_network_describe_village_root_to_s20",
 [
   (store_script_param_1, ":village_no"),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":village_no", "$current_town"),
   (assign, ":village_no", reg0),
   (str_store_string, s20, "@This village sends what it can: grain when the fields are kind, cattle when the herds hold, and sons when fear comes calling."),
   (try_begin),
     (is_between, ":village_no", villages_begin, villages_end),
     (party_get_slot, ":market_town", ":village_no", slot_village_market_town),
     (try_begin),
       (is_between, ":market_town", towns_begin, towns_end),
       (str_store_party_name, s21, ":market_town"),
       (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":market_town"),
     (else_try),
       (str_store_string, s21, "@the nearest town"),
       (str_store_string, s23, "@ordinary market"),
     (try_end),
     (call_script, "script_sod_get_center_goods_market_profile", ":village_no"),
     (assign, ":food_balance", reg0),
     (assign, ":raw_balance", reg1),
     (assign, ":strategic_balance", reg2),
     (assign, ":scarcity", reg4),
     (party_get_slot, ":health", ":village_no", slot_center_sod_local_health),
     (party_get_slot, ":looter_pressure", ":village_no", slot_center_sod_looter_raid_pressure),
     (str_store_string, s22, "@The road is passable enough, by our reckoning."),
     (try_begin),
       (ge, ":looter_pressure", 40),
       (str_store_string, s22, "@Raids and road fear are thinning the carts. The town will feel that before a lord admits it."),
     (else_try),
       (ge, ":scarcity", 130),
       (str_store_string, s22, "@We are keeping too much back for our own pots. The market will feel it."),
     (else_try),
       (lt, ":health", 15),
       (str_store_string, s22, "@Sickness slows carts before bandits ever see them."),
     (else_try),
       (ge, ":food_balance", 55),
       (str_store_string, s22, "@Grain is our strongest word to the market."),
     (else_try),
       (ge, ":raw_balance", 55),
       (str_store_string, s22, "@Wool, hides, and rough goods are what we can spare."),
     (else_try),
       (ge, ":strategic_balance", 45),
       (str_store_string, s22, "@Salt, tools, and hard stores matter more than finery here."),
     (try_end),
     (str_store_string, s20, "@Our carts mostly answer to {s21}. Merchants call it a {s23}. {s22} Ask the wagon folk if you want fresh road truth; an elder hears late and worries early."),
   (try_end),
 ]),

("sod_trade_network_describe_town_roots_to_s20",
 [
   (store_script_param_1, ":town_no"),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":town_no", "$current_town"),
   (assign, ":town_no", reg0),
   (str_store_string, s20, "@This town eats from roads and villages I cannot name with certainty. Ask the caravans for fresher truth."),
   (try_begin),
     (is_between, ":town_no", towns_begin, towns_end),
     (assign, ":root_count", 0),
     (assign, ":first_root", -1),
     (try_for_range, ":village_no", villages_begin, villages_end),
       (party_slot_eq, ":village_no", slot_village_market_town, ":town_no"),
       (val_add, ":root_count", 1),
       (try_begin),
         (lt, ":first_root", 0),
         (assign, ":first_root", ":village_no"),
       (try_end),
     (try_end),
     (str_store_party_name, s21, ":town_no"),
     (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":town_no"),
     (assign, reg20, ":root_count"),
     (try_begin),
       (is_between, ":first_root", villages_begin, villages_end),
       (str_store_party_name, s22, ":first_root"),
       (str_store_string, s20, "@{s21} is spoken of as a {s23}. {reg20} nearby villages send carts this way when fear and mud allow it. {s22} is one such root; when those villages are raided, food and raw goods vanish from this market first."),
     (else_try),
       (str_store_string, s20, "@{s21} is spoken of as a {s23}, but I have no reliable village-root ledger for it. That is a bad sign for prices and a worse one for bellies."),
     (try_end),
   (try_end),
 ]),

("sod_trade_network_apply_player_contract",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":contract"),
   (store_script_param, ":investment", 3),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (assign, reg0, 0),
   (try_begin),
     (neg|party_slot_ge, ":party_no", slot_party_sod_trade_contract, 1),
     (assign, reg0, 1),
     (party_set_slot, ":party_no", slot_party_sod_trade_contract, ":contract"),
     (party_set_slot, ":party_no", slot_party_sod_trade_investment, ":investment"),
     (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
     (val_add, ":trust", 1),
     (val_clamp, ":trust", 0, 101),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_trust, ":trust"),
     (store_current_day, "$g_sod_trade_network_last_contract_day"),
     (assign, "$g_sod_trade_network_last_contract_party", ":party_no"),
     (assign, "$g_sod_trade_network_last_contract_type", ":contract"),
     (assign, "$g_sod_trade_network_last_contract_investment", ":investment"),
     (try_begin),
       (eq, ":contract", sod_trade_contract_guards),
       (party_set_slot, ":party_no", slot_party_sod_trade_player_protection, 1),
       (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
       (val_sub, ":risk", 12),
       (val_clamp, ":risk", 0, 101),
       (party_set_slot, ":party_no", slot_party_sod_trade_route_risk, ":risk"),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_caravan_protection, 2),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 1),
     (else_try),
       (eq, ":contract", sod_trade_contract_cargo_space),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_trade_profit, 2),
     (else_try),
       (eq, ":contract", sod_trade_contract_insurance),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_orderly_profit, 1),
     (else_try),
       (eq, ":contract", sod_trade_contract_relief),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_food_security, 2),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_free_captives, 1),
     (else_try),
       (eq, ":contract", sod_trade_contract_profit),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_trade_profit, 2),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_dirty_profit, 1),
     (try_end),
   (try_end),
 ]),

("sod_trade_network_process_caravan_arrival",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":center_no"),
   (try_begin),
     (gt, ":party_no", 0),
     (is_between, ":center_no", centers_begin, centers_end),
     (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
     (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":center_no"),
     (assign, ":destination", reg0),
     (this_or_next|eq, ":destination", ":center_no"),
     (neg|is_between, ":destination", centers_begin, centers_end),
     (store_current_day, ":cur_day"),
     (neg|party_slot_eq, ":party_no", slot_party_sod_trade_last_result_day, ":cur_day"),
     (party_get_slot, ":contract", ":party_no", slot_party_sod_trade_contract),
     (party_get_slot, ":investment", ":party_no", slot_party_sod_trade_investment),
     (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
     (party_get_slot, ":route_label", ":party_no", slot_party_sod_trade_recent_trouble),
     (party_get_slot, ":origin", ":party_no", slot_party_sod_trade_origin),
     (assign, ":payout", 0),
     (assign, ":result", sod_trade_result_profitable),
     (try_begin),
       (is_between, ":origin", centers_begin, centers_end),
       (party_slot_ge, ":origin", slot_center_health_outbreak_type, 1),
       (party_get_slot, ":recent_exposure", ":center_no", slot_center_health_recent_exposure),
       (val_add, ":recent_exposure", 4),
       (val_clamp, ":recent_exposure", 0, 30),
       (party_set_slot, ":center_no", slot_center_health_recent_exposure, ":recent_exposure"),
     (try_end),
     (try_begin),
       (eq, ":route_label", sod_trade_route_sickness),
       (party_get_slot, ":recent_exposure", ":center_no", slot_center_health_recent_exposure),
       (val_add, ":recent_exposure", 2),
       (val_clamp, ":recent_exposure", 0, 30),
       (party_set_slot, ":center_no", slot_center_health_recent_exposure, ":recent_exposure"),
     (try_end),
     (try_begin),
       (eq, ":route_label", sod_trade_route_toll),
       (assign, ":result", sod_trade_result_taxed),
     (else_try),
       (eq, ":route_label", sod_trade_route_raider),
       (assign, ":result", sod_trade_result_raided),
     (else_try),
       (eq, ":route_label", sod_trade_route_sickness),
       (assign, ":result", sod_trade_result_dangerous),
     (else_try),
       (ge, ":risk", 70),
       (assign, ":result", sod_trade_result_dangerous),
     (else_try),
       (party_slot_ge, ":party_no", slot_party_sod_trade_player_protection, 1),
       (assign, ":result", sod_trade_result_protected),
     (try_end),
     (try_begin),
       (eq, ":contract", sod_trade_contract_cargo_space),
       (store_mul, ":payout", ":investment", 6),
       (val_div, ":payout", 5),
       (call_script, "script_troop_add_gold", "trp_player", ":payout"),
       (assign, ":result", sod_trade_result_profitable),
     (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
       (this_or_next|ge, ":risk", 70),
       (this_or_next|eq, ":result", sod_trade_result_raided),
       (eq, ":result", sod_trade_result_dangerous),
       (store_mul, ":payout", ":investment", 2),
       (call_script, "script_troop_add_gold", "trp_player", ":payout"),
       (assign, ":result", sod_trade_result_dangerous),
     (else_try),
       (eq, ":contract", sod_trade_contract_relief),
       (call_script, "script_change_center_prosperity", ":center_no", 1),
       (call_script, "script_change_center_health", ":center_no", 1),
       (party_get_slot, ":outbreak", ":center_no", slot_center_health_outbreak_type),
       (try_begin),
         (gt, ":outbreak", sod_outbreak_none),
         (party_get_slot, ":severity", ":center_no", slot_center_health_outbreak_severity),
         (val_sub, ":severity", 2),
         (val_max, ":severity", 0),
         (party_set_slot, ":center_no", slot_center_health_outbreak_severity, ":severity"),
       (try_end),
       (call_script, "script_change_player_relation_with_center", ":center_no", 1),
       (assign, ":result", sod_trade_result_shortage_supplied),
     (else_try),
       (eq, ":contract", sod_trade_contract_profit),
       (store_mul, ":payout", ":investment", 7),
       (val_div, ":payout", 5),
       (call_script, "script_troop_add_gold", "trp_player", ":payout"),
       (call_script, "script_change_center_prosperity", ":center_no", -1),
       (assign, ":result", sod_trade_result_exploited),
     (try_end),
     (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
     (try_begin),
       (eq, ":result", sod_trade_result_protected),
       (val_add, ":trust", 6),
     (else_try),
       (eq, ":result", sod_trade_result_shortage_supplied),
       (val_add, ":trust", 4),
     (else_try),
       (eq, ":result", sod_trade_result_exploited),
       (val_sub, ":trust", 6),
     (else_try),
       (eq, ":result", sod_trade_result_raided),
       (val_sub, ":trust", 2),
     (try_end),
     (val_clamp, ":trust", 0, 101),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_trust, ":trust"),
     (try_begin),
       (ge, ":contract", 1),
       (assign, ":report_magnitude", 1),
       (try_begin),
         (gt, ":payout", 0),
         (assign, ":report_magnitude", ":payout"),
       (try_end),
       (call_script, "script_sod_report_record_event", sod_report_category_roads, sod_report_severity_notable, sod_report_subject_party, ":party_no", sod_report_subject_center, ":center_no", ":report_magnitude", sod_report_reason_trade),
       (assign, reg23, ":payout"),
       (str_store_party_name, s21, ":party_no"),
      (str_store_party_name, s22, ":center_no"),
      (try_begin),
        (eq, ":contract", sod_trade_contract_guards),
        (display_message, "@Trade network: {s21} reached {s22}; your funded guards completed the run.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_cargo_space),
        (display_message, "@Trade network: {s21} reached {s22}; your cargo stake paid {reg23} denars.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_insurance),
        (gt, ":payout", 0),
        (display_message, "@Trade network: {s21} reached {s22} battered; your insurance claim paid {reg23} denars.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_insurance),
        (display_message, "@Trade network: {s21} reached {s22} safely; no insurance claim was needed.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_relief),
        (display_message, "@Trade network: {s21} reached {s22}; your relief cargo improved local stores.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_profit),
        (display_message, "@Trade network: {s21} reached {s22}; your profit stake paid {reg23} denars.", quest_success_color),
      (try_end),
     (try_end),
     (party_set_slot, ":party_no", slot_party_sod_trade_last_result, ":result"),
     (party_set_slot, ":party_no", slot_party_sod_trade_route_reputation, ":result"),
     (party_set_slot, ":party_no", slot_party_sod_trade_last_result_day, ":cur_day"),
     (party_set_slot, ":party_no", slot_party_sod_trade_contract, sod_trade_contract_none),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_protection, 0),
     (party_set_slot, ":party_no", slot_party_sod_trade_investment, 0),
     (assign, "$g_sod_trade_network_last_result_day", ":cur_day"),
     (assign, "$g_sod_trade_network_last_result_party", ":party_no"),
     (assign, "$g_sod_trade_network_last_result_center", ":center_no"),
     (assign, "$g_sod_trade_network_last_result_type", ":result"),
   (try_end),
 ]),

("cf_sod_trade_network_can_apply_strategy_action",
 [
   (store_current_day, ":cur_day"),
   (neq, "$g_sod_trade_network_last_strategy_day", ":cur_day"),
 ]),

("sod_trade_network_apply_strategy_action",
 [
   (store_script_param_1, ":action"),
   (assign, reg0, 0),
   (try_begin),
     (eq, ":action", 1), # Fund road patrols.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 1200),
     (call_script, "script_sod_player_charge_gold", 1200),
     (faction_get_slot, ":black_army_heat", "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
     (val_add, ":black_army_heat", 12),
     (val_clamp, ":black_army_heat", 0, 101),
     (faction_set_slot, "fac_sod_merc_guild1", slot_faction_black_army_contract_heat, ":black_army_heat"),
     (faction_get_slot, ":horde_pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (val_sub, ":horde_pressure", 4),
     (val_clamp, ":horde_pressure", 0, 101),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":horde_pressure"),
     (assign, "$g_sod_trade_network_last_strategy_action", 1),
     (store_current_day, "$g_sod_trade_network_last_strategy_day"),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: paid patrol silver is moving through the roads.", quest_success_color),
   (else_try),
     (eq, ":action", 2), # Suppress Boar toll pressure.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 900),
     (call_script, "script_sod_player_charge_gold", 900),
     (faction_get_slot, ":boar_pressure", "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure),
     (val_sub, ":boar_pressure", 12),
     (val_clamp, ":boar_pressure", 0, 101),
     (faction_set_slot, "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure, ":boar_pressure"),
     (assign, "$g_sod_trade_network_last_strategy_action", 2),
     (store_current_day, "$g_sod_trade_network_last_strategy_day"),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: toll marks are being challenged along the crossings.", quest_success_color),
   (else_try),
     (eq, ":action", 3), # Subsidize needy destination.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 1000),
     (is_between, "$g_sod_trade_network_last_result_center", centers_begin, centers_end),
     (call_script, "script_sod_player_charge_gold", 1000),
     (call_script, "script_change_center_prosperity", "$g_sod_trade_network_last_result_center", 1),
     (call_script, "script_center_get_food_store_limit", "$g_sod_trade_network_last_result_center"),
     (assign, ":food_limit", reg0),
     (store_div, ":relief_food", ":food_limit", 20),
     (val_max, ":relief_food", 10),
     (call_script, "script_sod_center_apply_food_delta", "$g_sod_trade_network_last_result_center", ":relief_food"),
     (call_script, "script_change_player_relation_with_center", "$g_sod_trade_network_last_result_center", 1),
     (assign, "$g_sod_trade_network_last_strategy_action", 3),
     (store_current_day, "$g_sod_trade_network_last_strategy_day"),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: subsidized relief has been sent toward the last known needy market.", quest_success_color),
   (else_try),
     (eq, ":action", 4), # Invest in repeat route.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 800),
     (gt, "$g_sod_trade_network_last_result_party", 0),
     (call_script, "script_sod_player_charge_gold", 800),
     (party_get_slot, ":trust", "$g_sod_trade_network_last_result_party", slot_party_sod_trade_player_trust),
     (val_add, ":trust", 8),
     (val_clamp, ":trust", 0, 101),
     (party_set_slot, "$g_sod_trade_network_last_result_party", slot_party_sod_trade_player_trust, ":trust"),
     (party_get_slot, ":risk", "$g_sod_trade_network_last_result_party", slot_party_sod_trade_route_risk),
     (val_sub, ":risk", 6),
     (val_clamp, ":risk", 0, 101),
     (party_set_slot, "$g_sod_trade_network_last_result_party", slot_party_sod_trade_route_risk, ":risk"),
     (assign, "$g_sod_trade_network_last_strategy_action", 4),
     (store_current_day, "$g_sod_trade_network_last_strategy_day"),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: repeat-route coin has bought better trust and steadier arrangements.", quest_success_color),
   (try_end),
 ]),

("sod_trade_network_center_allows_departure_to_reg",
 [
   (store_script_param_1, ":center_no"),
   (assign, reg0, 1),
   (try_begin),
     (is_between, ":center_no", walled_centers_begin, walled_centers_end),
     (neg|party_slot_eq, ":center_no", slot_center_is_besieged_by, -1),
     (assign, reg0, 0),
   (try_end),
 ]),

("sod_trade_network_send_party_to_center",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":target_center"),
   (store_script_param, ":clear_default_behavior", 3),
   (try_begin),
     (gt, ":party_no", 0),
     (is_between, ":target_center", centers_begin, centers_end),
     (party_set_ai_behavior, ":party_no", ai_bhvr_travel_to_party),
     (party_set_ai_object, ":party_no", ":target_center"),
     (try_begin),
       (eq, ":clear_default_behavior", 1),
       (party_set_flags, ":party_no", pf_default_behavior, 0),
     (try_end),
     (party_set_slot, ":party_no", slot_party_ai_state, spai_trading_with_town),
     (party_set_slot, ":party_no", slot_party_ai_object, ":target_center"),
   (try_end),
 ]),

("sod_trade_network_get_center_departure_chance_to_reg",
 [
   (store_script_param_1, ":center_no"),
   (store_script_param_2, ":base_chance"),
   (store_current_day, ":cache_day"),
   (val_add, ":cache_day", 1),
   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),
     (party_get_slot, ":cached_day", ":center_no", slot_center_sod_trade_departure_profile_day),
     (neq, ":cached_day", ":cache_day"),
     (assign, ":move_adjust", 0),
     (party_get_slot, ":cur_prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":cur_health", ":center_no", slot_center_sod_local_health),
     (party_get_slot, ":cur_food_store", ":center_no", slot_party_food_store),
     (party_get_slot, ":cur_population", ":center_no", slot_center_sod_local_population),
     (val_max, ":cur_population", town_pop_min),
     (call_script, "script_center_get_food_store_limit", ":center_no"),
     (assign, ":cur_food_limit", reg0),
     (call_script, "script_center_get_food_consumption", ":center_no"),
     (assign, ":cur_food_consumption", reg0),
     (try_begin),
       (gt, ":cur_food_limit", 0),
       (store_mul, ":cur_food_ratio", ":cur_food_store", 100),
       (val_div, ":cur_food_ratio", ":cur_food_limit"),
     (else_try),
       (assign, ":cur_food_ratio", 0),
     (try_end),
     (try_begin),
       (gt, ":cur_food_consumption", 0),
       (store_mul, ":cur_food_security", ":cur_food_store", 100),
       (val_div, ":cur_food_security", ":cur_food_consumption"),
     (else_try),
       (assign, ":cur_food_security", 0),
     (try_end),
     (try_begin),
       (lt, ":cur_prosperity", 45),
       (val_add, ":move_adjust", 8),
     (try_end),
     (try_begin),
       (lt, ":cur_health", 15),
       (val_add, ":move_adjust", 6),
     (try_end),
     (try_begin),
       (lt, ":cur_food_ratio", 35),
       (val_add, ":move_adjust", 5),
     (else_try),
       (gt, ":cur_food_ratio", 70),
       (val_sub, ":move_adjust", 2),
     (try_end),
     (try_begin),
       (lt, ":cur_food_security", 300),
       (val_add, ":move_adjust", 10),
     (else_try),
       (lt, ":cur_food_security", 700),
       (val_add, ":move_adjust", 5),
     (else_try),
       (gt, ":cur_food_security", 1400),
       (val_sub, ":move_adjust", 4),
     (try_end),
     (try_begin),
       (ge, ":cur_population", 2200),
       (lt, ":cur_prosperity", 55),
       (val_add, ":move_adjust", 6),
     (else_try),
       (ge, ":cur_population", 1600),
       (lt, ":cur_prosperity", 50),
       (val_add, ":move_adjust", 4),
     (else_try),
       (ge, ":cur_population", 1000),
       (lt, ":cur_prosperity", 45),
       (val_add, ":move_adjust", 2),
     (try_end),
     (try_begin),
       (ge, ":cur_population", 1800),
       (ge, ":cur_prosperity", 60),
       (ge, ":cur_health", 25),
       (ge, ":cur_food_security", 1200),
       (val_sub, ":move_adjust", 4),
     (try_end),
     (party_set_slot, ":center_no", slot_center_sod_trade_departure_profile_day, ":cache_day"),
     (party_set_slot, ":center_no", slot_center_sod_trade_departure_move_adjust, ":move_adjust"),
   (try_end),
   (assign, reg0, ":base_chance"),
   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),
     (party_get_slot, ":cached_adjust", ":center_no", slot_center_sod_trade_departure_move_adjust),
     (val_add, reg0, ":cached_adjust"),
   (try_end),
   (val_clamp, reg0, 10, 75),
 ]),

("sod_trade_network_process_daily_caravan_spawn_pulse",
 [
   # Keep kingdom trade visible on the world map. The caravan behavior and
   # trade engine already exist; this daily pulse supplies new caravans up to
   # each faction's configured cap.
   (try_for_range, ":faction_no", kingdoms_begin, kingdoms_end),
     (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
     (faction_get_slot, ":num_towns", ":faction_no", slot_faction_num_towns),
     (gt, ":num_towns", 0),
     (call_script, "script_create_kingdom_party_if_below_limit", ":faction_no", spt_kingdom_caravan),
   (try_end),
 ]),

("sod_trade_network_process_daily_village_farmer_spawn_pulse",
 [
   # Keep village-market traffic visible without leaving spawn eligibility
   # logic in the trigger layer.
   (try_for_range, ":village_no", villages_begin, villages_end),
     (party_slot_eq, ":village_no", slot_village_state, svs_normal),
     (party_get_slot, ":farmer_party", ":village_no", slot_village_farmer_party),
     (this_or_next|eq, ":farmer_party", 0),
     (neg|party_is_active, ":farmer_party"),
     (store_random_in_range, ":random_no", 0, 100),
     (lt, ":random_no", 30),
     (call_script, "script_create_village_farmer_party", ":village_no"),
     (party_set_slot, ":village_no", slot_village_farmer_party, reg0),
   (try_end),
 ]),

("sod_trade_network_process_caravan_arrival_tick",
 [
       (try_for_parties, ":party_no"),
         (neq, ":party_no", "p_main_party"),
         (party_slot_eq, ":party_no", slot_party_type, spt_kingdom_caravan),
         (party_is_in_any_town, ":party_no"),

         (store_faction_of_party, ":merchant_faction", ":party_no"),
         (faction_get_slot, ":num_towns", ":merchant_faction", slot_faction_num_towns),
         (try_begin),
           (le, ":num_towns", 0),
           (remove_party, ":party_no"),
         (else_try),
           (party_get_cur_town, ":cur_center", ":party_no"),

           (call_script, "script_sod_trade_network_center_allows_departure_to_reg", ":cur_center"),
           (eq, reg0, 1),

           (assign, ":do_trade", 0),
           (try_begin),
             (party_get_slot, ":cur_ai_state", ":party_no", slot_party_ai_state),
             (eq, ":cur_ai_state", spai_trading_with_town),
             (party_get_slot, ":cur_ai_object", ":party_no", slot_party_ai_object),
             (eq, ":cur_center", ":cur_ai_object"),
             (assign, ":do_trade", 1),
           (try_end),

           # Caravans should settle business whenever they actually reach the market
           # they were travelling to, instead of waiting for a low-probability exit roll.
           (try_begin),
             (eq, ":do_trade", 1),
             (call_script, "script_do_merchant_town_trade", ":party_no", ":cur_center"),
           (try_end),

           (assign, ":target_center", -1),
           (assign, ":move_chance", 18),

           (try_begin),
             (eq, ":do_trade", 1),
             (val_add, ":move_chance", 32),
           (try_end),

           (try_begin),
             (eq, "$caravan_escort_party_id", ":party_no"),
             (neg|party_is_in_town, ":party_no", "$caravan_escort_destination_town"),
             (assign, ":target_center", "$caravan_escort_destination_town"),
             (assign, ":move_chance", 100),
           (else_try),
             (call_script, "script_sod_trade_network_get_center_departure_chance_to_reg", ":cur_center", ":move_chance"),
             (assign, ":move_chance", reg0),
             (store_random_in_range, ":move_roll", 0, 100),
             (lt, ":move_roll", ":move_chance"),
             (call_script, "script_cf_select_random_town_at_peace_with_faction_in_trade_route", ":cur_center", ":merchant_faction"),
             (assign, ":target_center", reg0),
           (try_end),

           (try_begin),
             (is_between, ":target_center", towns_begin, towns_end),
             (neq, "$caravan_escort_party_id", ":party_no"),
             (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
             (call_script, "script_sod_trade_network_evaluate_route", ":cur_center", ":target_center"),
             (assign, ":route_risk", reg0),
             (assign, ":route_label", reg1),
             (try_begin),
               (party_slot_ge, ":party_no", slot_party_sod_trade_player_protection, 1),
               (val_sub, ":route_risk", 15),
             (try_end),
             (val_clamp, ":route_risk", 0, 101),
             (party_set_slot, ":party_no", slot_party_sod_trade_origin, ":cur_center"),
             (party_set_slot, ":party_no", slot_party_sod_trade_destination, ":target_center"),
             (party_set_slot, ":party_no", slot_party_sod_trade_route_risk, ":route_risk"),
             (party_set_slot, ":party_no", slot_party_sod_trade_recent_trouble, ":route_label"),
             (assign, ":route_departure_chance", 100),
             (try_begin),
               (ge, ":route_risk", 85),
               (assign, ":route_departure_chance", 35),
             (else_try),
               (ge, ":route_risk", 70),
               (assign, ":route_departure_chance", 55),
             (else_try),
               (ge, ":route_risk", 55),
               (assign, ":route_departure_chance", 75),
             (try_end),
             (try_begin),
               (eq, ":route_label", sod_trade_route_toll),
               (val_sub, ":route_departure_chance", 10),
             (else_try),
               (eq, ":route_label", sod_trade_route_raider),
               (val_sub, ":route_departure_chance", 15),
             (else_try),
               (eq, ":route_label", sod_trade_route_sickness),
               (val_sub, ":route_departure_chance", 12),
             (else_try),
               (eq, ":route_label", sod_trade_route_starving),
               (val_add, ":route_departure_chance", 15),
             (else_try),
               (eq, ":route_label", sod_trade_route_luxury),
               (val_add, ":route_departure_chance", 10),
             (try_end),
             (try_begin),
               (party_slot_ge, ":party_no", slot_party_sod_trade_player_protection, 1),
               (val_add, ":route_departure_chance", 20),
             (try_end),
             (val_clamp, ":route_departure_chance", 15, 100),
             (store_random_in_range, ":route_departure_roll", 0, 100),
             (try_begin),
               (ge, ":route_departure_roll", ":route_departure_chance"),
               (party_set_slot, ":party_no", slot_party_sod_trade_last_result, sod_trade_result_delayed),
               (assign, ":target_center", -1),
             (try_end),
           (try_end),

           (is_between, ":target_center", towns_begin, towns_end),
           (neg|party_is_in_town, ":party_no", ":target_center"),
           (call_script, "script_sod_trade_network_send_party_to_center", ":party_no", ":target_center", 1),
         (try_end),
       (try_end),
 ]),

("sod_trade_network_process_farmer_arrival_tick",
 [
       (try_for_parties, ":party_no"),
         (party_slot_eq, ":party_no", slot_party_type, spt_village_farmer),
         (party_is_in_any_town, ":party_no"),
         (party_get_slot, ":home_center", ":party_no", slot_party_home_center),
         (is_between, ":home_center", villages_begin, villages_end),
         (party_get_cur_town, ":cur_center", ":party_no"),
         (is_between, ":cur_center", centers_begin, centers_end),

         (call_script, "script_sod_trade_network_center_allows_departure_to_reg", ":cur_center"),
         (eq, reg0, 1),

         (party_get_slot, ":home_health", ":home_center", slot_center_sod_local_health),
         (val_add, ":home_health", 100),
         # Safety: health is used as a percent-style throughput factor.
         (val_clamp, ":home_health", 0, 151),
         (party_get_slot, ":home_population", ":home_center", slot_center_sod_local_population),
         (val_max, ":home_population", village_pop_min),
         (store_div, ":producer_bonus", ":home_population", 80),
         (val_clamp, ":producer_bonus", 0, 10),

         (try_begin),
           (eq, ":cur_center", ":home_center"),
           (assign, ":do_home_trade", 0),
           (try_begin),
             (party_get_slot, ":cur_ai_state", ":party_no", slot_party_ai_state),
             (party_get_slot, ":cur_ai_object", ":party_no", slot_party_ai_object),
             (eq, ":cur_ai_state", spai_trading_with_town),
             (eq, ":cur_ai_object", ":home_center"),
             (assign, ":do_home_trade", 1),
           (else_try),
             (party_get_slot, ":cur_ai_object", ":party_no", slot_party_ai_object),
             (lt, ":cur_ai_object", 0),
             (assign, ":do_home_trade", 1),
           (try_end),
           (try_begin),
             (eq, ":do_home_trade", 1),
             (store_faction_of_party, ":home_faction", ":home_center"),
             (call_script, "script_sod_law_calculate_trade_tax_policy", ":home_faction"),
             (assign, ":home_trade_tax_modifier", reg0),
             (assign, ":home_trade_volume_modifier", reg1),
             (assign, ":home_tariff_modifier", reg3),
             (assign, ":home_trade_percent", 50),
             (val_mul, ":home_trade_percent", ":home_trade_volume_modifier"),
             (val_div, ":home_trade_percent", 100),
             (val_clamp, ":home_trade_percent", 25, 60),
             (call_script, "script_do_party_center_trade", ":party_no", ":home_center", ":home_trade_percent"),
             (assign, ":total_change", reg0),
             (party_get_slot, ":prosperity", ":home_center", slot_town_prosperity),
             (val_add, ":prosperity", 30),
             (val_mul, ":total_change", ":prosperity"),
             (val_mul, ":total_change", ":home_health"),
             (val_div, ":total_change", 260000), # (30 + prosperity) / 130 * 5% of the sales, scaled by home health.
             (val_add, ":total_change", ":producer_bonus"),
             (val_mul, ":total_change", ":home_tariff_modifier"),
             (val_div, ":total_change", 100),
             (store_sub, ":home_tax_friction", ":home_trade_tax_modifier", 100),
             (val_div, ":home_tax_friction", 10),
             (val_sub, ":total_change", ":home_tax_friction"),

             #Adding tax revenue to the center
             (val_max, ":total_change", 0),
             (call_script, "script_sod_center_apply_tariffs_delta", ":home_center", ":total_change"),

             #Moving farmers to the market town immediately after village trade
             (party_get_slot, ":market_town", ":home_center", slot_village_market_town),
             (try_begin),
               (is_between, ":market_town", towns_begin, towns_end),
               (call_script, "script_sod_trade_network_send_party_to_center", ":party_no", ":market_town", 0),
             (else_try),
               (call_script, "script_sod_trade_network_send_party_to_center", ":party_no", ":home_center", 0),
             (try_end),
           (try_end),
         (else_try),
           (try_begin),
             (party_get_slot, ":cur_ai_state", ":party_no", slot_party_ai_state),
             (party_get_slot, ":cur_ai_object", ":party_no", slot_party_ai_object),
             (is_between, ":cur_ai_object", towns_begin, towns_end),
             (eq, ":cur_ai_state", spai_trading_with_town),
             (eq, ":cur_center", ":cur_ai_object"),

             (store_faction_of_party, ":market_faction", ":cur_ai_object"),
             (call_script, "script_sod_law_calculate_trade_tax_policy", ":market_faction"),
             (assign, ":market_trade_tax_modifier", reg0),
             (assign, ":market_trade_volume_modifier", reg1),
             (assign, ":market_merchant_happiness", reg2),
             (assign, ":market_tariff_modifier", reg3),
             (store_faction_of_party, ":home_faction", ":home_center"),
             (call_script, "script_sod_law_calculate_trade_tax_policy", ":home_faction"),
             (assign, ":home_trade_tax_modifier", reg0),
             (assign, ":home_trade_volume_modifier", reg1),
             (assign, ":home_tariff_modifier", reg3),
             (assign, ":farmer_trade_percent", 10),
             (val_mul, ":farmer_trade_percent", ":market_trade_volume_modifier"),
             (val_div, ":farmer_trade_percent", 100),
             (val_clamp, ":farmer_trade_percent", 6, 15),
             (call_script, "script_do_party_center_trade", ":party_no", ":cur_ai_object", ":farmer_trade_percent"),
             (assign, ":trade_value", reg0),
             (party_get_slot, ":market_population", ":cur_ai_object", slot_center_sod_local_population),
             (val_max, ":market_population", town_pop_min),
             (store_div, ":market_population_bonus", ":market_population", 350),
             (val_clamp, ":market_population_bonus", 0, 10),
             (call_script, "script_center_get_food_consumption", ":cur_ai_object"),
             (assign, ":town_food_consumption", reg0),

             # Destination tariffs depend on market prosperity, but also on whether the
             # home village is healthy enough to keep sending good volume to market.
             (assign, ":market_tariff_change", ":trade_value"),
             (party_get_slot, ":market_prosperity", ":cur_ai_object", slot_town_prosperity),
             (val_add, ":market_prosperity", 30),
             (val_mul, ":market_tariff_change", ":market_prosperity"),
             (val_mul, ":market_tariff_change", ":home_health"),
             (val_div, ":market_tariff_change", 260000),
             (val_add, ":market_tariff_change", ":market_population_bonus"),
             (val_mul, ":market_tariff_change", ":market_tariff_modifier"),
             (val_div, ":market_tariff_change", 100),

             # Home-center tariffs are a smaller producer-side cut of the same flow,
             # weighted a bit more by the village's own ability to participate.
             (assign, ":home_tariff_change", ":trade_value"),
             (party_get_slot, ":home_prosperity", ":home_center", slot_town_prosperity),
             (val_add, ":home_prosperity", 30),
             (val_mul, ":home_tariff_change", ":home_prosperity"),
             (val_mul, ":home_tariff_change", ":home_health"),
             (val_div, ":home_tariff_change", 325000),
             (val_add, ":home_tariff_change", ":producer_bonus"),
             (val_mul, ":home_tariff_change", ":home_tariff_modifier"),
             (val_div, ":home_tariff_change", 100),

             #Adding tax revenue to the center
             (val_max, ":market_tariff_change", 0),
             (call_script, "script_sod_center_apply_tariffs_delta", ":cur_ai_object", ":market_tariff_change"),

             #Adding tax revenue to the home center
             (val_max, ":home_tariff_change", 0),
             (call_script, "script_sod_center_apply_tariffs_delta", ":home_center", ":home_tariff_change"),

             # Increasing food stocks of the town based on actual trade volume,
             # but scaled to town storage capacity rather than huge flat imports.
             (party_get_slot, ":town_food_store", ":cur_ai_object", slot_party_food_store),
             (call_script, "script_center_get_food_store_limit", ":cur_ai_object"),
             (assign, ":food_store_limit", reg0),
             (store_mul, ":comfortable_stock_threshold", ":food_store_limit", 3),
             (val_div, ":comfortable_stock_threshold", 5),
             (store_mul, ":shortage_stock_threshold", ":food_store_limit", 1),
             (val_div, ":shortage_stock_threshold", 5),
             (assign, ":trade_food_import", ":trade_value"),
             (val_div, ":trade_food_import", 60),
             (val_mul, ":trade_food_import", ":market_trade_volume_modifier"),
             (val_div, ":trade_food_import", 100),
             (store_div, ":food_import_cap", ":food_store_limit", 10),
             (val_max, ":food_import_cap", 6),
             (val_add, ":food_import_cap", ":producer_bonus"),
             (val_add, ":food_import_cap", ":market_population_bonus"),
             (try_begin),
               (gt, ":town_food_consumption", 0),
               (store_div, ":consumption_import_bonus", ":town_food_consumption", 20),
               (val_add, ":food_import_cap", ":consumption_import_bonus"),
             (try_end),
             (try_begin),
               (lt, ":town_food_store", ":shortage_stock_threshold"),
               (val_add, ":food_import_cap", 4),
             (else_try),
               (lt, ":town_food_store", ":comfortable_stock_threshold"),
               (val_add, ":food_import_cap", 2),
             (try_end),
             (val_clamp, ":food_import_cap", 0, 20),
             (val_max, ":trade_food_import", 2),
             (val_min, ":trade_food_import", ":food_import_cap"),
             (call_script, "script_sod_center_apply_food_delta", ":cur_ai_object", ":trade_food_import"),
             (assign, ":town_food_store", reg0),

             # Let trade throughput materially influence both producer and market outcomes.
             (assign, ":trade_strength", ":trade_value"),
             (val_div, ":trade_strength", 90),
             (val_clamp, ":trade_strength", 0, 31),

             # Strong inbound trade should help towns prosper, especially if supply is healthy.
             (assign, ":market_gain_chance", 8),
             (val_add, ":market_gain_chance", ":trade_strength"),
             (val_add, ":market_gain_chance", ":market_merchant_happiness"),
             (store_sub, ":market_health_bonus", ":home_health", 100),
             (val_div, ":market_health_bonus", 5),
             (val_add, ":market_gain_chance", ":market_health_bonus"),
             (val_add, ":market_gain_chance", ":market_population_bonus"),
             (try_begin),
               (gt, ":food_store_limit", 0),
               (store_mul, ":comfortable_stock_threshold", ":food_store_limit", 3),
               (val_div, ":comfortable_stock_threshold", 5),
               (ge, ":town_food_store", ":comfortable_stock_threshold"),
               (val_add, ":market_gain_chance", 10),
             (try_end),
             (val_mul, ":market_gain_chance", ":market_trade_volume_modifier"),
             (val_div, ":market_gain_chance", 100),
             (store_sub, ":market_tax_friction", ":market_trade_tax_modifier", 100),
             (val_div, ":market_tax_friction", 5),
             (val_sub, ":market_gain_chance", ":market_tax_friction"),
             (val_clamp, ":market_gain_chance", 5, 61),
             (try_begin),
               (store_random_in_range, ":market_gain_roll", 0, 100),
               (lt, ":market_gain_roll", ":market_gain_chance"),
               (call_script, "script_change_center_prosperity", ":cur_ai_object", 1),
             (try_end),

             (party_get_slot, ":market_health", ":cur_ai_object", slot_center_sod_local_health),
             (try_begin),
               (ge, ":trade_strength", 10),
               (lt, ":market_health", 65),
               (store_random_in_range, ":market_health_roll", 0, 100),
               (lt, ":market_health_roll", 20),
               (call_script, "script_change_center_health", ":cur_ai_object", 1),
             (try_end),

             # Prosperity gain chance now reflects the quality and volume of the trade loop.
             (assign, ":village_gain_chance", 12),
             (val_add, ":village_gain_chance", ":trade_strength"),
             (store_sub, ":market_prosperity_bonus", ":market_prosperity", 30),
             (val_div, ":market_prosperity_bonus", 2),
             (val_add, ":village_gain_chance", ":market_prosperity_bonus"),
             (store_sub, ":health_bonus", ":home_health", 100),
             (val_div, ":health_bonus", 4),
             (val_add, ":village_gain_chance", ":health_bonus"),
             (val_add, ":village_gain_chance", ":producer_bonus"),
             (val_mul, ":village_gain_chance", ":home_trade_volume_modifier"),
             (val_div, ":village_gain_chance", 100),
             (store_sub, ":home_tax_friction", ":home_trade_tax_modifier", 100),
             (val_div, ":home_tax_friction", 6),
             (val_sub, ":village_gain_chance", ":home_tax_friction"),
             (val_clamp, ":village_gain_chance", 8, 85),

             # Adding 1 to village prosperity.
             (try_begin),
               (store_random_in_range, ":rand", 0, 100),
               (lt, ":rand", ":village_gain_chance"),
               (call_script, "script_change_center_prosperity", ":home_center", 1),
             (try_end),

             # Strong, regular trade can also slowly improve the producing village's condition.
             (try_begin),
               (ge, ":trade_strength", 8),
               (store_sub, ":raw_home_health", ":home_health", 100),
               (lt, ":raw_home_health", 62),
               (store_random_in_range, ":village_health_roll", 0, 100),
               (lt, ":village_health_roll", 18),
               (call_script, "script_change_center_health", ":home_center", 1),
             (try_end),
           (try_end),

           #Moving farmers to their home village
           (is_between, ":home_center", villages_begin, villages_end),
           (call_script, "script_sod_trade_network_send_party_to_center", ":party_no", ":home_center", 0),
         (try_end),
       (try_end),
 ]),

("sod_trade_network_describe_report_to_s20",
 [
   (assign, reg20, "$g_sod_trade_network_last_contract_day"),
   (assign, reg21, "$g_sod_trade_network_last_contract_investment"),
   (assign, reg22, "$g_sod_trade_network_last_result_day"),
   (str_store_string, s21, "@none recorded"),
   (try_begin),
     (gt, "$g_sod_trade_network_last_contract_party", 0),
     (str_store_party_name, s21, "$g_sod_trade_network_last_contract_party"),
   (try_end),
   (str_store_string, s25, "@unknown caravan"),
   (try_begin),
     (gt, "$g_sod_trade_network_last_result_party", 0),
     (str_store_party_name, s25, "$g_sod_trade_network_last_result_party"),
   (try_end),
   (str_store_string, s22, "@no arrival recorded"),
   (try_begin),
     (is_between, "$g_sod_trade_network_last_result_center", centers_begin, centers_end),
     (str_store_party_name, s22, "$g_sod_trade_network_last_result_center"),
   (try_end),
   (str_store_string, s23, "@no contract"),
   (try_begin),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_guards),
     (str_store_string, s23, "@funded guards"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_cargo_space),
     (str_store_string, s23, "@bought cargo space"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_insurance),
     (str_store_string, s23, "@insured a caravan"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_relief),
     (str_store_string, s23, "@sponsored relief cargo"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_profit),
     (str_store_string, s23, "@sponsored profit cargo"),
   (try_end),
   (str_store_string, s24, "@no result"),
   (try_begin),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_profitable),
     (str_store_string, s24, "@profitable run"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_protected),
     (str_store_string, s24, "@protected run"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_dangerous),
     (str_store_string, s24, "@dangerous road"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_shortage_supplied),
     (str_store_string, s24, "@shortage supplied"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_taxed),
     (str_store_string, s24, "@hard toll road"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_raided),
     (str_store_string, s24, "@raider-shadowed road"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_exploited),
     (str_store_string, s24, "@shortage exploited"),
   (try_end),
   (str_store_string, s26, "@No broad road order is active in memory."),
   (try_begin),
     (eq, "$g_sod_trade_network_last_strategy_action", 1),
     (str_store_string, s26, "@Recent order: patrol silver sent onto the roads."),
   (else_try),
     (eq, "$g_sod_trade_network_last_strategy_action", 2),
     (str_store_string, s26, "@Recent order: toll pressure challenged at the crossings."),
   (else_try),
     (eq, "$g_sod_trade_network_last_strategy_action", 3),
     (str_store_string, s26, "@Recent order: subsidized relief sent toward a needy market."),
   (else_try),
     (eq, "$g_sod_trade_network_last_strategy_action", 4),
     (str_store_string, s26, "@Recent order: coin invested in a familiar caravan route."),
   (try_end),
   (call_script, "script_sod_trade_network_get_route_pressure_to_regs"),
   (assign, reg23, reg10),
   (assign, reg24, reg11),
   (assign, reg25, reg12),
   (assign, reg26, reg13),
   (assign, reg27, reg14),
   (assign, reg28, 0),
   (try_begin),
     (gt, reg23, reg28),
     (assign, reg28, reg23),
   (try_end),
   (try_begin),
     (gt, reg24, reg28),
     (assign, reg28, reg24),
   (try_end),
   (try_begin),
     (gt, reg25, reg28),
     (assign, reg28, reg25),
   (try_end),
   (try_begin),
     (gt, reg27, reg28),
     (assign, reg28, reg27),
   (try_end),
   (str_store_string, s27, "@Road recommendation: no single pressure dominates. Ask a caravan master for a fresh route before spending broad road coin."),
   (try_begin),
     (ge, reg27, 45),
     (str_store_string, s27, "@Road recommendation: captive traffic is heating the roads. Relief cargo and anti-slaver pressure will do more than pure profit stakes."),
   (else_try),
     (ge, reg24, 55),
     (str_store_string, s27, "@Road recommendation: Black Khergit pressure is high. Fund patrols or ride escort before committing expensive cargo."),
   (else_try),
     (ge, reg23, 55),
     (str_store_string, s27, "@Road recommendation: Boar toll pressure is high. Challenge the crossings before repeat routes bleed coin."),
   (else_try),
     (ge, reg25, 45),
     (str_store_string, s27, "@Road recommendation: Serpent warnings are active. Talk to caravans directly; the road is watched for a reason."),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_taxed),
     (str_store_string, s27, "@Road recommendation: the last run paid hard tolls. Challenge toll pressure or avoid that road until it cools."),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_raided),
     (str_store_string, s27, "@Road recommendation: the last run saw raider shadows. Fund patrols or guards before trusting another caravan."),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_shortage_supplied),
     (str_store_string, s27, "@Road recommendation: relief worked. If the same market remains important, invest in the familiar route."),
   (try_end),
   (str_store_string, s20, "@Trade Network Report^^Best information comes from caravan masters on the road. Reports preserve only what your people have recently heard or sponsored.^^Last contract: {s23} with {s21} on day {reg20}, investment {reg21}.^Last arrival memory: {s24} by {s25} at {s22} on day {reg22}.^{s26}^^Road pressure snapshot:^Boar tolls {reg23}; Black Khergits {reg24}; Serpent warnings {reg25}; Black Army cover {reg26}; captive traffic {reg27}. Highest hostile pressure {reg28}.^^{s27}^^If there is no reliable word, ask a caravan what it carries, where it came from, where it is bound, how bad the roads are, and what goods are selling well. Boar tolls, Black Khergit raids, Serpent warnings, Black Army contracts, and local scarcity all shape their answers."),
 ]),
]
