# COST: low
SCRIPTS = [
("sod_threat_board_generate_offers",
 [
  (store_script_param_1, ":center_no"),

   (call_script, "script_sod_threat_board_normalize_center", ":center_no"),
   (assign, ":center_no", reg0),

   (store_current_day, ":cur_day"),
   (store_sub, ":center_seed", ":center_no", centers_begin),
   (val_max, ":center_seed", 0),
   (store_add, ":seed", ":cur_day", ":center_seed"),

   (store_mod, ":offer_1", ":seed", 12),
   (val_add, ":offer_1", 1),
   (store_add, ":offer_2", ":offer_1", 4),
   (try_begin),
     (gt, ":offer_2", 12),
     (val_sub, ":offer_2", 12),
   (try_end),
   (store_add, ":offer_3", ":offer_1", 8),
   (try_begin),
     (gt, ":offer_3", 12),
     (val_sub, ":offer_3", 12),
   (try_end),

   (try_begin),
     (party_slot_eq, ":center_no", slot_party_type, spt_village),
     (assign, ":offer_3", sod_threat_archetype_cattle_raiders),
   (else_try),
     (party_slot_eq, ":center_no", slot_party_type, spt_castle),
     (assign, ":offer_2", sod_threat_archetype_army_deserters),
   (try_end),

   (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
   (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
   (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
   (party_get_slot, ":local_prosperity", ":center_no", slot_center_sod_local_prosperity),
   (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
   (call_script, "script_sod_get_center_security_profile", ":center_no"),
   (assign, ":effective_threat", reg0),
   (assign, ":security", reg1),
   (assign, ":vulnerability", reg10),

   (try_begin),
     (party_slot_eq, ":center_no", slot_party_type, spt_village),
     (party_get_slot, ":cattle", ":center_no", slot_village_number_of_cattle),
     (try_begin),
       (lt, ":cattle", 12),
       (assign, ":offer_1", sod_threat_archetype_cattle_raiders),
     (else_try),
       (lt, ":population", 180),
       (assign, ":offer_1", sod_threat_archetype_herd_rustlers),
     (try_end),
   (try_end),

   (try_begin),
     (lt, ":prosperity", 30),
     (assign, ":offer_2", sod_threat_archetype_river_pirates),
   (else_try),
     (lt, ":local_prosperity", 25),
     (assign, ":offer_2", sod_threat_archetype_coastal_smugglers),
   (else_try),
     (lt, ":wealth", 1000),
     (assign, ":offer_2", sod_threat_archetype_rogue_company),
   (try_end),

   (try_begin),
     (lt, ":health", 35),
     (assign, ":offer_3", sod_threat_archetype_army_deserters),
   (else_try),
     (lt, ":population", 220),
     (assign, ":offer_3", sod_threat_archetype_invader_scouts),
   (try_end),

   (try_begin),
     (ge, ":effective_threat", 7),
     (assign, ":offer_1", sod_threat_archetype_raiding_captain),
   (else_try),
     (ge, ":effective_threat", 4),
     (assign, ":offer_1", sod_threat_archetype_invader_scouts),
   (try_end),

   (try_begin),
     (ge, ":vulnerability", 70),
     (assign, ":offer_2", sod_threat_archetype_rogue_company),
   (else_try),
     (lt, ":security", 0),
     (assign, ":offer_2", sod_threat_archetype_guild_traitors),
   (try_end),

   (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_offer_1, ":offer_1"),
   (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_offer_2, ":offer_2"),
   (quest_set_slot, "qst_regional_threat_contract", slot_quest_sod_threat_offer_3, ":offer_3"),
 ]),
]
