# COST: low
SCRIPTS = [
("sod_merc_guild_describe_ledger_to_s20",
 [
   (store_script_param_1, ":guild_faction"),

   (str_store_string, s20, "@No mercenary ledger available."),
   (try_begin),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (call_script, "script_sod_merc_guild_repair_ledgers"),
     (str_store_faction_name, s21, ":guild_faction"),
     (faction_get_slot, reg20, ":guild_faction", slot_faction_sod_merc_treasury),
     (faction_get_slot, reg21, ":guild_faction", slot_faction_sod_merc_manpower),
     (faction_get_slot, reg22, ":guild_faction", slot_faction_sod_merc_veterans),
     (faction_get_slot, reg23, ":guild_faction", slot_faction_sod_merc_elite_stock),
     (faction_get_slot, reg24, ":guild_faction", slot_faction_sod_merc_active_contracts),
     (faction_get_slot, reg25, ":guild_faction", slot_faction_sod_merc_support_capacity),
     (faction_get_slot, reg26, ":guild_faction", slot_faction_sod_merc_price_pressure),
     (faction_get_slot, reg27, ":guild_faction", slot_faction_sod_merc_market_reputation),
     (faction_get_slot, reg28, ":guild_faction", slot_faction_sod_merc_world_activity_pressure),
     (call_script, "script_sod_count_mercenary_guild_halls_for_guild", ":guild_faction"),
     (assign, reg33, reg0),
     (assign, reg34, reg1),
     (assign, reg35, reg2),
     (store_relation, reg30, ":guild_faction", "fac_player_faction"),
     (faction_get_slot, reg31, ":guild_faction", player_debt_to_faction),
     (assign, reg29, 0),
     (assign, ":top_contract_value", 0),
     (assign, ":top_employer", 0),
     (try_for_parties, ":party_no"),
       (party_is_active, ":party_no"),
       (party_slot_eq, ":party_no", slot_party_type, spt_mercenary_lord_party),
       (party_slot_eq, ":party_no", slot_party_sod_merc_contract_guild, ":guild_faction"),
       (val_add, reg29, 1),
     (try_end),
     (try_for_parties, ":party_no"),
       (party_is_active, ":party_no"),
       (party_slot_eq, ":party_no", slot_party_sod_merc_contract_guild, ":guild_faction"),
       (party_get_slot, ":contract_value", ":party_no", slot_party_sod_merc_contract_value),
       (ge, ":contract_value", ":top_contract_value"),
       (party_get_slot, ":employer", ":party_no", slot_party_sod_merc_contract_employer),
       (assign, ":top_contract_value", ":contract_value"),
       (assign, ":top_employer", ":employer"),
     (try_end),
     (assign, reg32, ":top_contract_value"),
     (try_begin),
       (gt, ":top_employer", 0),
       (str_store_faction_name, s24, ":top_employer"),
     (else_try),
       (str_store_string, s24, "@no active employer"),
     (try_end),
     (str_store_string, s22, "@available"),
     (try_begin),
       (ge, reg24, reg25),
       (str_store_string, s22, "@overcommitted"),
     (else_try),
       (store_mul, ":load", reg24, 100),
       (val_div, ":load", reg25),
       (ge, ":load", 67),
       (str_store_string, s22, "@stretched"),
     (else_try),
       (store_mul, ":load", reg24, 100),
       (val_div, ":load", reg25),
       (le, ":load", 25),
       (str_store_string, s22, "@plentiful"),
     (try_end),
     (str_store_string, s23, "@Road pressure quiet."),
     (try_begin),
       (ge, reg28, 35),
       (str_store_string, s23, "@Road pressure severe; world activity is draining coin and slowing replacement drafts."),
     (else_try),
       (ge, reg28, 15),
       (str_store_string, s23, "@Road pressure active; caravans, threats, and border trouble are stretching the guild."),
     (try_end),
     (call_script, "script_sod_merc_market_calculate_guild_supply", ":guild_faction"),
     (assign, ":refusal_reason", reg6),
     (str_store_string, s25, "@Open for contracts."),
     (try_begin),
       (eq, ":refusal_reason", sod_merc_refusal_no_capacity),
       (str_store_string, s25, "@Refusing work: no spare companies."),
     (else_try),
       (eq, ":refusal_reason", sod_merc_refusal_low_manpower),
       (str_store_string, s25, "@Refusing work: manpower too thin."),
     (else_try),
       (eq, ":refusal_reason", sod_merc_refusal_low_treasury),
       (str_store_string, s25, "@Refusing work: treasury too low."),
     (else_try),
       (eq, ":refusal_reason", sod_merc_refusal_overextended),
       (str_store_string, s25, "@Refusing work: overextended."),
     (else_try),
       (eq, ":refusal_reason", sod_merc_refusal_bad_relations),
       (str_store_string, s25, "@Refusing work: relations are too sour."),
     (else_try),
       (eq, ":refusal_reason", sod_merc_refusal_loss_shock),
       (str_store_string, s25, "@Refusing work: recent losses have shaken the rolls."),
     (try_end),
     (str_store_string, s26, "@No priority claim."),
     (try_begin),
       (faction_slot_eq, "fac_player_faction", slot_faction_merc_pact, ":guild_faction"),
       (str_store_string, s26, "@Player pact active; priority depends on payment record."),
     (else_try),
       (ge, reg30, 40),
       (str_store_string, s26, "@High standing gives the player preferential access."),
     (try_end),
     (str_store_string, s20, "@{s21}: {s22}. Treasury {reg20}; manpower {reg21}; veterans {reg22}; elites {reg23}; contracts {reg24}/{reg25}; named leaders active {reg29}; price pressure {reg26}; reputation {reg27}; road pressure {reg28}.^Castle halls backing this guild: {reg33} total, {reg34} player-held, {reg35} local hires in stock.^Top employer: {s24}; top contract {reg32}. Player standing {reg30}; debt {reg31}. {s26}^{s25}^{s23}"),
   (try_end),
 ]),
]
