# COST: medium
SCRIPTS = [
("sod_merc_market_calculate_world_activity_pressure",
 [
   (store_script_param_1, ":faction_no"),

   (assign, ":pressure", 0),
   (assign, ":treasury_drain", 0),
   (assign, ":report_flags", 0),

   (try_begin),
     (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
     (neq, ":faction_no", "fac_kingdom_6"),
     (store_current_day, ":cur_day"),
     (faction_get_slot, ":memory_last_day", ":faction_no", slot_faction_diplomacy_memory_player_last_day),
     (store_sub, ":memory_age", ":cur_day", ":memory_last_day"),
     (is_between, ":memory_age", 0, 8),
     (faction_get_slot, ":recent_grievance", ":faction_no", slot_faction_diplomacy_memory_player_grievance),
     (gt, ":recent_grievance", 0),
     (assign, ":caravan_attack_signal", sod_diplomacy_memory_caravan_attack),
     (store_div, ":caravan_pressure", ":recent_grievance", 5),
     (val_add, ":pressure", ":caravan_pressure"),
     (val_add, ":report_flags", ":caravan_attack_signal"),
   (try_end),

   (try_begin),
     (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
     (neq, ":faction_no", "fac_kingdom_6"),
     (quest_slot_eq, "qst_regional_threat_contract", slot_quest_sod_threat_sponsor_faction, ":faction_no"),
     (quest_get_slot, ":threat_tier", "qst_regional_threat_contract", slot_quest_sod_threat_tier),
     (val_max, ":threat_tier", 1),
     (store_mul, ":threat_pressure", ":threat_tier", 8),
     (val_add, ":pressure", ":threat_pressure"),
     (assign, ":report_flags", 1),
   (try_end),

   (try_begin),
     (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
     (neq, ":faction_no", "fac_kingdom_6"),
     (store_current_day, ":cur_day"),
     (store_sub, ":days_since_incident", ":cur_day", "$g_sod_mini_faction_last_incident_day"),
     (is_between, ":days_since_incident", 0, 8),
     (gt, "$g_sod_mini_faction_last_incident_center", 0),
     (store_faction_of_party, ":incident_faction", "$g_sod_mini_faction_last_incident_center"),
     (eq, ":incident_faction", ":faction_no"),
     (store_div, ":incident_pressure", "$g_sod_mini_faction_last_incident_score", 8),
     (val_add, ":pressure", ":incident_pressure"),
     (assign, ":report_flags", 2),
   (try_end),

   (try_begin),
     (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
     (neq, ":faction_no", "fac_kingdom_6"),
     (try_for_range, ":village_no", villages_begin, villages_end),
       (store_faction_of_party, ":village_faction", ":village_no"),
       (eq, ":village_faction", ":faction_no"),
       (party_get_slot, ":looter_pressure", ":village_no", slot_center_sod_looter_raid_pressure),
       (val_max, ":looter_pressure", 0),
       (store_div, ":village_pressure", ":looter_pressure", 8),
       (val_add, ":pressure", ":village_pressure"),
     (try_end),
   (try_end),

   (try_begin),
     (eq, ":faction_no", "fac_sod_merc_guild1"),
     (faction_get_slot, ":guild_pressure", "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
     (store_div, ":guild_pressure", ":guild_pressure", 7),
     (val_add, ":pressure", ":guild_pressure"),
   (else_try),
     (eq, ":faction_no", "fac_sod_merc_guild2"),
     (faction_get_slot, ":guild_pressure", "fac_sod_merc_guild2", slot_faction_conquistador_requisition_heat),
     (store_div, ":guild_pressure", ":guild_pressure", 7),
     (val_add, ":pressure", ":guild_pressure"),
   (else_try),
     (eq, ":faction_no", "fac_sod_merc_guild3"),
     (faction_get_slot, ":guild_pressure", "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),
     (store_div, ":guild_pressure", ":guild_pressure", 7),
     (val_add, ":pressure", ":guild_pressure"),
   (else_try),
     (eq, ":faction_no", "fac_sod_merc_guild4"),
     (faction_get_slot, ":guild_pressure", "fac_sod_merc_guild4", slot_faction_jotnar_hearth_pressure),
     (store_div, ":guild_pressure", ":guild_pressure", 7),
     (val_add, ":pressure", ":guild_pressure"),
   (else_try),
     (eq, ":faction_no", "fac_sod_merc_guild5"),
     (faction_get_slot, ":guild_pressure", "fac_sod_merc_guild5", slot_faction_serpent_route_pressure),
     (store_div, ":guild_pressure", ":guild_pressure", 7),
     (val_add, ":pressure", ":guild_pressure"),
   (else_try),
     (eq, ":faction_no", "fac_sod_merc_guild6"),
     (faction_get_slot, ":guild_pressure", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
     (store_div, ":guild_pressure", ":guild_pressure", 7),
     (val_add, ":pressure", ":guild_pressure"),
   (else_try),
     (eq, ":faction_no", "fac_sod_merc_guild7"),
     (faction_get_slot, ":guild_pressure", "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure),
     (store_div, ":guild_pressure", ":guild_pressure", 7),
     (val_add, ":pressure", ":guild_pressure"),
   (try_end),

   (try_begin),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":faction_no"),
     (store_div, ":treasury_drain", ":pressure", 2),
     (val_mul, ":treasury_drain", 15),
     (try_begin),
       (gt, ":pressure", 0),
       (assign, ":report_flags", 3),
     (try_end),
   (try_end),

   (val_clamp, ":pressure", 0, 60),
   (val_clamp, ":treasury_drain", 0, 2000),
   (try_begin),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":faction_no"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_world_activity_pressure, ":pressure"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_last_report_flags, ":report_flags"),
   (try_end),

   (assign, reg0, ":pressure"),
   (assign, reg1, ":treasury_drain"),
   (assign, reg2, ":report_flags"),
 ]),
]
