# COST: low
# COST: O(number of player centers)
SCRIPTS = [
("sod_describe_faith_world_report",
  [
    (call_script, "script_sod_troop_get_effective_faith"),
    (assign, reg1, reg1),
    (assign, reg2, reg2),
    (assign, reg3, reg0),
    (store_add, reg0, "str_sod_faith_suffix_0", "$g_sod_faith"),
    (str_store_string, s2, reg0),

    (call_script, "script_sod_get_realm_faith_profile", "fac_player_supporters_faction"),
    (assign, ":dominant_faith", reg0),
    (assign, reg4, reg1),
    (assign, reg5, reg2),
    (assign, reg6, reg3),
    (assign, reg7, reg4),
    (store_add, reg0, "str_sod_faith_suffix_0", ":dominant_faith"),
    (str_store_string, s3, reg0),

    (assign, ":ready_centers", 0),
    (assign, ":strained_centers", 0),
    (assign, ":religious_seats", 0),
    (assign, ":best_center", -1),
    (assign, ":best_readiness", -1),
    (try_for_range, ":center_no", centers_begin, centers_end),
      (store_faction_of_party, ":center_faction", ":center_no"),
      (this_or_next|eq, ":center_faction", "fac_player_supporters_faction"),
      (eq, ":center_faction", "fac_player_faction"),
      (call_script, "script_sod_get_center_faith_profile", ":center_no"),
      (assign, ":tension", reg3),
      (assign, ":institution", reg4),
      (assign, ":readiness", reg8),
      (try_begin),
        (ge, ":institution", 20),
        (val_add, ":religious_seats", 1),
      (try_end),
      (try_begin),
        (ge, ":readiness", 70),
        (val_add, ":ready_centers", 1),
      (try_end),
      (try_begin),
        (gt, ":tension", sod_faith_tension_soft_cap),
        (val_add, ":strained_centers", 1),
      (try_end),
      (try_begin),
        (gt, ":readiness", ":best_readiness"),
        (assign, ":best_readiness", ":readiness"),
        (assign, ":best_center", ":center_no"),
      (try_end),
    (try_end),
    (assign, reg8, ":religious_seats"),
    (assign, reg9, ":ready_centers"),
    (assign, reg10, ":strained_centers"),
    (try_begin),
      (gt, ":best_center", 0),
      (str_store_party_name, s4, ":best_center"),
      (assign, reg11, ":best_readiness"),
      (call_script, "script_sod_get_center_faith_profile", ":best_center"),
      (assign, reg12, reg2),
      (assign, reg13, reg3),
      (assign, reg14, reg4),
      (assign, reg15, reg7),
    (else_try),
      (str_store_string, s4, "@none"),
      (assign, reg11, 0),
      (assign, reg12, 0),
      (assign, reg13, 0),
      (assign, reg14, 0),
      (assign, reg15, 0),
    (try_end),

    (str_store_string, s1, "@Faith And Institutions^^Chosen faith: {s2}. Raw faith {reg1}, holy burden {reg2}, effective faith {reg3}. The chosen faith is locked; end-tier nobles ascend only through this creed.^^Realm profile:^Dominant realm faith: {s3}. Player-faith coverage {reg4}. faith tension {reg5}. Clergy legitimacy {reg6}. Centers counted {reg7}. Religious seats {reg8}. Ascension-ready centers {reg9}. Strained centers {reg10}.^^Best ascension seat:^ {s4}: readiness {reg11}, player-faith support {reg12}, tension {reg13}, institution strength {reg14}, unrest pressure {reg15}.^^How to read this:^Temples and chapels gate faith-elite access. Shrines and monasteries spread local support and help communities recover when tension is controlled. Rival faiths can stabilize their own communities, but high tension raises unrest and weakens recovery. Security, food, raids, prosperity, and clergy happiness all shape weekly faith drift."),
  ]),
]
