# COST: low
SCRIPTS = [
("sod_boar_clan_get_toll_amount",
 [
   (store_script_param_1, ":party_no"),
   (store_party_size, ":toll", ":party_no"),
   (val_mul, ":toll", 10),
   (val_clamp, ":toll", 1, 1001),
   (assign, reg0, ":toll"),
 ]),

("sod_boar_clan_prepare_encounter",
 [
   (assign, "$g_sod_boar_toll_amount", 0),
   (assign, "$g_sod_boar_hire_cost", 0),
   (assign, "$g_sod_demand_money", -1),
   (store_relation, ":relation", "fac_sod_merc_guild7", "fac_player_supporters_faction"),
   (faction_get_slot, ":intimidation", "fac_sod_merc_guild7", slot_faction_boar_intimidation),
   (try_begin),
     (this_or_next|lt, ":relation", 0),
     (ge, ":intimidation", 70),
     (str_store_string, s5, "@Stand easy, clan, but keep hands near steel. These travelers have not paid the road kindly, and the Boar Clan remembers every unpaid insult."),
   (else_try),
     (call_script, "script_sod_boar_clan_get_toll_amount", "$g_encountered_party"),
     (assign, "$g_sod_boar_toll_amount", reg0),
     (assign, reg5, reg0),
     (assign, "$g_sod_demand_money", "$g_encountered_party"),
     (str_store_string, s5, "@Hold there, wanderer. These roads are under Boar Clan warding, and every armed company that uses them owes frontier tribute. Pay {reg5} denars and pass with your honor untested."),
   (try_end),
 ]),

("sod_boar_clan_get_hire_cost",
 [
   (store_script_param_1, ":party_no"),
   (assign, ":total_cost", 0),
   (party_get_num_companion_stacks, ":num_stacks", ":party_no"),
   (try_for_range, ":i_stack", 0, ":num_stacks"),
     (party_stack_get_troop_id, ":stack_troop", ":party_no", ":i_stack"),
     (party_stack_get_size, ":stack_size", ":party_no", ":i_stack"),
     (call_script, "script_game_get_join_cost", ":stack_troop"),
     (assign, ":cur_cost", reg0),
     (val_max, ":cur_cost", 0),
     (val_mul, ":cur_cost", ":stack_size"),
     (val_add, ":total_cost", ":cur_cost"),
   (try_end),
   (val_clamp, ":total_cost", 1, 20001),
   (assign, reg0, ":total_cost"),
 ]),

("sod_boar_clan_prepare_hire_offer",
 [
   (store_encountered_party, ":party_no"),
   (call_script, "script_sod_boar_clan_get_hire_cost", ":party_no"),
   (assign, "$g_sod_boar_hire_cost", reg0),
   (assign, reg5, reg0),
 ]),

("sod_boar_clan_grant_toll_passage",
 [
   (store_current_hours, ":protected_until"),
   (val_add, ":protected_until", 72),
   (party_set_slot, "$g_encountered_party", slot_party_ignore_player_until, ":protected_until"),
   (party_ignore_player, "$g_encountered_party", 72),
   (assign, "$g_sod_boar_toll_amount", 0),
   (call_script, "script_sod_safe_leave_encounter"),
 ]),

("sod_boar_clan_convert_to_player_mercenaries",
 [
   (assign, ":converted", 0),
   (try_begin),
   (gt, "$g_encountered_party", 0),
   (neq, "$g_encountered_party", "p_main_party"),
   (party_is_active, "$g_encountered_party"),
   (party_get_template_id, ":encounter_template", "$g_encountered_party"),
   (this_or_next|eq, ":encounter_template", "pt_boar_clan_fighters"),
   (eq, ":encounter_template", "pt_boar_clan_fighters_desert"),
   (set_spawn_radius, 1),
   (spawn_around_party, "$g_encountered_party", "pt_player_mercenaries"),
   (assign, ":mercs", reg0),
   (gt, ":mercs", 0),
   (party_is_active, ":mercs"),
   (call_script, "script_party_add_party", ":mercs", "$g_encountered_party"),
   (remove_party, "$g_encountered_party"),
   (try_begin),
     (eq, "$g_custom_banner", 1),
     (troop_get_slot, ":flag_icon", "trp_player", slot_troop_custom_banner_map_flag_type),
     (val_max, ":flag_icon", 0),
     (val_add, ":flag_icon", custom_banner_map_icons_begin),
     (party_set_banner_icon, ":mercs", ":flag_icon"),
   (else_try),
     (troop_get_slot, ":cur_banner", "trp_player", slot_troop_banner_scene_prop),
     (gt, ":cur_banner", 0),
     (val_sub, ":cur_banner", banner_scene_props_begin),
     (val_add, ":cur_banner", banner_map_icons_begin),
     (party_set_banner_icon, ":mercs", ":cur_banner"),
   (try_end),
   (party_set_faction, ":mercs", "fac_player_faction"),
   (party_set_slot, ":mercs", slot_party_merc_contract, 365),
   (party_set_slot, ":mercs", slot_party_type, spt_player_mercenaries),
   (party_set_slot, ":mercs", slot_party_boss, "trp_player"),
   (party_set_ai_object, ":mercs", "p_main_party"),
   (party_set_ai_behavior, ":mercs", ai_bhvr_escort_party),
   (assign, ":converted", 1),
   (try_end),
   (try_begin),
     (eq, ":converted", 0),
     (display_message, "@The Boar Clan band could not form under your banner. No silver changed hands.", 0xFFCC66),
   (try_end),
   (assign, reg0, ":converted"),
   (call_script, "script_sod_safe_leave_encounter"),
 ]),
]
