# COST: low
SCRIPTS = [
("sod_merc_market_try_accept_bid",
 [
   (store_script_param_1, ":guild_faction"),
   (store_script_param_2, ":kingdom_faction"),
   (store_script_param, ":bid_value", 3),
   (store_script_param, ":demand_type", 4),
   (store_script_param, ":company_size", 5),
   (store_script_param, ":term_days", 6),

   (assign, ":accepted", 0),
   (assign, ":spawned_party", 0),

   (try_begin),
     (is_between, ":kingdom_faction", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":kingdom_faction", slot_faction_state, sfs_active),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (ge, ":bid_value", 250),
     (ge, ":company_size", 20),
     (faction_get_slot, ":budget", ":kingdom_faction", slot_faction_sod_merc_budget),
     (ge, ":budget", ":bid_value"),
     (assign, ":budget_reserve", 200),
     (faction_get_slot, ":urgency", ":kingdom_faction", slot_faction_sod_merc_contract_urgency),
     (try_begin),
       (le, ":urgency", 2),
       (store_div, ":budget_reserve", ":budget", 5),
       (val_max, ":budget_reserve", 200),
     (else_try),
       (store_div, ":budget_reserve", ":budget", 10),
       (val_max, ":budget_reserve", 100),
     (try_end),
     (store_sub, ":budget_after_bid", ":budget", ":bid_value"),
     (ge, ":budget_after_bid", ":budget_reserve"),
     (call_script, "script_sod_merc_market_calculate_guild_supply", ":guild_faction", 0),
     (assign, ":available_companies", reg0),
     (assign, ":max_company_size", reg1),
     (assign, ":quality", reg2),
     (assign, ":refusal_reason", reg6),
     (gt, ":available_companies", 0),
     (ge, ":max_company_size", ":company_size"),
     (eq, ":refusal_reason", sod_merc_refusal_none),

     (assign, ":boss_troop", 0),
     (assign, ":boss_party", 0),
     (faction_get_slot, ":leader_troop", ":kingdom_faction", slot_faction_leader),
     (try_begin),
       (is_between, ":leader_troop", kingdom_heroes_begin, kingdom_heroes_end),
       (troop_get_slot, ":leader_party", ":leader_troop", slot_troop_leaded_party),
       (gt, ":leader_party", 0),
       (assign, ":boss_troop", ":leader_troop"),
       (assign, ":boss_party", ":leader_party"),
     (try_end),
     (try_begin),
       (le, ":boss_party", 0),
       (try_for_range, ":kingdom_hero", kingdom_heroes_begin, kingdom_heroes_end),
         (eq, ":boss_party", 0),
         (store_troop_faction, ":hero_faction", ":kingdom_hero"),
         (eq, ":hero_faction", ":kingdom_faction"),
         (troop_get_slot, ":hero_party", ":kingdom_hero", slot_troop_leaded_party),
         (gt, ":hero_party", 0),
         (assign, ":boss_troop", ":kingdom_hero"),
         (assign, ":boss_party", ":hero_party"),
       (try_end),
     (try_end),
     (gt, ":boss_party", 0),
     # Resolve the role before formation. A local crisis without a viable
     # target becomes field service before its company mix is selected.
     (call_script, "script_sod_merc_market_resolve_ai_contract_role", ":kingdom_faction", ":demand_type", ":boss_party"),
     (assign, ":effective_demand_type", reg0),

     (assign, ":collectable_wealth", 0),
     (try_begin),
       (is_between, ":boss_troop", kingdom_heroes_begin, kingdom_heroes_end),
       (troop_get_slot, ":payer_wealth", ":boss_troop", slot_troop_wealth),
       (val_max, ":payer_wealth", 0),
       (val_add, ":collectable_wealth", ":payer_wealth"),
     (try_end),
     (try_begin),
       (is_between, ":leader_troop", kingdom_heroes_begin, kingdom_heroes_end),
       (neq, ":leader_troop", ":boss_troop"),
       (troop_get_slot, ":payer_wealth", ":leader_troop", slot_troop_wealth),
       (val_max, ":payer_wealth", 0),
       (val_add, ":collectable_wealth", ":payer_wealth"),
     (try_end),
     (try_for_range, ":kingdom_hero", kingdom_heroes_begin, kingdom_heroes_end),
       (store_troop_faction, ":hero_faction", ":kingdom_hero"),
       (eq, ":hero_faction", ":kingdom_faction"),
       (neq, ":kingdom_hero", ":boss_troop"),
       (neq, ":kingdom_hero", ":leader_troop"),
       (troop_get_slot, ":payer_wealth", ":kingdom_hero", slot_troop_wealth),
       (val_max, ":payer_wealth", 0),
       (val_add, ":collectable_wealth", ":payer_wealth"),
     (try_end),
     (ge, ":collectable_wealth", ":bid_value"),

     (call_script, "script_cf_spawn_ai_mercs", ":boss_troop", ":guild_faction", ":boss_party", ":company_size", ":kingdom_faction", ":effective_demand_type"),
     (assign, ":spawned_party", reg0),
     (gt, ":spawned_party", 0),

     (assign, ":remaining_payment", ":bid_value"),
     (try_begin),
       (is_between, ":boss_troop", kingdom_heroes_begin, kingdom_heroes_end),
       (troop_get_slot, ":payer_wealth", ":boss_troop", slot_troop_wealth),
       (val_max, ":payer_wealth", 0),
       (assign, ":payment", ":payer_wealth"),
       (val_min, ":payment", ":remaining_payment"),
       (val_sub, ":payer_wealth", ":payment"),
       (troop_set_slot, ":boss_troop", slot_troop_wealth, ":payer_wealth"),
       (val_sub, ":remaining_payment", ":payment"),
     (try_end),
     (try_begin),
       (gt, ":remaining_payment", 0),
       (is_between, ":leader_troop", kingdom_heroes_begin, kingdom_heroes_end),
       (neq, ":leader_troop", ":boss_troop"),
       (troop_get_slot, ":payer_wealth", ":leader_troop", slot_troop_wealth),
       (val_max, ":payer_wealth", 0),
       (assign, ":payment", ":payer_wealth"),
       (val_min, ":payment", ":remaining_payment"),
       (val_sub, ":payer_wealth", ":payment"),
       (troop_set_slot, ":leader_troop", slot_troop_wealth, ":payer_wealth"),
       (val_sub, ":remaining_payment", ":payment"),
     (try_end),
     (try_for_range, ":kingdom_hero", kingdom_heroes_begin, kingdom_heroes_end),
       (gt, ":remaining_payment", 0),
       (store_troop_faction, ":hero_faction", ":kingdom_hero"),
       (eq, ":hero_faction", ":kingdom_faction"),
       (neq, ":kingdom_hero", ":boss_troop"),
       (neq, ":kingdom_hero", ":leader_troop"),
       (troop_get_slot, ":payer_wealth", ":kingdom_hero", slot_troop_wealth),
       (val_max, ":payer_wealth", 0),
       (assign, ":payment", ":payer_wealth"),
       (val_min, ":payment", ":remaining_payment"),
       (val_sub, ":payer_wealth", ":payment"),
       (troop_set_slot, ":kingdom_hero", slot_troop_wealth, ":payer_wealth"),
       (val_sub, ":remaining_payment", ":payment"),
     (try_end),
     (eq, ":remaining_payment", 0),

     (store_current_day, ":cur_day"),
     (store_add, ":term_end", ":cur_day", ":term_days"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_employer, ":kingdom_faction"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_guild, ":guild_faction"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_value, ":bid_value"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_role, ":effective_demand_type"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_start_day, ":cur_day"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_initial_size, ":company_size"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_loss_score, 0),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_term_end, ":term_end"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_quality, ":quality"),
     (party_set_slot, ":spawned_party", slot_party_sod_merc_contract_replenishment_level, ":max_company_size"),
     (party_set_slot, ":spawned_party", slot_party_merc_contract, ":term_end"),
     (party_set_slot, ":spawned_party", slot_party_orginal_faction, ":guild_faction"),
     (call_script, "script_sod_merc_market_deploy_ai_contract", ":spawned_party", ":kingdom_faction", ":effective_demand_type", ":boss_party"),

     (faction_get_slot, ":cached_contract_value", ":guild_faction", slot_faction_sod_merc_contract_value_cache),
     (val_add, ":cached_contract_value", ":bid_value"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_contract_value_cache, ":cached_contract_value"),
     (store_sub, ":guild_offset", ":guild_faction", guilds_begin),
     (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_value_cache_begin, ":guild_offset"),
     (faction_get_slot, ":cached_contract_value", ":kingdom_faction", ":cache_slot"),
     (val_add, ":cached_contract_value", ":bid_value"),
     (faction_set_slot, ":kingdom_faction", ":cache_slot", ":cached_contract_value"),
     (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_count_cache_begin, ":guild_offset"),
     (faction_get_slot, ":cached_active_contracts", ":kingdom_faction", ":cache_slot"),
     (val_add, ":cached_active_contracts", 1),
     (faction_set_slot, ":kingdom_faction", ":cache_slot", ":cached_active_contracts"),

     (assign, ":budget", ":budget_after_bid"),
     (val_max, ":budget", 0),
     (faction_set_slot, ":kingdom_faction", slot_faction_sod_merc_budget, ":budget"),
     (faction_set_slot, ":kingdom_faction", slot_faction_sod_merc_last_hired_guild, ":guild_faction"),

     (faction_get_slot, ":treasury", ":guild_faction", slot_faction_sod_merc_treasury),
     (faction_get_slot, ":manpower", ":guild_faction", slot_faction_sod_merc_manpower),
     (faction_get_slot, ":veterans", ":guild_faction", slot_faction_sod_merc_veterans),
     (faction_get_slot, ":active_contracts", ":guild_faction", slot_faction_sod_merc_active_contracts),
     (val_add, ":treasury", ":bid_value"),
     (val_sub, ":manpower", ":company_size"),
     (store_div, ":veteran_commitment", ":company_size", 5),
     (val_sub, ":veterans", ":veteran_commitment"),
     (val_add, ":active_contracts", 1),
     (val_max, ":manpower", 0),
     (val_max, ":veterans", 0),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_treasury, ":treasury"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_manpower, ":manpower"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_veterans, ":veterans"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_active_contracts, ":active_contracts"),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_contract_load, ":active_contracts"),
     (call_script, "script_sod_merc_market_apply_guardrails", ":guild_faction"),
     (call_script, "script_sod_merc_market_calculate_guild_supply", ":guild_faction", 0),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_weekly_supply_available_cache, reg0),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_weekly_supply_max_size_cache, reg1),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_weekly_supply_quality_cache, reg2),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_weekly_supply_price_pressure_cache, reg3),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_weekly_supply_long_willingness_cache, reg4),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_weekly_supply_danger_willingness_cache, reg5),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_weekly_supply_refusal_reason_cache, reg6),
     (assign, ":accepted", 1),
   (try_end),

   (assign, reg0, ":accepted"),
   (assign, reg1, ":spawned_party"),
 ]),
]
