# COST: O(1)
SCRIPTS = [
("sod_get_center_construction_workforce",
  [
    (store_script_param, ":center_no", 1),

    (assign, ":workforce", 0),
    (assign, ":population", 0),
    (assign, ":health", 50),
    (assign, ":prosperity", 50),
    (assign, ":food_security", 100),
    (assign, ":workforce_cap", 0),

    (try_begin),
      (gt, ":center_no", 0),
      (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
      (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
      (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),

      (try_begin),
        (is_between, ":center_no", villages_begin, villages_end),
        (gt, ":population", 0),
        (store_div, ":workforce", ":population", sod_village_construction_pop_divisor),
        (assign, ":workforce_cap", sod_village_construction_workforce_cap),
      (else_try),
        (is_between, ":center_no", towns_begin, towns_end),
        (gt, ":population", 0),
        (store_div, ":workforce", ":population", sod_town_construction_pop_divisor),
        (assign, ":workforce_cap", sod_town_construction_workforce_cap),
      (else_try),
        (is_between, ":center_no", castles_begin, castles_end),
        (party_get_num_companions, ":garrison", ":center_no"),
        (call_script, "script_sod_get_castle_support_profile", ":center_no"),
        (assign, ":castle_support", reg0),
        (assign, ":bound_population", reg2),
        (store_div, ":workforce", ":bound_population", sod_castle_construction_bound_pop_divisor),
        (store_div, ":support_labor", ":castle_support", sod_castle_construction_support_divisor),
        (val_add, ":workforce", ":support_labor"),
        (try_begin),
          (gt, ":garrison", 0),
          (store_div, ":garrison_labor", ":garrison", sod_castle_construction_garrison_divisor),
          (val_add, ":workforce", ":garrison_labor"),
          (val_max, ":workforce", sod_castle_construction_min_garrison_labor),
        (try_end),
        (assign, ":workforce_cap", sod_castle_construction_workforce_cap),
      (try_end),

      (try_begin),
        (gt, ":workforce", 0),
        (call_script, "script_sod_get_center_population_capacity_profile", ":center_no"),
        (assign, ":labor_base_pct", reg4),
        (val_mul, ":workforce", ":labor_base_pct"),
        (val_div, ":workforce", 100),

        (call_script, "script_sod_get_center_food_profile", ":center_no"),
        (assign, ":food_security", reg4),

        (try_begin),
          (lt, ":health", 0),
          (val_mul, ":workforce", 50),
          (val_div, ":workforce", 100),
        (else_try),
          (lt, ":health", 25),
          (val_mul, ":workforce", 65),
          (val_div, ":workforce", 100),
        (else_try),
          (lt, ":health", 50),
          (val_mul, ":workforce", 85),
          (val_div, ":workforce", 100),
        (else_try),
          (gt, ":health", 75),
          (val_mul, ":workforce", 110),
          (val_div, ":workforce", 100),
        (try_end),

        (try_begin),
          (lt, ":prosperity", 20),
          (val_mul, ":workforce", 75),
          (val_div, ":workforce", 100),
        (else_try),
          (lt, ":prosperity", 40),
          (val_mul, ":workforce", 90),
          (val_div, ":workforce", 100),
        (else_try),
          (gt, ":prosperity", 70),
          (val_mul, ":workforce", 115),
          (val_div, ":workforce", 100),
        (try_end),

        (try_begin),
          (lt, ":food_security", 300),
          (val_mul, ":workforce", 65),
          (val_div, ":workforce", 100),
        (else_try),
          (lt, ":food_security", 700),
          (val_mul, ":workforce", 85),
          (val_div, ":workforce", 100),
        (else_try),
          (gt, ":food_security", 1200),
          (val_mul, ":workforce", 110),
          (val_div, ":workforce", 100),
        (try_end),

        (call_script, "script_sod_get_center_security_profile", ":center_no"),
        (assign, ":effective_threat", reg0),
        (assign, ":security", reg1),
        (assign, ":unrest_pressure", reg8),
        # sod_center_modifier_security_flat feeds this through the shared security profile.
        (try_begin),
          (lt, ":security", -20),
          (val_mul, ":workforce", 85),
          (val_div, ":workforce", 100),
        (else_try),
          (gt, ":security", 20),
          (val_mul, ":workforce", 110),
          (val_div, ":workforce", 100),
        (try_end),
        (try_begin),
          (ge, ":effective_threat", 7),
          (val_mul, ":workforce", 70),
          (val_div, ":workforce", 100),
        (else_try),
          (ge, ":effective_threat", 4),
          (val_mul, ":workforce", 85),
          (val_div, ":workforce", 100),
        (try_end),
        (try_begin),
          (gt, ":unrest_pressure", 30),
          (val_mul, ":workforce", 85),
          (val_div, ":workforce", 100),
        (try_end),

        (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_construction_speed_pct),
        (assign, ":construction_speed_pct", reg0),
        (val_mul, ":workforce", ":construction_speed_pct"),
        (val_div, ":workforce", 100),
        (store_faction_of_party, ":center_faction", ":center_no"),
        (try_begin),
          (is_between, ":center_faction", kingdoms_begin, kingdoms_end),
          (faction_get_slot, ":labor_policy", ":center_faction", slot_faction_sod_prisoner_labor_policy),
          (this_or_next|eq, ":labor_policy", sod_prisoner_labor_policy_penal),
          (this_or_next|eq, ":labor_policy", sod_prisoner_labor_policy_regulated),
          (eq, ":labor_policy", sod_prisoner_labor_policy_unrestricted),
          (party_get_slot, ":slave_laborers", ":center_no", slot_center_sod_slave_laborers),
          (gt, ":slave_laborers", 0),
          (store_div, ":prisoner_labor_bonus", ":slave_laborers", 10),
          (val_min, ":prisoner_labor_bonus", 20),
          (try_begin),
            (eq, ":labor_policy", sod_prisoner_labor_policy_regulated),
            (val_div, ":prisoner_labor_bonus", 2),
          (try_end),
          (val_add, ":workforce", ":prisoner_labor_bonus"),
        (try_end),
      (try_end),

      (try_begin),
        (gt, ":workforce", 0),
        (val_max, ":workforce", 1),
        (try_begin),
          (gt, ":workforce_cap", 0),
          (val_add, ":workforce_cap", 1),
          (val_clamp, ":workforce", 1, ":workforce_cap"),
        (try_end),
      (try_end),
    (try_end),

    (assign, reg0, ":workforce"),
    (assign, reg1, ":population"),
    (assign, reg2, ":health"),
    (assign, reg3, ":prosperity"),
    (assign, reg4, ":food_security"),
  ]),

("sod_get_building_development_required",
  [
    (store_script_param, ":building_no", 1),

    (call_script, "script_get_improvement_details", ":building_no"),
    (assign, ":building_cost", reg0),
    (assign, ":building_tier", reg7),
    (store_div, ":required", ":building_cost", 25),
    (val_max, ":required", 40),
    (try_begin),
      (gt, ":building_tier", 1),
      (store_sub, ":tier_steps", ":building_tier", 1),
      (store_mul, ":tier_bonus", ":required", ":tier_steps"),
      (val_mul, ":tier_bonus", 15),
      (val_div, ":tier_bonus", 100),
      (val_add, ":required", ":tier_bonus"),
    (try_end),
    (val_clamp, ":required", 40, 601),
    (assign, reg0, ":required"),
  ]),

("sod_get_center_construction_cost",
  [
    (store_script_param, ":center_no", 1),
    (store_script_param, ":building_no", 2),
    (store_script_param, ":base_cost", 3),

    (assign, ":cost", ":base_cost"),
    (try_begin),
      (le, ":cost", 0),
      (call_script, "script_get_improvement_details", ":building_no"),
      (assign, ":cost", reg0),
    (try_end),
    (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_construction_cost_pct),
    (assign, ":construction_cost_pct", reg0),
    (store_faction_of_party, ":center_faction", ":center_no"),
    (try_begin),
      (is_between, ":center_faction", kingdoms_begin, kingdoms_end),
      (faction_get_slot, ":labor_policy", ":center_faction", slot_faction_sod_prisoner_labor_policy),
      (this_or_next|eq, ":labor_policy", sod_prisoner_labor_policy_penal),
      (this_or_next|eq, ":labor_policy", sod_prisoner_labor_policy_regulated),
      (eq, ":labor_policy", sod_prisoner_labor_policy_unrestricted),
      (party_get_slot, ":slave_laborers", ":center_no", slot_center_sod_slave_laborers),
      (gt, ":slave_laborers", 0),
      (store_div, ":labor_cost_discount", ":slave_laborers", 15),
      (val_min, ":labor_cost_discount", 15),
      (try_begin),
        (eq, ":labor_policy", sod_prisoner_labor_policy_regulated),
        (val_div, ":labor_cost_discount", 2),
      (try_end),
      (val_sub, ":construction_cost_pct", ":labor_cost_discount"),
      (val_max, ":construction_cost_pct", 65),
    (try_end),
    (val_mul, ":cost", ":construction_cost_pct"),
    (val_div, ":cost", 100),
    (val_max, ":cost", 0),
    (assign, reg0, ":cost"),
    (assign, reg1, ":construction_cost_pct"),
  ]),

("sod_start_center_construction",
  [
    (store_script_param, ":center_no", 1),
    (store_script_param, ":building_no", 2),

    (call_script, "script_sod_get_building_development_required", ":building_no"),
    (assign, ":required", reg0),
    (party_set_slot, ":center_no", slot_center_current_improvement, ":building_no"),
    (party_set_slot, ":center_no", slot_center_construction_progress, 0),
    (party_set_slot, ":center_no", slot_center_construction_required, ":required"),
    (party_set_slot, ":center_no", slot_center_construction_weekly_workforce, 0),
    (party_set_slot, ":center_no", slot_center_construction_last_progress, 0),
    (party_set_slot, ":center_no", slot_center_improvement_end_hour, 0),
    (assign, reg0, ":required"),
  ]),

("sod_ensure_center_construction_state",
  [
    (store_script_param, ":center_no", 1),
    (party_get_slot, ":building_no", ":center_no", slot_center_current_improvement),
    (try_begin),
      (gt, ":building_no", 0),
      (party_slot_ge, ":center_no", ":building_no", 1),
      (party_set_slot, ":center_no", slot_center_current_improvement, 0),
      (party_set_slot, ":center_no", slot_center_construction_progress, 0),
      (party_set_slot, ":center_no", slot_center_construction_required, 0),
      (party_set_slot, ":center_no", slot_center_construction_weekly_workforce, 0),
      (party_set_slot, ":center_no", slot_center_construction_last_progress, 0),
      (party_set_slot, ":center_no", slot_center_improvement_end_hour, 0),
    (else_try),
      (gt, ":building_no", 0),
      (party_get_slot, ":required", ":center_no", slot_center_construction_required),
      (le, ":required", 0),
      (call_script, "script_sod_get_building_development_required", ":building_no"),
      (assign, ":required", reg0),
      (party_set_slot, ":center_no", slot_center_construction_required, ":required"),
      (party_get_slot, ":progress", ":center_no", slot_center_construction_progress),
      (store_add, ":required_plus_one", ":required", 1),
      (val_clamp, ":progress", 0, ":required_plus_one"),
      (party_set_slot, ":center_no", slot_center_construction_progress, ":progress"),
    (try_end),
  ]),

("cf_sod_complete_center_construction",
  [
    (store_script_param, ":center_no", 1),

    (party_get_slot, ":cur_improvement", ":center_no", slot_center_current_improvement),
    (gt, ":cur_improvement", 0),
    (party_set_slot, ":center_no", ":cur_improvement", 1),
    (party_set_slot, ":center_no", slot_center_current_improvement, 0),
    (party_set_slot, ":center_no", slot_center_construction_progress, 0),
    (party_set_slot, ":center_no", slot_center_construction_required, 0),
    (party_set_slot, ":center_no", slot_center_construction_weekly_workforce, 0),
    (party_set_slot, ":center_no", slot_center_construction_last_progress, 0),
    (party_set_slot, ":center_no", slot_center_improvement_end_hour, 0),
    (call_script, "script_get_improvement_details", ":cur_improvement"),

    (try_begin),
      (gt, "$g_sod_hide_messages", -2),
      (party_get_slot, ":owner", ":center_no", slot_town_lord),
      (ge, ":owner", 0),
      (store_troop_faction, ":fac", ":owner"),
      (this_or_next|eq, ":owner", "trp_player"),
      (eq, ":fac", "fac_player_supporters_faction"),
      (str_store_party_name_link, s4, ":center_no"),
      (display_log_message, "@Work on the {s0} in {s4} has been completed.", build_color),
    (try_end),

    (try_begin),
      (this_or_next|eq, ":cur_improvement", slot_center_has_mill),
      (this_or_next|eq, ":cur_improvement", slot_center_has_manufacture),
      (this_or_next|eq, ":cur_improvement", slot_center_has_bank),
      (this_or_next|eq, ":cur_improvement", slot_center_has_rustic_blacksmith),
      (eq, ":cur_improvement", slot_center_has_clayworks),
      (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
      (assign, ":prosperity_bonus", 3),
      (try_begin),
        (lt, ":prosperity", 40),
        (assign, ":prosperity_bonus", 7),
      (else_try),
        (lt, ":prosperity", 70),
        (assign, ":prosperity_bonus", 5),
      (try_end),
      (call_script, "script_change_center_prosperity", ":center_no", ":prosperity_bonus"),
    (try_end),

    (try_begin),
      (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
      (this_or_next|eq, ":cur_improvement", slot_center_has_mill),
      (this_or_next|eq, ":cur_improvement", slot_center_has_manufacture),
      (this_or_next|eq, ":cur_improvement", slot_center_has_bank),
      (this_or_next|eq, ":cur_improvement", slot_center_has_guild),
      (this_or_next|eq, ":cur_improvement", slot_center_has_clayworks),
      (eq, ":cur_improvement", slot_center_has_rustic_blacksmith),
      (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_build_market, 2),
    (try_end),

    (try_begin),
      (this_or_next|eq, ":cur_improvement", slot_center_has_hospital),
      (eq, ":cur_improvement", slot_center_has_ambulatory),
      (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
      (assign, ":health_bonus", 6),
      (try_begin),
        (lt, ":health", 0),
        (assign, ":health_bonus", 15),
      (else_try),
        (lt, ":health", 30),
        (assign, ":health_bonus", 10),
      (try_end),
      (call_script, "script_change_center_health", ":center_no", ":health_bonus"),
    (try_end),

    (try_begin),
      (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
      (this_or_next|eq, ":cur_improvement", slot_center_has_hospital),
      (this_or_next|eq, ":cur_improvement", slot_center_has_ambulatory),
      (this_or_next|eq, ":cur_improvement", slot_center_has_canalization),
      (this_or_next|eq, ":cur_improvement", slot_center_has_water_supply),
      (eq, ":cur_improvement", slot_center_has_chapel),
      (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_build_healing, 2),
    (try_end),

    (try_begin),
      (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
      (this_or_next|eq, ":cur_improvement", slot_center_has_watch_tower),
      (this_or_next|eq, ":cur_improvement", slot_center_has_messenger_post),
      (this_or_next|eq, ":cur_improvement", slot_center_has_stables),
      (this_or_next|eq, ":cur_improvement", slot_center_has_barracks),
      (this_or_next|eq, ":cur_improvement", slot_center_has_range),
      (this_or_next|eq, ":cur_improvement", slot_center_has_prisoner_tower),
      (this_or_next|eq, ":cur_improvement", slot_center_has_blacksmith),
      (eq, ":cur_improvement", slot_center_has_chapter),
      (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_scout_warning, 2),
      (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_build_security, 2),
    (try_end),

    (try_begin),
      (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
      (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_efficient_construction, 1),
    (try_end),

    (try_begin),
      (this_or_next|eq, ":cur_improvement", slot_center_has_canalization),
      (eq, ":cur_improvement", slot_center_has_water_supply),
      (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
      (assign, ":health_bonus", 3),
      (try_begin),
        (lt, ":health", 0),
        (assign, ":health_bonus", 8),
      (else_try),
        (lt, ":health", 30),
        (assign, ":health_bonus", 5),
      (try_end),
      (call_script, "script_change_center_health", ":center_no", ":health_bonus"),
    (try_end),
  ]),

("sod_advance_center_construction",
  [
    (store_script_param, ":center_no", 1),

    (assign, ":completed", 0),
    (party_get_slot, ":building_no", ":center_no", slot_center_current_improvement),
    (try_begin),
      (gt, ":building_no", 0),
      (call_script, "script_sod_ensure_center_construction_state", ":center_no"),
      (party_get_slot, ":progress", ":center_no", slot_center_construction_progress),
      (party_get_slot, ":required", ":center_no", slot_center_construction_required),
      (try_begin),
        (gt, ":required", 0),
        (ge, ":progress", ":required"),
        (call_script, "script_cf_sod_complete_center_construction", ":center_no"),
        (assign, ":completed", 1),
      (else_try),
        (call_script, "script_sod_get_center_construction_workforce", ":center_no"),
        (assign, ":weekly_workforce", reg0),
        (party_set_slot, ":center_no", slot_center_construction_weekly_workforce, ":weekly_workforce"),
        (party_set_slot, ":center_no", slot_center_construction_last_progress, ":progress"),
        (try_begin),
          (gt, ":weekly_workforce", 0),
          (val_add, ":progress", ":weekly_workforce"),
          (val_min, ":progress", ":required"),
          (party_set_slot, ":center_no", slot_center_construction_progress, ":progress"),
          (try_begin),
            (ge, ":progress", ":required"),
            (call_script, "script_cf_sod_complete_center_construction", ":center_no"),
            (assign, ":completed", 1),
          (try_end),
        (try_end),
      (try_end),
    (try_end),
    (assign, reg0, ":completed"),
  ]),
]
