# COST: light to moderate
SCRIPTS = [
("sod_trade_network_validate_center_to_reg",
 [
   (store_script_param_1, ":center_no"),
   (store_script_param_2, ":fallback_center"),
   (assign, reg0, ":center_no"),
   (try_begin),
     (neg|is_between, reg0, centers_begin, centers_end),
     (assign, reg0, ":fallback_center"),
   (try_end),
   (try_begin),
     (neg|is_between, reg0, centers_begin, centers_end),
     (assign, reg0, "p_town_1"),
   (try_end),
 ]),

("sod_trade_network_get_route_pressure_to_regs",
 [
   (faction_get_slot, reg10, "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure),
   (faction_get_slot, reg11, "fac_black_khergits", slot_faction_black_khergit_pressure),
   (faction_get_slot, reg12, "fac_sod_merc_guild5", slot_faction_serpent_route_pressure),
   (faction_get_slot, reg13, "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
   (faction_get_slot, reg14, "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (faction_get_slot, reg15, "fac_sod_merc_guild4", slot_faction_jotnar_hearth_pressure),
   (faction_get_slot, reg16, "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),
 ]),

("sod_trade_network_initialize_caravan",
 [
   (store_script_param_1, ":party_no"),
   (try_begin),
     (gt, ":party_no", 0),
     (neg|party_slot_ge, ":party_no", slot_party_sod_trade_destination, 1),
     (call_script, "script_get_closest_center", ":party_no"),
     (assign, ":origin", reg0),
     (get_party_ai_object, ":destination", ":party_no"),
     (call_script, "script_sod_trade_network_validate_center_to_reg", ":origin", ":destination"),
     (assign, ":origin", reg0),
     (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":origin"),
     (assign, ":destination", reg0),
     (party_set_slot, ":party_no", slot_party_sod_trade_origin, ":origin"),
     (party_set_slot, ":party_no", slot_party_sod_trade_destination, ":destination"),
     (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":destination"),
     (assign, ":cargo_focus", reg0),
     (party_set_slot, ":party_no", slot_party_sod_trade_cargo_focus, ":cargo_focus"),
     (call_script, "script_sod_trade_network_evaluate_route", ":origin", ":destination"),
     (party_set_slot, ":party_no", slot_party_sod_trade_route_risk, reg0),
     (party_set_slot, ":party_no", slot_party_sod_trade_recent_trouble, reg1),
     (party_set_slot, ":party_no", slot_party_sod_trade_last_result, sod_trade_result_none),
   (try_end),
   (try_begin),
     (gt, ":party_no", 0),
     (neg|party_slot_ge, ":party_no", slot_party_sod_trade_player_trust, 1),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_trust, 50),
     (store_current_day, ":cur_day"),
     (store_mul, ":seed", ":party_no", 17),
     (val_add, ":seed", ":cur_day"),
     (party_set_slot, ":party_no", slot_party_sod_trade_captain_seed, ":seed"),
     (store_mod, ":house_style", ":seed", 4),
     (party_set_slot, ":party_no", slot_party_sod_trade_house_style, ":house_style"),
     (party_set_slot, ":party_no", slot_party_sod_trade_route_reputation, sod_trade_result_none),
   (try_end),
 ]),

("sod_trade_network_evaluate_route",
 [
   (store_script_param_1, ":origin"),
   (store_script_param_2, ":destination"),
   (assign, ":risk", 15),
   (assign, ":trouble", sod_trade_route_safe),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":origin", ":destination"),
   (assign, ":origin", reg0),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":origin"),
   (assign, ":destination", reg0),
   (try_begin),
     (is_between, ":origin", centers_begin, centers_end),
     (is_between, ":destination", centers_begin, centers_end),
     (store_distance_to_party_from_party, ":route_distance", ":origin", ":destination"),
     (store_div, ":distance_risk", ":route_distance", 10),
     (val_add, ":risk", ":distance_risk"),
   (try_end),
   (try_begin),
     (gt, ":destination", 0),
     (party_get_slot, ":destination_health", ":destination", slot_center_sod_local_health),
     (try_begin),
       (lt, ":destination_health", 15),
       (store_sub, ":health_risk", 25, ":destination_health"),
       (val_add, ":risk", ":health_risk"),
     (else_try),
       (ge, ":destination_health", 55),
       (val_sub, ":risk", 4),
     (try_end),
     (call_script, "script_sod_get_center_trade_demand_profile", ":destination"),
     (assign, ":scarcity", reg0),
     (assign, ":import_demand", reg1),
     (assign, ":security_willingness", reg4),
     (assign, ":caravan_attractiveness", reg6),
     (store_div, ":scarcity_risk", ":scarcity", 12),
     (val_add, ":risk", ":scarcity_risk"),
     (store_sub, ":security_drag", 80, ":security_willingness"),
     (val_max, ":security_drag", 0),
     (val_div, ":security_drag", 3),
     (val_add, ":risk", ":security_drag"),
     (try_begin),
       (ge, ":scarcity", 120),
       (assign, ":trouble", sod_trade_route_starving),
     (else_try),
       (ge, ":caravan_attractiveness", 130),
       (assign, ":trouble", sod_trade_route_luxury),
     (else_try),
       (ge, ":import_demand", 90),
       (assign, ":trouble", sod_trade_route_grain),
     (try_end),
   (try_end),
   (call_script, "script_sod_trade_network_get_route_pressure_to_regs"),
   (assign, ":boar_pressure", reg10),
   (assign, ":horde_pressure", reg11),
   (assign, ":serpent_pressure", reg12),
   (assign, ":black_army_heat", reg13),
   (assign, ":slaver_heat", reg14),
   (assign, ":jotnar_pressure", reg15),
   (assign, ":elephant_alarm", reg16),
   (store_div, ":boar_risk", ":boar_pressure", 8),
   (store_div, ":horde_risk", ":horde_pressure", 7),
   (store_div, ":serpent_warning", ":serpent_pressure", 12),
   (store_div, ":black_army_cover", ":black_army_heat", 14),
   (store_div, ":slaver_risk", ":slaver_heat", 12),
   (store_div, ":jotnar_cover", ":jotnar_pressure", 18),
   (store_div, ":elephant_cover", ":elephant_alarm", 18),
   (val_add, ":risk", ":boar_risk"),
   (val_add, ":risk", ":horde_risk"),
   (val_add, ":risk", ":serpent_warning"),
   (val_add, ":risk", ":slaver_risk"),
   (val_sub, ":risk", ":black_army_cover"),
   (val_sub, ":risk", ":jotnar_cover"),
   (val_sub, ":risk", ":elephant_cover"),
   (try_begin),
     (ge, ":boar_pressure", 55),
     (assign, ":trouble", sod_trade_route_toll),
   (else_try),
     (ge, ":horde_pressure", 55),
     (assign, ":trouble", sod_trade_route_raider),
   (else_try),
     (ge, ":serpent_pressure", 45),
     (assign, ":trouble", sod_trade_route_watched),
   (try_end),
   (val_clamp, ":risk", 0, 101),
   (assign, reg0, ":risk"),
   (assign, reg1, ":trouble"),
 ]),

("sod_trade_network_get_contract_terms_to_regs",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":contract"),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
   (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
   (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
   (party_get_slot, ":cargo_focus", ":party_no", slot_party_sod_trade_cargo_focus),
   (assign, ":cost", 400),
   (assign, ":expected_return", 0),
   (try_begin),
     (eq, ":contract", sod_trade_contract_guards),
     (assign, ":cost", 350),
     (store_div, ":risk_cost", ":risk", 4),
     (val_add, ":cost", ":risk_cost"),
   (else_try),
     (eq, ":contract", sod_trade_contract_cargo_space),
     (assign, ":cost", 500),
     (try_begin),
       (is_between, ":destination", centers_begin, centers_end),
       (call_script, "script_sod_get_center_trade_demand_profile", ":destination"),
       (assign, ":scarcity", reg0),
       (assign, ":import_demand", reg1),
       (store_div, ":demand_cost", ":scarcity", 8),
       (val_add, ":cost", ":demand_cost"),
       (store_div, ":import_cost", ":import_demand", 8),
       (val_add, ":cost", ":import_cost"),
     (try_end),
     (try_begin),
       (eq, ":cargo_focus", sod_trade_cargo_luxury),
       (val_add, ":cost", 125),
     (else_try),
       (eq, ":cargo_focus", sod_trade_cargo_strategic),
       (val_add, ":cost", 75),
     (try_end),
   (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
     (assign, ":cost", 180),
     (store_div, ":risk_cost", ":risk", 2),
     (val_add, ":cost", ":risk_cost"),
   (else_try),
     (eq, ":contract", sod_trade_contract_relief),
     (assign, ":cost", 500),
   (else_try),
     (eq, ":contract", sod_trade_contract_profit),
     (assign, ":cost", 650),
     (store_div, ":risk_cost", ":risk", 3),
     (val_sub, ":cost", ":risk_cost"),
   (try_end),
   (try_begin),
     (ge, ":trust", 70),
     (val_mul, ":cost", 9),
     (val_div, ":cost", 10),
   (else_try),
     (le, ":trust", 35),
     (val_mul, ":cost", 6),
     (val_div, ":cost", 5),
   (try_end),
   (val_clamp, ":cost", 150, 1500),
   (try_begin),
     (eq, ":contract", sod_trade_contract_cargo_space),
     (store_mul, ":expected_return", ":cost", 6),
     (val_div, ":expected_return", 5),
   (else_try),
     (eq, ":contract", sod_trade_contract_profit),
     (store_mul, ":expected_return", ":cost", 7),
     (val_div, ":expected_return", 5),
   (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
     (store_mul, ":expected_return", ":cost", 2),
   (try_end),
   (assign, reg0, ":cost"),
   (assign, reg1, ":expected_return"),
   (assign, reg2, ":risk"),
   (assign, reg3, ":trust"),
 ]),

("sod_trade_network_describe_center_identity_to_s23",
 [
   (store_script_param_1, ":center_no"),
   (assign, ":cargo_focus", sod_trade_cargo_unknown),
   (str_store_string, s23, "@ordinary market"),
   (try_begin),
     (eq, ":center_no", "p_town_1"),
     (assign, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s23, "@northern grain harbor"),
   (else_try),
     (eq, ":center_no", "p_town_2"),
     (assign, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s23, "@cattle and butter market"),
   (else_try),
     (eq, ":center_no", "p_town_3"),
     (assign, ":cargo_focus", sod_trade_cargo_strategic),
     (str_store_string, s23, "@iron and tool market"),
   (else_try),
     (eq, ":center_no", "p_town_4"),
     (assign, ":cargo_focus", sod_trade_cargo_luxury),
     (str_store_string, s23, "@busy caravan hub"),
   (else_try),
     (eq, ":center_no", "p_town_5"),
     (assign, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s23, "@thin-stored frontier market"),
   (else_try),
     (eq, ":center_no", "p_town_6"),
     (assign, ":cargo_focus", sod_trade_cargo_luxury),
     (str_store_string, s23, "@velvet and spice court"),
   (else_try),
     (eq, ":center_no", "p_town_10"),
     (assign, ":cargo_focus", sod_trade_cargo_raw),
     (str_store_string, s23, "@wool and hide country"),
   (else_try),
     (eq, ":center_no", "p_town_14"),
     (assign, ":cargo_focus", sod_trade_cargo_strategic),
     (str_store_string, s23, "@salt-road fortress market"),
   (else_try),
     (gt, ":center_no", 0),
     (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
     (assign, ":food_balance", reg0),
     (assign, ":raw_balance", reg1),
     (assign, ":strategic_balance", reg2),
     (assign, ":luxury_flow", reg3),
     (assign, ":scarcity", reg4),
     (assign, ":liquidity", reg6),
     (try_begin),
       (ge, ":scarcity", 150),
       (assign, ":cargo_focus", sod_trade_cargo_food),
       (str_store_string, s23, "@starving market"),
     (else_try),
       (ge, ":luxury_flow", 45),
       (assign, ":cargo_focus", sod_trade_cargo_luxury),
       (str_store_string, s23, "@luxury sink"),
     (else_try),
       (ge, ":strategic_balance", 45),
       (assign, ":cargo_focus", sod_trade_cargo_strategic),
       (str_store_string, s23, "@strategic depot"),
     (else_try),
       (ge, ":raw_balance", 55),
       (assign, ":cargo_focus", sod_trade_cargo_raw),
       (str_store_string, s23, "@raw-goods market"),
     (else_try),
       (ge, ":food_balance", 55),
       (assign, ":cargo_focus", sod_trade_cargo_food),
       (str_store_string, s23, "@grain root"),
     (else_try),
       (ge, ":liquidity", 90),
       (assign, ":cargo_focus", sod_trade_cargo_luxury),
       (str_store_string, s23, "@caravan hub"),
     (try_end),
   (try_end),
   (assign, reg0, ":cargo_focus"),
 ]),

("sod_trade_network_describe_route_to_s22",
 [
   (store_script_param_1, ":party_no"),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (party_get_slot, ":origin", ":party_no", slot_party_sod_trade_origin),
   (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
   (call_script, "script_sod_trade_network_evaluate_route", ":origin", ":destination"),
   (assign, ":risk", reg0),
   (assign, ":route_label", reg1),
   (party_set_slot, ":party_no", slot_party_sod_trade_route_risk, ":risk"),
   (party_set_slot, ":party_no", slot_party_sod_trade_recent_trouble, ":route_label"),
   (assign, reg22, ":risk"),
   (str_store_string, s22, "@The road is quiet enough for honest wagons."),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (party_get_slot, ":destination_health", ":destination", slot_center_sod_local_health),
     (lt, ":destination_health", 12),
     (str_store_string, s22, "@The market ahead has sickness in the talk. Some drivers will not unload without extra coin and clean water."),
   (else_try),
     (eq, ":route_label", sod_trade_route_toll),
     (str_store_string, s22, "@Boar tolls have made this road ugly. Expect hazard silver and hard words at the crossings."),
   (else_try),
     (eq, ":route_label", sod_trade_route_raider),
     (str_store_string, s22, "@Rich roads draw Black Khergit eyes. A fast escort is worth more than a pretty writ."),
   (else_try),
     (eq, ":route_label", sod_trade_route_watched),
     (str_store_string, s22, "@Serpent scouts are whispering over this route. That means warnings, but also trouble worth warning about."),
   (else_try),
     (eq, ":route_label", sod_trade_route_luxury),
     (str_store_string, s22, "@This is a luxury artery. The profit is good, and so is the smell of blood around it."),
   (else_try),
     (eq, ":route_label", sod_trade_route_grain),
     (str_store_string, s22, "@This is a grain road. Hungry markets are pulling carts this way."),
   (else_try),
     (eq, ":route_label", sod_trade_route_starving),
     (str_store_string, s22, "@The destination is thin on stores. Relief cargo would matter there."),
   (try_end),
   (call_script, "script_sod_trade_network_get_route_pressure_to_regs"),
   (try_begin),
     (ge, reg14, 45),
     (str_store_string, s22, "@There is captive traffic somewhere near the road. Honest wagons avoid chains when they can."),
   (else_try),
     (ge, reg15, 55),
     (str_store_string, s22, "@Jotnar hearth guards have been seen on nearby roads. Proud folk, but they make slavers and raiders think twice."),
   (else_try),
     (ge, reg16, 45),
     (str_store_string, s22, "@Elephant Guard sanctuary patrols have made this road feel watched in a better way."),
   (try_end),
 ]),

("sod_trade_network_describe_caravan_to_s20",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":mode"),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (party_get_slot, ":origin", ":party_no", slot_party_sod_trade_origin),
   (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":origin", ":destination"),
   (assign, ":origin", reg0),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":origin"),
   (assign, ":destination", reg0),
   (party_get_slot, ":cargo_focus", ":party_no", slot_party_sod_trade_cargo_focus),
   (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
   (party_get_slot, ":contract", ":party_no", slot_party_sod_trade_contract),
   (party_get_slot, ":last_result", ":party_no", slot_party_sod_trade_last_result),
   (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
   (store_skill_level, ":trade_skill", "skl_trade", "trp_player"),
   (party_get_skill_level, ":pathfinding", "p_main_party", skl_pathfinding),
   (party_get_skill_level, ":spotting", "p_main_party", skl_spotting),
   (troop_get_slot, ":renown", "trp_player", slot_troop_renown),
   (assign, ":road_skill", ":pathfinding"),
   (val_max, ":road_skill", ":spotting"),
   (assign, ":local_relation", 0),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (party_get_slot, ":local_relation", ":destination", slot_center_player_relation),
   (try_end),
   (try_begin),
     (is_between, ":origin", centers_begin, centers_end),
     (str_store_party_name, s21, ":origin"),
   (else_try),
     (str_store_string, s21, "@the last market"),
   (try_end),
   (try_begin),
     (is_between, ":destination", centers_begin, centers_end),
     (str_store_party_name, s22, ":destination"),
     (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":destination"),
   (else_try),
     (str_store_string, s22, "@the next market"),
     (str_store_string, s23, "@ordinary market"),
   (try_end),
   (str_store_string, s24, "@mixed goods"),
   (try_begin),
     (eq, ":cargo_focus", sod_trade_cargo_food),
     (str_store_string, s24, "@food, flour, ale, and whatever fills hungry shelves"),
   (else_try),
     (eq, ":cargo_focus", sod_trade_cargo_raw),
     (str_store_string, s24, "@wool, hides, pottery, and raw goods"),
   (else_try),
     (eq, ":cargo_focus", sod_trade_cargo_strategic),
     (str_store_string, s24, "@salt, iron, oil, tools, and military stores"),
   (else_try),
     (eq, ":cargo_focus", sod_trade_cargo_luxury),
     (str_store_string, s24, "@spice, velvet, wine, and soft things that make hard roads profitable"),
   (try_end),
   (assign, reg20, ":risk"),
   (assign, reg21, ":trust"),
   (str_store_string, s25, "@No player bargain is marked on this run."),
   (try_begin),
     (eq, ":contract", sod_trade_contract_guards),
     (str_store_string, s25, "@Your funded guards are riding with this caravan."),
   (else_try),
     (eq, ":contract", sod_trade_contract_cargo_space),
     (str_store_string, s25, "@Your cargo stake is loaded into these wagons."),
   (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
     (str_store_string, s25, "@Your insurance mark is written against this run."),
   (else_try),
     (eq, ":contract", sod_trade_contract_relief),
     (str_store_string, s25, "@Your relief cargo is riding under this caravan's guard."),
   (else_try),
     (eq, ":contract", sod_trade_contract_profit),
     (str_store_string, s25, "@Your profit stake is riding with this caravan."),
   (try_end),
   (str_store_string, s26, "@We have no old account with you."),
   (try_begin),
     (eq, ":last_result", sod_trade_result_protected),
     (str_store_string, s26, "@We remember your guards. That kind of help is worth more than seals."),
   (else_try),
     (eq, ":last_result", sod_trade_result_dangerous),
     (str_store_string, s26, "@Last run left men counting arrows and missing wheels."),
   (else_try),
     (eq, ":last_result", sod_trade_result_taxed),
     (str_store_string, s26, "@Last run paid too much at the crossings."),
   (else_try),
     (eq, ":last_result", sod_trade_result_raided),
     (str_store_string, s26, "@Last run had raider shadows on it."),
   (else_try),
     (eq, ":last_result", sod_trade_result_shortage_supplied),
     (str_store_string, s26, "@Last run carried relief. Folk remember bread when ledgers forget names."),
   (else_try),
     (eq, ":last_result", sod_trade_result_exploited),
     (str_store_string, s26, "@Last run earned hard coin from a hungry market. Some drivers still mutter about it."),
   (else_try),
     (ge, ":trust", 65),
     (str_store_string, s26, "@Your name is not strange to this caravan."),
   (else_try),
     (le, ":trust", 35),
     (str_store_string, s26, "@We keep our ledgers close around unfamiliar blades."),
   (try_end),
   (str_store_string, s27, "@That is a merchant's guess, broad as a cart track."),
   (try_begin),
     (ge, ":trade_skill", 5),
     (str_store_string, s27, "@You have the eye for ledgers, so I will say it plain: shortage and price are both pulling this road."),
   (else_try),
     (ge, ":local_relation", 10),
     (str_store_string, s27, "@They speak better of you near that market, so the gossip comes less wrapped in fog."),
   (else_try),
     (lt, ":renown", 100),
     (str_store_string, s27, "@No offense meant, but a caravan keeps its sharpest price talk for names the road already knows."),
   (try_end),
   (str_store_string, s28, "@Road danger is old-woman talk until arrows prove it."),
   (try_begin),
     (ge, ":road_skill", 5),
     (str_store_string, s28, "@Your scouts would read the same signs: fresh wheels, thin guards, and too few campfires off the road."),
   (else_try),
     (ge, ":trust", 70),
     (str_store_string, s28, "@You know this road well enough now. It has places where men count purses before prayers; that is familiar-road truth, not tavern smoke."),
   (else_try),
     (lt, ":renown", 100),
     (str_store_string, s28, "@You are not yet a name every driver knows, so take this as road mutter rather than sworn witness."),
   (try_end),
   (try_begin),
     (eq, ":mode", 1),
     (str_store_string, s20, "@We are carrying {s24}. Carts like ours make towns breathe. {s26}"),
   (else_try),
     (eq, ":mode", 2),
     (str_store_string, s20, "@We came out of {s21}. If you want the truth of a market, ask the drivers leaving it."),
   (else_try),
     (eq, ":mode", 3),
     (str_store_string, s20, "@We are bound for {s22}. They are known as a {s23}, so the right cargo can still earn. {s27}"),
   (else_try),
     (eq, ":mode", 4),
     (call_script, "script_sod_trade_network_describe_route_to_s22", ":party_no"),
     (str_store_string, s20, "@{s22} {s28} {s26}"),
   (else_try),
     (eq, ":mode", 5),
     (str_store_string, s20, "@Goods selling well? Watch {s22}. A {s23} often pays for {s24}, if the road lets the carts through. {s27}"),
   (else_try),
     (eq, ":mode", 6),
     (call_script, "script_sod_trade_network_describe_route_to_s22", ":party_no"),
     (str_store_string, s20, "@Avoid roads like this when you are slow: {s22} I speak from cart wheels, superstition, and rumor, not a lord's map."),
   (else_try),
     (eq, ":mode", 7),
     (call_script, "script_sod_trade_network_get_contract_terms_to_regs", ":party_no", sod_trade_contract_guards),
     (str_store_string, s20, "@Protection is always welcome. For this road, extra guards would cost about {reg0} denars. Trusted names get better terms; strangers pay for uncertainty. {s25}"),
   (else_try),
     (str_store_string, s20, "@We run from {s21} to {s22}, carrying {s24}. They call the destination a {s23}. {s25} {s26}"),
   (try_end),
 ]),

("sod_trade_network_describe_village_root_to_s20",
 [
   (store_script_param_1, ":village_no"),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":village_no", "$current_town"),
   (assign, ":village_no", reg0),
   (str_store_string, s20, "@This village sends what it can: grain when the fields are kind, cattle when the herds hold, and sons when fear comes calling."),
   (try_begin),
     (is_between, ":village_no", villages_begin, villages_end),
     (party_get_slot, ":market_town", ":village_no", slot_village_market_town),
     (try_begin),
       (is_between, ":market_town", towns_begin, towns_end),
       (str_store_party_name, s21, ":market_town"),
       (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":market_town"),
     (else_try),
       (str_store_string, s21, "@the nearest town"),
       (str_store_string, s23, "@ordinary market"),
     (try_end),
     (call_script, "script_sod_get_center_goods_market_profile", ":village_no"),
     (assign, ":food_balance", reg0),
     (assign, ":raw_balance", reg1),
     (assign, ":strategic_balance", reg2),
     (assign, ":scarcity", reg4),
     (party_get_slot, ":health", ":village_no", slot_center_sod_local_health),
     (party_get_slot, ":looter_pressure", ":village_no", slot_center_sod_looter_raid_pressure),
     (str_store_string, s22, "@The road is passable enough, by our reckoning."),
     (try_begin),
       (ge, ":looter_pressure", 40),
       (str_store_string, s22, "@Raids and road fear are thinning the carts. The town will feel that before a lord admits it."),
     (else_try),
       (ge, ":scarcity", 130),
       (str_store_string, s22, "@We are keeping too much back for our own pots. The market will feel it."),
     (else_try),
       (lt, ":health", 15),
       (str_store_string, s22, "@Sickness slows carts before bandits ever see them."),
     (else_try),
       (ge, ":food_balance", 55),
       (str_store_string, s22, "@Grain is our strongest word to the market."),
     (else_try),
       (ge, ":raw_balance", 55),
       (str_store_string, s22, "@Wool, hides, and rough goods are what we can spare."),
     (else_try),
       (ge, ":strategic_balance", 45),
       (str_store_string, s22, "@Salt, tools, and hard stores matter more than finery here."),
     (try_end),
     (str_store_string, s20, "@Our carts mostly answer to {s21}. Merchants call it a {s23}. {s22} Ask the wagon folk if you want fresh road truth; an elder hears late and worries early."),
   (try_end),
 ]),

("sod_trade_network_describe_town_roots_to_s20",
 [
   (store_script_param_1, ":town_no"),
   (call_script, "script_sod_trade_network_validate_center_to_reg", ":town_no", "$current_town"),
   (assign, ":town_no", reg0),
   (str_store_string, s20, "@This town eats from roads and villages I cannot name with certainty. Ask the caravans for fresher truth."),
   (try_begin),
     (is_between, ":town_no", towns_begin, towns_end),
     (assign, ":root_count", 0),
     (assign, ":first_root", -1),
     (try_for_range, ":village_no", villages_begin, villages_end),
       (party_slot_eq, ":village_no", slot_village_market_town, ":town_no"),
       (val_add, ":root_count", 1),
       (try_begin),
         (lt, ":first_root", 0),
         (assign, ":first_root", ":village_no"),
       (try_end),
     (try_end),
     (str_store_party_name, s21, ":town_no"),
     (call_script, "script_sod_trade_network_describe_center_identity_to_s23", ":town_no"),
     (assign, reg20, ":root_count"),
     (try_begin),
       (is_between, ":first_root", villages_begin, villages_end),
       (str_store_party_name, s22, ":first_root"),
       (str_store_string, s20, "@{s21} is spoken of as a {s23}. {reg20} nearby villages send carts this way when fear and mud allow it. {s22} is one such root; when those villages are raided, food and raw goods vanish from this market first."),
     (else_try),
       (str_store_string, s20, "@{s21} is spoken of as a {s23}, but I have no reliable village-root ledger for it. That is a bad sign for prices and a worse one for bellies."),
     (try_end),
   (try_end),
 ]),

("sod_trade_network_apply_player_contract",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":contract"),
   (store_script_param, ":investment", 3),
   (call_script, "script_sod_trade_network_initialize_caravan", ":party_no"),
   (assign, reg0, 0),
   (try_begin),
     (neg|party_slot_ge, ":party_no", slot_party_sod_trade_contract, 1),
     (assign, reg0, 1),
     (party_set_slot, ":party_no", slot_party_sod_trade_contract, ":contract"),
     (party_set_slot, ":party_no", slot_party_sod_trade_investment, ":investment"),
     (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
     (val_add, ":trust", 1),
     (val_clamp, ":trust", 0, 101),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_trust, ":trust"),
     (store_current_day, "$g_sod_trade_network_last_contract_day"),
     (assign, "$g_sod_trade_network_last_contract_party", ":party_no"),
     (assign, "$g_sod_trade_network_last_contract_type", ":contract"),
     (assign, "$g_sod_trade_network_last_contract_investment", ":investment"),
     (try_begin),
       (eq, ":contract", sod_trade_contract_guards),
       (party_set_slot, ":party_no", slot_party_sod_trade_player_protection, 1),
       (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
       (val_sub, ":risk", 12),
       (val_clamp, ":risk", 0, 101),
       (party_set_slot, ":party_no", slot_party_sod_trade_route_risk, ":risk"),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_caravan_protection, 2),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 1),
     (else_try),
       (eq, ":contract", sod_trade_contract_cargo_space),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_trade_profit, 2),
     (else_try),
       (eq, ":contract", sod_trade_contract_insurance),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_orderly_profit, 1),
     (else_try),
       (eq, ":contract", sod_trade_contract_relief),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_food_security, 2),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_free_captives, 1),
     (else_try),
       (eq, ":contract", sod_trade_contract_profit),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_trade_profit, 2),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_dirty_profit, 1),
     (try_end),
   (try_end),
 ]),

("sod_trade_network_process_caravan_arrival",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":center_no"),
   (try_begin),
     (gt, ":party_no", 0),
     (is_between, ":center_no", centers_begin, centers_end),
     (party_get_slot, ":destination", ":party_no", slot_party_sod_trade_destination),
     (call_script, "script_sod_trade_network_validate_center_to_reg", ":destination", ":center_no"),
     (assign, ":destination", reg0),
     (this_or_next|eq, ":destination", ":center_no"),
     (neg|is_between, ":destination", centers_begin, centers_end),
     (store_current_day, ":cur_day"),
     (neg|party_slot_eq, ":party_no", slot_party_sod_trade_last_result_day, ":cur_day"),
     (party_get_slot, ":contract", ":party_no", slot_party_sod_trade_contract),
     (party_get_slot, ":investment", ":party_no", slot_party_sod_trade_investment),
     (party_get_slot, ":risk", ":party_no", slot_party_sod_trade_route_risk),
     (party_get_slot, ":route_label", ":party_no", slot_party_sod_trade_recent_trouble),
     (assign, ":payout", 0),
     (assign, ":result", sod_trade_result_profitable),
     (try_begin),
       (eq, ":route_label", sod_trade_route_toll),
       (assign, ":result", sod_trade_result_taxed),
     (else_try),
       (eq, ":route_label", sod_trade_route_raider),
       (assign, ":result", sod_trade_result_raided),
     (else_try),
       (ge, ":risk", 70),
       (assign, ":result", sod_trade_result_dangerous),
     (else_try),
       (party_slot_ge, ":party_no", slot_party_sod_trade_player_protection, 1),
       (assign, ":result", sod_trade_result_protected),
     (try_end),
     (try_begin),
       (eq, ":contract", sod_trade_contract_cargo_space),
       (store_mul, ":payout", ":investment", 6),
       (val_div, ":payout", 5),
       (call_script, "script_troop_add_gold", "trp_player", ":payout"),
       (assign, ":result", sod_trade_result_profitable),
     (else_try),
     (eq, ":contract", sod_trade_contract_insurance),
       (this_or_next|ge, ":risk", 70),
       (this_or_next|eq, ":result", sod_trade_result_raided),
       (eq, ":result", sod_trade_result_dangerous),
       (store_mul, ":payout", ":investment", 2),
       (call_script, "script_troop_add_gold", "trp_player", ":payout"),
       (assign, ":result", sod_trade_result_dangerous),
     (else_try),
       (eq, ":contract", sod_trade_contract_relief),
       (call_script, "script_change_center_prosperity", ":center_no", 1),
       (call_script, "script_change_player_relation_with_center", ":center_no", 1),
       (assign, ":result", sod_trade_result_shortage_supplied),
     (else_try),
       (eq, ":contract", sod_trade_contract_profit),
       (store_mul, ":payout", ":investment", 7),
       (val_div, ":payout", 5),
       (call_script, "script_troop_add_gold", "trp_player", ":payout"),
       (call_script, "script_change_center_prosperity", ":center_no", -1),
       (assign, ":result", sod_trade_result_exploited),
     (try_end),
     (party_get_slot, ":trust", ":party_no", slot_party_sod_trade_player_trust),
     (try_begin),
       (eq, ":result", sod_trade_result_protected),
       (val_add, ":trust", 6),
     (else_try),
       (eq, ":result", sod_trade_result_shortage_supplied),
       (val_add, ":trust", 4),
     (else_try),
       (eq, ":result", sod_trade_result_exploited),
       (val_sub, ":trust", 6),
     (else_try),
       (eq, ":result", sod_trade_result_raided),
       (val_sub, ":trust", 2),
     (try_end),
     (val_clamp, ":trust", 0, 101),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_trust, ":trust"),
     (try_begin),
       (ge, ":contract", 1),
       (assign, reg23, ":payout"),
       (str_store_party_name, s21, ":party_no"),
      (str_store_party_name, s22, ":center_no"),
      (try_begin),
        (eq, ":contract", sod_trade_contract_guards),
        (display_message, "@Trade network: {s21} reached {s22}; your funded guards completed the run.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_cargo_space),
        (display_message, "@Trade network: {s21} reached {s22}; your cargo stake paid {reg23} denars.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_insurance),
        (gt, ":payout", 0),
        (display_message, "@Trade network: {s21} reached {s22} battered; your insurance claim paid {reg23} denars.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_insurance),
        (display_message, "@Trade network: {s21} reached {s22} safely; no insurance claim was needed.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_relief),
        (display_message, "@Trade network: {s21} reached {s22}; your relief cargo improved local stores.", quest_success_color),
      (else_try),
        (eq, ":contract", sod_trade_contract_profit),
        (display_message, "@Trade network: {s21} reached {s22}; your profit stake paid {reg23} denars.", quest_success_color),
      (try_end),
     (try_end),
     (party_set_slot, ":party_no", slot_party_sod_trade_last_result, ":result"),
     (party_set_slot, ":party_no", slot_party_sod_trade_route_reputation, ":result"),
     (party_set_slot, ":party_no", slot_party_sod_trade_last_result_day, ":cur_day"),
     (party_set_slot, ":party_no", slot_party_sod_trade_contract, sod_trade_contract_none),
     (party_set_slot, ":party_no", slot_party_sod_trade_player_protection, 0),
     (party_set_slot, ":party_no", slot_party_sod_trade_investment, 0),
     (assign, "$g_sod_trade_network_last_result_day", ":cur_day"),
     (assign, "$g_sod_trade_network_last_result_party", ":party_no"),
     (assign, "$g_sod_trade_network_last_result_center", ":center_no"),
     (assign, "$g_sod_trade_network_last_result_type", ":result"),
   (try_end),
 ]),

("sod_trade_network_apply_strategy_action",
 [
   (store_script_param_1, ":action"),
   (assign, reg0, 0),
   (try_begin),
     (eq, ":action", 1), # Fund road patrols.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 1200),
     (call_script, "script_sod_player_charge_gold", 1200),
     (faction_get_slot, ":black_army_heat", "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
     (val_add, ":black_army_heat", 12),
     (val_clamp, ":black_army_heat", 0, 101),
     (faction_set_slot, "fac_sod_merc_guild1", slot_faction_black_army_contract_heat, ":black_army_heat"),
     (faction_get_slot, ":horde_pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (val_sub, ":horde_pressure", 4),
     (val_clamp, ":horde_pressure", 0, 101),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":horde_pressure"),
     (assign, "$g_sod_trade_network_last_strategy_action", 1),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: paid patrol silver is moving through the roads.", quest_success_color),
   (else_try),
     (eq, ":action", 2), # Suppress Boar toll pressure.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 900),
     (call_script, "script_sod_player_charge_gold", 900),
     (faction_get_slot, ":boar_pressure", "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure),
     (val_sub, ":boar_pressure", 12),
     (val_clamp, ":boar_pressure", 0, 101),
     (faction_set_slot, "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure, ":boar_pressure"),
     (assign, "$g_sod_trade_network_last_strategy_action", 2),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: toll marks are being challenged along the crossings.", quest_success_color),
   (else_try),
     (eq, ":action", 3), # Subsidize needy destination.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 1000),
     (is_between, "$g_sod_trade_network_last_result_center", centers_begin, centers_end),
     (call_script, "script_sod_player_charge_gold", 1000),
     (call_script, "script_change_center_prosperity", "$g_sod_trade_network_last_result_center", 1),
     (call_script, "script_center_get_food_store_limit", "$g_sod_trade_network_last_result_center"),
     (assign, ":food_limit", reg0),
     (store_div, ":relief_food", ":food_limit", 20),
     (val_max, ":relief_food", 10),
     (call_script, "script_sod_center_apply_food_delta", "$g_sod_trade_network_last_result_center", ":relief_food"),
     (call_script, "script_change_player_relation_with_center", "$g_sod_trade_network_last_result_center", 1),
     (assign, "$g_sod_trade_network_last_strategy_action", 3),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: subsidized relief has been sent toward the last known needy market.", quest_success_color),
   (else_try),
     (eq, ":action", 4), # Invest in repeat route.
     (store_troop_gold, ":gold", "trp_player"),
     (ge, ":gold", 800),
     (gt, "$g_sod_trade_network_last_result_party", 0),
     (call_script, "script_sod_player_charge_gold", 800),
     (party_get_slot, ":trust", "$g_sod_trade_network_last_result_party", slot_party_sod_trade_player_trust),
     (val_add, ":trust", 8),
     (val_clamp, ":trust", 0, 101),
     (party_set_slot, "$g_sod_trade_network_last_result_party", slot_party_sod_trade_player_trust, ":trust"),
     (party_get_slot, ":risk", "$g_sod_trade_network_last_result_party", slot_party_sod_trade_route_risk),
     (val_sub, ":risk", 6),
     (val_clamp, ":risk", 0, 101),
     (party_set_slot, "$g_sod_trade_network_last_result_party", slot_party_sod_trade_route_risk, ":risk"),
     (assign, "$g_sod_trade_network_last_strategy_action", 4),
     (assign, reg0, 1),
     (display_message, "@Caravan road notes: repeat-route coin has bought better trust and steadier arrangements.", quest_success_color),
   (try_end),
 ]),

("sod_trade_network_describe_report_to_s20",
 [
   (assign, reg20, "$g_sod_trade_network_last_contract_day"),
   (assign, reg21, "$g_sod_trade_network_last_contract_investment"),
   (assign, reg22, "$g_sod_trade_network_last_result_day"),
   (str_store_string, s21, "@none recorded"),
   (try_begin),
     (gt, "$g_sod_trade_network_last_contract_party", 0),
     (str_store_party_name, s21, "$g_sod_trade_network_last_contract_party"),
   (try_end),
   (str_store_string, s25, "@unknown caravan"),
   (try_begin),
     (gt, "$g_sod_trade_network_last_result_party", 0),
     (str_store_party_name, s25, "$g_sod_trade_network_last_result_party"),
   (try_end),
   (str_store_string, s22, "@no arrival recorded"),
   (try_begin),
     (is_between, "$g_sod_trade_network_last_result_center", centers_begin, centers_end),
     (str_store_party_name, s22, "$g_sod_trade_network_last_result_center"),
   (try_end),
   (str_store_string, s23, "@no contract"),
   (try_begin),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_guards),
     (str_store_string, s23, "@funded guards"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_cargo_space),
     (str_store_string, s23, "@bought cargo space"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_insurance),
     (str_store_string, s23, "@insured a caravan"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_relief),
     (str_store_string, s23, "@sponsored relief cargo"),
   (else_try),
     (eq, "$g_sod_trade_network_last_contract_type", sod_trade_contract_profit),
     (str_store_string, s23, "@sponsored profit cargo"),
   (try_end),
   (str_store_string, s24, "@no result"),
   (try_begin),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_profitable),
     (str_store_string, s24, "@profitable run"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_protected),
     (str_store_string, s24, "@protected run"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_dangerous),
     (str_store_string, s24, "@dangerous road"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_shortage_supplied),
     (str_store_string, s24, "@shortage supplied"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_taxed),
     (str_store_string, s24, "@hard toll road"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_raided),
     (str_store_string, s24, "@raider-shadowed road"),
   (else_try),
     (eq, "$g_sod_trade_network_last_result_type", sod_trade_result_exploited),
     (str_store_string, s24, "@shortage exploited"),
   (try_end),
   (str_store_string, s26, "@No broad road order is active in memory."),
   (try_begin),
     (eq, "$g_sod_trade_network_last_strategy_action", 1),
     (str_store_string, s26, "@Recent order: patrol silver sent onto the roads."),
   (else_try),
     (eq, "$g_sod_trade_network_last_strategy_action", 2),
     (str_store_string, s26, "@Recent order: toll pressure challenged at the crossings."),
   (else_try),
     (eq, "$g_sod_trade_network_last_strategy_action", 3),
     (str_store_string, s26, "@Recent order: subsidized relief sent toward a needy market."),
   (else_try),
     (eq, "$g_sod_trade_network_last_strategy_action", 4),
     (str_store_string, s26, "@Recent order: coin invested in a familiar caravan route."),
   (try_end),
   (str_store_string, s20, "@Trade Network Report^^Best information comes from caravan masters on the road. Reports preserve only what your people have recently heard or sponsored.^^Last contract: {s23} with {s21} on day {reg20}, investment {reg21}.^Last arrival memory: {s24} by {s25} at {s22} on day {reg22}.^{s26}^^If there is no reliable word, ask a caravan what it carries, where it came from, where it is bound, how bad the roads are, and what goods are selling well. Boar tolls, Black Khergit raids, Serpent warnings, Black Army contracts, and local scarcity all shape their answers."),
 ]),
]
