# COST: light, shared mini-faction world-presence helpers.
SCRIPTS = [
("sod_world_presence_configure_activity_party",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":faction_no"),
   (store_script_param, ":base_party", 3),
   (store_script_param, ":activity_slot", 4),
   (store_script_param, ":origin_slot", 5),
   (store_script_param, ":destination_slot", 6),
   (store_script_param, ":destination", 7),
   (store_script_param, ":contract_days", 8),
   (assign, reg0, 0),
   # World-presence parties reuse AI-mercenary map behavior, so they always
   # need a renewable term before the generic mercenary expiry service runs.
   (try_begin),
     (le, ":contract_days", 0),
     (assign, ":contract_days", sod_world_presence_activity_contract_days),
   (try_end),
   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (party_set_faction, ":party_no", ":faction_no"),
     (party_set_slot, ":party_no", slot_party_orginal_faction, ":faction_no"),
     (party_set_slot, ":party_no", slot_party_starting_base, ":base_party"),
     (party_set_slot, ":party_no", slot_party_type, spt_ai_mercenaries),
     (party_set_slot, ":party_no", slot_party_boss, -1),
     (party_set_slot, ":party_no", ":activity_slot", 1),
     (party_set_slot, ":party_no", ":origin_slot", ":base_party"),
     (party_set_slot, ":party_no", ":destination_slot", ":destination"),
     (try_begin),
       (eq, ":activity_slot", slot_party_sod_slaver_web_activity),
       (call_script, "script_sod_slavers_mark_market_dirty"),
     (try_end),
     (store_current_day, ":cur_day"),
     (store_add, ":contract_day", ":cur_day", ":contract_days"),
     (party_set_slot, ":party_no", slot_party_merc_contract, ":contract_day"),
     (assign, reg0, 1),
   (try_end),
 ]),

("sod_world_presence_store_slaver_pressure_to_reg",
 [
   (store_script_param_1, ":base_party"),
   (store_script_param_2, ":heat_divisor"),
   (store_script_param, ":per_party_pressure", 3),
   (store_script_param, ":near_pressure", 4),
   (store_script_param, ":near_distance", 5),
   (faction_get_slot, ":pressure", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (try_begin),
     (gt, ":heat_divisor", 0),
     (val_div, ":pressure", ":heat_divisor"),
   (try_end),
   (try_for_parties, ":slaver_party"),
     (party_is_active, ":slaver_party"),
     (party_slot_eq, ":slaver_party", slot_party_sod_slaver_web_activity, 1),
     (val_add, ":pressure", ":per_party_pressure"),
     (store_distance_to_party_from_party, ":slaver_dist", ":slaver_party", ":base_party"),
     (try_begin),
       (lt, ":slaver_dist", ":near_distance"),
       (val_add, ":pressure", ":near_pressure"),
     (try_end),
   (try_end),
   (val_clamp, ":pressure", 0, 101),
   (assign, reg0, ":pressure"),
 ]),

("sod_world_presence_try_interdict_slaver_to_reg",
 [
   (store_script_param_1, ":party_no"),
   (store_script_param_2, ":max_distance"),
   (assign, reg0, 0),
   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (try_for_parties, ":slaver_party"),
       (eq, reg0, 0),
       (party_is_active, ":slaver_party"),
       (party_slot_eq, ":slaver_party", slot_party_sod_slaver_web_activity, 1),
       (store_distance_to_party_from_party, ":slaver_dist", ":party_no", ":slaver_party"),
       (lt, ":slaver_dist", ":max_distance"),
       (party_set_ai_behavior, ":party_no", ai_bhvr_attack_party),
       (party_set_ai_object, ":party_no", ":slaver_party"),
       (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_hostile, 1),
       (assign, reg0, 1),
     (try_end),
   (try_end),
 ]),

("sod_world_presence_mark_scan_due_to_reg",
 [
   (store_script_param_1, ":faction_no"),
   (store_script_param_2, ":last_scan_slot"),
   (store_script_param, ":interval_hours", 3),
   (store_current_hours, ":cur_hours"),
   (faction_get_slot, ":last_scan_hour", ":faction_no", ":last_scan_slot"),
   (assign, reg0, 0),
   (try_begin),
     (le, ":interval_hours", 0),
     (assign, ":interval_hours", 1),
   (try_end),
   (try_begin),
     (le, ":last_scan_hour", 0),
     (try_begin),
       (gt, ":cur_hours", 0),
       (faction_set_slot, ":faction_no", ":last_scan_slot", ":cur_hours"),
     (else_try),
       (faction_set_slot, ":faction_no", ":last_scan_slot", 1),
     (try_end),
     (assign, reg0, 1),
   (else_try),
     (store_sub, ":hours_since_scan", ":cur_hours", ":last_scan_hour"),
     (ge, ":hours_since_scan", ":interval_hours"),
     (faction_set_slot, ":faction_no", ":last_scan_slot", ":cur_hours"),
     (assign, reg0, 1),
   (try_end),
 ]),
]
