# COST: low
SCRIPTS = [
("sod_castle_patrol_destroyed",
 [
   (store_script_param, ":patrol_party", 1),
   (party_get_slot, ":origin", ":patrol_party", slot_party_sod_patrol_origin_castle),
   (try_begin),
     (is_between, ":origin", castles_begin, castles_end),
     (party_get_slot, ":status", ":patrol_party", slot_party_sod_patrol_status),
     (neq, ":status", sod_castle_patrol_status_destroyed),
     (neq, ":status", sod_castle_patrol_status_disbanded),
     (party_set_slot, ":patrol_party", slot_party_sod_patrol_status, sod_castle_patrol_status_destroyed),
     (store_current_day, ":cur_day"),
     (party_set_slot, ":origin", slot_center_sod_patrol_recent_destroyed_day, ":cur_day"),
     (store_faction_of_party, ":origin_faction", ":origin"),
     (try_begin),
       (is_between, ":origin_faction", kingdoms_begin, kingdoms_end),
       (faction_get_slot, ":intel_pressure", ":origin_faction", slot_faction_intelligence_pressure),
       (val_add, ":intel_pressure", 1),
       (faction_set_slot, ":origin_faction", slot_faction_intelligence_pressure, ":intel_pressure"),
     (try_end),
     (party_get_slot, ":threat", ":origin", slot_center_sod_security_cache_effective_threat),
     (val_add, ":threat", 3),
     (party_set_slot, ":origin", slot_center_sod_security_cache_effective_threat, ":threat"),
     (party_get_slot, ":security", ":origin", slot_center_sod_security_cache_security),
     (val_sub, ":security", 3),
     (val_max, ":security", 0),
     (party_set_slot, ":origin", slot_center_sod_security_cache_security, ":security"),
     (party_get_slot, ":role", ":patrol_party", slot_party_sod_patrol_role),
     (call_script, "script_sod_apply_castle_patrol_population_effect", ":origin", ":role", -1),
     (call_script, "script_sod_dispatch_castle_patrol_companion_action", ":role", -1),
     (party_get_num_prisoners, ":prisoners", ":patrol_party"),
     (try_begin),
       (gt, ":prisoners", 0),
       (party_get_slot, ":escape_pressure", ":origin", slot_center_sod_prisoner_escape_pressure),
       (val_add, ":escape_pressure", ":prisoners"),
       (party_set_slot, ":origin", slot_center_sod_prisoner_escape_pressure, ":escape_pressure"),
       (party_get_slot, ":threat", ":origin", slot_center_sod_security_cache_effective_threat),
       (store_div, ":prisoner_threat", ":prisoners", 3),
       (val_add, ":threat", ":prisoner_threat"),
       (party_set_slot, ":origin", slot_center_sod_security_cache_effective_threat, ":threat"),
     (try_end),
     (try_begin),
       (eq, "$g_sod_debug", 1),
       (str_store_party_name, s1, ":origin"),
       (assign, reg10, ":role"),
       (display_message, "@Castle patrol destroyed near {s1}; role {reg10}.", debug_color),
     (try_end),
   (try_end),
 ]),
]
