# COST: light
SCRIPTS = [
("sod_company_dialogue_select_spokesperson_to_regs",
 [
   (call_script, "script_sod_company_accounts_update_morale_pressure"),
   (call_script, "script_sod_company_accounts_update_troop_category_morale"),
   (assign, ":incident_type", sod_company_spokesperson_none),
   (assign, ":incident_class", sod_company_troop_class_enlisted),
   (assign, ":severity", 0),

   (call_script, "script_sod_company_accounts_get_due_to_regs"),
   (assign, ":total_due", reg22),
   (try_begin),
     (gt, ":total_due", 0),
     (store_div, ":arrears_score", ":total_due", 250),
     (val_add, ":arrears_score", "$g_sod_company_camp_strain"),
     (try_begin),
       (gt, "$g_sod_company_mercenary_count", 0),
       (lt, "$g_sod_company_mercenary_morale", 55),
       (val_add, ":arrears_score", 20),
     (try_end),
     (gt, ":arrears_score", ":severity"),
     (assign, ":incident_type", sod_company_spokesperson_pay_arrears),
     (assign, ":incident_class", sod_company_troop_class_mercenary),
     (try_begin),
       (le, "$g_sod_company_mercenary_count", 0),
       (assign, ":incident_class", sod_company_troop_class_enlisted),
     (try_end),
     (assign, ":severity", ":arrears_score"),
   (try_end),

   (try_begin),
     (le, "$g_sod_company_ration_confidence", 45),
     (store_sub, ":ration_score", 55, "$g_sod_company_ration_confidence"),
     (val_add, ":ration_score", "$g_sod_company_camp_strain"),
     (gt, ":ration_score", ":severity"),
     (assign, ":incident_type", sod_company_spokesperson_thin_rations),
     (assign, ":incident_class", sod_company_troop_class_enlisted),
     (assign, ":severity", ":ration_score"),
   (try_end),

   (try_begin),
     (gt, "$g_sod_company_casualty_compensation_pressure", ":severity"),
     (assign, ":incident_type", sod_company_spokesperson_wounded_care),
     (assign, ":incident_class", sod_company_troop_class_faith),
     (assign, ":severity", "$g_sod_company_casualty_compensation_pressure"),
   (try_end),

   (try_begin),
     (gt, "$g_sod_company_siege_hazard_pressure", ":severity"),
     (assign, ":incident_type", sod_company_spokesperson_hazard_pay),
     (assign, ":incident_class", sod_company_troop_class_mercenary),
     (assign, ":severity", "$g_sod_company_siege_hazard_pressure"),
   (try_end),

   (try_begin),
     (gt, "$g_sod_company_noble_restlessness", ":severity"),
     (assign, ":incident_type", sod_company_spokesperson_noble_honor),
     (assign, ":incident_class", sod_company_troop_class_noble),
     (assign, ":severity", "$g_sod_company_noble_restlessness"),
   (try_end),

   (try_begin),
     (gt, "$g_sod_company_faith_count", 0),
     (lt, "$g_sod_company_faith_morale", 45),
     (store_sub, ":faith_score", 55, "$g_sod_company_faith_morale"),
     (val_add, ":faith_score", "$g_sod_company_casualty_compensation_pressure"),
     (gt, ":faith_score", ":severity"),
     (assign, ":incident_type", sod_company_spokesperson_faith_rites),
     (assign, ":incident_class", sod_company_troop_class_faith),
     (assign, ":severity", ":faith_score"),
   (try_end),

   (try_begin),
     (gt, "$g_sod_company_battle_promise_active", 0),
     (ge, 45, ":severity"),
     (assign, ":incident_type", sod_company_spokesperson_battle_promise_due),
     (assign, ":incident_class", sod_company_troop_class_mercenary),
     (assign, ":severity", 45),
   (try_end),

   (val_clamp, ":severity", 0, 101),
   (assign, reg60, ":incident_type"),
   (assign, reg61, ":incident_class"),
   (assign, reg62, ":severity"),
 ]),

("sod_company_dialogue_find_mediator_to_regs",
 [
   (store_script_param_1, ":incident_type"),
   (assign, ":mediator", -1),
   (try_begin),
     (this_or_next|eq, ":incident_type", sod_company_spokesperson_pay_arrears),
     (eq, ":incident_type", sod_company_spokesperson_hazard_pay),
     (try_begin),
       (main_party_has_troop, "trp_npc2"),
       (assign, ":mediator", "trp_npc2"),
     (else_try),
       (eq, ":incident_type", sod_company_spokesperson_hazard_pay),
       (main_party_has_troop, "trp_npc15"),
       (assign, ":mediator", "trp_npc15"),
     (else_try),
       (main_party_has_troop, "trp_npc10"),
       (assign, ":mediator", "trp_npc10"),
     (else_try),
       (main_party_has_troop, "trp_npc11"),
       (assign, ":mediator", "trp_npc11"),
     (else_try),
       (main_party_has_troop, "trp_npc1"),
       (assign, ":mediator", "trp_npc1"),
     (try_end),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_thin_rations),
     (try_begin),
       (main_party_has_troop, "trp_npc11"),
       (assign, ":mediator", "trp_npc11"),
     (else_try),
       (main_party_has_troop, "trp_npc3"),
       (assign, ":mediator", "trp_npc3"),
     (else_try),
       (main_party_has_troop, "trp_npc1"),
       (assign, ":mediator", "trp_npc1"),
     (else_try),
       (main_party_has_troop, "trp_npc7"),
       (assign, ":mediator", "trp_npc7"),
     (try_end),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_wounded_care),
     (try_begin),
       (main_party_has_troop, "trp_npc12"),
       (assign, ":mediator", "trp_npc12"),
     (else_try),
       (main_party_has_troop, "trp_npc3"),
       (assign, ":mediator", "trp_npc3"),
     (else_try),
       (main_party_has_troop, "trp_npc10"),
       (assign, ":mediator", "trp_npc10"),
     (else_try),
       (main_party_has_troop, "trp_npc6"),
       (assign, ":mediator", "trp_npc6"),
     (try_end),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_noble_honor),
     (try_begin),
       (main_party_has_troop, "trp_npc6"),
       (assign, ":mediator", "trp_npc6"),
     (else_try),
       (main_party_has_troop, "trp_npc8"),
       (assign, ":mediator", "trp_npc8"),
     (else_try),
       (main_party_has_troop, "trp_npc14"),
       (assign, ":mediator", "trp_npc14"),
     (try_end),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_faith_rites),
     (try_begin),
       (main_party_has_troop, "trp_npc12"),
       (assign, ":mediator", "trp_npc12"),
     (else_try),
       (main_party_has_troop, "trp_npc3"),
       (assign, ":mediator", "trp_npc3"),
     (else_try),
       (main_party_has_troop, "trp_npc6"),
       (assign, ":mediator", "trp_npc6"),
     (try_end),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_battle_promise_due),
     (try_begin),
       (main_party_has_troop, "trp_npc2"),
       (assign, ":mediator", "trp_npc2"),
     (else_try),
       (main_party_has_troop, "trp_npc1"),
       (assign, ":mediator", "trp_npc1"),
     (else_try),
       (main_party_has_troop, "trp_npc11"),
       (assign, ":mediator", "trp_npc11"),
     (try_end),
   (else_try),
     (this_or_next|eq, ":incident_type", sod_company_spokesperson_defeat_shock),
     (eq, ":incident_type", sod_company_spokesperson_discipline_threat),
     (try_begin),
       (main_party_has_troop, "trp_npc14"),
       (assign, ":mediator", "trp_npc14"),
     (else_try),
       (main_party_has_troop, "trp_npc10"),
       (assign, ":mediator", "trp_npc10"),
     (else_try),
       (main_party_has_troop, "trp_npc6"),
       (assign, ":mediator", "trp_npc6"),
     (else_try),
       (main_party_has_troop, "trp_npc5"),
       (assign, ":mediator", "trp_npc5"),
     (try_end),
   (else_try),
     (main_party_has_troop, "trp_npc10"),
     (assign, ":mediator", "trp_npc10"),
   (try_end),
   (try_begin),
     (gt, ":mediator", 0),
     (neg|troop_slot_ge, ":mediator", slot_troop_companion_approval, 45),
     (assign, ":mediator", -1),
   (try_end),
   (try_begin),
     (le, ":mediator", 0),
     (assign, ":best_approval", 44),
     (try_for_range, ":companion", companions_begin, companions_end),
       (main_party_has_troop, ":companion"),
       (troop_get_slot, ":role", ":companion", slot_troop_companion_role),
       (this_or_next|eq, ":role", sod_companion_role_envoy),
       (this_or_next|eq, ":role", sod_companion_role_captain),
       (this_or_next|eq, ":role", sod_companion_role_quartermaster),
       (this_or_next|eq, ":role", sod_companion_role_surgeon),
       (eq, ":role", sod_companion_role_scout),
       (troop_get_slot, ":approval_candidate", ":companion", slot_troop_companion_approval),
       (gt, ":approval_candidate", ":best_approval"),
       (assign, ":best_approval", ":approval_candidate"),
       (assign, ":mediator", ":companion"),
     (try_end),
   (try_end),
   (assign, reg63, ":mediator"),
 ]),

("sod_company_dialogue_get_mediator_strength_to_reg",
 [
   (store_script_param_1, ":mediator"),
   (store_script_param_2, ":incident_type"),
   (assign, ":strength", 0),
   (try_begin),
     (gt, ":mediator", 0),
     (main_party_has_troop, ":mediator"),
     (troop_get_slot, ":approval", ":mediator", slot_troop_companion_approval),
     (store_div, ":strength", ":approval", 2),
     (troop_get_slot, ":role", ":mediator", slot_troop_companion_role),
     (try_begin),
       (ge, ":approval", 45),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_pay_arrears),
       (eq, ":incident_type", sod_company_spokesperson_hazard_pay),
       (this_or_next|eq, ":role", sod_companion_role_quartermaster),
       (eq, ":role", sod_companion_role_envoy),
       (val_add, ":strength", 15),
     (else_try),
       (ge, ":approval", 45),
       (eq, ":incident_type", sod_company_spokesperson_thin_rations),
       (this_or_next|eq, ":role", sod_companion_role_quartermaster),
       (eq, ":role", sod_companion_role_scout),
       (val_add, ":strength", 12),
     (else_try),
       (ge, ":approval", 45),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_wounded_care),
       (eq, ":incident_type", sod_company_spokesperson_faith_rites),
       (this_or_next|eq, ":role", sod_companion_role_surgeon),
       (eq, ":role", sod_companion_role_envoy),
       (val_add, ":strength", 15),
     (else_try),
       (ge, ":approval", 45),
       (eq, ":incident_type", sod_company_spokesperson_noble_honor),
       (this_or_next|eq, ":role", sod_companion_role_captain),
       (eq, ":role", sod_companion_role_envoy),
       (val_add, ":strength", 15),
     (else_try),
       (ge, ":approval", 45),
       (eq, ":incident_type", sod_company_spokesperson_discipline_threat),
       (eq, ":role", sod_companion_role_captain),
       (val_add, ":strength", 15),
     (try_end),
     (try_begin),
       (lt, ":approval", 30),
       (val_div, ":strength", 2),
     (try_end),
     (assign, ":skill_bonus", 0),
     (try_begin),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_pay_arrears),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_hazard_pay),
       (eq, ":incident_type", sod_company_spokesperson_victory_spoils),
       (store_skill_level, ":skill_bonus", "skl_trade", ":mediator"),
     (else_try),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_wounded_care),
       (eq, ":incident_type", sod_company_spokesperson_faith_rites),
       (store_skill_level, ":skill_bonus", "skl_surgery", ":mediator"),
     (else_try),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_thin_rations),
       (eq, ":incident_type", sod_company_spokesperson_defeat_shock),
       (store_skill_level, ":skill_bonus", "skl_pathfinding", ":mediator"),
     (else_try),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_noble_honor),
       (this_or_next|eq, ":incident_type", sod_company_spokesperson_discipline_threat),
       (eq, ":incident_type", sod_company_spokesperson_battle_promise_due),
       (store_skill_level, ":skill_bonus", "skl_leadership", ":mediator"),
     (try_end),
     (val_min, ":skill_bonus", 10),
     (val_add, ":strength", ":skill_bonus"),
   (try_end),
   (val_clamp, ":strength", 0, 101),
   (assign, reg52, ":strength"),
 ]),

("sod_company_dialogue_store_incident_focus",
 [
   (store_script_param_1, ":incident_type"),
   (store_script_param_2, ":incident_class"),
   (store_script_param, ":severity", 3),
   (assign, "$g_sod_company_spokesperson_focus_party", "p_main_party"),
   (assign, "$g_sod_company_spokesperson_focus_center", -1),
   (assign, "$g_sod_company_spokesperson_focus_cause", ":incident_type"),
   (assign, "$g_sod_company_spokesperson_focus_class", ":incident_class"),
   (assign, "$g_sod_company_spokesperson_focus_severity", ":severity"),
   (try_begin),
     (is_between, "$current_town", centers_begin, centers_end),
     (assign, "$g_sod_company_spokesperson_focus_center", "$current_town"),
   (try_end),
 ]),

("sod_company_dialogue_try_spokesperson_incident",
 [
   (call_script, "script_sod_company_dialogue_select_spokesperson_to_regs"),
   (assign, ":incident_type", reg60),
   (assign, ":incident_class", reg61),
   (assign, ":severity", reg62),
   (assign, ":mediator", -1),
   (try_begin),
     (ge, ":severity", 35),
     (call_script, "script_sod_company_dialogue_find_mediator_to_regs", ":incident_type"),
     (assign, ":mediator", reg63),
     (assign, "$g_sod_company_spokesperson_type", ":incident_type"),
     (assign, "$g_sod_company_spokesperson_class", ":incident_class"),
     (assign, "$g_sod_company_spokesperson_severity", ":severity"),
     (assign, "$g_sod_company_spokesperson_mediator", ":mediator"),
     (call_script, "script_sod_company_dialogue_store_incident_focus", ":incident_type", ":incident_class", ":severity"),
     (store_current_day, "$g_sod_company_last_spokesperson_incident_day"),
   (else_try),
     (assign, "$g_sod_company_spokesperson_type", sod_company_spokesperson_none),
     (assign, "$g_sod_company_spokesperson_class", sod_company_troop_class_enlisted),
     (assign, "$g_sod_company_spokesperson_severity", 0),
     (assign, "$g_sod_company_spokesperson_mediator", -1),
     (assign, "$g_sod_company_spokesperson_focus_party", -1),
     (assign, "$g_sod_company_spokesperson_focus_center", -1),
     (assign, "$g_sod_company_spokesperson_focus_cause", sod_company_spokesperson_none),
     (assign, "$g_sod_company_spokesperson_focus_class", sod_company_troop_class_enlisted),
     (assign, "$g_sod_company_spokesperson_focus_severity", 0),
   (try_end),
   (assign, reg60, "$g_sod_company_spokesperson_type"),
   (assign, reg61, "$g_sod_company_spokesperson_class"),
   (assign, reg62, "$g_sod_company_spokesperson_severity"),
   (assign, reg63, "$g_sod_company_spokesperson_mediator"),
 ]),

("sod_company_dialogue_schedule_spokesperson_incident",
 [
   (store_current_day, ":cur_day"),
   (store_sub, ":days_since_spokesperson", ":cur_day", "$g_sod_company_last_spokesperson_incident_day"),
   (try_begin),
     (this_or_next|le, "$g_sod_company_spokesperson_type", sod_company_spokesperson_none),
     (ge, ":days_since_spokesperson", 3),
     (call_script, "script_sod_company_dialogue_select_spokesperson_to_regs"),
     (assign, ":incident_type", reg60),
     (assign, ":incident_class", reg61),
     (assign, ":severity", reg62),
     (ge, ":severity", 55),
     (assign, "$g_sod_company_spokesperson_type", ":incident_type"),
     (assign, "$g_sod_company_spokesperson_class", ":incident_class"),
     (assign, "$g_sod_company_spokesperson_severity", ":severity"),
     (call_script, "script_sod_company_dialogue_find_mediator_to_regs", ":incident_type"),
     (assign, "$g_sod_company_spokesperson_mediator", reg63),
     (call_script, "script_sod_company_dialogue_store_incident_focus", ":incident_type", ":incident_class", ":severity"),
     (assign, "$g_sod_company_last_spokesperson_incident_day", ":cur_day"),
     (try_begin),
       (ge, ":severity", 70),
       (assign, "$g_sod_company_spokesperson_dialogue_pending", 1),
       (display_message, "@A company spokesman is gathering around a grievance. They will ask to speak before pressure hardens.", warning_color),
     (try_end),
   (try_end),
 ]),

("sod_company_dialogue_find_spokesperson_troop_to_reg",
 [
   (assign, ":preferred_class", "$g_sod_company_spokesperson_class"),
   (assign, ":speaker", -1),
   (assign, ":fallback", -1),
   (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
   (try_for_range, ":stack_no", 0, ":num_stacks"),
     (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":stack_no"),
     (party_stack_get_size, ":stack_size", "p_main_party", ":stack_no"),
     (gt, ":stack_size", 0),
     (neg|troop_is_hero, ":stack_troop"),
     (try_begin),
       (lt, ":fallback", 0),
       (assign, ":fallback", ":stack_troop"),
     (try_end),
     (call_script, "script_sod_company_accounts_get_troop_class", ":stack_troop"),
     (eq, reg39, ":preferred_class"),
     (lt, ":speaker", 0),
     (assign, ":speaker", ":stack_troop"),
   (try_end),
   (try_begin),
     (lt, ":speaker", 0),
     (assign, ":speaker", ":fallback"),
   (try_end),
   (try_begin),
     (lt, ":speaker", 0),
     (gt, "$g_sod_company_spokesperson_mediator", 0),
     (main_party_has_troop, "$g_sod_company_spokesperson_mediator"),
     (troop_slot_ge, "$g_sod_company_spokesperson_mediator", slot_troop_companion_approval, 45),
     (assign, ":speaker", "$g_sod_company_spokesperson_mediator"),
   (try_end),
   (assign, reg63, ":speaker"),
 ]),

("sod_company_dialogue_process_faith_value_action",
 [
   (store_script_param_1, ":action"),
   (store_script_param_2, ":weight"),
   (try_begin),
     (gt, "$g_sod_company_faith_count", 0),
     (this_or_next|eq, ":action", sod_companion_action_buy_slaves),
     (this_or_next|eq, ":action", sod_companion_action_carry_slaves),
     (this_or_next|eq, ":action", sod_companion_action_sell_prisoners),
     (eq, ":action", sod_companion_action_ymira_refugee_expedience),
     (store_mul, ":pressure", ":weight", 8),
     (val_add, "$g_sod_company_casualty_compensation_pressure", ":pressure"),
     (val_add, "$g_sod_company_camp_strain", ":weight"),
     (assign, "$g_sod_company_spokesperson_type", sod_company_spokesperson_faith_rites),
     (assign, "$g_sod_company_spokesperson_class", sod_company_troop_class_faith),
     (val_add, "$g_sod_company_spokesperson_severity", ":pressure"),
     (val_clamp, "$g_sod_company_spokesperson_severity", 35, 101),
     (call_script, "script_sod_company_dialogue_find_mediator_to_regs", sod_company_spokesperson_faith_rites),
     (assign, "$g_sod_company_spokesperson_mediator", reg63),
     (call_script, "script_sod_company_dialogue_store_incident_focus", sod_company_spokesperson_faith_rites, sod_company_troop_class_faith, "$g_sod_company_spokesperson_severity"),
     (store_current_day, "$g_sod_company_last_spokesperson_incident_day"),
     (display_message, "@Company accounts: faith-minded troops are troubled by captive traffic and cruel profit. A doctrinal voice may ask for rites, mercy, or an offering.", warning_color),
   (else_try),
     (gt, "$g_sod_company_faith_count", 0),
     (this_or_next|eq, ":action", sod_companion_action_free_captives),
     (eq, ":action", sod_companion_action_ymira_refugee_mercy),
     (store_mul, ":relief", ":weight", 5),
     (val_sub, "$g_sod_company_casualty_compensation_pressure", ":relief"),
     (val_sub, "$g_sod_company_camp_strain", ":weight"),
     (try_begin),
       (eq, "$g_sod_company_spokesperson_type", sod_company_spokesperson_faith_rites),
       (val_sub, "$g_sod_company_spokesperson_severity", ":relief"),
     (try_end),
   (try_end),
   (val_clamp, "$g_sod_company_casualty_compensation_pressure", 0, 101),
   (val_clamp, "$g_sod_company_camp_strain", 0, 101),
   (val_clamp, "$g_sod_company_spokesperson_severity", 0, 101),
 ]),

("sod_company_dialogue_describe_mediator_to_s63",
 [
   (assign, ":mediator", "$g_sod_company_spokesperson_mediator"),
   (str_store_string, s63, "@Company spokesman: no trusted companion is ready to mediate the camp's complaint."),
   (try_begin),
     (gt, ":mediator", 0),
     (str_store_troop_name, s64, ":mediator"),
     (call_script, "script_sod_company_dialogue_get_mediator_strength_to_reg", ":mediator", "$g_sod_company_spokesperson_type"),
     (assign, reg53, reg52),
     (call_script, "script_sod_companion_get_approval_band_to_s68", ":mediator"),
     (str_store_string_reg, s67, s68),
     (troop_get_slot, ":role", ":mediator", slot_troop_companion_role),
     (call_script, "script_sod_companion_role_to_s68", ":role"),
     (str_store_string_reg, s66, s68),
     (str_store_string, s62, "@They know enough of camp grievance to speak without making it smaller."),
     (try_begin),
       (eq, ":mediator", "trp_npc2"),
       (str_store_string, s62, "@Marnid frames the grievance as terms, ledgers, and the danger of command losing honest credit."),
     (else_try),
       (eq, ":mediator", "trp_npc10"),
       (str_store_string, s62, "@Bunduk speaks for the line first: tired men, hard orders, and officers who must answer plainly."),
     (else_try),
       (eq, ":mediator", "trp_npc3"),
       (str_store_string, s62, "@Ymira keeps the wound in view: hunger, mercy, and the people command risks forgetting."),
     (else_try),
       (eq, ":mediator", "trp_npc12"),
       (str_store_string, s62, "@Jeremus turns the complaint toward triage, sickness, burial, and care that keeps soldiers human."),
     (else_try),
       (eq, ":mediator", "trp_npc14"),
       (str_store_string, s62, "@Lezalit makes it a question of order: discipline must be legible before it can be obeyed."),
     (else_try),
       (eq, ":mediator", "trp_npc11"),
       (str_store_string, s62, "@Katrin names the practical truth: empty purses and empty pots do not care for speeches."),
     (else_try),
       (eq, ":mediator", "trp_npc1"),
       (str_store_string, s62, "@Borcha reads the camp like a bad road and points out which promise will break first."),
     (else_try),
       (eq, ":mediator", "trp_npc6"),
       (str_store_string, s62, "@Firentis speaks carefully of honor, restraint, and the cost of ordering men past conscience."),
     (else_try),
       (eq, ":mediator", "trp_npc5"),
       (str_store_string, s62, "@Baheshtur judges whether riders are being led by loyalty or merely pulled by reins."),
     (else_try),
       (eq, ":mediator", "trp_npc15"),
       (str_store_string, s62, "@Artimenner reduces the anger to stores, works, ladders, and preparation command can actually fix."),
     (else_try),
       (eq, ":mediator", "trp_npc16"),
       (str_store_string, s62, "@Klethi can speak to dirty bargains, but honorable soldiers may distrust the shape of her help."),
     (try_end),
     (try_begin),
       (ge, reg53, 55),
       (str_store_string, s63, "@Mediator: {s64}, {s67}, serving as {s66}. {s62} They can carry this grievance with real authority."),
     (else_try),
       (ge, reg53, 30),
       (str_store_string, s63, "@Mediator: {s64}, {s67}, serving as {s66}. {s62} They can soften the complaint, but command still needs to answer it."),
     (else_try),
       (str_store_string, s63, "@Mediator: {s64}, {s67}, serving as {s66}. {s62} Their standing is shaky; asking them to speak may only buy a little time."),
     (try_end),
   (try_end),
 ]),

("sod_company_dialogue_describe_spokesperson_risk_to_s65",
 [
   (call_script, "script_sod_company_dialogue_try_spokesperson_incident"),
   (assign, ":incident_type", "$g_sod_company_spokesperson_type"),
   (assign, reg65, "$g_sod_company_spokesperson_severity"),
   (str_store_string, s65, "@Spokesperson risk: none. No formal voice has separated from the camp noise."),
   (try_begin),
     (eq, ":incident_type", sod_company_spokesperson_pay_arrears),
     (str_store_string, s65, "@Spokesperson risk: pay arrears ({reg65}). Contract-minded troops are most likely to send a hard voice to the accounts."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_thin_rations),
     (str_store_string, s65, "@Spokesperson risk: rations ({reg65}). The common line is close to speaking in bowls, boots, and empty bellies."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_wounded_care),
     (str_store_string, s65, "@Spokesperson risk: wounded care ({reg65}). The injured and those who watched them fall are waiting for an answer."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_hazard_pay),
     (str_store_string, s65, "@Spokesperson risk: hazard pay ({reg65}). Veterans and paid swords are measuring walls, ladders, and risk in silver."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_noble_honor),
     (str_store_string, s65, "@Spokesperson risk: noble honor ({reg65}). Retainers are looking for public worth, prestige, and command that remembers oaths."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_faith_rites),
     (str_store_string, s65, "@Spokesperson risk: faith and rites ({reg65}). Oath-bound troops are watching mercy, burial, food security, and care for the wounded."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_battle_promise_due),
     (str_store_string, s65, "@Spokesperson risk: battle promise ({reg65}). The camp remembers that you tied coin to the next fight."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_victory_spoils),
     (str_store_string, s65, "@Spokesperson risk: victory claim ({reg65}). The company wants the victory named in coin, honors, food, or a clear refusal."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_defeat_shock),
     (str_store_string, s65, "@Spokesperson risk: defeat shock ({reg65}). The camp is asking whether the next order will repair confidence or spend what is left."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_discipline_threat),
     (str_store_string, s65, "@Spokesperson risk: discipline threat ({reg65}). The complaint is close to becoming a test of command itself."),
   (try_end),
   (try_begin),
     (gt, "$g_sod_company_spokesperson_mediator", 0),
     (str_store_troop_name, s66, "$g_sod_company_spokesperson_mediator"),
     (str_store_string_reg, s97, s65),
     (str_store_string, s65, "@{s97}^Best mediator: {s66}."),
   (try_end),
 ]),

("sod_company_dialogue_describe_spokesperson_to_s60",
 [
   (try_begin),
     (eq, "$g_sod_company_spokesperson_dialogue_active", 0),
     (call_script, "script_sod_company_dialogue_try_spokesperson_incident"),
   (try_end),
   (assign, ":incident_type", "$g_sod_company_spokesperson_type"),
   (assign, reg60, "$g_sod_company_spokesperson_severity"),
   (str_store_string, s61, "@No one is ready to speak formally. The camp is watching, but no single voice has stepped forward."),
   (try_begin),
     (eq, ":incident_type", sod_company_spokesperson_pay_arrears),
     (str_store_string, s61, "@A hard-faced pay spokesman waits near the accounts. 'Captain, terms are terms. Coin late after blood spent is still coin owed.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_thin_rations),
     (str_store_string, s61, "@An enlisted spokesman turns a wooden bowl in his hands. 'The men can march hungry, commander. They cannot keep doing it and call it loyalty.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_wounded_care),
     (str_store_string, s61, "@A voice from the wounded line speaks quietly. 'Those who stood in front need tending, and those who will stand tomorrow are watching.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_hazard_pay),
     (str_store_string, s61, "@A veteran points back toward the walls and ladders. 'Hazard has a price. If command names it glory, the men name it silver.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_noble_honor),
     (str_store_string, s61, "@A noble retainer bows stiffly. 'Oaths are not hired noise. Your household must be seen to honor those who carry its dignity.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_battle_promise_due),
     (str_store_string, s61, "@The camp remembers your battle promise. No one shouts it, which is worse: the silence has begun counting coin."),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_faith_rites),
     (str_store_string, s61, "@A faith-bound spokesman waits with oath-token in hand. 'Burial, bread, and mercy tell us what kind of road this banner walks.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_victory_spoils),
     (str_store_string, s61, "@A victory spokesman stands where the company can hear. 'Captain, we carried the day. Say what that means before the tale grows teeth.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_defeat_shock),
     (str_store_string, s61, "@A shaken spokesman comes forward from a quiet line. 'We can follow after defeat. We need to know command learned from it.'"),
   (else_try),
     (eq, ":incident_type", sod_company_spokesperson_discipline_threat),
     (str_store_string, s61, "@A hard-eyed spokesman keeps his voice level. 'If this is discipline, make it legible. If it is anger, name it before men answer in kind.'"),
   (try_end),
   (call_script, "script_sod_company_dialogue_describe_mediator_to_s63"),
   (str_store_string, s64, "@Focus: the complaint is a camp-wide grievance, not tied to a single place."),
   (try_begin),
     (is_between, "$g_sod_company_spokesperson_focus_center", centers_begin, centers_end),
     (str_store_party_name, s62, "$g_sod_company_spokesperson_focus_center"),
     (str_store_string, s64, "@Focus: this grievance was last anchored near {s62}."),
   (else_try),
     (gt, "$g_sod_company_spokesperson_focus_party", 0),
     (str_store_party_name, s62, "$g_sod_company_spokesperson_focus_party"),
     (str_store_string, s64, "@Focus: this grievance is centered on {s62} and the company road."),
   (try_end),
   (assign, reg61, "$g_sod_company_last_spokesperson_incident_day"),
   (assign, reg62, "$g_sod_company_spokesperson_last_response"),
   (assign, reg50, "$g_sod_company_spokesperson_focus_cause"),
   (assign, reg51, "$g_sod_company_spokesperson_focus_class"),
   (assign, reg52, "$g_sod_company_spokesperson_focus_severity"),
   (str_store_string, s60, "@Company Spokesperson^^Severity: {reg60}. Last formal hearing day: {reg61}. Last response: {reg62}. Focus cause/class/severity: {reg50}/{reg51}/{reg52}.^^{s61}^^{s64}^^{s63}"),
 ]),

("sod_company_dialogue_describe_battle_start_morale_to_s60",
 [
   (call_script, "script_sod_company_accounts_get_battle_morale_context_to_regs"),
   (assign, ":company_morale", reg60),
   (assign, ":pay_strain", reg61),
   (assign, ":fatigue", reg62),
   (assign, ":supply_confidence", reg63),
   (str_store_string, s60, "@"),
   (assign, reg50, 0),
   (try_begin),
     (gt, "$g_sod_company_battle_promise_active", 0),
     (str_store_string, s60, "@Company morale: the line forms with one promise in every ear. Win or lose, battle-pay will be counted after this fight."),
     (assign, reg50, 1),
   (else_try),
     (ge, ":pay_strain", 75),
     (str_store_string, s60, "@Company morale: unpaid coin and strained accounts make the ranks quiet. They will fight, but every order walks beside debt."),
     (assign, reg50, 1),
   (else_try),
     (le, ":supply_confidence", 30),
     (str_store_string, s60, "@Company morale: hunger has followed the company onto the field. Men tighten belts before they tighten shields."),
     (assign, reg50, 1),
   (else_try),
     (ge, ":fatigue", 55),
     (str_store_string, s60, "@Company morale: wounded memories and hard marching weigh on the line. The company needs a clean answer from this battle."),
     (assign, reg50, 1),
   (else_try),
     (this_or_next|lt, "$g_sod_company_enlisted_morale", 35),
     (this_or_next|lt, "$g_sod_company_mercenary_morale", 35),
     (this_or_next|lt, "$g_sod_company_noble_morale", 35),
     (lt, "$g_sod_company_faith_morale", 35),
     (str_store_string, s60, "@Company morale: one part of the host is wavering. The battle line holds, but not every bench believes for the same reason."),
     (assign, reg50, 1),
   (else_try),
     (ge, ":company_morale", 70),
     (str_store_string, s60, "@Company morale: pay, food, and command are steady enough that the ranks answer with confidence."),
     (assign, reg50, 1),
   (else_try),
     (le, ":company_morale", 35),
     (str_store_string, s60, "@Company morale: the company enters battle brittle. Victory may steady them; defeat will echo in camp."),
     (assign, reg50, 1),
   (try_end),
 ]),

("sod_company_dialogue_process_battle_start_morale",
 [
   (call_script, "script_sod_company_dialogue_describe_battle_start_morale_to_s60"),
   (try_begin),
     (eq, reg50, 1),
     (display_message, "@Battle report: {s60}", warning_color),
   (try_end),
 ]),

("sod_company_dialogue_flag_post_battle_incident",
 [
   (store_script_param_1, ":outcome"),
   (call_script, "script_sod_company_dialogue_select_spokesperson_to_regs"),
   (assign, ":incident_type", reg60),
   (assign, ":incident_class", reg61),
   (assign, ":severity", reg62),
   (try_begin),
     (gt, ":outcome", 0),
     (store_current_day, ":cur_day"),
     (store_sub, ":days_since_reward", ":cur_day", "$g_sod_company_last_victory_reward_day"),
     (store_sub, ":days_since_honor", ":cur_day", "$g_sod_company_last_public_honor_day"),
     (try_begin),
       (gt, "$g_player_debt_to_party_members", 0),
       (val_add, ":severity", 18),
       (assign, ":incident_type", sod_company_spokesperson_victory_spoils),
       (assign, ":incident_class", sod_company_troop_class_mercenary),
     (else_try),
       (this_or_next|gt, ":days_since_reward", 3),
       (gt, ":days_since_honor", 3),
       (val_add, ":severity", 10),
       (assign, ":incident_type", sod_company_spokesperson_victory_spoils),
       (assign, ":incident_class", sod_company_troop_class_noble),
     (try_end),
     (try_begin),
       (gt, "$g_sod_company_casualty_compensation_pressure", 35),
       (assign, ":incident_type", sod_company_spokesperson_wounded_care),
       (assign, ":incident_class", sod_company_troop_class_faith),
       (assign, ":severity", "$g_sod_company_casualty_compensation_pressure"),
     (try_end),
   (else_try),
     (assign, ":incident_type", sod_company_spokesperson_defeat_shock),
     (assign, ":incident_class", sod_company_troop_class_enlisted),
     (store_add, ":severity", "$g_sod_company_camp_strain", 20),
     (try_begin),
       (gt, "$g_player_debt_to_party_members", 0),
       (assign, ":incident_class", sod_company_troop_class_mercenary),
       (val_add, ":severity", 15),
     (try_end),
     (try_begin),
       (gt, "$g_sod_company_casualty_compensation_pressure", 45),
       (assign, ":incident_type", sod_company_spokesperson_wounded_care),
       (assign, ":incident_class", sod_company_troop_class_faith),
       (assign, ":severity", "$g_sod_company_casualty_compensation_pressure"),
     (try_end),
   (try_end),
   (val_clamp, ":severity", 0, 101),
   (try_begin),
     (ge, ":severity", 35),
     (assign, "$g_sod_company_spokesperson_type", ":incident_type"),
     (assign, "$g_sod_company_spokesperson_class", ":incident_class"),
     (assign, "$g_sod_company_spokesperson_severity", ":severity"),
     (call_script, "script_sod_company_dialogue_find_mediator_to_regs", ":incident_type"),
     (assign, "$g_sod_company_spokesperson_mediator", reg63),
     (call_script, "script_sod_company_dialogue_store_incident_focus", ":incident_type", ":incident_class", ":severity"),
     (store_current_day, "$g_sod_company_last_spokesperson_incident_day"),
   (try_end),
 ]),

("sod_company_dialogue_process_post_battle_prompt",
 [
   (store_script_param_1, ":outcome"),
   (call_script, "script_sod_company_dialogue_flag_post_battle_incident", ":outcome"),
 ]),

("sod_company_dialogue_describe_post_battle_to_s66",
 [
   (store_current_day, ":cur_day"),
   (store_sub, ":days_since_victory", ":cur_day", "$g_sod_company_last_victory_day"),
   (store_sub, ":days_since_reward", ":cur_day", "$g_sod_company_last_victory_reward_day"),
   (store_sub, ":days_since_honor", ":cur_day", "$g_sod_company_last_public_honor_day"),
   (store_sub, ":days_since_feast", ":cur_day", "$g_sod_company_last_victory_feast_day"),
   (store_sub, ":days_since_casualties", ":cur_day", "$g_sod_company_last_casualty_day"),
   (val_max, ":days_since_victory", 0),
   (val_max, ":days_since_reward", 0),
   (val_max, ":days_since_honor", 0),
   (val_max, ":days_since_feast", 0),
   (val_max, ":days_since_casualties", 0),
   (assign, reg52, ":days_since_victory"),
   (assign, reg53, ":days_since_reward"),
   (assign, reg54, ":days_since_honor"),
   (assign, reg55, ":days_since_feast"),
   (assign, reg56, "$g_sod_company_recent_wounded_count"),
   (assign, reg57, "$g_sod_company_casualty_compensation_pressure"),
   (str_store_string, s66, "@Aftermath: no fresh battle grievance is asking for company-account attention."),
   (try_begin),
     (gt, "$g_sod_company_wage_promise_amount", 0),
     (str_store_string, s66, "@Aftermath: battle-pay is now a live account. {reg56} wounded are remembered, and the promise line should be settled before it turns sour."),
   (else_try),
     (le, ":days_since_victory", 3),
     (gt, "$g_sod_company_casualty_compensation_pressure", 35),
     (str_store_string, s66, "@Aftermath: victory is recent, but the wounded are the louder memory. Settle casualty care first; any ceremony should come through a camp spokesman, not the account book."),
   (else_try),
     (le, ":days_since_victory", 3),
     (str_store_string, s66, "@Aftermath: victory is still warm. Spoils last shared {reg53} days ago, honors {reg54}, feast {reg55}. Let the spokesman raise ceremony; the accounts screen keeps to pay, rations, and recovery."),
   (else_try),
     (le, ":days_since_casualties", 3),
     (gt, "$g_sod_company_casualty_compensation_pressure", 20),
     (str_store_string, s66, "@Aftermath: defeat or hard fighting left {reg56} wounded and casualty pressure {reg57}. Rally the camp through pay, wounded care, rations, rest, or a clear recovery promise."),
   (try_end),
 ]),

("sod_company_dialogue_apply_response",
 [
   (store_script_param_1, ":response"),
   (assign, "$g_sod_company_spokesperson_last_response", ":response"),
   (try_begin),
     (eq, ":response", sod_company_spokesperson_response_pay_now),
     (call_script, "script_sod_company_accounts_apply_pay_choice", sod_company_pay_choice_full),
     (val_sub, "$g_sod_company_spokesperson_severity", 25),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_fair_pay, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_promise),
     (call_script, "script_sod_company_accounts_set_pay_promise"),
     (val_sub, "$g_sod_company_spokesperson_severity", 10),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_debt_honesty, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_battle_promise),
     (call_script, "script_sod_company_accounts_set_battle_pay_promise"),
     (val_sub, "$g_sod_company_spokesperson_severity", 8),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_empty_speech, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_ration_change),
     (call_script, "script_sod_company_accounts_set_ration_policy", sod_company_ration_policy_generous),
     (val_sub, "$g_sod_company_spokesperson_severity", 14),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_generous_rations, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_rites_wounded),
     (call_script, "script_sod_company_accounts_apply_casualty_compensation"),
     (val_sub, "$g_sod_company_spokesperson_severity", 18),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_wounded_pay, 1),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_religious_rites, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_hazard_pay),
     (call_script, "script_sod_company_accounts_apply_hazard_pay"),
     (val_sub, "$g_sod_company_spokesperson_severity", 20),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_veteran_pay, 1),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_siege_preparation, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_recreation),
     (call_script, "script_sod_company_accounts_apply_recreation", sod_company_recreation_campfire),
     (val_sub, "$g_sod_company_camp_strain", 6),
     (val_sub, "$g_sod_company_spokesperson_severity", 10),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_tavern_recreation, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_public_honors),
     (eq, "$g_sod_company_spokesperson_type", sod_company_spokesperson_victory_spoils),
     (call_script, "script_sod_company_accounts_apply_victory_reward", 2),
     (val_sub, "$g_sod_company_spokesperson_severity", 16),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_tournament_glory, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_victory_feast),
     (eq, "$g_sod_company_spokesperson_type", sod_company_spokesperson_victory_spoils),
     (eq, "$g_sod_company_victory_feast_available", 1),
     (call_script, "script_sod_company_accounts_apply_victory_feast"),
     (val_sub, "$g_sod_company_spokesperson_severity", 12),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_ration_feast, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_refuse_spectacle),
     (eq, "$g_sod_company_spokesperson_type", sod_company_spokesperson_victory_spoils),
     (call_script, "script_sod_company_accounts_refuse_public_spectacle"),
     (val_sub, "$g_sod_company_spokesperson_severity", 6),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_strict_discipline, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_company_offering),
     (call_script, "script_sod_company_accounts_apply_recreation", sod_company_recreation_company_offering),
     (val_sub, "$g_sod_company_spokesperson_severity", 14),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_religious_rites, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_mediation),
     (call_script, "script_sod_company_dialogue_get_mediator_strength_to_reg", "$g_sod_company_spokesperson_mediator", "$g_sod_company_spokesperson_type"),
     (assign, ":mediation_strength", reg52),
     (try_begin),
       (ge, ":mediation_strength", 55),
       (val_sub, "$g_sod_company_camp_strain", 12),
       (val_sub, "$g_sod_company_petition_severity", 18),
       (val_sub, "$g_sod_company_desertion_risk", 12),
       (val_add, "$g_sod_company_pay_confidence", 3),
       (val_sub, "$g_sod_company_spokesperson_severity", 18),
       (display_message, "@Company spokesman: trusted mediation turns anger into terms the camp can live with.", good_color),
     (else_try),
       (ge, ":mediation_strength", 30),
       (val_sub, "$g_sod_company_camp_strain", 7),
       (val_sub, "$g_sod_company_petition_severity", 10),
       (val_sub, "$g_sod_company_desertion_risk", 6),
       (val_add, "$g_sod_company_pay_confidence", 1),
       (val_sub, "$g_sod_company_spokesperson_severity", 9),
       (display_message, "@Company spokesman: mediation buys time, but the grievance still wants an answer.", warning_color),
     (else_try),
       (val_sub, "$g_sod_company_petition_severity", 4),
       (val_add, "$g_sod_company_camp_strain", 1),
       (val_sub, "$g_sod_company_spokesperson_severity", 3),
       (display_message, "@Company spokesman: weak mediation quiets the nearest voices, not the grievance beneath them.", warning_color),
     (try_end),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_petition_mediated, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_persuade),
     (store_skill_level, ":leadership", "skl_leadership", "trp_player"),
     (store_skill_level, ":persuasion", "skl_persuasion", "trp_player"),
     (store_add, ":command_skill", ":leadership", ":persuasion"),
     (val_add, ":command_skill", 4),
     (val_sub, "$g_sod_company_spokesperson_severity", ":command_skill"),
     (val_sub, "$g_sod_company_petition_severity", ":persuasion"),
     (try_begin),
       (ge, ":command_skill", 10),
       (val_sub, "$g_sod_company_camp_strain", 3),
       (display_message, "@Company spokesman: your answer has enough substance to hold the grievance for now.", good_color),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_debt_honesty, 1),
     (else_try),
       (val_add, "$g_sod_company_camp_strain", 2),
       (display_message, "@Company spokesman: the words land thin. The camp hears an answer, not yet a remedy.", warning_color),
       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_empty_speech, 1),
     (try_end),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_threaten),
     (call_script, "script_sod_company_accounts_apply_threat"),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_threatened_troops, 1),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_strict_discipline, 1),
   (else_try),
     (eq, ":response", sod_company_spokesperson_response_dismiss),
     (val_add, "$g_sod_company_camp_strain", 5),
     (val_add, "$g_sod_company_petition_severity", 6),
     (val_sub, "$g_sod_company_pay_confidence", 3),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_empty_speech, 1),
   (try_end),
   (val_clamp, "$g_sod_company_spokesperson_severity", 0, 101),
   (val_clamp, "$g_sod_company_camp_strain", 0, 101),
   (val_clamp, "$g_sod_company_petition_severity", 0, 101),
   (val_clamp, "$g_sod_company_desertion_risk", 0, 121),
   (val_clamp, "$g_sod_company_pay_confidence", 0, 101),
 ]),
]
