# COST: O(trade goods)
SCRIPTS = [
("sod_get_center_goods_market_profile",
  [
    (store_script_param, ":center_no", 1),

    (assign, ":food_balance", 0),
    (assign, ":raw_balance", 0),
    (assign, ":strategic_balance", 0),
    (assign, ":luxury_flow", 0),
    (assign, ":scarcity_pressure", 0),
    (assign, ":trade_willingness", 100),
    (assign, ":liquidity_pressure", 0),
    (assign, ":wealth_delta", 0),
    (assign, ":prosperity_pressure", 0),
    (assign, ":market_role", 0),

    (try_begin),
      (is_between, ":center_no", centers_begin, centers_end),

      (call_script, "script_sod_get_center_trade_demand_profile", ":center_no"),
      (assign, ":demand_scarcity", reg0),
      (assign, ":import_demand", reg1),
      (assign, ":export_supply", reg2),
      (assign, ":profile_liquidity", reg3),
      (assign, ":security_willingness", reg4),
      (assign, ":tax_friction", reg5),
      (assign, ":caravan_attractiveness", reg6),
      (assign, ":effective_trade_volume", reg7),

      (try_for_range, ":cur_good", trade_goods_begin, trade_goods_end),
        (store_sub, ":production_slot", ":cur_good", trade_goods_begin),
        (val_add, ":production_slot", slot_town_trade_good_productions_begin),
        (party_get_slot, ":production", ":center_no", ":production_slot"),

        (try_begin),
          (this_or_next|eq, ":cur_good", "itm_grain"),
          (this_or_next|eq, ":cur_good", "itm_flour"),
          (this_or_next|eq, ":cur_good", "itm_bread"),
          (this_or_next|eq, ":cur_good", "itm_cabbages"),
          (this_or_next|eq, ":cur_good", "itm_apples"),
          (this_or_next|eq, ":cur_good", "itm_smoked_fish"),
          (this_or_next|eq, ":cur_good", "itm_dried_meat"),
          (this_or_next|eq, ":cur_good", "itm_cattle_meat"),
          (this_or_next|eq, ":cur_good", "itm_pork"),
          (this_or_next|eq, ":cur_good", "itm_chicken"),
          (this_or_next|eq, ":cur_good", "itm_cheese"),
          (this_or_next|eq, ":cur_good", "itm_butter"),
          (this_or_next|eq, ":cur_good", "itm_honey"),
          (this_or_next|eq, ":cur_good", "itm_sausages"),
          (this_or_next|eq, ":cur_good", "itm_ale"),
          (eq, ":cur_good", "itm_wine"),
          (val_add, ":food_balance", ":production"),
        (else_try),
          (this_or_next|eq, ":cur_good", "itm_wool"),
          (this_or_next|eq, ":cur_good", "itm_pottery"),
          (this_or_next|eq, ":cur_good", "itm_linen"),
          (eq, ":cur_good", "itm_furs"),
          (val_add, ":raw_balance", ":production"),
        (else_try),
          (this_or_next|eq, ":cur_good", "itm_salt"),
          (this_or_next|eq, ":cur_good", "itm_iron"),
          (this_or_next|eq, ":cur_good", "itm_oil"),
          (eq, ":cur_good", "itm_tools"),
          (val_add, ":strategic_balance", ":production"),
        (else_try),
          (this_or_next|eq, ":cur_good", "itm_spice"),
          (eq, ":cur_good", "itm_velvet"),
          (val_add, ":luxury_flow", ":production"),
        (try_end),
      (try_end),

      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (assign, ":market_role", 3),
        (store_div, ":town_import_need", ":import_demand", 2),
        (val_sub, ":food_balance", ":town_import_need"),
        (val_add, ":liquidity_pressure", ":profile_liquidity"),
        (store_div, ":service_liquidity", ":caravan_attractiveness", 3),
        (val_add, ":liquidity_pressure", ":service_liquidity"),
      (else_try),
        (is_between, ":center_no", villages_begin, villages_end),
        (assign, ":market_role", 1),
        (val_add, ":liquidity_pressure", ":export_supply"),
        (val_div, ":liquidity_pressure", 2),
      (else_try),
        (is_between, ":center_no", castles_begin, castles_end),
        (assign, ":market_role", 2),
        (store_div, ":castle_store_need", ":import_demand", 2),
        (val_sub, ":strategic_balance", ":castle_store_need"),
        (store_div, ":castle_liquidity", ":profile_liquidity", 2),
        (val_add, ":liquidity_pressure", ":castle_liquidity"),
      (try_end),

      (assign, ":scarcity_pressure", ":demand_scarcity"),
      (try_begin),
        (lt, ":food_balance", 0),
        (store_mul, ":food_shortage", ":food_balance", -1),
        (val_div, ":food_shortage", 2),
        (val_add, ":scarcity_pressure", ":food_shortage"),
      (try_end),
      (try_begin),
        (lt, ":strategic_balance", 0),
        (store_mul, ":strategic_shortage", ":strategic_balance", -1),
        (val_div, ":strategic_shortage", 3),
        (val_add, ":scarcity_pressure", ":strategic_shortage"),
      (try_end),
      (val_clamp, ":scarcity_pressure", 0, 251),

      (assign, ":trade_willingness", ":security_willingness"),
      (store_div, ":volume_willingness", ":effective_trade_volume", 5),
      (val_add, ":trade_willingness", ":volume_willingness"),
      (store_div, ":friction_drag", ":tax_friction", 2),
      (val_sub, ":trade_willingness", ":friction_drag"),
      (try_begin),
        (gt, ":scarcity_pressure", 120),
        (val_sub, ":trade_willingness", 10),
      (try_end),
      (val_clamp, ":trade_willingness", 15, 181),

      (store_div, ":food_liquidity", ":food_balance", 5),
      (val_add, ":liquidity_pressure", ":food_liquidity"),
      (store_div, ":raw_liquidity", ":raw_balance", 4),
      (val_add, ":liquidity_pressure", ":raw_liquidity"),
      (store_div, ":strategic_liquidity", ":strategic_balance", 3),
      (val_add, ":liquidity_pressure", ":strategic_liquidity"),
      (store_div, ":luxury_liquidity", ":luxury_flow", 2),
      (val_add, ":liquidity_pressure", ":luxury_liquidity"),
      (store_div, ":scarcity_liquidity_drag", ":scarcity_pressure", 3),
      (val_sub, ":liquidity_pressure", ":scarcity_liquidity_drag"),
      (val_mul, ":liquidity_pressure", ":trade_willingness"),
      (val_div, ":liquidity_pressure", 100),
      (val_clamp, ":liquidity_pressure", -80, 301),

      (assign, ":wealth_delta", ":liquidity_pressure"),
      (val_mul, ":wealth_delta", 8),
      (try_begin),
        (eq, ":market_role", 3),
        (val_mul, ":wealth_delta", 3),
        (val_div, ":wealth_delta", 2),
      (else_try),
        (eq, ":market_role", 2),
        (val_mul, ":wealth_delta", 2),
        (val_div, ":wealth_delta", 3),
      (try_end),
      (val_clamp, ":wealth_delta", -500, 1801),

      (assign, ":prosperity_pressure", 0),
      (try_begin),
        (gt, ":liquidity_pressure", 80),
        (assign, ":prosperity_pressure", 1),
      (else_try),
        (gt, ":scarcity_pressure", 150),
        (assign, ":prosperity_pressure", -1),
      (try_end),
    (try_end),

    (assign, reg0, ":food_balance"),
    (assign, reg1, ":raw_balance"),
    (assign, reg2, ":strategic_balance"),
    (assign, reg3, ":luxury_flow"),
    (assign, reg4, ":scarcity_pressure"),
    (assign, reg5, ":trade_willingness"),
    (assign, reg6, ":liquidity_pressure"),
    (assign, reg7, ":wealth_delta"),
    (assign, reg8, ":prosperity_pressure"),
    (assign, reg9, ":market_role"),
  ]),
]
