# COST: light
SCRIPTS = [
("sod_black_army_world_presence",
 [
   (store_current_day, ":cur_day"),
   (store_character_level, ":player_level", "trp_player"),

   (store_num_parties_of_template, ":active_patrols", "pt_black_army_patrol"),
   (store_num_parties_of_template, ":active_columns", "pt_black_army_contract_column"),
   (store_add, ":active_total", ":active_patrols", ":active_columns"),

   (assign, ":employer_faction", 0),
   (try_for_range, ":cur_faction", kingdoms_begin, kingdoms_end),
     (eq, ":employer_faction", 0),
     (faction_slot_eq, ":cur_faction", slot_faction_merc_pact, "fac_sod_merc_guild1"),
     (faction_slot_eq, ":cur_faction", slot_faction_state, sfs_active),
     (assign, ":employer_faction", ":cur_faction"),
   (try_end),

   (assign, ":target_limit", 2),
   (try_begin),
     (ge, ":player_level", 10),
     (val_add, ":target_limit", 1),
   (try_end),
   (try_begin),
     (gt, ":employer_faction", 0),
     (val_add, ":target_limit", 1),
   (try_end),
   (val_clamp, ":target_limit", 2, 5),

   (assign, ":threat_center", 0),
   (assign, ":threat_score", 0),
   (try_for_range, ":center_no", centers_begin, centers_end),
     (try_begin),
       (gt, ":employer_faction", 0),
       (store_faction_of_party, ":center_faction", ":center_no"),
       (eq, ":center_faction", ":employer_faction"),
     (else_try),
       (store_distance_to_party_from_party, ":dist", ":center_no", "p_sod_merc_guild_1"),
       (lt, ":dist", 45),
     (try_end),
     (try_begin),
       (is_between, ":center_no", walled_centers_begin, walled_centers_end),
       (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
     (else_try),
       (is_between, ":center_no", villages_begin, villages_end),
       (neg|party_slot_eq, ":center_no", slot_village_state, svs_looted),
       (neg|party_slot_eq, ":center_no", slot_village_state, svs_deserted),
     (try_end),
     (call_script, "script_get_center_threat_level", ":center_no"),
     (assign, ":center_threat", reg0),
     (party_get_slot, ":center_health", ":center_no", slot_center_sod_local_health),
     (party_get_slot, ":center_prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
     (store_sub, ":damage_pressure", 100, ":center_health"),
     (val_add, ":damage_pressure", 100),
     (val_sub, ":damage_pressure", ":center_prosperity"),
     (try_begin),
       (is_between, ":center_no", villages_begin, villages_end),
       (store_sub, ":population_pressure", village_pop_min, ":center_population"),
       (val_max, ":population_pressure", 0),
       (val_div, ":population_pressure", 5),
       (val_add, ":damage_pressure", ":population_pressure"),
     (else_try),
       (store_sub, ":population_pressure", town_pop_min, ":center_population"),
       (val_max, ":population_pressure", 0),
       (val_div, ":population_pressure", 20),
       (val_add, ":damage_pressure", ":population_pressure"),
     (try_end),
     (val_div, ":damage_pressure", 12),
     (store_mul, ":center_score", ":center_threat", 8),
     (val_add, ":center_score", ":damage_pressure"),
     (gt, ":center_score", ":threat_score"),
     (assign, ":threat_score", ":center_score"),
     (assign, ":threat_center", ":center_no"),
   (try_end),

   (try_begin),
     (gt, ":threat_score", 10),
     (lt, ":target_limit", 5),
     (val_add, ":target_limit", 1),
   (try_end),

   (try_for_parties, ":cur_party"),
     (party_get_template_id, ":cur_template", ":cur_party"),
     (this_or_next|eq, ":cur_template", "pt_black_army_patrol"),
     (eq, ":cur_template", "pt_black_army_contract_column"),
     (party_set_faction, ":cur_party", "fac_sod_merc_guild1"),
     (party_set_slot, ":cur_party", slot_party_orginal_faction, "fac_sod_merc_guild1"),
     (party_set_slot, ":cur_party", slot_party_starting_base, "p_sod_merc_guild_1"),
     (party_set_slot, ":cur_party", slot_party_type, spt_ai_mercenaries),
     (party_set_slot, ":cur_party", slot_party_boss, -1),
     (store_add, ":contract_day", ":cur_day", 35),
     (party_set_slot, ":cur_party", slot_party_merc_contract, ":contract_day"),
     (try_begin),
       (gt, ":threat_center", 0),
       (party_set_slot, ":cur_party", slot_party_commander_party, ":threat_center"),
       (call_script, "script_party_set_ai_state", ":cur_party", spai_patrolling_around_center, ":threat_center"),
     (else_try),
       (party_set_slot, ":cur_party", slot_party_commander_party, "p_sod_merc_guild_1"),
       (call_script, "script_party_set_ai_state", ":cur_party", spai_patrolling_around_center, "p_sod_merc_guild_1"),
     (try_end),
   (try_end),

   (try_begin),
     (lt, ":active_total", ":target_limit"),
     (assign, ":spawn_center", "p_sod_merc_guild_1"),
     (try_begin),
       (gt, ":threat_center", 0),
       (assign, ":spawn_center", ":threat_center"),
     (try_end),
     (try_begin),
       (gt, ":employer_faction", 0),
       (lt, ":active_columns", 1),
       (assign, ":template", "pt_black_army_contract_column"),
     (else_try),
       (assign, ":template", "pt_black_army_patrol"),
     (try_end),
     (set_spawn_radius, 5),
     (spawn_around_party, ":spawn_center", ":template"),
     (assign, ":new_party", reg0),
     (party_set_faction, ":new_party", "fac_sod_merc_guild1"),
     (party_set_slot, ":new_party", slot_party_orginal_faction, "fac_sod_merc_guild1"),
     (party_set_slot, ":new_party", slot_party_starting_base, "p_sod_merc_guild_1"),
     (party_set_slot, ":new_party", slot_party_type, spt_ai_mercenaries),
     (party_set_slot, ":new_party", slot_party_boss, -1),
     (party_set_slot, ":new_party", slot_party_commander_party, ":spawn_center"),
     (store_add, ":contract_day", ":cur_day", 35),
     (party_set_slot, ":new_party", slot_party_merc_contract, ":contract_day"),
     (party_set_banner_icon, ":new_party", "icon_banner_298"),
     (call_script, "script_party_set_ai_state", ":new_party", spai_patrolling_around_center, ":spawn_center"),
     (party_set_ai_patrol_radius, ":new_party", 8),
   (try_end),

   (try_for_range, ":center_no", centers_begin, centers_end),
     (assign, ":protected", 0),
     (try_for_parties, ":cur_party"),
       (eq, ":protected", 0),
       (party_slot_eq, ":cur_party", slot_party_orginal_faction, "fac_sod_merc_guild1"),
       (this_or_next|party_slot_eq, ":cur_party", slot_party_type, spt_ai_mercenaries),
       (party_slot_eq, ":cur_party", slot_party_starting_base, "p_sod_merc_guild_1"),
       (store_distance_to_party_from_party, ":dist", ":cur_party", ":center_no"),
       (le, ":dist", 12),
       (assign, ":protected", 1),
     (try_end),
     (eq, ":protected", 1),
     (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
     (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
     (try_begin),
       (lt, ":health", 75),
       (call_script, "script_sod_center_apply_health_delta", ":center_no", 1),
     (try_end),
     (try_begin),
       (lt, ":prosperity", 65),
       (call_script, "script_change_center_prosperity", ":center_no", 1),
     (try_end),
     (try_begin),
       (ge, ":health", 40),
       (try_begin),
         (is_between, ":center_no", villages_begin, villages_end),
         (assign, ":recovery_floor", village_pop_min),
       (else_try),
         (assign, ":recovery_floor", town_pop_min),
       (try_end),
       (lt, ":population", ":recovery_floor"),
       (store_sub, ":population_delta", ":recovery_floor", ":population"),
       (val_min, ":population_delta", 2),
       (call_script, "script_sod_center_apply_population_delta", ":center_no", ":population_delta"),
     (try_end),
     (try_begin),
       (lt, ":wealth", 1000),
       (store_sub, ":wealth_delta", 1000, ":wealth"),
       (val_min, ":wealth_delta", 25),
       (call_script, "script_sod_center_apply_wealth_delta", ":center_no", ":wealth_delta"),
       (faction_get_slot, ":security_fund", "fac_sod_merc_guild1", slot_faction_black_army_security_fund),
       (val_add, ":security_fund", 10),
       (val_clamp, ":security_fund", 0, 2000),
       (faction_set_slot, "fac_sod_merc_guild1", slot_faction_black_army_security_fund, ":security_fund"),
     (try_end),
   (try_end),

   (assign, ":interdictions", 0),
   (try_for_parties, ":black_party"),
     (eq, ":interdictions", 0),
     (party_is_active, ":black_party"),
     (party_get_template_id, ":black_template", ":black_party"),
     (this_or_next|eq, ":black_template", "pt_black_army_patrol"),
     (eq, ":black_template", "pt_black_army_contract_column"),
     (try_for_parties, ":threat_party"),
       (eq, ":interdictions", 0),
       (party_is_active, ":threat_party"),
      (try_begin),
        (party_slot_eq, ":threat_party", slot_party_sod_slaver_web_activity, 1),
      (else_try),
        (party_slot_eq, ":threat_party", slot_party_sod_boar_frontier_activity, 1),
      (else_try),
        (party_slot_eq, ":threat_party", slot_party_black_khergit_camp_activity, 1),
      (try_end),
       (store_distance_to_party_from_party, ":threat_dist", ":black_party", ":threat_party"),
       (lt, ":threat_dist", 9),
       (party_set_ai_behavior, ":black_party", ai_bhvr_attack_party),
       (party_set_ai_object, ":black_party", ":threat_party"),
       (faction_get_slot, ":contract_heat", "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
       (val_add, ":contract_heat", 4),
       (val_clamp, ":contract_heat", 0, 101),
       (faction_set_slot, "fac_sod_merc_guild1", slot_faction_black_army_contract_heat, ":contract_heat"),
       (assign, ":interdictions", 1),
     (try_end),
   (try_end),
   (try_begin),
     (gt, ":interdictions", 0),
     (display_message, "@Black Army patrols are moving against road predators.", 0x444444),
   (try_end),

   (assign, reg0, ":active_patrols"),
   (assign, reg1, ":active_columns"),
   (assign, reg2, ":target_limit"),
   (assign, reg3, ":employer_faction"),
 ]),

("sod_black_army_apply_player_action",
 [
   (store_script_param_1, ":action"),
   (store_script_param_2, ":magnitude"),
   (val_max, ":magnitude", 1),
   (faction_get_slot, ":security_fund", "fac_sod_merc_guild1", slot_faction_black_army_security_fund),
   (faction_get_slot, ":contract_heat", "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
   (try_begin),
     (eq, ":action", sod_black_army_action_security_contract),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_army_security, 3),
     (val_add, ":security_fund", ":magnitude"),
     (val_add, ":contract_heat", 2),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild1", 1),
   (else_try),
     (eq, ":action", sod_black_army_action_hire_patrol),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_army_security, 4),
     (val_add, ":security_fund", ":magnitude"),
     (val_sub, ":contract_heat", 1),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild1", 2),
   (else_try),
     (eq, ":action", sod_black_army_action_attack_patrol),
     (val_sub, ":security_fund", ":magnitude"),
     (val_add, ":contract_heat", 5),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild1", -5),
   (else_try),
     (eq, ":action", sod_black_army_action_interdict_road_threats),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_army_security, 4),
     (val_add, ":security_fund", ":magnitude"),
     (val_add, ":contract_heat", 4),
     (faction_get_slot, ":slaver_heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
     (faction_get_slot, ":boar_pressure", "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure),
     (faction_get_slot, ":boar_intimidation", "fac_sod_merc_guild7", slot_faction_boar_intimidation),
     (faction_get_slot, ":horde_pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (store_div, ":relief", ":magnitude", 250),
     (val_clamp, ":relief", 1, 7),
     (val_sub, ":slaver_heat", ":relief"),
     (val_sub, ":boar_pressure", ":relief"),
     (val_sub, ":boar_intimidation", ":relief"),
     (val_sub, ":horde_pressure", ":relief"),
     (val_clamp, ":slaver_heat", 0, 101),
     (val_clamp, ":boar_pressure", 0, 101),
     (val_clamp, ":boar_intimidation", 0, 101),
     (val_clamp, ":horde_pressure", 0, 101),
     (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_heat, ":slaver_heat"),
     (faction_set_slot, "fac_sod_merc_guild7", slot_faction_boar_frontier_pressure, ":boar_pressure"),
     (faction_set_slot, "fac_sod_merc_guild7", slot_faction_boar_intimidation, ":boar_intimidation"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":horde_pressure"),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild1", 2),
   (try_end),
   (val_clamp, ":security_fund", 0, 2000),
   (val_clamp, ":contract_heat", 0, 101),
   (faction_set_slot, "fac_sod_merc_guild1", slot_faction_black_army_security_fund, ":security_fund"),
   (faction_set_slot, "fac_sod_merc_guild1", slot_faction_black_army_contract_heat, ":contract_heat"),
   (assign, reg0, ":security_fund"),
   (assign, reg1, ":contract_heat"),
 ]),

("sod_black_army_describe_status_to_s24",
 [
   (store_num_parties_of_template, reg21, "pt_black_army_patrol"),
   (store_num_parties_of_template, reg22, "pt_black_army_contract_column"),
   (store_add, reg23, reg21, reg22),
  (faction_get_slot, reg24, "fac_sod_merc_guild1", slot_faction_black_army_security_fund),
  (faction_get_slot, reg25, "fac_sod_merc_guild1", slot_faction_black_army_contract_heat),
  (store_relation, reg26, "fac_player_supporters_faction", "fac_sod_merc_guild1"),
  (try_begin),
    (eq, "$cheat_mode", 1),
    (str_store_string, s22, "@unsettled account"),
  (else_try),
    (str_store_string, s22, "@indifferent"),
  (try_end),
  (try_begin),
    (ge, reg26, 20),
    (str_store_string, s22, "@trusted"),
  (else_try),
    (ge, reg26, 5),
    (str_store_string, s22, "@friendly"),
  (else_try),
    (le, reg26, -20),
    (str_store_string, s22, "@hostile"),
  (else_try),
    (le, reg26, -5),
    (str_store_string, s22, "@wary"),
  (try_end),
   (assign, ":employer_faction", 0),
   (try_for_range, ":cur_faction", kingdoms_begin, kingdoms_end),
     (eq, ":employer_faction", 0),
     (faction_slot_eq, ":cur_faction", slot_faction_merc_pact, "fac_sod_merc_guild1"),
     (faction_slot_eq, ":cur_faction", slot_faction_state, sfs_active),
     (assign, ":employer_faction", ":cur_faction"),
   (try_end),
   (str_store_string, s21, "@independent road work"),
   (try_begin),
     (gt, ":employer_faction", 0),
     (str_store_faction_name_link, s21, ":employer_faction"),
   (try_end),
  (str_store_string, s24, "@^Black Army standing: road-security network with {reg21} patrols and {reg22} contract columns active ({reg23} total). Security fund {reg24}; contract heat {reg25}; current employer {s21}; your standing {s22} ({reg26}). The Black Army sells order, hunts road predators, and repairs profit where banditry made a hole."),
  (str_clear, s22),
 ]),
]
