# COST: moderate
SCRIPTS = [
("sod_slavers_prepare_market_deltas",
 [
   (store_current_day, ":cur_day"),
   (try_begin),
     (this_or_next|eq, "$g_sod_slaver_market_delta_initialized", 0),
     (neq, "$g_sod_slaver_market_delta_day", ":cur_day"),
     (assign, "$g_sod_slaver_market_delta_day", ":cur_day"),
     (assign, "$g_sod_slaver_market_demand_delta", 0),
     (assign, "$g_sod_slaver_market_supply_delta", 0),
     (assign, "$g_sod_slaver_market_delta_initialized", 1),
   (try_end),
 ]),

("sod_slavers_refresh_market_state_to_regs",
 [
   (call_script, "script_sod_slavers_prepare_market_deltas"),
   (assign, ":base_count", 0),
   (try_for_range, ":center_no", towns_begin, towns_end),
     (party_slot_ge, ":center_no", slot_town_slavers, 1),
     (val_add, ":base_count", 1),
   (try_end),

   (assign, ":active_web_parties", 0),
   (assign, ":prisoner_supply", 0),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (try_begin),
       (party_slot_eq, ":party_no", slot_party_sod_slaver_web_activity, 1),
       (val_add, ":active_web_parties", 1),
     (try_end),
     (store_faction_of_party, ":party_faction", ":party_no"),
     (try_begin),
       (this_or_next|eq, ":party_faction", "fac_sod_merc_guild6"),
       (party_slot_eq, ":party_no", slot_party_sod_slaver_web_activity, 1),
       (party_get_num_prisoners, ":num_prisoners", ":party_no"),
       (val_add, ":prisoner_supply", ":num_prisoners"),
     (try_end),
   (try_end),

   (faction_get_slot, ":heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (store_mul, ":supply", ":base_count", 8),
   (val_add, ":supply", ":active_web_parties"),
   (store_div, ":prisoner_factor", ":prisoner_supply", 3),
   (val_add, ":supply", ":prisoner_factor"),
   (val_clamp, ":supply", 0, 101),
   (val_add, ":supply", "$g_sod_slaver_market_supply_delta"),
   (val_clamp, ":supply", 0, 101),

   (store_mul, ":demand", ":base_count", 12),
   (val_add, ":demand", 20),
   (store_div, ":heat_demand", ":heat", 3),
   (val_add, ":demand", ":heat_demand"),
   (store_div, ":supply_drag", ":supply", 4),
   (val_sub, ":demand", ":supply_drag"),
   (val_clamp, ":demand", 5, 101),
   (val_add, ":demand", "$g_sod_slaver_market_demand_delta"),
   (val_clamp, ":demand", 0, 101),

   (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_bases, ":base_count"),
   (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_supply, ":supply"),
   (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_demand, ":demand"),
   (store_current_day, ":cur_day"),
   (assign, "$g_sod_slaver_market_cache_day", ":cur_day"),
   (assign, "$g_sod_slaver_market_cache_initialized", 1),
   (assign, "$g_sod_slaver_market_cache_dirty", 0),
   (assign, "$g_sod_slaver_market_active_web_parties", ":active_web_parties"),
   (assign, reg0, ":demand"),
   (assign, reg1, ":supply"),
   (assign, reg2, ":heat"),
   (assign, reg3, ":base_count"),
   (assign, reg4, ":active_web_parties"),
 ]),

("sod_slavers_update_market_state",
 [
   (store_current_day, ":cur_day"),
   (try_begin),
     (eq, "$g_sod_slaver_market_cache_initialized", 1),
     (eq, "$g_sod_slaver_market_cache_day", ":cur_day"),
     (eq, "$g_sod_slaver_market_cache_dirty", 0),
     (faction_get_slot, ":demand", "fac_sod_merc_guild6", slot_faction_slaver_market_demand),
     (faction_get_slot, ":supply", "fac_sod_merc_guild6", slot_faction_slaver_market_supply),
     (faction_get_slot, ":heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
     (faction_get_slot, ":base_count", "fac_sod_merc_guild6", slot_faction_slaver_market_bases),
     (assign, ":active_web_parties", "$g_sod_slaver_market_active_web_parties"),
   (else_try),
     (call_script, "script_sod_slavers_refresh_market_state_to_regs"),
     (assign, ":demand", reg0),
     (assign, ":supply", reg1),
     (assign, ":heat", reg2),
     (assign, ":base_count", reg3),
     (assign, ":active_web_parties", reg4),
   (try_end),
   (assign, reg0, ":demand"),
   (assign, reg1, ":supply"),
   (assign, reg2, ":heat"),
   (assign, reg3, ":base_count"),
   (assign, reg4, ":active_web_parties"),
 ]),

("sod_slavers_mark_market_dirty",
 [
   (assign, "$g_sod_slaver_market_cache_dirty", 1),
 ]),

("sod_slavers_mark_market_party_dirty",
 [
   (store_script_param_1, ":party_no"),
   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (party_slot_eq, ":party_no", slot_party_sod_slaver_web_activity, 1),
     (call_script, "script_sod_slavers_mark_market_dirty"),
   (try_end),
 ]),

("sod_slavers_apply_market_delta",
 [
   (store_script_param_1, ":demand_delta"),
   (store_script_param_2, ":supply_delta"),
   (store_script_param, ":heat_delta", 3),
   (call_script, "script_sod_slavers_update_market_state"),
   (call_script, "script_sod_slavers_prepare_market_deltas"),
   (faction_get_slot, ":demand", "fac_sod_merc_guild6", slot_faction_slaver_market_demand),
   (faction_get_slot, ":supply", "fac_sod_merc_guild6", slot_faction_slaver_market_supply),
   (faction_get_slot, ":heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (assign, ":old_demand", ":demand"),
   (assign, ":old_supply", ":supply"),
   (val_add, ":demand", ":demand_delta"),
   (val_add, ":supply", ":supply_delta"),
   (val_add, ":heat", ":heat_delta"),
   (val_clamp, ":demand", 0, 101),
   (val_clamp, ":supply", 0, 101),
   (val_clamp, ":heat", 0, 101),
   (store_sub, ":applied_demand_delta", ":demand", ":old_demand"),
   (store_sub, ":applied_supply_delta", ":supply", ":old_supply"),
   (val_add, "$g_sod_slaver_market_demand_delta", ":applied_demand_delta"),
   (val_add, "$g_sod_slaver_market_supply_delta", ":applied_supply_delta"),
   (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_demand, ":demand"),
   (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_supply, ":supply"),
   (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_heat, ":heat"),
   (store_current_day, ":cur_day"),
   (assign, "$g_sod_slaver_market_cache_day", ":cur_day"),
   (assign, "$g_sod_slaver_market_cache_dirty", 0),
   (assign, reg0, ":demand"),
   (assign, reg1, ":supply"),
   (assign, reg2, ":heat"),
 ]),

("sod_slavers_apply_player_action",
 [
   (store_script_param_1, ":action"),
   (store_script_param_2, ":magnitude"),
   (val_max, ":magnitude", 1),
   (call_script, "script_sod_slavers_update_market_state"),
   (faction_get_slot, ":demand", "fac_sod_merc_guild6", slot_faction_slaver_market_demand),
   (faction_get_slot, ":supply", "fac_sod_merc_guild6", slot_faction_slaver_market_supply),
   (faction_get_slot, ":heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (assign, ":base_demand", ":demand"),
   (assign, ":base_supply", ":supply"),
   (assign, ":base_heat", ":heat"),
  (try_begin),
    (eq, ":action", sod_slaver_action_trade_prisoners),
    (store_mul, ":supply_gain", ":magnitude", 2),
    (val_add, ":supply", ":supply_gain"),
    (val_add, ":demand", ":magnitude"),
    (val_add, ":heat", 1),
    (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", -1),
    (try_for_range, ":kingdom_no", native_kingdoms_begin, native_kingdoms_end),
      (neq, ":kingdom_no", "$players_kingdom"),
      (call_script, "script_sod_diplomacy_apply_memory", ":kingdom_no", sod_diplomacy_memory_slaver_cooperation, 1),
    (try_end),
    (try_begin),
      (main_party_has_troop, "trp_diego_companion"),
      (assign, "$g_sod_diego_warning_pending", 1),
      (troop_get_slot, ":diego_approval", "trp_diego_companion", slot_troop_companion_approval),
      (val_sub, ":diego_approval", 4),
      (val_clamp, ":diego_approval", 0, 101),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_approval, ":diego_approval"),
      (call_script, "script_sod_companion_get_approval_band_to_reg", "trp_diego_companion"),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_trust_tier, reg0),
      (display_message, "@Diego watches the prisoner trade in silence. Some chains are sold with cleaner words.", 0xCC6666),
    (try_end),
  (else_try),
    (eq, ":action", sod_slaver_action_escort_caravan),
    (store_mul, ":supply_gain", ":magnitude", 4),
    (val_add, ":supply", ":supply_gain"),
    (val_add, ":demand", ":magnitude"),
    (val_sub, ":heat", 1),
    (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", -1),
    (try_for_range, ":kingdom_no", native_kingdoms_begin, native_kingdoms_end),
      (neq, ":kingdom_no", "$players_kingdom"),
      (call_script, "script_sod_diplomacy_apply_memory", ":kingdom_no", sod_diplomacy_memory_slaver_cooperation, 1),
    (try_end),
    (try_begin),
      (main_party_has_troop, "trp_diego_companion"),
      (assign, "$g_sod_diego_warning_pending", 1),
      (troop_get_slot, ":diego_approval", "trp_diego_companion", slot_troop_companion_approval),
      (val_sub, ":diego_approval", 3),
      (val_clamp, ":diego_approval", 0, 101),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_approval, ":diego_approval"),
      (call_script, "script_sod_companion_get_approval_band_to_reg", "trp_diego_companion"),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_trust_tier, reg0),
      (display_message, "@Diego marks every Slaver wagon you escort. He says no road is neutral when it carries cages.", 0xCC6666),
    (try_end),
  (else_try),
    (eq, ":action", sod_slaver_action_return_runaways),
    (store_mul, ":supply_gain", ":magnitude", 5),
    (val_add, ":supply", ":supply_gain"),
    (val_sub, ":heat", 2),
    (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", -1),
    (try_for_range, ":kingdom_no", native_kingdoms_begin, native_kingdoms_end),
      (neq, ":kingdom_no", "$players_kingdom"),
      (call_script, "script_sod_diplomacy_apply_memory", ":kingdom_no", sod_diplomacy_memory_slaver_cooperation, 1),
    (try_end),
    (try_begin),
      (main_party_has_troop, "trp_diego_companion"),
      (assign, "$g_sod_diego_warning_pending", 1),
      (troop_get_slot, ":diego_approval", "trp_diego_companion", slot_troop_companion_approval),
      (val_sub, ":diego_approval", 8),
      (val_clamp, ":diego_approval", 0, 101),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_approval, ":diego_approval"),
      (call_script, "script_sod_companion_get_approval_band_to_reg", "trp_diego_companion"),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_trust_tier, reg0),
      (display_message, "@Diego's jaw tightens as the runaways are sent back. This is a line he will remember.", 0xCC3333),
    (try_end),
  (else_try),
    (eq, ":action", sod_slaver_action_free_runaways),
    (call_script, "script_sod_company_accounts_apply_faith_conduct", sod_companion_action_free_captives, ":magnitude"),
    (store_mul, ":heat_gain", ":magnitude", 6),
    (val_add, ":heat", ":heat_gain"),
    (val_sub, ":supply", ":magnitude"),
    (val_add, ":demand", 2),
    (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", 1),
    (try_for_range, ":kingdom_no", native_kingdoms_begin, native_kingdoms_end),
      (neq, ":kingdom_no", "$players_kingdom"),
      (call_script, "script_sod_diplomacy_apply_memory", ":kingdom_no", sod_diplomacy_memory_anti_slaver_action, 1),
    (try_end),
    (try_begin),
      (main_party_has_troop, "trp_diego_companion"),
      (val_add, "$g_sod_diego_anti_slaver_proof", ":magnitude"),
      (troop_get_slot, ":diego_approval", "trp_diego_companion", slot_troop_companion_approval),
      (val_add, ":diego_approval", 3),
      (val_clamp, ":diego_approval", 0, 101),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_approval, ":diego_approval"),
      (call_script, "script_sod_companion_get_approval_band_to_reg", "trp_diego_companion"),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_trust_tier, reg0),
      (try_begin),
        (eq, "$g_sod_diego_warning_pending", 2),
        (ge, "$g_sod_diego_anti_slaver_proof", 5),
        (assign, "$g_sod_diego_warning_pending", 3),
      (try_end),
      (try_begin),
        (ge, ":diego_approval", 45),
        (display_message, "@Diego helps the runaways scatter before the road can betray them. Not every victory needs a banner.", 0x99CCFF),
        (call_script, "script_change_player_relation_with_faction", "fac_commoners", 1),
        (try_begin),
          (party_get_free_companions_capacity, ":free_capacity", "p_main_party"),
          (gt, ":free_capacity", 0),
          (store_random_in_range, ":chainbreaker_roll", 0, 100),
          (store_mul, ":chainbreaker_chance", ":magnitude", 8),
          (val_min, ":chainbreaker_chance", 32),
          (try_begin),
            (troop_slot_eq, "trp_diego_companion", slot_troop_companion_role, sod_companion_role_spymaster),
            (val_add, ":chainbreaker_chance", 8),
            (val_min, ":chainbreaker_chance", 40),
          (try_end),
          (lt, ":chainbreaker_roll", ":chainbreaker_chance"),
          (party_add_members, "p_main_party", "trp_refugee", 1),
          (display_message, "@One rescued refugee follows Diego's road-signs back to your column.", 0x99CCFF),
        (try_end),
      (else_try),
        (display_message, "@Diego helps cut the road open, but keeps the freed moving away from your banner.", 0xCC9966),
      (try_end),
    (try_end),
   (else_try),
     (eq, ":action", sod_slaver_action_captivity),
     (val_add, ":supply", ":magnitude"),
     (val_add, ":heat", 2),
  (else_try),
    (eq, ":action", sod_slaver_action_hostile),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_free_captives, 2),
    (call_script, "script_sod_company_accounts_apply_faith_conduct", sod_companion_action_free_captives, 2),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 1),
    (store_mul, ":heat_gain", ":magnitude", 4),
    (val_add, ":heat", ":heat_gain"),
    (val_sub, ":supply", ":magnitude"),
    (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", 1),
    (try_for_range, ":kingdom_no", native_kingdoms_begin, native_kingdoms_end),
      (neq, ":kingdom_no", "$players_kingdom"),
      (call_script, "script_sod_diplomacy_apply_memory", ":kingdom_no", sod_diplomacy_memory_anti_slaver_action, 1),
    (try_end),
    (try_begin),
      (main_party_has_troop, "trp_diego_companion"),
      (val_add, "$g_sod_diego_anti_slaver_proof", ":magnitude"),
      (troop_get_slot, ":diego_approval", "trp_diego_companion", slot_troop_companion_approval),
      (val_add, ":diego_approval", 4),
      (val_clamp, ":diego_approval", 0, 101),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_approval, ":diego_approval"),
      (call_script, "script_sod_companion_get_approval_band_to_reg", "trp_diego_companion"),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_trust_tier, reg0),
      (try_begin),
        (eq, "$g_sod_diego_warning_pending", 2),
        (ge, "$g_sod_diego_anti_slaver_proof", 5),
        (assign, "$g_sod_diego_warning_pending", 3),
      (try_end),
      (try_begin),
        (ge, ":diego_approval", 45),
        (display_message, "@Diego walks the broken Slaver line and checks the cages before the loot.", 0x99CCFF),
        (call_script, "script_change_player_relation_with_faction", "fac_commoners", 1),
        (try_begin),
          (party_get_free_companions_capacity, ":free_capacity", "p_main_party"),
          (gt, ":free_capacity", 0),
          (store_random_in_range, ":chainbreaker_roll", 0, 100),
          (store_mul, ":chainbreaker_chance", ":magnitude", 6),
          (val_min, ":chainbreaker_chance", 24),
          (try_begin),
            (troop_slot_eq, "trp_diego_companion", slot_troop_companion_role, sod_companion_role_spymaster),
            (val_add, ":chainbreaker_chance", 8),
            (val_min, ":chainbreaker_chance", 32),
          (try_end),
          (lt, ":chainbreaker_roll", ":chainbreaker_chance"),
          (party_add_members, "p_main_party", "trp_refugee", 1),
          (display_message, "@A freed captive joins the march after Diego cuts the last knot from their wrists.", 0x99CCFF),
        (try_end),
      (else_try),
        (display_message, "@Diego opens cages and says little. Trust will take more than one broken lock.", 0xCC9966),
      (try_end),
    (try_end),
  (else_try),
    (eq, ":action", sod_slaver_action_buy_slaves),
    (call_script, "script_sod_company_accounts_apply_faith_conduct", sod_companion_action_buy_slaves, ":magnitude"),
    (store_mul, ":supply_loss", ":magnitude", 2),
    (val_sub, ":supply", ":supply_loss"),
    (store_div, ":heat_gain", ":magnitude", 2),
    (val_add, ":heat", ":heat_gain"),
    (val_add, ":demand", 1),
    (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild4", -1),
    (try_for_range, ":kingdom_no", native_kingdoms_begin, native_kingdoms_end),
      (neq, ":kingdom_no", "$players_kingdom"),
      (call_script, "script_sod_diplomacy_apply_memory", ":kingdom_no", sod_diplomacy_memory_slaver_cooperation, 1),
    (try_end),
    (try_begin),
      (main_party_has_troop, "trp_diego_companion"),
      (assign, "$g_sod_diego_warning_pending", 1),
      (troop_get_slot, ":diego_approval", "trp_diego_companion", slot_troop_companion_approval),
      (val_sub, ":diego_approval", 6),
      (val_clamp, ":diego_approval", 0, 101),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_approval, ":diego_approval"),
      (call_script, "script_sod_companion_get_approval_band_to_reg", "trp_diego_companion"),
      (troop_set_slot, "trp_diego_companion", slot_troop_companion_trust_tier, reg0),
      (display_message, "@Diego says buying chains still teaches the market to make more of them.", 0xCC3333),
    (try_end),
   (else_try),
     (eq, ":action", sod_slaver_action_carry_slaves),
     (call_script, "script_sod_company_accounts_apply_faith_conduct", sod_companion_action_carry_slaves, ":magnitude"),
     (val_add, ":heat", ":magnitude"),
     (store_div, ":demand_gain", ":magnitude", 2),
     (val_add, ":demand", ":demand_gain"),
     (try_begin),
       (main_party_has_troop, "trp_diego_companion"),
       (assign, "$g_sod_diego_warning_pending", 1),
       (troop_get_slot, ":diego_approval", "trp_diego_companion", slot_troop_companion_approval),
       (val_sub, ":diego_approval", 2),
       (val_clamp, ":diego_approval", 0, 101),
       (troop_set_slot, "trp_diego_companion", slot_troop_companion_approval, ":diego_approval"),
       (call_script, "script_sod_companion_get_approval_band_to_reg", "trp_diego_companion"),
       (troop_set_slot, "trp_diego_companion", slot_troop_companion_trust_tier, reg0),
       (display_message, "@Diego keeps away from the slave line. He knows too well what counted bodies sound like.", 0xCC6666),
     (try_end),
   (try_end),
   (val_clamp, ":demand", 0, 101),
   (val_clamp, ":supply", 0, 101),
   (val_clamp, ":heat", 0, 101),
   (store_sub, ":demand_delta", ":demand", ":base_demand"),
   (store_sub, ":supply_delta", ":supply", ":base_supply"),
   (store_sub, ":heat_delta", ":heat", ":base_heat"),
   (call_script, "script_sod_slavers_apply_market_delta", ":demand_delta", ":supply_delta", ":heat_delta"),
 ]),

("sod_slavers_spawn_world_activity",
 [
   (call_script, "script_sod_slavers_update_market_state"),
   (assign, ":active_web_parties", reg4),

   (faction_get_slot, ":base_count", "fac_sod_merc_guild6", slot_faction_slaver_market_bases),
   (faction_get_slot, ":heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (faction_get_slot, ":demand", "fac_sod_merc_guild6", slot_faction_slaver_market_demand),
   (try_begin),
     (gt, ":base_count", 0),
     (store_div, ":heat_cap", ":heat", 25),
     (store_div, ":base_cap", ":base_count", 4),
     (store_add, ":party_cap", 1, ":heat_cap"),
     (val_add, ":party_cap", ":base_cap"),
     (val_clamp, ":party_cap", 1, 5),
     (lt, ":active_web_parties", ":party_cap"),

     (store_current_day, ":cur_day"),
     (faction_get_slot, ":last_spawn_day", "fac_sod_merc_guild6", slot_faction_slaver_market_last_spawn_day),
     (store_sub, ":days_since_spawn", ":cur_day", ":last_spawn_day"),
     (this_or_next|ge, ":days_since_spawn", 5),
     (lt, ":last_spawn_day", 1),

     (store_random_in_range, ":origin_index", 0, ":base_count"),
     (store_random_in_range, ":destination_index", 0, ":base_count"),
     (assign, ":origin", -1),
     (assign, ":destination", -1),
     (assign, ":base_cursor", 0),
     (try_for_range, ":center_no", towns_begin, towns_end),
       (party_slot_ge, ":center_no", slot_town_slavers, 1),
       (try_begin),
         (eq, ":base_cursor", ":origin_index"),
         (assign, ":origin", ":center_no"),
       (try_end),
       (try_begin),
         (eq, ":base_cursor", ":destination_index"),
         (assign, ":destination", ":center_no"),
       (try_end),
       (val_add, ":base_cursor", 1),
     (try_end),
     (ge, ":origin", 0),
     (ge, ":destination", 0),
     (try_begin),
       (eq, ":destination", ":origin"),
       (try_for_range, ":center_no", towns_begin, towns_end),
         (party_slot_ge, ":center_no", slot_town_slavers, 1),
         (neq, ":center_no", ":origin"),
         (assign, ":destination", ":center_no"),
       (try_end),
     (try_end),

     (set_spawn_radius, 2),
     (assign, ":web_party", -1),
     (assign, ":spawned_recovery_party", 0),
     (try_begin),
       (ge, ":heat", 50),
       (spawn_around_party, ":origin", "pt_slaves_with_jotnar_clansmen"),
       (assign, ":web_party", reg0),
       (str_store_string, s60, "@Slaver Recovery Party"),
       (assign, ":spawned_recovery_party", 1),
     (else_try),
       (spawn_around_party, ":origin", "pt_slavers_caravan"),
       (assign, ":web_party", reg0),
       (str_store_string, s60, "@Slave Transport"),
     (try_end),
     (gt, ":web_party", 0),
     (party_is_active, ":web_party"),
     (party_set_name, ":web_party", s60),
    (party_set_faction, ":web_party", "fac_sod_merc_guild6"),
     (party_set_slot, ":web_party", slot_party_orginal_faction, "fac_sod_merc_guild6"),
     (party_set_slot, ":web_party", slot_party_starting_base, "p_sod_merc_guild_6"),
     (party_set_slot, ":web_party", slot_party_type, spt_ai_mercenaries),
     (party_set_slot, ":web_party", slot_party_boss, -1),
     (party_set_slot, ":web_party", slot_party_sod_slaver_web_activity, 1),
     (party_set_slot, ":web_party", slot_party_sod_slaver_origin, ":origin"),
     (party_set_slot, ":web_party", slot_party_sod_slaver_destination, ":destination"),
     (store_add, ":contract_day", ":cur_day", 35),
     (party_set_slot, ":web_party", slot_party_merc_contract, ":contract_day"),
    (party_set_ai_behavior, ":web_party", ai_bhvr_travel_to_party),
    (party_set_ai_object, ":web_party", ":destination"),
    (party_set_flags, ":web_party", pf_default_behavior, 0),
    (assign, ":report_destination_kind", sod_report_subject_none),
    (try_begin),
      (is_between, ":destination", centers_begin, centers_end),
      (assign, ":report_destination_kind", sod_report_subject_center),
    (try_end),
    (call_script, "script_sod_report_record_event", sod_report_category_captives, sod_report_severity_notable, sod_report_subject_party, ":web_party", ":report_destination_kind", ":destination", 1, sod_report_reason_slaver_market),
    (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_last_spawn_day, ":cur_day"),
     (call_script, "script_sod_slavers_apply_market_delta", 0, 0, -3),
     (call_script, "script_sod_slavers_mark_market_dirty"),
   (try_end),
 ]),

("sod_slavers_process_world_activity",
 [
   (store_num_parties_of_template, ":active_caravans", "pt_slavers_caravan"),
   (store_num_parties_of_template, ":active_recovery_parties", "pt_slaves_with_jotnar_clansmen"),
   (store_add, ":active_web_parties", ":active_caravans", ":active_recovery_parties"),
   (assign, ":arrivals", 0),
   (try_begin),
     (gt, ":active_web_parties", 0),
     (try_for_parties, ":party_no"),
       (party_is_active, ":party_no"),
       (party_slot_eq, ":party_no", slot_party_sod_slaver_web_activity, 1),
       (party_set_faction, ":party_no", "fac_sod_merc_guild6"),
       (party_set_slot, ":party_no", slot_party_orginal_faction, "fac_sod_merc_guild6"),
       (party_set_slot, ":party_no", slot_party_starting_base, "p_sod_merc_guild_6"),
       (party_set_slot, ":party_no", slot_party_type, spt_ai_mercenaries),
       (party_set_slot, ":party_no", slot_party_boss, -1),
       (party_get_slot, ":destination", ":party_no", slot_party_sod_slaver_destination),
       (ge, ":destination", 0),
       (store_distance_to_party_from_party, ":distance", ":party_no", ":destination"),
       (lt, ":distance", 4),
       (party_get_template_id, ":template", ":party_no"),
       (try_begin),
         (eq, ":template", "pt_slavers_caravan"),
         (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_escort_caravan, 2),
         (val_add, ":arrivals", 1),
       (else_try),
         (eq, ":template", "pt_slaves_with_jotnar_clansmen"),
         (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_return_runaways, 1),
         (call_script, "script_sod_slavers_apply_market_delta", 0, 0, -4),
         (val_add, ":arrivals", 1),
       (try_end),
       (neq, ":party_no", "p_main_party"),
       (call_script, "script_sod_slavers_mark_market_party_dirty", ":party_no"),
       (remove_party, ":party_no"),
     (try_end),
   (try_end),
   (try_begin),
     (gt, ":arrivals", 0),
     (call_script, "script_sod_report_record_event", sod_report_category_captives, sod_report_severity_notable, sod_report_subject_none, -1, sod_report_subject_none, -1, ":arrivals", sod_report_reason_slaver_market),
   (try_end),
   (try_begin),
     (gt, ":arrivals", 0),
     (call_script, "script_sod_slavers_mark_market_dirty"),
   (try_end),
   (call_script, "script_sod_slavers_update_market_state"),
 ]),

("sod_slavers_process_player_slave_burden",
 [
   (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
   (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
   (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
   (try_begin),
     (gt, ":slave_count", 0),
     (store_div, ":pressure", ":slave_count", 5),
     (val_add, ":pressure", 1),
     (val_clamp, ":pressure", 1, 11),
     (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_carry_slaves, ":pressure"),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_carry_slaves, ":pressure"),
     (try_begin),
       (ge, ":slave_count", 10),
       (store_current_day, ":cur_day"),
       (store_sub, ":days_since_honor_loss", ":cur_day", "$g_sod_slaver_slave_burden_last_honor_day"),
       (this_or_next|ge, ":days_since_honor_loss", 7),
       (lt, "$g_sod_slaver_slave_burden_last_honor_day", 1),
       (call_script, "script_change_player_honor", -1),
       (assign, "$g_sod_slaver_slave_burden_last_honor_day", ":cur_day"),
       (display_message, "@Keeping slaves in your party damages your honor and draws black market attention.", 0x8B0000),
     (else_try),
       (ge, ":slave_count", 5),
       (store_random_in_range, ":warning_roll", 0, 100),
       (lt, ":warning_roll", 15),
       (display_message, "@Your slaves draw notice from informants and Slaver market brokers.", 0x8B0000),
     (try_end),
   (try_end),
 ]),

("sod_slavers_store_slave_purchase_quote",
 [
   (call_script, "script_sod_slavers_update_market_state"),
   (faction_get_slot, ":demand", "fac_sod_merc_guild6", slot_faction_slaver_market_demand),
   (faction_get_slot, ":supply", "fac_sod_merc_guild6", slot_faction_slaver_market_supply),
   (faction_get_slot, ":heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (faction_get_slot, ":bases", "fac_sod_merc_guild6", slot_faction_slaver_market_bases),
   (store_div, ":available", ":supply", 5),
   (store_mul, ":base_stock", ":bases", 2),
   (val_add, ":available", ":base_stock"),
   (val_clamp, ":available", 1, 21),
   (party_get_free_companions_capacity, ":free_capacity", "p_main_party"),
   (val_min, ":available", ":free_capacity"),
   (assign, ":batch", ":available"),
   (val_min, ":batch", 5),
   (assign, ":unit_price", 35),
   (store_div, ":demand_price", ":demand", 2),
   (val_add, ":unit_price", ":demand_price"),
   (store_div, ":heat_price", ":heat", 3),
   (val_add, ":unit_price", ":heat_price"),
   (store_div, ":supply_discount", ":supply", 4),
   (val_sub, ":unit_price", ":supply_discount"),
   (val_clamp, ":unit_price", 20, 121),
   (store_mul, ":total_price", ":unit_price", ":batch"),
   (assign, reg0, ":available"),
   (assign, reg1, ":unit_price"),
   (assign, reg2, ":batch"),
   (assign, reg3, ":total_price"),
 ]),

("sod_slavers_buy_slaves_for_player",
 [
   (store_script_param_1, ":requested"),
   (call_script, "script_sod_slavers_store_slave_purchase_quote"),
   (assign, ":available", reg0),
   (assign, ":unit_price", reg1),
   (assign, ":amount", ":requested"),
   (val_min, ":amount", ":available"),
   (val_min, ":amount", 5),
   (assign, reg0, 0),
   (try_begin),
     (gt, ":amount", 0),
     (store_mul, ":total_price", ":unit_price", ":amount"),
     (store_troop_gold, ":player_gold", "trp_player"),
     (ge, ":player_gold", ":total_price"),
     (call_script, "script_sod_player_charge_gold", ":total_price"),
     (party_add_members, "p_main_party", "trp_slave", ":amount"),
     (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_buy_slaves, ":amount"),
     (assign, reg0, 1),
     (assign, reg1, ":amount"),
     (assign, reg2, ":total_price"),
   (try_end),
 ]),

("sod_slavers_describe_status_to_s20",
 [
   (call_script, "script_sod_slavers_update_market_state"),
   (faction_get_slot, reg20, "fac_sod_merc_guild6", slot_faction_slaver_market_demand),
   (faction_get_slot, reg21, "fac_sod_merc_guild6", slot_faction_slaver_market_supply),
   (faction_get_slot, reg22, "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (faction_get_slot, reg23, "fac_sod_merc_guild6", slot_faction_slaver_market_bases),
   (assign, reg24, reg4),
   (store_relation, reg25, "fac_player_supporters_faction", "fac_sod_merc_guild6"),
   (str_store_string, s21, "@unmarked by the market"),
   (try_begin),
     (ge, reg25, 20),
     (str_store_string, s21, "@trusted"),
   (else_try),
     (ge, reg25, 5),
     (str_store_string, s21, "@friendly"),
   (else_try),
     (le, reg25, -20),
     (str_store_string, s21, "@hostile"),
   (else_try),
     (le, reg25, -5),
     (str_store_string, s21, "@wary"),
   (try_end),
   (try_begin),
     (ge, reg22, 65),
     (str_store_string, s20, "@^Black market: {reg23} bases, demand {reg20}, supply {reg21}, heat {reg22}, transports {reg24}. Recovery parties are active. Standing: {s21} ({reg25})."),
   (else_try),
     (ge, reg20, 60),
     (str_store_string, s20, "@^Black market web: {reg23} bases, demand {reg20}, supply {reg21}, heat {reg22}, active transports {reg24}. Demand is high; captives and guarded transports are profitable. Your standing: {s21} ({reg25})."),
   (else_try),
     (str_store_string, s20, "@^Black market web: {reg23} bases, demand {reg20}, supply {reg21}, heat {reg22}, active transports {reg24}. The trade is present but not currently surging. Your standing: {s21} ({reg25})."),
   (try_end),
   (str_clear, s21),
 ]),
]
