# COST: medium
SCRIPTS = [
("sod_merc_market_refresh_kingdom_demands",
 [
   (store_current_day, ":cur_day"),

   (try_for_range, ":faction_no", native_kingdoms_begin, native_kingdoms_end),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_active_support_cache, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_population_shortage, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_health_pressure, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_food_pressure, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_outbreak_pressure, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_lord_wealth_score, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_lord_wealth_total_cache, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_lord_wealth_count_cache, 0),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_ruler_wealth_cache, 0),
     (try_for_range, ":guild_faction", guilds_begin, guilds_end),
       (store_sub, ":guild_offset", ":guild_faction", guilds_begin),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_service_days_cache_begin, ":guild_offset"),
       (faction_set_slot, ":faction_no", ":cache_slot", 0),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_value_cache_begin, ":guild_offset"),
       (faction_set_slot, ":faction_no", ":cache_slot", 0),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_loss_cache_begin, ":guild_offset"),
       (faction_set_slot, ":faction_no", ":cache_slot", 0),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_count_cache_begin, ":guild_offset"),
       (faction_set_slot, ":faction_no", ":cache_slot", 0),
     (try_end),
   (try_end),

   (try_for_parties, ":cur_party"),
     (party_is_active, ":cur_party"),
     (store_faction_of_party, ":party_faction", ":cur_party"),
     (try_begin),
       (is_between, ":party_faction", native_kingdoms_begin, native_kingdoms_end),
       (faction_slot_eq, ":party_faction", slot_faction_state, sfs_active),
       (this_or_next|party_slot_eq, ":cur_party", slot_party_type, spt_ai_mercenaries),
       (party_slot_eq, ":cur_party", slot_party_type, spt_mercenary_lord_party),
       (faction_get_slot, ":active_merc_support", ":party_faction", slot_faction_sod_merc_active_support_cache),
       (val_add, ":active_merc_support", 1),
       (faction_set_slot, ":party_faction", slot_faction_sod_merc_active_support_cache, ":active_merc_support"),
     (try_end),

     (try_begin),
       (party_is_active, ":cur_party"),
       (party_get_slot, ":party_guild", ":cur_party", slot_party_sod_merc_contract_guild),
       (is_between, ":party_guild", guilds_begin, guilds_end),
       (party_get_slot, ":employer_faction", ":cur_party", slot_party_sod_merc_contract_employer),
       (is_between, ":employer_faction", native_kingdoms_begin, native_kingdoms_end),
       (faction_slot_eq, ":employer_faction", slot_faction_state, sfs_active),
       (party_get_slot, ":contract_value", ":cur_party", slot_party_sod_merc_contract_value),
       (party_get_slot, ":loss_score", ":cur_party", slot_party_sod_merc_contract_loss_score),
       (party_get_slot, ":start_day", ":cur_party", slot_party_sod_merc_contract_start_day),
       (val_max, ":contract_value", 0),
       (val_max, ":loss_score", 0),
       (val_max, ":start_day", 0),
       (store_sub, ":service_days", ":cur_day", ":start_day"),
       (val_max, ":service_days", 0),
       (store_sub, ":guild_offset", ":party_guild", guilds_begin),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_service_days_cache_begin, ":guild_offset"),
       (faction_get_slot, ":cached_service_days", ":employer_faction", ":cache_slot"),
       (val_add, ":cached_service_days", ":service_days"),
       (faction_set_slot, ":employer_faction", ":cache_slot", ":cached_service_days"),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_value_cache_begin, ":guild_offset"),
       (faction_get_slot, ":cached_contract_value", ":employer_faction", ":cache_slot"),
       (val_add, ":cached_contract_value", ":contract_value"),
       (faction_set_slot, ":employer_faction", ":cache_slot", ":cached_contract_value"),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_loss_cache_begin, ":guild_offset"),
       (faction_get_slot, ":cached_contract_losses", ":employer_faction", ":cache_slot"),
       (val_add, ":cached_contract_losses", ":loss_score"),
       (faction_set_slot, ":employer_faction", ":cache_slot", ":cached_contract_losses"),
       (store_add, ":cache_slot", slot_faction_sod_merc_kingdom_guild_count_cache_begin, ":guild_offset"),
       (faction_get_slot, ":cached_active_contracts", ":employer_faction", ":cache_slot"),
       (val_add, ":cached_active_contracts", 1),
       (faction_set_slot, ":employer_faction", ":cache_slot", ":cached_active_contracts"),
     (try_end),
   (try_end),

   (try_for_range, ":kingdom_hero", kingdom_heroes_begin, kingdom_heroes_end),
     (store_troop_faction, ":hero_faction", ":kingdom_hero"),
     (is_between, ":hero_faction", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":hero_faction", slot_faction_state, sfs_active),
     (troop_get_slot, ":hero_wealth", ":kingdom_hero", slot_troop_wealth),
     (val_max, ":hero_wealth", 0),
     (faction_get_slot, ":lord_wealth_total", ":hero_faction", slot_faction_sod_merc_lord_wealth_total_cache),
     (val_add, ":lord_wealth_total", ":hero_wealth"),
     (faction_set_slot, ":hero_faction", slot_faction_sod_merc_lord_wealth_total_cache, ":lord_wealth_total"),
     (faction_get_slot, ":lord_wealth_count", ":hero_faction", slot_faction_sod_merc_lord_wealth_count_cache),
     (val_add, ":lord_wealth_count", 1),
     (faction_set_slot, ":hero_faction", slot_faction_sod_merc_lord_wealth_count_cache, ":lord_wealth_count"),
     (try_begin),
       (faction_slot_eq, ":hero_faction", slot_faction_leader, ":kingdom_hero"),
       (faction_set_slot, ":hero_faction", slot_faction_sod_merc_ruler_wealth_cache, ":hero_wealth"),
     (try_end),
   (try_end),

   (try_for_range, ":center_no", centers_begin, centers_end),
     (store_faction_of_party, ":center_faction", ":center_no"),
     (is_between, ":center_faction", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":center_faction", slot_faction_state, sfs_active),
     (call_script, "script_sod_merc_market_get_center_settlement_pressure", ":center_no"),
     (assign, ":center_shortage", reg0),
     (assign, ":center_health_pressure", reg1),
     (assign, ":center_food_pressure", reg2),
     (assign, ":center_outbreak_pressure", reg3),
     (faction_get_slot, ":population_shortage", ":center_faction", slot_faction_sod_merc_population_shortage),
     (val_add, ":population_shortage", ":center_shortage"),
     (val_clamp, ":population_shortage", 0, 41),
     (faction_set_slot, ":center_faction", slot_faction_sod_merc_population_shortage, ":population_shortage"),
     (faction_get_slot, ":health_pressure", ":center_faction", slot_faction_sod_merc_health_pressure),
     (val_add, ":health_pressure", ":center_health_pressure"),
     (val_clamp, ":health_pressure", 0, 41),
     (faction_set_slot, ":center_faction", slot_faction_sod_merc_health_pressure, ":health_pressure"),
     (faction_get_slot, ":food_pressure", ":center_faction", slot_faction_sod_merc_food_pressure),
     (val_add, ":food_pressure", ":center_food_pressure"),
     (val_clamp, ":food_pressure", 0, 41),
     (faction_set_slot, ":center_faction", slot_faction_sod_merc_food_pressure, ":food_pressure"),
     (faction_get_slot, ":outbreak_pressure", ":center_faction", slot_faction_sod_merc_outbreak_pressure),
     (val_add, ":outbreak_pressure", ":center_outbreak_pressure"),
     (val_clamp, ":outbreak_pressure", 0, 31),
     (faction_set_slot, ":center_faction", slot_faction_sod_merc_outbreak_pressure, ":outbreak_pressure"),
   (try_end),

   (call_script, "script_sod_merc_market_prepare_village_patrol_cache"),

   (try_for_range, ":faction_no", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
     (faction_get_slot, ":lord_wealth_total", ":faction_no", slot_faction_sod_merc_lord_wealth_total_cache),
     (faction_get_slot, ":lord_wealth_count", ":faction_no", slot_faction_sod_merc_lord_wealth_count_cache),
     (faction_get_slot, ":ruler_wealth", ":faction_no", slot_faction_sod_merc_ruler_wealth_cache),
     (val_max, ":lord_wealth_total", 0),
     (val_max, ":lord_wealth_count", 0),
     (val_max, ":ruler_wealth", 0),
     (assign, ":average_lord_wealth", 0),
     (try_begin),
       (gt, ":lord_wealth_count", 0),
       (store_div, ":average_lord_wealth", ":lord_wealth_total", ":lord_wealth_count"),
     (try_end),
     (store_div, ":lord_wealth_score", ":average_lord_wealth", 150),
     (store_div, ":ruler_wealth_score", ":ruler_wealth", 300),
     (val_add, ":lord_wealth_score", ":ruler_wealth_score"),
     (val_clamp, ":lord_wealth_score", 0, 61),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_lord_wealth_score, ":lord_wealth_score"),
   (try_end),

   (try_for_range, ":faction_no", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
     (call_script, "script_sod_merc_market_calculate_kingdom_demand", ":faction_no", 1, 1, 1, 1, 1),
   (try_end),
 ]),
]
