# COST: O(active laws)
SCRIPTS = [
("sod_get_realm_military_centralization_profile",
  [
    (store_script_param, ":faction_no", 1),

    (assign, ":centralization", 0),
    (assign, ":militarization", 0),
    (assign, ":ruler_modifier", 0),
    (assign, ":vassal_modifier", 0),
    (assign, ":noble_happiness", 0),
    (assign, ":legitimacy", 0),
    (assign, ":unrest", 0),

    (try_begin),
      (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
      (call_script, "script_sod_law_recalculate_faction_law_modifiers", ":faction_no"),
      (faction_get_slot, ":centralization", ":faction_no", slot_faction_law_centralization),
      (faction_get_slot, ":militarization", ":faction_no", slot_faction_law_militarization),
      (faction_get_slot, ":ruler_modifier", ":faction_no", slot_faction_law_ruler_party_size_modifier),
      (faction_get_slot, ":vassal_modifier", ":faction_no", slot_faction_law_lord_party_size_modifier),
      (faction_get_slot, ":noble_happiness", ":faction_no", slot_faction_law_noble_happiness),
      (faction_get_slot, ":legitimacy", ":faction_no", slot_faction_law_legitimacy),
      (faction_get_slot, ":unrest", ":faction_no", slot_faction_law_unrest),
    (try_end),

    (val_clamp, ":centralization", -40, 61),
    (val_clamp, ":militarization", 0, 81),
    (val_clamp, ":ruler_modifier", -50, 101),
    (val_clamp, ":vassal_modifier", -50, 101),
    (val_clamp, ":noble_happiness", -100, 101),
    (val_clamp, ":legitimacy", -100, 101),
    (val_clamp, ":unrest", 0, 101),

    (assign, ":ruler_centralization_modifier", ":centralization"),
    (store_div, ":ruler_militarization_bonus", ":militarization", 2),
    (val_add, ":ruler_centralization_modifier", ":ruler_militarization_bonus"),
    (store_div, ":ruler_legitimacy_bonus", ":legitimacy", 5),
    (val_add, ":ruler_centralization_modifier", ":ruler_legitimacy_bonus"),
    (store_div, ":ruler_unrest_drag", ":unrest", 3),
    (val_sub, ":ruler_centralization_modifier", ":ruler_unrest_drag"),
    (val_add, ":ruler_centralization_modifier", ":ruler_modifier"),
    (val_clamp, ":ruler_centralization_modifier", -40, 101),

    (store_sub, ":vassal_centralization_modifier", 0, ":centralization"),
    (store_div, ":vassal_militarization_bonus", ":militarization", 2),
    (val_add, ":vassal_centralization_modifier", ":vassal_militarization_bonus"),
    (store_div, ":vassal_noble_bonus", ":noble_happiness", 4),
    (val_add, ":vassal_centralization_modifier", ":vassal_noble_bonus"),
    (store_div, ":vassal_unrest_drag", ":unrest", 4),
    (val_sub, ":vassal_centralization_modifier", ":vassal_unrest_drag"),
    (val_add, ":vassal_centralization_modifier", ":vassal_modifier"),
    (val_clamp, ":vassal_centralization_modifier", -50, 101),

    (assign, reg0, ":centralization"),
    (assign, reg1, ":militarization"),
    (assign, reg2, ":ruler_centralization_modifier"),
    (assign, reg3, ":vassal_centralization_modifier"),
    (assign, reg4, ":noble_happiness"),
    (assign, reg5, ":unrest"),
    (assign, reg6, ":ruler_modifier"),
    (assign, reg7, ":vassal_modifier"),
    (assign, reg8, ":legitimacy"),
  ]),
]
