# COST: low
SCRIPTS = [
("sod_merc_market_generate_bid",
 [
   (store_script_param_1, ":kingdom_faction"),
   (store_script_param_2, ":guild_faction"),
   (store_script_param, ":demand_type", 3),
   (store_script_param, ":use_cached_contract_totals", 4),

   (assign, ":bid_value", 0),
   (assign, ":bid_score", -1000),
   (assign, ":company_size", 0),
   (assign, ":term_days", 30),
   (assign, ":refusal_reason", sod_merc_refusal_none),
   (assign, ":role_fit_score", 0),

   (try_begin),
     (is_between, ":kingdom_faction", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":kingdom_faction", slot_faction_state, sfs_active),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (faction_get_slot, ":max_bid", ":kingdom_faction", slot_faction_sod_merc_max_bid),
     (faction_get_slot, ":urgency", ":kingdom_faction", slot_faction_sod_merc_contract_urgency),
      (faction_get_slot, ":preferred_guild", ":kingdom_faction", slot_faction_sod_merc_preferred_guild),
      (gt, ":max_bid", 0),
      (gt, ":urgency", 0),

      # The bid gets its role score once here. The generic relationship weight
      # below deliberately receives role_none to avoid counting doctrine twice.
      (call_script, "script_sod_merc_market_calculate_guild_role_fit", ":guild_faction", ":demand_type"),
      (assign, ":role_fit_score", reg0),

     (try_begin),
       (gt, ":use_cached_contract_totals", 0),
       (faction_get_slot, ":available_companies", ":guild_faction", slot_faction_sod_merc_weekly_supply_available_cache),
       (faction_get_slot, ":max_company_size", ":guild_faction", slot_faction_sod_merc_weekly_supply_max_size_cache),
       (faction_get_slot, ":quality", ":guild_faction", slot_faction_sod_merc_weekly_supply_quality_cache),
       (faction_get_slot, ":price_pressure", ":guild_faction", slot_faction_sod_merc_weekly_supply_price_pressure_cache),
       (faction_get_slot, ":long_contract_willingness", ":guild_faction", slot_faction_sod_merc_weekly_supply_long_willingness_cache),
       (faction_get_slot, ":danger_willingness", ":guild_faction", slot_faction_sod_merc_weekly_supply_danger_willingness_cache),
       (faction_get_slot, ":refusal_reason", ":guild_faction", slot_faction_sod_merc_weekly_supply_refusal_reason_cache),
     (else_try),
       (call_script, "script_sod_merc_market_calculate_guild_supply", ":guild_faction", 0),
       (assign, ":available_companies", reg0),
       (assign, ":max_company_size", reg1),
       (assign, ":quality", reg2),
       (assign, ":price_pressure", reg3),
       (assign, ":long_contract_willingness", reg4),
       (assign, ":danger_willingness", reg5),
       (assign, ":refusal_reason", reg6),
     (try_end),
     (gt, ":available_companies", 0),
     (ge, ":max_company_size", 20),
     (eq, ":refusal_reason", sod_merc_refusal_none),

     (assign, ":company_size", ":max_company_size"),
     (try_begin),
       (eq, ":demand_type", sod_merc_contract_role_patrol),
       (val_min, ":company_size", 35),
       (assign, ":term_days", 20),
     (else_try),
       (eq, ":demand_type", sod_merc_contract_role_escort),
       (val_min, ":company_size", 30),
       (assign, ":term_days", 20),
     (else_try),
       (eq, ":demand_type", sod_merc_contract_role_garrison_support),
       (val_min, ":company_size", 45),
       (assign, ":term_days", 30),
     (else_try),
       (eq, ":demand_type", sod_merc_contract_role_supply_column),
       (val_min, ":company_size", 35),
       (assign, ":term_days", 25),
     (else_try),
       (eq, ":demand_type", sod_merc_contract_role_field_company),
       (val_min, ":company_size", 60),
       (assign, ":term_days", 35),
     (else_try),
       (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
       (val_min, ":company_size", 40),
       (assign, ":term_days", 25),
     (else_try),
       (val_min, ":company_size", 40),
     (try_end),
     (val_max, ":company_size", 20),

     (store_mul, ":bid_value", ":company_size", 16),
     (try_begin),
       (ge, ":quality", 3),
       (val_mul, ":bid_value", 145),
       (val_div, ":bid_value", 100),
     (else_try),
       (eq, ":quality", 2),
       (val_mul, ":bid_value", 125),
       (val_div, ":bid_value", 100),
     (try_end),
     (val_mul, ":bid_value", ":price_pressure"),
     (val_div, ":bid_value", 100),
     (try_begin),
       (store_relation, ":kingdom_guild_relation", ":kingdom_faction", ":guild_faction"),
       (lt, ":kingdom_guild_relation", -20),
       (assign, ":hostility_surcharge", 120),
       (val_mul, ":bid_value", ":hostility_surcharge"),
       (val_div, ":bid_value", 100),
     (try_end),
     (try_begin),
       (eq, ":preferred_guild", ":guild_faction"),
       (val_mul, ":bid_value", 9),
       (val_div, ":bid_value", 10),
     (try_end),
      (try_begin),
        (eq, ":guild_faction", "fac_sod_merc_guild5"),
        (this_or_next|eq, ":demand_type", sod_merc_contract_role_escort),
        (this_or_next|eq, ":demand_type", sod_merc_contract_role_patrol),
        (this_or_next|eq, ":demand_type", sod_merc_contract_role_supply_column),
        (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
        (faction_get_slot, ":safe_passage", ":guild_faction", slot_faction_serpent_safe_passage),
        (store_div, ":safe_discount", ":safe_passage", 10),
        (val_min, ":safe_discount", 12),
       (store_sub, ":safe_multiplier", 100, ":safe_discount"),
       (val_mul, ":bid_value", ":safe_multiplier"),
       (val_div, ":bid_value", 100),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       (faction_get_slot, ":slaver_heat", ":guild_faction", slot_faction_slaver_market_heat),
       (store_div, ":heat_surcharge", ":slaver_heat", 5),
       (val_min, ":heat_surcharge", 25),
       (store_add, ":heat_multiplier", 100, ":heat_surcharge"),
       (val_mul, ":bid_value", ":heat_multiplier"),
       (val_div, ":bid_value", 100),
      (try_end),
     (try_begin),
       (gt, ":urgency", 2),
       (val_mul, ":bid_value", 115),
       (val_div, ":bid_value", 100),
     (try_end),
     (try_begin),
       (eq, ":demand_type", sod_merc_contract_role_field_company),
       (lt, ":danger_willingness", 45),
       (val_mul, ":bid_value", 125),
       (val_div, ":bid_value", 100),
     (try_end),
     (try_begin),
       (gt, ":term_days", 30),
       (lt, ":long_contract_willingness", 45),
       (val_mul, ":bid_value", 115),
       (val_div, ":bid_value", 100),
     (try_end),
     (try_begin),
       (faction_slot_eq, "fac_player_faction", slot_faction_merc_pact, ":guild_faction"),
       (ge, "$g_sod_merc_weekly_paiment_paid_in_a_row", 4),
       (faction_get_slot, ":player_debt", ":guild_faction", player_debt_to_faction),
       (le, ":player_debt", 0),
       (val_mul, ":bid_value", 110),
       (val_div, ":bid_value", 100),
     (try_end),
     (val_max, ":bid_value", 250),
     (le, ":bid_value", ":max_bid"),

      (call_script, "script_sod_merc_market_calculate_kingdom_guild_weight", ":kingdom_faction", ":guild_faction", ":use_cached_contract_totals", sod_merc_contract_role_none),
     (assign, ":relation_weight", reg0),
     (assign, ":bid_score", ":max_bid"),
     (val_sub, ":bid_score", ":bid_value"),
     (store_mul, ":urgency_score", ":urgency", 15),
     (val_add, ":bid_score", ":urgency_score"),
     (val_add, ":bid_score", ":relation_weight"),
     (try_begin),
       (eq, ":preferred_guild", ":guild_faction"),
       (val_add, ":bid_score", 20),
     (try_end),
     (val_add, ":bid_score", ":role_fit_score"),
     (try_begin),
       (faction_slot_eq, "fac_player_faction", slot_faction_merc_pact, ":guild_faction"),
       (ge, "$g_sod_merc_weekly_paiment_paid_in_a_row", 4),
       (faction_get_slot, ":player_debt", ":guild_faction", player_debt_to_faction),
       (le, ":player_debt", 0),
       (val_sub, ":bid_score", 20),
     (try_end),
     (store_div, ":risk_score", ":danger_willingness", 4),
     (val_add, ":bid_score", ":risk_score"),
   (try_end),

   (assign, reg0, ":bid_value"),
   (assign, reg1, ":bid_score"),
   (assign, reg2, ":company_size"),
   (assign, reg3, ":term_days"),
   (assign, reg4, ":refusal_reason"),
 ]),
]
