# COST: O(1)
SCRIPTS = [
("sod_get_center_economy_profile",
  [
    (store_script_param, ":center_no", 1),

    (assign, ":wealth", 0),
    (assign, ":prosperity", 0),
    (assign, ":local_prosperity", 0),
    (assign, ":health", 0),
    (assign, ":population", 0),
    (assign, ":liquidity_pct", 0),
    (assign, ":condition_pct", 0),
    (assign, ":market_capacity", 0),

    (try_begin),
      (gt, ":center_no", 0),
      (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
      (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
      (party_get_slot, ":local_prosperity", ":center_no", slot_center_sod_local_prosperity),
      (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
      (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
      (val_max, ":wealth", 0),
      (val_max, ":prosperity", 0),
      (val_clamp, ":local_prosperity", 0, 101),
      (val_clamp, ":health", -100, 121),
      (val_max, ":population", 0),

      (call_script, "script_sod_get_center_population_capacity_profile", ":center_no"),
      (assign, ":population_capacity_pct", reg2),

      (assign, ":market_capacity", 2000),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (assign, ":market_capacity", 12000),
      (else_try),
        (is_between, ":center_no", castles_begin, castles_end),
        (assign, ":market_capacity", 4500),
      (else_try),
        (is_between, ":center_no", villages_begin, villages_end),
        (assign, ":market_capacity", 2500),
      (try_end),
      (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_market_wealth_flat),
      (val_add, ":market_capacity", reg0),
      (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_market_wealth_pct),
      (val_mul, ":market_capacity", reg0),
      (val_div, ":market_capacity", 100),
      (val_clamp, ":market_capacity", 500, 2000001),

      (store_mul, ":liquidity_pct", ":wealth", 100),
      (val_div, ":liquidity_pct", ":market_capacity"),
      (val_clamp, ":liquidity_pct", 0, 201),

      (assign, ":condition_pct", ":prosperity"),
      (val_add, ":condition_pct", ":local_prosperity"),
      (store_add, ":health_condition", ":health", 100),
      (val_div, ":health_condition", 2),
      (val_add, ":condition_pct", ":health_condition"),
      (val_add, ":condition_pct", ":population_capacity_pct"),
      (val_div, ":condition_pct", 4),
      (val_clamp, ":condition_pct", 0, 151),
    (try_end),

    (assign, reg0, ":wealth"),
    (assign, reg1, ":prosperity"),
    (assign, reg2, ":local_prosperity"),
    (assign, reg3, ":liquidity_pct"),
    (assign, reg4, ":condition_pct"),
    (assign, reg5, ":market_capacity"),
    (assign, reg6, ":health"),
    (assign, reg7, ":population"),
  ]),

("sod_change_center_wealth",
  [
    (store_script_param, ":center_no", 1),
    (store_script_param, ":difference", 2),

    (assign, ":old_wealth", 0),
    (assign, ":new_wealth", 0),
    (try_begin),
      (gt, ":center_no", 0),
      (party_get_slot, ":old_wealth", ":center_no", slot_town_wealth),
      (val_max, ":old_wealth", 0),
      (store_add, ":new_wealth", ":old_wealth", ":difference"),
      (val_clamp, ":new_wealth", 0, 2000001),
      (party_set_slot, ":center_no", slot_town_wealth, ":new_wealth"),
    (try_end),

    (store_sub, ":actual_change", ":new_wealth", ":old_wealth"),
    (assign, reg0, ":new_wealth"),
    (assign, reg1, ":old_wealth"),
    (assign, reg2, ":actual_change"),
  ]),

("sod_change_center_local_prosperity",
  [
    (store_script_param, ":center_no", 1),
    (store_script_param, ":difference", 2),

    (assign, ":old_local_prosperity", 0),
    (assign, ":new_local_prosperity", 0),
    (try_begin),
      (gt, ":center_no", 0),
      (party_get_slot, ":old_local_prosperity", ":center_no", slot_center_sod_local_prosperity),
      (val_clamp, ":old_local_prosperity", 0, 101),
      (store_add, ":new_local_prosperity", ":old_local_prosperity", ":difference"),
      (val_clamp, ":new_local_prosperity", 0, 101),
      (party_set_slot, ":center_no", slot_center_sod_local_prosperity, ":new_local_prosperity"),
    (try_end),

    (store_sub, ":actual_change", ":new_local_prosperity", ":old_local_prosperity"),
    (assign, reg0, ":new_local_prosperity"),
    (assign, reg1, ":old_local_prosperity"),
    (assign, reg2, ":actual_change"),
  ]),
]
