# COST: O(number of player walled centers)
SCRIPTS = [
("sod_describe_elite_doctrine_report",
  [
    (call_script, "script_update_nobles_gather_at"),

    (try_begin),
      (gt, "$g_sod_nobles_gather_at", 0),
      (str_store_party_name, s2, "$g_sod_nobles_gather_at"),
      (str_store_string, s1, "@Elite Doctrine Report^^Noble assembly: {s2}. The houses know where to send their sons and daughters."),
    (else_try),
      (str_store_string, s1, "@Elite Doctrine Report^^Noble assembly: none. Build or recover a chapter house to gather noble recruits."),
    (try_end),

    (assign, ":chapter_count", 0),
    (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
      (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
      (party_slot_eq, ":center_no", slot_center_has_chapter, 1),
      (val_add, ":chapter_count", 1),
    (try_end),
    (assign, reg0, ":chapter_count"),

    (assign, ":effective_faith", "$g_sod_global_faith"),
    (store_mul, ":holy_burden", "$g_sod_holy", 10),
    (val_sub, ":effective_faith", ":holy_burden"),
    (assign, reg1, "$g_sod_global_faith"),
    (assign, reg2, ":holy_burden"),
    (assign, reg3, ":effective_faith"),
    (assign, reg4, sod_zealot_min_faith),

    (try_begin),
      (ge, ":effective_faith", 500),
      (str_store_string, s3, "@Fervent"),
    (else_try),
      (ge, ":effective_faith", 300),
      (str_store_string, s3, "@Strong"),
    (else_try),
      (ge, ":effective_faith", sod_zealot_min_faith),
      (str_store_string, s3, "@Possible"),
    (else_try),
      (str_store_string, s3, "@Locked"),
    (try_end),

    (str_store_string, s1, "@{s1}^Chapter houses under your banner: {reg0}.^^Faith ledger:^Raw faith: {reg1}. Holy burden: {reg2}. Effective faith: {reg3}. Required for ascension: {reg4}. Ascension outlook: {s3}.^^Homeland noble doctrine:"),

    (try_begin),
      (eq, "$g_sod_country", cb_antares),
      (str_store_troop_name, s4, "trp_sod_ant_honor_guard"),
      (call_script, "script_sod_troop_get_faith_upgrade", "trp_sod_ant_honor_guard1"),
    (else_try),
      (eq, "$g_sod_country", cb_marina),
      (str_store_troop_name, s4, "trp_sod_mar_condottieri"),
      (call_script, "script_sod_troop_get_faith_upgrade", "trp_sod_mar_condottieri1"),
    (else_try),
      (eq, "$g_sod_country", cb_aden),
      (str_store_troop_name, s4, "trp_sod_ade_magnate"),
      (call_script, "script_sod_troop_get_faith_upgrade", "trp_sod_ade_magnate1"),
    (else_try),
      (eq, "$g_sod_country", cb_villian),
      (str_store_troop_name, s4, "trp_sod_vil_high_chief"),
      (call_script, "script_sod_troop_get_faith_upgrade", "trp_sod_vil_high_chief1"),
    (else_try),
      (str_store_troop_name, s4, "trp_sod_zer_3_noble"),
      (call_script, "script_sod_troop_get_faith_upgrade", "trp_sod_zer_3_noble1"),
    (try_end),

    (try_begin),
      (gt, reg0, 0),
      (str_store_troop_name, s5, reg0),
      (call_script, "script_sod_artifact_get_doctrine_discount", reg0),
      (assign, reg5, reg0),
    (else_try),
      (str_store_string, s5, "@unmapped faith elite"),
      (assign, reg5, 0),
    (try_end),

    (assign, reg6, "$g_sod_doctrine_inspiration"),
    (try_begin),
      (gt, "$g_sod_nobles_gather_at", 0),
      (str_store_string, s6, "@Ready"),
    (else_try),
      (str_store_string, s6, "@Requires a chapter house"),
    (try_end),
    (try_begin),
      (ge, ":effective_faith", sod_zealot_min_faith),
      (str_store_string, s7, "@Possible if a noble volunteers"),
    (else_try),
      (str_store_string, s7, "@Not enough effective faith"),
    (try_end),

    (str_store_string, s1, "@{s1}^{s4}: noble elite. Status: {s6}.^Faith ascension: {s5}. Status: {s7}. Requires chapel or temple support, an eligible noble, and sufficient effective faith.^^Royal legitimacy:^Artifact doctrine discount: {reg5}%. Duel inspiration batches remaining: {reg6}. Matching recovered or vaulted royal artifacts can reduce elite training costs, and commander duel victories can inspire a few veteran upgrades. Neither bypasses buildings, faith, or culture gates.^^Doctrine notes:^Infantry, ranged, and mounted troops still require barracks, range, and stables. Nobles remain the second-best troop tier. Faith elites remain the best-in-game tier."),
  ]),
]
