# COST: medium; called only when a center note is refreshed, never from a campaign pulse.
# Map notes need a human-readable situation, while detailed figures live in fief reports.
SCRIPTS = [
("sod_store_center_recon_brief_to_s68",
 [
   (store_script_param_1, ":center_no"),

   (str_store_string, s68, "@No current settlement report is available."),
   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),

     # Health: name a crisis or a condition, never expose the raw health ledger.
     (call_script, "script_sod_center_public_health_compute_causes", ":center_no"),
     (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
     (party_get_slot, ":risk", ":center_no", slot_center_health_disease_risk),
     (party_get_slot, ":outbreak", ":center_no", slot_center_health_outbreak_type),
     (party_get_slot, ":quarantine", ":center_no", slot_center_health_quarantine),
     (party_get_slot, ":aftermath", ":center_no", slot_center_health_recent_aftermath),

     # Gather state before constructing text. Profile helpers can use scratch
     # strings themselves, so none are called after this point.
     (call_script, "script_sod_get_center_food_profile", ":center_no"),
     (assign, ":food_days", reg3),
     (assign, ":food_security", reg4),

     (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
     (assign, ":food_balance", reg0),
     (assign, ":scarcity", reg4),
     (assign, ":trade_willingness", reg5),
     (assign, ":wealth_delta", reg7),

     (call_script, "script_sod_get_center_security_profile", ":center_no"),
     (assign, ":effective_threat", reg0),
     (assign, ":security", reg1),

     (call_script, "script_sod_get_center_faith_profile", ":center_no"),
     (assign, ":faith_tension", reg3),
     (assign, ":faith_unrest", reg7),

     # Compose a short situation report only after all helpers have finished.
     (str_store_string, s69, "@The people are in fair health."),
     (try_begin),
       (gt, ":outbreak", sod_outbreak_none),
       (call_script, "script_sod_center_public_health_outbreak_name_to_s0", ":outbreak"),
       (str_store_string_reg, s74, s0),
       (str_store_string, s69, "@An outbreak of {s74} is active."),
     (else_try),
       (gt, ":quarantine", 0),
       (str_store_string, s69, "@A quarantine is in force."),
     (else_try),
       (gt, ":aftermath", 0),
       (str_store_string, s69, "@The people are recovering from recent sickness."),
     (else_try),
       (ge, ":risk", 60),
       (str_store_string, s69, "@Illness is spreading through the settlement."),
     (else_try),
       (le, ":health", 25),
       (str_store_string, s69, "@The people are in poor health."),
     (try_end),

     # Supply and commerce: use clear conditions instead of production, tax, and liquidity values.
     (str_store_string, s70, "@Food stores are adequate."),
     (try_begin),
       (lt, ":food_security", 300),
       (assign, reg0, ":food_days"),
       (str_store_string, s70, "@Stores will last only {reg0} days."),
     (else_try),
       (lt, ":food_security", 700),
       (str_store_string, s70, "@Food stores are running short."),
     (else_try),
       (ge, ":food_security", 1400),
       (str_store_string, s70, "@Food stores are plentiful."),
     (try_end),

     (str_store_string, s71, "@Trade is steady."),
     (try_begin),
       (this_or_next|ge, ":scarcity", 65),
       (lt, ":food_balance", -20),
       (str_store_string, s71, "@The market is short of goods."),
     (else_try),
       (this_or_next|lt, ":trade_willingness", 35),
       (lt, ":wealth_delta", -10),
       (str_store_string, s71, "@Trade is faltering."),
     (else_try),
       (gt, ":wealth_delta", 10),
       (str_store_string, s71, "@Trade is lively."),
     (try_end),

     # Security and faith share one final line because both are local stability signals.
     (str_store_string, s72, "@The roads are quiet."),
     (try_begin),
       (ge, ":effective_threat", 6),
       (str_store_string, s72, "@The roads are dangerous."),
     (else_try),
       (ge, ":effective_threat", 3),
       (str_store_string, s72, "@Travelers report growing danger."),
     (else_try),
       (le, ":security", 0),
       (str_store_string, s72, "@There is little local protection."),
     (else_try),
       (ge, ":security", 80),
       (str_store_string, s72, "@The roads are well watched."),
     (try_end),

     (str_clear, s73),
     (try_begin),
       (this_or_next|ge, ":faith_tension", 50),
       (ge, ":faith_unrest", 20),
       (str_store_string, s73, "@ Religious tension is worsening."),
     (try_end),

     (try_begin),
       (is_between, ":center_no", towns_begin, towns_end),
       (party_collect_attachments_to_party, ":center_no", "p_collective_ally"),
       (party_get_num_companions, reg0, "p_collective_ally"),
       (str_store_string, s68, "@The garrison numbers {reg0}. {s69} {s70} {s71} {s72}{s73}"),
     (else_try),
       (is_between, ":center_no", castles_begin, castles_end),
       (party_collect_attachments_to_party, ":center_no", "p_collective_ally"),
       (party_get_num_companions, reg0, "p_collective_ally"),
       (str_store_string, s68, "@The garrison numbers {reg0}. {s69} {s70} {s71} {s72}{s73}"),
     (else_try),
       (is_between, ":center_no", villages_begin, villages_end),
       (try_begin),
         (this_or_next|party_slot_eq, ":center_no", slot_village_state, svs_looted),
         (party_slot_eq, ":center_no", slot_village_state, svs_deserted),
         (str_store_string, s68, "@The village is devastated. {s69} {s70} {s72}{s73}"),
       (else_try),
         (str_store_string, s68, "@{s69} {s70} {s71} {s72}{s73}"),
       (try_end),
     (try_end),
   (try_end),
 ]),
]
