# COST: trivial; evaluated only while the market weighs a possible contract.
# Guild doctrine belongs here so employer choice and bid scoring cannot drift.
SCRIPTS = [
("sod_merc_market_calculate_guild_role_fit",
 [
   (store_script_param_1, ":guild_faction"),
   (store_script_param, ":demand_type", 2),

   (assign, ":role_fit", 0),
   (try_begin),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild1"),
       # Black Army: professional security, dependable field service, limited logistics.
       (try_begin),
         (eq, ":demand_type", sod_merc_contract_role_field_company),
         (assign, ":role_fit", 10),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_patrol),
         (assign, ":role_fit", 18),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_escort),
         (assign, ":role_fit", 10),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_supply_column),
         (assign, ":role_fit", 4),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_mercenary_lord),
         (assign, ":role_fit", 12),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_garrison_support),
         (assign, ":role_fit", 20),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
         (assign, ":role_fit", 14),
       (try_end),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild2"),
       # Conquistadors: organized infantry, siege defense, and protected supply work.
       (try_begin),
         (eq, ":demand_type", sod_merc_contract_role_field_company),
         (assign, ":role_fit", 14),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_patrol),
         (assign, ":role_fit", 8),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_escort),
         (assign, ":role_fit", 12),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_supply_column),
         (assign, ":role_fit", 22),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_mercenary_lord),
         (assign, ":role_fit", 10),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_garrison_support),
         (assign, ":role_fit", 20),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
         (assign, ":role_fit", 12),
       (try_end),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild3"),
       # Elephant Guard: wardens first, with their strongest call in protection crises.
       (try_begin),
         (eq, ":demand_type", sod_merc_contract_role_field_company),
         (assign, ":role_fit", 6),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_patrol),
         (assign, ":role_fit", 10),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_escort),
         (assign, ":role_fit", 8),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_supply_column),
         (assign, ":role_fit", 2),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_mercenary_lord),
         (assign, ":role_fit", 6),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_garrison_support),
         (assign, ":role_fit", 20),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
         (assign, ":role_fit", 22),
       (try_end),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild4"),
       # Jotnar: hearth defenders and durable field infantry, not routine caravan guards.
       (try_begin),
         (eq, ":demand_type", sod_merc_contract_role_field_company),
         (assign, ":role_fit", 16),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_patrol),
         (assign, ":role_fit", 9),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_escort),
         (assign, ":role_fit", 6),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_supply_column),
         (assign, ":role_fit", 0),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_mercenary_lord),
         (assign, ":role_fit", 12),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_garrison_support),
         (assign, ":role_fit", 22),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
         (assign, ":role_fit", 14),
       (try_end),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild5"),
       # Serpent Host: route control and open-field tempo, intentionally poor static garrisons.
       (try_begin),
         (eq, ":demand_type", sod_merc_contract_role_field_company),
         (assign, ":role_fit", 14),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_patrol),
         (assign, ":role_fit", 21),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_escort),
         (assign, ":role_fit", 24),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_supply_column),
         (assign, ":role_fit", 12),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_mercenary_lord),
         (assign, ":role_fit", 12),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_garrison_support),
         (assign, ":role_fit", -12),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
         (assign, ":role_fit", 16),
       (try_end),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild6"),
       # Slavers are capture specialists. They are never a credible civic garrison or relief corps.
       (try_begin),
         (eq, ":demand_type", sod_merc_contract_role_field_company),
         (assign, ":role_fit", 12),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_patrol),
         (assign, ":role_fit", 11),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_escort),
         (assign, ":role_fit", 4),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_supply_column),
         (assign, ":role_fit", -18),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_mercenary_lord),
         (assign, ":role_fit", 8),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_garrison_support),
         (assign, ":role_fit", -28),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
         (assign, ":role_fit", 19),
       (try_end),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild7"),
       # Boar Clan sells frontier pressure and raids, not town guard or relief service.
       (try_begin),
         (eq, ":demand_type", sod_merc_contract_role_field_company),
         (assign, ":role_fit", 15),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_patrol),
         (assign, ":role_fit", 19),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_escort),
         (assign, ":role_fit", 8),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_supply_column),
         (assign, ":role_fit", -16),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_mercenary_lord),
         (assign, ":role_fit", 10),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_garrison_support),
         (assign, ":role_fit", -18),
       (else_try),
         (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
         (assign, ":role_fit", 22),
       (try_end),
     (try_end),

     # World ledgers sharpen a valid niche; they never erase a guild's base doctrine.
     (try_begin),
       (eq, ":guild_faction", "fac_sod_merc_guild1"),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_patrol),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_garrison_support),
       (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
       (faction_get_slot, ":pressure", ":guild_faction", slot_faction_black_army_contract_heat),
       (store_div, ":bonus", ":pressure", 8),
       (val_min, ":bonus", 10),
       (val_add, ":role_fit", ":bonus"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild2"),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_supply_column),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_garrison_support),
       (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
       (faction_get_slot, ":pressure", ":guild_faction", slot_faction_conquistador_supply_stock),
       (store_div, ":bonus", ":pressure", 8),
       (val_min, ":bonus", 10),
       (val_add, ":role_fit", ":bonus"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild3"),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_garrison_support),
       (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
       (faction_get_slot, ":pressure", ":guild_faction", slot_faction_elephant_guard_slaver_alarm),
       (store_div, ":bonus", ":pressure", 6),
       (val_min, ":bonus", 14),
       (val_add, ":role_fit", ":bonus"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild4"),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_garrison_support),
       (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
       (faction_get_slot, ":pressure", ":guild_faction", slot_faction_jotnar_hearth_pressure),
       (store_div, ":bonus", ":pressure", 9),
       (val_min, ":bonus", 10),
       (val_add, ":role_fit", ":bonus"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild5"),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_patrol),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_escort),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_supply_column),
       (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
       (faction_get_slot, ":pressure", ":guild_faction", slot_faction_serpent_intelligence),
       (store_div, ":bonus", ":pressure", 5),
       (val_min, ":bonus", 14),
       (val_add, ":role_fit", ":bonus"),
     (else_try),
       (eq, ":guild_faction", "fac_sod_merc_guild7"),
       (this_or_next|eq, ":demand_type", sod_merc_contract_role_patrol),
       (eq, ":demand_type", sod_merc_contract_role_special_world_activity),
       (faction_get_slot, ":pressure", ":guild_faction", slot_faction_boar_frontier_pressure),
       (store_div, ":bonus", ":pressure", 7),
       (val_min, ":bonus", 12),
       (val_add, ":role_fit", ":bonus"),
     (try_end),
     (val_clamp, ":role_fit", -40, 46),
   (try_end),

   (assign, reg0, ":role_fit"),
 ]),
]
