# COST: low
SCRIPTS = [
("sod_threat_board_apply_economy_effect",
 [
   (store_script_param_1, ":threat_type"),
   (store_script_param_2, ":sponsor_center"),
   (store_script_param, ":outcome", 3), # 1 = completed, -1 = failed/expired

   (assign, ":prosperity_delta", 1),
   (assign, ":local_prosperity_delta", 1),
   (assign, ":health_delta", 0),
   (assign, ":population_delta", 3),
   (assign, ":wealth_delta", 250),
   (assign, ":cattle_delta", 0),

   (try_begin),
     (eq, ":threat_type", sod_threat_type_cattle_raiders),
     (assign, ":prosperity_delta", 1),
     (assign, ":local_prosperity_delta", 1),
     (assign, ":health_delta", 1),
     (assign, ":population_delta", 5),
     (assign, ":wealth_delta", 150),
     (assign, ":cattle_delta", 5),
   (else_try),
     (eq, ":threat_type", sod_threat_type_pirates),
     (assign, ":prosperity_delta", 2),
     (assign, ":local_prosperity_delta", 2),
     (assign, ":population_delta", 2),
     (assign, ":wealth_delta", 450),
   (else_try),
     (eq, ":threat_type", sod_threat_type_deserters),
     (assign, ":prosperity_delta", 1),
     (assign, ":local_prosperity_delta", 1),
     (assign, ":health_delta", 1),
     (assign, ":population_delta", 3),
     (assign, ":wealth_delta", 300),
   (else_try),
     (eq, ":threat_type", sod_threat_type_relic_thieves),
     (assign, ":prosperity_delta", 1),
     (assign, ":local_prosperity_delta", 1),
     (assign, ":health_delta", 1),
     (assign, ":population_delta", 2),
     (assign, ":wealth_delta", 250),
   (else_try),
     (eq, ":threat_type", sod_threat_type_rogue_company),
     (assign, ":prosperity_delta", 2),
     (assign, ":local_prosperity_delta", 2),
     (assign, ":population_delta", 2),
     (assign, ":wealth_delta", 500),
   (else_try),
     (eq, ":threat_type", sod_threat_type_faction_problem),
     (assign, ":prosperity_delta", 2),
     (assign, ":local_prosperity_delta", 2),
     (assign, ":health_delta", 1),
     (assign, ":population_delta", 4),
     (assign, ":wealth_delta", 400),
   (try_end),

   (try_begin),
     (lt, ":outcome", 0),
     (val_mul, ":prosperity_delta", -2),
     (val_mul, ":local_prosperity_delta", -2),
     (val_mul, ":health_delta", -1),
     (val_mul, ":population_delta", -2),
     (val_mul, ":wealth_delta", -2),
     (try_begin),
       (eq, ":threat_type", sod_threat_type_cattle_raiders),
       (assign, ":cattle_delta", -8),
     (try_end),
   (try_end),

   (call_script, "script_change_center_prosperity", ":sponsor_center", ":prosperity_delta"),
   (call_script, "script_change_center_health", ":sponsor_center", ":health_delta"),

   (party_get_slot, ":local_prosperity", ":sponsor_center", slot_center_sod_local_prosperity),
   (val_add, ":local_prosperity", ":local_prosperity_delta"),
   (val_clamp, ":local_prosperity", 0, 101),
   (party_set_slot, ":sponsor_center", slot_center_sod_local_prosperity, ":local_prosperity"),

   (party_get_slot, ":population", ":sponsor_center", slot_center_sod_local_population),
   (val_add, ":population", ":population_delta"),
   (val_max, ":population", 0),
   (party_set_slot, ":sponsor_center", slot_center_sod_local_population, ":population"),

   (party_get_slot, ":wealth", ":sponsor_center", slot_town_wealth),
   (val_add, ":wealth", ":wealth_delta"),
   (party_set_slot, ":sponsor_center", slot_town_wealth, ":wealth"),

   (try_begin),
     (neq, ":cattle_delta", 0),
     (party_get_slot, ":cattle", ":sponsor_center", slot_village_number_of_cattle),
     (val_add, ":cattle", ":cattle_delta"),
     (val_max, ":cattle", 0),
     (party_set_slot, ":sponsor_center", slot_village_number_of_cattle, ":cattle"),
   (try_end),

    (assign, reg(0), ":prosperity_delta"),
    (assign, reg(1), ":health_delta"),
    (assign, reg(2), ":population_delta"),
    (assign, reg(3), ":wealth_delta"),
    (assign, reg(4), ":cattle_delta"),
 ]),
]
