# COST: light
SCRIPTS = [
("sod_store_hostile_reputation_report",
 [
   (assign, reg1, "$g_sod_hostile_mercy_count"),
   (assign, reg2, "$g_sod_hostile_recruit_count"),
   (assign, reg3, "$g_sod_hostile_paid_toll_count"),
   (assign, reg4, "$g_sod_hostile_intimidation_count"),
   (assign, reg5, "$g_sod_hostile_shakedown_count"),
   (assign, reg6, "$g_sod_hostile_informant_count"),
   (assign, reg7, "$g_sod_hostile_deserter_destroyed_count"),
   (assign, reg8, "$g_sod_hostile_refugee_help_count"),
   (assign, reg9, "$g_sod_hostile_regional_noncombat_count"),
   (assign, reg10, "$g_sod_hostile_regional_combat_count"),
   (assign, reg11, "$g_sod_hostile_prisoner_count"),
   (assign, reg12, "$g_sod_hostile_reputation_last_day"),
   (troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
   (try_begin),
     (gt, "$g_sod_hostile_reputation_last_center", 0),
     (str_store_party_name, s8, "$g_sod_hostile_reputation_last_center"),
   (else_try),
     (str_store_string, s8, "@no specific center"),
   (try_end),
   (try_begin),
     (gt, "$g_sod_hostile_reputation_last_faction", 0),
     (str_store_faction_name, s9, "$g_sod_hostile_reputation_last_faction"),
   (else_try),
     (str_store_string, s9, "@no specific faction"),
   (try_end),
   (assign, ":dominant", 0),
   (assign, ":dominant_score", 0),
   (try_begin),
     (gt, "$g_sod_hostile_mercy_count", ":dominant_score"),
     (assign, ":dominant_score", "$g_sod_hostile_mercy_count"),
     (assign, ":dominant", 1),
   (try_end),
   (try_begin),
     (gt, "$g_sod_hostile_paid_toll_count", ":dominant_score"),
     (assign, ":dominant_score", "$g_sod_hostile_paid_toll_count"),
     (assign, ":dominant", 2),
   (try_end),
   (try_begin),
     (gt, "$g_sod_hostile_intimidation_count", ":dominant_score"),
     (assign, ":dominant_score", "$g_sod_hostile_intimidation_count"),
     (assign, ":dominant", 3),
   (try_end),
   (try_begin),
     (gt, "$g_sod_hostile_shakedown_count", ":dominant_score"),
     (assign, ":dominant_score", "$g_sod_hostile_shakedown_count"),
     (assign, ":dominant", 4),
   (try_end),
   (try_begin),
     (gt, "$g_sod_hostile_deserter_destroyed_count", ":dominant_score"),
     (assign, ":dominant_score", "$g_sod_hostile_deserter_destroyed_count"),
     (assign, ":dominant", 5),
   (try_end),
   (try_begin),
     (lt, ":player_renown", 75),
     (str_store_string, s6, "@No one knows who you are yet, my liege."),
     (str_store_string, s7, "@A few scouts may remember your banner, but the roads have no settled opinion of you."),
   (else_try),
     (lt, ":player_renown", 250),
     (str_store_string, s6, "@Your name has begun to travel, but unevenly."),
     (str_store_string, s7, "@Some crews will have heard one tale of you, not enough to know whether to bargain, flee, or test your line."),
   (else_try),
     (eq, ":dominant", 1),
     (str_store_string, s6, "@Scouts and innkeepers say you sometimes spare men who expected a noose."),
     (str_store_string, s7, "@That may make desperate bands try words before steel, though mercy is not always repaid wisely."),
   (else_try),
     (eq, ":dominant", 2),
     (str_store_string, s6, "@Tollmen and outlaws remember that you have paid when the road turned ugly."),
     (str_store_string, s7, "@Some will ask for silver before blood. Others may mistake patience for weakness."),
   (else_try),
     (eq, ":dominant", 3),
     (str_store_string, s6, "@Smaller crews are beginning to fear your banner."),
     (str_store_string, s7, "@Weak men may scatter. Proud fools may step forward just to prove they still have courage."),
   (else_try),
     (eq, ":dominant", 4),
     (str_store_string, s6, "@Travelers say you take from those who prey on travelers."),
     (str_store_string, s7, "@Outlaws remember that kind of justice. Expect fewer clean bargains and more old grudges."),
   (else_try),
     (eq, ":dominant", 5),
     (str_store_string, s6, "@Deserters have begun to believe they will find little mercy under your banner."),
     (str_store_string, s7, "@Broken soldiers may be harder to win over, and quicker to fight like cornered men."),
   (else_try),
     (str_store_string, s6, "@Your name has not settled into a clear shape beyond the campfires yet."),
     (str_store_string, s7, "@Some know your banner. Few agree on what it means."),
   (try_end),
   (try_begin),
     (lt, ":player_renown", 75),
     (str_store_string, s10, "@For now, there is nothing useful to read. Win battles, spare men, hang thieves, pay tolls; then people will begin to talk."),
   (else_try),
     (lt, ":player_renown", 250),
     (str_store_string, s10, "@The pattern is forming, but not settled. Give the roads a few more victories or scandals and they will speak more plainly."),
   (else_try),
     (gt, "$g_sod_hostile_regional_noncombat_count", "$g_sod_hostile_regional_combat_count"),
     (str_store_string, s10, "@Lately, more quarrels seem to end with words, dispersals, or men walking away alive."),
   (else_try),
     (lt, "$g_sod_hostile_regional_noncombat_count", "$g_sod_hostile_regional_combat_count"),
     (str_store_string, s10, "@Lately, more quarrels seem to end with steel, graves, and stories told too loudly."),
   (else_try),
     (gt, "$g_sod_hostile_regional_combat_count", 0),
     (str_store_string, s10, "@Lately, the stories are mixed: bargains in one village, blood in the next."),
   (else_try),
     (str_store_string, s10, "@There is not enough rumor yet for a wise man to trust the pattern."),
   (try_end),
 ]),
]
