# COST: lightweight adviser trust and reaction helpers; no party scans.
from header_operations import *
from module_constants import *
from module_troops import *

SCRIPTS = [
("sod_strategy_advisor_initialize_mentor",
 [
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_trust, 50),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_arc_stage, sod_mentor_arc_old_hand),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_warning_state, sod_mentor_warning_none),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_reaction_day, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_legion_memory, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_first_imperial_victory, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_centurion_death, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_alliance_victory, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_ruthless_victory, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_final_closure, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_front_warning_day, 0),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_treaty_comment_day, 0),
 ]),

("sod_strategy_advisor_get_trust_band_to_reg",
 [
   (troop_get_slot, ":trust", "trp_sod_strategy_advisor", slot_troop_sod_mentor_trust),
   (try_begin),
     (ge, ":trust", 85),
     (assign, reg0, sod_mentor_trust_reverent),
     (str_store_string, s0, "@reverent"),
   (else_try),
     (ge, ":trust", 70),
     (assign, reg0, sod_mentor_trust_confident),
     (str_store_string, s0, "@confident"),
   (else_try),
     (ge, ":trust", 45),
     (assign, reg0, sod_mentor_trust_watchful),
     (str_store_string, s0, "@watchful"),
   (else_try),
     (ge, ":trust", 25),
     (assign, reg0, sod_mentor_trust_strained),
     (str_store_string, s0, "@strained"),
   (else_try),
     (assign, reg0, sod_mentor_trust_bitter),
     (str_store_string, s0, "@bitter"),
   (try_end),
 ]),

("sod_strategy_advisor_describe_trust_to_s1",
 [
   (call_script, "script_sod_strategy_advisor_get_trust_band_to_reg"),
   (try_begin),
     (eq, reg0, sod_mentor_trust_reverent),
     (str_store_string, s1, "@You are no longer merely your father's child in my eyes. You have taken his best hopes and given them cleaner hands. I will still argue with you, but I do so as a man who believes the realm can survive your victory."),
   (else_try),
     (eq, reg0, sod_mentor_trust_confident),
     (str_store_string, s1, "@I trust your command. Not blindly; blind trust is how courts die smiling. But you prepare, you listen, and you have not mistaken cruelty for strength."),
   (else_try),
     (eq, reg0, sod_mentor_trust_watchful),
     (str_store_string, s1, "@I am watchful. You have promise, scars, and too many roads open at once. That is not condemnation. It is the condition of command before discipline hardens into habit."),
   (else_try),
     (eq, reg0, sod_mentor_trust_strained),
     (str_store_string, s1, "@I am strained, my liege. I have watched good causes learn the language of their enemies. Give me reasons to believe this war is shaping you, not hollowing you."),
   (else_try),
     (str_store_string, s1, "@I serve the realm because someone must. Between us, there is bitterness now. I will still give counsel, but do not ask me to pretend every necessary order has been clean."),
   (try_end),
 ]),

("sod_strategy_advisor_apply_player_action",
 [
   (store_script_param, ":action", 1),
   (store_script_param, ":weight", 2),
   (val_max, ":weight", 1),
   (val_min, ":weight", 20),
   (assign, ":delta", 0),
   (try_begin),
     (this_or_next|eq, ":action", sod_companion_action_free_captives),
     (this_or_next|eq, ":action", sod_companion_action_help_village),
     (this_or_next|eq, ":action", sod_companion_action_honorable_peace),
     (this_or_next|eq, ":action", sod_companion_action_caravan_protection),
     (this_or_next|eq, ":action", sod_companion_action_food_security),
     (this_or_next|eq, ":action", sod_companion_action_build_healing),
     (this_or_next|eq, ":action", sod_companion_action_build_security),
     (this_or_next|eq, ":action", sod_companion_action_jotnar_support),
     (this_or_next|eq, ":action", sod_companion_action_elephant_guard_support),
     (this_or_next|eq, ":action", sod_companion_action_fair_pay),
     (this_or_next|eq, ":action", sod_companion_action_bonus_pay),
     (this_or_next|eq, ":action", sod_companion_action_generous_rations),
     (eq, ":action", sod_companion_action_debt_honesty),
     (assign, ":delta", 1),
   (else_try),
     (this_or_next|eq, ":action", sod_companion_action_defeat_imperials),
     (this_or_next|eq, ":action", sod_companion_action_scout_warning),
     (this_or_next|eq, ":action", sod_companion_action_siege_preparation),
     (this_or_next|eq, ":action", sod_companion_action_strict_discipline),
     (this_or_next|eq, ":action", sod_companion_action_black_army_security),
     (this_or_next|eq, ":action", sod_companion_action_castle_patrol_village_shield),
     (this_or_next|eq, ":action", sod_companion_action_castle_patrol_road_control),
     (eq, ":action", sod_companion_action_castle_patrol_caravan_screen),
     (assign, ":delta", 2),
   (else_try),
     (this_or_next|eq, ":action", sod_companion_action_sell_prisoners),
     (this_or_next|eq, ":action", sod_companion_action_buy_slaves),
     (this_or_next|eq, ":action", sod_companion_action_carry_slaves),
     (this_or_next|eq, ":action", sod_companion_action_execute_lord),
     (this_or_next|eq, ":action", sod_companion_action_abuse_village),
     (this_or_next|eq, ":action", sod_companion_action_diplomacy_betrayal),
     (this_or_next|eq, ":action", sod_companion_action_black_khergit_tribute),
     (this_or_next|eq, ":action", sod_companion_action_black_khergit_bribe),
     (this_or_next|eq, ":action", sod_companion_action_dirty_profit),
     (this_or_next|eq, ":action", sod_companion_action_unpaid_wages),
     (this_or_next|eq, ":action", sod_companion_action_threatened_troops),
     (this_or_next|eq, ":action", sod_companion_action_mutiny_suppressed),
     (this_or_next|eq, ":action", sod_companion_action_thin_rations),
     (this_or_next|eq, ":action", sod_companion_action_broken_pay_promise),
     (eq, ":action", sod_companion_action_castle_patrol_abuse),
     (assign, ":delta", -2),
   (else_try),
     (this_or_next|eq, ":action", sod_companion_action_retreat_or_fail),
     (this_or_next|eq, ":action", sod_companion_action_cowardice),
     (this_or_next|eq, ":action", sod_companion_action_hunger),
     (eq, ":action", sod_companion_action_empty_speech),
     (assign, ":delta", -1),
   (try_end),
   (try_begin),
     (neq, ":delta", 0),
     (val_mul, ":delta", ":weight"),
     (troop_get_slot, ":trust", "trp_sod_strategy_advisor", slot_troop_sod_mentor_trust),
     (val_add, ":trust", ":delta"),
     (val_max, ":trust", 0),
     (val_min, ":trust", 100),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_trust, ":trust"),
     (store_current_day, ":cur_day"),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_reaction_day, ":cur_day"),
     (try_begin),
       (eq, ":action", sod_companion_action_defeat_imperials),
       (troop_get_slot, ":memory", "trp_sod_strategy_advisor", slot_troop_sod_mentor_legion_memory),
       (val_add, ":memory", ":weight"),
       (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_legion_memory, ":memory"),
     (try_end),
     (try_begin),
       (lt, ":trust", 25),
       (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_warning_state, sod_mentor_warning_bitter),
     (else_try),
       (lt, ":trust", 45),
       (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_warning_state, sod_mentor_warning_strained),
     (else_try),
       (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_warning_state, sod_mentor_warning_none),
     (try_end),
   (try_end),
 ]),

("sod_strategy_advisor_start_last_order",
 [
   (call_script, "script_sod_quest_runtime_accept", "qst_companion_cassian_last_order", "trp_sod_strategy_advisor"),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_state, sod_quest_state_active),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_stage, sod_mentor_last_order_opened),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_last_actor, "trp_sod_strategy_advisor"),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_target, "fac_kingdom_6"),
   (try_begin),
     (is_between, "$current_town", centers_begin, centers_end),
     (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_last_center, "$current_town"),
   (else_try),
     (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_last_center, "p_town_6"),
   (try_end),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_metadata, sod_mentor_last_order_network_found),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_arc_stage, sod_mentor_arc_last_order),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_legion_memory, sod_mentor_last_order_opened),
   (call_script, "script_sod_quest_dialogue_record_event", "qst_companion_cassian_last_order", "trp_sod_strategy_advisor", sod_quest_event_dialogue),
   (call_script, "script_sod_quest_runtime_update", "qst_companion_cassian_last_order", "trp_sod_strategy_advisor"),
   (call_script, "script_sod_quest_journal_update"),
 ]),

("sod_strategy_advisor_resolve_last_order",
 [
   (store_script_param, ":outcome", 1),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_stage, ":outcome"),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_chain_ending, ":outcome"),
   (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_runtime_progress, 100),
   (try_begin),
     (eq, ":outcome", sod_mentor_last_order_sabotage),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_defeat_imperials, 5),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_lezalit_ief_harsh, 2),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_cassian_last_order_sabotage, 4),
     (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_reward_discount, 1),
     (str_store_string, s2, "@Cassian marks the network as weapon, not family. His counsel becomes sharper, but colder."),
   (else_try),
     (eq, ":outcome", sod_mentor_last_order_rescue),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_free_captives, 5),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_help_village, 2),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_cassian_last_order_rescue, 4),
     (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_reward_honor, 2),
     (str_store_string, s2, "@Cassian sends the old names toward refuge. The order becomes conscience before strategy."),
   (else_try),
     (eq, ":outcome", sod_mentor_last_order_exposed),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_honorable_peace, 4),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_scout_warning, 2),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_cassian_last_order_expose, 4),
     (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_reward_renown, 3),
     (str_store_string, s2, "@Cassian lets the network become public truth. Some value is lost, but the ghosts are no longer useful lies."),
   (else_try),
     (eq, ":outcome", sod_mentor_last_order_burned),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_free_captives, 2),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_scout_warning, -1),
     (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_cassian_last_order_burn, 4),
     (quest_set_slot, "qst_companion_cassian_last_order", slot_quest_sod_consequence_lockout_days, 30),
     (str_store_string, s2, "@Cassian burns the old network to protect those who survived it. The strategic loss hurts him, but the mercy is clean."),
   (else_try),
     (call_script, "script_sod_strategy_advisor_apply_player_action", sod_companion_action_diplomacy_betrayal, 2),
     (str_store_string, s2, "@Cassian closes the order without peace. The old names remain dangerous and unresolved."),
   (try_end),
   (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_legion_memory, ":outcome"),
   (call_script, "script_sod_quest_dialogue_record_event", "qst_companion_cassian_last_order", "trp_sod_strategy_advisor", sod_quest_event_stage_complete),
   (call_script, "script_sod_quest_runtime_update", "qst_companion_cassian_last_order", "trp_sod_strategy_advisor"),
   (call_script, "script_sod_quest_runtime_complete", "qst_companion_cassian_last_order", "trp_sod_strategy_advisor"),
   (call_script, "script_sod_quest_outcome_apply_consequences", "qst_companion_cassian_last_order"),
   (call_script, "script_sod_quest_journal_update"),
   (display_message, "@Advisor report: {s2}", 0xCCCC66),
 ]),

("sod_strategy_advisor_record_imperial_victory",
 [
   (try_begin),
     (troop_slot_eq, "trp_sod_strategy_advisor", slot_troop_sod_mentor_first_imperial_victory, 0),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_first_imperial_victory, 1),
   (try_end),
   (assign, ":friendly_realms", 0),
   (try_for_range, ":kingdom_no", kingdoms_begin, kingdoms_end),
     (neq, ":kingdom_no", "fac_player_supporters_faction"),
     (neq, ":kingdom_no", "fac_kingdom_6"),
     (store_relation, ":relation", "fac_player_supporters_faction", ":kingdom_no"),
     (ge, ":relation", 20),
     (val_add, ":friendly_realms", 1),
   (try_end),
   (try_begin),
     (ge, ":friendly_realms", 3),
     (troop_slot_eq, "trp_sod_strategy_advisor", slot_troop_sod_mentor_alliance_victory, 0),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_alliance_victory, 1),
   (try_end),
   (try_begin),
     (faction_get_slot, ":badboy", "fac_player_supporters_faction", slot_faction_badboy_rating),
     (ge, ":badboy", 30),
     (troop_slot_eq, "trp_sod_strategy_advisor", slot_troop_sod_mentor_ruthless_victory, 0),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_ruthless_victory, 1),
   (try_end),
 ]),

("sod_strategy_advisor_record_centurion_death",
 [
   (store_script_param, ":troop_no", 1),
   (store_troop_faction, ":troop_faction", ":troop_no"),
   (try_begin),
     (eq, ":troop_faction", "fac_kingdom_6"),
     (neg|faction_slot_eq, "fac_kingdom_6", slot_faction_leader, ":troop_no"),
     (troop_slot_eq, "trp_sod_strategy_advisor", slot_troop_sod_mentor_centurion_death, 0),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_centurion_death, 1),
   (try_end),
 ]),

("sod_strategy_advisor_note_treaty_signed",
 [
   (store_script_param_1, ":source_faction"),
   (store_script_param_2, ":partner_faction"),
   (store_script_param, ":treaty_type", 3),
   (assign, ":player_involved", 0),
   (try_begin),
     (this_or_next|eq, ":source_faction", "fac_player_supporters_faction"),
     (eq, ":partner_faction", "fac_player_supporters_faction"),
     (assign, ":player_involved", 1),
   (try_end),
   (try_begin),
     (gt, "$players_kingdom", 0),
     (this_or_next|eq, ":source_faction", "$players_kingdom"),
     (eq, ":partner_faction", "$players_kingdom"),
     (assign, ":player_involved", 1),
   (try_end),
   (try_begin),
     (eq, ":player_involved", 1),
     (store_current_day, ":cur_day"),
     (troop_get_slot, ":last_comment_day", "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_treaty_comment_day),
     (store_sub, ":days_since_comment", ":cur_day", ":last_comment_day"),
     (this_or_next|eq, ":last_comment_day", 0),
     (ge, ":days_since_comment", 1),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_treaty_comment_day, ":cur_day"),
     (try_begin),
       (eq, ":treaty_type", sod_diplomacy_treaty_anti_imperial_league),
       (str_store_string, s2, "@Cassian says an anti-Imperial league is not friendship. It is a map full of locked gates, burnt bridges, and delayed marching orders. Good. Every day bought before the Legion arrives is a day your allies can turn into steel."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_defensive_pact),
       (str_store_string, s2, "@Cassian calls a defensive pact a promise with a shield behind it. Keep that border quiet and you may force the Legion to fight through someone else's prepared wall first."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_truce),
       (str_store_string, s2, "@Cassian says a truce is not peace, my liege. It is one fewer knife at your back while you prepare for the Imperial blade in front of you."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_trade_accord),
       (str_store_string, s2, "@Cassian says trade accords win ugly wars quietly. Grain and iron moving under seal can delay the Legion as surely as a battle line."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_non_aggression),
       (str_store_string, s2, "@Cassian says a non-aggression pact buys silence. Spend that silence building friends, roads, and stores before the Imperial scouts count your empty barns."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_military_access),
       (str_store_string, s2, "@Cassian says military access is useful only if you use it before the enemy does. Mark the roads now; the Legion will not ask politely."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_prisoner_exchange),
       (str_store_string, s2, "@Cassian says prisoner exchanges turn grief into leverage. They also remind other rulers that your word can carry men home alive."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_anti_slaver_compact),
       (str_store_string, s2, "@Cassian says an anti-slaver compact will anger the markets that feed on chaos. Good. The Legion thrives where people are already broken."),
     (else_try),
       (eq, ":treaty_type", sod_diplomacy_treaty_border_security_pact),
       (str_store_string, s2, "@Cassian says border security is not glamorous, but safe roads make loyal allies and late invaders. The Legion hates roads it cannot poison."),
     (else_try),
       (this_or_next|eq, ":treaty_type", sod_diplomacy_treaty_tribute),
       (eq, ":treaty_type", sod_diplomacy_treaty_demand_tribute),
       (str_store_string, s2, "@Cassian says tribute can buy time, but it leaves fingerprints. If you purchase one quiet frontier, make certain another does not call you coward for it."),
     (else_try),
       (str_store_string, s2, "@Cassian says one more signed agreement means one fewer uncertainty. Keep building the web before the Legion tries to burn through it."),
     (try_end),
     (display_message, "@Advisor report: {s2}", 0xCCCC66),
   (try_end),
 ]),

("sod_strategy_advisor_warn_many_fronts",
 [
   (store_script_param_1, ":faction_no"),
   (store_script_param_2, ":enemy_count"),
   (assign, ":is_player_realm", 0),
   (try_begin),
     (eq, ":faction_no", "fac_player_supporters_faction"),
     (assign, ":is_player_realm", 1),
   (try_end),
   (try_begin),
     (gt, "$players_kingdom", 0),
     (eq, ":faction_no", "$players_kingdom"),
     (assign, ":is_player_realm", 1),
   (try_end),
   (try_begin),
     (eq, ":is_player_realm", 1),
     (ge, ":enemy_count", 3),
     (store_current_day, ":cur_day"),
     (troop_get_slot, ":last_warning_day", "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_front_warning_day),
     (store_sub, ":days_since_warning", ":cur_day", ":last_warning_day"),
     (this_or_next|eq, ":last_warning_day", 0),
     (ge, ":days_since_warning", 7),
     (troop_set_slot, "trp_sod_strategy_advisor", slot_troop_sod_mentor_last_front_warning_day, ":cur_day"),
     (assign, reg1, ":enemy_count"),
     (display_message, "@Cassian warns that {reg1} active fronts will not make you look strong when the Legion comes. Close one border, buy one truce, or turn one enemy into a shield.", 0xFFCC66),
   (try_end),
 ]),

("sod_strategy_advisor_note_imperial_diplomacy_exception",
 [
   (store_script_param_1, ":source_faction"),
   (store_script_param_2, ":target_faction"),
   (store_script_param, ":treaty_type", 3),
   (assign, ":player_involved", 0),
   (try_begin),
     (this_or_next|eq, ":source_faction", "fac_player_supporters_faction"),
     (this_or_next|eq, ":target_faction", "fac_player_supporters_faction"),
     (this_or_next|eq, ":source_faction", "$players_kingdom"),
     (eq, ":target_faction", "$players_kingdom"),
     (assign, ":player_involved", 1),
   (try_end),
   (try_begin),
     (eq, ":player_involved", 1),
     (eq, ":target_faction", "fac_kingdom_6"),
     (assign, reg1, ":treaty_type"),
     (display_message, "@Cassian says the Imperial Expeditionary Force is outside normal diplomacy. Do not send them treaties. Send delays, allies, saboteurs, or armies.", 0xFFCC66),
   (try_end),
 ]),

("sod_strategy_advisor_describe_company_morale_to_s3",
 [
   (call_script, "script_sod_company_accounts_update_morale_pressure"),
   (call_script, "script_sod_company_accounts_get_due_to_regs"),
   (assign, ":total_due", reg22),
   (assign, ":days_since_full_pay", reg24),
   (assign, ":pay_confidence", "$g_sod_company_pay_confidence"),
   (assign, ":camp_strain", "$g_sod_company_camp_strain"),
   (assign, ":ration_confidence", "$g_sod_company_ration_confidence"),
   (assign, ":noble_restlessness", "$g_sod_company_noble_restlessness"),
   (assign, ":last_spokesman_response", "$g_sod_company_spokesperson_last_response"),
   (assign, ":mutiny_stage", "$g_sod_company_mutiny_stage"),
   (try_begin),
     (this_or_next|eq, ":last_spokesman_response", sod_company_spokesperson_response_threaten),
     (ge, ":mutiny_stage", sod_company_mutiny_stage_warning),
      (str_store_string, s3, "@Threats can quiet a man for an hour, my liege. They do not make him loyal. If the company hears fear where it expected pay or justice, the next complaint will come with harder men behind it."),
   (else_try),
     (this_or_next|gt, ":total_due", 0),
     (ge, ":days_since_full_pay", 7),
      (str_store_string, s3, "@The men are counting missed pay by memory now, not by ink. Settle what you can, and give a plain date for the rest. A soldier will endure poverty better than being made a fool."),
   (else_try),
     (ge, ":noble_restlessness", 45),
      (str_store_string, s3, "@Your noble and faith troops are restless. Coin will not be enough for them. They want honor in public: a worthy battle, a tournament, rites, or praise where lesser men can hear it."),
   (else_try),
     (le, ":pay_confidence", 35),
      (str_store_string, s3, "@The company is beginning to doubt your purse. Once men count excuses instead of victories, even full bowls taste thin. Pay before you ask them to bleed again."),
   (else_try),
     (this_or_next|lt, ":ration_confidence", 45),
     (ge, ":camp_strain", 45),
      (str_store_string, s3, "@The company is not breaking, but the fires are quieter than they should be. Give them food they can see, rest they can feel, and pay they do not have to beg for."),
   (else_try),
     (ge, ":pay_confidence", 70),
     (le, ":camp_strain", 25),
     (ge, ":ration_confidence", 65),
      (str_store_string, s3, "@The company is sound. The men know when they are paid, fed, and led. Keep that rhythm and hard orders will reach them before fear does."),
   (else_try),
      (str_store_string, s3, "@The company is holding, my liege. Not thriving, not failing. Watch the purse, the bread, and the pride of the men who think themselves above common hirelings."),
   (try_end),
 ]),

("sod_strategy_advisor_describe_center_health_to_s4",
 [
   (assign, ":realm_faction", "fac_player_supporters_faction"),
   (try_begin),
     (gt, "$players_kingdom", 0),
     (assign, ":realm_faction", "$players_kingdom"),
   (try_end),
   (assign, ":worst_village", -1),
   (assign, ":worst_village_score", 101),
   (assign, ":weak_castle", -1),
   (assign, ":weak_castle_support", 101),
   (assign, ":worst_town", -1),
   (assign, ":worst_town_score", 101),
   (try_for_range, ":village_no", villages_begin, villages_end),
     (store_faction_of_party, ":center_faction", ":village_no"),
     (eq, ":center_faction", ":realm_faction"),
     (party_get_slot, ":health", ":village_no", slot_center_sod_local_health),
     (party_get_slot, ":population", ":village_no", slot_center_sod_local_population),
     (party_get_slot, ":prosperity", ":village_no", slot_center_sod_local_prosperity),
     (store_add, ":village_score", ":health", ":prosperity"),
     (val_add, ":village_score", ":population"),
     (val_div, ":village_score", 3),
     (lt, ":village_score", ":worst_village_score"),
     (assign, ":worst_village_score", ":village_score"),
     (assign, ":worst_village", ":village_no"),
   (try_end),
   (try_for_range, ":castle_no", castles_begin, castles_end),
     (store_faction_of_party, ":center_faction", ":castle_no"),
     (eq, ":center_faction", ":realm_faction"),
     (call_script, "script_sod_get_castle_support_profile", ":castle_no"),
     (assign, ":castle_support", reg0),
     (lt, ":castle_support", ":weak_castle_support"),
     (assign, ":weak_castle_support", ":castle_support"),
     (assign, ":weak_castle", ":castle_no"),
   (try_end),
   (try_for_range, ":town_no", towns_begin, towns_end),
     (store_faction_of_party, ":center_faction", ":town_no"),
     (eq, ":center_faction", ":realm_faction"),
     (party_get_slot, ":health", ":town_no", slot_center_sod_local_health),
     (party_get_slot, ":prosperity", ":town_no", slot_center_sod_local_prosperity),
     (store_add, ":town_score", ":health", ":prosperity"),
     (val_div, ":town_score", 2),
     (try_begin),
       (faction_slot_eq, ":realm_faction", slot_faction_diplomacy_decree_war_taxes, 1),
       (val_sub, ":town_score", 15),
     (try_end),
     (lt, ":town_score", ":worst_town_score"),
     (assign, ":worst_town_score", ":town_score"),
     (assign, ":worst_town", ":town_no"),
   (try_end),
   (try_begin),
     (is_between, ":worst_village", villages_begin, villages_end),
     (lt, ":worst_village_score", 45),
     (str_store_party_name, s5, ":worst_village"),
     (assign, reg5, ":worst_village_score"),
     (str_store_string, s4, "@Villages are the economic roots of your realm. {s5} is weak enough to matter. Its root score is {reg5}. If villages cannot produce food, cattle, recruits, and labor, castles become mouths without fields and towns become markets arguing over empty carts."),
   (else_try),
     (is_between, ":weak_castle", castles_begin, castles_end),
     (lt, ":weak_castle_support", 60),
     (str_store_party_name, s5, ":weak_castle"),
     (assign, reg5, ":weak_castle_support"),
     (str_store_string, s4, "@{s5} lacks support. Castle support stands at {reg5}. A castle is not a town with thicker walls; it needs attached villages, stores, road control, and administration. Without those, the garrison is only a delayed surrender."),
   (else_try),
     (is_between, ":worst_town", towns_begin, towns_end),
     (lt, ":worst_town_score", 50),
     (str_store_party_name, s5, ":worst_town"),
     (assign, reg5, ":worst_town_score"),
     (try_begin),
       (faction_slot_eq, ":realm_faction", slot_faction_diplomacy_decree_war_taxes, 1),
       (str_store_string, s4, "@{s5} is under town strain. Health, prosperity, and war-tax pressure leave it at {reg5}. Starving or diseased towns do not become loyal because the crown needs coin. Ease taxes, move food, and secure the roads before revenue becomes unrest."),
     (else_try),
       (str_store_string, s4, "@{s5} is showing town strain. Health and prosperity leave it at {reg5}. If it is starving, move grain. If it is diseased, fund recovery. If trade has stopped, secure the roads before the market forgets how to breathe."),
     (try_end),
   (else_try),
     (str_store_string, s4, "@The realm's center health is not yet screaming, which is when counsel matters most. Keep villages productive, castles supported by their hinterland, and towns fed before disease, hunger, or tax pressure teaches people to measure your rule by absence."),
   (try_end),
 ]),
]
