# COST: local party scan
SCRIPTS = [
("sod_get_castle_patrol_demand",
 [
   (store_script_param, ":castle_no", 1),
   (assign, ":demand", 0),
   (assign, ":role", sod_castle_patrol_role_road),
   (assign, ":target", ":castle_no"),
   (assign, ":urgency", 0),
   (assign, ":threat", 0),

   (try_begin),
     (is_between, ":castle_no", castles_begin, castles_end),
     (store_faction_of_party, ":castle_faction", ":castle_no"),
     (call_script, "script_sod_get_castle_support_profile", ":castle_no"),
     (assign, ":road_control", reg6),
     (assign, ":village_protection", reg16),
     (try_begin),
       (lt, ":road_control", 30),
       (val_add, ":demand", 25),
       (assign, ":role", sod_castle_patrol_role_road),
     (try_end),
     (try_begin),
       (lt, ":village_protection", 35),
       (val_add, ":demand", 20),
       (assign, ":role", sod_castle_patrol_role_village_shield),
     (try_end),
     (try_begin),
       (faction_slot_eq, ":castle_faction", slot_faction_diplomacy_decree_road_patrol, 1),
       (val_add, ":demand", 20),
     (try_end),

     (faction_get_slot, ":faction_ai_state", ":castle_faction", slot_faction_ai_state),
     (faction_get_slot, ":faction_ai_object", ":castle_faction", slot_faction_ai_object),
     (faction_get_slot, ":marshal_coordination", ":castle_faction", slot_faction_sod_marshal_coordination_score),
     (faction_get_slot, ":marshal_offense", ":castle_faction", slot_faction_sod_marshal_offensive_readiness),
     (faction_get_slot, ":marshal_caution", ":castle_faction", slot_faction_sod_marshal_caution_score),
     (faction_get_slot, ":morale_pressure", ":castle_faction", slot_faction_sod_lord_morale_pressure),
     (try_begin),
       (this_or_next|eq, ":faction_ai_state", sfai_attacking_center),
       (eq, ":faction_ai_state", sfai_attacking_enemies_around_center),
       (is_between, ":faction_ai_object", walled_centers_begin, walled_centers_end),
       (store_distance_to_party_from_party, ":campaign_dist", ":castle_no", ":faction_ai_object"),
       (le, ":campaign_dist", 24),
       (val_add, ":demand", 18),
       (assign, ":role", sod_castle_patrol_role_campaign_screen),
       (assign, ":target", ":faction_ai_object"),
       (party_set_slot, ":castle_no", slot_center_sod_patrol_campaign_screen_request, 1),
       (try_begin),
         (ge, ":marshal_coordination", 60),
         (ge, ":marshal_offense", 55),
         (val_add, ":demand", 18),
       (else_try),
         (lt, ":marshal_coordination", 35),
         (val_add, ":demand", 10),
         (assign, ":role", sod_castle_patrol_role_road),
       (try_end),
     (else_try),
       (party_set_slot, ":castle_no", slot_center_sod_patrol_campaign_screen_request, 0),
     (try_end),
     (try_begin),
       (neg|is_between, ":faction_ai_object", walled_centers_begin, walled_centers_end),
       (party_set_slot, ":castle_no", slot_center_sod_patrol_campaign_screen_request, 0),
     (try_end),
     (try_begin),
       (ge, ":morale_pressure", 25),
       (val_add, ":demand", 12),
       (try_begin),
         (this_or_next|eq, ":role", sod_castle_patrol_role_border_harasser),
         (eq, ":role", sod_castle_patrol_role_campaign_screen),
         (assign, ":role", sod_castle_patrol_role_village_shield),
       (try_end),
     (try_end),
     (try_begin),
       (ge, ":marshal_caution", 60),
       (ge, ":morale_pressure", 20),
       (try_begin),
         (eq, ":role", sod_castle_patrol_role_border_harasser),
         (assign, ":role", sod_castle_patrol_role_road),
       (try_end),
     (try_end),

     (try_for_range, ":village_no", villages_begin, villages_end),
       (party_slot_eq, ":village_no", slot_village_bound_center, ":castle_no"),
       (party_get_slot, ":village_state", ":village_no", slot_village_state),
       (try_begin),
         (eq, ":village_state", svs_being_raided),
         (val_add, ":demand", 60),
         (assign, ":role", sod_castle_patrol_role_emergency_relief),
         (assign, ":target", ":village_no"),
         (val_add, ":threat", 40),
       (else_try),
         (this_or_next|eq, ":village_state", svs_looted),
         (eq, ":village_state", svs_recovering),
         (val_add, ":demand", 20),
         (try_begin),
           (eq, ":role", sod_castle_patrol_role_road),
           (assign, ":role", sod_castle_patrol_role_village_shield),
           (assign, ":target", ":village_no"),
         (try_end),
       (try_end),
     (try_end),

     (try_for_parties, ":cur_party"),
       (store_distance_to_party_from_party, ":dist", ":castle_no", ":cur_party"),
       (le, ":dist", 12),
       (party_get_template_id, ":template", ":cur_party"),
       (store_faction_of_party, ":party_faction", ":cur_party"),
       (try_begin),
         (this_or_next|eq, ":template", "pt_bandits"),
         (this_or_next|eq, ":template", "pt_mountain_bandits"),
         (this_or_next|eq, ":template", "pt_forest_bandits"),
         (this_or_next|eq, ":template", "pt_steppe_bandits"),
         (this_or_next|eq, ":template", "pt_sea_raiders"),
         (this_or_next|eq, ":template", "pt_deserters"),
         (this_or_next|eq, ":template", "pt_sod_deserters"),
         (eq, ":template", "pt_sod_merc_deserters"),
         (val_add, ":demand", 12),
         (val_add, ":threat", 10),
         (try_begin),
           (eq, ":target", ":castle_no"),
           (assign, ":target", ":cur_party"),
         (try_end),
       (else_try),
         (lt, ":party_faction", kingdoms_end),
         (ge, ":party_faction", kingdoms_begin),
         (store_relation, ":relation", ":castle_faction", ":party_faction"),
         (lt, ":relation", 0),
         (party_get_num_companions, ":enemy_size", ":cur_party"),
         (le, ":enemy_size", 45),
         (val_add, ":demand", 18),
         (val_add, ":threat", 15),
         (assign, ":role", sod_castle_patrol_role_border_harasser),
         (try_begin),
           (eq, ":target", ":castle_no"),
           (assign, ":target", ":cur_party"),
         (try_end),
       (try_end),
     (try_end),

     (try_for_range, ":lord_no", kingdom_heroes_begin, kingdom_heroes_end),
       (store_troop_faction, ":lord_faction", ":lord_no"),
       (eq, ":lord_faction", ":castle_faction"),
       (troop_get_slot, ":lord_party", ":lord_no", slot_troop_leaded_party),
       (gt, ":lord_party", 0),
       (party_is_active, ":lord_party"),
       (store_distance_to_party_from_party, ":lord_dist", ":castle_no", ":lord_party"),
       (le, ":lord_dist", 18),
       (troop_get_slot, ":lord_morale", ":lord_no", slot_troop_sod_lord_party_morale),
       (troop_get_slot, ":lord_intent", ":lord_no", slot_troop_sod_lord_strategic_intent),
       (try_begin),
         (is_between, ":lord_morale", 1, 40),
         (val_add, ":demand", 10),
         (try_begin),
           (eq, ":role", sod_castle_patrol_role_border_harasser),
           (assign, ":role", sod_castle_patrol_role_road),
         (try_end),
       (try_end),
       (try_begin),
         (eq, ":lord_intent", sod_lord_intent_defending_home),
         (troop_get_slot, ":home_center", ":lord_no", slot_troop_home),
         (this_or_next|eq, ":home_center", ":castle_no"),
         (le, ":lord_dist", 8),
         (val_add, ":demand", 14),
         (assign, ":role", sod_castle_patrol_role_village_shield),
       (try_end),
       (try_begin),
         (eq, ":lord_intent", sod_lord_intent_siege_ready),
         (ge, ":marshal_coordination", 50),
         (val_add, ":demand", 8),
         (assign, ":role", sod_castle_patrol_role_campaign_screen),
       (try_end),
     (try_end),

     (try_begin),
       (ge, ":marshal_offense", 60),
       (lt, ":morale_pressure", 20),
       (ge, ":demand", 35),
       (eq, ":role", sod_castle_patrol_role_road),
       (assign, ":role", sod_castle_patrol_role_campaign_screen),
     (else_try),
       (ge, ":morale_pressure", 40),
       (try_begin),
         (eq, ":role", sod_castle_patrol_role_border_harasser),
         (assign, ":role", sod_castle_patrol_role_village_shield),
       (try_end),
     (try_end),

     (try_begin),
       (ge, ":demand", 80),
       (assign, ":urgency", 3),
     (else_try),
       (ge, ":demand", 45),
       (assign, ":urgency", 2),
     (else_try),
       (gt, ":demand", 0),
       (assign, ":urgency", 1),
     (try_end),
   (try_end),

   (assign, reg0, ":demand"),
   (assign, reg1, ":role"),
   (assign, reg2, ":target"),
   (assign, reg3, ":urgency"),
   (assign, reg4, ":threat"),
 ]),
]
