# COST: low
SCRIPTS = [
("sod_describe_player_mercenary_guild_halls_to_s20",
 [
   (assign, ":found", 0),
   (str_store_string, s20, "@No personally held castle has a guild hall."),

   (call_script, "script_get_number_of_hero_centers", "trp_player"),
   (assign, ":no_centers", reg0),
   (try_for_range, ":i_center", 0, ":no_centers"),
     (call_script, "script_troop_get_leaded_center_with_index", "trp_player", ":i_center"),
     (assign, ":center_no", reg0),
     (is_between, ":center_no", castles_begin, castles_end),
     (party_slot_eq, ":center_no", slot_center_has_mercenary_guild_hall, 1),
     (call_script, "script_sod_center_refresh_mercenary_guild_hall_stock", ":center_no"),
     (str_store_party_name, s21, ":center_no"),
     (party_get_slot, ":troop", ":center_no", slot_center_sod_merc_hall_troop_type),
     (party_get_slot, ":amount", ":center_no", slot_center_sod_merc_hall_troop_amount),
     (party_get_slot, ":guild", ":center_no", slot_center_sod_merc_hall_guild),
     (assign, reg21, ":amount"),
     (try_begin),
       (gt, ":guild", 0),
       (str_store_faction_name, s22, ":guild"),
       (try_begin),
         (gt, ":amount", 0),
         (str_store_troop_name_by_count, s23, ":troop", ":amount"),
         (str_store_string, s24, "@{s21}: {s22} pact, {reg21} {s23} ready."),
       (else_try),
         (str_store_string, s24, "@{s21}: {s22} pact, no stock this week."),
       (try_end),
     (else_try),
       (try_begin),
         (gt, ":amount", 0),
         (str_store_troop_name_by_count, s23, ":troop", ":amount"),
         (str_store_string, s24, "@{s21}: independent office, {reg21} {s23} ready."),
       (else_try),
         (str_store_string, s24, "@{s21}: independent office, no stock this week."),
       (try_end),
     (try_end),
     (try_begin),
       (eq, ":found", 0),
       (str_store_string, s20, "@{s24}"),
       (assign, ":found", 1),
     (else_try),
       (str_store_string_reg, s97, s20),
       (str_store_string, s20, "@{s97}^{s24}"),
     (try_end),
   (try_end),
 ]),
]
