# COST: low
SCRIPTS = [
("sod_add_castle_patrol_troops",
 [
   (store_script_param, ":patrol_party", 1),
   (store_script_param, ":origin_castle", 2),
   (store_script_param, ":faction_no", 3),
   (store_script_param, ":role", 4),
   (store_script_param, ":quality", 5),
   (store_script_param, ":urgency", 6),

   (assign, ":target_size", 12),
   (try_begin),
     (eq, ":role", sod_castle_patrol_role_village_shield),
     (assign, ":target_size", 16),
   (else_try),
     (eq, ":role", sod_castle_patrol_role_road),
     (assign, ":target_size", 18),
   (else_try),
     (this_or_next|eq, ":role", sod_castle_patrol_role_border_harasser),
     (eq, ":role", sod_castle_patrol_role_caravan_screen),
     (assign, ":target_size", 22),
   (else_try),
     (this_or_next|eq, ":role", sod_castle_patrol_role_campaign_screen),
     (eq, ":role", sod_castle_patrol_role_emergency_relief),
     (assign, ":target_size", 26),
   (try_end),
   (store_div, ":quality_bonus", ":quality", 20),
   (val_add, ":target_size", ":quality_bonus"),
   (val_add, ":target_size", ":urgency"),
   (val_clamp, ":target_size", 10, 31),

   (faction_get_slot, ":template_a", ":faction_no", slot_faction_reinforcements_a),
   (faction_get_slot, ":template_b", ":faction_no", slot_faction_reinforcements_b),
   (faction_get_slot, ":template_c", ":faction_no", slot_faction_reinforcements_c),
   (try_begin),
     (this_or_next|eq, ":role", sod_castle_patrol_role_border_harasser),
     (eq, ":role", sod_castle_patrol_role_caravan_screen),
     (gt, ":template_c", 0),
     (party_add_template, ":patrol_party", ":template_c"),
   (else_try),
     (ge, ":quality", 70),
     (gt, ":template_b", 0),
     (party_add_template, ":patrol_party", ":template_b"),
   (else_try),
     (gt, ":template_a", 0),
     (party_add_template, ":patrol_party", ":template_a"),
   (try_end),
   (try_begin),
     (party_slot_eq, ":origin_castle", slot_center_has_stables, 1),
     (neq, ":role", sod_castle_patrol_role_village_shield),
     (gt, ":template_c", 0),
     (party_add_template, ":patrol_party", ":template_c"),
   (try_end),

   (party_get_num_companions, ":active_size", ":patrol_party"),
   (try_begin),
     (lt, ":active_size", 10),
     (store_sub, ":shortfall", 10, ":active_size"),
     (party_add_members, ":patrol_party", "trp_watchman", ":shortfall"),
   (try_end),
   (party_get_num_companions, ":active_size", ":patrol_party"),
   (try_begin),
     (lt, ":active_size", ":target_size"),
     (store_sub, ":shortfall", ":target_size", ":active_size"),
     (val_min, ":shortfall", 8),
     (party_add_members, ":patrol_party", "trp_watchman", ":shortfall"),
   (try_end),
   (call_script, "script_sod_trim_party_active_troops", ":patrol_party", 30),
   (party_get_num_companions, reg0, ":patrol_party"),
 ]),
]
