# COST: low
SCRIPTS = [
("sod_castle_patrol_apply_success",
 [
   (store_script_param, ":patrol_party", 1),
   (party_get_slot, ":origin", ":patrol_party", slot_party_sod_patrol_origin_castle),
   (party_get_slot, ":role", ":patrol_party", slot_party_sod_patrol_role),
   (try_begin),
     (gt, ":origin", 0),
     (try_begin),
       (eq, ":role", sod_castle_patrol_role_road),
       (store_current_day, ":cur_day"),
       (party_set_slot, ":origin", slot_center_sod_patrol_road_preference, ":cur_day"),
       (party_get_slot, ":security", ":origin", slot_center_sod_security_cache_security),
       (val_add, ":security", 2),
       (party_set_slot, ":origin", slot_center_sod_security_cache_security, ":security"),
       (party_get_slot, ":threat", ":origin", slot_center_sod_security_cache_effective_threat),
       (val_sub, ":threat", 1),
       (val_max, ":threat", 0),
       (party_set_slot, ":origin", slot_center_sod_security_cache_effective_threat, ":threat"),
     (else_try),
       (eq, ":role", sod_castle_patrol_role_village_shield),
       (party_get_slot, ":protection", ":origin", slot_center_sod_security_cache_raid_resistance),
       (val_add, ":protection", 2),
       (party_set_slot, ":origin", slot_center_sod_security_cache_raid_resistance, ":protection"),
     (else_try),
       (eq, ":role", sod_castle_patrol_role_border_harasser),
       (party_get_slot, ":bandit_pressure", ":origin", slot_center_sod_security_cache_bandit_reduction),
       (val_add, ":bandit_pressure", 2),
       (party_set_slot, ":origin", slot_center_sod_security_cache_bandit_reduction, ":bandit_pressure"),
     (else_try),
       (eq, ":role", sod_castle_patrol_role_caravan_screen),
       (store_current_day, ":cur_day"),
       (party_set_slot, ":origin", slot_center_sod_patrol_road_preference, ":cur_day"),
       (party_get_slot, ":trade_security", ":origin", slot_center_sod_security_cache_contract_security),
       (val_add, ":trade_security", 2),
       (party_set_slot, ":origin", slot_center_sod_security_cache_contract_security, ":trade_security"),
       (party_get_slot, ":security", ":origin", slot_center_sod_security_cache_security),
       (val_add, ":security", 1),
       (party_set_slot, ":origin", slot_center_sod_security_cache_security, ":security"),
     (else_try),
       (eq, ":role", sod_castle_patrol_role_campaign_screen),
       (party_get_slot, ":warning", ":origin", slot_center_sod_security_cache_warning_range),
       (val_add, ":warning", 1),
       (party_set_slot, ":origin", slot_center_sod_security_cache_warning_range, ":warning"),
     (else_try),
       (eq, ":role", sod_castle_patrol_role_emergency_relief),
       (party_get_slot, ":threat", ":origin", slot_center_sod_security_cache_effective_threat),
       (val_sub, ":threat", 2),
       (val_max, ":threat", 0),
       (party_set_slot, ":origin", slot_center_sod_security_cache_effective_threat, ":threat"),
     (try_end),
     (call_script, "script_sod_apply_castle_patrol_population_effect", ":origin", ":role", 1),
     (call_script, "script_sod_dispatch_castle_patrol_companion_action", ":role", 1),
   (try_end),
 ]),
]
