# COST: O(bound villages for towns)
SCRIPTS = [
("sod_get_center_trade_demand_profile",
  [
    (store_script_param, ":center_no", 1),

    (assign, ":scarcity_pressure", 0),
    (assign, ":import_demand", 0),
    (assign, ":export_supply", 0),
    (assign, ":market_liquidity", 0),
    (assign, ":security_willingness", 100),
    (assign, ":tax_friction", 0),
    (assign, ":caravan_attractiveness", 0),
    (assign, ":effective_trade_volume", 100),

    (assign, ":population", 0),
    (assign, ":prosperity", 0),
    (assign, ":wealth", 0),
    (try_begin),
      (this_or_next|is_between, ":center_no", towns_begin, towns_end),
      (this_or_next|is_between, ":center_no", villages_begin, villages_end),
      (is_between, ":center_no", castles_begin, castles_end),
      (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
      (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
      (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
    (try_end),
    (val_max, ":population", 0),
    (val_max, ":prosperity", 0),
    (val_max, ":wealth", 0),

    (call_script, "script_sod_get_center_food_profile", ":center_no"),
    (assign, ":food_security", reg4),
    (assign, ":food_capacity_ratio", reg5),
    (assign, ":food_pressure", reg6),

    (call_script, "script_sod_get_center_security_profile", ":center_no"),
    (assign, ":effective_threat", reg0),
    (assign, ":security", reg1),
    (assign, ":unrest_pressure", reg8),

    (call_script, "script_sod_get_center_security_economy_profile", ":center_no"),
    (assign, ":security_trade_pct", reg0),
    (assign, ":bandit_pressure_pct", reg2),
    (assign, ":merchant_confidence", reg4),
    (assign, ":route_security", reg5),

    (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
    (assign, ":tax_extraction_pressure", reg1),
    (assign, ":tax_liquidity_pct", reg4),
    (assign, ":tax_tariff_capture_pct", reg8),

    (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_goods_import_demand_pct),
    (assign, ":goods_import_demand_pct", reg0),
    (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_goods_export_supply_pct),
    (assign, ":goods_export_supply_pct", reg0),
    (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_trade_liquidity_flat),
    (assign, ":trade_liquidity_flat", reg0),
    (call_script, "script_sod_get_center_modifier", ":center_no", sod_center_modifier_trade_volume_pct),
    (assign, ":trade_volume_pct", reg0),

    (store_sub, ":food_store_scarcity", 75, ":food_capacity_ratio"),
    (val_clamp, ":food_store_scarcity", 0, 75),
    (store_sub, ":food_security_scarcity", 900, ":food_security"),
    (val_div, ":food_security_scarcity", 25),
    (val_clamp, ":food_security_scarcity", 0, 45),
    (store_sub, ":prosperity_scarcity", 55, ":prosperity"),
    (val_clamp, ":prosperity_scarcity", 0, 40),
    (assign, ":scarcity_pressure", ":food_store_scarcity"),
    (val_add, ":scarcity_pressure", ":food_security_scarcity"),
    (val_add, ":scarcity_pressure", ":prosperity_scarcity"),
    (val_add, ":scarcity_pressure", ":food_pressure"),
    (store_mul, ":threat_scarcity", ":effective_threat", 3),
    (val_add, ":scarcity_pressure", ":threat_scarcity"),
    (val_clamp, ":scarcity_pressure", 0, 201),

    (try_begin),
      (is_between, ":center_no", towns_begin, towns_end),
      (call_script, "script_sod_get_town_market_profile", ":center_no"),
      (assign, ":town_market_score", reg0),
      (assign, ":town_rural_surplus", reg1),
      (assign, ":town_consumption_pressure", reg2),
      (assign, ":town_import_demand", reg3),
      (assign, ":town_services", reg4),
      (assign, ":town_liquidity", reg6),
      (assign, ":town_trade_volume", reg7),
      (assign, ":town_tariff_capture", reg8),
      (assign, ":import_demand", ":town_import_demand"),
      (val_add, ":import_demand", ":scarcity_pressure"),
      (val_add, ":import_demand", ":town_consumption_pressure"),
      (assign, ":export_supply", ":town_rural_surplus"),
      (assign, ":market_liquidity", ":town_liquidity"),
      (val_add, ":market_liquidity", ":town_services"),
      (val_add, ":market_liquidity", ":town_market_score"),
      (assign, ":effective_trade_volume", ":town_trade_volume"),
      (val_mul, ":tax_tariff_capture_pct", ":town_tariff_capture"),
      (val_div, ":tax_tariff_capture_pct", 100),
    (else_try),
      (is_between, ":center_no", villages_begin, villages_end),
      (call_script, "script_sod_get_village_output_profile", ":center_no"),
      (assign, ":village_food_output", reg1),
      (assign, ":village_raw_output", reg3),
      (assign, ":village_fragility", reg6),
      (assign, ":village_reliability", reg8),
      (assign, ":import_demand", ":scarcity_pressure"),
      (store_add, ":export_supply", ":village_food_output", ":village_raw_output"),
      (val_mul, ":export_supply", ":village_reliability"),
      (val_div, ":export_supply", 100),
      (store_div, ":market_liquidity", ":wealth", 500),
      (store_sub, ":fragility_drag", ":village_fragility", 40),
      (val_max, ":fragility_drag", 0),
      (val_sub, ":market_liquidity", ":fragility_drag"),
      (store_div, ":effective_trade_volume", ":village_reliability", 2),
      (val_add, ":effective_trade_volume", 65),
    (else_try),
      (is_between, ":center_no", castles_begin, castles_end),
      (call_script, "script_sod_get_castle_support_profile", ":center_no"),
      (assign, ":castle_support", reg0),
      (assign, ":castle_food_security", reg4),
      (assign, ":castle_road_control", reg6),
      (assign, ":castle_tax_reliability", reg15),
      (assign, ":import_demand", ":scarcity_pressure"),
      (store_div, ":castle_support_liquidity", ":castle_support", 4),
      (assign, ":market_liquidity", ":castle_support_liquidity"),
      (store_div, ":castle_road_volume", ":castle_road_control", 2),
      (store_add, ":effective_trade_volume", 75, ":castle_road_volume"),
      (val_mul, ":effective_trade_volume", ":castle_tax_reliability"),
      (val_div, ":effective_trade_volume", 100),
      (try_begin),
        (gt, ":castle_food_security", 900),
        (val_add, ":export_supply", 10),
      (try_end),
    (else_try),
      (assign, ":import_demand", ":scarcity_pressure"),
      (store_div, ":market_liquidity", ":wealth", 600),
    (try_end),

    (val_mul, ":import_demand", ":goods_import_demand_pct"),
    (val_div, ":import_demand", 100),
    (val_mul, ":export_supply", ":goods_export_supply_pct"),
    (val_div, ":export_supply", 100),
    (val_add, ":market_liquidity", ":trade_liquidity_flat"),
    (store_div, ":wealth_liquidity", ":wealth", 700),
    (val_add, ":market_liquidity", ":wealth_liquidity"),
    (val_mul, ":market_liquidity", ":tax_liquidity_pct"),
    (val_div, ":market_liquidity", 100),
    (val_clamp, ":market_liquidity", 0, 501),

    (assign, ":security_willingness", ":security_trade_pct"),
    (store_div, ":security_bonus", ":security", 4),
    (val_add, ":security_willingness", ":security_bonus"),
    (store_div, ":route_bonus", ":route_security", 20),
    (val_add, ":security_willingness", ":route_bonus"),
    (store_div, ":confidence_bonus", ":merchant_confidence", 4),
    (val_add, ":security_willingness", ":confidence_bonus"),
    (store_mul, ":threat_drag", ":effective_threat", 8),
    (val_sub, ":security_willingness", ":threat_drag"),
    (store_sub, ":bandit_drag", ":bandit_pressure_pct", 100),
    (val_max, ":bandit_drag", 0),
    (val_div, ":bandit_drag", 2),
    (val_sub, ":security_willingness", ":bandit_drag"),
    (val_sub, ":security_willingness", ":unrest_pressure"),
    (val_clamp, ":security_willingness", 15, 151),

    (assign, ":tax_friction", ":tax_extraction_pressure"),
    (store_sub, ":tariff_friction", ":tax_tariff_capture_pct", 100),
    (val_max, ":tariff_friction", 0),
    (val_div, ":tariff_friction", 3),
    (val_add, ":tax_friction", ":tariff_friction"),
    (val_clamp, ":tax_friction", 0, 101),

    (val_mul, ":effective_trade_volume", ":trade_volume_pct"),
    (val_div, ":effective_trade_volume", 100),
    (val_mul, ":effective_trade_volume", ":security_willingness"),
    (val_div, ":effective_trade_volume", 100),
    (store_sub, ":volume_tax_drag", ":tax_friction", 0),
    (val_div, ":volume_tax_drag", 3),
    (val_sub, ":effective_trade_volume", ":volume_tax_drag"),
    (val_clamp, ":effective_trade_volume", 35, 181),

    (assign, ":caravan_attractiveness", ":import_demand"),
    (store_div, ":liquidity_pull", ":market_liquidity", 6),
    (val_add, ":caravan_attractiveness", ":liquidity_pull"),
    (store_div, ":export_pull", ":export_supply", 8),
    (val_add, ":caravan_attractiveness", ":export_pull"),
    (store_div, ":security_pull", ":security_willingness", 5),
    (val_add, ":caravan_attractiveness", ":security_pull"),
    (store_div, ":tax_drag", ":tax_friction", 2),
    (val_sub, ":caravan_attractiveness", ":tax_drag"),
    (try_begin),
      (lt, ":security_willingness", 55),
      (val_sub, ":caravan_attractiveness", 20),
    (try_end),
    (try_begin),
      (lt, ":market_liquidity", 25),
      (val_sub, ":caravan_attractiveness", 10),
    (try_end),
    (val_clamp, ":caravan_attractiveness", -50, 251),

    (assign, reg0, ":scarcity_pressure"),
    (assign, reg1, ":import_demand"),
    (assign, reg2, ":export_supply"),
    (assign, reg3, ":market_liquidity"),
    (assign, reg4, ":security_willingness"),
    (assign, reg5, ":tax_friction"),
    (assign, reg6, ":caravan_attractiveness"),
    (assign, reg7, ":effective_trade_volume"),
  ]),
]
