# COST: support profile + party scan
SCRIPTS = [
("sod_get_castle_patrol_capacity",
 [
   (store_script_param, ":castle_no", 1),
   (assign, ":max_active", 0),
   (assign, ":active", 0),
   (assign, ":available", 0),
   (assign, ":patrol_strength", 0),
   (assign, ":readiness", 0),
   (assign, ":failure", sod_castle_patrol_fail_none),

   (try_begin),
     (neg|is_between, ":castle_no", castles_begin, castles_end),
     (assign, ":failure", sod_castle_patrol_fail_not_castle),
   (else_try),
     (store_faction_of_party, ":castle_faction", ":castle_no"),
     (this_or_next|le, ":castle_faction", 0),
     (eq, ":castle_faction", "fac_neutral"),
     (assign, ":failure", sod_castle_patrol_fail_no_owner),
   (else_try),
     (party_get_slot, ":besieger", ":castle_no", slot_center_is_besieged_by),
     (ge, ":besieger", 0),
     (party_is_active, ":besieger"),
     (assign, ":failure", sod_castle_patrol_fail_besieged),
   (else_try),
     (call_script, "script_sod_get_castle_support_profile", ":castle_no"),
     (assign, ":garrison", reg1),
     (assign, ":food_security", reg4),
     (assign, ":road_control", reg6),
     (assign, ":commander_quality", reg10),
     (assign, ":patrol_strength", reg13),
     (assign, ":village_protection", reg16),
     (call_script, "script_sod_count_castle_patrols", ":castle_no"),
     (assign, ":active", reg0),
     (assign, ":readiness", ":patrol_strength"),
     (val_add, ":readiness", ":road_control"),
     (store_div, ":commander_readiness", ":commander_quality", 3),
     (val_add, ":readiness", ":commander_readiness"),
     (store_div, ":village_readiness", ":village_protection", 3),
     (val_add, ":readiness", ":village_readiness"),
     (try_begin),
       (party_slot_eq, ":castle_no", slot_center_has_stables, 1),
       (val_add, ":readiness", 12),
     (try_end),
     (try_begin),
       (party_slot_eq, ":castle_no", slot_center_has_messenger_post, 1),
       (val_add, ":readiness", 8),
     (try_end),
     (try_begin),
       (party_slot_eq, ":castle_no", slot_center_has_barracks, 1),
       (val_add, ":readiness", 10),
     (try_end),
     (try_begin),
       (faction_slot_eq, ":castle_faction", slot_faction_diplomacy_decree_road_patrol, 1),
       (val_add, ":readiness", 15),
     (try_end),
     (try_begin),
       (lt, ":garrison", 45),
       (assign, ":failure", sod_castle_patrol_fail_garrison_low),
     (else_try),
       (lt, ":food_security", 30),
       (assign, ":failure", sod_castle_patrol_fail_food_low),
     (else_try),
       (assign, ":max_active", 1),
       (try_begin),
         (ge, ":readiness", 130),
         (assign, ":max_active", 2),
       (try_end),
       (try_begin),
         (ge, ":readiness", 210),
         (assign, ":max_active", sod_castle_patrol_max_active),
       (try_end),
       (val_min, ":max_active", sod_castle_patrol_max_active),
       (store_sub, ":available", ":max_active", ":active"),
       (val_max, ":available", 0),
       (try_begin),
         (le, ":available", 0),
         (assign, ":failure", sod_castle_patrol_fail_no_capacity),
       (try_end),
     (try_end),
   (try_end),

   (assign, reg0, ":max_active"),
   (assign, reg1, ":active"),
   (assign, reg2, ":available"),
   (assign, reg3, ":patrol_strength"),
   (assign, reg4, ":readiness"),
   (assign, reg5, ":failure"),
 ]),
]
