# COST: O(bound villages) live profile; cached selectors use O(centers) slot reads.
SCRIPTS = [
("sod_get_center_investment_need_profile",
 [
   (store_script_param, ":center_no", 1),

   (assign, ":need_score", 0),
   (assign, ":recommended_mode", 0),
   (assign, ":health_pressure", 0),
   (assign, ":population_pressure", 0),
   (assign, ":food_pressure", 0),
   (assign, ":public_health_pressure", 0),
   (assign, ":regional_weakness", 0),
   (assign, ":food_security", 1000),

   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),
     (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":local_prosperity", ":center_no", slot_center_sod_local_prosperity),
     (val_clamp, ":health", 0, 101),
     (val_clamp, ":prosperity", 0, 101),
     (val_clamp, ":local_prosperity", 0, 101),

     # Regional flow owns settlement-type differences and the normal investment mode.
     (call_script, "script_sod_get_center_regional_flow_profile", ":center_no"),
     (assign, ":food_security", reg6),
     (assign, ":regional_weakness", reg7),
     (assign, ":recommended_mode", reg8),

     # Capacity is the authority for underpopulation rather than raw type-specific maxima.
     (call_script, "script_sod_get_center_population_capacity_profile", ":center_no"),
     (assign, ":capacity_pct", reg2),
     (try_begin),
       (lt, ":capacity_pct", 75),
       (store_sub, ":population_pressure", 75, ":capacity_pct"),
       (val_div, ":population_pressure", 2),
     (try_end),

     # Use the live public-health calculation so player menus and AI share one crisis model.
     (call_script, "script_sod_center_public_health_compute_causes", ":center_no"),
     (assign, ":disease_risk", reg4),
     (party_get_slot, ":outbreak_severity", ":center_no", slot_center_health_outbreak_severity),
     (val_clamp, ":outbreak_severity", 0, 7),

     (try_begin),
       (lt, ":health", 60),
       (store_sub, ":health_pressure", 60, ":health"),
     (try_end),
     (assign, ":economic_pressure", 0),
     (try_begin),
       (lt, ":prosperity", 60),
       (store_sub, ":prosperity_pressure", 60, ":prosperity"),
       (val_add, ":economic_pressure", ":prosperity_pressure"),
     (try_end),
     (try_begin),
       (lt, ":local_prosperity", 50),
       (store_sub, ":local_pressure", 50, ":local_prosperity"),
       (val_add, ":economic_pressure", ":local_pressure"),
     (try_end),
     (try_begin),
       (lt, ":food_security", 700),
       (store_sub, ":food_pressure", 700, ":food_security"),
       (val_div, ":food_pressure", 35),
     (try_end),
     (try_begin),
       (gt, ":disease_risk", 55),
       (store_sub, ":public_health_pressure", ":disease_risk", 55),
       (val_div, ":public_health_pressure", 2),
     (try_end),
     (try_begin),
       (gt, ":outbreak_severity", 0),
       (store_mul, ":outbreak_pressure", ":outbreak_severity", 8),
       (val_add, ":public_health_pressure", ":outbreak_pressure"),
     (try_end),

     (assign, ":need_score", ":regional_weakness"),
     (val_add, ":need_score", ":health_pressure"),
     (val_add, ":need_score", ":economic_pressure"),
     (val_add, ":need_score", ":population_pressure"),
     (val_add, ":need_score", ":food_pressure"),
     (val_add, ":need_score", ":public_health_pressure"),

     # Food and disease crises always receive emergency recovery rather than trade stimulus.
     (try_begin),
       (this_or_next|ge, ":food_pressure", 10),
       (ge, ":public_health_pressure", 18),
       (assign, ":recommended_mode", 1),
     (try_end),
   (try_end),

   (val_clamp, ":need_score", 0, 501),
   (val_clamp, ":health_pressure", 0, 61),
   (val_clamp, ":population_pressure", 0, 38),
   (val_clamp, ":food_pressure", 0, 21),
   (val_clamp, ":public_health_pressure", 0, 101),
   (val_clamp, ":regional_weakness", 0, 301),
   (val_clamp, ":food_security", 0, 2001),

   (assign, reg0, ":need_score"),
   (assign, reg1, ":recommended_mode"),
   (assign, reg2, ":health_pressure"),
   (assign, reg3, ":population_pressure"),
   (assign, reg4, ":food_pressure"),
   (assign, reg5, ":public_health_pressure"),
   (assign, reg6, ":regional_weakness"),
   (assign, reg7, ":food_security"),
 ]),

("sod_refresh_center_investment_profile",
 [
   (store_script_param, ":center_no", 1),

   (assign, ":need_score", 0),
   (assign, ":recommended_mode", 0),
   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),
     (call_script, "script_sod_get_center_investment_need_profile", ":center_no"),
     (assign, ":need_score", reg0),
     (assign, ":recommended_mode", reg1),
     (party_set_slot, ":center_no", slot_center_sod_investment_need_cache, ":need_score"),
     (party_set_slot, ":center_no", slot_center_sod_investment_mode_cache, ":recommended_mode"),
   (try_end),

   (assign, reg0, ":need_score"),
   (assign, reg1, ":recommended_mode"),
 ]),

("sod_refresh_all_center_investment_profiles",
 [
   (try_for_range, ":center_no", centers_begin, centers_end),
     (call_script, "script_sod_refresh_center_investment_profile", ":center_no"),
   (try_end),
 ]),

("sod_find_investment_target",
 [
   (store_script_param, ":investor_troop", 1),
   (store_script_param, ":scope", 2),

   (assign, ":best_center", -1),
   (assign, ":best_score", -1),
   (store_troop_faction, ":investor_faction", ":investor_troop"),

   (try_for_range, ":center_no", centers_begin, centers_end),
     (assign, ":eligible", 0),
     (try_begin),
       (eq, ":scope", 0),
       (party_slot_eq, ":center_no", slot_town_lord, ":investor_troop"),
       (assign, ":eligible", 1),
     (else_try),
       (eq, ":scope", 1),
       (store_faction_of_party, ":center_faction", ":center_no"),
       (eq, ":center_faction", ":investor_faction"),
       (faction_slot_eq, ":investor_faction", slot_faction_leader, ":investor_troop"),
       (assign, ":eligible", 1),
     (try_end),

     (eq, ":eligible", 1),
     (call_script, "script_sod_get_center_investment_need_profile", ":center_no"),
     (assign, ":score", reg0),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),

   (assign, reg0, ":best_center"),
   (assign, reg1, ":best_score"),
 ]),

("sod_find_cached_investment_target",
 [
   (store_script_param, ":investor_troop", 1),
   (store_script_param, ":scope", 2),

   (assign, ":best_center", -1),
   (assign, ":best_score", -1),
   (assign, ":best_mode", 0),
   (store_troop_faction, ":investor_faction", ":investor_troop"),

   (try_for_range, ":center_no", centers_begin, centers_end),
     (assign, ":eligible", 0),
     (try_begin),
       (eq, ":scope", 0),
       (party_slot_eq, ":center_no", slot_town_lord, ":investor_troop"),
       (assign, ":eligible", 1),
     (else_try),
       (eq, ":scope", 1),
       (store_faction_of_party, ":center_faction", ":center_no"),
       (eq, ":center_faction", ":investor_faction"),
       (faction_slot_eq, ":investor_faction", slot_faction_leader, ":investor_troop"),
       (assign, ":eligible", 1),
     (try_end),

     (eq, ":eligible", 1),
     (party_get_slot, ":score", ":center_no", slot_center_sod_investment_need_cache),
     (gt, ":score", ":best_score"),
     (party_get_slot, ":best_mode", ":center_no", slot_center_sod_investment_mode_cache),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),

   (assign, reg0, ":best_center"),
   (assign, reg1, ":best_score"),
   (assign, reg2, ":best_mode"),
 ]),
]
