# COST: Weekly center security, desperation, and hardship migration stage.
SCRIPTS = [
("sod_center_weekly_get_desperation_scores",
 [
      (store_script_param, ":prosperity", 1),
      (store_script_param, ":center_health", 2),
      (store_script_param, ":food_capacity_ratio", 3),
      (store_script_param, ":food_security", 4),
      (store_script_param, ":center_relation", 5),
      (store_script_param, ":unrest_pressure", 6),
      (store_script_param, ":effective_threat", 7),
      (store_script_param, ":trade_security_pct", 8),
      (store_script_param, ":recovery_security_pct", 9),

      (assign, ":pressure_hunger", 0),
      (assign, ":pressure_poverty", 0),
      (assign, ":pressure_sickness", 0),
      (assign, ":pressure_unrest", 0),

      (assign, ":desperation_score", 0),
      (assign, ":stability_score", 0),

      (try_begin),
        (lt, ":prosperity", 30),
        (assign, ":pressure_poverty", 1),
        (store_sub, ":tmp", 30, ":prosperity"),
        (val_add, ":desperation_score", ":tmp"),
      (else_try),
        (gt, ":prosperity", 70),
        (store_sub, ":tmp", ":prosperity", 70),
        (val_div, ":tmp", 2),
        (val_add, ":stability_score", ":tmp"),
      (try_end),

      (try_begin),
        (lt, ":center_health", 35),
        (assign, ":pressure_sickness", 1),
        (store_sub, ":tmp", 35, ":center_health"),
        (val_add, ":desperation_score", ":tmp"),
      (else_try),
        (gt, ":center_health", 70),
        (store_sub, ":tmp", ":center_health", 70),
        (val_div, ":tmp", 2),
        (val_add, ":stability_score", ":tmp"),
      (try_end),

      (try_begin),
        (lt, ":food_capacity_ratio", 20),
        (assign, ":pressure_hunger", 1),
        (store_sub, ":tmp", 20, ":food_capacity_ratio"),
        (val_mul, ":tmp", 2),
        (val_add, ":desperation_score", ":tmp"),
      (else_try),
        (lt, ":food_capacity_ratio", 45),
        (assign, ":pressure_hunger", 1),
        (store_sub, ":tmp", 45, ":food_capacity_ratio"),
        (val_div, ":tmp", 2),
        (val_add, ":desperation_score", ":tmp"),
      (else_try),
        (gt, ":food_capacity_ratio", 80),
        (store_sub, ":tmp", ":food_capacity_ratio", 80),
        (val_div, ":tmp", 2),
        (val_add, ":stability_score", ":tmp"),
      (try_end),

      (try_begin),
        (lt, ":food_security", 350),
        (assign, ":pressure_hunger", 1),
        (store_sub, ":tmp", 350, ":food_security"),
        (val_div, ":tmp", 25),
        (val_add, ":desperation_score", ":tmp"),
      (else_try),
        (lt, ":food_security", 700),
        (assign, ":pressure_hunger", 1),
        (store_sub, ":tmp", 700, ":food_security"),
        (val_div, ":tmp", 60),
        (val_add, ":desperation_score", ":tmp"),
      (else_try),
        (gt, ":food_security", 900),
        (store_sub, ":tmp", ":food_security", 900),
        (val_div, ":tmp", 120),
        (val_add, ":stability_score", ":tmp"),
      (try_end),

      (try_begin),
        (lt, ":center_relation", -10),
        (assign, ":pressure_unrest", 1),
        (store_sub, ":tmp", 0, ":center_relation"),
        (val_div, ":tmp", 2),
        (val_add, ":desperation_score", ":tmp"),
      (else_try),
        (gt, ":center_relation", 15),
        (store_sub, ":tmp", ":center_relation", 15),
        (val_div, ":tmp", 5),
        (val_add, ":stability_score", ":tmp"),
      (try_end),

      (try_begin),
        (gt, ":unrest_pressure", 20),
        (assign, ":pressure_unrest", 1),
        (store_div, ":tmp", ":unrest_pressure", 4),
        (val_add, ":desperation_score", ":tmp"),
      (try_end),
      (try_begin),
        (gt, ":effective_threat", 3),
        (store_mul, ":tmp", ":effective_threat", 3),
        (val_add, ":desperation_score", ":tmp"),
      (try_end),
      (try_begin),
        (gt, ":trade_security_pct", 115),
        (store_sub, ":tmp", ":trade_security_pct", 115),
        (val_div, ":tmp", 5),
        (val_add, ":stability_score", ":tmp"),
      (try_end),
      (try_begin),
        (gt, ":recovery_security_pct", 115),
        (store_sub, ":tmp", ":recovery_security_pct", 115),
        (val_div, ":tmp", 5),
        (val_add, ":stability_score", ":tmp"),
      (try_end),

      (assign, reg0, ":desperation_score"),
      (assign, reg1, ":stability_score"),
      (assign, reg2, ":pressure_hunger"),
      (assign, reg3, ":pressure_poverty"),
      (assign, reg4, ":pressure_sickness"),
      (assign, reg5, ":pressure_unrest"),
 ]),

("sod_center_weekly_get_desperation_spawn_chance_to_reg",
 [
      (store_script_param, ":desperation_score", 1),
      (store_script_param, ":stability_score", 2),
      (store_script_param, ":desperation_bandit_reduction", 3),
      (store_script_param, ":bandit_pressure_pct", 4),

      (assign, ":chance", sod_desperation_chance_percent),
      (val_add, ":chance", ":desperation_score"),
      (val_sub, ":chance", ":stability_score"),
      (val_sub, ":chance", ":desperation_bandit_reduction"),
      (val_mul, ":chance", ":bandit_pressure_pct"),
      (val_div, ":chance", 100),
      (val_clamp, ":chance", 5, 80),
      (assign, reg0, ":chance"),
 ]),

("sod_center_weekly_get_desperation_bandit_count_to_reg",
 [
      (store_script_param, ":desperation_score", 1),
      (store_script_param, ":bandit_pressure_pct", 2),
      (store_script_param, ":desperation_bandit_reduction", 3),
      (store_script_param, ":surplus", 4),
      (store_script_param, ":count_divisor", 5),
      (store_script_param, ":count_base", 6),
      (store_script_param, ":count_cap", 7),
      (store_script_param, ":extra_value_1", 8),
      (store_script_param, ":extra_threshold_1", 9),
      (store_script_param, ":extra_value_2", 10),
      (store_script_param, ":extra_threshold_2", 11),

      (assign, ":bandit_count", ":desperation_score"),
      (val_div, ":bandit_count", ":count_divisor"),
      (val_add, ":bandit_count", ":count_base"),
      (try_begin),
        (lt, ":extra_value_1", ":extra_threshold_1"),
        (val_add, ":bandit_count", 1),
      (try_end),
      (try_begin),
        (lt, ":extra_value_2", ":extra_threshold_2"),
        (val_add, ":bandit_count", 1),
      (try_end),
      (val_mul, ":bandit_count", ":bandit_pressure_pct"),
      (val_div, ":bandit_count", 100),
      (try_begin),
        (gt, ":desperation_bandit_reduction", 0),
        (store_div, ":tmp", ":desperation_bandit_reduction", 25),
        (val_sub, ":bandit_count", ":tmp"),
      (try_end),
      (val_min, ":bandit_count", ":surplus"),
      (val_min, ":bandit_count", ":count_cap"),
      (assign, reg0, ":bandit_count"),
 ]),

("sod_center_weekly_apply_security_desperation",
 [
    (try_begin),
      (eq, "$g_sod_hide_messages", -2),
      (set_show_messages, 0),
    (try_end),
    (set_spawn_radius, 1),
    (call_script, "script_sod_center_weekly_refresh_profile_cache"),

    (try_for_range, ":center_no", villages_begin, villages_end),
      (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":center_no"),
      (assign, ":center_population", reg0),
      (assign, ":prosperity", reg1),
      (assign, ":center_health", reg2),
      (assign, ":food_capacity_ratio", reg6),
      (assign, ":food_security", reg7),
      (assign, ":center_relation", reg8),

      (store_sub, ":surplus", ":center_population", village_pop_min),
      (ge, ":surplus", sod_desperation_pop_surplus_min),

      (call_script, "script_sod_get_center_security_economy_profile", ":center_no"),
      (assign, ":trade_security_pct", reg0),
      (assign, ":recovery_security_pct", reg1),
      (assign, ":bandit_pressure_pct", reg2),
      (call_script, "script_sod_get_center_security_profile", ":center_no"),
      (assign, ":effective_threat", reg0),
      (assign, ":desperation_bandit_reduction", reg5),
      (assign, ":unrest_pressure", reg8),

      (call_script, "script_sod_center_weekly_get_desperation_scores", ":prosperity", ":center_health", ":food_capacity_ratio", ":food_security", ":center_relation", ":unrest_pressure", ":effective_threat", ":trade_security_pct", ":recovery_security_pct"),
      (assign, ":desperation_score", reg0),
      (assign, ":stability_score", reg1),
      (assign, ":pressure_hunger", reg2),
      (assign, ":pressure_poverty", reg3),
      (assign, ":pressure_sickness", reg4),
      (assign, ":pressure_unrest", reg5),

      (gt, ":desperation_score", 0),

      (store_random_in_range, ":roll", 0, 100),
      (call_script, "script_sod_center_weekly_get_desperation_spawn_chance_to_reg", ":desperation_score", ":stability_score", ":desperation_bandit_reduction", ":bandit_pressure_pct"),
      (assign, ":chance", reg0),
      (lt, ":roll", ":chance"),

      (call_script, "script_sod_center_weekly_get_desperation_bandit_count_to_reg", ":desperation_score", ":bandit_pressure_pct", ":desperation_bandit_reduction", ":surplus", 5, 2, 18, ":food_security", 250, ":center_health", 25),
      (assign, ":bandit_count", reg0),
      (gt, ":bandit_count", 0),

      (spawn_around_party, ":center_no", "pt_bandits"),
      (assign, ":looter_party", reg0),
      (gt, ":looter_party", 0),
      (party_is_active, ":looter_party"),
      (party_clear, ":looter_party"),
      (party_add_members, ":looter_party", "trp_looter", ":bandit_count"),
      (party_set_slot, ":looter_party", slot_party_sod_threat_type, sod_threat_type_faction_problem),
      (party_set_slot, ":looter_party", slot_party_sod_threat_archetype, sod_threat_archetype_cattle_raiders),
      (party_set_slot, ":looter_party", slot_party_sod_threat_sponsor_center, ":center_no"),
      (store_faction_of_party, ":center_faction", ":center_no"),
      (party_set_slot, ":looter_party", slot_party_sod_threat_sponsor_faction, ":center_faction"),

      (store_mul, ":population_delta", ":bandit_count", -1),
      (call_script, "script_sod_center_apply_population_delta", ":center_no", ":population_delta"),
      (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":center_no", ":population_delta"),
      (try_begin),
        (eq, "$g_sod_hide_messages", 0),
        (str_store_party_name_link, s68, ":center_no"),
        (assign, reg0, ":bandit_count"),
        (try_begin),
          (eq, ":pressure_hunger", 1),
          (display_message, "@Desperation grips {s68}: empty granaries and lean stores have driven {reg0} villagers to become looters and flee into the wilds.", dark_red),
        (else_try),
          (eq, ":pressure_sickness", 1),
          (display_message, "@Desperation grips {s68}: sickness and hard living have driven {reg0} villagers into looter bands in the wilds.", dark_red),
        (else_try),
          (eq, ":pressure_unrest", 1),
          (display_message, "@Desperation grips {s68}: grievance and bitter feeling have pushed {reg0} villagers out among the looters beyond the fields.", dark_red),
        (else_try),
          (eq, ":pressure_poverty", 1),
          (display_message, "@Desperation grips {s68}: lean seasons and empty cupboards have driven {reg0} villagers to become looters and flee into the wilds.", dark_red),
        (else_try),
          (display_message, "@Desperation grips {s68}: {reg0} villagers have become looters and fled into the wilds.", dark_red),
        (try_end),
      (try_end),
    (try_end),

    (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
      (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":center_no"),
      (assign, ":center_population", reg0),
      (assign, ":prosperity", reg1),
      (assign, ":center_health", reg2),
      (assign, ":food_capacity_ratio", reg6),
      (assign, ":food_security", reg7),
      (assign, ":center_relation", reg8),

      (store_sub, ":surplus", ":center_population", town_pop_min),
      (ge, ":surplus", sod_desperation_pop_surplus_min),

      (call_script, "script_sod_get_center_security_economy_profile", ":center_no"),
      (assign, ":trade_security_pct", reg0),
      (assign, ":recovery_security_pct", reg1),
      (assign, ":bandit_pressure_pct", reg2),
      (call_script, "script_sod_get_center_security_profile", ":center_no"),
      (assign, ":effective_threat", reg0),
      (assign, ":desperation_bandit_reduction", reg5),
      (assign, ":unrest_pressure", reg8),

      (call_script, "script_sod_center_weekly_get_desperation_scores", ":prosperity", ":center_health", ":food_capacity_ratio", ":food_security", ":center_relation", ":unrest_pressure", ":effective_threat", ":trade_security_pct", ":recovery_security_pct"),
      (assign, ":desperation_score", reg0),
      (assign, ":stability_score", reg1),
      (assign, ":pressure_hunger", reg2),
      (assign, ":pressure_poverty", reg3),
      (assign, ":pressure_sickness", reg4),
      (assign, ":pressure_unrest", reg5),

      (gt, ":desperation_score", 0),

      (store_random_in_range, ":roll", 0, 100),
      (call_script, "script_sod_center_weekly_get_desperation_spawn_chance_to_reg", ":desperation_score", ":stability_score", ":desperation_bandit_reduction", ":bandit_pressure_pct"),
      (assign, ":chance", reg0),
      (lt, ":roll", ":chance"),

      (call_script, "script_sod_center_weekly_get_desperation_bandit_count_to_reg", ":desperation_score", ":bandit_pressure_pct", ":desperation_bandit_reduction", ":surplus", 4, 3, 24, ":food_capacity_ratio", 15, ":prosperity", 20),
      (assign, ":bandit_count", reg0),
      (gt, ":bandit_count", 0),

      (spawn_around_party, ":center_no", "pt_bandits"),
      (assign, ":bandit_party", reg0),
      (gt, ":bandit_party", 0),
      (party_is_active, ":bandit_party"),
      (party_set_slot, ":bandit_party", slot_party_sod_threat_type, sod_threat_type_faction_problem),
      (party_set_slot, ":bandit_party", slot_party_sod_threat_archetype, sod_threat_archetype_cattle_raiders),
      (party_set_slot, ":bandit_party", slot_party_sod_threat_sponsor_center, ":center_no"),
      (store_faction_of_party, ":center_faction", ":center_no"),
      (party_set_slot, ":bandit_party", slot_party_sod_threat_sponsor_faction, ":center_faction"),
      (store_party_size, ":current_size", ":bandit_party"),
      (try_begin),
        (lt, ":current_size", ":bandit_count"),
        (store_sub, ":to_add", ":bandit_count", ":current_size"),
        (party_add_members, ":bandit_party", "trp_bandit", ":to_add"),
      (try_end),
      (store_party_size, ":current_size", ":bandit_party"),
      (store_sub, ":to_remove", ":current_size", ":bandit_count"),
      (try_begin),
        (gt, ":to_remove", 0),
        (try_for_range, ":unused", 0, ":to_remove"),
          (party_get_num_companion_stacks, ":num_stacks", ":bandit_party"),
          (try_for_range, ":i", 0, ":num_stacks"),
            (party_stack_get_size, ":sz", ":bandit_party", ":i"),
            (gt, ":sz", 0),
            (party_stack_get_troop_id, ":tid", ":bandit_party", ":i"),
            (neg|troop_is_hero, ":tid"),
            (party_remove_members, ":bandit_party", ":tid", 1),
            (assign, ":i", ":num_stacks"),
          (try_end),
        (try_end),
      (try_end),

      (store_mul, ":population_delta", ":bandit_count", -1),
      (call_script, "script_sod_center_apply_population_delta", ":center_no", ":population_delta"),
      (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":center_no", ":population_delta"),
      (try_begin),
        (eq, "$g_sod_hide_messages", 0),
        (str_store_party_name_link, s68, ":center_no"),
        (assign, reg0, ":bandit_count"),
        (try_begin),
          (eq, ":pressure_hunger", 1),
          (display_message, "@Desperation grips {s68}: empty granaries and failing food markets have driven {reg0} desperate folk to become bandits beyond the walls.", dark_red),
        (else_try),
          (eq, ":pressure_sickness", 1),
          (display_message, "@Desperation grips {s68}: foul streets and hard living have driven {reg0} desperate folk beyond the gates to join bandit gangs.", dark_red),
        (else_try),
          (eq, ":pressure_unrest", 1),
          (display_message, "@Desperation grips {s68}: grievance and unrest have pushed {reg0} desperate folk into bandit life beyond the walls.", dark_red),
        (else_try),
          (eq, ":pressure_poverty", 1),
          (display_message, "@Desperation grips {s68}: empty purses and failing markets have driven {reg0} desperate folk to become bandits beyond the walls.", dark_red),
        (else_try),
          (display_message, "@Desperation grips {s68}: {reg0} desperate folk have become bandits and slipped beyond the gates.", dark_red),
        (try_end),
      (try_end),
    (try_end),

    (try_for_range, ":source_no", towns_begin, towns_end),
      (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":source_no"),
      (assign, ":src_pop", reg0),
      (assign, ":src_prosp", reg1),
      (assign, ":src_health", reg2),
      (assign, ":src_food_store", reg3),
      (assign, ":src_food_consumption", reg5),
      (assign, ":src_food_capacity_ratio", reg6),
      (assign, ":src_relation", reg8),
      (assign, ":src_lord", reg9),
      (gt, ":src_lord", 0),

      (assign, ":src_pressure_hunger", 0),

      (store_sub, ":surplus", ":src_pop", town_pop_min),
      (ge, ":surplus", sod_migration_pop_surplus_min),

      (call_script, "script_sod_center_weekly_get_basic_migration_pressure", ":src_prosp", ":src_health", ":src_relation"),
      (assign, ":migration_pressure", reg0),
      (assign, ":src_pressure_poverty", reg1),
      (assign, ":src_pressure_sickness", reg2),
      (assign, ":src_pressure_unrest", reg3),
      (try_begin),
        (gt, ":src_food_consumption", 0),
        (store_mul, ":src_three_day_stock", ":src_food_consumption", 3),
        (store_mul, ":src_seven_day_stock", ":src_food_consumption", 7),
        (try_begin),
          (le, ":src_food_store", 0),
            (assign, ":src_pressure_hunger", 1),
            (val_add, ":migration_pressure", 8),
          (else_try),
            (lt, ":src_food_store", ":src_three_day_stock"),
            (assign, ":src_pressure_hunger", 1),
            (val_add, ":migration_pressure", 5),
          (else_try),
            (lt, ":src_food_store", ":src_seven_day_stock"),
            (assign, ":src_pressure_hunger", 1),
            (val_add, ":migration_pressure", 2),
        (try_end),
      (try_end),
      (try_begin),
        (lt, ":src_food_capacity_ratio", 15),
        (assign, ":src_pressure_hunger", 1),
        (val_add, ":migration_pressure", 5),
      (else_try),
        (lt, ":src_food_capacity_ratio", 30),
        (assign, ":src_pressure_hunger", 1),
        (val_add, ":migration_pressure", 2),
      (try_end),
      (try_begin),
        (ge, ":src_pop", 2200),
        (lt, ":src_prosp", 60),
        (val_add, ":migration_pressure", 3),
      (else_try),
        (ge, ":src_pop", 1700),
        (lt, ":src_prosp", 55),
        (val_add, ":migration_pressure", 2),
      (else_try),
        (ge, ":src_pop", 1200),
        (lt, ":src_prosp", 50),
        (val_add, ":migration_pressure", 1),
      (try_end),
      (gt, ":migration_pressure", 0),

      (store_troop_faction, ":src_faction", ":src_lord"),
      (assign, ":src_score", ":src_prosp"),
      (val_add, ":src_score", ":src_health"),
      (val_add, ":src_score", ":src_relation"),
      (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":src_score", ":src_food_store", ":src_food_consumption", ":src_food_capacity_ratio", 0),
      (assign, ":src_score", reg0),

      (store_random_in_range, ":migrants", 1, sod_migration_max_per_week),
      (val_min, ":migrants", ":surplus"),
      (val_min, ":migrants", ":migration_pressure"),
      (gt, ":migrants", 0),

      (try_for_range, ":dest_no", villages_begin, villages_end),
        (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":dest_no"),
        (assign, ":dest_pop", reg0),
        (assign, ":dest_prosp", reg1),
        (assign, ":dest_health", reg2),
        (assign, ":dest_relation", reg8),
        (assign, ":dest_lord", reg9),
        (gt, ":dest_lord", 0),

        (store_troop_faction, ":dest_faction", ":dest_lord"),
        (eq, ":dest_faction", ":src_faction"),
        (lt, ":dest_pop", village_pop_max),

        (store_sub, ":prosp_gap", ":dest_prosp", ":src_prosp"),
        (ge, ":prosp_gap", 5),

        (assign, ":dest_score", ":dest_prosp"),
        (val_add, ":dest_score", ":dest_health"),
        (val_add, ":dest_score", ":dest_relation"),
        (store_sub, ":score_gap", ":dest_score", ":src_score"),
        (ge, ":score_gap", 8),

        (call_script, "script_sod_center_weekly_get_migration_transfer_to_reg", ":migrants", ":dest_pop", village_pop_max, ":score_gap"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),

        (call_script, "script_sod_center_transfer_population", ":source_no", ":dest_no", ":transfer"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),
        (store_mul, ":source_cache_delta", ":transfer", -1),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":source_no", ":source_cache_delta"),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":dest_no", ":transfer"),
        (try_begin),
          (eq, "$g_sod_hide_messages", 0),
          (str_store_party_name_link, s68, ":source_no"),
          (str_store_party_name_link, s69, ":dest_no"),
          (assign, reg0, ":transfer"),
          (try_begin),
            (eq, ":src_pressure_hunger", 1),
            (display_message, "@Word spreads that {reg0} townsfolk have left hungry {s68} and settled instead among the fields of {s69}, trusting the countryside more than empty markets.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_sickness", 1),
            (display_message, "@Word spreads that {reg0} townsfolk have left foul-aired {s68} and settled among the fields of {s69}, hoping country life will be kinder to them.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_unrest", 1),
            (display_message, "@Word spreads that {reg0} townsfolk have left troubled {s68} and settled among the fields of {s69}, preferring quiet labor to strife in the streets.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_poverty", 1),
            (display_message, "@Word spreads that {reg0} townsfolk have left poor {s68} and settled instead among the fields of {s69}, where bread and rent seem less cruelly matched.", 0xAAAAAA),
          (else_try),
            (display_message, "@Word spreads that {reg0} townsfolk have left {s68} and settled instead among the fields of {s69}.", 0xAAAAAA),
          (try_end),
        (try_end),
        (assign, ":migrants", 0),
        (assign, ":dest_no", villages_end), # loop break
      (try_end),

      (gt, ":migrants", 0),
      (try_for_range, ":dest_no", towns_begin, towns_end),
        (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":dest_no"),
        (assign, ":dest_pop", reg0),
        (assign, ":dest_prosp", reg1),
        (assign, ":dest_health", reg2),
        (assign, ":dest_food_store", reg3),
        (assign, ":dest_food_consumption", reg5),
        (assign, ":dest_food_capacity_ratio", reg6),
        (assign, ":dest_relation", reg8),
        (assign, ":dest_lord", reg9),
        (gt, ":dest_lord", 0),

        (store_troop_faction, ":dest_faction", ":dest_lord"),
        (eq, ":dest_faction", ":src_faction"),
        (lt, ":dest_pop", town_pop_max),

        (store_sub, ":prosp_gap", ":dest_prosp", ":src_prosp"),
        (ge, ":prosp_gap", 5),

        (assign, ":dest_score", ":dest_prosp"),
        (val_add, ":dest_score", ":dest_health"),
        (val_add, ":dest_score", ":dest_relation"),
        (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":dest_score", ":dest_food_store", ":dest_food_consumption", ":dest_food_capacity_ratio", 1),
        (assign, ":dest_score", reg0),
        (store_sub, ":score_gap", ":dest_score", ":src_score"),
        (ge, ":score_gap", 8),

        (call_script, "script_sod_center_weekly_get_migration_transfer_to_reg", ":migrants", ":dest_pop", town_pop_max, ":score_gap"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),

        (call_script, "script_sod_center_transfer_population", ":source_no", ":dest_no", ":transfer"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),
        (store_mul, ":source_cache_delta", ":transfer", -1),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":source_no", ":source_cache_delta"),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":dest_no", ":transfer"),
        (try_begin),
          (eq, "$g_sod_hide_messages", 0),
          (str_store_party_name_link, s68, ":source_no"),
          (str_store_party_name_link, s69, ":dest_no"),
          (assign, reg0, ":transfer"),
          (try_begin),
            (eq, ":src_pressure_hunger", 1),
            (display_message, "@Word spreads that {reg0} villagers have left hungry {s68} for {s69}, trusting the walls and steadier stores there.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_sickness", 1),
            (display_message, "@Word spreads that {reg0} villagers have left sickly {s68} for {s69}, hoping the castle life will be kinder to them.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_unrest", 1),
            (display_message, "@Word spreads that {reg0} villagers have left troubled {s68} for {s69}, preferring order behind the walls to the unrest they left behind.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_poverty", 1),
            (display_message, "@Word spreads that {reg0} villagers have left poor {s68} for {s69}, seeking a steadier living under stronger shelter.", 0xAAAAAA),
          (else_try),
            (display_message, "@Word spreads that {reg0} villagers have left {s68} and settled under the walls of {s69}.", 0xAAAAAA),
          (try_end),
        (try_end),
        (assign, ":migrants", 0),
        (assign, ":dest_no", towns_end), # loop break
      (try_end),

      (gt, ":migrants", 0),
      (try_for_range, ":dest_no", castles_begin, castles_end),
        (call_script, "script_sod_center_weekly_store_cached_profile_to_regs", ":dest_no"),
        (assign, ":dest_pop", reg0),
        (assign, ":dest_prosp", reg1),
        (assign, ":dest_health", reg2),
        (assign, ":dest_food_store", reg3),
        (assign, ":dest_food_consumption", reg5),
        (assign, ":dest_food_capacity_ratio", reg6),
        (assign, ":dest_relation", reg8),
        (assign, ":dest_lord", reg9),
        (gt, ":dest_lord", 0),

        (store_troop_faction, ":dest_faction", ":dest_lord"),
        (eq, ":dest_faction", ":src_faction"),
        (lt, ":dest_pop", town_pop_max),

        (store_sub, ":prosp_gap", ":dest_prosp", ":src_prosp"),
        (ge, ":prosp_gap", 5),

        (assign, ":dest_score", ":dest_prosp"),
        (val_add, ":dest_score", ":dest_health"),
        (val_add, ":dest_score", ":dest_relation"),
        (val_add, ":dest_score", 5),
        (call_script, "script_sod_center_weekly_get_migration_food_adjusted_score", ":dest_score", ":dest_food_store", ":dest_food_consumption", ":dest_food_capacity_ratio", 1),
        (assign, ":dest_score", reg0),
        (store_sub, ":score_gap", ":dest_score", ":src_score"),
        (ge, ":score_gap", 8),

        (call_script, "script_sod_center_weekly_get_migration_transfer_to_reg", ":migrants", ":dest_pop", town_pop_max, ":score_gap"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),

        (call_script, "script_sod_center_transfer_population", ":source_no", ":dest_no", ":transfer"),
        (assign, ":transfer", reg0),
        (gt, ":transfer", 0),
        (store_mul, ":source_cache_delta", ":transfer", -1),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":source_no", ":source_cache_delta"),
        (call_script, "script_sod_center_weekly_apply_cached_population_delta", ":dest_no", ":transfer"),
        (try_begin),
          (eq, "$g_sod_hide_messages", 0),
          (str_store_party_name_link, s68, ":source_no"),
          (str_store_party_name_link, s69, ":dest_no"),
          (assign, reg0, ":transfer"),
          (try_begin),
            (eq, ":src_pressure_hunger", 1),
            (display_message, "@Word spreads that {reg0} villagers have left hungry {s68} and taken shelter under the walls of {s69}, hoping for steadier stores and protection.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_sickness", 1),
            (display_message, "@Word spreads that {reg0} villagers have left sickly {s68} and taken shelter under the walls of {s69}, hoping the castle life will be kinder to them.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_unrest", 1),
            (display_message, "@Word spreads that {reg0} villagers have left troubled {s68} and taken shelter under the walls of {s69}, preferring order to the unrest they left behind.", 0xAAAAAA),
          (else_try),
            (eq, ":src_pressure_poverty", 1),
            (display_message, "@Word spreads that {reg0} villagers have left poor {s68} and taken shelter under the walls of {s69}, seeking a steadier living under stronger shelter.", 0xAAAAAA),
          (else_try),
            (display_message, "@Word spreads that {reg0} villagers have left {s68} and taken shelter under the walls of {s69}.", 0xAAAAAA),
          (try_end),
        (try_end),
        (assign, ":migrants", 0),
        (assign, ":dest_no", castles_end), # loop break
      (try_end),
    (try_end),

    (try_begin),
      (eq, "$g_sod_hide_messages", -2),
      (set_show_messages, 1),
    (try_end),
 ]),
]
