# COST: moderate
SCRIPTS = [
("sod_elephant_guard_update_sacred_state",
 [
   (store_num_parties_of_template, ":active_patrols", "pt_elephant_guard_sanctuary_patrol"),
   (store_num_parties_of_template, ":active_processions", "pt_elephant_guard_relic_procession"),
   (store_add, ":active_total", ":active_patrols", ":active_processions"),
   (faction_get_slot, ":slaver_heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
   (store_div, ":slaver_alarm", ":slaver_heat", 3),
   (try_for_parties, ":slaver_party"),
     (party_slot_eq, ":slaver_party", slot_party_sod_slaver_web_activity, 1),
     (val_add, ":slaver_alarm", 8),
     (store_distance_to_party_from_party, ":slaver_dist", ":slaver_party", "p_sod_merc_guild_3"),
     (try_begin),
       (lt, ":slaver_dist", 65),
       (val_add, ":slaver_alarm", 5),
     (try_end),
   (try_end),
   (val_clamp, ":slaver_alarm", 0, 101),

   (assign, ":target_center", "p_sod_merc_guild_3"),
   (assign, ":omen_pressure", 0),
   (try_for_range, ":center_no", centers_begin, centers_end),
     (store_distance_to_party_from_party, ":dist", ":center_no", "p_sod_merc_guild_3"),
     (lt, ":dist", 55),
     (try_begin),
       (is_between, ":center_no", walled_centers_begin, walled_centers_end),
       (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
     (else_try),
       (is_between, ":center_no", villages_begin, villages_end),
       (neg|party_slot_eq, ":center_no", slot_village_state, svs_looted),
       (neg|party_slot_eq, ":center_no", slot_village_state, svs_deserted),
     (try_end),
     (call_script, "script_get_center_threat_level", ":center_no"),
     (assign, ":center_threat", reg0),
     (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
     (store_sub, ":need", 100, ":health"),
     (store_sub, ":prosperity_need", 65, ":prosperity"),
     (val_max, ":prosperity_need", 0),
     (val_add, ":need", ":prosperity_need"),
     (try_begin),
       (is_between, ":center_no", villages_begin, villages_end),
       (store_sub, ":population_need", village_pop_min, ":population"),
       (val_max, ":population_need", 0),
       (val_div, ":population_need", 5),
       (val_add, ":need", ":population_need"),
     (try_end),
     (store_mul, ":center_score", ":center_threat", 8),
     (val_add, ":center_score", ":need"),
     (gt, ":center_score", ":omen_pressure"),
     (assign, ":omen_pressure", ":center_score"),
     (assign, ":target_center", ":center_no"),
   (try_end),

   (store_relation, ":player_relation", "fac_player_supporters_faction", "fac_sod_merc_guild3"),
   (assign, ":devotion", 35),
   (val_add, ":devotion", ":player_relation"),
   (store_div, ":honor_factor", "$player_honor", 4),
   (val_add, ":devotion", ":honor_factor"),
   (store_mul, ":active_devotion", ":active_total", 4),
   (val_add, ":devotion", ":active_devotion"),
   (val_clamp, ":devotion", 0, 101),

   (assign, ":supplies", 30),
   (try_begin),
     (gt, ":target_center", 0),
     (party_get_slot, ":target_prosperity", ":target_center", slot_town_prosperity),
     (store_div, ":prosperity_supplies", ":target_prosperity", 3),
     (val_add, ":supplies", ":prosperity_supplies"),
   (try_end),
   (val_sub, ":supplies", ":active_total"),
   (val_clamp, ":supplies", 0, 101),

   (store_div, ":omens", ":omen_pressure", 3),
   (val_add, ":omens", ":slaver_alarm"),
   (val_clamp, ":omens", 0, 101),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_devotion, ":devotion"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_supplies, ":supplies"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_omens, ":omens"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_active_parties, ":active_total"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_target_center, ":target_center"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm, ":slaver_alarm"),
   (assign, reg0, ":devotion"),
   (assign, reg1, ":supplies"),
   (assign, reg2, ":omens"),
   (assign, reg3, ":active_total"),
   (assign, reg4, ":target_center"),
   (assign, reg5, ":slaver_alarm"),
 ]),

("sod_elephant_guard_spawn_world_activity",
 [
   (call_script, "script_sod_elephant_guard_update_sacred_state"),
   (faction_get_slot, ":devotion", "fac_sod_merc_guild3", slot_faction_elephant_guard_devotion),
   (faction_get_slot, ":supplies", "fac_sod_merc_guild3", slot_faction_elephant_guard_supplies),
   (faction_get_slot, ":omens", "fac_sod_merc_guild3", slot_faction_elephant_guard_omens),
   (faction_get_slot, ":active_total", "fac_sod_merc_guild3", slot_faction_elephant_guard_active_parties),
   (faction_get_slot, ":target_center", "fac_sod_merc_guild3", slot_faction_elephant_guard_target_center),
   (faction_get_slot, ":slaver_alarm", "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),

   (assign, ":party_cap", 1),
   (try_begin),
     (ge, ":devotion", 45),
     (val_add, ":party_cap", 1),
   (try_end),
   (try_begin),
     (ge, ":omens", 45),
     (val_add, ":party_cap", 1),
   (try_end),
   (try_begin),
     (ge, ":supplies", 60),
     (val_add, ":party_cap", 1),
   (try_end),
   (try_begin),
     (ge, ":slaver_alarm", 25),
     (val_add, ":party_cap", 1),
   (try_end),
   (val_clamp, ":party_cap", 1, 5),

   (try_begin),
     (lt, ":active_total", ":party_cap"),

     (store_current_day, ":cur_day"),
     (faction_get_slot, ":last_spawn_day", "fac_sod_merc_guild3", slot_faction_elephant_guard_last_spawn_day),
     (store_sub, ":days_since_spawn", ":cur_day", ":last_spawn_day"),
     (try_begin),
       (this_or_next|ge, ":days_since_spawn", 5),
       (lt, ":last_spawn_day", 1),

       (assign, ":origin", "p_sod_merc_guild_3"),
       (assign, ":destination", ":target_center"),
       (try_begin),
         (le, ":destination", 0),
         (assign, ":destination", "p_sod_merc_guild_3"),
       (try_end),

       (try_begin),
         (this_or_next|ge, ":omens", 45),
         (ge, ":slaver_alarm", 20),
         (assign, ":template", "pt_elephant_guard_sanctuary_patrol"),
         (assign, ":activity_type", sod_elephant_guard_activity_patrol),
       (else_try),
         (assign, ":template", "pt_elephant_guard_relic_procession"),
         (assign, ":activity_type", sod_elephant_guard_activity_procession),
       (try_end),

       (set_spawn_radius, 4),
       (spawn_around_party, ":origin", ":template"),
       (assign, ":new_party", reg0),
       (party_set_faction, ":new_party", "fac_sod_merc_guild3"),
       (party_set_slot, ":new_party", slot_party_sod_elephant_guard_activity, 1),
       (party_set_slot, ":new_party", slot_party_sod_elephant_guard_origin, ":origin"),
       (party_set_slot, ":new_party", slot_party_sod_elephant_guard_destination, ":destination"),
       (party_set_slot, ":new_party", slot_party_sod_elephant_guard_activity_type, ":activity_type"),
       (party_set_slot, ":new_party", slot_party_orginal_faction, "fac_sod_merc_guild3"),
       (party_set_slot, ":new_party", slot_party_starting_base, "p_sod_merc_guild_3"),
       (party_set_slot, ":new_party", slot_party_type, spt_ai_mercenaries),
       (party_set_slot, ":new_party", slot_party_boss, -1),
       (try_begin),
         (eq, ":activity_type", sod_elephant_guard_activity_patrol),
         (call_script, "script_party_set_ai_state", ":new_party", spai_patrolling_around_center, ":destination"),
         (party_set_ai_patrol_radius, ":new_party", 10),
         (try_begin),
           (ge, ":slaver_alarm", 20),
           (display_message, "@Elephant Guard sanctuary patrols are watching Slaver traffic.", 0x8B4513),
         (else_try),
           (display_message, "@Elephant Guard sanctuary patrols have taken to the roads.", 0x8B4513),
         (try_end),
       (else_try),
         (party_set_ai_behavior, ":new_party", ai_bhvr_travel_to_party),
         (party_set_ai_object, ":new_party", ":destination"),
         (display_message, "@An Elephant Guard relic procession has left its sanctuary.", 0x8B4513),
       (try_end),
       (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_last_spawn_day, ":cur_day"),
     (try_end),
   (try_end),
 ]),

("sod_elephant_guard_process_world_activity",
 [
   (assign, ":arrivals", 0),
   (assign, ":interdictions", 0),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (party_slot_eq, ":party_no", slot_party_sod_elephant_guard_activity, 1),
     (party_set_faction, ":party_no", "fac_sod_merc_guild3"),
     (party_get_slot, ":destination", ":party_no", slot_party_sod_elephant_guard_destination),
     (party_get_slot, ":activity_type", ":party_no", slot_party_sod_elephant_guard_activity_type),
     (gt, ":destination", 0),
     (store_distance_to_party_from_party, ":distance", ":party_no", ":destination"),
     (try_begin),
       (le, ":distance", 12),
       (is_between, ":destination", centers_begin, centers_end),
       (party_get_slot, ":health", ":destination", slot_center_sod_local_health),
       (party_get_slot, ":prosperity", ":destination", slot_town_prosperity),
       (party_get_slot, ":population", ":destination", slot_center_sod_local_population),
       (try_begin),
         (lt, ":health", 85),
         (val_add, ":health", 1),
         (val_min, ":health", 85),
         (party_set_slot, ":destination", slot_center_sod_local_health, ":health"),
       (try_end),
       (try_begin),
         (lt, ":prosperity", 70),
         (call_script, "script_change_center_prosperity", ":destination", 1),
       (try_end),
       (try_begin),
         (is_between, ":destination", villages_begin, villages_end),
         (lt, ":population", village_pop_min),
         (val_add, ":population", 1),
         (val_min, ":population", village_pop_min),
         (party_set_slot, ":destination", slot_center_sod_local_population, ":population"),
       (try_end),
     (try_end),
     (try_begin),
       (eq, ":activity_type", sod_elephant_guard_activity_patrol),
       (eq, ":interdictions", 0),
       (try_for_parties, ":slaver_party"),
         (eq, ":interdictions", 0),
         (party_is_active, ":slaver_party"),
         (party_slot_eq, ":slaver_party", slot_party_sod_slaver_web_activity, 1),
         (store_distance_to_party_from_party, ":slaver_dist", ":party_no", ":slaver_party"),
         (lt, ":slaver_dist", 10),
         (party_set_ai_behavior, ":party_no", ai_bhvr_attack_party),
         (party_set_ai_object, ":party_no", ":slaver_party"),
         (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_hostile, 1),
         (assign, ":interdictions", 1),
       (try_end),
     (try_end),
     (try_begin),
       (eq, ":activity_type", sod_elephant_guard_activity_procession),
       (lt, ":distance", 4),
       (is_between, ":destination", centers_begin, centers_end),
       (val_add, ":arrivals", 1),
       (remove_party, ":party_no"),
     (try_end),
   (try_end),
   (try_begin),
     (gt, ":arrivals", 0),
     (assign, reg1, ":arrivals"),
     (display_message, "@{reg1} Elephant Guard relic procession(s) completed their rites.", 0x8B4513),
   (try_end),
   (try_begin),
     (gt, ":interdictions", 0),
     (display_message, "@Elephant Guard patrols have begun shadowing Slaver traffic.", 0x8B4513),
   (try_end),
   (call_script, "script_sod_elephant_guard_update_sacred_state"),
 ]),

("sod_elephant_guard_apply_player_support",
 [
   (store_script_param_1, ":support"),
   (val_max, ":support", 1),
   (call_script, "script_sod_elephant_guard_update_sacred_state"),
   (faction_get_slot, ":devotion", "fac_sod_merc_guild3", slot_faction_elephant_guard_devotion),
   (faction_get_slot, ":supplies", "fac_sod_merc_guild3", slot_faction_elephant_guard_supplies),
   (faction_get_slot, ":omens", "fac_sod_merc_guild3", slot_faction_elephant_guard_omens),
   (faction_get_slot, ":slaver_alarm", "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),
   (store_mul, ":supply_gain", ":support", 4),
   (val_add, ":supplies", ":supply_gain"),
   (store_mul, ":devotion_gain", ":support", 2),
   (val_add, ":devotion", ":devotion_gain"),
   (val_sub, ":omens", ":support"),
   (val_sub, ":slaver_alarm", ":support"),
   (val_clamp, ":devotion", 0, 101),
   (val_clamp, ":supplies", 0, 101),
   (val_clamp, ":omens", 0, 101),
   (val_clamp, ":slaver_alarm", 0, 101),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_devotion, ":devotion"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_supplies, ":supplies"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_omens, ":omens"),
   (faction_set_slot, "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm, ":slaver_alarm"),
   (try_begin),
     (ge, ":support", 3),
     (faction_get_slot, ":slaver_supply", "fac_sod_merc_guild6", slot_faction_slaver_market_supply),
     (faction_get_slot, ":slaver_heat", "fac_sod_merc_guild6", slot_faction_slaver_market_heat),
     (val_sub, ":slaver_supply", ":support"),
     (val_sub, ":slaver_heat", 1),
     (val_clamp, ":slaver_supply", 0, 101),
     (val_clamp, ":slaver_heat", 0, 101),
     (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_supply, ":slaver_supply"),
     (faction_set_slot, "fac_sod_merc_guild6", slot_faction_slaver_market_heat, ":slaver_heat"),
   (try_end),
   (try_begin),
     (ge, ":support", 2),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 1),
   (try_end),
 ]),

("sod_elephant_guard_grant_player_blessing",
 [
   (assign, reg0, 0),
   (store_current_day, ":cur_day"),
   (store_sub, ":days_since_blessing", ":cur_day", "$g_sod_elephant_guard_last_blessing_day"),
   (store_relation, ":relation", "fac_player_supporters_faction", "fac_sod_merc_guild3"),
   (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
   (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
   (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
   (try_begin),
     (ge, "$player_honor", 5),
     (ge, ":relation", 0),
     (eq, ":slave_count", 0),
     (this_or_next|ge, ":days_since_blessing", 7),
     (lt, "$g_sod_elephant_guard_last_blessing_day", 1),
     (party_add_xp, "p_main_party", 400),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 1),
     (call_script, "script_sod_elephant_guard_apply_player_support", 1),
     (assign, "$g_sod_elephant_guard_last_blessing_day", ":cur_day"),
     (assign, reg0, 1),
   (try_end),
 ]),

("sod_elephant_guard_grant_road_volunteers",
 [
   (assign, reg0, 0),
   (assign, reg1, 0),
   (store_current_day, ":cur_day"),
   (store_sub, ":days_since_volunteers", ":cur_day", "$g_sod_elephant_guard_last_volunteer_day"),
   (store_relation, ":relation", "fac_player_supporters_faction", "fac_sod_merc_guild3"),
   (party_get_free_companions_capacity, ":free_capacity", "p_main_party"),
   (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
   (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
   (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
   (try_begin),
     (ge, "$player_honor", 5),
     (ge, ":relation", 5),
     (eq, ":slave_count", 0),
     (gt, ":free_capacity", 0),
     (this_or_next|ge, ":days_since_volunteers", 14),
     (lt, "$g_sod_elephant_guard_last_volunteer_day", 1),
     (assign, ":tribesmen", 2),
     (try_begin),
       (ge, ":relation", 15),
       (val_add, ":tribesmen", 1),
     (try_end),
     (val_min, ":tribesmen", ":free_capacity"),
     (party_add_members, "p_main_party", "trp_elephant_guard_tribesman", ":tribesmen"),
     (assign, ":joined", ":tribesmen"),
     (store_sub, ":remaining_capacity", ":free_capacity", ":tribesmen"),
     (try_begin),
       (ge, ":relation", 15),
       (gt, ":remaining_capacity", 0),
       (party_add_members, "p_main_party", "trp_elephant_guard_fighter", 1),
       (val_add, ":joined", 1),
     (try_end),
     (assign, "$g_sod_elephant_guard_last_volunteer_day", ":cur_day"),
     (call_script, "script_sod_elephant_guard_apply_player_support", 1),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 1),
     (assign, reg0, 1),
     (assign, reg1, ":joined"),
   (try_end),
 ]),

("sod_elephant_guard_free_player_slaves",
 [
   (assign, reg0, 0),
   (assign, reg1, 0),
   (assign, reg2, 0),
   (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
   (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
   (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
   (try_begin),
     (gt, ":slave_count", 0),
     (party_remove_members, "p_main_party", "trp_slave", ":male_slaves"),
     (party_remove_members, "p_main_party", "trp_slave_female", ":female_slaves"),
     (store_div, ":honor_gain", ":slave_count", 5),
     (val_add, ":honor_gain", 1),
     (val_clamp, ":honor_gain", 1, 6),
     (call_script, "script_change_player_honor", ":honor_gain"),
     (store_div, ":market_pressure", ":slave_count", 2),
     (val_add, ":market_pressure", 1),
     (val_clamp, ":market_pressure", 1, 16),
     (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_free_runaways, ":market_pressure"),
     (call_script, "script_change_player_relation_with_faction", "fac_sod_merc_guild3", 2),
     (call_script, "script_sod_elephant_guard_apply_player_support", 1),
     (assign, reg0, 1),
     (assign, reg1, ":slave_count"),
     (assign, reg2, ":honor_gain"),
   (try_end),
 ]),

("sod_elephant_guard_describe_status_to_s21",
 [
   (call_script, "script_sod_elephant_guard_update_sacred_state"),
   (faction_get_slot, reg21, "fac_sod_merc_guild3", slot_faction_elephant_guard_devotion),
   (faction_get_slot, reg22, "fac_sod_merc_guild3", slot_faction_elephant_guard_supplies),
   (faction_get_slot, reg23, "fac_sod_merc_guild3", slot_faction_elephant_guard_omens),
   (faction_get_slot, reg24, "fac_sod_merc_guild3", slot_faction_elephant_guard_active_parties),
   (faction_get_slot, reg25, "fac_sod_merc_guild3", slot_faction_elephant_guard_slaver_alarm),
   (faction_get_slot, ":target_center", "fac_sod_merc_guild3", slot_faction_elephant_guard_target_center),
   (call_script, "script_sod_store_center_name_or_fallback_to_s21", ":target_center", "@no confirmed shrine-road"),
   (try_begin),
     (ge, reg25, 30),
     (str_store_string, s20, "@^Sacred wardens: devotion {reg21}, supplies {reg22}, omens {reg23}, active rites {reg24}, Slaver alarm {reg25}. Their shamans are watching slave roads and sending patrols against the black market."),
   (else_try),
     (ge, reg23, 55),
     (str_store_string, s20, "@^Sacred wardens: devotion {reg21}, supplies {reg22}, omens {reg23}, active rites {reg24}, Slaver alarm {reg25}. Their shamans are focused on {s21}, where bad omens and wounded settlements call for protection."),
   (else_try),
     (ge, reg22, 55),
     (str_store_string, s20, "@^Sacred wardens: devotion {reg21}, supplies {reg22}, omens {reg23}, active rites {reg24}, Slaver alarm {reg25}. Their stores are strong enough to send relic processions and aid parties from the sanctuary."),
   (else_try),
     (str_store_string, s20, "@^Sacred wardens: devotion {reg21}, supplies {reg22}, omens {reg23}, active rites {reg24}, Slaver alarm {reg25}. The Elephant Guard is quiet, guarding its sanctuary and nearby workers."),
   (try_end),
 ]),
]
