# COST: low
SCRIPTS = [
("sod_artifact_describe_tooltip",
 [
   (store_script_param_1, ":item_no"),
   (store_script_param_2, ":extra_text_id"),
   (store_script_param, ":item_modifier", 3),
   (assign, reg0, 0),
   (try_begin),
     (item_get_slot, ":flags", ":item_no", slot_item_artifact_flags),
     (gt, ":flags", 0),
     (try_begin),
       (eq, ":extra_text_id", 0),
       (item_get_slot, ":family", ":item_no", slot_item_artifact_family),
       (try_begin),
         (eq, ":family", artifact_family_antarian),
         (str_store_string, s1, "@Antarian royal artifact"),
       (else_try),
         (eq, ":family", artifact_family_marinian),
         (str_store_string, s1, "@Marinian royal artifact"),
       (else_try),
         (eq, ":family", artifact_family_adenian),
         (str_store_string, s1, "@Adenian royal artifact"),
       (else_try),
         (eq, ":family", artifact_family_villianese),
         (str_store_string, s1, "@Villianese royal artifact"),
       (else_try),
         (eq, ":family", artifact_family_zerrikanian),
         (str_store_string, s1, "@Zerrikanian royal artifact"),
       (else_try),
         (str_store_string, s1, "@Artifact of uncertain provenance"),
       (try_end),
       (set_result_string, "@{s1}"),
       (set_trigger_result, 0xD6B15E),
       (assign, reg0, 1),
     (else_try),
       (eq, ":extra_text_id", 1),
       (item_get_slot, ":rank", ":item_no", slot_item_artifact_provenance_rank),
       (try_begin),
         (ge, ":rank", 4),
         (str_store_string, s1, "@Provenance: royal legend"),
       (else_try),
         (ge, ":rank", 3),
         (str_store_string, s1, "@Provenance: famous campaign weapon"),
       (else_try),
         (ge, ":rank", 2),
         (str_store_string, s1, "@Provenance: respected armament"),
       (else_try),
         (ge, ":rank", 1),
         (str_store_string, s1, "@Provenance: blooded heirloom"),
       (else_try),
         (str_store_string, s1, "@Provenance: recovered heirloom"),
       (try_end),
       (set_result_string, "@{s1}"),
       (set_trigger_result, 0xD6B15E),
       (assign, reg0, 1),
     (else_try),
       (eq, ":extra_text_id", 2),
       (item_get_slot, ":flags", ":item_no", slot_item_artifact_flags),
       (store_and, ":is_weapon", ":flags", artifact_flag_weapon),
       (gt, ":is_weapon", 0),
       (call_script, "script_sod_artifact_get_progress", ":item_no", ":item_modifier"),
       (assign, reg21, reg0),
       (assign, reg22, reg2),
       (set_result_string, "@Battle record: {reg21}/{reg22} kills toward next provenance mark"),
       (set_trigger_result, 0xD6B15E),
       (assign, reg0, 1),
     (else_try),
       (eq, ":extra_text_id", 3),
       (item_get_slot, ":tech", ":item_no", slot_item_artifact_technique_flags),
       (gt, ":tech", 0),
       (str_store_string, s1, "@Craft: maintained by master hands"),
       (try_begin),
         (store_and, ":has", ":tech", artifact_tech_folded_steel),
         (gt, ":has", 0),
         (str_store_string, s1, "@Craft: folded steel"),
       (else_try),
         (store_and, ":has", ":tech", artifact_tech_perfect_balance),
         (gt, ":has", 0),
         (str_store_string, s1, "@Craft: perfect balance"),
       (else_try),
         (store_and, ":has", ":tech", artifact_tech_hardened_point),
         (gt, ":has", 0),
         (str_store_string, s1, "@Craft: hardened point"),
       (else_try),
         (store_and, ":has", ":tech", artifact_tech_engraved_grip),
         (gt, ":has", 0),
         (str_store_string, s1, "@Craft: engraved grip"),
       (try_end),
       (set_result_string, "@{s1}"),
       (set_trigger_result, 0xD6B15E),
       (assign, reg0, 1),
     (try_end),
   (try_end),
 ]),
]
