# COST: party scan
SCRIPTS = [
("sod_process_castle_patrols",
 [
   (store_current_day, ":cur_day"),
   (try_for_parties, ":cur_party"),
     (party_slot_eq, ":cur_party", slot_party_sod_support_type, sod_support_type_castle_patrol),
     (party_slot_eq, ":cur_party", slot_party_type, spt_patrol),
     (party_get_slot, ":origin", ":cur_party", slot_party_sod_patrol_origin_castle),
     (party_get_slot, ":expiry", ":cur_party", slot_party_sod_support_expiry_day),
     (party_get_num_companions, ":active_size", ":cur_party"),
     (try_begin),
       (party_get_slot, ":status", ":cur_party", slot_party_sod_patrol_status),
       (this_or_next|eq, ":status", sod_castle_patrol_status_destroyed),
       (eq, ":status", sod_castle_patrol_status_disbanded),
       (remove_party, ":cur_party"),
     (else_try),
       (this_or_next|le, ":origin", 0),
       (neg|is_between, ":origin", castles_begin, castles_end),
       (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_disbanded),
       (remove_party, ":cur_party"),
     (else_try),
       (store_faction_of_party, ":origin_faction", ":origin"),
       (store_faction_of_party, ":patrol_faction", ":cur_party"),
       (neq, ":origin_faction", ":patrol_faction"),
       (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_disbanded),
       (remove_party, ":cur_party"),
     (else_try),
       (party_get_slot, ":besieger", ":origin", slot_center_is_besieged_by),
       (neq, ":besieger", -1),
       (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_returning),
       (party_set_ai_behavior, ":cur_party", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":cur_party", ":origin"),
     (else_try),
       (party_get_slot, ":status", ":cur_party", slot_party_sod_patrol_status),
       (this_or_next|eq, ":status", sod_castle_patrol_status_returning),
       (this_or_next|eq, ":status", sod_castle_patrol_status_damaged),
       (eq, ":status", sod_castle_patrol_status_expired),
       (store_distance_to_party_from_party, ":dist_to_origin", ":cur_party", ":origin"),
       (le, ":dist_to_origin", 2),
       (call_script, "script_sod_castle_patrol_return_to_origin", ":cur_party"),
     (else_try),
       (party_get_slot, ":target", ":cur_party", slot_party_sod_support_target),
       (assign, ":target_invalid", 0),
       (try_begin),
         (le, ":target", 0),
         (assign, ":target_invalid", 1),
       (else_try),
         (neg|party_is_active, ":target"),
         (assign, ":target_invalid", 1),
       (try_end),
       (eq, ":target_invalid", 1),
       (party_get_slot, ":route_target", ":cur_party", slot_party_sod_patrol_route_endpoint),
       (try_begin),
         (gt, ":route_target", 0),
         (party_is_active, ":route_target"),
         (party_set_slot, ":cur_party", slot_party_sod_support_target, ":route_target"),
         (party_set_ai_behavior, ":cur_party", ai_bhvr_patrol_party),
         (party_set_ai_object, ":cur_party", ":route_target"),
       (else_try),
         (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_returning),
         (party_set_ai_behavior, ":cur_party", ai_bhvr_travel_to_party),
         (party_set_ai_object, ":cur_party", ":origin"),
       (try_end),
     (else_try),
       (le, ":active_size", 5),
       (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_damaged),
       (party_set_ai_behavior, ":cur_party", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":cur_party", ":origin"),
     (else_try),
       (call_script, "script_sod_get_castle_patrol_capacity", ":origin"),
       (eq, reg5, sod_castle_patrol_fail_food_low),
       (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_returning),
       (party_set_ai_behavior, ":cur_party", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":cur_party", ":origin"),
     (else_try),
       (party_get_slot, ":status", ":cur_party", slot_party_sod_patrol_status),
       (eq, ":status", sod_castle_patrol_status_active),
       (gt, ":expiry", 0),
       (ge, ":cur_day", ":expiry"),
       (call_script, "script_sod_castle_patrol_apply_success", ":cur_party"),
       (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_expired),
       (party_set_ai_behavior, ":cur_party", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":cur_party", ":origin"),
     (else_try),
       (party_get_num_prisoners, ":prisoners", ":cur_party"),
       (ge, ":prisoners", 5),
       (party_set_slot, ":cur_party", slot_party_sod_patrol_status, sod_castle_patrol_status_returning),
       (party_set_ai_behavior, ":cur_party", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":cur_party", ":origin"),
     (else_try),
       (party_get_slot, ":status", ":cur_party", slot_party_sod_patrol_status),
       (eq, ":status", sod_castle_patrol_status_active),
       (call_script, "script_sod_find_castle_patrol_threat_target", ":cur_party"),
       (gt, reg0, 0),
       (assign, ":threat_target", reg0),
       (call_script, "script_sod_castle_patrol_target_overwhelming", ":cur_party", ":threat_target"),
       (try_begin),
         (eq, reg0, 1),
         (call_script, "script_sod_castle_patrol_seek_refuge", ":cur_party"),
       (else_try),
         (party_set_ai_behavior, ":cur_party", ai_bhvr_attack_party),
         (party_set_ai_object, ":cur_party", ":threat_target"),
       (try_end),
     (else_try),
       (party_get_slot, ":status", ":cur_party", slot_party_sod_patrol_status),
       (eq, ":status", sod_castle_patrol_status_active),
       (party_get_slot, ":target", ":cur_party", slot_party_sod_support_target),
       (gt, ":target", 0),
       (party_is_active, ":target"),
       (store_distance_to_party_from_party, ":dist_to_target", ":cur_party", ":target"),
       (gt, ":dist_to_target", 4),
       (party_set_ai_behavior, ":cur_party", ai_bhvr_patrol_party),
       (party_set_ai_object, ":cur_party", ":target"),
     (try_end),
   (try_end),
 ]),
]
