# COST: medium
SCRIPTS = [
("sod_redirect_hostile_party_for_bribe",
 [
   (store_script_param, ":party_no", 1),
   (assign, ":best_target", -1),
   (assign, ":best_dist", 100000),
   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (store_faction_of_party, ":hostile_faction", ":party_no"),
     (try_for_range, ":cur_lord", kingdom_heroes_begin, kingdom_heroes_end),
       (troop_get_slot, ":cur_party", ":cur_lord", slot_troop_leaded_party),
       (gt, ":cur_party", 0),
       (party_is_active, ":cur_party"),
       (neq, ":cur_party", "p_main_party"),
       (store_faction_of_party, ":target_faction", ":cur_party"),
       (store_relation, ":relation", ":hostile_faction", ":target_faction"),
       (lt, ":relation", 0),
       (store_distance_to_party_from_party, ":dist", ":party_no", ":cur_party"),
       (lt, ":dist", ":best_dist"),
       (assign, ":best_dist", ":dist"),
       (assign, ":best_target", ":cur_party"),
     (try_end),
     (try_begin),
       (gt, ":best_target", 0),
       (party_set_ai_behavior, ":party_no", ai_bhvr_attack_party),
       (party_set_ai_object, ":party_no", ":best_target"),
       (party_set_flags, ":party_no", pf_default_behavior, 0),
       (assign, reg0, 1),
     (else_try),
       (party_set_ai_behavior, ":party_no", ai_bhvr_patrol_location),
       (party_set_ai_patrol_radius, ":party_no", 12),
       (party_set_flags, ":party_no", pf_default_behavior, 0),
       (assign, reg0, 0),
     (try_end),
     (store_current_hours, ":protected_until"),
     (val_add, ":protected_until", 96),
     (party_set_slot, ":party_no", slot_party_ignore_player_until, ":protected_until"),
     (party_ignore_player, ":party_no", 96),
   (else_try),
     (assign, reg0, 0),
   (try_end),
   (assign, "$g_leave_encounter", 1),
 ]),
]
