# COST: light
SCRIPTS = [
("sod_nemesis_note_lord_event",
 [
   (store_script_param, ":lord_troop", 1),
   (store_script_param, ":reason", 2),
   (store_current_day, ":cur_day"),
   (try_begin),
     (is_between, ":lord_troop", kingdom_heroes_begin, kingdom_heroes_end),
     (store_troop_faction, ":lord_faction", ":lord_troop"),
     (neq, ":lord_faction", "fac_kingdom_6"),
     (assign, "$g_sod_nemesis_actor_type", sod_nemesis_actor_lord),
     (assign, "$g_sod_nemesis_reason", ":reason"),
     (assign, "$g_sod_nemesis_last_troop", ":lord_troop"),
     (assign, "$g_sod_nemesis_last_party", "$g_enemy_party"),
     (assign, "$g_sod_nemesis_last_template", 0),
     (assign, "$g_sod_nemesis_last_center", 0),
     (assign, "$g_sod_nemesis_last_faction", ":lord_faction"),
     (assign, "$g_sod_nemesis_last_day", ":cur_day"),
     (troop_get_slot, ":defeats", ":lord_troop", slot_troop_sod_nemesis_defeats),
     (val_add, ":defeats", 1),
     (troop_set_slot, ":lord_troop", slot_troop_sod_nemesis_defeats, ":defeats"),
     (troop_get_slot, ":strength", ":lord_troop", slot_troop_sod_nemesis_strength),
     (assign, ":was_below_strength_cap", 0),
     (try_begin),
       (lt, ":strength", 6),
       (assign, ":was_below_strength_cap", 1),
     (try_end),
     (val_add, ":strength", 1),
     (val_min, ":strength", 6),
     (troop_set_slot, ":lord_troop", slot_troop_sod_nemesis_strength, ":strength"),
     (troop_get_slot, ":duel_pressure", ":lord_troop", slot_troop_sod_nemesis_duel_pressure),
     (val_add, ":duel_pressure", 2),
     (val_min, ":duel_pressure", 10),
     (troop_set_slot, ":lord_troop", slot_troop_sod_nemesis_duel_pressure, ":duel_pressure"),
     (troop_get_slot, ":renown", ":lord_troop", slot_troop_renown),
     (val_add, ":renown", 20),
     (troop_set_slot, ":lord_troop", slot_troop_renown, ":renown"),
     (try_begin),
       (eq, ":was_below_strength_cap", 1),
       (troop_raise_attribute, ":lord_troop", ca_strength, 1),
     (try_end),
     (try_begin),
       (store_skill_level, ":ironflesh", "skl_ironflesh", ":lord_troop"),
       (lt, ":ironflesh", 7),
       (troop_raise_skill, ":lord_troop", "skl_ironflesh", 1),
     (try_end),
     (try_begin),
       (store_skill_level, ":power_strike", "skl_power_strike", ":lord_troop"),
       (lt, ":power_strike", 7),
       (troop_raise_skill, ":lord_troop", "skl_power_strike", 1),
     (try_end),
     (try_begin),
       (store_mod, ":defeat_mod", ":defeats", 2),
       (eq, ":defeat_mod", 0),
       (troop_raise_attribute, ":lord_troop", ca_agility, 1),
     (try_end),
     (assign, ":adaptation", sod_nemesis_adaptation_anti_melee),
     (assign, ":player_has_ranged", 0),
     (try_for_range, ":slot", ek_item_0, ek_item_3 + 1),
       (troop_get_inventory_slot, ":item_no", "trp_player", ":slot"),
       (gt, ":item_no", 0),
       (item_get_type, ":item_type", ":item_no"),
       (this_or_next|eq, ":item_type", itp_type_bow),
       (this_or_next|eq, ":item_type", itp_type_crossbow),
       (eq, ":item_type", itp_type_thrown),
       (assign, ":player_has_ranged", 1),
     (try_end),
     (try_begin),
       (gt, "$g_sod_battle_ally_duel_momentum", 0),
       (assign, ":adaptation", sod_nemesis_adaptation_anti_duel),
     (else_try),
       (eq, ":player_has_ranged", 1),
       (assign, ":adaptation", sod_nemesis_adaptation_anti_ranged),
     (else_try),
       (troop_get_inventory_slot, ":player_horse", "trp_player", ek_horse),
       (gt, ":player_horse", 0),
       (assign, ":adaptation", sod_nemesis_adaptation_anti_cavalry),
     (try_end),
     (troop_set_slot, ":lord_troop", slot_troop_sod_nemesis_adaptation, ":adaptation"),
     (troop_get_slot, ":adapt_count", ":lord_troop", slot_troop_sod_nemesis_adaptation_count),
     (val_add, ":adapt_count", 1),
     (val_min, ":adapt_count", 10),
     (troop_set_slot, ":lord_troop", slot_troop_sod_nemesis_adaptation_count, ":adapt_count"),
     (try_begin),
       (eq, ":adaptation", sod_nemesis_adaptation_anti_cavalry),
       (troop_raise_proficiency_linear, ":lord_troop", wpt_polearm, 15),
       (store_skill_level, ":riding", "skl_riding", ":lord_troop"),
       (lt, ":riding", 6),
       (troop_raise_skill, ":lord_troop", "skl_riding", 1),
     (else_try),
       (eq, ":adaptation", sod_nemesis_adaptation_anti_ranged),
       (troop_raise_proficiency_linear, ":lord_troop", wpt_one_handed_weapon, 10),
       (store_skill_level, ":shield", "skl_shield", ":lord_troop"),
       (lt, ":shield", 7),
       (troop_raise_skill, ":lord_troop", "skl_shield", 1),
     (else_try),
       (eq, ":adaptation", sod_nemesis_adaptation_anti_duel),
       (troop_raise_proficiency_linear, ":lord_troop", wpt_one_handed_weapon, 12),
       (troop_raise_proficiency_linear, ":lord_troop", wpt_two_handed_weapon, 12),
     (else_try),
       (troop_raise_proficiency_linear, ":lord_troop", wpt_one_handed_weapon, 10),
       (troop_raise_proficiency_linear, ":lord_troop", wpt_two_handed_weapon, 10),
     (try_end),
     (val_add, "$g_sod_nemesis_intensity", 2),
     (val_max, "$g_sod_nemesis_intensity", 1),
     (val_min, "$g_sod_nemesis_intensity", 5),
     (try_begin),
       (ge, "$g_sod_nemesis_intensity", 4),
       (assign, "$g_sod_nemesis_state", sod_nemesis_state_hunting),
     (else_try),
       (assign, "$g_sod_nemesis_state", sod_nemesis_state_watching),
     (try_end),
   (try_end),
 ]),
]
