# COST: medium
SCRIPTS = [
("sod_merc_market_get_center_settlement_pressure",
 [
   (store_script_param_1, ":center_no"),

   (assign, ":population_shortage", 0),
   (assign, ":health_pressure", 0),
   (assign, ":food_pressure", 0),
   (assign, ":outbreak_pressure", 0),
   (try_begin),
     (is_between, ":center_no", centers_begin, centers_end),
     (call_script, "script_sod_get_center_population_capacity_profile", ":center_no"),
     (assign, ":capacity_pct", reg2),
     (try_begin),
       (lt, ":capacity_pct", 75),
       (store_sub, ":population_shortage", 75, ":capacity_pct"),
       (val_div, ":population_shortage", 3),
     (try_end),

     # Refresh causes here so mercenary demand reacts to the current food and disease state.
     (call_script, "script_sod_center_public_health_compute_causes", ":center_no"),
     (assign, ":food_quality", reg2),
     (assign, ":disease_risk", reg4),
     (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
     (party_get_slot, ":outbreak_severity", ":center_no", slot_center_health_outbreak_severity),
     (val_clamp, ":health", 0, 101),
     (val_clamp, ":food_quality", 0, 101),
     (val_clamp, ":disease_risk", 0, 101),
     (val_clamp, ":outbreak_severity", 0, 7),
     (try_begin),
       (lt, ":health", 60),
       (store_sub, ":health_pressure", 60, ":health"),
       (val_div, ":health_pressure", 5),
     (try_end),
     (try_begin),
       (gt, ":disease_risk", 60),
       (store_sub, ":disease_pressure", ":disease_risk", 60),
       (val_div, ":disease_pressure", 5),
       (val_add, ":health_pressure", ":disease_pressure"),
     (try_end),
     (try_begin),
       (lt, ":food_quality", 50),
       (store_sub, ":food_pressure", 50, ":food_quality"),
       (val_div, ":food_pressure", 2),
     (try_end),
     (try_begin),
       (gt, ":outbreak_severity", 0),
       (store_mul, ":outbreak_pressure", ":outbreak_severity", 3),
     (try_end),
   (try_end),

   (val_clamp, ":population_shortage", 0, 26),
   (val_clamp, ":health_pressure", 0, 25),
   (val_clamp, ":food_pressure", 0, 26),
   (val_clamp, ":outbreak_pressure", 0, 22),
   (assign, reg0, ":population_shortage"),
   (assign, reg1, ":health_pressure"),
   (assign, reg2, ":food_pressure"),
   (assign, reg3, ":outbreak_pressure"),
 ]),

("sod_merc_market_calculate_kingdom_demand",
 [
   (store_script_param_1, ":faction_no"),
   (store_script_param, ":use_cached_active_support", 2),
   (store_script_param, ":use_cached_population_shortage", 3),
   (store_script_param, ":use_cached_lord_wealth_score", 4),
   (store_script_param, ":use_cached_guild_weight_totals", 5),
   (store_script_param, ":use_cached_settlement_pressure", 6),

   (assign, ":demand", 0),
   (assign, ":budget", 0),
   (assign, ":max_bid", 0),
   (assign, ":need_type", sod_merc_contract_role_none),
   (assign, ":urgency", 0),
     (assign, ":preferred_guild", 0),
     (assign, ":population_shortage", 0),
     (assign, ":lord_wealth_score", 0),
     (assign, ":gold_manpower_pressure", 0),
     (assign, ":health_pressure", 0),
     (assign, ":food_pressure", 0),
     (assign, ":outbreak_pressure", 0),

   (try_begin),
     (is_between, ":faction_no", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
     (faction_get_slot, ":power", ":faction_no", slot_faction_current_power),
     (faction_get_slot, ":economic_strength", ":faction_no", slot_faction_economic_strength),
     (faction_get_slot, ":num_armies", ":faction_no", slot_faction_num_armies),
     (faction_get_slot, ":campaign_health", ":faction_no", slot_faction_sod_campaign_health),
     (faction_get_slot, ":marshal_readiness", ":faction_no", slot_faction_sod_marshal_offensive_readiness),
     (faction_get_slot, ":desired_followers", ":faction_no", slot_faction_sod_marshal_desired_followers),
     (faction_get_slot, ":current_followers", ":faction_no", slot_faction_sod_marshal_current_followers),
     (faction_get_slot, ":unpaid_lords", ":faction_no", slot_faction_sod_unpaid_lord_count),
     (val_max, ":power", 0),
     (val_max, ":economic_strength", 0),
     (val_max, ":num_armies", 0),
     (val_clamp, ":campaign_health", 0, 100),
     (val_clamp, ":marshal_readiness", 0, 100),
     (val_max, ":desired_followers", 0),
     (val_max, ":current_followers", 0),
     (val_max, ":unpaid_lords", 0),

     (call_script, "script_get_number_of_factions_at_war_with_faction", ":faction_no"),
     (assign, ":war_count", reg0),
     (val_max, ":war_count", 0),

     (assign, ":enemy_pressure", 0),
     (try_for_range, ":enemy_faction", native_kingdoms_begin, native_kingdoms_end),
       (neq, ":enemy_faction", ":faction_no"),
       (faction_slot_eq, ":enemy_faction", slot_faction_state, sfs_active),
       (store_relation, ":enemy_relation", ":faction_no", ":enemy_faction"),
       (lt, ":enemy_relation", 0),
       (faction_get_slot, ":enemy_power", ":enemy_faction", slot_faction_current_power),
       (val_max, ":enemy_power", 0),
       (store_sub, ":power_gap", ":enemy_power", ":power"),
       (try_begin),
         (gt, ":power_gap", 0),
         (val_div, ":power_gap", 3),
         (val_add, ":enemy_pressure", ":power_gap"),
       (else_try),
         (val_add, ":enemy_pressure", 3),
       (try_end),
     (try_end),
     (val_clamp, ":enemy_pressure", 0, 60),

     (call_script, "script_sod_merc_market_calculate_village_patrol_demand", ":faction_no"),
     (assign, ":village_patrol_demand", reg0),
     (assign, ":village_patrol_budget", reg1),
     (assign, ":village_patrol_target", reg2),
     (assign, ":village_patrol_urgency", reg3),
     (call_script, "script_sod_merc_market_calculate_world_activity_pressure", ":faction_no"),
     (assign, ":world_activity_pressure", reg0),

     (assign, ":lord_wealth_total", 0),
     (assign, ":lord_wealth_count", 0),
     (assign, ":ruler_wealth", 0),
     (try_begin),
       (gt, ":use_cached_lord_wealth_score", 0),
       (faction_get_slot, ":lord_wealth_score", ":faction_no", slot_faction_sod_merc_lord_wealth_score),
       (val_max, ":lord_wealth_score", 0),
     (else_try),
       (try_for_range, ":kingdom_hero", kingdom_heroes_begin, kingdom_heroes_end),
         (store_troop_faction, ":hero_faction", ":kingdom_hero"),
         (eq, ":hero_faction", ":faction_no"),
         (troop_get_slot, ":hero_wealth", ":kingdom_hero", slot_troop_wealth),
         (val_max, ":hero_wealth", 0),
         (val_add, ":lord_wealth_total", ":hero_wealth"),
         (val_add, ":lord_wealth_count", 1),
         (try_begin),
           (faction_slot_eq, ":faction_no", slot_faction_leader, ":kingdom_hero"),
           (assign, ":ruler_wealth", ":hero_wealth"),
         (try_end),
       (try_end),
       (assign, ":average_lord_wealth", 0),
       (try_begin),
         (gt, ":lord_wealth_count", 0),
         (store_div, ":average_lord_wealth", ":lord_wealth_total", ":lord_wealth_count"),
       (try_end),
       (store_div, ":lord_wealth_score", ":average_lord_wealth", 150),
       (store_div, ":ruler_wealth_score", ":ruler_wealth", 300),
       (val_add, ":lord_wealth_score", ":ruler_wealth_score"),
     (try_end),
     (val_clamp, ":lord_wealth_score", 0, 61),

     (assign, ":use_live_settlement_scan", 0),
     (try_begin),
       (le, ":use_cached_population_shortage", 0),
       (assign, ":use_live_settlement_scan", 1),
     (else_try),
       (le, ":use_cached_settlement_pressure", 0),
       (assign, ":use_live_settlement_scan", 1),
     (try_end),
     (try_begin),
       (eq, ":use_live_settlement_scan", 1),
       (try_for_range, ":center_no", centers_begin, centers_end),
         (store_faction_of_party, ":center_faction", ":center_no"),
         (eq, ":center_faction", ":faction_no"),
         (call_script, "script_sod_merc_market_get_center_settlement_pressure", ":center_no"),
         (val_add, ":population_shortage", reg0),
         (val_add, ":health_pressure", reg1),
         (val_add, ":food_pressure", reg2),
         (val_add, ":outbreak_pressure", reg3),
       (try_end),
     (else_try),
       (faction_get_slot, ":population_shortage", ":faction_no", slot_faction_sod_merc_population_shortage),
       (faction_get_slot, ":health_pressure", ":faction_no", slot_faction_sod_merc_health_pressure),
       (faction_get_slot, ":food_pressure", ":faction_no", slot_faction_sod_merc_food_pressure),
       (faction_get_slot, ":outbreak_pressure", ":faction_no", slot_faction_sod_merc_outbreak_pressure),
     (try_end),
     (val_clamp, ":population_shortage", 0, 41),
     (val_clamp, ":health_pressure", 0, 41),
     (val_clamp, ":food_pressure", 0, 41),
     (val_clamp, ":outbreak_pressure", 0, 31),
     (try_begin),
       (gt, ":population_shortage", 0),
       (ge, ":lord_wealth_score", 12),
       (store_mul, ":gold_manpower_pressure", ":population_shortage", ":lord_wealth_score"),
       (val_div, ":gold_manpower_pressure", 45),
       (val_clamp, ":gold_manpower_pressure", 0, 26),
     (try_end),

     (assign, ":active_merc_support", 0),
     (try_begin),
       (gt, ":use_cached_active_support", 0),
       (faction_get_slot, ":active_merc_support", ":faction_no", slot_faction_sod_merc_active_support_cache),
       (val_max, ":active_merc_support", 0),
     (else_try),
       (try_for_parties, ":cur_party"),
         (party_is_active, ":cur_party"),
         (store_faction_of_party, ":party_faction", ":cur_party"),
         (eq, ":party_faction", ":faction_no"),
         (this_or_next|party_slot_eq, ":cur_party", slot_party_type, spt_ai_mercenaries),
         (party_slot_eq, ":cur_party", slot_party_type, spt_mercenary_lord_party),
         (val_add, ":active_merc_support", 1),
       (try_end),
     (try_end),

     (store_sub, ":army_need", 8, ":num_armies"),
     (val_max, ":army_need", 0),
     (val_mul, ":army_need", 8),
     (val_add, ":demand", ":army_need"),
     (store_mul, ":war_need", ":war_count", 12),
     (val_add, ":demand", ":war_need"),
     (val_add, ":demand", ":enemy_pressure"),
     (try_begin),
       (lt, ":power", 40),
       (val_add, ":demand", 30),
     (else_try),
       (lt, ":power", 70),
       (val_add, ":demand", 15),
     (try_end),
     (store_sub, ":health_need", 70, ":campaign_health"),
     (val_max, ":health_need", 0),
     (val_div, ":health_need", 3),
     (val_add, ":demand", ":health_need"),
     (store_div, ":readiness_need", ":marshal_readiness", 5),
     (val_add, ":demand", ":readiness_need"),
     (store_sub, ":follower_gap", ":desired_followers", ":current_followers"),
     (val_max, ":follower_gap", 0),
     (val_mul, ":follower_gap", 4),
     (val_add, ":demand", ":follower_gap"),
     (store_mul, ":unpaid_penalty", ":unpaid_lords", 5),
     (val_add, ":demand", ":unpaid_penalty"),
     (store_mul, ":support_offset", ":active_merc_support", 12),
     (val_sub, ":demand", ":support_offset"),
     (val_add, ":demand", ":village_patrol_demand"),
     (val_add, ":demand", ":world_activity_pressure"),
     (val_add, ":demand", ":gold_manpower_pressure"),
     (val_add, ":demand", ":health_pressure"),
     (val_add, ":demand", ":food_pressure"),
     (val_add, ":demand", ":outbreak_pressure"),
     (val_clamp, ":demand", 0, 100),

     (faction_set_slot, ":faction_no", slot_faction_sod_merc_demand_score, ":demand"),
     (call_script, "script_sod_merc_market_calculate_kingdom_budget", ":faction_no"),
     (assign, ":budget", reg0),
     (assign, ":max_bid", reg1),
     (val_add, ":budget", ":village_patrol_budget"),
     (val_clamp, ":budget", 0, 1000000),
     (store_div, ":village_budget_bid", ":village_patrol_budget", 2),
     (val_add, ":max_bid", ":village_budget_bid"),
     (store_mul, ":world_activity_bid", ":world_activity_pressure", 12),
     (val_add, ":max_bid", ":world_activity_bid"),
     (val_min, ":max_bid", ":budget"),
     (try_begin),
       (ge, ":demand", 70),
       (assign, ":urgency", 3),
       (assign, ":need_type", sod_merc_contract_role_field_company),
     (else_try),
       (ge, ":demand", 40),
       (assign, ":urgency", 2),
       (assign, ":need_type", sod_merc_contract_role_patrol),
     (else_try),
       (gt, ":demand", 0),
       (assign, ":urgency", 1),
       (assign, ":need_type", sod_merc_contract_role_escort),
     (try_end),
     (try_begin),
       (ge, ":follower_gap", 8),
       (assign, ":need_type", sod_merc_contract_role_field_company),
     (else_try),
       (ge, ":world_activity_pressure", 25),
       (assign, ":need_type", sod_merc_contract_role_special_world_activity),
     (else_try),
       (ge, ":enemy_pressure", 35),
       (assign, ":need_type", sod_merc_contract_role_field_company),
     (else_try),
       (ge, ":gold_manpower_pressure", 12),
       (gt, ":war_count", 0),
       (assign, ":need_type", sod_merc_contract_role_field_company),
     (else_try),
       (gt, ":war_count", 0),
       (ge, ":demand", 55),
       (assign, ":need_type", sod_merc_contract_role_field_company),
     (else_try),
       (ge, ":outbreak_pressure", 12),
       (assign, ":need_type", sod_merc_contract_role_garrison_support),
     (else_try),
       (ge, ":health_pressure", 18),
       (assign, ":need_type", sod_merc_contract_role_garrison_support),
     (else_try),
       (ge, ":food_pressure", 16),
       (assign, ":need_type", sod_merc_contract_role_supply_column),
     (else_try),
       (ge, ":gold_manpower_pressure", 8),
       (assign, ":need_type", sod_merc_contract_role_patrol),
     (else_try),
       (lt, ":campaign_health", 45),
       (assign, ":need_type", sod_merc_contract_role_garrison_support),
     (else_try),
       (ge, ":village_patrol_urgency", 2),
       (gt, ":village_patrol_target", 0),
       (assign, ":need_type", sod_merc_contract_role_patrol),
     (else_try),
       (eq, ":war_count", 0),
       (gt, ":economic_strength", 55),
       (assign, ":need_type", sod_merc_contract_role_escort),
     (try_end),
     (call_script, "script_sod_merc_market_select_preferred_guild", ":faction_no", ":use_cached_guild_weight_totals", ":need_type"),
     (assign, ":preferred_guild", reg0),
     (store_current_day, ":cur_day"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_last_bid_day, ":cur_day"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_demand_score, ":demand"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_budget, ":budget"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_max_bid, ":max_bid"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_preferred_guild, ":preferred_guild"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_contract_need_type, ":need_type"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_contract_urgency, ":urgency"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_population_shortage, ":population_shortage"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_lord_wealth_score, ":lord_wealth_score"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_gold_manpower_pressure, ":gold_manpower_pressure"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_health_pressure, ":health_pressure"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_food_pressure, ":food_pressure"),
     (faction_set_slot, ":faction_no", slot_faction_sod_merc_outbreak_pressure, ":outbreak_pressure"),
   (try_end),

   (assign, reg0, ":demand"),
   (assign, reg1, ":budget"),
   (assign, reg2, ":max_bid"),
   (assign, reg3, ":need_type"),
   (assign, reg4, ":urgency"),
   (assign, reg5, ":preferred_guild"),
 ]),
]
