# COST: low
SCRIPTS = [
("sod_count_player_merc_companies",
 [
   (assign, ":company_count", 0),
   (assign, ":total_size", 0),
   (assign, ":next_expiry", 10000),
   (assign, ":sample_guild", 0),

   (store_current_day, ":cur_day"),
   (try_for_parties, ":cur_party"),
     (party_slot_eq, ":cur_party", slot_party_type, spt_player_mercenaries),
     (party_slot_eq, ":cur_party", slot_party_boss, "trp_player"),
     (party_get_num_companions, ":size", ":cur_party"),
     (party_get_slot, ":guild_faction", ":cur_party", slot_party_sod_merc_contract_guild),
     (try_begin),
       (le, ":guild_faction", 0),
       (party_get_slot, ":guild_faction", ":cur_party", slot_party_orginal_faction),
     (try_end),
     (val_add, ":company_count", 1),
     (val_add, ":total_size", ":size"),
     (try_begin),
       (eq, ":sample_guild", 0),
       (assign, ":sample_guild", ":guild_faction"),
     (try_end),
     (party_get_slot, ":contract_end", ":cur_party", slot_party_merc_contract),
     (try_begin),
       (le, ":contract_end", 0),
       (party_get_slot, ":contract_end", ":cur_party", slot_party_sod_merc_contract_term_end),
     (try_end),
     (try_begin),
       (gt, ":contract_end", 0),
       (store_sub, ":days_left", ":contract_end", ":cur_day"),
       (lt, ":days_left", ":next_expiry"),
       (assign, ":next_expiry", ":days_left"),
     (try_end),
   (try_end),

   (try_begin),
     (eq, ":next_expiry", 10000),
     (assign, ":next_expiry", 0),
   (try_end),

   (assign, reg0, ":company_count"),
   (assign, reg1, ":total_size"),
   (assign, reg2, ":next_expiry"),
   (assign, reg3, ":sample_guild"),
 ]),
]
