# COST: low
SCRIPTS = [
("sod_store_castle_patrol_dialog_context",
 [
   (store_script_param, ":patrol_party", 1),
   (party_get_slot, ":origin", ":patrol_party", slot_party_sod_patrol_origin_castle),
   (party_get_slot, ":target", ":patrol_party", slot_party_sod_patrol_route_endpoint),
   (party_get_slot, ":role", ":patrol_party", slot_party_sod_patrol_role),
   (party_get_slot, ":commander", ":patrol_party", slot_party_sod_support_commander),
   (try_begin),
     (gt, ":origin", 0),
     (str_store_party_name, s1, ":origin"),
   (else_try),
     (str_store_string, s1, "@a castle whose seal is not shown"),
   (try_end),
   (try_begin),
     (gt, ":target", 0),
     (str_store_party_name, s2, ":target"),
   (else_try),
     (str_store_string, s2, "@the roads nearby"),
   (try_end),
   (try_begin),
     (eq, ":role", sod_castle_patrol_role_village_shield),
     (str_store_string, s3, "@village shield"),
   (else_try),
     (eq, ":role", sod_castle_patrol_role_border_harasser),
     (str_store_string, s3, "@border harasser"),
   (else_try),
     (eq, ":role", sod_castle_patrol_role_caravan_screen),
     (str_store_string, s3, "@caravan screen"),
   (else_try),
     (eq, ":role", sod_castle_patrol_role_campaign_screen),
     (str_store_string, s3, "@campaign screen"),
   (else_try),
     (eq, ":role", sod_castle_patrol_role_emergency_relief),
     (str_store_string, s3, "@emergency relief patrol"),
   (else_try),
     (str_store_string, s3, "@road patrol"),
   (try_end),
   (try_begin),
     (gt, ":commander", 0),
     (str_store_troop_name, s4, ":commander"),
   (else_try),
     (gt, ":origin", 0),
     (party_get_slot, ":lord", ":origin", slot_town_lord),
     (gt, ":lord", 0),
     (str_store_troop_name, s4, ":lord"),
   (else_try),
     (str_store_string, s4, "@the castle watch captain"),
   (try_end),
   (call_script, "script_sod_find_castle_patrol_threat_target", ":patrol_party"),
   (try_begin),
     (gt, reg0, 0),
     (str_store_party_name, s5, reg0),
     (str_store_string, s6, "@We have seen trouble near {s5}. Give the word and we can turn on it."),
   (else_try),
     (str_store_string, s5, "@no clear raider trail"),
     (str_store_string, s6, "@No urgent raider sign. We need water, shoeing, and clean orders more than heroics."),
   (try_end),
 ]),
]
