# COST: low
SCRIPTS = [
("sod_merc_market_describe_kingdom_demand_to_s20",
 [
   (store_script_param_1, ":faction_no"),

   (str_store_string, s20, "@No active kingdom mercenary demand."),
   (try_begin),
     (is_between, ":faction_no", native_kingdoms_begin, native_kingdoms_end),
     (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
     (call_script, "script_sod_merc_market_calculate_kingdom_demand", ":faction_no", 0, 0, 0, 0),
     (assign, reg20, reg0),
     (assign, reg21, reg1),
     (assign, reg22, reg2),
     (assign, ":need_type", reg3),
     (assign, reg23, reg4),
     (faction_get_slot, ":village_patrol_target", ":faction_no", slot_faction_sod_merc_village_patrol_target),
     (faction_get_slot, reg24, ":faction_no", slot_faction_sod_merc_village_patrol_demand),
     (faction_get_slot, reg25, ":faction_no", slot_faction_sod_merc_population_shortage),
     (faction_get_slot, reg26, ":faction_no", slot_faction_sod_merc_lord_wealth_score),
     (faction_get_slot, reg27, ":faction_no", slot_faction_sod_merc_gold_manpower_pressure),
     (faction_get_slot, reg28, ":faction_no", slot_faction_sod_merc_health_pressure),
     (faction_get_slot, reg29, ":faction_no", slot_faction_sod_merc_food_pressure),
     (faction_get_slot, reg30, ":faction_no", slot_faction_sod_merc_outbreak_pressure),
     (faction_get_slot, ":preferred_guild", ":faction_no", slot_faction_sod_merc_preferred_guild),
     (str_store_faction_name, s21, ":faction_no"),
     (try_begin),
       (is_between, ":preferred_guild", guilds_begin, guilds_end),
       (str_store_faction_name, s24, ":preferred_guild"),
     (else_try),
       (str_store_string, s24, "@no favored guild"),
     (try_end),
     (try_begin),
       (eq, ":need_type", sod_merc_contract_role_field_company),
       (str_store_string, s22, "@field companies"),
     (else_try),
       (eq, ":need_type", sod_merc_contract_role_patrol),
       (str_store_string, s22, "@patrol and road security"),
     (else_try),
       (eq, ":need_type", sod_merc_contract_role_escort),
       (str_store_string, s22, "@escort and trade protection"),
     (else_try),
       (eq, ":need_type", sod_merc_contract_role_garrison_support),
       (str_store_string, s22, "@garrison support"),
     (else_try),
       (eq, ":need_type", sod_merc_contract_role_supply_column),
       (str_store_string, s22, "@supply and relief support"),
     (else_try),
       (str_store_string, s22, "@no specific contract"),
     (try_end),
     (try_begin),
       (gt, ":village_patrol_target", 0),
       (str_store_party_name, s23, ":village_patrol_target"),
       (str_store_string, s20, "@{s21}: demand {reg20}, urgency {reg23}. Budget {reg21}; max bid {reg22}. Preferred need: {s22}. Favored guild: {s24}. Village patrol pressure {reg24}, led by {s23}. Population shortage {reg25}; lord-gold strength {reg26}; gold-for-manpower pressure {reg27}. Settlement health pressure {reg28}; food pressure {reg29}; outbreak pressure {reg30}."),
     (else_try),
       (str_store_string, s20, "@{s21}: demand {reg20}, urgency {reg23}. Budget {reg21}; max bid {reg22}. Preferred need: {s22}. Favored guild: {s24}. Population shortage {reg25}; lord-gold strength {reg26}; gold-for-manpower pressure {reg27}. Settlement health pressure {reg28}; food pressure {reg29}; outbreak pressure {reg30}."),
     (try_end),
   (try_end),
 ]),
]
