# COST: moderate
SCRIPTS = [
("sod_black_khergits_update_horde_state",
 [
   (call_script, "script_sod_black_khergits_enforce_player_standing"),
   (store_num_parties_of_template, ":active_raiders", "pt_black_khergit_raiders"),
   (store_num_parties_of_template, ":active_guards", "pt_black_khergit_night_guard"),
   (store_num_parties_of_template, ":active_camps", "pt_black_khergit_horde_camp"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (assign, ":camp_valid", 0),
   (try_begin),
     (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
     (assign, ":camp_valid", 1),
   (try_end),
   (try_begin),
     (eq, ":camp_valid", 0),
     (assign, ":camp_party", 0),
     (gt, ":active_camps", 0),
     (try_for_parties, ":party_no"),
       (eq, ":camp_party", 0),
       (party_is_active, ":party_no"),
       (party_get_template_id, ":template", ":party_no"),
       (eq, ":template", "pt_black_khergit_horde_camp"),
       (store_faction_of_party, ":party_faction", ":party_no"),
       (eq, ":party_faction", "fac_black_khergits"),
       (assign, ":camp_party", ":party_no"),
     (try_end),
   (try_end),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_get_position, pos1, ":camp_party"),
     (party_set_ai_target_position, ":camp_party", pos1),
   (try_end),

   (faction_get_slot, ":stored_target", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (faction_get_slot, ":target_lock_until", "fac_black_khergits", slot_faction_black_khergit_target_lock_until),
   (store_current_day, ":cur_day"),
   (assign, ":target_center", 0),
   (assign, ":target_score", 0),
   (try_begin),
     (gt, ":camp_party", 0),
     (is_between, ":stored_target", centers_begin, centers_end),
     (call_script, "script_cf_sod_black_khergits_valid_target_center", ":stored_target"),
     (assign, ":target_center", ":stored_target"),
   (else_try),
     (gt, ":target_lock_until", ":cur_day"),
     (is_between, ":stored_target", centers_begin, centers_end),
     (call_script, "script_cf_sod_black_khergits_valid_target_center", ":stored_target"),
     (assign, ":target_center", ":stored_target"),
   (try_end),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (try_for_range, ":center_no", towns_begin, towns_end),
       (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
       (call_script, "script_cf_sod_black_khergits_valid_target_center", ":center_no"),
       (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
       (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
       (assign, ":center_score", ":prosperity"),
       (store_div, ":wealth_score", ":wealth", 80),
       (val_add, ":center_score", ":wealth_score"),
       (try_for_parties, ":caravan_party"),
         (party_is_active, ":caravan_party"),
         (party_get_template_id, ":caravan_template", ":caravan_party"),
         (eq, ":caravan_template", "pt_merchant_caravan"),
         (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":center_no"),
         (le, ":road_dist", 18),
         (val_add, ":center_score", 4),
       (try_end),
       (try_begin),
         (gt, ":camp_party", 0),
         (store_distance_to_party_from_party, ":dist", ":camp_party", ":center_no"),
         (store_sub, ":dist_penalty", ":dist", 20),
         (val_max, ":dist_penalty", 0),
         (val_div, ":dist_penalty", 2),
         (val_sub, ":center_score", ":dist_penalty"),
       (try_end),
       (gt, ":center_score", ":target_score"),
       (assign, ":target_score", ":center_score"),
       (assign, ":target_center", ":center_no"),
     (try_end),
   (try_end),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (assign, ":target_center", "p_town_18"),
   (try_end),

   (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
   (val_clamp, ":pressure", 0, 101),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":camp_party"),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":target_center"),
   (assign, reg0, ":active_raiders"),
   (assign, reg1, ":active_guards"),
   (assign, reg2, ":active_camps"),
   (assign, reg3, ":camp_party"),
   (assign, reg4, ":target_center"),
   (assign, reg5, ":pressure"),
 ]),

("cf_sod_black_khergits_valid_target_center",
 [
   (store_script_param, ":center_no", 1),
   (assign, ":valid", 1),
   (try_begin),
     (neg|is_between, ":center_no", centers_begin, centers_end),
     (assign, ":valid", 0),
   (else_try),
     (neg|party_is_active, ":center_no"),
     (assign, ":valid", 0),
   (else_try),
     (store_faction_of_party, ":center_faction", ":center_no"),
     (eq, ":center_faction", "fac_sod_merc_guild7"),
     (assign, ":valid", 0),
   (else_try),
     (faction_get_slot, ":boar_target", "fac_sod_merc_guild7", slot_faction_boar_target_center),
     (eq, ":center_no", ":boar_target"),
     (assign, ":valid", 0),
   (else_try),
     (try_for_parties, ":boar_party"),
       (party_is_active, ":boar_party"),
       (party_get_template_id, ":boar_template", ":boar_party"),
       (this_or_next|eq, ":boar_template", "pt_boar_clan_fighters"),
       (eq, ":boar_template", "pt_boar_clan_fighters_desert"),
       (party_get_slot, ":boar_destination", ":boar_party", slot_party_sod_boar_frontier_destination),
       (try_begin),
         (eq, ":boar_destination", ":center_no"),
         (assign, ":valid", 0),
       (else_try),
         (store_distance_to_party_from_party, ":boar_dist", ":boar_party", ":center_no"),
         (le, ":boar_dist", 8),
         (assign, ":valid", 0),
       (try_end),
     (try_end),
   (try_end),
   (eq, ":valid", 1),
 ]),

("cf_sod_black_khergits_party_is_horde_camp",
 [
   (store_script_param, ":party_no", 1),
   (gt, ":party_no", 0),
   (party_is_active, ":party_no"),
   (party_get_template_id, ":template", ":party_no"),
   (eq, ":template", "pt_black_khergit_horde_camp"),
   (store_faction_of_party, ":party_faction", ":party_no"),
   (eq, ":party_faction", "fac_black_khergits"),
  ]),

("cf_sod_black_khergits_party_is_camped",
 [
   (store_script_param, ":party_no", 1),
   (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":party_no"),
   (party_get_slot, ":camped_center", ":party_no", slot_party_black_khergit_origin),
   (party_get_slot, ":target_center", ":party_no", slot_party_black_khergit_target),
   (is_between, ":camped_center", centers_begin, centers_end),
   (eq, ":camped_center", ":target_center"),
 ]),

("cf_sod_black_khergits_party_is_raider",
 [
   (store_script_param, ":party_no", 1),
   (gt, ":party_no", 0),
   (party_is_active, ":party_no"),
   (party_get_template_id, ":template", ":party_no"),
   (eq, ":template", "pt_black_khergit_raiders"),
   (store_faction_of_party, ":party_faction", ":party_no"),
   (eq, ":party_faction", "fac_black_khergits"),
 ]),

("cf_sod_black_khergits_party_is_horde_force",
 [
   (store_script_param, ":party_no", 1),
   (gt, ":party_no", 0),
   (party_is_active, ":party_no"),
   (party_get_template_id, ":template", ":party_no"),
   (this_or_next|eq, ":template", "pt_black_khergit_horde_camp"),
   (this_or_next|eq, ":template", "pt_black_khergit_raiders"),
   (eq, ":template", "pt_black_khergit_night_guard"),
   (store_faction_of_party, ":party_faction", ":party_no"),
   (eq, ":party_faction", "fac_black_khergits"),
 ]),

("sod_black_khergits_initialize_world_presence",
 [
   (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
   (try_begin),
     (le, ":pressure", 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, 18),
   (try_end),
   (faction_get_slot, ":tribute", "fac_black_khergits", slot_faction_black_khergit_tribute),
   (try_begin),
     (lt, ":tribute", 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_tribute, 0),
   (try_end),
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (call_script, "script_sod_black_khergits_choose_relocation_target"),
   (try_end),
   (call_script, "script_sod_black_khergits_spawn_or_recover_camp"),
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (call_script, "script_sod_black_khergits_spawn_raids"),
   (call_script, "script_sod_black_khergits_update_horde_state"),
 ]),

("sod_black_khergits_process_pressure_economy",
 [
   (store_current_day, ":cur_day"),
   (faction_get_slot, ":last_pressure_day", "fac_black_khergits", slot_faction_black_khergit_last_pressure_day),
   (try_begin),
     (gt, ":cur_day", ":last_pressure_day"),
     (call_script, "script_sod_black_khergits_update_horde_state"),
     (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
     (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
     (store_num_parties_of_template, ":active_raiders", "pt_black_khergit_raiders"),
     (store_num_parties_of_template, ":active_guards", "pt_black_khergit_night_guard"),
      (try_begin),
        (gt, ":camp_party", 0),
        (party_is_active, ":camp_party"),
        (val_add, ":pressure", 3),
        (store_mul, ":raider_pressure", ":active_raiders", 2),
        (val_add, ":pressure", ":raider_pressure"),
        (val_add, ":pressure", ":active_guards"),
        (try_begin),
          (is_between, ":target_center", centers_begin, centers_end),
          (party_get_slot, ":target_prosperity", ":target_center", slot_town_prosperity),
          (store_div, ":target_pressure", ":target_prosperity", 18),
          (val_add, ":pressure", ":target_pressure"),
          (try_for_parties, ":caravan_party"),
            (party_is_active, ":caravan_party"),
            (party_get_template_id, ":caravan_template", ":caravan_party"),
            (eq, ":caravan_template", "pt_merchant_caravan"),
            (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":target_center"),
            (le, ":road_dist", 18),
            (val_add, ":pressure", 1),
          (try_end),
        (try_end),
      (else_try),
        (val_sub, ":pressure", 5),
      (try_end),
     (val_clamp, ":pressure", 0, 101),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":pressure"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_pressure_day, ":cur_day"),
     (call_script, "script_sod_black_khergits_enforce_player_standing"),
   (try_end),
 ]),

("sod_black_khergits_lock_camped_ai",
 [
   (store_script_param, ":camp_party", 1),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (party_get_template_id, ":template", ":camp_party"),
     (eq, ":template", "pt_black_khergit_horde_camp"),
     (party_get_position, pos1, ":camp_party"),
     (party_set_ai_target_position, ":camp_party", pos1),
     (party_set_ai_initiative, ":camp_party", 0),
     (party_set_ai_behavior, ":camp_party", ai_bhvr_hold),
     (party_set_flags, ":camp_party", pf_default_behavior, 0),
     (party_set_slot, ":camp_party", slot_party_ai_state, spai_holding_center),
     (party_set_slot, ":camp_party", slot_party_ai_object, 0),
     (party_set_slot, ":camp_party", slot_party_ai_substate, 0),
     (party_set_slot, ":camp_party", slot_party_follow_me, 0),
   (try_end),
 ]),

("sod_black_khergits_spawn_or_recover_camp",
 [
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (faction_get_slot, ":disrupted_until", "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until),
   (store_current_day, ":cur_day"),
   (assign, ":camp_valid", 0),
   (try_begin),
     (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
     (assign, ":camp_valid", 1),
   (try_end),
   (try_begin),
     (eq, ":camp_valid", 0),
     (assign, ":camp_party", 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, 0),
   (try_end),
   (try_begin),
     (le, ":camp_party", 0),
     (le, ":disrupted_until", ":cur_day"),
      (assign, ":spawn_center", "p_black_khergit_spawn_point"),
     (set_spawn_radius, 1),
     (spawn_around_party, ":spawn_center", "pt_black_khergit_horde_camp"),
     (assign, ":camp_party", reg0),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (party_set_faction, ":camp_party", "fac_black_khergits"),
     (party_set_slot, ":camp_party", slot_party_black_khergit_camp_activity, 1),
     (party_set_slot, ":camp_party", slot_party_black_khergit_origin, 0),
     (try_begin),
       (is_between, ":target_center", centers_begin, centers_end),
       (party_set_slot, ":camp_party", slot_party_black_khergit_target, ":target_center"),
     (else_try),
       (party_set_slot, ":camp_party", slot_party_black_khergit_target, ":spawn_center"),
     (try_end),
     (party_set_slot, ":camp_party", slot_party_black_khergit_role, sod_black_khergit_role_camp),
     (party_set_banner_icon, ":camp_party", "icon_banner_302"),
     (party_set_icon, ":camp_party", "icon_khergit_horseman_b"),
     (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":camp_party"),
     (try_begin),
       (is_between, ":target_center", centers_begin, centers_end),
       (party_set_ai_initiative, ":camp_party", 0),
       (party_set_ai_behavior, ":camp_party", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":camp_party", ":target_center"),
     (else_try),
       (call_script, "script_sod_black_khergits_lock_camped_ai", ":camp_party"),
     (try_end),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":camp_party"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, ":cur_day"),
     (display_message, "@The Black Khergits are rumored to have invaded Calradia.", 0x222222),
   (try_end),
 ]),

("sod_black_khergits_process_day_cycle",
 [
   (call_script, "script_sod_black_khergits_spawn_or_recover_camp"),
   (call_script, "script_sod_black_khergits_update_scout_intelligence"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
  (try_begin),
    (gt, ":camp_party", 0),
    (party_is_active, ":camp_party"),
    (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
    (call_script, "script_sod_black_khergits_release_hero_prisoners", ":camp_party"),
   (try_end),
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (store_current_day, ":cur_day"),
   (store_current_hours, ":cur_hours"),
   (store_mod, ":hour_of_day", ":cur_hours", 24),
   (assign, ":is_night", 0),
   (try_begin),
     (this_or_next|ge, ":hour_of_day", 18),
     (lt, ":hour_of_day", 6),
     (assign, ":is_night", 1),
   (try_end),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (call_script, "script_sod_black_khergits_choose_relocation_target"),
     (assign, ":target_center", reg0),
   (try_end),

  (try_begin),
    (gt, ":camp_party", 0),
    (party_is_active, ":camp_party"),
    (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
     (is_between, ":target_center", centers_begin, centers_end),
     (party_set_slot, ":camp_party", slot_party_black_khergit_target, ":target_center"),
     (party_slot_eq, ":camp_party", slot_party_black_khergit_target, ":target_center"),
     (store_distance_to_party_from_party, ":camp_target_dist", ":camp_party", ":target_center"),
     (try_for_parties, ":guard_party"),
       (party_is_active, ":guard_party"),
       (party_get_template_id, ":guard_template", ":guard_party"),
       (eq, ":guard_template", "pt_black_khergit_night_guard"),
       (party_get_attached_to, ":attached_to", ":guard_party"),
       (try_begin),
         (eq, ":is_night", 0),
         (try_begin),
           (ge, ":attached_to", 0),
           (party_detach, ":guard_party"),
         (try_end),
         (party_set_ai_behavior, ":guard_party", ai_bhvr_travel_to_party),
         (party_set_ai_object, ":guard_party", ":camp_party"),
       (else_try),
         (eq, ":is_night", 1),
         (store_distance_to_party_from_party, ":guard_dist", ":guard_party", ":camp_party"),
         (try_begin),
           (le, ":guard_dist", 1),
           (party_attach_to_party, ":guard_party", ":camp_party"),
           (party_set_ai_behavior, ":guard_party", ai_bhvr_hold),
         (else_try),
           (party_set_ai_behavior, ":guard_party", ai_bhvr_travel_to_party),
           (party_set_ai_object, ":guard_party", ":camp_party"),
         (try_end),
       (try_end),
     (try_end),
     (try_begin),
       (le, ":camp_target_dist", 3),
       (party_get_slot, ":camped_origin", ":camp_party", slot_party_black_khergit_origin),
       (try_begin),
         (neq, ":camped_origin", ":target_center"),
         (party_set_slot, ":camp_party", slot_party_black_khergit_origin, ":target_center"),
         (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, ":cur_day"),
         (call_script, "script_sod_report_record_center_event", sod_report_category_world, sod_report_severity_notable, ":target_center", -1, 1, sod_report_reason_black_khergit_raid),
       (try_end),
       (faction_get_slot, ":last_migration_day", "fac_black_khergits", slot_faction_black_khergit_last_migration_day),
       (store_sub, ":days_camped", ":cur_day", ":last_migration_day"),
       (try_begin),
         (ge, ":days_camped", 4),
         (call_script, "script_sod_black_khergits_choose_relocation_target"),
         (assign, ":target_center", reg0),
         (party_set_slot, ":camp_party", slot_party_black_khergit_target, ":target_center"),
         (party_set_slot, ":camp_party", slot_party_black_khergit_origin, 0),
         (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, ":cur_day"),
         (try_for_parties, ":guard_party"),
           (party_is_active, ":guard_party"),
           (party_get_template_id, ":guard_template", ":guard_party"),
           (eq, ":guard_template", "pt_black_khergit_night_guard"),
           (neq, ":guard_party", "p_main_party"),
           (remove_party, ":guard_party"),
         (try_end),
         (party_set_icon, ":camp_party", "icon_khergit_horseman_b"),
         (party_set_ai_initiative, ":camp_party", 0),
         (party_set_ai_behavior, ":camp_party", ai_bhvr_travel_to_party),
         (party_set_ai_object, ":camp_party", ":target_center"),
         (call_script, "script_sod_report_record_center_event", sod_report_category_world, sod_report_severity_notable, ":target_center", -1, 1, sod_report_reason_black_khergit_raid),
        (else_try),
          # A pitched camp remains stationary until the relocation branch above
          # deliberately clears its camped origin and assigns a new target.
          (party_set_icon, ":camp_party", "icon_camp"),
          (call_script, "script_sod_black_khergits_lock_camped_ai", ":camp_party"),
          (try_begin),
            (eq, ":is_night", 1),
            (store_num_parties_of_template, ":active_guards", "pt_black_khergit_night_guard"),
            (lt, ":active_guards", 2),
            (set_spawn_radius, 3),
            (spawn_around_party, ":camp_party", "pt_black_khergit_night_guard"),
            (assign, ":guard_party", reg0),
            (gt, ":guard_party", 0),
            (party_is_active, ":guard_party"),
            (party_set_faction, ":guard_party", "fac_black_khergits"),
            (party_set_slot, ":guard_party", slot_party_black_khergit_camp_activity, 1),
            (party_set_slot, ":guard_party", slot_party_black_khergit_origin, ":camp_party"),
            (party_set_slot, ":guard_party", slot_party_black_khergit_target, ":target_center"),
            (party_set_slot, ":guard_party", slot_party_black_khergit_role, sod_black_khergit_role_guard),
            (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":guard_party"),
            (call_script, "script_party_set_ai_state", ":guard_party", spai_patrolling_around_center, ":camp_party"),
            (party_set_ai_patrol_radius, ":guard_party", 5),
          (try_end),
       (try_end),
     (else_try),
       (gt, ":camp_target_dist", 3),
       (party_set_slot, ":camp_party", slot_party_black_khergit_origin, 0),
       (party_set_icon, ":camp_party", "icon_khergit_horseman_b"),
       (party_set_ai_initiative, ":camp_party", 0),
       (party_set_ai_behavior, ":camp_party", ai_bhvr_travel_to_party),
       (party_set_ai_object, ":camp_party", ":target_center"),
     (try_end),
   (try_end),
   (call_script, "script_sod_black_khergits_process_pressure_economy"),
 ]),

("sod_black_khergits_spawn_raids",
 [
   (call_script, "script_sod_black_khergits_spawn_or_recover_camp"),
   (call_script, "script_sod_black_khergits_process_scattered_raider_aftermath"),
   (store_relation, ":player_relation", "fac_player_supporters_faction", "fac_black_khergits"),
   (try_begin),
     (ge, ":player_relation", 100),
     (assign, ":stop_for_player_friendship", 1),
   (else_try),
     (assign, ":stop_for_player_friendship", 0),
   (try_end),
   (try_begin),
     (eq, ":stop_for_player_friendship", 0),
     (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
     (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
     (try_begin),
       (neg|is_between, ":target_center", centers_begin, centers_end),
       (assign, ":target_center", "p_town_18"),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":target_center"),
     (try_end),
     (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (store_num_parties_of_template, ":active_raiders", "pt_black_khergit_raiders"),
     (store_current_day, ":cur_day"),
     (faction_get_slot, ":last_spawn_day", "fac_black_khergits", slot_faction_black_khergit_last_spawn_day),
     (store_sub, ":days_since_spawn", ":cur_day", ":last_spawn_day"),
     (assign, ":spawned_raider", 0),
     (assign, ":raider_cap", 1),
     (try_begin),
       (ge, ":pressure", 30),
       (val_add, ":raider_cap", 1),
     (try_end),
     (try_begin),
       (ge, ":pressure", 65),
       (val_add, ":raider_cap", 1),
     (try_end),
      (try_begin),
        (gt, ":camp_party", 0),
        (party_is_active, ":camp_party"),
        (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
        (call_script, "script_cf_sod_companion_in_main_party", "trp_npc1"),
       (troop_slot_ge, "trp_npc1", slot_troop_companion_approval, 45),
       (troop_slot_eq, "trp_npc1", slot_troop_companion_role, sod_companion_role_scout),
       (troop_slot_eq, "trp_npc1", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
       (val_sub, ":pressure", 2),
       (val_max, ":pressure", 0),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":pressure"),
       (val_sub, ":raider_cap", 1),
       (val_max, ":raider_cap", 1),
       (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
       (try_begin),
         (lt, ":last_raid_report_day", ":cur_day"),
         (display_message, "@Borcha finds a hidden road before the Black Khergit camp can flood it with riders.", 0x99CCFF),
         (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
       (try_end),
     (try_end),
    (try_begin),
      (gt, ":camp_party", 0),
      (party_is_active, ":camp_party"),
      (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
      (lt, ":active_raiders", ":raider_cap"),
       (this_or_next|ge, ":days_since_spawn", 2),
       (lt, ":last_spawn_day", 1),
       (set_spawn_radius, 5),
       (spawn_around_party, ":camp_party", "pt_black_khergit_raiders"),
       (assign, ":raider_party", reg0),
       (gt, ":raider_party", 0),
       (party_is_active, ":raider_party"),
       (party_set_faction, ":raider_party", "fac_black_khergits"),
       (party_set_slot, ":raider_party", slot_party_black_khergit_camp_activity, 1),
       (party_set_slot, ":raider_party", slot_party_black_khergit_origin, ":camp_party"),
       (party_set_slot, ":raider_party", slot_party_black_khergit_target, ":target_center"),
       (party_set_slot, ":raider_party", slot_party_black_khergit_role, sod_black_khergit_role_raider),
       (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":raider_party"),
       (try_begin),
         (is_between, ":target_center", centers_begin, centers_end),
         (call_script, "script_party_set_ai_state", ":raider_party", spai_patrolling_around_center, ":target_center"),
         (party_set_ai_patrol_radius, ":raider_party", 14),
       (else_try),
         (call_script, "script_party_set_ai_state", ":raider_party", spai_patrolling_around_center, ":camp_party"),
         (party_set_ai_patrol_radius, ":raider_party", 12),
       (try_end),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_spawn_day, ":cur_day"),
       (call_script, "script_sod_report_record_center_event", sod_report_category_security, sod_report_severity_urgent, ":target_center", -1, 1, sod_report_reason_black_khergit_raid),
       (assign, ":spawned_raider", 1),
       (val_add, ":active_raiders", 1),
     (try_end),

     (try_begin),
       (gt, ":active_raiders", 0),
       (faction_get_slot, ":last_harassment_day", "fac_black_khergits", slot_faction_black_khergit_last_harassment_day),
       (this_or_next|gt, ":cur_day", ":last_harassment_day"),
       (eq, ":spawned_raider", 1),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_harassment_day, ":cur_day"),
       (try_for_range, ":center_no", villages_begin, villages_end),
         (party_is_active, ":center_no"),
         (assign, ":raided", 0),
         (try_for_parties, ":raider_party"),
           (eq, ":raided", 0),
           (party_is_active, ":raider_party"),
           (call_script, "script_cf_sod_black_khergits_party_is_raider", ":raider_party"),
           (store_distance_to_party_from_party, ":raid_dist", ":raider_party", ":center_no"),
           (le, ":raid_dist", 7),
           (assign, ":raided", 1),
         (try_end),
           (try_begin),
             (eq, ":raided", 1),
           (party_is_active, ":center_no"),
           (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
           (try_begin),
             (gt, ":wealth", 250),
             (store_sub, ":wealth_delta", 250, ":wealth"),
             (val_max, ":wealth_delta", -12),
             (call_script, "script_sod_center_apply_wealth_delta", ":center_no", ":wealth_delta"),
             (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
             (try_begin),
               (lt, ":last_raid_report_day", ":cur_day"),
              (store_mul, ":raid_impact", ":wealth_delta", -1),
              (call_script, "script_sod_report_record_center_event", sod_report_category_security, sod_report_severity_urgent, ":center_no", -1, ":raid_impact", sod_report_reason_black_khergit_raid),
               (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
             (try_end),
           (try_end),
           (party_get_slot, ":prosperity", ":center_no", slot_center_sod_local_prosperity),
           (try_begin),
             (gt, ":prosperity", 25),
             (call_script, "script_sod_center_apply_local_prosperity_delta", ":center_no", -1),
           (try_end),
         (try_end),
       (try_end),

       (try_for_parties, ":raider_party"),
         (party_is_active, ":raider_party"),
         (call_script, "script_cf_sod_black_khergits_party_is_raider", ":raider_party"),
         (try_for_parties, ":caravan_party"),
           (party_is_active, ":caravan_party"),
           (party_get_template_id, ":caravan_template", ":caravan_party"),
           (eq, ":caravan_template", "pt_merchant_caravan"),
           (store_distance_to_party_from_party, ":caravan_dist", ":raider_party", ":caravan_party"),
           (lt, ":caravan_dist", 8),
           (party_set_ai_behavior, ":raider_party", ai_bhvr_attack_party),
           (party_set_ai_object, ":raider_party", ":caravan_party"),
           (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
           (try_begin),
             (lt, ":last_raid_report_day", ":cur_day"),
            (call_script, "script_sod_report_record_event", sod_report_category_roads, sod_report_severity_urgent, sod_report_subject_party, ":raider_party", sod_report_subject_party, ":caravan_party", 1, sod_report_reason_black_khergit_raid),
             (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
           (try_end),
         (try_end),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_apply_safe_passage_to_party",
 [
   (store_script_param_1, ":party_no"),
   (faction_get_slot, ":safe_until", "fac_black_khergits", slot_faction_black_khergit_safe_passage_until),
   (store_current_hours, ":cur_hours"),
   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (gt, ":safe_until", ":cur_hours"),
     (store_sub, ":safe_hours", ":safe_until", ":cur_hours"),
     (party_set_slot, ":party_no", slot_party_ignore_player_until, ":safe_until"),
     (party_ignore_player, ":party_no", ":safe_hours"),
   (try_end),
 ]),

("sod_black_khergits_scatter_or_cleanup_patrols",
 [
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (assign, ":target_center", "p_town_18"),
   (try_end),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (party_get_template_id, ":template", ":party_no"),
     (try_begin),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (neq, ":party_no", "p_main_party"),
       (remove_party, ":party_no"),
     (else_try),
       (eq, ":template", "pt_black_khergit_raiders"),
       (party_set_slot, ":party_no", slot_party_black_khergit_origin, 0),
       (party_set_slot, ":party_no", slot_party_black_khergit_target, ":target_center"),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_raider),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":target_center"),
       (party_set_ai_patrol_radius, ":party_no", 18),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_refresh_active_parties",
 [
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (store_current_hours, ":cur_hours"),
   (store_mod, ":hour_of_day", ":cur_hours", 24),
   (assign, ":is_night", 0),
   (try_begin),
     (this_or_next|ge, ":hour_of_day", 18),
     (lt, ":hour_of_day", 6),
     (assign, ":is_night", 1),
   (try_end),
   (try_begin),
     (neg|is_between, ":target_center", centers_begin, centers_end),
     (assign, ":target_center", "p_town_18"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":target_center"),
   (try_end),
   (assign, ":camp_valid", 0),
   (try_begin),
     (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
     (assign, ":camp_valid", 1),
   (try_end),
   (try_begin),
     (eq, ":camp_valid", 0),
     (assign, ":camp_party", 0),
     (try_for_parties, ":party_no"),
       (eq, ":camp_party", 0),
       (party_is_active, ":party_no"),
       (party_get_template_id, ":template", ":party_no"),
       (eq, ":template", "pt_black_khergit_horde_camp"),
       (assign, ":camp_party", ":party_no"),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":party_no"),
     (try_end),
   (try_end),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (party_get_template_id, ":template", ":party_no"),
     (assign, ":is_horde_party", 0),
     (try_begin),
       (eq, ":template", "pt_black_khergit_horde_camp"),
       (assign, ":is_horde_party", 1),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_camp),
       (assign, ":camp_party", ":party_no"),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, ":party_no"),
     (else_try),
       (eq, ":template", "pt_black_khergit_raiders"),
       (assign, ":is_horde_party", 1),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_raider),
     (else_try),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (assign, ":is_horde_party", 1),
       (party_set_slot, ":party_no", slot_party_black_khergit_role, sod_black_khergit_role_guard),
     (try_end),
     (eq, ":is_horde_party", 1),
     (party_set_slot, ":party_no", slot_party_black_khergit_camp_activity, 1),
     (party_set_slot, ":party_no", slot_party_black_khergit_target, ":target_center"),
     (party_set_slot, ":party_no", slot_party_sod_boar_frontier_activity, 0),
     (party_set_slot, ":party_no", slot_party_sod_boar_frontier_origin, 0),
     (party_set_slot, ":party_no", slot_party_sod_boar_frontier_destination, 0),
     (call_script, "script_sod_black_khergits_apply_safe_passage_to_party", ":party_no"),
      (try_begin),
        (eq, ":template", "pt_black_khergit_horde_camp"),
        (call_script, "script_cf_sod_black_khergits_party_is_camped", ":party_no"),
        (party_set_icon, ":party_no", "icon_camp"),
        (call_script, "script_sod_black_khergits_lock_camped_ai", ":party_no"),
      (else_try),
        (eq, ":template", "pt_black_khergit_horde_camp"),
        (is_between, ":target_center", centers_begin, centers_end),
        (party_set_icon, ":party_no", "icon_khergit_horseman_b"),
        (party_set_ai_initiative, ":party_no", 0),
        (party_set_ai_behavior, ":party_no", ai_bhvr_travel_to_party),
        (party_set_ai_object, ":party_no", ":target_center"),
     (else_try),
       (eq, ":template", "pt_black_khergit_raiders"),
       (is_between, ":target_center", centers_begin, centers_end),
       (try_begin),
         (gt, ":camp_party", 0),
         (party_set_slot, ":party_no", slot_party_black_khergit_origin, ":camp_party"),
       (try_end),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":target_center"),
       (party_set_ai_patrol_radius, ":party_no", 14),
     (else_try),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (eq, ":is_night", 1),
       (gt, ":camp_party", 0),
       (party_set_slot, ":party_no", slot_party_black_khergit_origin, ":camp_party"),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":camp_party"),
       (party_set_ai_patrol_radius, ":party_no", 5),
     (else_try),
       (eq, ":template", "pt_black_khergit_night_guard"),
       (eq, ":is_night", 0),
       (is_between, ":target_center", centers_begin, centers_end),
       (call_script, "script_party_set_ai_state", ":party_no", spai_patrolling_around_center, ":target_center"),
       (party_set_ai_patrol_radius, ":party_no", 8),
     (try_end),
   (try_end),
   (try_for_parties, ":party_no"),
     (party_is_active, ":party_no"),
     (party_get_template_id, ":template", ":party_no"),
     (neq, ":template", "pt_black_khergit_horde_camp"),
     (neq, ":template", "pt_black_khergit_raiders"),
     (neq, ":template", "pt_black_khergit_night_guard"),
     (party_slot_eq, ":party_no", slot_party_black_khergit_camp_activity, 1),
     (party_set_slot, ":party_no", slot_party_black_khergit_camp_activity, 0),
     (party_set_slot, ":party_no", slot_party_black_khergit_origin, 0),
     (party_set_slot, ":party_no", slot_party_black_khergit_target, 0),
     (party_set_slot, ":party_no", slot_party_black_khergit_role, 0),
     (party_set_slot, ":party_no", slot_party_black_khergit_response_target, 0),
     (party_set_slot, ":party_no", slot_party_black_khergit_response_until, 0),
   (try_end),
 ]),

("sod_black_khergits_apply_player_action",
 [
   (store_script_param_1, ":action"),
   (store_script_param_2, ":magnitude"),
   (val_max, ":magnitude", 1),
   (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
   (faction_get_slot, ":tribute", "fac_black_khergits", slot_faction_black_khergit_tribute),
  (try_begin),
    (eq, ":action", sod_black_khergit_action_tribute),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_tribute, 4),
    (call_script, "script_sod_companion_try_klethi_old_job_incident", 1, 2),
    (val_add, ":tribute", ":magnitude"),
     (val_sub, ":pressure", 3),
     (store_current_hours, ":safe_until"),
     (store_div, ":safe_hours", ":magnitude", 5),
     (val_clamp, ":safe_hours", 24, 169),
     (val_add, ":safe_until", ":safe_hours"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_safe_passage_until, ":safe_until"),
     (call_script, "script_sod_black_khergits_refresh_active_parties"),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 1),
  (else_try),
    (eq, ":action", sod_black_khergit_action_bribe_target),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_bribe, 4),
    (call_script, "script_sod_companion_try_klethi_old_job_incident", 1, 3),
    (val_add, ":tribute", ":magnitude"),
      (val_add, ":pressure", 4),
      (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 2),
      (call_script, "script_sod_black_khergits_choose_bribed_target"),
      (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
      (store_current_day, ":lock_until"),
      (val_add, ":lock_until", 7),
      (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, ":lock_until"),
  (try_begin),
    (is_between, ":target_center", centers_begin, centers_end),
    (display_message, "@The Black Khergit Khan takes the silver. His riders turn toward the paid mark for several days.", 0x222222),
    (store_faction_of_party, ":target_faction", ":target_center"),
        (call_script, "script_sod_diplomacy_apply_memory", ":target_faction", sod_diplomacy_memory_border_raid, 1),
      (try_end),
      (call_script, "script_sod_black_khergits_refresh_active_parties"),
    (else_try),
    (eq, ":action", sod_black_khergit_action_persuade_enemy),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_bribe, 3),
    (call_script, "script_sod_companion_try_klethi_old_job_incident", 1, 2),
    (val_add, ":pressure", 6),
      (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 1),
      (call_script, "script_sod_black_khergits_choose_enemy_target"),
      (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
      (store_current_day, ":lock_until"),
      (val_add, ":lock_until", 5),
      (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, ":lock_until"),
  (try_begin),
    (is_between, ":target_center", centers_begin, centers_end),
    (display_message, "@Black Khergit scouts carry your enemy's name into the steppe. The horde turns toward the chosen mark for now.", 0x222222),
    (store_faction_of_party, ":target_faction", ":target_center"),
        (call_script, "script_sod_diplomacy_apply_memory", ":target_faction", sod_diplomacy_memory_border_raid, 1),
      (try_end),
      (call_script, "script_sod_black_khergits_refresh_active_parties"),
  (else_try),
    (eq, ":action", sod_black_khergit_action_attack_camp),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 4),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_black_khergit_camp_defeat, 4),
    (call_script, "script_sod_companion_try_baheshtur_saddle_incident", 2, 4),
    (val_sub, ":pressure", 30),
     (val_sub, ":tribute", ":magnitude"),
     (store_current_day, ":cur_day"),
     (store_div, ":disruption_days", ":magnitude", 5),
     (val_clamp, ":disruption_days", 7, 22),
     (val_add, ":cur_day", ":disruption_days"),
     (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
     (call_script, "script_sod_black_khergits_resolve_broken_camp_prisoners", ":camp_party", "p_main_party"),
     (try_begin),
       (gt, reg44, 0),
       (display_message, "@You take {reg44} rescued captives under guard before the black tents burn.", 0x99CCFF),
     (else_try),
       (gt, reg45, 0),
       (display_message, "@You cut loose {reg45} captives from the black ropes before the camp collapses.", 0x99CCFF),
     (try_end),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until, ":cur_day"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, 0),
     (call_script, "script_sod_black_khergits_scatter_or_cleanup_patrols"),
     (display_message, "@With the Black Khergit camp broken, its night guards vanish and loose raiders scatter along the roads.", 0x222222),
     (call_script, "script_change_troop_renown", "trp_player", 12),
     (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
     (try_begin),
       (is_between, ":target_center", centers_begin, centers_end),
       (call_script, "script_change_player_relation_with_center", ":target_center", 2),
      (display_message, "@Merchants and villagers breathe easier: the horde's heart has been broken for now.", 0x99CCFF),
     (try_end),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", -8),
  (else_try),
    (eq, ":action", sod_black_khergit_action_defeat_raiders),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 2),
    (call_script, "script_sod_companion_try_baheshtur_saddle_incident", 1, 2),
    (val_sub, ":pressure", ":magnitude"),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", -2),
  (else_try),
    (eq, ":action", sod_black_khergit_action_defeat_guards),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_safe_roadcraft, 2),
    (call_script, "script_sod_companion_try_baheshtur_saddle_incident", 1, 2),
    (val_sub, ":pressure", ":magnitude"),
     (val_sub, ":tribute", 5),
     (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", -4),
  (else_try),
    (eq, ":action", sod_black_khergit_action_duel_victory),
    (val_sub, ":pressure", 22),
    (val_sub, ":tribute", 10),
    (call_script, "script_sod_black_khergits_choose_relocation_target"),
    (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
    (store_current_day, ":lock_until"),
    (val_add, ":lock_until", 8),
    (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_lock_until, ":lock_until"),
    (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, 0),
    (call_script, "script_sod_black_khergits_refresh_active_parties"),
    (call_script, "script_change_troop_renown", "trp_player", 15),
    (call_script, "script_sod_black_khergits_strengthen_khan_after_duel_loss"),
    (try_begin),
      (is_between, ":target_center", centers_begin, centers_end),
      (display_message, "@Temujin Black Sky yields the field. The Black Khergit camp pulls its stakes and rides toward its next mark.", 0x99CCFF),
    (else_try),
      (display_message, "@Temujin Black Sky yields the field. The Black Khergit camp pulls its stakes and vanishes onto a colder road.", 0x99CCFF),
    (try_end),
    (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 10),
    (call_script, "script_sod_black_khergits_enforce_player_standing"),
  (else_try),
    (eq, ":action", sod_black_khergit_action_duel_defeat),
    (val_add, ":pressure", 8),
    (display_message, "@Temujin Black Sky leaves you breathing. The horde laughs, and its riders grow bold.", 0xCC9966),
    (call_script, "script_change_player_relation_with_faction", "fac_black_khergits", 1),
   (try_end),
   (val_clamp, ":pressure", 0, 101),
   (val_clamp, ":tribute", 0, 5000),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":pressure"),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_tribute, ":tribute"),
   (call_script, "script_sod_black_khergits_enforce_player_standing"),
   (assign, reg0, ":pressure"),
    (assign, reg1, ":tribute"),
 ]),

("sod_black_khergits_strengthen_khan_after_duel_loss",
 [
   (troop_get_slot, ":duel_losses", "trp_black_khergit_khan", slot_troop_black_khergit_khan_duel_losses),
   (val_add, ":duel_losses", 1),
   (troop_set_slot, "trp_black_khergit_khan", slot_troop_black_khergit_khan_duel_losses, ":duel_losses"),
   (store_mul, ":xp_gain", ":duel_losses", 750),
   (val_add, ":xp_gain", 2500),
   (val_clamp, ":xp_gain", 2500, 9001),
   (add_xp_to_troop, ":xp_gain", "trp_black_khergit_khan"),
   (troop_raise_attribute, "trp_black_khergit_khan", ca_strength, 1),
   (troop_raise_attribute, "trp_black_khergit_khan", ca_agility, 1),
   (try_begin),
     (store_mod, ":even_loss", ":duel_losses", 2),
     (eq, ":even_loss", 0),
     (troop_raise_attribute, "trp_black_khergit_khan", ca_charisma, 1),
     (troop_raise_skill, "trp_black_khergit_khan", "skl_tactics", 1),
   (try_end),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_ironflesh", 1),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_power_strike", 1),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_riding", 1),
   (troop_raise_skill, "trp_black_khergit_khan", "skl_horse_archery", 1),
   (store_mul, ":prof_bonus", ":duel_losses", 2),
   (val_add, ":prof_bonus", 10),
   (val_clamp, ":prof_bonus", 10, 26),
   (troop_raise_proficiency_linear, "trp_black_khergit_khan", wpt_one_handed_weapon, ":prof_bonus"),
   (troop_raise_proficiency_linear, "trp_black_khergit_khan", wpt_polearm, ":prof_bonus"),
   (troop_raise_proficiency_linear, "trp_black_khergit_khan", wpt_archery, ":prof_bonus"),
   (assign, reg44, ":duel_losses"),
   (assign, reg45, ":xp_gain"),
   (display_message, "@Temujin Black Sky remembers defeat. His next challenge will be harder: duel scars {reg44}, experience gained {reg45}.", 0xCC9966),
 ]),

("sod_black_khergits_enforce_player_standing",
 [
   (store_relation, ":player_relation", "fac_player_supporters_faction", "fac_black_khergits"),
   (try_begin),
     (ge, ":player_relation", 100),
     (set_relation, "fac_black_khergits", "fac_player_supporters_faction", 100),
     (set_relation, "fac_black_khergits", "fac_player_faction", 100),
     (set_relation, "fac_player_supporters_faction", "fac_black_khergits", 100),
     (set_relation, "fac_player_faction", "fac_black_khergits", 100),
     (store_current_hours, ":safe_until"),
     (val_add, ":safe_until", 8760),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_safe_passage_until, ":safe_until"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, 0),
   (try_end),
 ]),

("sod_black_khergits_prepare_hire_offer",
 [
   (assign, "$g_sod_black_khergit_buy_screen_active", 0),
   (store_relation, ":relation", "fac_player_supporters_faction", "fac_black_khergits"),
   (val_clamp, ":relation", 0, 101),
   (store_div, ":relation_band", ":relation", 20),
   (store_random_in_range, ":random_bonus", 0, 3),
   (store_add, ":total", 2, ":relation_band"),
   (val_add, ":total", ":random_bonus"),
   (val_clamp, ":total", 2, 9),
   (store_div, ":max_guards", ":total", 3),
   (val_add, ":max_guards", 2),
   (store_random_in_range, ":guards", 0, ":max_guards"),
   (val_min, ":guards", ":total"),
   (store_sub, ":horsemen", ":total", ":guards"),
   (store_sub, ":horseman_cost", 220, ":relation"),
   (val_max, ":horseman_cost", 120),
   (store_sub, ":guard_cost", 320, ":relation"),
   (val_max, ":guard_cost", 200),
   (store_mul, ":cost", ":horsemen", ":horseman_cost"),
   (store_mul, ":guard_total", ":guards", ":guard_cost"),
   (val_add, ":cost", ":guard_total"),
   (assign, "$g_sod_black_khergit_hire_horsemen", ":horsemen"),
   (assign, "$g_sod_black_khergit_hire_guards", ":guards"),
   (assign, "$g_sod_black_khergit_hire_cost", ":cost"),
   (assign, "$g_sod_black_khergit_hire_horseman_cost", ":horseman_cost"),
   (assign, "$g_sod_black_khergit_hire_guard_cost", ":guard_cost"),
   (assign, reg40, ":horsemen"),
   (assign, reg41, ":guards"),
   (assign, reg42, ":cost"),
   (assign, reg43, ":relation"),
 ]),

("sod_black_khergits_buy_hire_offer",
 [
   (store_troop_gold, ":player_gold", "trp_player"),
   (try_begin),
     (ge, ":player_gold", "$g_sod_black_khergit_hire_cost"),
     (gt, "$g_sod_black_khergit_hire_cost", 0),
     (store_add, ":total_hired", "$g_sod_black_khergit_hire_horsemen", "$g_sod_black_khergit_hire_guards"),
     (party_get_free_companions_capacity, ":free_capacity", "p_main_party"),
     (ge, ":free_capacity", ":total_hired"),
     (call_script, "script_sod_player_charge_gold", "$g_sod_black_khergit_hire_cost"),
     (eq, reg1, 1),
     (val_add, "$g_sod_weekly_troops_hired", "$g_sod_black_khergit_hire_cost"),
     (val_clamp, "$g_sod_weekly_troops_hired", 0, 2000001),
     (try_begin),
       (gt, "$g_sod_black_khergit_hire_horsemen", 0),
       (party_add_members, "p_main_party", "trp_black_khergit_horseman", "$g_sod_black_khergit_hire_horsemen"),
     (try_end),
     (try_begin),
       (gt, "$g_sod_black_khergit_hire_guards", 0),
       (party_add_members, "p_main_party", "trp_black_khergit_guard", "$g_sod_black_khergit_hire_guards"),
     (try_end),
     (assign, reg40, "$g_sod_black_khergit_hire_horsemen"),
     (assign, reg41, "$g_sod_black_khergit_hire_guards"),
     (assign, reg42, "$g_sod_black_khergit_hire_cost"),
     (display_message, "@Temujin Black Sky sends {reg40} horsemen and {reg41} guards to ride under your banner for {reg42} denars.", 0x99CCFF),
     (call_script, "script_sod_black_khergits_choose_relocation_target"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, 0),
     (call_script, "script_sod_black_khergits_refresh_active_parties"),
   (else_try),
     (display_message, "@The Black Khergit hire bargain cannot be completed right now.", 0xCC9966),
   (try_end),
   (assign, "$g_sod_black_khergit_hire_horsemen", 0),
   (assign, "$g_sod_black_khergit_hire_guards", 0),
   (assign, "$g_sod_black_khergit_hire_cost", 0),
   (assign, "$g_sod_black_khergit_hire_horseman_cost", 0),
   (assign, "$g_sod_black_khergit_hire_guard_cost", 0),
 ]),

("sod_black_khergits_begin_individual_hire_offer",
 [
   (party_clear, "p_temp_party"),
   (try_begin),
     (gt, "$g_sod_black_khergit_hire_horsemen", 0),
     (party_add_members, "p_temp_party", "trp_black_khergit_horseman", "$g_sod_black_khergit_hire_horsemen"),
   (try_end),
   (try_begin),
     (gt, "$g_sod_black_khergit_hire_guards", 0),
     (party_add_members, "p_temp_party", "trp_black_khergit_guard", "$g_sod_black_khergit_hire_guards"),
   (try_end),
   (store_troop_gold, "$g_sod_black_khergit_pick_gold_before", "trp_player"),
   (assign, "$g_sod_black_khergit_buy_screen_active", 1),
 ]),

("sod_black_khergits_finish_individual_hire_offer",
 [
   (assign, "$g_sod_black_khergit_buy_screen_active", 0),
   (party_count_members_of_type, ":horsemen_left", "p_temp_party", "trp_black_khergit_horseman"),
   (party_count_members_of_type, ":guards_left", "p_temp_party", "trp_black_khergit_guard"),
   (store_sub, ":horsemen_hired", "$g_sod_black_khergit_hire_horsemen", ":horsemen_left"),
   (store_sub, ":guards_hired", "$g_sod_black_khergit_hire_guards", ":guards_left"),
   (val_max, ":horsemen_hired", 0),
   (val_max, ":guards_hired", 0),
   (store_add, ":hired_total", ":horsemen_hired", ":guards_hired"),
   (store_troop_gold, ":gold_after", "trp_player"),
   (store_sub, ":spent", "$g_sod_black_khergit_pick_gold_before", ":gold_after"),
   (val_max, ":spent", 0),
   (try_begin),
     (gt, ":hired_total", 0),
     (val_add, "$g_sod_weekly_troops_hired", ":spent"),
     (val_clamp, "$g_sod_weekly_troops_hired", 0, 2000001),
     (assign, reg40, ":horsemen_hired"),
     (assign, reg41, ":guards_hired"),
     (assign, reg42, ":spent"),
     (display_message, "@Temujin Black Sky sends {reg40} horsemen and {reg41} guards to ride under your banner for {reg42} denars.", 0x99CCFF),
     (call_script, "script_sod_black_khergits_choose_relocation_target"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_migration_day, 0),
     (call_script, "script_sod_black_khergits_refresh_active_parties"),
   (else_try),
     (display_message, "@No Black Khergit riders take your coin today.", 0xCC9966),
   (try_end),
   (party_clear, "p_temp_party"),
   (assign, "$g_sod_black_khergit_hire_horsemen", 0),
   (assign, "$g_sod_black_khergit_hire_guards", 0),
   (assign, "$g_sod_black_khergit_hire_cost", 0),
   (assign, "$g_sod_black_khergit_hire_horseman_cost", 0),
   (assign, "$g_sod_black_khergit_hire_guard_cost", 0),
   (assign, "$g_sod_black_khergit_pick_gold_before", 0),
   (assign, reg0, ":hired_total"),
 ]),

("sod_black_khergits_release_hero_prisoners",
 [
   (store_script_param_1, ":camp_party"),
   (assign, ":released", 0),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (party_get_num_prisoner_stacks, ":num_stacks", ":camp_party"),
     (try_for_range_backwards, ":stack_no", 0, ":num_stacks"),
       (party_prisoner_stack_get_troop_id, ":prisoner_troop", ":camp_party", ":stack_no"),
       (troop_is_hero, ":prisoner_troop"),
       (party_prisoner_stack_get_size, ":stack_size", ":camp_party", ":stack_no"),
       (gt, ":stack_size", 0),
       (troop_set_slot, ":prisoner_troop", slot_troop_prisoner_of_party, ":camp_party"),
       (call_script, "script_remove_troop_from_prison", ":prisoner_troop"),
       (party_count_prisoners_of_type, ":remaining", ":camp_party", ":prisoner_troop"),
       (try_begin),
         (gt, ":remaining", 0),
         (party_remove_prisoners, ":camp_party", ":prisoner_troop", ":remaining"),
       (try_end),
       (val_add, ":released", 1),
      (display_message, "@Temujin Black Sky refuses to keep a captive noble bound in the camp and sends them out under guard.", 0x99CCFF),
     (try_end),
   (try_end),
   (assign, reg0, ":released"),
 ]),

("sod_black_khergits_resolve_broken_camp_prisoners",
 [
   (store_script_param_1, ":camp_party"),
   (store_script_param_2, ":rescue_party"),
   (assign, ":captive_count", 0),
   (assign, ":moved_count", 0),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (call_script, "script_sod_black_khergits_release_hero_prisoners", ":camp_party"),
     (party_get_num_prisoner_stacks, ":num_stacks", ":camp_party"),
     (try_for_range, ":stack_no", 0, ":num_stacks"),
       (party_prisoner_stack_get_troop_id, ":prisoner_troop", ":camp_party", ":stack_no"),
       (neg|troop_is_hero, ":prisoner_troop"),
       (is_between, ":prisoner_troop", soldiers_begin, soldiers_end),
       (party_prisoner_stack_get_size, ":stack_size", ":camp_party", ":stack_no"),
       (gt, ":stack_size", 0),
       (val_add, ":captive_count", ":stack_size"),
     (try_end),
     (try_begin),
       (gt, ":captive_count", 0),
       (assign, ":move_heroes_before", "$g_move_heroes"),
       (assign, "$g_move_heroes", 0),
       (try_begin),
         (gt, ":rescue_party", 0),
         (party_is_active, ":rescue_party"),
         (party_get_free_prisoners_capacity, ":free_capacity", ":rescue_party"),
         (ge, ":free_capacity", ":captive_count"),
         (call_script, "script_party_prisoners_add_party_prisoners", ":rescue_party", ":camp_party"),
         (assign, ":moved_count", ":captive_count"),
       (try_end),
       (call_script, "script_party_remove_all_prisoners", ":camp_party"),
       (assign, "$g_move_heroes", ":move_heroes_before"),
     (try_end),
   (try_end),
   (assign, reg44, ":moved_count"),
   (assign, reg45, ":captive_count"),
 ]),

("sod_black_khergits_prepare_prisoner_purchase_offer",
 [
   (assign, "$g_sod_black_khergit_prisoner_buy_screen_active", 0),
   (assign, "$g_sod_black_khergit_prisoner_relation_discount", 0),
   (assign, "$g_sod_black_khergit_prisoner_buy_count", 0),
   (assign, "$g_sod_black_khergit_prisoner_buy_cost", 0),
   (assign, reg44, 0),
   (assign, reg45, 0),
   (assign, reg46, 0),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (call_script, "script_sod_black_khergits_release_hero_prisoners", ":camp_party"),
     (party_get_free_prisoners_capacity, ":free_prisoner_capacity", "p_main_party"),
     (party_get_free_companions_capacity, ":free_party_capacity", "p_main_party"),
     (assign, ":remaining_offer", ":free_prisoner_capacity"),
     (val_max, ":remaining_offer", ":free_party_capacity"),
     (gt, ":remaining_offer", 0),
     (val_min, ":remaining_offer", 20),
     (store_relation, ":relation", "fac_player_supporters_faction", "fac_black_khergits"),
     (val_clamp, ":relation", 0, 101),
     (store_div, ":relation_discount", ":relation", 3),
     (party_get_num_prisoner_stacks, ":num_stacks", ":camp_party"),
     (try_for_range_backwards, ":stack_no", 0, ":num_stacks"),
       (gt, ":remaining_offer", 0),
       (party_prisoner_stack_get_troop_id, ":prisoner_troop", ":camp_party", ":stack_no"),
       (neg|troop_is_hero, ":prisoner_troop"),
       (is_between, ":prisoner_troop", soldiers_begin, soldiers_end),
       (party_prisoner_stack_get_size, ":stack_size", ":camp_party", ":stack_no"),
       (gt, ":stack_size", 0),
       (assign, ":move_count", ":stack_size"),
       (val_min, ":move_count", ":remaining_offer"),
       (store_character_level, ":troop_level", ":prisoner_troop"),
       (store_mul, ":unit_price", ":troop_level", 7),
       (val_add, ":unit_price", 45),
       (val_sub, ":unit_price", ":relation_discount"),
       (val_max, ":unit_price", 35),
       (store_mul, ":stack_cost", ":unit_price", ":move_count"),
       (try_begin),
         (eq, "$g_sod_black_khergit_prisoner_buy_count", 0),
         (str_store_troop_name_by_count, s28, ":prisoner_troop", ":move_count"),
       (try_end),
       (val_add, "$g_sod_black_khergit_prisoner_buy_count", ":move_count"),
       (val_add, "$g_sod_black_khergit_prisoner_buy_cost", ":stack_cost"),
       (val_sub, ":remaining_offer", ":move_count"),
     (try_end),
   (try_end),
   (assign, reg44, "$g_sod_black_khergit_prisoner_buy_count"),
   (assign, reg45, "$g_sod_black_khergit_prisoner_buy_cost"),
 ]),

("sod_black_khergits_begin_individual_prisoner_recruit_offer",
 [
   (party_clear, "p_temp_party"),
   (call_script, "script_sod_black_khergits_prepare_prisoner_purchase_offer"),
   (store_relation, ":relation", "fac_player_supporters_faction", "fac_black_khergits"),
   (val_clamp, ":relation", 0, 101),
   (store_div, "$g_sod_black_khergit_prisoner_relation_discount", ":relation", 3),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (assign, ":remaining_offer", "$g_sod_black_khergit_prisoner_buy_count"),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (party_get_num_prisoner_stacks, ":num_stacks", ":camp_party"),
     (try_for_range_backwards, ":stack_no", 0, ":num_stacks"),
       (gt, ":remaining_offer", 0),
       (party_prisoner_stack_get_troop_id, ":prisoner_troop", ":camp_party", ":stack_no"),
       (neg|troop_is_hero, ":prisoner_troop"),
       (is_between, ":prisoner_troop", soldiers_begin, soldiers_end),
       (party_prisoner_stack_get_size, ":stack_size", ":camp_party", ":stack_no"),
       (gt, ":stack_size", 0),
       (assign, ":move_count", ":stack_size"),
       (val_min, ":move_count", ":remaining_offer"),
       (party_add_members, "p_temp_party", ":prisoner_troop", ":move_count"),
       (val_sub, ":remaining_offer", ":move_count"),
     (try_end),
   (try_end),
   (store_troop_gold, "$g_sod_black_khergit_prisoner_pick_gold_before", "trp_player"),
   (assign, "$g_sod_black_khergit_prisoner_buy_screen_active", 1),
 ]),

("sod_black_khergits_finish_individual_prisoner_recruit_offer",
 [
   (assign, "$g_sod_black_khergit_prisoner_buy_screen_active", 0),
   (assign, ":moved_total", 0),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (assign, ":remaining_offer", "$g_sod_black_khergit_prisoner_buy_count"),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (party_get_num_prisoner_stacks, ":num_stacks", ":camp_party"),
     (try_for_range_backwards, ":stack_no", 0, ":num_stacks"),
       (gt, ":remaining_offer", 0),
       (party_prisoner_stack_get_troop_id, ":prisoner_troop", ":camp_party", ":stack_no"),
       (neg|troop_is_hero, ":prisoner_troop"),
       (is_between, ":prisoner_troop", soldiers_begin, soldiers_end),
       (party_prisoner_stack_get_size, ":stack_size", ":camp_party", ":stack_no"),
       (gt, ":stack_size", 0),
       (assign, ":offered_count", ":stack_size"),
       (val_min, ":offered_count", ":remaining_offer"),
       (party_count_members_of_type, ":left_in_offer", "p_temp_party", ":prisoner_troop"),
       (assign, ":selected", ":offered_count"),
       (val_sub, ":selected", ":left_in_offer"),
       (val_max, ":selected", 0),
       (val_min, ":selected", ":offered_count"),
       (try_begin),
         (gt, ":selected", 0),
         (party_remove_prisoners, ":camp_party", ":prisoner_troop", ":selected"),
         (assign, ":removed", reg0),
         (gt, ":removed", 0),
         (party_add_members, "p_main_party", ":prisoner_troop", ":removed"),
         (val_add, ":moved_total", ":removed"),
       (try_end),
       (val_sub, ":remaining_offer", ":offered_count"),
     (try_end),
   (try_end),
   (store_troop_gold, ":gold_after", "trp_player"),
   (store_sub, ":spent", "$g_sod_black_khergit_prisoner_pick_gold_before", ":gold_after"),
   (val_max, ":spent", 0),
   (try_begin),
     (gt, ":moved_total", 0),
     (val_add, "$g_sod_weekly_troops_hired", ":spent"),
     (val_clamp, "$g_sod_weekly_troops_hired", 0, 2000001),
     (assign, reg44, ":moved_total"),
     (assign, reg45, ":spent"),
     (display_message, "@You buy {reg44} captives out of the Black Khergit ropes and place them in your ranks for {reg45} denars.", 0x99CCFF),
   (else_try),
     (display_message, "@No captives agree to leave the ropes for your shield-wall today.", 0xCC9966),
   (try_end),
   (party_clear, "p_temp_party"),
   (assign, "$g_sod_black_khergit_prisoner_buy_count", 0),
   (assign, "$g_sod_black_khergit_prisoner_buy_cost", 0),
   (assign, "$g_sod_black_khergit_prisoner_relation_discount", 0),
   (assign, "$g_sod_black_khergit_prisoner_pick_gold_before", 0),
   (assign, reg0, ":moved_total"),
 ]),

("sod_black_khergits_buy_prisoners",
 [
   (assign, reg44, 0),
   (assign, reg45, 0),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (call_script, "script_sod_black_khergits_prepare_prisoner_purchase_offer"),
     (gt, "$g_sod_black_khergit_prisoner_buy_count", 0),
     (store_troop_gold, ":player_gold", "trp_player"),
     (ge, ":player_gold", "$g_sod_black_khergit_prisoner_buy_cost"),
     (party_get_free_prisoners_capacity, ":free_capacity", "p_main_party"),
     (ge, ":free_capacity", "$g_sod_black_khergit_prisoner_buy_count"),
     (call_script, "script_sod_player_charge_gold", "$g_sod_black_khergit_prisoner_buy_cost"),
     (assign, ":remaining", "$g_sod_black_khergit_prisoner_buy_count"),
     (assign, ":moved_total", 0),
     (party_get_num_prisoner_stacks, ":num_stacks", ":camp_party"),
     (try_for_range_backwards, ":stack_no", 0, ":num_stacks"),
       (gt, ":remaining", 0),
       (party_prisoner_stack_get_troop_id, ":prisoner_troop", ":camp_party", ":stack_no"),
       (neg|troop_is_hero, ":prisoner_troop"),
       (is_between, ":prisoner_troop", soldiers_begin, soldiers_end),
       (party_prisoner_stack_get_size, ":stack_size", ":camp_party", ":stack_no"),
       (gt, ":stack_size", 0),
       (assign, ":move_count", ":stack_size"),
       (val_min, ":move_count", ":remaining"),
       (party_remove_prisoners, ":camp_party", ":prisoner_troop", ":move_count"),
       (assign, ":removed", reg0),
       (gt, ":removed", 0),
       (party_add_prisoners, "p_main_party", ":prisoner_troop", ":removed"),
       (val_add, ":moved_total", ":removed"),
       (val_sub, ":remaining", ":removed"),
     (try_end),
     (assign, reg44, ":moved_total"),
     (assign, reg45, "$g_sod_black_khergit_prisoner_buy_cost"),
     (display_message, "@You buy {reg44} prisoners out of the Black Khergit ropes for {reg45} denars.", 0x99CCFF),
   (else_try),
     (display_message, "@The Black Khergit prisoner bargain cannot be completed right now.", 0xCC9966),
   (try_end),
   (assign, "$g_sod_black_khergit_prisoner_buy_count", 0),
   (assign, "$g_sod_black_khergit_prisoner_buy_cost", 0),
 ]),

("sod_black_khergits_choose_relocation_target",
 [
   (assign, ":best_center", 0),
   (assign, ":best_score", -100000),
   (faction_get_slot, ":current_target", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (try_for_range, ":center_no", centers_begin, centers_end),
     (neq, ":center_no", ":current_target"),
     (store_faction_of_party, ":center_faction", ":center_no"),
     (neq, ":center_faction", "fac_player_supporters_faction"),
     (neq, ":center_faction", "fac_player_faction"),
     (try_begin),
       (gt, "$players_kingdom", 0),
       (neq, ":center_faction", "$players_kingdom"),
     (try_end),
     (neg|party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
     (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
     (store_distance_to_party_from_party, ":dist", "p_main_party", ":center_no"),
     (assign, ":score", ":dist"),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (store_div, ":prosperity_score", ":prosperity", 2),
     (val_add, ":score", ":prosperity_score"),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),
   (try_begin),
     (neg|is_between, ":best_center", centers_begin, centers_end),
     (assign, ":best_center", "p_town_18"),
   (try_end),
   (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":best_center"),
   (assign, reg0, ":best_center"),
 ]),

("sod_black_khergits_resolve_khan_duel",
 [
   (store_script_param_1, ":result"),
   (try_begin),
     (eq, ":result", 1),
     (call_script, "script_sod_black_khergits_apply_player_action", sod_black_khergit_action_duel_victory, 1),
   (else_try),
     (call_script, "script_sod_black_khergits_apply_player_action", sod_black_khergit_action_duel_defeat, 1),
   (try_end),
   (assign, "$g_sod_black_khergit_duel_active", 0),
 ]),

("sod_black_khergits_update_scout_intelligence",
 [
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (store_current_day, ":cur_day"),
   (faction_get_slot, ":last_seen_day", "fac_black_khergits", slot_faction_black_khergit_last_seen_day),
   (try_begin),
     (gt, ":camp_party", 0),
     (party_is_active, ":camp_party"),
     (store_distance_to_party_from_party, ":dist", "p_main_party", ":camp_party"),
     (assign, ":spotting_range", 18),
     (party_get_skill_level, ":spotting", "p_main_party", skl_spotting),
     (party_get_skill_level, ":tracking", "p_main_party", skl_tracking),
     (store_add, ":fieldcraft", ":spotting", ":tracking"),
     (val_mul, ":fieldcraft", 4),
    (val_add, ":spotting_range", ":fieldcraft"),
   (try_begin),
      (call_script, "script_cf_sod_companion_in_main_party", "trp_npc1"),
      (troop_slot_ge, "trp_npc1", slot_troop_companion_approval, 45),
      (troop_slot_eq, "trp_npc1", slot_troop_companion_role, sod_companion_role_scout),
      (val_add, ":spotting_range", 12),
    (try_end),
    (try_begin),
      (call_script, "script_cf_sod_companion_in_main_party", "trp_npc7"),
      (troop_slot_ge, "trp_npc7", slot_troop_companion_approval, 45),
      (this_or_next|troop_slot_eq, "trp_npc7", slot_troop_companion_role, sod_companion_role_scout),
      (troop_slot_eq, "trp_npc7", slot_troop_companion_role, sod_companion_role_spymaster),
       (val_add, ":spotting_range", 10),
     (try_end),
     (le, ":dist", ":spotting_range"),
     (call_script, "script_get_closest_center", ":camp_party"),
     (assign, ":seen_center", reg0),
     (is_between, ":seen_center", centers_begin, centers_end),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_seen_center, ":seen_center"),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_seen_day, ":cur_day"),
     (try_begin),
       (lt, ":last_seen_day", ":cur_day"),
       (str_store_party_name, s21, ":seen_center"),
       (try_begin),
         (call_script, "script_cf_sod_companion_in_main_party", "trp_npc7"),
         (troop_slot_ge, "trp_npc7", slot_troop_companion_approval, 45),
         (this_or_next|troop_slot_eq, "trp_npc7", slot_troop_companion_role, sod_companion_role_scout),
         (troop_slot_eq, "trp_npc7", slot_troop_companion_role, sod_companion_role_spymaster),
         (display_message, "@Deshavi finds steppe ash and tether marks from the Black Khergit camp.", 0x99CCFF),
       (else_try),
         (call_script, "script_cf_sod_companion_in_main_party", "trp_npc1"),
         (troop_slot_ge, "trp_npc1", slot_troop_companion_approval, 45),
         (troop_slot_eq, "trp_npc1", slot_troop_companion_role, sod_companion_role_scout),
         (display_message, "@Borcha reads the road dirt and finds signs of the Black Khergit camp.", 0x99CCFF),
       (else_try),
         (display_message, "@Your scouts mark fresh Black Khergit camp signs.", 0x99CCFF),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_process_scattered_raider_aftermath",
 [
   (store_current_day, ":cur_day"),
   (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
   (faction_get_slot, ":disrupted_until", "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until),
   (try_begin),
     (this_or_next|le, ":camp_party", 0),
     (gt, ":disrupted_until", ":cur_day"),
     (try_for_parties, ":party_no"),
       (party_is_active, ":party_no"),
       (party_get_template_id, ":template", ":party_no"),
       (eq, ":template", "pt_black_khergit_raiders"),
       (party_slot_eq, ":party_no", slot_party_black_khergit_origin, 0),
       (party_get_num_companions, ":size", ":party_no"),
       (try_begin),
       (le, ":size", 10),
         (neq, ":party_no", "p_main_party"),
         (remove_party, ":party_no"),
       (else_try),
         (call_script, "script_cf_party_remove_random_regular_troop", ":party_no"),
         (try_begin),
           (gt, ":size", 20),
           (call_script, "script_cf_party_remove_random_regular_troop", ":party_no"),
         (try_end),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_cache_response_candidates",
 [
   (store_script_param_1, ":cur_hours"),
   (store_add, ":response_scan_token", ":cur_hours", 1),
   (assign, ":candidate_count", 0),
   (try_for_parties, ":scan_party"),
     (neq, ":scan_party", "p_main_party"),
     (party_is_active, ":scan_party"),
     (party_get_battle_opponent, ":battle_opponent", ":scan_party"),
     (lt, ":battle_opponent", 0),
     (party_get_slot, ":response_until", ":scan_party", slot_party_black_khergit_response_until),
     (le, ":response_until", ":cur_hours"),
     (store_faction_of_party, ":candidate_faction", ":scan_party"),
     (neq, ":candidate_faction", "fac_black_khergits"),
     (party_get_slot, ":party_type", ":scan_party", slot_party_type),
     (assign, ":eligible_defender", 0),
     (try_begin),
       (eq, ":party_type", spt_kingdom_hero_party),
       (party_get_slot, ":defender_ai_state", ":scan_party", slot_party_ai_state),
       (this_or_next|eq, ":defender_ai_state", spai_holding_center),
       (this_or_next|eq, ":defender_ai_state", spai_patrolling_around_center),
       (this_or_next|eq, ":defender_ai_state", spai_undefined),
       (eq, ":defender_ai_state", spai_recruiting_troops),
       (party_get_slot, ":commander_party", ":scan_party", slot_party_commander_party),
       (this_or_next|eq, ":commander_party", -1),
       (eq, ":commander_party", 0),
       (assign, ":eligible_defender", 1),
     (else_try),
       (eq, ":party_type", spt_patrol),
       (party_slot_eq, ":scan_party", slot_party_sod_support_type, sod_support_type_castle_patrol),
       (party_get_slot, ":patrol_status", ":scan_party", slot_party_sod_patrol_status),
       (this_or_next|le, ":patrol_status", 0),
       (eq, ":patrol_status", sod_castle_patrol_status_active),
       (assign, ":eligible_defender", 1),
     (try_end),
     (eq, ":eligible_defender", 1),
     (store_party_size, ":candidate_size", ":scan_party"),
     (ge, ":candidate_size", 12),
     (store_mul, ":base_score", ":candidate_size", 2),
     (try_begin),
       (eq, ":party_type", spt_kingdom_hero_party),
       (val_add, ":base_score", 10),
     (try_end),
     (party_set_slot, ":scan_party", slot_party_black_khergit_response_candidate_hour, ":response_scan_token"),
     (party_set_slot, ":scan_party", slot_party_black_khergit_response_faction_cache, ":candidate_faction"),
     (party_set_slot, ":scan_party", slot_party_black_khergit_response_base_score_cache, ":base_score"),
     (val_add, ":candidate_count", 1),
   (try_end),
   (assign, reg0, ":candidate_count"),
   (assign, reg1, ":response_scan_token"),
 ]),

("sod_black_khergits_cache_response_threats",
 [
   (store_script_param_1, ":cur_hours"),
   (store_script_param_2, ":fallback_target_center"),
   (store_add, ":response_scan_token", ":cur_hours", 1),
   (assign, ":threat_count", 0),
   (try_for_parties, ":scan_party"),
     (party_is_active, ":scan_party"),
     (party_get_battle_opponent, ":battle_opponent", ":scan_party"),
     (lt, ":battle_opponent", 0),
     (call_script, "script_cf_sod_black_khergits_party_is_horde_force", ":scan_party"),
     (party_get_template_id, ":threat_template", ":scan_party"),
     (neq, ":threat_template", "pt_black_khergit_horde_camp"),
     (party_get_slot, ":threat_target", ":scan_party", slot_party_black_khergit_target),
     (try_begin),
       (neg|is_between, ":threat_target", centers_begin, centers_end),
       (assign, ":threat_target", ":fallback_target_center"),
     (try_end),
     (is_between, ":threat_target", centers_begin, centers_end),
     (store_faction_of_party, ":target_faction", ":threat_target"),
     (neq, ":target_faction", "fac_black_khergits"),
     (party_set_slot, ":scan_party", slot_party_black_khergit_threat_scan_hour, ":response_scan_token"),
     (party_set_slot, ":scan_party", slot_party_black_khergit_threat_target_cache, ":threat_target"),
     (party_set_slot, ":scan_party", slot_party_black_khergit_threat_faction_cache, ":target_faction"),
     (val_add, ":threat_count", 1),
   (try_end),
   (assign, reg0, ":threat_count"),
   (assign, reg1, ":response_scan_token"),
 ]),

("sod_black_khergits_process_ai_responses",
 [
   (store_current_hours, ":cur_hours"),
   (store_mod, ":hour_of_day", ":cur_hours", 24),
   (assign, ":is_day", 1),
   (try_begin),
     (this_or_next|ge, ":hour_of_day", 18),
     (lt, ":hour_of_day", 6),
     (assign, ":is_day", 0),
   (try_end),
   (try_begin),
     (eq, ":is_day", 1),
     (store_relation, ":player_relation", "fac_player_supporters_faction", "fac_black_khergits"),
     (lt, ":player_relation", 100),
     (store_current_day, ":cur_day"),
     (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
     (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),

     (try_for_parties, ":responder_party"),
       (party_is_active, ":responder_party"),
       (party_get_slot, ":response_target", ":responder_party", slot_party_black_khergit_response_target),
       (gt, ":response_target", 0),
       (try_begin),
         (neg|party_is_active, ":response_target"),
         (party_set_slot, ":responder_party", slot_party_black_khergit_response_target, 0),
         (party_set_slot, ":responder_party", slot_party_black_khergit_response_until, 0),
         (try_begin),
           (party_slot_eq, ":responder_party", slot_party_type, spt_patrol),
           (party_slot_eq, ":responder_party", slot_party_sod_support_type, sod_support_type_castle_patrol),
           (party_set_slot, ":responder_party", slot_party_sod_support_target, 0),
         (try_end),
       (try_end),
     (try_end),

     (call_script, "script_sod_world_presence_mark_scan_due_to_reg", "fac_black_khergits", slot_faction_black_khergit_last_response_hour, 3),
     (try_begin),
       (eq, reg0, 1),
       (store_num_parties_of_template, ":active_raiders", "pt_black_khergit_raiders"),
       (store_num_parties_of_template, ":active_guards", "pt_black_khergit_night_guard"),
       (store_add, ":active_threat_parties", ":active_raiders", ":active_guards"),
       (gt, ":active_threat_parties", 0),
       (call_script, "script_sod_black_khergits_cache_response_candidates", ":cur_hours"),
       (assign, ":candidate_count", reg0),
       (assign, ":response_scan_token", reg1),
       (gt, ":candidate_count", 0),
       (call_script, "script_sod_black_khergits_cache_response_threats", ":cur_hours", ":target_center"),
       (assign, ":threat_count", reg0),
       (assign, ":response_scan_token", reg1),
       (gt, ":threat_count", 0),
       (try_for_parties, ":threat_party"),
       (call_script, "script_cf_sod_black_khergits_party_is_horde_force", ":threat_party"),
       (party_slot_eq, ":threat_party", slot_party_black_khergit_threat_scan_hour, ":response_scan_token"),
       (party_get_slot, ":target_faction", ":threat_party", slot_party_black_khergit_threat_faction_cache),
       (assign, ":best_defender", 0),
       (assign, ":best_score", -100000),

       (try_for_parties, ":defender_party"),
         (party_slot_eq, ":defender_party", slot_party_black_khergit_response_candidate_hour, ":response_scan_token"),
         (party_get_slot, ":response_until", ":defender_party", slot_party_black_khergit_response_until),
         (le, ":response_until", ":cur_hours"),
         (party_get_slot, ":defender_faction", ":defender_party", slot_party_black_khergit_response_faction_cache),
         (eq, ":defender_faction", ":target_faction"),
         (store_distance_to_party_from_party, ":defender_dist", ":defender_party", ":threat_party"),
         (le, ":defender_dist", 24),
         (party_get_slot, ":defender_score", ":defender_party", slot_party_black_khergit_response_base_score_cache),
         (val_sub, ":defender_score", ":defender_dist"),
         (gt, ":defender_score", ":best_score"),
         (assign, ":best_score", ":defender_score"),
         (assign, ":best_defender", ":defender_party"),
       (try_end),

       (try_begin),
         (gt, ":best_defender", 0),
         (party_set_slot, ":best_defender", slot_party_black_khergit_response_until, ":cur_hours"),
         (party_set_slot, ":best_defender", slot_party_black_khergit_response_target, ":threat_party"),
         (party_get_slot, ":best_type", ":best_defender", slot_party_type),
         (try_begin),
           (eq, ":best_type", spt_patrol),
           (party_set_slot, ":best_defender", slot_party_sod_support_target, ":threat_party"),
         (try_end),
         (call_script, "script_party_set_ai_state", ":best_defender", spai_engaging_army, ":threat_party"),
         (party_set_ai_behavior, ":best_defender", ai_bhvr_attack_party),
         (party_set_ai_object, ":best_defender", ":threat_party"),
         (store_add, ":response_until_new", ":cur_hours", 18),
         (party_set_slot, ":best_defender", slot_party_black_khergit_response_until, ":response_until_new"),
         (call_script, "script_sod_report_record_event", sod_report_category_security, sod_report_severity_routine, sod_report_subject_party, ":best_defender", sod_report_subject_party, ":threat_party", 1, sod_report_reason_black_khergit_raid),
         (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
         (store_distance_to_party_from_party, ":player_dist", "p_main_party", ":threat_party"),
         (try_begin),
           (le, ":player_dist", 35),
           (lt, ":last_raid_report_day", ":cur_day"),
           (display_message, "@Local riders are moving to challenge Black Khergit raiders.", 0x99CCFF),
           (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
         (try_end),
       (try_end),
       (try_end),
     (try_end),

     (call_script, "script_sod_world_presence_mark_scan_due_to_reg", "fac_black_khergits", slot_faction_black_khergit_last_camp_response_hour, 6),
     (try_begin),
       (eq, reg0, 1),
       (ge, ":pressure", 65),
       (faction_get_slot, ":camp_party", "fac_black_khergits", slot_faction_black_khergit_camp_party),
       (gt, ":camp_party", 0),
       (party_is_active, ":camp_party"),
       (call_script, "script_cf_sod_black_khergits_party_is_horde_camp", ":camp_party"),
       (is_between, ":target_center", centers_begin, centers_end),
       (store_faction_of_party, ":target_faction", ":target_center"),
       (neq, ":target_faction", "fac_black_khergits"),
       (assign, ":best_lord", 0),
       (assign, ":best_score", -100000),
       (try_for_parties, ":lord_party"),
         (party_is_active, ":lord_party"),
         (party_slot_eq, ":lord_party", slot_party_type, spt_kingdom_hero_party),
         (party_get_battle_opponent, ":lord_battle_opponent", ":lord_party"),
         (lt, ":lord_battle_opponent", 0),
         (party_get_slot, ":response_until", ":lord_party", slot_party_black_khergit_response_until),
         (le, ":response_until", ":cur_hours"),
         (store_faction_of_party, ":lord_faction", ":lord_party"),
         (eq, ":lord_faction", ":target_faction"),
         (store_distance_to_party_from_party, ":lord_dist", ":lord_party", ":camp_party"),
         (le, ":lord_dist", 35),
         (store_party_size, ":lord_size", ":lord_party"),
         (ge, ":lord_size", 70),
         (store_mul, ":lord_score", ":lord_size", 2),
         (val_sub, ":lord_score", ":lord_dist"),
         (gt, ":lord_score", ":best_score"),
         (assign, ":best_score", ":lord_score"),
         (assign, ":best_lord", ":lord_party"),
       (try_end),
       (try_begin),
         (gt, ":best_lord", 0),
         (store_add, ":lord_response_until", ":cur_hours", 24),
         (party_set_slot, ":best_lord", slot_party_black_khergit_response_until, ":lord_response_until"),
         (party_set_slot, ":best_lord", slot_party_black_khergit_response_target, ":camp_party"),
         (call_script, "script_party_set_ai_state", ":best_lord", spai_engaging_army, ":camp_party"),
         (party_set_ai_behavior, ":best_lord", ai_bhvr_attack_party),
         (party_set_ai_object, ":best_lord", ":camp_party"),
         (call_script, "script_sod_report_record_event", sod_report_category_security, sod_report_severity_notable, sod_report_subject_party, ":best_lord", sod_report_subject_party, ":camp_party", 1, sod_report_reason_black_khergit_raid),
         (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
         (store_distance_to_party_from_party, ":player_dist", "p_main_party", ":camp_party"),
         (try_begin),
           (le, ":player_dist", 45),
           (lt, ":last_raid_report_day", ":cur_day"),
          (display_message, "@A local warband has turned toward the Black Khergit camp.", 0x99CCFF),
           (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
         (try_end),
       (try_end),
     (try_end),
   (try_end),
 ]),

("sod_black_khergits_note_ai_battle_outcome",
 [
   (store_script_param, ":winner_party", 1),
   (store_script_param, ":defeated_party", 2),
   (assign, ":pressure_delta", 0),
   (assign, ":outcome_kind", 0),
   (store_current_day, ":cur_day"),

   (try_begin),
     (gt, ":winner_party", 0),
     (gt, ":defeated_party", 0),
     (neq, ":winner_party", "p_main_party"),
     (neq, ":defeated_party", "p_main_party"),
     (party_is_active, ":winner_party"),
     (party_is_active, ":defeated_party"),
     (party_get_template_id, ":winner_template", ":winner_party"),
     (party_get_template_id, ":defeated_template", ":defeated_party"),
     (store_faction_of_party, ":winner_faction", ":winner_party"),
     (store_faction_of_party, ":defeated_faction", ":defeated_party"),
     (try_begin),
       (eq, ":defeated_faction", "fac_black_khergits"),
       (eq, ":defeated_template", "pt_black_khergit_raiders"),
       (assign, ":pressure_delta", -5),
       (assign, ":outcome_kind", 1),
     (else_try),
       (eq, ":defeated_faction", "fac_black_khergits"),
       (eq, ":defeated_template", "pt_black_khergit_night_guard"),
       (assign, ":pressure_delta", -4),
       (assign, ":outcome_kind", 2),
     (else_try),
       (eq, ":defeated_faction", "fac_black_khergits"),
       (eq, ":defeated_template", "pt_black_khergit_horde_camp"),
       (assign, ":pressure_delta", -18),
       (assign, ":outcome_kind", 3),
       (store_add, ":disrupted_until", ":cur_day", 7),
       (call_script, "script_sod_black_khergits_resolve_broken_camp_prisoners", ":defeated_party", ":winner_party"),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until, ":disrupted_until"),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_camp_party, 0),
       (call_script, "script_sod_black_khergits_scatter_or_cleanup_patrols"),
     (else_try),
       (this_or_next|eq, ":winner_template", "pt_black_khergit_raiders"),
       (this_or_next|eq, ":winner_template", "pt_black_khergit_night_guard"),
       (eq, ":winner_template", "pt_black_khergit_horde_camp"),
       (eq, ":winner_faction", "fac_black_khergits"),
       (neq, ":defeated_faction", "fac_black_khergits"),
       (assign, ":meaningful_defeat", 0),
       (party_get_slot, ":defeated_type", ":defeated_party", slot_party_type),
       (try_begin),
         (this_or_next|eq, ":defeated_type", spt_kingdom_hero_party),
         (this_or_next|eq, ":defeated_type", spt_patrol),
         (this_or_next|eq, ":defeated_type", spt_kingdom_caravan),
         (eq, ":defeated_template", "pt_merchant_caravan"),
         (assign, ":meaningful_defeat", 1),
       (try_end),
       (eq, ":meaningful_defeat", 1),
       (assign, ":pressure_delta", 3),
       (assign, ":outcome_kind", 4),
     (try_end),
   (try_end),

   (try_begin),
     (neq, ":pressure_delta", 0),
     (faction_get_slot, ":pressure", "fac_black_khergits", slot_faction_black_khergit_pressure),
     (val_add, ":pressure", ":pressure_delta"),
     (val_clamp, ":pressure", 0, 101),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_pressure, ":pressure"),
     (assign, ":report_impact", ":pressure_delta"),
     (try_begin),
       (lt, ":report_impact", 0),
       (val_mul, ":report_impact", -1),
     (try_end),
     (assign, ":report_severity", sod_report_severity_notable),
     (try_begin),
       (this_or_next|eq, ":outcome_kind", 3),
       (eq, ":outcome_kind", 4),
       (assign, ":report_severity", sod_report_severity_urgent),
     (try_end),
     (call_script, "script_sod_report_record_event", sod_report_category_security, ":report_severity", sod_report_subject_party, ":winner_party", sod_report_subject_party, ":defeated_party", ":report_impact", sod_report_reason_black_khergit_raid),
     (try_begin),
       (gt, ":outcome_kind", 0),
       (faction_get_slot, ":last_raid_report_day", "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
       (lt, ":last_raid_report_day", ":cur_day"),
       (store_distance_to_party_from_party, ":player_dist", "p_main_party", ":winner_party"),
       (le, ":player_dist", 45),
       (try_begin),
         (eq, ":outcome_kind", 1),
         (display_message, "@Local defenders have broken a Black Khergit raider band.", 0x99CCFF),
       (else_try),
         (eq, ":outcome_kind", 2),
         (display_message, "@A Black Khergit night guard has been scattered by local defenders.", 0x99CCFF),
       (else_try),
         (eq, ":outcome_kind", 3),
         (display_message, "@A local host has broken the Black Khergit camp; the horde will need time to reform.", 0x99CCFF),
       (else_try),
         (eq, ":outcome_kind", 4),
         (display_message, "@Black Khergit riders have bloodied the local defense and grown bolder.", 0x222222),
       (try_end),
       (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day, ":cur_day"),
     (try_end),
   (try_end),
   (assign, reg0, ":pressure_delta"),
 ]),

("sod_black_khergits_choose_bribed_target",
 [
   (assign, ":best_center", 0),
   (assign, ":best_score", 0),
   (try_for_range, ":center_no", towns_begin, towns_end),
     (neg|party_slot_ge, ":center_no", slot_center_is_besieged_by, 0),
     (call_script, "script_cf_sod_black_khergits_valid_target_center", ":center_no"),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
     (assign, ":score", ":prosperity"),
     (store_div, ":wealth_score", ":wealth", 60),
     (val_add, ":score", ":wealth_score"),
     (try_for_parties, ":caravan_party"),
       (party_is_active, ":caravan_party"),
       (party_get_template_id, ":caravan_template", ":caravan_party"),
       (eq, ":caravan_template", "pt_merchant_caravan"),
       (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":center_no"),
       (le, ":road_dist", 18),
       (val_add, ":score", 4),
     (try_end),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),
   (try_begin),
     (gt, ":best_center", 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":best_center"),
   (try_end),
 ]),

("sod_black_khergits_choose_enemy_target",
 [
   (assign, ":best_center", 0),
   (assign, ":best_score", 0),
   (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
     (store_faction_of_party, ":center_faction", ":center_no"),
     (assign, ":valid_enemy", 0),
     (try_begin),
       (gt, "$players_kingdom", 0),
       (store_relation, ":relation", "$players_kingdom", ":center_faction"),
       (lt, ":relation", 0),
       (assign, ":valid_enemy", 1),
     (else_try),
       (store_relation, ":relation", "fac_player_faction", ":center_faction"),
       (lt, ":relation", 0),
       (assign, ":valid_enemy", 1),
     (try_end),
     (eq, ":valid_enemy", 1),
     (call_script, "script_cf_sod_black_khergits_valid_target_center", ":center_no"),
     (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
     (assign, ":score", ":prosperity"),
     (store_div, ":wealth_score", ":wealth", 80),
     (val_add, ":score", ":wealth_score"),
     (try_for_parties, ":caravan_party"),
       (party_is_active, ":caravan_party"),
       (party_get_template_id, ":caravan_template", ":caravan_party"),
       (eq, ":caravan_template", "pt_merchant_caravan"),
       (store_distance_to_party_from_party, ":road_dist", ":caravan_party", ":center_no"),
       (le, ":road_dist", 18),
       (val_add, ":score", 4),
     (try_end),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_center", ":center_no"),
   (try_end),
   (try_begin),
     (gt, ":best_center", 0),
     (faction_set_slot, "fac_black_khergits", slot_faction_black_khergit_target_center, ":best_center"),
   (try_end),
 ]),

("sod_black_khergits_describe_status_to_s27",
 [
   (call_script, "script_sod_black_khergits_update_horde_state"),
   (store_num_parties_of_template, reg21, "pt_black_khergit_raiders"),
   (store_num_parties_of_template, reg22, "pt_black_khergit_night_guard"),
   (store_num_parties_of_template, reg23, "pt_black_khergit_horde_camp"),
   (faction_get_slot, reg24, "fac_black_khergits", slot_faction_black_khergit_pressure),
   (faction_get_slot, reg25, "fac_black_khergits", slot_faction_black_khergit_tribute),
  (faction_get_slot, reg26, "fac_black_khergits", slot_faction_black_khergit_last_migration_day),
  (store_relation, reg27, "fac_player_supporters_faction", "fac_black_khergits"),
  (str_store_string, s22, "@unproven before the horde"),
  (try_begin),
    (ge, reg27, 100),
    (str_store_string, s22, "@blood-respected"),
  (else_try),
    (ge, reg27, 20),
    (str_store_string, s22, "@trusted"),
  (else_try),
    (ge, reg27, 5),
    (str_store_string, s22, "@friendly"),
  (else_try),
    (le, reg27, -20),
    (str_store_string, s22, "@hostile"),
  (else_try),
    (le, reg27, -5),
    (str_store_string, s22, "@wary"),
  (try_end),
  (faction_get_slot, ":safe_until", "fac_black_khergits", slot_faction_black_khergit_safe_passage_until),
   (faction_get_slot, reg29, "fac_black_khergits", slot_faction_black_khergit_camp_disrupted_until),
   (faction_get_slot, reg30, "fac_black_khergits", slot_faction_black_khergit_last_raid_report_day),
   (faction_get_slot, ":lock_until", "fac_black_khergits", slot_faction_black_khergit_target_lock_until),
   (store_current_day, ":cur_day"),
   (assign, reg31, 0),
   (try_begin),
     (gt, reg29, ":cur_day"),
     (store_sub, reg31, reg29, ":cur_day"),
   (try_end),
   (assign, reg32, 0),
   (str_store_string, s23, "@The horde's mark is not bound by payment or pressure."),
   (try_begin),
     (gt, ":lock_until", ":cur_day"),
     (store_sub, reg32, ":lock_until", ":cur_day"),
     (str_store_string, s23, "@The current mark is locked by recent silver or persuasion for {reg32} more days."),
   (try_end),
   (store_current_hours, ":cur_hours"),
   (assign, reg28, 0),
   (try_begin),
     (gt, ":safe_until", ":cur_hours"),
     (store_sub, reg28, ":safe_until", ":cur_hours"),
   (try_end),
   (faction_get_slot, ":target_center", "fac_black_khergits", slot_faction_black_khergit_target_center),
   (call_script, "script_sod_store_center_name_or_fallback_to_s21", ":target_center", "@no confirmed rich road"),
  (faction_get_slot, ":last_seen_center", "fac_black_khergits", slot_faction_black_khergit_last_seen_center),
  (faction_get_slot, reg33, "fac_black_khergits", slot_faction_black_khergit_last_seen_day),
  (str_store_string, s24, "@no reliable last sighting"),
  (try_begin),
    (is_between, ":last_seen_center", centers_begin, centers_end),
    (str_store_party_name_link, s24, ":last_seen_center"),
  (try_end),
  (str_store_string, s27, "@^Black Khergit horde: {reg23} camp, {reg21} raider bands, {reg22} night guards. Horde pressure {reg24}; tribute {reg25}; current mark {s21}; last seen near {s24} on day {reg33}; last migration day {reg26}; your standing {s22} ({reg27}); safe-passage hours {reg28}; camp disrupted until day {reg29} ({reg31} days remaining); last reported raid day {reg30}. {s23} Raiders range around the mark; night guards cling to the camp. If the camp is broken, guards vanish and loose raiders scatter until the horde reforms."),
  (str_clear, s22),
  (str_clear, s23),
  (str_clear, s24),
 ]),
]

