# COST: medium
SCRIPTS = [
("sod_merc_market_weekly_pulse",
 [
   (store_current_day, ":cur_day"),
   (try_begin),
     (neq, "$g_sod_merc_market_last_pulse_day", ":cur_day"),
     (assign, "$g_sod_merc_market_last_pulse_day", ":cur_day"),

     (call_script, "script_sod_merc_guild_repair_ledgers"),
     (call_script, "script_sod_merc_market_weekly_recover_guilds"),
     (call_script, "script_sod_merc_market_refresh_kingdom_demands"),

     (assign, ":bid_generation_ran", 0),
     (try_for_range, ":kingdom_faction", native_kingdoms_begin, native_kingdoms_end),
       (faction_slot_eq, ":kingdom_faction", slot_faction_state, sfs_active),
       (faction_get_slot, ":demand_score", ":kingdom_faction", slot_faction_sod_merc_demand_score),
       (faction_get_slot, ":need_type", ":kingdom_faction", slot_faction_sod_merc_contract_need_type),
       (faction_get_slot, ":urgency", ":kingdom_faction", slot_faction_sod_merc_contract_urgency),
       (faction_get_slot, ":max_bid", ":kingdom_faction", slot_faction_sod_merc_max_bid),
       (ge, ":demand_score", 45),
       (gt, ":urgency", 0),
       (gt, ":max_bid", 0),
       (neq, ":need_type", sod_merc_contract_role_none),
       (assign, ":bid_generation_ran", 1),

       (assign, ":best_guild", 0),
       (assign, ":best_bid", 0),
       (assign, ":best_score", -1000),
       (assign, ":best_size", 0),
       (assign, ":best_term", 0),
       (try_for_range, ":guild_faction", guilds_begin, guilds_end),
         (call_script, "script_sod_merc_market_generate_bid", ":kingdom_faction", ":guild_faction", ":need_type", 1),
         (assign, ":bid_value", reg0),
         (assign, ":bid_score", reg1),
         (assign, ":company_size", reg2),
         (assign, ":term_days", reg3),
         (gt, ":bid_value", 0),
         (gt, ":bid_score", ":best_score"),
         (assign, ":best_guild", ":guild_faction"),
         (assign, ":best_bid", ":bid_value"),
         (assign, ":best_score", ":bid_score"),
         (assign, ":best_size", ":company_size"),
         (assign, ":best_term", ":term_days"),
       (try_end),

       (gt, ":best_guild", 0),
       (call_script, "script_sod_merc_market_try_accept_bid", ":best_guild", ":kingdom_faction", ":best_bid", ":need_type", ":best_size", ":best_term"),
       (eq, reg0, 1),
       (store_sub, ":demand_score", ":demand_score", 25),
       (val_max, ":demand_score", 0),
       (faction_set_slot, ":kingdom_faction", slot_faction_sod_merc_demand_score, ":demand_score"),
     (try_end),

     (try_begin),
       (gt, ":bid_generation_ran", 0),
       (call_script, "script_sod_merc_guild_repair_ledgers"),
       (call_script, "script_sod_merc_market_refresh_kingdom_demands"),
     (try_end),
   (try_end),
 ]),
]
