# COST: medium
SCRIPTS = [
("sod_threat_board_spawn_target",
 [
   (store_script_param_1, ":archetype"),
   (store_script_param_2, ":sponsor_center"),
   (store_script_param, ":reward_seed", 3),

   (call_script, "script_sod_threat_board_get_archetype", ":archetype"),
    (assign, ":threat_type", reg(0)),
    (assign, ":tier", reg(1)),
    (assign, ":party_template", reg(2)),
    (assign, ":deadline_days", reg(3)),
    (assign, ":guild_sponsor", reg(5)),

   (spawn_around_party, ":sponsor_center", ":party_template"),
    (assign, ":target_party", reg(0)),
   (store_current_day, ":cur_day"),
   (store_add, ":deadline_day", ":cur_day", ":deadline_days"),
   (try_begin),
     (le, ":guild_sponsor", 0),
     (store_faction_of_party, ":guild_sponsor", ":sponsor_center"),
   (try_end),

   (party_set_slot, ":target_party", slot_party_sod_threat_type, ":threat_type"),
   (party_set_slot, ":target_party", slot_party_sod_threat_tier, ":tier"),
   (party_set_slot, ":target_party", slot_party_sod_threat_sponsor_center, ":sponsor_center"),
   (party_set_slot, ":target_party", slot_party_sod_threat_sponsor_faction, ":guild_sponsor"),
   (party_set_slot, ":target_party", slot_party_sod_threat_expiration_day, ":deadline_day"),
   (party_set_slot, ":target_party", slot_party_sod_threat_reward_seed, ":reward_seed"),
   (party_set_slot, ":target_party", slot_party_sod_threat_active_quest, "qst_regional_threat_contract"),
   (party_set_slot, ":target_party", slot_party_sod_threat_archetype, ":archetype"),
   (party_set_ai_behavior, ":target_party", ai_bhvr_patrol_party),
   (party_set_ai_object, ":target_party", ":sponsor_center"),

   (try_begin),
     (eq, ":archetype", sod_threat_archetype_river_pirates),
     (party_set_name, ":target_party", "@Red Ford Reavers"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_coastal_smugglers),
     (party_set_name, ":target_party", "@Salt Road Smugglers"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_army_deserters),
     (party_set_name, ":target_party", "@Ash Road Deserters"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_noble_deserters),
     (party_set_name, ":target_party", "@Broken Banner Deserters"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_relic_thieves),
     (party_set_name, ":target_party", "@Candlemark Relic Thieves"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_tomb_robbers),
     (party_set_name, ":target_party", "@Grave-Dust Robbers"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_rogue_company),
     (party_set_name, ":target_party", "@Black Ledger Company"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_guild_traitors),
     (party_set_name, ":target_party", "@False Colors Company"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_cattle_raiders),
     (party_set_name, ":target_party", "@Low Pasture Raiders"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_herd_rustlers),
     (party_set_name, ":target_party", "@Rival Brand Rustlers"),
   (else_try),
     (eq, ":archetype", sod_threat_archetype_invader_scouts),
     (party_set_name, ":target_party", "@Far-Road Invader Scouts"),
   (else_try),
     (party_set_name, ":target_party", "@Named Marches Captain"),
   (try_end),

    (assign, reg(0), ":target_party"),
    (assign, reg(1), ":deadline_day"),
    (assign, reg(2), ":guild_sponsor"),
 ]),
]
