# COST: O(1)
SCRIPTS = [
("sod_apply_center_investment",
  [
    (store_script_param, ":center_no", 1),
    (store_script_param, ":investor_troop", 2),
    (store_script_param, ":budget", 3),
    (store_script_param, ":mode", 4),

    (assign, ":prosperity_delta", 0),
    (assign, ":health_delta", 0),
    (assign, ":population_delta", 0),
    (assign, ":local_prosperity_delta", 0),
    (assign, ":wealth_delta", 0),
    (assign, ":cattle_delta", 0),

    (val_max, ":budget", 0),
    (try_begin),
      (ge, ":budget", 300),
      (try_begin),
        (eq, ":mode", 1), # emergency recovery: raids, razing, starvation, disease
        (store_div, ":health_delta", ":budget", 500),
        (store_div, ":population_delta", ":budget", 125),
        (store_div, ":prosperity_delta", ":budget", 900),
        (store_div, ":local_prosperity_delta", ":budget", 700),
        (store_div, ":wealth_delta", ":budget", 3),
        (store_div, ":cattle_delta", ":budget", 1000),
      (else_try),
        (eq, ":mode", 2), # trade stimulus: inventories, workshops, credit
        (store_div, ":prosperity_delta", ":budget", 450),
        (store_div, ":local_prosperity_delta", ":budget", 350),
        (store_div, ":wealth_delta", ":budget", 2),
        (store_div, ":health_delta", ":budget", 1800),
        (store_div, ":population_delta", ":budget", 350),
      (else_try), # balanced civic investment
        (store_div, ":prosperity_delta", ":budget", 700),
        (store_div, ":health_delta", ":budget", 900),
        (store_div, ":population_delta", ":budget", 225),
        (store_div, ":local_prosperity_delta", ":budget", 650),
        (store_div, ":wealth_delta", ":budget", 2),
        (store_div, ":cattle_delta", ":budget", 1600),
      (try_end),

      (val_clamp, ":prosperity_delta", 0, 12),
      (val_clamp, ":health_delta", 0, 12),
      (val_clamp, ":population_delta", 0, 80),
      (val_clamp, ":local_prosperity_delta", 0, 12),
      (val_clamp, ":wealth_delta", 0, 6000),
      (val_clamp, ":cattle_delta", 0, 8),

      (try_begin),
        (neg|is_between, ":center_no", castles_begin, castles_end),
        (call_script, "script_change_center_prosperity", ":center_no", ":prosperity_delta"),
      (try_end),
      (call_script, "script_change_center_health", ":center_no", ":health_delta"),

      (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
      (val_add, ":population", ":population_delta"),
      (try_begin),
        (is_between, ":center_no", villages_begin, villages_end),
        (val_clamp, ":population", village_pop_min, village_pop_max),
      (else_try),
        (is_between, ":center_no", towns_begin, towns_end),
        (val_clamp, ":population", town_pop_min, town_pop_max),
      (try_end),
      (party_set_slot, ":center_no", slot_center_sod_local_population, ":population"),

      (party_get_slot, ":local_prosperity", ":center_no", slot_center_sod_local_prosperity),
      (val_add, ":local_prosperity", ":local_prosperity_delta"),
      (val_clamp, ":local_prosperity", 0, 101),
      (party_set_slot, ":center_no", slot_center_sod_local_prosperity, ":local_prosperity"),

      (party_get_slot, ":wealth", ":center_no", slot_town_wealth),
      (val_add, ":wealth", ":wealth_delta"),
      (val_max, ":wealth", 0),
      (party_set_slot, ":center_no", slot_town_wealth, ":wealth"),

      (try_begin),
        (is_between, ":center_no", villages_begin, villages_end),
        (party_get_slot, ":cattle", ":center_no", slot_village_number_of_cattle),
        (val_add, ":cattle", ":cattle_delta"),
        (val_clamp, ":cattle", 0, 101),
        (party_set_slot, ":center_no", slot_village_number_of_cattle, ":cattle"),
      (try_end),

      (try_begin),
        (eq, ":investor_troop", "trp_player"),
        (call_script, "script_change_player_relation_with_center", ":center_no", 1),
        (str_store_party_name_link, s1, ":center_no"),
        (assign, reg1, ":budget"),
        (assign, reg2, ":prosperity_delta"),
        (assign, reg3, ":health_delta"),
        (assign, reg4, ":population_delta"),
        (display_message, "@You invest {reg1} denars into {s1}: prosperity +{reg2}, health +{reg3}, population +{reg4}.", quest_success_color),
      (try_end),
    (try_end),

    (assign, reg0, ":prosperity_delta"),
    (assign, reg1, ":health_delta"),
    (assign, reg2, ":population_delta"),
    (assign, reg3, ":local_prosperity_delta"),
    (assign, reg4, ":wealth_delta"),
    (assign, reg5, ":cattle_delta"),
  ]),
]
