# COST: O(owned centers + bound villages)
SCRIPTS = [
("sod_get_lord_reinforcement_support_profile",
  [
    (store_script_param, ":lord_no", 1),

    (assign, ":faction_no", "fac_commoners"),
    (assign, ":readiness", 0),
    (assign, ":support_score", 0),
    (assign, ":rounds", 1),
    (assign, ":cost_pct", 100),
    (assign, ":wealth_pct", 75),
    (assign, ":centralization", 0),
    (assign, ":militarization", 0),
    (assign, ":is_ruler", 0),
    (assign, ":security_drag", 0),
    (assign, ":food_drag", 0),
    (assign, ":owned_centers", 0),

    (try_begin),
      (is_between, ":lord_no", kingdom_heroes_begin, kingdom_heroes_end),
      (store_troop_faction, ":faction_no", ":lord_no"),
      (try_begin),
        (faction_slot_eq, ":faction_no", slot_faction_leader, ":lord_no"),
        (assign, ":is_ruler", 1),
      (try_end),

      (call_script, "script_sod_get_realm_military_centralization_profile", ":faction_no"),
      (assign, ":centralization", reg0),
      (assign, ":militarization", reg1),
      (assign, ":ruler_host_modifier", reg2),
      (assign, ":vassal_host_modifier", reg3),
      (assign, ":law_unrest", reg5),

      (try_for_range, ":center_no", centers_begin, centers_end),
        (party_slot_eq, ":center_no", slot_town_lord, ":lord_no"),
        (val_add, ":owned_centers", 1),
        (try_begin),
          (party_slot_eq, ":center_no", slot_party_type, spt_castle),
          (call_script, "script_sod_get_castle_support_profile", ":center_no"),
          (assign, ":castle_support", reg0),
          (assign, ":castle_food_security", reg4),
          (assign, ":castle_road_control", reg6),
          (assign, ":castle_military_power", reg8),
          (assign, ":castle_recovery", reg12),
          (assign, ":castle_recruitment", reg14),
          (store_div, ":center_support", ":castle_military_power", 55),
          (store_div, ":castle_support_bonus", ":castle_support", 18),
          (val_add, ":center_support", ":castle_support_bonus"),
          (val_add, ":center_support", ":castle_recovery"),
          (val_add, ":center_support", ":castle_recruitment"),
          (try_begin),
            (lt, ":castle_food_security", 500),
            (val_add, ":food_drag", 10),
          (try_end),
          (try_begin),
            (lt, ":castle_road_control", 0),
            (store_sub, ":road_drag", 0, ":castle_road_control"),
            (val_add, ":security_drag", ":road_drag"),
          (try_end),
          (val_clamp, ":center_support", 4, 55),
          (val_add, ":support_score", ":center_support"),
        (else_try),
          (party_slot_eq, ":center_no", slot_party_type, spt_town),
          (call_script, "script_sod_get_town_market_profile", ":center_no"),
          (assign, ":town_market", reg0),
          (assign, ":town_services", reg4),
          (assign, ":town_liquidity", reg6),
          (assign, ":town_food_security", reg10),
          (assign, ":town_effective_threat", reg12),
          (store_div, ":center_support", ":town_market", 20),
          (store_div, ":town_service_bonus", ":town_services", 20),
          (val_add, ":center_support", ":town_service_bonus"),
          (store_div, ":town_liquidity_bonus", ":town_liquidity", 50),
          (val_add, ":center_support", ":town_liquidity_bonus"),
          (store_mul, ":town_threat_drag", ":town_effective_threat", 2),
          (val_sub, ":center_support", ":town_threat_drag"),
          (try_begin),
            (lt, ":town_food_security", 500),
            (val_add, ":food_drag", 8),
          (try_end),
          (val_clamp, ":center_support", 2, 38),
          (val_add, ":support_score", ":center_support"),
        (else_try),
          (party_slot_eq, ":center_no", slot_party_type, spt_village),
          (call_script, "script_sod_get_village_output_profile", ":center_no"),
          (assign, ":village_recruit_capacity", reg4),
          (assign, ":village_fragility", reg6),
          (assign, ":village_reliability", reg8),
          (store_mul, ":center_support", ":village_recruit_capacity", 2),
          (store_div, ":village_reliability_bonus", ":village_reliability", 16),
          (val_add, ":center_support", ":village_reliability_bonus"),
          (store_div, ":village_fragility_drag", ":village_fragility", 20),
          (val_sub, ":center_support", ":village_fragility_drag"),
          (val_clamp, ":center_support", 0, 20),
          (val_add, ":support_score", ":center_support"),
        (try_end),
      (try_end),

      (assign, ":readiness", 35),
      (val_add, ":readiness", ":support_score"),
      (store_div, ":militarization_bonus", ":militarization", 2),
      (val_add, ":readiness", ":militarization_bonus"),
      (try_begin),
        (eq, ":is_ruler", 1),
        (store_div, ":centralization_bonus", ":ruler_host_modifier", 2),
        (val_add, ":readiness", ":centralization_bonus"),
      (else_try),
        (store_div, ":vassal_bonus", ":vassal_host_modifier", 2),
        (val_add, ":readiness", ":vassal_bonus"),
      (try_end),
      (store_div, ":unrest_drag", ":law_unrest", 2),
      (val_sub, ":readiness", ":unrest_drag"),
      (val_sub, ":readiness", ":security_drag"),
      (val_sub, ":readiness", ":food_drag"),
      (try_begin),
        (eq, ":owned_centers", 0),
        (val_sub, ":readiness", 25),
      (try_end),
      (val_clamp, ":readiness", 0, 201),

      (assign, ":rounds", 1),
      (try_begin),
        (ge, ":readiness", 130),
        (assign, ":rounds", 3),
      (else_try),
        (ge, ":readiness", 85),
        (assign, ":rounds", 2),
      (try_end),

      (assign, ":cost_pct", 120),
      (try_begin),
        (ge, ":readiness", 130),
        (assign, ":cost_pct", 85),
      (else_try),
        (ge, ":readiness", 90),
        (assign, ":cost_pct", 100),
      (try_end),

      (assign, ":wealth_pct", 55),
      (try_begin),
        (ge, ":readiness", 130),
        (assign, ":wealth_pct", 90),
      (else_try),
        (ge, ":readiness", 85),
        (assign, ":wealth_pct", 75),
      (try_end),
    (try_end),

    (assign, reg0, ":readiness"),
    (assign, reg1, ":support_score"),
    (assign, reg2, ":rounds"),
    (assign, reg3, ":cost_pct"),
    (assign, reg4, ":wealth_pct"),
    (assign, reg5, ":centralization"),
    (assign, reg6, ":militarization"),
    (assign, reg7, ":is_ruler"),
    (assign, reg8, ":security_drag"),
    (assign, reg9, ":food_drag"),
    (assign, reg10, ":owned_centers"),
  ]),
]
