# COST: medium
SCRIPTS = [
("sod_artifact_describe_reliquary_report",
 [
   (assign, ":recovered", 0),
   (assign, ":weapons", 0),
   (assign, ":known_leads", 0),
   (assign, ":active", 0),
   (assign, ":best_kills", 0),
   (assign, ":best_item", -1),
   (assign, ":stolen_count", 0),
   (assign, ":stolen_item", -1),
   (assign, ":stolen_owner", -1),
   (assign, ":smith_item", -1),
   (assign, ":smith_kills", 0),
   (assign, ":smith_next", 25),
   (assign, ":equipped_set_pieces", 0),
   (assign, ":equipped_set_family", artifact_family_none),

   (try_for_range, ":slot", 0, 96),
     (troop_get_inventory_slot, ":item_no", "trp_player", ":slot"),
     (gt, ":item_no", 0),
     (item_get_slot, ":flags", ":item_no", slot_item_artifact_flags),
     (gt, ":flags", 0),
     (val_add, ":recovered", 1),
     (store_and, ":is_weapon", ":flags", artifact_flag_weapon),
     (try_begin),
       (gt, ":is_weapon", 0),
       (val_add, ":weapons", 1),
       (troop_get_inventory_slot_modifier, ":imod", "trp_player", ":slot"),
       (call_script, "script_sod_artifact_get_progress", ":item_no", ":imod"),
       (try_begin),
         (gt, reg0, ":best_kills"),
         (assign, ":best_kills", reg0),
         (assign, ":best_item", ":item_no"),
       (try_end),
     (try_end),
   (try_end),

   (try_begin),
     (gt, "$sod_royal_artifact", 0),
     (val_add, ":recovered", 1),
   (try_end),

   (try_for_range, ":item_no", "itm_blacksmith_adenian_armor", "itm_items_end"),
     (item_get_slot, ":flags", ":item_no", slot_item_artifact_flags),
     (gt, ":flags", 0),
     (item_get_slot, ":owner", ":item_no", slot_item_artifact_current_owner),
     (is_between, ":owner", kingdom_heroes_begin, kingdom_heroes_end),
     (neq, ":owner", "trp_player"),
     (val_add, ":stolen_count", 1),
     (try_begin),
       (lt, ":stolen_item", 0),
       (assign, ":stolen_item", ":item_no"),
       (assign, ":stolen_owner", ":owner"),
     (try_end),
   (try_end),

   (try_for_range, ":mission_no", 1, 20),
     (try_begin),
       (eq, ":mission_no", 1),
       (assign, ":state", "$sod_mission_1"),
     (else_try),
       (eq, ":mission_no", 2),
       (assign, ":state", "$sod_mission_2"),
     (else_try),
       (eq, ":mission_no", 3),
       (assign, ":state", "$sod_mission_3"),
     (else_try),
       (eq, ":mission_no", 4),
       (assign, ":state", "$sod_mission_4"),
     (else_try),
       (eq, ":mission_no", 5),
       (assign, ":state", "$sod_mission_5"),
     (else_try),
       (eq, ":mission_no", 6),
       (assign, ":state", "$sod_mission_6"),
     (else_try),
       (eq, ":mission_no", 7),
       (assign, ":state", "$sod_mission_7"),
     (else_try),
       (eq, ":mission_no", 8),
       (assign, ":state", "$sod_mission_8"),
     (else_try),
       (eq, ":mission_no", 9),
       (assign, ":state", "$sod_mission_9"),
     (else_try),
       (eq, ":mission_no", 10),
       (assign, ":state", "$sod_mission_10"),
     (else_try),
       (eq, ":mission_no", 11),
       (assign, ":state", "$sod_mission_11"),
     (else_try),
       (eq, ":mission_no", 12),
       (assign, ":state", "$sod_mission_12"),
     (else_try),
       (eq, ":mission_no", 13),
       (assign, ":state", "$sod_mission_13"),
     (else_try),
       (eq, ":mission_no", 14),
       (assign, ":state", "$sod_mission_14"),
     (else_try),
       (eq, ":mission_no", 15),
       (assign, ":state", "$sod_mission_15"),
     (else_try),
       (eq, ":mission_no", 16),
       (assign, ":state", "$sod_mission_16"),
     (else_try),
       (eq, ":mission_no", 17),
       (assign, ":state", "$sod_mission_17"),
     (else_try),
       (eq, ":mission_no", 18),
       (assign, ":state", "$sod_mission_18"),
     (else_try),
       (assign, ":state", "$sod_mission_19"),
     (try_end),
     (try_begin),
       (eq, ":state", 2),
       (val_add, ":known_leads", 1),
     (else_try),
       (eq, ":state", 1),
       (val_add, ":active", 1),
     (try_end),
   (try_end),

   (assign, reg1, ":recovered"),
   (assign, reg2, ":weapons"),
   (assign, reg3, ":known_leads"),
   (assign, reg4, ":active"),
   (assign, reg5, ":best_kills"),
   (assign, reg6, ":stolen_count"),

   (call_script, "script_sod_artifact_find_maintainable_weapon", "trp_player"),
   (try_begin),
     (eq, reg0, 1),
     (assign, ":smith_item", reg2),
     (assign, ":smith_kills", reg4),
     (assign, ":smith_next", reg5),
   (try_end),
   (assign, reg5, ":best_kills"),

   (call_script, "script_sod_artifact_check_equipped_set", "trp_player"),
   (assign, ":equipped_set_pieces", reg0),
   (assign, ":equipped_set_family", reg1),

   (try_begin),
     (gt, ":best_item", 0),
     (str_store_item_name, s2, ":best_item"),
   (else_try),
     (str_store_string, s2, "@No blooded artifact weapon yet"),
   (try_end),

   (try_begin),
     (gt, "$sod_royal_artifact", 0),
     (str_store_item_name, s3, "$sod_royal_artifact"),
     (str_store_string, s4, "@Vault: {s3} awaits release by the treasurer."),
   (else_try),
     (str_store_string, s4, "@Vault: no recovered artifact is waiting."),
   (try_end),

   (try_begin),
     (gt, ":stolen_item", 0),
     (str_store_item_name, s6, ":stolen_item"),
     (str_store_troop_name, s7, ":stolen_owner"),
     (str_store_string, s8, "@Stolen artifacts: {reg6}. Known trail: {s6} is held by {s7}."),
   (else_try),
     (str_store_string, s8, "@Stolen artifacts: none known."),
   (try_end),

   (try_begin),
     (gt, ":smith_item", 0),
     (str_store_item_name, s9, ":smith_item"),
     (assign, reg7, ":smith_kills"),
     (assign, reg8, ":smith_next"),
     (str_store_string, s10, "@Smiths can maintain: {s9} ({reg7}/{reg8} kills toward next provenance mark)."),
   (else_try),
     (str_store_string, s10, "@Smiths can maintain: no equipped artifact weapon currently needs work."),
   (try_end),

   (try_begin),
     (eq, ":equipped_set_family", artifact_family_antarian),
     (str_store_string, s11, "@Antarian"),
   (else_try),
     (eq, ":equipped_set_family", artifact_family_marinian),
     (str_store_string, s11, "@Marinian"),
   (else_try),
     (eq, ":equipped_set_family", artifact_family_adenian),
     (str_store_string, s11, "@Adenian"),
   (else_try),
     (eq, ":equipped_set_family", artifact_family_villianese),
     (str_store_string, s11, "@Villianese"),
   (else_try),
     (eq, ":equipped_set_family", artifact_family_zerrikanian),
     (str_store_string, s11, "@Zerrikanian"),
   (else_try),
     (str_store_string, s11, "@mixed or no"),
   (try_end),
   (assign, reg9, ":equipped_set_pieces"),
   (try_begin),
     (ge, ":equipped_set_pieces", 5),
     (str_store_string, s12, "@Equipped set: {reg9} matching {s11} pieces. The court sees a restored royal image, not just recovered gear."),
   (else_try),
     (ge, ":equipped_set_pieces", 3),
     (str_store_string, s12, "@Equipped set: {reg9} matching {s11} pieces. The royal image is visible, but not complete."),
   (else_try),
     (ge, ":equipped_set_pieces", 1),
     (str_store_string, s12, "@Equipped set: {reg9} matching {s11} pieces. More matching pieces would make the regalia speak louder."),
   (else_try),
     (str_store_string, s12, "@Equipped set: no matching royal set is currently worn."),
   (try_end),

   (try_begin),
     (ge, ":recovered", 5),
     (str_store_string, s5, "@The court has begun to speak of restoration, not survival."),
   (else_try),
     (ge, ":known_leads", 1),
     (str_store_string, s5, "@The reliquary scribes have real leads; another expedition may recover a royal piece."),
   (else_try),
     (str_store_string, s5, "@The reliquary is quiet. Send expeditions to turn rumor into proof."),
   (try_end),

   (str_store_string, s1, "@Royal Reliquary^^Recovered or vaulted artifacts: {reg1}^Blooded artifact weapons: {reg2}^Known artifact leads: {reg3}^Active expeditions: {reg4}^{s8}^^Most proven weapon: {s2} ({reg5} recorded kills)^{s4}^{s10}^{s12}^^{s5}"),
 ]),
]
