# COST: medium
SCRIPTS = [
("sod_store_hostile_local_context",
 [
   (store_script_param, ":party_no", 1),
   (assign, ":center_no", 0),
   (try_begin),
     (gt, ":party_no", 0),
     (party_slot_eq, ":party_no", slot_party_sod_threat_active_quest, "qst_regional_threat_contract"),
     (party_get_slot, ":center_no", ":party_no", slot_party_sod_threat_sponsor_center),
   (else_try),
     (gt, "$g_sod_hostile_reputation_last_center", 0),
     (assign, ":center_no", "$g_sod_hostile_reputation_last_center"),
   (try_end),
   (try_begin),
     (gt, ":center_no", 0),
     (str_store_party_name, s11, ":center_no"),
   (else_try),
     (str_store_string, s11, "@these roads"),
   (try_end),
   (str_store_string, s12, "@The land here is neither rich enough to ignore nor poor enough to empty by itself."),
   (try_begin),
     (gt, ":center_no", 0),
     (party_get_slot, ":prosperity", ":center_no", slot_center_sod_local_prosperity),
     (try_begin),
       (le, ":prosperity", 0),
       (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
     (try_end),
     (try_begin),
       (ge, ":prosperity", 65),
       (str_store_string, s12, "@{s11} still has fat storehouses. Fat storehouses attract knives."),
     (else_try),
       (le, ":prosperity", 25),
       (str_store_string, s12, "@{s11} is poor enough that hunger has become a recruiting sergeant."),
     (try_end),
   (try_end),
   (str_store_string, s13, "@No fresh village smoke guides this conversation."),
   (try_begin),
     (gt, ":center_no", 0),
     (party_get_slot, ":village_state", ":center_no", slot_village_state),
     (try_begin),
       (eq, ":village_state", svs_being_raided),
       (str_store_string, s13, "@A raid is already chewing at {s11}. We are not the only teeth on this road."),
     (else_try),
       (eq, ":village_state", svs_looted),
       (str_store_string, s13, "@{s11} has been picked over recently. Ruin makes men cheap and angry."),
     (else_try),
       (eq, ":village_state", svs_recovering),
       (str_store_string, s13, "@{s11} is still recovering. That makes guards nervous and peasants desperate."),
     (try_end),
   (try_end),
   (store_num_parties_of_template, ":slaver_caravans", "pt_slavers_caravan"),
   (try_begin),
     (gt, ":slaver_caravans", 0),
     (assign, reg11, ":slaver_caravans"),
     (str_store_string, s14, "@Slaver wagons are moving too. {reg11} caravans means coin, chains, and frightened witnesses."),
   (else_try),
     (str_store_string, s14, "@No slaver train is close enough to scare our price upward today."),
   (try_end),
   (store_num_parties_of_template, ":player_patrols", "pt_player_patrol"),
   (store_num_parties_of_template, ":player_patrols_2", "pt_player_patrol_2"),
   (val_add, ":player_patrols", ":player_patrols_2"),
   (assign, reg12, ":player_patrols"),
   (try_begin),
     (gt, ":player_patrols", 0),
     (str_store_string, s15, "@Your patrols are a rumor with boots. {reg12} parties make cowards cautious and bold men famous."),
   (else_try),
     (str_store_string, s15, "@Patrols are thin. Roads remember absence faster than orders."),
   (try_end),
   (str_store_string, s16, "@No siege drums are close enough to drown this argument."),
   (try_begin),
     (gt, ":center_no", 0),
     (party_get_slot, ":besieger_party", ":center_no", slot_center_is_besieged_by),
     (ge, ":besieger_party", 0),
     (party_is_active, ":besieger_party"),
     (str_store_string, s16, "@A siege near {s11} pulls soldiers one way and hunger the other. Roads split open under that pressure."),
   (try_end),
   (try_begin),
     (gt, ":party_no", 0),
     (store_faction_of_party, ":party_faction", ":party_no"),
     (str_store_faction_name, s17, ":party_faction"),
     (try_begin),
       (gt, "$players_kingdom", 0),
       (store_relation, ":relation", "$players_kingdom", ":party_faction"),
       (lt, ":relation", 0),
       (str_store_string, s18, "@Your realm and {s17} are already enemies. Do not pretend this meeting is only about coin."),
     (else_try),
       (str_store_string, s18, "@We wore or robbed under {s17} long enough to learn what banners are worth."),
     (try_end),
   (else_try),
     (str_store_string, s18, "@No banner explains this meeting better than hunger and opportunity."),
   (try_end),
 ]),
]
