# COST: low
SCRIPTS = [
("sod_merc_player_company_try_replenish",
 [
   (store_script_param_1, ":party_no"),

   (assign, ":added", 0),
   (try_begin),
     (party_is_active, ":party_no"),
     (party_slot_eq, ":party_no", slot_party_type, spt_player_mercenaries),
     (party_get_slot, ":guild_faction", ":party_no", slot_party_sod_merc_contract_guild),
     (try_begin),
       (neg|is_between, ":guild_faction", guilds_begin, guilds_end),
       (party_get_slot, ":guild_faction", ":party_no", slot_party_orginal_faction),
     (try_end),
     (call_script, "script_cf_sod_faction_is_merc_guild", ":guild_faction"),
     (faction_get_slot, ":guild_manpower", ":guild_faction", slot_faction_sod_merc_manpower),
     (gt, ":guild_manpower", 0),
     (call_script, "script_sod_merc_market_calculate_guild_supply", ":guild_faction"),
     (assign, ":available_companies", reg0),
     (assign, ":refusal_reason", reg6),
     (gt, ":available_companies", 0),
     (eq, ":refusal_reason", sod_merc_refusal_none),
     (faction_get_slot, ":player_debt", ":guild_faction", player_debt_to_faction),
     (le, ":player_debt", 0),
     (lt, "$g_sod_merc_weekly_paiment_not_paid_in_a_row", 2),

     (party_get_num_companions, ":size", ":party_no"),
     (faction_get_slot, ":proportion", ":guild_faction", slot_guild_troop_proportion),
     (store_sub, ":target_size", 34, ":proportion"),
     (val_max, ":target_size", 18),
     (val_add, ":target_size", 8),
     (lt, ":size", ":target_size"),

     (assign, reg0, slot_guild_tier_1_unit_1),
     (assign, reg1, slot_guild_tier_1_unit_2),
     (shuffle_range, 0, 2),
     (faction_get_slot, ":troop_to_add", ":guild_faction", reg0),
     (gt, ":troop_to_add", 0),
     (neq, ":troop_to_add", "trp_player"),

     (store_sub, ":shortfall", ":target_size", ":size"),
     (val_div, ":shortfall", 5),
     (val_add, ":shortfall", 1),
     (val_min, ":shortfall", 4),
     (store_relation, ":player_relation", "fac_player_faction", ":guild_faction"),
     (try_begin),
       (ge, ":player_relation", 60),
       (val_add, ":shortfall", 1),
     (else_try),
       (lt, ":player_relation", 10),
       (val_min, ":shortfall", 2),
     (try_end),
     (val_min, ":shortfall", ":guild_manpower"),
     (gt, ":shortfall", 0),
     (party_add_members, ":party_no", ":troop_to_add", ":shortfall"),
     (val_sub, ":guild_manpower", ":shortfall"),
     (val_max, ":guild_manpower", 0),
     (faction_set_slot, ":guild_faction", slot_faction_sod_merc_manpower, ":guild_manpower"),
     (assign, ":added", ":shortfall"),
   (try_end),

   (assign, reg0, ":added"),
 ]),
]
