# COST: O(1)
SCRIPTS = [
("sod_get_realm_tax_pressure_profile",
  [
    (store_script_param, ":faction_no", 1),

    (assign, ":peasant_extraction", 0),
    (assign, ":merchant_tariff_pressure", 0),
    (assign, ":noble_obligation_pressure", 0),
    (assign, ":clergy_faith_support_pressure", 0),
    (assign, ":war_tax_pressure", 0),
    (assign, ":total_social_pressure", 0),
    (assign, ":revenue_modifier", 100),
    (assign, ":recovery_modifier", 100),
    (assign, ":migration_modifier", 100),
    (assign, ":trade_volume_modifier", 100),
    (assign, ":unrest_pressure", 0),
    (assign, ":commoner_happiness_delta", 0),
    (assign, ":merchant_happiness_delta", 0),
    (assign, ":noble_happiness_delta", 0),
    (assign, ":clergy_happiness_delta", 0),
    (assign, ":tariff_capture_pct", 100),

    (try_begin),
      (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
      (call_script, "script_sod_law_recalculate_faction_law_modifiers", ":faction_no"),

      (faction_get_slot, ":peasant_tax", ":faction_no", slot_faction_law_tax_peasants),
      (faction_get_slot, ":town_tax", ":faction_no", slot_faction_law_tax_townspeople),
      (faction_get_slot, ":noble_tax", ":faction_no", slot_faction_law_tax_nobles),
      (faction_get_slot, ":commoner_happiness_delta", ":faction_no", slot_faction_law_commoner_happiness),
      (faction_get_slot, ":merchant_happiness_delta", ":faction_no", slot_faction_law_merchant_happiness),
      (faction_get_slot, ":noble_happiness_delta", ":faction_no", slot_faction_law_noble_happiness),
      (faction_get_slot, ":clergy_happiness_delta", ":faction_no", slot_faction_law_clergy_happiness),
      (faction_get_slot, ":law_unrest", ":faction_no", slot_faction_law_unrest),
      (faction_get_slot, ":legitimacy", ":faction_no", slot_faction_law_legitimacy),
      (faction_get_slot, ":holy_modifier", ":faction_no", slot_faction_law_holy_modifier),

      (store_sub, ":peasant_extraction", ":peasant_tax", 0),
      (store_sub, ":merchant_tariff_pressure", ":town_tax", 0),
      (store_sub, ":noble_obligation_pressure", ":noble_tax", 100),
      (store_sub, ":clergy_faith_support_pressure", ":holy_modifier", 100),
      (val_clamp, ":peasant_extraction", -60, 101),
      (val_clamp, ":merchant_tariff_pressure", -60, 101),
      (val_clamp, ":noble_obligation_pressure", -60, 101),
      (val_clamp, ":clergy_faith_support_pressure", -60, 81),

      (call_script, "script_sod_law_calculate_trade_tax_policy", ":faction_no"),
      (assign, ":trade_tax_modifier", reg0),
      (assign, ":trade_volume_modifier", reg1),
      (assign, ":trade_merchant_happiness", reg2),
      (assign, ":tariff_capture_pct", reg3),
      (store_sub, ":trade_tax_pressure", ":trade_tax_modifier", 100),
      (val_add, ":merchant_tariff_pressure", ":trade_tax_pressure"),
      (val_add, ":merchant_happiness_delta", ":trade_merchant_happiness"),

      (try_begin),
        (faction_slot_eq, ":faction_no", slot_faction_diplomacy_decree_war_taxes, 1),
        (assign, ":war_tax_pressure", 28),
        (val_sub, ":commoner_happiness_delta", 8),
        (val_sub, ":merchant_happiness_delta", 8),
        (val_sub, ":noble_happiness_delta", 5),
        (val_sub, ":clergy_happiness_delta", 3),
      (try_end),

      (assign, ":total_social_pressure", 0),
      (try_begin),
        (gt, ":peasant_extraction", 0),
        (store_div, ":pressure_part", ":peasant_extraction", 2),
        (val_add, ":total_social_pressure", ":pressure_part"),
      (else_try),
        (lt, ":peasant_extraction", 0),
        (store_sub, ":relief_part", 0, ":peasant_extraction"),
        (store_div, ":relief_part", ":relief_part", 4),
        (val_sub, ":total_social_pressure", ":relief_part"),
      (try_end),
      (try_begin),
        (gt, ":merchant_tariff_pressure", 0),
        (store_div, ":pressure_part", ":merchant_tariff_pressure", 3),
        (val_add, ":total_social_pressure", ":pressure_part"),
      (else_try),
        (lt, ":merchant_tariff_pressure", 0),
        (store_sub, ":relief_part", 0, ":merchant_tariff_pressure"),
        (store_div, ":relief_part", ":relief_part", 5),
        (val_sub, ":total_social_pressure", ":relief_part"),
      (try_end),
      (try_begin),
        (gt, ":noble_obligation_pressure", 0),
        (store_div, ":pressure_part", ":noble_obligation_pressure", 2),
        (val_add, ":total_social_pressure", ":pressure_part"),
      (else_try),
        (lt, ":noble_obligation_pressure", 0),
        (store_sub, ":relief_part", 0, ":noble_obligation_pressure"),
        (store_div, ":relief_part", ":relief_part", 5),
        (val_sub, ":total_social_pressure", ":relief_part"),
      (try_end),
      (try_begin),
        (gt, ":clergy_faith_support_pressure", 0),
        (store_div, ":pressure_part", ":clergy_faith_support_pressure", 4),
        (val_add, ":total_social_pressure", ":pressure_part"),
      (else_try),
        (lt, ":clergy_faith_support_pressure", 0),
        (store_sub, ":relief_part", 0, ":clergy_faith_support_pressure"),
        (store_div, ":relief_part", ":relief_part", 5),
        (val_sub, ":total_social_pressure", ":relief_part"),
      (try_end),
      (val_add, ":total_social_pressure", ":war_tax_pressure"),

      (try_begin),
        (lt, ":commoner_happiness_delta", 0),
        (store_sub, ":happiness_pressure", 0, ":commoner_happiness_delta"),
        (val_div, ":happiness_pressure", 4),
        (val_add, ":total_social_pressure", ":happiness_pressure"),
      (try_end),
      (try_begin),
        (lt, ":merchant_happiness_delta", 0),
        (store_sub, ":happiness_pressure", 0, ":merchant_happiness_delta"),
        (val_div, ":happiness_pressure", 4),
        (val_add, ":total_social_pressure", ":happiness_pressure"),
      (try_end),
      (try_begin),
        (lt, ":noble_happiness_delta", 0),
        (store_sub, ":happiness_pressure", 0, ":noble_happiness_delta"),
        (val_div, ":happiness_pressure", 5),
        (val_add, ":total_social_pressure", ":happiness_pressure"),
      (try_end),

      (assign, ":revenue_modifier", 100),
      (try_begin),
        (gt, ":peasant_extraction", 0),
        (val_add, ":revenue_modifier", ":peasant_extraction"),
      (else_try),
        (lt, ":peasant_extraction", 0),
        (val_add, ":revenue_modifier", ":peasant_extraction"),
      (try_end),
      (try_begin),
        (gt, ":merchant_tariff_pressure", 0),
        (store_div, ":revenue_part", ":merchant_tariff_pressure", 2),
        (val_add, ":revenue_modifier", ":revenue_part"),
      (else_try),
        (lt, ":merchant_tariff_pressure", 0),
        (store_div, ":revenue_part", ":merchant_tariff_pressure", 2),
        (val_add, ":revenue_modifier", ":revenue_part"),
      (try_end),
      (store_div, ":noble_revenue_part", ":noble_obligation_pressure", 2),
      (val_add, ":revenue_modifier", ":noble_revenue_part"),
      (val_add, ":revenue_modifier", ":war_tax_pressure"),

      (assign, ":recovery_modifier", 100),
      (assign, ":migration_modifier", 100),
      (try_begin),
        (gt, ":total_social_pressure", 0),
        (store_div, ":recovery_drag", ":total_social_pressure", 2),
        (val_sub, ":recovery_modifier", ":recovery_drag"),
        (val_sub, ":migration_modifier", ":total_social_pressure"),
      (else_try),
        (lt, ":total_social_pressure", 0),
        (store_sub, ":pressure_relief", 0, ":total_social_pressure"),
        (store_div, ":recovery_bonus", ":pressure_relief", 2),
        (val_add, ":recovery_modifier", ":recovery_bonus"),
        (store_div, ":migration_bonus", ":pressure_relief", 2),
        (val_add, ":migration_modifier", ":migration_bonus"),
      (try_end),

      (try_begin),
        (gt, ":law_unrest", 0),
        (val_add, ":unrest_pressure", ":law_unrest"),
      (try_end),
      (try_begin),
        (lt, ":legitimacy", 0),
        (store_sub, ":legitimacy_unrest", 0, ":legitimacy"),
        (val_div, ":legitimacy_unrest", 2),
        (val_add, ":unrest_pressure", ":legitimacy_unrest"),
      (else_try),
        (gt, ":legitimacy", 0),
        (store_div, ":legitimacy_relief", ":legitimacy", 3),
        (val_sub, ":unrest_pressure", ":legitimacy_relief"),
      (try_end),
      (try_begin),
        (gt, ":war_tax_pressure", 0),
        (val_add, ":unrest_pressure", 8),
      (try_end),
      (try_begin),
        (gt, ":clergy_happiness_delta", 0),
        (store_div, ":clergy_unrest_relief", ":clergy_happiness_delta", 5),
        (val_sub, ":unrest_pressure", ":clergy_unrest_relief"),
      (else_try),
        (lt, ":clergy_happiness_delta", 0),
        (store_sub, ":clergy_unrest", 0, ":clergy_happiness_delta"),
        (val_div, ":clergy_unrest", 5),
        (val_add, ":unrest_pressure", ":clergy_unrest"),
      (try_end),
    (try_end),

    (val_clamp, ":peasant_extraction", -60, 101),
    (val_clamp, ":merchant_tariff_pressure", -60, 101),
    (val_clamp, ":noble_obligation_pressure", -60, 101),
    (val_clamp, ":clergy_faith_support_pressure", -60, 81),
    (val_clamp, ":war_tax_pressure", 0, 51),
    (val_clamp, ":total_social_pressure", 0, 121),
    (val_clamp, ":revenue_modifier", 60, 201),
    (val_clamp, ":recovery_modifier", 45, 126),
    (val_clamp, ":migration_modifier", 45, 126),
    (val_clamp, ":trade_volume_modifier", 65, 136),
    (val_clamp, ":unrest_pressure", 0, 101),
    (val_clamp, ":commoner_happiness_delta", -100, 101),
    (val_clamp, ":merchant_happiness_delta", -100, 101),
    (val_clamp, ":noble_happiness_delta", -100, 101),
    (val_clamp, ":clergy_happiness_delta", -100, 101),
    (val_clamp, ":tariff_capture_pct", 65, 181),

    (assign, reg0, ":peasant_extraction"),
    (assign, reg1, ":merchant_tariff_pressure"),
    (assign, reg2, ":noble_obligation_pressure"),
    (assign, reg3, ":clergy_faith_support_pressure"),
    (assign, reg4, ":war_tax_pressure"),
    (assign, reg5, ":total_social_pressure"),
    (assign, reg6, ":revenue_modifier"),
    (assign, reg7, ":recovery_modifier"),
    (assign, reg8, ":migration_modifier"),
    (assign, reg9, ":trade_volume_modifier"),
    (assign, reg10, ":unrest_pressure"),
    (assign, reg11, ":commoner_happiness_delta"),
    (assign, reg12, ":merchant_happiness_delta"),
    (assign, reg13, ":noble_happiness_delta"),
    (assign, reg14, ":clergy_happiness_delta"),
    (assign, reg15, ":tariff_capture_pct"),
  ]),

("sod_get_center_tax_extraction_profile",
  [
    (store_script_param, ":center_no", 1),

    (assign, ":tax_revenue_pct", 100),
    (assign, ":tax_pressure", 0),
    (assign, ":merchant_happiness_delta", 0),
    (assign, ":migration_retention_pct", 100),
    (assign, ":liquidity_pct", 100),
    (assign, ":recovery_pct", 100),
    (assign, ":wealth_drift", 0),
    (assign, ":tax_law_delta", 0),
    (assign, ":tariff_capture_pct", 100),

    (try_begin),
      (is_between, ":center_no", centers_begin, centers_end),
      (store_faction_of_party, ":center_faction", ":center_no"),
      (call_script, "script_sod_get_realm_tax_pressure_profile", ":center_faction"),
      (assign, ":peasant_extraction", reg0),
      (assign, ":merchant_tariff_pressure", reg1),
      (assign, ":noble_obligation_pressure", reg2),
      (assign, ":clergy_faith_support_pressure", reg3),
      (assign, ":war_tax_pressure", reg4),
      (assign, ":realm_revenue_modifier", reg6),
      (assign, ":realm_recovery_modifier", reg7),
      (assign, ":realm_migration_modifier", reg8),
      (assign, ":realm_trade_volume_modifier", reg9),
      (assign, ":realm_unrest_pressure", reg10),
      (assign, ":commoner_happiness_delta", reg11),
      (assign, ":merchant_happiness_delta", reg12),
      (assign, ":noble_happiness_delta", reg13),
      (assign, ":clergy_happiness_delta", reg14),
      (assign, ":tariff_capture_pct", reg15),

      (assign, ":law_tax", 0),
      (assign, ":law_tax_reference", 0),
      (try_begin),
        (is_between, ":center_no", villages_begin, villages_end),
        (faction_get_slot, ":law_tax", ":center_faction", slot_faction_law_tax_peasants),
        (assign, ":tax_pressure", ":peasant_extraction"),
        (val_add, ":tax_pressure", ":war_tax_pressure"),
        (val_add, ":merchant_happiness_delta", ":commoner_happiness_delta"),
      (else_try),
        (is_between, ":center_no", towns_begin, towns_end),
        (faction_get_slot, ":law_tax", ":center_faction", slot_faction_law_tax_townspeople),
        (assign, ":tax_pressure", ":merchant_tariff_pressure"),
        (val_add, ":tax_pressure", ":war_tax_pressure"),
      (else_try),
        (is_between, ":center_no", castles_begin, castles_end),
        (faction_get_slot, ":law_tax", ":center_faction", slot_faction_law_tax_nobles),
        (assign, ":law_tax_reference", 100),
        (assign, ":tax_pressure", ":noble_obligation_pressure"),
        (val_add, ":tax_pressure", ":war_tax_pressure"),
        (val_add, ":merchant_happiness_delta", ":noble_happiness_delta"),
      (try_end),
      (store_sub, ":tax_law_delta", ":law_tax", ":law_tax_reference"),
      (val_clamp, ":tax_law_delta", -60, 81),

      (assign, ":tax_revenue_pct", ":realm_revenue_modifier"),

      (try_begin),
        (this_or_next|is_between, ":center_no", towns_begin, towns_end),
        (is_between, ":center_no", castles_begin, castles_end),
        (call_script, "script_sod_law_calculate_trade_tax_policy", ":center_faction"),
        (assign, ":trade_volume_pct", reg1),
        (assign, ":tariff_capture_pct", reg3),
        (assign, ":realm_trade_volume_modifier", ":trade_volume_pct"),
        (val_mul, ":liquidity_pct", ":trade_volume_pct"),
        (val_div, ":liquidity_pct", 100),
      (try_end),

      (try_begin),
        (gt, ":clergy_faith_support_pressure", 0),
        (store_div, ":clergy_recovery_bonus", ":clergy_happiness_delta", 5),
        (val_add, ":recovery_pct", ":clergy_recovery_bonus"),
      (else_try),
        (lt, ":clergy_happiness_delta", 0),
        (store_sub, ":clergy_recovery_drag", 0, ":clergy_happiness_delta"),
        (val_div, ":clergy_recovery_drag", 5),
        (val_sub, ":recovery_pct", ":clergy_recovery_drag"),
      (try_end),
      (val_add, ":tax_pressure", ":realm_unrest_pressure"),

      (try_begin),
        (gt, ":tax_pressure", 0),
        (store_div, ":retention_drag", ":tax_pressure", 1),
        (val_sub, ":migration_retention_pct", ":retention_drag"),
        (store_div, ":liquidity_drag", ":tax_pressure", 2),
        (val_sub, ":liquidity_pct", ":liquidity_drag"),
        (store_div, ":recovery_drag", ":tax_pressure", 2),
        (val_sub, ":recovery_pct", ":recovery_drag"),
        (store_mul, ":wealth_drift", ":tax_pressure", -12),
      (else_try),
        (lt, ":tax_pressure", 0),
        (store_sub, ":tax_relief", 0, ":tax_pressure"),
        (store_div, ":retention_bonus", ":tax_relief", 2),
        (val_add, ":migration_retention_pct", ":retention_bonus"),
        (store_div, ":liquidity_bonus", ":tax_relief", 2),
        (val_add, ":liquidity_pct", ":liquidity_bonus"),
        (store_div, ":recovery_bonus", ":tax_relief", 2),
        (val_add, ":recovery_pct", ":recovery_bonus"),
        (store_mul, ":wealth_drift", ":tax_relief", 5),
      (try_end),
      (val_mul, ":migration_retention_pct", ":realm_migration_modifier"),
      (val_div, ":migration_retention_pct", 100),
      (val_mul, ":liquidity_pct", ":realm_trade_volume_modifier"),
      (val_div, ":liquidity_pct", 100),
      (val_mul, ":recovery_pct", ":realm_recovery_modifier"),
      (val_div, ":recovery_pct", 100),
    (try_end),

    (val_clamp, ":tax_revenue_pct", 60, 181),
    (val_clamp, ":tax_pressure", 0, 101),
    (val_clamp, ":merchant_happiness_delta", -100, 101),
    (val_clamp, ":migration_retention_pct", 45, 126),
    (val_clamp, ":liquidity_pct", 45, 126),
    (val_clamp, ":recovery_pct", 45, 126),
    (val_clamp, ":wealth_drift", -1200, 501),
    (val_clamp, ":tax_law_delta", -60, 81),
    (val_clamp, ":tariff_capture_pct", 65, 181),

    (assign, reg0, ":tax_revenue_pct"),
    (assign, reg1, ":tax_pressure"),
    (assign, reg2, ":merchant_happiness_delta"),
    (assign, reg3, ":migration_retention_pct"),
    (assign, reg4, ":liquidity_pct"),
    (assign, reg5, ":recovery_pct"),
    (assign, reg6, ":wealth_drift"),
    (assign, reg7, ":tax_law_delta"),
    (assign, reg8, ":tariff_capture_pct"),
  ]),
]
