SCRIPTS = [
("cf_formation_wedge",
                      [
                        (team_get_leader, ":teamleader", reg0),
                        (gt, ":teamleader", -1),
                        (assign, ":leader", -1),
                        (agent_get_class, ":class", ":teamleader"),
                        (try_begin),
                          (eq, ":class", reg1),
                          (get_player_agent_no, ":player"),
                          (neq, ":teamleader", ":player"),
                          (assign, ":fail", 0),
                          (try_for_range, ":ranged_item", ranged_weapons_begin, ranged_weapons_end),
                            (agent_has_item_equipped, ":teamleader", ":ranged_item"),
                            (assign, ":fail", 1),
                          (end_try),
                          (eq, ":fail", 0),
                          (assign, ":leader", ":teamleader"),
                        (else_try),
                          (assign, reg2, -1),
                          (assign, ":max_xp", 0),
                          (try_for_agents, ":agent"),
                            (agent_is_alive, ":agent"),
                            (agent_is_human, ":agent"),
                            (agent_get_team, ":team", ":agent"),
                            (eq, ":team", reg0),
                            (agent_get_class, ":class", ":agent"),
                            (eq, ":class", reg1),
                            (get_player_agent_no, ":player"),
                            (neq, ":player", ":agent"),
                            (assign, ":fail", 0),
                            (try_for_range, ":ranged_item", ranged_weapons_begin, ranged_weapons_end),
                              (agent_has_item_equipped, ":agent", ":ranged_item"),
                              (assign, ":fail", 1),
                            (end_try),
                            (eq, ":fail", 0),
                            (agent_get_troop_id, ":troop", ":agent"),
                            (troop_get_xp, ":xp", ":troop"),
                            (gt, ":xp", ":max_xp"),
                            (assign, ":max_xp", ":xp"),
                            (assign, reg2, ":agent"),
                          (end_try),
                          (gt, reg2, -1),
                          (assign, ":leader", reg2),
                        (end_try),
                        (gt, ":leader", -1),
                        (agent_get_position, 1, ":leader"),
                        (assign, ":collumn", 1),
                        (assign, ":nc", 3),
                        (position_move_x, 1, -150),
                        (try_for_agents, reg(5)),
                          (neq, reg5, ":leader"),
                          (agent_is_alive, reg(5)),
                          (agent_is_human, reg(5)),
                          (agent_get_team  , ":team", reg5),
                          (eq, ":team", reg0),
                          (agent_get_class , ":class", reg5),
                          (eq, ":class", reg1),
                          (assign, ":fail", 0),
                          (try_for_range, ":ranged_item", ranged_weapons_begin, ranged_weapons_end),
                            (agent_has_item_equipped, reg5, ":ranged_item"),
                            (assign, ":fail", 1),
                          (end_try),
                          (eq, ":fail", 0),
                          (agent_set_scripted_destination, reg(5), 1),
                          (try_begin),
                            (eq, ":collumn", ":nc"),
                            (val_mul, ":nc", -150),
                            (position_move_x, 1, ":nc"),
                            (position_move_y, 1, -300),
                            (assign, ":collumn", 1),
                            (val_div, ":nc", -150),
                            (val_add, ":nc", 2),
                          (else_try),
                            (position_move_x, 1, 150),
                            (val_add, ":collumn", 1),
                          (end_try),
                        (end_try)
                      ]
                    ),
]
