SCRIPTS = [
("cf_formation_stagger",
                      [
                        (team_get_leader, ":teamleader", reg0),
                        (gt, ":teamleader", -1),
                        (assign, ":leader", -1),
                        (agent_get_class, ":class", ":teamleader"),
                        (try_begin),
                          (eq, ":class", reg1),
                          (get_player_agent_no, ":player"),
                          (neq, ":teamleader", ":player"),
                          (assign, ":leader", ":teamleader"),
                        (else_try),
                          (call_script, "script_choose_formation_leader"),
                          (gt, reg2, -1),
                          (assign, ":leader", reg2),
                        (end_try),
                        (gt, ":leader", -1),
                        (agent_get_position, 1, ":leader"),
                        (position_move_x, 1, 100),
                        (assign, ":move_y", -100),
                        (try_for_agents, reg(5)),
                          (neq, reg5, ":leader"),
                          (agent_is_alive, reg(5)),
                          (agent_is_human, reg(5)),
                          (agent_get_team  , ":team", reg5),
                          (eq, ":team", reg0),
                          (agent_get_class , ":class", reg5),
                          (eq, ":class", reg1),
                          (agent_set_scripted_destination, reg(5), 1),
                          (position_move_x, 1, 100),
                          (position_move_y, 1, ":move_y"),
                          (val_mul, ":move_y", -1),
                        (end_try)
                      ]
                    ),
]
