SCRIPTS = [
("process_sieges",
    [
      (try_for_range, ":center_no", walled_centers_begin, walled_centers_end),
        #Reducing siege hardness every day by 20
        (party_get_slot, ":siege_hardness", ":center_no", slot_center_siege_hardness),
        (assign, ":daily_siege_hardness_decay", 20),
        (try_begin),
          (party_slot_eq, ":center_no", slot_party_type, spt_castle),
          (call_script, "script_sod_get_castle_support_profile", ":center_no"),
          (assign, ":castle_siege_readiness", reg11),
          (store_div, ":readiness_delay", ":castle_siege_readiness", 50),
          (val_sub, ":daily_siege_hardness_decay", ":readiness_delay"),
          (val_clamp, ":daily_siege_hardness_decay", 10, 21),
        (try_end),
        (val_sub, ":siege_hardness", ":daily_siege_hardness_decay"),
        (val_max, ":siege_hardness", 0),
        (party_set_slot, ":center_no", slot_center_siege_hardness, ":siege_hardness"),

        (party_get_slot, ":town_food_store", ":center_no", slot_party_food_store),
        (call_script, "script_center_get_food_store_limit", ":center_no"),
        (assign, ":food_store_limit", reg0),
        (try_begin),
          (party_get_slot, ":besieger_party", ":center_no", slot_center_is_besieged_by),
          (ge, ":besieger_party", 0), #town is under siege

          (store_faction_of_party, ":center_faction", ":center_no"),
          # Lift siege unless there is an enemy party nearby
          (assign, ":siege_lifted", 0),
          (try_begin),
            (try_begin),
              (neg|party_is_active, ":besieger_party"),
              (assign, ":siege_lifted", 1),
            (else_try),
              (store_distance_to_party_from_party, ":besieger_distance", ":center_no", ":besieger_party"),
              (gt, ":besieger_distance", 5),
              (assign, ":siege_lifted", 1),
            (try_end),
            (eq, ":siege_lifted", 1),
            (try_for_range, ":enemy_hero", kingdom_heroes_begin, kingdom_heroes_end),
              (troop_slot_eq, ":enemy_hero", slot_troop_occupation, slto_kingdom_hero),
              (troop_get_slot, ":enemy_party", ":enemy_hero", slot_troop_leaded_party),
              (ge, ":enemy_party", 0),
              (party_is_active, ":enemy_party"),
              (store_faction_of_party, ":party_faction", ":enemy_party"),
              (store_relation, ":reln", ":party_faction", ":center_faction"),
              (lt, ":reln", 0),
              (store_distance_to_party_from_party, ":distance", ":center_no", ":enemy_party"),
              (lt, ":distance", 4),
              (assign, ":besieger_party", ":enemy_party"),
              (party_set_slot, ":center_no", slot_center_is_besieged_by, ":enemy_party"),
              (assign, ":siege_lifted", 0),
            (try_end),
          (try_end),
          (try_begin),
            (eq, ":siege_lifted", 1),
            (call_script, "script_lift_siege", ":center_no", 1),
          (else_try),
            #Reduce prosperity of besieged center by -1 with a 33% chance every day. TWAN454
            (try_begin),
              (store_random_in_range, ":random_no", 0, 3),
              (eq, ":random_no", 0),
              (call_script, "script_change_center_prosperity", ":center_no", -3), #MORDACHAI - cause the prosperity to drop faster during a siege
            (try_end),

            # Baseline depopulation from disruption, shelling, and civilian flight.
            # Castles do not use the SoD local population system, so apply this only to towns.
            (try_begin),
              (is_between, ":center_no", towns_begin, towns_end),
              (store_random_in_range, ":rand", 10, 60),
              (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
              (val_sub, ":center_population", ":rand"),
              (val_max, ":center_population", town_pop_min),
              (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
            (try_end),

            (call_script, "script_center_get_food_consumption", ":center_no"),
            (assign, ":food_consumption", reg0),
            (assign, ":starvation_wound_chance", 15),
            (try_begin),
              (party_slot_eq, ":center_no", slot_party_type, spt_castle),
              (call_script, "script_sod_get_castle_support_profile", ":center_no"),
              (assign, ":castle_siege_readiness", reg11),
              (store_div, ":consumption_reduction", ":castle_siege_readiness", 4),
              (val_clamp, ":consumption_reduction", 0, 36),
              (store_sub, ":consumption_factor", 100, ":consumption_reduction"),
              (val_mul, ":food_consumption", ":consumption_factor"),
              (val_div, ":food_consumption", 100),
              (val_max, ":food_consumption", 1),
              (store_div, ":wound_reduction", ":castle_siege_readiness", 20),
              (val_sub, ":starvation_wound_chance", ":wound_reduction"),
              (val_clamp, ":starvation_wound_chance", 5, 16),
            (try_end),
            (val_sub, ":town_food_store", ":food_consumption"), # reduce food while under siege

            # Model shortage pressure in stages instead of only at absolute starvation.
            (try_begin),
              (gt, ":food_consumption", 0),
              (store_mul, ":two_day_stock", ":food_consumption", 2),
              (store_mul, ":five_day_stock", ":food_consumption", 5),

              (try_begin),
                # Absolute starvation: heavy health collapse, sharp urban depopulation, and stronger surrender pressure.
                (le, ":town_food_store", 0),
                (try_begin),
                  (is_between, ":center_no", towns_begin, towns_end),
                  (call_script, "script_change_center_health", ":center_no", -12),
                  (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
                  (store_random_in_range, ":starvation_loss", 80, 181),
                  (val_sub, ":center_population", ":starvation_loss"),
                  (val_max, ":center_population", town_pop_min),
                  (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
                  (call_script, "script_change_center_prosperity", ":center_no", -2),
                (try_end),
                (store_random_in_range, ":r", 0, 100),
                (lt, ":r", ":starvation_wound_chance"),
                (call_script, "script_party_wound_all_members", ":center_no"), # starving garrison may collapse
              (else_try),
                # Critically low stocks: famine conditions begin before full starvation.
                (lt, ":town_food_store", ":two_day_stock"),
                (try_begin),
                  (is_between, ":center_no", towns_begin, towns_end),
                  (call_script, "script_change_center_health", ":center_no", -6),
                  (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
                  (store_random_in_range, ":critical_loss", 25, 81),
                  (val_sub, ":center_population", ":critical_loss"),
                  (val_max, ":center_population", town_pop_min),
                  (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
                (try_end),
                (store_random_in_range, ":random_no", 0, 2),
                (eq, ":random_no", 0),
                (call_script, "script_change_center_prosperity", ":center_no", -1),
              (else_try),
                # Low reserves: sickness and desertion start creeping in even before famine.
                (lt, ":town_food_store", ":five_day_stock"),
                (try_begin),
                  (is_between, ":center_no", towns_begin, towns_end),
                  (call_script, "script_change_center_health", ":center_no", -3),
                  (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
                  (store_random_in_range, ":low_loss", 10, 41),
                  (val_sub, ":center_population", ":low_loss"),
                  (val_max, ":center_population", town_pop_min),
                  (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
                (try_end),
              (try_end),
            (try_end),
          (try_end),
        (else_try),
          #town is not under siege...
          (val_add, ":town_food_store", 30), #add 30 food (significant for castles only.
        (try_end),

        (val_min, ":town_food_store", ":food_store_limit"),
        (val_max, ":town_food_store", 0),
        (party_set_slot, ":center_no", slot_party_food_store, ":town_food_store"),
      (try_end),
  ]),
]
