SCRIPTS = [
("sod_safe_leave_encounter",
 [
   (assign, "$g_leave_encounter", 1),
   (call_script, "script_sod_sanitize_encounter_globals"),
 ]),

("sod_sanitize_encounter_globals",
 [
   (store_current_day, "$g_sod_last_runtime_cleanup_day"),
   (try_begin),
     (lt, "$g_encountered_party", 0),
     (assign, "$g_encountered_party", -1),
   (else_try),
     (neg|party_is_active, "$g_encountered_party"),
     (assign, "$g_encountered_party", -1),
   (try_end),
   (try_begin),
     (lt, "$g_encountered_party_2", 0),
     (assign, "$g_encountered_party_2", -1),
   (else_try),
     (neg|party_is_active, "$g_encountered_party_2"),
     (assign, "$g_encountered_party_2", -1),
   (try_end),
   (try_begin),
     (lt, "$g_enemy_party", 0),
     (assign, "$g_enemy_party", -1),
   (else_try),
     (neg|party_is_active, "$g_enemy_party"),
     (assign, "$g_enemy_party", -1),
   (try_end),
   (try_begin),
     (lt, "$g_talk_troop_party", 0),
     (assign, "$g_talk_troop_party", -1),
   (else_try),
     (neg|party_is_active, "$g_talk_troop_party"),
     (assign, "$g_talk_troop_party", -1),
   (try_end),
   (try_begin),
     (le, "$capturer_party", 0),
     (assign, "$capturer_party", -1),
   (else_try),
     (neg|party_is_active, "$capturer_party"),
     (assign, "$capturer_party", -1),
   (try_end),
 ]),

("sod_validate_capturer_party_to_reg",
 [
   (assign, reg0, 0),
   (try_begin),
     (gt, "$capturer_party", 0),
     (party_is_active, "$capturer_party"),
     (assign, reg0, 1),
   (else_try),
     (assign, "$capturer_party", -1),
   (try_end),
 ]),

("sod_capture_set_capturer_from_encounter_to_reg",
 [
   (assign, "$capturer_party", -1),
   (try_begin),
     (gt, "$g_encountered_party", 0),
     (party_is_active, "$g_encountered_party"),
     (assign, "$capturer_party", "$g_encountered_party"),
   (else_try),
     (gt, "$g_enemy_party", 0),
     (party_is_active, "$g_enemy_party"),
     (assign, "$capturer_party", "$g_enemy_party"),
   (try_end),
   (call_script, "script_sod_validate_capturer_party_to_reg"),
 ]),

("sod_runtime_trace_event",
 [
   (store_script_param_1, ":event_code"),
   (store_script_param_2, ":party_no"),
   (store_script_param, ":troop_no", 3),
   (store_current_day, "$g_sod_last_runtime_trace_day"),
   (assign, "$g_sod_last_runtime_trace_event", ":event_code"),
   (assign, "$g_sod_last_runtime_trace_party", -1),
   (assign, "$g_sod_last_runtime_trace_troop", -1),
   (try_begin),
     (gt, ":party_no", 0),
     (party_is_active, ":party_no"),
     (assign, "$g_sod_last_runtime_trace_party", ":party_no"),
   (try_end),
   (try_begin),
     (is_between, ":troop_no", heroes_begin, heroes_end),
     (assign, "$g_sod_last_runtime_trace_troop", ":troop_no"),
   (try_end),
   (assign, "$g_sod_last_runtime_trace_menu", "$g_next_menu"),
   (assign, "$g_sod_last_runtime_trace_enemy_party", "$g_enemy_party"),
   (assign, "$g_sod_last_runtime_trace_capturer_party", "$capturer_party"),
 ]),

("sod_describe_runtime_sanity_to_s20",
 [
   (assign, reg20, "$g_encountered_party"),
   (assign, reg21, "$g_encountered_party_2"),
   (assign, reg22, "$g_enemy_party"),
   (assign, reg23, "$g_talk_troop_party"),
   (assign, reg24, "$g_leave_encounter"),
   (assign, reg25, "$g_next_menu"),
   (assign, reg26, "$g_ally_party"),
   (assign, reg27, "$current_town"),
   (assign, reg28, "$capturer_party"),
   (assign, reg29, "$g_sod_last_runtime_cleanup_day"),
   (assign, reg30, "$g_sod_last_runtime_trace_day"),
   (assign, reg31, "$g_sod_last_runtime_trace_event"),
   (assign, reg32, "$g_sod_last_runtime_trace_party"),
   (assign, reg33, "$g_sod_last_runtime_trace_troop"),
   (assign, reg34, "$g_sod_last_runtime_trace_menu"),
   (assign, reg35, "$g_sod_last_defeated_party"),
   (assign, reg36, "$g_sod_last_captured_hero"),
   (assign, reg37, "$g_sod_last_runtime_trace_enemy_party"),
   (assign, reg38, "$g_sod_last_runtime_trace_capturer_party"),
   (str_store_string, s21, "@none or stale"),
   (try_begin),
     (gt, "$g_encountered_party", 0),
     (party_is_active, "$g_encountered_party"),
     (str_store_party_name, s21, "$g_encountered_party"),
   (try_end),
   (str_store_string, s22, "@none or stale"),
   (try_begin),
     (gt, "$g_encountered_party_2", 0),
     (party_is_active, "$g_encountered_party_2"),
     (str_store_party_name, s22, "$g_encountered_party_2"),
   (try_end),
   (str_store_string, s23, "@none or stale"),
   (try_begin),
     (gt, "$g_enemy_party", 0),
     (party_is_active, "$g_enemy_party"),
     (str_store_party_name, s23, "$g_enemy_party"),
   (try_end),
   (str_store_string, s24, "@none or stale"),
   (try_begin),
     (gt, "$g_talk_troop_party", 0),
     (party_is_active, "$g_talk_troop_party"),
     (str_store_party_name, s24, "$g_talk_troop_party"),
   (try_end),
   (str_store_string, s25, "@none or stale"),
   (try_begin),
     (gt, "$g_ally_party", 0),
     (party_is_active, "$g_ally_party"),
     (str_store_party_name, s25, "$g_ally_party"),
   (try_end),
   (str_store_string, s26, "@none or stale"),
   (try_begin),
     (is_between, "$current_town", centers_begin, centers_end),
     (str_store_party_name, s26, "$current_town"),
   (try_end),
   (str_store_string, s27, "@none or stale"),
   (try_begin),
     (gt, "$capturer_party", 0),
     (party_is_active, "$capturer_party"),
     (str_store_party_name, s27, "$capturer_party"),
   (try_end),
   (str_store_string, s28, "@none or stale"),
   (try_begin),
     (gt, "$g_sod_last_runtime_trace_party", 0),
     (party_is_active, "$g_sod_last_runtime_trace_party"),
     (str_store_party_name, s28, "$g_sod_last_runtime_trace_party"),
   (try_end),
   (str_store_string, s29, "@none"),
   (try_begin),
     (is_between, "$g_sod_last_runtime_trace_troop", heroes_begin, heroes_end),
     (str_store_troop_name, s29, "$g_sod_last_runtime_trace_troop"),
   (try_end),
   (str_store_string, s30, "@none or stale"),
   (try_begin),
     (gt, "$g_sod_last_defeated_party", 0),
     (party_is_active, "$g_sod_last_defeated_party"),
     (str_store_party_name, s30, "$g_sod_last_defeated_party"),
   (try_end),
   (str_store_string, s31, "@none"),
   (try_begin),
     (is_between, "$g_sod_last_captured_hero", heroes_begin, heroes_end),
     (str_store_troop_name, s31, "$g_sod_last_captured_hero"),
   (try_end),
   (str_store_string, s32, "@none or stale"),
   (try_begin),
     (gt, "$g_sod_last_runtime_trace_enemy_party", 0),
     (party_is_active, "$g_sod_last_runtime_trace_enemy_party"),
     (str_store_party_name, s32, "$g_sod_last_runtime_trace_enemy_party"),
   (try_end),
   (str_store_string, s33, "@none or stale"),
   (try_begin),
     (gt, "$g_sod_last_runtime_trace_capturer_party", 0),
     (party_is_active, "$g_sod_last_runtime_trace_capturer_party"),
     (str_store_party_name, s33, "$g_sod_last_runtime_trace_capturer_party"),
   (try_end),
   (str_store_string, s20, "@Runtime Sanity Report^^Encountered party: {s21} ({reg20})^Second encountered party: {s22} ({reg21})^Enemy party: {s23} ({reg22})^Talk troop party: {s24} ({reg23})^Ally party: {s25} ({reg26})^Current town: {s26} ({reg27})^Capturer party: {s27} ({reg28})^^Leave encounter flag: {reg24}^Next menu: {reg25}^Last cleanup day: {reg29}^^Last runtime trace: event {reg31}, day {reg30}^Trace party: {s28} ({reg32})^Trace troop: {s29} ({reg33})^Trace menu: {reg34}^Trace enemy party: {s32} ({reg37})^Trace capturer party: {s33} ({reg38})^^Last defeated party: {s30} ({reg35})^Last captured hero: {s31} ({reg36})^^Use this report after unusual battle, prisoner, capture, ransom, or menu-return behavior. The cleanup action only clears invalid or inactive encounter globals; it does not change valid parties."),
 ]),
]
