SCRIPTS = [
("cf_sod_battle_commander_troop_available",
 [
   (store_script_param, ":troop_no", 1),
   (assign, ":available", 0),
   (try_begin),
     (eq, ":troop_no", "trp_player"),
     (neg|troop_is_wounded, "trp_player"),
     (assign, ":available", 1),
   (else_try),
     (is_between, ":troop_no", 0, "trp_last_troop"),
     (neq, ":troop_no", "trp_player"),
     (troop_is_hero, ":troop_no"),
     (main_party_has_troop, ":troop_no"),
     (neg|troop_is_wounded, ":troop_no"),
     (assign, ":available", 1),
   (try_end),
   (eq, ":available", 1),
 ]),

("cf_sod_battle_commander_party_has_available_commander",
 [
   (assign, ":found", 0),
   (try_begin),
     (call_script, "script_cf_sod_battle_commander_troop_available", "trp_player"),
     (assign, ":found", 1),
   (else_try),
     (try_for_range, ":companion", active_npcs_begin, active_npcs_end),
       (eq, ":found", 0),
       (call_script, "script_cf_sod_battle_commander_troop_available", ":companion"),
       (assign, ":found", 1),
     (try_end),
   (try_end),
   (eq, ":found", 1),
 ]),

("sod_battle_commander_normalize",
 [
   (assign, ":commander", "$g_sod_battle_commander_troop"),
   (assign, ":valid", 0),
   (try_begin),
     (is_between, ":commander", 0, "trp_last_troop"),
     (call_script, "script_cf_sod_battle_commander_troop_available", ":commander"),
     (assign, ":valid", 1),
   (try_end),
   (try_begin),
     (eq, ":valid", 0),
     (assign, ":commander", -1),
     (try_begin),
       (call_script, "script_cf_sod_battle_commander_troop_available", "trp_player"),
       (assign, ":commander", "trp_player"),
     (else_try),
       (try_for_range, ":companion", active_npcs_begin, active_npcs_end),
         (eq, ":commander", -1),
         (call_script, "script_cf_sod_battle_commander_troop_available", ":companion"),
         (assign, ":commander", ":companion"),
       (try_end),
     (try_end),
   (try_end),
   (assign, "$g_sod_battle_commander_troop", ":commander"),
   (assign, reg0, ":commander"),
 ]),

("cf_sod_battle_commander_can_start",
 [
   (call_script, "script_sod_battle_commander_normalize"),
   (assign, ":commander", reg0),
   (gt, ":commander", -1),
   (call_script, "script_cf_sod_battle_commander_troop_available", ":commander"),
 ]),

("sod_battle_commander_store_current_name_to_s7",
 [
   (call_script, "script_sod_battle_commander_normalize"),
   (assign, ":commander", reg0),
   (try_begin),
     (gt, ":commander", -1),
     (str_store_troop_name, s7, ":commander"),
   (else_try),
     (str_store_string, s7, "@no fit commander"),
   (try_end),
 ]),

("sod_battle_commander_select",
 [
   (store_script_param, ":troop_no", 1),
   (try_begin),
     (call_script, "script_cf_sod_battle_commander_troop_available", ":troop_no"),
     (assign, "$g_sod_battle_commander_troop", ":troop_no"),
   (try_end),
   (call_script, "script_sod_battle_commander_store_current_name_to_s7"),
 ]),

("sod_battle_commander_apply_before_mission",
 [
   (call_script, "script_sod_battle_commander_normalize"),
   (assign, ":commander", reg0),
   (try_begin),
     (gt, ":commander", -1),
     (assign, "$g_sod_battle_commander_troop", ":commander"),
     (assign, "$g_sod_battle_commander_active", 1),
     (assign, "$g_sod_battle_commander_player_spawned", 0),
     (assign, "$g_sod_battle_commander_health_restored", 0),
     (assign, "$g_sod_battle_commander_player_begin_hp", -1),
     (assign, "$g_sod_battle_commander_player_horse_item", -1),
     (assign, "$g_sod_battle_commander_player_horse_imod", 0),
     (set_player_troop, ":commander"),
     (try_begin),
       (neq, ":commander", "trp_player"),
       (str_store_troop_name, s1, ":commander"),
       (display_message, "@{s1} takes the company standard for this fight.", 0xDDDDDD),
       (troop_get_slot, ":times", ":commander", slot_troop_sod_times_took_command),
       (val_add, ":times", 1),
       (troop_set_slot, ":commander", slot_troop_sod_times_took_command, ":times"),
       (store_current_hours, ":hours"),
       (troop_set_slot, ":commander", slot_troop_sod_last_took_command_hours, ":hours"),
     (try_end),
   (else_try),
     (call_script, "script_sod_battle_commander_reset"),
   (try_end),
 ]),

("sod_battle_commander_spawn_player_ally",
 [
   (store_script_param, ":dismount_player", 1),
   (try_begin),
     (eq, "$g_sod_battle_commander_active", 1),
     (neq, "$g_sod_battle_commander_troop", "trp_player"),
     (eq, "$g_sod_battle_commander_player_spawned", 0),
     (neg|troop_is_wounded, "trp_player"),
     (get_player_agent_no, ":player_agent"),
     (ge, ":player_agent", 0),
     (store_troop_health, "$g_sod_battle_commander_player_begin_hp", "trp_player"),
     (agent_get_team, ":player_team", ":player_agent"),
     (agent_get_position, pos49, ":player_agent"),
     (position_move_x, pos49, -100),
     (set_spawn_position, pos49),
     (try_begin),
       (eq, ":dismount_player", 1),
       (troop_get_inventory_slot, "$g_sod_battle_commander_player_horse_item", "trp_player", ek_horse),
       (troop_get_inventory_slot_modifier, "$g_sod_battle_commander_player_horse_imod", "trp_player", ek_horse),
       (troop_set_inventory_slot, "trp_player", ek_horse, -1),
     (try_end),
     (spawn_agent, "trp_player"),
     (assign, ":spawned_agent", reg0),
     (agent_set_team, ":spawned_agent", ":player_team"),
     (try_begin),
       (eq, ":dismount_player", 1),
       (troop_set_inventory_slot, "trp_player", ek_horse, "$g_sod_battle_commander_player_horse_item"),
       (troop_set_inventory_slot_modifier, "trp_player", ek_horse, "$g_sod_battle_commander_player_horse_imod"),
     (try_end),
     (assign, "$g_sod_battle_commander_player_spawned", 1),
   (try_end),
 ]),

("sod_battle_commander_restore_player_health",
 [
   (try_begin),
     (eq, "$g_sod_battle_commander_active", 1),
     (neq, "$g_sod_battle_commander_troop", "trp_player"),
     (eq, "$g_sod_battle_commander_player_spawned", 1),
     (eq, "$g_sod_battle_commander_health_restored", 0),
     (store_troop_health, ":player_end_hp", "trp_player"),
     (party_get_skill_level, ":first_aid_level", "p_main_party", skl_first_aid),
     (val_mul, ":first_aid_level", 5),
     (try_begin),
       (ge, "$g_sod_battle_commander_player_begin_hp", 0),
       (le, ":player_end_hp", "$g_sod_battle_commander_player_begin_hp"),
       (store_sub, ":result_hp", "$g_sod_battle_commander_player_begin_hp", ":player_end_hp"),
       (val_mul, ":result_hp", ":first_aid_level"),
       (val_div, ":result_hp", 100),
       (val_add, ":result_hp", ":player_end_hp"),
       (troop_set_health, "trp_player", ":result_hp"),
     (try_end),
     (assign, "$g_sod_battle_commander_health_restored", 1),
   (try_end),
 ]),

("sod_battle_commander_reset",
 [
   (assign, "$g_sod_battle_commander_troop", "trp_player"),
   (assign, "$g_sod_battle_commander_active", 0),
   (assign, "$g_sod_battle_commander_player_spawned", 0),
   (assign, "$g_sod_battle_commander_health_restored", 0),
   (assign, "$g_sod_battle_commander_player_begin_hp", -1),
   (assign, "$g_sod_battle_commander_player_horse_item", -1),
   (assign, "$g_sod_battle_commander_player_horse_imod", 0),
   (set_player_troop, "trp_player"),
 ]),
]
