SCRIPTS = [
("sod_post_defeat_init",
 [
   (assign, "$sod_post_defeat_state", 0),
   (assign, "$sod_post_defeat_enabled", 1),
   (assign, "$sod_post_defeat_focus_agent", -1),
   (assign, "$sod_post_defeat_focus_index", 0),
   (assign, "$sod_post_defeat_focus_count", 0),
   (assign, "$sod_post_defeat_takeover_used", 0),
   (assign, "$sod_post_defeat_second_in_command", -1),
   (assign, "$sod_post_defeat_help_shown", 0),
   (assign, "$sod_post_defeat_next_rebuild_time", 0),
   (assign, "$sod_post_defeat_casualties_counted", 0),
   (assign, "$sod_post_defeat_aftermath_recorded", 0),
 ]),

("sod_post_defeat_clear",
 [
   (assign, "$sod_post_defeat_state", 0),
   (assign, "$sod_post_defeat_focus_agent", -1),
   (assign, "$sod_post_defeat_focus_index", 0),
   (assign, "$sod_post_defeat_focus_count", 0),
   (assign, "$sod_post_defeat_next_rebuild_time", 0),
 ]),

("cf_sod_post_defeat_agent_is_watchable_base",
 [
   (store_script_param, ":agent_no", 1),
   (gt, ":agent_no", -1),
   (agent_is_alive, ":agent_no"),
   (agent_is_human, ":agent_no"),
   (agent_is_ally, ":agent_no"),
   (agent_slot_eq, ":agent_no", slot_agent_is_hard_routed, 0),
 ]),

("cf_sod_post_defeat_agent_is_watchable_hero",
 [
   (store_script_param, ":agent_no", 1),
   (call_script, "script_cf_sod_post_defeat_agent_is_watchable_base", ":agent_no"),
   (agent_get_troop_id, ":troop_no", ":agent_no"),
   (troop_is_hero, ":troop_no"),
 ]),

("cf_sod_post_defeat_agent_is_watchable_officer",
 [
   (store_script_param, ":agent_no", 1),
   (call_script, "script_cf_sod_post_defeat_agent_is_watchable_base", ":agent_no"),
   (agent_get_troop_id, ":troop_no", ":agent_no"),
   (neg|troop_is_hero, ":troop_no"),
   (store_character_level, ":level", ":troop_no"),
   (ge, ":level", 15),
   (store_skill_level, ":leadership", "skl_leadership", ":troop_no"),
   (store_skill_level, ":tactics", "skl_tactics", ":troop_no"),
   (this_or_next|ge, ":leadership", 1),
   (ge, ":tactics", 1),
 ]),

("sod_post_defeat_rebuild_watch_list",
 [
   (assign, ":desired_index", "$sod_post_defeat_focus_index"),
   (val_max, ":desired_index", 1),
   (assign, ":count", 0),
   (assign, ":focus_agent", -1),
   (try_for_agents, ":agent_no"),
     (agent_set_slot, ":agent_no", slot_agent_sod_post_defeat_focus_index, 0),
   (try_end),
   (try_for_agents, ":agent_no"),
     (call_script, "script_cf_sod_post_defeat_agent_is_watchable_hero", ":agent_no"),
     (val_add, ":count", 1),
     (agent_set_slot, ":agent_no", slot_agent_sod_post_defeat_focus_index, ":count"),
   (try_end),
   (try_begin),
     (eq, ":count", 0),
     (try_for_agents, ":agent_no"),
       (call_script, "script_cf_sod_post_defeat_agent_is_watchable_officer", ":agent_no"),
       (val_add, ":count", 1),
       (agent_set_slot, ":agent_no", slot_agent_sod_post_defeat_focus_index, ":count"),
     (try_end),
   (try_end),
   (try_begin),
     (eq, ":count", 0),
     (try_for_agents, ":agent_no"),
       (call_script, "script_cf_sod_post_defeat_agent_is_watchable_base", ":agent_no"),
       (val_add, ":count", 1),
       (agent_set_slot, ":agent_no", slot_agent_sod_post_defeat_focus_index, ":count"),
     (try_end),
   (try_end),
   (try_begin),
     (gt, ":count", 0),
     (try_begin),
       (gt, ":desired_index", ":count"),
       (assign, ":desired_index", 1),
     (try_end),
     (try_for_agents, ":agent_no"),
       (agent_slot_eq, ":agent_no", slot_agent_sod_post_defeat_focus_index, ":desired_index"),
       (assign, ":focus_agent", ":agent_no"),
     (try_end),
   (else_try),
     (assign, ":desired_index", 0),
   (try_end),
   (assign, "$sod_post_defeat_focus_index", ":desired_index"),
   (assign, "$sod_post_defeat_focus_count", ":count"),
   (assign, "$sod_post_defeat_focus_agent", ":focus_agent"),
   (assign, reg0, ":count"),
   (assign, reg1, ":focus_agent"),
 ]),

("sod_post_defeat_choose_second_in_command",
 [
   (assign, ":best_agent", -1),
   (assign, ":best_troop", -1),
   (assign, ":best_score", -1),
   (try_for_agents, ":agent_no"),
     (call_script, "script_cf_sod_post_defeat_agent_is_watchable_hero", ":agent_no"),
     (agent_get_troop_id, ":troop_no", ":agent_no"),
     (store_character_level, ":level", ":troop_no"),
     (store_skill_level, ":leadership", "skl_leadership", ":troop_no"),
     (store_skill_level, ":tactics", "skl_tactics", ":troop_no"),
     (store_mul, ":score", ":leadership", 600),
     (store_mul, ":tactics_score", ":tactics", 450),
     (val_add, ":score", ":tactics_score"),
     (store_mul, ":level_score", ":level", 20),
     (val_add, ":score", ":level_score"),
     (try_begin),
       (is_between, ":troop_no", companions_begin, companions_end),
       (val_add, ":score", 1200),
       (troop_get_slot, ":approval", ":troop_no", slot_troop_companion_approval),
       (val_add, ":score", ":approval"),
       (troop_get_slot, ":grievance", ":troop_no", slot_troop_companion_grievance),
       (val_sub, ":score", ":grievance"),
     (try_end),
     (gt, ":score", ":best_score"),
     (assign, ":best_score", ":score"),
     (assign, ":best_agent", ":agent_no"),
     (assign, ":best_troop", ":troop_no"),
   (try_end),
   (assign, "$sod_post_defeat_second_in_command", ":best_troop"),
   (try_begin),
     (gt, ":best_agent", -1),
     (assign, "$sod_post_defeat_focus_agent", ":best_agent"),
     (agent_get_slot, "$sod_post_defeat_focus_index", ":best_agent", slot_agent_sod_post_defeat_focus_index),
   (try_end),
   (assign, reg0, ":best_troop"),
   (assign, reg1, ":best_agent"),
   (assign, reg2, ":best_score"),
 ]),

("sod_post_defeat_on_player_fallen",
 [
   (try_begin),
     (eq, "$sod_post_defeat_enabled", 1),
     (eq, "$sod_post_defeat_state", 0),
     (assign, "$sod_post_defeat_state", 1),
     (assign, "$g_sod_battle_player_morale_wavered", 1),
     (call_script, "script_sod_post_defeat_rebuild_watch_list"),
     (call_script, "script_sod_post_defeat_choose_second_in_command"),
     (try_begin),
       (gt, "$sod_post_defeat_second_in_command", 0),
       (str_store_troop_name, s1, "$sod_post_defeat_second_in_command"),
       (try_begin),
         (neq, "$g_sod_battle_commander_troop", "trp_player"),
         (str_store_troop_name, s2, "$g_sod_battle_commander_troop"),
         (display_message, "@{s2} falls. {s1} takes command of the line.", 0xDDDDDD),
       (else_try),
         (display_message, "@You fall. {s1} takes command of the line.", 0xDDDDDD),
       (try_end),
       (troop_get_slot, ":times", "$sod_post_defeat_second_in_command", slot_troop_sod_times_took_command),
       (val_add, ":times", 1),
       (troop_set_slot, "$sod_post_defeat_second_in_command", slot_troop_sod_times_took_command, ":times"),
       (store_current_hours, ":hours"),
       (troop_set_slot, "$sod_post_defeat_second_in_command", slot_troop_sod_last_took_command_hours, ":hours"),
       (call_script, "script_sod_battle_apply_courage_pressure", 0, 8),
       (val_sub, "$g_sod_battle_ally_lord_morale", 5),
     (else_try),
       (try_begin),
         (neq, "$g_sod_battle_commander_troop", "trp_player"),
         (str_store_troop_name, s2, "$g_sod_battle_commander_troop"),
         (display_message, "@{s2} falls. No officer holds the company steady.", 0xDDDDDD),
       (else_try),
         (display_message, "@You fall. No officer holds the company steady.", 0xDDDDDD),
       (try_end),
       (call_script, "script_sod_battle_apply_courage_pressure", 0, 18),
       (val_sub, "$g_sod_battle_ally_lord_morale", 14),
     (try_end),
     (val_clamp, "$g_sod_battle_ally_lord_morale", 0, 101),
   (try_end),
 ]),

("sod_post_defeat_record_aftermath",
 [
   (store_script_param, ":outcome", 1),
   (try_begin),
     (eq, "$sod_post_defeat_aftermath_recorded", 0),
     (assign, "$sod_post_defeat_aftermath_recorded", 1),
     (try_begin),
       (gt, "$sod_post_defeat_state", 0),
       (try_begin),
         (gt, "$sod_post_defeat_second_in_command", 0),
         (str_store_troop_name, s1, "$sod_post_defeat_second_in_command"),
         (try_begin),
           (gt, ":outcome", 0),
           (try_begin),
             (neq, "$g_sod_battle_commander_troop", "trp_player"),
             (str_store_troop_name, s2, "$g_sod_battle_commander_troop"),
             (display_message, "@The company stands victorious after {s2} falls; {s1} held command.", 0xDDDDDD),
           (else_try),
             (display_message, "@The company stands victorious after you fall; {s1} held command.", 0xDDDDDD),
           (try_end),
         (else_try),
           (try_begin),
             (neq, "$g_sod_battle_commander_troop", "trp_player"),
             (str_store_troop_name, s2, "$g_sod_battle_commander_troop"),
             (display_message, "@The company breaks after {s2} falls; {s1} was the last officer holding the line.", 0xDDDDDD),
           (else_try),
             (display_message, "@The company breaks after you fall; {s1} was the last officer holding the line.", 0xDDDDDD),
           (try_end),
         (try_end),
       (else_try),
         (try_begin),
           (gt, ":outcome", 0),
           (try_begin),
             (neq, "$g_sod_battle_commander_troop", "trp_player"),
             (str_store_troop_name, s2, "$g_sod_battle_commander_troop"),
             (display_message, "@The company stands victorious after {s2} falls, but no surviving officer clearly held command.", 0xDDDDDD),
           (else_try),
             (display_message, "@The company stands victorious after you fall, but no surviving officer clearly held command.", 0xDDDDDD),
           (try_end),
         (else_try),
           (try_begin),
             (neq, "$g_sod_battle_commander_troop", "trp_player"),
             (str_store_troop_name, s2, "$g_sod_battle_commander_troop"),
             (display_message, "@The company breaks after {s2} falls; no surviving officer held the line.", 0xDDDDDD),
           (else_try),
             (display_message, "@The company breaks after you fall; no surviving officer held the line.", 0xDDDDDD),
           (try_end),
         (try_end),
       (try_end),
     (try_end),
     (gt, "$sod_post_defeat_second_in_command", 0),
     (try_begin),
       (gt, ":outcome", 0),
       (troop_get_slot, ":victories", "$sod_post_defeat_second_in_command", slot_troop_sod_post_fall_victories),
       (val_add, ":victories", 1),
       (troop_set_slot, "$sod_post_defeat_second_in_command", slot_troop_sod_post_fall_victories, ":victories"),
     (else_try),
       (lt, ":outcome", 0),
       (troop_get_slot, ":failures", "$sod_post_defeat_second_in_command", slot_troop_sod_post_fall_failures),
       (val_add, ":failures", 1),
       (troop_set_slot, "$sod_post_defeat_second_in_command", slot_troop_sod_post_fall_failures, ":failures"),
     (try_end),
   (try_end),
 ]),

("sod_post_defeat_count_casualties_once",
 [
   (try_begin),
     (eq, "$sod_post_defeat_casualties_counted", 0),
     (assign, "$sod_post_defeat_casualties_counted", 1),
     (call_script, "script_count_mission_casualties_from_agents"),
   (try_end),
 ]),

("sod_post_defeat_select_next_agent",
 [
   (store_script_param, ":direction", 1),
   (call_script, "script_sod_post_defeat_rebuild_watch_list"),
   (assign, ":count", reg0),
   (try_begin),
     (gt, ":count", 0),
     (val_add, "$sod_post_defeat_focus_index", ":direction"),
     (try_begin),
       (lt, "$sod_post_defeat_focus_index", 1),
       (assign, "$sod_post_defeat_focus_index", ":count"),
     (else_try),
       (gt, "$sod_post_defeat_focus_index", ":count"),
       (assign, "$sod_post_defeat_focus_index", 1),
     (try_end),
     (call_script, "script_sod_post_defeat_rebuild_watch_list"),
   (try_end),
 ]),

("sod_post_defeat_show_focus_message",
 [
   (try_begin),
     (gt, "$sod_post_defeat_focus_agent", -1),
     (agent_is_alive, "$sod_post_defeat_focus_agent"),
     (str_store_agent_name, s1, "$sod_post_defeat_focus_agent"),
     (display_message, "@Camera follows {s1}.", 0xDDDDDD),
   (else_try),
     (display_message, "@No surviving officer remains to follow.", 0xDDDDDD),
   (try_end),
 ]),

("sod_post_defeat_focus_camera",
 [
   (store_mission_timer_a, ":mission_time"),
   (try_begin),
     (ge, ":mission_time", "$sod_post_defeat_next_rebuild_time"),
     (call_script, "script_sod_post_defeat_rebuild_watch_list"),
     (assign, "$sod_post_defeat_next_rebuild_time", ":mission_time"),
     (val_add, "$sod_post_defeat_next_rebuild_time", 2),
   (else_try),
     (lt, "$sod_post_defeat_focus_agent", 0),
     (call_script, "script_sod_post_defeat_rebuild_watch_list"),
   (else_try),
     (neg|agent_is_alive, "$sod_post_defeat_focus_agent"),
     (call_script, "script_sod_post_defeat_rebuild_watch_list"),
   (try_end),
   (try_begin),
     (gt, "$sod_post_defeat_focus_agent", -1),
     (agent_is_alive, "$sod_post_defeat_focus_agent"),
     (agent_get_position, pos2, "$sod_post_defeat_focus_agent"),
     (agent_get_look_position, pos1, "$sod_post_defeat_focus_agent"),
     (position_copy_rotation, pos2, pos1),
     (position_move_y, pos2, -600),
     (position_move_z, pos2, 260),
     (mission_cam_set_position, pos2),
   (else_try),
     (assign, "$camera_mode", 1),
     (assign, "$sod_post_defeat_state", 2),
     (display_message, "@No surviving ally remains to follow. Free camera.", 0xDDDDDD),
   (try_end),
 ]),

("sod_post_defeat_describe_command_memory_to_s35",
 [
   (assign, ":best_companion", -1),
   (assign, ":best_times", 0),
   (assign, ":best_victories", 0),
   (assign, ":best_failures", 0),
   (assign, ":best_last_hours", 0),
   (assign, ":best_score", -1),
   (try_for_range, ":companion", companions_begin, companions_end),
     (main_party_has_troop, ":companion"),
     (troop_get_slot, ":times", ":companion", slot_troop_sod_times_took_command),
     (troop_get_slot, ":victories", ":companion", slot_troop_sod_post_fall_victories),
     (troop_get_slot, ":last_hours", ":companion", slot_troop_sod_last_took_command_hours),
     (assign, ":candidate_score", ":times"),
     (val_mul, ":candidate_score", 1000),
     (store_mul, ":victory_score", ":victories", 100),
     (val_add, ":candidate_score", ":victory_score"),
     (val_add, ":candidate_score", ":last_hours"),
     (try_begin),
       (eq, ":best_companion", -1),
       (gt, ":times", 0),
       (assign, ":best_companion", ":companion"),
       (assign, ":best_times", ":times"),
       (assign, ":best_victories", ":victories"),
       (troop_get_slot, ":best_failures", ":companion", slot_troop_sod_post_fall_failures),
       (assign, ":best_last_hours", ":last_hours"),
       (assign, ":best_score", ":candidate_score"),
     (else_try),
       (gt, ":candidate_score", ":best_score"),
       (gt, ":times", 0),
       (assign, ":best_companion", ":companion"),
       (assign, ":best_times", ":times"),
       (assign, ":best_victories", ":victories"),
       (troop_get_slot, ":best_failures", ":companion", slot_troop_sod_post_fall_failures),
       (assign, ":best_last_hours", ":last_hours"),
       (assign, ":best_score", ":candidate_score"),
     (try_end),
   (try_end),
   (try_begin),
     (gt, ":best_companion", -1),
     (str_store_troop_name, s36, ":best_companion"),
     (assign, reg50, ":best_times"),
     (assign, reg51, ":best_victories"),
     (assign, reg52, ":best_failures"),
     (store_current_hours, ":current_hours"),
     (store_sub, reg53, ":current_hours", ":best_last_hours"),
     (val_div, reg53, 24),
     (val_max, reg53, 0),
     (str_store_string, s35, "@Command continuity: {s36} has held command after you fell {reg50} time(s). Outcomes after your fall: victories {reg51}, collapses {reg52}. Last called forward {reg53} day(s) ago."),
   (else_try),
     (str_store_string, s35, "@Command continuity: no companion in the company has yet had to hold the line after you fell."),
   (try_end),
 ]),
]
