SCRIPTS = [
("store_movement_order_name_to_s1",
      [(store_script_param_1, ":team_no"),
        (store_script_param_2, ":class_no"),
        (team_get_movement_order, ":cur_order", ":team_no", ":class_no"),
        (try_begin),
          (eq, ":cur_order", mordr_hold),
          (str_store_string, s1, "@Holding"),
        (else_try),
          (eq, ":cur_order", mordr_follow),
          (str_store_string, s1, "@Following"),
        (else_try),
          (eq, ":cur_order", mordr_charge),
          (str_store_string, s1, "@Charging"),
        (else_try),
          (eq, ":cur_order", mordr_advance),
          (str_store_string, s1, "@Advancing"),
        (else_try),
          (eq, ":cur_order", mordr_fall_back),
          (str_store_string, s1, "@Falling Back"),
        (else_try),
          (eq, ":cur_order", mordr_stand_closer),
          (str_store_string, s1, "@Standing Closer"),
        (else_try),
          (eq, ":cur_order", mordr_spread_out),
          (str_store_string, s1, "@Spreading Out"),
        (else_try),
          (eq, ":cur_order", mordr_stand_ground),
          (str_store_string, s1, "@Standing"),
        (else_try),
          (str_store_string, s1, "@N/A"),
        (try_end),
    ]),
]
