SCRIPTS = [
("store_riding_order_name_to_s1",
      [(store_script_param_1, ":team_no"),
        (store_script_param_2, ":class_no"),
        (team_get_riding_order, ":cur_order", ":team_no", ":class_no"),
        (try_begin),
          (eq, ":cur_order", rordr_free),
          (str_store_string, s1, "@Free"),
        (else_try),
          (eq, ":cur_order", rordr_mount),
          (str_store_string, s1, "@Mount"),
        (else_try),
          (eq, ":cur_order", rordr_dismount),
          (str_store_string, s1, "@Dismount"),
        (else_try),
          (str_store_string, s1, "@N/A"),
        (try_end),
    ]),
]
