SCRIPTS = [
("team_give_order_from_order_panel",
      [(store_script_param_1, ":leader_agent_no"),
        (store_script_param_2, ":order"),
        (agent_get_team, ":team_no", ":leader_agent_no"),
        (set_show_messages, 0),
        (try_begin),
          (eq, "$g_formation_infantry_selected", 1),
          (team_give_order, ":team_no", grc_infantry, ":order"),
        (try_end),
        (try_begin),
          (eq, "$g_formation_archers_selected", 1),
          (team_give_order, ":team_no", grc_archers, ":order"),
        (try_end),
        (try_begin),
          (eq, "$g_formation_cavalry_selected", 1),
          (team_give_order, ":team_no", grc_cavalry, ":order"),
        (try_end),

        (try_begin),
          (eq, ":order", mordr_hold),
          (agent_get_position, pos1, ":leader_agent_no"),
          (try_begin),
            (eq, "$g_formation_infantry_selected", 1),
            (team_set_order_position, ":team_no", grc_infantry, pos1),
          (try_end),
          (try_begin),
            (eq, "$g_formation_archers_selected", 1),
            (team_set_order_position, ":team_no", grc_archers, pos1),
          (try_end),
          (try_begin),
            (eq, "$g_formation_cavalry_selected", 1),
            (team_set_order_position, ":team_no", grc_cavalry, pos1),
          (try_end),
        (try_end),
        (set_show_messages, 1),
    ]),
]
