SCRIPTS = [
("update_order_panel_statistics_and_map", #TODO: Call this in every battle mission template, once per second
      [(set_fixed_point_multiplier, 1000),
        (assign, ":num_us_ready_infantry", 0),
        (assign, ":num_us_ready_archers", 0),
        (assign, ":num_us_ready_cavalry", 0),
        (assign, ":num_us_wounded_infantry", 0),
        (assign, ":num_us_wounded_archers", 0),
        (assign, ":num_us_wounded_cavalry", 0),
        (assign, ":num_us_dead_infantry", 0),
        (assign, ":num_us_dead_archers", 0),
        (assign, ":num_us_dead_cavalry", 0),
        (assign, ":num_allies_ready_men", 0),
        (assign, ":num_allies_wounded_men", 0),
        (assign, ":num_allies_dead_men", 0),
        (assign, ":num_enemies_ready_men", 0),
        (assign, ":num_enemies_wounded_men", 0),
        (assign, ":num_enemies_dead_men", 0),

        (get_player_agent_no, ":player_agent"),
        (agent_get_team, ":player_team", ":player_agent"),

        (assign, ":old_is_infantry_listening", 0),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_infantry),
          (assign, ":old_is_infantry_listening", 1),
        (try_end),
        (assign, ":old_is_archers_listening", 0),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_archers),
          (assign, ":old_is_archers_listening", 1),
        (try_end),
        (assign, ":old_is_cavalry_listening", 0),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_cavalry),
          (assign, ":old_is_cavalry_listening", 1),
        (try_end),

        (get_scene_boundaries, pos2, pos3),

        (try_for_agents, ":cur_agent"),
          (agent_is_human, ":cur_agent"),
          (agent_get_class, ":agent_class", ":cur_agent"),
          (agent_get_party_id, ":agent_party", ":cur_agent"),
          (agent_get_slot, ":agent_overlay", ":cur_agent", slot_agent_map_overlay_id),
          (try_begin),
            (eq, ":agent_party", "p_main_party"),
            (try_begin),
              (agent_is_alive, ":cur_agent"),
              (call_script, "script_update_agent_position_on_map", ":cur_agent"),

              (try_begin),
                (eq, ":agent_class", grc_archers),
                (val_add, ":num_us_ready_archers", 1),
              (else_try),
                (eq, ":agent_class", grc_cavalry),
                (val_add, ":num_us_ready_cavalry", 1),
              (else_try),
                #infantry
                (val_add, ":num_us_ready_infantry", 1),
              (try_end),
            (else_try),
              (overlay_set_alpha, ":agent_overlay", 0),
              (agent_is_wounded, ":cur_agent"),
              (try_begin),
                (eq, ":agent_class", grc_archers),
                (val_add, ":num_us_wounded_archers", 1),
              (else_try),
                (eq, ":agent_class", grc_cavalry),
                (val_add, ":num_us_wounded_cavalry", 1),
              (else_try),
                #infantry
                (val_add, ":num_us_wounded_infantry", 1),
              (try_end),
            (else_try),
              (try_begin),
                (eq, ":agent_class", grc_archers),
                (val_add, ":num_us_dead_archers", 1),
              (else_try),
                (eq, ":agent_class", grc_cavalry),
                (val_add, ":num_us_dead_cavalry", 1),
              (else_try),
                #infantry
                (val_add, ":num_us_dead_infantry", 1),
              (try_end),
            (try_end),
          (else_try),
            (agent_is_ally, ":cur_agent"),
            (try_begin),
              (agent_is_alive, ":cur_agent"),
              (call_script, "script_update_agent_position_on_map", ":cur_agent"),
              (val_add, ":num_allies_ready_men", 1),
            (else_try),
              (overlay_set_alpha, ":agent_overlay", 0),
              (agent_is_wounded, ":cur_agent"),
              (val_add, ":num_allies_wounded_men", 1),
            (else_try),
              (val_add, ":num_allies_dead_men", 1),
            (try_end),
          (else_try),
            (try_begin),
              (agent_is_alive, ":cur_agent"),
              (call_script, "script_update_agent_position_on_map", ":cur_agent"),
              (val_add, ":num_enemies_ready_men", 1),
            (else_try),
              (overlay_set_alpha, ":agent_overlay", 0),
              (agent_is_wounded, ":cur_agent"),
              (val_add, ":num_enemies_wounded_men", 1),
            (else_try),
              (val_add, ":num_enemies_dead_men", 1),
            (try_end),
          (try_end),
        (try_end),
        (assign, reg1, ":num_us_ready_infantry"),
        (assign, reg2, ":num_us_ready_archers"),
        (assign, reg3, ":num_us_ready_cavalry"),
        (store_add, ":num_us_ready_men", ":num_us_ready_infantry", ":num_us_ready_archers"),
        (val_add, ":num_us_ready_men", ":num_us_ready_cavalry"),
        (store_add, ":num_us_wounded_men", ":num_us_wounded_infantry", ":num_us_wounded_archers"),
        (val_add, ":num_us_wounded_men", ":num_us_wounded_cavalry"),
        (store_add, ":num_us_dead_men", ":num_us_dead_infantry", ":num_us_dead_archers"),
        (val_add, ":num_us_dead_men", ":num_us_dead_cavalry"),
        (assign, reg4, ":num_us_ready_men"),
        (assign, reg5, ":num_us_wounded_men"),
        (assign, reg6, ":num_us_dead_men"),
        (assign, reg7, ":num_allies_ready_men"),
        (assign, reg8, ":num_allies_wounded_men"),
        (assign, reg9, ":num_allies_dead_men"),
        (assign, reg10, ":num_enemies_ready_men"),
        (assign, reg11, ":num_enemies_wounded_men"),
        (assign, reg12, ":num_enemies_dead_men"),
        (overlay_set_text, "$g_presentation_obj_7", "@Infantry ({reg1})"),
        (overlay_set_text, "$g_presentation_obj_8", "@Archers ({reg2})"),
        (overlay_set_text, "$g_presentation_obj_9", "@Cavalry ({reg3})"),
        (overlay_set_text, "$g_battle_us_ready", "@{reg4}"),
        (overlay_set_text, "$g_battle_us_wounded", "@{reg5}"),
        (overlay_set_text, "$g_battle_us_dead", "@{reg6}"),
        (overlay_set_text, "$g_battle_allies_ready", "@{reg7}"),
        (overlay_set_text, "$g_battle_allies_wounded", "@{reg8}"),
        (overlay_set_text, "$g_battle_allies_dead", "@{reg9}"),
        (overlay_set_text, "$g_battle_enemies_ready", "@{reg10}"),
        (overlay_set_text, "$g_battle_enemies_wounded", "@{reg11}"),
        (overlay_set_text, "$g_battle_enemies_dead", "@{reg12}"),

        (assign, ":stat_position_x", 100),
        (assign, ":stat_position_y", 100),
        (val_add, ":stat_position_x", 150),
        (val_add, ":stat_position_y", 80),
        (position_set_x, pos1, ":stat_position_x"),
        (position_set_y, pos1, ":stat_position_y"),
        (overlay_set_position, "$g_battle_us_ready", pos1),
        (val_add, ":stat_position_x", 150),
        (position_set_x, pos1, ":stat_position_x"),
        (overlay_set_position, "$g_battle_us_wounded", pos1),
        (val_add, ":stat_position_x", 150),
        (position_set_x, pos1, ":stat_position_x"),
        (overlay_set_position, "$g_battle_us_dead", pos1),
        (val_add, ":stat_position_x", -300),
        (val_add, ":stat_position_y", -40),
        (position_set_x, pos1, ":stat_position_x"),
        (position_set_y, pos1, ":stat_position_y"),
        (overlay_set_position, "$g_battle_allies_ready", pos1),
        (val_add, ":stat_position_x", 150),
        (position_set_x, pos1, ":stat_position_x"),
        (overlay_set_position, "$g_battle_allies_wounded", pos1),
        (val_add, ":stat_position_x", 150),
        (position_set_x, pos1, ":stat_position_x"),
        (overlay_set_position, "$g_battle_allies_dead", pos1),
        (val_add, ":stat_position_x", -300),
        (val_add, ":stat_position_y", -40),
        (position_set_x, pos1, ":stat_position_x"),
        (position_set_y, pos1, ":stat_position_y"),
        (overlay_set_position, "$g_battle_enemies_ready", pos1),
        (val_add, ":stat_position_x", 150),
        (position_set_x, pos1, ":stat_position_x"),
        (overlay_set_position, "$g_battle_enemies_wounded", pos1),
        (val_add, ":stat_position_x", 150),
        (position_set_x, pos1, ":stat_position_x"),
        (overlay_set_position, "$g_battle_enemies_dead", pos1),

        (call_script, "script_update_order_flags_on_map"),

        (try_begin),
          (eq, ":old_is_infantry_listening", 1),
          (eq, ":old_is_archers_listening", 1),
          (eq, ":old_is_cavalry_listening", 1),
          (team_set_order_listener, ":player_team", grc_everyone),
        (else_try),
          (eq, ":old_is_infantry_listening", 1),
          (team_set_order_listener, ":player_team", grc_infantry),
        (else_try),
          (eq, ":old_is_archers_listening", 1),
          (team_set_order_listener, ":player_team", grc_archers),
        (else_try),
          (eq, ":old_is_cavalry_listening", 1),
          (team_set_order_listener, ":player_team", grc_cavalry),
        (try_end),
    ]),
]
