SCRIPTS = [
("update_order_panel_checked_classes",
      [(get_player_agent_no, ":player_agent"),
        (agent_get_team, ":player_team", ":player_agent"),

        (try_begin),
          (class_is_listening_order, ":player_team", grc_infantry),
          (overlay_set_val, "$g_presentation_obj_4", 1),
          (assign, "$g_formation_infantry_selected", 1),
          (overlay_animate_to_alpha, "$g_presentation_obj_1", 250, 0x44),
        (else_try),
          (overlay_set_val, "$g_presentation_obj_4", 0),
          (assign, "$g_formation_infantry_selected", 0),
          (overlay_animate_to_alpha, "$g_presentation_obj_1", 250, 0),
        (try_end),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_archers),
          (overlay_set_val, "$g_presentation_obj_5", 1),
          (assign, "$g_formation_archers_selected", 1),
          (overlay_animate_to_alpha, "$g_presentation_obj_2", 250, 0x44),
        (else_try),
          (overlay_set_val, "$g_presentation_obj_5", 0),
          (assign, "$g_formation_archers_selected", 0),
          (overlay_animate_to_alpha, "$g_presentation_obj_2", 250, 0),
        (try_end),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_cavalry),
          (overlay_set_val, "$g_presentation_obj_6", 1),
          (assign, "$g_formation_cavalry_selected", 1),
          (overlay_animate_to_alpha, "$g_presentation_obj_3", 250, 0x44),
        (else_try),
          (overlay_set_val, "$g_presentation_obj_6", 0),
          (assign, "$g_formation_cavalry_selected", 0),
          (overlay_animate_to_alpha, "$g_presentation_obj_3", 250, 0),
        (try_end),
    ]),
]
