SCRIPTS = [
("update_order_flags_on_map",
      [(set_fixed_point_multiplier, 1000),
        (get_player_agent_no, ":player_agent"),
        (agent_get_team, ":player_team", ":player_agent"),

        (assign, ":old_is_infantry_listening", 0),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_infantry),
          (assign, ":old_is_infantry_listening", 1),
        (try_end),
        (assign, ":old_is_archers_listening", 0),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_archers),
          (assign, ":old_is_archers_listening", 1),
        (try_end),
        (assign, ":old_is_cavalry_listening", 0),
        (try_begin),
          (class_is_listening_order, ":player_team", grc_cavalry),
          (assign, ":old_is_cavalry_listening", 1),
        (try_end),

        (get_scene_boundaries, pos2, pos3),

        (team_get_movement_order, ":cur_order", ":player_team", grc_infantry),
        (try_begin),
          (eq, ":cur_order", mordr_hold),
          (team_get_order_position, pos1, ":player_team", grc_infantry),
          (call_script, "script_convert_3d_pos_to_map_pos"),
          (overlay_set_alpha, "$g_battle_map_infantry_order_flag", 0xFF),
          (overlay_set_position, "$g_battle_map_infantry_order_flag", pos0),
        (else_try),
          (overlay_set_alpha, "$g_battle_map_infantry_order_flag", 0),
        (try_end),
        (team_get_movement_order, ":cur_order", ":player_team", grc_archers),
        (try_begin),
          (eq, ":cur_order", mordr_hold),
          (team_get_order_position, pos1, ":player_team", grc_archers),
          (call_script, "script_convert_3d_pos_to_map_pos"),
          (overlay_set_alpha, "$g_battle_map_archers_order_flag", 0xFF),
          (overlay_set_position, "$g_battle_map_archers_order_flag", pos0),
        (else_try),
          (overlay_set_alpha, "$g_battle_map_archers_order_flag", 0),
        (try_end),
        (team_get_movement_order, ":cur_order", ":player_team", grc_cavalry),
        (try_begin),
          (eq, ":cur_order", mordr_hold),
          (team_get_order_position, pos1, ":player_team", grc_cavalry),
          (call_script, "script_convert_3d_pos_to_map_pos"),
          (overlay_set_alpha, "$g_battle_map_cavalry_order_flag", 0xFF),
          (overlay_set_position, "$g_battle_map_cavalry_order_flag", pos0),
        (else_try),
          (overlay_set_alpha, "$g_battle_map_cavalry_order_flag", 0),
        (try_end),

        (try_begin),
          (eq, ":old_is_infantry_listening", 1),
          (eq, ":old_is_archers_listening", 1),
          (eq, ":old_is_cavalry_listening", 1),
          (team_set_order_listener, ":player_team", grc_everyone),
        (else_try),
          (eq, ":old_is_infantry_listening", 1),
          (team_set_order_listener, ":player_team", grc_infantry),
        (else_try),
          (eq, ":old_is_archers_listening", 1),
          (team_set_order_listener, ":player_team", grc_archers),
        (else_try),
          (eq, ":old_is_cavalry_listening", 1),
          (team_set_order_listener, ":player_team", grc_cavalry),
        (try_end),
    ]),
]
