DIALOGS = [
[anyone, "tavernkeeper_deliver_wine", [
    (check_quest_active, "qst_deliver_wine"),
    (quest_slot_eq, "qst_deliver_wine", slot_quest_target_center, "$g_encountered_party"),
    (quest_get_slot, ":quest_target_item", "qst_deliver_wine", slot_quest_target_item),
    (quest_get_slot, ":quest_target_amount", "qst_deliver_wine", slot_quest_target_amount),
    (quest_get_slot, reg5, "qst_deliver_wine", slot_quest_gold_reward),
    (quest_get_slot, ":quest_giver_troop", "qst_deliver_wine", slot_quest_giver_troop),
    (store_item_kind_count, ":item_count", ":quest_target_item"),
    (ge, ":item_count", ":quest_target_amount"),
    (str_store_item_name, s4, ":quest_target_item"),
    (call_script, "script_store_troop_name", s9, ":quest_giver_troop"),
   ],
   "At last! My stock was almost depleted. I had paid the cost of the {s4} in advance. Here, take these {reg5} denars. That should cover your pay. And give {s9} my regards. I'll put in a good word for you next time I deal with him.",
   "tavernkeeper_pretalk",
   [(quest_get_slot, ":quest_target_item", "qst_deliver_wine", slot_quest_target_item),
    (quest_get_slot, ":quest_target_amount", "qst_deliver_wine", slot_quest_target_amount),
    (quest_get_slot, ":quest_gold_reward", "qst_deliver_wine", slot_quest_gold_reward),
    (store_item_kind_count, ":item_count", ":quest_target_item"),
    (try_begin),
      (check_quest_active, "qst_deliver_wine"),
      (ge, ":item_count", ":quest_target_amount"),
      (troop_remove_items, "trp_player", ":quest_target_item", ":quest_target_amount"),
      (call_script, "script_troop_add_gold", "trp_player", ":quest_gold_reward"),
      (assign, ":xp_reward", ":quest_gold_reward"),
      (val_mul, ":xp_reward", 4),
      (add_xp_as_reward, ":xp_reward"),
      (quest_get_slot, ":giver_town", "qst_deliver_wine", slot_quest_giver_center),
      (call_script, "script_change_player_relation_with_center", ":giver_town", 2),
      (call_script, "script_change_player_relation_with_center", "$current_town", 1),
      (call_script, "script_end_quest", "qst_deliver_wine"),
    (else_try),
      (display_message, "@The wine delivery could not be completed because the cargo was no longer in your inventory.", 0xFF6666),
    (try_end),
    ]],
]
