DIALOGS = [
[anyone, "tavernkeeper_deliver_wine_incomplete", [],
   "Attacked by bandits eh? You are lucky they left you alive. Anyway, I can pay you no more than {reg5} denars for this. And I will let {s1} know that my order was delivered less than completely, so you will probably be charged for this loss.",
   "tavernkeeper_pretalk",
   [    (quest_get_slot, ":quest_target_item", "qst_deliver_wine", slot_quest_target_item),
    (quest_get_slot, ":quest_target_amount", "qst_deliver_wine", slot_quest_target_amount),
    (quest_get_slot, ":quest_gold_reward", "qst_deliver_wine", slot_quest_gold_reward),
    (quest_get_slot, ":quest_giver_troop", "qst_deliver_wine", slot_quest_giver_troop),
    (store_item_kind_count, ":item_count", ":quest_target_item"),
    (troop_remove_items, "trp_player", ":quest_target_item", ":item_count"),
    (val_mul, ":quest_gold_reward", ":item_count"),
    (try_begin),
    (gt, ":quest_target_amount", 0),
    (val_div, ":quest_gold_reward", ":quest_target_amount"),
    (try_end),
    (call_script, "script_troop_add_gold", "trp_player", ":quest_gold_reward"),
    (assign, reg5, ":quest_gold_reward"),
    (assign, ":xp_reward", ":quest_gold_reward"),
    (val_mul, ":xp_reward", 4),
    (add_xp_as_reward, ":xp_reward"),
    (call_script, "script_store_troop_name", s1, ":quest_giver_troop"),
    (assign, ":debt", "$qst_deliver_wine_debt"),
    (store_sub, ":item_left", ":quest_target_amount", ":item_count"),
    (val_mul, ":debt", ":item_left"),
    (try_begin),
    (gt, ":quest_target_amount", 0),
    (val_div, ":debt", ":quest_target_amount"),
    (try_end),
    (val_add, "$debt_to_merchants_guild", ":debt"),
    (quest_get_slot, ":giver_town", "qst_deliver_wine", slot_quest_giver_center),
    (call_script, "script_change_player_relation_with_center", ":giver_town", 1),
    (call_script, "script_end_quest", "qst_deliver_wine"),
    ]],
]
