DIALOGS = [
[anyone, "militia_awaiting_ransom_fight", [],
   "You won't be demanding anything when you're dead.", "close_window",
   [(quest_get_slot, ":quest_target_party", "qst_serpent_host_free_spy", slot_quest_target_party),
    (try_begin),
      (gt, ":quest_target_party", 0),
      (party_is_active, ":quest_target_party"),
      (party_count_prisoners_of_type, ":spy_prisoners", ":quest_target_party", "trp_sh_spy"),
      (eq, ":spy_prisoners", 0),
      (party_add_prisoners, ":quest_target_party", "trp_sh_spy", 1),
    (try_end),
    (assign, "$g_enemy_party", "$g_encountered_party"),
    (call_script, "script_let_nearby_parties_join_current_battle", 0, 0),
    (encounter_attack)]],
]
