DIALOGS = [
[anyone, "tavernkeeper_deliver_wine_lost", [
    (check_quest_active, "qst_deliver_wine"),
    (quest_slot_eq, "qst_deliver_wine", slot_quest_target_center, "$g_encountered_party"),
    (quest_get_slot, ":quest_target_item", "qst_deliver_wine", slot_quest_target_item),
    (quest_get_slot, ":quest_giver_troop", "qst_deliver_wine", slot_quest_giver_troop),
    (store_item_kind_count, ":item_count", ":quest_target_item"),
    (eq, ":item_count", 0),
    (str_store_item_name, s4, ":quest_target_item"),
    (call_script, "script_store_troop_name", s1, ":quest_giver_troop"),
   ], "What? I was waiting for that {s4} for weeks! And now you are telling me that you lost it? You may rest assured that I will let {s1} know about this.", "tavernkeeper_pretalk",
   [(quest_get_slot, ":quest_target_item", "qst_deliver_wine", slot_quest_target_item),
    (store_item_kind_count, ":item_count", ":quest_target_item"),
    (try_begin),
      (check_quest_active, "qst_deliver_wine"),
      (eq, ":item_count", 0),
      (add_xp_as_reward, 40),
      (val_add, "$debt_to_merchants_guild", "$qst_deliver_wine_debt"),
      (call_script, "script_end_quest", "qst_deliver_wine"),
    (else_try),
      (display_message, "@The lost wine report could not be completed because the cargo state changed.", 0xFF6666),
    (try_end),
   ]],
]
