DIALOGS = [
[anyone, "tavernkeeper_smuggle_wine_lost", [
    (check_quest_active, "qst_slavers_deliver_wine"),
    (store_item_kind_count, ":item_count", "itm_wine"),
    (eq, ":item_count", 0),
   ], "What? I was waiting for that wine for weeks! And now you are telling me that you lost it? You may rest assured that I will let the Slavers know about this.", "close_window",
   [(store_item_kind_count, ":item_count", "itm_wine"),
    (try_begin),
      (check_quest_active, "qst_slavers_deliver_wine"),
      (eq, ":item_count", 0),
      (add_xp_as_reward, 40),
      (faction_get_slot, ":plyr_debt", "fac_sod_merc_guild6", player_debt_to_faction),
	  (val_add, ":plyr_debt", "$qst_slavers_deliver_wine_debt"),
	  (faction_set_slot, "fac_sod_merc_guild6", player_debt_to_faction, ":plyr_debt"),
      (call_script, "script_fail_quest", "qst_slavers_deliver_wine"),
      (call_script, "script_end_quest", "qst_slavers_deliver_wine"),
    (else_try),
      (display_message, "@The lost smuggled wine report could not be completed because the cargo state changed.", 0xFF6666),
    (try_end),
   ]],
]
