DIALOGS = [
[party_tpl|pt_bandits_awaiting_ransom, "bandits_awaiting_ransom_pay", [
   (check_quest_active, "qst_kidnapped_girl"),
   (neg|check_quest_concluded, "qst_kidnapped_girl"),
   (quest_slot_eq, "qst_kidnapped_girl", slot_quest_current_state, 1),
   (quest_slot_eq, "qst_kidnapped_girl", slot_quest_target_party, "$g_encountered_party"),
   (party_is_active, "$g_encountered_party"),
],
   "The coin is good. Take her and leave before we regret being reasonable.", "close_window",
   [(quest_get_slot, ":quest_target_amount", "qst_kidnapped_girl", slot_quest_target_amount),
    (quest_get_slot, ":quest_target_party", "qst_kidnapped_girl", slot_quest_target_party),
    (quest_get_slot, ":quest_target_center", "qst_kidnapped_girl", slot_quest_target_center),
    (try_begin),
      (party_is_active, ":quest_target_party"),
      (eq, ":quest_target_party", "$g_encountered_party"),
      (party_count_prisoners_of_type, ":girl_prisoners", ":quest_target_party", "trp_kidnapped_girl"),
      (gt, ":girl_prisoners", 0),
      (set_spawn_radius, 1),
      (spawn_around_party, ":quest_target_party", "pt_kidnapped_girl"),
      (assign, ":girl_party", reg0),
      (gt, ":girl_party", 0),
      (party_is_active, ":girl_party"),
      (call_script, "script_sod_player_charge_gold", ":quest_target_amount"),
      (play_sound, "snd_money_paid"),
      (party_remove_prisoners, ":quest_target_party", "trp_kidnapped_girl", 1),
      (party_set_ai_behavior, ":girl_party", ai_bhvr_hold),
      (party_set_flags, ":girl_party", pf_default_behavior, 0),
      (quest_set_slot, "qst_kidnapped_girl", slot_quest_target_party, ":girl_party"),
      (quest_set_slot, "qst_kidnapped_girl", slot_quest_current_state, 2),
      (party_set_ai_behavior, ":quest_target_party", ai_bhvr_travel_to_party),
      (party_set_ai_object, ":quest_target_party", ":quest_target_center"),
      (party_set_flags, ":quest_target_party", pf_default_behavior, 0),
      (add_gold_to_party, ":quest_target_amount", ":quest_target_party"),
      (assign, "$g_leave_encounter", 1),
    (else_try),
      (display_message, "@The kidnapped girl could not be placed on the map. Keep the ransom and try again later.", 0xFFCC66),
    (try_end),
    ]],
]
