DIALOGS = [
[trp_seven_ash_sister_elianor, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_stage, sod_seven_ash_stage_aftermath),
      (quest_get_slot, ":survivors", "qst_seven_ash_ultimatum", slot_quest_seven_ash_survival_bitmask),
      (store_and, ":alive", ":survivors", sod_seven_ash_defender_elianor),
      (gt, ":alive", 0),
      (quest_get_slot, ":unlocks", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
      (store_and, ":can_join", ":unlocks", sod_seven_ash_defender_elianor),
      (gt, ":can_join", 0),
    ],
    "The church floor is clean enough for fever now. Not clean. Enough. The wounded have water, the children have names on the tally, and the refugees know which cellar door opens if fire comes again. You spent food before lives. That is why I can leave some mercy behind me.",
    "seven_ash_elianor_offer_choice",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer_choice", [],
    "Come with me. I need someone who remembers the wounded before victory speeches begin.",
    "seven_ash_elianor_join",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer_choice", [],
    "Stay in Ashwick. Keep the infirmary, the water, and the refugee lists honest.",
    "seven_ash_elianor_stay",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer_choice", [],
    "You have carried enough grief. Keep your shelter here.",
    "seven_ash_elianor_farewell",
    []],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_join", [],
    "I will come with bandages, ledgers, and a voice that will irritate every man who thinks mercy is what happens after useful work is done.",
    "close_window",
    [
      (party_add_members, "p_main_party", "trp_seven_ash_sister_elianor", 1),
      (quest_get_slot, ":joined", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_joined_bitmask),
      (val_or, ":joined", sod_seven_ash_defender_elianor),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_joined_bitmask, ":joined"),
      (str_store_string, s49, "@Elianor joined the player after Ashwick made sanctuary, supplied care, and protected wounded people without turning refugees into guarded labor."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 8, s49, 0),
    ]],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_stay", [],
    "Good. A village with a wall is still only a village. A village with a place for the helpless has begun becoming worth defending.",
    "close_window",
    [
      (quest_get_slot, ":stayed", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_stayed_bitmask),
      (val_or, ":stayed", sod_seven_ash_defender_elianor),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_stayed_bitmask, ":stayed"),
      (str_store_string, s49, "@Elianor stayed in Ashwick as infirmary keeper, refugee advocate, and witness for the wounded."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 8, s49, 0),
    ]],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_farewell", [],
    "Grief is not a sack one sets down. But it can be carried with straighter shoulders when someone else admits its weight.",
    "close_window",
    [
      (quest_get_slot, ":refused", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask),
      (val_or, ":refused", sod_seven_ash_defender_elianor),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask, ":refused"),
      (str_store_string, s49, "@Elianor kept her road short and her shelter open after Ashwick's wounded and refugees were given room."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 8, s49, 0),
    ]],
[trp_seven_ash_sister_elianor, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_stage, sod_seven_ash_stage_aftermath),
      (quest_get_slot, ":survivors", "qst_seven_ash_ultimatum", slot_quest_seven_ash_survival_bitmask),
      (store_and, ":alive", ":survivors", sod_seven_ash_defender_elianor),
      (gt, ":alive", 0),
      (quest_get_slot, ":unlocks", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
      (store_and, ":can_join", ":unlocks", sod_seven_ash_defender_elianor),
      (eq, ":can_join", 0),
    ],
    "The wounded lived because someone made room after the shouting. That is not the same as mercy. You counted useful hands first, or guarded desperation and called it shelter. I will not follow a banner that weighs hurt people by what they can carry.",
    "seven_ash_elianor_refusal_close",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_refusal_close", [],
    "Then stay with the wounded. Ashwick needs your witness more than my company does.",
    "seven_ash_elianor_refusal_done",
    []],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_refusal_done", [],
    "It needs more water, more cloth, and fewer men mistaking survival for absolution. I will begin there.",
    "close_window",
    [
      (quest_get_slot, ":refused", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask),
      (val_or, ":refused", sod_seven_ash_defender_elianor),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask, ":refused"),
      (str_store_string, s49, "@Elianor refused to join because her sanctuary condition was not met, but remained with Ashwick's wounded and refugees."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 8, s49, 0),
    ]],
]
