DIALOGS = [
[trp_seven_ash_beren_hardhand, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_recruit_id, sod_seven_ash_defender_beren),
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_beren_status, sod_seven_ash_recruit_in_progress),
    ],
    "Ansel still telling folk I was not empty? Kind of him. Useless, but kind. Villages remember law when they need hanging done. Now one needs a lawless man to stand in its gate. That is a fine joke.",
    "seven_ash_beren_offer",
    [
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_beren_evidence, sod_seven_ash_evidence_witness),
    ]],
[trp_seven_ash_beren_hardhand|plyr, "seven_ash_beren_offer", [],
    "Fight me by the pit rules. If you can be stopped, you can be trusted to stop.",
    "seven_ash_beren_duel_answer",
    []],
[trp_seven_ash_beren_hardhand|plyr, "seven_ash_beren_offer", [],
    "Serve Ashwick under witness, and I will seek lawful pardon for what famine law made of you.",
    "seven_ash_beren_pardon_answer",
    []],
[trp_seven_ash_beren_hardhand|plyr, "seven_ash_beren_offer", [],
    "Stand in the breach and take spoils from raiders, not villagers. That is the bargain.",
    "seven_ash_beren_spoils_answer",
    []],
[trp_seven_ash_beren_hardhand|plyr, "seven_ash_beren_offer", [],
    "Wulfred has Halvorn Pike. I do not care what happens to anyone between you and him.",
    "seven_ash_beren_unrestrained_answer",
    []],
[trp_seven_ash_beren_hardhand|plyr, "seven_ash_beren_offer", [],
    "Stay in the pit. Ashwick cannot afford your kind of help.",
    "seven_ash_beren_refusal_answer",
    []],
[trp_seven_ash_beren_hardhand, "seven_ash_beren_duel_answer", [],
    "There. A boundary with teeth. I like that better than mercy speeches. I will stand where the wall breaks, and I will stop when the work is done.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_beren, sod_seven_ash_route_best),
      (str_store_string, s49, "@Beren joined after accepting a controlled pit challenge: violence bounded by rules before being brought to Ashwick."),
      (add_quest_note_from_sreg, "qst_seven_ash_beren_hardhand", 3, s49, 0),
    ]],
[trp_seven_ash_beren_hardhand, "seven_ash_beren_pardon_answer", [],
    "A pardon is a thin blanket over old graves. Still, Ansel would want me to take it. I will fight for the village and let witnesses count what I do.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_beren, sod_seven_ash_route_legal_promise),
      (str_store_string, s49, "@Beren joined under witnessed service and a promise to seek lawful pardon after Ashwick survives."),
      (add_quest_note_from_sreg, "qst_seven_ash_beren_hardhand", 3, s49, 0),
    ]],
[trp_seven_ash_beren_hardhand, "seven_ash_beren_spoils_answer", [],
    "Spoils from wolves, not sheep. Easy words before smoke. I will take them anyway and see whether your village remembers the difference.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_beren, sod_seven_ash_route_hard),
      (str_store_string, s49, "@Beren joined for raider spoils, useful in the breach but watched by Ashwick's people."),
      (add_quest_note_from_sreg, "qst_seven_ash_beren_hardhand", 3, s49, 0),
    ]],
[trp_seven_ash_beren_hardhand, "seven_ash_beren_unrestrained_answer", [],
    "Then you want a fire and will complain about ash. Fine. Point me at Halvorn when the gate breaks.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_beren, sod_seven_ash_route_forced_service),
      (str_store_string, s49, "@Beren joined without restraint, focused on Halvorn Pike and dangerous to anything in his path."),
      (add_quest_note_from_sreg, "qst_seven_ash_beren_hardhand", 3, s49, 0),
    ]],
[trp_seven_ash_beren_hardhand, "seven_ash_beren_refusal_answer", [],
    "Good. Keep your clean hands. Just do not come looking for mine when the gate beam screams.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_beren, sod_seven_ash_route_refusal),
      (str_store_string, s49, "@Beren refused the call and remained at the mill-yard pit."),
      (add_quest_note_from_sreg, "qst_seven_ash_beren_hardhand", 3, s49, 0),
    ]],
]
