DIALOGS = [
[trp_seven_ash_reeve_martin, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_pressure_interlude_active, sod_seven_ash_interlude_grain_riot),
    ],
    "Reeve Martin says the measure changed because the sacks changed. I can show the tally. Hungry people do not eat tally marks. Tomas calls this disorder. Elianor calls it hunger. I call it three days before ugly.",
    "seven_ash_grain_riot_reply",
    []],
[trp_seven_ash_reeve_martin|plyr, "seven_ash_grain_riot_reply", [],
    "Open the stores by fair measure. Let everyone see the same scoop.",
    "seven_ash_grain_fair",
    []],
[trp_seven_ash_reeve_martin|plyr, "seven_ash_grain_riot_reply", [],
    "Enforce ration discipline. The line survives only if the measures hold.",
    "seven_ash_grain_discipline",
    []],
[trp_seven_ash_reeve_martin|plyr, "seven_ash_grain_riot_reply", [],
    "Buy grain at whatever price keeps the granary from becoming a battlefield.",
    "seven_ash_grain_buy",
    []],
[trp_seven_ash_reeve_martin|plyr, "seven_ash_grain_riot_reply", [],
    "Seize hidden private grain. No one eats well while Ashwick counts crumbs.",
    "seven_ash_grain_seize",
    []],
[trp_seven_ash_reeve_martin|plyr, "seven_ash_grain_riot_reply", [],
    "Promise future compensation and keep the ration line moving.",
    "seven_ash_grain_promise",
    []],
[trp_seven_ash_reeve_martin, "seven_ash_grain_fair", [],
    "A fair scoop empties sacks faster. It also keeps hands off throats. I will bring the tally into the yard.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_grain_riot, sod_seven_ash_route_best),
    ]],
[trp_seven_ash_reeve_martin, "seven_ash_grain_discipline", [],
    "Then Tomas gets his line and I keep the key. Useful things. Not beloved things.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_grain_riot, sod_seven_ash_route_hard),
    ]],
[trp_seven_ash_reeve_martin, "seven_ash_grain_buy", [],
    "Dear grain tastes like survival until the debt collector arrives. I will send riders with coin.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_grain_riot, sod_seven_ash_route_legal_promise),
    ]],
[trp_seven_ash_reeve_martin, "seven_ash_grain_seize", [],
    "Hidden sacks are still sacks. Hidden grudges are still grudges. We will gain both.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_grain_riot, sod_seven_ash_route_forced_service),
    ]],
[trp_seven_ash_reeve_martin, "seven_ash_grain_promise", [],
    "Future compensation. I can write it clean. Ink is cheap today.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_grain_riot, sod_seven_ash_route_refusal),
    ]],
]
