DIALOGS = [
[trp_seven_ash_sister_elianor, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_recruit_id, sod_seven_ash_defender_elianor),
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_elianor_status, sod_seven_ash_recruit_in_progress),
    ],
    "If you want blessings, go to a bishop. If you want people carried out from under burning roofs, tell me how many carts you brought. You saw the wounded, the widows, the children, and the men too hurt to stand. Which of them does Ashwick have room to save?",
    "seven_ash_elianor_offer",
    [
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_elianor_evidence, sod_seven_ash_evidence_witness),
    ]],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer", [],
    "Ashwick will make sanctuary. Bring the wounded, children, and widows. We will spend food before we spend lives.",
    "seven_ash_elianor_sanctuary_answer",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer", [],
    "Bring only able workers and fighters. I need hands that can carry timber or hold a spear.",
    "seven_ash_elianor_able_answer",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer", [],
    "I will fund your camp and send supplies, but Ashwick cannot take everyone inside the walls.",
    "seven_ash_elianor_fund_answer",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer", [],
    "The refugees come as guarded labor. Shelter is earned by work on Ashwick's defenses.",
    "seven_ash_elianor_forced_answer",
    []],
[trp_seven_ash_sister_elianor|plyr, "seven_ash_elianor_offer", [],
    "Stay with Saint Ormond's. Ashwick cannot carry this much grief.",
    "seven_ash_elianor_refusal_answer",
    []],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_sanctuary_answer", [],
    "Then you understand the wall is not the village. The people are. I will come, and I will bring the ones who cannot buy their way into anyone's mercy.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_elianor, sod_seven_ash_route_best),
      (str_store_string, s49, "@Elianor joined after Ashwick promised sanctuary for wounded, children, and widows at real cost to food and space."),
      (add_quest_note_from_sreg, "qst_seven_ash_sister_elianor", 3, s49, 0),
    ]],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_able_answer", [],
    "You choose the ones easiest to defend and call it prudence. Some will live because of that. Some will remember why they were left outside.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_elianor, sod_seven_ash_route_hard),
      (str_store_string, s49, "@Elianor joined reluctantly after Ashwick accepted only able workers and fighters from Saint Ormond's."),
      (add_quest_note_from_sreg, "qst_seven_ash_sister_elianor", 3, s49, 0),
    ]],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_fund_answer", [],
    "Coin and supplies are not mercy, but they can become bread and clean cloth. I will send helpers, then come when the carts return.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_elianor, sod_seven_ash_route_legal_promise),
      (str_store_string, s49, "@Elianor joined through a supply bargain: Saint Ormond's remains outside, but Ashwick funds the camp and gains healer support."),
      (add_quest_note_from_sreg, "qst_seven_ash_sister_elianor", 3, s49, 0),
    ]],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_forced_answer", [],
    "No. Labor under guard is just captivity with warmer words. I will come only because someone must watch what you do to the desperate.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_elianor, sod_seven_ash_route_forced_service),
      (str_store_string, s49, "@Elianor was forced into Ashwick's plan after refugees were treated as guarded labor. She comes as witness, not ally."),
      (add_quest_note_from_sreg, "qst_seven_ash_sister_elianor", 3, s49, 0),
    ]],
[trp_seven_ash_sister_elianor, "seven_ash_elianor_refusal_answer", [],
    "Then carry less grief and more guilt. I have no shortage of either here.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_elianor, sod_seven_ash_route_refusal),
      (str_store_string, s49, "@Elianor refused the call and remained at Saint Ormond's refugee camp."),
      (add_quest_note_from_sreg, "qst_seven_ash_sister_elianor", 3, s49, 0),
    ]],
]
