DIALOGS = [
[trp_seven_ash_mother_hilda, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_pressure_interlude_active, sod_seven_ash_interlude_first_funeral),
    ],
    "We are burying someone before the siege. Remember that when folk call this preparation. The grave is shallow because hands are needed elsewhere. Tell me what words you want above it.",
    "seven_ash_first_funeral_reply",
    []],
[trp_seven_ash_mother_hilda|plyr, "seven_ash_first_funeral_reply", [],
    "Tell the truth. This death is part of the price, and we will not hide the cost from those paying it.",
    "seven_ash_first_funeral_truth",
    []],
[trp_seven_ash_mother_hilda|plyr, "seven_ash_first_funeral_reply", [],
    "Promise victory. Give them something stronger than grief to hold.",
    "seven_ash_first_funeral_victory",
    []],
[trp_seven_ash_mother_hilda|plyr, "seven_ash_first_funeral_reply", [],
    "Name Wulfred as the cause. Put the anger where it belongs.",
    "seven_ash_first_funeral_blame_wulfred",
    []],
[trp_seven_ash_mother_hilda|plyr, "seven_ash_first_funeral_reply", [],
    "Blame negligence. Someone failed before Wulfred ever touched the wall.",
    "seven_ash_first_funeral_blame_us",
    []],
[trp_seven_ash_mother_hilda|plyr, "seven_ash_first_funeral_reply", [],
    "Say nothing. Let the work continue.",
    "seven_ash_first_funeral_silence",
    []],
[trp_seven_ash_mother_hilda, "seven_ash_first_funeral_truth", [],
    "Truth, then. It is a poor blanket, but it does not rot in the rain.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_first_funeral, sod_seven_ash_route_best),
    ]],
[trp_seven_ash_mother_hilda, "seven_ash_first_funeral_victory", [],
    "Victory is a bright word for a dark hole. I will say it carefully.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_first_funeral, sod_seven_ash_route_hard),
    ]],
[trp_seven_ash_mother_hilda, "seven_ash_first_funeral_blame_wulfred", [],
    "Anger can keep a body standing. It cannot tell the body where to stand. We will need both.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_first_funeral, sod_seven_ash_route_legal_promise),
    ]],
[trp_seven_ash_mother_hilda, "seven_ash_first_funeral_blame_us", [],
    "Blame is a fast shovel. It digs badly.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_first_funeral, sod_seven_ash_route_forced_service),
    ]],
[trp_seven_ash_mother_hilda, "seven_ash_first_funeral_silence", [],
    "Then the grave will have more words than we do.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_first_funeral, sod_seven_ash_route_refusal),
    ]],
]
