DIALOGS = [
[trp_seven_ash_garric_ashbow, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_recruit_id, sod_seven_ash_defender_garric),
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_garric_status, sod_seven_ash_recruit_in_progress),
    ],
    "Door, window, kitchen hatch, stairs. Four exits, five if Eda still keeps the cellar loose. You came loud enough for every man here to know you need something. Say it plain.",
    "seven_ash_garric_offer",
    [
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_garric_evidence, sod_seven_ash_evidence_witness),
    ]],
[trp_seven_ash_garric_ashbow|plyr, "seven_ash_garric_offer", [],
    "Eda told me what happened here. I will not use it. Ashwick needs eyes that see exits before blood starts.",
    "seven_ash_garric_best_answer",
    []],
[trp_seven_ash_garric_ashbow|plyr, "seven_ash_garric_offer", [],
    "You get the watch platform and clear authority over archers. Pride waits until after the village lives.",
    "seven_ash_garric_hard_answer",
    []],
[trp_seven_ash_garric_ashbow|plyr, "seven_ash_garric_offer", [],
    "Stand for Ashwick and I will put Eda Flint under written protection before reeve and priest.",
    "seven_ash_garric_legal_answer",
    []],
[trp_seven_ash_garric_ashbow|plyr, "seven_ash_garric_offer", [],
    "The Split Hart story can stay buried or it can buy me an archer. Choose quickly.",
    "seven_ash_garric_blackmail_answer",
    []],
[trp_seven_ash_garric_ashbow|plyr, "seven_ash_garric_offer", [],
    "Keep your corner. Ashwick will need another answer.",
    "seven_ash_garric_refusal_answer",
    []],
[trp_seven_ash_garric_ashbow, "seven_ash_garric_best_answer", [],
    "That is the first decent silence I have heard in this room. Tell Eda I leave by the back. Tell Ashwick I shoot for the living, not for applause.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_garric, sod_seven_ash_route_best),
      (str_store_string, s49, "@Garric Ashbow joined after the player protected Eda Flint's testimony and asked him to choose the living over old insult."),
      (add_quest_note_from_sreg, "qst_seven_ash_garric_ashbow", 3, s49, 0),
    ]],
[trp_seven_ash_garric_ashbow, "seven_ash_garric_hard_answer", [],
    "Good. Orders I can test. If your archers waste arrows, I will say so where their mothers can hear it.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_garric, sod_seven_ash_route_hard),
      (str_store_string, s49, "@Garric Ashbow joined under hard terms: command of the watch platform and no room for tavern pride."),
      (add_quest_note_from_sreg, "qst_seven_ash_garric_ashbow", 3, s49, 0),
    ]],
[trp_seven_ash_garric_ashbow, "seven_ash_garric_legal_answer", [],
    "Paper burns, but witnesses remember who signed it. Have the reeve write it. I will come when the ink is wet.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_garric, sod_seven_ash_route_legal_promise),
      (str_store_string, s49, "@Garric Ashbow joined after the player promised written protection for Eda Flint."),
      (add_quest_note_from_sreg, "qst_seven_ash_garric_ashbow", 3, s49, 0),
    ]],
[trp_seven_ash_garric_ashbow, "seven_ash_garric_blackmail_answer", [],
    "Then you bought a bow and poisoned the hand holding it. I will stand on your wall. I will not stand beside you.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_garric, sod_seven_ash_route_blackmail),
      (str_store_string, s49, "@Garric Ashbow was forced toward Ashwick by leverage over the Split Hart story. His skill comes with resentment."),
      (add_quest_note_from_sreg, "qst_seven_ash_garric_ashbow", 3, s49, 0),
    ]],
[trp_seven_ash_garric_ashbow, "seven_ash_garric_refusal_answer", [],
    "Then remember this corner when the arrows fall short. Some men are cowards. Some are just finished.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_first_defender_road", sod_seven_ash_defender_garric, sod_seven_ash_route_refusal),
      (str_store_string, s49, "@Garric Ashbow refused the call and remained at the Split Hart."),
      (add_quest_note_from_sreg, "qst_seven_ash_garric_ashbow", 3, s49, 0),
    ]],
]
