DIALOGS = [
[trp_seven_ash_sir_aldrik_vane, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_stage, sod_seven_ash_stage_aftermath),
      (quest_get_slot, ":survivors", "qst_seven_ash_ultimatum", slot_quest_seven_ash_survival_bitmask),
      (store_and, ":alive", ":survivors", sod_seven_ash_defender_aldrik),
      (gt, ":alive", 0),
      (quest_get_slot, ":unlocks", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
      (store_and, ":can_join", ":unlocks", sod_seven_ash_defender_aldrik),
      (gt, ":can_join", 0),
    ],
    "Mara stood before the gate and named the bridge without lowering her eyes. The villagers heard it. My shield hangs where frightened men can see that an oath is a task, not a song. You gave me witness instead of flattery, and restraint instead of revenge.",
    "seven_ash_aldrik_offer_choice",
    []],
[trp_seven_ash_sir_aldrik_vane|plyr, "seven_ash_aldrik_offer_choice", [],
    "Ride with me. I need an oath that can survive ugly orders.",
    "seven_ash_aldrik_join",
    []],
[trp_seven_ash_sir_aldrik_vane|plyr, "seven_ash_aldrik_offer_choice", [],
    "Stay in Ashwick. Teach shieldmen that duty is work, not decoration.",
    "seven_ash_aldrik_stay",
    []],
[trp_seven_ash_sir_aldrik_vane|plyr, "seven_ash_aldrik_offer_choice", [],
    "You have answered enough for one name. Keep your peace here.",
    "seven_ash_aldrik_farewell",
    []],
[trp_seven_ash_sir_aldrik_vane, "seven_ash_aldrik_join", [],
    "Then I ride. If your cause asks for courage, I will lend it steel. If it asks for cruelty and calls it necessity, I will answer as witness.",
    "close_window",
    [
      (party_add_members, "p_main_party", "trp_seven_ash_sir_aldrik_vane", 1),
      (quest_get_slot, ":joined", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_joined_bitmask),
      (val_or, ":joined", sod_seven_ash_defender_aldrik),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_joined_bitmask, ":joined"),
      (str_store_string, s49, "@Aldrik joined the player after public witness and lawful duty restored his oath without turning it into revenge."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 4, s49, 0),
    ]],
[trp_seven_ash_sir_aldrik_vane, "seven_ash_aldrik_stay", [],
    "A village that has survived a wolf needs more than a knight's departure. I will stay until their shield line no longer needs my shame to stand straight.",
    "close_window",
    [
      (quest_get_slot, ":stayed", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_stayed_bitmask),
      (val_or, ":stayed", sod_seven_ash_defender_aldrik),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_stayed_bitmask, ":stayed"),
      (str_store_string, s49, "@Aldrik stayed in Ashwick as shield captain and public witness to the village oath."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 4, s49, 0),
    ]],
[trp_seven_ash_sir_aldrik_vane, "seven_ash_aldrik_farewell", [],
    "Peace is not the word. Usefulness, perhaps. I can accept usefulness without asking it to sing.",
    "close_window",
    [
      (quest_get_slot, ":refused", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask),
      (val_or, ":refused", sod_seven_ash_defender_aldrik),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask, ":refused"),
      (str_store_string, s49, "@Aldrik laid his farewell beside the shield on Ashwick's gate and kept his oath within sight of it."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 4, s49, 0),
    ]],
[trp_seven_ash_sir_aldrik_vane, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_stage, sod_seven_ash_stage_aftermath),
      (quest_get_slot, ":survivors", "qst_seven_ash_ultimatum", slot_quest_seven_ash_survival_bitmask),
      (store_and, ":alive", ":survivors", sod_seven_ash_defender_aldrik),
      (gt, ":alive", 0),
      (quest_get_slot, ":unlocks", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
      (store_and, ":can_join", ":unlocks", sod_seven_ash_defender_aldrik),
      (eq, ":can_join", 0),
    ],
    "I survived, and Ashwick survived. That is mercy enough. But you hired my shame, or held a charge over it, and no oath follows a hand that treats witness as a tool. I will guard this gate, not your banner.",
    "seven_ash_aldrik_refusal_close",
    []],
[trp_seven_ash_sir_aldrik_vane|plyr, "seven_ash_aldrik_refusal_close", [],
    "Then guard it. Let Ashwick remember what you stood for.",
    "seven_ash_aldrik_refusal_done",
    []],
[trp_seven_ash_sir_aldrik_vane, "seven_ash_aldrik_refusal_done", [],
    "I will try. A man can be late to honor and still arrive before the last bell.",
    "close_window",
    [
      (quest_get_slot, ":refused", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask),
      (val_or, ":refused", sod_seven_ash_defender_aldrik),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_refusal_bitmask, ":refused"),
      (str_store_string, s49, "@Aldrik refused to join because his oath was not restored through public witness or lawful terms, but he remained at Ashwick's gate."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 4, s49, 0),
    ]],
]
