DIALOGS = [
[trp_seven_ash_rafe_carrick, "start",
    [
      (quest_slot_eq, "qst_seven_ash_ultimatum", slot_quest_seven_ash_pressure_interlude_active, sod_seven_ash_interlude_wulfred_offer),
    ],
    "Carr sends parchment instead of riders today. One offer, written seven ways: a clean name, paid timber, knightly standing, safe passage, command, a champion's place, refugees spared. He knows which hunger belongs to which defender. Do you answer as a village, or let each person hold the hook alone?",
    "seven_ash_wulfred_offer_reply",
    []],
[trp_seven_ash_rafe_carrick|plyr, "seven_ash_wulfred_offer_reply", [],
    "Read it aloud and answer aloud. No one is being bought quietly.",
    "seven_ash_wulfred_offer_public",
    []],
[trp_seven_ash_rafe_carrick|plyr, "seven_ash_wulfred_offer_reply", [],
    "Forge a reply. Let Wulfred think one hook caught.",
    "seven_ash_wulfred_offer_forge",
    []],
[trp_seven_ash_rafe_carrick|plyr, "seven_ash_wulfred_offer_reply", [],
    "Hide the letter. The defenders have enough fear without tailored bait.",
    "seven_ash_wulfred_offer_hide",
    []],
[trp_seven_ash_rafe_carrick|plyr, "seven_ash_wulfred_offer_reply", [],
    "Punish the messenger. Let Wulfred learn what his paper is worth here.",
    "seven_ash_wulfred_offer_punish",
    []],
[trp_seven_ash_rafe_carrick, "seven_ash_wulfred_offer_public", [],
    "Brave, or costly. Sometimes those are married. I will carry back that Ashwick answers with one throat.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_wulfred_offer, sod_seven_ash_route_best),
    ]],
[trp_seven_ash_rafe_carrick, "seven_ash_wulfred_offer_forge", [],
    "A false yes. Carr respects traps when they are his. We will see whether he respects yours.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_wulfred_offer, sod_seven_ash_route_hard),
    ]],
[trp_seven_ash_rafe_carrick, "seven_ash_wulfred_offer_hide", [],
    "Silence, then. A locked box can still rattle.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_wulfred_offer, sod_seven_ash_route_refusal),
    ]],
[trp_seven_ash_rafe_carrick, "seven_ash_wulfred_offer_punish", [],
    "Punish boots for the road they walked. Carr will understand that language. He speaks it too.",
    "close_window",
    [
      (call_script, "script_sod_seven_ash_resolve_pressure_interlude", sod_seven_ash_interlude_wulfred_offer, sod_seven_ash_route_forced_service),
    ]],
]
