MISSION_TEMPLATES = [
(
    "village_attack_bandits", mtf_battle_mode, charge,
    "You lead your men to battle.",
    [
     (3, mtef_visitor_source|mtef_team_1, 0, aif_start_alarmed, 1, []),
     (1, mtef_team_0|mtef_use_exact_number, 0, aif_start_alarmed, 7, []),
     (1, mtef_visitor_source|mtef_team_0, 0, aif_start_alarmed, 1, []),
     ],
    [
      common_battle_mission_start,
      common_battle_tab_press, 
	  common_battle_horse_health, 
      common_battle_xp_log_suppression_tick,
      sod_battle_commander_spawn_player_ally,

      (ti_question_answered, 0, 0, [],
       [(store_trigger_param_1, ":answer"),
        (eq, ":answer", 0),
        (assign, "$pin_player_fallen", 0),
        (str_store_string, s5, "str_retreat"),
        (call_script, "script_simulate_retreat", 10, 20),
        (assign, "$g_battle_result", -1),
        (call_script, "script_sod_post_defeat_record_aftermath", -1),
        (call_script, "script_sod_post_defeat_count_casualties_once"),
        (call_script, "script_sod_post_defeat_clear"),
        (finish_mission, 0), ]),

      (0, 0, ti_once, [], [(assign, "$battle_won", 0),
                           (assign, "$defender_reinforcement_stage", 0),
                           (assign, "$attacker_reinforcement_stage", 0),
                           (assign, "$g_presentation_battle_active", 0),
                           (try_begin),
                             (eq, "$g_mt_mode", vba_after_training),
                             (add_reinforcements_to_entry, 1, 6),
                           (else_try),
                             (add_reinforcements_to_entry, 1, 29),
                           (try_end),
                           (call_script, "script_combat_music_set_situation_with_culture"),
                           ]),

      common_music_situation_update,
      common_battle_check_friendly_kills,
      common_battle_check_victory_condition,
      common_battle_victory_display,

      (1, 4, ti_once, [(main_hero_fallen)],
          [
              (assign, "$pin_player_fallen", 1),
#SoD              (str_store_string, s5, "str_retreat"),
#SoD              (call_script, "script_simulate_retreat", 10, 20),
#SoD              (assign, "$g_battle_result", -1),
#SoD              (set_mission_result, -1),
#SoD              (call_script, "script_count_mission_casualties_from_agents"),
#SoD              (finish_mission, 0)
        ]),

      common_battle_inventory,
      common_battle_order_panel,
      common_battle_order_panel_tick,

      camera_trigger_1,
      camera_trigger_2,
      camera_trigger_3,
      camera_trigger_4,
      camera_trigger_5,
      camera_trigger_6,
      camera_trigger_7,
      camera_trigger_8,

      formations_init,
      formations_0,
      formations_1,
      formations_2,
      formations_3,
      formations_j,
      formations_p,
      formations_k,
      formations_u,
      formations_ai_end,
      formations_ai_dismount,
      formations_end,
      formations_dismount,
      formations_move_infantry,
      formations_move_archers,
      formations_move_cavalry,
      formations_update_ai_infantry,
      formations_update_ai_archers,
      formations_update_ai_cavalry,
      formations_update_ally_infantry,
      formations_update_ally_archers,
      formations_update_ally_cavalry,
      formations_init_kill_count,
      formations_update_kill_count,
      formations_t,
      formations_rally,
      formations_start_coherence,
      formations_update_morale,
      formations_update_route,
    ],
  ),
]
