MENUS = [
("center_public_health_report", mnf_enable_hot_keys,
   "{s98}",
   "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),
      (str_clear, s98),
      (assign, "$g_sod_public_health_report_target", -1),
      (call_script, "script_sod_center_public_health_find_player_target"),
      (assign, "$g_sod_public_health_report_target", reg0),
      (assign, ":target_need", reg1),
      (assign, ":first", 1),
      (call_script, "script_get_number_of_hero_centers", "trp_player"),
      (assign, ":no_centers", reg0),
      (try_begin),
        (gt, ":no_centers", 0),
        (try_for_range, ":i_center", 0, ":no_centers"),
          (call_script, "script_troop_get_leaded_center_with_index", "trp_player", ":i_center"),
          (assign, ":center_no", reg0),
          (str_store_party_name, s1, ":center_no"),
          (call_script, "script_sod_center_public_health_describe_to_s0", ":center_no"),
          (str_store_string_reg, s68, s0),
          (try_begin),
            (eq, ":first", 1),
            (str_store_string, s98, "@{s1}: {s68}"),
            (assign, ":first", 0),
          (else_try),
            (str_store_string_reg, s97, s98),
            (str_store_string, s98, "@{s97}^^{s1}: {s68}"),
          (try_end),
        (try_end),
        (try_begin),
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (str_store_party_name, s7, "$g_sod_public_health_report_target"),
          (assign, reg7, ":target_need"),
          (str_store_string_reg, s97, s98),
          (str_store_string, s98, "@Public Health Report:^^Most urgent fief: {s7}. Need score {reg7}.^^{s97}"),
        (else_try),
          (str_store_string_reg, s97, s98),
          (str_store_string, s98, "@Public Health Report:^^No urgent fief target could be found.^^{s97}"),
        (try_end),
      (else_try),
        (str_store_string, s98, "@Public Health Report:^^You do not personally hold any fiefs."),
      (try_end),
    ],
    [
      ("public_health_fund_healers",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 1200),
        ],
        "Fund healers for the neediest fief. (1200 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 1200),
          (val_add, "$g_sod_weekly_construction", 1200),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_fund_healers),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_distribute_grain",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 800),
        ],
        "Distribute grain to the neediest fief. (800 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 800),
          (val_add, "$g_sod_weekly_construction", 800),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_distribute_grain),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_clean_wells",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 600),
        ],
        "Clean wells and streets in the neediest fief. (600 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 600),
          (val_add, "$g_sod_weekly_construction", 600),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_clean_wells),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_repair_water",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 1500),
        ],
        "Repair water systems and infirmary works. (1500 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 1500),
          (val_add, "$g_sod_weekly_construction", 1500),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_repair_water),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_quarantine",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (neg|party_slot_ge, "$g_sod_public_health_report_target", slot_center_health_quarantine, 1),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 300),
        ],
        "Establish quarantine in the neediest fief. (300 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 300),
          (val_add, "$g_sod_weekly_construction", 300),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_establish_quarantine),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_lift_quarantine",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (party_slot_ge, "$g_sod_public_health_report_target", slot_center_health_quarantine, 1),
        ],
        "Lift quarantine in the neediest fief.",
        [
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_lift_quarantine),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_shelter_refugees",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 700),
        ],
        "Shelter refugees and sick travelers. (700 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 700),
          (val_add, "$g_sod_weekly_construction", 700),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_shelter_refugees),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_move_refugees",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (party_slot_ge, "$g_sod_public_health_report_target", slot_center_health_refugee_pressure, 1),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 500),
        ],
        "Move refugees onward under guarded road writs. (500 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 500),
          (val_add, "$g_sod_weekly_construction", 500),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_move_refugees),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_temple_aid",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 900),
        ],
        "Request temple, shrine, or monastery aid. (900 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 900),
          (val_add, "$g_sod_weekly_construction", 900),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_request_temple_aid),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_medicine_shipment",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 1800),
        ],
        "Sponsor a medicine shipment. (1800 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 1800),
          (val_add, "$g_sod_weekly_construction", 1800),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_medicine_shipment),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_grain_shipment",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 1400),
        ],
        "Sponsor a grain shipment. (1400 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 1400),
          (val_add, "$g_sod_weekly_construction", 1400),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_grain_shipment),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_burial_cleanup",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
          (store_troop_gold, ":gold", "trp_player"),
          (ge, ":gold", 1000),
        ],
        "Pay for burial and cleanup. (1000 denars)",
        [
          (call_script, "script_sod_player_charge_gold", 1000),
          (val_add, "$g_sod_weekly_construction", 1000),
          (call_script, "script_sod_center_public_health_apply_intervention", "$g_sod_public_health_report_target", sod_public_health_intervention_burial_cleanup),
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("public_health_orders_today",
        [
          (is_between, "$g_sod_public_health_report_target", centers_begin, centers_end),
          (neg|call_script, "script_cf_sod_center_public_health_can_order_intervention", "$g_sod_public_health_report_target"),
        ],
        "Orders are already in motion for the neediest fief today.",
        [
          (jump_to_menu, "mnu_center_public_health_report"),
        ]),
      ("continue", [], "Continue...", [(jump_to_menu, "mnu_fief_reports")]),
    ]
  ),
]
