PRESENTATIONS = [
("sod_fief_management",0,0,[
      (ti_on_presentation_load,
       [(set_fixed_point_multiplier, 1000),
	   (call_script, "script_clear_presentation_obj"),
	   (try_begin),
         (eq, "$g_sod_debug", 1),
         (create_text_overlay, "$g_little_pos_helper", "@00,00"),
         (overlay_set_color, "$g_little_pos_helper", white),
         (position_set_x, pos1, 10),
         (position_set_y, pos1, 700),
         (overlay_set_position, "$g_little_pos_helper", pos1),
      (try_end),
		#DISPLAY BACGROUND ####################################################################
		(create_mesh_overlay, reg1, "mesh_sod_fief_mesh_background"),
        (position_set_x, pos1, 0),
        (position_set_y, pos1, 0),
        (overlay_set_position, reg1, pos1),
		#DISPLAY Kingdom INFORMATION ####################################################################
		#Player name & Title
			#Name
		(create_text_overlay, reg1, "@{playername}", tf_center_justify),	
		(position_set_x, pos1, 860),
        (position_set_y, pos1, 670),
        (overlay_set_position, reg1, pos1),
		(try_begin),
			(troop_get_slot, ":title", "trp_player", slot_troop_title),
			(gt,":title", 0),
			(str_store_string, s27, ":title"),
			(call_script, "script_get_best_fief_name_of_troop", s17, "trp_player"),
			(create_text_overlay, reg1, "@{s27}{s17}", tf_center_justify),	
			(position_set_x, pos1, 850),
			(position_set_y, pos1, 650),
			(overlay_set_position, reg1, pos1),
			(position_set_x, pos1, 200),
			(position_set_y, pos1, 20),
			(overlay_set_area_size, reg1, pos1),
		(try_end),
		
		################relations with clergy
		(create_text_overlay, reg1, "@Relations with Clergy"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 630),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(assign, reg14, "$g_sod_clergy_happines"),
		(create_text_overlay, reg1, "@{reg14}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 630),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		################relations with nobles
		(create_text_overlay, reg1, "@Relations with Nobles"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 610),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(assign, reg14, "$g_sod_nobles_happines"),
		(create_text_overlay, reg1, "@{reg14}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 610),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
#############################################################
		#Overview
		(create_text_overlay, reg1, "@Kingdom Overview", tf_center_justify),	
		(position_set_x, pos1, 850),
		(position_set_y, pos1, 570),
		(overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 200),
		(position_set_y, pos1, 20),
		(overlay_set_area_size, reg1, pos1),
	
		#Number of Towns
		(create_text_overlay, reg1, "@Towns"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 550),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		(assign, ":count", 0),
		(try_for_range, ":center_no", centers_begin, centers_end),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(party_slot_eq, ":center_no", slot_party_type, spt_town),
			(val_add, ":count", 1),
		(try_end),
		(assign, reg14, ":count"),
		(create_text_overlay, reg1, "@{reg14}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 550),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		#Number of Castles
		(create_text_overlay, reg1, "@Castles"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 530),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		(assign, ":count", 0),
		(try_for_range, ":center_no", centers_begin, centers_end),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(party_slot_eq, ":center_no", slot_party_type, spt_castle), #twan456
			(val_add, ":count", 1),
		(try_end),
		(assign, reg14, ":count"),
		(create_text_overlay, reg1, "@{reg14}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 530),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		#Number of Villages
		(create_text_overlay, reg1, "@Villages"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 510),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		(assign, ":count", 0),
		(try_for_range, ":center_no", centers_begin, centers_end),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(party_slot_eq, ":center_no", slot_party_type, spt_village), #twan456
			(val_add, ":count", 1),
		(try_end),
		(assign, reg14, ":count"),
		(create_text_overlay, reg1, "@{reg14}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 510),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		
		(create_text_overlay, reg1, "@Administration", tf_center_justify),	
		(position_set_x, pos1, 850),
		(position_set_y, pos1, 470),
		(overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 200),
		(position_set_y, pos1, 20),
		(overlay_set_area_size, reg1, pos1),
		
		#Demesne Points
		(create_text_overlay, reg1, "@Demesne Points"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 450),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		(call_script, "script_get_player_administration_multiplier"),
		(create_text_overlay, reg1, "@{reg51}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 450),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		#Demesne Size
		(create_text_overlay, reg1, "@Demesne Size"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 430),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		(call_script, "script_get_player_administration_multiplier"),
		(create_text_overlay, reg1, "@{reg52}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 430),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		#Tax effectiveness
		(create_text_overlay, reg1, "@Tax Efficiency"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 410),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		(call_script, "script_get_player_administration_multiplier"),
		(val_add, reg0, 100),
		(create_text_overlay, reg1, "@{reg0}%", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 410),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		#Propaganda Points
		(create_text_overlay, reg1, "@Propaganda Points"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 390),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(call_script, "script_get_player_propaganda"),
		(create_text_overlay, reg1, "@{reg0}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 390),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		(create_text_overlay, reg1, "@Weekly Relations"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 370),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(call_script, "script_get_player_propaganda"),
		(create_text_overlay, reg1, "@{reg52}", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 370),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		
		###############LAW MODIFIERS ###########################################################
		(create_text_overlay, reg1, "@Edict Modifiers", tf_center_justify),	
		(position_set_x, pos1, 860),
        (position_set_y, pos1, 330),
        (overlay_set_position, reg1, pos1),
		################Tax peasants
		(create_text_overlay, reg1, "@Taxation - Villages"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 310),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(assign, reg14, "$g_sod_tax_peasants"),
		(create_text_overlay, reg1, "@{reg14}%", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 310),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		################Tax townspeople
		(create_text_overlay, reg1, "@Taxation - Towns"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 290),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(assign, reg14, "$g_sod_tax_townspeople"),
		(create_text_overlay, reg1, "@{reg14}%", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 290),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		################Village growth
		(create_text_overlay, reg1, "@Growth - Villages"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 270),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(assign, reg14, "$g_sod_village_population_modifier"),
		(create_text_overlay, reg1, "@{reg14}%", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 270),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		################Town growth
		(create_text_overlay, reg1, "@Growth - Towns"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 250),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(assign, reg14, "$g_sod_town_population_modifier"),
		(create_text_overlay, reg1, "@{reg14}%", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 250),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		################royal tribute
		(create_text_overlay, reg1, "@Royal tribute"),	
		(position_set_x, pos1, 755),
        (position_set_y, pos1, 230),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),

		(assign, reg15, "$g_sod_tax_nobles"),
		(create_text_overlay, reg1, "@{reg15}%", tf_left_align),	
		(position_set_x, pos1, 923),
        (position_set_y, pos1, 230),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		

		#FIEF TYPE TOWN CASTLE VILLAGE ####################################################################
		(create_game_button_overlay, "$g_presentation_obj_1", "@Town", tf_center_justify),
		(position_set_x, pos1, 390),
        (position_set_y, pos1, 650),
        (overlay_set_position, "$g_presentation_obj_1", pos1),
		(position_set_x, pos1, 100),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$g_presentation_obj_1", pos1),
		(create_game_button_overlay, "$g_presentation_obj_2", "@Castle", tf_center_justify),
		(position_set_x, pos1, 520),
        (position_set_y, pos1, 650),
        (overlay_set_position, "$g_presentation_obj_2", pos1),
		(position_set_x, pos1, 100),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$g_presentation_obj_2", pos1),
		(create_game_button_overlay, "$g_presentation_obj_3", "@Village", tf_center_justify),
		(position_set_x, pos1, 650),
        (position_set_y, pos1, 650),
        (overlay_set_position, "$g_presentation_obj_3", pos1),
		(position_set_x, pos1, 100),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$g_presentation_obj_3", pos1),
		#FIEF SLIDER ####################################################################
		(assign, ":fief_count", 0),
		(try_for_range, ":slot", 0, 300),
			(troop_set_slot, "trp_fief", ":slot", 0),
		(try_end),
		(try_for_range, ":cur_fief", centers_begin, centers_end),
			(party_slot_eq, ":cur_fief", slot_town_lord, "trp_player"),
			(party_slot_eq, ":cur_fief", slot_party_type, "$pres_sod_fief_type"),
			(troop_set_slot, "trp_fief", ":fief_count", ":cur_fief"),
			(val_add, ":fief_count", 1),
		(try_end),
		(assign, "$pres_sod_fief_slider_fiefnumber", -1),
		(store_add, ":slider_max", ":fief_count", 1),
		(val_clamp, "$pres_sod_fief_slider_value", 1, ":slider_max"),
		(store_sub, ":fief_index", "$pres_sod_fief_slider_value", 1),
		(troop_get_slot, "$pres_sod_fief_selected", "trp_fief", ":fief_index"),
		(try_begin),
			(gt, ":fief_count", 1),
			(create_slider_overlay, "$pres_sod_fief_slider_fiefnumber", 1, ":fief_count"),
			(overlay_set_val, "$pres_sod_fief_slider_fiefnumber", "$pres_sod_fief_slider_value"),
			(create_text_overlay, "$pres_sod_fief_slider_fiefnumber_txt", "@Choose Fief", tf_center_justify),		
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 570),
			(overlay_set_position, "$pres_sod_fief_slider_fiefnumber", pos1),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 600),
			(overlay_set_position, "$pres_sod_fief_slider_fiefnumber_txt", pos1),
		#FIEF SLIDER + - ####################################################################
			(create_game_button_overlay, "$g_presentation_obj_4", "@<", tf_center_justify),
			(position_set_x, pos1, 720),
			(position_set_y, pos1, 570),
			(overlay_set_position, "$g_presentation_obj_4", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_4", pos1),
			(create_game_button_overlay, "$g_presentation_obj_5", "@>", tf_center_justify),
			(position_set_x, pos1, 400),
			(position_set_y, pos1, 570),
			(overlay_set_position, "$g_presentation_obj_5", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_5", pos1),
		(try_end),
		#DISPLAY FIEF NAME ####################################################################
		(str_store_party_name, s1, "$pres_sod_fief_selected"),
		(create_text_overlay, "$pres_sod_fief_name_txt", s1, tf_center_justify),	
		(position_set_x, pos1, 150),
        (position_set_y, pos1, 670),
        (overlay_set_position, "$pres_sod_fief_name_txt", pos1),
		#DISPLAY FIEF GRAPHIC ####################################################################
		(create_mesh_overlay_with_tableau_material, reg1, -1, "tableau_center_note_mesh", "$pres_sod_fief_selected"),
			(try_begin),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_town),
				(position_set_x, pos1, 48),
				(position_set_y, pos1, 489),
				(overlay_set_position, reg1, pos1),
				(position_set_x, pos1, 1000),
				(position_set_y, pos1, 800),
			(else_try),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_castle),
				(position_set_x, pos1, 6),
				(position_set_y, pos1, 439),
				(overlay_set_position, reg1, pos1),
				(position_set_x, pos1, 1400),
				(position_set_y, pos1, 1000),
			(else_try),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_village),
				(position_set_x, pos1, 1),
				(position_set_y, pos1, 429),
				(overlay_set_position, reg1, pos1),
				(position_set_x, pos1, 1500),
				(position_set_y, pos1, 1100),
			(try_end),
        (overlay_set_size, reg1, pos1),
		#DISPLAY FIEF DESCRIPTION ####################################################################
		(try_begin),
			(this_or_next|eq, "$pres_sod_fief_info", 0),
			(eq, "$pres_sod_fief_info", 1),
		(str_clear, s7),
		(str_clear, s10),
		(str_clear, s11),
		(str_clear, s15),
		(str_clear, s16),
		(str_clear, s17),
		(str_clear, s3),
		(try_begin),
			(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_village),
			(str_store_party_name, s2, "$pres_sod_fief_selected"),
			(party_get_slot, ":center_lord", "$pres_sod_fief_selected", slot_town_lord),
			(store_faction_of_party, ":center_faction", "$pres_sod_fief_selected"),
			(str_store_faction_name, s9, ":center_faction"),
			(call_script, "script_describe_current_project", s20, "$pres_sod_fief_selected"),
			(party_get_slot, reg13, "$pres_sod_fief_selected", slot_center_sod_local_population),
			(party_get_slot, ":center_health", "$pres_sod_fief_selected", slot_center_sod_local_health),
			(call_script, "script_describe_center_health", s16, ":center_health"),
			(party_get_slot, ":faith", "$pres_sod_fief_selected", slot_center_sod_local_faith),
			(call_script, "script_describe_center_faith", s15, ":faith"),
			(try_begin),
			  (ge, ":center_lord", 0),
			  (call_script, "script_store_troop_name_fief", s7, ":center_lord"),
			(try_end),
			(str_clear, s10),
			(str_store_party_name, s60, "$pres_sod_fief_selected"),
			(party_get_slot, ":prosperity", "$pres_sod_fief_selected", slot_town_prosperity),
			(val_add, ":prosperity", 5),
            (store_div, ":str_offset", ":prosperity", 10),
			(val_clamp, ":str_offset", 0, 11), # BUG FIX: don't allow us to go beyond the range of messges (best is best, no further to go)
            (store_add, ":str_id", "str_village_prosperity_0",  ":str_offset"),
            (str_store_string, s10, ":str_id"),
			(str_clear, s11),
			(try_begin),
			  (party_slot_eq, "$pres_sod_fief_selected", slot_village_state, svs_looted),
			(else_try),
			  (eq, ":center_lord", "trp_player"),
			  (str_store_string, s11, "@ This village and the surrounding lands belong to you."),
			(else_try),
			  (ge, ":center_lord", 0),
			  (str_store_string, s11, "@ You remember that this village and the surrounding lands belong to {s7}."),
			(else_try),
			  (str_store_string, s11, "@ These lands belong to no one."),
			(try_end),
			(str_store_string, s17, "@ {s2} has population of {reg13} taxpayers. "),
			(str_clear, s7),
			(try_begin),
			  (neg|party_slot_eq, "$pres_sod_fief_selected", slot_village_state, svs_looted),
			  (party_get_slot, ":center_relation", "$pres_sod_fief_selected", slot_center_player_relation),
			  (call_script, "script_describe_center_relation", s3, ":center_relation"),
			  (str_store_string, s7, "@{s3}. "),
			(try_end),
			(create_text_overlay, reg1, "@{s10}{s11}{s17}{s15}{s16}{s7}^{s20}", tf_center_justify|tf_scrollable),
		(else_try),
			(party_get_slot, ":center_lord", "$pres_sod_fief_selected", slot_town_lord),
			
			  (str_store_party_name, s2, "$pres_sod_fief_selected"),
			  (party_get_slot, ":center_lord", "$pres_sod_fief_selected", slot_town_lord),
			  (store_faction_of_party, ":center_faction", "$pres_sod_fief_selected"),
			  (str_store_faction_name, s9, ":center_faction"),
		
			  (try_begin),
				#MORDACHAI - castles don't have a real civlian population - so we don't track health or faith there
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_town),
				(party_get_slot, reg13, "$pres_sod_fief_selected", slot_center_sod_local_population),
				(party_get_slot, ":center_health", "$pres_sod_fief_selected", slot_center_sod_local_health),
				(call_script, "script_describe_center_health", s16, ":center_health"),
				(party_get_slot, ":faith", "$pres_sod_fief_selected", slot_center_sod_local_faith),
				(call_script, "script_describe_center_faith", s15, ":faith"),
			  (else_try),
				(str_clear, s15),
				(str_clear, s16),
			  (try_end),
		
			  

			  (try_begin),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_town),
				(str_store_party_name, s60, "$pres_sod_fief_selected"),
			(party_get_slot, ":prosperity", "$pres_sod_fief_selected", slot_town_prosperity),
			(val_add, ":prosperity", 5),
            (store_div, ":str_offset", ":prosperity", 10),
			(val_clamp, ":str_offset", 0, 11), # BUG FIX: don't allow us to go beyond the range of messges (best is best, no further to go)
            (store_add, ":str_id", "str_town_prosperity_0",  ":str_offset"),
            (str_store_string, s10, ":str_id"),
			  (else_try),
				(str_store_string, s10, "@You are at {s2}. "),
			  (try_end),
			
			(try_begin),
				(ge, ":center_lord", 0),
				(call_script, "script_store_troop_name", s8, ":center_lord"),
				(str_store_string, s7, "@{s8} of {s9}"), #MORDACHAI - better without the .
			  (try_end),
			  
			(try_begin),
			(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_castle),
			(try_begin),
			  (eq, ":center_lord", "trp_player"),
			  (str_store_string, s11, "@ This castle belongs to you. "),
			(else_try),
			  (ge, ":center_lord", 0),
			  (str_store_string, s11, "@ This castle belongs to {s7}. "),
			(else_try),
			  (str_store_string, s11, "@ This castle seems to belong to no one. "),
			(try_end),
		  (else_try),
			(try_begin),
			  (eq, ":center_lord", "trp_player"),
			  (str_store_string, s11, "@ This town belongs to you. "),
			(else_try),
			  (ge, ":center_lord", 0),
			  (str_store_string, s11, "@ This town belongs to {s7}. "),
			(else_try),
			  (str_store_string, s11, "@ The townsfolk here have declared their independence. "), #not usefull here at the moment but maybe in future...
			(try_end),
			(str_store_string, s17, "@{s2} has a population of {reg13} taxpayers. "),
		  (try_end),
			(party_collect_attachments_to_party, "$pres_sod_fief_selected", "p_collective_ally"),
			(party_get_num_companions, reg7, "p_collective_ally"),
			  (str_clear, s3),
			  (try_begin),
				(eq, reg7, 0),
				(try_begin),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_castle),
				(str_store_string, s9, "str_castle_is_abondened"),
				(else_try),
				(str_store_string, s9, "str_town_is_abondened"),
				(try_end),
			  (else_try),
				(str_store_string, s9, "@{reg7} troops are garrisoning here."),
			  (try_end),
			(call_script, "script_describe_current_project", s20, "$pres_sod_fief_selected"),
			
				(str_clear, s12),
		  (try_begin),
			(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_town),
			(party_get_slot, ":center_relation", "$pres_sod_fief_selected", slot_center_player_relation),
			(call_script, "script_describe_center_relation", s3, ":center_relation"),
			(str_store_string, s12, "@{s3}. "),
		  (try_end),
			
			(create_text_overlay, reg1, "@{s10}{s11}{s17}{s15}{s16}{s12}{s9}^^{s20}", tf_center_justify|tf_scrollable),
		(try_end),
        (position_set_x, pos1, 50),
        (position_set_y, pos1, 310),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 630),
        (position_set_y, pos1, 110),
        (overlay_set_area_size, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		(try_end),
		#DISPLAY CONSTRUCTION BUTTON ####################################################################
		(create_game_button_overlay, "$g_presentation_obj_6", "@Construction", tf_center_justify),
        (position_set_x, pos1, 390),
        (position_set_y, pos1, 500),
        (overlay_set_position, "$g_presentation_obj_6", pos1),
		(position_set_x, pos1, 130),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$g_presentation_obj_6", pos1),
		#DISPLAY CONSTRUCTION INFORMATION #############################################################
		(try_begin),
		(eq, "$pres_sod_fief_info", 1),
			  (assign, ":num_improvements", 0),
			  (str_clear, s21),
			  (str_clear, s22),
			  (str_clear, s24),
			  (str_clear, s4),
			  (try_begin),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_village),
				(assign, ":buf", "trp_village"),
				(str_store_string, s21, "@village"),
			  (else_try),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_town),
				(assign, ":buf", "trp_town"),
				(str_store_string, s21, "@town"),
			  (else_try),
				(assign, ":buf", "trp_castle"),
				(str_store_string, s21, "@castle"),
			  (try_end),

			  (troop_get_slot, ":count", ":buf", 0),
			  (val_add, ":count", 1),
			  (try_for_range, ":improvement_no", 1, ":count"),
				(troop_get_slot, ":improvement", ":buf", ":improvement_no"),
				(party_slot_eq, "$pres_sod_fief_selected", ":improvement", 1),
				(val_add, ":num_improvements", 1),
				(call_script, "script_get_improvement_details", ":improvement"),
				(try_begin),
				  (eq, ":num_improvements", 1),
				  (str_store_string, s22, "@{s0}"),
				(else_try),
				  (str_store_string, s22, "@{s22}, {s0}"),
				(try_end),
			  (try_end),

			  (try_begin),
				(eq, ":num_improvements", 0),
			    (str_store_string, s24, "@The {s21} has no improvements."),
			  (else_try),
				(str_store_string, s24, "@The {s21} has the following improvements:^^{s22}."),
			  (try_end),

			  (assign, reg6, 0),
			  (try_begin),
				(party_get_slot, ":cur_improvement", "$pres_sod_fief_selected", slot_center_current_improvement),
				(gt, ":cur_improvement", 0),
				(call_script, "script_get_improvement_details", ":cur_improvement"),
				(str_store_string, s4, s0),
				(assign, reg6, 1),
				(store_current_hours, ":cur_hours"),
				(party_get_slot, ":finish_time", "$pres_sod_fief_selected", slot_center_improvement_end_hour),
				(val_sub, ":finish_time", ":cur_hours"),
				(store_div, reg8, ":finish_time", 24),
				(val_max, reg8, 1),
				(store_sub, reg9, reg8, 1),
			  (try_end),
		
		# (create_text_overlay, reg1, "@{s24}^{reg6?^You are currently building {s4}, which should be completed after {reg8} day{reg9?s:}.:}", tf_center_justify|tf_scrollable),
		(create_text_overlay, reg1, s24, tf_center_justify|tf_scrollable),
		(position_set_x, pos1, 50),
        (position_set_y, pos1, 240),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 630),
        (position_set_y, pos1, 70),
        (overlay_set_area_size, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		(try_end),
		#BUILDINGS SLIDER ####################################################################
		#First set slider options
		(try_begin),
		(eq, "$pres_sod_fief_info", 1),
		(assign, ":num_improvements", 0),
			(try_begin),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_village),
				(troop_get_slot, "$pres_sod_fief_buildings", "trp_village", 0),
				(troop_get_slot, "$pres_sod_fief_selected_building", "trp_village", "$pres_sod_fief_buildings_value"),
				(call_script, "script_get_improvement_details", "$pres_sod_fief_selected_building"),
				(str_store_string, s35, s0),
			(else_try),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_town),
				(troop_get_slot, "$pres_sod_fief_buildings", "trp_town", 0),
				(troop_get_slot, "$pres_sod_fief_selected_building", "trp_town", "$pres_sod_fief_buildings_value"),
				(call_script, "script_get_improvement_details", "$pres_sod_fief_selected_building"),
				(str_store_string, s35, s0),
			(else_try),
				(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_castle),
				(troop_get_slot, "$pres_sod_fief_buildings", "trp_castle", 0),
				(troop_get_slot, "$pres_sod_fief_selected_building", "trp_castle", "$pres_sod_fief_buildings_value"),
				(call_script, "script_get_improvement_details", "$pres_sod_fief_selected_building"),
				(str_store_string, s35, s0),
			(try_end),
		
        (create_slider_overlay, "$g_presentation_obj_7", 1, "$pres_sod_fief_buildings"),
		(overlay_set_val, "$g_presentation_obj_7", "$pres_sod_fief_buildings_value"),
		(position_set_x, pos1, 360),
        (position_set_y, pos1, 220),
        (overlay_set_position, "$g_presentation_obj_7", pos1),
		(create_text_overlay, reg1, "@{s35}", tf_center_justify),
		(position_set_x, pos1, 360),
		(position_set_y, pos1, 190),
        (overlay_set_position, reg1, pos1),
		
		(try_end),
		#BUILDING DESCRIPTION ##################################################################
		(try_begin),
		(eq, "$pres_sod_fief_info", 1),		
		
			  (call_script, "script_get_improvement_details", "$pres_sod_fief_selected_building"),
			  (assign, ":improvement_cost", reg0),
			  (str_store_string, s34, s0),
			  (str_store_string, s39, s1),
			  (str_clear, s40),
			  (call_script, "script_validate_construction_choice", "$pres_sod_fief_selected", "$pres_sod_fief_selected_building"),
			  (assign, ":validation_code", reg1),
			  (assign, ":validation_blocking_slot", reg2),
			  (try_begin),
			    (eq, ":validation_code", 0),
			    (str_store_string, s40, "@This improvement can be started now."),
			  (else_try),
			    (eq, ":validation_code", 6),
			    (call_script, "script_get_building_display_name", ":validation_blocking_slot"),
			    (str_store_string, s40, "@Upgrade available from {s0}."),
			  (else_try),
			    (eq, ":validation_code", 3),
			    (call_script, "script_get_building_display_name", ":validation_blocking_slot"),
			    (str_store_string, s40, "@Already built: {s0}."),
			  (else_try),
			    (eq, ":validation_code", 4),
			    (call_script, "script_get_building_display_name", ":validation_blocking_slot"),
			    (str_store_string, s40, "@Missing prerequisite: {s0}."),
			  (else_try),
			    (eq, ":validation_code", 5),
			    (call_script, "script_get_building_display_name", ":validation_blocking_slot"),
			    (str_store_string, s40, "@Conflicts with existing improvement: {s0}."),
			  (else_try),
			    (eq, ":validation_code", 7),
			    (str_store_string, s40, "@This improvement is locked by faction ownership."),
			  (else_try),
			    (eq, ":validation_code", 2),
			    (str_store_string, s40, "@This improvement is for a different center type."),
			  (else_try),
			    (str_store_string, s40, "@This improvement is unavailable right now."),
			  (try_end),
			  (call_script, "script_get_max_skill_of_player_party", "skl_engineer"),
			  (assign, ":max_skill", reg0),
			  (assign, ":max_skill_owner", reg1),
			  (assign, reg2, ":max_skill"),

			  (store_sub, ":multiplier", 12, ":max_skill"),
			  (val_mul, ":improvement_cost", ":multiplier"),
			  (val_div, ":improvement_cost", 10),
			  (store_div, ":improvement_time", ":improvement_cost", 200),

			  (val_max, ":improvement_time", 0),

			  (assign, reg5, ":improvement_cost"),
			  (assign, reg10, ":improvement_time"),
			  (store_troop_gold, reg7, "trp_player"),

			  (try_begin),
				(eq, ":max_skill_owner", "trp_player"),
				(assign, reg3, 1),
			  (else_try),
				(assign, reg3, 0),
				(call_script, "script_store_troop_name", s33, ":max_skill_owner"),
			  (try_end),
		
		(create_text_overlay, reg1, "@{s39} As the party member with the highest engineer skill ({reg2}), {reg3?you reckon:{s33} reckons} that building the {s34} will take {reg10} days, and cost {reg5} denars.  You currently have {reg7} denars.^^{s40}", tf_center_justify|tf_scrollable),
        (position_set_x, pos1, 50),
        (position_set_y, pos1, 100),
        (overlay_set_position, reg1, pos1),
		(position_set_x, pos1, 630),
        (position_set_y, pos1, 80),
        (overlay_set_area_size, reg1, pos1),
		(position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
		
		(try_end),
		#BUILDINGS SLIDER + - ####################################################################
		(try_begin),
		(eq, "$pres_sod_fief_info", 1),
		(create_game_button_overlay, "$g_presentation_obj_8", "@<", tf_center_justify),
		(position_set_x, pos1, 580),
        (position_set_y, pos1, 220),
        (overlay_set_position, "$g_presentation_obj_8", pos1),
		(position_set_x, pos1, 30),
        (position_set_y, pos1, 30),
        (overlay_set_size, "$g_presentation_obj_8", pos1),
		(create_game_button_overlay, "$g_presentation_obj_9", "@>", tf_center_justify),
		(position_set_x, pos1, 260),
        (position_set_y, pos1, 220),
        (overlay_set_position, "$g_presentation_obj_9", pos1),
		(position_set_x, pos1, 30),
        (position_set_y, pos1, 30),
        (overlay_set_size, "$g_presentation_obj_9", pos1),
		
		(try_end),
# #############################################################################################################################################################
# ###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###GARRISON###
# #############################################################################################################################################################
		(try_begin),
			(eq, "$pres_sod_fief_info", 2),
			
			(party_get_slot, ":soldiers", "$pres_sod_fief_selected", slot_center_garrison_soldiers),
			(party_get_slot, ":ranged", "$pres_sod_fief_selected", slot_center_garrison_ranged),
			(store_add, reg11, ":soldiers", ":ranged"),
	
			(party_get_slot, ":num_trainers", "$pres_sod_fief_selected", slot_center_trainers),
			(assign, reg12, ":num_trainers"),
			(store_mul, reg13, ":num_trainers", 2),
			
			(party_get_slot, reg14, "$pres_sod_fief_selected", slot_center_max_garrison),
	
			(create_text_overlay, "$g_presentation_object_13", "@Max garrison:^{reg14}", tf_center_justify),
			(position_set_x, pos1, 140),
			(position_set_y, pos1, 370),
			(overlay_set_position, "$g_presentation_object_13", pos1),
			(create_game_button_overlay, "$g_presentation_obj_14", "@>", tf_center_justify),
			(position_set_x, pos1, 165),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_14", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_14", pos1),
			(create_game_button_overlay, "$g_presentation_obj_15", "@<", tf_center_justify),
			(position_set_x, pos1, 235),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_15", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_15", pos1),
			(create_text_overlay, "$g_presentation_obj_16", "@Daily garrisoning:^{reg11}/{reg13}", tf_center_justify),
			(position_set_x, pos1, 370),
			(position_set_y, pos1, 370),
			(overlay_set_position, "$g_presentation_obj_16", pos1),
			(create_game_button_overlay, "$g_presentation_obj_17", "@>", tf_center_justify),
			(position_set_x, pos1, 395),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_17", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_17", pos1),
			(create_game_button_overlay, "$g_presentation_obj_18", "@<", tf_center_justify),
			(position_set_x, pos1, 465),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_18", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_18", pos1),
			(create_text_overlay, "$g_presentation_obj_19", "@Trainers:^{reg12}/5", tf_center_justify),
			(position_set_x, pos1, 600),
			(position_set_y, pos1, 370),
			(overlay_set_position, "$g_presentation_obj_19", pos1),
			(create_game_button_overlay, "$g_presentation_obj_20", "@>", tf_center_justify),
			(position_set_x, pos1, 625),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_20", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_20", pos1),
			(create_game_button_overlay, "$g_presentation_obj_21", "@<", tf_center_justify),
			(position_set_x, pos1, 695),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_21", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_21", pos1),
			
			# "?" buttons
			(create_game_button_overlay, "$g_presentation_obj_22", "@?", tf_center_justify),
			(position_set_x, pos1, 200),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_22", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_22", pos1),
			(create_game_button_overlay, "$g_presentation_obj_29", "@?", tf_center_justify),
			(position_set_x, pos1, 430),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_29", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_29", pos1),
			(create_game_button_overlay, "$g_presentation_obj_30", "@?", tf_center_justify),
			(position_set_x, pos1, 660),
			(position_set_y, pos1, 335),
			(overlay_set_position, "$g_presentation_obj_30", pos1),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, 30),
			(overlay_set_size, "$g_presentation_obj_30", pos1),
			
			(try_begin),
				(gt, reg11, 0),
				
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks1, 1),
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks2, 1),
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks3, 1),
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks4, 1),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks5, 1),
				
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 1),
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range2, 1),
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range3, 1),
				# (this_or_next|party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range4, 1),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range5, 1),
				
				(position_set_x, pos1, 200),
				(position_set_y, pos1, 190),
				(assign, reg15, ":soldiers"),
				(create_text_overlay, "$g_presentation_object_23", "@Foot Soldiers^^^{reg15}", tf_center_justify),
				(overlay_set_position, "$g_presentation_object_23", pos1),
				(position_set_x, pos1, 520),
				(position_set_y, pos1, 190),
				(assign, reg16, ":ranged"),
				(create_text_overlay, "$g_presentation_object_24", "@Ranged Infantry^^^{reg16}", tf_center_justify),
				(overlay_set_position, "$g_presentation_object_24", pos1),
				(position_set_x, pos1, 360),
				(position_set_y, pos1, 220),
				(create_slider_overlay, "$g_presentation_object_25", 0, reg11),
				(overlay_set_position, "$g_presentation_object_25", pos1),
				(overlay_set_val, "$g_presentation_object_25", reg16),
				
				(create_game_button_overlay, "$g_presentation_obj_27", "@<", tf_center_justify),
				(position_set_x, pos1, 580),
				(position_set_y, pos1, 220),
				(overlay_set_position, "$g_presentation_obj_27", pos1),
				(position_set_x, pos1, 30),
				(position_set_y, pos1, 30),
        		(overlay_set_size, "$g_presentation_obj_27", pos1),
				(create_game_button_overlay, "$g_presentation_obj_28", "@>", tf_center_justify),
				(position_set_x, pos1, 260),
				(position_set_y, pos1, 220),
        		(overlay_set_position, "$g_presentation_obj_28", pos1),
				(position_set_x, pos1, 30),
        		(position_set_y, pos1, 30),
        		(overlay_set_size, "$g_presentation_obj_28", pos1),
			# (else_try),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks2, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks3, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks4, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks5, 0),
				
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				
				# (position_set_x, pos1, 370),
				# (position_set_y, pos1, 220),
				# (create_text_overlay, "$g_presentation_object_26", "@Garrisoning impossible.^Center does not have any facilities to train and upgrade recruits.", tf_center_justify),
				# (overlay_set_position, "$g_presentation_object_26", pos1),
			# (else_try),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks2, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks3, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks4, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks5, 0),
				
				# (position_set_x, pos1, 370),
				# (position_set_y, pos1, 220),
				# (create_text_overlay, "$g_presentation_object_26", "@Garrisoning ranged infantry only.^Center does not have barracks to train and upgrade foot soldiers.", tf_center_justify),
				# (overlay_set_position, "$g_presentation_object_26", pos1),
			# (else_try),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				# (party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range1, 0),
				
				# (position_set_x, pos1, 370),
				# (position_set_y, pos1, 220),
				# (create_text_overlay, "$g_presentation_object_26", "@Garrisoning foot soldiers only.^Center does not have practice range to train and upgrade ranged infantry.", tf_center_justify),
				# (overlay_set_position, "$g_presentation_object_26", pos1),
			(else_try),
				(position_set_x, pos1, 370),
				(position_set_y, pos1, 220),
				(create_text_overlay, "$g_presentation_object_26", "@No garrisoning orders", tf_center_justify),
				(overlay_set_position, "$g_presentation_object_26", pos1),
			(try_end),
			
			(try_begin),
			(eq, "$pres_sod_fief_info", 2),
			(ge, "$pres_sod_garrison_tip", 1),
			
			(try_begin),
				(eq, "$pres_sod_garrison_tip", 1),
				(str_store_string, s1, "@Set garrison limit. Trainers won't recruit more men to this castle if it's max garrison limit is reached or exceeded."),
			(else_try),
				(eq, "$pres_sod_garrison_tip", 2),
				(str_store_string, s1, "@Set how much men can this castle's trainers recruit daily. To start garrisoning you need barracks or practice range."),
			(else_try),
				(eq, "$pres_sod_garrison_tip", 3),
				(str_store_string, s1, "@Set this castle's trainers amount. Hiring one trainer cost 50 denars and then another 50 denars weekly wage. Trainers are needed to garrison and train recruits."),
			(try_end),
			
			(create_text_overlay, reg1, "@{s1}", tf_center_justify|tf_scrollable),
			(position_set_x, pos1, 50),
			(position_set_y, pos1, 100),
			(overlay_set_position, reg1, pos1),
			(position_set_x, pos1, 630),
			(position_set_y, pos1, 80),
			(overlay_set_area_size, reg1, pos1),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 900),
			(overlay_set_size, reg1, pos1),
			
			(try_end),
			
		(try_end),
		
		#DISPLAY BUILD BUTTON ####################################################################
		(try_begin),
		(eq, "$pres_sod_fief_info", 1),
		(eq, reg6, 0),
		(party_slot_eq, "$pres_sod_fief_selected", "$pres_sod_fief_selected_building", 0),
		(call_script, "script_validate_construction_choice", "$pres_sod_fief_selected", "$pres_sod_fief_selected_building"),
		(eq, reg0, 1),
		(store_troop_gold, ":cur_gold", "trp_player"),
		(ge, ":cur_gold", reg5),
		(create_game_button_overlay, "$g_presentation_obj_10", "@Build", tf_center_justify),
        (position_set_x, pos1, 380),
        (position_set_y, pos1, 55),
        (overlay_set_position, "$g_presentation_obj_10", pos1),
		(position_set_x, pos1, 130),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$g_presentation_obj_10", pos1),
		(try_end),
		#DISPLAY GARRISON BUTTON FOR CASTLES/TOWNS OR WORKFORCE FOR VILLAGES BUTTON ####################################################################
		(try_begin),
		(party_slot_eq, "$pres_sod_fief_selected", slot_party_type, spt_village),
		(create_game_button_overlay, "$g_presentation_obj_11", "@Workforce", tf_center_justify),
        (position_set_x, pos1, 630),
        (position_set_y, pos1, 500),
        (overlay_set_position, "$g_presentation_obj_11", pos1),
		(position_set_x, pos1, 130),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$g_presentation_obj_11", pos1),
		(else_try),
		(create_game_button_overlay, "$g_presentation_obj_12", "@Garrison", tf_center_justify),
        (position_set_x, pos1, 630),
        (position_set_y, pos1, 500),
        (overlay_set_position, "$g_presentation_obj_12", pos1),
		(position_set_x, pos1, 130),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$g_presentation_obj_12", pos1),
		(try_end),
		
		#DISPLAY LEAVE BUTTON ####################################################################
		(try_begin),
		(create_game_button_overlay, "$pres_fief_leave", "@Leave", tf_center_justify),
        (position_set_x, pos1, 865),
        (position_set_y, pos1, 60),
        (overlay_set_position, "$pres_fief_leave", pos1),
		(position_set_x, pos1, 130),
        (position_set_y, pos1, 40),
        (overlay_set_size, "$pres_fief_leave", pos1),
		(try_end),
		
        (presentation_set_duration, 999999),
        ]),
# #############################################################################################
# #############################################################################################
	  (ti_on_presentation_run,
       [
	   #Presenter's Little Helper
      (eq, "$g_sod_debug", 1),
      (mouse_get_position, pos1),
      (position_get_x, reg1, pos1),
      (position_get_y, reg2, pos1),
      (overlay_set_text, "$g_little_pos_helper", "@{reg1},{reg2}"),
        ]),
      (ti_on_presentation_event_state_change,
       [
	   (store_trigger_param_1, ":object"),
	   (store_trigger_param_2, ":value"),
	   
	(try_begin),
		(eq, ":object", "$g_presentation_obj_1"),
		(assign, ":end", centers_end),
		(try_for_range, ":center_no", centers_begin, ":end"),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(party_slot_eq, ":center_no", slot_party_type, spt_town),	
			(assign, ":end", 0),	
			(assign, "$pres_sod_fief_type", spt_town),
			(assign, "$pres_sod_fief_info", 0),
			(assign, "$pres_sod_fief_slider_value", 1),
			(start_presentation, "prsnt_sod_fief_management"),
		(try_end),
		(try_begin),
			(eq, ":end", centers_end),
			(display_message, "@You have no towns!", red),
		(try_end),
	(else_try),
		(eq, ":object", "$g_presentation_obj_2"),
		(assign, ":end", centers_end),
		(try_for_range, ":center_no", centers_begin, ":end"),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(party_slot_eq, ":center_no", slot_party_type, spt_castle),	
			(assign, ":end", 0),	
			(assign, "$pres_sod_fief_type", spt_castle),
			(assign, "$pres_sod_fief_info", 0),
			(assign, "$pres_sod_fief_slider_value", 1),
			(start_presentation, "prsnt_sod_fief_management"),
		(try_end),
		(try_begin),
			(eq, ":end", centers_end),
			(display_message, "@You have no castles!", red),
		(try_end),
	(else_try),
		(eq, ":object", "$g_presentation_obj_3"),
		(assign, ":end", centers_end),
		(try_for_range, ":center_no", centers_begin, ":end"),
			(party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
			(party_slot_eq, ":center_no", slot_party_type, spt_village),	
			(assign, ":end", 0),	
			(assign, "$pres_sod_fief_type", spt_village),
			(assign, "$pres_sod_fief_info", 0),
			(assign, "$pres_sod_fief_slider_value", 1),
			(start_presentation, "prsnt_sod_fief_management"),
		(try_end),
		(try_begin),
			(eq, ":end", centers_end),
			(display_message, "@You have no villages!", red),
		(try_end),
	(else_try),   
		(eq, ":object", "$pres_sod_fief_slider_fiefnumber"),
		(neq, "$pres_sod_fief_slider_value", ":value"),
		(assign, "$pres_sod_fief_slider_value", ":value"),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_4"),
		(val_add, "$pres_sod_fief_slider_value", 1),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_5"),
		(val_sub, "$pres_sod_fief_slider_value", 1),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_6"),
		(assign, "$pres_sod_fief_info", 1),
		(assign, "$pres_sod_fief_buildings_value", 1),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_7"),
		(neq, "$pres_sod_fief_buildings_value", ":value"),
		(assign, "$pres_sod_fief_buildings_value", ":value"),
		(overlay_set_val, "$g_presentation_obj_7", ":value"),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_8"),
		(neq, "$pres_sod_fief_buildings_value", "$pres_sod_fief_buildings"),
			(val_add, "$pres_sod_fief_buildings_value", 1),
			(overlay_set_val, "$g_presentation_obj_7", "$pres_sod_fief_buildings_value"),
			(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_9"),
		(neq, "$pres_sod_fief_buildings_value", 1),
			(val_sub, "$pres_sod_fief_buildings_value", 1),
			(overlay_set_val, "$g_presentation_obj_7", "$pres_sod_fief_buildings_value"),
			(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_object_25"),
		
		(neg|party_slot_eq, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":value"),
		
		(party_get_slot, ":soldiers", "$pres_sod_fief_selected", slot_center_garrison_soldiers),
		(party_get_slot, ":ranged", "$pres_sod_fief_selected", slot_center_garrison_ranged),
		(val_add, ":soldiers", ":ranged"),
		(val_sub, ":soldiers", ":value"),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_soldiers, ":soldiers"),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":value"),
		
		(overlay_set_val, "$g_presentation_obj_25", ":value"),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_27"),
		
		(party_get_slot, ":soldiers", "$pres_sod_fief_selected", slot_center_garrison_soldiers),
		(party_get_slot, ":ranged", "$pres_sod_fief_selected", slot_center_garrison_ranged),
		(store_add, ":daily_garrisoning", ":ranged", ":soldiers"),
		(neg|party_slot_eq, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":daily_garrisoning"),
		
		(val_add, ":ranged", 1),
		(val_sub, ":soldiers", 1),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_soldiers, ":soldiers"),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":ranged"),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_28"),
		
		(party_get_slot, ":soldiers", "$pres_sod_fief_selected", slot_center_garrison_soldiers),
		(party_get_slot, ":ranged", "$pres_sod_fief_selected", slot_center_garrison_ranged),
		(store_add, ":daily_garrisoning", ":ranged", ":soldiers"),
		(neg|party_slot_eq, "$pres_sod_fief_selected", slot_center_garrison_ranged, 0),
		
		(val_add, ":soldiers", 1),
		(val_sub, ":ranged", 1),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_soldiers, ":soldiers"),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":ranged"),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_14"),
		
		(party_slot_ge, "$pres_sod_fief_selected", slot_center_max_garrison, 25),
		
		(party_get_slot, ":max_garrison", "$pres_sod_fief_selected", slot_center_max_garrison),
		(val_sub, ":max_garrison", 25),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_max_garrison, ":max_garrison"),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_15"),
		
		(party_get_slot, ":max_garrison", "$pres_sod_fief_selected", slot_center_max_garrison),
		(val_add, ":max_garrison", 25),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_max_garrison, ":max_garrison"),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_17"),
		
		(party_get_slot, ":soldiers", "$pres_sod_fief_selected", slot_center_garrison_soldiers),
		(party_get_slot, ":ranged", "$pres_sod_fief_selected", slot_center_garrison_ranged),
		(store_add, ":daily_garrisoning", ":ranged", ":soldiers"),
		(gt, ":daily_garrisoning", 0),
		(try_begin),
			(party_slot_ge, "$pres_sod_fief_selected", slot_center_garrison_soldiers, 1),
			(party_slot_ge, "$pres_sod_fief_selected", slot_center_garrison_ranged, 1),
			(store_random_in_range, ":rand", 0, 2),
			(try_begin),
				(eq, ":rand", 0),
				(val_sub, ":soldiers", 1),
			(else_try),
				(val_sub, ":ranged", 1),
			(try_end),
		(else_try),
			(party_slot_ge, "$pres_sod_fief_selected", slot_center_garrison_soldiers, 1),
			(val_sub, ":soldiers", 1),
		(else_try),
			(val_sub, ":ranged", 1),
		(try_end),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_soldiers, ":soldiers"),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":ranged"),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_18"),
		
		(party_get_slot, ":trainers", "$pres_sod_fief_selected", slot_center_trainers),
		(gt, ":trainers", 0),
		(val_mul, ":trainers", 2),
		(party_get_slot, ":soldiers", "$pres_sod_fief_selected", slot_center_garrison_soldiers),
		(party_get_slot, ":ranged", "$pres_sod_fief_selected", slot_center_garrison_ranged),
		(store_add, ":daily_garrisoning", ":ranged", ":soldiers"),
		(lt, ":daily_garrisoning", ":trainers"),
		(try_begin),
			(party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks, 1),
			(party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range, 1),
			(store_random_in_range, ":rand", 0, 2),
			(try_begin),
				(eq, ":rand", 0),
				(val_add, ":soldiers", 1),
				(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_soldiers, ":soldiers"),
			(else_try),
				(val_add, ":ranged", 1),
				(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":ranged"),
			(try_end),
		(else_try),
			(party_slot_eq, "$pres_sod_fief_selected", slot_center_has_barracks, 1),
			(val_add, ":soldiers", 1),
			(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_soldiers, ":soldiers"),
		(else_try),
			(party_slot_eq, "$pres_sod_fief_selected", slot_center_has_range, 1),
			(val_add, ":ranged", 1),
			(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":ranged"),
		(try_end),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_20"),
		(party_slot_ge, "$pres_sod_fief_selected", slot_center_trainers, 1),
		
		(party_get_slot, ":trainers", "$pres_sod_fief_selected", slot_center_trainers),
		(val_sub, ":trainers", 1),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_trainers, ":trainers"),
		
		(val_mul, ":trainers", 2),
		(party_get_slot, ":soldiers", "$pres_sod_fief_selected", slot_center_garrison_soldiers),
		(party_get_slot, ":ranged", "$pres_sod_fief_selected", slot_center_garrison_ranged),
		(store_add, ":daily_garrisoning", ":ranged", ":soldiers"),
		(try_for_range, ":unused", 0, 5),
			(gt, ":daily_garrisoning", ":trainers"),
			(try_begin),
				(party_slot_ge, "$pres_sod_fief_selected", slot_center_garrison_soldiers, 1),
				(val_sub, ":soldiers", 1),
			(else_try),
				(val_sub, ":ranged", 1),
			(try_end),
			(val_sub, ":daily_garrisoning", 1),
		(try_end),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_soldiers, ":soldiers"),
		(party_set_slot, "$pres_sod_fief_selected", slot_center_garrison_ranged, ":ranged"),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_21"),
		(party_get_slot, ":num_trainers", "$pres_sod_fief_selected", slot_center_trainers, 5),
		(lt, ":num_trainers", 5),
		
		(store_mul, ":next_trainer_price", ":num_trainers", 100),
		(val_add, ":next_trainer_price", 100),
		
		(store_troop_gold, ":gold", "trp_player"),
		(try_begin),
			(ge, ":gold", ":next_trainer_price"),
			(troop_remove_gold, "trp_player", ":next_trainer_price"),
			(party_get_slot, ":trainers", "$pres_sod_fief_selected", slot_center_trainers),
			(val_add, ":trainers", 1),
			(party_set_slot, "$pres_sod_fief_selected", slot_center_trainers, ":trainers"),
		(else_try),
			(display_message, "@Not enogh founds.", dark_red),
		(try_end),
		
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_10"),
		(troop_remove_gold, "trp_player", reg5),
        # Safety: track only positive spending.
        (val_max, reg5, 0),
        (val_add, "$g_sod_weekly_construction", reg5), # track player expenses
        (val_clamp, "$g_sod_weekly_construction", 0, 2000001),
        (party_set_slot, "$pres_sod_fief_selected", slot_center_current_improvement, "$pres_sod_fief_selected_building"),
        (store_current_hours, ":cur_hours"),
        (store_mul, ":hours_takes", reg10, 24),
        (val_add, ":hours_takes", ":cur_hours"),
        (party_set_slot, "$pres_sod_fief_selected", slot_center_improvement_end_hour, ":hours_takes"),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_12"),
		(assign, "$pres_sod_fief_info", 2),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_22"),
		(assign, "$pres_sod_garrison_tip", 1),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_29"),
		(assign, "$pres_sod_garrison_tip", 2),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$g_presentation_obj_30"),
		(assign, "$pres_sod_garrison_tip", 3),
		(start_presentation, "prsnt_sod_fief_management"),
	(else_try),
		(eq, ":object", "$pres_fief_leave"),
		(presentation_set_duration, 0),
	(try_end),
		]),
      ]),
]
