MENUS = [
("character_report", mnf_enable_hot_keys,
   "{s9}",
   "none",
   [
    (set_background_mesh, "mesh_pic_report_screen"),
    (try_begin),
      (gt, "$g_player_reading_book", 0),
      (player_has_item, "$g_player_reading_book"),
      (str_store_item_name, s8, "$g_player_reading_book"),
      (str_store_string, s9, "@You are currently reading {s8}."),
    (else_try),
      (assign, "$g_player_reading_book", 0),
      (str_store_string, s9, "@You are not reading any books."),
    (try_end),
    (assign, ":num_friends", 0),
    (assign, ":num_enemies", 0),
    (str_store_string, s6, "@none"),
    (str_store_string, s8, "@none"),
    (try_for_range, ":troop_no", kingdom_heroes_begin, kingdom_heroes_end),
      (call_script, "script_troop_get_player_relation", ":troop_no"),
      (assign, ":player_relation", reg0),
      #(troop_get_slot, ":player_relation", ":troop_no", slot_troop_player_relation),
      (try_begin),
        (gt, ":player_relation", 20),
        (try_begin),
          (eq, ":num_friends", 0),
          (call_script, "script_store_troop_name", s8, ":troop_no"),
        (else_try),
          (eq, ":num_friends", 1),
          (call_script, "script_store_troop_name", s7, ":troop_no"),
          (str_store_string, s8, "@{s7} and {s8}"),
        (else_try),
          (call_script, "script_store_troop_name", s7, ":troop_no"),
          (str_store_string, s8, "@{s7}, {s8}"),
        (try_end),
        (val_add, ":num_friends", 1),
      (else_try),
        (lt, ":player_relation", -20),
        (try_begin),
          (eq, ":num_enemies", 0),
          (call_script, "script_store_troop_name", s6, ":troop_no"),
        (else_try),
          (eq, ":num_enemies", 1),
          (call_script, "script_store_troop_name", s5, ":troop_no"),
          (str_store_string, s6, "@{s5} and {s6}"),
        (else_try),
          (call_script, "script_store_troop_name", s5, ":troop_no"),
          (str_store_string, s6, "@{s5}, {s6}"),
        (try_end),
        (val_add, ":num_enemies", 1),
      (try_end),
    (try_end),
    (assign, reg3, "$player_honor"),
    (troop_get_slot, reg2, "trp_player", slot_troop_renown),
    (try_begin), # SoD Twan : display badboy rating and decay when PSF is active
      (faction_slot_eq, "fac_player_supporters_faction", slot_faction_state, sfs_active),           
      (faction_get_slot, reg4, "fac_player_supporters_faction", slot_faction_badboy_rating),
      (call_script, "script_calculate_badboy_decay"), 
    (str_store_string, s9, "@Renown: {reg2}.^Honour rating: {reg3}.^Badboy rating : {reg4} (with a weekly decay of {reg0}).^^Friends: {s8}.^Enemies: {s6}.^{s9}"),
    (else_try),
    (str_store_string, s9, "@Renown: {reg2}.^Honour rating: {reg3}.^^Friends: {s8}.^Enemies: {s6}.^{s9}"),
    (try_end),          # Sod Twan End

    (call_script, "script_get_number_of_hero_centers", "trp_player"),
    (assign, ":no_centers", reg0),
    (try_begin),
      (gt, ":no_centers", 0),
      (try_for_range, ":i_center", 0, ":no_centers"),
        (call_script, "script_troop_get_leaded_center_with_index", "trp_player", ":i_center"),
        (assign, ":cur_center", reg0),
        (try_begin),
          (eq, ":i_center", 0),
          (str_store_party_name, s8, ":cur_center"),
        (else_try),
          (eq, ":i_center", 1),
          (str_store_party_name, s7, ":cur_center"),
          (str_store_string, s8, "@{s7} and {s8}"),
        (else_try),
          (str_store_party_name, s7, ":cur_center"),
          (str_store_string, s8, "@{s7}, {s8}"),
        (try_end),
      (try_end),
      (str_store_string, s9, "@Your estates are: {s8}.^{s9}"),
    (try_end),
    (try_begin),
      (gt, "$players_kingdom", 0),
      (str_store_faction_name, s8, "$players_kingdom"),
      #MORDACHAI - tell them they're King, if they are...
      (try_begin),
        (faction_slot_eq, "$players_kingdom", slot_faction_leader, "trp_player"),
        (str_store_string, s9, "@You are the {King/Queen} of the {s8}.^{s9}"),
      (else_try),
        (try_begin),
          (eq, "$player_has_homage", 0),
          (store_current_day, ":day"),
          (store_sub, reg0, "$mercenary_service_next_renew_day", ":day"),
          (str_store_string, s9, "@Your mercenary contract will expire in {reg0} days.^{s9}"),
        (try_end),
        (assign, reg0, "$player_has_homage"),
        (str_store_string, s9, "@You are a {reg0?lord of:mercenary for} the {s8}.^{s9}"),
      (try_end),
    (try_end),
    (call_script, "script_merc_describe_report_summary"),
    (str_store_string, s9, "@{s60}^{s61}^{s62}^{s9}"),
  ],
  [
    ("continue", [], "Continue...",
     [(jump_to_menu, "mnu_reports"),
      ]
     ),
    ]
  ),
]
