MENUS = [
("fief_reports", mnf_enable_hot_keys,
    "{s1}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),

      (try_begin),
        (gt, "$players_kingdom", 0),
        (str_store_faction_name, s1, "$players_kingdom"),
        (faction_get_slot, ":King", "$players_kingdom", slot_faction_leader),
        (try_begin),
          (eq, ":King", "trp_player"),
          (str_store_string, s1, "@You are the {King/Queen} of the {s1}."),
        (else_try),
          (eq, "$player_has_homage", 1),
          (call_script, "script_store_troop_name", s2, ":King"),
          (str_store_string, s1, "@You are a vassal of {s2}, King of the {s1}."),
        (else_try),
          (str_store_string, s1, "@You are a mercenary for the {s1}."),
        (try_end),
      (else_try),
        (str_store_string, s1, "@You are a foreigner, without allegience of any kind..."),
      (try_end),

      (call_script, "script_get_number_of_hero_centers", "trp_player"),
      (assign, ":no_centers", reg0),
      (store_sub, ":last", reg0, 1),
      (try_for_range, ":i_center", 0, ":no_centers"),
        (call_script, "script_troop_get_leaded_center_with_index", "trp_player", ":i_center"),
        (assign, ":cur_center", reg0),
        (try_begin),
          (eq, ":i_center", 0),
          (str_store_party_name, s8, ":cur_center"),
        (else_try),
          (eq, ":i_center", ":last"),
          (str_store_party_name, s7, ":cur_center"),
          (str_store_string, s8, "@{s8} and {s7}"),
        (else_try),
          (str_store_party_name, s7, ":cur_center"),
          (str_store_string, s8, "@{s8}, {s7}"),
        (try_end),
      (try_end),
      (str_store_string, s1, "@{s1}^^Your estates are: {s8}."),
      # add on the accumulated income / rents
      (assign, ":total_income", 0),
      (try_for_range, ":center_no", centers_begin, centers_end),
        (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
        (party_get_slot, ":accumulated_rents", ":center_no", slot_center_accumulated_rents),
        (party_get_slot, ":accumulated_tariffs", ":center_no", slot_center_accumulated_tariffs),
        (val_add, ":total_income", ":accumulated_rents"),
        (val_add, ":total_income", ":accumulated_tariffs"),
      (try_end),
      (assign, reg1, ":total_income"),
      (str_store_string, s1, "@{s1}^^Accumulated taxes & rents: {reg1} denars."),
    ],
    [
      ("view_prosperity_report", [], "View prosperity report.", [(jump_to_menu, "mnu_fief_prosperity_report")]),
      ("view_trade_pressure_report", [], "View trade pressure report.", [(jump_to_menu, "mnu_fief_trade_pressure_report")]),
      ("view_construction_report", [], "View current construction report.", [(jump_to_menu, "mnu_fief_under_construction_report")]),
      ("view_available_construction_report", [], "View available construction report.", [(jump_to_menu, "mnu_fief_available_construction_report")]),
      ("view_lord_other", [], "Let me see a different report...", [(jump_to_menu, "mnu_reports")]),
      ("view_lord_travel", [], "Resume travelling.", [(change_screen_return)]),
    ]
  ),
]
