MENUS = [
("firentis_debt_restitution", mnf_scale_picture|mnf_enable_hot_keys,
   "Firentis stands at the edge of the rescued village with his helmet under one arm. The smoke has thinned, but the people still flinch at mailed hands. A boy keeps staring at Firentis' sword as if it might remember another house, another night.^^Firentis speaks quietly. A victory can still leave a debt. What shall be paid?",
   "none",
    [
      (set_background_mesh, "mesh_pic_camp"),
      (try_begin),
        (this_or_next|neg|main_party_has_troop, "trp_npc6"),
        (neq, "$g_sod_firentis_restitution_pending", 1),
        (assign, "$g_sod_firentis_restitution_pending", 0),
        (jump_to_menu, "mnu_camp_action"),
      (try_end),
    ],
    [
      ("firentis_restitution_protect", [
          (main_party_has_troop, "trp_npc6"),
          (call_script, "script_cf_sod_companion_campaign_available", "trp_npc6", sod_companion_campaign_mode_dialog),
          (eq, "$g_sod_firentis_restitution_pending", 1),
          (eq, "$g_sod_firentis_restitution_confronted", 1),
        ], "Leave guards, coin, and supplies. Protection is part of penance.",
        [
          (assign, "$g_sod_firentis_restitution_pending", 0),
          (assign, "$g_sod_firentis_restitution_result_grade", 3),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_help_village, 3),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_honorable_peace, 2),
          (call_script, "script_sod_companion_advance_personal_quest", "trp_npc6", 1),
          (call_script, "script_sod_companion_firentis_apply_restitution_payoff"),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 100),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 3),
          (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
          (display_message, "@Firentis accepts that penance must become shelter, coin, and restraint. Debt of the Sword remembers restitution.", 0x99CCFF),
          (jump_to_menu, "mnu_camp_action"),
        ]
      ),
      ("firentis_restitution_confess", [
          (main_party_has_troop, "trp_npc6"),
          (call_script, "script_cf_sod_companion_campaign_available", "trp_npc6", sod_companion_campaign_mode_dialog),
          (eq, "$g_sod_firentis_restitution_pending", 1),
          (eq, "$g_sod_firentis_restitution_confronted", 1),
        ], "Let truth be spoken. Ask the village what justice can still mean.",
        [
          (assign, "$g_sod_firentis_restitution_pending", 0),
          (assign, "$g_sod_firentis_restitution_result_grade", 2),
          (call_script, "script_sod_companion_shift_approval", "trp_npc6", 2),
          (try_begin),
            (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
            (troop_set_slot, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
          (else_try),
            (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
            (call_script, "script_sod_companion_advance_personal_quest", "trp_npc6", 1),
            (call_script, "script_sod_companion_firentis_apply_restitution_payoff"),
          (try_end),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 100),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 2),
          (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
          (display_message, "@The answer is not clean, but it is honest. Firentis hears judgment without reaching for steel.", 0xCCCC66),
          (jump_to_menu, "mnu_camp_action"),
        ]
      ),
      ("firentis_restitution_silence", [
          (main_party_has_troop, "trp_npc6"),
          (call_script, "script_cf_sod_companion_campaign_available", "trp_npc6", sod_companion_campaign_mode_dialog),
          (eq, "$g_sod_firentis_restitution_pending", 1),
          (eq, "$g_sod_firentis_restitution_confronted", 1),
        ], "Say nothing more. The village needed swords, not confession.",
        [
          (assign, "$g_sod_firentis_restitution_pending", 0),
          (assign, "$g_sod_firentis_restitution_result_grade", 1),
          (call_script, "script_sod_companion_advance_personal_quest", "trp_npc6", 0),
          (troop_set_slot, "trp_npc6", slot_troop_companion_warning_state, sod_companion_warning_pending),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 100),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 1),
          (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
          (display_message, "@Firentis obeys. Debt of the Sword remembers silence as another wound.", 0xCC6666),
          (jump_to_menu, "mnu_camp_action"),
        ]
      ),
      ("firentis_restitution_leave", [], "Return to camp.",
        [
          (jump_to_menu, "mnu_camp_action"),
        ]
      ),
    ]
  ),
("firentis_restitution_hearing", mnf_scale_picture|mnf_enable_hot_keys,
   "The village gathers near a blackened fence. Firentis stands without helmet or drawn sword while an elder names the cost of soldiers who arrive too late, too proud, or too hungry. Then shouting breaks at the lane: deserters and camp followers who expected payment from the village have come back to collect.^^Firentis does not move until you answer. 'If restitution is only words,' he says, 'it will fail before the first frightened door.'",
   "none",
    [
      (set_background_mesh, "mesh_pic_camp"),
      (try_begin),
        (this_or_next|neg|main_party_has_troop, "trp_npc6"),
        (neq, "$current_town", "$g_sod_firentis_restitution_focus_center"),
        (jump_to_menu, "mnu_village"),
      (try_end),
    ],
    [
      ("firentis_hearing_defend", [
          (main_party_has_troop, "trp_npc6"),
          (call_script, "script_cf_sod_companion_campaign_available", "trp_npc6", sod_companion_campaign_mode_battle),
          (eq, "$g_sod_firentis_restitution_pending", 1),
          (eq, "$g_sod_firentis_restitution_witnessed", 1),
          (eq, "$g_sod_firentis_restitution_confronted", 0),
          (eq, "$current_town", "$g_sod_firentis_restitution_focus_center"),
          (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
        ], "Defend the restitution hearing.",
        [
          (party_get_slot, ":village_scene", "$current_town", slot_castle_exterior),
          (modify_visitors_at_site, ":village_scene"),
          (reset_visitors),
          (set_visitor, 0, "trp_player"),
          (set_visitor, 1, "trp_npc6"),
          (set_visitor, 2, "trp_farmer"),
          (set_visitor, 3, "trp_farmer"),
          (set_visitor, 10, "trp_bandit"),
          (set_visitor, 11, "trp_brigand"),
          (set_visitor, 12, "trp_henchman"),
          (set_visitor, 13, "trp_brigand"),
          (set_jump_mission, "mt_companion_firentis_restitution_defense"),
          (jump_to_scene, ":village_scene"),
          (change_screen_mission),
        ]
      ),
      ("firentis_hearing_confess", [
          (main_party_has_troop, "trp_npc6"),
          (call_script, "script_cf_sod_companion_campaign_available", "trp_npc6", sod_companion_campaign_mode_scene),
          (eq, "$g_sod_firentis_restitution_pending", 1),
          (eq, "$g_sod_firentis_restitution_witnessed", 1),
          (eq, "$g_sod_firentis_restitution_confronted", 0),
          (eq, "$current_town", "$g_sod_firentis_restitution_focus_center"),
        ], "Let Firentis answer the accusation in public.",
        [
          (assign, "$g_sod_firentis_restitution_confronted", 1),
          (assign, "$g_sod_firentis_restitution_result_grade", 2),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 75),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 2),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_debt_honesty, 2),
          (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
          (display_message, "@Firentis lets the accusation stand in daylight. The village hears truth before it hears promises.", 0xCCCC66),
          (jump_to_menu, "mnu_village"),
        ]
      ),
      ("firentis_hearing_silence", [
          (main_party_has_troop, "trp_npc6"),
          (call_script, "script_cf_sod_companion_campaign_available", "trp_npc6", sod_companion_campaign_mode_scene),
          (eq, "$g_sod_firentis_restitution_pending", 1),
          (eq, "$g_sod_firentis_restitution_witnessed", 1),
          (eq, "$g_sod_firentis_restitution_confronted", 0),
          (eq, "$current_town", "$g_sod_firentis_restitution_focus_center"),
        ], "End the hearing before it weakens command.",
        [
          (assign, "$g_sod_firentis_restitution_confronted", 1),
          (assign, "$g_sod_firentis_restitution_result_grade", 1),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 75),
          (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 1),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_hard_compromise, 2),
          (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
          (display_message, "@The hearing ends under armed quiet. Firentis follows, but the village now knows which truth was too costly.", 0xCC6666),
          (jump_to_menu, "mnu_village"),
        ]
      ),
      ("firentis_hearing_leave", [], "Step back from the hearing.",
        [
          (jump_to_menu, "mnu_village"),
        ]
      ),
    ]
  ),
("firentis_restitution_defense_succeeded", mnf_disable_all_keys,
   "The deserters break and run, leaving stolen bread and loose arrows in the mud. The village has seen Firentis stand where a penitent man should stand: between old harm and new harm.",
   "none",
    [
      (assign, "$g_sod_firentis_restitution_confronted", 1),
      (try_begin),
        (lt, "$g_sod_firentis_restitution_result_grade", 2),
        (assign, "$g_sod_firentis_restitution_result_grade", 3),
      (try_end),
      (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 75),
      (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, "$g_sod_firentis_restitution_result_grade"),
      (call_script, "script_sod_companion_apply_player_action", sod_companion_action_help_village, 2),
      (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
    ],
    [
      ("continue", [], "Continue...", [(jump_to_menu, "mnu_village")]),
    ]
  ),
("firentis_restitution_defense_failed", mnf_disable_all_keys,
   "The hearing scatters under blows and shouted blame. Firentis survives, but the village has learned that good intentions still need a line that holds.",
   "none",
    [
      (assign, "$g_sod_firentis_restitution_result_grade", -1),
      (assign, "$g_sod_firentis_restitution_confronted", 0),
      (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 50),
      (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, -1),
      (call_script, "script_sod_companion_shift_approval", "trp_npc6", -2),
      (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
    ],
    [
      ("continue", [], "Continue...", [(jump_to_menu, "mnu_village")]),
    ]
  ),
]
