MENUS = [
("free_slaves_confirm", mnf_scale_picture|mnf_enable_hot_keys,
   "You have {reg1} slaves in your party. Freeing them will remove them from your ranks, improve your honor by {reg2}, and anger the Slaver black market.",
   "none",
    [
      (set_background_mesh, "mesh_pic_camp"),
      (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
      (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
      (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
      (assign, reg1, ":slave_count"),
      (store_div, ":honor_gain", ":slave_count", 5),
      (val_add, ":honor_gain", 1),
      (val_clamp, ":honor_gain", 1, 6),
      (assign, reg2, ":honor_gain"),
    ],
    [
      ("free_slaves_confirm_yes", [
          (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
          (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
          (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
          (gt, ":slave_count", 0),
        ], "Free them.",
        [
          (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
          (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
          (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
          (party_remove_members, "p_main_party", "trp_slave", ":male_slaves"),
          (party_remove_members, "p_main_party", "trp_slave_female", ":female_slaves"),
          (store_div, ":honor_gain", ":slave_count", 5),
          (val_add, ":honor_gain", 1),
          (val_clamp, ":honor_gain", 1, 6),
          (call_script, "script_change_player_honor", ":honor_gain"),
          (store_div, ":market_pressure", ":slave_count", 2),
          (val_add, ":market_pressure", 1),
          (val_clamp, ":market_pressure", 1, 16),
          (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_free_runaways, ":market_pressure"),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_free_captives, ":market_pressure"),
          (call_script, "script_sod_companion_try_ymira_refugee_incident", ":slave_count"),
          (call_script, "script_sod_companion_try_deshavi_trail_warning_incident", 2, ":market_pressure"),
          (call_script, "script_sod_companion_try_klethi_old_job_incident", 2, ":market_pressure"),
          (call_script, "script_sod_companion_ymira_apply_mercy_payoff", ":slave_count"),
          (assign, reg1, ":slave_count"),
          (assign, reg2, ":honor_gain"),
          (display_message, "@You freed {reg1} slaves. Your honor rises by {reg2}, and the Slavers will remember it.", 0x00AA00),
          (jump_to_menu, "mnu_camp_action"),
        ]
      ),
      ("free_slaves_confirm_no", [], "Keep them.",
        [
          (party_count_members_of_type, ":male_slaves", "p_main_party", "trp_slave"),
          (party_count_members_of_type, ":female_slaves", "p_main_party", "trp_slave_female"),
          (store_add, ":slave_count", ":male_slaves", ":female_slaves"),
          (call_script, "script_sod_companion_try_ymira_refugee_expedience", ":slave_count"),
          (jump_to_menu, "mnu_camp_action"),
        ]
      ),
    ]
  ),
]
