MENUS = [
("invasion_status_report", mnf_enable_hot_keys,
    "{s1}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),
      (store_current_day, ":cur_day"),
      (try_begin),
        (faction_slot_eq, "fac_kingdom_6", slot_faction_state, sfs_active),
        (faction_get_slot, ":front_center", "fac_kingdom_6", slot_faction_central_center),
        (str_store_party_name, s32, ":front_center"),
        (faction_get_slot, reg1, "fac_kingdom_6", slot_faction_num_armies),
        (faction_get_slot, reg2, "fac_kingdom_6", slot_faction_num_towns),
        (faction_get_slot, reg3, "fac_kingdom_6", slot_faction_num_castles),
        (faction_get_slot, reg4, "fac_kingdom_6", slot_faction_current_power),
        (assign, reg5, 0),
        (try_for_range, ":kingdom_no", kingdoms_begin, kingdoms_end),
          (neq, ":kingdom_no", "fac_kingdom_6"),
          (faction_slot_eq, ":kingdom_no", slot_faction_state, sfs_active),
          (store_relation, ":relation", ":kingdom_no", "fac_kingdom_6"),
          (lt, ":relation", 0),
          (val_add, reg5, 1),
        (try_end),
        (try_begin),
          (faction_slot_eq, "fac_player_supporters_faction", slot_faction_state, sfs_active),
          (store_relation, reg6, "fac_player_supporters_faction", "fac_kingdom_6"),
        (else_try),
          (assign, reg6, 0),
        (try_end),
        (str_store_string, s1, "@Imperial Invasion Status^^Front: {s32}^Imperial armies: {reg1}^Imperial towns: {reg2}^Imperial castles: {reg3}^Estimated power: {reg4}^Calradian realms at war with the Legion: {reg5}^Your realm relation to the Legion: {reg6}^^Strategic read:^Hold border garrisons near the front, keep mobile reserves ready to intercept centurions, and exploit any alliance pressure against the Legion."),
      (else_try),
        (store_sub, reg1, "$g_sod_invasion_begin", ":cur_day"),
        (val_max, reg1, 0),
        (str_store_string, s1, "@Imperial Invasion Status^^The Legion has not yet entered Calradia.^Estimated days until invasion: {reg1}^^Strategic read:^Build reserves, improve border fiefs, secure mercenary relations, and prepare a fast field army before the first Imperial armies arrive."),
      (try_end),
    ],
    [
      ("continue", [], "Continue.", [(jump_to_menu, "mnu_reports")]),
    ]
  ),
]
