MENUS = [
("royal_artifact_smith", mnf_enable_hot_keys,
   "The royal smiths unroll oilcloth, chalk, and thin strips of polished steel. They can maintain one artifact weapon at a time, preserving its edge and recording its provenance.",
   "none",
  [
    (set_background_mesh, "mesh_pic_report_screen"),
    ],
    [
      ("refine_weapon", [(store_troop_gold, ":gold", "trp_player"), (ge, ":gold", 1500)], "Commission careful artifact maintenance (1500 denars).",
       [
         (troop_remove_gold, "trp_player", 1500),
         (assign, ":done", 0),
         (try_for_range, ":slot", ek_item_0, ek_item_3 + 1),
           (eq, ":done", 0),
           (troop_get_inventory_slot, ":item_no", "trp_player", ":slot"),
           (gt, ":item_no", 0),
           (item_get_slot, ":flags", ":item_no", slot_item_artifact_flags),
           (store_and, ":is_weapon", ":flags", artifact_flag_weapon),
           (gt, ":is_weapon", 0),
           (item_get_slot, ":tech", ":item_no", slot_item_artifact_technique_flags),
           (val_or, ":tech", artifact_tech_reinforced_haft),
           (item_set_slot, ":item_no", slot_item_artifact_technique_flags, ":tech"),
           (str_store_item_name, s59, ":item_no"),
           (display_message, "@The royal smiths reinforce and document {s59}.", 0x66CC66),
           (assign, ":done", 1),
         (try_end),
         (try_begin),
           (eq, ":done", 0),
           (display_message, "@You have no equipped royal artifact weapon for the smiths to maintain.", 0xFFCC66),
         (try_end),
         (jump_to_menu, "mnu_royal_reliquary_report"),
       ]),
      ("back", [], "Back to the reliquary.", [(jump_to_menu, "mnu_royal_reliquary_report"),]),
      ]
  ),
]
