MENUS = [
("sod_upgrade_camp", 0,
	"{reg1?{reg1}:No} mercenaries in your party can be promoted from camp.{s19}",
	"none", [	
		(assign, "$jump_menu", "mnu_camp"),
		(assign, "$g_encountered_party", -1),
		(str_store_string, s18, "@The Commoners, The Slavers"),
		(try_for_range, ":guild", "fac_sod_merc_guild1", "fac_kingdom_6_mercenaries"),
			(neq, ":guild", "fac_sod_merc_guild6"),
			(faction_slot_eq, ":guild", slot_faction_upgrade_permission, 1),
			(str_store_faction_name, s0, ":guild"),
			(str_store_string, s18, "@{s18}, {s0}"),
		(try_end),

		(str_store_string, s19, "@^^^Authorized promotion sources:^^{s18}.^^Guild promotions remain camp-based; noble and faith doctrines require proper centers."),
			
		(assign, ":total", 0),
		(assign, reg1, 0),
		(try_for_range, ":troop_no", "trp_experience_troop", "trp_last_troop"),
			(assign, ":can_up1", 0),
			(assign, ":can_up2", 0),
			(party_count_companions_of_type, ":troop_count", "p_main_party", ":troop_no"),
			(troop_get_slot, ":upgrade1", ":troop_no", slot_troop_sod_upgrade1),
			(try_begin),
				(gt, ":upgrade1", 0),
				(call_script, "script_sod_can_upgrade_troops_here", ":upgrade1", "$g_encountered_party"),
				(assign, ":can_up1", reg0),
			(try_end),
			(troop_get_slot, ":upgrade2", ":troop_no", slot_troop_sod_upgrade2),
			(try_begin),
				(gt, ":upgrade2", 0),
				(call_script, "script_sod_can_upgrade_troops_here", ":upgrade2", "$g_encountered_party"),
				(assign, ":can_up2", reg0),
			(try_end),
			(this_or_next|eq, ":can_up1", 1),
			(eq, ":can_up2", 1),
			(val_add, ":total", ":troop_count"),
		(try_end),
		(assign, reg1, ":total"),
	],
		generate_upgrade_options()
	),
]
