DIALOGS = [
[anyone|plyr, "marshal_skirmish5a",
    [],
    "Next toop.", "marshal_skirmish2",
    [
	(val_add, "$sod_skirmish_fcount", 1),
    (try_begin),
		(eq, "$sod_skirmish_fcount", 1),
		(assign, "$sod_skirmish_ftroop_1", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_1_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 2),
		(assign, "$sod_skirmish_ftroop_2", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_2_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 3),
		(assign, "$sod_skirmish_ftroop_3", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_3_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 4),
		(assign, "$sod_skirmish_ftroop_4", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_4_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 5),
		(assign, "$sod_skirmish_ftroop_5", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_5_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 6),
		(assign, "$sod_skirmish_ftroop_6", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_6_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 7),
		(assign, "$sod_skirmish_ftroop_7", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_7_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 8),
		(assign, "$sod_skirmish_ftroop_8", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_8_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 9),
		(assign, "$sod_skirmish_ftroop_9", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_9_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 10),
		(assign, "$sod_skirmish_ftroop_10", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_10_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 11),
		(assign, "$sod_skirmish_ftroop_11", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_11_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_fcount", 12),
		(assign, "$sod_skirmish_ftroop_12", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_ftroop_12_number", "$sod_skirmish_troopcount"),
	(try_end),
	 ]],
]
