DIALOGS = [
[anyone|plyr, "marshal_skirmish8a",
    [],
    "Next Enemy Troop", "marshal_skirmish2",
    [
	(val_add, "$sod_skirmish_ecount", 1),
    (try_begin),
		(eq, "$sod_skirmish_ecount", 1),
		(assign, "$sod_skirmish_etroop_1", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_1_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 2),
		(assign, "$sod_skirmish_etroop_2", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_2_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 3),
		(assign, "$sod_skirmish_etroop_3", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_3_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 4),
		(assign, "$sod_skirmish_etroop_4", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_4_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 5),
		(assign, "$sod_skirmish_etroop_5", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_5_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 6),
		(assign, "$sod_skirmish_etroop_6", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_6_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 7),
		(assign, "$sod_skirmish_etroop_7", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_7_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 8),
		(assign, "$sod_skirmish_etroop_8", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_8_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 9),
		(assign, "$sod_skirmish_etroop_9", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_9_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 10),
		(assign, "$sod_skirmish_etroop_10", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_10_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 11),
		(assign, "$sod_skirmish_etroop_11", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_11_number", "$sod_skirmish_troopcount"),
	(else_try),
		(eq, "$sod_skirmish_ecount", 12),
		(assign, "$sod_skirmish_etroop_12", "$sod_skirmish_troop"),
		(assign, "$sod_skiermish_etroop_12_number", "$sod_skirmish_troopcount"),
	(try_end),
	 ]],
]
