DIALOGS = [
[trp_sod_chancellor, "chancellor_fiefs_who",
    [
      (party_get_slot, ":lord", "$assign_fief", slot_town_lord),

      (str_store_party_name, s1, "$assign_fief"),
      (try_begin),
        (party_slot_eq, "$assign_fief", slot_party_type, spt_village),
        (party_get_slot, ":bound_to", "$assign_fief", slot_village_bound_center),
        (str_store_party_name, s2, ":bound_to"),
        (str_store_string, s1, "@The village of {s1} bound to {s2}"),
      (else_try),
        (str_clear, s3),
        (assign, ":count", 0),
        (try_for_range, ":village", villages_begin, villages_end),
          (party_slot_eq, ":village", slot_village_bound_center, "$assign_fief"),
          (str_store_party_name, s2, ":village"),
          (val_add, ":count", 1),
          (try_begin),
            (eq, ":count", 1),
            (str_store_string_reg, s3, s2),
          (else_try),
            (str_store_string, s3, "@{s3},{s2}"),
          (try_end),
        (try_end),
        (try_begin),
          (party_slot_eq, "$assign_fief", slot_party_type, spt_town),
          (str_store_string, s1, "@Town of {s1}+{s3}"),
        (else_try),
          (str_store_string, s1, "@{s1}+{s3}"),
        (try_end),
      (try_end),

      (call_script, "script_store_troop_name", s2, ":lord"),
    ],
    "{s1} ({s2}). Who shall be your vassal to manage these lands?", "chancellor_fiefs_reassign", []],
]
