DIALOGS = [
[trp_sod_chancellor|plyr|repeat_for_parties, "chancellor_fiefs_which",
    [
      (store_repeat_object, ":fief"),
      (is_between, ":fief", "p_town_1", "p_salt_mine"),
      (store_faction_of_party, ":center_faction", ":fief"),
      (eq, ":center_faction", "fac_player_supporters_faction"),
      (str_store_party_name, s1, ":fief"),
      (try_begin),
        (party_slot_eq, ":fief", slot_party_type, spt_village),
        (party_get_slot, ":bound_to", ":fief", slot_village_bound_center),
        (str_store_party_name, s2, ":bound_to"),
        (str_store_string, s1, "@Village of {s1} bound to {s2}"),
      (else_try),
        (str_clear, s3),
        (assign, ":count", 0),
        (try_for_range, ":village", villages_begin, villages_end),
          (party_slot_eq, ":village", slot_village_bound_center, ":fief"),
          (str_store_party_name, s2, ":village"),
          (val_add, ":count", 1),
          (try_begin),
            (eq, ":count", 1),
            (str_store_string_reg, s3, s2),
          (else_try),
            (str_store_string, s3, "@{s3},{s2}"),
          (try_end),
        (try_end),
        (try_begin),
          (party_slot_eq, ":fief", slot_party_type, spt_town),
          (str_store_string, s1, "@Town of {s1}+{s3}"),
        (else_try),
          (str_store_string, s1, "@{s1}+{s3}"),
        (try_end),
      (try_end),
      (party_get_slot, ":lord", ":fief", slot_town_lord),
      (call_script, "script_store_troop_name", s2, ":lord"),
      (call_script, "script_troop_get_player_relation", ":lord"),
      (call_script, "script_describe_troop_relation", s3, reg0),
      (call_script, "script_get_number_of_hero_centers", ":lord"),
      (try_begin),
        (eq, ":lord", "trp_player"),
        (str_store_string, s2, "@{s2}, {reg0?{reg0}:no} fiefs"),
      (else_try),
        (str_store_string, s2, "@{s2}, {reg0?{reg0}:no} fiefs, {s3}"),
      (try_end),
    ],
    "{s1} ({s2})", "chancellor_fiefs_who", [(store_repeat_object, "$assign_fief")]
  ],
]
