MENUS = [
(
    "give_center_to_player", mnf_scale_picture,
    "Your lord offers to extend your fiefs! {s1} sends word that he is willing to grant {s2} to you in payment for your loyal service, adding it to your holdings.{reg4? A castle grant is a high honor: it carries real military power, noble obligations, and command over its attached villages.:} What is your answer?",
    "none",
    [(set_background_mesh, "mesh_pic_messenger"),
     (str_store_string, s1, "@your lord"),
     (str_store_string, s2, "@the disputed fief"),
     (assign, reg4, 0),
     (try_begin),
       (is_between, "$g_center_to_give_to_player", centers_begin, centers_end),
       (store_faction_of_party, ":center_faction", "$g_center_to_give_to_player"),
       (faction_get_slot, ":faction_leader", ":center_faction", slot_faction_leader),
       (try_begin),
         (is_between, ":faction_leader", kingdom_heroes_begin, kingdom_heroes_end),
         (call_script, "script_store_troop_name", s1, ":faction_leader"),
       (try_end),
       (str_store_party_name, s2, "$g_center_to_give_to_player"),
       (try_begin),
         (party_slot_eq, "$g_center_to_give_to_player", slot_party_type, spt_castle),
         (assign, reg4, 1),
       (try_end),
     (try_end),
    ],
    [
      ("give_center_to_player_accept", [(is_between, "$g_center_to_give_to_player", centers_begin, centers_end)], "Accept the offer.",
       [(call_script, "script_give_center_to_lord", "$g_center_to_give_to_player", "trp_player", 0),
        (jump_to_menu, "mnu_give_center_to_player_2"),
        ]),
      ("give_center_to_player_reject", [(is_between, "$g_center_to_give_to_player", centers_begin, centers_end)], "Reject. You have no interest in holding {s2}.",
       [(party_set_slot, "$g_center_to_give_to_player", slot_town_lord, stl_rejected_by_player),
        (change_screen_return),
        ]),
      ("give_center_to_player_invalid_return", [(neg|is_between, "$g_center_to_give_to_player", centers_begin, centers_end)], "Let the matter pass.",
       [(assign, "$g_center_to_give_to_player", -1),
        (change_screen_return),
        ]),
    ],
  ),
]
