SCRIPTS = [
("decide_faction_ai_collect_marshall_context",
    [
      (store_script_param_1, ":faction_no"),
      (store_script_param_2, ":ambition"),

      (assign, ":faction_marshall_party", -1),
      (assign, ":faction_marshall_army_strength", 1), # keep non-zero to avoid bad divs
      (assign, ":faction_marshall_num_followers", 1),

      (try_begin),
        (neq, "fac_player_supporters_faction", ":faction_no"),
        (call_script, "script_select_faction_marshall", ":faction_no"),
        (assign, ":faction_marshall", reg0),
      (else_try),
        (faction_get_slot, ":faction_marshall", ":faction_no", slot_faction_marshall),
      (try_end),

      (assign, ":marshall_changed", 0),
      (try_begin),
        (neg|faction_slot_eq, ":faction_no", slot_faction_marshall, ":faction_marshall"),
        (assign, ":marshall_changed", 1),
        (eq, "$players_kingdom", ":faction_no"),
        (call_script, "script_store_troop_name_link", s1, ":faction_marshall"),
        (str_store_faction_name_link, s2, ":faction_no"),
        (try_begin),
          (eq, "$g_sod_hide_messages", 0),
          (display_message, "@{s1} is the new marshall of {s2}.", trivia_color),
        (try_end),
        (call_script, "script_check_and_finish_active_army_quests_for_faction", ":faction_no"),
      (try_end),

      (faction_set_slot, ":faction_no", slot_faction_marshall, ":faction_marshall"),

      (try_begin),
        (gt, ":faction_marshall", 0),
        (troop_get_slot, ":faction_marshall_party", ":faction_marshall", slot_troop_leaded_party),
        (gt, ":faction_marshall_party", 0),
        (party_get_slot, ":faction_marshall_army_strength", ":faction_marshall_party", slot_party_cached_strength),
        (troop_get_slot, ":self_confidence", ":faction_marshall", slot_lord_self_confidence),
        (val_mul, ":faction_marshall_army_strength", ":self_confidence"),
        (val_div, ":faction_marshall_army_strength", 100),
        (party_get_slot, ":follower_strength", ":faction_marshall_party", slot_party_follower_strength),
        (val_add, ":faction_marshall_army_strength", ":follower_strength"),
        (try_for_range, ":cur_troop", kingdom_heroes_begin, kingdom_heroes_end),
          (troop_slot_eq, ":cur_troop", slot_troop_occupation, slto_kingdom_hero),
          (troop_get_slot, ":cur_party", ":cur_troop", slot_troop_leaded_party),
          (gt, ":cur_party", 0),
          (party_is_active, ":cur_party"),
          (party_slot_eq, ":cur_party", slot_party_commander_party, ":faction_marshall_party"),
          (val_add, ":faction_marshall_num_followers", 1),
        (try_end),
      (try_end),

      (faction_get_slot, ":marshall_num_old_followers", ":faction_no", slot_faction_ai_offensive_max_followers),
      (val_max, ":marshall_num_old_followers", 1),
      (store_mul, ":offensive_rating", ":faction_marshall_num_followers", 100),
      (val_mul, ":offensive_rating", ":faction_marshall_num_followers"),
      (val_div, ":offensive_rating", ":marshall_num_old_followers"),
      (val_div, ":offensive_rating", ":marshall_num_old_followers"),
      (val_min, ":offensive_rating", 100),

      (store_mul, ":offensive_rating_bonus", ":ambition", 5),
      (store_add, ":factor", 100, ":offensive_rating_bonus"),
      (val_mul, ":offensive_rating", ":factor"),
      (val_div, ":offensive_rating", 100),

      (assign, reg0, ":faction_marshall"),
      (assign, reg1, ":marshall_changed"),
      (assign, reg2, ":faction_marshall_party"),
      (assign, reg3, ":faction_marshall_army_strength"),
      (assign, reg4, ":faction_marshall_num_followers"),
      (assign, reg5, ":marshall_num_old_followers"),
      (assign, reg6, ":offensive_rating"),
  ]),
]
