try:
    from src.compiler import *
except ImportError:
    from src.module_system import *

from src.constants.module_constants import *

SCRIPTS = [
    (
        "diplomacy_start_peace_between_kingdoms",
        [
            (store_script_param_1, ":faction_a"),
            (store_script_param_2, ":faction_b"),
            (store_script_param, ":initializing_war_peace_cond", 3),

            (try_begin),
                (neq, ":faction_a", ":faction_b"),
                (neg|is_between, ":faction_a", rebel_factions_begin, rebel_factions_end),
                (neg|is_between, ":faction_b", rebel_factions_begin, rebel_factions_end),

                (store_current_day, ":current_day"),
                (assign, ":truce_day", ":current_day"),
                (val_add, ":truce_day", 21),

                (assign, ":truce_slot_ab", slot_faction_truce_player_realm),
                (val_add, ":truce_slot_ab", ":faction_b"),
                (assign, ":truce_slot_ba", slot_faction_truce_player_realm),
                (val_add, ":truce_slot_ba", ":faction_a"),

                (try_begin),
                    (is_between, ":truce_slot_ab", slot_faction_truce_player_realm, faction_truce_slots_end),
                    (faction_get_slot, ":existing_truce_ab", ":faction_a", ":truce_slot_ab"),
                    (gt, ":existing_truce_ab", ":truce_day"),
                    (assign, ":truce_day", ":existing_truce_ab"),
                (try_end),
                (try_begin),
                    (is_between, ":truce_slot_ba", slot_faction_truce_player_realm, faction_truce_slots_end),
                    (faction_get_slot, ":existing_truce_ba", ":faction_b", ":truce_slot_ba"),
                    (gt, ":existing_truce_ba", ":truce_day"),
                    (assign, ":truce_day", ":existing_truce_ba"),
                (try_end),

                (try_begin),
                    (is_between, ":truce_slot_ab", slot_faction_truce_player_realm, faction_truce_slots_end),
                    (faction_set_slot, ":faction_a", ":truce_slot_ab", ":truce_day"),
                (try_end),
                (try_begin),
                    (is_between, ":truce_slot_ba", slot_faction_truce_player_realm, faction_truce_slots_end),
                    (faction_set_slot, ":faction_b", ":truce_slot_ba", ":truce_day"),
                (try_end),

                (try_begin),
                    (neq, ":faction_a", "fac_kingdom_6"),
                    (neq, ":faction_b", "fac_kingdom_6"),
                    (call_script, "script_sod_diplomacy_find_treaty_slot", ":faction_a", ":faction_b"),
                    (assign, ":treaty_slot", reg0),
                    (gt, ":treaty_slot", 0),
                    (store_add, ":type_slot", ":treaty_slot", 1),
                    (store_add, ":until_slot", ":treaty_slot", 2),
                    (store_add, ":strength_slot", ":treaty_slot", 3),
                    (faction_set_slot, ":faction_a", ":treaty_slot", ":faction_b"),
                    (faction_set_slot, ":faction_a", ":type_slot", sod_diplomacy_treaty_truce),
                    (faction_set_slot, ":faction_a", ":until_slot", ":truce_day"),
                    (faction_set_slot, ":faction_a", ":strength_slot", 60),
                    (call_script, "script_sod_diplomacy_find_treaty_slot", ":faction_b", ":faction_a"),
                    (assign, ":reverse_treaty_slot", reg0),
                    (gt, ":reverse_treaty_slot", 0),
                    (store_add, ":reverse_type_slot", ":reverse_treaty_slot", 1),
                    (store_add, ":reverse_until_slot", ":reverse_treaty_slot", 2),
                    (store_add, ":reverse_strength_slot", ":reverse_treaty_slot", 3),
                    (faction_set_slot, ":faction_b", ":reverse_treaty_slot", ":faction_a"),
                    (faction_set_slot, ":faction_b", ":reverse_type_slot", sod_diplomacy_treaty_truce),
                    (faction_set_slot, ":faction_b", ":reverse_until_slot", ":truce_day"),
                    (faction_set_slot, ":faction_b", ":reverse_strength_slot", 60),
                    (faction_set_slot, ":faction_a", slot_faction_diplomacy_last_treaty_day, ":current_day"),
                    (faction_set_slot, ":faction_b", slot_faction_diplomacy_last_treaty_day, ":current_day"),
                (try_end),
                (store_sub, reg39, ":truce_day", ":current_day"),

                (store_relation, ":current_relation", ":faction_a", ":faction_b"),
                (val_max, ":current_relation", 0),
                (set_relation, ":faction_a", ":faction_b", ":current_relation"),

                (faction_get_slot, ":weariness_a", ":faction_a", slot_faction_diplomacy_war_weariness),
                (val_sub, ":weariness_a", 12),
                (val_clamp, ":weariness_a", 0, 101),
                (faction_set_slot, ":faction_a", slot_faction_diplomacy_war_weariness, ":weariness_a"),
                (faction_get_slot, ":weariness_b", ":faction_b", slot_faction_diplomacy_war_weariness),
                (val_sub, ":weariness_b", 12),
                (val_clamp, ":weariness_b", 0, 101),
                (faction_set_slot, ":faction_b", slot_faction_diplomacy_war_weariness, ":weariness_b"),

                (faction_set_slot, ":faction_a", slot_faction_last_refused_peace, 0),
                (faction_set_slot, ":faction_b", slot_faction_last_refused_peace, 0),
                (faction_set_slot, ":faction_a", slot_faction_diplomacy_war_reason, sod_diplomacy_war_reason_unknown),
                (faction_set_slot, ":faction_a", slot_faction_diplomacy_war_reason_target, 0),
                (faction_set_slot, ":faction_b", slot_faction_diplomacy_war_reason, sod_diplomacy_war_reason_unknown),
                (faction_set_slot, ":faction_b", slot_faction_diplomacy_war_reason_target, 0),

                (call_script, "script_sod_process_prisoner_exchange_between_factions", ":faction_a", ":faction_b", sod_diplomacy_treaty_truce),

                (try_begin),
                    (eq, ":initializing_war_peace_cond", 0),
                    (this_or_next|eq, ":faction_a", fac_player_supporters_faction),
                    (eq, ":faction_b", fac_player_supporters_faction),
                    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_honorable_peace, 3),
                    (call_script, "script_sod_strategy_advisor_note_treaty_signed", ":faction_a", ":faction_b", sod_diplomacy_treaty_truce),
                (try_end),

                (call_script, "script_event_kingdom_make_peace_with_kingdom", ":faction_a", ":faction_b"),

                (try_begin),
                    (eq, ":initializing_war_peace_cond", 0),
                    (this_or_next|eq, ":faction_a", fac_player_supporters_faction),
                    (eq, ":faction_b", fac_player_supporters_faction),
                    (str_store_faction_name, s1, ":faction_a"),
                    (str_store_faction_name, s2, ":faction_b"),
                    (display_message, "@Peace has been concluded between {s1} and {s2}. A truce is expected to hold for {reg39} days.", 0x66CCFF),
                (else_try),
                    (eq, ":initializing_war_peace_cond", 0),
                    (this_or_next|eq, ":faction_a", "fac_kingdom_6"),
                    (eq, ":faction_b", "fac_kingdom_6"),
                    (str_store_faction_name, s1, ":faction_a"),
                    (str_store_faction_name, s2, ":faction_b"),
                    (display_message, "@Diplomatic dispatch: {s1} and {s2} have paused hostilities for {reg39} days, though the Imperial front remains unstable.", 0x66CCFF),
                (try_end),
            (try_end),
        ],
    ),
]
