try:
    from src.compiler import *
except ImportError:
    from src.module_system import *

from src.constants.module_constants import *

SCRIPTS = [
    (
        "diplomacy_start_war_between_kingdoms",
        [
            (store_script_param_1, ":faction_a"),
            (store_script_param_2, ":faction_b"),
            (store_script_param, ":initializing_war_peace_cond", 3),
            (assign, reg0, 0),

            (try_begin),
                (neq, ":faction_a", ":faction_b"),
                (this_or_next|eq, ":faction_a", fac_player_supporters_faction),
                (faction_slot_eq, ":faction_a", slot_faction_state, sfs_active),
                (this_or_next|eq, ":faction_b", fac_player_supporters_faction),
                (faction_slot_eq, ":faction_b", slot_faction_state, sfs_active),
                (neg|is_between, ":faction_a", rebel_factions_begin, rebel_factions_end),
                (neg|is_between, ":faction_b", rebel_factions_begin, rebel_factions_end),

                (store_current_day, ":current_day"),
                (store_relation, ":starting_relation", ":faction_a", ":faction_b"),
                (assign, ":already_at_war", 0),
                (try_begin),
                    (lt, ":starting_relation", 0),
                    (assign, ":already_at_war", 1),
                (try_end),
                (assign, ":war_reason", sod_diplomacy_war_reason_unknown),
                (try_begin),
                    (eq, ":already_at_war", 0),
                    (call_script, "script_sod_diplomacy_break_treaty", ":faction_a", ":faction_b", 1),
                    (try_begin),
                        (eq, reg0, 1),
                        (assign, ":war_reason", sod_diplomacy_war_reason_broken_treaty),
                    (try_end),
                (try_end),

                (assign, ":truce_slot_ab", slot_faction_truce_player_realm),
                (val_add, ":truce_slot_ab", ":faction_b"),
                (val_sub, ":truce_slot_ab", "fac_player_supporters_faction"),
                (assign, ":truce_slot_ba", slot_faction_truce_player_realm),
                (val_add, ":truce_slot_ba", ":faction_a"),
                (val_sub, ":truce_slot_ba", "fac_player_supporters_faction"),

                (try_begin),
                    (is_between, ":truce_slot_ab", slot_faction_truce_player_realm, faction_truce_slots_end),
                    (faction_get_slot, ":existing_truce_ab", ":faction_a", ":truce_slot_ab"),
                    (try_begin),
                        (eq, ":already_at_war", 0),
                        (gt, ":existing_truce_ab", ":current_day"),
                        (assign, ":war_reason", sod_diplomacy_war_reason_broken_treaty),
                        (try_begin),
                            (eq, reg0, 0),
                            (eq, ":faction_a", fac_player_supporters_faction),
                            (call_script, "script_sod_diplomacy_apply_memory", ":faction_b", sod_diplomacy_memory_broken_truce, 1),
                        (else_try),
                            (eq, reg0, 0),
                            (eq, ":faction_b", fac_player_supporters_faction),
                            (call_script, "script_sod_diplomacy_apply_memory", ":faction_a", sod_diplomacy_memory_broken_truce, 1),
                        (try_end),
                    (try_end),
                    (faction_set_slot, ":faction_a", ":truce_slot_ab", 0),
                (try_end),
                (try_begin),
                    (is_between, ":truce_slot_ba", slot_faction_truce_player_realm, faction_truce_slots_end),
                    (faction_get_slot, ":existing_truce_ba", ":faction_b", ":truce_slot_ba"),
                    (try_begin),
                        (eq, ":already_at_war", 0),
                        (gt, ":existing_truce_ba", ":current_day"),
                        (assign, ":war_reason", sod_diplomacy_war_reason_broken_treaty),
                    (try_end),
                    (faction_set_slot, ":faction_b", ":truce_slot_ba", 0),
                (try_end),

                (store_relation, ":current_relation", ":faction_a", ":faction_b"),
                (val_min, ":current_relation", -40),
                (set_relation, ":faction_a", ":faction_b", ":current_relation"),

                (try_begin),
                    (eq, ":already_at_war", 0),
                    (eq, ":initializing_war_peace_cond", 0),
                    (faction_set_slot, ":faction_a", slot_faction_last_big_offensive, ":current_day"),
                (try_end),

                (try_begin),
                (eq, ":already_at_war", 0),
                (faction_set_slot, ":faction_a", slot_faction_last_started_war, ":faction_b"),
                (faction_set_slot, ":faction_a", slot_faction_last_started_war_date, ":current_day"),
                (faction_set_slot, ":faction_b", slot_faction_last_started_war, ":faction_a"),
                (faction_set_slot, ":faction_b", slot_faction_last_started_war_date, ":current_day"),
                (call_script, "script_sod_diplomacy_note_war_reason", ":faction_a", ":faction_b", ":war_reason"),
                (call_script, "script_sod_diplomacy_describe_war_reason_to_s39", ":faction_a"),
                (try_end),
                (try_begin),
                    (eq, ":already_at_war", 0),
                    (eq, ":initializing_war_peace_cond", 0),
                    (eq, ":war_reason", sod_diplomacy_war_reason_broken_treaty),
                    (this_or_next|eq, ":faction_a", fac_player_supporters_faction),
                    (eq, ":faction_b", fac_player_supporters_faction),
                    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_diplomacy_betrayal, 4),
                (try_end),
                (try_begin),
                    (eq, ":already_at_war", 0),
                    (eq, ":initializing_war_peace_cond", 0),
                    (call_script, "script_sod_diplomacy_process_defensive_pacts_on_war", ":faction_a", ":faction_b"),
                (try_end),

                (call_script, "script_update_faction_notes", ":faction_a"),
                (call_script, "script_update_faction_notes", ":faction_b"),
                (call_script, "script_update_faction_traveler_notes", ":faction_a"),
                (call_script, "script_update_faction_traveler_notes", ":faction_b"),

                (try_begin),
                    (eq, ":already_at_war", 0),
                    (eq, ":initializing_war_peace_cond", 0),
                    (this_or_next|eq, ":faction_a", fac_player_supporters_faction),
                    (eq, ":faction_b", fac_player_supporters_faction),
                    (str_store_faction_name, s1, ":faction_a"),
                    (str_store_faction_name, s2, ":faction_b"),
                    (display_message, "@War has broken out between {s1} and {s2}. {s39}", 0xFF4444),
                (else_try),
                    (eq, ":already_at_war", 0),
                    (eq, ":initializing_war_peace_cond", 0),
                    (eq, "$g_sod_debug", 1),
                    (this_or_next|eq, ":faction_a", "fac_kingdom_6"),
                    (this_or_next|eq, ":faction_b", "fac_kingdom_6"),
                    (eq, ":war_reason", sod_diplomacy_war_reason_broken_treaty),
                    (eq, "$g_sod_debug", 1),
                    (str_store_faction_name, s1, ":faction_a"),
                    (str_store_faction_name, s2, ":faction_b"),
                    (display_message, "@Diplomatic dispatch: {s1} and {s2} are at war. {s39}", 0xFF8844),
                (try_end),
                (try_begin),
                    (eq, ":already_at_war", 0),
                    (assign, reg0, 1),
                (else_try),
                    (assign, reg0, 0),
                (try_end),
            (try_end),
        ],
    ),
]
