SCRIPTS = [
("player_join_faction",
      [
        (store_script_param, ":faction_no", 1),
        (assign, "$players_kingdom", ":faction_no"),
        (faction_set_slot, "fac_player_supporters_faction", slot_faction_ai_state, sfai_default),
        (assign, "$players_oath_renounced_against_kingdom", 0),
        (assign, "$players_oath_renounced_given_center", 0),
        (assign, "$players_oath_renounced_begin_time", 0),
        (try_for_range, ":other_kingdom", kingdoms_begin, kingdoms_end),
          (faction_slot_eq, ":other_kingdom", slot_faction_state, sfs_active),
          (neq, ":other_kingdom", "fac_player_supporters_faction"),
          (try_begin),
            (neq, ":other_kingdom", ":faction_no"),
            (store_relation, ":other_kingdom_reln", ":other_kingdom", ":faction_no"),
          (else_try),
            (store_relation, ":other_kingdom_reln", "fac_player_supporters_faction", ":other_kingdom"),
            (val_max, ":other_kingdom_reln", 12),
          (try_end),
          (call_script, "script_set_player_relation_with_faction", ":other_kingdom", ":other_kingdom_reln"),
        (try_end),
        (try_for_range, ":cur_center", centers_begin, centers_end),
          #Give center to kingdom if player is the owner
          (party_slot_eq, ":cur_center", slot_town_lord, "trp_player"),
          (party_set_faction, ":cur_center", ":faction_no"),
        (try_end),
        (try_for_range, ":quest_no", lord_quests_begin, lord_quests_end),
          (check_quest_active, ":quest_no"),
          (quest_get_slot, ":quest_giver_troop", ":quest_no", slot_quest_giver_troop),
          (store_troop_faction, ":quest_giver_faction", ":quest_giver_troop"),
          (store_relation, ":quest_giver_faction_relation", "fac_player_supporters_faction", ":quest_giver_faction"),
          (lt, ":quest_giver_faction_relation", 0),
          (call_script, "script_abort_quest", ":quest_no", 0),
        (try_end),
        (try_begin),
          (neq, ":faction_no", "fac_player_supporters_faction"),
          (faction_set_slot, "fac_player_supporters_faction", slot_faction_state, sfs_inactive),
          (faction_set_slot, "fac_player_supporters_faction", slot_faction_leader, "trp_player"),
        (try_end),
        (call_script, "script_store_average_center_value_per_faction"),
        (call_script, "script_update_all_notes"),
        (assign, "$g_recalculate_ais", 1),
    ]),
]
