SCRIPTS = [
("player_leave_faction",
      [
        (store_script_param, ":give_back_fiefs", 1),
        (call_script, "script_check_and_finish_active_army_quests_for_faction", "$players_kingdom"),
        (assign, ":old_kingdom", "$players_kingdom"),
        (assign, ":old_has_homage", "$player_has_homage"),
        (assign, "$players_kingdom", 0),
        (assign, "$player_has_homage", 0),
        (try_begin),
          (neq, ":give_back_fiefs", 0),
          (try_for_range, ":cur_center", centers_begin, centers_end),
            (party_slot_eq, ":cur_center", slot_town_lord, "trp_player"),
            (call_script, "script_give_center_to_faction", ":cur_center", ":old_kingdom"),
          (try_end),
        (else_try),
          (try_for_range, ":cur_center", centers_begin, centers_end),
            (party_slot_eq, ":cur_center", slot_town_lord, "trp_player"),
            (call_script, "script_give_center_to_faction", ":cur_center", "fac_player_supporters_faction"),
          (try_end),
          (try_for_range, ":cur_center", villages_begin, villages_end),
            (party_get_slot, ":cur_bound_center", ":cur_center", slot_village_bound_center),
            (party_slot_eq, ":cur_center", slot_town_lord, "trp_player"),
            (neg|party_slot_eq, ":cur_bound_center", slot_town_lord, "trp_player"),
            (call_script, "script_give_center_to_faction", ":cur_center", ":old_kingdom"),
          (try_end),
          (store_relation, ":reln", "fac_player_supporters_faction", ":old_kingdom"),
          (store_sub, ":req_dif", -40, ":reln"),
          (call_script, "script_change_player_relation_with_faction", ":old_kingdom", ":req_dif"),
        (try_end),
        (try_begin),
          (eq, ":old_has_homage", 1),
          (faction_get_slot, ":faction_leader", ":old_kingdom", slot_faction_leader),
          (call_script, "script_change_player_relation_with_troop", ":faction_leader", -20),
        (try_end),
        (call_script, "script_update_all_notes"),
        (assign, "$g_recalculate_ais", 1),
    ]),
]
