try:
    from src.compiler import *
except ImportError:
    from src.module_system import *

from src.constants.module_constants import *

SCRIPTS = [
("update_faction_notes",
      [(store_script_param, ":faction_no", 1),
		(try_begin),
			(eq, ":faction_no", "fac_black_khergits"),
			(str_store_faction_name, s5, ":faction_no"),
			(call_script, "script_sod_black_khergits_describe_status_to_s27"),
			(str_store_string, s49, "@{s5} are a moving horde, not a court or a hireling guild. Their strength gathers around a roaming camp that feeds on wealthy roads and settled borders."),

			(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
			(add_faction_note_from_sreg, ":faction_no", 0, s27, 0),
			(str_store_string, s49, "@^Destroying raider bands weakens the horde for a time; disrupting the camp itself delays the next wave. Tribute may buy passage, but it also keeps the camp supplied."),

			(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
			(add_faction_note_tableau_mesh, ":faction_no", "tableau_faction_note_mesh_banner"),
		(else_try),
			(this_or_next|is_between, ":faction_no", "fac_sod_merc_guild1", "fac_sod_merc_guild7"),
			(eq, ":faction_no", "fac_sod_merc_guild7"),
			(faction_get_slot, ":faction_leader", ":faction_no", slot_guild_master),
			(faction_get_slot, ":faction_base", ":faction_no", slot_guild_base),
			(party_get_slot, ":faction_marshal", ":faction_base", slot_town_lord),
			(call_script, "script_update_faction_intelligence_report", ":faction_no", 0),
			(str_store_faction_name, s5, ":faction_no"),
			(str_store_troop_name_link, s6, ":faction_leader"),
			(str_store_troop_name_link, s7, ":faction_marshal"),
			(str_store_string, s8, "@unknown grounds"),
			(try_begin),
				(gt, ":faction_base", 0),
				(str_store_party_name_link, s8, ":faction_base"),
			(try_end),
			(assign, reg1, 0),
			(try_for_range, ":employer", kingdoms_begin, kingdoms_end),
				(faction_slot_eq, ":employer", slot_faction_merc_pact, ":faction_no"),
				(str_store_faction_name_link, s9, ":employer"),
				(assign, reg1, 1),
			(try_end),
			(try_begin),
				(eq, ":faction_no", "fac_sod_merc_guild6"),
				(str_store_troop_name_link, s7, "trp_slaver_leader_1"),
				(call_script, "script_sod_slavers_describe_status_to_s20"),
				(assign, reg20, 1),
				(str_store_string, s9, "@^The Slavers are too large and disorganized to be trusted with pacts."),
			(else_try),
				(eq, ":faction_no", "fac_sod_merc_guild3"),
				(call_script, "script_sod_elephant_guard_describe_status_to_s21"),
				(assign, reg20, 1),
				(str_store_string, s9, "@^It is currently employed by {s9}."),
			(else_try),
				(str_clear, s20),
				(assign, reg20, 0),
				(str_store_string, s9, "@^It is currently employed by {s9}."),
			(try_end),
			(str_store_string, s49, "@{s5} is a mercenary guild ruled by {s6}.^Its headquarters are at {s8}.^Its field marshal is {s7}.{s9}"),

			(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
			(try_begin),
				(eq, reg20, 1),
				(add_faction_note_from_sreg, ":faction_no", 0, s20, 0),
			(try_end),
			(try_begin),
				(eq, ":faction_no", "fac_sod_merc_guild1"),
				(call_script, "script_sod_black_army_describe_status_to_s24"),
				(add_faction_note_from_sreg, ":faction_no", 0, s24, 0),
			(try_end),
			(try_begin),
				(eq, ":faction_no", "fac_sod_merc_guild2"),
				(call_script, "script_sod_conquistador_describe_status_to_s25"),
				(add_faction_note_from_sreg, ":faction_no", 0, s25, 0),
			(try_end),
			(try_begin),
				(eq, ":faction_no", "fac_sod_merc_guild4"),
				# Hearth status text is produced by the shared Jotnar status helper.
				(call_script, "script_sod_jotnar_describe_status_to_s22"),
				(add_faction_note_from_sreg, ":faction_no", 0, s22, 0),
			(try_end),
			(try_begin),
				(eq, ":faction_no", "fac_sod_merc_guild5"),
				(call_script, "script_sod_serpent_host_describe_status_to_s26"),
				(add_faction_note_from_sreg, ":faction_no", 0, s26, 0),
			(try_end),
			(try_begin),
				(eq, ":faction_no", "fac_sod_merc_guild7"),
				(call_script, "script_sod_boar_clan_describe_status_to_s23"),
				(add_faction_note_from_sreg, ":faction_no", 0, s23, 0),
			(try_end),
			(str_store_string, s49, "@^Strategic intelligence is limited for mercenary guilds, but their contracts can still reshape a campaign overnight."),

			(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
			(add_faction_note_tableau_mesh, ":faction_no", "tableau_faction_note_mesh_banner"),
		(else_try),
          (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
          (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
          (faction_get_slot, ":faction_leader", ":faction_no", slot_faction_leader),
          (str_store_faction_name_link, s5, ":faction_no"),
          (call_script, "script_store_troop_name_link", s6, ":faction_leader"),
          (call_script, "script_update_faction_intelligence_report", ":faction_no", 0),

			(assign, ":cached_score", reg0),
			(assign, ":cached_pressure", reg1),
			(assign, ":power_rank", reg2),
			(assign, ":growth_band", reg3),
			(assign, ":num_centers", reg4),
			(assign, ":num_enemies", reg5),
			(assign, ":num_truces", reg6),
			(assign, ":marshal_present", reg7),
			(assign, ":num_vassals", reg8),

			(assign, reg23, ":cached_score"),
			(assign, reg24, ":cached_pressure"),
			(assign, reg25, ":num_centers"),
			(assign, reg26, ":num_enemies"),
			(assign, reg27, ":num_truces"),
			(assign, reg28, ":num_vassals"),

          (assign, ":num_centers_built", 0),
          (str_store_string, s8, "@nowhere"),
          (try_begin),
            (gt, ":num_centers", 0),
            (try_for_range_backwards, ":cur_center", centers_begin, centers_end),
              (store_faction_of_party, ":center_faction", ":cur_center"),
              (eq, ":center_faction", ":faction_no"),
              (try_begin),
                (eq, ":num_centers_built", 0),
                (str_store_party_name_link, s8, ":cur_center"),
              (else_try),
                (eq, ":num_centers_built", 1),
                (str_store_party_name_link, s7, ":cur_center"),
                (str_store_string, s8, "@{s7} and {s8}"),
              (else_try),
                (str_store_party_name_link, s7, ":cur_center"),
                (str_store_string, s8, "@{s7}, {s8}"),
              (try_end),
              (val_add, ":num_centers_built", 1),
            (try_end),
          (try_end),

          (assign, ":num_members", 0),
          (str_store_string, s10, "@noone"),
          (try_begin),
            (gt, ":num_vassals", 0),
            (try_for_range_backwards, ":cur_troop", kingdom_heroes_begin, kingdom_heroes_end),
              (store_troop_faction, ":troop_faction", ":cur_troop"),
              (eq, ":troop_faction", ":faction_no"),
              (neq, ":cur_troop", ":faction_leader"),
              (troop_slot_eq, ":cur_troop", slot_troop_occupation, slto_kingdom_hero),
              (try_begin),
                (eq, ":num_members", 0),
                (call_script, "script_store_troop_name_link", s10, ":cur_troop"),
              (else_try),
                (eq, ":num_members", 1),
                (call_script, "script_store_troop_name_link", s9, ":cur_troop"),
                (str_store_string, s10, "@{s9} and {s10}"),
              (else_try),
                (call_script, "script_store_troop_name_link", s9, ":cur_troop"),
                (str_store_string, s10, "@{s9}, {s10}"),
              (try_end),
              (val_add, ":num_members", 1),
            (try_end),
            (try_begin),
              (eq, "$players_kingdom", ":faction_no"),
              (neq, "trp_player", ":faction_leader"),
              (troop_slot_eq, "trp_player", slot_troop_occupation, slto_kingdom_hero),
              (try_begin),
                (eq, ":num_members", 0),
                (call_script, "script_store_troop_name_link", s10, "trp_player"),
              (else_try),
                (eq, ":num_members", 1),
                (call_script, "script_store_troop_name_link", s9, "trp_player"),
                (str_store_string, s10, "@{s9} and {s10}"),
              (else_try),
                (call_script, "script_store_troop_name_link", s9, "trp_player"),
                (str_store_string, s10, "@{s9}, {s10}"),
              (try_end),
              (val_add, ":num_members", 1),
            (try_end),
          (try_end),

          (str_store_string, s12, "@no known enemies"),
          (assign, ":num_enemies_built", 0),
          (try_begin),
            (gt, ":num_enemies", 0),
            (try_for_range_backwards, ":cur_faction", kingdoms_begin, kingdoms_end),
              (faction_slot_eq, ":cur_faction", slot_faction_state, sfs_active),
              (store_relation, ":cur_relation", ":faction_no", ":cur_faction"),
              (lt, ":cur_relation", 0),
              (try_begin),
                (eq, ":num_enemies_built", 0),
                (str_store_faction_name_link, s12, ":cur_faction"),
              (else_try),
                (eq, ":num_enemies_built", 1),
                (str_store_faction_name_link, s11, ":cur_faction"),
                (str_store_string, s12, "@{s11} and {s12}"),
              (else_try),
                (str_store_faction_name_link, s11, ":cur_faction"),
                (str_store_string, s12, "@{s11}, {s12}"),
              (try_end),
              (val_add, ":num_enemies_built", 1),
            (try_end),
          (try_end),

		 (try_begin),
		    (eq, ":power_rank", 0),
			(str_store_string, s21, "@the first"),
			(else_try),
			(eq, ":power_rank", 1),
			(str_store_string, s21, "@the second"),
			(else_try),
			(eq, ":power_rank", 2),
			(str_store_string, s21, "@the third"),
			(else_try),
			(str_store_string, s21, "@a minor"),
		  (try_end),

          (try_begin),
            (eq, ":growth_band", 0),
            (str_store_string, s22, "@growing fast"),
          (else_try),
            (eq, ":growth_band", 1),
            (str_store_string, s22, "@growing"),
          (else_try),
            (eq, ":growth_band", 2),
            (str_store_string, s22, "@stable"),
		  (else_try),
		    (eq, ":growth_band", 3),
			(str_store_string, s22, "@declining"),
	      (else_try),
            (str_store_string, s22, "@declining fast"),
          (try_end),

		(str_clear, s15),
		(store_current_day, ":cur_day"),
		(str_store_string, s15, "@^They have no active truces."),
		(try_begin),
			(gt, ":num_truces", 0),
			(str_clear, s15),
			(try_for_range, ":slot_no", faction_truce_slots_begin, faction_truce_slots_end),
			(faction_get_slot, ":truce_day", ":faction_no", ":slot_no"),

			(try_begin),
			(gt, ":truce_day", ":cur_day"),
			(assign, reg1, ":truce_day"),
			(store_sub, ":kingdom_no", ":slot_no", faction_truce_slots_begin),
			(val_add, ":kingdom_no", "fac_player_supporters_faction"),
			(str_store_faction_name_link, s33, ":kingdom_no"),
			   (try_begin),
			   (eq, ":kingdom_no", "fac_player_supporters_faction"),
			   (str_store_string, s15, "@^You have a peace agreement with {s5}. It ends on day {reg1}."),
			   (else_try),
			   (str_store_string, s15, "@{s15}^They have a peace agreement with {s33}. It ends on day {reg1}."),
			    (try_end),
			(try_end),
		(try_end),
		(try_begin),
			(eq, ":num_truces", 0),
			(str_store_string, s15, "@^They have no active truces."),
		(try_end),

		(assign, reg21, 0),
		(try_begin),
			(faction_get_slot, ":mercs", ":faction_no", slot_faction_merc_pact),
			(gt, ":mercs", 0),
			(str_store_faction_name_link, s16, ":mercs"),
			(str_store_string, s16, "@It's supported by {s16}."),
			(assign, reg21, 1),
		(try_end),

		(assign, reg22, 0),
		(try_begin),
			(eq, ":marshal_present", 1),
			(faction_get_slot, ":marshall", ":faction_no", slot_faction_marshall),
			(gt, ":marshall", 0),
			(neq, ":marshall", ":faction_leader"),
			(call_script, "script_store_troop_name_link", s17, ":marshall"),
			(str_store_string, s17, "@Its Field Marshal is {s17}."),
			(assign, reg22, 1),
		(try_end),

		(try_begin),
			(ge, ":cached_score", 35),
			(lt, ":cached_pressure", 20),
			(str_store_string, s18, "@It currently has strong momentum and can press its advantage."),
		(else_try),
			(lt, ":cached_score", -15),
			(ge, ":cached_pressure", 20),
			(str_store_string, s18, "@It is under strain and may be vulnerable to pressure."),
		(else_try),
			(str_store_string, s18, "@It is broadly stable, but neither dominant nor collapsing."),
		(try_end),

		(call_script, "script_sod_law_recalculate_faction_law_modifiers", ":faction_no"),
		(call_script, "script_sod_law_count_active_for_faction", ":faction_no"),
		(assign, reg29, reg0),
		(faction_get_slot, reg30, ":faction_no", slot_faction_law_militarization),
		(faction_get_slot, reg31, ":faction_no", slot_faction_law_centralization),
		(faction_get_slot, reg32, ":faction_no", slot_faction_law_legitimacy),
		(faction_get_slot, reg33, ":faction_no", slot_faction_law_unrest),
		(faction_get_slot, reg34, ":faction_no", slot_faction_current_power),

		(try_begin),
			(eq, ":faction_no", "fac_kingdom_6"),
			(call_script, "script_sod_imperial_expedition_describe_status_to_s28"),
			(str_store_string, s19, "@This is the Imperial invasion power; every open war against it changes the whole map."),
		(else_try),
			(str_clear, s28),
			(faction_slot_eq, "fac_kingdom_6", slot_faction_state, sfs_active),
			(store_relation, reg35, ":faction_no", "fac_kingdom_6"),
			(try_begin),
				(lt, reg35, 0),
				(str_store_string, s19, "@It is actively committed against the Legion."),
			(else_try),
				(str_store_string, s19, "@It is not openly committed against the Legion."),
			(try_end),
		(else_try),
			(str_store_string, s19, "@The Legion has not yet become an open strategic front."),
		(try_end),

		(try_begin),
			(gt, ":num_enemies", 0),
			(str_store_string, s14, "@^It is at war with {s12}."),
		(else_try),
			(str_store_string, s14, "@^It has no active enemies."),
		(try_end),

		(str_store_string, s49, "@{s5} is ruled by {s6}.^Court reports place it {s21} among the powers of Calradia, and its momentum is {s22}."),
		(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
		(try_begin),
			(eq, reg22, 1),
			(str_store_string, s49, "@^{s17}"),
			(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
		(try_end),
		(str_store_string, s49, "@^Its holdings are {s8}.^Its vassals are {s10}."),
		(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
		(try_begin),
			(eq, reg21, 1),
			(str_store_string, s49, "@^{s16}"),
			(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
		(try_end),
		(add_faction_note_from_sreg, ":faction_no", 0, s14, 0),
		(add_faction_note_from_sreg, ":faction_no", 0, s15, 0),
		(str_store_string, s49, "@^Council brief: score {reg23}, pressure {reg24}, {reg25} centers, {reg26} enemies, {reg27} truces, and {reg28} vassals."),

		(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
		(str_store_string, s49, "@^Strategic outlook: {s18}"),

		(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
		(call_script, "script_sod_faction_describe_campaign_posture_to_s31", ":faction_no"),
		(add_faction_note_from_sreg, ":faction_no", 0, s31, 0),
		(call_script, "script_sod_lord_describe_landless_politics_to_s68", ":faction_no"),
		(add_faction_note_from_sreg, ":faction_no", 0, s68, 0),
		(str_store_string, s49, "@^Realm systems: {reg29} known laws, power {reg34}, militarization {reg30}, centralization {reg31}, legitimacy {reg32}, unrest {reg33}. {s19}"),

		(add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
		(call_script, "script_sod_diplomacy_describe_status_to_s30", ":faction_no"),
		(add_faction_note_from_sreg, ":faction_no", 0, s30, 0),
		(try_begin),
			(is_between, ":faction_no", rebel_factions_begin, rebel_factions_end),
			(call_script, "script_sod_claimant_describe_active_wars_to_s1"),
			(add_faction_note_from_sreg, ":faction_no", 0, s1, 0),
		(else_try),
			(faction_get_slot, ":rebel_faction", ":faction_no", slot_faction_sod_rebel_counterpart),
			(is_between, ":rebel_faction", rebel_factions_begin, rebel_factions_end),
			(faction_slot_eq, ":rebel_faction", slot_faction_sod_civil_war_state, sod_civil_war_open_rebellion),
			(call_script, "script_sod_claimant_describe_active_wars_to_s1"),
			(add_faction_note_from_sreg, ":faction_no", 0, s1, 0),
		(try_end),
		(try_begin),
			(eq, ":faction_no", "fac_kingdom_6"),
			(add_faction_note_from_sreg, ":faction_no", 0, s28, 0),
		(try_end),
       # SoD Twan end
	   (else_try),
          (is_between, ":faction_no", kingdoms_begin, kingdoms_end),
          (faction_slot_eq, ":faction_no", slot_faction_state, sfs_defeated),
          (call_script, "script_update_faction_intelligence_report", ":faction_no", 0),
          (str_store_faction_name_link, s5, ":faction_no"),
          (str_store_string, s49, "@{s5} has been defeated and no longer fields a realm."),

          (add_faction_note_from_sreg, ":faction_no", 0, s49, 0),
          (str_clear, s1),
          (add_faction_note_from_sreg, ":faction_no", 1, s1, 0),
        (else_try),
          (str_clear, s1),
          (add_faction_note_from_sreg, ":faction_no", 0, s1, 0),
          (add_faction_note_from_sreg, ":faction_no", 1, s1, 0),
        (try_end),
        (try_begin),
          (is_between, ":faction_no", "fac_kingdom_1", kingdoms_end), #Excluding player kingdom
          (add_faction_note_tableau_mesh, ":faction_no", "tableau_faction_note_mesh"),
        (else_try),
          (add_faction_note_tableau_mesh, ":faction_no", "tableau_faction_note_mesh_banner"),
        (try_end),
    ]),
]
