SCRIPTS = [
("abort_quest",
    [
      (store_script_param_1, ":quest_no"),
      (store_script_param_2, ":abort_type"), #0=aborted by event, 1=abort by talking 2=abort by expire

      (assign, ":quest_return_penalty", -1),
      (assign, ":quest_expire_penalty", -2),

      #      (quest_get_slot, ":quest_object_troop", ":quest_no", slot_quest_object_troop),
      (try_begin),
        (this_or_next|eq, ":quest_no", "qst_deliver_message"),
		(this_or_next|eq, ":quest_no", "qst_slavers_deliver_message"),
		(this_or_next|eq, ":quest_no", "qst_bc_deliver_message"),
		(this_or_next|eq, ":quest_no", "qst_black_army_deliver_message"),
		(this_or_next|eq, ":quest_no", "qst_conquistadors_deliver_message"),
		(this_or_next|eq, ":quest_no", "qst_elephant_guard_deliver_message"),
		(this_or_next|eq, ":quest_no", "qst_jotnar_clan_deliver_message"),
		(this_or_next|eq, ":quest_no", "qst_serpent_host_deliver_message"),
        (eq, ":quest_no", "qst_deliver_message_to_enemy_lord"),
        (assign, ":quest_return_penalty", -2),
        (assign, ":quest_expire_penalty", -3),
      (else_try),
        (eq, ":quest_no", "qst_escort_lady"),
        (quest_get_slot, ":quest_object_troop", "qst_escort_lady", slot_quest_object_troop),
        (party_remove_members, "p_main_party", ":quest_object_troop", 1),
        (assign, ":quest_return_penalty", -2),
        (assign, ":quest_expire_penalty", -3),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_rescue_lady_under_siege"),
        ##        (party_remove_members, "p_main_party", ":quest_object_troop", 1),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_deliver_message_to_lover"),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_bring_prisoners_to_enemy"),
        ##        (try_begin),
        ##          (check_quest_succeeded, ":quest_no"),
        ##          (quest_get_slot, ":quest_target_amount", ":quest_no", slot_quest_target_amount),
        ##          (quest_get_slot, ":quest_object_troop", ":quest_no", slot_quest_object_troop),
        ##          (quest_get_slot, ":quest_giver_troop", ":quest_no", slot_quest_giver_troop),
        ##          (call_script, "script_game_get_join_cost", ":quest_object_troop"),
        ##          (assign, ":reward", reg0),
        ##          (val_mul, ":reward", ":quest_target_amount"),
        ##          (val_div, ":reward", 2),
        ##        (else_try),
        ##          (quest_get_slot, ":reward", ":quest_no", slot_quest_target_amount),
        ##        (try_end),
        ##        (call_script, "script_change_debt_to_troop", ":quest_giver_troop", ":reward"),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_bring_reinforcements_to_siege"),
        ##        (quest_get_slot, ":quest_target_amount", ":quest_no", slot_quest_target_amount),
        ##        (quest_get_slot, ":quest_object_troop", ":quest_no", slot_quest_object_troop),
        ##        (quest_get_slot, ":quest_giver_troop", ":quest_no", slot_quest_giver_troop),
        ##        (call_script, "script_game_get_join_cost", ":quest_object_troop"),
        ##        (assign, ":reward", reg0),
        ##        (val_mul, ":reward", ":quest_target_amount"),
        ##        (val_mul, ":reward", 2),
        ##        (call_script, "script_change_debt_to_troop", ":quest_giver_troop", ":reward"),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_deliver_supply_to_center_under_siege"),
        ##        (quest_get_slot, ":quest_target_amount", ":quest_no", slot_quest_target_amount),
        ##        (quest_get_slot, ":quest_giver_troop", ":quest_no", slot_quest_giver_troop),
        ##        (store_item_value, ":reward", "itm_siege_supply"),
        ##        (val_mul, ":reward", ":quest_target_amount"),
        ##        (call_script, "script_change_debt_to_troop", ":quest_giver_troop", ":reward"),
      (else_try),
        (eq, ":quest_no", "qst_raise_troops"),
        (quest_get_slot, ":quest_giver_troop", ":quest_no", slot_quest_giver_troop),
        (call_script, "script_change_debt_to_troop", ":quest_giver_troop", 100),
        (assign, ":quest_return_penalty", -4),
        (assign, ":quest_expire_penalty", -5),
      (else_try),
	    (this_or_next|eq, ":quest_no", "qst_serpent_host_raise_troops"),
		(this_or_next|eq, ":quest_no", "qst_black_army_raise_troops"),
		(this_or_next|eq, ":quest_no", "qst_bc_raise_troops"),
	    (eq, ":quest_no", "qst_conquistadors_raise_troops"),
        (assign, ":quest_return_penalty", -4),
        (assign, ":quest_expire_penalty", -5),
      (else_try),
        (eq, ":quest_no", "qst_deal_with_looters"),
        (try_for_parties, ":cur_party_no"),
          (party_get_template_id, ":cur_party_template", ":cur_party_no"),
          (eq, ":cur_party_template", "pt_bandits"),
          (party_set_flags, ":cur_party_no", pf_quest_party, 0),
        (try_end),
        (assign, ":quest_return_penalty", -4),
        (assign, ":quest_expire_penalty", -5),
      (else_try),
        (eq, ":quest_no", "qst_deal_with_bandits_at_lords_village"),
        (quest_get_slot, ":quest_giver_troop", ":quest_no", slot_quest_giver_troop),
        (call_script, "script_change_debt_to_troop", ":quest_giver_troop", 200),
        (assign, ":quest_return_penalty", -5),
        (assign, ":quest_expire_penalty", -6),
      (else_try),
        (eq, ":quest_no", "qst_collect_taxes"),
        (quest_get_slot, ":gold_reward", ":quest_no", slot_quest_gold_reward),
        (quest_set_slot, ":quest_no", slot_quest_gold_reward, 0),
        (quest_get_slot, ":quest_giver_troop", ":quest_no", slot_quest_giver_troop),
        (call_script, "script_change_debt_to_troop", ":quest_giver_troop", ":gold_reward"),
        (assign, ":quest_return_penalty", -4),
        (assign, ":quest_expire_penalty", -6),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_capture_messenger"),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_bring_back_deserters"),
      (else_try),
		(this_or_next|eq, ":quest_no", "qst_elephant_guard_hunt_down_fugitive"),
		(this_or_next|eq, ":quest_no", "qst_bc_hunt_down_fugitive"),
		(this_or_next|eq, ":quest_no", "qst_conquistadors_hunt_down_fugitive"),
        (eq, ":quest_no", "qst_hunt_down_fugitive"),
        (assign, ":quest_return_penalty", -3),
        (assign, ":quest_expire_penalty", -4),
      (else_try),
        (eq, ":quest_no", "qst_kill_local_merchant"),
      (else_try),
        (eq, ":quest_no", "qst_bring_back_runaway_serfs"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -1),
      (else_try),
		(eq, ":quest_no", "qst_slavers_bring_back_runaway_slaves"),
        (assign, ":quest_return_penalty", -3),
        (assign, ":quest_expire_penalty", -5),
      (else_try),
        (eq, ":quest_no", "qst_lend_companion"),
      (else_try),
        (eq, ":quest_no", "qst_collect_debt"),
        (try_begin),
          (quest_slot_eq, "qst_collect_debt", slot_quest_current_state, 1), #debt collected but not delivered
          (quest_get_slot, ":debt", "qst_collect_debt", slot_quest_target_amount),
          (quest_get_slot, ":quest_giver", "qst_collect_debt", slot_quest_giver_troop),
          (call_script, "script_change_debt_to_troop", ":quest_giver", ":debt"),
          (assign, ":quest_return_penalty", -3),
          (assign, ":quest_expire_penalty", -6),
        (else_try),
          (assign, ":quest_return_penalty", -3),
          (assign, ":quest_expire_penalty", -4),
        (try_end),
	  (else_try),
		(this_or_next|eq, ":quest_no", "qst_black_army_collect_debt"),
		(this_or_next|eq, ":quest_no", "qst_slavers_collect_debt"),
        (eq, ":quest_no", "qst_conquistadors_collect_debt"),
        (try_begin),
          (quest_slot_eq, ":quest_no", slot_quest_current_state, 1), # debt collected but not delivered
          (quest_get_slot, ":debt", ":quest_no", slot_quest_target_amount),
          (quest_get_slot, ":quest_giver", ":quest_no", slot_quest_giver_troop),
          (store_troop_faction, ":giver_fac", ":quest_giver"),
		  (faction_get_slot, ":cur_debt", ":giver_fac", player_debt_to_faction),
		  (val_add, ":cur_debt", ":debt"),
		  (faction_set_slot, ":giver_fac", player_debt_to_faction, ":cur_debt"),
          (assign, ":quest_return_penalty", -3),
          (assign, ":quest_expire_penalty", -6),
        (else_try),
          (assign, ":quest_return_penalty", -3),
          (assign, ":quest_expire_penalty", -4),
        (try_end),
      (else_try),
        (eq, ":quest_no", "qst_deal_with_bandits_at_lords_village"),
        (assign, ":quest_return_penalty", -6),
        (assign, ":quest_expire_penalty", -6),
      (else_try),
        (eq, ":quest_no", "qst_raid_caravan_to_start_war"),
        (assign, ":quest_return_penalty", -10),
        (assign, ":quest_expire_penalty", -13),
      (else_try),
        (eq, ":quest_no", "qst_persuade_lords_to_make_peace"),
        (assign, ":quest_return_penalty", -10),
        (assign, ":quest_expire_penalty", -13),
      (else_try),
        (eq, ":quest_no", "qst_deal_with_night_bandits"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -1),
	  (else_try),
        (eq, ":quest_no", "qst_serpent_host_raid_caravan"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -3),
      (else_try),
        (eq, ":quest_no", "qst_follow_spy"),
        (assign, ":quest_return_penalty", -2),
        (assign, ":quest_expire_penalty", -3),
        (try_begin),
          (neq, "$qst_follow_spy_spy_party", "p_main_party"),
          (gt, "$qst_follow_spy_spy_party", 0),
          (party_is_active, "$qst_follow_spy_spy_party"),
          (remove_party, "$qst_follow_spy_spy_party"),
        (try_end),
        (try_begin),
          (neq, "$qst_follow_spy_spy_partners_party", "p_main_party"),
          (gt, "$qst_follow_spy_spy_partners_party", 0),
          (party_is_active, "$qst_follow_spy_spy_partners_party"),
          (remove_party, "$qst_follow_spy_spy_partners_party"),
        (try_end),
        (assign, "$qst_follow_spy_spy_party", 0),
        (assign, "$qst_follow_spy_spy_partners_party", 0),
        (assign, "$qst_follow_spy_no_active_parties", 1),
      (else_try),
        (eq, ":quest_no", "qst_capture_enemy_hero"),
        (assign, ":quest_return_penalty", -3),
        (assign, ":quest_expire_penalty", -4),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_lend_companion"),
        ##        (quest_get_slot, ":quest_target_troop", "qst_lend_companion", slot_quest_target_troop),
        ##        (party_add_members, "p_main_party", ":quest_target_troop", 1),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_capture_conspirators"),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_defend_nobles_against_peasants"),
      (else_try),
        (eq, ":quest_no", "qst_incriminate_loyal_commander"),
        (quest_get_slot, ":messenger_party", "qst_incriminate_loyal_commander", slot_quest_target_party),
        (try_begin),
          (gt, ":messenger_party", 0),
          (party_is_active, ":messenger_party"),
          (party_get_template_id, ":messenger_party_template", ":messenger_party"),
          (eq, ":messenger_party_template", "pt_sacrificed_messenger"),
          (remove_party, ":messenger_party"),
        (try_end),
        (quest_set_slot, "qst_incriminate_loyal_commander", slot_quest_target_party, -1),
        (assign, ":quest_return_penalty", -5),
        (assign, ":quest_expire_penalty", -6),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_hunt_down_raiders"),
        ##      (else_try),
        ##        (eq, ":quest_no", "qst_capture_prisoners"),
        ##        #Enemy lord quests
      (else_try),
        (eq, ":quest_no", "qst_lend_surgeon"),

        #Kingdom lady quests
      (else_try),
        (eq, ":quest_no", "qst_rescue_lord_by_replace"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -1),
      (else_try),
        (eq, ":quest_no", "qst_deliver_message_to_prisoner_lord"),
        (assign, ":quest_return_penalty", 0),
        (assign, ":quest_expire_penalty", -1),
      (else_try),
        (eq, ":quest_no", "qst_duel_for_lady"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -1),

        #Kingdom Army quests
      (else_try),
        (eq, ":quest_no", "qst_follow_army"),
        (assign, ":quest_return_penalty", -4),
        (assign, ":quest_expire_penalty", -5),
      (else_try),
        (eq, ":quest_no", "qst_deliver_cattle_to_army"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -2),
      (else_try),
        (eq, ":quest_no", "qst_join_siege_with_army"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -2),
      (else_try),
        (eq, ":quest_no", "qst_scout_waypoints"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -2),

        #Village Elder quests
      (else_try),
        (eq, ":quest_no", "qst_deliver_grain"),
        (assign, ":quest_return_penalty", -6),
        (assign, ":quest_expire_penalty", -7),
	  (else_try),
		(this_or_next|eq, ":quest_no", "qst_conquistadors_deliver_grain"),
		(this_or_next|eq, ":quest_no", "qst_conquistadors_deliver_horses"),
        (eq, ":quest_no", "qst_elephant_guard_deliver_grain"),
        (assign, ":quest_return_penalty", -3),
        (assign, ":quest_expire_penalty", -5),
      (else_try),
        (eq, ":quest_no", "qst_deliver_cattle"),
        (assign, ":quest_return_penalty", -3),
        (assign, ":quest_expire_penalty", -4),
      (else_try),
        (eq, ":quest_no", "qst_train_peasants_against_bandits"),
        (assign, ":quest_return_penalty", -4),
        (assign, ":quest_expire_penalty", -5),
	  (else_try),
        (eq, ":quest_no", "qst_elephant_guard_train_peasants_against_bandits"),
        (assign, ":quest_return_penalty", -2),
        (assign, ":quest_expire_penalty", -5),

        #Mayor quests
      (else_try),
        (eq, ":quest_no", "qst_deliver_wine"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -3),
        (val_add, "$debt_to_merchants_guild", "$qst_deliver_wine_debt"),
	  (else_try),
        (eq, ":quest_no", "qst_deliver_wine"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -3),
        (faction_get_slot, ":cur_debt", "fac_sod_merc_guild6", player_debt_to_faction),
		(val_add, ":cur_debt", "$qst_deliver_wine_debt"),
		(faction_set_slot, "fac_sod_merc_guild6", player_debt_to_faction, ":cur_debt"),
      (else_try),
        (eq, ":quest_no", "qst_move_cattle_herd"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -3),
      (else_try),
        (eq, ":quest_no", "qst_escort_merchant_caravan"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -3),
	  (else_try),
        (this_or_next|eq, ":quest_no", "qst_black_army_escort_merchant_caravan"),
		(eq, ":quest_no", "qst_slavers_escort_merchant_caravan"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -3),
      (else_try),
        (eq, ":quest_no", "qst_troublesome_bandits"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -2),
	  (else_try),
        (this_or_next|eq, ":quest_no", "qst_elephant_guard_troublesome_bandits"),
		(this_or_next|eq, ":quest_no", "qst_bc_troublesome_bandits"),
		(this_or_next|eq, ":quest_no", "qst_conquistadors_troublesome_bandits"),
		(eq, ":quest_no", "qst_serpent_host_troublesome_bandits"),
        (assign, ":quest_return_penalty", -1),
        (assign, ":quest_expire_penalty", -2),
        #Other quests
      (else_try),
        (eq, ":quest_no", "qst_join_faction"),
        (assign, ":quest_return_penalty", -3),
        (assign, ":quest_expire_penalty", -3),
        (try_begin),
          (call_script, "script_get_number_of_hero_centers", "trp_player"),
          (gt, reg0, 0),
          (call_script, "script_change_player_relation_with_faction", "$g_invite_faction", -10),
        (try_end),
        (assign, "$g_invite_faction", 0),
        (assign, "$g_invite_faction_lord", 0),
        (assign, "$g_invite_offered_center", 0),
      (else_try),
        (eq, ":quest_no", "qst_eliminate_bandits_infesting_village"),
        (assign, ":quest_return_penalty", -3),
        (assign, ":quest_expire_penalty", -3),
      (try_end),
      (try_begin),
        (gt, ":abort_type", 0),
        (quest_get_slot, ":quest_giver", ":quest_no", slot_quest_giver_troop),
        (assign, ":relation_penalty", ":quest_return_penalty"),
        (try_begin),
          (eq, ":abort_type", 2),
          (assign, ":relation_penalty", ":quest_expire_penalty"),
        (try_end),
		(store_troop_faction, ":quest_giver_faction", ":quest_giver"),
        (try_begin),
          (is_between, ":quest_giver_faction", guilds_begin, guilds_end),
          (call_script, "script_change_player_relation_with_faction", ":quest_giver_faction", ":relation_penalty"),
        (else_try),
          (this_or_next|is_between, ":quest_giver", village_elders_begin, village_elders_end),
          (is_between, ":quest_giver", mayors_begin, mayors_end),
          (quest_get_slot, ":quest_giver_center", ":quest_no", slot_quest_giver_center),
          (call_script, "script_change_player_relation_with_center", ":quest_giver_center", ":relation_penalty"),
        (else_try),
          (call_script, "script_change_player_relation_with_troop", ":quest_giver", ":relation_penalty"),
        (try_end),
      (try_end),
      (fail_quest, ":quest_no"),

      #NPC companion changes begin
      (try_begin),
        (gt, ":abort_type", 0),
        (call_script, "script_objectionable_action", tmt_honest, "str_fail_quest"),
      (try_end),
      #NPC companion changes end
      (call_script, "script_sod_quest_runtime_abort", ":quest_no", ":abort_type"),
      (call_script, "script_end_quest", ":quest_no"),
  ]),
]
