SCRIPTS = [
("cancel_quest",
      [(store_script_param, ":quest_no", 1),
        (str_clear, s1),
        (add_quest_note_from_sreg, ":quest_no", 0, s1, 0),
        (add_quest_note_from_sreg, ":quest_no", 1, s1, 0),
        (add_quest_note_from_sreg, ":quest_no", 2, s1, 0),
        (add_quest_note_from_sreg, ":quest_no", 3, s1, 0),
        (add_quest_note_from_sreg, ":quest_no", 4, s1, 0),
        (add_quest_note_from_sreg, ":quest_no", 5, s1, 0),
        (add_quest_note_from_sreg, ":quest_no", 6, s1, 0),
        (add_quest_note_from_sreg, ":quest_no", 7, s1, 0),
        (cancel_quest, ":quest_no"),
        (try_begin),
          (is_between, ":quest_no", mayor_quests_begin, mayor_quests_end),
          (assign, "$merchant_quest_last_offerer", -1),
          (assign, "$merchant_offered_quest", -1),
        (try_end),
        (call_script, "script_sod_quest_runtime_abort", ":quest_no", 0),
    ]),
]
