SCRIPTS = [
("sod_seven_ash_prepare_breach",
    [
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_siege_phase_active, sod_seven_ash_siege_phase_breach),
      (quest_get_slot, ":elite_core", "qst_seven_ash_ultimatum", slot_quest_seven_ash_wulfred_elite_core),
      (quest_get_slot, ":pressure", "qst_seven_ash_ultimatum", slot_quest_seven_ash_wulfred_pressure),
      (quest_get_slot, ":palisade_breach_pressure", "qst_seven_ash_ultimatum", slot_quest_seven_ash_palisade_breach_pressure),
      (quest_get_slot, ":gate_reserve", "qst_seven_ash_ultimatum", slot_quest_seven_ash_sector_gate_reserve),
      (quest_get_slot, ":aldrik_support", "qst_seven_ash_ultimatum", slot_quest_seven_ash_aldrik_return_applied),
      (quest_get_slot, ":beren_support", "qst_seven_ash_ultimatum", slot_quest_seven_ash_beren_return_applied),
      (quest_get_slot, ":beren_breach", "qst_seven_ash_ultimatum", slot_quest_seven_ash_beren_breach_support),

      # The breach is Halvorn's hard push. It uses Wulfred's elite core rather
      # than the whole host, then inherits damage from the palisade result.
      (assign, ":enemy_committed", ":elite_core"),
      (store_div, ":pressure_bonus", ":pressure", 6),
      (val_add, ":enemy_committed", ":pressure_bonus"),
      (store_mul, ":breach_bonus", ":palisade_breach_pressure", 10),
      (val_add, ":enemy_committed", ":breach_bonus"),
      (try_begin),
        (ge, ":gate_reserve", 1),
        (val_sub, ":enemy_committed", 14),
      (try_end),
      (try_begin),
        (ge, ":aldrik_support", 1),
        (val_sub, ":enemy_committed", 8),
      (try_end),
      (try_begin),
        (ge, ":beren_support", 1),
        (val_sub, ":enemy_committed", 8),
      (try_end),
      (try_begin),
        (ge, ":beren_breach", 1),
        (val_sub, ":enemy_committed", 6),
      (try_end),
      (val_max, ":enemy_committed", 24),
      (val_min, ":enemy_committed", 90),

      (assign, ":wave_count", 2),
      (try_begin),
        (ge, ":enemy_committed", 64),
        (assign, ":wave_count", 3),
      (try_end),

      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_breach_enemy_committed, ":enemy_committed"),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_breach_wave_count, ":wave_count"),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_breach_result, sod_seven_ash_siege_result_unresolved),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_breach_street_pressure, 0),
      (assign, reg0, ":enemy_committed"),
      (assign, reg1, ":wave_count"),
  ]),
]
