SCRIPTS = [
("sod_rtc_price_of_bread_apply_local_aftermath",
    [
      (store_script_param, ":resolution", 1),
      (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_sod_chain_choice, ":resolution"),

      (quest_get_slot, ":target_center", "qst_rtc_price_of_bread", slot_quest_target_center),
      (try_begin),
        (is_between, ":target_center", centers_begin, centers_end),
        (try_begin),
          (eq, ":resolution", 1),
          (call_script, "script_change_player_relation_with_center", ":target_center", 2),
          (call_script, "script_change_center_prosperity", ":target_center", 1),
        (else_try),
          (eq, ":resolution", 2),
          (call_script, "script_change_player_relation_with_center", ":target_center", 1),
          (call_script, "script_change_center_prosperity", ":target_center", 2),
        (else_try),
          (eq, ":resolution", 3),
          (call_script, "script_change_player_relation_with_center", ":target_center", 2),
        (else_try),
          (eq, ":resolution", 4),
          (call_script, "script_change_player_relation_with_center", ":target_center", -4),
          (call_script, "script_change_center_prosperity", ":target_center", -1),
        (else_try),
          (eq, ":resolution", 6),
          (call_script, "script_change_player_relation_with_center", ":target_center", 3),
          (call_script, "script_change_center_prosperity", ":target_center", 1),
        (else_try),
          (call_script, "script_change_player_relation_with_center", ":target_center", -2),
          (call_script, "script_change_center_prosperity", ":target_center", -1),
        (try_end),
      (try_end),
  ]),
]
