SCRIPTS = [
("sod_rtc_first_recognition_prepare_witness_target",
    [
      (store_script_param, ":recognition", 1),
      (quest_get_slot, ":target_party", "qst_rtc_first_recognition", slot_quest_target_party),
      (try_begin),
        (gt, ":target_party", 0),
        (neq, ":target_party", "p_main_party"),
        (party_is_active, ":target_party"),
        (remove_party, ":target_party"),
      (try_end),

      (quest_get_slot, ":spawn_center", "qst_rtc_first_recognition", slot_quest_target_center),

      (assign, ":template", "pt_sod_diplomatic_envoy"),
      (try_begin),
        (eq, ":recognition", sod_rtc_recognition_lawful_claimant),
        (assign, ":template", "pt_sod_diplomatic_envoy"),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_free_captain),
        (assign, ":template", "pt_sod_diplomatic_envoy"),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_trade_power),
        (assign, ":template", "pt_merchant_caravan"),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_people_defender),
        (assign, ":template", "pt_sod_diplomatic_envoy"),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_dangerous_warlord),
        (assign, ":template", "pt_bandits"),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_shadow_operator),
        (assign, ":template", "pt_bandits"),
      (else_try),
        (assign, ":template", "pt_sod_diplomatic_envoy"),
      (try_end),

      (call_script, "script_sod_rtc_prepare_temporary_target", "qst_rtc_first_recognition", ":template", ":spawn_center", 4, 1),
  ]),
]
