SCRIPTS = [
("sod_seven_ash_apply_first_defender_return",
    [
      (store_script_param, ":defender_bit", 1),

      (try_begin),
        (eq, ":defender_bit", sod_seven_ash_defender_garric),
        (quest_get_slot, ":applied", "qst_seven_ash_ultimatum", slot_quest_seven_ash_garric_return_applied),
        (eq, ":applied", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_garric_return_applied, 1),
        (quest_get_slot, ":training", "qst_seven_ash_ultimatum", slot_quest_seven_ash_training),
        (val_add, ":training", 8),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_training, ":training"),
        (quest_get_slot, ":intelligence", "qst_seven_ash_ultimatum", slot_quest_seven_ash_intelligence),
        (val_add, ":intelligence", 6),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_intelligence, ":intelligence"),
        (quest_get_slot, ":route", "qst_seven_ash_ultimatum", slot_quest_seven_ash_garric_route),
        (try_begin),
          (eq, ":route", sod_seven_ash_route_best),
          (quest_get_slot, ":unlock_flags", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
          (val_or, ":unlock_flags", sod_seven_ash_defender_garric),
          (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask, ":unlock_flags"),
        (try_end),
        (str_store_string, s49, "@Garric walked Ashwick's watch platform, cut two bad firing angles, and taught the first archers when not to loose. The village gained safer lanes and sharper eyes."),
        (add_quest_note_from_sreg, "qst_seven_ash_garric_ashbow", 4, s49, 0),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_oswin),
        (quest_get_slot, ":applied", "qst_seven_ash_ultimatum", slot_quest_seven_ash_oswin_return_applied),
        (eq, ":applied", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_oswin_return_applied, 1),
        (quest_get_slot, ":fortification", "qst_seven_ash_ultimatum", slot_quest_seven_ash_fortification),
        (val_add, ":fortification", 12),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_fortification, ":fortification"),
        (quest_get_slot, ":civilian_safety", "qst_seven_ash_ultimatum", slot_quest_seven_ash_civilian_safety),
        (val_add, ":civilian_safety", 5),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_civilian_safety, ":civilian_safety"),
        (quest_get_slot, ":route", "qst_seven_ash_ultimatum", slot_quest_seven_ash_oswin_route),
        (try_begin),
          (this_or_next|eq, ":route", sod_seven_ash_route_best),
          (eq, ":route", sod_seven_ash_route_hard),
          (quest_get_slot, ":unlock_flags", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
          (val_or, ":unlock_flags", sod_seven_ash_defender_oswin),
          (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask, ":unlock_flags"),
        (try_end),
        (str_store_string, s49, "@Oswin walked the palisade with string line and cold arithmetic. Ashwick lost weak timber and excuses, but gained a defensible gate plan."),
        (add_quest_note_from_sreg, "qst_seven_ash_oswin_ditchwright", 4, s49, 0),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_aldrik),
        (quest_get_slot, ":applied", "qst_seven_ash_ultimatum", slot_quest_seven_ash_aldrik_return_applied),
        (eq, ":applied", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_aldrik_return_applied, 1),
        (quest_get_slot, ":morale", "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale),
        (val_add, ":morale", 10),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale, ":morale"),
        (quest_get_slot, ":training", "qst_seven_ash_ultimatum", slot_quest_seven_ash_training),
        (val_add, ":training", 6),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_training, ":training"),
        (quest_get_slot, ":route", "qst_seven_ash_ultimatum", slot_quest_seven_ash_aldrik_route),
        (try_begin),
          (this_or_next|eq, ":route", sod_seven_ash_route_best),
          (eq, ":route", sod_seven_ash_route_legal_promise),
          (quest_get_slot, ":unlock_flags", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
          (val_or, ":unlock_flags", sod_seven_ash_defender_aldrik),
          (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask, ":unlock_flags"),
        (try_end),
        (str_store_string, s49, "@Aldrik set his shield on Ashwick's gate. The cheer was too large for one knight, but it gave frightened people a shape for courage."),
        (add_quest_note_from_sreg, "qst_seven_ash_sir_aldrik_vane", 4, s49, 0),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_mirelle),
        (quest_get_slot, ":applied", "qst_seven_ash_ultimatum", slot_quest_seven_ash_mirelle_return_applied),
        (eq, ":applied", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_mirelle_return_applied, 1),
        (quest_get_slot, ":civilian_safety", "qst_seven_ash_ultimatum", slot_quest_seven_ash_civilian_safety),
        (val_add, ":civilian_safety", 10),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_civilian_safety, ":civilian_safety"),
        (quest_get_slot, ":intelligence", "qst_seven_ash_ultimatum", slot_quest_seven_ash_intelligence),
        (val_add, ":intelligence", 10),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_intelligence, ":intelligence"),
        (quest_get_slot, ":route", "qst_seven_ash_ultimatum", slot_quest_seven_ash_mirelle_route),
        (try_begin),
          (this_or_next|eq, ":route", sod_seven_ash_route_best),
          (eq, ":route", sod_seven_ash_route_hard),
          (quest_get_slot, ":unlock_flags", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
          (val_or, ":unlock_flags", sod_seven_ash_defender_mirelle),
          (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask, ":unlock_flags"),
        (try_end),
        (str_store_string, s49, "@Mirelle marked kitchens, pig pens, fence boards, and quiet hands. Ashwick gained doors the raiders would not see until the villagers were gone."),
        (add_quest_note_from_sreg, "qst_seven_ash_mirelle_voss", 4, s49, 0),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_tomas),
        (quest_get_slot, ":applied", "qst_seven_ash_ultimatum", slot_quest_seven_ash_tomas_return_applied),
        (eq, ":applied", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_tomas_return_applied, 1),
        (quest_get_slot, ":training", "qst_seven_ash_ultimatum", slot_quest_seven_ash_training),
        (val_add, ":training", 14),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_training, ":training"),
        (quest_get_slot, ":morale", "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale),
        (val_add, ":morale", 5),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale, ":morale"),
        (quest_get_slot, ":route", "qst_seven_ash_ultimatum", slot_quest_seven_ash_tomas_route),
        (try_begin),
          (this_or_next|eq, ":route", sod_seven_ash_route_best),
          (eq, ":route", sod_seven_ash_route_legal_promise),
          (quest_get_slot, ":unlock_flags", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
          (val_or, ":unlock_flags", sod_seven_ash_defender_tomas),
          (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask, ":unlock_flags"),
        (try_end),
        (str_store_string, s49, "@Tomas found no bad habits in Ashwick's militia, only fear without shape. By dusk the spears shook in time, and the shouting had rules."),
        (add_quest_note_from_sreg, "qst_seven_ash_tomas_reed", 4, s49, 0),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_beren),
        (quest_get_slot, ":applied", "qst_seven_ash_ultimatum", slot_quest_seven_ash_beren_return_applied),
        (eq, ":applied", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_beren_return_applied, 1),
        (quest_get_slot, ":morale", "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale),
        (val_add, ":morale", 8),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale, ":morale"),
        (quest_get_slot, ":fortification", "qst_seven_ash_ultimatum", slot_quest_seven_ash_fortification),
        (val_add, ":fortification", 5),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_fortification, ":fortification"),
        (quest_get_slot, ":route", "qst_seven_ash_ultimatum", slot_quest_seven_ash_beren_route),
        (try_begin),
          (this_or_next|eq, ":route", sod_seven_ash_route_best),
          (eq, ":route", sod_seven_ash_route_legal_promise),
          (quest_get_slot, ":unlock_flags", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
          (val_or, ":unlock_flags", sod_seven_ash_defender_beren),
          (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask, ":unlock_flags"),
        (try_end),
        (str_store_string, s49, "@Beren tested Ashwick's gate beam with his shoulder and named where a champion would try to break it. The gate looked weaker afterward, and somehow safer."),
        (add_quest_note_from_sreg, "qst_seven_ash_beren_hardhand", 4, s49, 0),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_elianor),
        (quest_get_slot, ":applied", "qst_seven_ash_ultimatum", slot_quest_seven_ash_elianor_return_applied),
        (eq, ":applied", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_elianor_return_applied, 1),
        (quest_get_slot, ":civilian_safety", "qst_seven_ash_ultimatum", slot_quest_seven_ash_civilian_safety),
        (val_add, ":civilian_safety", 14),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_civilian_safety, ":civilian_safety"),
        (quest_get_slot, ":morale", "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale),
        (val_add, ":morale", 6),
        (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_morale, ":morale"),
        (quest_get_slot, ":route", "qst_seven_ash_ultimatum", slot_quest_seven_ash_elianor_route),
        (try_begin),
          (this_or_next|eq, ":route", sod_seven_ash_route_best),
          (eq, ":route", sod_seven_ash_route_legal_promise),
          (quest_get_slot, ":unlock_flags", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask),
          (val_or, ":unlock_flags", sod_seven_ash_defender_elianor),
          (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_unlock_bitmask, ":unlock_flags"),
        (try_end),
        (str_store_string, s49, "@Elianor took the church key, granary tally, and dry-cellar list. Ashwick gained an infirmary before it gained more wounded."),
        (add_quest_note_from_sreg, "qst_seven_ash_sister_elianor", 4, s49, 0),
      (try_end),

      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_active_recruit_id, sod_seven_ash_defender_none),
  ]),
]
