from header_operations import *
from module_constants import *

SCRIPTS = [
("sod_rtc_hounds_terms_resolve",
    [
      (store_script_param, ":terms_choice", 1),
      (call_script, "script_sod_rtc_hounds_terms_prepare_envoy"),
      (quest_get_slot, ":flags", "qst_rtc_hounds_terms", slot_quest_rtc_flags),
      (quest_get_slot, ":route", "qst_rtc_hounds_terms", slot_quest_rtc_branch_seed),
      (quest_get_slot, ":envoy_handling", "qst_rtc_hounds_terms", slot_quest_sod_chain_choice),
      (quest_get_slot, ":offer", "qst_rtc_hounds_terms", slot_quest_object_troop),
      (quest_get_slot, ":bread_center", "qst_rtc_hounds_terms", slot_quest_target_center),
      (quest_get_slot, ":grain_pressure", "qst_rtc_hounds_terms", slot_quest_target_amount),

      (try_begin),
        (eq, ":terms_choice", sod_rtc_terms_accepted),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_method_seed, sod_rtc_terms_accepted),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_open),
        (try_begin),
          (neq, ":route", sod_rtc_branch_imperial),
          (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_branch_seed, sod_rtc_branch_imperial),
        (try_end),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_diplomacy_betrayal, 2),
        (str_store_string, s49, "@You accepted the Hound's terms. Septima's seal buys time and recognition, but the road now bends toward Empire."),

        (add_quest_note_from_sreg, "qst_rtc_hounds_terms", 3, s49, 0),
        (call_script, "script_succeed_quest", "qst_rtc_hounds_terms"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_hounds_terms", "qst_rtc_war_of_witnesses", 0),
      (else_try),
        (eq, ":terms_choice", sod_rtc_terms_delay_negotiated),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_method_seed, sod_rtc_terms_delay_negotiated),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_rising),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_honorable_peace, 1),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_scout_warning, 1),
        (str_store_string, s49, "@You negotiated delay. The Hound has not been stopped, but the witnesses live long enough for a war of legitimacy to begin."),

        (add_quest_note_from_sreg, "qst_rtc_hounds_terms", 3, s49, 0),
        (call_script, "script_succeed_quest", "qst_rtc_hounds_terms"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_hounds_terms", "qst_rtc_war_of_witnesses", 0),
      (else_try),
        (eq, ":terms_choice", sod_rtc_terms_rejected),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_method_seed, sod_rtc_terms_rejected),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_open),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_defeat_imperials, 2),
        (str_store_string, s49, "@You rejected the Hound's terms. The Empire now has its answer, and witnesses will need protection before banners can matter."),

        (add_quest_note_from_sreg, "qst_rtc_hounds_terms", 3, s49, 0),
        (call_script, "script_succeed_quest", "qst_rtc_hounds_terms"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_hounds_terms", "qst_rtc_war_of_witnesses", 0),
      (else_try),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_method_seed, sod_rtc_terms_collapsed),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_invasion),
        (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_branch_seed, sod_rtc_branch_fractured_claim),
        (val_and, ":flags", -8388609),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_retreat_or_fail, 3),
        (str_store_string, s49, "@The talks collapsed. The Hound has what he wanted: division, panic, and a road for the Empire to march down."),

        (add_quest_note_from_sreg, "qst_rtc_hounds_terms", 3, s49, 0),
        (call_script, "script_fail_quest", "qst_rtc_hounds_terms"),
        (call_script, "script_sod_quest_chain_branch_failure", "qst_rtc_hounds_terms", -1, 0),
      (try_end),

      (try_begin),
        (eq, ":offer", sod_rtc_offer_bread_oath),
        (str_store_string, s49, "@The Hound's terms tried to own the bread oath. Whatever answer you gave, hunger is now part of the Imperial battlefield."),
        (add_quest_note_from_sreg, "qst_rtc_hounds_terms", 5, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_books_oath),
        (str_store_string, s49, "@The Hound's terms tried to own the books oath. Roads, audits, and grain ledgers will become weapons in the witness war."),
        (add_quest_note_from_sreg, "qst_rtc_hounds_terms", 5, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_witness_oath),
        (str_store_string, s49, "@The Hound's terms tried to own the witness oath. Marius will not merely hunt witnesses; he will try to certify them into silence."),
        (add_quest_note_from_sreg, "qst_rtc_hounds_terms", 5, s49, 0),
      (try_end),

      (quest_set_slot, "qst_rtc_hounds_terms", slot_quest_rtc_flags, ":flags"),
      (quest_get_slot, ":final_route", "qst_rtc_hounds_terms", slot_quest_rtc_branch_seed),
      (quest_get_slot, ":pressure", "qst_rtc_hounds_terms", slot_quest_rtc_imperial_pressure),
      (quest_get_slot, ":companion_pressure", "qst_rtc_hounds_terms", slot_quest_rtc_companion_pressure),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_branch_seed, ":final_route"),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_imperial_pressure, ":pressure"),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_companion_pressure, ":companion_pressure"),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_target_center, ":bread_center"),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_target_amount, ":grain_pressure"),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_object_troop, ":offer"),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_sod_chain_choice, ":envoy_handling"),
      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_flags, ":flags"),
      (call_script, "script_sod_rtc_war_of_witnesses_prepare_target"),
      (call_script, "script_sod_rtc_hounds_terms_cleanup_envoy"),
  ]),
]
