SCRIPTS = [
("sod_rtc_last_smoke_resolve",
    [
      (store_script_param, ":salvage_choice", 1),
      (quest_get_slot, ":origin", "qst_rtc_last_smoke", slot_quest_rtc_origin),
      (quest_get_slot, ":faith", "qst_rtc_last_smoke", slot_quest_rtc_faith),
      (quest_set_slot, "qst_rtc_last_smoke", slot_quest_rtc_salvage_choice, ":salvage_choice"),
      (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_salvage_choice, ":salvage_choice"),
      (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_salvage_choice, ":salvage_choice"),
      (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_salvage_choice, ":salvage_choice"),
      (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_salvage_choice, ":salvage_choice"),
      (assign, "$g_sod_rtc_starting_salvage_choice", ":salvage_choice"),

      (try_begin),
        (eq, ":salvage_choice", sod_rtc_salvage_wounded),
        (str_store_string, s49, "@You saved the wounded from the burned road. The camp will remember the mercy, though supplies are thinner."),

        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 3, s49, 0),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_ymira_refugee_mercy, 3),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_free_captives, 1),
        (call_script, "script_sod_apply_rtc_starting_salvage_bonus"),
      (else_try),
        (eq, ":salvage_choice", sod_rtc_salvage_baggage),
        (str_store_string, s49, "@You saved baggage and stores from the road. The camp has more supplies, though some refugees question the cost."),

        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 3, s49, 0),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_food_security, 2),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_orderly_profit, 1),
      (else_try),
        (eq, ":salvage_choice", sod_rtc_salvage_papers),
        (str_store_string, s49, "@You saved military papers from the road. Garran believes they may reveal the Imperial line of advance."),

        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 3, s49, 0),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_scout_warning, 2),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_defeat_imperials, 1),
      (else_try),
        (eq, ":salvage_choice", sod_rtc_salvage_abandoned),
        (quest_get_slot, ":flags", "qst_rtc_last_smoke", slot_quest_rtc_flags),
        (val_or, ":flags", sod_rtc_flag_companion_wary_mercy),
        (quest_set_slot, "qst_rtc_last_smoke", slot_quest_rtc_flags, ":flags"),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_flags, ":flags"),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_flags, ":flags"),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_flags, ":flags"),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_flags, ":flags"),
        (str_store_string, s49, "@You left part of the road behind to reach the camp quickly. The survivors are fewer, and mercy-minded companions will remember it."),

        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 3, s49, 0),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_retreat_or_fail, 3),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_ymira_refugee_expedience, 2),
      (try_end),

      (try_begin),
        (eq, ":origin", cb_antares),
        (str_store_string, s49, "@Founding pressure: Antarian memory will judge whether the road preserved discipline, name, and command under fire."),
        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 5, s49, 0),
      (else_try),
        (eq, ":origin", cb_marina),
        (str_store_string, s49, "@Founding pressure: Marinan memory will judge whether the road preserved stores, movement, and the practical means to survive."),
        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 5, s49, 0),
      (else_try),
        (eq, ":origin", cb_aden),
        (str_store_string, s49, "@Founding pressure: Adenian memory will judge whether the road preserved order when fear broke formation."),
        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 5, s49, 0),
      (else_try),
        (eq, ":origin", cb_villian),
        (str_store_string, s49, "@Founding pressure: Villian memory will judge the story survivors tell before any herald improves it."),
        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 5, s49, 0),
      (else_try),
        (eq, ":origin", cb_zerrikan),
        (str_store_string, s49, "@Founding pressure: Zerrikanian memory will judge the tracks, witnesses, and roadcraft left behind in the smoke."),
        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 5, s49, 0),
      (else_try),
        (eq, ":faith", cb_the_one),
        (str_store_string, s49, "@Founding pressure: The One's faithful will judge whether mercy survived the first fire."),
        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 5, s49, 0),
      (else_try),
        (eq, ":faith", cb_old_gods),
        (str_store_string, s49, "@Founding pressure: the old gods' faithful will judge what debt is owed to the dead left in the smoke."),
        (add_quest_note_from_sreg, "qst_rtc_last_smoke", 5, s49, 0),
      (try_end),

      (try_begin),
        (eq, ":salvage_choice", sod_rtc_salvage_abandoned),
        (call_script, "script_fail_quest", "qst_rtc_last_smoke"),
        (call_script, "script_sod_quest_chain_branch_failure", "qst_rtc_last_smoke", "qst_rtc_borrowed_names", 0),
      (else_try),
        (call_script, "script_succeed_quest", "qst_rtc_last_smoke"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_last_smoke", "qst_rtc_borrowed_names", 0),
      (try_end),
  ]),
]
