SCRIPTS = [
("sod_quest_journal_update",
    [
      (store_current_day, ":cur_day"),
      (assign, "$sod_quest_journal_active_count", 0),
      (assign, "$sod_quest_journal_pinned_count", 0),
      (assign, "$sod_quest_journal_main_count", 0),
      (assign, "$sod_quest_journal_side_count", 0),
      (assign, "$sod_quest_journal_urgent_count", 0),
      (assign, "$sod_quest_journal_completed_count", 0),
      (assign, "$sod_quest_journal_failed_count", 0),
      (assign, "$sod_quest_journal_expiring_count", 0),
      (assign, "$sod_quest_journal_capacity", sod_quest_journal_capacity_default),
      (try_for_range, ":quest_no", all_quests_begin, all_quests_end),
        (quest_get_slot, ":state", ":quest_no", slot_quest_sod_runtime_state),
        (quest_get_slot, ":flags", ":quest_no", slot_quest_sod_journal_flags),
        (quest_get_slot, ":runtime_stage", ":quest_no", slot_quest_sod_runtime_stage),
        (quest_get_slot, ":chain_progress", ":quest_no", slot_quest_sod_journal_chain_progress),
        (try_begin),
          (check_quest_active, ":quest_no"),
          (val_add, "$sod_quest_journal_active_count", 1),
          (quest_set_slot, ":quest_no", slot_quest_sod_runtime_state, sod_quest_state_active),
          (quest_set_slot, ":quest_no", slot_quest_sod_journal_stage_progress, ":runtime_stage"),
          (quest_set_slot, ":quest_no", slot_quest_sod_journal_chain_progress, ":chain_progress"),
          (call_script, "script_sod_quest_journal_set_flags", ":quest_no", ":flags", ":runtime_stage"),
          (try_begin),
            (store_and, ":is_pinned", ":flags", sod_quest_journal_flag_pinned),
            (gt, ":is_pinned", 0),
            (val_add, "$sod_quest_journal_pinned_count", 1),
          (try_end),
          (try_begin),
            (store_and, ":is_main", ":flags", sod_quest_journal_flag_main),
            (gt, ":is_main", 0),
            (val_add, "$sod_quest_journal_main_count", 1),
          (else_try),
            (store_and, ":is_urgent", ":flags", sod_quest_journal_flag_urgent),
            (gt, ":is_urgent", 0),
            (val_add, "$sod_quest_journal_urgent_count", 1),
          (else_try),
            (store_and, ":is_side", ":flags", sod_quest_journal_flag_side),
            (gt, ":is_side", 0),
            (val_add, "$sod_quest_journal_side_count", 1),
          (else_try),
            (val_add, "$sod_quest_journal_side_count", 1),
          (try_end),
          (try_begin),
            (quest_slot_ge, ":quest_no", slot_quest_expiration_days, 1),
            (quest_get_slot, ":expiration_days", ":quest_no", slot_quest_expiration_days),
            (quest_get_slot, ":start_day", ":quest_no", slot_quest_sod_runtime_last_day),
            (store_sub, ":elapsed", ":cur_day", ":start_day"),
            (store_sub, ":remaining", ":expiration_days", ":elapsed"),
            (le, ":remaining", 3),
            (ge, ":remaining", 0),
            (val_add, "$sod_quest_journal_expiring_count", 1),
            (val_or, ":flags", sod_quest_journal_flag_urgent),
            (quest_set_slot, ":quest_no", slot_quest_sod_journal_flags, ":flags"),
            (quest_set_slot, ":quest_no", slot_quest_sod_journal_category, sod_quest_journal_category_urgent),
          (try_end),
        (else_try),
          (this_or_next|eq, ":state", sod_quest_state_completed),
          (check_quest_succeeded, ":quest_no"),
          (val_add, "$sod_quest_journal_completed_count", 1),
          (quest_set_slot, ":quest_no", slot_quest_sod_journal_category, sod_quest_journal_category_completed),
          (quest_set_slot, ":quest_no", slot_quest_sod_journal_archive_day, ":cur_day"),
        (else_try),
          (this_or_next|eq, ":state", sod_quest_state_failed),
          (check_quest_failed, ":quest_no"),
          (val_add, "$sod_quest_journal_failed_count", 1),
          (quest_set_slot, ":quest_no", slot_quest_sod_journal_category, sod_quest_journal_category_failed),
          (quest_set_slot, ":quest_no", slot_quest_sod_journal_archive_day, ":cur_day"),
        (try_end),
      (try_end),
  ]),
]
