SCRIPTS = [
("sod_seven_ash_archive_aftermath_endings",
    [
      (quest_get_slot, ":recruited", "qst_seven_ash_ultimatum", slot_quest_seven_ash_recruited_bitmask),
      (quest_get_slot, ":survivors", "qst_seven_ash_ultimatum", slot_quest_seven_ash_survival_bitmask),
      (quest_get_slot, ":survivor_count", "qst_seven_ash_ultimatum", slot_quest_seven_ash_surviving_defender_count),
      (quest_get_slot, ":result_grade", "qst_seven_ash_ultimatum", slot_quest_seven_ash_result_grade),
      (quest_get_slot, ":wulfred_outcome", "qst_seven_ash_ultimatum", slot_quest_seven_ash_wulfred_outcome),
      (quest_get_slot, ":settlement", "qst_seven_ash_ultimatum", slot_quest_seven_ash_settlement_outcome),
      (quest_get_slot, ":civilian_deaths", "qst_seven_ash_ultimatum", slot_quest_seven_ash_civilian_deaths),
      (quest_get_slot, ":burned_homes", "qst_seven_ash_ultimatum", slot_quest_seven_ash_burned_homes),
      (quest_get_slot, ":promises_kept", "qst_seven_ash_ultimatum", slot_quest_seven_ash_promises_kept),
      (quest_get_slot, ":prisoners", "qst_seven_ash_ultimatum", slot_quest_seven_ash_prisoner_treatment),
      (quest_get_slot, ":final_plan", "qst_seven_ash_ultimatum", slot_quest_seven_ash_final_plan),
      (quest_get_slot, ":joined", "qst_seven_ash_ultimatum", slot_quest_seven_ash_companion_joined_bitmask),

      (assign, ":memorial", 0),
      (try_begin),
        (store_and, ":recruited_bit", ":recruited", sod_seven_ash_defender_garric),
        (gt, ":recruited_bit", 0),
        (store_and, ":survived_bit", ":survivors", sod_seven_ash_defender_garric),
        (eq, ":survived_bit", 0),
        (val_or, ":memorial", sod_seven_ash_defender_garric),
      (try_end),
      (try_begin),
        (store_and, ":recruited_bit", ":recruited", sod_seven_ash_defender_oswin),
        (gt, ":recruited_bit", 0),
        (store_and, ":survived_bit", ":survivors", sod_seven_ash_defender_oswin),
        (eq, ":survived_bit", 0),
        (val_or, ":memorial", sod_seven_ash_defender_oswin),
      (try_end),
      (try_begin),
        (store_and, ":recruited_bit", ":recruited", sod_seven_ash_defender_aldrik),
        (gt, ":recruited_bit", 0),
        (store_and, ":survived_bit", ":survivors", sod_seven_ash_defender_aldrik),
        (eq, ":survived_bit", 0),
        (val_or, ":memorial", sod_seven_ash_defender_aldrik),
      (try_end),
      (try_begin),
        (store_and, ":recruited_bit", ":recruited", sod_seven_ash_defender_mirelle),
        (gt, ":recruited_bit", 0),
        (store_and, ":survived_bit", ":survivors", sod_seven_ash_defender_mirelle),
        (eq, ":survived_bit", 0),
        (val_or, ":memorial", sod_seven_ash_defender_mirelle),
      (try_end),
      (try_begin),
        (store_and, ":recruited_bit", ":recruited", sod_seven_ash_defender_tomas),
        (gt, ":recruited_bit", 0),
        (store_and, ":survived_bit", ":survivors", sod_seven_ash_defender_tomas),
        (eq, ":survived_bit", 0),
        (val_or, ":memorial", sod_seven_ash_defender_tomas),
      (try_end),
      (try_begin),
        (store_and, ":recruited_bit", ":recruited", sod_seven_ash_defender_beren),
        (gt, ":recruited_bit", 0),
        (store_and, ":survived_bit", ":survivors", sod_seven_ash_defender_beren),
        (eq, ":survived_bit", 0),
        (val_or, ":memorial", sod_seven_ash_defender_beren),
      (try_end),
      (try_begin),
        (store_and, ":recruited_bit", ":recruited", sod_seven_ash_defender_elianor),
        (gt, ":recruited_bit", 0),
        (store_and, ":survived_bit", ":survivors", sod_seven_ash_defender_elianor),
        (eq, ":survived_bit", 0),
        (val_or, ":memorial", sod_seven_ash_defender_elianor),
      (try_end),

      (assign, ":ending_flags", 0),
      (try_begin),
        (ge, ":survivor_count", 7),
        (ge, ":promises_kept", 2),
        (val_or, ":ending_flags", sod_seven_ash_ending_seven_oaths_kept),
      (try_end),
      (try_begin),
        (neq, ":result_grade", sod_seven_ash_result_failed),
        (this_or_next|eq, ":settlement", sod_seven_ash_settlement_village),
        (eq, ":settlement", sod_seven_ash_settlement_fortified),
        (val_or, ":ending_flags", sod_seven_ash_ending_ashwick_stands),
      (try_end),
      (try_begin),
        (gt, ":memorial", 0),
        (val_or, ":ending_flags", sod_seven_ash_ending_wall_of_names),
      (try_end),
      (try_begin),
        (this_or_next|ge, ":burned_homes", 12),
        (this_or_next|eq, ":settlement", sod_seven_ash_settlement_refugee_camp),
        (eq, ":settlement", sod_seven_ash_settlement_ruined),
        (val_or, ":ending_flags", sod_seven_ash_ending_empty_houses),
      (try_end),
      (try_begin),
        (this_or_next|eq, ":wulfred_outcome", sod_seven_ash_wulfred_killed),
        (eq, ":wulfred_outcome", sod_seven_ash_wulfred_captured),
        (val_or, ":ending_flags", sod_seven_ash_ending_wulfred_broken),
      (try_end),
      (try_begin),
        (eq, ":wulfred_outcome", sod_seven_ash_wulfred_escaped),
        (val_or, ":ending_flags", sod_seven_ash_ending_wulfred_escaped),
      (try_end),
      (try_begin),
        (this_or_next|eq, ":result_grade", sod_seven_ash_result_bargain),
        (eq, ":final_plan", sod_seven_ash_plan_empty_village),
        (val_or, ":ending_flags", sod_seven_ash_ending_bargain_brand),
      (try_end),
      (try_begin),
        (this_or_next|eq, ":prisoners", sod_seven_ash_prisoners_executed),
        (eq, ":wulfred_outcome", sod_seven_ash_wulfred_killed),
        (val_or, ":ending_flags", sod_seven_ash_ending_blood_for_ash),
      (try_end),
      (try_begin),
        (gt, ":joined", 0),
        (val_or, ":ending_flags", sod_seven_ash_ending_long_road_from_ashwick),
      (try_end),
      (try_begin),
        (this_or_next|eq, ":result_grade", sod_seven_ash_result_pyrrhic),
        (ge, ":civilian_deaths", 20),
        (val_or, ":ending_flags", sod_seven_ash_ending_palisade_grave),
      (try_end),
      (try_begin),
        (this_or_next|eq, ":wulfred_outcome", sod_seven_ash_wulfred_wins),
        (eq, ":result_grade", sod_seven_ash_result_failed),
        (val_or, ":ending_flags", sod_seven_ash_ending_new_wolf),
      (try_end),
      (try_begin),
        (ge, ":promises_kept", 2),
        (le, ":civilian_deaths", 8),
        (val_or, ":ending_flags", sod_seven_ash_ending_common_bell),
      (try_end),

      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_memorial_bitmask, ":memorial"),
      (quest_set_slot, "qst_seven_ash_ultimatum", slot_quest_seven_ash_ending_flags, ":ending_flags"),
      (assign, reg3, ":memorial"),
      (assign, reg4, ":ending_flags"),
      (str_store_string, s49, "@Ashwick's last record names the endings left behind: Seven Oaths Kept, Ashwick Stands, Wall of Names, Empty Houses, Wulfred Broken, Wulfred Escaped, Bargain Brand, Blood for Ash, Long Road From Ashwick, Palisade Grave, New Wolf, and Common Bell."),
      (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 9, s49, 0),
      (try_begin),
        (gt, ":memorial", 0),
        (str_store_string, s49, "@Memorial roll: dead defenders are recorded by craft and relationship - Garric's sightlines, Oswin's timber, Aldrik's oath, Mirelle's doors, Tomas's drill, Beren's breach, and Elianor's water."),
        (add_quest_note_from_sreg, "qst_seven_ash_aftermath", 10, s49, 0),
      (try_end),
  ]),
]
