from header_operations import *
from module_constants import *

SCRIPTS = [
("sod_rtc_archive_campaign_ending",
    [
      (store_script_param, ":final_outcome", 1),
      (quest_get_slot, ":branch", "qst_rtc_final_confrontation", slot_quest_rtc_branch_seed),
      (quest_get_slot, ":faith", "qst_rtc_final_confrontation", slot_quest_rtc_faith),
      (quest_get_slot, ":motive", "qst_rtc_final_confrontation", slot_quest_rtc_motive),
      (quest_get_slot, ":flags", "qst_rtc_final_confrontation", slot_quest_rtc_flags),
      (quest_get_slot, ":offer", "qst_rtc_final_confrontation", slot_quest_object_troop),
      (assign, ":has_reform_flag", ":flags"),
      (val_and, ":has_reform_flag", sod_rtc_flag_route_reform),
      (assign, ":has_accusation_turned", ":flags"),
      (val_and, ":has_accusation_turned", sod_rtc_flag_envoy_accusation_turned),

      (assign, ":ending", sod_rtc_ending_crown_of_law),
      (assign, ":successor", sod_rtc_successor_governance_campaign),

      (try_begin),
        (this_or_next|eq, ":final_outcome", sod_rtc_final_claim_collapse),
        (eq, ":branch", sod_rtc_branch_fractured_claim),
        (assign, ":ending", sod_rtc_ending_crown_of_ashes),
        (assign, ":successor", sod_rtc_successor_exile_redemption),
      (else_try),
        (eq, ":final_outcome", sod_rtc_final_unworn_crown),
        (assign, ":ending", sod_rtc_ending_unworn_crown),
        (assign, ":successor", sod_rtc_successor_league_protector),
      (else_try),
        (this_or_next|eq, ":final_outcome", sod_rtc_final_marius_overlord),
        (eq, ":branch", sod_rtc_branch_imperial),
        (assign, ":ending", sod_rtc_ending_crown_of_empire),
        (assign, ":successor", sod_rtc_successor_imperial_civil_war),
      (else_try),
        (eq, ":branch", sod_rtc_branch_restoration),
        (assign, ":ending", sod_rtc_ending_crown_of_return),
        (assign, ":successor", sod_rtc_successor_homeland_restoration),
      (else_try),
        (this_or_next|eq, ":branch", sod_rtc_branch_conquest),
        (eq, ":branch", sod_rtc_branch_regime_maker),
        (try_begin),
          (eq, ":motive", cb4_revenge),
          (assign, ":ending", sod_rtc_ending_crown_of_vengeance),
          (assign, ":successor", sod_rtc_successor_survivor_reckoning),
        (else_try),
          (assign, ":ending", sod_rtc_ending_crown_of_iron),
          (assign, ":successor", sod_rtc_successor_rebellion_reform),
        (try_end),
      (else_try),
        (eq, ":branch", sod_rtc_branch_mercenary),
        (assign, ":ending", sod_rtc_ending_crown_of_coin),
        (assign, ":successor", sod_rtc_successor_merchant_league),
      (else_try),
        (this_or_next|eq, ":faith", cb_the_one),
        (eq, ":faith", cb_old_gods),
        (this_or_next|gt, ":has_reform_flag", 0),
        (eq, ":branch", sod_rtc_branch_coalition),
        (assign, ":ending", sod_rtc_ending_crown_of_faith),
        (assign, ":successor", sod_rtc_successor_schism_reform),
      (try_end),

      (quest_set_slot, "qst_rtc_final_confrontation", slot_quest_rtc_final_ending, ":ending"),
      (quest_set_slot, "qst_rtc_final_confrontation", slot_quest_rtc_successor_unlock, ":successor"),
      (quest_get_slot, ":journal_flags", "qst_rtc_final_confrontation", slot_quest_sod_journal_flags),
      (val_or, ":journal_flags", sod_quest_journal_flag_archived),
      (quest_set_slot, "qst_rtc_final_confrontation", slot_quest_sod_journal_flags, ":journal_flags"),
      (try_begin),
        (eq, ":ending", sod_rtc_ending_crown_of_ashes),
        (quest_set_slot, "qst_rtc_final_confrontation", slot_quest_sod_journal_category, sod_quest_journal_category_failed),
      (else_try),
        (quest_set_slot, "qst_rtc_final_confrontation", slot_quest_sod_journal_category, sod_quest_journal_category_completed),
      (try_end),

      (try_begin),
        (eq, ":ending", sod_rtc_ending_crown_of_law),
        (str_store_string, s49, "@Ending: Crown of Law. The next road opens toward governance, courts, and the burdens of ruling in public."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_crown_of_iron),
        (str_store_string, s49, "@Ending: Crown of Iron. The next road opens toward rebellion, military reform, and the price of rule by force."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_crown_of_coin),
        (str_store_string, s49, "@Ending: Crown of Coin. The next road opens toward merchant leagues, contracts, and power measured in routes."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_crown_of_ashes),
        (str_store_string, s49, "@Ending: Crown of Ashes. The next road opens toward exile, redemption, and debts carried out of ruin."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_crown_of_faith),
        (str_store_string, s49, "@Ending: Crown of Faith. The next road opens toward schism, reform, and oaths that must feed the living."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_crown_of_vengeance),
        (str_store_string, s49, "@Ending: Crown of Vengeance. The next road opens toward survivor reckoning and the cost of making memory into a blade."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_crown_of_return),
        (str_store_string, s49, "@Ending: Crown of Return. The next road opens toward homeland restoration and promises made to the dead."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_crown_of_empire),
        (str_store_string, s49, "@Ending: Crown of Empire. The next road opens toward province, patronage, and Imperial civil war."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (else_try),
        (eq, ":ending", sod_rtc_ending_unworn_crown),
        (str_store_string, s49, "@Ending: Unworn Crown. The next road opens toward league, protectorate, and authority without a throne."),

        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 4, s49, 0),
      (try_end),

      (try_begin),
        (gt, ":has_accusation_turned", 0),
        (str_store_string, s49, "@Archive: The envoy dispute survived into the ending. Later campaigns can treat the crown as having won a public accusation battle, not merely a field victory."),
        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 6, s49, 0),
      (try_end),
      (try_begin),
        (eq, ":offer", sod_rtc_offer_bread_oath),
        (str_store_string, s49, "@Archive: The first oath of this crown was bread. Successor arcs can remember hunger, granaries, refugees, and commoner trust as founding pressure."),
        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 7, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_books_oath),
        (str_store_string, s49, "@Archive: The first oath of this crown was books. Successor arcs can remember roads, contracts, grain ledgers, and merchant trust as founding pressure."),
        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 7, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_witness_oath),
        (str_store_string, s49, "@Archive: The first oath of this crown was witness. Successor arcs can remember testimony, courts, and witness protection as founding pressure."),
        (add_quest_note_from_sreg, "qst_rtc_final_confrontation", 7, s49, 0),
      (try_end),
  ]),
]
