SCRIPTS = [
("sod_rtc_last_road_prepare_strategy_target",
    [
      (store_script_param, ":force_refresh", 1),
      (quest_get_slot, ":target_party", "qst_rtc_last_road", slot_quest_target_party),
      (try_begin),
        (this_or_next|le, ":target_party", 0),
        (neg|party_is_active, ":target_party"),
        (quest_get_slot, ":strategy", "qst_rtc_last_road", slot_quest_rtc_method_seed),
        (quest_get_slot, ":spawn_center", "qst_rtc_last_road", slot_quest_target_center),
        (try_begin),
          (neg|is_between, ":spawn_center", centers_begin, centers_end),
          (assign, ":spawn_center", "p_main_party"),
        (try_end),

        (assign, ":template", "pt_sod_diplomatic_envoy"),
        (try_begin),
          (eq, ":strategy", sod_rtc_last_road_hold_line),
          (assign, ":template", "pt_sod_diplomatic_envoy"),
        (else_try),
          (eq, ":strategy", sod_rtc_last_road_strike_hound),
          (assign, ":template", "pt_sod_diplomatic_envoy"),
        (else_try),
          (eq, ":strategy", sod_rtc_last_road_starve_empire),
          (assign, ":template", "pt_kingdom_caravan_party"),
        (else_try),
          (eq, ":strategy", sod_rtc_last_road_break_seal),
          (assign, ":template", "pt_sod_diplomatic_envoy"),
        (else_try),
          (eq, ":strategy", sod_rtc_last_road_accept_collar),
          (assign, ":template", "pt_sod_diplomatic_envoy"),
        (else_try),
          (eq, ":strategy", sod_rtc_last_road_turn_accusation),
          (assign, ":template", "pt_sod_diplomatic_envoy"),
        (else_try),
          (eq, ":strategy", sod_rtc_last_road_catastrophic_loss),
          (assign, ":template", "pt_bandits"),
        (try_end),

        (call_script, "script_sod_rtc_prepare_temporary_target", "qst_rtc_last_road", ":template", ":spawn_center", 6, ":force_refresh"),
      (try_end),
  ]),
]
