SCRIPTS = [
("sod_rtc_price_of_bread_bind_world",
    [
      (quest_get_slot, ":target_center", "qst_rtc_price_of_bread", slot_quest_target_center),
      (try_begin),
        (neg|is_between, ":target_center", villages_begin, villages_end),
        (call_script, "script_get_closest_village", "p_main_party"),
        (assign, ":target_center", reg0),
      (try_end),
      (try_begin),
        (neg|is_between, ":target_center", villages_begin, villages_end),
        (assign, ":target_center", villages_begin),
      (try_end),

      (try_begin),
        (is_between, ":target_center", villages_begin, villages_end),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_target_center, ":target_center"),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_target_troop, "trp_rtc_tamsin_reedhand"),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_object_troop, "trp_rtc_celeste_di_marina"),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_giver_troop, "trp_rtc_brother_odran"),

        (party_get_slot, ":prosperity", ":target_center", slot_town_prosperity),
        (assign, ":pressure", 1),
        (try_begin),
          (lt, ":prosperity", 25),
          (assign, ":pressure", 3),
        (else_try),
          (lt, ":prosperity", 50),
          (assign, ":pressure", 2),
        (try_end),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_target_amount, ":pressure"),

        (quest_get_slot, ":contact", "qst_rtc_price_of_bread", slot_quest_rtc_social_contact),
        (try_begin),
          (eq, ":contact", sod_rtc_contact_road_scout),
          (call_script, "script_sod_rtc_price_of_bread_prepare_bandit_target"),
        (try_end),
      (try_end),
  ]),
]
