SCRIPTS = [
("sod_seven_ash_set_defender_status",
    [
      (store_script_param, ":defender_bit", 1),
      (store_script_param, ":new_status", 2),
      (assign, ":status_slot", slot_quest_seven_ash_garric_status),

      (try_begin),
        (eq, ":defender_bit", sod_seven_ash_defender_garric),
        (assign, ":status_slot", slot_quest_seven_ash_garric_status),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_oswin),
        (assign, ":status_slot", slot_quest_seven_ash_oswin_status),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_aldrik),
        (assign, ":status_slot", slot_quest_seven_ash_aldrik_status),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_mirelle),
        (assign, ":status_slot", slot_quest_seven_ash_mirelle_status),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_tomas),
        (assign, ":status_slot", slot_quest_seven_ash_tomas_status),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_beren),
        (assign, ":status_slot", slot_quest_seven_ash_beren_status),
      (else_try),
        (eq, ":defender_bit", sod_seven_ash_defender_elianor),
        (assign, ":status_slot", slot_quest_seven_ash_elianor_status),
      (try_end),

      (quest_get_slot, ":old_status", "qst_seven_ash_ultimatum", ":status_slot"),

      (try_begin),
        (this_or_next|eq, ":old_status", sod_seven_ash_recruit_recruited),
        (this_or_next|eq, ":old_status", sod_seven_ash_recruit_refused),
        (this_or_next|eq, ":old_status", sod_seven_ash_recruit_alienated),
        (this_or_next|eq, ":old_status", sod_seven_ash_recruit_lost),
        (eq, ":old_status", sod_seven_ash_recruit_abandoned),
        (assign, ":already_terminal", 1),
      (else_try),
        (assign, ":already_terminal", 0),
      (try_end),

      (try_begin),
        (eq, ":already_terminal", 0),
        (quest_set_slot, "qst_seven_ash_ultimatum", ":status_slot", ":new_status"),
        (this_or_next|eq, ":new_status", sod_seven_ash_recruit_recruited),
        (this_or_next|eq, ":new_status", sod_seven_ash_recruit_refused),
        (this_or_next|eq, ":new_status", sod_seven_ash_recruit_alienated),
        (this_or_next|eq, ":new_status", sod_seven_ash_recruit_lost),
        (eq, ":new_status", sod_seven_ash_recruit_abandoned),
        (call_script, "script_sod_seven_ash_mark_defender_resolved", ":defender_bit", ":new_status"),
      (try_end),
  ]),
]
