SCRIPTS = [
("sod_rtc_three_offers_prepare_route_target",
    [
      (store_script_param, ":offer", 1),
      (quest_get_slot, ":target_party", "qst_rtc_three_offers", slot_quest_target_party),
      (try_begin),
        (gt, ":target_party", 0),
        (party_is_active, ":target_party"),
        (remove_party, ":target_party"),
      (try_end),

      (quest_get_slot, ":spawn_center", "qst_rtc_three_offers", slot_quest_target_center),
      (try_begin),
        (neg|is_between, ":spawn_center", centers_begin, centers_end),
        (assign, ":spawn_center", "p_main_party"),
      (try_end),

      (assign, ":template", "pt_sod_diplomatic_envoy"),
      (try_begin),
        (eq, ":offer", sod_rtc_offer_noble_protection),
        (assign, ":template", "pt_sod_diplomatic_envoy"),
      (else_try),
        (eq, ":offer", sod_rtc_offer_paid_steel),
        (assign, ":template", "pt_merchant_caravan"),
      (else_try),
        (eq, ":offer", sod_rtc_offer_peoples_road),
        (assign, ":template", "pt_scout_party"),
      (else_try),
        (eq, ":offer", sod_rtc_offer_hard_claim),
        (assign, ":template", "pt_bandits"),
      (else_try),
        (eq, ":offer", sod_rtc_offer_quiet_ledger),
        (assign, ":template", "pt_bandits"),
      (else_try),
        (assign, ":template", "pt_scout_party"),
      (try_end),

      (set_spawn_radius, 4),
      (spawn_around_party, ":spawn_center", ":template"),
      (assign, ":target_party", reg0),
      (quest_set_slot, "qst_rtc_three_offers", slot_quest_target_party, ":target_party"),
      (quest_set_slot, "qst_rtc_three_offers", slot_quest_target_party_template, ":template"),
  ]),
]
