SCRIPTS = [
("sod_rtc_borrowed_names_choose_identity",
    [
      (store_script_param, ":reputation", 1),
      (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_reputation, ":reputation"),
      (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_reputation, ":reputation"),
      (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_reputation, ":reputation"),
      (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_reputation, ":reputation"),
      (quest_get_slot, ":camp_target_party", "qst_rtc_borrowed_names", slot_quest_target_party),

      (try_begin),
        (eq, ":reputation", sod_rtc_reputation_foreign_noble),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_noble_trust, 1),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_noble_trust, 1),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_noble_trust, 1),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_noble_trust, 1),
        (str_store_string, s49, "@Lysara wrote you as a noble of a fallen house. Calradia will hear a claim before it hears a plea."),

        (add_quest_note_from_sreg, "qst_rtc_borrowed_names", 3, s49, 0),
      (else_try),
        (eq, ":reputation", sod_rtc_reputation_free_captain),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_method_seed, sod_rtc_method_honor),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_method_seed, sod_rtc_method_honor),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_method_seed, sod_rtc_method_honor),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_method_seed, sod_rtc_method_honor),
        (str_store_string, s49, "@Lysara wrote you as a captain looking for work. Soldiers and marshals will understand that language."),

        (add_quest_note_from_sreg, "qst_rtc_borrowed_names", 3, s49, 0),
      (else_try),
        (eq, ":reputation", sod_rtc_reputation_trade_operator),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_merchant_trust, 1),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_merchant_trust, 1),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_merchant_trust, 1),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_merchant_trust, 1),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_method_seed, sod_rtc_method_trade),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_method_seed, sod_rtc_method_trade),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_method_seed, sod_rtc_method_trade),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_method_seed, sod_rtc_method_trade),
        (str_store_string, s49, "@Lysara wrote you as a trader with surviving contacts. Coin, supply, and debt will open the first doors."),

        (add_quest_note_from_sreg, "qst_rtc_borrowed_names", 3, s49, 0),
      (else_try),
        (eq, ":reputation", sod_rtc_reputation_refugee),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_commoner_trust, 1),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_commoner_trust, 1),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_commoner_trust, 1),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_commoner_trust, 1),
        (str_store_string, s49, "@Lysara wrote you as another exile. The camp trusts the honesty more than the world will."),

        (add_quest_note_from_sreg, "qst_rtc_borrowed_names", 3, s49, 0),
      (else_try),
        (eq, ":reputation", sod_rtc_reputation_avenger),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_rising),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_rising),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_rising),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_rising),
        (str_store_string, s49, "@Lysara wrote that you are owed blood. Some will call that justice; others will call it warning."),

        (add_quest_note_from_sreg, "qst_rtc_borrowed_names", 3, s49, 0),
      (else_try),
        (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_rtc_reputation, sod_rtc_reputation_unproven),
        (quest_set_slot, "qst_rtc_hound_sign", slot_quest_rtc_reputation, sod_rtc_reputation_unproven),
        (quest_set_slot, "qst_rtc_door_into_calradia", slot_quest_rtc_reputation, sod_rtc_reputation_unproven),
        (quest_set_slot, "qst_rtc_price_of_bread", slot_quest_rtc_reputation, sod_rtc_reputation_unproven),
        (str_store_string, s49, "@No clear public name took hold in the camp. Calradia will meet you as an unproven stranger."),

        (add_quest_note_from_sreg, "qst_rtc_borrowed_names", 3, s49, 0),
      (try_end),

      (try_begin),
        (gt, ":camp_target_party", 0),
        (neq, ":camp_target_party", "p_main_party"),
        (party_is_active, ":camp_target_party"),
        (str_store_party_name_link, s48, ":camp_target_party"),
        (str_store_string, s49, "@Camp event: Lysara's ledger closed over testimony from {s48}. The public name was chosen in front of surviving road witnesses, not in private."),
        (add_quest_note_from_sreg, "qst_rtc_borrowed_names", 5, s49, 0),
        (remove_party, ":camp_target_party"),
      (try_end),
      (quest_set_slot, "qst_rtc_last_smoke", slot_quest_target_party, -1),
      (quest_set_slot, "qst_rtc_last_smoke", slot_quest_target_party_template, -1),
      (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_target_party, -1),
      (quest_set_slot, "qst_rtc_borrowed_names", slot_quest_target_party_template, -1),
      (quest_set_slot, "qst_rtc_hound_sign", slot_quest_target_party, -1),
      (quest_set_slot, "qst_rtc_hound_sign", slot_quest_target_party_template, -1),

      (call_script, "script_succeed_quest", "qst_rtc_borrowed_names"),
      (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_borrowed_names", "qst_rtc_hound_sign", 0),
  ]),
]
