SCRIPTS = [
("sod_quest_chain_advance",
    [
      (store_script_param, ":quest_no", 1),
      (store_script_param, ":branch_type", 2),
      (store_script_param, ":next_quest", 3),
      (store_script_param, ":delay_days", 4),
      (store_current_day, ":cur_day"),
      (quest_set_slot, ":quest_no", slot_quest_sod_chain_branch, ":branch_type"),
      (quest_set_slot, ":quest_no", slot_quest_sod_chain_next_quest, ":next_quest"),
      (try_begin),
        (gt, ":delay_days", 0),
        (store_add, ":resume_day", ":cur_day", ":delay_days"),
        (quest_set_slot, ":quest_no", slot_quest_sod_chain_resume_day, ":resume_day"),
        (quest_set_slot, ":quest_no", slot_quest_sod_chain_lock_state, sod_quest_chain_lock_resuming),
        (quest_get_slot, ":flags", ":quest_no", slot_quest_sod_chain_flags),
        (val_or, ":flags", sod_quest_chain_flag_resume_pending),
        (quest_set_slot, ":quest_no", slot_quest_sod_chain_flags, ":flags"),
        (str_store_quest_name, s1, ":quest_no"),
        (display_message, "@Quest chain delayed: {s1} will resume after new developments.", quest_success_color),
      (else_try),
        (is_between, ":next_quest", all_quests_begin, all_quests_end),
        (quest_get_slot, ":chain_id", ":quest_no", slot_quest_sod_chain_id),
        (quest_get_slot, ":step_no", ":quest_no", slot_quest_sod_chain_step),
        (val_add, ":step_no", 1),
        (quest_set_slot, ":next_quest", slot_quest_sod_chain_id, ":chain_id"),
        (quest_set_slot, ":next_quest", slot_quest_sod_chain_step, ":step_no"),
        (quest_set_slot, ":next_quest", slot_quest_sod_chain_previous_quest, ":quest_no"),
        (quest_set_slot, ":next_quest", slot_quest_sod_journal_chain_progress, ":step_no"),
        (quest_set_slot, ":next_quest", slot_quest_sod_journal_category, sod_quest_journal_category_main),
        (setup_quest_text, ":next_quest"),
        (str_store_string, s2, "@A connected quest has begun."),
        (call_script, "script_start_quest", ":next_quest", "trp_player"),
        (str_store_quest_name, s1, ":next_quest"),
        (display_message, "@Quest chain advanced: {s1}.", quest_success_color),
      (else_try),
        (quest_set_slot, ":quest_no", slot_quest_sod_chain_ending, ":branch_type"),
        (try_begin),
          (eq, ":branch_type", sod_quest_chain_branch_failure),
          (quest_set_slot, ":quest_no", slot_quest_sod_chain_lock_state, sod_quest_chain_lock_failed),
        (else_try),
          (quest_set_slot, ":quest_no", slot_quest_sod_chain_lock_state, sod_quest_chain_lock_completed),
        (try_end),
      (try_end),
  ]),
]
