from header_operations import *
from module_constants import *

SCRIPTS = [
("sod_rtc_first_recognition_resolve",
    [
      (store_script_param, ":recognition", 1),
      (quest_get_slot, ":flags", "qst_rtc_first_recognition", slot_quest_rtc_flags),
      (quest_get_slot, ":route", "qst_rtc_first_recognition", slot_quest_rtc_branch_seed),
      (quest_get_slot, ":offer", "qst_rtc_first_recognition", slot_quest_sod_chain_choice),
      (quest_get_slot, ":bread_center", "qst_rtc_first_recognition", slot_quest_target_center),
      (quest_get_slot, ":grain_pressure", "qst_rtc_first_recognition", slot_quest_target_amount),
      (call_script, "script_sod_rtc_first_recognition_prepare_witness_target", ":recognition"),
      (quest_get_slot, ":recognition_target_party", "qst_rtc_first_recognition", slot_quest_target_party),
      (quest_get_slot, ":recognition_target_template", "qst_rtc_first_recognition", slot_quest_target_party_template),

      (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_rising),
      (try_begin),
        (eq, ":recognition", sod_rtc_recognition_lawful_claimant),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_method_seed, sod_rtc_recognition_lawful_claimant),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_branch_seed, sod_rtc_branch_legitimacy),
        (str_store_string, s49, "@First recognition: lawful claimant. A court witness has repeated your name as something more than an armed refugee."),

        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 3, s49, 0),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_free_captain),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_method_seed, sod_rtc_recognition_free_captain),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_branch_seed, sod_rtc_branch_mercenary),
        (str_store_string, s49, "@First recognition: free captain. Soldiers and employers now speak of your company as a force that can be bargained with."),

        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 3, s49, 0),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_trade_power),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_method_seed, sod_rtc_recognition_trade_power),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_branch_seed, sod_rtc_branch_mercenary),
        (str_store_string, s49, "@First recognition: trade power. Guild factors and caravan masters now count your protection, threats, and contracts in the same column."),

        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 3, s49, 0),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_people_defender),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_method_seed, sod_rtc_recognition_people_defender),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_branch_seed, sod_rtc_branch_coalition),
        (val_or, ":flags", sod_rtc_flag_route_reform),
        (str_store_string, s49, "@First recognition: people's defender. Villages and refugees have begun using your name as a promise, not only a warning."),

        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 3, s49, 0),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_dangerous_warlord),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_method_seed, sod_rtc_recognition_dangerous_warlord),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_branch_seed, sod_rtc_branch_conquest),
        (val_or, ":flags", sod_rtc_flag_route_betrayal),
        (str_store_string, s49, "@First recognition: dangerous warlord. Rivals now plan around your violence, and some allies do too."),

        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 3, s49, 0),
      (else_try),
        (eq, ":recognition", sod_rtc_recognition_shadow_operator),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_method_seed, sod_rtc_recognition_shadow_operator),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_branch_seed, sod_rtc_branch_regime_maker),
        (val_or, ":flags", sod_rtc_flag_route_hidden_regime_maker),
        (str_store_string, s49, "@First recognition: shadow operator. The first people to recognize your claim are those who profit from never saying it aloud."),

        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 3, s49, 0),
      (else_try),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_method_seed, sod_rtc_recognition_none),
        (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_branch_seed, ":route"),
        (str_store_string, s49, "@First recognition remains unsettled. Calradia knows you are present, but not yet what kind of power you are."),

        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 3, s49, 0),
      (try_end),

      (try_begin),
        (eq, ":offer", sod_rtc_offer_witness_oath),
        (val_or, ":flags", sod_rtc_flag_witness_noble),
        (str_store_string, s49, "@The witness oath shaped first recognition. Even when the label changed, people repeated that the claim had bound itself to testimony before patrons."),
        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 5, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_books_oath),
        (val_or, ":flags", sod_rtc_flag_witness_fourth),
        (val_or, ":flags", sod_rtc_flag_merchant_trust_high),
        (str_store_string, s49, "@The books oath shaped first recognition. Roads, grain, and debt gave merchants a vocabulary for the claim before courts did."),
        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 5, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_bread_oath),
        (val_or, ":flags", sod_rtc_flag_witness_commoner),
        (val_or, ":flags", sod_rtc_flag_commoner_trust_high),
        (str_store_string, s49, "@The bread oath shaped first recognition. Refugees and villagers repeated the claim as a promise that rule begins where hunger is answered."),
        (add_quest_note_from_sreg, "qst_rtc_first_recognition", 5, s49, 0),
      (try_end),

      (quest_set_slot, "qst_rtc_first_recognition", slot_quest_rtc_flags, ":flags"),
      (quest_get_slot, ":final_route", "qst_rtc_first_recognition", slot_quest_rtc_branch_seed),
      (quest_get_slot, ":reputation", "qst_rtc_first_recognition", slot_quest_rtc_reputation),
      (quest_get_slot, ":commoner_trust", "qst_rtc_first_recognition", slot_quest_rtc_commoner_trust),
      (quest_get_slot, ":merchant_trust", "qst_rtc_first_recognition", slot_quest_rtc_merchant_trust),
      (quest_get_slot, ":noble_trust", "qst_rtc_first_recognition", slot_quest_rtc_noble_trust),
      (quest_get_slot, ":pressure", "qst_rtc_first_recognition", slot_quest_rtc_imperial_pressure),
      (quest_get_slot, ":companion_pressure", "qst_rtc_first_recognition", slot_quest_rtc_companion_pressure),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_branch_seed, ":final_route"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_reputation, ":reputation"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_commoner_trust, ":commoner_trust"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_merchant_trust, ":merchant_trust"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_noble_trust, ":noble_trust"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_imperial_pressure, ":pressure"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_companion_pressure, ":companion_pressure"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_method_seed, ":recognition"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_sod_chain_choice, ":offer"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_target_center, ":bread_center"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_target_amount, ":grain_pressure"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_target_party, ":recognition_target_party"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_target_party_template, ":recognition_target_template"),
      (quest_set_slot, "qst_rtc_crown_council", slot_quest_rtc_flags, ":flags"),
      (call_script, "script_succeed_quest", "qst_rtc_first_recognition"),
      (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_first_recognition", "qst_rtc_crown_council", 0),
  ]),
]
