SCRIPTS = [
("sod_quest_outcome_configure_unlocks",
    [
      (store_script_param, ":quest_no", 1),
      (store_script_param, ":access_flags", 2),
      (store_script_param, ":title_id", 3),
      (store_script_param, ":discount_value", 4),
      (store_script_param, ":followup_quest", 5),
      (quest_set_slot, ":quest_no", slot_quest_sod_reward_access_flags, ":access_flags"),
      (quest_set_slot, ":quest_no", slot_quest_sod_reward_title, ":title_id"),
      (quest_set_slot, ":quest_no", slot_quest_sod_reward_discount, ":discount_value"),
      (quest_set_slot, ":quest_no", slot_quest_sod_reward_followup_quest, ":followup_quest"),
      (quest_get_slot, ":flags", ":quest_no", slot_quest_sod_outcome_flags),
      (try_begin),
        (gt, ":access_flags", 0),
        (val_or, ":flags", sod_quest_outcome_flag_access_unlock),
      (try_end),
      (try_begin),
        (is_between, ":followup_quest", all_quests_begin, all_quests_end),
        (val_or, ":flags", sod_quest_outcome_flag_followup),
      (try_end),
      (quest_set_slot, ":quest_no", slot_quest_sod_outcome_flags, ":flags"),
  ]),
]
