SCRIPTS = [
("sod_quest_chain_resume_due",
    [
      (store_current_day, ":cur_day"),
      (try_for_range, ":quest_no", all_quests_begin, all_quests_end),
        (quest_slot_eq, ":quest_no", slot_quest_sod_chain_lock_state, sod_quest_chain_lock_resuming),
        (quest_get_slot, ":resume_day", ":quest_no", slot_quest_sod_chain_resume_day),
        (gt, ":resume_day", 0),
        (ge, ":cur_day", ":resume_day"),
        (quest_get_slot, ":next_quest", ":quest_no", slot_quest_sod_chain_next_quest),
        (quest_set_slot, ":quest_no", slot_quest_sod_chain_lock_state, sod_quest_chain_lock_none),
        (quest_set_slot, ":quest_no", slot_quest_sod_chain_resume_day, 0),
        (quest_get_slot, ":flags", ":quest_no", slot_quest_sod_chain_flags),
        (val_and, ":flags", -9),
        (quest_set_slot, ":quest_no", slot_quest_sod_chain_flags, ":flags"),
        (try_begin),
          (is_between, ":next_quest", all_quests_begin, all_quests_end),
          (quest_get_slot, ":chain_id", ":quest_no", slot_quest_sod_chain_id),
          (quest_get_slot, ":step_no", ":quest_no", slot_quest_sod_chain_step),
          (val_add, ":step_no", 1),
          (quest_set_slot, ":next_quest", slot_quest_sod_chain_id, ":chain_id"),
          (quest_set_slot, ":next_quest", slot_quest_sod_chain_step, ":step_no"),
          (quest_set_slot, ":next_quest", slot_quest_sod_chain_previous_quest, ":quest_no"),
          (quest_set_slot, ":next_quest", slot_quest_sod_journal_chain_progress, ":step_no"),
          (quest_set_slot, ":next_quest", slot_quest_sod_journal_category, sod_quest_journal_category_main),
          (setup_quest_text, ":next_quest"),
          (str_store_string, s2, "@A delayed quest chain has resumed."),
          (call_script, "script_start_quest", ":next_quest", "trp_player"),
          (str_store_quest_name, s1, ":next_quest"),
          (display_message, "@Quest chain resumed: {s1}.", quest_success_color),
        (try_end),
      (try_end),
  ]),
]
