from header_operations import *
from module_constants import *

SCRIPTS = [
("sod_rtc_war_of_witnesses_resolve",
    [
      (store_script_param, ":war_choice", 1),
      (call_script, "script_sod_rtc_war_of_witnesses_prepare_target"),
      (quest_get_slot, ":flags", "qst_rtc_war_of_witnesses", slot_quest_rtc_flags),
      (quest_get_slot, ":route", "qst_rtc_war_of_witnesses", slot_quest_rtc_branch_seed),
      (quest_get_slot, ":bread_center", "qst_rtc_war_of_witnesses", slot_quest_target_center),
      (quest_get_slot, ":grain_pressure", "qst_rtc_war_of_witnesses", slot_quest_target_amount),
      (quest_get_slot, ":envoy_handling", "qst_rtc_war_of_witnesses", slot_quest_sod_chain_choice),
      (quest_get_slot, ":offer", "qst_rtc_war_of_witnesses", slot_quest_object_troop),

      (try_begin),
        (eq, ":war_choice", sod_rtc_witness_war_protect),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_method_seed, sod_rtc_witness_war_protect),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_caravan_protection, 2),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_help_village, 1),
        (str_store_string, s49, "@You protected the witnesses who made the crown possible. The Imperial answer becomes harder because the story still has living voices."),

        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (try_begin),
          (is_between, ":bread_center", centers_begin, centers_end),
          (str_store_party_name_link, s48, ":bread_center"),
          (str_store_string, s49, "@The witness from {s48} survived the Imperial pressure. The bread story remains anchored to a living place."),
          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 4, s49, 0),
          (call_script, "script_change_player_relation_with_center", ":bread_center", 1),
        (try_end),
        (call_script, "script_succeed_quest", "qst_rtc_war_of_witnesses"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_war_of_witnesses", "qst_rtc_last_road", 0),
      (else_try),
        (eq, ":war_choice", sod_rtc_witness_war_route_variant),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_method_seed, sod_rtc_witness_war_route_variant),
        (try_begin),
          (eq, ":route", sod_rtc_branch_conquest),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_hard_victory, 3),
          (str_store_string, s49, "@Route variant: you broke an Imperial vanguard before it could reach the witnesses."),

          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (else_try),
          (eq, ":route", sod_rtc_branch_mercenary),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_caravan_protection, 3),
          (str_store_string, s49, "@Route variant: you secured the payroll and supply road that keeps the claim armed."),

          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (else_try),
          (eq, ":route", sod_rtc_branch_restoration),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_free_captives, 3),
          (str_store_string, s49, "@Route variant: you rescued homeland survivors before Marius could turn memory into a hostage."),

          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (else_try),
          (eq, ":route", sod_rtc_branch_imperial),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_diplomacy_betrayal, 2),
          (str_store_string, s49, "@Route variant: you proved Imperial loyalty on paper while keeping enough witnesses alive to matter later."),

          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (else_try),
          (eq, ":route", sod_rtc_branch_regime_maker),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_stealth_success, 3),
          (str_store_string, s49, "@Route variant: the quiet ledger moved witnesses, pursuers, and false trails with fewer losses than anyone can publicly explain."),

          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (else_try),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_scout_warning, 2),
          (str_store_string, s49, "@Route variant: you answered the witness war in the shape your route could sustain."),

          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (try_end),
        (call_script, "script_succeed_quest", "qst_rtc_war_of_witnesses"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_war_of_witnesses", "qst_rtc_last_road", 0),
      (else_try),
        (eq, ":war_choice", sod_rtc_witness_war_side_crisis),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_method_seed, sod_rtc_witness_war_side_crisis),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_open),
        (str_store_string, s49, "@The witness war has spilled into the Last Banner of the East crisis. This campaign now has a side-crisis handoff point."),

        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (call_script, "script_succeed_quest", "qst_rtc_war_of_witnesses"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_war_of_witnesses", "qst_rtc_last_road", 0),
      (else_try),
        (eq, ":war_choice", sod_rtc_witness_war_envoy_leverage),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_method_seed, sod_rtc_witness_war_envoy_leverage),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_rising),
        (try_begin),
          (eq, ":envoy_handling", 2),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_hard_victory, 2),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_diplomacy_betrayal, 1),
          (str_store_string, s49, "@You used the detained envoy as hard leverage. Marius's witness hunt slows while every camp argues whether this is law, hostage craft, or survival."),
        (else_try),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_scout_warning, 2),
          (call_script, "script_sod_companion_apply_player_action", sod_companion_action_honorable_peace, 1),
          (str_store_string, s49, "@You used your counter-demand to muddy the witness hunt. Imperial officers now spend as much effort answering your terms as frightening your witnesses."),
        (try_end),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (try_begin),
          (is_between, ":bread_center", centers_begin, centers_end),
          (str_store_party_name_link, s48, ":bread_center"),
          (str_store_string, s49, "@The witness from {s48} survives because the Imperial script no longer reaches every village cleanly."),
          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 4, s49, 0),
          (call_script, "script_change_player_relation_with_center", ":bread_center", 1),
        (try_end),
        (call_script, "script_succeed_quest", "qst_rtc_war_of_witnesses"),
        (call_script, "script_sod_quest_chain_branch_success", "qst_rtc_war_of_witnesses", "qst_rtc_last_road", 0),
      (else_try),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_method_seed, sod_rtc_witness_war_sacrifice),
        (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_imperial_pressure, sod_rtc_pressure_invasion),
        (val_and, ":flags", -8388609),
        (call_script, "script_sod_companion_apply_player_action", sod_companion_action_diplomacy_betrayal, 3),
        (str_store_string, s49, "@You sacrificed a witness to preserve the route. The crown road survives, but the story now has a missing voice where trust used to stand."),

        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 3, s49, 0),
        (try_begin),
          (is_between, ":bread_center", centers_begin, centers_end),
          (str_store_party_name_link, s48, ":bread_center"),
          (str_store_string, s49, "@The witness from {s48} did not survive the witness war intact. The bread story can now be retold by your enemies."),
          (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 4, s49, 0),
          (call_script, "script_change_player_relation_with_center", ":bread_center", -3),
        (try_end),
        (call_script, "script_fail_quest", "qst_rtc_war_of_witnesses"),
        (call_script, "script_sod_quest_chain_branch_failure", "qst_rtc_war_of_witnesses", -1, 0),
      (try_end),

      (quest_set_slot, "qst_rtc_war_of_witnesses", slot_quest_rtc_flags, ":flags"),
      (try_begin),
        (eq, ":offer", sod_rtc_offer_bread_oath),
        (try_begin),
          (neq, ":war_choice", sod_rtc_witness_war_sacrifice),
          (val_or, ":flags", sod_rtc_flag_witness_commoner),
          (val_or, ":flags", sod_rtc_flag_commoner_trust_high),
          (str_store_string, s49, "@The bread oath survived the witness war. The Empire can still threaten granaries, but it failed to make hunger forget who answered first."),
        (else_try),
          (val_or, ":flags", sod_rtc_flag_commoner_trust_low),
          (str_store_string, s49, "@The bread oath was wounded in the witness war. Hunger remains useful to the claim, but now Marius can ask why a promise of bread required a missing voice."),
        (try_end),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 6, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_books_oath),
        (try_begin),
          (neq, ":war_choice", sod_rtc_witness_war_sacrifice),
          (val_or, ":flags", sod_rtc_flag_witness_fourth),
          (val_or, ":flags", sod_rtc_flag_merchant_trust_high),
          (str_store_string, s49, "@The books oath survived the witness war. Ledgers were copied, road debts remembered, and the Empire failed to make every account Imperial property."),
        (else_try),
          (val_or, ":flags", sod_rtc_flag_merchant_trust_low),
          (str_store_string, s49, "@The books oath was wounded in the witness war. Merchants still count the road, but some now count the cost of being seen beside it."),
        (try_end),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 6, s49, 0),
      (else_try),
        (eq, ":offer", sod_rtc_offer_witness_oath),
        (try_begin),
          (neq, ":war_choice", sod_rtc_witness_war_sacrifice),
          (val_or, ":flags", sod_rtc_flag_witness_noble),
          (str_store_string, s49, "@The witness oath survived the witness war. Testimony bent under fear, but did not break into Imperial ownership."),
        (else_try),
          (val_or, ":flags", sod_rtc_flag_noble_trust_low),
          (str_store_string, s49, "@The witness oath was wounded in the witness war. Maeron's old question returns with blood on it: who owns the right when witnesses disappear?"),
        (try_end),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 6, s49, 0),
      (try_end),
      (try_begin),
        (eq, ":envoy_handling", 2),
        (str_store_string, s49, "@Because you detained the envoy, Marius frames the witness war as proof that your claim needs hostages more than law. Some hard captains respect the leverage; softer witnesses hear a warning."),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 5, s49, 0),
      (else_try),
        (eq, ":envoy_handling", 3),
        (str_store_string, s49, "@Because you sent a counter-demand, the witness war begins with competing terms already on the road. Imperial certainty has to fight through rumor before it reaches steel."),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 5, s49, 0),
      (else_try),
        (eq, ":envoy_handling", 1),
        (str_store_string, s49, "@Because you released the envoy cleanly, your answer reaches Marius without a convenient excuse. The war that follows looks more like Imperial choice than frontier confusion."),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 5, s49, 0),
      (else_try),
        (str_store_string, s49, "@Because the envoy left with muddled terms, the witness war begins in fog. Rumor moves first, and every faction chooses the version that serves it."),
        (add_quest_note_from_sreg, "qst_rtc_war_of_witnesses", 5, s49, 0),
      (try_end),
      (quest_get_slot, ":final_route", "qst_rtc_war_of_witnesses", slot_quest_rtc_branch_seed),
      (quest_get_slot, ":pressure", "qst_rtc_war_of_witnesses", slot_quest_rtc_imperial_pressure),
      (quest_get_slot, ":companion_pressure", "qst_rtc_war_of_witnesses", slot_quest_rtc_companion_pressure),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_rtc_branch_seed, ":final_route"),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_rtc_imperial_pressure, ":pressure"),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_rtc_companion_pressure, ":companion_pressure"),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_sod_chain_choice, ":envoy_handling"),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_object_troop, ":offer"),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_target_center, ":bread_center"),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_target_amount, ":grain_pressure"),
      (quest_set_slot, "qst_rtc_last_road", slot_quest_rtc_flags, ":flags"),
      (call_script, "script_sod_rtc_last_road_prepare_strategy_target", 0),
      (call_script, "script_sod_rtc_war_of_witnesses_cleanup_target"),
  ]),
]
