DIALOGS = [
[anyone, "start", [(eq, "$talk_context", tc_party_encounter),
                    (neg|encountered_party_is_attacker),
				
	(try_begin),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_sane),
		(str_store_string, s0, "@So we meet again, {playername}. Is it that time already?"),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_respectful),
		(str_store_string, s0, "@Your path has crossed mine once again. Is our grand struggle about to take place?"),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_imperialist),
		(str_store_string, s0, "@Yet again, the burden of your presence is mine to bear. Why have you sought me out?"),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_capitalist),
		(str_store_string, s0, "@Ach, not you again, peon! I am starting to grow sick of your persistence."),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_racist),
		(str_store_string, s0, "@You again. Why do you insist on crossing my path? I have no patience left for dull company."),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_crusader),
		(str_store_string, s0, "@Ah, finally you dare to approach me again. Did courage find you at last?"),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_liberator),
		(str_store_string, s0, "@Destiny has drawn our paths together one more time. Is this the hour of our reckoning?"),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_nihilistic),
		(str_store_string, s0, "@It seems the road still insists on meaning. Speak, then."),
	(else_try),
		is_legate,
		(str_store_string, s0, "@Our paths cross yet again. What do you intend to do?"),
	(else_try),
		(str_store_string, s0, "@You have my attention. Make the reason plain."),
	(try_end),
					
                    ],
   "{s0}", "party_encounter_hostile_defender",
   []],
]
