DIALOGS = [
[anyone, "start", [
		(this_or_next|is_between, "$g_talk_troop", "trp_knight_6_01", "trp_black_army_leader_1"),
		(eq, "$g_talk_troop", "trp_kingdom_6_lord"),
		(call_script, "script_store_troop_name", s29, "$g_talk_troop"),
		(try_begin),
			(eq, "$g_sod_country", cb_antares),
			(str_store_string, s31, "@Antarian Empire"),
			(str_store_string, s32, "@Antarians"),
		(else_try),
			(eq, "$g_sod_country", cb_aden),
			(str_store_string, s31, "@Kingdom of Aden"),
			(str_store_string, s32, "@Adenians"),
		(else_try),
			(eq, "$g_sod_country", cb_villian),
			(str_store_string, s31, "@Villianese Duchy"),
			(str_store_string, s32, "@Villianese"),
		(else_try),
			(eq, "$g_sod_country", cb_marina),
			(str_store_string, s31, "@Republic of Marina"),
			(str_store_string, s32, "@Marinans"),
		(else_try),
			(eq, "$g_sod_country", cb_zerrikan),
			(str_store_string, s31, "@Zerrikanian Sultanate"),
			(str_store_string, s32, "@Zerrikanians"),
		(try_end),
		(try_begin),
			(eq, "$g_sod_faith", cb_the_one),
			(str_store_string, s33, "@The One"),
		(else_try),
			(eq, "$g_sod_faith", cb_the_void),
			(str_store_string, s33, "@The Void"),
		(else_try),
			(eq, "$g_sod_faith", cb_old_gods),
			(str_store_string, s33, "@The Old Gods"),
		(else_try),
			(eq, "$g_sod_faith", cb_enlightenment),
			(str_store_string, s33, "@Spiritual Enlightment"),
		(else_try),
			(eq, "$g_sod_faith", cb_atheism),
			(str_store_string, s33, "@Natural Philosophy"),
		(try_end),
		(assign, "$centurion_first_meeting", 0),
		(eq, 1, 0),
	], "none", "centurion_personality", [] ],
]
