DIALOGS = [
[anyone, "start", [
		(check_quest_active, "qst_serpent_host_free_spy"),
		(quest_slot_eq, "qst_serpent_host_free_spy", slot_quest_current_state, 1),
        (main_party_has_troop, "trp_sh_spy"),
		(quest_slot_eq, "qst_serpent_host_free_spy", slot_quest_giver_troop, "$g_talk_troop"),
                          ],
   "Great work {playername}! I am in your debt for bringing back my spy.", "close_window",
   [(quest_get_slot, ":quest_gold_reward", "qst_serpent_host_free_spy", slot_quest_gold_reward),
    (call_script, "script_troop_add_gold", "trp_player", ":quest_gold_reward"),
    (assign, reg8, ":quest_gold_reward"),
    (assign, ":xp_reward", ":quest_gold_reward"),
    (val_mul, ":xp_reward", 2),
    (val_add, ":xp_reward", 100),
    (add_xp_as_reward, ":xp_reward"),
	(remove_member_from_party, "trp_sh_spy", "p_main_party"),
    (call_script, "script_change_troop_renown", "trp_player", 3),
    (call_script, "script_change_player_relation_with_faction", "$g_talk_troop_faction", 5),
    (call_script, "script_succeed_quest", "qst_serpent_host_free_spy"),
    (call_script, "script_end_quest", "qst_serpent_host_free_spy"),
  (finish_mission),
    ]],
]
