DIALOGS = [
[party_tpl|pt_messenger_party, "start", [
    (party_slot_eq, "$g_encountered_party", slot_party_sod_messenger_role, sod_messenger_role_public_health_relief),
    (party_get_slot, ":origin_center", "$g_encountered_party", slot_party_sod_public_health_origin),
    (party_get_slot, ":destination", "$g_encountered_party", slot_party_sod_public_health_destination),
    (try_begin),
      (is_between, ":origin_center", centers_begin, centers_end),
      (str_store_party_name, s1, ":origin_center"),
      (call_script, "script_sod_center_public_health_relief_institution_to_s0", ":origin_center"),
      (str_store_string_reg, s3, s0),
    (else_try),
      (str_store_string, s1, "@a house of care"),
      (str_store_string, s3, "@the care houses of"),
    (try_end),
    (try_begin),
      (is_between, ":destination", centers_begin, centers_end),
      (str_store_party_name, s2, ":destination"),
    (else_try),
      (str_store_string, s2, "@a sick settlement"),
    (try_end),
], "We carry healers, clean cloth, bitter draughts, and prayers from {s3} {s1} to {s2}. Our escort keeps steel sheathed unless someone bars the sick from mercy.", "public_health_relief_talk", []],

[anyone|plyr, "public_health_relief_talk", [], "Ride on. The sick need you more than I do.", "close_window", [
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_help_village, 1),
    (assign, "$g_leave_encounter", 1),
]],

[anyone|plyr, "public_health_relief_talk", [], "Take these supplies and hurry. (300 denars)", "close_window", [
    (store_troop_gold, ":gold", "trp_player"),
    (try_begin),
      (ge, ":gold", 300),
      (call_script, "script_sod_player_charge_gold", 300),
      (party_get_slot, ":payload", "$g_encountered_party", slot_party_sod_public_health_health_payload),
      (val_add, ":payload", 1),
      (party_set_slot, "$g_encountered_party", slot_party_sod_public_health_health_payload, ":payload"),
      (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_build_healing, 1),
      (display_message, "@The relief party adds your supplies to its litters and presses on.", 0x66CC66),
    (else_try),
      (display_message, "@You do not have enough coin to supply the relief party.", 0xCC3333),
    (try_end),
    (assign, "$g_leave_encounter", 1),
]],

[anyone|plyr, "public_health_relief_talk", [
    (party_get_slot, ":origin_faith", "$g_encountered_party", slot_party_sod_public_health_origin_faith),
    (is_between, ":origin_faith", sod_faiths_begin, sod_faiths_end),
    (eq, ":origin_faith", "$g_sod_faith"),
    (store_troop_gold, ":gold", "trp_player"),
    (ge, ":gold", 700),
    (store_current_day, ":cur_day"),
    (store_sub, ":days_since_blessing", ":cur_day", "$g_sod_public_health_last_clergy_blessing_day"),
    (this_or_next|ge, ":days_since_blessing", 7),
    (lt, "$g_sod_public_health_last_clergy_blessing_day", 1),
], "Offer alms and ask for a blessing. (700 denars)", "public_health_relief_blessing", [
    (call_script, "script_sod_player_charge_gold", 700),
    (store_current_day, "$g_sod_public_health_last_clergy_blessing_day"),
    (call_script, "script_sod_center_public_health_apply_player_clergy_blessing", 2),
]],

[anyone, "public_health_relief_blessing", [], "Then walk lighter, and let mercy find roads faster than fear.", "close_window", [
    (assign, "$g_leave_encounter", 1),
]],

[anyone|plyr, "public_health_relief_talk", [
    (party_get_slot, ":origin_faith", "$g_encountered_party", slot_party_sod_public_health_origin_faith),
    (is_between, ":origin_faith", sod_faiths_begin, sod_faiths_end),
    (neq, ":origin_faith", "$g_sod_faith"),
], "This road will not carry a rival faith's mercy. Defend yourselves.", "close_window", [
    (call_script, "script_change_badboy_rating", 6),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_abuse_village, 2),
    (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_dirty_profit, 1),
    (display_message, "@Word spreads that you attacked a clergy relief party on the road.", 0xCC3333),
    (assign, "$g_enemy_party", "$g_encountered_party"),
    (call_script, "script_let_nearby_parties_join_current_battle", 0, 0),
    (encounter_attack),
]],

[party_tpl|pt_messenger_party, "start", [
    (party_slot_eq, "$g_encountered_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
    (party_slot_eq, "$g_encountered_party", slot_party_sod_tax_courier_recipient_troop, "trp_player"),
    (party_get_slot, ":origin_center", "$g_encountered_party", slot_party_sod_tax_courier_origin_center),
    (try_begin),
      (is_between, ":origin_center", centers_begin, centers_end),
      (str_store_party_name, s1, ":origin_center"),
    (else_try),
      (str_store_string, s1, "@one of your estates"),
    (try_end),
], "Your banner is a relief, not a problem. We carry sealed tax from {s1}, and every hoofbeat has sounded like a question until now.", "tax_courier_player_talk", []],

[party_tpl|pt_messenger_party, "start", [
    (party_slot_eq, "$g_encountered_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
    (store_faction_of_party, ":courier_faction", "$g_encountered_party"),
    (store_relation, ":relation", ":courier_faction", "fac_player_supporters_faction"),
    (lt, ":relation", 0),
    (party_get_slot, ":origin_center", "$g_encountered_party", slot_party_sod_tax_courier_origin_center),
    (try_begin),
      (is_between, ":origin_center", centers_begin, centers_end),
      (str_store_party_name, s1, ":origin_center"),
    (else_try),
      (str_store_string, s1, "@our lord's estate"),
    (try_end),
], "If you want the chest from {s1}, you will have to make your claim louder than our lord's seal. We do not slow for enemies.", "tax_courier_hostile_talk", []],

[party_tpl|pt_messenger_party, "start", [
    (party_slot_eq, "$g_encountered_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
    (store_faction_of_party, ":courier_faction", "$g_encountered_party"),
    (is_between, ":courier_faction", kingdoms_begin, kingdoms_end),
    (neq, ":courier_faction", "fac_player_supporters_faction"),
    (store_relation, ":relation", ":courier_faction", "fac_player_supporters_faction"),
    (ge, ":relation", 0),
    (ge, "$g_sod_tax_courier_nonhostile_coercions", 2),
    (party_get_slot, ":origin_center", "$g_encountered_party", slot_party_sod_tax_courier_origin_center),
    (try_begin),
      (is_between, ":origin_center", centers_begin, centers_end),
      (str_store_party_name, s1, ":origin_center"),
    (else_try),
      (str_store_string, s1, "@our lord's estate"),
    (try_end),
], "I know who you are. Couriers trade stories when lords forget we have mouths. The chest from {s1} is sealed, and my hands are already shaking. Say what you mean to do.", "tax_courier_nonhostile_talk", []],

[party_tpl|pt_messenger_party, "start", [
    (party_slot_eq, "$g_encountered_party", slot_party_sod_messenger_role, sod_messenger_role_tax_courier),
    (store_faction_of_party, ":courier_faction", "$g_encountered_party"),
    (is_between, ":courier_faction", kingdoms_begin, kingdoms_end),
    (neq, ":courier_faction", "fac_player_supporters_faction"),
    (store_relation, ":relation", ":courier_faction", "fac_player_supporters_faction"),
    (ge, ":relation", 0),
    (party_get_slot, ":origin_center", "$g_encountered_party", slot_party_sod_tax_courier_origin_center),
    (try_begin),
      (is_between, ":origin_center", centers_begin, centers_end),
      (str_store_party_name, s1, ":origin_center"),
    (else_try),
      (str_store_string, s1, "@our lord's estate"),
    (try_end),
], "We have a sealed chest, two tired horses, and no appetite for clever men on roads. The tax from {s1} must pass.", "tax_courier_nonhostile_talk", []],

[anyone|plyr, "tax_courier_hostile_talk", [], "Hand over the tax chest and ride away alive.", "tax_courier_surrender_demand", [
    (store_skill_level, ":persuasion", "skl_persuasion", "trp_player"),
    (store_skill_level, ":leadership", "skl_leadership", "trp_player"),
    (party_get_num_companions, ":player_size", "p_main_party"),
    (party_get_num_companions, ":courier_size", "$g_encountered_party"),
    (val_max, ":courier_size", 1),
    (assign, ":chance", 35),
    (store_mul, ":persuasion_bonus", ":persuasion", 8),
    (val_add, ":chance", ":persuasion_bonus"),
    (store_mul, ":leadership_bonus", ":leadership", 3),
    (val_add, ":chance", ":leadership_bonus"),
    (store_mul, ":courier_double", ":courier_size", 2),
    (try_begin),
      (ge, ":player_size", ":courier_double"),
      (val_add, ":chance", 25),
    (try_end),
    (val_clamp, ":chance", 5, 96),
    (store_random_in_range, ":roll", 0, 100),
    (try_begin),
      (lt, ":roll", ":chance"),
      (assign, "$g_sod_tax_courier_surrender_success", 1),
    (else_try),
      (assign, "$g_sod_tax_courier_surrender_success", 0),
    (try_end),
]],

[anyone|plyr, "tax_courier_nonhostile_talk", [], "Hand over the tax chest and ride away alive.", "tax_courier_surrender_demand", [
    (call_script, "script_sod_tax_courier_apply_nonhostile_coercion_consequence", "$g_encountered_party"),
    (store_skill_level, ":persuasion", "skl_persuasion", "trp_player"),
    (store_skill_level, ":leadership", "skl_leadership", "trp_player"),
    (party_get_num_companions, ":player_size", "p_main_party"),
    (party_get_num_companions, ":courier_size", "$g_encountered_party"),
    (val_max, ":courier_size", 1),
    (assign, ":chance", 35),
    (try_begin),
      (ge, "$g_sod_tax_courier_nonhostile_coercions", 2),
      (val_add, ":chance", 12),
    (try_end),
    (store_mul, ":persuasion_bonus", ":persuasion", 8),
    (val_add, ":chance", ":persuasion_bonus"),
    (store_mul, ":leadership_bonus", ":leadership", 3),
    (val_add, ":chance", ":leadership_bonus"),
    (store_mul, ":courier_double", ":courier_size", 2),
    (try_begin),
      (ge, ":player_size", ":courier_double"),
      (val_add, ":chance", 25),
    (try_end),
    (val_clamp, ":chance", 5, 96),
    (store_random_in_range, ":roll", 0, 100),
    (try_begin),
      (lt, ":roll", ":chance"),
      (assign, "$g_sod_tax_courier_surrender_success", 1),
    (else_try),
      (assign, "$g_sod_tax_courier_surrender_success", 0),
    (try_end),
]],

[anyone, "tax_courier_surrender_demand", [
    (eq, "$g_sod_tax_courier_surrender_success", 1),
], "Take it, then. A seal can shame a man, but it cannot stop steel. Remember this: coin travels farther than couriers. So do stories.", "close_window", [
    (call_script, "script_sod_tax_courier_surrender_to_player", "$g_encountered_party"),
]],

[anyone, "tax_courier_surrender_demand", [], "No. If I return empty by choice, I am dead anyway. Better to earn it honestly. The chest reaches its lord or we die around it.", "close_window", [
    (assign, "$g_enemy_party", "$g_encountered_party"),
    (call_script, "script_let_nearby_parties_join_current_battle", 0, 0),
    (encounter_attack),
]],

[anyone|plyr, "tax_courier_hostile_talk", [], "Then defend it.", "close_window", [
    (assign, "$g_enemy_party", "$g_encountered_party"),
    (call_script, "script_let_nearby_parties_join_current_battle", 0, 0),
    (encounter_attack),
]],

[anyone|plyr, "tax_courier_hostile_talk", [], "Ride on. This road has enough blood on it.", "close_window", [
    (assign, "$g_leave_encounter", 1),
]],

[anyone|plyr, "tax_courier_nonhostile_talk", [], "Ride on. Safe roads serve us all.", "close_window", [
    (call_script, "script_sod_tax_courier_record_social_event", "$g_encountered_party", 3, 0),
    (assign, "$g_leave_encounter", 1),
]],

[anyone|plyr, "tax_courier_player_talk", [], "Ride on. Keep the chest close.", "close_window", [
    (call_script, "script_sod_tax_courier_record_social_event", "$g_encountered_party", 3, 0),
    (assign, "$g_leave_encounter", 1),
]],
]
