DIALOGS = [
[party_tpl|pt_village_farmers, "start", [(eq, "$talk_context", tc_party_encounter),
                                          (agent_play_sound, "$g_talk_agent", "snd_encounter_farmers"),
   (party_get_slot, ":target_center", "$g_encountered_party", slot_party_ai_object),
    (party_get_slot, ":home_center", "$g_encountered_party", slot_party_home_center),
    (try_begin),
      (is_between, ":home_center", villages_begin, villages_end),
      (party_get_slot, ":market_town", ":home_center", slot_village_market_town),
      (str_store_party_name, s11, ":home_center"),
    (else_try),
      (assign, ":market_town", -1),
      (str_store_string, s11, "@a village whose road has gone wrong"),
    (try_end),
    (try_begin),
      (is_between, ":market_town", towns_begin, towns_end),
      (str_store_party_name, s12, ":market_town"),
    (else_try),
      (str_store_string, s12, "@the nearest market"),
    (try_end),
    (assign, reg1, 1),
    (try_begin),
      (is_between, ":target_center", villages_begin, villages_end),
      (assign, reg1, 0),
    (try_end),
    (try_begin),
      (eq, reg1, 1),
      (str_store_string, s68, "@ My {lord/lady}, we're only poor farmers from the village of {s11}. We are taking our products to the market at {s12}."),
    (else_try),
      (str_store_string, s68, "@ My {lord/lady}, we're only poor farmers from the village of {s11}. We are returning from the market at {s12} back to our village."),
    (try_end),
  ],
   "{s68}", "village_farmer_talk",
   []],
]
