DIALOGS = [
[party_tpl|pt_slavers_caravan, "start", [(quest_get_slot, ":quest_target_party", "qst_slavers_escort_merchant_caravan", slot_quest_target_party),
                                           (gt, ":quest_target_party", 0),
                                           (eq, "$g_encountered_party", ":quest_target_party"),
                                           (party_is_active, ":quest_target_party"),
                                           (quest_get_slot, ":quest_target_center", "qst_slavers_escort_merchant_caravan", slot_quest_target_center),
                                           (party_is_active, ":quest_target_center"),
                                           (quest_slot_eq, "qst_slavers_escort_merchant_caravan", slot_quest_current_state, 1),
                                           (store_distance_to_party_from_party, ":dist", ":quest_target_center", "$g_encountered_party"),
                                           (lt, ":dist", 4),
                                           (quest_get_slot, reg14, "qst_slavers_escort_merchant_caravan", slot_quest_gold_reward),
                                           (str_store_party_name, s21, ":quest_target_center"),
                                           ],
   "We are close enough to {s21}. The chains and wagons can make the last stretch without you.\
 Here is your pay: {reg14} denars.\
 Spend it before the road takes it back.", "close_window", [(quest_get_slot, ":quest_target_party", "qst_slavers_escort_merchant_caravan", slot_quest_target_party),
                                                       (quest_get_slot, ":quest_giver_troop", "qst_slavers_escort_merchant_caravan", slot_quest_giver_troop),
                                                       (quest_get_slot, ":quest_gold_reward", "qst_slavers_escort_merchant_caravan", slot_quest_gold_reward),
                                                       (try_begin),
                                                         (is_between, ":quest_giver_troop", 0, "trp_last_troop"),
                                                         (call_script, "script_change_player_relation_with_troop", ":quest_giver_troop", 3),
                                                       (try_end),
                                                       (call_script, "script_end_quest", "qst_slavers_escort_merchant_caravan"),
                                                       (quest_set_slot, "qst_slavers_escort_merchant_caravan", slot_quest_current_state, 2),
                                                       (call_script, "script_troop_add_gold", "trp_player", ":quest_gold_reward"),
                                                       (assign, ":xp_reward", ":quest_gold_reward"),
                                                       (val_mul, ":xp_reward", 5),
                                                       (val_add, ":xp_reward", 100),
                                                       (add_xp_as_reward, ":xp_reward"),
                                                       (call_script, "script_change_troop_renown", "trp_player", 2),
                                                       (call_script, "script_sod_slavers_apply_player_action", sod_slaver_action_escort_caravan, 3),
                                                       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_buy_slaves, 2),
                                                       (call_script, "script_sod_companion_dispatch_player_action", sod_companion_action_dirty_profit, 2),
                                                       (assign, reg14, ":quest_gold_reward"),
                                                       (assign, "$g_leave_encounter", 1),
                                                       (try_begin),
                                                         (gt, ":quest_target_party", 0),
                                                         (neq, ":quest_target_party", "p_main_party"),
                                                         (party_is_active, ":quest_target_party"),
                                                         (party_get_template_id, ":target_template", ":quest_target_party"),
                                                         (eq, ":target_template", "pt_slavers_caravan"),
													     (remove_party, ":quest_target_party"), 
                                                       (try_end),
                                                       ]],
]
