DIALOGS = [
[trp_slave_hero, "start", [
  (eq, "$prison_break", 0),
  #(store_random_in_range, ":start", 0, 5),
  #(eq, ":start", 0),
  (assign, ":num_tries", 50),
  (try_for_range, ":unused", 0, ":num_tries"),
	(store_random_in_range, ":lord", "trp_knight_5_1", "trp_reserved_knight_1"),
	(troop_slot_eq, ":lord", slot_troop_occupation, slto_kingdom_hero),
	(assign, ":num_tries", 0),
  (try_end),
  (eq, ":num_tries", 0),
  (quest_set_slot, "qst_slave_q1", slot_quest_target_troop, ":lord"),
  (assign, "$prison_break_random_lord", ":lord"),
  (call_script, "script_store_troop_name_link", s13, ":lord"),
  (setup_quest_text, "qst_slave_q1"),
  (str_store_string, s2, "@Take Diego's message to his old friend {s13}."),
  (assign, "$prison_break", -1),
  ], "Finally, someone who isn't Slaver scum. Psst, come here. Yes, you. Now listen to me carefully...", "prison_break_1", []],
]