SCRIPTS = [
("assign_lords_to_empty_centers",
      [(try_for_range, ":cur_center", centers_begin, centers_end),
          (party_get_slot, ":center_lord", ":cur_center", slot_town_lord),
          (this_or_next|eq, ":center_lord", stl_unassigned),
          (eq, ":center_lord", stl_rejected_by_player),

          (store_faction_of_party, ":center_faction", ":cur_center"),
          (is_between, ":center_faction", kingdoms_begin, kingdoms_end),
          (neg|faction_slot_eq, ":center_faction", slot_faction_leader, "trp_player"),

          (assign, ":best_lord", -1),
          (assign, ":best_lord_score", -1),
          (try_begin),
            (eq, ":center_lord", stl_unassigned),
            (try_begin),
              (eq, "$players_kingdom", ":center_faction"),
              (eq, "$player_has_homage", 1),
              (assign, ":best_lord", stl_reserved_for_player),
              (call_script, "script_calculate_troop_score_for_center", "trp_player", ":cur_center"),
              (assign, ":best_lord_score", reg0),
            (try_end),
          (try_end),

          (try_for_range, ":cur_troop", kingdom_heroes_begin, kingdom_heroes_end),
            (troop_slot_eq, ":cur_troop", slot_troop_occupation, slto_kingdom_hero),
            (store_troop_faction, ":troop_faction", ":cur_troop"),
            (eq, ":troop_faction", ":center_faction"),

            (call_script, "script_calculate_troop_score_for_center", ":cur_troop", ":cur_center"),
            (assign, ":score", reg0),

            (gt, ":score", ":best_lord_score"),
            (assign, ":best_lord_score", ":score"),
            (assign, ":best_lord", ":cur_troop"),
          (try_end),
          (try_begin),
            (ge, ":best_lord", 0),
            (call_script, "script_give_center_to_lord", ":cur_center", ":best_lord", 1),
          (else_try),
            (eq, ":best_lord", stl_reserved_for_player),
            (party_set_slot, ":cur_center", slot_town_lord, stl_reserved_for_player),
            (try_begin),
              (party_slot_eq, ":cur_center", slot_party_type, spt_castle),
              (try_for_range, ":cur_village", villages_begin, villages_end),
                (party_slot_eq, ":cur_village", slot_village_bound_center, ":cur_center"),
                (party_set_slot, ":cur_village", slot_town_lord, stl_reserved_for_player),
              (try_end),
            (try_end),
          (try_end),
        (try_end),
    ]),
]
