SCRIPTS = [
("get_best_fief_name_of_troop", [
	(store_script_param_1, ":string"),
	(store_script_param_2, ":troop_no"),
	
	(assign, ":continue", 0),

	(try_for_range, ":village_no", villages_begin, villages_end),
        (party_slot_eq, ":village_no", slot_town_lord, ":troop_no"),
        (str_store_party_name, s17, ":village_no"),
		(assign, ":continue", 1),
    (try_end),            
	(try_for_range, ":castle_no", castles_begin, castles_end),
	#	(val_add, ":castle", 1),
        (party_slot_eq, ":castle_no", slot_town_lord, ":troop_no"),
		(str_store_party_name, s17, ":castle_no"),
	#	(store_add, reg0, "str_castlename_0", ":castle"),
	#	(str_store_string, s17, reg0),
		(assign, ":continue", 1),
    (try_end), 
   (try_for_range, ":town_no", towns_begin, towns_end),  # should take a town name in priority
        (party_slot_eq, ":town_no", slot_town_lord, ":troop_no"),
        (str_store_party_name, s17, ":town_no"),
		(assign, ":continue", 1),
    (try_end),
	(try_begin),
		(store_troop_faction, ":faction", ":troop_no"),
		(faction_slot_eq, ":faction", slot_faction_leader, ":troop_no"),
		(try_begin),
			(eq, ":faction", "fac_kingdom_1"),
			(str_store_string, s17, "@Swadia"),
		(else_try),
			(eq, ":faction", "fac_kingdom_2"),
			(str_store_string, s17, "@Vaegirs"),
		(else_try),
			(eq, ":faction", "fac_kingdom_3"),
			(str_store_string, s17, "@Khergits"),
		(else_try),
			(eq, ":faction", "fac_kingdom_4"),
			(str_store_string, s17, "@the Nords"),
		(else_try),
			(eq, ":faction", "fac_kingdom_5"),
			(str_store_string, s17, "@Rhodok Republic"),
		(else_try),
			(eq, ":faction", "fac_kingdom_6"),
			(str_store_string, s17, "@the Imperial Legion"),
		(try_end),
		(assign, ":continue", 1),
	(try_end),
	(try_begin),
		(eq, ":troop_no", "trp_player"),
		(eq, "$g_sod_king", 1),
		(try_begin),
			(eq, "$g_sod_country", cb_antares),
			(str_store_string, s17, "@Antares"),
		(else_try),
			(eq, "$g_sod_country", cb_marina),
			(str_store_string, s17, "@Marina"),
		(else_try),
			(eq, "$g_sod_country", cb_aden),
			(str_store_string, s17, "@Aden"),
		(else_try),
			(eq, "$g_sod_country", cb_villian),
			(str_store_string, s17, "@Villian"),
		(else_try),
			(eq, "$g_sod_country", cb_zerrikan),
			(str_store_string, s17, "@Zerrikania"),
		(try_end),
		(assign, ":continue", 1),
	(try_end),
	(try_begin),
		(eq, ":continue", 1),
		(str_store_string, ":string", "@ of {s17}"),
	(else_try),
		(str_clear, ":string"),
	(try_end),
	]),
]
