SCRIPTS = [
("get_center_relative_value",
    [ (store_script_param_1, ":center_no"),
      (assign, reg0, 0),
      (try_begin),
      (is_between, ":center_no", centers_begin, centers_end),
      (assign, ":player_center", 0), 
      (party_get_slot, ":population", ":center_no", slot_center_sod_local_population),
      (party_get_slot, ":health", ":center_no", slot_center_sod_local_health),
      (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
      (store_faction_of_party, ":faction_no", ":center_no"),
		  (try_begin),
		  (eq, ":faction_no", "fac_player_supporters_faction"),
		  (assign, ":player_center", 1),
		  (party_get_slot, ":faith", ":center_no", slot_center_sod_local_faith),
		  (val_max, ":faith", 0),  # to avoid to advantage player, under average faith shouldn't reduce relative value (used by ai to chose the richest targets)
		  (val_add, ":faith", 100),
		  (val_div, ":faith", 2),
		  (try_end),
      (try_begin), 
      (party_slot_eq, ":center_no", slot_party_type, spt_town),
      (assign, ":max_pop", town_pop_max),
      (else_try),
      (assign, ":max_pop", village_pop_max),
      (try_end),
      (val_add, ":health", 100),
      (val_div, ":health", 2),
      (val_mul, ":population", 100),
      (val_div, ":population", ":max_pop"),
      (val_mul, ":prosperity", 3),
      (val_mul, ":population", 2),
      (store_add, reg0, ":prosperity", ":population"),
      (val_add, reg0, ":health"),
      (try_begin),
        (party_slot_eq, ":center_no", slot_party_type, spt_town),
        (assign, ":base_relative_value", reg0),
        (call_script, "script_sod_get_town_market_profile", ":center_no"),
        (assign, ":town_market_score", reg0),
        (assign, ":town_liquidity", reg6),
        (assign, ":town_services", reg4),
        (assign, reg0, ":base_relative_value"),
        (store_div, ":town_market_value", ":town_market_score", 2),
        (val_add, reg0, ":town_market_value"),
        (store_div, ":town_liquidity_value", ":town_liquidity", 8),
        (val_add, reg0, ":town_liquidity_value"),
        (store_div, ":town_services_value", ":town_services", 2),
        (val_add, reg0, ":town_services_value"),
      (try_end),
      (try_begin),
        (party_slot_eq, ":center_no", slot_party_type, spt_castle),
        (call_script, "script_sod_get_castle_support_profile", ":center_no"),
        (assign, ":castle_support", reg0),
        (assign, ":castle_military_power", reg8),
        (assign, ":castle_honor_value", reg9),
        (store_mul, reg0, ":castle_support", 2),
        (val_add, reg0, ":castle_military_power"),
        (store_mul, ":castle_honor_score", ":castle_honor_value", 10),
        (val_add, reg0, ":castle_honor_score"),
      (try_end),
      (try_begin),
        (party_slot_eq, ":center_no", slot_party_type, spt_village),
        (party_slot_eq, ":center_no", slot_village_state, svs_being_raided),
        (val_sub, reg0, 20),
      (try_end),
      (try_begin),
        (party_slot_eq, ":center_no", slot_party_type, spt_village),
        (party_slot_eq, ":center_no", slot_village_state, svs_looted),
        (val_sub, reg0, 40),
      (try_end),
      (try_begin),
        (party_slot_eq, ":center_no", slot_party_type, spt_village),
        (party_slot_ge, ":center_no", slot_village_infested_by_bandits, 1),
        (val_sub, reg0, 15),
      (try_end),
      (try_begin),
        (this_or_next|party_slot_eq, ":center_no", slot_party_type, spt_town),
        (party_slot_eq, ":center_no", slot_party_type, spt_castle),
        (assign, ":bound_village_pressure", 0),
        (try_for_range, ":village_no", villages_begin, villages_end),
          (party_slot_eq, ":village_no", slot_village_bound_center, ":center_no"),
          (try_begin),
            (party_slot_eq, ":village_no", slot_village_state, svs_being_raided),
            (val_add, ":bound_village_pressure", 20),
          (else_try),
            (party_slot_eq, ":village_no", slot_village_state, svs_looted),
            (val_add, ":bound_village_pressure", 35),
          (try_end),
          (try_begin),
            (party_slot_ge, ":village_no", slot_village_infested_by_bandits, 1),
            (val_add, ":bound_village_pressure", 10),
          (try_end),
        (try_end),
        (val_sub, reg0, ":bound_village_pressure"),
      (try_end),
      (val_max, reg0, 0),
		  (try_begin),
		  (eq, ":player_center", 1),
		  (val_add, reg0, ":faith"),
		  (val_div, reg0, 7),
		  (else_try),
		  (val_div, reg0, 6),
		  (try_end),
      (try_end),
      ]),
]
