SCRIPTS = [
("get_center_threat_level",
   [
     (store_script_param_1, ":center_no"),
     (try_begin),
       (is_between, ":center_no", centers_begin, centers_end),
       (call_script, "script_sod_get_center_security_profile", ":center_no"),
     (else_try),
       (assign, reg0, 0),
       (assign, reg1, 0),
       (assign, reg2, 0),
       (assign, reg3, 0),
       (assign, reg4, 0),
       (assign, reg5, 0),
       (assign, reg6, 0),
       (assign, reg7, 0),
       (assign, reg8, 0),
       (assign, reg9, 0),
       (assign, reg10, 0),
       (assign, reg11, 0),
     (try_end),
     ]),
]
