SCRIPTS = [
("refresh_village_defenders",
    [
      (store_script_param_1, ":village_no"),

      (party_get_slot, ":population", ":village_no", slot_center_sod_local_population),
      (party_get_slot, ":health", ":village_no", slot_center_sod_local_health),
      (party_get_slot, ":prosperity", ":village_no", slot_town_prosperity),
      (store_sub, ":population_surplus", ":population", village_pop_min),
      (val_max, ":population_surplus", 0),
      (assign, ":ideal_size", 35),
      (store_div, ":population_defense_bonus", ":population_surplus", 20),
      (val_add, ":ideal_size", ":population_defense_bonus"),
      (try_begin),
        (lt, ":health", 30),
        (val_sub, ":ideal_size", 12),
      (else_try),
        (ge, ":health", 70),
        (val_add, ":ideal_size", 5),
      (try_end),
      (try_begin),
        (lt, ":prosperity", 30),
        (val_sub, ":ideal_size", 8),
      (else_try),
        (ge, ":prosperity", 70),
        (val_add, ":ideal_size", 5),
      (try_end),
      (val_clamp, ":ideal_size", 20, 70),
      (store_div, ":population_defense_cap", ":population_surplus", 4),
      (val_add, ":population_defense_cap", 15),
      (val_min, ":ideal_size", ":population_defense_cap"),
      (try_begin),
        (party_get_num_companions, ":size_before", ":village_no"),
        (lt, ":size_before", ":ideal_size"),
        (gt, ":population_surplus", 0),
        (party_add_template, ":village_no", "pt_village_defenders"),
        (party_get_num_companions, ":size_after", ":village_no"),
        (store_sub, ":added", ":size_after", ":size_before"),
        (val_min, ":added", ":population_surplus"),
        (val_sub, ":population", ":added"),
        (val_max, ":population", village_pop_min),
        (party_set_slot, ":village_no", slot_center_sod_local_population, ":population"),
      (try_end),
  ]),
]
