SCRIPTS = [
("update_center_recon_notes",
      [(store_script_param, ":center_no", 1),
        (str_clear, s49),
        (add_party_note_from_sreg, ":center_no", 1, s49, 0),
        (try_begin),
          (this_or_next|is_between, ":center_no", towns_begin, towns_end),
          (is_between, ":center_no", castles_begin, castles_end),
          (call_script, "script_sod_get_center_food_profile", ":center_no"),
          (assign, reg6, reg3),
          (assign, reg12, reg4),
          (assign, ":food_days", reg3),
          (assign, ":food_security", reg4),
          (call_script, "script_sod_get_center_security_profile", ":center_no"),
          (assign, ":effective_threat", reg0),
          (assign, ":security", reg1),
          (assign, ":raid_resistance", reg3),
          (assign, ":patrol_response", reg7),
          (assign, ":unrest_pressure", reg8),
          (call_script, "script_sod_get_center_security_economy_profile", ":center_no"),
          (assign, ":security_trade_pct", reg0),
          (assign, ":security_recovery_pct", reg1),
          (assign, ":security_bandit_pressure_pct", reg2),
          (assign, ":security_contract", reg6),
          (assign, reg7, ":security"),
          (assign, reg8, ":effective_threat"),
          (assign, reg9, ":raid_resistance"),
          (assign, reg10, ":patrol_response"),
          (assign, reg11, ":unrest_pressure"),
          (assign, reg35, ":security_trade_pct"),
          (assign, reg36, ":security_recovery_pct"),
          (assign, reg37, ":security_bandit_pressure_pct"),
          (assign, reg38, ":security_contract"),
          (call_script, "script_sod_get_center_faith_profile", ":center_no"),
          (assign, ":dominant_faith", reg0),
          (assign, ":dominant_support", reg1),
          (assign, ":player_faith_support", reg2),
          (assign, ":faith_tension", reg3),
          (assign, ":institution_strength", reg4),
          (assign, ":faith_unrest_pressure", reg7),
          (store_add, reg0, "str_sod_faith_suffix_0", ":dominant_faith"),
          (str_store_string, s12, reg0),
          (assign, reg39, ":dominant_support"),
          (assign, reg40, ":player_faith_support"),
          (assign, reg41, ":faith_tension"),
          (assign, reg42, ":institution_strength"),
          (assign, reg43, ":faith_unrest_pressure"),
          (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
          (assign, ":goods_food_balance", reg0),
          (assign, ":goods_raw_balance", reg1),
          (assign, ":goods_strategic_balance", reg2),
          (assign, ":goods_luxury_flow", reg3),
          (assign, ":goods_scarcity_pressure", reg4),
          (assign, ":goods_trade_willingness", reg5),
          (assign, ":goods_liquidity_pressure", reg6),
          (assign, ":goods_wealth_delta", reg7),
          (assign, reg44, ":goods_food_balance"),
          (assign, reg45, ":goods_raw_balance"),
          (assign, reg46, ":goods_strategic_balance"),
          (assign, reg47, ":goods_luxury_flow"),
          (assign, reg48, ":goods_scarcity_pressure"),
          (assign, reg49, ":goods_trade_willingness"),
          (assign, reg50, ":goods_liquidity_pressure"),
          (assign, reg51, ":goods_wealth_delta"),
          (party_collect_attachments_to_party, ":center_no", "p_collective_ally"),
          (party_get_num_companions, reg5, "p_collective_ally"),
          (assign, ":current_garrison", reg5),
          (try_begin),
            (is_between, ":center_no", towns_begin, towns_end),
            (call_script, "script_sod_get_town_market_profile", ":center_no"),
            (assign, ":town_market_score", reg0),
            (assign, ":town_rural_surplus", reg1),
            (assign, ":town_consumption_pressure", reg2),
            (assign, ":town_import_demand", reg3),
            (assign, ":town_services", reg4),
            (assign, ":town_recovery_rate", reg5),
            (assign, ":town_liquidity", reg6),
            (assign, ":town_trade_volume", reg7),
            (assign, ":town_tariff_capture", reg8),
            (assign, ":town_tax_reliability", reg9),
            (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
            (assign, ":tax_revenue_pct", reg0),
            (assign, ":tax_pressure", reg1),
            (assign, ":tax_retention_pct", reg3),
            (assign, ":tax_liquidity_pct", reg4),
            (assign, ":tax_recovery_pct", reg5),
            (assign, reg20, ":town_market_score"),
            (assign, reg21, ":town_rural_surplus"),
            (assign, reg22, ":town_consumption_pressure"),
            (assign, reg23, ":town_import_demand"),
            (assign, reg24, ":town_services"),
            (assign, reg25, ":town_recovery_rate"),
            (assign, reg26, ":town_liquidity"),
            (assign, reg27, ":town_trade_volume"),
            (assign, reg28, ":town_tariff_capture"),
            (assign, reg29, ":town_tax_reliability"),
            (assign, reg30, ":tax_revenue_pct"),
            (assign, reg31, ":tax_pressure"),
            (assign, reg32, ":tax_retention_pct"),
            (assign, reg33, ":tax_liquidity_pct"),
            (assign, reg34, ":tax_recovery_pct"),
            (assign, reg7, ":security"),
            (assign, reg8, ":effective_threat"),
            (assign, reg9, ":raid_resistance"),
            (assign, reg10, ":patrol_response"),
            (assign, reg11, ":unrest_pressure"),
            (assign, reg12, ":food_security"),
            (assign, reg5, ":current_garrison"),
            (assign, reg6, ":food_days"),
            (store_faction_of_party, ":center_faction", ":center_no"),
            (call_script, "script_sod_get_realm_tax_pressure_profile", ":center_faction"),
            (assign, reg52, reg0),
            (assign, reg53, reg1),
            (assign, reg54, reg2),
            (assign, reg55, reg3),
            (assign, reg56, reg4),
            (str_store_string, s49, "@Current garrison consists of {reg5} men.^Has food stock for {reg6} days. Food security {reg12}.^Town market engine {reg20}: rural surplus {reg21}, consumption pressure {reg22}, import demand {reg23}.^Goods market: food {reg44}, raw {reg45}, strategic {reg46}, luxury {reg47}; scarcity {reg48}, trade willingness {reg49}%, liquidity pressure {reg50}, weekly wealth drift {reg51}.^Craftsmen and services {reg24}, recovery rate {reg25}, liquidity {reg26}. Trade volume {reg27}%, tariff capture {reg28}%, tax reliability {reg29}%.^Tax extraction: revenue {reg30}%, pressure {reg31}, migration retention {reg32}%, liquidity {reg33}%, recovery {reg34}%.^Local tax burden: peasant extraction {reg52}, merchant tariffs {reg53}, noble obligations {reg54}, clergy support {reg55}, war taxes {reg56}.^Security infrastructure: trade protection {reg35}%, recovery {reg36}%, bandit pressure {reg37}%, contract security {reg38}.^Faith: dominant {s12} at {reg39}, player-faith support {reg40}, tension {reg41}, institutions {reg42}, faith unrest {reg43}.^Security {reg7}, effective threat {reg8}, raid resistance {reg9}%, patrol response {reg10}%, unrest pressure {reg11}."),

            (add_party_note_from_sreg, ":center_no", 1, s49, 1),
          (else_try),
            (is_between, ":center_no", castles_begin, castles_end),
            (call_script, "script_sod_get_castle_support_profile", ":center_no"),
            (assign, reg13, reg0),
            (assign, reg14, reg2),
            (assign, reg15, reg3),
            (assign, reg16, reg6),
            (assign, reg17, reg7),
            (assign, reg18, reg8),
            (assign, reg19, reg9),
            (assign, ":castle_support", reg13),
            (assign, ":bound_population", reg14),
            (assign, ":bound_villages", reg15),
            (assign, ":road_control", reg16),
            (assign, ":noble_access", reg17),
            (assign, ":military_power", reg18),
            (assign, ":honor_value", reg19),
            (assign, reg20, ":castle_support"),
            (assign, reg21, ":bound_population"),
            (assign, reg22, ":bound_villages"),
            (assign, reg23, ":road_control"),
            (assign, reg24, ":noble_access"),
            (assign, reg25, ":military_power"),
            (assign, reg26, ":honor_value"),
            (assign, reg27, reg10),
            (assign, reg28, reg11),
            (assign, reg29, reg12),
            (assign, reg30, reg13),
            (assign, reg31, reg14),
            (assign, reg32, reg15),
            (assign, reg33, reg16),
            (assign, reg7, ":security"),
            (assign, reg8, ":effective_threat"),
            (assign, reg9, ":raid_resistance"),
            (assign, reg10, ":patrol_response"),
            (assign, reg11, ":unrest_pressure"),
            (assign, reg12, ":food_security"),
            (assign, reg5, ":current_garrison"),
            (assign, reg6, ":food_days"),
            (store_faction_of_party, ":center_faction", ":center_no"),
            (call_script, "script_sod_get_realm_tax_pressure_profile", ":center_faction"),
            (assign, reg52, reg0),
            (assign, reg53, reg1),
            (assign, reg54, reg2),
            (assign, reg55, reg3),
            (assign, reg56, reg4),
            (str_store_string, s49, "@Current garrison consists of {reg5} men.^Has food stock for {reg6} days. Food security {reg12}.^Castle support {reg20}: {reg22} bound villages, {reg21} bound population, road control {reg23}, noble chapter {reg24}, military power {reg25}, grant honor {reg26}.^Goods market: food {reg44}, raw {reg45}, strategic {reg46}, luxury {reg47}; scarcity {reg48}, trade willingness {reg49}%, liquidity pressure {reg50}, weekly wealth drift {reg51}.^Commander {reg27}, siege readiness {reg28}, garrison recovery {reg29}, patrol strength {reg30}, recruitment quality {reg31}, scutage reliability {reg32}%, village protection {reg33}.^Local tax burden: peasant extraction {reg52}, merchant tariffs {reg53}, noble obligations {reg54}, clergy support {reg55}, war taxes {reg56}.^Security infrastructure: trade protection {reg35}%, recovery {reg36}%, bandit pressure {reg37}%, contract security {reg38}.^Faith: dominant {s12} at {reg39}, player-faith support {reg40}, tension {reg41}, institutions {reg42}, faith unrest {reg43}.^Security {reg7}, effective threat {reg8}, raid resistance {reg9}%, patrol response {reg10}%, unrest pressure {reg11}."),

            (add_party_note_from_sreg, ":center_no", 1, s49, 1),
          (else_try),
            (assign, reg5, ":current_garrison"),
            (assign, reg6, ":food_days"),
            (assign, reg12, ":food_security"),
            (str_store_string, s49, "@Current garrison consists of {reg5} men.^Has food stock for {reg6} days. Food security {reg12}.^Goods market: food {reg44}, raw {reg45}, strategic {reg46}, luxury {reg47}; scarcity {reg48}, trade willingness {reg49}%, liquidity pressure {reg50}, weekly wealth drift {reg51}.^Faith: dominant {s12} at {reg39}, player-faith support {reg40}, tension {reg41}, institutions {reg42}, faith unrest {reg43}.^Security {reg7}, effective threat {reg8}, raid resistance {reg9}%, patrol response {reg10}%, unrest pressure {reg11}."),

            (add_party_note_from_sreg, ":center_no", 1, s49, 1),
          (try_end),
        (else_try),
          (is_between, ":center_no", villages_begin, villages_end),
          (call_script, "script_sod_get_village_output_profile", ":center_no"),
          (assign, reg5, reg0),
          (assign, reg6, reg1),
          (assign, reg7, reg2),
          (assign, reg8, reg3),
          (assign, reg9, reg4),
          (assign, reg10, reg5),
          (assign, reg11, reg6),
          (assign, reg12, reg7),
          (assign, reg13, reg8),
          (assign, reg14, reg9),
          (call_script, "script_sod_get_center_tax_extraction_profile", ":center_no"),
          (assign, reg20, reg0),
          (assign, reg21, reg1),
          (assign, reg22, reg3),
          (assign, reg23, reg4),
          (assign, reg24, reg5),
          (call_script, "script_sod_get_center_security_economy_profile", ":center_no"),
          (assign, reg25, reg0),
          (assign, reg26, reg1),
          (assign, reg27, reg2),
          (assign, reg28, reg6),
          (call_script, "script_sod_get_center_security_profile", ":center_no"),
          (assign, reg15, reg0),
          (assign, reg16, reg3),
          (call_script, "script_sod_get_center_faith_profile", ":center_no"),
          (assign, ":dominant_faith", reg0),
          (store_add, reg0, "str_sod_faith_suffix_0", ":dominant_faith"),
          (str_store_string, s12, reg0),
          (assign, reg29, reg1),
          (assign, reg30, reg2),
          (assign, reg31, reg3),
          (assign, reg32, reg4),
          (assign, reg33, reg7),
          (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
          (assign, reg34, reg0),
          (assign, reg35, reg1),
          (assign, reg36, reg2),
          (assign, reg37, reg3),
          (assign, reg38, reg4),
          (assign, reg39, reg5),
          (assign, reg40, reg6),
          (assign, reg41, reg7),
          (party_get_num_companions, reg17, ":center_no"),
          (party_get_slot, reg18, ":center_no", slot_center_npc_volunteer_troop_amount),
          (val_max, reg18, 0),
          (party_get_slot, reg19, ":center_no", slot_center_volunteer_troop_amount),
          (val_max, reg19, 0),
          (store_faction_of_party, ":center_faction", ":center_no"),
          (call_script, "script_sod_get_realm_tax_pressure_profile", ":center_faction"),
          (assign, reg42, reg0),
          (assign, reg43, reg1),
          (assign, reg44, reg2),
          (assign, reg45, reg3),
          (assign, reg46, reg4),
          (str_store_string, s49, "@Village root economy: workforce {reg5}, food output {reg6}, cattle output {reg7}, raw materials {reg8}.^Goods market: food {reg34}, raw {reg35}, strategic {reg36}, luxury {reg37}; scarcity {reg38}, trade willingness {reg39}%, liquidity pressure {reg40}, weekly wealth drift {reg41}.^Recruit capacity {reg9}, labor capacity {reg10}, reliability {reg13}. Fragility {reg11}, coercion pressure {reg12}, cattle growth {reg14}.^Tax extraction: revenue {reg20}%, pressure {reg21}, migration retention {reg22}%, liquidity {reg23}%, recovery {reg24}%.^Local tax burden: peasant extraction {reg42}, merchant tariffs {reg43}, noble obligations {reg44}, clergy support {reg45}, war taxes {reg46}.^Security infrastructure: trade protection {reg25}%, recovery {reg26}%, bandit pressure {reg27}%, contract security {reg28}.^Faith: dominant {s12} at {reg29}, player-faith support {reg30}, tension {reg31}, institutions {reg32}, faith unrest {reg33}.^Village garrison {reg17}; NPC militia pool {reg18}; player recruit pool {reg19}.^Effective threat {reg15}, raid resistance {reg16}%."),

          (add_party_note_from_sreg, ":center_no", 1, s49, 1),
        (try_end),
    ]),
]
