MENUS = [
("character_report", mnf_enable_hot_keys,
   "{s9}",
   "none",
   [
    (set_background_mesh, "mesh_pic_report_screen"),
    (try_begin),
      (gt, "$g_player_reading_book", 0),
      (player_has_item, "$g_player_reading_book"),
      (call_script, "script_sod_books_describe_current_reading_to_s20"),
      (str_store_string, s9, "@{s20}"),
    (else_try),
      (assign, "$g_player_reading_book", 0),
      (str_store_string, s9, "@No book is open beside your bedroll."),
    (try_end),
    (assign, ":num_friends", 0),
    (assign, ":num_enemies", 0),
    (str_store_string, s6, "@none"),
    (str_store_string, s8, "@none"),
    (try_for_range, ":troop_no", kingdom_heroes_begin, kingdom_heroes_end),
      (call_script, "script_troop_get_player_relation", ":troop_no"),
      (assign, ":player_relation", reg0),
      #(troop_get_slot, ":player_relation", ":troop_no", slot_troop_player_relation),
      (try_begin),
        (gt, ":player_relation", 20),
        (try_begin),
          (eq, ":num_friends", 0),
          (call_script, "script_store_troop_name", s8, ":troop_no"),
        (else_try),
          (eq, ":num_friends", 1),
          (call_script, "script_store_troop_name", s7, ":troop_no"),
          (str_store_string, s8, "@{s7} and {s8}"),
        (else_try),
          (call_script, "script_store_troop_name", s7, ":troop_no"),
          (str_store_string, s8, "@{s7}, {s8}"),
        (try_end),
        (val_add, ":num_friends", 1),
      (else_try),
        (lt, ":player_relation", -20),
        (try_begin),
          (eq, ":num_enemies", 0),
          (call_script, "script_store_troop_name", s6, ":troop_no"),
        (else_try),
          (eq, ":num_enemies", 1),
          (call_script, "script_store_troop_name", s5, ":troop_no"),
          (str_store_string, s6, "@{s5} and {s6}"),
        (else_try),
          (call_script, "script_store_troop_name", s5, ":troop_no"),
          (str_store_string, s6, "@{s5}, {s6}"),
        (try_end),
        (val_add, ":num_enemies", 1),
      (try_end),
    (try_end),
    (assign, ":honor_score", "$player_honor"),
    (troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
    (try_begin),
      (lt, ":player_renown", 100),
      (str_store_string, s2, "@little known"),
    (else_try),
      (lt, ":player_renown", 300),
      (str_store_string, s2, "@locally known"),
    (else_try),
      (lt, ":player_renown", 700),
      (str_store_string, s2, "@well known"),
    (else_try),
      (lt, ":player_renown", 1200),
      (str_store_string, s2, "@famous across the realm"),
    (else_try),
      (str_store_string, s2, "@spoken of everywhere"),
    (try_end),
    (try_begin),
      (lt, ":honor_score", -20),
      (str_store_string, s3, "@feared and distrusted"),
    (else_try),
      (lt, ":honor_score", 0),
      (str_store_string, s3, "@questionable"),
    (else_try),
      (lt, ":honor_score", 15),
      (str_store_string, s3, "@ordinary"),
    (else_try),
      (lt, ":honor_score", 40),
      (str_store_string, s3, "@respectable"),
    (else_try),
      (str_store_string, s3, "@widely honored"),
    (try_end),
    (try_begin), # SoD Twan : display badboy rating and decay when PSF is active
      (faction_slot_eq, "fac_player_supporters_faction", slot_faction_state, sfs_active),           
      (faction_get_slot, ":badboy_rating", "fac_player_supporters_faction", slot_faction_badboy_rating),
      (call_script, "script_calculate_badboy_decay"),
      (try_begin),
        (lt, ":badboy_rating", 10),
        (str_store_string, s4, "@barely noticed"),
      (else_try),
        (lt, ":badboy_rating", 30),
        (str_store_string, s4, "@muttered about"),
      (else_try),
        (lt, ":badboy_rating", 60),
        (str_store_string, s4, "@watched with suspicion"),
      (else_try),
        (str_store_string, s4, "@treated as a serious menace"),
      (try_end),
    (str_store_string, s9, "@Fame: {s2}.^Reputation: {s3}.^Political notoriety: {s4}.^^Friends: {s8}.^Enemies: {s6}.^{s9}"),
    (else_try),
    (str_store_string, s9, "@Fame: {s2}.^Reputation: {s3}.^^Friends: {s8}.^Enemies: {s6}.^{s9}"),
    (try_end),          # Sod Twan End

    (call_script, "script_get_number_of_hero_centers", "trp_player"),
    (assign, ":no_centers", reg0),
    (try_begin),
      (gt, ":no_centers", 0),
      (try_for_range, ":i_center", 0, ":no_centers"),
        (call_script, "script_troop_get_leaded_center_with_index", "trp_player", ":i_center"),
        (assign, ":cur_center", reg0),
        (try_begin),
          (eq, ":i_center", 0),
          (str_store_party_name, s8, ":cur_center"),
        (else_try),
          (eq, ":i_center", 1),
          (str_store_party_name, s7, ":cur_center"),
          (str_store_string, s8, "@{s7} and {s8}"),
        (else_try),
          (str_store_party_name, s7, ":cur_center"),
          (str_store_string, s8, "@{s7}, {s8}"),
        (try_end),
      (try_end),
      (str_store_string, s9, "@Your estates are: {s8}.^{s9}"),
    (try_end),
    (try_begin),
      (gt, "$players_kingdom", 0),
      (str_store_faction_name, s8, "$players_kingdom"),
      #MORDACHAI - tell them they're King, if they are...
      (try_begin),
        (faction_slot_eq, "$players_kingdom", slot_faction_leader, "trp_player"),
        (str_store_string, s9, "@You are the {King/Queen} of the {s8}.^{s9}"),
      (else_try),
        (try_begin),
          (eq, "$player_has_homage", 0),
          (store_current_day, ":day"),
          (store_sub, ":contract_days_left", "$mercenary_service_next_renew_day", ":day"),
          (try_begin),
            (le, ":contract_days_left", 3),
            (str_store_string, s7, "@will expire very soon"),
          (else_try),
            (le, ":contract_days_left", 10),
            (str_store_string, s7, "@has little time remaining"),
          (else_try),
            (str_store_string, s7, "@is still secure for now"),
          (try_end),
          (str_store_string, s9, "@Your kingdom mercenary service {s7}.^{s9}"),
        (try_end),
        (assign, reg0, "$player_has_homage"),
        (str_store_string, s9, "@You are a {reg0?lord of:mercenary for} the {s8}.^{s9}"),
      (try_end),
    (try_end),
    (call_script, "script_merc_describe_report_summary"),
    (str_store_string, s9, "@{s60}^{s61}^{s62}^{s9}"),
  ],
  [
    ("continue", [], "Continue...",
     [(jump_to_menu, "mnu_reports"),
      ]
     ),
    ]
  ),
]
