MENUS = [
("game_options_3", mnf_enable_hot_keys,
    "{s98}",
    "none",
    [
      (set_background_mesh, "mesh_pic_report_screen"),

      (str_clear, s98),
      (str_store_string, s98, "@Other settings:"),

      (try_begin),
        (eq, "$g_sod_hide_messages", 0),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^^Messages: All"),
      (else_try),
        (eq, "$g_sod_hide_messages", -1),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^^Messages: Fewer"),
      (else_try),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^^Messages: Fewest"),
      (try_end),

	  # (try_begin),
	    # (eq, "$g_sod_anti_pursuit", 0),
	    # Anti Pursuit System display removed.
	  # (else_try),
		# Anti Pursuit System display removed.
	  # (try_end),

      (try_begin),
        (eq, "$g_sod_debug", 1),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^SoD debugging: ON"),
      (else_try),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^SoD debugging: OFF"),
      (try_end),

	  (try_begin),
        (eq, "$g_sod_horse_health_bar_on", 1),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^Horse health bar: ON"),
      (else_try),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^Horse health bar: OFF"),
      (try_end),

      (try_begin),
        (eq, "$g_sod_deactivate_ai", 0),
        (eq, "$g_sod_deactivate_lords_ai", 0),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^Strategic AI: Full, including lord decisions"),
      (else_try),
        (eq, "$g_sod_deactivate_ai", 0),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^Strategic AI: Faction decisions only"),
      (else_try),
        (str_store_string_reg, s97, s98),
        (str_store_string, s98, "@{s97}^Strategic AI: Native"),
       (try_end),

	   	(try_begin),  #twan454
		 (eq, "$g_sod_deactivate_ai", 0),
		 (faction_slot_eq, "fac_player_faction", slot_faction_center_transfer_option, 0),
		 (str_store_string_reg, s97, s98),
		 (str_store_string, s98, "@{s97}^Troop transfers: Lords move troops between centers; centers recruit some prisoners weekly."),
		 (else_try),
		 (eq, "$g_sod_deactivate_ai", 0),
		 (faction_slot_eq, "fac_player_faction", slot_faction_center_transfer_option, 1),
		 (str_store_string_reg, s97, s98),
		 (str_store_string, s98, "@{s97}^Troop transfers: AI lords move troops; their centers recruit prisoners."),
		 (else_try),
		 (eq, "$g_sod_deactivate_ai", 0),
		 (faction_slot_eq, "fac_player_faction", slot_faction_center_transfer_option, 2),
		 (str_store_string_reg, s97, s98),
		 (str_store_string, s98, "@{s97}^Troop transfers: Lords move troops; prisoner recruitment is disabled."),
		 (else_try),
		 (eq, "$g_sod_deactivate_ai", 0),
		 (faction_slot_eq, "fac_player_faction", slot_faction_center_transfer_option, 3),
		 (str_store_string_reg, s97, s98),
		 (str_store_string, s98, "@{s97}^Troop transfers: AI lords move troops; prisoner recruitment is disabled."),
		 (else_try),
		 (this_or_next|eq, "$g_sod_deactivate_ai", 1),
		 (faction_slot_eq, "fac_player_faction", slot_faction_center_transfer_option, 4),
		 (str_store_string_reg, s97, s98),
		 (str_store_string, s98, "@{s97}^Troop transfers: Disabled."),
         (try_end), #twan454
	  
	  (try_begin), #twan456
		 (eq, "$g_sod_badboy_cheat", 1),
		 (str_store_string_reg, s97, s98),
		 (str_store_string, s98, "@{s97}^Badboy gain: Disabled"),
	  (try_end),
	  (try_begin),
	    (eq, "$g_sod_parental_advisory", 1),
		(str_store_string_reg, s97, s98),
		(str_store_string, s98, "@{s97}^Adult events filter: ON"),
		(else_try),
		(str_store_string_reg, s97, s98),
		(str_store_string, s98, "@{s97}^Adult events filter: OFF"),
	  (try_end),

],
 [
      ("game_options_few", [(eq, "$g_sod_hide_messages", 0)], "Show fewer messages.", [(assign, "$g_sod_hide_messages", -1), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_none", [(eq, "$g_sod_hide_messages", -1)], "Show fewest messages.", [(assign, "$g_sod_hide_messages", -2), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_all", [(eq, "$g_sod_hide_messages", -2)], "Show all messages.", [(assign, "$g_sod_hide_messages", 0), (jump_to_menu, "mnu_game_options_3")]),
      # ("game_options_anti_pursuit_1", [(eq, "$g_sod_anti_pursuit", 1)], "Enable Anti Pursuit System", [(assign, "$g_sod_anti_pursuit", 0), (jump_to_menu, "mnu_game_options_3")]),
      # ("game_options_anti_pursuit_2", [(eq, "$g_sod_anti_pursuit", 0)], "Disable Anti Pursuit System", [(assign, "$g_sod_anti_pursuit", 1), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_enable_ai", [(eq, "$g_sod_deactivate_ai", 1)], "Use full Strategic AI", [(assign, "$g_sod_deactivate_ai", 0), (assign, "$g_sod_deactivate_lords_ai", 0),(jump_to_menu, "mnu_game_options_3")]),   # Sod Twan new options
      ("game_options_disable_lordsai", [(eq, "$g_sod_deactivate_ai", 0), (eq, "$g_sod_deactivate_lords_ai", 0)], "Limit Strategic AI to faction decisions", [(assign, "$g_sod_deactivate_lords_ai", 1), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_disable_ai", [(eq, "$g_sod_deactivate_ai", 0), (eq, "$g_sod_deactivate_lords_ai", 1)], "Use Native strategic AI", [(assign, "$g_sod_deactivate_ai", 1), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_enable_hhb", [(eq, "$g_sod_horse_health_bar_on", 0)], "Enable horse health bar", [(assign, "$g_sod_horse_health_bar_on", 1), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_disable_hhb", [(eq, "$g_sod_horse_health_bar_on", 1)], "Disable horse health bar", [(assign, "$g_sod_horse_health_bar_on", 0), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_enable_debug", [(eq, "$g_sod_debug", 0)], "Enable debugging menus & messages", [(assign, "$g_sod_debug", 1), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_disable_debug", [(eq, "$g_sod_debug", 1)], "Disable debugging menus & messages", [(assign, "$g_sod_debug", 0), (jump_to_menu, "mnu_game_options_3")]),
	  ("game_options_transfer_system", [(eq, "$g_sod_deactivate_ai", 0)], "Change troop transfer rules.",
        [
          (faction_get_slot, ":transfer_system", "fac_player_faction", slot_faction_center_transfer_option),
          (try_begin),
            (lt, ":transfer_system", 4),
            (val_add, ":transfer_system", 1),
			(else_try),
			(assign, ":transfer_system", 0),
          (try_end),
		  (faction_set_slot, "fac_player_faction", slot_faction_center_transfer_option, ":transfer_system"),
          (jump_to_menu, "mnu_game_options_3"),
        ]),	                   #twan454 end
	 ("deactivate_badboy", [(eq, "$g_sod_cheat_mode", 1), (eq, "$g_sod_debug", 1)], "Disable badboy gain",  [ (assign, "$g_sod_badboy_cheat", 1), (val_add, "$g_sod_cheat_mode_used", 1), #twan456
	 (jump_to_menu, "mnu_game_options_3")]),
    ("reactivate_badboy", [(eq, "$g_sod_badboy_cheat", 1)], "Enable badboy gain", [(assign, "$g_sod_badboy_cheat", 0), (jump_to_menu, "mnu_game_options_3")]), #twan456
	  ("advisory_1", [(eq, "$g_sod_parental_advisory", 0)], "Enable adult events filter", [(assign, "$g_sod_parental_advisory", 1), (jump_to_menu, "mnu_game_options_3")]),    #twan456
	  ("advisory_2", [(eq, "$g_sod_parental_advisory", 1)], "Disable adult events filter", [(assign, "$g_sod_parental_advisory", 0), (jump_to_menu, "mnu_game_options_3")]),
      ("game_options_return", [], "Back to Options...", [(jump_to_menu, "mnu_game_options")]),
]),
]
