MENUS = [
("morale_report", mnf_enable_hot_keys,
   "{s1}",
   "none",
  [
    (set_background_mesh, "mesh_pic_report_screen"),
    (call_script, "script_get_player_party_morale_values"),
    (assign, ":party_size_modifier", "$g_player_party_morale_modifier_party_size"),
    (assign, ":leadership_modifier", "$g_player_party_morale_modifier_leadership"),
    (assign, ":food_modifier", "$g_player_party_morale_modifier_food"),
    (party_get_morale, ":current_morale", "p_main_party"),
    (try_begin),
      (lt, ":current_morale", 25),
      (str_store_string, s2, "@dangerously low"),
    (else_try),
      (lt, ":current_morale", 45),
      (str_store_string, s2, "@poor"),
    (else_try),
      (lt, ":current_morale", 65),
      (str_store_string, s2, "@steady"),
    (else_try),
      (lt, ":current_morale", 85),
      (str_store_string, s2, "@good"),
    (else_try),
      (str_store_string, s2, "@excellent"),
    (try_end),
    (try_begin),
      (gt, ":party_size_modifier", 20),
      (str_store_string, s3, "@The company is large enough that crowding and divided attention are wearing on discipline."),
    (else_try),
      (str_store_string, s3, "@Party size is not the main morale problem."),
    (try_end),
    (try_begin),
      (gt, ":leadership_modifier", 20),
      (str_store_string, s4, "@Leadership is doing real work to hold the company together."),
    (else_try),
      (str_store_string, s4, "@Leadership helps, but cannot solve every complaint alone."),
    (try_end),
    (try_begin),
      (gt, "$g_player_party_morale_modifier_no_food", 0),
      (str_store_string, s5, "@Food is an immediate grievance."),
    (else_try),
      (gt, ":food_modifier", 15),
      (str_store_string, s5, "@Food variety is helping spirits."),
    (else_try),
      (str_store_string, s5, "@Food is adequate, though nobody is singing about it."),
    (try_end),
    (try_begin),
      (gt, "$g_player_party_morale_modifier_debt", 0),
      (str_store_string, s6, "@Wage debt is souring the ranks."),
    (else_try),
      (str_store_string, s6, "@Wages are not causing open complaint."),
    (try_end),
    (str_store_string, s1, "@Company Morale Report^^Current party morale is {s2}.^^{s3}^{s4}^{s5}^{s6}"),
    ],
    [
      ("continue", [], "Continue...",
       [(jump_to_menu, "mnu_reports"),
        ]
       ),
      ]
  ),
]
