DIALOGS = [
[anyone, "companion_depth_baheshtur_saddle_pending",
  [
    (eq, "$g_sod_baheshtur_saddle_witnessed", 1),
    (eq, "$g_sod_baheshtur_saddle_confronted", 1),
    (try_begin),
      (eq, "$g_sod_baheshtur_saddle_cause", 2),
      (str_store_string, s1, "@a broken camp leaves many saddles empty"),
    (else_try),
      (str_store_string, s1, "@a broken raid leaves proud riders measuring rope against open sky"),
    (try_end),
  ],
  "You heard him. {s1}. A horse can carry a free oath or a chain with better leather. We choose which one we offer.",
  "companion_depth_baheshtur_saddle_choice",
  []],

[anyone, "companion_depth_baheshtur_saddle_pending",
  [
    (eq, "$g_sod_baheshtur_saddle_witnessed", 1),
    (eq, "$g_sod_baheshtur_saddle_confronted", 0),
    (try_begin),
      (eq, "$g_sod_baheshtur_saddle_cause", 2),
      (str_store_string, s1, "@the horde camp is broken, and many riders have nowhere to return"),
    (else_try),
      (str_store_string, s1, "@the raider band is broken, and survivors are waiting to learn whether defeat means a new master"),
    (try_end),
  ],
  "{s1}. The rider has spoken, but words are cheap under another man's blade. Run the rider oath trial with me before you choose what freedom means.",
  "companion_depth_baheshtur_oath_trial_choice",
  []],

[anyone, "companion_depth_baheshtur_saddle_pending",
  [
    (eq, "$g_sod_baheshtur_saddle_witnessed", 0),
    (try_begin),
      (eq, "$g_sod_baheshtur_saddle_cause", 2),
      (str_store_string, s1, "@the horde camp is broken, and many riders have nowhere to return"),
    (else_try),
      (str_store_string, s1, "@the raider band is broken, and survivors are waiting to learn whether defeat means a new master"),
    (try_end),
  ],
  "{s1}. Find a living rider and let him say whether a saddle means choice or rope. Then we will answer.",
  "member_talk",
  []],

[anyone|plyr, "companion_depth_baheshtur_oath_trial_choice", [
    (main_party_has_troop, "trp_npc5"),
    (eq, "$g_sod_baheshtur_saddle_pending", 1),
    (eq, "$g_sod_baheshtur_saddle_witnessed", 1),
    (eq, "$g_sod_baheshtur_saddle_confronted", 0),
  ],
  "Run the oath trial now.", "close_window",
  [
    (jump_to_menu, "mnu_baheshtur_rider_oath_trial"),
    (finish_mission),
  ]],

[anyone|plyr, "companion_depth_baheshtur_oath_trial_choice", [
    (main_party_has_troop, "trp_npc5"),
  ],
  "Not yet.", "member_talk", []],

[anyone|plyr, "companion_depth_baheshtur_saddle_choice", [
    (main_party_has_troop, "trp_npc5"),
    (eq, "$g_sod_baheshtur_saddle_witnessed", 1),
    (eq, "$g_sod_baheshtur_saddle_confronted", 1),
  ],
  "Offer freedom to riders who swear freely.", "member_talk",
  [
    (assign, "$g_sod_baheshtur_saddle_pending", 0),
    (assign, "$g_sod_baheshtur_saddle_result_grade", 3),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_black_khergit_camp_defeat, 2),
    (call_script, "script_sod_companion_shift_approval", "trp_npc5", 3),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc5", 1),
    (quest_set_slot, "qst_companion_baheshtur_unbroken_saddle", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_baheshtur_unbroken_saddle", slot_quest_sod_runtime_metadata, "$g_sod_baheshtur_saddle_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc5"),
    (call_script, "script_sod_companion_baheshtur_apply_saddle_payoff"),
    (display_message, "@The riders who remain do so by their own word. The Unbroken Saddle remembers chosen loyalty.", 0x99CCFF),
  ]],

[anyone|plyr, "companion_depth_baheshtur_saddle_choice", [
    (main_party_has_troop, "trp_npc5"),
    (eq, "$g_sod_baheshtur_saddle_witnessed", 1),
    (eq, "$g_sod_baheshtur_saddle_confronted", 1),
  ],
  "Ride hard, but leave surrender unchained.", "member_talk",
  [
    (assign, "$g_sod_baheshtur_saddle_pending", 0),
    (try_begin),
      (lt, "$g_sod_baheshtur_saddle_result_grade", 2),
      (assign, "$g_sod_baheshtur_saddle_result_grade", 2),
    (try_end),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_safe_roadcraft, 2),
    (call_script, "script_sod_companion_shift_approval", "trp_npc5", 2),
    (try_begin),
      (troop_slot_eq, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (troop_set_slot, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (else_try),
      (troop_slot_eq, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
      (call_script, "script_sod_companion_advance_personal_quest", "trp_npc5", 1),
      (call_script, "script_sod_companion_baheshtur_apply_saddle_payoff"),
    (try_end),
    (quest_set_slot, "qst_companion_baheshtur_unbroken_saddle", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_baheshtur_unbroken_saddle", slot_quest_sod_runtime_metadata, "$g_sod_baheshtur_saddle_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc5"),
    (display_message, "@Baheshtur drives the pursuit without turning surrender into rope. Respect follows hard behind the horses.", 0xCCCC66),
  ]],

[anyone|plyr, "companion_depth_baheshtur_saddle_choice", [
    (main_party_has_troop, "trp_npc5"),
    (eq, "$g_sod_baheshtur_saddle_witnessed", 1),
    (eq, "$g_sod_baheshtur_saddle_confronted", 1),
  ],
  "Force submission. Useful riders are useful.", "member_talk",
  [
    (assign, "$g_sod_baheshtur_saddle_pending", 0),
    (assign, "$g_sod_baheshtur_saddle_result_grade", 1),
    (call_script, "script_sod_companion_shift_approval", "trp_npc5", -4),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc5", 0),
    (troop_set_slot, "trp_npc5", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (quest_set_slot, "qst_companion_baheshtur_unbroken_saddle", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_baheshtur_unbroken_saddle", slot_quest_sod_runtime_metadata, "$g_sod_baheshtur_saddle_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc5"),
    (display_message, "@The riders obey. Baheshtur does not mistake obedience for loyalty.", 0xCC6666),
  ]],

[anyone, "companion_depth_baheshtur",
  [
    (troop_slot_ge, "trp_npc5", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (neg|troop_slot_ge, "trp_npc5", slot_troop_companion_warning_state, sod_companion_warning_redeemed),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "A forced oath is a rope with better words. My trust in your hand on the reins is {s2}; I am watching which riders you call free.",
  "member_talk",
  [
    (troop_set_slot, "trp_npc5", slot_troop_companion_warning_state, sod_companion_warning_acknowledged),
  ]],

[anyone, "companion_depth_baheshtur",
  [
    (troop_slot_eq, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "Those who stayed did so by their own word. Now they ride with us, not under us. My trust in your hand on the reins is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_baheshtur",
  [
    (troop_slot_eq, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_hard),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "The riders obey. Obedience is not loyalty. A broken saddle carries weight until it throws the rider. My trust in your hand on the reins is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_baheshtur",
  [
    (eq, "$g_sod_baheshtur_saddle_pending", 1),
    (eq, "$g_sod_baheshtur_saddle_witnessed", 1),
    (eq, "$g_sod_baheshtur_saddle_confronted", 0),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "The rider has given us a living witness. Run the oath trial with me, and we will see whether choice survives when steel is near. My trust in your hand on the reins is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_baheshtur",
  [
    (eq, "$g_sod_baheshtur_saddle_pending", 1),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "The horde riders are beaten enough to listen and proud enough to remember. We need a living witness, then an oath tested under open sky. My trust in your hand on the reins is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_baheshtur",
  [
    (troop_slot_eq, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "The Unbroken Saddle is simple enough. A hard ride can still be freely chosen. A forced ride is a chain, even under open sky. My trust is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_baheshtur",
  [
    (troop_slot_eq, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "A saddle can carry a man or mark him owned. The difference is who chose the ride. My trust in your hand on the reins is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_baheshtur",
  [
    (troop_slot_ge, "trp_npc5", slot_troop_companion_approval, 70),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "You understand that open ground is not freedom if another man holds the reins. That is worth riding beside. My trust in your hand on the reins is {s2}.",
  "member_talk",
  [
    (try_begin),
      (troop_slot_eq, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_none),
      (troop_set_slot, "trp_npc5", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc5"),
      (display_message, "@Baheshtur seems ready to speak at camp about The Unbroken Saddle and the price of chosen loyalty.", 0x99CCFF),
    (try_end),
  ]],

[anyone, "companion_depth_baheshtur",
  [
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc5"),
    (str_store_string_reg, s2, s68),
  ],
  "A hard ride can still be freely chosen. A forced ride is a chain, even under open sky. My trust in your hand on the reins is {s2}.",
  "member_talk",
  []],
]
