DIALOGS = [
[anyone, "companion_depth_artimenner_siege_pending",
  [
    (eq, "$g_sod_artimenner_siege_witnessed", 1),
    (eq, "$g_sod_artimenner_siege_confronted", 1),
    (try_begin),
      (eq, "$g_sod_artimenner_siege_cause", 2),
      (str_store_string, s1, "@the tower will stand only if the design is rebuilt around the load"),
    (else_try),
      (str_store_string, s1, "@the ladders will carry men only if the rushed joints are corrected"),
    (try_end),
  ],
  "{s1}. The weak point has a witness. Now decide whether haste or engineering commands the work.",
  "companion_depth_artimenner_siege_choice",
  []],

[anyone, "companion_depth_artimenner_siege_pending",
  [
    (eq, "$g_sod_artimenner_siege_witnessed", 1),
    (eq, "$g_sod_artimenner_siege_confronted", 0),
  ],
  "The weak point has a witness now. Guard the repair watch before we pretend a chalk mark has become engineering.",
  "companion_depth_artimenner_repair_watch_choice",
  []],

[anyone, "companion_depth_artimenner_siege_pending", [],
  "There is a weak point in the works. Inspect it at the construction site first; timber is more persuasive when it is failing in front of you.",
  "member_talk",
  []],

[anyone|plyr, "companion_depth_artimenner_repair_watch_choice",
  [
    (main_party_has_troop, "trp_npc15"),
    (eq, "$g_sod_artimenner_siege_pending", 1),
    (eq, "$g_sod_artimenner_siege_witnessed", 1),
    (eq, "$g_sod_artimenner_siege_confronted", 0),
  ],
  "Guard the repair watch now.", "close_window",
  [
    (jump_to_menu, "mnu_artimenner_repair_watch"),
    (finish_mission),
  ]],

[anyone|plyr, "companion_depth_artimenner_repair_watch_choice",
  [
    (main_party_has_troop, "trp_npc15"),
  ],
  "Not yet.", "member_talk", []],

[anyone|plyr, "companion_depth_artimenner_siege_choice",
  [
    (main_party_has_troop, "trp_npc15"),
    (eq, "$g_sod_artimenner_siege_witnessed", 1),
    (eq, "$g_sod_artimenner_siege_confronted", 1),
  ],
  "Rebuild the works properly.", "member_talk",
  [
    (assign, "$g_sod_artimenner_siege_pending", 0),
    (assign, "$g_sod_artimenner_siege_result_grade", 3),
    (quest_set_slot, "qst_companion_artimenner_siege_that_should", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_artimenner_siege_that_should", slot_quest_sod_runtime_metadata, "$g_sod_artimenner_siege_result_grade"),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_siege_preparation, 3),
    (call_script, "script_sod_companion_shift_approval", "trp_npc15", 3),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc15", 1),
    (call_script, "script_sod_companion_artimenner_apply_siege_payoff"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc15"),
    (display_message, "@The works hold because they were built to hold. The Siege That Should Have Worked remembers respected design.", 0x99CCFF),
  ]],

[anyone|plyr, "companion_depth_artimenner_siege_choice",
  [
    (main_party_has_troop, "trp_npc15"),
    (eq, "$g_sod_artimenner_siege_witnessed", 1),
    (eq, "$g_sod_artimenner_siege_confronted", 1),
  ],
  "Use a leaner plan with what we have.", "member_talk",
  [
    (assign, "$g_sod_artimenner_siege_pending", 0),
    (try_begin),
      (lt, "$g_sod_artimenner_siege_result_grade", 2),
      (assign, "$g_sod_artimenner_siege_result_grade", 2),
    (try_end),
    (quest_set_slot, "qst_companion_artimenner_siege_that_should", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_artimenner_siege_that_should", slot_quest_sod_runtime_metadata, "$g_sod_artimenner_siege_result_grade"),
    (call_script, "script_sod_companion_shift_approval", "trp_npc15", 2),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc15", 1),
    (call_script, "script_sod_companion_artimenner_apply_siege_payoff"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc15"),
    (display_message, "@Artimenner accepts the inferior plan because it is still a plan, not glorious nonsense.", 0xCCCC66),
  ]],

[anyone|plyr, "companion_depth_artimenner_siege_choice",
  [
    (main_party_has_troop, "trp_npc15"),
    (eq, "$g_sod_artimenner_siege_witnessed", 1),
    (eq, "$g_sod_artimenner_siege_confronted", 1),
  ],
  "If the works fail, you answer for it.", "member_talk",
  [
    (assign, "$g_sod_artimenner_siege_pending", 0),
    (assign, "$g_sod_artimenner_siege_result_grade", 1),
    (call_script, "script_sod_companion_shift_approval", "trp_npc15", -3),
    (quest_set_slot, "qst_companion_artimenner_siege_that_should", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_artimenner_siege_that_should", slot_quest_sod_runtime_metadata, "$g_sod_artimenner_siege_result_grade"),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc15", 0),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc15"),
    (troop_set_slot, "trp_npc15", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (display_message, "@Artimenner's voice goes flat. A neat report cannot carry a ladder.", 0xCC6666),
  ]],

[anyone, "companion_depth_artimenner",
  [
    (troop_slot_ge, "trp_npc15", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (neg|troop_slot_ge, "trp_npc15", slot_troop_companion_warning_state, sod_companion_warning_redeemed),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "I can calculate load, span, and failure. I cannot calculate how often pride will ask me to catch falling stones. My confidence in your respect for expertise is {s2}.",
  "member_talk",
  [
    (troop_set_slot, "trp_npc15", slot_troop_companion_warning_state, sod_companion_warning_acknowledged),
  ]],

[anyone, "companion_depth_artimenner",
  [
    (troop_slot_eq, "trp_npc15", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "The works held because they were built to hold. A rare victory for timber, geometry, and being listened to. My confidence in your respect for expertise is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_artimenner",
  [
    (troop_slot_eq, "trp_npc15", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_hard),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "The failed work found a culprit and the army moved on. A neat report. Shame it cannot carry a ladder. My confidence in your respect for expertise is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_artimenner",
  [
    (eq, "$g_sod_artimenner_siege_pending", 1),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "There is a weak point in the works. Inspect it, guard the repair watch, then decide whether the army respects expertise before or after men die. My confidence in your respect for expertise is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_artimenner",
  [
    (troop_slot_eq, "trp_npc15", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "The Siege That Should Have Worked is not a tragedy. Tragedy implies surprise. Ignored tolerances are a timetable. My confidence in your respect for expertise is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_artimenner",
  [
    (troop_slot_eq, "trp_npc15", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "This is how men die, not from courage, but from one brace nobody inspected. I intend to learn whether this company inspects braces. My confidence is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_artimenner",
  [
    (troop_slot_ge, "trp_npc15", slot_troop_companion_approval, 70),
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "You let facts be inconvenient before they become fatal. I assure you, this is rarer than command tents suggest. My confidence in your respect for expertise is {s2}.",
  "member_talk",
  [
    (try_begin),
      (troop_slot_eq, "trp_npc15", slot_troop_companion_personal_quest_stage, sod_companion_quest_none),
      (troop_set_slot, "trp_npc15", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc15"),
      (display_message, "@Artimenner seems ready to speak at camp about The Siege That Should Have Worked and the cost of ignored expertise.", 0x99CCFF),
    (try_end),
  ]],

[anyone, "companion_depth_artimenner",
  [
    (call_script, "script_sod_companion_get_approval_band_to_s68", "trp_npc15"),
    (str_store_string_reg, s2, s68),
  ],
  "Plans hold when commanders let them. Timber, stone, grain, and time all answer to laws older than pride. My confidence in your respect for expertise is {s2}.",
  "member_talk",
  []],
]
