DIALOGS = [
[anyone, "companion_depth_firentis_restitution_pending",
  [
    (eq, "$g_sod_firentis_restitution_witnessed", 1),
    (eq, "$g_sod_firentis_restitution_confronted", 1),
    (gt, "$g_sod_firentis_restitution_focus_center", 0),
    (party_is_active, "$g_sod_firentis_restitution_focus_center"),
    (str_store_party_name_link, s3, "$g_sod_firentis_restitution_focus_center"),
  ],
  "The elder at {s3} did not absolve us. Good. Absolution would be too easy. The village spoke, the hearing tested us, and now restitution can answer a living voice.",
  "companion_depth_firentis_restitution_choice",
  []],

[anyone, "companion_depth_firentis_restitution_pending",
  [
    (eq, "$g_sod_firentis_restitution_witnessed", 1),
    (eq, "$g_sod_firentis_restitution_confronted", 0),
    (gt, "$g_sod_firentis_restitution_focus_center", 0),
    (party_is_active, "$g_sod_firentis_restitution_focus_center"),
    (str_store_party_name_link, s3, "$g_sod_firentis_restitution_focus_center"),
  ],
  "The elder at {s3} gave us a living voice. Now we owe that village more than a private answer. Stand with me at the hearing before we decide what penance means.",
  "member_talk",
  []],

[anyone, "companion_depth_firentis_restitution_pending",
  [
    (try_begin),
      (le, "$g_sod_firentis_restitution_focus_center", 0),
      (call_script, "script_sod_companion_select_focus_village", sod_companion_focus_restitution_village),
      (assign, "$g_sod_firentis_restitution_focus_center", reg0),
    (try_end),
    (try_begin),
      (gt, "$g_sod_firentis_restitution_focus_center", 0),
      (party_is_active, "$g_sod_firentis_restitution_focus_center"),
      (str_store_party_name_link, s3, "$g_sod_firentis_restitution_focus_center"),
    (else_try),
      (str_store_string, s3, "@the nearest harmed village"),
    (try_end),
  ],
  "A saved village can still flinch at mailed hands. We brought swords. Go with me to the elder at {s3}, if you would have this judged by more than campfire guilt.",
  "member_talk",
  []],

[anyone|plyr, "companion_depth_firentis_restitution_choice", [],
  "Leave guards, coin, and supplies. Protection is part of penance.", "member_talk",
  [
    (assign, "$g_sod_firentis_restitution_pending", 0),
    (assign, "$g_sod_firentis_restitution_result_grade", 3),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_help_village, 3),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_honorable_peace, 2),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc6", 1),
    (call_script, "script_sod_companion_firentis_apply_restitution_payoff"),
    (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 3),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
    (display_message, "@Firentis accepts that penance must become shelter, coin, and restraint. Debt of the Sword remembers restitution.", 0x99CCFF),
  ]],

[anyone|plyr, "companion_depth_firentis_restitution_choice", [],
  "Let truth be spoken. Ask the village what justice can still mean.", "member_talk",
  [
    (assign, "$g_sod_firentis_restitution_pending", 0),
    (assign, "$g_sod_firentis_restitution_result_grade", 2),
    (call_script, "script_sod_companion_shift_approval", "trp_npc6", 2),
    (try_begin),
      (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (troop_set_slot, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (else_try),
      (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
      (call_script, "script_sod_companion_advance_personal_quest", "trp_npc6", 1),
      (call_script, "script_sod_companion_firentis_apply_restitution_payoff"),
    (try_end),
    (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 2),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
    (display_message, "@The answer is not clean, but it is honest. Firentis hears judgment without reaching for steel.", 0xCCCC66),
  ]],

[anyone|plyr, "companion_depth_firentis_restitution_choice", [],
  "Say nothing more. The village needed swords, not confession.", "member_talk",
  [
    (assign, "$g_sod_firentis_restitution_pending", 0),
    (assign, "$g_sod_firentis_restitution_result_grade", 1),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc6", 0),
    (troop_set_slot, "trp_npc6", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_firentis_debt_restitution", slot_quest_sod_runtime_metadata, 1),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc6"),
    (display_message, "@Firentis obeys. Debt of the Sword remembers silence as another wound.", 0xCC6666),
  ]],

[anyone, "companion_depth_firentis",
  [
    (troop_slot_ge, "trp_npc6", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "I have hidden behind obedience before. It is a fine shield until a man notices whose blood is on the rim. My faith in your command is {s2}, but I need the truth named.",
  "member_talk",
  [
    (troop_set_slot, "trp_npc6", slot_troop_companion_warning_state, sod_companion_warning_acknowledged),
  ]],

[anyone, "companion_depth_firentis",
  [
    (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "Restitution did not raise the dead. It did give the living something more honest than another speech beside a sword. My faith in your command is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_firentis",
  [
    (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_hard),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "The matter is quiet now. Quiet can be mercy, or cowardice, or only a grave with grass over it. I remain, but my faith in your command is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_firentis",
  [
    (eq, "$g_sod_firentis_restitution_pending", 1),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "The village is saved, and still something in it asks payment from every armed hand. I would have your order before I mistake silence for discipline. My faith in your command is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_firentis",
  [
    (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "There will come a village, a prisoner, or a frightened face that asks whether this sword has changed hands or merely changed banners. My faith in your command is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_firentis",
  [
    (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "A sword remembers what the hand asks of it. So do the living. I think I am near a reckoning, and my faith in your command is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_firentis",
  [
    (troop_slot_ge, "trp_npc6", slot_troop_companion_approval, 70),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "You have shown me that strength can kneel without becoming weak. That is a harder lesson than any fencing master ever gave. My faith in your command is {s2}.",
  "member_talk",
  [
    (try_begin),
      (troop_slot_eq, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_none),
      (troop_set_slot, "trp_npc6", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (display_message, "@Firentis seems ready to speak at camp about the debts a sword cannot pay alone.", 0x99CCFF),
    (try_end),
  ]],

[anyone, "companion_depth_firentis",
  [
    (call_script, "script_sod_companion_get_approval_band", "trp_npc6"),
    (str_store_string_reg, s2, s0),
  ],
  "Conscience is not a thing I would trust to comfort, my friend. It is a watchman. At present, my faith in your command is {s2}.",
  "member_talk",
  []],
]
