DIALOGS = [
[anyone, "companion_depth_katrin_coin_pending",
  [
    (eq, "$g_sod_katrin_last_coin_witnessed", 1),
    (eq, "$g_sod_katrin_last_coin_confronted", 1),
    (try_begin),
      (eq, "$g_sod_katrin_last_coin_cause", 2),
      (str_store_string, s1, "@arrears, owed shares, and the kind of promise that gets counted by hungry men"),
    (else_try),
      (str_store_string, s1, "@thin sacks, hard broth, and medicine stretched until it becomes hope"),
    (try_end),
  ],
  "You saw the ledger. Good. No romance left in it, then: {s1}. Now choose where the last coin goes.",
  "companion_depth_katrin_coin_choice",
  []],

[anyone, "companion_depth_katrin_coin_pending",
  [
    (eq, "$g_sod_katrin_last_coin_witnessed", 1),
    (eq, "$g_sod_katrin_last_coin_confronted", 0),
  ],
  "You saw the ledger. Good. Now put eyes on the supply watch. People get philosophical about shortages until someone stands beside the sacks.",
  "member_talk",
  []],

[anyone, "companion_depth_katrin_coin_pending",
  [
    (eq, "$g_sod_katrin_last_coin_witnessed", 0),
    (try_begin),
      (eq, "$g_sod_katrin_last_coin_cause", 2),
      (str_store_string, s1, "@wages are owed and promises have become thin coin"),
    (else_try),
      (str_store_string, s1, "@food sacks are light and supper has become a negotiation"),
    (try_end),
  ],
  "Here it is, then. {s1}. The brave version is expensive. The sensible version is also expensive. The foolish version pretends not to be.",
  "member_talk",
  []],

[anyone|plyr, "companion_depth_katrin_coin_choice", [
    (eq, "$g_sod_katrin_last_coin_witnessed", 1),
    (eq, "$g_sod_katrin_last_coin_confronted", 1),
  ],
  "Put the coin toward food, medicine, and honest arrears.", "member_talk",
  [
    (assign, "$g_sod_katrin_last_coin_pending", 0),
    (assign, "$g_sod_katrin_last_coin_result_grade", 3),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_food_security, 3),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc11", 1),
    (quest_set_slot, "qst_companion_katrin_last_coin", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_katrin_last_coin", slot_quest_sod_runtime_metadata, "$g_sod_katrin_last_coin_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc11"),
    (call_script, "script_sod_companion_katrin_apply_last_coin_payoff"),
    (display_message, "@Katrin spends without ceremony and saves without romance. The Last Coin in Camp remembers practical care.", 0x99CCFF),
  ]],

[anyone|plyr, "companion_depth_katrin_coin_choice", [
    (eq, "$g_sod_katrin_last_coin_witnessed", 1),
    (eq, "$g_sod_katrin_last_coin_confronted", 1),
  ],
  "Stretch the stores hard, but keep the burden shared.", "member_talk",
  [
    (assign, "$g_sod_katrin_last_coin_pending", 0),
    (try_begin),
      (lt, "$g_sod_katrin_last_coin_result_grade", 2),
      (assign, "$g_sod_katrin_last_coin_result_grade", 2),
    (try_end),
    (call_script, "script_sod_companion_shift_approval", "trp_npc11", 2),
    (try_begin),
      (troop_slot_eq, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (troop_set_slot, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (else_try),
      (troop_slot_eq, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
      (call_script, "script_sod_companion_advance_personal_quest", "trp_npc11", 1),
      (call_script, "script_sod_companion_katrin_apply_last_coin_payoff"),
    (try_end),
    (quest_set_slot, "qst_companion_katrin_last_coin", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_katrin_last_coin", slot_quest_sod_runtime_metadata, "$g_sod_katrin_last_coin_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc11"),
    (display_message, "@Katrin makes the rationing fair enough that resentment has fewer places to root.", 0xCCCC66),
  ]],

[anyone|plyr, "companion_depth_katrin_coin_choice", [
    (eq, "$g_sod_katrin_last_coin_witnessed", 1),
    (eq, "$g_sod_katrin_last_coin_confronted", 1),
  ],
  "Spend for momentum. The camp can tighten belts later.", "member_talk",
  [
    (assign, "$g_sod_katrin_last_coin_pending", 0),
    (assign, "$g_sod_katrin_last_coin_result_grade", 1),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc11", 0),
    (troop_set_slot, "trp_npc11", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (quest_set_slot, "qst_companion_katrin_last_coin", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_katrin_last_coin", slot_quest_sod_runtime_metadata, "$g_sod_katrin_last_coin_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc11"),
    (display_message, "@The company moves faster today. Katrin makes the thin broth last and says nothing generous about tomorrow.", 0xCC6666),
  ]],

[anyone, "companion_depth_katrin",
  [
    (troop_slot_ge, "trp_npc11", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "Do not ask people to clap for glory while their bellies are arguing with their ribs. My trust in your sense is {s2}, and that is me being polite.",
  "member_talk",
  [
    (troop_set_slot, "trp_npc11", slot_troop_companion_warning_state, sod_companion_warning_acknowledged),
  ]],

[anyone, "companion_depth_katrin",
  [
    (troop_slot_eq, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "The coin went where it should: food, wages, medicine, and fewer foolish deaths. It was not grand. Grand things are usually expensive and poorly packed. My trust in your sense is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_katrin",
  [
    (troop_slot_eq, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_hard),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "We spent the coin on momentum and patched the consequences with boiled water and bad tempers. I kept the camp standing. Do not mistake that for approval. My trust in your sense is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_katrin",
  [
    (eq, "$g_sod_katrin_last_coin_pending", 1),
    (eq, "$g_sod_katrin_last_coin_witnessed", 1),
    (eq, "$g_sod_katrin_last_coin_confronted", 0),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "The ledger is no longer private. Run the supply watch with me before you spend the last coin. My trust in your sense is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_katrin",
  [
    (eq, "$g_sod_katrin_last_coin_pending", 1),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "The camp has reached the part of command where coins, bread, and promises stop pretending to be separate things. First hear the ledger witness, then stand the supply watch. My trust in your sense is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_katrin",
  [
    (troop_slot_eq, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "Sooner or later the heroic plan reaches the cooking pot. I am waiting to see whether you notice before the pot is empty. My trust in your sense is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_katrin",
  [
    (troop_slot_eq, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "I have seen brave companies fail because nobody wanted to count spoons. The Last Coin in Camp will tell me plenty about you. My trust in your sense is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_katrin",
  [
    (troop_slot_ge, "trp_npc11", slot_troop_companion_approval, 70),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "You remember that people march on feet, not banners, and eat bread, not intentions. Sensible. Suspiciously so. My trust in your sense is {s2}.",
  "member_talk",
  [
    (try_begin),
      (troop_slot_eq, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_none),
      (troop_set_slot, "trp_npc11", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (display_message, "@Katrin seems ready to speak at camp about the last coin left after heroics have eaten their fill.", 0x99CCFF),
    (try_end),
  ]],

[anyone, "companion_depth_katrin",
  [
    (call_script, "script_sod_companion_get_approval_band", "trp_npc11"),
    (str_store_string, s2, s0),
  ],
  "It needs food before glory, wages before speeches, and clean cloth before another brave fool bleeds on my blankets. My trust in your sense is {s2}.",
  "member_talk",
  []],
]
