DIALOGS = [
[anyone, "companion_depth_matheld_step_pending",
  [
    (eq, "$g_sod_matheld_no_backward_step_witnessed", 1),
    (eq, "$g_sod_matheld_no_backward_step_confronted", 1),
    (try_begin),
      (eq, "$g_sod_matheld_no_backward_step_cause", 2),
      (str_store_string, s1, "@too many fell while the line stood"),
    (else_try),
      (str_store_string, s1, "@the line gave ground, and fear learned the shape of retreat"),
    (try_end),
  ],
  "{s1}. The next line will learn from what you praise, punish, and repair. So choose the lesson.",
  "companion_depth_matheld_step_choice",
  []],

[anyone, "companion_depth_matheld_step_pending",
  [
    (eq, "$g_sod_matheld_no_backward_step_witnessed", 1),
    (eq, "$g_sod_matheld_no_backward_step_confronted", 0),
  ],
  "The ranker has said what the line remembers. Now we put shields in hands and test the lesson where fear can push back.",
  "member_talk",
  []],

[anyone, "companion_depth_matheld_step_pending",
  [
    (eq, "$g_sod_matheld_no_backward_step_witnessed", 0),
  ],
  "Ask someone who stood in that line. I know what I saw, but a shield wall belongs to the ones whose ribs held it.",
  "member_talk",
  []],

[anyone|plyr, "companion_depth_matheld_step_choice", [
    (eq, "$g_sod_matheld_no_backward_step_witnessed", 1),
    (eq, "$g_sod_matheld_no_backward_step_confronted", 1),
  ],
  "Temper courage into a shield wall that saves lives.", "member_talk",
  [
    (assign, "$g_sod_matheld_no_backward_step_pending", 0),
    (assign, "$g_sod_matheld_no_backward_step_result_grade", 3),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_honorable_peace, 2),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc8", 1),
    (quest_set_slot, "qst_companion_matheld_no_backward_step", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_matheld_no_backward_step", slot_quest_sod_runtime_metadata, "$g_sod_matheld_no_backward_step_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc8"),
    (call_script, "script_sod_companion_matheld_apply_step_payoff"),
    (display_message, "@Matheld accepts discipline because the shield still faces forward. No Backward Step remembers courage with teeth.", 0x99CCFF),
  ]],

[anyone|plyr, "companion_depth_matheld_step_choice", [
    (eq, "$g_sod_matheld_no_backward_step_witnessed", 1),
    (eq, "$g_sod_matheld_no_backward_step_confronted", 1),
  ],
  "Stand firm and answer the next threat directly.", "member_talk",
  [
    (assign, "$g_sod_matheld_no_backward_step_pending", 0),
    (try_begin),
      (lt, "$g_sod_matheld_no_backward_step_result_grade", 2),
      (assign, "$g_sod_matheld_no_backward_step_result_grade", 2),
    (try_end),
    (call_script, "script_sod_companion_apply_player_action", sod_companion_action_hard_victory, 2),
    (call_script, "script_sod_companion_shift_approval", "trp_npc8", 2),
    (try_begin),
      (troop_slot_eq, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (troop_set_slot, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (else_try),
      (troop_slot_eq, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
      (call_script, "script_sod_companion_advance_personal_quest", "trp_npc8", 1),
      (call_script, "script_sod_companion_matheld_apply_step_payoff"),
    (try_end),
    (quest_set_slot, "qst_companion_matheld_no_backward_step", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_matheld_no_backward_step", slot_quest_sod_runtime_metadata, "$g_sod_matheld_no_backward_step_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc8"),
    (display_message, "@Matheld bares her teeth. Let them see the shield before they feel it.", 0xCCCC66),
  ]],

[anyone|plyr, "companion_depth_matheld_step_choice", [
    (eq, "$g_sod_matheld_no_backward_step_witnessed", 1),
    (eq, "$g_sod_matheld_no_backward_step_confronted", 1),
  ],
  "Make every insult cost blood. No one calls the company soft.", "member_talk",
  [
    (assign, "$g_sod_matheld_no_backward_step_pending", 0),
    (assign, "$g_sod_matheld_no_backward_step_result_grade", 1),
    (call_script, "script_sod_companion_advance_personal_quest", "trp_npc8", 0),
    (troop_set_slot, "trp_npc8", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (quest_set_slot, "qst_companion_matheld_no_backward_step", slot_quest_sod_runtime_progress, 100),
    (quest_set_slot, "qst_companion_matheld_no_backward_step", slot_quest_sod_runtime_metadata, "$g_sod_matheld_no_backward_step_result_grade"),
    (call_script, "script_sod_companion_sync_personal_quest_framework", "trp_npc8"),
    (display_message, "@No one can call the company soft. The dead cannot call it wise.", 0xCC6666),
  ]],

[anyone, "companion_depth_matheld",
  [
    (troop_slot_ge, "trp_npc8", slot_troop_companion_warning_state, sod_companion_warning_pending),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "Blood-price is easy. Wisdom is harder, and less fun to sing about. My trust in your courage is {s2}, but courage is not just who dies loudest.",
  "member_talk",
  [
    (troop_set_slot, "trp_npc8", slot_troop_companion_warning_state, sod_companion_warning_acknowledged),
  ]],

[anyone, "companion_depth_matheld",
  [
    (troop_slot_eq, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "The line stood and lived enough to stand again. That is courage with teeth, not courage with an empty skull. My trust in your courage is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_matheld",
  [
    (troop_slot_eq, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_hard),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "No one calls us soft. Good. Some also do not answer when names are called. Less good. My trust in your courage is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_matheld",
  [
    (eq, "$g_sod_matheld_no_backward_step_pending", 1),
    (eq, "$g_sod_matheld_no_backward_step_witnessed", 1),
    (eq, "$g_sod_matheld_no_backward_step_confronted", 0),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "The line has spoken. Now run the shield-line test with me. Then we can decide what courage should teach. My trust in your courage is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_matheld",
  [
    (eq, "$g_sod_matheld_no_backward_step_pending", 1),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "The line learned something in that fight. Ask a ranker what it was, then test the lesson with shields in hand. My trust in your courage is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_matheld",
  [
    (troop_slot_eq, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_test_started),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "No Backward Step is not about never moving. It is about keeping your face toward the danger even when the feet must be clever. My trust is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_matheld",
  [
    (troop_slot_eq, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "There are days a company learns whether its back is bone or smoke. I am waiting for that day. My trust in your courage is {s2}.",
  "member_talk",
  []],

[anyone, "companion_depth_matheld",
  [
    (troop_slot_ge, "trp_npc8", slot_troop_companion_approval, 70),
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "You know a shield wall must breathe if it means to last. Good. I prefer courage that can fight again tomorrow. My trust in your courage is {s2}.",
  "member_talk",
  [
    (try_begin),
      (troop_slot_eq, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_none),
      (troop_set_slot, "trp_npc8", slot_troop_companion_personal_quest_stage, sod_companion_quest_trust_unlocked),
      (display_message, "@Matheld seems ready to speak at camp about the line between a backward step and a living shield.", 0x99CCFF),
    (try_end),
  ]],

[anyone, "companion_depth_matheld",
  [
    (call_script, "script_sod_companion_get_approval_band", "trp_npc8"),
    (str_store_string, s2, s0),
  ],
  "Courage is not a song. It is what remains when the shield is heavy and the road behind you looks kinder than the one ahead. My trust in your courage is {s2}.",
  "member_talk",
  []],
]
