MENUS = [
(
    "rtc_hounds_terms", mnf_disable_all_keys,
    "{s1}^^{s2}^^{s3}^^{s4}^^Legate Gaius Marius does not come himself. The Hound sends terms with enough soldiers behind the messenger to make the parchment feel heavier than steel.",
    "none",
    [
      (try_begin),
        (neq, "$g_sod_rtc_enabled", 1),
        (jump_to_menu, "mnu_start_phase_2"),
      (try_end),
      (set_background_mesh, "mesh_pic_mb_warrior_1"),
      (call_script, "script_sod_rtc_hounds_terms_prepare_envoy"),

      (quest_get_slot, ":bread_center", "qst_rtc_hounds_terms", slot_quest_target_center),
      (quest_get_slot, ":bread_choice", "qst_rtc_price_of_bread", slot_quest_sod_chain_choice),
      (try_begin),
        (is_between, ":bread_center", centers_begin, centers_end),
        (str_store_party_name_link, s5, ":bread_center"),
        (try_begin),
          (eq, ":bread_choice", 4),
          (str_store_string, s3, "@The Imperial clerk has heard of {s5}. He calls it proof that your mercy requires supervision."),
        (else_try),
          (eq, ":bread_choice", 5),
          (str_store_string, s3, "@The Imperial clerk has heard of {s5}. He calls unresolved hunger a census problem waiting for Imperial order."),
        (else_try),
          (eq, ":bread_choice", 6),
          (str_store_string, s3, "@The Imperial clerk has heard of {s5}. He dislikes that bandits, not villagers, paid the first price of your hunger."),
        (else_try),
          (eq, ":bread_choice", 3),
          (str_store_string, s3, "@The Imperial clerk has heard of {s5}. He offers to protect merchants from the kind of truth you exposed."),
        (else_try),
          (eq, ":bread_choice", 2),
          (str_store_string, s3, "@The Imperial clerk has heard of {s5}. He calls your labor bargain primitive administration, then offers a stamped version of it."),
        (else_try),
          (eq, ":bread_choice", 1),
          (str_store_string, s3, "@The Imperial clerk has heard of {s5}. Fair payment makes poor propaganda, so he calls it temporary luck."),
        (else_try),
          (str_store_string, s3, "@The Imperial clerk has heard the bread rumor and files it wherever useful accusations are kept."),
        (try_end),
      (else_try),
        (str_store_string, s3, "@The Imperial clerk has heard the bread rumor without a place-name. That makes it easier to weaponize."),
      (try_end),

      (quest_get_slot, ":offer", "qst_rtc_hounds_terms", slot_quest_object_troop),
      (try_begin),
        (eq, ":offer", sod_rtc_offer_bread_oath),
        (str_store_string, s4, "@The terms attack the bread oath directly: Imperial granaries will feed the hungry, if the hungry accept Imperial counting first."),
      (else_try),
        (eq, ":offer", sod_rtc_offer_books_oath),
        (str_store_string, s4, "@The terms attack the books oath directly: Imperial auditors offer cleaner ledgers, safer roads, and chains hidden in the margins."),
      (else_try),
        (eq, ":offer", sod_rtc_offer_witness_oath),
        (str_store_string, s4, "@The terms attack the witness oath directly: Marius offers to certify every witness who agrees to be smaller than the Empire."),
      (else_try),
        (str_store_string, s4, "@The terms attack whatever part of the claim looks easiest to own, register, or frighten."),
      (try_end),

      (quest_get_slot, ":route", "qst_rtc_hounds_terms", slot_quest_rtc_branch_seed),
      (try_begin),
        (eq, ":route", sod_rtc_branch_legitimacy),
        (str_store_string, s1, "@Marius offers legal recognition under Imperial supervision: law, if you accept the collar beneath it."),
      (else_try),
        (eq, ":route", sod_rtc_branch_mercenary),
        (str_store_string, s1, "@Marius offers contract rights, pay, and road authority as an Imperial auxiliary command."),
      (else_try),
        (eq, ":route", sod_rtc_branch_conquest),
        (str_store_string, s1, "@Marius offers to recognize strength if it kneels before a stronger banner."),
      (else_try),
        (eq, ":route", sod_rtc_branch_coalition),
        (str_store_string, s1, "@Marius offers protection for villages and refugees if their leaders submit to Imperial registration."),
      (else_try),
        (eq, ":route", sod_rtc_branch_restoration),
        (str_store_string, s1, "@Marius offers a road home under Imperial census, tribute, and permanent garrison."),
      (else_try),
        (eq, ":route", sod_rtc_branch_imperial),
        (str_store_string, s1, "@Septima's offer has become explicit: accept Imperial recognition and survive as a sanctioned power."),
      (else_try),
        (eq, ":route", sod_rtc_branch_regime_maker),
        (str_store_string, s1, "@Marius offers silence for silence: your hidden regime survives if it points its knives away from the Empire."),
      (else_try),
        (str_store_string, s1, "@Marius offers mercy to a fractured claim, which is another way of naming surrender."),
      (try_end),

      (quest_get_slot, ":pressure", "qst_rtc_hounds_terms", slot_quest_rtc_companion_pressure),
      (try_begin),
        (gt, ":pressure", 0),
        (str_store_string, s2, "@Your company is not whole. The Hound's terms press hardest where the campfire already cracked."),
      (else_try),
        (str_store_string, s2, "@Your company hears the terms together. That does not make the answer easy; it makes it answerable."),
      (try_end),
    ],
    [
      ("rtc_terms_reject_release", [], "Reject the terms and release the envoy. Open conflict follows, but the answer is clean.", [
        (call_script, "script_sod_rtc_hounds_terms_handle_envoy", 1),
        (call_script, "script_sod_rtc_hounds_terms_resolve", sod_rtc_terms_rejected),
        (jump_to_menu, "mnu_rtc_war_of_witnesses"),
      ]),
      ("rtc_terms_reject_detain", [], "Reject the terms and detain the envoy. Gain leverage, give Marius propaganda.", [
        (call_script, "script_sod_rtc_hounds_terms_handle_envoy", 2),
        (call_script, "script_sod_rtc_hounds_terms_resolve", sod_rtc_terms_rejected),
        (jump_to_menu, "mnu_rtc_war_of_witnesses"),
      ]),
      ("rtc_terms_delay", [], "Negotiate delay and send a counter-demand. Buy time, leave the threat intact.", [
        (call_script, "script_sod_rtc_hounds_terms_handle_envoy", 3),
        (call_script, "script_sod_rtc_hounds_terms_resolve", sod_rtc_terms_delay_negotiated),
        (jump_to_menu, "mnu_rtc_war_of_witnesses"),
      ]),
      ("rtc_terms_accept", [], "Accept the terms. Bend the claim toward Empire.", [
        (call_script, "script_sod_rtc_hounds_terms_handle_envoy", 1),
        (call_script, "script_sod_rtc_hounds_terms_resolve", sod_rtc_terms_accepted),
        (jump_to_menu, "mnu_rtc_war_of_witnesses"),
      ]),
      ("rtc_terms_collapse", [], "Let talks collapse. The claim fractures under Imperial pressure.", [
        (call_script, "script_sod_rtc_hounds_terms_handle_envoy", 4),
        (call_script, "script_sod_rtc_hounds_terms_resolve", sod_rtc_terms_collapsed),
        (jump_to_menu, "mnu_banner_selection"),
      ]),
    ]
  ),
]
