MENUS = [
(
    "rtc_final_confrontation", mnf_disable_all_keys,
    "{s1}^^{s2}^^{s3}^^{s4}^^The final road has chosen its shape. Marius, the Empire, and the crown all arrive at the same hour.",
    "none",
    [
      (try_begin),
        (neq, "$g_sod_rtc_enabled", 1),
        (jump_to_menu, "mnu_start_phase_2"),
      (try_end),
      (set_background_mesh, "mesh_pic_mb_warrior_1"),
      (call_script, "script_sod_rtc_final_confrontation_prepare_target", 0),

      (quest_get_slot, ":bread_center", "qst_rtc_final_confrontation", slot_quest_target_center),
      (quest_get_slot, ":bread_choice", "qst_rtc_price_of_bread", slot_quest_sod_chain_choice),
      (try_begin),
        (is_between, ":bread_center", centers_begin, centers_end),
        (str_store_party_name_link, s5, ":bread_center"),
        (try_begin),
          (eq, ":bread_choice", 4),
          (str_store_string, s2, "@If you win, {s5} will remember being fed by fear. If you lose, the Empire will call that fear evidence."),
        (else_try),
          (eq, ":bread_choice", 5),
          (str_store_string, s2, "@If you win, {s5} may yet see hunger answered late. If you lose, the Empire will inherit every empty bowl as accusation."),
        (else_try),
          (eq, ":bread_choice", 6),
          (str_store_string, s2, "@If you win, {s5} will remember that predators bled before villagers did. If you lose, Marius will make that story disappear."),
        (else_try),
          (eq, ":bread_choice", 3),
          (str_store_string, s2, "@If you win, {s5} will remember that hidden stores can be dragged into daylight. If you lose, merchants will learn which truths are punishable."),
        (else_try),
          (eq, ":bread_choice", 2),
          (str_store_string, s2, "@If you win, {s5} will remember labor for bread as the first rough draft of rule. If you lose, that bargain becomes a footnote."),
        (else_try),
          (eq, ":bread_choice", 1),
          (str_store_string, s2, "@If you win, {s5} will remember that the road began with a debt paid cleanly. If you lose, clean debts will not save the witnesses."),
        (else_try),
          (str_store_string, s2, "@The bread village remains one of the small places history usually crushes unless someone makes it matter."),
        (try_end),
      (else_try),
        (str_store_string, s2, "@The first bread rumor reaches the final hour blurred but stubborn. Even legends begin as someone needing to eat."),
      (try_end),

      (quest_get_slot, ":envoy_handling", "qst_rtc_final_confrontation", slot_quest_sod_chain_choice),
      (try_begin),
        (eq, ":envoy_handling", 2),
        (str_store_string, s3, "@The detained envoy's shadow reaches the final field. The Empire names it hostage-taking; your harder allies name it necessary leverage."),
      (else_try),
        (eq, ":envoy_handling", 3),
        (str_store_string, s3, "@Your counter-demand reaches this hour beside Marius's terms. The Empire no longer owns the only script."),
      (else_try),
        (eq, ":envoy_handling", 1),
        (str_store_string, s3, "@The released envoy carried your answer cleanly. If Marius comes now, he comes by choice, not confusion."),
      (else_try),
        (str_store_string, s3, "@The envoy's muddled road has become rumor around the final field. No one agrees what was offered, refused, or threatened."),
      (try_end),

      (quest_get_slot, ":offer", "qst_rtc_final_confrontation", slot_quest_object_troop),
      (try_begin),
        (eq, ":offer", sod_rtc_offer_bread_oath),
        (str_store_string, s4, "@The bread oath reaches the final hour. Victory must mean hungry people can point to something stronger than Imperial counting."),
      (else_try),
        (eq, ":offer", sod_rtc_offer_books_oath),
        (str_store_string, s4, "@The books oath reaches the final hour. Victory must mean roads and debts answer to something other than Imperial auditors."),
      (else_try),
        (eq, ":offer", sod_rtc_offer_witness_oath),
        (str_store_string, s4, "@The witness oath reaches the final hour. Victory must mean testimony survives longer than fear."),
      (else_try),
        (str_store_string, s4, "@No single oath reaches the final hour cleanly. The ending will be easier for others to define if you leave it empty."),
      (try_end),

      (quest_get_slot, ":strategy", "qst_rtc_final_confrontation", slot_quest_rtc_method_seed),
      (try_begin),
        (eq, ":strategy", sod_rtc_last_road_strike_hound),
        (str_store_string, s1, "@The confrontation is direct: the Hound must be defeated or forced from the field."),
      (else_try),
        (eq, ":strategy", sod_rtc_last_road_accept_collar),
        (str_store_string, s1, "@The confrontation is political: the Hound can become overlord, patron, or mask."),
      (else_try),
        (eq, ":strategy", sod_rtc_last_road_break_seal),
        (str_store_string, s1, "@The confrontation is public: the Imperial seal must break where witnesses can see it."),
      (else_try),
        (eq, ":strategy", sod_rtc_last_road_turn_accusation),
        (str_store_string, s1, "@The confrontation is rhetorical: Marius must answer the envoy dispute before he can turn it into a weapon."),
      (else_try),
        (eq, ":strategy", sod_rtc_last_road_starve_empire),
        (str_store_string, s1, "@The confrontation is logistical: the Empire must discover that hunger can face both directions."),
      (else_try),
        (eq, ":strategy", sod_rtc_last_road_catastrophic_loss),
        (str_store_string, s1, "@The confrontation is collapse: the road is ash underfoot."),
      (else_try),
        (str_store_string, s1, "@The confrontation is defensive: hold long enough for the crown road to outlive the Hound's demand."),
      (try_end),
    ],
    [
      ("rtc_final_defeat_marius", [], "Defeat Marius. Break the Hound's command.", [
        (call_script, "script_sod_rtc_final_confrontation_resolve", sod_rtc_final_marius_defeated),
        (jump_to_menu, "mnu_banner_selection"),
      ]),
      ("rtc_final_force_back", [], "Force Marius back. Win time, not peace.", [
        (call_script, "script_sod_rtc_final_confrontation_resolve", sod_rtc_final_marius_forced_back),
        (jump_to_menu, "mnu_banner_selection"),
      ]),
      ("rtc_final_overlord", [
        (quest_slot_eq, "qst_rtc_final_confrontation", slot_quest_rtc_branch_seed, sod_rtc_branch_imperial),
      ], "Accept Marius as overlord. Become an Imperial crown.", [
        (call_script, "script_sod_rtc_final_confrontation_resolve", sod_rtc_final_marius_overlord),
        (jump_to_menu, "mnu_banner_selection"),
      ]),
      ("rtc_final_unworn", [], "Reject personal rule. Leave the crown unworn.", [
        (call_script, "script_sod_rtc_final_confrontation_resolve", sod_rtc_final_unworn_crown),
        (jump_to_menu, "mnu_banner_selection"),
      ]),
      ("rtc_final_collapse", [], "Let the claim collapse. The road ends in ash.", [
        (call_script, "script_sod_rtc_final_confrontation_resolve", sod_rtc_final_claim_collapse),
        (jump_to_menu, "mnu_banner_selection"),
      ]),
    ]
  ),
]
