SCRIPTS = [
("calculate_player_faction_wage",
    [(assign, ":nongarrison_wages", 0),
      (assign, ":garrison_wages", 0),
      (try_for_parties, ":party_no"),
        (assign, ":garrison_troop", 0),
        (assign, ":ungarrison_troop", 0),
        (try_begin),
          (this_or_next|party_slot_eq, ":party_no", slot_party_type, spt_town),
          (party_slot_eq, ":party_no", slot_party_type, spt_castle),
          (party_slot_eq, ":party_no", slot_town_lord, "trp_player"),
          (assign, ":garrison_troop", 1),
        (else_try),
          (this_or_next|party_slot_eq, ":party_no", slot_party_type, spt_player_mercenaries),
		  (party_slot_eq, ":party_no", slot_party_type, spt_player_patrol),
		  (party_get_attached_to, ":is_resting", ":party_no"),
		  (try_begin),
			(gt, ":is_resting", 0),
			(assign, ":ungarrison_troop", 2),
		  (else_try),
			(assign, ":ungarrison_troop", 1),
		  (try_end),
        (try_end),
        (this_or_next|eq, ":party_no", "p_main_party"),
        (this_or_next|eq, ":garrison_troop", 1),
        (this_or_next|eq, ":ungarrison_troop", 1),
		(eq, ":ungarrison_troop", 2),
		(try_begin),
			(assign, ":upkeep", 0),
			(this_or_next|party_slot_eq, ":party_no", slot_party_type, spt_castle),
			(party_slot_eq, ":party_no", slot_party_type, spt_town), #twan456 town have no reason not to pay this part of upkeep
			(party_get_num_companions, ":garrison_size", ":party_no"),
				(try_begin),
				    (this_or_next|party_slot_eq, ":party_no", slot_party_type, spt_castle),
				    (party_slot_eq, ":party_no", slot_party_type, spt_town),
					(party_slot_eq, ":party_no", slot_center_has_blacksmith, 0),  # blacksmith reduces garrison overhead
					(val_mul, ":garrison_size", 3),
				(else_try),
					(val_mul, ":garrison_size", 2),
				(try_end),
			(val_add, ":upkeep", ":garrison_size"),
			(party_get_num_prisoners, ":num_prisoners", ":party_no"),
				(try_begin),
					(party_slot_eq, ":party_no", slot_center_has_prisoner_tower, 0), #twan456 upkeep was reduced by garrison !??
				(else_try),
					(val_div, ":num_prisoners", 2),
				(try_end),
			(val_add, ":upkeep", ":num_prisoners"),
			(try_begin),
				(party_slot_eq, ":party_no", slot_party_type, spt_castle),
				(party_get_slot, ":num_trainers", ":party_no", slot_center_trainers),
				(val_max, ":num_trainers", 0),
				(val_mul, ":num_trainers", 75),
				(val_add, ":upkeep", ":num_trainers"),
				(val_mul, ":upkeep", 2),
			(try_end),
			(val_add, ":garrison_wages", ":upkeep"),
		(try_end),
        (party_get_num_companion_stacks, ":num_stacks", ":party_no"),
        (try_for_range, ":i_stack", 0, ":num_stacks"),
          (party_stack_get_troop_id, ":stack_troop", ":party_no", ":i_stack"),
          (party_stack_get_size, ":stack_size", ":party_no", ":i_stack"),
          (call_script, "script_game_get_troop_wage", ":stack_troop", ":party_no"),
          (assign, ":cur_wage", reg0),
          (val_mul, ":cur_wage", ":stack_size"),
          (try_begin),
            (eq, ":garrison_troop", 1),
            (val_add, ":garrison_wages", ":cur_wage"),
          (else_try),
            (try_begin),
              (eq, ":ungarrison_troop", 1),
              (val_mul, ":cur_wage", 3),
              (val_div, ":cur_wage", 2),
			(else_try),
              (eq, ":ungarrison_troop", 2),
              (val_mul, ":cur_wage", 2),
              (val_div, ":cur_wage", 3),           
			(try_end),
            (val_add, ":nongarrison_wages", ":cur_wage"),
          (try_end),
        (try_end),
      (try_end),
      (val_div, ":garrison_wages", 2), #Half payment for garrisons
      (store_sub, ":total_payment", 14, "$g_cur_week_half_daily_wage_payments"), #between 0 and 7
      (val_mul, ":nongarrison_wages", ":total_payment"),
      (val_div, ":nongarrison_wages", 14),
      (store_add, reg0, ":nongarrison_wages", ":garrison_wages"),
  ]),
]
