SCRIPTS = [
("do_merchant_town_trade",
    [
      (store_script_param_1, ":party_no"),
      (store_script_param_2, ":center_no"),
      (assign, ":merchant_troop", -1),
      (assign, ":scarcity_score", 0),
      (assign, ":abundance_score", 0),
      (assign, ":import_pressure", 0),
      (assign, ":export_pressure", 0),
      (assign, ":center_prosperity", 0),
      (assign, ":center_population", 20),
      (assign, ":town_rural_surplus", 0),
      (assign, ":town_consumption_pressure", 0),
      (assign, ":town_import_demand", 0),
      (assign, ":town_services", 0),
      (assign, ":town_recovery_rate", 0),
      (assign, ":town_liquidity", 0),
      (assign, ":town_trade_volume", 100),
      (assign, ":town_tariff_capture", 100),
      (assign, ":town_tax_reliability", 100),
      (assign, ":goods_food_balance", 0),
      (assign, ":goods_raw_balance", 0),
      (assign, ":goods_strategic_balance", 0),
      (assign, ":goods_luxury_flow", 0),
      (assign, ":goods_scarcity_pressure", 0),
      (assign, ":goods_trade_willingness", 100),
      (assign, ":goods_liquidity_pressure", 0),
      (assign, ":goods_prosperity_pressure", 0),
      (call_script, "script_sod_get_center_trade_demand_profile", ":center_no"),
      (assign, ":profile_scarcity", reg0),
      (assign, ":profile_import_demand", reg1),
      (assign, ":profile_export_supply", reg2),
      (assign, ":profile_market_liquidity", reg3),
      (assign, ":profile_security_willingness", reg4),
      (assign, ":profile_tax_friction", reg5),
      (assign, ":profile_caravan_attractiveness", reg6),
      (assign, ":profile_trade_volume", reg7),
      (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
      (assign, ":goods_food_balance", reg0),
      (assign, ":goods_raw_balance", reg1),
      (assign, ":goods_strategic_balance", reg2),
      (assign, ":goods_luxury_flow", reg3),
      (assign, ":goods_scarcity_pressure", reg4),
      (assign, ":goods_trade_willingness", reg5),
      (assign, ":goods_liquidity_pressure", reg6),
      (assign, ":goods_prosperity_pressure", reg8),
      (store_faction_of_party, ":trade_tax_faction", ":center_no"),
      (call_script, "script_sod_law_calculate_trade_tax_policy", ":trade_tax_faction"),
      (assign, ":trade_tax_modifier", reg0),
      (assign, ":trade_volume_modifier", reg1),
      (assign, ":merchant_happiness_modifier", reg2),
      (assign, ":tariff_modifier", reg3),
      (call_script, "script_sod_get_center_modifier_totals", ":center_no"),
      (assign, ":stock_roll", reg8),
      (assign, ":center_prosperity_growth_pct", reg11),
      (assign, ":center_trade_liquidity", reg12),
      (assign, ":center_trade_volume_pct", reg13),
      (assign, ":center_tariff_pct", reg14),
      (assign, ":center_health_recovery", reg5),
      (val_mul, ":trade_volume_modifier", ":center_trade_volume_pct"),
      (val_div, ":trade_volume_modifier", 100),
      (val_mul, ":trade_volume_modifier", ":profile_trade_volume"),
      (val_div, ":trade_volume_modifier", 100),
      (val_clamp, ":trade_volume_modifier", 35, 180),
      (val_mul, ":tariff_modifier", ":center_tariff_pct"),
      (val_div, ":tariff_modifier", 100),
      (val_clamp, ":tariff_modifier", 25, 250),
      (try_begin),
        (this_or_next|is_between, ":center_no", towns_begin, towns_end),
        (is_between, ":center_no", villages_begin, villages_end),
        (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
        (party_get_slot, ":center_prosperity", ":center_no", slot_town_prosperity),
      (try_end),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (call_script, "script_sod_get_town_market_profile", ":center_no"),
        (assign, ":town_rural_surplus", reg1),
        (assign, ":town_consumption_pressure", reg2),
        (assign, ":town_import_demand", reg3),
        (assign, ":town_services", reg4),
        (assign, ":town_recovery_rate", reg5),
        (assign, ":town_liquidity", reg6),
        (assign, ":town_trade_volume", reg7),
        (assign, ":town_tariff_capture", reg8),
        (assign, ":town_tax_reliability", reg9),
        (val_mul, ":trade_volume_modifier", ":town_trade_volume"),
        (val_div, ":trade_volume_modifier", 100),
        (val_clamp, ":trade_volume_modifier", 35, 220),
        (val_mul, ":tariff_modifier", ":town_tariff_capture"),
        (val_div, ":tariff_modifier", 100),
        (val_clamp, ":tariff_modifier", 25, 300),
      (try_end),
      (val_max, ":center_population", 1),
      (assign, ":food_store", 0),
      (assign, ":food_store_limit", 0),
      (assign, ":food_security", 0),
      (assign, ":food_capacity_ratio", 0),
      (assign, ":food_pressure", 0),
      (try_begin),
        (this_or_next|is_between, ":center_no", towns_begin, towns_end),
        (is_between, ":center_no", villages_begin, villages_end),
        (call_script, "script_sod_get_center_food_profile", ":center_no"),
        (assign, ":food_store", reg0),
        (assign, ":food_store_limit", reg1),
        (assign, ":food_security", reg4),
        (assign, ":food_capacity_ratio", reg5),
        (assign, ":food_pressure", reg6),
        (val_add, ":food_security", ":stock_roll"),
      (try_end),
      (assign, ":trade_percent", 20),
      (assign, ":old_caravan_upgrade_tier", 0),
      (try_begin),
        (party_slot_eq, ":party_no", slot_party_type, spt_kingdom_caravan),
        (party_get_slot, ":old_caravan_upgrade_tier", ":party_no", slot_party_caravan_upgrade_tier),
        (val_clamp, ":old_caravan_upgrade_tier", 0, 4),
        (store_mul, ":stock_roll", ":old_caravan_upgrade_tier", sod_caravan_trade_percent_bonus_per_tier),
        (val_add, ":trade_percent", ":stock_roll"),
      (try_end),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (party_get_slot, ":merchant_troop", ":center_no", slot_town_merchant),
      (try_end),
      (try_begin),
        (gt, ":merchant_troop", 0),
        (store_sub, ":item_to_price_slot", slot_town_trade_good_prices_begin, trade_goods_begin),
        (try_for_range, ":cur_good", trade_goods_begin, trade_goods_end),
          (call_script, "script_get_troop_item_amount", ":merchant_troop", ":cur_good"),
          (assign, ":stock_amount", reg0),
          (assign, ":desired_stock", 1),
          (try_begin),
            (is_between, ":center_no", towns_begin, towns_end),
            (store_div, ":pop_stock_need", ":center_population", 225),
            (val_add, ":desired_stock", 2),
          (else_try),
            (store_div, ":pop_stock_need", ":center_population", 90),
            (val_add, ":desired_stock", 1),
          (try_end),
          (val_add, ":desired_stock", ":pop_stock_need"),
          (store_div, ":prosperity_stock_need", ":center_prosperity", 25),
          (val_add, ":desired_stock", ":prosperity_stock_need"),
          (val_clamp, ":desired_stock", 1, 13),
          (store_sub, ":stock_gap", ":desired_stock", ":stock_amount"),
          (store_sub, ":stock_surplus", ":stock_amount", ":desired_stock"),
          (try_begin),
            (ge, ":stock_gap", 4),
            (val_add, ":scarcity_score", 2),
          (else_try),
            (ge, ":stock_gap", 1),
            (val_add, ":scarcity_score", 1),
          (else_try),
            (ge, ":stock_surplus", 5),
            (val_add, ":abundance_score", 2),
          (else_try),
            (ge, ":stock_surplus", 2),
            (val_add, ":abundance_score", 1),
          (try_end),
          (store_add, ":cur_good_price_slot", ":cur_good", ":item_to_price_slot"),
          (party_get_slot, ":cur_merchant_price", ":party_no", ":cur_good_price_slot"),
          (party_get_slot, ":cur_center_price", ":center_no", ":cur_good_price_slot"),
          (store_sub, ":price_gap", ":cur_center_price", ":cur_merchant_price"),
          (try_begin),
            (gt, ":price_gap", 8),
            (try_begin),
              (ge, ":stock_gap", 4),
              (val_add, ":import_pressure", 2),
            (else_try),
              (ge, ":stock_gap", 1),
              (val_add, ":import_pressure", 1),
            (try_end),
            (try_begin),
              (gt, ":stock_gap", 0),
              (store_random_in_range, ":stock_roll", 0, 100),
              (store_add, ":restock_chance", 25, ":stock_gap"),
              (val_clamp, ":restock_chance", 0, 65),
              (lt, ":stock_roll", ":restock_chance"),
              (troop_add_item, ":merchant_troop", ":cur_good", 0),
            (try_end),
          (else_try),
            (lt, ":price_gap", -8),
            (try_begin),
              (ge, ":stock_surplus", 5),
              (val_add, ":export_pressure", 2),
            (else_try),
              (ge, ":stock_surplus", 2),
              (val_add, ":export_pressure", 1),
            (try_end),
            (try_begin),
              (ge, ":stock_surplus", 2),
              (store_random_in_range, ":stock_roll", 0, 100),
              (store_add, ":trim_chance", 20, ":stock_surplus"),
              (val_clamp, ":trim_chance", 0, 60),
              (lt, ":stock_roll", ":trim_chance"),
              (troop_remove_item, ":merchant_troop", ":cur_good"),
            (try_end),
          (try_end),
        (try_end),
        (troop_ensure_inventory_space, ":merchant_troop", 80),
        (troop_sort_inventory, ":merchant_troop"),
      (try_end),

      # Markets under real pressure should trade more aggressively, while already
      # comfortable centers should not over-consume caravan attention.
      (val_add, ":trade_percent", ":import_pressure"),
      (store_div, ":stock_roll", ":profile_import_demand", 16),
      (val_add, ":trade_percent", ":stock_roll"),
      (store_div, ":stock_roll", ":profile_scarcity", 18),
      (val_add, ":trade_percent", ":stock_roll"),
      (store_div, ":stock_roll", ":profile_market_liquidity", 80),
      (val_add, ":trade_percent", ":stock_roll"),
      (store_div, ":stock_roll", ":goods_liquidity_pressure", 60),
      (val_add, ":trade_percent", ":stock_roll"),
      (store_div, ":stock_roll", ":goods_scarcity_pressure", 24),
      (val_add, ":trade_percent", ":stock_roll"),
      (store_sub, ":goods_willingness_drag", 85, ":goods_trade_willingness"),
      (val_max, ":goods_willingness_drag", 0),
      (val_div, ":goods_willingness_drag", 10),
      (val_sub, ":trade_percent", ":goods_willingness_drag"),
      (try_begin),
        (lt, ":goods_food_balance", -40),
        (val_add, ":trade_percent", 3),
      (try_end),
      (try_begin),
        (lt, ":goods_strategic_balance", -35),
        (val_add, ":trade_percent", 2),
      (try_end),
      (store_div, ":stock_roll", ":profile_export_supply", 70),
      (val_sub, ":trade_percent", ":stock_roll"),
      (val_sub, ":trade_percent", ":export_pressure"),
      (val_add, ":trade_percent", ":scarcity_score"),
      (val_sub, ":trade_percent", ":abundance_score"),
      (try_begin),
        (gt, ":food_pressure", 0),
        (store_div, ":stock_roll", ":food_pressure", 5),
        (val_add, ":trade_percent", ":stock_roll"),
      (try_end),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (store_div, ":stock_roll", ":town_import_demand", 12),
        (val_add, ":trade_percent", ":stock_roll"),
        (store_div, ":stock_roll", ":town_consumption_pressure", 18),
        (val_add, ":trade_percent", ":stock_roll"),
        (store_div, ":stock_roll", ":town_services", 30),
        (val_add, ":trade_percent", ":stock_roll"),
        (store_div, ":stock_roll", ":town_rural_surplus", 80),
        (val_sub, ":trade_percent", ":stock_roll"),
      (try_end),
      (try_begin),
        (lt, ":food_capacity_ratio", 20),
        (val_add, ":trade_percent", 10),
      (else_try),
        (lt, ":food_capacity_ratio", 40),
        (val_add, ":trade_percent", 5),
      (else_try),
        (ge, ":food_capacity_ratio", 80),
        (val_sub, ":trade_percent", 3),
      (try_end),
      (try_begin),
        (lt, ":food_security", 350),
        (val_add, ":trade_percent", 10),
      (else_try),
        (lt, ":food_security", 700),
        (val_add, ":trade_percent", 5),
      (else_try),
        (ge, ":food_security", 1400),
        (val_sub, ":trade_percent", 3),
      (try_end),
      (try_begin),
        (ge, ":center_population", 1800),
        (lt, ":food_security", 900),
        (val_add, ":trade_percent", 4),
      (else_try),
        (ge, ":center_population", 1000),
        (lt, ":food_security", 600),
        (val_add, ":trade_percent", 2),
      (try_end),
      (try_begin),
        (lt, ":center_prosperity", 40),
        (val_add, ":trade_percent", 3),
      (else_try),
        (ge, ":center_prosperity", 65),
        (ge, ":food_capacity_ratio", 70),
        (val_sub, ":trade_percent", 2),
      (try_end),
      (try_begin),
        (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
        (call_script, "script_cf_sod_companion_in_main_party", "trp_npc2"),
        (troop_slot_ge, "trp_npc2", slot_troop_companion_approval, 45),
        (troop_slot_eq, "trp_npc2", slot_troop_companion_role, sod_companion_role_quartermaster),
        (troop_slot_eq, "trp_npc2", slot_troop_companion_personal_quest_stage, sod_companion_quest_resolved_good),
        (val_add, ":trade_percent", 3),
        (val_add, ":town_tax_reliability", 2),
        (val_clamp, ":town_tax_reliability", 0, 151),
      (try_end),
      (try_begin),
        (gt, ":import_pressure", ":export_pressure"),
        (gt, ":tariff_modifier", 112),
        (val_add, ":import_pressure", 1),
      (try_end),
      (val_mul, ":trade_percent", ":trade_volume_modifier"),
      (val_div, ":trade_percent", 100),
      (store_sub, ":profile_security_drag", 90, ":profile_security_willingness"),
      (val_max, ":profile_security_drag", 0),
      (val_div, ":profile_security_drag", 8),
      (val_sub, ":trade_percent", ":profile_security_drag"),
      (store_div, ":stock_roll", ":profile_tax_friction", 16),
      (val_sub, ":trade_percent", ":stock_roll"),
      (val_clamp, ":trade_percent", 12, 45),

      (call_script, "script_do_party_center_trade", ":party_no", ":center_no", ":trade_percent"), # upgraded caravans trade more aggressively

      (assign, ":total_change", reg0),
      #Adding the earnings to the wealth (maximum changed price is the earning)
      (val_div, ":total_change", 2),
      (str_store_party_name_link, s1, ":party_no"),
      (str_store_party_name_link, s2, ":center_no"),
      (assign, reg1, ":total_change"),
      (try_begin),
        (eq, "$cheat_mode", 1),
        (display_message, "@Merchant {s1} traded with {s2} and earned {reg1} denars.", debug_color),
      (try_end),

      (try_begin),
        (party_slot_eq, ":party_no", slot_party_type, spt_kingdom_caravan),
        (party_get_slot, ":caravan_lifetime_profit", ":party_no", slot_party_caravan_trade_profit),
        (val_add, ":caravan_lifetime_profit", ":total_change"),
        (party_set_slot, ":party_no", slot_party_caravan_trade_profit, ":caravan_lifetime_profit"),
        (assign, ":new_caravan_upgrade_tier", 0),
        (try_begin),
          (ge, ":caravan_lifetime_profit", sod_caravan_upgrade_profit_tier_3),
          (assign, ":new_caravan_upgrade_tier", 3),
        (else_try),
          (ge, ":caravan_lifetime_profit", sod_caravan_upgrade_profit_tier_2),
          (assign, ":new_caravan_upgrade_tier", 2),
        (else_try),
          (ge, ":caravan_lifetime_profit", sod_caravan_upgrade_profit_tier_1),
          (assign, ":new_caravan_upgrade_tier", 1),
        (try_end),
        (party_set_slot, ":party_no", slot_party_caravan_upgrade_tier, ":new_caravan_upgrade_tier"),
        (try_begin),
          (gt, ":new_caravan_upgrade_tier", ":old_caravan_upgrade_tier"),
          (store_faction_of_party, ":trade_tax_faction", ":party_no"),
          (faction_get_slot, ":stock_roll", ":trade_tax_faction", slot_faction_reinforcements_b),
          (try_for_range, ":cur_good", ":old_caravan_upgrade_tier", ":new_caravan_upgrade_tier"),
            (party_add_template, ":party_no", ":stock_roll"),
          (try_end),
          (try_begin),
            (eq, "$cheat_mode", 1),
            (assign, reg2, ":new_caravan_upgrade_tier"),
            (assign, reg3, ":caravan_lifetime_profit"),
            (display_message, "@Merchant {s1} reached caravan tier {reg2} with {reg3} lifetime profit.", debug_color),
          (try_end),
        (try_end),
      (try_end),

      #Adding tax revenue to the center
      (party_get_slot, ":accumulated_tariffs", ":center_no", slot_center_accumulated_tariffs),
      (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
      (party_get_slot, ":center_health", ":center_no", slot_center_sod_local_health),
      (party_get_slot, ":food_store", ":center_no", slot_party_food_store),
      (call_script, "script_center_get_food_store_limit", ":center_no"),
      (assign, ":food_store_limit", reg0),
      (store_mul, ":food_good_threshold", ":food_store_limit", 3),
      (val_div, ":food_good_threshold", 5),
      (store_mul, ":food_low_threshold", ":food_store_limit", 1),
      (val_div, ":food_low_threshold", 5),
      (val_max, ":food_good_threshold", 30),
      (val_max, ":food_low_threshold", 10),
      # Safety: keep trade/tariff math from going negative or overflowing.
      (val_max, ":accumulated_tariffs", 0),
      (val_max, ":total_change", 0),
      (val_max, ":prosperity", 0),
      (val_max, ":food_store", 0),
      (val_clamp, ":center_health", -100, 121),
      (store_div, ":population_market_bonus", ":center_population", 300),
      (val_clamp, ":population_market_bonus", 0, 10),
      (store_add, ":tax_gain", ":prosperity", 10),
      (val_add, ":tax_gain", ":import_pressure"),
      (val_add, ":tax_gain", ":abundance_score"),
      (val_sub, ":tax_gain", ":scarcity_score"),
      (store_add, ":health_modifier", ":center_health", 100),
      (val_div, ":health_modifier", 12),
      (val_add, ":tax_gain", ":health_modifier"),
      (val_add, ":tax_gain", ":population_market_bonus"),
      (store_div, ":profile_liquidity_tax_bonus", ":profile_market_liquidity", 100),
      (val_add, ":tax_gain", ":profile_liquidity_tax_bonus"),
      (store_div, ":stock_roll", ":goods_liquidity_pressure", 120),
      (val_add, ":tax_gain", ":stock_roll"),
      (store_div, ":stock_roll", ":goods_luxury_flow", 12),
      (val_add, ":tax_gain", ":stock_roll"),
      (store_div, ":stock_roll", ":goods_scarcity_pressure", 60),
      (val_sub, ":tax_gain", ":stock_roll"),
      (try_begin),
        (ge, ":food_store", ":food_good_threshold"),
        (val_add, ":tax_gain", 4),
      (else_try),
        (lt, ":food_store", ":food_low_threshold"),
        (val_sub, ":tax_gain", 4),
      (try_end),
      (val_max, ":tax_gain", 5),
      (val_mul, ":tax_gain", ":total_change"),
      (val_div, ":tax_gain", 2200), #(10 + prosperity) / 110 * 5% of the merchant's revenue.
      (val_mul, ":tax_gain", ":tariff_modifier"),
      (val_div, ":tax_gain", 100),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (val_mul, ":tax_gain", ":town_tax_reliability"),
        (val_div, ":tax_gain", 100),
      (try_end),
      (val_max, ":tax_gain", 0),
      (call_script, "script_sod_center_apply_tariffs_delta", ":center_no", ":tax_gain"),

      # Trade also improves immediate market liquidity; shortages and net exports dampen it.
      (assign, ":market_liquidity", ":total_change"),
      (val_div, ":market_liquidity", 4),
      (store_div, ":profile_liquidity_bonus", ":profile_market_liquidity", 12),
      (val_add, ":market_liquidity", ":profile_liquidity_bonus"),
      (store_div, ":profile_attractiveness_bonus", ":profile_caravan_attractiveness", 20),
      (val_add, ":market_liquidity", ":profile_attractiveness_bonus"),
      (store_div, ":goods_liquidity_bonus", ":goods_liquidity_pressure", 5),
      (val_add, ":market_liquidity", ":goods_liquidity_bonus"),
      (store_div, ":goods_raw_liquidity_bonus", ":goods_raw_balance", 12),
      (val_add, ":market_liquidity", ":goods_raw_liquidity_bonus"),
      (store_div, ":goods_strategic_liquidity_bonus", ":goods_strategic_balance", 10),
      (val_add, ":market_liquidity", ":goods_strategic_liquidity_bonus"),
      (store_div, ":goods_luxury_liquidity_bonus", ":goods_luxury_flow", 8),
      (val_add, ":market_liquidity", ":goods_luxury_liquidity_bonus"),
      (store_div, ":goods_scarcity_liquidity_drag", ":goods_scarcity_pressure", 10),
      (val_sub, ":market_liquidity", ":goods_scarcity_liquidity_drag"),
      (val_add, ":market_liquidity", ":import_pressure"),
      (val_add, ":market_liquidity", ":abundance_score"),
      (val_sub, ":market_liquidity", ":scarcity_score"),
      (val_sub, ":market_liquidity", ":export_pressure"),
      (val_add, ":market_liquidity", ":merchant_happiness_modifier"),
      (val_add, ":market_liquidity", ":center_trade_liquidity"),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (store_div, ":town_liquidity_trade", ":town_liquidity", 8),
        (val_add, ":market_liquidity", ":town_liquidity_trade"),
        (store_div, ":town_services_liquidity", ":town_services", 15),
        (val_add, ":market_liquidity", ":town_services_liquidity"),
        (store_div, ":town_import_liquidity_drag", ":town_import_demand", 25),
        (val_sub, ":market_liquidity", ":town_import_liquidity_drag"),
      (try_end),
      (try_begin),
        (ge, ":food_store", ":food_good_threshold"),
        (val_add, ":market_liquidity", 3),
      (else_try),
        (lt, ":food_store", ":food_low_threshold"),
        (val_sub, ":market_liquidity", 3),
      (try_end),
      (val_mul, ":market_liquidity", ":trade_volume_modifier"),
      (val_div, ":market_liquidity", 100),
      (store_sub, ":tax_friction", ":trade_tax_modifier", 100),
      (val_div, ":tax_friction", 5),
      (val_sub, ":market_liquidity", ":tax_friction"),
      (store_div, ":profile_liquidity_tax_drag", ":profile_tax_friction", 6),
      (val_sub, ":market_liquidity", ":profile_liquidity_tax_drag"),
      (val_clamp, ":market_liquidity", -25, 300),
      (call_script, "script_sod_change_center_wealth", ":center_no", ":market_liquidity"),

      # debug
      (try_begin),
        (eq, "$g_sod_debug", 1),
        (str_store_party_name_link, s1, ":center_no"),
        (assign, reg0, ":accumulated_tariffs"),
        (display_message, "@{s1} accumulated {reg0} tariffs", debug_color),
      (try_end),

      #      (try_begin),
      #        (is_between, ":center_no", towns_begin, towns_end),
      #        (party_get_slot, ":merchant", ":center_no", slot_town_merchant),
      #        (gt, ":merchant", 0),
      #        (store_mul, ":merchant_profit", ":total_change", 1),
      #        (val_div, ":merchant_profit", 2),
      #        (troop_add_gold, ":merchant", ":merchant_profit"),
      #      (try_end),

      # Adding prosperity/health/food effects based on trade value and real stock conditions.
      (assign, ":prosperity_chance", 18),
      (val_add, ":prosperity_chance", ":import_pressure"),
      (val_add, ":prosperity_chance", ":abundance_score"),
      (val_sub, ":prosperity_chance", ":scarcity_score"),
      (val_sub, ":prosperity_chance", ":export_pressure"),
      (store_add, ":health_trade_bonus", ":center_health", 100),
      (val_div, ":health_trade_bonus", 10),
      (val_add, ":prosperity_chance", ":health_trade_bonus"),
      (val_add, ":prosperity_chance", ":population_market_bonus"),
      (store_div, ":profile_recovery_bonus", ":profile_caravan_attractiveness", 25),
      (val_add, ":prosperity_chance", ":profile_recovery_bonus"),
      (store_div, ":goods_recovery_bonus", ":goods_liquidity_pressure", 14),
      (val_add, ":prosperity_chance", ":goods_recovery_bonus"),
      (store_div, ":goods_scarcity_recovery_drag", ":goods_scarcity_pressure", 16),
      (val_sub, ":prosperity_chance", ":goods_scarcity_recovery_drag"),
      (try_begin),
        (gt, ":goods_prosperity_pressure", 0),
        (val_add, ":prosperity_chance", 5),
      (else_try),
        (lt, ":goods_prosperity_pressure", 0),
        (val_sub, ":prosperity_chance", 7),
      (try_end),
      (try_begin),
        (ge, ":food_store", ":food_good_threshold"),
        (val_add, ":prosperity_chance", 8),
      (else_try),
        (lt, ":food_store", ":food_low_threshold"),
        (val_sub, ":prosperity_chance", 10),
      (try_end),
      (try_begin),
        (gt, ":total_change", 80),
        (val_add, ":prosperity_chance", 10),
      (else_try),
        (gt, ":total_change", 30),
        (val_add, ":prosperity_chance", 5),
      (try_end),
      (val_mul, ":prosperity_chance", ":trade_volume_modifier"),
      (val_div, ":prosperity_chance", 100),
      (val_mul, ":prosperity_chance", ":center_prosperity_growth_pct"),
      (val_div, ":prosperity_chance", 100),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (store_div, ":town_recovery_chance", ":town_recovery_rate", 8),
        (val_add, ":prosperity_chance", ":town_recovery_chance"),
      (try_end),
      (store_sub, ":tax_friction", ":trade_tax_modifier", 100),
      (val_div, ":tax_friction", 4),
      (val_sub, ":prosperity_chance", ":tax_friction"),
      (store_div, ":profile_recovery_tax_drag", ":profile_tax_friction", 8),
      (val_sub, ":prosperity_chance", ":profile_recovery_tax_drag"),
      (val_clamp, ":prosperity_chance", 5, 80),
      (store_random_in_range, ":rand", 0, 100),
      (try_begin),
        (lt, ":rand", ":prosperity_chance"),
        (call_script, "script_change_center_prosperity", ":center_no", 1),
      (try_end),

      (try_begin),
        (gt, ":import_pressure", ":export_pressure"),
        (assign, ":food_import", ":total_change"),
        (val_div, ":food_import", 12),
        (try_begin),
          (lt, ":food_capacity_ratio", 20),
          (val_add, ":food_import", 4),
        (else_try),
          (lt, ":food_capacity_ratio", 40),
          (val_add, ":food_import", 2),
        (try_end),
        (try_begin),
          (lt, ":food_security", 350),
          (val_add, ":food_import", 4),
        (else_try),
          (lt, ":food_security", 700),
          (val_add, ":food_import", 2),
        (try_end),
        (try_begin),
          (gt, ":scarcity_score", ":abundance_score"),
          (store_sub, ":import_bonus", ":scarcity_score", ":abundance_score"),
          (val_add, ":food_import", ":import_bonus"),
        (try_end),
        (try_begin),
          (is_between, ":center_no", towns_begin, towns_end),
          (store_div, ":town_food_import_bonus", ":town_import_demand", 30),
          (val_add, ":food_import", ":town_food_import_bonus"),
        (try_end),
        (try_begin),
          (lt, ":goods_food_balance", -30),
          (store_mul, ":goods_food_import_bonus", ":goods_food_balance", -1),
          (val_div, ":goods_food_import_bonus", 20),
          (val_add, ":food_import", ":goods_food_import_bonus"),
        (try_end),
        (try_begin),
          (is_between, ":center_no", towns_begin, towns_end),
          (val_clamp, ":food_import", 0, 25),
        (else_try),
          (val_clamp, ":food_import", 0, 15),
        (try_end),
        (call_script, "script_sod_center_apply_food_delta", ":center_no", ":food_import"),
        (assign, ":food_store", reg0),
      (else_try),
        (gt, ":scarcity_score", ":abundance_score"),
        (assign, ":food_loss", ":scarcity_score"),
        (val_div, ":food_loss", 2),
        (val_add, ":food_loss", 1),
        (store_mul, ":food_delta", ":food_loss", -1),
        (call_script, "script_sod_center_apply_food_delta", ":center_no", ":food_delta"),
        (assign, ":food_store", reg0),
      (try_end),

      (try_begin),
        (gt, ":import_pressure", ":export_pressure"),
        (gt, ":total_change", 45),
        (assign, ":health_chance", 8),
        (val_add, ":health_chance", ":abundance_score"),
        (val_sub, ":health_chance", ":scarcity_score"),
        (try_begin),
          (store_add, ":food_ok_threshold", ":food_low_threshold", ":food_good_threshold"),
          (val_div, ":food_ok_threshold", 2),
          (ge, ":food_store", ":food_ok_threshold"),
          (val_add, ":health_chance", 6),
        (try_end),
        (val_mul, ":health_chance", ":trade_volume_modifier"),
        (val_div, ":health_chance", 100),
        (val_add, ":health_chance", ":center_health_recovery"),
        (store_sub, ":health_tax_friction", ":trade_tax_modifier", 100),
        (val_div, ":health_tax_friction", 8),
        (val_sub, ":health_chance", ":health_tax_friction"),
        (val_clamp, ":health_chance", 0, 30),
        (store_random_in_range, ":health_roll", 0, 100),
        (lt, ":health_roll", ":health_chance"),
        (call_script, "script_change_center_health", ":center_no", 1),
      (try_end),

      (try_begin),
        (party_slot_eq, ":party_no", slot_party_type, spt_kingdom_caravan),
        (call_script, "script_sod_trade_network_process_caravan_arrival", ":party_no", ":center_no"),
      (try_end),

  ]),
]
