SCRIPTS = [
("get_prosperity_text_to_s50",
      [(store_script_param, ":center_no", 1),
        (party_get_slot, ":prosperity", ":center_no", slot_town_prosperity),
        (val_div, ":prosperity", 20),
        (try_begin),
          (eq, ":prosperity", 0),
          (str_store_string, s50, "@Very Poor"),
        (else_try),
          (eq, ":prosperity", 1),
          (str_store_string, s50, "@Poor"),
        (else_try),
          (eq, ":prosperity", 2),
          (str_store_string, s50, "@Average"),
        (else_try),
          (eq, ":prosperity", 3),
          (str_store_string, s50, "@Rich"),
        (else_try),
          (str_store_string, s50, "@Very Rich"),
        (try_end),
    ]),
]
