SCRIPTS = [
("loot_player_items",
    [
      (store_script_param, ":enemy_party_no", 1),

      (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
      (try_for_range, ":i_slot", 0, ":inv_cap"),
        (troop_get_inventory_slot, ":item_id", "trp_player", ":i_slot"),
        (ge, ":item_id", 0),
        (troop_get_inventory_slot_modifier, ":item_modifier", "trp_player", ":i_slot"),
        (item_get_type, ":item_type", ":item_id"),
        (assign, ":randomness", 0),
        (try_begin),
          (is_between, ":item_id", trade_goods_begin, trade_goods_end),
          (assign, ":randomness", 20),
        (else_try),
          (eq, ":item_type", itp_type_horse),
          (assign, ":randomness", 15),
        (else_try),
          (this_or_next|eq, ":item_type", itp_type_one_handed_wpn),
          (this_or_next|eq, ":item_type", itp_type_two_handed_wpn),
          (this_or_next|eq, ":item_type", itp_type_polearm),
          (this_or_next|eq, ":item_type", itp_type_arrows),
          (this_or_next|eq, ":item_type", itp_type_bolts),
          (this_or_next|eq, ":item_type", itp_type_bullets),
          (this_or_next|eq, ":item_type", itp_type_bow),
          (this_or_next|eq, ":item_type", itp_type_crossbow),
          (this_or_next|eq, ":item_type", itp_type_thrown),
          (this_or_next|eq, ":item_type", itp_type_pistol),
          (eq, ":item_type", itp_type_musket),
          (assign, ":randomness", 5),
        (else_try),
          (this_or_next|eq, ":item_type", itp_type_head_armor),
          (this_or_next|eq, ":item_type", itp_type_body_armor),
          (this_or_next|eq, ":item_type", itp_type_foot_armor),
          (this_or_next|eq, ":item_type", itp_type_hand_armor),
          (eq, ":item_type", itp_type_shield),
          (assign, ":randomness", 5),
        (try_end),
        (store_random_in_range, ":random_no", 0, 100),
        (lt, ":random_no", ":randomness"),
        (troop_remove_item, "trp_player", ":item_id"),

        (try_begin),
          (gt, ":enemy_party_no", 0),
          (party_is_active, ":enemy_party_no"),
          (party_get_slot, ":cur_loot_slot", ":enemy_party_no", slot_party_next_looted_item_slot),
          (val_add, ":cur_loot_slot", slot_party_looted_item_1),
          (party_set_slot, ":enemy_party_no", ":cur_loot_slot", ":item_id"),
          (val_sub, ":cur_loot_slot", slot_party_looted_item_1),
          (val_add, ":cur_loot_slot", slot_party_looted_item_1_modifier),
          (party_set_slot, ":enemy_party_no", ":cur_loot_slot", ":item_modifier"),
          (val_sub, ":cur_loot_slot", slot_party_looted_item_1_modifier),
          (val_add, ":cur_loot_slot", 1),
          (val_mod, ":cur_loot_slot", num_party_loot_slots),
          (party_set_slot, ":enemy_party_no", slot_party_next_looted_item_slot, ":cur_loot_slot"),
        (try_end),
      (try_end),
      (store_troop_gold, ":cur_gold", "trp_player"),
      (try_begin),
        (gt, ":cur_gold", 0),
        (store_div, ":max_lost", ":cur_gold", 4),
        (store_div, ":min_lost", ":cur_gold", 10),
        (val_max, ":max_lost", 1),
        (val_min, ":max_lost", ":cur_gold"),
        (val_min, ":min_lost", ":max_lost"),
        (try_begin),
          (eq, ":min_lost", ":max_lost"),
          (assign, ":lost_gold", ":max_lost"),
        (else_try),
          (store_random_in_range, ":lost_gold", ":min_lost", ":max_lost"),
        (try_end),
        (call_script, "script_sod_player_charge_gold", ":lost_gold"),
        (play_sound, "snd_money_paid"),
      (try_end),
  ]),
]
