SCRIPTS = [
("refresh_village_merchant_inventory",
    [
      (store_script_param_1, ":village_no"),
      (party_get_slot, ":merchant_troop", ":village_no", slot_town_elder),
      (party_get_slot, ":village_population", ":village_no", slot_center_sod_local_population),
      (party_get_slot, ":prosperity", ":village_no", slot_town_prosperity),
      (store_sub, ":pop_surplus", ":village_population", village_pop_min),
      (val_max, ":pop_surplus", 0),
      (store_sub, ":pop_range", village_pop_max, village_pop_min),
      (val_max, ":pop_range", 1),
      (store_mul, ":merchandise_factor", ":pop_surplus", 50),
      (val_div, ":merchandise_factor", ":pop_range"),
      (val_add, ":merchandise_factor", 30),
      (val_clamp, ":merchandise_factor", 20, 100),
      (val_add, ":prosperity", 10),
      (val_mul, ":merchandise_factor", ":prosperity"),
      (val_div, ":merchandise_factor", 110),
      (val_max, ":merchandise_factor", 15),
      (val_min, ":merchandise_factor", 100),
      (reset_item_probabilities, 0),
      (store_sub, ":item_to_price_slot", slot_town_trade_good_prices_begin, trade_goods_begin),
      (try_for_range, ":cur_goods", trade_goods_begin, trade_goods_end),
        (store_add, ":cur_price_slot", ":cur_goods", ":item_to_price_slot"),
        (party_get_slot, ":cur_price", ":village_no", ":cur_price_slot"),
        (assign, ":cur_probability", 100),
        (val_mul, ":cur_probability", average_price_factor),
        (val_div, ":cur_probability", ":cur_price"),
        (val_mul, ":cur_probability", average_price_factor),
        (val_div, ":cur_probability", ":cur_price"),
        (val_mul, ":cur_probability", average_price_factor),
        (val_div, ":cur_probability", ":cur_price"),
        (val_mul, ":cur_probability", average_price_factor),
        (val_div, ":cur_probability", ":cur_price"),
        (val_mul, ":cur_probability", ":merchandise_factor"),
        (val_div, ":cur_probability", 100),
        (val_max, ":cur_probability", 0),
        (set_item_probability_in_merchandise, ":cur_goods", ":cur_probability"),
      (try_end),
      (set_item_probability_in_merchandise, "itm_spice", 0),
      (set_item_probability_in_merchandise, "itm_velvet", 0),
      (troop_add_merchandise, ":merchant_troop", itp_type_goods, 3),
      (troop_ensure_inventory_space, ":merchant_troop", 80),

      #MORDACHAI - changed it from 3000 to 1000 per point of prosperity (3k for a village?!  get serious!)
      #Adding 1 prosperity to the village while reducing each 1000 gold from the elder
      (store_troop_gold, ":gold", ":merchant_troop"),
      (try_begin),
        (gt, ":gold", 1000),
        (store_div, ":prosperity_added", ":gold", 1000),
        (store_mul, ":gold_removed", ":prosperity_added", 1000),
        (troop_remove_gold, ":merchant_troop", ":gold_removed"),
        (play_sound, "snd_money_paid"),
        (call_script, "script_change_center_prosperity", ":village_no", ":prosperity_added"),
      (try_end),
  ]),
]
