SCRIPTS = [
("sod_recover_protected_items_from_loot_pool",
 [
   (store_script_param_1, ":loot_pool"),

   (assign, ":recovered", 0),
   (assign, ":stranded", 0),
   (troop_get_inventory_capacity, ":pool_capacity", ":loot_pool"),
   (try_for_range, ":slot", first_inventory_slot, ":pool_capacity"),
     (troop_get_inventory_slot, ":item_no", ":loot_pool", ":slot"),
     (ge, ":item_no", 0),
     (call_script, "script_sod_auto_loot_item_is_protected", ":item_no"),
     (eq, reg0, 1),
     (store_free_inventory_capacity, ":player_space", "trp_player"),
     (try_begin),
       (gt, ":player_space", 0),
       (call_script, "script_sod_transfer_inventory_slot_to_free_inventory", ":loot_pool", "trp_player", ":slot", 1),
       (eq, reg0, 1),
       (val_add, ":recovered", 1),
     (else_try),
       (val_add, ":stranded", 1),
     (try_end),
   (try_end),

   (try_begin),
     (gt, ":recovered", 0),
     (assign, reg21, ":recovered"),
     (display_message, "@Recovered {reg21} protected item(s) from the loot pool.", 0xD6B15E),
   (try_end),
   (try_begin),
     (gt, ":stranded", 0),
     (assign, reg22, ":stranded"),
     (display_message, "@{reg22} protected item(s) remain in the loot pool because your inventory is full.", 0xFFCC66),
   (try_end),

   (assign, reg0, ":recovered"),
   (assign, reg1, ":stranded"),
 ]),
]
