SCRIPTS = [
("sod_auto_loot_item_is_protected",
 [
   (store_script_param_1, ":item_no"),
   (assign, reg0, 0),
   (try_begin),
     (gt, ":item_no", 0),
     (item_get_slot, ":artifact_flags", ":item_no", slot_item_artifact_flags),
     (gt, ":artifact_flags", 0),
     (assign, reg0, 1),
   (else_try),
     (item_slot_eq, ":item_no", slot_item_sod_auto_loot_protected, 1),
     (assign, reg0, 1),
   (else_try),
     (is_between, ":item_no", books_begin, books_end),
     (assign, reg0, 1),
   (else_try),
     (this_or_next|eq, ":item_no", "itm_book_administration"),
     (this_or_next|eq, ":item_no", "itm_book_chirurgeons_ledger"),
     (this_or_next|eq, ":item_no", "itm_book_anatomy_of_mercy"),
     (this_or_next|eq, ":item_no", "itm_book_drill_camp_company"),
     (this_or_next|eq, ":item_no", "itm_book_roads_before_armies"),
     (this_or_next|eq, ":item_no", "itm_book_quartermasters_burden"),
     (this_or_next|eq, ":item_no", "itm_book_embassies_in_wartime"),
     (eq, ":item_no", "itm_book_pathfinding_reference"),
     (assign, reg0, 1),
   (else_try),
     (is_between, ":item_no", trade_goods_begin, trade_goods_end),
     (assign, reg0, 1),
   (try_end),
 ]),
]
