SCRIPTS = [
("update_trade_good_price_for_party",
    [
      (store_script_param, ":center_no", 1),
      (assign, ":merchant_troop", -1),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (party_get_slot, ":merchant_troop", ":center_no", slot_town_merchant),
      (else_try),
        (is_between, ":center_no", villages_begin, villages_end),
        (party_get_slot, ":merchant_troop", ":center_no", slot_town_elder),
      (try_end),
      (party_get_slot, ":center_prosperity", ":center_no", slot_town_prosperity),
      (party_get_slot, ":center_health", ":center_no", slot_center_sod_local_health),
      (assign, ":center_population", 0),
      (try_begin),
        (this_or_next|is_between, ":center_no", towns_begin, towns_end),
        (is_between, ":center_no", villages_begin, villages_end),
        (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
      (else_try),
        (assign, ":center_population", 20),
      (try_end),
      (val_max, ":center_population", 1),
      (party_get_slot, ":food_store", ":center_no", slot_party_food_store),
      (call_script, "script_center_get_food_consumption", ":center_no"),
      (assign, ":weekly_food_consumption", reg0),
      (val_max, ":weekly_food_consumption", 1),
      (call_script, "script_center_get_food_store_limit", ":center_no"),
      (assign, ":food_store_limit", reg0),
      (store_mul, ":food_buffer", ":weekly_food_consumption", 2),
      (store_mul, ":food_capacity_comfort", ":food_store_limit", 3),
      (val_div, ":food_capacity_comfort", 5),
      (store_mul, ":food_capacity_shortage", ":food_store_limit", 1),
      (val_div, ":food_capacity_shortage", 5),
      (try_begin),
        (lt, ":food_capacity_comfort", ":food_buffer"),
        (assign, ":food_capacity_comfort", ":food_buffer"),
      (try_end),
      (try_begin),
        (lt, ":food_capacity_shortage", ":weekly_food_consumption"),
        (assign, ":food_capacity_shortage", ":weekly_food_consumption"),
      (try_end),
      (assign, ":supply_bonus", 0),
      (try_begin),
        (ge, ":food_store", ":food_capacity_comfort"),
          (assign, ":supply_bonus", 12),
      (else_try),
        (lt, ":food_store", ":food_capacity_shortage"),
          (assign, ":supply_bonus", -12),
      (else_try),
          (assign, ":supply_bonus", 4),
      (try_end),
      (assign, ":stock_pressure_scale", 100),
      (try_begin),
        (is_between, ":center_no", towns_begin, towns_end),
        (store_div, ":market_depth_bonus", ":center_population", 350),
        (assign, ":stock_pressure_scale", 95),
        (val_sub, ":stock_pressure_scale", ":market_depth_bonus"),
      (else_try),
        (is_between, ":center_no", villages_begin, villages_end),
        (store_div, ":market_depth_bonus", ":center_population", 160),
        (assign, ":stock_pressure_scale", 105),
        (val_sub, ":stock_pressure_scale", ":market_depth_bonus"),
      (try_end),
      (val_clamp, ":stock_pressure_scale", 70, 115),
      (assign, ":scarcity_score", 0),
      (assign, ":abundance_score", 0),
      (assign, ":critical_shortage_score", 0),
      (call_script, "script_sod_get_center_goods_market_profile", ":center_no"),
      (assign, ":goods_food_balance", reg0),
      (assign, ":goods_raw_balance", reg1),
      (assign, ":goods_strategic_balance", reg2),
      (assign, ":goods_luxury_flow", reg3),
      (assign, ":goods_scarcity_pressure", reg4),
      (assign, ":goods_trade_willingness", reg5),
      (assign, ":goods_liquidity_pressure", reg6),
      (call_script, "script_sod_center_public_health_compute_causes", ":center_no"),
      (assign, ":disease_risk", reg4),
      (party_get_slot, ":outbreak", ":center_no", slot_center_health_outbreak_type),
      (party_get_slot, ":quarantine", ":center_no", slot_center_health_quarantine),
      (party_get_slot, ":aftermath", ":center_no", slot_center_health_recent_aftermath),
      (try_for_range, ":cur_good", trade_goods_begin, trade_goods_end),
        (store_sub, ":cur_good_slot", ":cur_good", trade_goods_begin),
        (val_add, ":cur_good_slot", slot_town_trade_good_productions_begin),
        (store_sub, ":cur_good_price_slot", ":cur_good", trade_goods_begin),
        (val_add, ":cur_good_price_slot", slot_town_trade_good_prices_begin),
        (party_get_slot, ":production", ":center_no", ":cur_good_slot"),
        (party_get_slot, ":cur_price", ":center_no", ":cur_good_price_slot"),
        (assign, ":stock_amount", 0),
        (try_begin),
          (gt, ":merchant_troop", 0),
          (call_script, "script_get_troop_item_amount", ":merchant_troop", ":cur_good"),
          (assign, ":stock_amount", reg0),
        (try_end),
        # Bigger populations and richer centers need deeper shelves to feel "well supplied".
        (assign, ":desired_stock", 1),
        (try_begin),
          (is_between, ":center_no", towns_begin, towns_end),
          (store_div, ":pop_stock_need", ":center_population", 225),
          (val_add, ":desired_stock", 2),
        (else_try),
          (store_div, ":pop_stock_need", ":center_population", 90),
          (val_add, ":desired_stock", 1),
        (try_end),
        (val_add, ":desired_stock", ":pop_stock_need"),
        (store_div, ":prosperity_stock_need", ":center_prosperity", 25),
        (val_add, ":desired_stock", ":prosperity_stock_need"),
        (try_begin),
          (gt, ":supply_bonus", 0),
          (val_add, ":desired_stock", 1),
        (else_try),
          (lt, ":supply_bonus", 0),
          (val_sub, ":desired_stock", 1),
        (try_end),
        (val_clamp, ":desired_stock", 1, 13),
        (store_sub, ":stock_gap", ":desired_stock", ":stock_amount"),
        (store_sub, ":stock_surplus", ":stock_amount", ":desired_stock"),
        (assign, ":stock_price_shift", 0),
        (try_begin),
          (ge, ":stock_gap", 4),
          (assign, ":stock_price_shift", 16),
          (val_add, ":scarcity_score", 2),
          (val_add, ":critical_shortage_score", 1),
        (else_try),
          (ge, ":stock_gap", 2),
          (assign, ":stock_price_shift", 10),
          (val_add, ":scarcity_score", 1),
        (else_try),
          (ge, ":stock_gap", 1),
          (assign, ":stock_price_shift", 5),
          (val_add, ":scarcity_score", 1),
        (else_try),
          (ge, ":stock_surplus", 5),
          (assign, ":stock_price_shift", -8),
          (val_add, ":abundance_score", 2),
        (else_try),
          (ge, ":stock_surplus", 2),
          (assign, ":stock_price_shift", -4),
          (val_add, ":abundance_score", 1),
        (try_end),
        (val_mul, ":stock_price_shift", ":stock_pressure_scale"),
        (val_div, ":stock_price_shift", 100),
        (assign, ":profile_price_shift", 0),
        (try_begin),
          (this_or_next|eq, ":cur_good", "itm_grain"),
          (this_or_next|eq, ":cur_good", "itm_flour"),
          (this_or_next|eq, ":cur_good", "itm_bread"),
          (this_or_next|eq, ":cur_good", "itm_cabbages"),
          (this_or_next|eq, ":cur_good", "itm_apples"),
          (this_or_next|eq, ":cur_good", "itm_smoked_fish"),
          (this_or_next|eq, ":cur_good", "itm_dried_meat"),
          (this_or_next|eq, ":cur_good", "itm_cattle_meat"),
          (this_or_next|eq, ":cur_good", "itm_pork"),
          (this_or_next|eq, ":cur_good", "itm_chicken"),
          (this_or_next|eq, ":cur_good", "itm_cheese"),
          (this_or_next|eq, ":cur_good", "itm_butter"),
          (this_or_next|eq, ":cur_good", "itm_honey"),
          (this_or_next|eq, ":cur_good", "itm_sausages"),
          (this_or_next|eq, ":cur_good", "itm_ale"),
          (eq, ":cur_good", "itm_wine"),
          (try_begin),
            (lt, ":goods_food_balance", 0),
            (store_mul, ":group_price_pressure", ":goods_food_balance", -1),
            (val_div, ":group_price_pressure", 10),
            (val_add, ":profile_price_shift", ":group_price_pressure"),
          (else_try),
            (gt, ":goods_food_balance", 30),
            (store_div, ":group_price_relief", ":goods_food_balance", 18),
            (val_sub, ":profile_price_shift", ":group_price_relief"),
          (try_end),
        (else_try),
          (this_or_next|eq, ":cur_good", "itm_wool"),
          (this_or_next|eq, ":cur_good", "itm_pottery"),
          (this_or_next|eq, ":cur_good", "itm_linen"),
          (eq, ":cur_good", "itm_furs"),
          (try_begin),
            (lt, ":goods_raw_balance", 0),
            (store_mul, ":group_price_pressure", ":goods_raw_balance", -1),
            (val_div, ":group_price_pressure", 12),
            (val_add, ":profile_price_shift", ":group_price_pressure"),
          (else_try),
            (gt, ":goods_raw_balance", 30),
            (store_div, ":group_price_relief", ":goods_raw_balance", 14),
            (val_sub, ":profile_price_shift", ":group_price_relief"),
          (try_end),
        (else_try),
          (this_or_next|eq, ":cur_good", "itm_salt"),
          (this_or_next|eq, ":cur_good", "itm_iron"),
          (this_or_next|eq, ":cur_good", "itm_oil"),
          (eq, ":cur_good", "itm_tools"),
          (try_begin),
            (lt, ":goods_strategic_balance", 0),
            (store_mul, ":group_price_pressure", ":goods_strategic_balance", -1),
            (val_div, ":group_price_pressure", 8),
            (val_add, ":profile_price_shift", ":group_price_pressure"),
          (else_try),
            (gt, ":goods_strategic_balance", 20),
            (store_div, ":group_price_relief", ":goods_strategic_balance", 16),
            (val_sub, ":profile_price_shift", ":group_price_relief"),
          (try_end),
        (else_try),
          (this_or_next|eq, ":cur_good", "itm_spice"),
          (eq, ":cur_good", "itm_velvet"),
          (store_div, ":luxury_price_support", ":goods_liquidity_pressure", 40),
          (val_add, ":profile_price_shift", ":luxury_price_support"),
          (try_begin),
            (gt, ":goods_luxury_flow", 30),
            (store_div, ":luxury_surplus_relief", ":goods_luxury_flow", 15),
            (val_sub, ":profile_price_shift", ":luxury_surplus_relief"),
          (try_end),
        (try_end),
        (store_div, ":scarcity_price_pressure", ":goods_scarcity_pressure", 25),
        (val_add, ":profile_price_shift", ":scarcity_price_pressure"),
        (store_sub, ":willingness_shortfall", 85, ":goods_trade_willingness"),
        (val_max, ":willingness_shortfall", 0),
        (val_div, ":willingness_shortfall", 10),
        (val_add, ":profile_price_shift", ":willingness_shortfall"),
        (val_clamp, ":profile_price_shift", -18, 31),
        (assign, ":change_factor", 0),
        (assign, ":random_change", 0),
        (try_begin),
          (lt, ":production", 0), #demand is greater than supply
          (store_mul, ":change_factor", ":production", -3), #price will be increased by this factor
          (val_max, ":change_factor", 1),
          (store_random_in_range, ":random_change", 0, ":change_factor"),
          (val_add, ":cur_price", ":random_change"),
        (else_try),
          (gt, ":production", 0),
          (store_mul, ":change_factor", ":production", 3), #price will be decreased by this factor
          (val_max, ":change_factor", 1),
          (store_random_in_range, ":random_change", 0, ":change_factor"),
          (val_sub, ":cur_price", ":random_change"),
        (try_end),
        # Move price towards average by 2%, then bias with real market stock pressure.
        (store_sub, ":price_difference", ":cur_price", average_price_factor),
        (val_mul, ":price_difference", 97),
        (val_div, ":price_difference", 100),
        (store_add, ":new_price", average_price_factor, ":price_difference"),
        (val_add, ":new_price", ":stock_price_shift"),
        (val_add, ":new_price", ":profile_price_shift"),
        (val_clamp, ":new_price", minimum_price_factor, maximum_price_factor),
        (party_set_slot, ":center_no", ":cur_good_price_slot", ":new_price"),
        # Restocking now follows local carrying capacity: more people = more throughput and demand.
        (try_begin),
          (gt, ":merchant_troop", 0),
          (assign, ":restock_score", ":center_prosperity"),
          (val_add, ":restock_score", ":center_health"),
          (val_div, ":restock_score", 4),
          (store_div, ":population_throughput", ":center_population", 150),
          (val_add, ":restock_score", ":population_throughput"),
          (val_add, ":restock_score", ":supply_bonus"),
          (try_begin),
            (gt, ":outbreak", sod_outbreak_none),
            (val_sub, ":restock_score", 20),
          (else_try),
            (gt, ":quarantine", 0),
            (val_sub, ":restock_score", 12),
          (else_try),
            (ge, ":disease_risk", 65),
            (val_sub, ":restock_score", 8),
          (else_try),
            (gt, ":aftermath", 0),
            (val_sub, ":restock_score", 5),
          (try_end),
          (try_begin),
            (ge, ":stock_gap", 5),
            (val_add, ":restock_score", 18),
          (else_try),
            (ge, ":stock_gap", 3),
            (val_add, ":restock_score", 10),
          (else_try),
            (ge, ":stock_gap", 1),
            (val_add, ":restock_score", 4),
          (try_end),
          (val_clamp, ":restock_score", 0, 85),
          (try_begin),
            (ge, ":stock_gap", 3),
            (store_random_in_range, ":restock_roll", 0, 100),
            (lt, ":restock_roll", ":restock_score"),
            (troop_add_item, ":merchant_troop", ":cur_good", 0),
            (try_begin),
              (gt, ":restock_score", 35),
              (ge, ":stock_gap", 5),
              (store_random_in_range, ":extra_roll", 0, 100),
              (lt, ":extra_roll", 35),
              (troop_add_item, ":merchant_troop", ":cur_good", 0),
            (try_end),
          (else_try),
            (ge, ":stock_gap", 1),
            (store_random_in_range, ":restock_roll", 0, 100),
            (lt, ":restock_roll", ":restock_score"),
            (troop_add_item, ":merchant_troop", ":cur_good", 0),
          (else_try),
            (ge, ":stock_surplus", 5),
            (assign, ":trim_score", 25),
            (val_add, ":trim_score", ":stock_surplus"),
            (try_begin),
              (ge, ":stock_surplus", 8),
              (val_add, ":trim_score", 12),
            (else_try),
              (ge, ":stock_surplus", 5),
              (val_add, ":trim_score", 6),
            (else_try),
              (ge, ":stock_surplus", 2),
              (val_add, ":trim_score", 3),
            (try_end),
            (try_begin),
              (lt, ":center_prosperity", 40),
              (val_add, ":trim_score", 10),
            (try_end),
            (try_begin),
              (lt, ":supply_bonus", 0),
              (val_add, ":trim_score", 10),
            (try_end),
            (val_clamp, ":trim_score", 0, 70),
            (store_random_in_range, ":trim_roll", 0, 100),
            (lt, ":trim_roll", ":trim_score"),
            (troop_remove_item, ":merchant_troop", ":cur_good"),
          (try_end),
        (try_end),
      (try_end),
      (try_begin),
        (gt, ":merchant_troop", 0),
        (troop_ensure_inventory_space, ":merchant_troop", 80),
        (troop_sort_inventory, ":merchant_troop"),
      (try_end),
      # Feed real shelf conditions back into the center economy.
      (try_begin),
        (gt, ":critical_shortage_score", 5),
        (store_random_in_range, ":economy_roll", 0, 100),
        (lt, ":economy_roll", 65),
        (call_script, "script_change_center_prosperity", ":center_no", -1),
      (else_try),
        (gt, ":scarcity_score", 8),
        (store_random_in_range, ":economy_roll", 0, 100),
        (lt, ":economy_roll", 40),
        (call_script, "script_change_center_prosperity", ":center_no", -1),
      (else_try),
        (gt, ":abundance_score", ":scarcity_score"),
        (store_sub, ":abundance_margin", ":abundance_score", ":scarcity_score"),
        (store_add, ":growth_chance", 12, ":abundance_margin"),
        (try_begin),
          (gt, ":supply_bonus", 0),
          (val_add, ":growth_chance", 8),
        (try_end),
        (val_clamp, ":growth_chance", 0, 55),
        (store_random_in_range, ":economy_roll", 0, 100),
        (lt, ":economy_roll", ":growth_chance"),
        (call_script, "script_change_center_prosperity", ":center_no", 1),
      (try_end),
      (try_begin),
        (gt, ":abundance_score", 10),
        (ge, ":food_store", ":food_capacity_shortage"),
        (store_random_in_range, ":food_roll", 0, 100),
        (lt, ":food_roll", 45),
        (store_div, ":food_bonus", ":abundance_score", 3),
        (val_add, ":food_bonus", 1),
        (call_script, "script_sod_center_apply_food_delta", ":center_no", ":food_bonus"),
        (assign, ":food_store", reg0),
      (else_try),
        (gt, ":critical_shortage_score", 4),
        (store_random_in_range, ":food_roll", 0, 100),
        (lt, ":food_roll", 50),
        (store_div, ":food_penalty", ":critical_shortage_score", 2),
        (val_add, ":food_penalty", 1),
        (store_mul, ":food_delta", ":food_penalty", -1),
        (call_script, "script_sod_center_apply_food_delta", ":center_no", ":food_delta"),
        (assign, ":food_store", reg0),
      (try_end),
  ]),
]
