MENUS = [
(
    "event_14", mnf_disable_all_keys,
    "Deadly disease strikes {s1}. There is nothing we can do.",
    "none",
    [
      (assign, ":stop", 9999),
      (try_for_range, ":unused", 0, ":stop"),
        (store_random_party_in_range, "$temp", centers_begin, centers_end),
        (neg|party_slot_eq, "$temp", slot_party_type, spt_castle),
        (party_slot_eq, "$temp", slot_town_lord, "trp_player"),
        (assign, ":stop", ":unused"),
        (str_store_party_name, s1, "$temp"),
      (try_end),
    ],
    [
      ("choice_14_1", [], "That's terrible!",
        [
          (str_store_party_name_link, s1, "$temp"),
          (call_script, "script_change_center_prosperity", "$temp", -5),
          (val_sub, "$g_sod_global_health", 1),
          (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
          (assign, ":temp_center_population", ":center_population"),
          (val_div, ":temp_center_population", 10),
          (store_mul, ":population_delta", ":temp_center_population", -1),
          (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
          (call_script, "script_sod_center_apply_health_delta", "$temp", -10),
          (display_message, "@Both population and health of {s1} decreases. Economy of {s1} also suffered. The disease might have spread to other parts of Your kingdom.", quest_fail_color),
          (change_screen_return),
        ]
      ),
      ("choice_14_2", [], "At least help the survivors. =500 denars=",
        [
          (str_store_party_name_link, s1, "$temp"),
          (store_troop_gold, ":gold", "trp_player"),
          (val_sub, "$g_sod_global_health", 1),
          (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
          (assign, ":temp_center_population", ":center_population"),
          (val_div, ":temp_center_population", 10),
          (store_mul, ":population_delta", ":temp_center_population", -1),
          (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
          (call_script, "script_sod_center_apply_health_delta", "$temp", -10),
          (try_begin),
            (ge, ":gold", 500),
            (call_script, "script_sod_player_charge_gold", 500),
            (call_script, "script_change_player_relation_with_center", "$temp", 10),
            (display_message, "@Both population and health of {s1} decreases. People are grateful for Your help. The disease might have spread to other parts of Your kingdom.", quest_success_color),
          (else_try),
            (display_message, "@You don't have enough gold. How embarrassing! Population, health and economy of {s1} suffer. The disease might have spread to other parts of your kingdom.", quest_fail_color),
            (call_script, "script_change_troop_renown", "trp_player", -2),
            (call_script, "script_change_center_prosperity", "$temp", -5),
          (try_end),
          (change_screen_return),
        ]
       ),
      ]
  ),
]
