MENUS = [
(
    "event_13", mnf_disable_all_keys,
    "People in {s1} are suffering from an unknown but deadly disease. What should we do, my liege?",
    "none",
    [
      (assign, "$temp", -1),
      (str_store_string, s68, "@one of your fiefs"),
      (assign, ":stop", 0),
      (try_for_range, ":unused", 0, 9999),
        (eq, ":stop", 0),
        (store_random_party_in_range, "$temp", centers_begin, centers_end),
        (neg|party_slot_eq, "$temp", slot_party_type, spt_castle),
        (party_slot_eq, "$temp", slot_town_lord, "trp_player"),
        (assign, ":stop", 1),
        (str_store_party_name, s68, "$temp"),
      (try_end),
      (str_store_string_reg, s1, s68),
    ],
    [
      ("choice_13_1", [(is_between, "$temp", centers_begin, centers_end)], "Summon physicians from across the realm for 1000 denars.",
        [
          (str_store_party_name_link, s1, "$temp"),
          (store_troop_gold, ":gold", "trp_player"),
          (try_begin),
            (ge, ":gold", 1000),
            (call_script, "script_sod_player_charge_gold", 1000),
            (val_add, "$g_sod_global_health", 1),
            (display_message, "@Your decisive response improves public health across the realm.", quest_success_color),
          (else_try),
            (display_message, "@You don't have enough gold. Population and health in {s1} are falling.", quest_fail_color),
            (call_script, "script_change_troop_renown", "trp_player", -2),
            (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
            (assign, ":temp_center_population", ":center_population"),
            (val_div, ":temp_center_population", 10),
            (store_mul, ":population_delta", ":temp_center_population", -1),
            (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
            (call_script, "script_sod_center_apply_health_delta", "$temp", -20),
            (val_sub, "$g_sod_global_health", 1),
          (try_end),
          (change_screen_return),
        ]
      ),
      ("choice_13_2", [(is_between, "$temp", centers_begin, centers_end)], "Quarantine the settlement.",
        [
          (str_store_party_name_link, s1, "$temp"),
          (call_script, "script_change_player_relation_with_center", "$temp", -10),
          (call_script, "script_change_center_prosperity", "$temp", -5),
          (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
          (assign, ":temp_center_population", ":center_population"),
          (val_div, ":temp_center_population", 10),
          (store_mul, ":population_delta", ":temp_center_population", -1),
          (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
          (display_message, "@Many people have died. {s1} is ruined and your reputation is shattered there but disease will not spread.", quest_fail_color),
          (change_screen_return),
        ]
      ),
      ("choice_13_3", [(is_between, "$temp", centers_begin, centers_end)], "Do nothing.",
        [
          (str_store_party_name_link, s1, "$temp"),
          (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
          (assign, ":temp_center_population", ":center_population"),
          (val_div, ":temp_center_population", 10),
          (store_mul, ":population_delta", ":temp_center_population", -1),
          (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
          (call_script, "script_sod_center_apply_health_delta", "$temp", -20),
          (call_script, "script_change_center_prosperity", "$temp", -5),
          (val_sub, "$g_sod_global_health", 1),
          (display_message, "@Many people have died in {s1}. The disease remains and may spread through the realm.", quest_fail_color),
          (change_screen_return),
        ]
      ),
      ("choice_13_no_center", [(neg|is_between, "$temp", centers_begin, centers_end)], "Continue.",
        [
          (display_message, "@No affected fief could be found. The report is dismissed.", quest_fail_color),
          (change_screen_return),
        ]
      ),
    ]
  ),
]
