MENUS = [
(
    "event_17", mnf_disable_all_keys,
    "Excellent global health policy causes population boom in whole kingdom.",
    "none",
    [
      (assign, ":stop", 0),
      (try_for_range, ":unused", 0, 9999),
        (eq, ":stop", 0),
        (store_random_party_in_range, "$temp", centers_begin, centers_end),
        (neg|party_slot_eq, "$temp", slot_party_type, spt_castle),
        (party_slot_eq, "$temp", slot_town_lord, "trp_player"),
        (assign, ":stop", 1),
        (str_store_party_name, s1, "$temp"),
      (try_end),
    ],
    [
      ("choice_17_1", [], "Excellent!",
       [
        (try_for_range, ":center_no", centers_begin, centers_end),
        (neg|party_slot_eq, ":center_no", slot_party_type, spt_castle),
        (party_slot_eq, ":center_no", slot_town_lord, "trp_player"),
        (val_add, "$g_sod_global_health", 1),
            (try_begin),
                (party_slot_eq, ":center_no", slot_party_type, spt_village),
                (store_random_in_range, ":rand", 20, 50),
                (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
                (val_add, ":center_population", ":rand"),
                (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
                (party_get_slot, ":center_health", "$temp", slot_center_sod_local_health),
                (val_add, ":center_health", 10),
                (party_set_slot, "$temp", slot_center_sod_local_health, ":center_health"),
            (else_try),
                (store_random_in_range, ":rand", 50, 150),
                (party_get_slot, ":center_population", ":center_no", slot_center_sod_local_population),
                (val_add, ":center_population", ":rand"),
                (party_set_slot, ":center_no", slot_center_sod_local_population, ":center_population"),
                (party_get_slot, ":center_health", "$temp", slot_center_sod_local_health),
                (val_add, ":center_health", 10),
                (party_set_slot, "$temp", slot_center_sod_local_health, ":center_health"),
            (try_end),
        (try_end),
        (display_message, "@All Your fiefs experience population boom.", quest_success_color),
        (change_screen_return),
        ]
       ),
      ]
  ),
]
