MENUS = [
(
    "event_12", mnf_disable_all_keys,
    "{s1} has been infected by a group of rats carrying the black death. The population is panicking. What are your orders, my liege?",
    "none",
    [
      (assign, ":stop", 0),
      (try_for_range, ":unused", 0, 9999),
        (eq, ":stop", 0),
        (store_random_party_in_range, "$temp", centers_begin, centers_end),
        (neg|party_slot_eq, "$temp", slot_party_type, spt_castle),
        (party_slot_eq, "$temp", slot_town_lord, "trp_player"),
        (assign, ":stop", 1),
        (str_store_party_name, s1, "$temp"),
      (try_end),
    ],
    [
      ("choice_12_1", [], "Hire group of professional rat exterminators for 500 denars.",
      [
        (store_troop_gold, ":gold", "trp_player"),
        (str_store_party_name_link, s1, "$temp"),
        (try_begin),
          (ge, ":gold", 500),
          (call_script, "script_sod_player_charge_gold", 500),
          (val_add, "$g_sod_global_health", 1),
          (display_message, "@Good example causes health in Your kingdom to improve.", quest_success_color),
        (else_try),
          (display_message, "@You don't have enough gold. How embarrassing! Both population and health in {s1} are falling.", quest_fail_color),
          (call_script, "script_change_troop_renown", "trp_player", -2),
          (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
          (assign, ":temp_center_population", ":center_population"),
          (val_div, ":temp_center_population", 10),
          (store_mul, ":population_delta", ":temp_center_population", -1),
          (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
          (call_script, "script_sod_center_apply_health_delta", "$temp", -20),
          (val_sub, "$g_sod_global_health", 1),
        (try_end),
        (change_screen_return),
      ]
      ),
      ("choice_12_2", [], "Cleanse it with fire.",
      [
        (str_store_party_name_link, s1, "$temp"),
        (call_script, "script_change_player_relation_with_center", "$temp", -10),
        (call_script, "script_change_center_prosperity", "$temp", -5),
        (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
        (assign, ":temp_center_population", ":center_population"),
        (val_div, ":temp_center_population", 10),
        (store_mul, ":population_delta", ":temp_center_population", -1),
        (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
        (display_message, "@Many people have died. {s1} is ruined and your reputation is shattered there but disease will not spread.", quest_fail_color),
        (change_screen_return),
      ]
      ),
      ("choice_12_3", [], "So what?",
      [
        (str_store_party_name_link, s1, "$temp"),
        (party_get_slot, ":center_population", "$temp", slot_center_sod_local_population),
        (assign, ":temp_center_population", ":center_population"),
        (val_div, ":temp_center_population", 10),
        (store_mul, ":population_delta", ":temp_center_population", -1),
        (call_script, "script_sod_center_apply_population_delta", "$temp", ":population_delta"),
        (call_script, "script_sod_center_apply_health_delta", "$temp", -20),
        (val_sub, "$g_sod_global_health", 1),
        (display_message, "@Many people have died in {s1}. Disease is still present and may spread throughout whole kingdom!", quest_fail_color),
        (change_screen_return),
      ]
    ),
  ]
  ),
]
