SIMPLE_TRIGGERS = [
(0.5, [(check_quest_active, "qst_move_cattle_herd"),
         (neg|check_quest_concluded, "qst_move_cattle_herd"),
         (quest_get_slot, ":target_party", "qst_move_cattle_herd", slot_quest_target_party),
         (quest_get_slot, ":target_center", "qst_move_cattle_herd", slot_quest_target_center),
         (gt, ":target_party", 0),
         (neq, ":target_party", "p_main_party"),
         (party_is_active, ":target_party"),
         (party_slot_eq, ":target_party", slot_party_type, spt_cattle_herd),
         (store_distance_to_party_from_party, ":dist", ":target_party", ":target_center"),
         (lt, ":dist", 3),
         (remove_party, ":target_party"),
         (call_script, "script_succeed_quest", "qst_move_cattle_herd"),
    ]),
]
