SIMPLE_TRIGGERS = [
(0,
   [
     (troop_slot_ge, "trp_notification_menu_types", 0, 1),
     (troop_get_slot, ":menu_type", "trp_notification_menu_types", 0),
     (troop_get_slot, "$g_notification_menu_var1", "trp_notification_menu_var1", 0),
     (troop_get_slot, "$g_notification_menu_var2", "trp_notification_menu_var2", 0),
     (jump_to_menu, ":menu_type"),
     # Keep this in lockstep with script_add_notification_menu's bounded FIFO.
     (assign, ":queue_limit", 8),
     (try_for_range, ":cur_slot", 1, ":queue_limit"),
       (store_sub, ":cur_slot_minus_one", ":cur_slot", 1),
       (troop_get_slot, ":local_temp", "trp_notification_menu_types", ":cur_slot"),
       (troop_set_slot, "trp_notification_menu_types", ":cur_slot_minus_one", ":local_temp"),
       (troop_get_slot, ":local_temp", "trp_notification_menu_var1", ":cur_slot"),
       (troop_set_slot, "trp_notification_menu_var1", ":cur_slot_minus_one", ":local_temp"),
       (troop_get_slot, ":local_temp", "trp_notification_menu_var2", ":cur_slot"),
       (troop_set_slot, "trp_notification_menu_var2", ":cur_slot_minus_one", ":local_temp"),
     (try_end),
     (store_sub, ":last_slot", ":queue_limit", 1),
     (troop_set_slot, "trp_notification_menu_types", ":last_slot", 0),
     (troop_set_slot, "trp_notification_menu_var1", ":last_slot", 0),
     (troop_set_slot, "trp_notification_menu_var2", ":last_slot", 0),
    ]),
]
