SCRIPTS = [
("get_relevant_comment_for_log_entry",
        [(store_script_param, ":log_entry_no", 1),

          (troop_get_slot, ":entry_type",            "trp_log_array_entry_type",            ":log_entry_no"),
          (troop_get_slot, ":entry_time",            "trp_log_array_entry_time",            ":log_entry_no"),
          (troop_get_slot, ":actor",                 "trp_log_array_actor",                 ":log_entry_no"),
          (troop_get_slot, ":center_object_lord",    "trp_log_array_center_object_lord",    ":log_entry_no"),
          (troop_get_slot, ":center_object_faction", "trp_log_array_center_object_faction", ":log_entry_no"),
          (troop_get_slot, ":troop_object",          "trp_log_array_troop_object",          ":log_entry_no"),
          (troop_get_slot, ":troop_object_faction",  "trp_log_array_troop_object_faction",  ":log_entry_no"),
          (troop_get_slot, ":faction_object",        "trp_log_array_faction_object",        ":log_entry_no"),

          # Some old battle/result paths can record an invalid troop object
          # for a lord-defeat entry. Those comments all interpolate {s54};
          # suppress them instead of letting lords say "unknown commander."
          (try_begin),
            (eq, ":entry_type", logent_lord_defeated_by_player),
            (neg|is_between, ":troop_object", heroes_begin, heroes_end),
            (assign, ":entry_type", -1),
          (try_end),

          (assign, ":relevance", 0),
          (assign, ":comment", -1),
          (assign, ":suggested_relation_change", 0),

          (troop_get_slot, ":reputation", "$g_talk_troop", slot_lord_reputation_type),
          (store_current_hours, ":current_time"),
          (store_sub, ":entry_hours_elapsed", ":current_time", ":entry_time"),

          #Post 0907 changes begin
          (assign, ":players_kingdom_relation", 0), ##the below is so that lords will not congratulate player on attacking neutrals
          (try_begin),
            (eq, "$cheat_mode", 1),
            (try_begin),
              (assign, reg5, ":log_entry_no"),
              (assign, reg6, ":entry_type"),
              (assign, reg8, ":entry_time"),

              (gt, "$players_kingdom", 0),
              (try_begin),
                (gt, ":troop_object_faction", 0),
                (store_relation, ":players_kingdom_relation", "$players_kingdom", ":troop_object_faction"),
                (assign, reg7, ":players_kingdom_relation"),
                (display_message, "@Event #{reg5}, type {reg6}, time {reg8}: player's kingdom relation to troop object = {reg7}", debug_color),
                (else_try),
                  (gt, ":center_object_faction", 0),
                  (store_relation, ":players_kingdom_relation", "$players_kingdom", ":center_object_faction"),
                  (assign, reg7, ":players_kingdom_relation"),
                  (display_message, "@Event #{reg5}, type {reg6}, time {reg8}: player's kingdom relation to center object faction = {reg7}", debug_color),
                  (else_try),
                    (gt, ":faction_object", 0),
                    (store_relation, ":players_kingdom_relation", "$players_kingdom", ":faction_object"),
                    (assign, reg7, ":players_kingdom_relation"),

                    (display_message, "@Event #{reg5}, type {reg6}, time {reg8}: player's kingdom relation to faction object = {reg7}", debug_color),
                    (else_try),
                      (display_message, "@Event #{reg5}, type {reg6}, time {reg8}. No relevant kingdom relation", debug_color),
                      (try_end),
                    (else_try),
                      (display_message, "@Event #{reg5}, type {reg6}, time {reg8}. Player unaffiliated", debug_color),
                      (try_end),
                    (try_end),

                    (try_begin),
                      (eq, ":entry_type", logent_game_start),
                      (eq, "$g_talk_troop_met", 0),
                      (is_between, "$g_talk_troop_faction_relation", -5, 5),
                      (is_between, "$g_talk_troop_relation", -5, 5),

                      (assign, ":relevance", 25),
                      (troop_get_slot, ":plyr_renown", "trp_player", slot_troop_renown),
                      #normal_banner_begin
					  (try_begin),
						(eq, "$g_custom_banner", 0),
						(troop_get_slot, ":banner", "trp_player", slot_troop_banner_scene_prop),
                      # custom_banner_begin
					  (else_try),
                        (troop_get_slot, ":banner", "trp_player", slot_troop_custom_banner_flag_type),
                      (try_end),
					  (store_random_in_range, ":renown_check", 100, 200),
                      (try_begin),
                        (eq, ":reputation", lrep_none),
                        (gt, "$supported_pretender", 0),
                        (assign, ":comment", "str_comment_intro_liege_affiliated"),
                      (else_try),
                        (gt, ":plyr_renown", ":renown_check"),
                        (assign, ":comment", "str_comment_intro_famous_liege"),
                        (val_add, ":comment", ":reputation"),
                      (else_try),
                        #normal_banner_begin
						(try_begin),
							(eq, "$g_custom_banner", 0),
							(gt, ":banner", 0),
						(else_try),
                        # custom_banner_begin
							(ge, ":banner", 0),
							(assign, ":comment", "str_comment_intro_noble_liege"),
							(val_add, ":comment", ":reputation"),
						(try_end),
                      (else_try),
                        (assign, ":comment", "str_comment_intro_common_liege"),
                        (val_add, ":comment", ":reputation"),
                      (try_end),
                      #Post 0907 changes end

                    (else_try),
                      (eq, ":entry_type", logent_village_raided),
                      (eq, ":actor", "trp_player"),
                      (try_begin),
                        (eq, ":center_object_lord", "$g_talk_troop"),
                        (assign, ":relevance", 200),
                        (assign, ":suggested_relation_change", -1),
                        (assign, ":comment", "str_comment_you_raided_my_village_default"),
                        (try_begin),
                          (lt, "$g_talk_troop_faction_relation", -5),
                          (this_or_next|eq, ":reputation", lrep_goodnatured),
                          (eq, ":reputation", lrep_upstanding),
                          (assign, ":comment", "str_comment_you_raided_my_village_enemy_benevolent"),
                        (else_try),
                          (lt, "$g_talk_troop_faction_relation", -5),
                          (this_or_next|eq, ":reputation", lrep_cunning),
                          (eq, ":reputation", lrep_selfrighteous),
                          (assign, ":comment", "str_comment_you_raided_my_village_enemy_coldblooded"),
                        (else_try),
                          (lt, "$g_talk_troop_faction_relation", -5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_you_raided_my_village_enemy_spiteful"),
                        (else_try),
                          (lt, "$g_talk_troop_faction_relation", -5),
                          (assign, ":comment", "str_comment_you_raided_my_village_enemy"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_you_raided_my_village_unfriendly_spiteful"),
                        (else_try),
                          (gt, "$g_talk_troop_relation", 5),
                          (assign, ":comment", "str_comment_you_raided_my_village_friendly"),
                        (try_end),
                      (try_end),

                    (else_try),
                      (eq, ":entry_type", logent_village_extorted),
                      (eq, ":actor", "trp_player"),
                      (try_begin),
                        (eq, ":center_object_lord", "$g_talk_troop"),
                        (assign, ":relevance", 30),
                        (assign, ":suggested_relation_change", -1),
                        (assign, ":comment", "str_comment_you_robbed_my_village_default"),
                        (try_begin),
                          (lt, "$g_talk_troop_faction_relation", -5),
                          (this_or_next|eq, ":reputation", lrep_cunning),
                          (eq, ":reputation", lrep_selfrighteous),
                          (assign, ":comment", "str_comment_you_robbed_my_village_enemy_coldblooded"),
                        (else_try),
                          (lt, "$g_talk_troop_faction_relation", -5),
                          (assign, ":comment", "str_comment_you_robbed_my_village_enemy"),
                        (else_try),
                          (gt, "$g_talk_troop_relation", 5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_you_robbed_my_village_friendly_spiteful"),
                        (else_try),
                          (gt, "$g_talk_troop_relation", 5),
                          (assign, ":comment", "str_comment_you_robbed_my_village_friendly"),
                        (try_end),
                      (try_end),

                    (else_try),
                      (eq, ":entry_type", logent_caravan_accosted),
                      (eq, ":actor", "trp_player"),
                      (eq, ":faction_object", "$g_talk_troop_faction"),
                      (faction_slot_eq, "$g_talk_troop_faction", slot_faction_leader, "$g_talk_troop"),
                      (assign, ":relevance", 30),
                      (assign, ":suggested_relation_change", -1),
                      (assign, ":comment", "str_comment_you_accosted_my_caravan_default"),
                      (try_begin),
                        (lt, "$g_talk_troop_faction_relation", -5),
                        (assign, ":comment", "str_comment_you_accosted_my_caravan_enemy"),
                      (try_end),

                    (else_try),
                      (eq, ":entry_type", logent_helped_peasants),
                      (eq, ":actor", "trp_player"),
                      (try_begin),
                        (eq, ":center_object_lord", "$g_talk_troop"),
                        (assign, ":relevance", 40),
                        (assign, ":suggested_relation_change", 0),
                        (try_begin),
                          (this_or_next|eq, ":reputation", lrep_goodnatured),
                          (eq, ":reputation", lrep_upstanding),
                          (assign, ":comment", "str_comment_you_helped_villagers_benevolent"),
                          (assign, ":suggested_relation_change", 1),
                        (else_try),
                          (gt, "$g_talk_troop_relation", 5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_you_helped_villagers_friendly_cruel"),
                          (assign, ":suggested_relation_change", -1),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_you_helped_villagers_unfriendly_spiteful"),
                          (assign, ":suggested_relation_change", -1),
                        (else_try),
                          (gt, "$g_talk_troop_relation", 5),
                          (assign, ":comment", "str_comment_you_helped_villagers_friendly"),
                        (else_try),
                          (this_or_next|eq, ":reputation", lrep_selfrighteous),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_you_helped_villagers_cruel"),
                          (assign, ":suggested_relation_change", -1),
                        (else_try),
                          (assign, ":comment", "str_comment_you_helped_villagers_default"),
                        (try_end),
                      (try_end),

                      ###Combat events
                    (else_try),
                      (eq, ":entry_type", logent_castle_captured_by_player),
                      (try_begin),
                        (eq, ":center_object_lord", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_captured_my_castle_enemy_spiteful"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":center_object_lord", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_goodnatured),
                        (assign, ":comment", "str_comment_you_captured_my_castle_enemy_chivalrous"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":center_object_lord", "$g_talk_troop"),
                        (assign, ":comment", "str_comment_you_captured_my_castle_enemy"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_captured_a_castle_allied_spiteful"),
                        (assign, ":relevance", 75),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (gt, "$g_talk_troop_relation", 5),
                        (assign, ":comment", "str_comment_you_captured_a_castle_allied_friendly"),
                        (assign, ":relevance", 75),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_captured_a_castle_allied_unfriendly_spiteful"),
                        (assign, ":relevance", 75),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (lt, "$g_talk_troop_relation", -5),
                        (assign, ":comment", "str_comment_you_captured_a_castle_allied_unfriendly"),
                        (assign, ":relevance", 75),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (assign, ":comment", "str_comment_you_captured_a_castle_allied"),
                        (assign, ":relevance", 75),
                      (try_end),

                      #Post 0907 changes begin
                    (else_try),
                      (this_or_next|eq, ":entry_type", logent_lord_defeated_by_player),
                      (eq, ":entry_type", logent_lord_helped_by_player),
                      (troop_slot_eq, "$g_talk_troop", slot_troop_present_at_event, ":log_entry_no"),
                      (try_begin),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_defeated_a_lord_unfriendly_spiteful"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (assign, ":comment", "str_comment_we_defeated_a_lord_unfriendly"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_defeated_a_lord_cruel"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (eq, ":reputation", lrep_quarrelsome),
                        (assign, ":comment", "str_comment_we_defeated_a_lord_cruel"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_we_defeated_a_lord_upstanding"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (assign, ":comment", "str_comment_we_defeated_a_lord_default"),
                        (assign, ":relevance", 150),
                      (try_end),


                    (else_try),
                      (this_or_next|eq, ":entry_type", logent_castle_captured_by_player),
                      (eq, ":entry_type", logent_player_participated_in_siege),
                      (troop_slot_eq, "$g_talk_troop", slot_troop_present_at_event, ":log_entry_no"),
                      (try_begin),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_fought_in_siege_unfriendly_spiteful"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (assign, ":comment", "str_comment_we_fought_in_siege_unfriendly"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_fought_in_siege_cruel"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (eq, ":reputation", lrep_quarrelsome),
                        (assign, ":comment", "str_comment_we_fought_in_siege_quarrelsome"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_we_fought_in_siege_upstanding"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (assign, ":comment", "str_comment_we_fought_in_siege_default"),
                        (assign, ":relevance", 150),
                      (try_end),


                    (else_try),
                      (eq, ":entry_type", logent_player_participated_in_major_battle),
                      (troop_slot_eq, "$g_talk_troop", slot_troop_present_at_event, ":log_entry_no"),
                      (try_begin),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_fought_in_major_battle_unfriendly_spiteful"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (assign, ":comment", "str_comment_we_fought_in_major_battle_unfriendly"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_fought_in_major_battle_cruel"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (eq, ":reputation", lrep_quarrelsome),
                        (assign, ":comment", "str_comment_we_fought_in_major_battle_cruel"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_we_fought_in_major_battle_upstanding"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (assign, ":comment", "str_comment_we_fought_in_major_battle_default"),
                        (assign, ":relevance", 150),
                      (try_end),


                      #Post 0907 changes end

                    (else_try),
                      (eq, ":entry_type", logent_lord_defeated_by_player),
                      (try_begin),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_goodnatured),
                        (assign, ":comment", "str_comment_you_defeated_me_enemy_chivalrous"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_debauched),
                        (eq, ":reputation", lrep_quarrelsome),
                        (assign, ":comment", "str_comment_you_defeated_me_enemy_spiteful"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (assign, ":comment", "str_comment_you_defeated_me_enemy"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_upstanding),
                        (eq, ":reputation", lrep_cunning),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy_pragmatic"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_goodnatured),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy_chivalrous"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy_spiteful"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (faction_slot_eq, "$players_kingdom", slot_faction_leader, "$g_talk_troop"),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_liege"),
                        (assign, ":relevance", 70),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_unfriendly_spiteful"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_spiteful"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_upstanding),
                        (eq, ":reputation", lrep_martial),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_unfriendly_chivalrous"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied"),
                        (assign, ":relevance", 65),
                      (try_end),


                    (else_try),
                      (eq, ":entry_type", logent_lord_defeated_by_player),
                      (try_begin),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_goodnatured),
                        (assign, ":comment", "str_comment_you_defeated_me_enemy_chivalrous"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_debauched),
                        (eq, ":reputation", lrep_quarrelsome),
                        (assign, ":comment", "str_comment_you_defeated_me_enemy_spiteful"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (assign, ":comment", "str_comment_you_defeated_me_enemy"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_upstanding),
                        (eq, ":reputation", lrep_cunning),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy_pragmatic"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_goodnatured),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy_chivalrous"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy_spiteful"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                        (assign, ":comment", "str_comment_you_defeated_my_friend_enemy"),
                        (assign, ":relevance", 85),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (faction_slot_eq, "$players_kingdom", slot_faction_leader, "$g_talk_troop"),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_liege"),
                        (assign, ":relevance", 70),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_unfriendly_spiteful"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_spiteful"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_upstanding),
                        (eq, ":reputation", lrep_martial),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied_unfriendly_chivalrous"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (assign, ":comment", "str_comment_you_defeated_a_lord_allied"),
                        (assign, ":relevance", 65),
                      (try_end),

                      #Post 0907 changes begin
                    (else_try),
                      (eq, ":entry_type", logent_lord_helped_by_player),
                      (neq, ":troop_object", "$g_talk_troop"),
                      (eq, ":troop_object_faction", "$g_talk_troop_faction"),
                      (try_begin),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_upstanding),
                        (eq, ":reputation", lrep_martial),
                        (assign, ":comment", "str_comment_you_helped_my_ally_unfriendly_chivalrous"),
                        (assign, ":relevance", 65),
                        (assign, ":suggested_relation_change", 2),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (assign, ":comment", "str_comment_you_helped_my_ally_unfriendly"),
                        (assign, ":relevance", 0),
                      (else_try),
                        (eq, ":reputation", lrep_none),
                        (assign, ":comment", "str_comment_you_helped_my_ally_liege"),
                        (assign, ":relevance", 65),
                        (assign, ":suggested_relation_change", 3),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_helped_my_ally_unfriendly_spiteful"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_helped_my_ally_spiteful"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_you_helped_my_ally_chivalrous"),
                        (assign, ":relevance", 65),
                        (assign, ":suggested_relation_change", 2),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (assign, ":comment", "str_comment_you_helped_my_ally_default"),
                      (try_end),

                      #Post 0907 changes begin
                    (else_try),
                      (eq, ":entry_type", logent_player_defeated_by_lord),
                      (troop_slot_eq, "$g_talk_troop", slot_troop_present_at_event, ":log_entry_no"),
                      (try_begin),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_were_defeated_unfriendly_spiteful"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (assign, ":comment", "str_comment_we_were_defeated_unfriendly"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_we_were_defeated_cruel"),
                        (assign, ":relevance", 150),
                      (else_try),
                        (assign, ":comment", "str_comment_we_were_defeated_default"),
                        (assign, ":relevance", 150),
                      (try_end),

                    (else_try),
                      (eq, ":entry_type", logent_player_defeated_by_lord),
                      (try_begin),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_i_defeated_you_enemy_spiteful"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (eq, ":reputation", lrep_martial),
                        (assign, ":comment", "str_comment_i_defeated_you_enemy_chivalrous"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_goodnatured),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_i_defeated_you_enemy_benevolent"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_cunning),
                        (assign, ":comment", "str_comment_i_defeated_you_enemy_coldblooded"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (assign, ":comment", "str_comment_i_defeated_you_enemy"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (assign, ":comment", "str_comment_i_defeated_you_enemy"),
                        (assign, ":relevance", 200),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (gt, "$g_talk_troop_relation", 5),
                        (assign, ":comment", "str_comment_you_were_defeated_allied_friendly_spiteful"),
                        (assign, ":relevance", 80),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_debauched),
                        (lt, "$g_talk_troop_relation", -5),
                        (assign, ":comment", "str_comment_you_were_defeated_allied_unfriendly_cruel"),
                        (assign, ":relevance", 80),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (le, "$g_talk_troop_relation", 5),
                        (assign, ":comment", "str_comment_you_were_defeated_allied_spiteful"),
                        (assign, ":relevance", 80),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (eq, ":reputation", lrep_selfrighteous),
                        (assign, ":comment", "str_comment_you_were_defeated_allied_pitiless"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (eq, ":reputation", lrep_upstanding),
                        (lt, "$g_talk_troop_relation", -15),
                        (assign, ":comment", "str_comment_you_were_defeated_allied_unfriendly_upstanding"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, "$g_talk_troop_relation", -10),
                        (assign, ":comment", "str_comment_you_were_defeated_allied_unfriendly"),
                        (assign, ":relevance", 65),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (assign, ":comment", "str_comment_you_were_defeated_allied"),
                        (assign, ":relevance", 65),
                      (try_end),
                      #Post 0907 changes end

                      #Post 0907 changes begin
                    (else_try),
                      (eq, ":entry_type", logent_player_retreated_from_lord),
                      (troop_slot_eq, "$g_talk_troop", slot_troop_present_at_event, ":log_entry_no"),
                      (try_begin),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_abandoned_us_unfriendly_spiteful"),
                        (assign, ":relevance", 150),
                        (assign, ":suggested_relation_change", -5),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (eq, ":reputation", lrep_selfrighteous),
                        (assign, ":comment", "str_comment_you_abandoned_us_unfriendly_pitiless"),
                        (assign, ":relevance", 150),
                        (assign, ":suggested_relation_change", -5),
                      (else_try),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_abandoned_us_spiteful"),
                        (assign, ":suggested_relation_change", -5),
                      (else_try),
                        (eq, ":reputation", lrep_martial),
                        (assign, ":comment", "str_comment_you_abandoned_us_chivalrous"),
                        (assign, ":relevance", 150),
                        (assign, ":suggested_relation_change", -2),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_upstanding),
                        (eq, ":reputation", lrep_goodnatured),
                        (assign, ":comment", "str_comment_you_abandoned_us_benefitofdoubt"),
                        (assign, ":relevance", 150),
                        (assign, ":suggested_relation_change", -1),
                      (else_try),
                        (assign, ":comment", "str_comment_you_abandoned_us_default"),
                        (assign, ":relevance", 150),
                        (assign, ":suggested_relation_change", -2),
                      (try_end),


                      #Post 0907 changes end

                    (else_try),
                      (this_or_next|eq, ":entry_type", logent_player_retreated_from_lord),
                      (eq, ":entry_type", logent_player_retreated_from_lord_cowardly),
                      (eq, ":troop_object", "$g_talk_troop"),
                      (try_begin),
                        (eq, "$cheat_mode", 1),
                        (assign, reg7, ":entry_hours_elapsed"),
                        (display_message, "@Elapsed hours: {reg7}", debug_color),
                      (try_end),
                      (gt, ":entry_hours_elapsed", 2),
                      (try_begin),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_ran_from_me_enemy_spiteful"),
                        (assign, ":relevance", 25),
                      (else_try),
                        (eq, ":reputation", lrep_martial),
                        (assign, ":comment", "str_comment_you_ran_from_me_enemy_chivalrous"),
                        (assign, ":relevance", 25),
                      (else_try),
                        (this_or_next|eq, ":reputation", lrep_goodnatured),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_you_ran_from_me_enemy_benevolent"),
                        (assign, ":relevance", 25),
                      (else_try),
                        (eq, ":reputation", lrep_cunning),
                        (assign, ":comment", "str_comment_you_ran_from_me_enemy_coldblooded"),
                        (assign, ":relevance", 25),
                      (else_try),
                        (assign, ":comment", "str_comment_you_ran_from_me_enemy"),
                        (assign, ":relevance", 25),
                      (try_end),

                    (else_try),
                      (eq, ":entry_type", logent_player_retreated_from_lord_cowardly),
                      (try_begin),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (lt, "$g_talk_troop_relation", 5),
                        (eq, ":reputation", lrep_martial),
                        (assign, ":comment", "str_comment_you_ran_from_foe_allied_chivalrous"),
                        (assign, ":relevance", 80),
                        (assign, ":suggested_relation_change", -3),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_you_ran_from_foe_allied_upstanding"),
                        (assign, ":relevance", 80),
                        (assign, ":suggested_relation_change", -1),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (lt, "$g_talk_troop_relation", 5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_ran_from_foe_allied_spiteful"),
                        (assign, ":relevance", 80),
                      (try_end),

                    (else_try),
                      (eq, ":entry_type", logent_lord_defeated_but_let_go_by_player),
                      (try_begin),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_let_me_go_spiteful"),
                        (assign, ":relevance", 300),
                        (assign, ":suggested_relation_change", -15),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (ge, "$g_talk_troop_faction_relation", 0),
                        (assign, ":comment", "str_comment_you_let_me_go_default"),
                        (assign, ":relevance", 300),
                        (assign, ":suggested_relation_change", 2),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (lt, "$g_talk_troop_faction_relation", 0),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":suggested_relation_change", 5),
                        (assign, ":relevance", 300),
                        (assign, ":comment", "str_comment_you_let_me_go_enemy_chivalrous"),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (lt, "$g_talk_troop_faction_relation", 0),
                        (this_or_next|eq, ":reputation", lrep_selfrighteous),
                        (eq, ":reputation", lrep_cunning),
                        (assign, ":relevance", 300),
                        (assign, ":comment", "str_comment_you_let_me_go_enemy_coldblooded"),
                      (else_try),
                        (eq, ":troop_object", "$g_talk_troop"),
                        (lt, "$g_talk_troop_faction_relation", 0),
                        (assign, ":relevance", 300),
                        (assign, ":comment", "str_comment_you_let_me_go_enemy"),
                        (assign, ":suggested_relation_change", 1),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_martial),
                        (eq, ":reputation", lrep_goodnatured),
                        (assign, ":comment", "str_comment_you_let_go_a_lord_allied_chivalrous"),
                        (assign, ":relevance", 80),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (eq, ":reputation", lrep_upstanding),
                        (assign, ":comment", "str_comment_you_let_go_a_lord_allied_upstanding"),
                        (assign, ":relevance", 80),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (this_or_next|eq, ":reputation", lrep_cunning),
                        (eq, ":reputation", lrep_selfrighteous),
                        (assign, ":comment", "str_comment_you_let_go_a_lord_allied_coldblooded"),
                        (assign, ":relevance", 80),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (lt, "$g_talk_troop_relation", -5),
                        (this_or_next|eq, ":reputation", lrep_quarrelsome),
                        (eq, ":reputation", lrep_debauched),
                        (assign, ":comment", "str_comment_you_let_go_a_lord_allied_unfriendly_spiteful"),
                        (assign, ":relevance", 80),
                      (else_try),
                        (eq, "$players_kingdom", "$g_talk_troop_faction"),
                        (lt, ":players_kingdom_relation", 0),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (assign, ":comment", "str_comment_you_let_go_a_lord_allied"),
                        (assign, ":relevance", 80),
                      (try_end),

                      #Internal faction relations

                    (else_try),
                      (eq, ":entry_type", logent_pledged_allegiance),
                      (eq, ":actor", "trp_player"),
                      (try_begin),
                        (eq, ":faction_object", "$g_talk_troop_faction"),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (assign, ":relevance", 200),
                        (try_begin),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_martial),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_martial_unfriendly"),
                        (else_try),
                          (eq, ":reputation", lrep_martial),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_martial"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_quarrelsome),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_quarrelsome_unfriendly"),
                        (else_try),
                          (eq, ":reputation", lrep_quarrelsome),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_quarrelsome"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_selfrighteous),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_selfrighteous_unfriendly"),
                        (else_try),
                          (eq, ":reputation", lrep_selfrighteous),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_selfrighteous"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_cunning),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_cunning_unfriendly"),
                        (else_try),
                          (eq, ":reputation", lrep_cunning),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_cunning"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_debauched_unfriendly"),
                        (else_try),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_debauched"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_goodnatured),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_goodnatured_unfriendly"),
                        (else_try),
                          (eq, ":reputation", lrep_goodnatured),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_goodnatured"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_upstanding),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_upstanding_unfriendly"),
                        (else_try),
                          (eq, ":reputation", lrep_upstanding),
                          (assign, ":comment", "str_comment_pledged_allegiance_allied_upstanding"),
                        (try_end),
                      (try_end),


                    (else_try),
                      (eq, ":entry_type", logent_fief_granted_village),
                      (eq, ":actor", "trp_player"),
                      (try_begin),
                        (eq, ":faction_object", "$g_talk_troop_faction"),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (eq, ":faction_object", "$players_kingdom"),
                        (assign, ":relevance", 110),
                        (try_begin),
                          (gt, "$g_talk_troop_relation", 5),
                          (this_or_next|eq, ":reputation", lrep_selfrighteous),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_our_king_granted_you_a_fief_allied_friendly_cruel"),
                        (else_try),
                          (gt, "$g_talk_troop_relation", 5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_cunning),
                          (assign, ":comment", "str_comment_our_king_granted_you_a_fief_allied_friendly_cynical"),
                        (else_try),
                          (gt, "$g_talk_troop_relation", 5),
                          (assign, ":comment", "str_comment_our_king_granted_you_a_fief_allied_friendly"),
                        (else_try),
                          (is_between, "$g_talk_troop_relation", -5, 5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_our_king_granted_you_a_fief_allied_spiteful"),
                          (assign, ":suggested_relation_change", -2),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (eq, ":reputation", lrep_upstanding),
                          (assign, ":comment", "str_comment_our_king_granted_you_a_fief_allied_unfriendly_upstanding"),
                        (else_try),
                          (lt, "$g_talk_troop_relation", -5),
                          (this_or_next|eq, ":reputation", lrep_quarrelsome),
                          (eq, ":reputation", lrep_debauched),
                          (assign, ":comment", "str_comment_our_king_granted_you_a_fief_allied_unfriendly_spiteful"),
                        (else_try),
                          (assign, ":comment", "str_comment_our_king_granted_you_a_fief_allied"),
                        (try_end),
                      (try_end),

                    (else_try),
                      (eq, ":entry_type", logent_renounced_allegiance),
                      (eq, ":actor", "trp_player"),
                      (try_begin),
                        (eq, ":faction_object", "$g_talk_troop_faction"),
                        (neq, ":troop_object", "$g_talk_troop"),
                        (try_begin),
                          (ge, "$g_talk_troop_faction_relation", 0),
                          (neq, "$g_talk_troop_faction", "$players_kingdom"),
                          (assign, ":relevance", 180),
                          (try_begin),
                            (gt, "$g_talk_troop_relation", 5),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_friendly"),
                          (else_try),
                            (ge, "$g_talk_troop_relation", 0),
                            (eq, ":reputation", lrep_goodnatured),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_friendly"),
                          (try_end),
                        (else_try),
                          (lt, "$g_talk_troop_faction_relation", 0),
                          (assign, ":relevance", 300),
                          (try_begin),
                            (ge, "$g_talk_troop_relation", 0),
                            (this_or_next|eq, ":reputation", lrep_selfrighteous),
                            (eq, ":reputation", lrep_debauched),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_unfriendly_moralizing"),
                          (else_try),
                            (gt, "$g_talk_troop_relation", 5),
                            (this_or_next|eq, ":reputation", lrep_goodnatured),
                            (eq, ":reputation", lrep_upstanding),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_enemy_friendly"),
                          (else_try),
                            (gt, "$g_talk_troop_relation", 5),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_enemy"),
                          (else_try),
                            (is_between, "$g_talk_troop_relation", -5, 5),
                            (this_or_next|eq, ":reputation", lrep_quarrelsome),
                            (eq, ":reputation", lrep_debauched),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_unfriendly_spiteful"),
                            (assign, ":suggested_relation_change", -2),
                          (else_try),
                            (lt, "$g_talk_troop_relation", -5),
                            (this_or_next|eq, ":reputation", lrep_quarrelsome),
                            (this_or_next|eq, ":reputation", lrep_selfrighteous),
                            (eq, ":reputation", lrep_debauched),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_unfriendly_spiteful"),
                          (else_try),
                            (assign, ":comment", "str_comment_you_renounced_your_alliegance_default"),
                          (try_end),
                        (try_end),
                      (try_end),


                    (try_end),
                    (assign, reg0, ":comment"),
                    (assign, reg1, ":relevance"),
                    (assign, reg2, ":suggested_relation_change"),
                ]),
]
