DIALOGS = [
[anyone, "lord_mission_accepted", [], "Then the charge is yours, {playername}. Do it cleanly if you can, decisively if you must, and do not make me regret trusting your hands.", "close_window",
   [(assign, "$g_leave_encounter", 1),
    (assign, ":start_random_quest", 1),
    (try_begin),
      (eq, "$random_quest_no", "qst_escort_lady"),
      (quest_get_slot, ":quest_object_troop", "$random_quest_no", slot_quest_object_troop),
      (troop_set_slot, ":quest_object_troop", slot_troop_cur_center, 0),
      (troop_join, ":quest_object_troop"),
    (else_try),
      (eq, "$random_quest_no", "qst_deliver_message_to_enemy_lord"),
      (call_script, "script_troop_add_gold", "trp_player", 10),
    (else_try),
      (eq, "$random_quest_no", "qst_bring_back_runaway_serfs"),
      (quest_get_slot, ":quest_giver_center", "$random_quest_no", slot_quest_giver_center),
      (quest_get_slot, ":quest_target_center", "$random_quest_no", slot_quest_target_center),
      (quest_get_slot, ":quest_target_party_template", "$random_quest_no", slot_quest_target_party_template),
      (assign, "$qst_bring_back_runaway_serfs_party_1", 0),
      (assign, "$qst_bring_back_runaway_serfs_party_2", 0),
      (assign, "$qst_bring_back_runaway_serfs_party_3", 0),
      (assign, ":spawned_serf_parties", 0),

      (set_spawn_radius, 3),
      (spawn_around_party, ":quest_giver_center", ":quest_target_party_template"),
      (assign, ":serf_party", reg0),
      (try_begin),
        (gt, ":serf_party", 0),
        (party_is_active, ":serf_party"),
        (assign, "$qst_bring_back_runaway_serfs_party_1", ":serf_party"),
        (party_set_ai_behavior, "$qst_bring_back_runaway_serfs_party_1", ai_bhvr_travel_to_party),
        (party_set_ai_object, "$qst_bring_back_runaway_serfs_party_1", ":quest_target_center"),
        (party_set_flags, "$qst_bring_back_runaway_serfs_party_1", pf_default_behavior, 0),
        (val_add, ":spawned_serf_parties", 1),
      (try_end),
      (spawn_around_party, ":quest_giver_center", ":quest_target_party_template"),
      (assign, ":serf_party", reg0),
      (try_begin),
        (gt, ":serf_party", 0),
        (party_is_active, ":serf_party"),
        (assign, "$qst_bring_back_runaway_serfs_party_2", ":serf_party"),
        (party_set_ai_behavior, "$qst_bring_back_runaway_serfs_party_2", ai_bhvr_travel_to_party),
        (party_set_ai_object, "$qst_bring_back_runaway_serfs_party_2", ":quest_target_center"),
        (party_set_flags, "$qst_bring_back_runaway_serfs_party_2", pf_default_behavior, 0),
        (val_add, ":spawned_serf_parties", 1),
      (try_end),
      (spawn_around_party, ":quest_giver_center", ":quest_target_party_template"),
      (assign, ":serf_party", reg0),
      (try_begin),
        (gt, ":serf_party", 0),
        (party_is_active, ":serf_party"),
        (assign, "$qst_bring_back_runaway_serfs_party_3", ":serf_party"),
        (party_set_ai_behavior, "$qst_bring_back_runaway_serfs_party_3", ai_bhvr_travel_to_party),
        (party_set_ai_object, "$qst_bring_back_runaway_serfs_party_3", ":quest_target_center"),
        (party_set_flags, "$qst_bring_back_runaway_serfs_party_3", pf_default_behavior, 0),
        (val_add, ":spawned_serf_parties", 1),
      (try_end),
      (try_begin),
        (lt, ":spawned_serf_parties", 3),
        (try_begin),
          (gt, "$qst_bring_back_runaway_serfs_party_1", 0),
          (party_is_active, "$qst_bring_back_runaway_serfs_party_1"),
          (remove_party, "$qst_bring_back_runaway_serfs_party_1"),
        (try_end),
        (try_begin),
          (gt, "$qst_bring_back_runaway_serfs_party_2", 0),
          (party_is_active, "$qst_bring_back_runaway_serfs_party_2"),
          (remove_party, "$qst_bring_back_runaway_serfs_party_2"),
        (try_end),
        (try_begin),
          (gt, "$qst_bring_back_runaway_serfs_party_3", 0),
          (party_is_active, "$qst_bring_back_runaway_serfs_party_3"),
          (remove_party, "$qst_bring_back_runaway_serfs_party_3"),
        (try_end),
        (assign, "$qst_bring_back_runaway_serfs_party_1", 0),
        (assign, "$qst_bring_back_runaway_serfs_party_2", 0),
        (assign, "$qst_bring_back_runaway_serfs_party_3", 0),
        (assign, ":start_random_quest", 0),
        (display_message, "@The runaway serf trail could not be placed on the map. Return later and ask again.", 0xFFCC66),
      (else_try),
        (rest_for_hours, 1, 4),
      (try_end),
    (try_end),
    (try_begin),
      (eq, ":start_random_quest", 1),
      (call_script, "script_start_quest", "$random_quest_no", "$g_talk_troop"),
    (try_end),
    (try_begin),
      (eq, ":start_random_quest", 1),
      (eq, "$random_quest_no", "qst_lend_surgeon"),
      (assign, "$g_leave_town_outside", 1),
      (assign, "$auto_enter_town", "$g_encountered_party"),
      (rest_for_hours, 4),
      (assign, "$lord_requested_to_talk_to", "$g_talk_troop"),
    (try_end),
    ]],
]
