DIALOGS = [
[anyone|plyr, "defeat_lord_answer", [
	(neg|troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_nihilistic),
	(try_begin),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_sane),
		(str_store_string, s68, "@Don't you worry now. I'll put you into a nice cell."),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_respectful),
		(str_store_string, s68, "@For the damage you caused to my people, I will take you into prison."),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_imperialist),
		(str_store_string, s68, "@Now it is your turn to bear the shame of defeat. I will take you to prison."),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_capitalist),
		(str_store_string, s68, "@A fitting end for a parasite like you. It's time to put you where you belong - a prison cell."),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_racist),
		(str_store_string, s68, "@I'll take you prisoner. Soldiers, chain him !"),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_crusader),
		(str_store_string, s68, "@I figure you can't do much harm imprisoned, so that's what I'm going to do to you."),
	(else_try),
		(troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_liberator),
		(str_store_string, s68, "@There are fates worse than death, Centurion. You'll learn that in my dungeon soon enough."),
	(else_try),
		is_legate,
		(str_store_string, s68, "@For your crimes committed against the {s31}, I place you under arrest."),
	(else_try),
		(str_store_string, s68, "@You are my prisoner now."),
	(try_end),
  ],
   "{s68}", "defeat_lord_answer_1",
   [
	(try_begin),
	 (neg|troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_capitalist),
     (call_script, "script_sod_player_capture_hero_to_reg", "$g_talk_troop"),
     (call_script, "script_sod_nemesis_note_lord_resolution", "$g_talk_troop", sod_nemesis_lord_resolution_capture),
	 (try_begin),
		(neg|troop_slot_eq, "$g_talk_troop", slot_troop_centurion_personality, slcp_sane),
		(neq, "$g_talk_troop", "trp_kingdom_6_lord"),
		(call_script, "script_change_player_relation_with_troop", "$g_talk_troop", -10),
     (try_end),
     (call_script, "script_change_player_relation_with_faction_ex", "$g_talk_troop_faction", -3),
     (call_script, "script_add_log_entry", logent_lord_captured_by_player, "trp_player",  -1, "$g_talk_troop", "$g_talk_troop_faction"),
    (try_end),
	 ]],
]
