DIALOGS = [
[anyone|plyr, "lord_talk", [
   (assign, "$g_cur_deliver_quest", -1),
	(try_begin),
		(check_quest_active, "qst_black_army_deliver_message"),
		(neg|check_quest_succeeded, "qst_black_army_deliver_message"),
		(quest_slot_eq, "qst_black_army_deliver_message", slot_quest_target_troop, "$g_talk_troop"),
		(assign, "$g_cur_deliver_quest", "qst_black_army_deliver_message"),
	(else_try),
		(check_quest_active, "qst_conquistadors_deliver_message"),
		(neg|check_quest_succeeded, "qst_conquistadors_deliver_message"),
		(quest_slot_eq, "qst_conquistadors_deliver_message", slot_quest_target_troop, "$g_talk_troop"),
		(assign, "$g_cur_deliver_quest", "qst_conquistadors_deliver_message"),
	(else_try),
		(check_quest_active, "qst_elephant_guard_deliver_message"),
		(neg|check_quest_succeeded, "qst_elephant_guard_deliver_message"),
		(quest_slot_eq, "qst_elephant_guard_deliver_message", slot_quest_target_troop, "$g_talk_troop"),
		(assign, "$g_cur_deliver_quest", "qst_elephant_guard_deliver_message"),
	(else_try),
		(check_quest_active, "qst_jotnar_clan_deliver_message"),
		(neg|check_quest_succeeded, "qst_jotnar_clan_deliver_message"),
		(quest_slot_eq, "qst_jotnar_clan_deliver_message", slot_quest_target_troop, "$g_talk_troop"),
		(assign, "$g_cur_deliver_quest", "qst_jotnar_clan_deliver_message"),
	(else_try),
		(check_quest_active, "qst_serpent_host_deliver_message"),
		(neg|check_quest_succeeded, "qst_serpent_host_deliver_message"),
		(quest_slot_eq, "qst_serpent_host_deliver_message", slot_quest_target_troop, "$g_talk_troop"),
		(assign, "$g_cur_deliver_quest", "qst_serpent_host_deliver_message"),
	(else_try),
		(check_quest_active, "qst_bc_deliver_message"),
		(neg|check_quest_succeeded, "qst_bc_deliver_message"),
		(quest_slot_eq, "qst_bc_deliver_message", slot_quest_target_troop, "$g_talk_troop"),
		(assign, "$g_cur_deliver_quest", "qst_bc_deliver_message"),
	(else_try),
		(check_quest_active, "qst_slavers_deliver_message"),
		(neg|check_quest_succeeded, "qst_slavers_deliver_message"),
		(quest_slot_eq, "qst_slavers_deliver_message", slot_quest_target_troop, "$g_talk_troop"),
		(assign, "$g_cur_deliver_quest", "qst_slavers_deliver_message"),
	(try_end),
	(ge, "$g_cur_deliver_quest", 0),],
   "I have a message for you.", "lord_gm_message_delivered1",
   []],
]
