DIALOGS = [
[anyone, "lord_talk_ask_about_war_details", [],
   "We have {reg5?{reg5}:no} {reg3?armies:army} and they have {reg6?{reg6}:none}. Overall, {s9}.",
   "lord_talk_ask_about_war_2", [(call_script, "script_faction_get_number_of_armies", "$g_encountered_party_faction"),
                                (assign, reg5, reg0),
                                (assign, reg3, 1),
                                (try_begin),
                                  (eq, reg5, 1),
                                  (assign, reg3, 0),
                                (try_end),
                                (call_script, "script_faction_get_number_of_armies", "$faction_requested_to_learn_more_details_about_the_war_against"),
                                (assign, reg6, reg0),
                                (assign, reg4, 1),
                                (try_begin),
                                  (eq, reg6, 1),
                                  (assign, reg4, 0),
                                (try_end),
                                (store_div, ":our_str", reg5, 2),
                                (store_div, ":enemy_str", reg6, 2),
                                (store_sub, ":advantage", ":our_str", ":enemy_str"),
                                (val_clamp, ":advantage", -4, 5),
                                (val_add, ":advantage", 4),
                                (store_add, ":adv_str", "str_war_report_minus_4", ":advantage"),
                                (str_store_string, s9, ":adv_str"),
                                ]],
]
